### ISSUE TITLE
Pixhack V3 ST LED and acceleometer calibration

### ISSUE THREAD

**Issue by xabierblanch** [ArduPilot/ardupilot#10001]
### Feature request

**Is your feature request related to a problem? Please describe.**
The pixhack V3 ST LED is fixed red after the boot and the accelerometer can not be calibrated. An error appears in MP. 

**Describe the solution you'd like**
Can it be a problem with new versions of Arducopter? With previous versions (I updated recently) it did not happen.

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by xabierblanch** [comment]
With px4 firmware works perfectly. But I'm interested in carry out ArduPilot. (for me is better)

**Comment by rmackay9** [comment]
Could you raise this in the Copter support forums first?  https://discuss.ardupilot.org/c/arducopter/copter-36.
