### ISSUE TITLE
QuadPlane SITL: Airspeed reported in VTOL modes is not accurate

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#10026]
### Bug report

**Issue details**

QuadPlanes will see the component of wind aligned with the pitot tube when in VTOL modes, SITL doesn't provide this, which makes testing anything that depends upon airspeed in a VTOL mode problematic.

**Version**
fc1e211039127

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
SIM_Quadplane

**Comment by tridge** [comment]
fixed in master, closing
