### ISSUE TITLE
Plane: climb first before RTH

### ISSUE THREAD

**Issue by Redshifft** [ArduPilot/ardupilot#10035]
Aeroplane option to climb first before RTH

An option to set climb to default altitude first on Failsafe or commanded RTH/RTL

Present action is to turn hard and start to climb, this is totally unsuitable if craft is low or behind an obstruction with a high probability of flying into it. I note also if very low there is more than a good chance the plane could stick a wing tip into the ground !! A wings level climb to safe altitude  before turning is what an Aeroplane needs as a first action before turning for home.

I am happy for this to be added as an option but see no reason for it to not be the default as it will only make a difference with events below target RTH height

**Comment by auturgy** [comment]
There are sound arguments for the proposed behaviour, and also for current behaviour.
I think RTL action is a good candidate for scripting, noting that the lua scripting engine is making good progress courtesy of @wickedshell

Regards,

James

**Comment by Naterater** [comment]
I believe this issue is a duplicate issue of https://github.com/ArduPilot/ardupilot/issues/8670. To keep the issue list a little cleaner, I'm going to close this issue so that the discussion can be moved over there. Your input on that discussion is very welcome!

**Comment by Naterater** [comment]
Yeah I've been advocating for a resolution for a while. You might also look at https://github.com/ArduPilot/ardupilot/issues/8064 - just like what you said! I'm trying to liven up that thread too.

**Comment by Redshifft** [comment]
Haha, see again while a perfectly presented request :)  it would not catch my eye as Failsafe/RTH issue

Dunno, maybe people just don't test their Autopilots, hoping only good things will happen if they ever need the Failsafe.

**Comment by Redshifft** [comment]
Just to tidy up, If we can implement the option to choose climb first..
Issue #8670  is fixed 

And issue #8064  could not occur

**Comment by magicrub** [comment]
Pull requests welcome!

**Comment by tridge** [comment]
I've finally implemented this in #14371 
my apologies it took so long to get to this

**Comment by Redshifft** [comment]
Thanks Tridge
Nice, Be good to finally be able to Fly low exploring or just testing Antennas etc with Arduplane :)
