### ISSUE TITLE
Copter: WPs are mixed or misinterpreted if new mission is new loaded over old one

### ISSUE THREAD

**Issue by msk7-ripe** [ArduPilot/ardupilot#1006]
If newer mission WPs are loaded into APM over older mission, copter shows strange  behavior: WPs are mixed somehow, and sometimes it goes to WP #1 instead of next WP.
This doesn't appear if I clear mission in MP, load empty mission and then load real new mission. I expect bug in mission load function not erasing previous WPs before loading new.

**Comment by peterbarker** [comment]
I think this has to be fixed by now.

Please reopen if that is not the case.
