### ISSUE TITLE
Plane: Full throttle when DISARMED after changing THR_MIN from - to 0.

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#10097]
### Bug report

Was working on my plane this afternoon and I needed to disable reverse thrust to get BLHeli passthrough to work (side issue https://github.com/ArduPilot/ardupilot/issues/9912). Immediately after I changed THR_MIN from -75 to 0, the plane launched itself across the room at full throttle.

Changing a parameter like this is dangerous and had nasty consequences. I'm lucky only foam was on the cutting block of the angry motors. The plane was not armed nor was the safety switch pressed.

**Version**
Plane 3.10 dev.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Twin engine electric

**Hardware type**
Lumineer 51A BLHeli_32 ESC's with telemetry on DShot. 6s battery. Cube black standard carrier board.

**Logs**
Will post later if requested - this should be easily duplicated using the parameters in #9912 above.

**Comment by magicrub** [comment]
this is expected behavior. What do you expect the autopilot to do?

**Comment by pompecukor** [comment]
Was this on PWM or on Dshot?

**Comment by Naterater** [comment]
@tridge, you asked me to bug you about this sometime.

**Comment by Naterater** [comment]
I'm going to chalk this up to a general issue of configuring on the bench. The rule is "DON'T HAVE PROPS ON."

**Comment by venom-code** [comment]
almost same experience. i changed the values in MP but reverted back, before that i went in parameters and changed the servo,1,2,3_function for elevon to 77, 78, 70, (but strangely it worked fine even with wrong values which had changed after update but i went it to put the recommended values, the moment my hand touched the plane without arming with the TX off it went 50% throttle, now when i move the plane the throttle starts and accelerates as much as the plane is moved by hand, thankfully i had props off, have the elevon settings changed in the arduplane, i did not read this anywhere, even the wiki is still showing above mentioned values for SERVOx_FUNCTION
