### ISSUE TITLE
Copter: transmitter initiated compass cal makes no sound

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#10093]
The issue appears to be that if the compass calibration is kicked off using the transmitter it makes no audible feedback sounds to the user.  I have not confirmed this personally but it has been [reported here as part of Copter-3.6.4 beta testing](https://discuss.ardupilot.org/t/copter-3-6-4-rc1-available-for-beta-testing/36504/4).

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/18338
