### ISSUE TITLE
Antenna Tracker chibios builds feature request

### ISSUE THREAD

**Issue by hdtechk** [ArduPilot/ardupilot#10096]
Issue details. No just features 
Since nuttx is being Removed. Is it possible to start a new beta version of Antenna Tracker. Based on chibios.   There has also been a few commits to tracker master since Aug 2016 latest stable of tracker 

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[ x ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Hardware type
Could add lots of new boards for tracker

#### Logs
Not relevant

**Comment by rmackay9** [comment]
I think we need to get @peterbarker an antenna tracker so he can take over as maintainer.. I'll raise a proposal for AP to buy him one.

**Comment by IamPete1** [comment]
We now build tracker for everything, https://firmware.ardupilot.org/AntennaTracker/latest/
