### ISSUE TITLE
error on the wizard part of the battery

### ISSUE THREAD

**Issue by manotroll** [ArduPilot/ardupilot#10104]
### Bug report

**Issue details**

_Please describe the problem_

**Version**
_What version was the issue encountered with_

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

https://i.imgur.com/aFWleIh.png
error in this part

**Comment by lvale** [comment]
This is a issue for Mission Planner.
Closing
