### ISSUE TITLE
SITL: Unable to arm throttle for Tailsitter.

### ISSUE THREAD

**Issue by thisisprateek** [ArduPilot/ardupilot#10106]
### Bug report

**Issue details**
Started simulation using the following command:

`sim_vehicle.py j4 -f plane-tailsitter --console --map -D`

On issuing this command, console and map pop up but the plane on the map makes rotating-drifting movements for some reason (Observe the orientations of the plane in the attached screenshots).

Then I issued commands to change the mode to auto and arm throttle as stated [here](http://ardupilot.org/dev/docs/plane-sitlmavproxy-tutorial.htmll). 
No take-off occurs. Rotating-drifting movements continue. The error on MAVProxy console says:

`APM: PreArm: Gyros inconsistent`

No changes have been made to the Ardupilot code or the scripts. Default plane-tailsitter.parm  from inside the autotest/default-params directory has been used.

**Version**
3.6

**Platform**
Plane

**Hardware type**
SITL on Linux(Ubuntu)

**Logs**

Init ArduPlane V3.10.0-dev (5e9a17d3)
Free RAM: 131072
load_all took 0us
0 0 0 validate_structures:348: Validating structures
DataFlash_File: buffer size=16384
online system 1
Mode MANUALAPM: GPS 1: detected as u-blox at 115200 baud
APM: Airspeed 1 calibrated
APM: EKF2 IMU1 initial yaw alignment complete
APM: EKF2 IMU0 initial yaw alignment complete
APM: EKF yaw reset -177.20
APM: EKF2 IMU0 tilt alignment complete
APM: EKF2 IMU1 tilt alignment complete
APM: ArduPlane V3.10.0-dev (5e9a17d3)
APM: f8b86c7150954249a58c455e2e5f43f9
Flight battery 100 percent
Got MAVLink msg: MISSION_ACK {target_system : 255, target_component : 0, type : 0}
Sent waypoint 0 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 0, frame : 0, command : 16, current : 0, autocontinue : 1, param1 : 0.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.362938, y : 149.165085, z : 650.0}
Sent waypoint 1 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 1, frame : 3, command : 22, current : 0, autocontinue : 1, param1 : 15.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.359833, y : 149.164703, z : 41.029999}
Sent waypoint 2 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 2, frame : 3, command : 16, current : 0, autocontinue : 1, param1 : 0.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.359585, y : 149.161392, z : 100.0}
Sent waypoint 3 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 3, frame : 3, command : 16, current : 1, autocontinue : 1, param1 : 0.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.366463, y : 149.162231, z : 100.0}
Sent waypoint 4 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 4, frame : 3, command : 16, current : 0, autocontinue : 1, param1 : 0.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.366131, y : 149.164581, z : 100.0}
Sent waypoint 5 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 5, frame : 3, command : 16, current : 0, autocontinue : 1, param1 : 0.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.359272, y : 149.163757, z : 100.0}
Sent waypoint 6 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 6, frame : 3, command : 177, current : 0, autocontinue : 1, param1 : 2.0, param2 : -1.0, param3 : 0.0, param4 : 0.0, x : 0.0, y : 0.0, z : 0.0}
Sent waypoint 7 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 7, frame : 3, command : 16, current : 0, autocontinue : 1, param1 : 0.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.359272, y : 149.163757, z : 100.0}
Sent all 8 waypoints
Got MAVLink msg: MISSION_ACK {target_system : 255, target_component : 0, type : 0}
APM: Flight plan received
APM: Executing nav command ID #22
Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}
APM: Reset alt target to 0.0
APM: Transition VTOL done
waypoint 1
Mode AUTO
APM: PreArm: Gyros inconsistent
Got MAVLink msg: COMMAND_ACK {command : 400, result : 4}

**Screenshots**
![screenshot from 2018-12-24 00-02-41](https://user-images.githubusercontent.com/24433560/50386590-f6ead600-070f-11e9-85f2-8ef33af1f0e0.png)
![screenshot from 2018-12-24 00-02-38](https://user-images.githubusercontent.com/24433560/50386592-f9e5c680-070f-11e9-8e80-8a33665d031d.png)

**Comment by IamPete1** [comment]
Seem to be able to arm now, although it dons't fly very well.....
