### ISSUE TITLE
Add support for RunCam camera control using UART

### ISSUE THREAD

**Issue by manotroll** [ArduPilot/ardupilot#10103]
is it possible to use the RunCam Split Mini?
How do I make her serial connection?
it can be shared with the miniosd since runcan would practically not receive external commands
How do other open-source controllers already support RunCam not add this support?

RunCam Support (Customer Services)

Dec 22, 10:08 CST
Sorry for that Split mini doesn’t support PWM control.

Regards,
Stella T.
RunCam Customer Service

as it does not support pwm control would not it be possible to add its support?
if it was compatible many would use it I already think that the controllers that supports px4 have more serial than others

https://discuss.ardupilot.org/t/runcam-split-mini-in-px4/36625

**Comment by auturgy** [comment]
https://support.runcam.com/hc/en-us/articles/115011786628-RunCam-Split-Communication-protocol?mobile_site=true

**Comment by rmackay9** [comment]
I think this request is to add support for controlling the RunCam using a UART.  I don't actually know what functions are supported using the UART but here is a link to the runcam website: https://www.runcam.com/

And here is a picture of the rear side of the camera showing the pins.

![runcam](https://user-images.githubusercontent.com/1498098/50388501-c16bda00-075b-11e9-9ccd-0e31a50c4d1b.png)

I've edited the subject line and description slightly to remove some misleading words.

**Comment by auturgy** [comment]
My link above has details of the protocol

**Comment by manotroll** [comment]
Thank you for reformulating
I already asked him and the mini does not support commands by pwm

**Comment by atshort** [comment]
In addition to the protocol there's the question of the user interface. Would be idea be to have ArduPilot use the same stick commands for menu navigation as [Betaflight](https://github.com/betaflight/betaflight/wiki/RunCam-Device-Protocol) uses for RunCam serial devices?

**Comment by manotroll** [comment]
I do not know how and the interface in Betaflight could gain a tab on the optional hardware

**Comment by gnumarco** [comment]
I have a RunCam Swift 3, seems it can be controlled using a UART and the controller's sticks, but it works only in betaflight. It would be great to have support for this !

**Comment by mikerob** [comment]
Here's the Betaflight pull request - their implementation in the FC and a link to the actual protocol definition.

https://github.com/betaflight/betaflight/pull/4251

The GCS interface is a problem, but given that there are existing camera control messages and functionality, it seems like it wouldn't be too hard to implement it as an option at least for the camera trigger / start and stop recording functions that already exist in MP / Ardupilot.

**Comment by gnumarco** [comment]
If I knew how to code for PixHawk, I'd do it, but I have no idea :(
But it would be a great feature to have, definitely!

**Comment by manotroll** [comment]
this is good that a developer has made available to put the feature
then I would have the smart audio plus this is something else
support could be for all RunCam

**Comment by gnumarco** [comment]
I have read the Betaflight pull request and the documentation, then I have gone a bit trough the ArduPilot dev doc, but I am afraid that, although I am a professional computer scientist, I am too used to Python and Java to efficiently implement this :(

**Comment by nwinova** [comment]
Does this mean there is no way to use the digital camera control of the swift 3 v2 with a kiss flight controller?

**Comment by Inv3nt0r1** [comment]
Is there any work going on to add this feature?

**Comment by rmackay9** [comment]
@Inv3nt0r1, I haven't seen any developer working on this but it's sometimes hard to know for sure.

**Comment by andyp1per** [comment]
I now have a runcam so plan to look at it in due course.

Andy

**Comment by manotroll** [comment]
I could not import the code in inav?
after you implement support could you try looking at smartaudio?

**Comment by andyp1per** [comment]
I have started on this. Still a work in progress.

https://github.com/ArduPilot/ardupilot/pull/12810

**Comment by andyp1per** [comment]
This has been fixed and is in master
