### ISSUE TITLE
LidarLite V1 PWM not working with AC3.6.3 ChibiOS

### ISSUE THREAD

**Issue by mtbsteve** [ArduPilot/ardupilot#10111]
### Bug report

**Issue details**
I am getting no reading on the Lidar altitude and voltage in the Rangefinder menu in MP. 
I am using a LidarLite V1 sensor connected via PWM. 
It was working well with AC3.5 and Nuttx versions. 
I could not find any description in the Chibios Missing Feature list, so I assume it’s a new problem. 

**Version**
_What version was the issue encountered with_
AC3.6.3 Chibios 

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Pixhawk 2.1 with Intel Edison and ApSync.

**Comment by KiwiDrones** [comment]
I'm also having the same problem on two cube drones.
I can't connect a new LW20 either on a serial or I2C port and get Bad Lidar Health message and sonarrange and sonarvoltage both = 0.
My LightWare SF11 on another drone which used to work and is connected on a serial port no longer works and gives the same results.
This seems to have occured when upgrading to AS 3.6.4 with Chibios on a cube

**Comment by peterbarker** [comment]
On Thu, 3 Jan 2019, KiwiDrones wrote:

> I'm also having the same problem on two cube drones.
> I can't connect a new LW20 either on a serial or I2C port and get Bad Lidar Health message and sonarrange and sonarvoltage both = 0.
> My LightWare SF11 on another drone which used to work and is connected on a serial port no longer works and gives the same results.
> This seems to have occured when upgrading to AS 3.6.4 with Chibios on a cube

Do you have power-saving enabled?  If so, please try disabling it 
temporarily and tell me the result?

**Comment by rmackay9** [comment]
@KiwiDrones, it would be better to report this in the [Copter-3.6 support area](https://discuss.ardupilot.org/c/arducopter/copter-36).  Sorry to be strict but if we're not then our to-do list turns into a support forum.

The original issue reported is because we don't support the LidarLite PWM value in Copter-3.6.

**Comment by KiwiDrones** [comment]
Thanks and I will look at the support area.

**Comment by rmackay9** [comment]
@mtbsteve, Yes, it's already fixed in master so it will certainly be included in Copter-3.7.

**Comment by maciek01** [comment]
When I upgraded from nuttx AC 3.6.7 to chibios 4.0.0-rc1 to test this fix. PWM Lidar Lite V3 stopped working right after the upgrade.

**Comment by rmackay9** [comment]
@maciek01, great, thanks.  I've added it to the list of things to check.  Can you double check that RNGFND1_TYPE = 5?

**Comment by maciek01** [comment]
Thanks @rmackay9 . That's correct: RNGFND1_TYPE,5

**Comment by rmackay9** [comment]
@maciek01, I successfully tested my LidarLite blue label using the PWM interface today.  Do you have a log file or parameter file that I could look at?

I think [our docs need some updating](http://ardupilot.org/copter/docs/common-rangefinder-lidarlite.html#connecting-to-pixhawk-via-pwm) but some of the key points I found when setting it up:

- RNGFND1_TYPE = 5.  we are not automatically copying params for lidar from 3.6.x to 4.0 it seems.  I will investigate if we can do this.
- A 1K resistor (or even as low as 300ohm resistor) must be connected between ground and the signal pin coming out of the lidar.
- RNGFND1_PIN = 54 (if the lidar's signal pin is being connected to a Pixhawk/Cube AUX5 out)
- it may be necessary to set RELAY_PIN = -1, RELAY_PIN2 = -1  to avoid a conflict with the relays.. although I didn't personally find an issue during testing it seems like it should conflict.
- BRD_PWM_COUNT = 4
- During testing I sometimes used a servo tester (which can output a pwm signal) to ensure that the ArduPilot side was working.

**Comment by maciek01** [comment]
thanks @rmackay9 

exact model is garmin Lidar lite v3

settings are a bit different - mine are based on earlier instructions (18 months back) on ardupilot website.
And it all worked fine until upgrade from 3.6.7 to 400. settings are consistent between pre and post upgrade so all copying over worked as expected:


RNGFND1_PIN,-1
RNGFND1_STOP_PIN,55
RNGFND1_TYPE,5

RELAY_PIN,54
RELAY_PIN2,55

BRD_PWM_COUNT,4

lidar is plugged into aux 5 and 6 with the resistor precisely as per website instructions

i will capture logs on weekend

[p46-400.txt](https://github.com/ArduPilot/ardupilot/files/3786037/p46-400.txt)
[p46-400.txt](https://github.com/ArduPilot/ardupilot/files/3786038/p46-400.txt)

**Comment by rmackay9** [comment]
@maciek01,

I've revamped our [LidarLite wiki page](http://ardupilot.org/copter/docs/common-rangefinder-lidarlite.html) so could you change the setup to match what's on the wiki?  I think it would be best if we stick to a single method.  In particular I think RNGFND1_PIN should be set to 54.

**Comment by maciek01** [comment]
this did not work. btw i have my wiring setup as per the video on the bottom of the page (which was consistent with the previous versions of the schematics 18 months ago). AUX 6 in the current schematic is not consistent with the video.

**Comment by rmackay9** [comment]
@maciek01,

So I guess you just tried setting it up as shown on the wiki?  This worked for me and I spent quite a bit of time on updating the page and bringing it in line with instructions from the manufacturer.

Sorry to be persistent but I think we need to stick to one consistent setup method, prove it works and make sure it's well documented.

**Comment by maciek01** [comment]
no problem, rewired and retested - no luck. log attached
[log_11_2019-10-29-22-01-30.bin.txt](https://github.com/ArduPilot/ardupilot/files/3786610/log_11_2019-10-29-22-01-30.bin.txt)

**Comment by rmackay9** [comment]
@maciek01, ok, sorry, I made a critical typo in the instructions.  The RNGFND1_PIN should be "54" ("AuxOut5") not "55".  Sorry about that.

I've fixed the wiki and it should update in 15min or so.

**Comment by maciek01** [comment]
this worked - thanks so much for your help. it works with the old wiring (did not check the new) including the stop pin (55)

**Comment by maciek01** [comment]
i would suggest to remove the last video or to mention that 400 setup is different (mission planner section)

**Comment by rmackay9** [comment]
@maciek01, great!  I've added a note above the video, "The video guide below shows the setup using PWM but is based on out-of-date instructions and skips the setting of the RNGFND1_PIN parameter".  Thanks for your patience and persistence!
