### ISSUE TITLE
Bugs on Pixhawk4 Mini

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#10127]
### Bug report

**Issue details**
1. PH4Mini on-board LED (ACT B/E PWR) is off after bootup.
2. Safety Switch LED is off, button is not work either.
3. Bootup always fail while use 3.6.4-Stable-PH4Mini, PWR keep blink.

**Version**
3.6.3-stable
3.6.4-stable

**Hardware type**
Pixhawk 4 Mini

**Comment by tridge** [comment]
thanks for reporting this, I've fixed it in a PR

**Comment by kmeagle1515** [comment]
Hello! Can anyone tell me how to can i understand the codebase sequentially so that i can contribute to any of the good first issues. I have been following the devs guide given in the website and have installed necessary packages.
