### ISSUE TITLE
Copter: Autop twitch during direction change to next WP

### ISSUE THREAD

**Issue by Pomaroli** [ArduPilot/ardupilot#1012]
hello i'm using mission planner V1.3.0,so far all seems ok. I like the new Compass calibration process which seems more accurate then the old.
Today i was testing the Autopilot doing a small circle to find out the best WPNAV values for a smooth flight. i have to say that i'm flying without Gimbal.
The flight himself is working fine and smooth but every time a waypoint is arrived and the direction change to the next waypoint is done there is always a hard twitch. A part of that it is working fine.
How can i do things better, anybody can give some advice i can test ?
Im flying an 3Dr iris, which is calibrated and setup properly.

consideration
as far as I understood the direction changes in autopilot are made by switching in short terms to loiter and then back to auto mode. Since the loiter mode fixes a gps point it is understandable that direction changes in auto mode are very difficult to make because the loiter modus will always try to stay at the fixed point and the Auto "Mission PLan" will have other directives like NAV Speed, NAVAccel, WPRadius.
Didn't they compromise each other ?

You can test this by programming a circle and setting a poi in the middle of the circle, the Drone will fly absolutly clean between the WP's but will twitch everytime a WP is passing, that's weird ;)

I was analysing this case and basically i'm interested to contribute as far i have time a apart of my day job. but It will take time until i understand all the code. As wrote above i think i found already the lib for this "thing" i am right by looking into the ap_navigation ? 
there are a lot of calculations which i'm not fully understand for now but basically i'll try to keep things simple KISS -> keep it smooth and simple ;)

im not sure about the solution but i think instead of loiter it should be a kind of curve which will guide the UAV around the WP.

here is the support case 
http://ardupilot.com/forum/viewtopic.php?f=25&t=7405

**Comment by OXINARF** [comment]
@rmackay9 Do you think this is also fixed in the latest 3.5 beta?

**Comment by Pomaroli** [comment]
Hi Randy, sorry for the big delay, i had so much things going on and could not follow this project as it would diserve. il give feedback asap. 👍

**Comment by lthall** [comment]
This is old now.
