### ISSUE TITLE
chibios system halt 

### ISSUE THREAD

**Issue by askariz** [ArduPilot/ardupilot#10136]
chibios system halt a few time and led stop flashing ,no pwm output and no seril device appear

**Version**
Copter 3.6.3 with chibios , uavcan and novatel gps .

**Platform**
[  ] All
[  ] AntennaTracker
[✔  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quadcopter 
**Hardware type**
 Cube

**Logs**
https://drive.google.com/open?id=19x_dzVB7RMEtDCUinTB8amkEu-Tw-4E2

**Comment by IamPete1** [comment]
@askariz sorry we never got to this, can you reproduce on 4.0/4.1?
