### ISSUE TITLE
Parameters: Add metadata - Tags

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#10165]
### Feature request

**Is your feature request related to a problem? Please describe.**
https://discuss.ardupilot.org/t/parameter-sorting-for-gcs-user-or-new-field-for-tags/36911

Parameter filtering is probably a nightmare for GCS makers. There are so many parameters, and not all of the critical ones are in GUI tuning windows. In addition, they often change names.

**Describe the solution you'd like**
Tags in the code that can be extracted and assist with sorting parameters based on your stage of building/tuning/using the vehicle. Parameters may have multiple tags. GCS's and maybe the website can search for or hide parameters based on their tags. 

Relevant Tag List: // @Tags:

Accessory
Altitude
Attitude
Battery
Camera
CAN
Compass
EKF2
EKF3
ESC
Failsafe
Fence
Frame
GPS
Gyro
IMU
Input
Instance
Land
Land_DeepStall
Mission
Mode
Navigation
OSD
Output
QuadPlane
Radio
Rangefinder
RC
RTH
Safety
Serial
Servo
Setup
Speed
Steering
Tune
Takeoff
Throttle
Yaw/Turn

**Describe alternatives you've considered**
Manually categorize parameters in each GCS and try to stay up-to-date with them as much as possible (when parameters change names, etc.)

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

If people are generally OK with this, I am willing to put a lot of the effort in for plane parameters and eventually other vehicles. I'll wait for some discussion here before I do PR's though.

**Comment by peterbarker** [comment]
@Naterater what advantages do you see in having tags rather than full-text-searching of the Description field?
