### ISSUE TITLE
Copter: add support for Bi-Copters

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1018]
Shinji Uemura-san has provided the bi-copter motors library so we should incorporate into master as a new frame type.

Demo video:  https://www.youtube.com/watch?v=RE6_QRYbBcg

**Comment by ypsonar** [comment]
Good . . .  How we can download that library for bicopter . . . Plz guide

**Comment by ncx94** [comment]
Did this frame type eventually end up in master?

**Comment by rmackay9** [comment]
@ncx94, no i'm afraid it's never made it into copter.  Somewhat strangely it is possible to fly these vehicles using Plane because it was added as part of the Plane VTOL code.

**Comment by ncx94** [comment]
that's a shame :(
How hard is it to port it to copter if plane supports it?

**Comment by rmackay9** [comment]
@ncx94, I don't think it's a very hard frame to support but I think we would want to make a new AP_BiCopter class in the AP_Motors directory perhaps taking some of the logic out of the [AP_MotorsTailsitter.cpp](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Motors/AP_MotorsTailsitter.cpp) class.

As always, it's about finding a developer who wants to take it on.

I guess you have one of these frames?

**Comment by ncx94** [comment]
i don't have one yet but i must admit that i've always loved the way they looked and as i ended on a youtube video of a bicopter i started looking around for the ardupilot support of that kind of frames haha

**Comment by IamPete1** [comment]
https://github.com/ArduPilot/ardupilot/pull/9596

**Comment by IamPete1** [comment]
Bicopter is now in master, I will try and add some documentation in the new year
