### ISSUE TITLE
Plane: Loiter Minimum Altitude Request

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#10196]
### Feature request

**Is your feature request related to a problem? Please describe.**
I had a user accidentally switch to loiter in the middle of an auto-takeoff. This caused a sweeping circle very low to the ground.

**Describe the solution you'd like**
New parameter WP_LOITER_ALTMIN
Display Name: Minimum Loiter Altitude
Description: Minimum altitude that the aircraft will loiter relative to home. Prevents low-altitude loiter events.

**Describe alternatives you've considered**
Remove the loiter option for my users.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Additional context**
![image](https://user-images.githubusercontent.com/35429159/50800822-8f07c400-12a7-11e9-9496-31bb53e5afb8.png)

**Comment by magicrub** [comment]
What do you think the default value should be? Maybe 0? What do negative numbers mean?

**Comment by Naterater** [comment]
Probably 0 (disable). Range 0-32,600 (or whatever that magic number is).

**Comment by peterbarker** [comment]
On Mon, 7 Jan 2019, Nathan E wrote:

> Is your feature request related to a problem? Please describe.
> I had a user accidentally switch to loiter in the middle of an auto-takeoff. This caused a sweeping circle very low to the ground.

Seriously, your user could have selected a half-a-dozen other ways to kill 
their vehicle.  Why pick on Loiter?

Perhaps another option you might consider here is that if you are doing an 
automated takeoff that the Loiter will occur at your takeoff altitude.... 
fewer parameters....  not sure I really like the idea of Loiter doing 
anything other than making a circle - even if it means writing the 
incident off as "Crashing as Intended"....

**Comment by ChrisBird** [comment]
@auturgy dont you normally have the geofence off for takeoff and landing?

**Comment by auturgy** [comment]
It’s a good test case for fence_autoenable. If it was set to 1 it should activate when the launch completes, so the switch to loiter should enable the geofence, and if a min alt was set, should then climb.
I would hope that switching to loiter doesn’t disable the fence.

**Comment by ChrisBird** [comment]
@auturgy  Thats what i like about this is that I'm always learning.  Will have to give that a go.

**Comment by Naterater** [comment]
I'll chalk this up to possibly available as a feature using geofence.
