### ISSUE TITLE
AP_Mount - odd stabilization w/o RC

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#1024]
I know the title is unclear - so here's how to reproduce:
1.- Set up pitch stabilization.
2.- assign channel for manual pitch angle control
(at this point everything works as expected)
3.- shutdown tx and autopilot.
4.- Start Autopilot only /(do not switch on RC)
Observe that pitch stabilization is very extreme, not working - until RC TX is turned on.
-now stabilization works as expected, even if radio goes off.

**Comment by Naterater** [comment]
Is this still a bug?

**Comment by rmackay9** [comment]
This was recently fixed in Copter-3.6.5.

Txs for reviewing these issues
