### ISSUE TITLE
No sanity checks on mavlink_to_mission_cmd

### ISSUE THREAD

**Issue by ptsneves** [ArduPilot/ardupilot#1026]
Hello,
While I was writing my command component I had to send mission items and while testing was careless with the validity of the waypoints.

As such whenever I sent a malformed waypoint of latitude 40000 for instance, the ardupilot always crashed. Luckily I was running in SIL mode. The error was an Arithmetic exception in AP_Mission.cpp:568, but from the looks of the code it could occur in many more parts of the code. 

Is there any reason to not bound check the received data?

Thank you
Paulo Neves

**Comment by WickedShell** [comment]
Lat/lng/alt are sanity these days.
