### ISSUE TITLE
MP rssi display issue

### ISSUE THREAD

**Issue by sheltercv** [ArduPilot/ardupilot#10294]
### Bug report
**Issue details**

I get the receiver rssi value from pwm channal , i connect receiver to controler and open radio,MP display rssi is 100, then when i move the receiver ,the MP display rssi value is also 100.
why isn't 0?

**Version**
Copter  3.6.4  Chibios firmware
MP Version: 1.3.62

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quad

**Hardware type**
matek f405

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by Naterater** [comment]
For the moment, this issue should be moved to discuss.ardupilot.org until it is diagnosed as a reproducible problem with the firmware and not just a parameter or hardware fault. Once that is complete, we should re-open this issue.

In addition, this wiki article is a little old but may help you find the parameters to set correctly http://ardupilot.org/copter/docs/common-rssi-received-signal-strength-indication.html
