### ISSUE TITLE
EKF3: store wheel encoder offsets as local copy

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#10318]
As discovered in [this PR](https://github.com/ArduPilot/ardupilot/pull/10220) the EKF3 seems to be keeping a pointer to the sensor offsets for both wheel encoders and visual odometry values passed instead of maintaining a local copy.  We should change the EKF3 so that it stores the offsets locally which would be much safer.

**Comment by peterbarker** [comment]
This was done on master as part of the DAL changes.

I doubt this will be backported at this stage when we're looking at a 4.1

**Comment by IamPete1** [comment]
> This was done on master as part of the DAL changes.

I guess we can close then.
