### ISSUE TITLE
ArduPlane: differential spoiler with ELEVON_OUTPUT

### ISSUE THREAD

**Issue by nhadrian** [ArduPilot/ardupilot#1032]
Hi,

I wanted to activate the differential spoiler feature in ArduPlane, following this: http://plane.ardupilot.com/wiki/differential-spoilers/

The servos on differential spoiler  don't move at all, they are staying on the minimum value (900 us) in every flight mode. 

I tried to thange the corresponding RC_FUNCTION to other type (eg. Aileron) and the servos are moving, so there are not any electrical issue around I think.

Controller: APM2.6
Firmware: ArduPlane 3.0.1 (and tried 2.76 too)
Plane: foam flying wing
Elevon mixing: FBW

Best regards 
Adrian

**Comment by ethomas997** [comment]
I've implemented (and flown) a fix for differential spoilers, submitted as Pull Request #1736.  Source and hex files are also posted here:  http://www.etheli.com/APM/ArduPlane_v3.2.0_etMod

--ET

**Comment by Jman841** [comment]
Was this ever resolved? I am currently trying to use differential spoilers with elevon output and can't seem to get it to work with Arduplane 3.3.0beta1 (Navio+ board)

**Comment by magicrub** [comment]
not resolved as far as I know

**Comment by gmorph** [comment]
I'm going to work on this and get it merged in.
Thanks, Grant.

**Comment by magicrub** [comment]
I don't use these, but I may want to at some point. @gmorph please keep us posted!

**Comment by ethomas997** [comment]
@gmorph Sounds good; let me know if I can do anything to help it along.

--ET

**Comment by gmorph** [comment]
This is now complete so closing out.
Thanks, Grant.
