### ISSUE TITLE
lower attitude speed/accel correction for larger drone

### ISSUE THREAD

**Issue by GlidLov** [ArduPilot/ardupilot#10340]
**Is your feature request related to a problem? Please describe.**

Attitude corrections (all Stabilized modes) are too fast making larger drones stabilization too abrupt 

**Describe the solution you'd like**

a way to smooth / lower angle speed/accel to make attitude corrections more gentle and lesser stressing for the frame

**Describe alternatives you've considered**

Lowering ANGLE_MAX may help but don't fix issue.

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Turn down your ATC_RATE_R_MAX and ATC_RATE_P_MAX to reduce your maximum accelerations. Can you ask on the forums if there is anything else as this is a user issue rather than a problem with the code. Thanks
