### ISSUE TITLE
Rover: "Airspeed 1 init failed" on startup

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#10371]
Rover displays an error message, "Airspeed 1 init failed" on startup.  Not a huge problem but it's best we don't display erroneous messages that could worry a user.

**Comment by magicrub** [comment]
I've seen this on Plane too

**Comment by WickedShell** [comment]
#10442 fixed the problem for most rover users, and moves it back to being the case that we tried (and failed) to find an airspeed sensor. Do we still want this open?

**Comment by WickedShell** [comment]
Closing due to lack of response, and I believe we've fixed the general problem. Feel free to reopen if this is incorrect.
