### ISSUE TITLE
Fail to build AP_Motors_test example with CubeBlack

### ISSUE THREAD

**Issue by thethaibinh** [ArduPilot/ardupilot#10376]
### Bug report

**Issue details**
When I tried to buil AP_Motors_test example from AP_Motors library with configure board=CubeBlack, I got the error: 
"No param area found 
Error: Param defaults support not found in firmware"

**Version**
AP Motors Library

**Platform**
[  ] All

**Hardware type**
CubeBlack

**Comment by BrightSoulXYHY** [comment]
I have the same problem when build AP_Notify_test with configure board=Pixhawk1&fmuv2 and so on. How about build other Library?

**Comment by IamPete1** [comment]
Sorry we went able to help, Both `./waf --target examples/AP_Motors_test` and `./waf --target examples/AP_Notify_test` are working for me on CubeBlack now so I'm going to close this.
