### ISSUE TITLE
Airspeed pressure log has no negative value

### ISSUE THREAD

**Issue by aero4** [ArduPilot/ardupilot#10390]
### Bug report

When Airspeed (1 and 2) is logged (on SD), the raw pressure (column _DiffPress_) does not have a sign.
I used a SDP31 as airspeed sensor and this I2C sensor delivers a sign (two's complement).
The sign is relevant for AoA/SSA-sensor tests.

Is there also a temporary fix for that?

Thank you in advance!

**Version**
ArduPlane 3.9

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Fixed wing

**Hardware type**
Pixhawk 2 Cube

**Comment by WickedShell** [comment]
If you set the `ARSP_TUBE_ORDER` parameter to something other then auto (the default) we won't make it always be a positive number. In practice though this is expected to be the pressure differential between ram air and static, if it goes negative that would indicate a higher static pressure/moving backwards. I don't see how that provides a AoA/SSA unless you aren't using it as an airspeed sensor, and just as a differential indicator?
