### ISSUE TITLE
QuadPlane QAUTOTUNE saves gains when it shouldn't

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#10411]
### Bug report

When landing in LAND gains should not be saved.  They are.

**Version**

master

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
SITL quadplane

**Hardware type**
SITL

**Logs**

autotest coming.

**Comment by peterbarker** [comment]
Autotest is now merged.

It can be run with
```
./Tools/autotest/autotest.py build.ArduPlane fly.QuadPlane.QAutoTune
```

It currently passes - it should not - so it needs fixing along with the code :-)

**Comment by peterbarker** [comment]
This was fixed.

**Comment by IamPete1** [comment]
I think this is now fixed.

**Comment by peterbarker** [comment]
.... test is still disabled in autotest.  Whoops!
