### ISSUE TITLE
Add user text field to F7 OSD for aircraft name or ham callsign.

### ISSUE THREAD

**Issue by atshort** [ArduPilot/ardupilot#10436]
Could we have a short text field on the F7 OSD for the user to specify a vehicle name or callsign?

This would be useful for identifying FPV video recorded from multiple vehicles.

Also possibly needed for a ham callsign in some locations.

**Describe the solution you'd like**
How about an 8 character text field added to the OSD parameters.

**Describe alternatives you've considered**
None.

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[x] Plane
[x] Rover
[  ] Submarine

Thank you.

**Comment by Rusty105** [comment]
I will second this. The stand alone OSDs have this, and as stated above, is needed for compliance with amateur radio regulations in some areas.

**Comment by Rusty105** [comment]
I have given this a shot at implementing, I'll post updates when I get something.

**Comment by squilter** [comment]
Callsign support was added a few months ago with #15789. I think that this issue can be closed.

**Comment by atshort** [comment]
Thank you.

**Comment by atshort** [comment]
Done. Thank you.
