### ISSUE TITLE
Division-by-zero error for two filter parameters

### ISSUE THREAD

**Issue by ktskt** [ArduPilot/ardupilot#10435]
### Bug report

**Issue details**
If I put some value larger than or equal to 0 and lower than 1 on INS_GYRO_FILTER or INS_ACCEL_FILTER, ArduPilot will crash due to division by zero.
I got the following message with GDB.

Program received signal SIGFPE, Arithmetic exception.
in LowPassFilter2p<Vector3<float> >::set_cutoff_frequency(float, float) ()

**Version**
3.5.7

**Platform**
[  ] All
[  ] AntennaTracker
[O] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
But, other platforms must share the same problems

**Airframe type**
Quadcopter but applicable to other frames

**Hardware type**
I checked this bug only on SITL

**Comment by peterbarker** [comment]
I'm thinking we should have some boot-time checks for out-of-bounds parameters like this and enter `sensor_config_error` loop (perhaps with a better name).

**Comment by peterbarker** [comment]
... in the meantime, "well don't do that then!" :-)

**Comment by ktskt** [comment]
@peterbarker Thank you for your comment.
Of course, I won't do that. It is a just bug report that I found :).
In the meantime, I think it would be better to change related document ranges since both parameters can be 0 according to the document. 

http://ardupilot.org/copter/docs/parameters.html#ins-gyro-filter-gyro-filter-cutoff-frequency
http://ardupilot.org/copter/docs/parameters.html#ins-accel-filter-accel-filter-cutoff-frequency

**Comment by peterbarker** [comment]
On Thu, 7 Feb 2019, ktskt wrote:

> In the meantime, I think it would be better to change related document
> ranges since both parameters can be 0 according to the document.

Ah.  Right.  Documented behaviour.  I guess we need to fix the behaviour 
rather than paper over people's parameter settings...

Similar code sets alpha to 1.0 - but compute_params is a little 
more complicated than that....

Reproduction is simple; start SITL and  param set INS_GYRO_FILTER 0

@tridge
