### ISSUE TITLE
Fatal error during SITL installation, Linux

### ISSUE THREAD

**Issue by giogamba** [ArduPilot/ardupilot#10446]
#### Issue details
Dear all, i'm trying to install the SITL according to http://ardupilot.org/dev/docs/setting-up-sitl-on-linux.html
I tried with a VM with Ubuntu 18.04, but i had a problem with submodules.
I retried with a VM with Ubuntu 16.04 LTS and the error is the same, as attached below.
Maybe this is the wrong place, but i found nothing pertinent on existing threads.
Many Thanks
Regards
Giovanni

#### Version
Last
#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
N/A

#### Hardware type
N/A

#### Logs
developer@developer-VirtualBox:~/ardupilot$ git submodule update --init --recursive
Submodule 'modules/ChibiOS' (git://github.com/ArduPilot/ChibiOS.git) registered for path 'modules/ChibiOS'
Submodule 'modules/gbenchmark' (git://github.com/google/benchmark.git) registered for path 'modules/gbenchmark'
Submodule 'gtest' (git://github.com/ArduPilot/googletest) registered for path 'modules/gtest'
Submodule 'modules/mavlink' (git://github.com/ArduPilot/mavlink) registered for path 'modules/mavlink'
Submodule 'modules/uavcan' (git://github.com/ArduPilot/uavcan.git) registered for path 'modules/uavcan'
Submodule 'modules/waf' (git://github.com/ArduPilot/waf.git) registered for path 'modules/waf'
Cloning into 'modules/ChibiOS'...
fatal: unable to connect to github.com:
github.com[0: 140.82.118.4]: errno=Connection timed out
github.com[1: 140.82.118.3]: errno=Connection timed out

fatal: clone of 'git://github.com/ArduPilot/ChibiOS.git' into submodule path 'modules/ChibiOS' failed

**Comment by khancyr** [comment]
hello, 
that comes from your configuration, try to check that you get internet access from the VM. Another solution could be to change the submodule to update from http 
We don't do user support on the issue list, as it is for issue in codebase. Please open a subject on https://discuss.ardupilot.org/ for further assistance.
