### ISSUE TITLE
Copter: speed up EKF failsafe by checking if velocity innovations > 2x FS_EKF_THRESH

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#10466]
Copter's EKF failsafe checks if 2 out of 3 innovations (compass, velocity, position) are greater than the FS_EKF_THRESH parameter value.  If they are (for more than a second or two) the failsafe triggers.

In cases where the GPS position/velocity has gone bad, we can likely speed up triggering of the EKF failsafe if we also trigger in cases where the velocity innovations are greater than twice the FS_EKF_THRESH.

Here is a graph from one log in which the compass was fine, but the GPS was providing terrible positions and velocities.  In this case the GPS itself also reported that it had very little idea of where it was.  Despite this it took 13seconds for the EKF failsafe to trigger.

![corrado-innovations](https://user-images.githubusercontent.com/1498098/52515206-07bdbf80-2c5c-11e9-9b58-3e706e7e61a1.png)

**Comment by chobitsfan** [comment]
I may have a similar situation. Our copter was jammed in a power tether test and it went crazy. After inspecting log, I found SV quickly go above 2 but SP and SM did not go above 0.6 Therefore it did not trigger EKF failsafe.
![jammed](https://user-images.githubusercontent.com/19793511/54184361-70a98900-44e1-11e9-9f4f-20c92d534789.jpg)

**Comment by rmackay9** [comment]
@chobitsfan, thanks for the report.  It's not a super hard fix so hopefully one of us can find the time to work on it.. certainly we should get this included in Copter-3.7

**Comment by chobitsfan** [comment]
hi @rmackay9 maybe I could create a PR for this issue? Currently, ekf_check_state.fail_count increased when  2 out of SV, SP and SM. Maybe ekf_check_state.fail_count also increased when either SV, SP or SM is greater  then 2x FS_EKF_THRESH ?

**Comment by rmackay9** [comment]
@chobitsfan, I was hoping you'd offer, yes please!
