### ISSUE TITLE
Copter: save trim with sticks in unarm position for 15Secs

### ISSUE THREAD

**Issue by svefro** [ArduPilot/ardupilot#1047]
Suggestion:
To save trim Hold Sticks in unarm position for 15 Seconds when disarming after 
trimming copter in stabilize mode with radio

**Comment by Naterater** [comment]
I think that the auto-trim features are well implemented now, so this may be closed.

**Comment by rmackay9** [comment]
I haven't seen many complaints from users about their stick trims being incorrect.  I think Plane may automatically trim the RC sticks but I must say that I'm not a big fan of doing this in copter or rover.  I'd rather just leave it to the GCS to capture the trims as part of the RC calibration.
