### ISSUE TITLE
Sub: SERVOn_MAX and MOT_PWM_MAX have no apparent effect.

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#10488]
There is no way to constrain the maximum pwm signal, these parameters are not functioning as they should.

Tested on Sub 3.5.3.

Perhaps related to https://github.com/ArduPilot/ardupilot/issues/9830, but this was tested with servo channels configured as motor output.

**Comment by Williangalvani** [comment]
The only way to adjust that seems to be changing RC3_MIN and RC3_MAX

see here:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Motors/AP_Motors6DOF.cpp#L235

**Comment by jaxxzer** [comment]
mucho relevant: https://github.com/ArduPilot/ardupilot/pull/7133
