### ISSUE TITLE
Plane: RC last valid input time set even when throttle is below failsafe

### ISSUE THREAD

**Issue by OXINARF** [ArduPilot/ardupilot#10514]
## BUG

On #9062, @peterbarker and I found out that Plane is setting the variable holding the time that RC input was last valid to `now` even when the throttle is below failsafe level.

This
Apparently you didn't do the exact same test because Travis failed 🙂 This is why: Plane is setting the time for valid RC input even when throttle is below failsafe:
https://github.com/ArduPilot/ardupilot/blob/5a19f447a707e15545127769f6b8e5c2fccccb7c/ArduPlane/radio.cpp#L190

This has the consequence that even after being in RC failsafe, Plane continues to send the RC MAVLink sensor health bit as valid - which isn't obviously the case if we are in RC failsafe.

@peterbarker added a test for RC failsafes but one of the checks is now disabled until this is fixed.

_Originally posted by @OXINARF in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTI5MjYxMjMyOnYy/pull_request_review_threads/discussion_

**Comment by IamPete1** [comment]
Sounds like this was fixed, https://github.com/ArduPilot/ardupilot/pull/10515#issuecomment-568618523 looks like this was the PR https://github.com/ArduPilot/ardupilot/pull/12137
