### ISSUE TITLE
OpticalFlow CXOF driver bodyRate rotation bug

### ISSUE THREAD

**Issue by dollop80** [ArduPilot/ardupilot#10535]
### Bug report

**Issue details**
A quad uses  CXOF (Cheerson CX-OF) as optical flow sensor.
When I apply parameter FLOW_ORIENT_YAWthat is different from 0 the values XY Body Rate estimated from OF sensor driver are erroneous

**Version**
3.7.0 dev

**Platform**
[ *] Copter

**Airframe type**
quadX

**Hardware type**
omnibusf4pro

**Solution**
Need to delete line #191 in the file AP_OpticalFlow_CXOF.cpp:

`_applyYaw(state.bodyRate);`

As there is no need to apply yaw to body rate, because it comes from AHRS

**Comment by rmackay9** [comment]
This has been fixed in "latest" with PR https://github.com/ArduPilot/ardupilot/pull/16256.  This will go out with Copter-4.1.  Thanks for the report!
