### ISSUE TITLE
Plane :full parameter list: MOT_PWM_TYPE

### ISSUE THREAD

**Issue by hdtechk** [ArduPilot/ardupilot#10548]
Can't find 
MOT_PWM_TYPE 
On full parameter list on wiki

#### Version
Wiki

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment]
This is a support issue, please use gitter, or the forums. That being said: [Q_M_PWM_TYPE](http://ardupilot.org/plane/docs/parameters.html#q-m-pwm-type-output-pwm-type)

**Comment by hdtechk** [comment]
Kool then this part of wiki needs editing.
http://ardupilot.org/plane/docs/common-dshot.html#dshot-protocol

**Comment by magicrub** [comment]
Uhm... Nope. Check it again

**Comment by hdtechk** [comment]
The SERVO_BLH_OTYPE needs to be added
