### ISSUE TITLE
Do not allow vehicle to fly near airports

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1056]
To keep copter and planes from accidentally interfering with manned aircraft we should add features that keep the vehicles away from airports.

Some ideas include downloading a list of airports from http://openflights.org/data.html and landing the vehicle if it gets within a certain distance (10km? 1km?) of an airport.

Another idea is to automatically configure the fence (aka geofence) to keep vehicles out of the way of the airports.

As with nearly all features, we would allow the user to disable the safety check.  This is necessary because all safety checks have occasional false positives or there may be a very good reason why the vehicle should be flying near the airport.

There is a related issue here for the mission planner to display nearby airport information to the user: https://github.com/diydrones/MissionPlanner/issues/455

**Comment by dscassid** [comment]
Does anyone know if airport warning messages or exclusion zones were implimented??

**Comment by kd5ftn** [comment]
How about also allowing user-defined "keep out zones". This may fall under an additional issue. I have an application where I would like autonomous flight over an area but would like to avoid pre-defined tall objects such as towers or particular trees. A "keep out" or exclusion zone would be sort of an inverse geofence, so if the Path between waypoint 1 and 2 were to intersect this zone, the autopilot would maintain distance and follow the perimeter of the zone, or compute a more efficient route that avoids it.

**Comment by rmackay9** [comment]
@kd5ftn,
the "keep out" zone is captured in issue #391.  There's some on and off progress on object avoidance going on but it's not there yet.

**Comment by kd5ftn** [comment]
Thanks for identifying that for me Randy. I'll bring my communication over there!

**Comment by squilter** [comment]
Has anybody put any more thought into this?  I might try taking this on.

**Comment by magicrub** [comment]
The implementation is not hard, the real issue is having an up-to-date list
that makes everyone happy and where to store it.

**Comment by WickedShell** [comment]
The implementation that satisfies the most people is probably the most difficult part. Within the US I'd almost argue that you would want to know the class of the airport and the controlled space associated with it. Unfortunately this locks out cities and takes up a large amount of space. And as was pointed out you would ideally want to know the local NOTAMs (the president is here, this airspace is closed etc).

I don't know, I haven't given to much thought to it, it's a feature I can't see ever enabling and using in my use of the system. (And if it's simply a parameter that people can disable I'd guess a lot of people will just turn it off the first time it bothers them).

**Comment by squilter** [comment]
A [csv file with all airports in the world](http://ourairports.com/data/) is less than 10mb.  The questions are now:
- How to upload initially
- How to update

Or maybe require the gcs to poll nearby airports from a website like [this](https://www.mapbox.com/drone/no-fly/).  It should solve the up-to-date problem.  But that would require that the gcs has an active internet connection.  Unlikely.

Then there's the [FAA app](http://www.faa.gov/uas/b4ufly/).  It's not released yet, but maybe I could email them and ask if there's a database that we could use.

**Comment by WickedShell** [comment]
My point with the airports is that in the US I'd like to actually load the correct radius's of controlled airspace (IE the class delta airport foo has a radius of X centered on this point). It gets worse if you look at the inverted cake shape on class C and B airports. And it gets worse still when coupled with the fact that every airport can be unique (not all class D's have the same radius). Anyways I suspect this makes it to difficult to look at this information easily/compile it, but it really limits the usefulness in my opinion and is a reason you would want to only look at a constant radius from the airport.

**Comment by rmackay9** [comment]
@squilter, yes, I think making the GCS responsible for providing the data to the vehicle similar similar to how we transfer the terrain data might be good.
http://mavlink.org/messages/common#TERRAIN_REQUEST
http://mavlink.org/messages/common#TERRAIN_DATA
http://mavlink.org/messages/common#TERRAIN_REPORT

I think the storage of the data could be similar to terrain data with the airport's lat,lon location and stay-out radius stored instead of the terrain altitude.  A bit unlike terrain data there could be multiple airports within a grid if the grid is very large.

Probably best to ping ideas around with Tridge a bit who wrote the terrain handling.

**Comment by abvgeej** [comment]
Emergency landings should be the last resort, not the first.
I vote against this feature, as I believe that the current functionality in the MP is more than what is needed, and the feature is too specific.

**Comment by squilter** [comment]
@abvgeej I don't use mission planner, and I know plenty of other people that don't either.  Sometimes people use mobile apps (Tower or Solo app).  Some people fly with only an rc.

**Comment by earsneyes** [comment]
The airport restrictions DJI Innovation built into their systems are wrong for my country and it forces me to drive far away to test things that are actually permitted where i like to fly ("near" airport). 

Very annoying thing. At least we would need an option too disable it. 
On the other side.. The average DJI user might need that feature for our all safety. 
Not so sure if that is valid for average ardupilot user.

**Comment by rmackay9** [comment]
I'm tentatively targeting Copter-3.4 for this feature but no promises

**Comment by govsux** [comment]
re-"As with nearly all features, we would allow the user to disable the safety check"
My brother has a Dji and after an update his phantom is useless to him in the area he flew %90 of the time and it's completely silly because the airport is rarely used and he is far enough away even at a 1/2 mile away that the planes are FAR higher than 400. PLEASE keep this as a user defined warning or action.

**Comment by R-Lefebvre** [comment]
I thought the DJI NFZ's were easy to defeat in the app?

**Comment by govsux** [comment]
It used to be user selectable but not anymore. It made a lot of people angry as they did not mention this was part of a FW update.

**Comment by R-Lefebvre** [comment]
Right, but my understanding is that you can simply disable the restriction, by registering an account with DJI, and then a couple easy taps on the app will allow flight in restricted areas.  Is that not the case?

**Comment by govsux** [comment]
Hmmmm I don't think he is aware of that I'll let him know and confirm thx

**Comment by OXINARF** [comment]
Rob that's in the new Geo system that, as far as I know, is still in beta - but even in this one there are areas that you can't fly no matter what.
The current system is the No Fly Zones where you can't fly near airports.

**Comment by erich-comsIO** [comment]
I am just beginning to work on my private pilots license, so am obviously not an expert , but planning ahead to take advantage of the 2020 ADS-B deadline for all aircraft in US airspace, it might be interesting to add some ADS-B receiver integration. I gather there are some fairly inexpensive and small receivers that, while not transponders, could pick up traffic info along with weather and NOTAMs.

For LOS operations, the receiver could be pretty useful even just as part of ground station. I just ordered a Stratus 2S, which might be prohibitively expensive overkill for hobbyists, but drives the ForeFlight Apps that offer some pretty nifty features, including hazard avoidance for well marked items on Sectional Charts (someone mentioned towers, etc). One imagines these features could be implemented as part of this project with a generic receiver.

This integration would give the platform a leg up in adapting to future regulatory regimes. NOTAMs could dynamically contribute to geofencing, etc.

**Comment by magicrub** [comment]
Erich,

Please visit http://plane.ardupilot.com/wiki/common-ads-b-reciever/

**Comment by erich-comsIO** [comment]
You mean someone already thought of this, lol… Sorry to waste space and thanks for the link - super cool!

**Comment by magicrub** [comment]
Which reminds me... That wiki needs to be updated

**Comment by hsteinhaus** [comment]
Alternative idea to on-board no-fly zones: overlay correct and up-to-date schematics of air spaces in the GCS map display, plus some help button showing a vertical cross-section and explaining the implication of the different airspace types. 

Idea behind: I guess 99% of the violations happen by lack of knowledge, not by intention. However, an evil pirate that plans to violate an airspace intentionally, can remove the NoFlyZone feature from source.

Advantage of this approach: better user acceptance, better usability, e.g. for people doing their (legitimate) flying on airfields

**Comment by rmackay9** [comment]
There is a partial fix to this included in Copter-3.4-rc2 if the user has an ADSB sensor (like the Ping from [uAvionix](http://www.uavionix.com/)).  The vehicle will not arm if the sensor reports it is within range of another vehicle.  It can also avoid vehicles.

**Comment by squilter** [comment]
I am still interested in developing this feature with airspace 'tiles'. Maybe we can restart this conversation. Here are some notes:

- The code should be shared between PX4Firmware and ardupilot. The library can be a dronecode project that is submoduled by both.
- 3dr added airpace info to the Solo app. Getting the info into a gcs is definitely easier than this whole tile thing.
- If we wait until the standard board is a linux board, then we could use something nice like JSON within the tiles. Otherwise we will likely need to develop some proprietary format in order to save emory and cpu cycles.
- There were a couple startups interested in supplying the airspace data to us. Any updates from them?

**Comment by magicrub** [comment]
>>There were a couple startups interested in supplying the airspace data to
us. Any updates from them?

The startups are AirMap <https://www.airmap.com/> and Altitude Angel
<https://www.altitudeangel.com/>, both are DroneCode members. There was a
DroneCode working group to integrate them but it didn't go anywhere.
Altitude Angel did most of the talking, mostly about what they have to
offer and their interface. They were busy building out their own platform
and could not allocate resources to add it to any DroneCode autopilot. So,
someone just needs to do it.


On Tue, Aug 9, 2016 at 10:21 AM, Sebastian Quilter <notifications@github.com

**Comment by rmackay9** [comment]
One thing that will make implementing this easier is that Copter-3.4 now supports polygon fences and stopping at the fence (see AC_Avoidance).  Basically we just need to add a new function below "adjust_velocity_circle" and "adjust_velocity_poly" which consumes the new data and shortens the desired velocity if necessary.

**Comment by squilter** [comment]
@rmackay9 @magicrub I put some thought into this today. See here:
http://discuss.dronecode.org/t/no-fly-zones/243

**Comment by rmackay9** [comment]
Out of time for Copter-3.4 so bumping to Copter-3.5.

**Comment by rmackay9** [comment]
Copter/Rover-4.0.0 include support for stay-out zones so from the flight code point of view we have the basic support required for this feature.  Remaining issues are mostly ground station issues I think although I think we might keep this issue open because without some guidance and possibly some code changes from the flight code team it probably won't be resolved.

**Comment by peterbarker** [comment]
> Copter/Rover-4.0.0 include support for stay-out zones so from the flight code point of view we have the basic support required for this feature. Remaining issues are mostly ground station issues I think although I think we might keep this issue open because without some guidance and possibly some code changes from the flight code team it probably won't be resolved.

Should we close this issue, or move it to be a WikiNeeded thing?

**Comment by rmackay9** [comment]
I guess we can close it by saying that it's really up to the GCSs now to pass the fences to AP

**Comment by timtuxworth** [comment]
This is not fixed for plane. Once a plane breaches a fence it will happily fly right through a keep-out-zone (such as an airport) if it is on the RTL path.

**Comment by rmackay9** [comment]
@timtuxworth,  OK, thanks for the report.  I think a more specific issue just for plane is probably in order then instead of this very general issue.
