### ISSUE TITLE
Update MAVLink RSSI field interpretation to latest versions

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#10584]
The  MAVLink definition of `.rssi` field on the following messages has been redefined from `0-100, 255=not used` to `0-254, 255=not used`: [RC_CHANNELS](https://mavlink.io/en/messages/common.html#RC_CHANNELS), [RC_CHANNELS_RAW](https://mavlink.io/en/messages/common.html#RC_CHANNELS_RAW), [RC_CHANNELS_SCALED](https://mavlink.io/en/messages/common.html#RC_CHANNELS_SCALED), [RADIO_STATUS](https://mavlink.io/en/messages/common.html#RADIO_STATUS)

ArduPilot (anecdotally) uses the range 0-255. Action is to move to the new definition. @auturgy - FYI

Reference: https://github.com/mavlink/mavlink/issues/1027

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/18435
