### ISSUE TITLE
Copter: Desired Yaw goes to zero during Auto

### ISSUE THREAD

**Issue by elpipe** [ArduPilot/ardupilot#1060]
I have been having a recurring issue with my copter yawing (aggressively) over 360 degrees at times on arrival at a waypoint. Checks of the logs shows that the desired Yaw goes to zero and then the actual yaw ultimately changes from its original direction. I have logged details of the issue here: https://groups.google.com/d/topic/drones-discuss/HK011DQSwqs/discussion
and would like someone to have a careful look at it for me to determine if its a bug or not.
![waypoint_yawing](https://cloud.githubusercontent.com/assets/7149927/2938178/e51ee738-d8f5-11e3-82fa-a100e6e18d23.png)

Regards,
Maurice

**Comment by OXINARF** [comment]
@elpipe Is this still a problem?

**Comment by lthall** [comment]
old
