### ISSUE TITLE
yaw change in APM:Copter V3.4-dev

### ISSUE THREAD

**Issue by shubham9436** [ArduPilot/ardupilot#10610]
How do I control the yaw of the drone?
I am using APM:Copter V3.4-dev .
I have used https://github.com/dronekit/dronekit-python/blob/master/examples/set_attitude_target/set_attitude_target.py . But set_attitude(yaw_rate = 30, thrust = 0.5, duration = 3) does not work properly.

I need to rotate the drone on its yaw axis. I am using Gazebo simulator

#### Version
APM:Copter V3.4-dev .

#### Platform
[  ] Copter

#### Airframe type
QUAD

**Comment by amilcarlucas** [comment]
This page is for software issues, not for support questions.
I already answered you in the discussion forum.
