### ISSUE TITLE
dual gps not working on pixhawk cube

### ISSUE THREAD

**Issue by amitmanish** [ArduPilot/ardupilot#10621]
Hello,
I have trying connecting dual gps on pixhawk cube. I connected second gps on gps2 port and have selected serial4 with serial protocol parameter set to 5. Both gps are getting detected by ardupilot as seen in message window of mission planner but only gps1 hdop appears and gps2 hdop2 shows 99 continuously.

**Comment by rmackay9** [comment]
Seems like a support issue so I will close this.  Normally it's best to [first raise an issue in the forums](https://discuss.ardupilot.org/c/arducopter) and then once it's confirmed we raise a bug or enhancement request here.
