### ISSUE TITLE
CopterWiki: Sport mode do not remain in it's current attitude

### ISSUE THREAD

**Issue by ginodouglas** [ArduPilot/ardupilot#1064]
Sport mode should remain in it's current attitude when the sticks are released, but it returns to level flight. The behavior is similar to Acro Trainer mode.

User Twistor have a post in http://ardupilot.com/forum/viewtopic.php?f=25&t=6835& showing that are 2 lines to be commented off to fix the problem.:

target_roll_rate = -constrain_int32(roll_angle, -ACRO_LEVEL_MAX_ANGLE, ACRO_LEVEL_MAX_ANGLE) \* g.acro_balance_roll;

 target_pitch_rate = -constrain_int32(pitch_angle, -ACRO_LEVEL_MAX_ANGLE, ACRO_LEVEL_MAX_ANGLE) \* g.acro_balance_pitch;

I had this problem in Arducopter 3.1.3 and 3.1.4 stable versions.

Gino

**Comment by ronhogwarts** [comment]
I too think that the default should be 0, otherwise it is too similar to alt hold by default.
