### ISSUE TITLE
FBWA response (differential spoilers config)

### ISSUE THREAD

**Issue by nikan8** [ArduPilot/ardupilot#10705]
This might be either a bug or require additional change of parameters. The issue relates to latest stable Arduplane release (3.9.5). FC: HBro Pixhawk4. 
I have setup Fx-79 flying wing with differential spoilers configuration. (FX-79 has 2 elevons on each wing). In manual mode all elevons' response to RC inputs are as expected. Response to pitch and roll in FBWA mode is also normal. However, while in FBWA mode, the magnitude of response of left-wing elevons to attitude change is bigger compared to the magnitude of response of right-side elevons. (in other words, left-side servos are more sensitive to attitude changes).
Is this behavior normal? What parameters govern sensitivity of elevons in FBW/stab modes?

Thank you for your comments.

**Comment by Naterater** [comment]
SERVOn_TRIM, MIN, and MAX all affect the limits and positions of the servo (and control surface). Left and right will apply the same proportion of PWM, so check your mechanical linkage or the parameters I stated above.
