### ISSUE TITLE
Sub: LCD screen is not updating

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#10707]
### Bug report

LCD screen starts with initial information but it does not update.
Does not update flight mode
Does not update battery

**Version**
Stable

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[x] Submarine

**Hardware type**
Pix-v2

**Comment by WickedShell** [comment]
@patrickelectric this was an intentional feature in the AP_Notify library to disable updates once flying. I'm not entirely sure what the backstory is, but I'm guessing it's due to overhead/bus jitter of updating a I2C display that can't be seen by a user?

**Comment by IamPete1** [comment]
Closing in favor of https://github.com/ArduPilot/ardupilot/issues/18215
