### ISSUE TITLE
Functions on SD folders do not work (ChibiOS)

### ISSUE THREAD

**Issue by maciek252** [ArduPilot/ardupilot#10725]
### Bug report

I need to read (in flight) several possible variants of a mission from a SD card, and modify the current mission loaded to the flight controller. It has been working fine in NuttX-based ArduCopter, but no longer works in ChibiOS. All the functions dealing with folders fail in my case (opendir, f_findfirst etc), either don't return any result or even hang the execution of the thread. Reading a file with the name given explicitly works fine (function open() ).

**Version**
3.6.7, tested on fresh copy from the repository

**Platform**
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Tested on pixhawk 2.4.8 (fmuv3)

**Comment by IamPete1** [comment]
This is a example of loading a mission from the SD card using scripting.

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/mission-load.lua
