### ISSUE TITLE
AC3.2-dev: S-BUS F/S bug

### ISSUE THREAD

**Issue by michas75** [ArduPilot/ardupilot#1074]
Hey. 

My setup:

3DR PX4, Futaba T14SG + R7008SB. On copter software ArduCopter 3.2-DEV fail safe S-BUS signal is not recognized. ArduPlane 3.0.2 with same setup all works great, F/S set in transmiter is working.

**Comment by OXINARF** [comment]
Current code recognizes the SBUS failsafe bit, so if this is what it was about, it is fixed, so I'm closing. If there is still some problem with SBUS in a recent version please post about it in the forum (http://discuss.ardupilot.org).
