### ISSUE TITLE
"MAV_CMD_DO_CHANGE_SPEED" command not compliant with MAVLink protocol

### ISSUE THREAD

**Issue by MoussSS** [ArduPilot/ardupilot#1079]
**Software versions:**
Arducopter: _ArduCopter-3.1.0_
Mission planner: _1.3.1 build 1.1.5229.30673_

**Detection context :**
 * In Flight test with DroidPlanner showed command does not work
 * In Flight test with Mission Planner works
 * Code inspection in both Mission Planner and embedded software revealed MAVLink non compliance.

**Description:**
The MAVLink **MAV\_CMD** "_MAV\_CMD\_DO\_CHANGE\_SPEED_" used in mission item implemented in ArduCopter does not match with the MAVLink protocol (https://pixhawk.ethz.ch/mavlink/).
Indeed the speed value should be set in the "Mission Param 2" but it is currently set with "Mission Param 1".

In GCS_MAVLINK.pde, the command is registered:

	case MAV_CMD_DO_CHANGE_SPEED:
    	tell_command.lat = packet.param3;
    	tell_command.alt = packet.param2;
    	tell_command.p1 = packet.param1;
    	break;

	
In commands_logic.pde the command is processed:

	static void do_change_speed()
	{
		wp_nav.set_horizontal_velocity(command_cond_queue.p1 * 100);
	}

**Correction proposition:**
The _command\_cond\_queue.alt_ should be used in the second function instead of _command\_cond\_queue.p1_.

**Comment by WickedShell** [comment]
Fixed sometime ago in master.
