### ISSUE TITLE
Copter 3.6.7 - autoland issue.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#10815]
### Bug report

Please see https://discuss.ardupilot.org/t/why-quad-doesnt-want-to-disarm-after-landing-happened-two-times-now-arducopter-3-6-7/39568

The landing may fail to get to the point where motors are stopped.

**Version**
3.6.7

**Platform**
[x ] Copter

**Logs**
logs in the forum thread.

**Comment by rmackay9** [comment]
Thanks for the report.  I don't think we can conclude this is a real bug though.  landing detection can fail due to all kinds of reasons.

Thanks again but I think I will close this until we have more evidence that it's a bug
