### ISSUE TITLE
serial interface read only!

### ISSUE THREAD

**Issue by karu2003** [ArduPilot/ardupilot#10822]
### Feature request

**Is your feature request related to a problem? Please describe.**
Freezes the work of Ardupilot with sensors over MAVLink.

**Describe the solution you'd like**
serial interface read only!
SERIALx_OPTIONS
read only 

**Platform**
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

It would be useful to expand the options for the serial interface. Add the ability to read only. For sensors working over MAVLink - RangeFinders, Proximity.

**Comment by IamPete1** [comment]
I think https://github.com/ArduPilot/ardupilot/pull/14742 implements the functionality described?

Fell free to re-open if it does not.
