### ISSUE TITLE
SITL: external sensors on Real Serial over MAVLink 

### ISSUE THREAD

**Issue by karu2003** [ArduPilot/ardupilot#10823]
### Bug report

**Issue details**
i have sensor on COM4
sim_vehicle.py -A "--uartF=uart:/dev/ttyS3" --console --map
SERIAL5_PROTOCOL = 1
SITL does not work with external sensors on Real Serial over MAVLnk.

**Version**
last

**Platform**
[ x ] Copter

**Hardware type**
SITL

**Logs**
link 1 down

**Comment by magicrub** [comment]
What sensor? Have you tried a different uartX and different serialX Param? Why are you using serial 5?

**Comment by karu2003** [comment]
5 - because it is free. But I tried others. The result is the same.
https://github.com/ipmgroup/RangeFinder_9xVL53LXX_software
