### ISSUE TITLE
ArduCopter:  Occasional EKF_STATUS_REPORT.airspeed variance

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#10835]
### Bug report

ArduCopter, no airspeed sensor, produces occasional airspeed data.
This, in turn, triggers warnings like https://github.com/ArduPilot/MAVProxy/blob/master/MAVProxy/modules/mavproxy_console.py#L365

**Version**
AC 3.6.6

**Hardware type**
Cube

![Screenshot from 2019-03-18 14-38-23](https://user-images.githubusercontent.com/1468842/54534088-f0c16a00-498b-11e9-9507-6a28a9c73122.png)

**Comment by IamPete1** [comment]
@AndKe any update? Do you still see this on 4.1?

**Comment by AndKe** [comment]
Oh, that's a long time ago.
No, I can't see this issue in recent releases.
