### ISSUE TITLE
Sub: enforce configuration of 'disarm' button

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#10844]
It should be a requirement that there is always a button configured with the `disarm` function. At least, we should not arm if there is not a disarm button configured.

**Comment by peterbarker** [comment]
On Tue, 19 Mar 2019, Jacob Walser wrote:

> It should be a requirement that there is always a button configured with the disarm function. At least, we should not arm if there is not a disarm button
> configured.

You can arm/disarm via mavlink on Sub.  Perhaps adding a check that if you 
have an arm button then you also have a disarm button?

**Comment by jaxxzer** [comment]
> You can arm/disarm via mavlink on Sub.

I think this does not preclude the potential to require the disarm button to be configured in any event.

**Comment by jaylthegreat** [comment]
I've made a PR solving this issue if you want to assign it in the meantime

**Comment by Williangalvani** [comment]
This got addressed in #11749
