### ISSUE TITLE
Heli: H3_140 Swash does not work

### ISSUE THREAD

**Issue by twistedwings** [ArduPilot/ardupilot#10864]
Pitch is reversed if heli is tilted in stabilize mode.
Seems that H3_140 (H_SWASH_TYPE 2) does not respect servo position
(-140°, 140°, 0° in my case).
H_SWASH_TYPE 0 works.

Arducopter 3.6.7

**Comment by lvale** [comment]
Please post the issue on the forum.

I have a Heli with the correct config H3_140 working just fine
