### ISSUE TITLE
 EKF: use position innovation to trigger failsafe or ekf primary change

### ISSUE THREAD

**Issue by chobitsfan** [ArduPilot/ardupilot#10889]
### Feature request

**Is your feature request related to a problem? Please describe.**
fly Copter-3.5.7, it continues to climbing up even in LAND mode (it finally start to descend in 1400m). 
This is a dangerous situation because there is no safe way to bring it down.
After inspect the log, the altitude of 1st EKF3 core (AHRS_EKF_TYPE=3 for this flight) is complete wrong. 
![report1](https://user-images.githubusercontent.com/19793511/54905746-b2dcbc80-4f1c-11e9-9933-787197e11171.jpg)
but 2nd EKF3 core is correct
![report2](https://user-images.githubusercontent.com/19793511/54905889-03ecb080-4f1d-11e9-9671-e776866fcd6b.jpg)
XKF3.IPD is very high short after take off, but no action is taken
![report3](https://user-images.githubusercontent.com/19793511/54906048-634ac080-4f1d-11e9-9d7e-80068cf0c8db.jpg)
XKF4.SH remains very low util the copter fly up to 1400m

**Describe the solution you'd like**
1. Maybe EKF can change primary or go to failsafe when IPD is really high
or
2. allow user to manually change ekf primary

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
log: https://drive.google.com/open?id=1avbVCBa1-i9SuasvowmT2dACVdvsTiNq

**Comment by rmackay9** [comment]
In parallel I've been working a bit with Paul Riseborough on some improved EKF vibration compensation which is in this branch: https://github.com/rmackay9/rmackay9-ardupilot/commits/copter-fake-clip

It's not quite working though so requires some more effort.  I think the general approach will work though.

**Comment by chobitsfan** [comment]
thank you @rmackay9 
It is strange that SP (or SH) remains low (<0.5) when IPN, IPE or IPD already go above 100. Below is another example. IPN already go above 200, but SP still below 0.5

![screenshot](https://user-images.githubusercontent.com/19793511/54975144-20e2bb80-4fd1-11e9-8a60-6945c3e63de6.jpg)
