### ISSUE TITLE
Copter: Number of parameters in mission items is limited to four

### ISSUE THREAD

**Issue by MoussSS** [ArduPilot/ardupilot#1090]
**Software version:** Arducopter: _ArduCopter-3.1.0_

**Detection context:**

Code inspection showed that number of parameters used by mission item is limited to four instead of the seven allowed by the MAVLink protocol
("[https://pixhawk.ethz.ch/mavlink/](https://pixhawk.ethz.ch/mavlink/)").

**Description:**

Mission items received in function `handleMessage` in **GCS_Mavlink.pde** are stored in a structure `Location` defined in **AP_Common.h** :

```
struct Location {
    uint8_t id;         ///< command id
    uint8_t options;    ///< options bitmask (1<<0 = relative altitude)
    uint8_t p1          ///< param 1
    int32_t alt;        ///< param 2 - Altitude in  centimeters (meters * 100)
    int32_t lat;        ///< param 3 - Lattitude * 10**7
    int32_t lng;        ///< param 4 - Longitude * 10**7
};
```

Therefore, there are some mission items for which certains functionnalities can not be useable. For example, **MAV_CMD_NAV_WAYPOINT**, it is not possible to directly set the desired yaw angle or the acceptance radius as defined below (MAVLink protocol):

```
16  MAV_CMD_NAV_WAYPOINT    Navigate to MISSION.
Mission Param #1    Hold time in decimal seconds. (ignored by fixed wing, time to stay at MISSION for rotary wing)
Mission Param #2    Acceptance radius in meters (if the sphere with this radius is hit, the MISSION counts as reached)
Mission Param #3    0 to pass through the WP, if > 0 radius in meters to pass by WP. Positive value for clockwise orbit, negative value for counter-clockwise orbit. Allows trajectory control.
Mission Param #4    Desired yaw angle at MISSION (rotary wing)
Mission Param #5    Latitude
Mission Param #6    Longitude
Mission Param #7    Altitude
```

**Comment by DavidIngraham** [comment]
Closing, this was fixed many years ago.
