### ISSUE TITLE
Copter: Follow me mode overrides a boolean field

### ISSUE THREAD

**Issue by valentinb** [ArduPilot/ardupilot#1091]
**Software version:**
Arducopter: _ArduCopter-3.1.0_

**Detection context:**

Code inspection of both Droid Planner and embedded software showed that "follow me" mode send mission items with the "current" boolean field overriden with the value **_2**_ and does not match the MAVLink protocol
("[https://pixhawk.ethz.ch/mavlink/](https://pixhawk.ethz.ch/mavlink/)").

**Description:**

Mission items received in function `handleMessage` in **GCS_Mavlink.pde** store the waypoint location (latitude, longitude and altitude) in a **`tell_command`** variable and launch the **`GUIDED MODE`** (corresponding to  the "follow me" mode) if the **`current`** field is equal to **_2**_:

```
if (packet.current == 2) {  //current = 2 is a flag to tell us this is a "guided mode" waypoint and not for the mission
    // initiate guided mode
    do_guided(&tell_command);

    // verify we recevied the command
    mavlink_msg_mission_ack_send(
        chan,
        msg->sysid,
        msg->compid,
        0);
}
```

**Correction proposition:**

This mode should perhaps use the **COMMAND_LONG** (**#76**) message defined in MAVLink protocol and which encapsulate the **MAV_CMD** to implement direct navigation to a waypoint:

| Field Name | Type | Description |
| --- | --- | --- |
| target_system | uint8_t | System which should execute the command |
| target_component | uint8_t | Component which should execute the command, 0 for all components |
| command | uint16_t | Command ID, as defined by MAV_CMD enum |
| confirmation | uint8_t | 0: First transmission / 1-255: Confirmation transmissions |
| param1 | float | Parameter 1, as defined by MAV_CMD enum |
| param2 | float | Parameter 2, as defined by MAV_CMD enum |
| param3 | float | Parameter 3, as defined by MAV_CMD enum |
| param4 | float | Parameter 4, as defined by MAV_CMD enum |
| param5 | float | Parameter 5, as defined by MAV_CMD enum |
| param6 | float | Parameter 6, as defined by MAV_CMD enum |
| param7 | float | Parameter 7, as defined by MAV_CMD enum |

**Comment by amilcarlucas** [comment]
Has this been implemented in the new follow me code?

**Comment by peterbarker** [comment]
@amilcarlucas No, the new follow-me code works completely differently to what this PR is talking about.

Given how embedded the current behaviour is, I'm pretty sure it defines another standard - which may or may not be compatible with the mavlink spec :-)
