### ISSUE TITLE
s.port only shows gps

### ISSUE THREAD

**Issue by oguzhantasdemir** [ArduPilot/ardupilot#10913]
#### Issue details
hi. i installed last arduplane ın my board. everythings works fine execpt telemetry. i have r9m and r9 slim+ set. r9 slim+ has inverted s.port out. i connected tx1 to inverted s.port(receiver pin rx1).set serial1_protocol =10 and serial1_options=4.  it only shows the gps sensor. nı other sensor. i tried deleted all sensor an re-adding new sensor.

#### Version
-latest

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
flying wing

#### Hardware type
omnibusf4v3

**Comment by rmackay9** [comment]
Theoretically at least this should go into the [discuss forums](https://discuss.ardupilot.org/c/arduplane/plane-3-9) before being raised here.
