### ISSUE TITLE
AC 3.6.7 firmware only in chibiOS version

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#10912]
Hello,

I'm using last mission planner, and I ugraded to 3.6.7 from 3.6.6 my hexacopter pixhawk FMUV2, and I checked NO chibi OS during firmware upgrade process.

After upgrade done, I see when connected to hexacopter, in the mission planner messages "
chibios" instead of "PX4"

I remade the upgrade many times to be sure that I dont made mistake, by cliking NO CHIBIOS when mission planner promt, and Always it install ChibiOS version.

And now I can't go back to 3.6.6....I Don't found the firmware on the previous firmware link.

thank you for your help.

**Comment by rmackay9** [comment]
I think this is fixed in beta MP and it's an MP issue not a flight-code issue I think so I'll close this one (i've also replied over on the similar MP issue)
