### ISSUE TITLE
Copter: deprecate SPORT mode

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#10930]
Sport mode is a very rarely used mode so I think we should deprecate it to help simplify Copter (a little bit).  Sport mode is a mixture of Acro and AltHold in that the user controls the lean rates (instead of angles) and climb rate.

It was added by Leonard Hall and I thinking that it might be good for filming but it wasn't really based on a user request.

**Comment by liang-tang** [comment]
agree

**Comment by muramura** [comment]
With the support of OMNIBUS and KAKUTE, I think that there are people who put ArduPilot on drone racing drone.
This drone racing drone camera is equipped with a fixed angle camera.
Recently, it seems that a promotional video has been taken using a quadcopter called nano drone.
This nano drone camera too. It is fixed at a certain angle.
This use has increased since last year, and this mode is considered to be useful from now on.

**Comment by rmackay9** [comment]
@muramura, nice video.  I don't think that most drone racers use Sport mode though.  They will tend to use acro I think.  I think it will be unlikely that we will find a user.

P.S. I've removed @lthall as the assignee because this is something i can take care of.  It's just a change to a definition.

**Comment by muramura** [comment]
@rmackay9 san...
I am an acquaintance of me who is shooting like a movie.
It seems that there is a nano drone using OMINIBUS and KAKUTE.
I think it is a good mode to shoot such videos.
ex:
https://youtu.be/HMHC4Pakf0Y

**Comment by rmackay9** [comment]
@muramura, if you can ask him to try it and report back that would be great.  I suspect he won't like it and will prefer to stay with acro, stabilize or one of the other modes.

**Comment by muramura** [comment]
@rmackay9 san.. Thanks Comments.

**Comment by Naterater** [comment]
If I remember correctly, sport mode works very well for steady cinematic shots for camera drones. I'm not sure removing it is the best, but I'm just one vote here, and I don't use it myself.

**Comment by lvale** [comment]
Although I don't use it frequently with large drones, have used several times with fixed cameras (too big to the gimbal).

**Comment by proficnc** [comment]
I use sport mode! It’s awesome!

**Comment by magicrub** [comment]
I see no positive, only huge negatives, for removing this.

**Comment by rmackay9** [comment]
Alright, seems like a few people want to keep it so we will leave it alone.
