### ISSUE TITLE
AP_HAL_FLYMAPLE/examples/Semaphore/Semaphore.pde

### ISSUE THREAD

**Issue by YangTingMDP** [ArduPilot/ardupilot#1094]
Semaphore.pde:9:26: error: 'AP_HAL_AVR_APM2' was not declared in this scope
Semaphore.pde: In function 'void setup()':
Semaphore.pde:84:56: error: invalid conversion from 'void (_)(uint32_t) {aka void (_)(long unsigned int)}' to 'fastdelegate::FastDelegate0<>::DesiredRetType (_)() {aka void (_)()}' [-fpermissive]

**Comment by OXINARF** [comment]
Flymaple isn't supported anymore and was removed. Closing.
