### ISSUE TITLE
BLHeli passthrough unavailable when THR_MIN <0

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#10965]
### Bug report

**Issue details**

Just as title shows, BLHeli passthrough is unavailable when THR_MIN is < 0. The flight controller "roboot" is unavailable according to BLHeli Suite.

**Version**
Master as of 3/22/2019, and I have noticed this since DSHOT reverse thrust has been supported (BLH_REMASK parameter was implemented).

**Platform**
[  ] All
[  ] AntennaTracker
[?] Copter
[X] Plane
[?] Rover
[?] Submarine

**Airframe type**
Dual motor electric plane

**Hardware type**
Cube black with mini carrier board.

**Logs**
N/A - configuration issue

**Comment by Naterater** [comment]
@IamPete1, wasn't this addressed? Unfortunately 4.0.6 still has this behavior.

**Comment by IamPete1** [comment]
Should be fixed in master, hasn't made it to stable tho
