### ISSUE TITLE
About Smart Batteries

### ISSUE THREAD

**Issue by 2357531789** [ArduPilot/ardupilot#10968]
Hello, the more UBEC pixhawk is used, the more deficiencies it will find, especially the demand for smart batteries, so I should add such a device in my imagination:
It can be directly tied to batteries, used with batteries, discharged and charged, and monitored the status of batteries.
It can set the parameters of the battery to which it is bound: maximum voltage, minimum voltage, capacity and discharge power with the use of calibration.
It can communicate with flight control through serial ports such as can or iic. Flight control can acquire these battery parameters and execute them.
Of course, if there is such a product to buy now, please let me know!

**Comment by rmackay9** [comment]
AP supports two different smart batteries ([wiki](http://ardupilot.org/copter/docs/common-smart-battery.html)).  If more smart batteries were available on the market that would be great but until then there's not much we can do about it I think so I will close this issue if that's OK.
