### ISSUE TITLE
sub: no motor output after motor test completion, then subsequent arming for piloting

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#10969]
Seen on stable 3.5.3

Steps to reproduce:
- boot
- motor test
- disarm
- wait ten seconds
- arm
- no motor output no matter what

**Comment by Williangalvani** [comment]
Another case here:
https://discuss.bluerobotics.com/t/problem-motor-test-command-failed/4741

**Comment by jaxxzer** [comment]
The workaround in the meantime is to reboot after a motor test. This should only affect first time set-up.

**Comment by jaxxzer** [comment]
The problem is actually in QGC: https://github.com/mavlink/qgroundcontrol/issues/7275#issuecomment-480306112
