### ISSUE TITLE
Copter: autotune gains doesn't get saved

### ISSUE THREAD

**Issue by twistedwings** [ArduPilot/ardupilot#10972]
After completed autotune session I landed with autotune on and disarmed.
The gains are still the same.
Tried twice.

Matek F405-CTR
ArduCopter 3.6.7

**Comment by rmackay9** [comment]
This should really be raised as a support issue first in [the Copter-3.6 forums](https://discuss.ardupilot.org/c/arducopter/copter-36) so I'll close this issue.  I know it can sometimes be hard to get answers on the discuss forums but still we need to be strict and restrict the issues list to just confirmed bugs and enhancement requests or else it turns into another support forum.

If you do post in the forums any chance a dataflash log can be included?  Also feel free to stick a link in this issue so I can find the discussion and have a peek.
