### ISSUE TITLE
sub + qgc: do not announce 'motor test timed out'

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#11018]
This is normal and expected, but it looks like something went wrong. Add a special prefix to the 'motor test timed out' message so that qgc does not speak it. Consider also changing severity of the message.

**Comment by jaylthegreat** [comment]
I'll do this issue. is there anything i should do to claim it other than ask here?

**Comment by jaxxzer** [comment]
> I'll do this issue. is there anything i should do to claim it other than ask here?

Go for it! I'll try to respond more expediently next time.

**Comment by Williangalvani** [comment]
This should have been closed by https://github.com/ArduPilot/ardupilot/pull/11748

**Comment by rmackay9** [comment]
Ok, closing..
