### ISSUE TITLE
Cortex-M7 (fmuv5 etc.) Data Corruption Errata 1259864

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#11029]
### Feature request

**Is your feature request related to a problem? Please describe.**
I saw this Errata in PX4 project‘s issue list, and PX4 already disable dcache on fmuv5, is Ardupilot need to follow this? I'm not sure would ChibiOS avoid this.
![image](https://user-images.githubusercontent.com/4748411/55679748-55e0fd80-5943-11e9-878c-b38ed5045813.png)

**Describe the solution you'd like**
Should ArduPilot disable dcache on M7 chips too?

**Platform**
[√] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by tridge** [comment]
thanks for raising this, but I am aware of this errata already
ArduPilot confgures the dcache as write-back, not write-through, which means we are unaffected. I have no idea why px4 uses write-through (assuming they do?). Maybe they don't have the hooks for the cache flush and invalidate options needed for DMA usage? We have all those hooks in ArduPilot and automatically apply the right cache ops for each DMA operation.
I already discussed this errata with Giovanni (the ChibiOS maintainer) and he and I both can't see any way that ArduPilot could be affected

**Comment by bys1123** [comment]
Thanks!
