### ISSUE TITLE
sdcard_init: execute twice.

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#11032]
### Bug report

![image](https://user-images.githubusercontent.com/16251761/55685307-1e944000-5987-11e9-980c-6d387dc6b5e1.png)

Why sdcard_init was executed twice？ 

**Version**
copter 3.6.7
**Platform**
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
I think this has been resolved on master, I'm going to close, but please re-open if you can re-produce.
