### ISSUE TITLE
HIL Simulation broken in ArduPlane 3.02 onwards

### ISSUE THREAD

**Issue by rimb05** [ArduPilot/ardupilot#1106]
In AP HIL v3.02 and 3.03, as soon as X-Plane starts sending packets, all servo outputs go to 1.0.  Also, the mode stays on INITIALIZING.  Disabling X-plane packet transmissions brings the servo outputs back to normal.
Loading 3.01 makes the issue go away, so it's something that changed in 3.02.

**Comment by Naterater** [comment]
It's been about 5 years since this was opened. Is it still an issue?

**Comment by auturgy** [comment]
HIL has not been reimplemented, and frequently gets asked for.
If there’s a duplicate feel free to link to it.

**Comment by peterbarker** [comment]
HIL has been removed.
