### ISSUE TITLE
PX4FLOW not work with Pixhawk4

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#11070]
### Bug report

**Issue details**
Seems PX4FLOW didn't scan bus3 which I2C A port is, this bug is like Digital Airspeed sensor before, I'll create a PR later. 

**Version**
Copter 3.6.7

**Platform**
[  ] All
[  ] AntennaTracker
[√] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Sounds like this has been fixed, https://github.com/ArduPilot/ardupilot/pull/11266#issuecomment-494189047
