### ISSUE TITLE
Copter:WP_YAW_BEHAVIOR not effecting

### ISSUE THREAD

**Issue by thomasonegd** [ArduPilot/ardupilot#11081]
### Bug report
Copter:WP_YAW_BEHAVIOR not effecting
**Issue details**
I'm running Copter 3.7.0(SITL)，the WP_YAW_BEHAVIOR is set to 1(or 2)，but the pilot never change it's heading during all the WPs,the heading keeps the value like it takes off.
**Version**
3.7.0

**Platform**
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
QUAD - X
**Hardware type**
SITL

**Logs**
_Please provide a link to any relevant logs that show the issue_
[my_waypoints.txt](https://github.com/ArduPilot/ardupilot/files/3067786/my_waypoints.txt)

**Comment by amilcarlucas** [comment]
Please retest with the latest master, this might have been fixed today.

**Comment by amilcarlucas** [comment]
I tested it, I could no reproduce this.

**Comment by rmackay9** [comment]
ok, thanks.  I will close this.
