### ISSUE TITLE
How to log mavlink stream

### ISSUE THREAD

**Issue by niXman** [ArduPilot/ardupilot#11100]
Hi,

Sorry, it is not a bug, it is the question.

In my program, I have a stream of UDP datagram, which I parse using the `mavlink_parse_char()`(https://mavlink.io/en/mavgen_c/#parsing-packets) function and process it in the way necessary for me.
I need to log all the messages in the same format as the `ardupilot` does.
Tell me please, how can I do this?
Am I understanding correctly that for this I should use the AP_Logger library in my program? What function member of the `AP_Logger` class should I use?

Thanks.

**Comment by DavidIngraham** [comment]
Hi niXman,
Unforunately we can't help you with this here. We have to keep the issues list clear so it doesn't get bogged down with developer support questions. I'd encourage you to re-post your question on the ardupilot gitter channel or the dev section of discuss.ardupilot.org
Good Luck!
-David
