### ISSUE TITLE
AHRS/EKF: get_vert_pos_rate always returns zero

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#11119]
I've found that the AP_AHRS_NavEKF::get_vert_pos_rate() function always returns zero.

Below is a screen shot of some code I added to SITL to output the EKF's normal climb rate (up is negative), the baro climb rate (up is positive) and the output from the get_vert_pos_rate function.
![ekf-pos-rate-issue-code](https://user-images.githubusercontent.com/1498098/56114654-7ab91e80-5f9c-11e9-85c5-0ebfd4729bda.png)

The result is that the pos_rate is always zero.
![ekf-pos-rate-issue](https://user-images.githubusercontent.com/1498098/56114659-7e4ca580-5f9c-11e9-954f-7f7d4ae37243.png)

By the way, the get_vert_pos_rate function returns a boolean (to show success) and this return is always true.

**Comment by WickedShell** [comment]
In EKF2 `posDownDerivative` is only set during the `StoreOutputReset` which is only called during the filter initialization. (`posDownDerivative` is the basis for the call to get_vert_pos_rate)

**Comment by priseborough** [comment]
The derivative is supposed to calculated by the output observer - I will check the code.

**Comment by priseborough** [comment]
I've checked the code and the posDownDerivative calculation which is supposed to be done inside the output observer is missing. 

It was added originally with this commit https://github.com/ArduPilot/ardupilot/commit/52fd369b2f82c2eb879fb13ac39cc04dbb8ca5fc

And removed when the output observer was re-written here: https://github.com/ArduPilot/ardupilot/commit/6523481c76d454f0fe4ec302a8f771bf3b1363da

The method we should be using is as used by the  PX4 ecl library calculation - see https://github.com/PX4/ecl/blob/master/EKF/ekf.cpp#L617

**Comment by rmackay9** [comment]
@priseborough, do you think you could fix this?  I could give it a try but I don't have a lot of confidence in my abilities to get it right.  I'm certainly happy to help test it.

**Comment by rmackay9** [comment]
@priseborough, I had a quick try and getting this to work but I don't think I've got it quite right. https://github.com/rmackay9/rmackay9-ardupilot/commit/41d236a34fcb4502850f0577caaa04ab1c47abb7

Any chance you could have a look at this?  It's quite important for the Copter-4.0.0 release which I hope we can enter beta testing within the next couple of weeks.

**Comment by priseborough** [comment]
@rmackay9 I've created a WIP branch here for the EKF2 changes https://github.com/priseborough/ardupilot/tree/ekf2VertPosDeriv-wip

**Comment by priseborough** [comment]
I'm in the process fo testing and tuning it and still need to update the comments to make the distinction between the vertical channel complementary filter used for the height derivative calculation and the one used for the normal NED state outputs.

**Comment by priseborough** [comment]
The output tracks, but it is 'over compensating' for changes in climb rate so further tuning is needed. The following shows NKF1.dPD which is the vertical position derivative data. This was generated using SITL Copter.

<img width="1023" alt="Screen Shot 2019-09-21 at 3 40 01 pm" src="https://user-images.githubusercontent.com/3596952/65368561-18202900-dc86-11e9-965f-9acaa4748dad.png">

**Comment by priseborough** [comment]
I will also compare it against the results obtained using the original method from https://github.com/ArduPilot/ardupilot/commit/52fd369b2f82c2eb879fb13ac39cc04dbb8ca5fc  . The output observer has changed structure since then, but the method should still be valid.

**Comment by priseborough** [comment]
I tried a different approach to what is used on the PX4/ecl library, this time using the same threes state complementary filter that ArduPlane TECS used for the heigh channel prior to the EKF.

See https://github.com/priseborough/ardupilot/tree/ekf2VertPosDeriv2-wip

The tracking is better and it won't be affected by EKF velocity state bias errors.

<img width="1029" alt="Screen Shot 2019-09-22 at 4 50 46 pm" src="https://user-images.githubusercontent.com/3596952/65383487-9994bb80-dd59-11e9-9a79-4c4223b05b8f.png">

**Comment by priseborough** [comment]
We may want to make the crossover frequency tuneable and I need to do another pass to make sure it's states are always reset whenever the EKF vertical position or velocity state is reset.

**Comment by rmackay9** [comment]
The vibration failsafe including EKF changes have gone into master so we can close this now, thanks!
