### ISSUE TITLE
Rover time rollover issue

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#11117]
### Bug report

Time roll-over seems to cause Rover significant issues, including reboot

**Version**

```
2019-04-10 07:58:25.91: STATUSTEXT {severity : 6, text : Mission Planner 1.3.64}
2019-04-10 07:58:27.60: STATUSTEXT {severity : 6, text : ArduRover V3.5.0-rc2 (90c9ec29)}
2019-04-10 07:58:27.60: STATUSTEXT {severity : 6, text : ChibiOS: 35ad8a79}
2019-04-10 07:58:27.62: STATUSTEXT {severity : 6, text : MatekF405 0027001B 4D4B5006 20343252}
```

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ X ] Rover
[  ] Submarine

**Airframe type**
boat

**Hardware type**
Matek F405 Wing

**Logs**

TBA

![image](https://user-images.githubusercontent.com/7077857/56102852-0ae26e00-5f73-11e9-8bec-e942f4e41073.png)

![image](https://user-images.githubusercontent.com/7077857/56102874-2b122d00-5f73-11e9-83f2-d9573e18fd43.png)

**Comment by tridge** [comment]
temperature increased over 4hrs leading up to reboot:
![image](https://user-images.githubusercontent.com/831867/56103590-fc965100-5f76-11e9-844c-83a62a4c70d8.png)

**Comment by peterbarker** [comment]
![image](https://user-images.githubusercontent.com/7077857/56103799-f5bc0e00-5f77-11e9-9da6-a3e9001bfc93.png)

**Comment by rmackay9** [comment]
I guess we've concluded that this is more likely a heat or power issue so I think I'll close this one.
