### ISSUE TITLE
Vtol configuration Tailsitter alway not armed

### ISSUE THREAD

**Issue by malpoma** [ArduPilot/ardupilot#11114]
Please check the always arming mode for vtol configuration.

if i put 0 to all parameter of arming, only the wing configuration is armed not the vtol...and in this case the pwm motor don't work.

if put arming rudder 1 or 2 the pwm motor on vtol conf start work...

many thx

**Comment by IamPete1** [comment]
log can be found here https://discuss.ardupilot.org/t/tailsitter-problem-at-pwm-motor/41085

to summarise ARMING_REQUIRE 0 does not arm VTOL motors but plane stuff works as it should. Tested on a tailsitter.

**Comment by kd0aij** [comment]
@IamPete1 Has this been fixed?

**Comment by IamPete1** [comment]
@kd0aij Not that I know of

**Comment by kd0aij** [comment]
this may be related to the fact that a copter state machine must be running for the motors to spool up, but plane isn't calling it in non-VTOL modes.

**Comment by IamPete1** [comment]
closing in favour of https://github.com/ArduPilot/ardupilot/issues/9676
