### ISSUE TITLE
MAV_CMD_NAV_SPLINE_WAYPOINT is missing from Mission_Command::type()

### ISSUE THREAD

**Issue by tizianofiorenzani** [ArduPilot/ardupilot#11123]
### Bug report

**Issue details**
The type MAV_CMD_NAV_SPLINE_WAYPOINT  (82) is missing from the definitions in Mission_Command::type(): https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mission/AP_Mission.cpp#L1856

**Version**
master

**Platform**
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
SITL copter

**Hardware type**
SITL

**Logs**

**Comment by peterbarker** [comment]
Fixed in master.
