### ISSUE TITLE
Linker failures not reported when building in Eclipse on Windows

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#11141]
Sometimes when building AP on Windows using Eclipse ([setup as described here](http://ardupilot.org/dev/docs/building-setup-windows-eclipse.html)), we find that the final message at the end (see blue line in the image below) reports success even though the linker has failed.  This confuses the developer for a bit because they think it's all worked when it hasn't actually.
![image](https://user-images.githubusercontent.com/1498098/56331847-ec75b000-61c8-11e9-85fa-505be087bb17.png)

**Comment by IamPete1** [comment]
@rmackay9 is this still a issue?

**Comment by IamPete1** [comment]
Please re-open if this is still a issue.
