### ISSUE TITLE
Help! APM 2.8 elevator in RTH mode

### ISSUE THREAD

**Issue by letruong6006** [ArduPilot/ardupilot#11159]
I am using APM 2.8 circuit for X-UAV minitalon. In RTH mode, my plane increased dramatically to achieve a safe height value, the height increase is probably too large, so it tends to lose balance. What should I do to reduce the value of servo tail motor ??

**Comment by auturgy** [comment]
Please use the forum at discuss.ardupilot.org for user assistance.
This issues list is for confirmed bugs and feature requests
