### ISSUE TITLE
Plane - Enhanced RTL algorithm 

### ISSUE THREAD

**Issue by RMFPV** [ArduPilot/ardupilot#11180]
### Feature request

**Is your feature request related to a problem? Please describe.**

Problem with RTL can happen as most of the obstacles located aside of the flight pass, but not in the front usually! RTL starts to turn immediately towards home and can lead a plane into an obstacle, This happened to me couple of times.

**Describe the solution you'd like**

The solution is to first climb up to desired RTL alt while keeping current direction (straight forward), and after reaching RTL Alt start to turn home.

**Describe alternatives you've considered**
Can be made as an option.

**Platform**
[  ] Plane

**Comment by magicrub** [comment]
seems reasonable

**Comment by Hwurzburg** [comment]
Already PR posted to solve this #14371 ....tested and works well...
