### ISSUE TITLE
Gimbal: Low-Pass filter on gimbal

### ISSUE THREAD

**Issue by brandonkal** [ArduPilot/ardupilot#1121]
I need an option to have a low pass filter on gimbal output. I am using this output for control of 32bit alexmos brushless gimbal board.
That way the gimbal controller knows the frame angle but the problem is I have a ton of jitter on the gimbal outputs from the Pixhawk which is actually making the gimbal stabilization worse.

**Comment by wjax** [comment]
Hi

I see this is an old topic with no recent update. I wonder if anythig has been done or is planned.
We may see a new age of servo gimbals as they are great for NADIR images in photogrametry/survey flights.
We have one servo gimbal and with servos being so fast and accurate, it becomes a problem the lack of a low pass filter in APM servo output. Gombal movement becomes jerky.
As servos are directly commanded from APM sw, the only way to filter and smooth the movement is within APM code.

I guess it should not bee difficult to do. If anyone points me in the right direction I will try to do it myself.

Thanks
