### ISSUE TITLE
Matek f405-STD reboot in flight

### ISSUE THREAD

**Issue by kiryam** [ArduPilot/ardupilot#11271]
### Bug report

**Issue details**

I had crash today, it looks like reboot in flight.
Look at the video (17s) I just fly in CRUISE, after that video gone. After a few seconds video back, but no telemetry on osd. 

**Version**
3.10.0-dev (b1bc4268)

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
airplane

**Hardware type**
MATEK f405-STD

**Logs**
[00000001.BIN.txt](https://github.com/ArduPilot/ardupilot/files/3144841/00000001.BIN.txt)

https://youtu.be/2uI3km0nMs4

**Comment by kiryam** [comment]
I found that I have stalled sero on left wing. But it stalled in neutral position. Look like servo was stalled. Controller reboots and moved servo on the right wing up. after that I had a crush.

**Comment by fikusir** [comment]
Just happenedto me as well. Have you find the reason why it happened to you? Me not

**Comment by rmackay9** [comment]
@fikusir, 

reboots can happen for a few reasons - the most common is probably a power issue but recent versions of ArduPilot include an "[independent watchdog](https://ardupilot.org/plane/docs/common-watchdog.html)" that records a message in **the next log** after the flight that ended in a reboot.

If you had a telemetry connection you may also have seen "Watchdog" appear on the HUD or OSD.

So ideally it would be good to see the logs of the flight in question and the next log if possible.

**Comment by ValeraSokot** [comment]
Привет. У меня точно такая же проблема. Получилось ли тебе найти причину перезагрузки ?

**Comment by ValeraSokot** [comment]
https://www.youtube.com/watch?v=SIjuAKOhuOg&ab_channel=%D0%B2%D0%B0%D0%BB%D0%B5%D1%80%D0%B0%D1%88%D0%BE%D0%BA%D0%BE%D1%82

**Comment by kiryam** [comment]
@ValeraSokot I think problem was been with servo. It locks on max position -> current draws goes high -> power module overloaded.

**Comment by ValeraSokot** [comment]
так ты заменил серву и проблема ушла ?

**Comment by kiryam** [comment]
Sorry, I don't remember already.

**Comment by ValeraSokot** [comment]
Плохо конечно что не помниш , ладно спасибо буду искать дальше.
