### ISSUE TITLE
hwdef_bl: Use different board_id for different boards in ChibiOS Bootloader

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#11274]
### Feature request

**Is your feature request related to a problem? Please describe.**
Current state lots of boards share the same board_id, but it maybe cause them can't work well. Especially for new users.
![image](https://user-images.githubusercontent.com/4748411/57196651-79728480-6f91-11e9-9b00-aba61e1a10f3.png)
![image](https://user-images.githubusercontent.com/4748411/57197960-cbbaa200-6f9f-11e9-9888-53c6bb8cfa90.png)

**Describe the solution you'd like**
I think we should use different board id for different board that already listed in AP_HAL_ChibiOS, then GCSs might possible identify it. If not, may cause a lot of unexpected behaviors.

**Platform**
[√] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by bys1123** [comment]
cc'ing @DonLakeFlyer

**Comment by tridge** [comment]
Yes, a different board_id for each board would have been a good idea, but if we changed the board_id now then existing boards would not be able to accept the new firmware.
The fix we have in the ArduPilot bootloader is to encode the board name (like "Pixhawk4") in the bootloader string. That is a much better solution I think, as it is backwards compatible

**Comment by bys1123** [comment]
@tridge Sounds good! Thanks!
