### ISSUE TITLE
AP_OpticalFlow: only publish PX4FLOW data few frame to MP then stopped

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#11278]
#### Issue details

MP can only show the first frame from optical flow. But the log shows it works well.

#### Version
Copter-3.6.7~3.6.9

#### Platform
[  ] All
[  ] AntennaTracker
[√] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Hardware type
Pix32(Pixhawk), Pixhawk4

#### Logs

![image](https://user-images.githubusercontent.com/4748411/57179761-caac4680-6eb3-11e9-958c-44ad8d777d6a.png)

tlog:
https://www.dropbox.com/s/8mos4rk87wtbm38/2019-05-04%2021-15-39.tlog?dl=0
https://github.com/ArduPilot/MissionPlanner/issues/2141#issuecomment-489495783

other person have the same issue:
https://discuss.ardupilot.org/t/how-to-setup-and-check-optical-flow/20444/40

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/57585650-878a4d00-751d-11e9-832f-7fc91e58d77d.png)
![image](https://user-images.githubusercontent.com/4748411/57585654-8ce79780-751d-11e9-86ac-9182e63f75e9.png)
Tried CX-OF today, values of opt_* still not updating.

**Comment by bys1123** [comment]
This drone also can't get rangefinder's data.
But I tried on other drone, use same firmware and same hardware configuration, that works fine.
Is there a parameter control this?

**Comment by bys1123** [comment]
I think I found the reason, disconnect companion computer, then optical flow information will work.

**Comment by bys1123** [comment]
It's work now, what ever I connect companion or not.

**Comment by bys1123** [comment]
But ESC telemetry can't show the data now……

**Comment by bys1123** [comment]
The reason why it's not have optical flow status data reading because of I didn't connect rangefinder, I got output after I connect a VL53L1X lidar, Is this expected? @rmackay9

**Comment by rmackay9** [comment]
I think we've resolved this in Copter-4.0.0-rc1 (https://github.com/ArduPilot/ardupilot/pull/13182) so I'm going to close this if that's OK.  Happy to re-open if we find the issue persists.
