### ISSUE TITLE
Copter: Master logging fails consistently

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#11294]
With both a CUAV v5 and a mRov2.1-777 so both F7 boards, after a short time the logger starts failing (on Pre-Arm which would stop flying)

Just have a couple of previous large log files on the sd card, and the board after a while starts sending logging failures (note: both boards on the table with nothing connected but the usb cable)
<img width="507" alt="Screenshot 2019-05-07 at 14 16 40" src="https://user-images.githubusercontent.com/3130363/57302796-e0985200-70d3-11e9-83cd-ef827ef81b78.png">

example parameter file:

[mav.parm.txt](https://github.com/ArduPilot/ardupilot/files/3152817/mav.parm.txt)

@peterbarker @tridge This is the issue we've discussed.

I can replicate this easily every time - Using Master Copter-Heli

Example with MavProxy

<img width="583" alt="Screenshot 2019-05-07 at 19 58 51" src="https://user-images.githubusercontent.com/3130363/57325734-a09c9380-7102-11e9-95f8-c519cf55504e.png">

**Comment by Jaaaky** [comment]
Are using a high quality SD card?
If not, I recommend that you use high quality UHS-I SD card or better, then try again.

**Comment by Jaaaky** [comment]
If you're using proper SD card as recommended, can you try to adjust BRD_SD_SLOWDOWN and try again?
Try increasing the value up to 32.

**Comment by lvale** [comment]
@Jaaaky Thanks for the input, but those are the obvious points, but not on this situation.

**Comment by IamPete1** [comment]
@lvale any update?

**Comment by rmackay9** [comment]
We've done a lot of fixes to the logging system since this report.

**Comment by lvale** [comment]
Would need to try to replicate with next release

**Comment by IamPete1** [comment]
@lvale If you could test on 4.1 beta that would be great.

**Comment by lvale** [comment]
Don't promise

**Comment by IamPete1** [comment]
Please re-open if this is still a issue.
