### ISSUE TITLE
EKF Vertical Position and Velocity Errors on Arming Events

### ISSUE THREAD

**Issue by JamesMegariotis** [ArduPilot/ardupilot#11304]
### Bug report

**Issue details**

On first arming event after pixhawk reboot, there is a relatively large error in EKF vertical position and velocity estimates. I have found the issue in the Copter-3.6 branch but not in the Copter-3.5 branch. This issue has been discussed pretty extensively on the forum over the past few days and more than 1 person has verified this issue. See forum post here:
https://discuss.ardupilot.org/t/copter-ekf-altitude-estimation-error-due-to-heavy-uart-communication-load/41625

This issue cannot be replicated in sitl, so the prevailing theory is that it has something to do with datalogging and uart load. This issue is independent of RTOS version (present in both chibios and nuttx).

I have a theory that this is somehow related to a delay just after resetting the ekf reference height (most likely due to log file creation or the start of a log). If I add an additional delay in the Copter::init_motors_arm() function, just before the function returns, the errors become significantly larger. 

Also if I enable log while disarmed, the errors are smaller. So the magnitude of this error seems to be related to log creation. 

Below is a typical signature of what happens on arming. This image comes from a log where I just armed the vehicle on the ground but did not fly. Additional log images can be seen on the forum post as well as a log file.
![ekf_errors](https://user-images.githubusercontent.com/20626288/57380895-db8cde80-7177-11e9-8d88-cceff47bda74.PNG)

These ekf errors show up in fused altitude and climb rate while armed and sitting on the ground. This issue is independent of EKF type, since I have been able to replicate this on every arming using both EKF2 and EKF3.

It is also worth noting that all successive arming events, after the first, will exhibit smaller ekf errors in vertical position and velocity. These errors seem to increase in magnitude based on uart load. If UART load is minimal, these errors are very small or nonexistent.

And finally I have found that when retrieving logs, the EKF seems to go into an unrecoverable state when using EKF3. You see vertical pos variance errors and compass variance errors that are not resolved until the pixhawk is rebooted. I never noticed this issue when running Copter 3.5. The ekf seemed to be unaffected by log downloads on older versions.

More details can be found in the forum posts, and this may be just one symptom of a larger issue since the user that created the post experienced a different but seemingly related issue with the EKF's vertical estimates.

**Version**
Copter-3.6

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Hexacopter, Octacopter, and should affect other frame types as well

**Hardware type**
Pixhawk 2.1

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by pompecukor** [comment]
Finally someone else is seeing this and seems to have some explanation. We are getting similar on Master of Plane too for almost 6 months now.
Typically after sitting on the ground for a while and trying to arm we get one of these. The number and the axis is different everytime.
"PreArm: EKF3 Yaw inconsistent by 30 deg". or "PreArm: EKF3 Pitch inconsistent by 45 deg".
All it takes to fix the issue is a reboot/re-power. After that the issue is gone. This happens on almost every cold start.
I have sent logs in the past to Trigdell, but was unable to find the issue.
