### ISSUE TITLE
Cube Cannot bind Spektrum satellite receiver in plane and copter 

### ISSUE THREAD

**Issue by Autonomost** [ArduPilot/ardupilot#11306]
#### Issue details
I cannot initiate bind on ChibiOS using a spektrum Satellite

#### Version
Copter 3.6.8 
Plane 3.9.8

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Raw autopilot

#### Hardware type
Cube Black 

#### Logs
I don't know how to show logs for the bind procedure. If someone lets me know I can get that.

**Comment by WickedShell** [comment]
There have been a couple rounds of fixing/breaking of this. Last I tested on 4.0 it was working, and I believe I tested one of the recent PR's that had to do with this, so I'm going to close this as resolved, if it's still an issue on master then we can address it again.
