### ISSUE TITLE
Rover: Log_Write_Nav_Tuning should log wp_bearing and nav_bearing in degrees

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#11312]
This issue was raised as part of this PR: https://github.com/ArduPilot/ardupilot/pull/11283

**Comment by harshitsankhla** [comment]
Working on it now !

**Comment by rishabsingh3003** [comment]
@rmackay9 This issue can now be closed since #13162 was merged.

**Comment by rmackay9** [comment]
Ah great, closed, txs!
