### ISSUE TITLE
Copter: add support for UPIXELS UP-Flow optical flow sensor

### ISSUE THREAD

**Issue by FLYBYME** [ArduPilot/ardupilot#11328]
### Feature request

I would like to officiously request support for the "UPIXELS UP-Flow sensor"
https://www.aliexpress.com/item/UPIXELS-UP-FLOW-Optical-Flow-Module-FPV-Drone-Hovering-Altitude-Hold-Control-Optical-Flow-Sensor-For/32969297064.html

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Comment by auturgy** [comment]
If someone picks this up: data format is posted in the forum https://discuss.ardupilot.org/t/cheerson-cx-of-low-cost-optical-flow-sensor-testing/35598/90

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/69854535-50666800-12c4-11ea-80bc-7ddc36c5f648.png)
![image](https://user-images.githubusercontent.com/4748411/69854563-5b20fd00-12c4-11ea-9fa4-beb81dff9bf7.png)

**Comment by rmackay9** [comment]
support added to master with PR https://github.com/ArduPilot/ardupilot/pull/16883 so closing.  txs!
