### ISSUE TITLE
Add RNGFND_ENABLE param

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/ardupilot#11326]
### Feature request
There are tens of params that are related to RNGFND - counting over 170 now on master arduplane - which is a secondary feature not usually enabled. It's alone about 20% of total default params!

**Describe the solution you'd like**
_So please add RNGFND_ENABLE param like BTN_ENABLE or EK?_ENABLE which activates underneath params only if enabled.._

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment]
Duplicate: #10502 #4599
