### ISSUE TITLE
Blue Robotics Ping sensor initialization

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#11345]
The device always boots in 'auto' mode and takes measurements at a fixed frequency (not sure what that is, maybe 2Hz). The measurement frequency must be manually adjusted (if desired).

A parameter may be appropriate, or we can decide what the appropriate default/static value is.

attention @patrickelectric

**Comment by patrickelectric** [comment]
Should this be in bluerobotics/ping-firmware repository ?
This issue does not describe an autopilot behavior and such configuration does not exist for the sensor.

**Comment by rmackay9** [comment]
I've closed this assuming patrick is right but we can always re-open if necessary
