### ISSUE TITLE
copter 3.6.8 Zed-f9p gps time error

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#11350]
hello,

Trying to make z9p work in UBX, position and vel is ok, but GPS Time Fail….

This is due to that is not possible to activate SOL msg, so I tryed with GPS TIME and GPS UTC, but no work.

Maybe you can update this on next minor release?

Also when using it in NMEA there is also errors on GPS time….and EK2 need 3D vel to good work. So NMEA is not useable.

**Comment by hdtechk** [comment]
There is an open PR to fix this already #10951

**Comment by roque-canales** [comment]
Randy does this enhancement is already fixed?
If not, can it be added to minor release ?

**Comment by peterbarker** [comment]
These units should work fine on our current stable and master branches.  Please open a new issue if they are not.
