### ISSUE TITLE
Support Holybro Kakute F7 mini SPI Flash (Blackbox)

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#11380]
### Feature request

Holybro just release their new FC, Kakute F7 mini, it's using a 16MB (128Mbit) SPI flash instead of TF card.
https://shop.holybro.com/kakute-f7-mini_p1133.html

**Platform**
[√] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
flash model: W25Q128FVSIG
SPI pin:
![image](https://user-images.githubusercontent.com/4748411/58000198-a636a800-7b0a-11e9-900c-dfba23cc0396.png)

**Comment by maroquio** [comment]
Would be awesome to have this feature enabled. Kakute F7 Mini is 4g weight and have a lot of features. I always got “Bad logging” when flying my under 250g drone, and I think it is something related to the sd-card. With an internal memory, I think this error would be gone.

**Comment by R-Lefebvre** [comment]
Closing issue as logging appears to be working in Master now.
