### ISSUE TITLE
Pixhawk1 or fmuv2 can not run.

### ISSUE THREAD

**Issue by LeiOuYang** [ArduPilot/ardupilot#11428]
### Bug report

**Issue details**
Eclipse and waf bulid the code(base the python3.6m).Pargram can not run: The led of F427 always flashing.

**Version**
Copter3.7.0-dev

**Hardware type**
Pixhawk1

**Comment by rmackay9** [comment]
Looks like a developer question so feel free to ask in the [developer gitter chat room](https://gitter.im/ArduPilot/ardupilot).

**Comment by LeiOuYang** [comment]
OK！Thank you!

**Comment by LeiOuYang** [comment]
> 
> 
> Looks like a developer question so feel free to ask in the [developer gitter chat room](https://gitter.im/ArduPilot/ardupilot).

OK! Thank you!
