### ISSUE TITLE
Matek F405-CTR FrSky telemetry does not work

### ISSUE THREAD

**Issue by twistedwings** [ArduPilot/ardupilot#11431]
ArduCopter 3.7.0

inverted S.Port (A/B) from XSR connected to Tx3/Rx3
![image](https://user-images.githubusercontent.com/562809/58512769-2d84bb00-819e-11e9-9514-03003e0d91db.png)

SERIAL1_BAUD 57
SERIAL1_OPTIONS 4
SERIAL1_PROTOCOL 4

No sensors discovered

Also tried Tx5/Rx5

**Comment by IamPete1** [comment]
You also need a diode to convert from half duplex to full, and you don't have to discover sensors. This is the best place to get help setting it up, https://discuss.ardupilot.org/t/some-soldering-required/27613

**Comment by twistedwings** [comment]
Why do I need a diode if halfduplex (SERIAL1_PROTOCOL 4) is configured?
The same configuration works perfect on a F405-Wing.
