### ISSUE TITLE
Firmware copter stop working on fmuv2

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#11455]
### Bug report

**Issue details**

This commit break fmuv2 : https://github.com/ArduPilot/ardupilot/pull/11319

**Version**
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
tested on pixhawk 1
**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
We had someone on the forum who was also having problems with fmuv2 - although @peterbarker couldn't reproduce.

**Comment by rmackay9** [comment]
I think this applies to master only and not Copter-3.6 but please tell me if I'm wrong (I'm in Tokyo this morning so can't immediately check myself)

**Comment by khancyr** [comment]
Yep master only, all release seems fine. I didn't try other vehicles but it will failed to.
It need a waf clean to fail.

**Comment by tridge** [comment]
@khancyr when you say "break" what do you mean? What are the exact symptoms.
I tested it on a Pixhawk1 here and it works fine.
Can you also please try changing the timing of it, specifically there are two loops in peripheral_power_enable(). If you increase the loop counts does it fix it?

**Comment by khancyr** [comment]
Did you clean the build first ?
Here is a video of what I got : 
https://youtu.be/OaRhmEQchYU
I will try later to change the timing

**Comment by tridge** [comment]
video link doesn't work.
Can you describe the error?

**Comment by tridge** [comment]
it may also matter what bootloader you have, and how you are powering. Can you describe those please?

**Comment by khancyr** [comment]
hello,
The error is that the boad keep disconnecting. Bootloader is accessible but the firmware doesn't start. On the pixhawk1 the orange led on FMU side keep blinking.
The bootloader is the one for pixhawk1.
The board is powered directly by usb, and got no periferical.

**Comment by rmackay9** [comment]
I uploaded Copter master for fmuv2 to my regular desktop pixhawk1 and it worked.  It was a bit odd immediately after the upload in that after the board rebooted the gyro calibration failed but once rebooted once more it seemed to work.

**Comment by khancyr** [comment]
@tridge @rmackay9 you got 3dr pixhawk 1, right? Mine is a chinese one's ... I guess I have another one from china, I will test

**Comment by peterbarker** [comment]
On Tue, 4 Jun 2019, Pierre Kancir wrote:

> @tridge @rmackay9 you got 3dr pixhawk 1, right? Mine is a chinese one's ... I guess I have another one from china, I will test

I'm guessing minor hardware differences.... "nobody could possibly need 
these components, works fine without them...."

**Comment by robustini** [comment]
I've exactly the same problem with a chinese Pixhawk that from the box looks exactly the same in my hands.
Flashed from the Planner with Plane 3.9.8 (fmuv2) no issue, flashed from the latest precompiled firmware on "Ardupilot Firmware" and it doesn't boot.
When I try to flash the .apj the Planner asks me if the board is a Solo, obviously I say no, flash and then zero activity, then the board is recognized with another COM and the firmware doesn't boot.
To solve this here it is enough to flash 3.9.8 Plane release and no problem.
And now?

**Comment by tridge** [comment]
@khancyr please test this PR and see if it fixes it for you:
https://github.com/ArduPilot/ardupilot/pull/11538

**Comment by robustini** [comment]
I'm sorry @tridge , false positive, seemed to work but after a reboot from the same problem.
