### ISSUE TITLE
External AHRS integration into EKF

### ISSUE THREAD

**Issue by Kiwa21** [ArduPilot/ardupilot#11479]
### Feature request

**Is your feature request related to a problem? Please describe.**
Attitude estimation with "cheap" sensors found in most of the market autopilots might sometimes be a trouble for high end vehicle integration. 

**Describe the solution you'd like**
I want to be able to use an external AHRS to provide euler angles (pitch, roll, yaw) / quaterions to the Ardupilot EKF.

**Describe alternatives you've considered**
There is already one attempt to use an external high end VecotrNav INS here: 
https://github.com/ArduPilot/ardupilot/pull/5459

And a IMU-F branch from Tridge doing kind of the same thing : 
https://github.com/tridge/ardupilot/commit/5f5211fbc679913259247332c1a5ca08d7860e4a
https://discuss.ardupilot.org/t/helio-spring-imu-f/29646/27

Using a full external INS would be interesting as well but I'm not sure how it can cope with the others sensors usable in the EKF (rangefinder, beacon, ...) that I want to keep.

@WickedShell @tridge : do you have any suggestions about how it should done ?
We would like to implement this in master, so it would be easier/faster if core devs could pinpoint what/how the would like to have this.

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by amilcarlucas** [comment]
Master has this now

**Comment by Tdoe4321** [comment]
> Master has this now

Is there a reference as to how to do this? I am looking at trying to integrate a beefy IMU into an ardusub system.

**Comment by rmackay9** [comment]
@Tdoe4321,

We don't have any wiki docs yet but when we do they should appear here: https://ardupilot.org/copter/docs/common-master-features.html

The connection with the external ahrs system needs to be using a serial cable and the relevant parameters start with EAHRS_ in case that helps.

**Comment by tridge** [comment]
@Tdoe4321 the code is here: https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_ExternalAHRS
it now supports adding new backends. Currently UART only, but CAN is planned

**Comment by lebarsfa** [comment]
FYI, I just made a ROS node https://github.com/ENSTABretagneRobotics/ardupilot2ros that should be able to convert `/imu/data` and `/navsat/fix` typical ROS messages (e.g. from AHRS/INS like SBG Ellipse and others) to the VectorNav protocol read by ArduPilot. 
In addition, it turns out that we can also use `SERVO_OUTPUT_RAW` MAVLink messages from ArduPilot to generate `/cmd_vel` typical ROS messages, so it could be a quick way to test/use ArduPilot ecosystem (without hardware modification if we use an SITL ArduPilot firmware) on ROS-based robots such as some from Clearpath Robotics and others.

**Comment by Ryanf55** [comment]
I'd like to consider re-opening this issue. I do not believe the implementation done actually meets this design request:
`I want to be able to use an external AHRS to provide euler angles (pitch, roll, yaw) / quaterions to the Ardupilot EKF.`

The implementation right now replaces the ArduPilot EKF with the external one. [If the external](https://ardupilot.org/copter/docs/parameters.html#ahrs-ekf-type-use-navekf-kalman-filter-for-attitude-and-position-estimation) is an enum, not a bitfield. The EAHRS data is not combined with any other data, and if EAHRS fails, then it appears ArduPilot falls back to DCM.

**Comment by ES-Alexander** [comment]
> The implementation right now replaces the ArduPilot EKF with the external one.

That does seem to be the default expectation, but seemingly it's also possible to have a partial integration, like when VectorNav is [used as a sensor set](https://ardupilot.org/sub/docs/common-external-ahrs-vectornav.html#use-as-an-external-sensor-set) (rather than a full AHRS replacement)?
