### ISSUE TITLE
Copter: actived autotune in Loiter mode, but it's Althold after autotune finish

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#11478]
### Bug report

**Issue details**

I'm very glad autotune can active in loiter and position mode. Makes it easy to control and friendly for newbies not good at RC control.

So, I tried to autotune all my drones these days. But I notice that it always back to Althold mode after autotune finish. If switch RC7 to low, then it's back to loiter, switch RC7 to high, it's althold again. Autotune also need to land while RC7 keep high to save parameters, but it's hard to land without GPS assist sometime especially for newbies.
Also it's different flight mode between the two positions, so can't compare the control feels between the two parameters.

It's 100% reproduce in my experience.

I only tune one axis each time, if it's relevant.

**Version**
3.7.0-dev

**Platform**
[  ] All
[  ] AntennaTracker
[√] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X4

**Hardware type**
Pixhawk4

**Log**
https://www.dropbox.com/s/xcgdkypnnqo0quw/2019-05-28%2019-50-29.bin?dl=0

**Comment by peterbarker** [comment]
Sorry, this is very out-of-date.

We haven't supported autotune in loiter mode for many years.

Closing this one.
