### ISSUE TITLE
Plane: Elevon jitter on the ground when throttle up, but only in FBWA and with throttle disarmed

### ISSUE THREAD

**Issue by cheintz** [ArduPilot/ardupilot#11490]
### Bug report

With my plane on the ground and safety-switch turned, on, I see elevon jitter under the following (combined) conditions:

Mode: FBWA
Throttle: disarmed
Throttle stick: Above 0%

Changing any of those makes the jitter go away. I have the ESC unplugged for this log, though the symptoms are the same with it plugged in.

The log includes various sequences of control movements and mode changes that demonstrate the problem

I have a very similar airframe running 3.9.5 that exhibits similar symptoms that are not as severe(logs and config attached)

**Version**
3.9.8, 3.9.5

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Flying Wing

**Hardware type**
PX4

**Logs**

[Elevon Jitter Log.zip](https://github.com/ArduPilot/ardupilot/files/3251076/Elevon.Jitter.Log.zip)

**Comment by magicrub** [comment]
Thanks for the log, I'll take a look

**Comment by tridge** [comment]
this is fixed now in master
please re-open this issue if you can still produce on master
