### ISSUE TITLE
Do_Set_Cam_Trigg_Dist command, wrong distance between photos

### ISSUE THREAD

**Issue by buckker** [ArduPilot/ardupilot#11505]
I posted this issue a few month ago here: https://discuss.ardupilot.org/t/wrong-distance-between-photos-do-set-cam-trigg-dist/40596

I still have no solution for this behaviour. 

Sometimes I thought the bug is flying speed related. Lower flying speed=>higher number of trigger commands. But this evening I reduce the flying speed from 6.75m/s to 6m/s and the trigger commands are lower that with higher flying speed.
So, there must be somewhere a bug. 

I use Arducopter 3.6.8

Here is a example: target number of photos according to mission planner is 292, effectively triggered photos 271.

![soll 3ha](https://user-images.githubusercontent.com/7835537/59048329-df4e7680-8885-11e9-9043-f31396d96d51.jpg)
![ist 3ha](https://user-images.githubusercontent.com/7835537/59048336-e1b0d080-8885-11e9-85d2-4cf239991c6a.jpg)

I also did some test flights with another mission, only changing the flight speed. target number of photos is 181. effectively triggerd photos:
with 6.75m/s 156 photos
with 6.5m/s 161 photos
with 6.0m/s 152 photos

How does arducopter calculate the distance between the triggered photos? Is there maybe an issue with the refresh rate from the gps signal?

**Comment by Naterater** [comment]
Provide logs. Are you considering "triggered" photos, or just actual photos? Sometimes it's a camera issue, not an autopilot issue. Do you have shutter feedback?

**Comment by buckker** [comment]
To be more precise, I don't use a photo camera. I use the signal to controll a servo and drop some small balls into the field for an agriculture project. I double checked if mission planner match the effectively dropped ball count. It match perfectly (Mission Planner last photo No. 127, I filled 130 balls to the container, after the flight 3 pcs were left)

**Comment by IamPete1** [comment]
I think this is just a issue with the difference between the mission distance and the copter actually flys, we cut the corners slightly so you end up flying a slightly shorter distance and thus end up with a few less triggers. The faster you fly the more the corners are cut so the shorter distance you fly and end with a few less triggers. 

You could improve this slightly by setting a short delay at each way-point, this will force the copter to got to it and not cut the corner. 

Or you could have a waypoint for each location and use a `DO_SET_RELAY` for the trigger.
