### ISSUE TITLE
Copter: add indoor mode to disable GPS (and maybe compass).

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#1152]
Often time, people would like to fly indoors, possibly for testing, or during the winter.  This can cause problems due to GPS reception.  Users may forget to turn off Fence, or accidentally try going into Auto, etc.  And, even if they do remember and only use Acro or Stabilize mode, the AHRS can be confused by large possible GPS glitches (due to AHRS_GPS_USE).  

Also, flying in some structures may cause problems with the compass.

The only bulletproof cure at this point is to disconnect the GPS physically.  It would be nice to provide a Master GPS Switch parameter which could easily have the same effect.

**Comment by R-Lefebvre** [comment]
Randy, can this be closed?  I'm not sure if it's done, but I'm sure there are newer issues written?

**Comment by OXINARF** [comment]
Is this something we still want to do? I think current modes work well enough inside that we don't need a specific mode for it.

**Comment by Naterater** [comment]
I don't think this is something that's worth it. Stabilize mode can do it almost on its own, and parameter changes can assist when indoor flights are planned. In addition, nobody has answered @OXINARF that this is something that is wanted.

**Comment by rmackay9** [comment]
Copter-3.7.0-dev includes a "GPS Disable" auxiliary switch which probably resolves this issue although it was intended for testing the EKF failsafe I think

**Comment by peterbarker** [comment]
On Thu, 17 Jan 2019, Nathan E wrote:

> Closed #1152.

You can put disable-gps on a switch now.
