### ISSUE TITLE
Blended GPS with two CAN devices: bad HDOP

### ISSUE THREAD

**Issue by yak-54** [ArduPilot/ardupilot#11541]
I am using plane 3.9.8 with 2 here2 gps on Can1 and Can2
if i try to arm it i get

PreArm: GPS Hoop 655.3 ( Needs 2.5 ) and it will not arm

i swapped it back to serial cables and the plane now arms so its must be can bus issue

Well after a week i think i found it  some of you may have to look into it
before i had 2 x Here2 gps on he serial ports so i had them setup as Blend armed fine.
so i left it on blend gps for Here2 gps on the can bus will not arm all i get is PreArm: GPS Hoop 655.3 ( Needs 2.5 )
so i set it to use best gps bingo starts to work on Can-bus now the plane Arms

so answer don’t use Blend gps if using 2 x Here2 gps units on the Can-bus

**Version**
3.9.8

**Platform**
Plane 

**Airframe type**
 fixed wing V-tail Plane

**Hardware type**
The Cube with 2 x Here2 Gps 1 x airspeed on i2c and one external led i2c 

i did look if it had been reported on github i can fine it

**Comment by WickedShell** [comment]
Here2 doesn't send HDOP/VDOP estimates through currently, so the values maxed out for that. This isn't a flaw with blending, it's just a missing feature in the GPS firmware (which isn't provided by ArduPilot). For now use these in serial mode instead if you want to do blending.
