### ISSUE TITLE
Rover: populate PIDA.Act and PIDS.Act dataflash log values

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#11542]
Rover logs the outputs of the Speed controller as PIDA and the Turn Rate controller as PIDS.  For both, the "Act" field is always left at zero.  We should populate these values with the actual speed or turn rate using the AC_PID object's set_actual_rate() method.

- For the speed controller we should [add the line right here in AR_AttitudeControl.cpp](https://github.com/ArduPilot/ardupilot/blob/master/libraries/APM_Control/AR_AttitudeControl.cpp#L469).
- for the turn-rate controller we should [add the line right here in AR_AttitudeControl.cpp](https://github.com/ArduPilot/ardupilot/blob/master/libraries/APM_Control/AR_AttitudeControl.cpp#L364).

**Comment by vishal-raj15** [comment]
hello @rmackay9  i am interested in working in this issue .
but i dont have any idea about solving this issue can help me .

**Comment by rishabsingh3003** [comment]
I believe this issue was fixed somehow down the line...

![image](https://user-images.githubusercontent.com/36970042/78589857-80b7a780-785e-11ea-8ded-d823310b67d5.png)

**Comment by rmackay9** [comment]
@rishabsingh3003, awesome, thanks!
