### ISSUE TITLE
AntennaTracker moves when disarmed if using continuous rotation servos

### ISSUE THREAD

**Issue by votingprawn** [ArduPilot/ardupilot#11575]
#### Issue details
Stop mode and Disarming the tracker appear to halt both servo outputs at their current PWM value.  This makes sense for standard position servos, but with continuous rotation servos the tracker continues to rotate.  The only way to stop the movement is to override the servo positions, e.g. using the extended tuning test window.

#### Version
AntennaTracker V1.1.0-rc1

#### Platform
[  ] All
[X] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Antenna tracker

#### Hardware type
Navio2

**Comment by Evan1010** [comment]
I had been wondering about this behavior, and thought that I was the only one dealing with it.

For the record, I was using the [PT2645-S](https://www.servocity.com/pt2645-s-pan-tilt) from ServoCity.

This pan tilt assembly uses continuous rotation servos for both yaw and pitch, with pitch runaway being lethal to the tracker . . .

This behavior was present in 1.0, I am still building out a tracker on 1.1-rc1. I was using a Pixhawk 1 from mRobotics at the time.
