### ISSUE TITLE
The aggressive switch into LAND Mode is back!

### ISSUE THREAD

**Issue by wasserwiesel** [ArduPilot/ardupilot#11588]
#### Issue details
Unfortunately, I’ve just found out that the Copter stops far too aggressive when flying in Loiter mode and switch into Land mode. This has already been fixed in version 3.6.7 under NuttX. Was this forgotten when switching to chibiOS?

#### Version
3.6.9

#### Platform
[ ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
X4

#### Hardware type
ardupilot on pixhawk 4

#### Logs
I think that's not necessary because the problem has already been fixed in an earlier version with nuttX

**Comment by rmackay9** [comment]
@wasserwiesel, from a vehicle code point of view (the part of the code that controls stopping behaviour), there's really no difference between the NuttX and ChibiOS versions.  The vehicle should fly the same on either OS.
