### ISSUE TITLE
Arducopter crashes regularly

### ISSUE THREAD

**Issue by rishab26201** [ArduPilot/ardupilot#11628]
Hey,
So I arm and take off the drone. But it goes above the given setpoint and crashes. Even if it doesn't it keeps oscillating (+/-2 m) and is very unstable. Is there any way to correct this. Also for thrust input of 0.5 from setpoint_raw/attitude the drone moves sideways even though I dont give roll or yaw. Is there any way to correct this

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
