### ISSUE TITLE
Can't select CCPM and Flybarless for RadioLink Mini Pix and Omnibus F4 Pro V2 in Mission Planner 1.3.68 build 1.3.7109.24799 + firmware 3.6.9 

### ISSUE THREAD

**Issue by jerrywoodz** [ArduPilot/ardupilot#11631]
Can't select CCPM and Flybarless for RadioLink Mini Pix and Omnibus F4 Pro V2 in Mission Planner 1.3.68 build 1.3.7109.24799 + firmware 3.6.9 

Please go to Heli Setup page, then, the check nox of CCPM and Flybarless  can't be checked

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
