### ISSUE TITLE
Copter:  Compass not detected on OmnibusF7V2.

### ISSUE THREAD

**Issue by ninja-zx11** [ArduPilot/ardupilot#11636]
OmnibusF7V2 running latest` Arducopter 3.7.0-FIRMWARE_VERSION_TYPE_DEV`

1)Drotek GPS+HMC5883 combo Compass is not detected.Its wired to SCL/TX3 and SDA/RX3 pads of the omnibusF7V2.UART3 is shared with I2C . SCL/TX3 connected to PB10 and SDA/RX3 connected to PB11 pin of the MCU.

**Comment by ninja-zx11** [comment]
Solved;Needed 2.2k pullups on I2C.

**Comment by st0rfrasarn** [comment]
Hi,

How did you manage the pullups? Is physical resistors you are talking about or internal? I have the same problem. Maybe you could explain how you did? 

Thanks! :)

**Comment by st0rfrasarn** [comment]
Ok, i soldered 2.2 pullups to SDA/SCL. Compass is still sketchy. But i am talking about the internal compass. Is your internal compass working?

**Comment by ninja-zx11** [comment]
Genuine HMC5883 compass is working fine. You may have bad clone compass chip as these days market is full of clones.

**Comment by ninja-zx11** [comment]
> Ok, i soldered 2.2 pullups to SDA/SCL. Compass is still sketchy. But i am talking about the internal compass. Is your internal compass working?

There is no internal compass on OmnibusF7V2.

**Comment by st0rfrasarn** [comment]
aha. thats why. i swear i read somewhere it has internal compass. ok problem solved. thanks!
