### ISSUE TITLE
FLTMODE_CH on Copter V3.2.1?

### ISSUE THREAD

**Issue by CrazyProfessor** [ArduPilot/ardupilot#11649]
Hello there, 
Is it possible to add the FLTMODE_CH to Copter V3.2.1? The flight controller I have will not allow me to flash 3.6 where the FLTMODE_CH parameter was added. I have recently moved to ppm and now unable to have the three position switch controlling the flight modes. My HiTec TX is unable to map the switches to other RX Channels. Thank You. CP

**Comment by WickedShell** [comment]
We only backport to the most recent stable release. Presumably the reason for wanting Copter 3.2 is due to using APM 2.X hardware which is no longer supported.
