### ISSUE TITLE
how add a new library to support a selfmade sensor? the right procedure

### ISSUE THREAD

**Issue by lmy568** [ArduPilot/ardupilot#11651]
#### Issue details
while i write a whole new library .cpp and .h to surppot a new sensor made by myself, how can i add a new library to ardupilot?  (i had read the development document of ardupilot, but found nothing about how to add a new library, there just add a new module), can someone help me about the right procedure to add a new library? thanks very much.

#### Version
rover 3.5

#### Platform
Rover

#### Airframe type
skid rover

#### Hardware type
pixhawk1

#### Logs

Build failed
 -> task in 'objs/AP_pol' failed (exit status 1): 
	{task 140028295433344: cxx AP_pol.cpp -> AP_pol.cpp.0.o}
 (run with -v to display more information)

**Comment by rmackay9** [comment]
This is really a development question so I will close this.

There is a bit of info at the bottom of [this wiki page](http://ardupilot.org/dev/docs/code-overview-sensor-drivers.html#additional-advice) which suggests adding the library to the [wsript file](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/wscript) is required.  The library's .h file will also need to be [included in Rover.h](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/Rover.h#L24)
