### ISSUE TITLE
Compass BMM150 not detected By firmware

### ISSUE THREAD

**Issue by Vkd4U2NtVkZOVg** [ArduPilot/ardupilot#11658]
### BUG Report
Pixhawk 2.4.6 running Arducopter 3.6.9

BMM150 is not detected, I check the IIC bus with usb analyzer, The FC is not communicate with the BMM150(IIC Address:0x10)

I am not familiar with the code, but after I add
 `    FOREACH_I2C_EXTERNAL(i){
        ADD_BACKEND(DRIVER_BMM150,
                    AP_Compass_BMM150::probe(GET_I2C_DEVICE(i, 0x10)));
    }`
at /ardupilot/libraries/AP_Compass/AP_Compass.cpp, Line: 634. the BMM150 is detected, and it works.
I hope you guys can check is again.
regaards
XinCheng

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/16076
