### ISSUE TITLE
Reverse possition assist (motor trust) not working on quadplane while it is in any Copter-mode.

### ISSUE THREAD

**Issue by pompecukor** [ArduPilot/ardupilot#11650]
### Bug report

According to the Wiki reverse assist should work, just as forward. This is not the case.

While forward assist works fine. We have tested and found that motor assist backward does not function in quad mode. No matter how we set it up. Also is not implemented in SITL either.

I can imagine that very few would ever try this as it need reverse trust capable ESC on the pusher motor of a traditional VTOL fixed-wing.

**Version**
Lastest master

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Any (none-tilt rotor) VTOL airplane

Revers trust is setup correctly on the plane. It functions during fixed wing flights. However when in Quadmode, the only time we get assist is if pushing forward. Motors never spin reverse no matter how we try to fly backwards.

We tried "Use_reverse" = "always" even. No matter how much gain we put on Q_WVANE_GAIN.

WIKI: 
![image](https://user-images.githubusercontent.com/31744367/60025421-e1903d80-9699-11e9-952d-669d4ad181fd.png)

**Comment by IamPete1** [comment]
Yep, its not allowed

https://github.com/ArduPilot/ardupilot/blob/659286ee4fe3895e164e2110f23be715e60e941c/ArduPlane/quadplane.cpp#L3230-L3232

The question is should we allow it or update the wiki?

**Comment by peterbarker** [comment]
Marked for DevCallEU to decide whether we should update the Wiki or the code.

**Comment by tridge** [comment]
I think this should be able to work, although usually you would weathervane nose into the wind so this would not normally be needed.

**Comment by tridge** [comment]
@Hwurzburg let's fix wiki now to say this doesn't work (or remove the text saying it does work) then if/when we fix it we can update again

**Comment by Hwurzburg** [comment]
done
