### ISSUE TITLE
FC reboot when trying to arm

### ISSUE THREAD

**Issue by lezabour** [ArduPilot/ardupilot#11701]
Hi,

**Issue details**

I have a Omnibus F4 v3 and flash with last version of arducopter.
Everything seams good,  i have done the ESC calibration, compass, accel, level, radio etc. 

**But when trying to arm, the board reboot.**
I hear the ESC make their usual noise to say "ready" (same noise as when you plug your lipo).
It does that not matter if i’m also connected with USB or not (FC reboot each time i try to arm)
Battery is fully charge (3S)

note1: i have desactivate all ARM check - 0 - and voltage check disable, so normally should arm without problem
note2: when is use mission planner to test motor, they all work perfectly…

Really don’t know what to do if anyone have an idea

**Version**
3.6.9

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
ZMR250

**Hardware type**
Omnibus F4 pro v3 (aliexpress clone)

**Comment by khancyr** [comment]
Hello,
Please don't disable arming check ....ever ! Disabling them won't solve any problem but make them harder to identify.

This is the bug tracker for code issues. It is more likely that you have something wrong on your configuration, so you will need to open a post on discuss https://discuss.ardupilot.org 

First step is then to enable back the arming check and check that they pass.
Step two will be to enable LOG_disarm, reboot the board and try to arm. Then could you provide us the dataflash log (the log from the sd card) And we should be able to spot what is wrong .
