### ISSUE TITLE
Add sensor thermal calibration

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#11703]
https://docs.px4.io/en/advanced_config/sensor_thermal_calibration.html

Hello, instead of heat imu, PX4 has dev thermal sensor calibration.

It can be very usefull feature for those who need to take off from boat or other complex scenarios.

**Comment by khancyr** [comment]
It should be pretty simple to implement it with logging like we do with Notch filter.

But currently, I think it is better to invest in a board with temperature controled IMU, it shouldn't pose problem.

**Comment by WickedShell** [comment]
Closing as this has mostly been done in #16262. I'm sure we might extend some of the sensor options in the future, but the core ones are done now.
