### ISSUE TITLE
RevoMini wrong IMU rotation on hwdef.dat

### ISSUE THREAD

**Issue by anbello** [ArduPilot/ardupilot#11743]
### Bug report

**Issue details**

After [this](https://github.com/ArduPilot/ardupilot/commit/614a059819855f217b0a5ad111c549fccac06236#diff-11d8dd1fa26a0cff3376c94acb0fd570) commit the IMU has a wrong orientation in hwdef.dat, this line:
`IMU Invensense SPI:mpu6000 ROTATION_YAW_90`
should be:
`IMU Invensense SPI:mpu6000 ROTATION_YAW_180`

**Version**
master

**Platform**
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
I tested on X quadcopter

**Hardware type**
RevoMini

**Logs**

**Comment by anbello** [comment]
I did a PR for this:
https://github.com/ArduPilot/ardupilot/pull/11744

**Comment by vierfuffzig** [comment]
thanks andrea, fix is merged, so closing this.
