### ISSUE TITLE
Z9P Copter 3.6.10rc1 setup

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#11764]
Hello,

First : How to activate Z9P autoconfiguration?
Second: for those who want to self setup Z9P modules, Could you please tell wich ubx message are needed and at how many HZ for each?

Thank you so much.

**Comment by rmackay9** [comment]
@roque-canales, I'm afraid I don't know the answer to this but I assume that the auto config works automatically just like it does for the M8 uBlox so there should be no extra setup required though uCenter.

**Comment by peterbarker** [comment]
@roque-canales as @rmackay9 hints, these should just-work.

Please reopen this if you have issues on the current stable or master branches.
