### ISSUE TITLE
AP_Mission: Log mission plan to .bin

### ISSUE THREAD

**Issue by JoshWelsh** [ArduPilot/ardupilot#1181]
Request for adding mission details (including any in-flight mission changes) to .bin file.  Alternatively one thought was writing to mission.txt but the concern is that when the user posts their log (1.bin, etc) they may not post mission.txt.

Goal is to be able to evaluate mission details as a part of a log where something went wrong.

**Comment by WickedShell** [comment]
Missions are logged to bins (have been for a bit, I forget when this went in)
