### ISSUE TITLE
Tools: param_parse script does not build files with all params

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#11819]
### Bug report

param_parse does not build all parameters into html file

ex: OSDx_VSPEED, _WIND, etc params are not built but others are

**Version**
Master
**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment]
`param_parse.py` works correctly, The formatting of the comments on `VSPEED` and `WIND` are wrong.

This is wrong:
```
    //@Group: VSPEED    
    //@Path: AP_OSD_Setting.cpp    
    AP_SUBGROUPINFO(vspeed, "VSPEED", 20, AP_OSD_Screen, AP_OSD_Setting),
```

This is correct:
```
    // @Group: VSPEED                                                                                                                                    
    // @Path: AP_OSD_Setting.cpp   
    AP_SUBGROUPINFO(vspeed, "VSPEED", 20, AP_OSD_Screen, AP_OSD_Setting),
```

Note the space between `//` and `@`

**Comment by khancyr** [comment]
We should catch this and make it an error in param_parse.py !

**Comment by Hwurzburg** [comment]
Since I have resolved this in the PR, shall we close this Pierre, or do you want it left open to entice someone to put in the error check in the script?

**Comment by DhairyaBahl** [comment]
I would like to work on this issue. kindly assign it to me.

Thanks

**Comment by peterbarker** [comment]
@DhairyaBahl again, can't assign it to you from a technical perspective, but its certainly yours for a while (or until you fix it!) :-)

**Comment by IamPete1** [comment]
Not sure of the exact patch that fixed, but I cant replicate on master. It seems like both `//@` and `// @` work the same now.
