### ISSUE TITLE
Direct control of drone motor speed through mavlink

### ISSUE THREAD

**Issue by JonathanPlasse** [ArduPilot/ardupilot#11859]
### Feature request

I want to be able to control directly the speed  of each individual motor from the companion computer of the drone.

Could it be done by creating a new mavlink message?

**Platform**
- [ ] All
- [ ] AntennaTracker
- [x] Copter
- [ ] Plane
- [ ] Rover
- [ ] Submarine

**Comment by magicrub** [comment]
Can you describe the application?

**Comment by rmackay9** [comment]
@JonathanPlasse, it's possible using the motor test feature although only for a few seconds..

**Comment by peterbarker** [comment]
On Mon, 22 Jul 2019, Randy Mackay wrote:

> @JonathanPlasse, it's possible using the motor test feature although only
> for a few seconds..

I think notionally you could use pass-through using RC channel options.

Note that this is typically a terrible, terrible idea as the latencies 
(and jitter!) will give you terrible control.

**Comment by rmackay9** [comment]
The suggestion to use rc passthrough (i.e. set SERVOx_FUNCTION = RCIN1) is OK although this would mean the transmitter couldn't be used because it would be overwritten by the RC_OVERRIDE input from the companion computer.  Also the regular AP flight code couldn't control the vehicle because it would be looking for SERVOx_FUNCTION = motor1,2,3,etc).

**Comment by JonathanPlasse** [comment]
> Can you describe the application?

@magicrub, It is to test low level control algorithms as MPC on the companion board.

**Comment by magicrub** [comment]
Well then just map an input to an output instead of to a motor. ServoX_function=RCinYpassthrough.

**Comment by JonathanPlasse** [comment]
And to control with the companion computer, can I use `RC_CHANNELS_OVERRIDE`?

**Comment by magicrub** [comment]
@JonathanPlasse  yes

**Comment by JonathanPlasse** [comment]
Thanks a lot
