### ISSUE TITLE
Bad frames

### ISSUE THREAD

**Issue by touchthebitum** [ArduPilot/ardupilot#11879]
#### Issue details
I had problems with weird soft crashes after about 3 min of flight. After about 3 min, the model falled down and (on the ground) only the left rear motor is rotating at idle speed, the others are off.  I can disarm.
I tried stabilized/loiter/alt hold mode and autotune but always the same behaviour.  
Log seems ok but I post it anyway.
I noticed several  bad frames on my 4in1 Holybro Tekktro32 F3 escs plugging it to Blheli32suite. 
I use Dshot150 and esc telemetry. I also use Yaapu telemetry wihtout inverter and therefore I use this dev version. 

#### Version
ArduCopter V3.7.0-dev (eed19a92) but I used the last ones since they are available

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad V

#### Hardware type
Kakute F7
Holybro Tekktro 32 F3 65 amp 4in1 in Dshot150 mode
Lipo 6s
Low Kv motors with 15" props

#### Logs

[00000004.zip](https://github.com/ArduPilot/ardupilot/files/3430014/00000004.zip)

**Comment by khancyr** [comment]
hello,

This is the issue list for software issue and enhancement. For user support, please use : https://discuss.ardupilot.org/
Thanks.
