### ISSUE TITLE
AC3.6.10 telemetry message at startup: “AK09166 reset failed” 

### ISSUE THREAD

**Issue by FilippoFranchini** [ArduPilot/ardupilot#11935]
### Bug report

**Issue details**

Upgraded from 3.6.8 to 3.6.10. When I power the copter, after a few seconds I get the message: AK09166 reset failed (2x). This message is not popping up with 3.6.8 version. The copter flights smoothly and the message is not included in the MSG section of the data flash log. The message appears only on my taranis as frsky passthrough telemetry INF message.

**Version**

AC 3.6.10

**Platform**

Copter

**Airframe type**

quad

**Hardware type**
Pixhawk 1, external GPS+compass module M8T XL + LIS3MDL

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by peterbarker** [comment]
I think this one went away already....

**Comment by rmackay9** [comment]
yes, it's gone now..
