### ISSUE TITLE
SITL Segfault

### ISSUE THREAD

**Issue by stephendade** [ArduPilot/ardupilot#11952]
### Bug report

When running SITL (Ubuntu 18.04) and switching to EKF3, A segfault in Ardupilot is caused.

This occurs consistently when running ``sim_vehicle.py`` with the ``-w`` option and using the ``param set EK3_ENABLE 1`` command in MAVProxy.

This issue does not appear to occur when running with debug symbols (``-D`` in ``sim_vehicle.py``)

The segfault error message I get is:
``Statustext (EKF3 IMU0 buffers, IMU=11, OBS=4, OF=10, dt=0.0120�3�U) too long``
or similar, such as:
``Statustext (EKF3 IMU0 buffers, IMU=11, OBS=4, OF=10, dt= 0.012Q�U) too long``

Digging down into the code, it appears to be an issue in ``AP_NavEKF3_core.cpp``, line 149.

Changing that line from:
``gcs().send_text(MAV_SEVERITY_INFO, "EKF3 IMU%u buffers, IMU=%u, OBS=%u, OF=%u, dt=%6.4f",``
to
``gcs().send_text(MAV_SEVERITY_INFO, "EKF3 IMU%u buffers, IMU=%u, OBS=%u, OF=%u, dt=%5.3f",``
appears to fix the issue.

That would indicate that there's some formatting issue with the ``dtEkfAvg`` variable in ``AP_NavEKF3_core.cpp``.

**Version**
master (as of 04/08/2019)

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
N/A

**Hardware type**
SITL

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by peterbarker** [comment]
Not a segfault - just a failed sanity check that we're not truncating any statustexts we are sending.

I've created a PR to shorten this string.
