### ISSUE TITLE
Buzzer command

### ISSUE THREAD

**Issue by Ayman-git** [ArduPilot/ardupilot#11950]
Hello, is there a way to make a buzzer command I would like to make an android app that is going to be connected to pixhawk and I would like to know if there is a way to make a buzzer work every time I press the button the buzzer works.

**Comment by rmackay9** [comment]
@Ayman-git, yes, we support the [PLAY_TUNE mavlink message](https://mavlink.io/en/messages/common.html#PLAY_TUNE)

**Comment by Ayman-git** [comment]
Oh Thanks alot. I didnt notice
