### ISSUE TITLE
Autotune

### ISSUE THREAD

**Issue by touchthebitum** [ArduPilot/ardupilot#11954]
### Bug report

**Issue details**

Autotune doesn't store results after completion.

**Version**
3.7 dev

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quad V

**Hardware type**
Kakute F7 Tekko32 F3 65amps

**Logs**
[00000017.zip](https://github.com/ArduPilot/ardupilot/files/3464996/00000017.zip)

**Comment by lthall** [comment]
You did not land in autotune. You changed mode into stabilize before landing and disarming.
