### ISSUE TITLE
NTF display smartport on telem one conflict

### ISSUE THREAD

**Issue by Gavsv8** [ArduPilot/ardupilot#11969]
### Bug report

I had an osd and led lights on telem 2 with  Mavlink protocol and frsky smartport for R9 on telem 1 . The strange thing is when I enable an NTF display (ssd1306)  connected to the i2c bus it works but the smartport telemetry on telem 1 stops working. I found a workaround to move the led and osd to telem 1 and smartport to telem 2 and all works including ssd display. There seems to b a link between Mavlink data on i2c bus to telem 1 serial port.

**Version**
Latest and previous version possibly always present

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe **
hex

**Hardware type**
Pixhawk 2.4.8 

**Logs**
Workaround found

**Comment by IamPete1** [comment]
@Gavsv8 any update? Is this still a issue on 4.1?

**Comment by IamPete1** [comment]
Please re-open if this is still a issue.
