### ISSUE TITLE
qt5AndroidDir

### ISSUE THREAD

**Issue by Ayman-git** [ArduPilot/ardupilot#11968]
Hello, I tried changing the compiledsdk and buildtoolsversion to my version and it solved one of the problems that I was facing, but I found this new error that idk how to solve...

![image](https://user-images.githubusercontent.com/53388390/62452796-f6282100-b781-11e9-8d98-2ff9a5ee8fda.png)

**Comment by khancyr** [comment]
hello, 

You post on wrong repo, this is ArduPilot not QGC : https://github.com/mavlink/qgroundcontrol
