### ISSUE TITLE
AP_RANGEFINDER: Rangefinder params need a subgroup rename 

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#12014]
### Bug report
Rangefinder params are recursed in two sub-groups with the same name, leading to param expansions in the wiki and MP with identical names and wiki build errors...not only ugly but potentially confusing..

**Version**
master

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by Hwurzburg** [comment]
I will happily do the work in the code to change this to eliminate wiki build errors, but need a decision on how the two subgroups should be named...

**Comment by rmackay9** [comment]
Here is what it looks like on the wiki.  So we can see there are two expanders for each range finder instance.
![rngfnd-duplicates](https://user-images.githubusercontent.com/1498098/62904684-49adf680-bda2-11e9-81df-6b63515cf6cd.png)

**Comment by peterbarker** [comment]
The linked PR just eliminated the duplicate heading here.
