### ISSUE TITLE
QGC can not detecting the pixhawk board , B/E in red color?

### ISSUE THREAD

**Issue by hughhugh** [ArduPilot/ardupilot#12044]
Hi. I met a problem after uploading the firmware built from the master branch. The codes can be compiled and uploaded. But after it is uploaded, the B/E light is always in orange color. The qgroundcontrol can not detect the pixhawk board now. Has anyone met this problem before?

-  Pixhawk 2.4.8  
-  ArduRover 3.5.1  
-  Master

$ ./waf configure --board fmuv2
The screen is like this after running the code.
I have run the './waf distclean'
before this.
Then I input '' ./waf --target bin/ardurover --upload ''
![图片](https://user-images.githubusercontent.com/9352717/63078506-45363900-bf6e-11e9-870b-bacc4c818477.png)

![图片](https://user-images.githubusercontent.com/9352717/63078489-3c456780-bf6e-11e9-897d-c245488ab0c5.png)

![图片](https://user-images.githubusercontent.com/9352717/63078516-4bc4b080-bf6e-11e9-96a0-30bf13c84f25.png)

**Comment by peterbarker** [comment]
On Wed, 14 Aug 2019, Nailong Wu wrote:

> Hi. I met a problem after uploading the firmware built from the master branch. The codes can be compiled and uploaded. But after it is uploaded, the B/E
> light is always in orange color. The qgroundcontrol can not detect the pixhawk board now. Has anyone met this problem before?

Which board?

Which git hash?

**Comment by hughhugh** [comment]
@peterbarker 
Hi.
I remove the arm-none-eabi-gcc and download the <gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2>, set the compiler again manually rather than using <Tools/environment_install/install-prereqs-ubuntu.sh -y>.  
Right now, the QGC can connect the pixhawk board. It works now. I think there is something wrong with my system update which caused the error.
