### ISSUE TITLE
Plane: empty "date modified"

### ISSUE THREAD

**Issue by jace26** [ArduPilot/ardupilot#12046]
*Issue details**
Dates for Flash logs now empty when pulled straight from the sd card. time data look fine in the logs themselves. 

**Version**
plane 3.9.9 stable

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
VTOL PLANE

**Hardware type**
Cube

**Logs**
![image](https://user-images.githubusercontent.com/38468300/63061004-70128580-beb9-11e9-8b5d-9df420f0e7de.png)

**Comment by peterbarker** [comment]
Dates work on modern ArduPilot.
