### ISSUE TITLE
AC3.6.10 Maxbotix I2C MB1242 Bad LiDAR Health

### ISSUE THREAD

**Issue by sergeyfatman** [ArduPilot/ardupilot#12061]
**Bug report**
**Issue details**
After update to 3.6.10 from 3.6.1 not work sonar Maxbotix I2C MB 1242. Message Bad LiDAR Health. But when I returned to 3.6.1 all working super.
**Version**
AC 3.6.10

**Platform**
Copter

**Airframe type**
Quad

**Hardware type**
Pixhawk PX4 (v 2.4.8), external GPS+compass module M8N

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
sorry we never got to this, please re-open if this is still a issue on 4.1
