### ISSUE TITLE
AP_Param: AP_PARAM_FLAG_INTERNAL_USE_ONLY flag is buggy

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/ardupilot#12154]
### Bug report

**Issue details**

_On master, MIS_TOTAL is set to have AP_PARAM_FLAG_INTERNAL_USE_ONLY, just try to change any other MIS\_ param, you'd also get Param write denied!_

**Version**
_master_

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by Jaaaky** [comment]
I found that the flag is effective only if the param with flag set has index 0, it seems to be then applied to the whole group and subgroups. If it's set to any other param it doesn't have effect at all; i.e. you can change it.

**Comment by peterbarker** [comment]
This was fixed - thanks for the report!
