### ISSUE TITLE
Logging: log used IMU, compass/mag and barometer for each EKF lane

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12188]
We should log which IMU, compass and barometer each EKF lane is using to allow easier debugging of estimation issues.

One way we could do this is to add some extra columns to the NKF4 (1st EKF lane) and NKF9 (2nd EKF lane) messages.  The final columns might be:

- PE : primary EKF lane (renamed current "PI" to "PE")
- UI : used IMU instance
- UM : used compass/mag instance
- UB : used barometer

**Comment by tridge** [comment]
yep!

**Comment by peterbarker** [comment]
On Sun, 1 Sep 2019, Randy Mackay wrote:

> One way we could do this is to add some extra columns to the NKF4 (1st
> EKF lane) and NKF9 (2nd EKF lane) messages. The final columns might be:

Not to mention NKF14 (3rd EKF lane).

**Comment by IamPete1** [comment]
We now have this:
```
// @LoggerMessage: XKFS
// @Description: EKF3 sensor selection
// @Field: TimeUS: Time since system startup
// @Field: C: EKF3 core this data is for
// @Field: MI: compass selection index
// @Field: BI: barometer selection index
// @Field: GI: GPS selection index
// @Field: AI: airspeed selection index
// @Field: SS: Source Set (primary=0/secondary=1/tertiary=2)
```

So the only outstanding thing is IMU, I think that is locked to the core index anyway?

**Comment by peterbarker** [comment]
On Sun, 12 Sep 2021, Peter Hall wrote:

> So the only outstanding thing is IMU, I think that is locked to the core index anyway?

Yep.  Give or take a mask, I think.

**Comment by IamPete1** [comment]
I think the conclusion is that we now log all of this anyway.
