### ISSUE TITLE
Copter: resolve conflict between CH6 tuning and CH6 used for controlling gimbal tilt/roll/yaw

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#122]
Vince Hogg has reported in the 2.9.1 thread that:

Make sure you dont have Ch6 assigned to some tuning parameter. Its a possible ‘gotcha’. There should be a warning that Ch6 (or 7) is already doing something when you set up a gimbal. Also if you have to reverse the gimbal it will also reverse the tuning effect – even if you disable the gimbal again.

**Comment by R-Lefebvre** [comment]
This should fit in with the Input Manager work.

**Comment by rmackay9** [comment]
Yes, I think this is fixed.  We provide a mask from the motors library that says which channels are used for motors so the gimbal can't use them.
