### ISSUE TITLE
FrSky R9MM RF issues

### ISSUE THREAD

**Issue by Zboubie** [ArduPilot/ardupilot#12220]
Hello,

Does anybody experience issues with this combination:

Pixhawk 2.4.8 (v1) 
Arduplane 3.9.8(+) 
ChibiOS
R9MM 868Mhz 
3DR Radio 915Mhz

I stick the R9MM directly on the pixhawk case with a short wire for the SBUS output, and a few seconds after enabling the Tx, the FMU stop responding (Error blinking LED) and if enabled, the watchdog is triggered continuously.

I have the same behavior without the 3DR Radio, but it might take a longer time before crashing.

Seems to work "better" with ChibiOS + arduplane 3.9.4 or NuttX

**Version**
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
VAMP BORMATEC

**Hardware type**
Pixhawk 2.4.8 v1

**Logs**
crash of the FMU. Logs are stopped at the moment of the crash

**Comment by IamPete1** [comment]
Sorry we never got to this, please re-open if this is still a issue on 4.1
