### ISSUE TITLE
Get height and height types in AC_WPNav class, no ABOVE_HOME

### ISSUE THREAD

**Issue by BreederBai** [ArduPilot/ardupilot#12246]
// convert location to vector from ekf origin.  terrain_alt is set to true if resulting vector's z-axis should be treated as alt-above-terrain
//      returns false if conversion failed (likely because terrain data was not available)
bool AC_WPNav::get_vector_NEU(const Location &loc, Vector3f &vec, bool &terrain_alt)
{
    // convert location to NE vector2f
    Vector2f res_vec;
    if (!loc.get_vector_xy_from_origin_NE(res_vec)) {
        return false;
    }

    // convert altitude
    if (loc.get_alt_frame() == Location::AltFrame::ABOVE_TERRAIN) {
        int32_t terr_alt;
        if (!loc.get_alt_cm(Location::AltFrame::ABOVE_TERRAIN, terr_alt)) {
            return false;
        }
        vec.z = terr_alt;
        terrain_alt = true;
    } else {
        terrain_alt = false;
        int32_t temp_alt;
        if (!loc.get_alt_cm(Location::AltFrame::ABOVE_ORIGIN, temp_alt)) {
            return false;
        }
        vec.z = temp_alt;
        terrain_alt = false;
    }

    // copy xy (we do this to ensure we do not adjust vector unless the overall conversion is successful
    vec.x = res_vec.x;
    vec.y = res_vec.y;

    return true;
}
In the above code, why is there no ABOVE_HOME type?

**Comment by rmackay9** [comment]
The purpose of the function is to convert a Location object to a Vector3f plus a bool to specify whether the Vector3f's z-axis is an altitude above the ekf origin or an altitude above terrain.  In side of AC_WPNav we almost never use altitudes above home because home can be moved.

This is really a question so I'll close this issue if that's OK.
