### ISSUE TITLE
Rover: add RC trim (aka autotrim)

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#12292]
### Feature request

Add RC Option in Rover for Steering channel trim capture . Placing current RC channel used for steering value as Steering channel's RC trim and Steering SERVO's output trim. Should be active only in Manual mode.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  x] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by rmackay9** [comment]
txs for this.  no need to assign to me though, others may pick up the development.

**Comment by Hwurzburg** [comment]
I managed to get it working... PR #12380

**Comment by Hwurzburg** [comment]
merged closing
