### ISSUE TITLE
SMBus battery driver not working

### ISSUE THREAD

**Issue by nbelanger99** [ArduPilot/ardupilot#12290]
### Bug report

**Issue details**

Ap_BattMonitor seems not to be working correctly; it seems that the i2c backend isn't actually looking for 0x0b on the bus (according to scope and breakpoint on the other end). I have BATT_MONITOR set to Maxell for testing, currently bypassing check_pec_support. I've been printf debugging: **read_word (BATTMONITOR_SMBUS_VOLTAGE, data)** is being called regularly, and **read_registers(reg, buff, sizeof(buff))** is returning 0. printf isn't doing anything in I2CDevice::transfer, even though I know it's being called

**Version**
3.7.0

**Platform**
[  ] All
[  ] AntennaTracker
[ x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Pixhawk 4

**Comment by tridge** [comment]
did it work for you previously? If so, can you try this process for seeing where it broke?
http://ardupilot.org/dev/docs/finding-the-particular-commit-which-introduced-a-bug.html
