### ISSUE TITLE
AP_BattMonitor I2C abstraction on Pixhawk 4

### ISSUE THREAD

**Issue by nbelanger99** [ArduPilot/ardupilot#12327]
### Bug report

**Issue details**

Debugging the AP_BattMonitor library, and at least for the Pixhawk 4, neither directive:

```
#define AP_BATTMONITOR_SMBUS_BUS_INTERNAL           0
#define AP_BATTMONITOR_SMBUS_BUS_EXTERNAL           1
```

Refers to the actual "I2C A" port on the board. Apparently 3:

`hal.i2c_mgr->get_device(3, AP_BATTMONITOR_SMBUS_I2C_ADDR, 100000, true, 20));`

Is the appropriate bus. 

**Version**
3.7

**Platform**
[  ] All
[  ] AntennaTracker
[ x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Pixhawk 4

**Comment by nbelanger99** [comment]
Update: this is still an issue in current master branch. 
See pull request https://github.com/ArduPilot/ardupilot/pull/14284

**Comment by tridge** [comment]
it's not actually an issue, it is a hangover from the days when boards had only 2 I2C buses.
For boards with more than 2 I2C buses you must set the BUS parameter on the instance

**Comment by WickedShell** [comment]
Closing as these days we have a bus parameter for I2C batteries to resolve this for you.
