### ISSUE TITLE
Pixhawk wont Disarm on Landing (Using stick)

### ISSUE THREAD

**Issue by vanjsy** [ArduPilot/ardupilot#12339]
#### Issue details
Im trying to fly in AltHold, i armed it using the throttle right corner down it arms, tried disarms without taking off first it disarms. But after take off then landing, it wont disarm anymore. Any fix on this?

#### Version
Tried Copter Versions 3.6.10, 3.6.7, 3.6.6

#### Platform
[  ] All
[  ] AntennaTracker
[b  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
F450 Quad

#### Hardware type
Pixhawk
#### Logs
https://drive.google.com/open?id=1k8R4xxzp04gwy1GOZZ9Bte1CFn6wvF-K

**Comment by rmackay9** [comment]
This is really a support issue so I'm going to close it here.  It looks like it's [already been raised in the support forums](https://discuss.ardupilot.org/t/pixhawk-wont-disarm-after-landing/47079) which is the correct place for it.
