### ISSUE TITLE
Rover: arming from switch should not happen when tx is turned on

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12342]
If a transmitter's auxiliary switch is setup for arm/disarm and this switch is in the High position when the transmitter is turned on then the vehicle will become armed.  I think the behaviour should be changed to be more like Copter which requires that the arming switch be moved (from the Low to High position) for the vehicle to arm.

I think this can be done by simply removing the [ARMDISARM line from the RC_Channel_Rover::init_aux_function method](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/RC_Channel.cpp#L38) but we should test this to be sure.

**Comment by IamPete1** [comment]
All vehicles now use a shared method with no init.
