### ISSUE TITLE
SBAS not operating with Piksi Multi

### ISSUE THREAD

**Issue by vag01** [ArduPilot/ardupilot#12354]
### Bug report
SBAS reception by Piksi Multi is not working on Ardupilot

**Issue details**
When using a Piksi Multi GNSS receiver and it goes in SBAS, Ardupilot interprets this as an "unknown state". This leads to a no GPS fix result, while it should be more like a 3D Fix state enhanced by SBAS.
When it happens, we see on the Piksi's console that it has a correct positioning and that it is well in SBAS, while on the same time the copter gives an invalid GPS reception.
This has been encountered with copter, but probably it concerns also the other platforms.

After having looked in the code it seems that in: SBP_POS_LLH_MSGTYPE (MSG POS LLH — 0x020A), the fleld flags is not correctly handled. 
There is missing at least the DGNSS and the SBAS.

**Version**
3.6.10

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Octa quad

**Hardware type**
Cube Black & Piksi Multi

**Comment by WickedShell** [comment]
This was fixed in #9607 but was never back ported to the copter stable release.
