### ISSUE TITLE
'modules' file is empty

### ISSUE THREAD

**Issue by BenjaminAssouline** [ArduPilot/ardupilot#12408]
Hi,
I downloaded many times the ardupilot-master, and also cloned it using the command line,
but yet every time the files in 'modules' are all empty, and I regularly get the following error:

'ardupilot/ module / waf/ waf-light'
no such file or directory

However when I navigate in the site, I see that the 'modules' file contains all the needed files (like waf -light)

Could you please be kind to link a full 'module' file to download?
Thanks!

**Comment by auturgy** [comment]
Clone from the command line then update the sub modules.
The wiki has a guide:
http://ardupilot.org/dev/docs/git-clone.html
As this isn’t a bug or feature request I’m closing this issue. User help is better through the forum discuss.ardupilot.org
