### ISSUE TITLE
AP_Proximity: improve filtering for 360lidar including SF40c

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12436]
The SF40c driver (and probably RPLidarA2 and MAV drivers) use the shortest distance when calculating the distance for a "sector" (a sector is normally 45deg).  These sectors are then used in the low level AC_Avoidance library to stop the vehicle before it hits things.  These sectors are not used for the higher level path planning avoidance (aka BendyRuler).

We should increase the filtering applied to the sensor readings so that a single short reading is not enough to trigger a drastic slow-down of the vehicle.  We could use a mode filter or something like the glitch protection used for downward facing lidar.

**Comment by peterbarker** [comment]
Related: https://github.com/ArduPilot/ardupilot/issues/12919

@rmackay9 I'm pretty sure you've played around extensively with this recently.  Has this been solved?

**Comment by rmackay9** [comment]
@peterbarker, it's not really fixed although I'm also not sure that it's a real problem.  I haven't seen any short readings in my logs.

**Comment by GlidLov** [comment]
hi, i'm using the DF40/C and facing this problem also (among others). Stop from obstacle should be WAY more filtered. Now it's like a ripple over the thing...

**Comment by IamPete1** [comment]
We now have filtering, https://github.com/ArduPilot/ardupilot/pull/16906
