### ISSUE TITLE
FrSky Telemetry on Kakute F7 AIO not working

### ISSUE THREAD

**Issue by Seeelefant** [ArduPilot/ardupilot#12446]
### Bug report
FrSky Telemetry on Kakute F7 AIO not working with the setting mentioned here http://ardupilot.org/copter/docs/common-holybro-kakutef7aio.html . RCIN and Telemetry are both configured on UART6. Is there some kind of Inverter or dedicated cable missing?

**Issue details**

RX6 <----->  S.BUS
TX6 <-----> S.PORT

![image](https://user-images.githubusercontent.com/30323691/71681921-57363e00-2d8e-11ea-88cc-233c534797c9.png)

No telemetry data (by yapuu script)/no sensors dicovered.
**Version**
 ArduCopter V4.0.0 (49693540)

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X4

**Hardware type**
Holybro Kakute F7 (not AIO)

**Logs**
02.01.2020 18:24:47 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:47 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:47 : PreArm: Compass not healthy
02.01.2020 18:24:17 : RCInput: decoding SBUS
02.01.2020 18:24:17 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:17 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:17 : PreArm: Compass not healthy
02.01.2020 18:24:17 : PreArm: Throttle below Failsafe
02.01.2020 18:23:53 : Frame: QUAD
02.01.2020 18:23:53 : KakuteF7 00340018 32365101 30383430
02.01.2020 18:23:53 : ChibiOS: 1ed2b2e9
02.01.2020 18:23:53 : ArduCopter V4.0.0 (49693540)

**Comment by IamPete1** [comment]
sorry we never go to this, please re-open if this is still a issue on 4.1
