### ISSUE TITLE
Cartographer SLAM for Non-GPS Navigation，when i set ekf origin,the rover is flutter all the time on the map.

### ISSUE THREAD

**Issue by machenxiang** [ArduPilot/ardupilot#12443]
### Bug report
I use Cartographer SLAM for Non-GPS Navigation as the instruction http://ardupilot.org/dev/docs/ros-cartographer-slam.html. After i set ekf origin the rover is fluttering on the map, and i think the orientation is wrong. And some tiiem i even can't set ekf origin.
**Issue details**

**Version**
rover 3.5.2
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ * ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Sorry we never got to this.
