### ISSUE TITLE
Unable to flash firmware with latest Kakute F7 V1.5

### ISSUE THREAD

**Issue by chris669** [ArduPilot/ardupilot#12452]
Just received latest version of Kakute V7 upgraded with MPU6000.
tried to flash firmware same way as I do with F4 v3AIO without success.
What I did:
1. download arducopter_with_bl.hex for kakute V7 there: http://firmware.ardupilot.org/Copter/latest/KakuteF7/

2. connect kakute V7 via usb pushing button to be in DFU
3. launching Betaflight (can see board is in DFU mode)
4. charging local firmware
5. activating Full chip erase
I can see messages: USB open with success and USB close with success, in less than a half second but firmware was not flashed, didn't see any progressmeter bar activated.

Did I miss a step?

**Comment by auturgy** [comment]
The kakute F7 hwdef hasn’t been updated to include v1.5 / mpu6000

It should only be a couple of line change.

Regards,

James

**Comment by chris669** [comment]
Thanks, anyway, I was able to flash the firmware updating to RC Betaflight 10.6.0-RC2
and it works. But will wait for the mpu6000 add.

**Comment by auturgy** [comment]
Can you upload a close up photo? The orientation may be different 

Regards,

James

**Comment by chris669** [comment]
![IMG_20190930_175046](https://user-images.githubusercontent.com/15046400/65895354-9fb71780-e3ab-11e9-80d1-f93f306104a7.jpg)
![IMG_20190930_175231](https://user-images.githubusercontent.com/15046400/65895390-ae053380-e3ab-11e9-90b5-e0f5b93b45fa.jpg)
ok like this?

**Comment by auturgy** [comment]
Thanks 

Regards,

James

**Comment by chris669** [comment]
I can test when you want! Thanks for your job. Chris

**Comment by tridge** [comment]
If the change is between a 20602 and a mpu6000 then there should be no software change needed in ArduPilot. Both sensors use the same driver, and we detect which it is at runtime using the whoami

**Comment by auturgy** [comment]
If it’s not working, could be another change in the update to the board. I’ll ask.

Regards,

James

**Comment by auturgy** [comment]
The v1.5 pin assignments are identical to v1.2, a few layout changes and the imu swap (same pins) are the only differences.

Regards,

James

**Comment by chris669** [comment]
sorry forget to mention, was able to upload the firmware with latest BetaFlight RC. Everything seems to work except that when moving up and down the controller, see no vertical speed indication, stays on zero. Can I check something else in order to be sure the baro is activated?

**Comment by chris669** [comment]
Ok, now for the third time I tried to connect GPS on Serial3 without success, but first message I get when connecting to MP:
Check BRD_TYPE: Baro: unable to initialise driver.
I didn't had this message before, just cannot give a valid explanation.
