### ISSUE TITLE
Copter: investigate aggressive stop when RTL command (within Auto) starts

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12468]
There is one report that the RTL-command aggressively stops the vehicle when it first activates (i.e. RTL within Auto) but this does not happen if the RTL flight mode is initiated when the vehicle is in PosHold mode.

Sorry I do not have logs yet demonstrating the difference but it is likely possible to replicate in SITL.

**Comment by roque-canales** [comment]
With copter 3.6.11 i also experienced agressive brake when during auto mission when use do change speed to lower speed in the middle of mission.  Very agressive brake that no respect wp acc limits.
