### ISSUE TITLE
Follow Mode: offset reset each time mode is entered

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#12460]
### Feature request
Currently if offset is zero, then current vehicle offset it used for Follow Mode, but it persists until next reboot...should be reset every entry into Follow mode...

**Platform**
[  ] All
[  ] AntennaTracker
[x  ] Copter
[  ] Plane
[x  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by rmackay9** [comment]
The fix for this is in master so closing
