### ISSUE TITLE
Copter: Interface between FDM(Customised JSBSim) and Ardupilot

### ISSUE THREAD

**Issue by miarmoh** [ArduPilot/ardupilot#12474]
Hello, i want to ask some solution for interface between FDM and Ardupilot specially for Hexa-copter case.

i am a student and new for Ardupilot so didn't know exactly where to change and update.. I did connection with FDM(customised JSBSim version which supported for quadcopter) and Ardupilot.

For Fixed wing case, it working very fine  but for hexa -copter case, no respond from FDM to Ardupilot.

I tried to send servos comments with six throttle cmd to JSBSim , but no respond. when i sent with alieron, elevator, throttle and rudder command (exactly same on STIL_JSBSim.cpp) then some respond in initial stage but aircraft not move at all.

This is how i updated on SIM_JSBSim.cpp; 
![image](https://user-images.githubusercontent.com/16092809/66032009-83e47a80-e53f-11e9-88b2-15b0cfcf0943.png)

So do i need to update on other place on ArduPilot code or runsim.py file? I would be too thankful if someone can help me for this..
Thanks~~~~~~

Platform
[ ] All
[ ] AntennaTracker
[x] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

**Comment by IamPete1** [comment]
sorry we never got to this, feel free to jump on the discord simulation channel if you have any questions. https://discord.gg/TQNb7cbw
