### ISSUE TITLE
Copter: add warning to user from vehicle and ground station when user is approaching the fence

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1254]
Original request appeared on mission planner issues list
https://github.com/diydrones/MissionPlanner/issues/468

**Comment by peterbarker** [comment]
Sooo... estimate time 'til fence crossed, warn if below threshold?

We have three fence types now, this can be done individually for each.

**Comment by rishabsingh3003** [comment]
@peterbarker @rmackay9  I wanted to fix this issue. I believe it would be good if we can provide the user with the option (through a user-settable parameter)  whether they want to use this feature and at what time interval they want the warnings to come? Also, should the warning be in terms of the approaching distance to the fence or the approaching estimated time or both?
 
Lastly, the warning should be issued using   `gcs().send_text(MAV_SEVERITY_CRITICAL"")` method right?  
Just wanted to discuss these things before I raise a PR

**Comment by peterbarker** [comment]
@rishabsingh3003 you've got a lot of good questions there.

I'd guess estimated time to hit the fence so it's then applicable for fast moving vehicles.

We try to minimise parameters, so some sensible interval initially for any warning.

You say statustext, but it's better to avoid those if possible - a dedicated message would let an RC "transmitter" provide tactile feedback if the user is approaching the fence.

I'm not even sure this is practical and wanted on a modern ArduCopter; the user can chooise to avoid being able to cross the fence if they choose, which wasn't an option back then.

I've marked this devcall so we can discuss as a team - you're welcome to turn up!

**Comment by tridge** [comment]
add mavlink2 extension to FENCE_STATUS for distance and time to fence, then leave it up to GCS to set thresholds for display?

**Comment by rmackay9** [comment]
This is a really old enhancement request and I haven't heard any users request this in years.  ArduPilot Copter and Rover now stop before hitting the fence (in all modes except very manual modes) so I think users can see pretty clearly from the GCS if it's stopped because it's nearing the fence.  I think we should consider not implementing this and instead close the issue.
