### ISSUE TITLE
Copter: significant issues with BLHeli on 4.0

### ISSUE THREAD

**Issue by andyp1per** [ArduPilot/ardupilot#12542]
I am seeing a number of issues with BLHeli support in 4.0

### Bug report

 - If I enable BLHeli Passthrough and connect with BLHeli, after I disconnect I start seeing the error " internal error (0x8000)"
- If I enable ESC testing I get (*UPDATE: caused by auto telemetry*)
```
APM: ESC: Running test on channel 0
APM: ESC: BL_ConnectEx 0/4 at 0
APM: Initialising APM
APM: ESC: BL_ReadBuf 8 -> 9
APM: ESC: Interface type imARM_BLB
APM: ESC: BL_SendCMDSetAddress 0x7C00
APM: ESC: BL_ReadBuf 256 -> 259
APM: ESC: BL_SendCMDSetAddress 0xEB00
APM: ESC: BL_ReadBuf 16 -> 19
APM: ESC: Prot 5 Good 151338 Bad 0 0 0 0 x0

APM: ESC: Test PASSED
Critical failure
```
 - If I enable ESC telemetry I lose logging (*UPDATE: caused by DMA on the RX pin*)

If I had to guess I would say the BLHeli support is pegging the CPU somehow

**Version**
4.0
BLHeli version 32.7 with auto telemetry enabled (I'll try switching this off next)

**Platform**
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad 3"

**Hardware type**
KakuteF7 Mini

**Logs**

**Comment by andyp1per** [comment]
If I turn off auto telemetry in BLHeli I no longer get the "Critical failure" when testing but I do still get "Internal errors (0x8000)"

**Comment by andyp1per** [comment]
Part of this seems to be related to DMA on the telemetry pin. If I disable this then things are better, rpm output is still a little suspicious however:

![image](https://user-images.githubusercontent.com/2893260/66704325-bb5ae000-ed12-11e9-9a43-64da98afd52d.png)

and the Internal errors is still there on test / passthrough

**Comment by vierfuffzig** [comment]
i could reproduce this, doing a BLH_TEST on copter firmware reliably triggers internal error 0x8000. it does this too without setting up or connecting ESC telemetry at all. on a sidenote, BLH_DEBUG prompts also do not work on copter.
there's no comparable issues on plane firmware.

**Comment by andyp1per** [comment]
I played around with blheli yesterday with this in and all looked good, so I think this has essentially fixed the problems I was seeing.
