### ISSUE TITLE
Dev: autotest reliability issues

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12549]
We're getting a lot of false failures in our auto test suite.  These failures are sometimes real but just as often they are not real failures which needlessly eat up developer time and reduce confidence in the tests.  Below are a list of common failures:

1. AUTOTEST: Failing tests: PolyFenceAvoidance ([example](https://travis-ci.org/ArduPilot/ardupilot/jobs/597394068)) 
2. azure-pipelines / ArduPilot.ardupilot (Cygwin SITL Plane test) Cmd.exe exited with code '1' ([example](https://github.com/ArduPilot/ardupilot/runs/257984498))
3. AUTOTEST: Failing tests: GCSRally ([example](https://travis-ci.org/ArduPilot/ardupilot/jobs/596058275))
4. drive.APMrover2.Polyfence ([example](https://travis-ci.org/ArduPilot/ardupilot/jobs/595425448))

I think we should fix or worst case disable the tests that are unreliable.

**Comment by WickedShell** [comment]
Closing this as this has just gone stale over time, and a lot of the testing structure has been reworked since this was opened.
