### ISSUE TITLE
AP_PrecLand: Add support for mavlink2 messages

### ISSUE THREAD

**Issue by erikasnow** [ArduPilot/ardupilot#12563]
### Feature request

I am currently trying to get a copter to precision land on an AprilTag using the LANDING_TARGET mavlink message. Basically, I am using the AprilTag localization methods described in http://ardupilot.org/dev/docs/ros-apriltag-detection.html 

But instead of sending a VISION_POSITION_ESTIMATE message, I want to send the LANDING_TARGET message so that I can land accurately. The vision estimate message already requires the x, y, z, and q between the copter and the tag, so I had hoped it would be an easy transition to the LANDING_TARGET message from mavlink2. 

It would be really useful if Ardupilot supported the mavlink2 LANDING_TARGET message, which contains those x, y, z, q fields, instead of just using the angle_x and angle_y fields from the original version. 

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Looks like this is already supported, https://github.com/ArduPilot/ardupilot/blob/0b0ca6a9e99e5f22621af1d0199f008ce1c786d0/ArduCopter/GCS_Mavlink.cpp#L585
