### ISSUE TITLE
Using NMEA - HDT message as heading/yaw source instead of compass

### ISSUE THREAD

**Issue by bigboy061293** [ArduPilot/ardupilot#12579]
Hi, 

I am kindly new to both github discussions and ardupilot/arducopter firmware. I have read all the discussion here but to be honest that I have no idea, already tried but does not help.

https://github.com/ArduPilot/ardupilot/pull/7215

What I am trying to do is replacing/lowering the weight the compass yaw angle by heading angle from HDT message (NMEA).

I have the GPS output GPGGA and GPHDT. Right now, GPS is read (readable long/lat in Mission planner status) but YAW is still drifting. GPHDT is fine when checked it standalone with terminal software . I disable COMPASS_USE, EK2_YAW_M_NSE, EK3_ENABLE are set, what else parameters do I miss?

<img width="1042" alt="para1" src="https://user-images.githubusercontent.com/29875842/67012331-66a4d400-f11b-11e9-8c48-ff7cb847a50f.PNG">

Sorry for duplicating the issue and thank you in advance.

**Comment by WickedShell** [comment]
Closing as a support issue, and based on posts on discuss I believe it has otherwise been solved already.

**Comment by rmackay9** [comment]
@WickedShell, we really need docs on how to set this up though.  It's come upon the Rover 4.0 testing thread as well.  I've added it to our [Rover-4.0 wiki to-do list](https://github.com/ArduPilot/ardupilot_wiki/issues/2109) so if you know how to set it up could you post comments somewhere?

**Comment by WickedShell** [comment]
@rmackay9 the only docs I really know of were dropped by tridge in #7215

**Comment by rmackay9** [comment]
@WickedShell, aha! thanks.  maybe that's enough..
