### ISSUE TITLE
Copter: add target final position to GUID logging

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12608]

**Comment by TanmayRajore** [comment]
I want to work on this issue and contribute to this can you please provide me what file to work on and what exactly you expect the new enhancement to do.

**Comment by peterbarker** [comment]
@TanmayRajore First thing - you must get to the point you can run ArduPilot in SITL.

Are you at that point yet?  https://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html

To answer your question, you need to modify this log message:

```
    { LOG_GUIDEDTARGET_MSG, sizeof(log_GuidedTarget),
      "GUID",  "QBffffff",    "TimeUS,Type,pX,pY,pZ,vX,vY,vZ", "s-mmmnnn", "F-000000" },
```

to contain a "final position" target.  When moving around obstacles this may be different to where the vehicle is currently headed.

The relevant code is in Copter/Rover mode_guided.cpp

**Comment by TanmayRajore** [comment]
I know how to use ArduPilot in SITL and I will get to work on it and understand it more. Thank you

**Comment by rishabsingh3003** [comment]
@rmackay9  Shouldn't this be done for Rover too? Since rover has the GUID message too. I see the PR marked as Copter.
