### ISSUE TITLE
AP_Mission: allow missions to be stored on SD cards to allow more points

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12601]
there have been a few requests from users including in [this forum post](https://discuss.ardupilot.org/t/maximum-waypoints-for-mission-planner/48316) to support very large numbers of waypoints (thousands) which leads to the request to store them on the SD card.

There's a similar request but the justification is to allow easily swapping SD cards to change the missions.

**Comment by IamPete1** [comment]
This script example allows loading scripts from SD, could be extended to switch missions with param or rc switch. One could put the both script and mission on a SD card that would then load its mission onto the flight controller.

Of course this is simply loading from the SD, the mission is still run from memory so there is no change to maximum number of waypoints.

https://github.com/ArduPilot/ardupilot/pull/15239

**Comment by peterbarker** [comment]
We do this now.
