### ISSUE TITLE
ESC clibration

### ISSUE THREAD

**Issue by sairoj59** [ArduPilot/ardupilot#12610]
I am using pixhawk quadcopter with firmware 3.6.11 my problem is every time i arm the copter it calibrates esc and the motors dont spin properly I tried esc calibration one at a time even then the same thing happens can some one give the solution for this.

**Comment by rmackay9** [comment]
I'm afraid this is definitely a support issue so it needs to go into [the support forums](https://discuss.ardupilot.org/c/arducopter/copter-36).  If it's confirmed as a bug or enhancement request then we can re-open it here.
