### ISSUE TITLE
AP_WheelEncoder: get_delta_angle() should also return get_last_update_ms()

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12613]
During the review of this PR https://github.com/ArduPilot/ardupilot/pull/12578, Tridge pointed out that Rover's [update_wheelencoders()](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/sensors.cpp#L36) method needs to [get_delta_angle()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_WheelEncoder/AP_WheelEncoder.h#L89) and [get_last_update_ms()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_WheelEncoder/AP_WheelEncoder.h#L107) atomically (i.e. both pieces of data should be retrieved at the same moment) to avoid the possibility of a race condition.

**Comment by hendjoshsr71** [comment]
This was completed with #13234.

**Comment by peterbarker** [comment]
Thanks @hendjoshsr71 (and @rishabsingh3003 :-) )
