### ISSUE TITLE
MAVLINK feeding GPS with YAW problem

### ISSUE THREAD

**Issue by bigboy061293** [ArduPilot/ardupilot#12623]
#### Issue details

The Ardupilot GPS_MAV (https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/AP_GPS_MAV.cpp) contains "packet.yaw" but not described in Mavlink message (https://mavlink.io/en/messages/common.html#GPS_INPUT) 

Anyone knows the reason why? What I need to do if I want to feed the yaw/heading to drone using this method (via MAVLINK)?

Thanks in advance!

#### Version
Mavlink 2 / Ardupilot 3.6.11 / Mission Planner 1.3.68

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad

#### Hardware type
Pixhawk 2 - CubeBlack

**Comment by WickedShell** [comment]
According to discuss this has been solved, closing it on this basis.
