### ISSUE TITLE
SITL: AP_HAL::panic: Should not be called on invalid location (probably SPLINE_WAYPOINT)

### ISSUE THREAD

**Issue by tizianofiorenzani** [ArduPilot/ardupilot#12636]
## Bug report

**Issue details**
Most of the times I use SITL, the simulation stops with the following error: "Should not be called on invalid location". 
![image](https://user-images.githubusercontent.com/2077106/67425611-f3c5ae00-f59d-11e9-945e-cc8ca9b17428.png)
Every times that it happens, the Copter is in AUTO.

I traced down the error code and it looks like it's originated by [Location.cpp](https://github.com/ArduPilot/ardupilot/blob/6e0cceff0d8df300b79a13a0dcff55c3e729aa76/libraries/AP_Common/Location.cpp#L107).

Here is the code:
`
#if CONFIG_HAL_BOARD == HAL_BOARD_SITL
    if (!initialised()) { 
        AP_HAL::panic("Should not be called on invalid location"); 
    } 
#endif 
`
The function [initialized()](https://github.com/ArduPilot/ardupilot/blob/6e0cceff0d8df300b79a13a0dcff55c3e729aa76/libraries/AP_Common/Location.h#L115) is defined in Location.h as
`
bool initialised() const { return (lat !=0 || lng != 0); }
`
The only way it fails is for lat and lon to be zero, but no waypoint in my mission has such coordinates.

I noticed that this behavior happens with some SPLINE_WAYPOINT. Here is an example where I have two Spline WP very close, with a sharp corner. The Copter is where the SITL stopped

![image](https://user-images.githubusercontent.com/2077106/67424002-ef4bc600-f59a-11e9-870b-daad65c8408b.png)

Only when I set 25 and 26 as normal waypoints, I had no problem:
![image](https://user-images.githubusercontent.com/2077106/67424791-6df53300-f59c-11e9-928e-9a59fdcea92a.png)

Here is another place where it stopped.
![image](https://user-images.githubusercontent.com/2077106/67426227-43f14000-f59f-11e9-9f98-027b68c01481.png)

The same place with 66 and 67 set as normal WAYPOINT
![image](https://user-images.githubusercontent.com/2077106/67426994-d34b2300-f5a0-11e9-9b3b-0658a4f1614b.png)

**Version**
SITL 3.7.0-dev (57ac582a)

**Platform**
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Copter

**Hardware type**
SITL

**Logs**

**Comment by WickedShell** [comment]
This was fixed in #12252
