### ISSUE TITLE
Declination: update declination table

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1264]
The AP_Declination library allows looking up the declination based upon the GPS location.  declinations are fairly stable but they do change a little each year so we should probably regenerate the database that the AP_Declination library uses.

From discussion on the Dev Call some suggestions came out:
1. the original Trig_LUK library (accidentally removed from GitHub but still available if you go back in the history) ran on an APM2.  This should be rewritten to be a python script.
2. From AC3.3 and beyond, AC will only run on high powered CPUs (i.e. PX4, Pixhawk FlyMaple, VRBrain, etc) so we can make the database larger and thus slightly more accurate for at least some location.

**Comment by WickedShell** [comment]
Can someone link me to the legacy tool that was used to calculate this? I'd really like to get this table updated, (and maybe at a higher resolution, but definitely updated)

**Comment by OXINARF** [comment]
Last version of Trig_LUT before deletion: https://github.com/ArduPilot/ardupilot/tree/1115dde0d42c3ea8c052697e985838d3ba988146/libraries/Trig_LUT

But there were updates to the AP_Declination library after that, made by @a432511. In https://github.com/ArduPilot/ardupilot/commit/01b1e58f7d4c7c1c1678a95a304e44192c495f1d he says he changed the LUT generation code. Unfortunately that apparently never made it to our repo. Searching in Google it looks like he isn't around drones anymore, but his e-mail appears to be <his username> at gmail.com if you want to contact him.

**Comment by a432511** [comment]
Good morning. I did have a utility that generated the LUT, but it has been a very long time since I saw it. The last I remember I had commited that to the repo, but I don't think it was Github at the time. IIRC, we were using Google Code at the time? I will dig around on my external HDDs to see if I can find it.

**Comment by OXINARF** [comment]
@a432511 Thank you for showing up :smiley: Yes, at the time it was Google Code but the repo was imported to GitHub with all the history. Looking at your commits (https://github.com/ArduPilot/ardupilot/commits/master?author=a432511) I couldn't find that utility so if you can find it in your archives it would be great, thanks!

**Comment by a432511** [comment]
I can't seem to find it unfortunately. Wasn't there a separate "downloads" section of google code that was not part of the git repo? I vaguely remember it being uploaded to that section.

**Comment by OXINARF** [comment]
Ah yes, Google Code used to have a Downloads section: https://code.google.com/archive/p/ardupilot-mega/downloads?page=3 
I guess it is DeclinationLookup_CompressedEMM.zip. Unfortunately it doesn't have the source code, only the program, but it may still be useful.

Thanks for looking Adam!

**Comment by a432511** [comment]
You could try to reengineer it. Here is my blog post which has a link to the code that generated the uncompressed lookup table using bilinear interpolation (http://diydrones.com/profiles/blogs/new-feature-automatic-compass-declination). I adapted that so it would spit out a nicely formatted array that I could simply copy and paste into the compression code - can't find that code.

Here is the last working snipped of code I have to compress and decompress, but it will probably require some tweaking.

[compress-lut.cpp.zip](https://github.com/ArduPilot/ardupilot/files/459992/compress-lut.cpp.zip)

IIRC, what you should expect is two separate arrays, one for the sign bytes and one for the values. Those ultimately make their way into the flight code.

**Comment by OXINARF** [comment]
Thank you very much for all the information Adam, it will certainly help.

**Comment by WickedShell** [comment]
#7826 regenerated and provided new tables, as well as provided a script.
