### ISSUE TITLE
Rover: blank pre-arm message

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12663]
A newly setup vehicle may display a blank prearm message, "PreArm:".  I don't know what the cause is but we should resolve this.

This is probably the same issue as I've found for TradHeli: https://github.com/ArduPilot/ardupilot/issues/11800

**Comment by peterbarker** [comment]
On Fri, 25 Oct 2019, Randy Mackay wrote:

> A newly setup vehicle may display a blank prearm message, "PreArm:". I don't know what the cause is but we should resolve this.
> 
> This is probably the same issue as I've found for TradHeli: #11800

Rover may have been branched before I patched this with 
3619856fc9bac3744d83c7b9a0127e0f1f56f667 and 
1c187d8feb78a1c71311baa8458f52b6cccd6dba ?

**Comment by rmackay9** [comment]
We've also got this PR that fixes a blank message: https://github.com/ArduPilot/ardupilot/pull/12651

**Comment by rmackay9** [comment]
This is fixed in master so closing
