### ISSUE TITLE
add a  pure GPS-RTH mode for quadcopter, do not need compass

### ISSUE THREAD

**Issue by sin5678** [ArduPilot/ardupilot#12682]
### Feature request

**Is your feature request related to a problem? Please describe.*
make the quadcopter fly like fixwing , only need GPS to do RTH ,better have basic GPS hold

**Describe the solution you'd like**
when do RTH , quad tilt to an pre-define angle ,and fly forward ,then we known the heading info from the GPS , then do a small yaw control , till we heading home point , just like fix-wings. better disable roll control at the same time , we do not need roll control  now and  too much roll may cause one motor overload in big wind.  no compass ,no more compass calibration to do ,for experienced pilot, it's totally ok and feel easy to build a quad (no more compass interference),

**Describe alternatives you've considered**

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

**Comment by roque-canales** [comment]
+1

**Comment by rmackay9** [comment]
It is possible that the GSF feature from 4.1 will resolve this issue because it allows discovering the yaw by comparing the GPS and IMU values.

**Comment by IamPete1** [comment]
This is possible in 4.1 using GSF, recommended that you have responsibly good GPS.
