### ISSUE TITLE
LogAnalyzer: Corrupt lines are not handled properly

### ISSUE THREAD

**Issue by cmavr8** [ArduPilot/ardupilot#1268]
Even when the "-s" option is used, semi-corrupted logs cause exceptions like this:

$ python LogAnalyzer.py -s c.log
BAD LINE: FMT, 10, 3, STRT, ,
Traceback (most recent call last):
  File "LogAnalyzer.py", line 255, in <module>
    main()
  File "LogAnalyzer.py", line 225, in main
    logdata = DataflashLog.DataflashLog(args.logfile.name, format='auto', ignoreBadlines=args.skip_bad) # read log
  File "/tmp/DataflashLog.py", line 417, in **init**
    self.read(logfile, format, ignoreBadlines)
  File "/tmp/DataflashLog.py", line 465, in read
    numBytes, lineNumber = self.read_text(f, ignoreBadlines)
  File "/tmp/DataflashLog.py", line 592, in read_text
    raise Exception("Error parsing line %d of log file %s - %s" % (lineNumber,self.filename,e.args[0]))
Exception: Error parsing line 24 of log file c.log - **init**() takes exactly 6 arguments (5 given)

Many of my logs contain this line for some reason.
Removing it manually allows LogAnalyzer to continue properly.

**Comment by peterbarker** [comment]
Old, old, old. 

We prefer download .BIN files now, of course.

Please reopen if more needs to be addressed here!
