### ISSUE TITLE
Loss of Yaw control during decent

### ISSUE THREAD

**Issue by lthall** [ArduPilot/ardupilot#12695]
Discussion here:
https://discuss.ardupilot.org/t/loss-of-yaw-control-during-fast-descent/48597

Loss of Yaw control is observed during low throttle. This is caused by a simplification of the yaw range calculation during the motor lost code update. This has been addressed in the following pull request:

AP_Motors: Add full yaw range calculation back #12696

**Comment by rmackay9** [comment]
Fixed in master and will go out with Copter-4.0.0-rc2.
