### ISSUE TITLE
Copter: add pre-arm check of GCS failsafe

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12723]
I think we should add a pre-arm check of whether the GCS failsafe has triggered.  We have similar pre-arm checks for RC, battery and ekf failsafes.

TBH, it's possible this may be more annoying than it is useful but without it there is some danger that the user will have triggered the GCS failsafe (perhaps the radio disconnects before takeoff) but the user doesn't notice and they end up flying without an active GCS failsafe.

**Comment by Pedals2Paddles** [comment]
IMO this definitely should be a pre-arm check. It can easily be disabled with the arming check bitmask for operators that don't want/need it. That being said, I think you're right in that it will certainly annoy people at first.  I'm ok with leaving this out of the failsafe PR so as not to completely torture users with multiple behavior changes at once :)

**Comment by Pedals2Paddles** [comment]
Since the default GCS Failsafe is now disabled, I think this should now be a pre-arm check that won't cause user heartburn. It won't do anything at all if no GCS has ever been connected, which is also good.  I'll get on this shortly.

**Comment by Pedals2Paddles** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/12790
