### ISSUE TITLE
Copter: GCS Failsafe should flash LED yellow

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12722]
During testing PR https://github.com/ArduPilot/ardupilot/pull/7432 which greatly improves the GCS failsafe I found that the LED was remaining Green which made it slightly less obvious to the pilot why the vehicle was entering RTL.

I'm not sure if we should also play the buzzer... maybe not..

This will require:

1. modifying AP_Notify to add a new failsafe_gcs flag similar to the existing failsafe_radio or "ekf_bad" flag
2. modify the RGBLED.cpp to add a check for the new flag.  It can probably just use the "sequence_failsafe_radio_or_battery".
3. modify Copter's events.cpp's set_failsafe_gcs() to update the Notify flag

**Comment by Pedals2Paddles** [comment]
Given my love for lights and buzzers, I'm surprised I didn't think of this when doing the failsafe PR.  I will add this to the failsafe PR this evening.

**Comment by peterbarker** [comment]
@Pedals2Paddles if you did - I don't think you pushed it?

**Comment by Pedals2Paddles** [comment]
After discussing the implications of lights, buzzers, and pre-arm checks with Randy, we decided not to do those in the original PR.  But this should still be done soon.  I'll get back to this one soon.

**Comment by Pedals2Paddles** [comment]
Ha, I forgot I did a PR for this two months ago when I pulled it out of the refactor.  Just rebased it. https://github.com/ArduPilot/ardupilot/pull/12790

**Comment by rmackay9** [comment]
PR merged so closing, thanks!
