### ISSUE TITLE
SERVOx_FUNCTION: run out of options using AP_Int8

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/ardupilot#12744]
We have now filled the number of servo output functions available using a Int8 parameter.

https://github.com/ArduPilot/ardupilot/blob/d8445928d1c5786204c19c68576eba59aa298dbc/libraries/SRV_Channel/SRV_Channel.h#L153

https://github.com/ArduPilot/ardupilot/blob/d8445928d1c5786204c19c68576eba59aa298dbc/libraries/SRV_Channel/SRV_Channel.h#L239

Int8 has a max value of 127, if we were to go to Int16 that would give us 32767.

I attempted a fix but failed on the parameter conversion.

**Comment by rmackay9** [comment]
yes, parameter conversions can be tough.  RC_Channel has some param conversion code that might be helpful but it's a guess.  we should probably add a developer wiki page at some point with advice.
