### ISSUE TITLE
QPlane switching past VTOL Takeoff and Transition before altitude

### ISSUE THREAD

**Issue by cody303** [ArduPilot/ardupilot#12770]
We keep having a our VTOL transition before the programmed altitude. We are using QGroundControl to do mission planning, and have checked, but Don seems to think planning is uploading correctly. Any ideas why it is skipping or ignoring this waypoint? 

https://www.dropbox.com/s/25jzbutmq361hpc/2019-11-03%2013-39-03.bin?dl=0

**Comment by IamPete1** [comment]
Looks like your battery just tanked. AP was giving it full throttle trying to climb.

![image](https://user-images.githubusercontent.com/33176108/129494729-00ac243a-c1cb-4af7-b624-317e9f5ee2ce.png)
