### ISSUE TITLE
Can’t find TAKEOFF-mode

### ISSUE THREAD

**Issue by Latticello** [ArduPilot/ardupilot#12779]
Hello 
Yesterday I updated to Plane 4.1dev to get the new TAKEOFF mode.
But now I can’t find it anywhere... it’s not in the list with all the other modes.
Has it be activated somehow or am I too stupid to find it ?

#### Airframe type
_What type of airframe - 
flying wing

#### Hardware type
_What autopilot hardware
OmnibusF4pro 

Please guide me the way ^^

Sebastian

**Comment by IamPete1** [comment]
The mode is defiantly there, you will have to update your GCS to get the latest parameter descriptions. Failing that you can set you FLTMODE1 ... FLTMODE6 parameters to 13 for takeoff mode.
