### ISSUE TITLE
Kakute F7 AIO Loiter Not working with PX4Flow

### ISSUE THREAD

**Issue by NitinJSanket** [ArduPilot/ardupilot#12771]
### Bug report

**Issue details**

I see the values of the optical flow and they seem correct. My Alt Hold works with the TFMini but drifts always in one direction in loiter on the PX4Flow.

**Version**
3.6.11 and 4.0.0

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
QuadX

**Hardware type**
Kakute F7 AIO

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
Normally it's best to report support issues in the forums.  If you're using Copter-4.0.0 could you create a new topic and include a dataflash log file? https://discuss.ardupilot.org/c/arducopter/copter-40

Once we've confirmed it's a real bug then we can raise an issue to get it fixed, thanks!
