### ISSUE TITLE
RC inoperable if RCx_OPTION set to invalid value

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12805]
During Rover-4.0.0 testing a user has found that if they have an RCx_OPTION param set to an invalid value (like "1") then two bad things happen:

- RC inputs no longer work at all for any channel
- "Config error: Failed to init: RCx_OPTION: 1" is streamed to the GCS every few seconds

Even if the user changes the RCx_OPTION to a reasonable value the RC input does not recover nor does the error message stop.  This is a unnecessarily extreme response to a small configuration issue.

FYI to @peterbarker, @kd0aij who are perhaps most involved in this area recently.

**Comment by kd0aij** [comment]
The configuration error is currently detected at boot, and the firmware enters an error loop which emits the error message every 3 seconds. To correct the problem you must first set the parameter to a valid value, then reboot. This is the reason no RC channels (or anything else) appear to be working.

Prior to this change there was a single error message emitted at bootup, and again in flight when you  attempted to execute the function. The new behavior is intended to make it obvious at boot-time that something is wrong, while providing a convenient way to fix the problem.

**Comment by Hwurzburg** [comment]
what does it do in flight?

**Comment by kd0aij** [comment]
You can't do anything until you fix the parameter and reboot.
I suppose the error loop could be modified to treat an invalid RC option differently from other configuration errors in order to restore behavior to ignoring the problem.

**Comment by Hwurzburg** [comment]
So change to invalid option in flight= crash??!

**Comment by kd0aij** [comment]
No, the only effect _should_ be to generate a console message complaining "...invalid option..." assuming that is the only problem...
But if there's an invalid RC option set, maybe other things are screwed up, such as might happen if parameters for the wrong vehicle were loaded.

**Comment by Hwurzburg** [comment]
good, just checking...

**Comment by rmackay9** [comment]
@kd0aij,

This is really not good at all.  This changes an innocuous config error into a real problem.  We should revert this change or fix it.

**Comment by kd0aij** [comment]
I'm not sure whether requiring the parameter be set to a valid value and rebooting before flight constitutes a "real problem", or "better error reporting" :)

But perhaps I misunderstood the conclusion on the devcall, and this was only supposed to apply to SITL builds.,,  Would that be an acceptable fix?

**Comment by rmackay9** [comment]
@kd0aij, I think better warning would have been ok but this actually led to subsystems (like RC) not working at all.  Anyway, thanks for the review on the [new PR](https://github.com/ArduPilot/ardupilot/pull/12811).

**Comment by rmackay9** [comment]
This has been fixed in master and rolled out with Rover-4.0.0-rc4 so closing, thanks!
