### ISSUE TITLE
Rover: ARM logs only logged by default while disarming

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12803]
As part of Rover 4.0 beta testing ([discussion](https://discuss.ardupilot.org/t/get-arm-disarm-info-from-bin-tlog-files/48983)) we discovered that the ARM messages are only appearing when the vehicle becomes disarmed.

This is probably because we log the ARM message before changing the soft_armed state and this soft_armed state is probably also what determine whether we log at all.

The better strategic fix is to use the same events that we use in Copter so we are consistent across vehicles.

**Comment by joker-smiling** [comment]
you should change a param.

**Comment by peterbarker** [comment]
@rmackay9 turns out I had a branch lying around for this....
