### ISSUE TITLE
KakuteF7Mini Compile from source not able to flash

### ISSUE THREAD

**Issue by NitinJSanket** [ArduPilot/ardupilot#12825]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

### Bug report
Not able to flash, says not compatible. However, KakuteF7 firmware works on the KakuteF7Mini.

_Please describe the problem_

**Version**
4.0.0.rc2

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X4 Quad

**Hardware type**
KakuteF7Mini

**Logs**
NA

**Comment by andyp1per** [comment]
The KakuteF7Mini and KakuteF7 firmware are different in 4.0 and have different bootloaders. If you have previously flashed your KakuteF7Mini with KakuteF7 bootloader you will need to use the blheli configurator to reflash the bootloader with the correct version.
