### ISSUE TITLE
Quadcopter cannot take-off when using Cartographer SLAM for Non-GPS navigation

### ISSUE THREAD

**Issue by trigger1996** [ArduPilot/ardupilot#12833]
This issue is also published [here](https://discuss.ardupilot.org/t/quadcopter-cannot-take-off-when-using-cartographer-slam-for-non-gps-navigation/49269)

I'd like to have a quadcopter to fly indoor stably so Cartographer laser SLAM is selected for indoor localization.

I take [this article](http://ardupilot.org/dev/docs/ros-cartographer-slam.html#) in ardupilot wiki for reference and do exactly as it says.

Finally the data is collected but the quad cannot arm due to **HIGH GPS HDOP** both in Loiter mode and Poshold mode
The value of GPS_HDOP is 655.35.

The quad is tunned for outdoor flight and most of parameters are default expect for those set in calibrations and companion link. Then the parameters are modified as the ardupilot wiki says.

- Baud for telem2 (to companion computer) 500000, which is not 921600 for not accepting by the USB-to-UART converter
- AHRS_EKF_TYPE = 2
- EK2_ENABLE = 1
- EK3_ENABLE = 0
- GPS_TYPE = 0
- EK2_GPS_TYPE = 3
- COMPASS_USE = 0, COMPASS_USE2 = 0, COMPASS_USE3 = 0
- MAG_ENABLE = 0, this option does not exist

What should I do now?
BTW, why there is still **BAD compass health** after disabling the compasses in parameter list? 
It would be very grateful if someone helps!

**Version**
AdruCopter V 4.0.0-rc2 (beta version when choosing Firmware these days)

**Platform**
[    ] All
[    ] AntennaTracker
[ X ] Copter
[    ] Plane
[    ] Rover
[    ] Submarine

**Airframe type**
    quad X frame with tip-to-tip length of 450mm
    the quad never takes off when fixing this issue

**Hardware type**

- Autopilot
Pixraptor 2.1
It is a modified pixhawk 2, which is shown Px4fmu-v3 in MAVROS

- Companion computer
Intel NUC with i3-8 CPU
OS: Ubuntu 18.04 LTS

![QQ图片20191115002334](https://user-images.githubusercontent.com/24710213/68877372-e933aa00-0740-11ea-85e1-777f4df42097.png)
![QQ图片20191115004536](https://user-images.githubusercontent.com/24710213/68877582-4596c980-0741-11ea-806d-1ff8a791c065.png)
![QQ截图20191115004817](https://user-images.githubusercontent.com/24710213/68877807-a3c3ac80-0741-11ea-85f9-168475f1dcb3.png)
![9F776DAF3FC95AE082AE3C4A19A5F764](https://user-images.githubusercontent.com/24710213/68878407-a07cf080-0742-11ea-8aa8-6118892ffcf4.png)

**Comment by amilcarlucas** [comment]
This is a support question, not a bug. Please post it in the ardupilot discussion forum.
