### ISSUE TITLE
DJI ID BEACON to others

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#12842]
https://www.dropbox.com/s/v4lkyr2kdp8ukvx/DJI%20Remote%20Identification%20Whitepaper%203-22-17.pdf?dl=0

DJI propose to governments FAA this “open” uas remote identification protocol that will become soonly mandatory for use uas.

Does anyone here have more information to this protocol? Its based on 2.4ghz so maybe connecting little esp to pixhawk we can dev low cost solution that enables all ardupilot UAV with this new requirement ?

Idea is to not affect users from non dji uavs!

**Comment by peterbarker** [comment]
I think events may have overtaken this with the new FAA proposal to use "da internet" to solve the problem.

**Comment by CraigElder** [comment]
@apache405

**Comment by rmackay9** [comment]
@magicrub - we also thought you might have an opinion on this one.

**Comment by peterbarker** [comment]
@magicrub and Jeff W.

This is a support request; please open something on discuss.ardupilot.org if you'd like to push further with this.

**Comment by apache405** [comment]
@magicrub and I were heavily involved in the development of Open Drone ID, which seems to be what the FAA is basing their requirements on.  DJI was also involved with the development of OpenDroneID (specifically on the WiFi side of things).  Several of us are working on hardware and firmware to address the remote ID requirements.

**Comment by roque-canales** [comment]
Hello @apache405, 

Many thanks for this news.

When its planned to have the solution working with hardware?

Here in france all uavs must be compliant before julliet....(for the wifi side)
