### ISSUE TITLE
 Mateksys F765-Wing: Bind BEC and Camera switchers

### ISSUE THREAD

**Issue by SergeyBokhantsev** [ArduPilot/ardupilot#12854]
The FC supports programmatic control for:
- enable/disable integrated BEC (PE4)
- switch Camera1/Camera2 inputs (PE15)

It would be great to bind these as a RC switch options

**Platform**
[x] All

**Comment by IamPete1** [comment]
You can link them to relay one and two and control with RCx_OPTION

http://www.mateksys.com/?portfolio=f765-wing#tab-id-6
