### ISSUE TITLE
Watchdog reset due to interrupt storm?

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#12862]
testing  PR #12857, had loss of GPS, followed by IWD reset just before landing....
bench test showed GPS back, but no compass
extracting BN-880 showed jst connector partially unseated...cable hard bent stressing connector...once freed and straight and connector fully seated, compass returned....subsequent movements of cable produced no issues, but did not attempt with connector partially seated...

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Convergence, QuadPlane....running  PR #12857

**Hardware type**
MatekF405-Wing, BN-880 GPS/Compass

**Logs**
flight ending in WD
https://www.dropbox.com/s/9hbi6fn6it75q23/2019-11-19%2013-09-01.bin?dl=0
after reset
https://www.dropbox.com/s/sjqtji2njet0nfh/25%2012-31-1979%206-00-00%20PM.bin?dl=0

**Comment by tridge** [comment]
I have reproduced this by connecting telem1 TX in parallel with the SDA line of i2c2 on a MatekF405-Wing. I am working on a fix

**Comment by tridge** [comment]
ChibiOS bug report here:
http://www.chibios.com/forum/viewtopic.php?f=35&t=5298

**Comment by tridge** [comment]
fixed by #12896
