### ISSUE TITLE
Crash detect bitmask talks about non-existent option

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#12866]
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X  ] Plane
[  ] Rover
[  ] Submarine

CRASH_DETECT bitmask description talks about DISARM and MANUAL MODE options, but only DISARM is shown in available bits...is the bit option there or documentation wrong?

**Comment by rishabsingh3003** [comment]
@Hwurzburg I think we can close this issue now. Just to clarify, setting the param to  value 0 would disable the feature and setting it to 1 enables it to disarm plane if a crash is detected. There is no other param option available. No manual mode switch either.

**Comment by Hwurzburg** [comment]
thanks...closing
