### ISSUE TITLE
Copter: pre-arm "Compass not calibrated" appears twice

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12914]
With Copter-4.0.1-dev a newly setup vehicle that has not yet had a compass calibration will have "Compass not Calibrated" appear twice on the ground station.
![image](https://user-images.githubusercontent.com/1498098/69765926-312ee400-11b9-11ea-91ec-2037e177c5bf.png)

**Comment by peterbarker** [comment]
This is probably a `virtual bool compass_must_be_calibrated_to_arm() const { return _compass.learn_offsets_enabled(); }` method on `AP_Arming`, and a `virtual bool compass_must_be_calibrated_to_run() const override { return true; }` in `AP_Arming_Copter`.  The existing `compass_checks` override in Copter goes away and the `AP_Arming` equivalent uses the new virtual method.
