### ISSUE TITLE
Copter: Terrain data missing for finland, terrain failsafe not triggered

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12923]
During investigation of [this user report](https://github.com/ArduPilot/ardupilot/issues/12888), I found that the terrain data seems to be missing for Finland (62.23075, 25.6993) which I think means that terrain following missions will not work.

@meee1 tells me that there should be a N62E025.hgt file in [this directory](http://firmware.ardupilot.org/SRTM/Eurasia/) but there are not files higher than N60.

**Comment by thadeausmaximus** [comment]
The terrain data comes from the SRTM, Shuttle Radar Topography Mission, and only covers from 60 N about 55 S. So you are north of the terrain database used. As the old cartographers said "There be dragons." Unless you have a line on good terrain data for that far north you may be out of luck.

**Comment by rmackay9** [comment]
@thadeausmaximus, thanks for this.

I've just done a quick test in SITL (both the regular one using mavproxy and the one built into MP) and I find that the terrain failsafe did not trigger when the user enters a waypoint with an altitude frame specified as "Terrain" (aka AGL).

**Comment by VDLJu** [comment]
There is reliable terrain data available from link below as WMS and WCS services. The map layer is "paituli:mml_korkeusmalli_10m_2019".

The grid size is 10m x 10m and the vertical accuracy is about 1,4 m. Height is given in N2000 system. It is the most accurate DEM available for whole Finland
Coordinate Reference System: ETRS89 / ETRS-TM35FIN (EPSG:3067)

At current state the difference/error between N2000 system and WGS84 (gps default) heights are under 1m. IMO this could be used as is, without any conversion.

API info to database
https://avaa.tdata.fi/web/paituli/rajapinta

Description for the DEM
http://www.nic.funet.fi/index/geodata/mml/dem10m/2019/MML_10mDEM_description.pdf

**Comment by rmackay9** [comment]
Mission Planner (beta) has been updated so that it will not send invalid altitudes when it has no SRTM data.  I think this will resolve the terrain-failsafe issue (i.e. a terrain failsafe will be triggered)

**Comment by tridge** [comment]
yes, issue is now resolved
