### ISSUE TITLE
Monitor uavcan GPS status in real time

### ISSUE THREAD

**Issue by cuhome** [ArduPilot/ardupilot#12929]
After I disconnected the UAVCAN GPS from the flight controller, the gpsstatus still shows as 1; during the flight, UAVCAN GPS may not work / cable is abnormal / GPS positioning is lost, and even worse, GPS2 no matter what you use GPS, it can not monitor the GPS connection status in real time. More and more drone jammers on the market may require more GPS information to help manufacturers analyze the source of the failure.
![image](https://user-images.githubusercontent.com/31507501/69857895-cde1a680-12cb-11ea-92f7-a0bd9fa9ff7a.png)

**Comment by tridge** [comment]
what version of ArduCopter? I fixed this in a recent change

**Comment by cuhome** [comment]
AC4.00 DEV

**Comment by cuhome** [comment]
![image](https://user-images.githubusercontent.com/31507501/69858368-d4245280-12cc-11ea-8cb3-9ac75384ac9f.png)

**Comment by tridge** [comment]
That version is from October 10th. I put in the fix on October 14th

**Comment by cuhome** [comment]
Thanks, I have tested the latest firmware and it does.

**Comment by cuhome** [comment]
Test completed, thank you.
