### ISSUE TITLE
CAM-message: Add shutter delay to increase Image-ref accuracy

### ISSUE THREAD

**Issue by Yups1337** [ArduPilot/ardupilot#1295]
Hey Guys!

The CAM-message is a big plus in Arducopter and Arduplane for everyone who is using the Ardupilot for survey and other mapping options.

But there is still one small point missing: You cannot configure a shutter delay for your camera. 
Range should be between 1-1000ms, so if your camera has a delay of 100ms, the exact position will be written to the log file 100ms after the camera trigger was "pushed". 
-> With a typical flying speed of 15m/s (medium size plane), the error in Lat and Long will be reduced by 1,5m - Thats a lot!

I think this feature would be very easy to develop!

Best Regards from Germany
Yannick

**Comment by WickedShell** [comment]
I'm not sure if this is of interest at this point. We support direct shutter feedback, which will be more accurate then predicting a delay value, and bench testing has shown a shocking amount of variation in lag time on the camera (even with auto focus turned off, with auto focus turned on the variation gets significantly worse).

Unless someone objects (or is looking to take up implementation) I think this should probably be closed. (I'll let it live for awhile first to collect feedback though).

**Comment by iskess** [comment]
I'll just comment that I cannot use direct shutter feedback because the Sony a5100 doesn't have a hot shoe. (Does anyone know a hack?) If a shutter lag parameter were available, I would use it. However I manage quite well without it and I would rather see development on one of my many other GitHub issues. 
Thanks.

**Comment by Naterater** [comment]
I'm all for this being closed @WickedShell. Trying to gain accuracy from shutter triggers is not ideal, and if anything, the GCS should calculate the offset post-flight.

**Comment by IamPete1** [comment]
consensus seems to be that this can be closed. Hot shoe feed back is preferred, if not possible a delay could be added in post.
