### ISSUE TITLE
SBUS-Based Link Quality Doesn't Seem to Work

### ISSUE THREAD

**Issue by tenten8401** [ArduPilot/ardupilot#12965]
### Bug report

**Issue details**

I have an FrSky R-XSR connected to a Matek F405-Wing flight controller. RSSI_TYPE is set to 3 (ReceiverProtocol) and SERIAL2_PROTOCOL is set to 23 (RCIN). Control is fully functional (am able to fly and move servos) but RSSI just constantly displays 0% in the OSD and ground station.
![image](https://user-images.githubusercontent.com/6174343/70071363-42b22a80-15c3-11ea-8d69-7091809ba114.png)

If I understand #6467 and #3274 correctly it should be able to detect the amount of dropped frames and set an RSSI value in the on-screen display.
Please let me know if there's any more information I can provide to help.

**Version**
Stable 4.0.1

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Sonicmodell AR Wing

**Hardware type**
Matek F405-Wing

**Logs**
N/A

**Comment by IamPete1** [comment]
We don't support SBUS link quality (yet), you can send the RSSI as a PWM on a spare channel from most transmitters. 

We have a existing issue to track that enhancement request here: https://github.com/ArduPilot/ardupilot/issues/2721 

so I'm goint to close this.
