### ISSUE TITLE
Repeating buzzer tones (low battery alarm) on Pixhawk ended after playback of other tone

### ISSUE THREAD

**Issue by xmikos** [ArduPilot/ardupilot#1297]
Hello,

while implementing radio lost alarm I have noticed faulty behavior of buzzer on PX4/Pixhawk (libraries/AP_Notify/ToneAlarm_PX4.cpp):

If some repeating tune is started (e.g. TONE_BATTERY_WARNING_FAST_TUNE on battery failsafe), it plays fine, but after ArduCopter plays some other tune (e.g. GPS glitch), repeating tune stops and doesn't play again. This can be really dangerous if someone rely on buzzer tones.

I assume it is caused by this condition:

```
if (flags.failsafe_battery != AP_Notify::flags.failsafe_battery)
```

Because failsafe_battery state is still same, repeating tune isn't activated again (after it was ended by playback of another tone).

**Comment by OXINARF** [comment]
This has been fixed: https://github.com/ArduPilot/ardupilot/blob/6cebd634cd64c6069b2a19bd7ced9f38f5ebf9cb/libraries/AP_Notify/ToneAlarm.cpp#L156-L166
