### ISSUE TITLE
Copter: allow ESC calibration without a reboot

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1298]
This request is to remove the need for at least one of the copter reboots when calibrating the ESCs.

The current ESC calibration routine requires this happen:
1. user plug in battery with flight controller throttle stick held high.  Arducopter code sets it's ESC parameter to "1" meaning the next boot will be for ESC calibration.
1. user unplugs battery and plugs in again while keeping throttle stick held high.  *\* THIS IS THE FIRST REQUIRED REBOOT **
2. Arducopter goes into passthrough mode so the pilot's throttle goes out to all motors
3. User pushes safety switch (if present) and high PWM signal is sent to all ESCs
4. ESCs interpret this high throttle as meaning go into calibration mode.
5. ESCs capture the high throttle and then beep to tell the user to pull the throttle low (the motors do not spin).
6. User pulls the throttle low
7. ESCs capture the low pwm value and then beep some more to indicate the calibration is complete and they return to "normal mode" (i.e. any future pwm messages received will cause the motors to spin up).
8. At this point, if the user raises the throttle, the motors will spin up but the vehicle will not fly because arducopter is in pass-through mode so it is not doing any attitude control.
9. User unplugs battery and plugs it in again in order to fly.  *\* THIS IS THE SECOND REQUIRED REBOOT **
10. User takes off an enjoys flying with their newly calibrated ESCs

**Comment by rmackay9** [comment]
I somehow doubt we will do this before ESC technology (i.e. CANBUS ESCs) make it irrelevant.  In any case, pushing to AC3.4.

**Comment by kovmarci86** [comment]
Hi, 
I did this like this:
disconnect batt, start motor/compass test, move throttle to 100%, connect battery.
After all, you need to redo the motor/compass calibration as suggested by the doc.

**Comment by lvale** [comment]
Most of the issues come from lots of standard ESC's that MUST be rebooted to save the new endpoints

**Comment by rmackay9** [comment]
Bumping to AC-3.5.

**Comment by IamPete1** [comment]
@rmackay9 Are you still interested in this? I don't think the double re-boot is that painful and having to calibrate at all is becoming less common with the digital protocols / annoying ESC's that don't calibrate (Tmotor).

**Comment by rmackay9** [comment]
OK, let's close this then.
