### ISSUE TITLE
MSP telemetry

### ISSUE THREAD

**Issue by twistedwings** [ArduPilot/ardupilot#13005]
It would be nice to have MultiWii serial protocol as an additional telemetry protocol.
The reason is to support DJI digital fpv osd.
They support MSP but chances are low they will ever support mavlink.

**Comment by tamboekie** [comment]
It seems there is some work going on in forum: Please see https://discuss.ardupilot.org/t/msp-protocol-support/57944

**Comment by WickedShell** [comment]
We do have support for MSP these days, if there are specific things still missing that should be opened as a seperate issue (if there isn't one already around that is appropriate for tracking it)
