### ISSUE TITLE
ros slam can't arm the copter

### ISSUE THREAD

**Issue by kenhuyang** [ArduPilot/ardupilot#13014]
### Bug report

**Issue details**

the link here https://ardupilot.org/dev/docs/ros-slam.html
describes how to use rplridar to use slam to fly a copter indoor, i followed the instruction, and the copter in the map moves accordingly.  but when i tried to arm it, the mp says compass not healthy, i set arming_check parameter to 0 to close the arming check, it didn't work. How to solve this? thanks!

**Version**
3.6.11 version

**Platform**
[  ] All
[  ] AntennaTracker
[ yes ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quad x

**Hardware type**

pixhawk

**Comment by rmackay9** [comment]
Could you download a dataflash log and if possible set the LOG_DISARMED = 1 so we can see what it looks like before arming.

**Comment by IamPete1** [comment]
No update from @kenhuyang so I'm going to close.
