### ISSUE TITLE
ArduPlane: weird servo output when starting with no RC link

### ISSUE THREAD

**Issue by KIrill-ka** [ArduPilot/ardupilot#1302]
While arduplane is initializing failsafe (failsafe.pde) takes over. If there's no RC/PPM signal yet, it tries to read radio input anyway. This makes servos to go to extreme positions (900 us pwm pulse).
It may damage the airframe or servos, because it doesn't respect configured min/max values.
By the way, why the failsafe is starting so early during initialization? Is it for ESC configuration?
I suggest the following fix in failsafe.pde:

```
if (in_failsafe && tnow - last_timestamp > 20000) {
    if(hal.rcin->num_channels() == 0) {
      channel_throttle->radio_out = 900;
      channel_throttle->output();
      return;
    }
    // pass RC inputs to outputs every 20ms
    last_timestamp = tnow;
```

Throttle setting is for safety, because all channels are initialized in `RC_Channel::output_trim_all()` which sets throttle channel to it's trim value. Alternatively throttle may be set to some sane value in `init_rc_out()`

**Comment by expntly** [comment]
While searching for a problem I'm having with the initialization of my servos, I came across this Github issue.

What is happening is that when I plug in the battery (pixhawk), *sometimes* the servos will turn to an extreme position (one end or the other) and just lock up there, against the frame.  It doesn't happen all the time.  Hard to repeat.  When this happens I just unplug and replug again, until it stops.

This looks related to what I'm reading above.  Is there a configuration change that would prevent this from happening?  Thanks

**Comment by WickedShell** [comment]
@expntly What version of plane, and what is ARMING_REQUIRE set to?

**Comment by magicrub** [comment]
This was an on going problem which I thought i fixed in... v3.5? Please confirm that it is not in the current latest v3.7.

**Comment by expntly** [comment]
@WickedShell @magicrub 

ArduPlane v3.7.0.
ARMING_REQUIRE=1

I see my THR_MIN is at 0, and Q_THR_MIN_PWM=1000 (I use QuadPlane Q_ENABLE=1)

**Comment by magicrub** [comment]
do you have logs to share? Do the logs show PWM out values at their extremes like you see? The problem we fixed before was actually in the PX4io chip and not commanded by the autopilot itself so the logs all showed OK.
