### ISSUE TITLE
Copter: Motor test does not work if MOT_SAFE_DISARMED = 1

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13040]
The Motor test (triggered from MP's MotorTest page) does not work if MOT_SAFE_DISARMED = 1

The issue will likely be somewhere [here in the motor_test.cpp file](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/motor_test.cpp).

**Comment by WickedShell** [comment]
Tagged as VTOL-Plane as quadplane has the same problem.

**Comment by peterbarker** [comment]
A test for this can be added to the autotest suite.

**Comment by rishabsingh3003** [comment]
I tried to reproduce this on SITL + MP by setting MOT_SAFE_DISARM=1, and I could not reproduce the issue. Motor Test worked just fine. Is this still a problem?

**Comment by IamPete1** [comment]
@rmackay9 I cant re-produce either. I suspect this has been fixed at some-point.

**Comment by rmackay9** [comment]
ok, closing!
