### ISSUE TITLE
Copter: save and replicate photographs in the same point

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#1306]
This is a much-requested feature that unfortunately does not currently exist in APM Copter.
In geological survey there's often the need for photo shoots in the air in exactly the same waypoint in different time, for example every month or year, in the same compass direction and with gimbal tilted in exactly the same spot.
It would be interesting to implement in the function "camera trigger" a system that save in the flashlog (or tlog) every time you do manually a photo shoot this data:
- gps coordinates
- altitude
- compass direction
- pwm value of the gimbal pitch output
- pwm value of the gimbal roll output
- pwm value of the gimbal pan output

Of course then there should be the possibility to be extracted these data from the flashlog and translate them into an automated mission, so that the drone in future will bring exactly the same points and execute all the wanted shots automatically.

Bests, Marco

**Comment by enjoybeta** [comment]
I think it can be closed since I found log_picture() in AP_camera.cpp
