### ISSUE TITLE
AP_BattMonitor: add logging of cycle count (and other health data) to onboard logs

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13061]
As part of the review of this PR https://github.com/ArduPilot/ardupilot/pull/13035 which adds support for retrieving the "cycle count" of the battery, we decided that it would add value if we logged this and perhaps other health data to the onboard logs.  This data does not update very often so it is probably sufficient to log the information once per log file perhaps at the same time as we log the CPU's serial number.

**Comment by TunaLobster** [comment]
This was completed with #16167.

**Comment by peterbarker** [comment]
Thanks @TunaLobster (and @hendjoshsr71 I guess :-) )
