### ISSUE TITLE
Mavftp:  Bad file time attribute

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#13079]
![image](https://user-images.githubusercontent.com/16251761/71138480-a2a50400-2246-11ea-9f9c-ce45a7c28f7a.png)

### Bug report

**Issue details**

 download file via mavftp, got bad file time attribute

**Version**
master branch

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[*] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

**Hardware type**

**Logs**

**Comment by IamPete1** [comment]
same as https://github.com/ArduPilot/ardupilot/issues/12046 when downloading via MP it sets the dates. I'm going to close this in favor of that one.
