### ISSUE TITLE
Rover: MOT_SLEWRATE limits

### ISSUE THREAD

**Issue by jimovonz** [ArduPilot/ardupilot#13075]
### Bug report

The actual slew rate achievable using the MOT_SLEWRATE parameter does not seem to correspond with stated range of 0-1000 percent throttle per second. The line in the code found [here](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/AP_MotorsUGV.cpp#L218):

`   
 const float throttle_change_max = MAX(1.0f, (float)_slew_rate * dt);
`

limits the minimum delta to 1 percent of throttle per loop cycle. For the Rover default of 50Hz, this equates to 50% throttle per second - any parameter values less than 50 results in the same slew rate of 50. For faster loop rates the minimum possible slew rate is higher - for instance, at 400Hz the minimum achievable rate is 400% throttle per second. I do not see the intended purpose of this line of code as there is already check for parameter values of zero or less and it certainly does nothing to enforce an upper limit. Perhaps this line should read: 

`
    const float throttle_change_max = MIN(1000.0 * dt, (float)_slew_rate * dt)
`

which results in slew rates that cover the stated range and no more.

**Version**
Rover-4.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Airframe type**
NA

**Hardware type**
NA

**Logs**
NA - reproducible in SITL using current master

**Comment by jimovonz** [comment]
This bug is still present in master...

**Comment by jimovonz** [comment]
Pull request: https://github.com/ArduPilot/ardupilot/pull/14843

**Comment by IamPete1** [comment]
fixed by https://github.com/ArduPilot/ardupilot/pull/14890/files
