### ISSUE TITLE
Plane: Allow Pre-Arm check pass without compasses

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#13110]
### Bug report

**Issue details**
When using plane without a compass, the INS pre-arm check will not pass... according to https://discuss.ardupilot.org/t/ahrs-not-healthy-on-arm/50239/

I recommend NOT disabling INS pre-arm checks in order to pass; we should allow passing, but maybe write a status text indicating that no compasses are enabled when arming.

**Version**
Plane 4.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
All

**Hardware type**
Presumably Matek

**Logs**
None given in the discuss topic.

**Comment by kd0aij** [comment]
I think setting COMPASS_USE to zero is a reasonable way to indicate that no compass is present, and in that case, the INS prearm check should pass.

**Comment by peterbarker** [comment]
@kd0aij That's current behaviour, isn't it?

So can we close this?

**Comment by kd0aij** [comment]
If @Naterater agrees...

**Comment by Naterater** [comment]
I guess this is still an issue: https://discuss.ardupilot.org/t/ahrs-not-healthy-on-arm/50239/8?u=naterater
