### ISSUE TITLE
Copter: SSD1306 onboard display not working with CubeOrange

### ISSUE THREAD

**Issue by zenuavsolutions** [ArduPilot/ardupilot#13127]
#### Issue details
on Cube Orange with the new 4.0.0 Copter release, the SSD1306 does not work

#### Version
Copter 4.0.0

#### Platform
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad

#### Hardware type
Cube Orange

#### Logs
relevant?
![IMG_1452](https://user-images.githubusercontent.com/7430902/71564075-a7658580-2a9a-11ea-947b-f673f1363cbc.jpeg)

**Comment by RJBeckwith** [comment]
I have the same issue with my Cube Orange. Have tried two different SSD1306 displays from the recommended vendors on the AC Wiki. I get the same "snow’ on the screen. It has not worked on any of the Dev or RC versions I have tried, so didn’t expect it to work on 4.0.0.
![Oled Display](https://user-images.githubusercontent.com/17806448/71564616-76b92800-2a69-11ea-9365-3ffa469fad82.jpg)

**Comment by peterbarker** [comment]
This is fixed in master.

**Comment by rmackay9** [comment]
This will be released next week as part of Copter-4.0.1-rc1
