### ISSUE TITLE
Add support for mavlink camera commands

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#13131]
Specifically: MAV_CMD_IMAGE_START_CAPTURE, MAV_CMD_VIDEO_START_CAPTURE and MAV_CMD_SET_CAMERA_MODE. These commands were added to mavlink spec ages ago. I thought I had added an issue somewhere about them but I guess not since I can't find it. QGC uses these in its Waypoint item editor to simplify things. I'm getting reports from ArduPilot users for lack of support.

There is also the change to MAV_CMD_DO_SET_CAM_TRIGG_DIST.param3 which allows you to start triggering immediately instead of after the distance is reached. This allow you to create surveys which have better coverage at the incoming edge of the survey area. QGC always uses this for all the surveys it creates.

**Comment by rmackay9** [comment]
@DonLakeFlyer, thanks for this.  I can't promise when we will implement this but we are trying to improve our gimbal and camera support.

**Comment by peterbarker** [comment]
We now have support for those messages - and the handling of the take-picture-now MAV_CMD_DO_SET_CAM_TRIGG_DIST.param3

We got there... eventually :-)

**Comment by DonLakeFlyer** [comment]
Thanks for letting me know. Let me look if there are things in QGC I need to turn on now. @peterbarker Do you know what ArduPilot version these show up in. I probably need to do a version specific thing.

**Comment by DonLakeFlyer** [comment]
Am I missing MAV_CMD_SET_CAMERA_MODE in the ardupilot source? I can't find support for that one?

**Comment by rmackay9** [comment]
Hi @DonLakeFlyer,

You're right that we don't support that message.  I think one reason could be that I didn't understand what we would do with it.  Some cameras at least (all the Siyi cameras for example) support taking images while recording video so it wasn't clear why would apply a restriction.  .. or maybe AP_Camera should report it's mode (in some message or other) of it's mode which is simply the last thing that it was asked to do (e.g. take a pic or start recording video)?

Sorry, I just didn't know what to do with the message

**Comment by DonLakeFlyer** [comment]
I think it's because of the opposite case: Where cameras only support capture in the corresponding mode. So if the camera is currently in video mode and you want to take a photo you need to change modes. That said, it's kinda up to the camera. 

If a cameras supports the v2 protocol and says it supports mode then SET_CAMERA_MODE from a GCS needs to flow through otherwise you are losing capability. QGC daily handles all the crazy matrix of cap flags. As it stands now QGC will show the mode switch UI if the caps flag say camera supports modes. But then if the user changes modes from the UI, they will get a command failed on the SET_CAMERA_MODE I assume with ardupilot.

Similar problem in missions. Mission is capturing video and then wants to change to photo mode to capture a photo and you can't do it.
