### ISSUE TITLE
Copter: Have ability to hold distance to a wall using facing forward range finder

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#1315]
For snapshots, we need to get as close to a wall. 

However, the dilution of the GPS signal in these circumstances, make the operation dangerous. 

If one adds forward facing horizontal distance hold  , one could solve the problem?

Can we implement it in the same way that althold with range finder facing down handling Z vector, except that here range finder is facing forward and handle X vector?

**Comment by rmackay9** [comment]
Here's the existing to-do item to add object avoidance support: https://github.com/diydrones/ardupilot/issues/131

**Comment by Naterater** [comment]
Avoidance is available now. Is it enough to close this issue?

**Comment by rmackay9** [comment]
@Naterater, we should probably keep this open 'cuz the object avoidance method would keep the vehicle at it's minimum distance (held in AVOID_MARGIN) but this request is to hold at a longer distance.

**Comment by rmackay9** [comment]
We have a [wall climber lua script](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/copter-wall-climber.lua) now that implements this feature.  It can be used along with [GPS/Non-GPS transitions](https://ardupilot.org/copter/docs/common-non-gps-to-gps.html) to do what is being requested.

ArduPilot 4.1 also support backing away from objects based on a lidar (in Loiter mode only) so I think we have this issue covered now so I think I will close this now..
