### ISSUE TITLE
Kakute F7 Mini and Kakute F7 AIO PX4Flow Not Working in Copter-4.0

### ISSUE THREAD

**Issue by NitinJSanket** [ArduPilot/ardupilot#13154]
### Bug report

**Issue details**

Optical flow gives no values in Kakute F7 Mini. Same thing works on Kakute F7 on Copter 3.6.12 though. Copter 4.0.0 has the same issue with kakute F7 too. Also, this is after the fix suggested in https://github.com/ArduPilot/ardupilot/issues/10105.

I also tried deleting all the code in AP_OpticalFlow.cpp to force it to use PX4Flow such that the only code remaining in void OpticalFlow::init(uint32_t log_bit) is backend = AP_OpticalFlow_PX4Flow::detect(*this); and backend->init();. No luck.

**Version**
4.0.0

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X4.

**Hardware type**
Kakute F7 Mini and Kakute F7 AIO.

**Logs**
Cant log on the Kakute F7 Mini. My Kakute F7 AIO SD card shield is broken.

**Comment by Seeelefant** [comment]
Also Cheerson CX-OF Optical Flow is not working.

**Comment by rmackay9** [comment]
We've found an issue with Copter-4.0.0 in which it isn't reporting the optical flow values to the ground station but the sensor itself works.  I'm woindering how you're testing that it doesn't work?  By the way, this should really be raised in the Copter-4.0 forums: https://discuss.ardupilot.org/c/arducopter/copter-40
