### ISSUE TITLE
Help needed in Developing New Controller Options other than PID

### ISSUE THREAD

**Issue by aby03** [ArduPilot/ardupilot#13233]
#### Issue details
_Please describe the problem, or desired feature_
I need to try out some other torque based controllers for my copter other than PID controller. Could you give me some basic outline how can i go about it? I need to implement it for copter specifically. The input to the controller will be yaw, pitch, roll, altitude and output would be pwm outputs to motors

#### Platform
[  ] Copter

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
X quad

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
pixhawk

**Comment by lthall** [comment]
This is not where you ask for support. Please take this to the discuss forums.

**Comment by rmackay9** [comment]
Hi @aby03 

the user support forums are here: https://discuss.ardupilot.org/c/arducopter/copter-40
developers (which it seems like you are) are also welcome to chat here: https://gitter.im/ArduPilot/ardupilot
