### ISSUE TITLE
Copter: add check if only one of MOT_PWM_MIN or MOT_PWM_MAX is set

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13242]
This issue is raised in response to [this report on the forums](https://discuss.ardupilot.org/t/copter-4-0-did-great-thou-scary-with-hexa-failed-motor/50808/9) which involved a user setting the MOT_PWM_MIN parameter (presumably to ensure the output to the motors was never below this value) but failed to set the MOT_PWM_MAX value.

We should add a pre-arm check to ensure that both these valures are either zero or non-zero.  I.e. a situation where only one of them is non-zero should trigger a pre-arm failure.

**Comment by kalaiselvan1219** [comment]
It's on only AC 4.0.0 stable version or will apply for all AC versions.?

**Comment by kd0aij** [comment]
link to report?

**Comment by rmackay9** [comment]
Ah, right, here's the link to the discussion. https://discuss.ardupilot.org/t/copter-4-0-did-great-thou-scary-with-hexa-failed-motor/50808/9

In the end the user's issues are not related to this misconfiguration but we should still add the check
