### ISSUE TITLE
Bug Reprot: Copter: wp_nav requested speed reduce can cause attitude shock

### ISSUE THREAD

**Issue by lukezhqin** [ArduPilot/ardupilot#13251]
### Bug report

You guys would easily met this issue if you change one of your waypoint speed and reduce the request speed in the mission. Then after this do_cmd waypoint take effect in SITL or real filght, the vehicle would definitely make a sudden brake and cause attitude shock just like the following figure shows which is just doing SITL using latest tag version Copter-4.0.0.

![2019-12-23_195410](https://user-images.githubusercontent.com/26009293/72244253-db0ee680-3628-11ea-9fda-435f7f885f82.PNG)
![2020-01-13_170903_tagcopter4 0 0](https://user-images.githubusercontent.com/26009293/72244262-e06c3100-3628-11ea-8eec-441b489324ef.PNG)

I konw it's better to try to update the '_leash' in pos_control.cpp but I actually haven't find a proper way yet. Now, my method in this #13102 may not look elegant enough but it can indeed avoid this waypoint change to reduce speed issue from distance limitation check of '_leash' once we update the speed request from the mission planned.

**I before actually really really really wish this bug to be solved before official Copter-4.0.0 released which would help a lot in my thoughts. But now please help me review the PR and help solve this problem in the future version ASAP. Many thanks.**

**Version**
_tag version Copter-4.0.0, master branch and all versions and branches before_

**Platform**
[  ] All
[  ] AntennaTracker
[×] Copter
[?] Plane
[  ] Rover
[?] Submarine

**Airframe type**
_hex, Y6, octa etc_

**Hardware type**
_SITL, Pixhawk, Cube, Pixracer, Navio2, etc_

**Logs**
_[00000013_copter4.0.0_49693540.BIN](https://drive.google.com/open?id=1__iMgy0DKg8qMt1vCkEQ6z3uxUq-Yl2N)_

**Comment by lukezhqin** [comment]
@tridge @rmackay9 Please help review this issue and PR.

**Comment by bnsgeyer** [comment]
I believe this is the same as issue #11048 and proposed fix is PR #12821

**Comment by rmackay9** [comment]
One of the two possible fixes has been merged to master and should be released with Copter-4.0.4 in a month or so.  Thanks very much for raising this issue!
