### ISSUE TITLE
Copter: add value for recovery throttle after flip

### ISSUE THREAD

**Issue by Christian666** [ArduPilot/ardupilot#1326]
If you are using an overpowered copter, ie. thr_mid ~300, the machine overshoots at least 5-10 meters in heigth after a flip. Add a new variable like flip_recovery_thr in control_flip.pde with default=170 like the flip_thr_inc and make it available in full parameter list. 

line 148 atm:
 // increase throttle to gain any lost alitude
throttle_out += FLIP_THR_INC;

line 148 new:
 // increase throttle to gain any lost alitude
throttle_out += FLIP_RECOVERY_THR;

**Comment by lthall** [comment]
old. open again if someone cares.
