### ISSUE TITLE
Remove AP_Vehicle::set_likely_flying

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#13279]
A lot of the vehicles already have their own internal variables that exactly match this, we should remove the `set_likely_flying` interface and allow a vehicle to maintain any appropriate state it needs. This would just save some code and ram. It wasn't worth adding as a blocker in #13118.

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by peterbarker** [comment]
Turns out that scripting can make use of  this state, so it's sticking around now.... closing this one.
