### ISSUE TITLE
Copter: reduce occurances of "Potential Thrust Loss" messages

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13289]
A few users have noticed the "Potential Thrust Loss" messages appearing on quad copters especially during fast descents ([discussion](https://discuss.ardupilot.org/t/potential-thrust-loss-error/49139/4)).  We should consider reducing how often this message is displayed in order to reduce the risk that users will learn to ignore it.

**Comment by rishabsingh3003** [comment]
A similar recent post here: 
https://discuss.ardupilot.org/t/potential-thrush-lost/55432

**Comment by pompecukor** [comment]
We get that a lot on our old copter, but it is actually on take-off. Right on take off. then it is gone and no more reports.

**Comment by IamPete1** [comment]
We now have a `FLIGHT_OPTION` to turn off the warning all together. So I would be tempted to close this.

**Comment by rmackay9** [comment]
Sounds good, let's close this.
