### ISSUE TITLE
PreArm check text overflow mavlink buffer

### ISSUE THREAD

**Issue by tecnic08** [ArduPilot/ardupilot#13294]
### Bug report

**Issue details**
Low battery prearm text is longer than the size of the mavlink text buffer.
Mavlink status text size is 50, but the prearm text is longer.

I'll create a PR soon.

**Version**
3.6.12

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad-X

**Hardware type**
Pixhawk 4 (fmuv5), Pixhawk 2 (fmuv3)

**Logs**
No log, but photo should be suffice.

![Screenshot from 2020-01-16 13-54-57](https://user-images.githubusercontent.com/2929677/72501279-fcf6ac00-3868-11ea-8207-4f578217dffa.png)

**Comment by rmackay9** [comment]
I thought that [STATUSTEXT](https://mavlink.io/en/messages/common.html#STATUSTEXT) messages didn't need to be null terminated if they were exactly 50 characters long

The "description" says, "Status text message, without null termination character".

**Comment by tecnic08** [comment]
> I thought that [STATUSTEXT](https://mavlink.io/en/messages/common.html#STATUSTEXT) messages didn't need to be null terminated if they were exactly 50 characters long
> 
> The "description" says, "Status text message, without null termination character".

I'm sorry, ignore the part that I say null terminator. However, the  "PreArm: PreArm:..." is causing the string to be longer than 50 characters.

**Comment by tecnic08** [comment]
PR submitted: https://github.com/ArduPilot/ardupilot/pull/13295

**Comment by rmackay9** [comment]
Resolved in Copter-3.6 branch (although it's unlikely to be released) and master so closing.
