### ISSUE TITLE
pip2 cannot install packages

### ISSUE THREAD

**Issue by azhdarshirinzada** [ArduPilot/ardupilot#13307]
### Bug report

**Issue details**

pip2 throw an error when trying install packages from [Set up directories/paths and extra packages in Cygwin](https://ardupilot.org/dev/docs/building-setup-windows-cygwin.html#set-up-directories-paths-and-extra-packages-in-cygwin) section.

**Logs**

$ pip2 install empy pyserial pymavlink
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting empy
  Using cached https://files.pythonhosted.org/packages/3b/95/88ed47cb7da88569a78b7d6fb9420298df7e99997810c844a924d96d3c08/empy-3.3.4.tar.gz
Collecting pyserial
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Collecting pymavlink
  Downloading https://files.pythonhosted.org/packages/45/4f/32e7d87eee88ae96d76d9574dda1e2480e880389d581da1ba2be00d39ef7/pymavlink-2.4.4.tar.gz (3.5MB)
     |████████████████████████████████| 3.5MB 379kB/s
Collecting future (from pymavlink)
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Collecting lxml (from pymavlink)
  Using cached https://files.pythonhosted.org/packages/e4/19/8dfeef50623892577dc05245093e090bb2bab4c8aed5cad5b03208959563/lxml-4.4.2.tar.gz
Installing collected packages: empy, pyserial, future, lxml, pymavlink
  Running setup.py install for empy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-SPWUNN/empy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-SPWUNN/empy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-EVexBA/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-SPWUNN/empy/
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying em.py -> build/lib
    running install_lib
    copying build/lib/em.py -> /usr/lib/python2.7/site-packages
    error: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/em.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-SPWUNN/empy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-SPWUNN/empy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-EVexBA/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Jaaaky** [comment]
This is rather a support issue, please post in forums.
