### ISSUE TITLE
Copter: ESC Sync problem with latest 4.00 Update

### ISSUE THREAD

**Issue by ChristianMultikopter** [ArduPilot/ardupilot#13310]
As mentioned in this Thread:

https://discuss.ardupilot.org/t/esc-sync-problem-with-update-from-3-6-9-to-3-6-10/48261

We had the Sync Problem, it was gone later in a DEV Version of 4.00. But with the stable 4.00 and 4.01 RC2, the problem is back.

Version
Copter-4.0.0

Platform
[ ] All
[ ] AntennaTracker
[×] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

Airframe type
hex, Y6, octa etc

Hardware type
Cube
T-Motor F55A Pro II Brushless ESC 55A 4in1

**Comment by rmackay9** [comment]
We think this is resolved with Copter-4.0.2 so closing.  Thanks again very much for the report!

Here's the beta testing announcement for Copter-4.0.2: https://discuss.ardupilot.org/c/arducopter/copter-40/155
