### ISSUE TITLE
Autoland confusion

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/ardupilot#13338]
I do not know if it is a bug
Hi I am not able to get successful autoland result. Am I overlooking something?
Can someone help?
The plane is a Twin engine AlbaBird
https://www.rcgroups.com/forums/showthread.php?3370815-Finwing-FPV-AlbaBird-Dual-Motor-official-owner-Thread-(easy-Two-hours-flight) 7

It flies well using the latest Arduplane. Hardware Pixhack 2.8.4
[My log here 1](https://drive.google.com/open?id=1kTbxsiPvb5dTPRDHYeTC_VpvbDpUI5MG)
[My param](https://drive.google.com/open?id=1-rT_3yXKKePpqPWk9il05ImaAKl0K3ho)

**Comment by rmackay9** [comment]
I think it's best to raise support issues in the Plane support forums: https://discuss.ardupilot.org/c/arduplane/plane-4-0

Sorry to be strict but we use this github issues list to record confirmed bugs and enhancement requests.
