### ISSUE TITLE
Autotune: Pitch acceleration saved in place of yaw acceleration

### ISSUE THREAD

**Issue by atantot** [ArduPilot/ardupilot#13344]
### Bug report

In autotune, when saving pids to originals, it seems that the pitch acceleration is saved in place of the yaw acceleration.

Link to the code: https://github.com/ArduPilot/ardupilot/blob/33ca2a20dda32bcee7fbdb9c6eae8167294cfdf2/libraries/AC_AutoTune/AC_AutoTune.cpp#L1213

**Comment by rmackay9** [comment]
oh my.  Very well done finding this though, thanks!

**Comment by rmackay9** [comment]
Fixed in master and will go out with Copter-4.0.2 or -4.0.3.  Thanks again!

**Comment by rmackay9** [comment]
This is included in Copter-4.0.2, thanks!

**Comment by atantot** [comment]
You're welcome :) Thank you !
