### ISSUE TITLE
BRD_OPTIONS: Board options - Documentation says 0 is enable

### ISSUE THREAD

**Issue by cardboardboks** [ArduPilot/ardupilot#13354]
### Bug report

**Issue details**

The documentation (https://ardupilot.org/copter/docs/parameters-Copter-latest-V4.0.1-dev.html#brd-options-board-options) states that 0 is to enable the Enable hardware watchdog.
Traditionally 0 would be disable and 1 would be enable. 
I'm guessing this is just a typo.

**Comment by Pedals2Paddles** [comment]
Nope, 0 is correct. There are no other options to select at this time as no other options have been developed.  It will allow for future modification of the watchdog and other board related settings.  But today the only setting is watchdog on.
