### ISSUE TITLE
The link to the Submitting patches wiki in the CONTRIBUTING.md howto is incorrect

### ISSUE THREAD

**Issue by tig987** [ArduPilot/ardupilot#13380]
in the CONTRIBUTING howto
https://github.com/ArduPilot/ardupilot/blob/master/.github/CONTRIBUTING.md
in chapter Submitting patches
the link to the wiki points to URL
http://dev.ardupilot.org/wiki/submitting-patches-back-to-master/
but this is incorrect - Error "The requested URL was not found on this server."

**Comment by auturgy** [comment]
I’ve just pushed a fix. Thanks for letting us know.

Regards,

James

**Comment by auturgy** [comment]
Closed via https://github.com/ArduPilot/ardupilot/pull/13381
