### ISSUE TITLE
TradHeli: add support for tandem helicopters

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#134]
Add support for Tandem rotor helicopters like CH-47 Chinook.  This will be done with a new frame type, #define and TandemHeli.pde.  Will require 6-servo support, CCPM swashplates.

**Comment by fhedberg** [comment]
https://github.com/diydrones/ardupilot/pull/1836

**Comment by fhedberg** [comment]
https://github.com/diydrones/ardupilot/pull/1860

**Comment by R-Lefebvre** [comment]
@fhedberg Can we close this one now?  Didn't you do this, or is it not in yet?

**Comment by fhedberg** [comment]
I guess we can close the issue, but the #1860 pull-request is not in yet.

**Comment by frizensami** [comment]
@fhedberg I'm extremely interested in your #1860 PR, any progress on it? Thanks for all the work :)

**Comment by auturgy** [comment]
Can this be closed? Tandem heli is in AC3.5 https://github.com/ArduPilot/ardupilot/pull/5867
