### ISSUE TITLE
AP_RangeFinder: some noise in TFMiniPlus-I2C

### ISSUE THREAD

**Issue by tatsuy** [ArduPilot/ardupilot#13411]
**Issue details**
I placed TFMiniPlus-I2C at the same place and measured the distance for 3 minutes.
There are a lot of noise in the graph.
![image](https://user-images.githubusercontent.com/16643069/73324758-6de98b00-428f-11ea-9866-f7e369ee445e.png)

I have some TFMiniPlus. And this issue happens in all devices in I2C.
But it doesn't happen using serial mode.

**Version**
ArduCopter V4.0.2-dev (56044b8b)

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Logs**
[00000182.zip](https://github.com/ArduPilot/ardupilot/files/4125984/00000182.zip)

**Comment by lukezhqin** [comment]
I indeed found this i2c issue and I chose to use serial port then ...I thought that i2c is not that reliable as we hope.

**Comment by muramura** [comment]
@tatsuy san.
This driver does the checksum calculation. The data is good and the quality of the distance is judged. I feel this quality judgment is loose. I think it would be easier to consider logging this quality value.

**Comment by peterbarker** [comment]
@muramura that sounds like a good idea.  Do you feel like knocking a patch together to put it into `log_RFND`?

Presumably it will go in as NaN if none is available.

**Comment by tatsuy** [comment]
Do you mean strength value of TFmini?
I logged it.
[00000062_tfminiplus-i2c_noise.zip](https://github.com/ArduPilot/ardupilot/files/4162840/00000062_tfminiplus-i2c_noise.zip)

Strength and distance seem to have little correlation.
![image](https://user-images.githubusercontent.com/16643069/73898870-1621d400-48ce-11ea-8ab9-bf984ab47a5d.png)

**Comment by wood1139** [comment]
The "i2c read" operation will interrupt the timing sequence in TFMiniPlus. Keep the i2c reading frequency lower than the sample rate will solve this problem. When TFMiniPlus is working under 100Hz sample rate, a practice i2c reading frecuency is 40Hz.

**Comment by lukezhqin** [comment]
> The "i2c read" operation will interrupt the timing sequence in TFMiniPlus. Keep the i2c reading frequency lower than the sample rate will solve this problem. When TFMiniPlus is working under 100Hz sample rate, a practice i2c reading frecuency is 40Hz.

@wood1139 ,Hi, is there any proof for this statement?

**Comment by wood1139** [comment]
> > The "i2c read" operation will interrupt the timing sequence in TFMiniPlus. Keep the i2c reading frequency lower than the sample rate will solve this problem. When TFMiniPlus is working under 100Hz sample rate, a practice i2c reading frecuency is 40Hz.
> 
> @wood1139 ,Hi, is there any proof for this statement?

I got this from Benewake F.A.E. and it really works.

**Comment by lukezhqin** [comment]
> > > The "i2c read" operation will interrupt the timing sequence in TFMiniPlus. Keep the i2c reading frequency lower than the sample rate will solve this problem. When TFMiniPlus is working under 100Hz sample rate, a practice i2c reading frecuency is 40Hz.
> > 
> > 
> > @wood1139 ,Hi, is there any proof for this statement?
> 
> I got this from Benewake F.A.E. and it really works.

@wood1139 thanks

**Comment by tatsuy** [comment]
@wood1139 Thank you!
I confirmed that it works.
I tested using 40Hz, 33Hz and 20Hz. and I've decided to use 33Hz.

**40Hz**
![image](https://user-images.githubusercontent.com/16643069/76204431-bf484b00-623b-11ea-947b-423d61ef7e2e.png)
There are still a few noise.

**33Hz**
![image](https://user-images.githubusercontent.com/16643069/76204464-cc653a00-623b-11ea-815d-36c3ce17b6c3.png)

**20Hz**
![image](https://user-images.githubusercontent.com/16643069/76204477-d0915780-623b-11ea-8277-f27ba305c39d.png)
