### ISSUE TITLE
SITL does not start with DJIX and some other frame types

### ISSUE THREAD

**Issue by rishabsingh3003** [ArduPilot/ardupilot#13412]
### Bug report

**Issue details**

When I enter the following command - 
` sim_vehicle.py -v ArduCopter -f djix  --map --console`
It gives the following error:

![image](https://user-images.githubusercontent.com/36970042/73332878-20205300-428e-11ea-9f97-2242c6f43c60.png)

Neither can I find the "default_params/copter-djix.parm" anywhere. Is this a bug? Forgive me if I am doing something wrong. I have noticed a similar issue for a few other frames. 

**Version**
Master

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by auturgy** [comment]
It just means that no one has pushed a parameter file for those frame types.
You can either start sitl with defaults and then set your own parameters, or generate a parameter file and pr it.

Regards,

James

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/19010
