### ISSUE TITLE
Copter: migrate to always use MOT_PWM_MIN/MAX

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13421]
Multicopters currently use the RC3 (or more accurately throttle input) for the output range to the ESCs.  We should migrate to always use the MOT_PWM_MIN/MAX values to improve separation between inputs and outputs.  In particular this improves safety because users would not need to re-calibrate the ESCs after they've recalibrated the RC input.

Changes required are probably:

- add parameter conversion/initialisation of MOT_PWM_MIN and MAX if they have not been changed from their defaults (which is zero):
   - if RC3_MIN and MAX (or more accurately whatever channel is used for throttle input) have been changed from their defaults, set MOT_PWM_MIN/MAX to these values
   - if RC3_MIN and MAX have not been changed from their defaults, set MOT_PWM_MIN = 1000, MOT_PWM_MAX = 2000
   - this logic above should mean that:
        - the MOT_PWM_MIN and MAX values are only automatically set once
        - existing vehicles should see no change in the output range used when upgraded
        - new builds should end up using an output range of 1000 to 2000
- modify [AP_Motors_Multicopter:: get_pwm_output_min()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Motors/AP_MotorsMulticopter.h#L84) and get_pwm_output_max() so they simply return the values from the parameters or perhaps local copies of the param values post sanity checks.
- remove AP_Motors::_throttle_radio_min and _throttle_radio_max.  It looks like there's an existing issue where AP_Motors6DOF is incorrectly using these values instead of using get_pwm_output_min()/get_pwm_output_max().
- extend the existing pre-arm check to ensure MOT_PWM_MIN/MAX are not zero

**Comment by rmackay9** [comment]
We discussed this on the 12-May-2021 dev call and noticed that the 2nd point, "if RC3_MIN and MAX have not been changed from their defaults, set MOT_PWM_MIN = 1000, MOT_PWM_MAX = 2000" could actually cause problems because if users had turned off their arming checks they might be using the 1100~1900 range for rc3 input and thus motor outputs and so changing MOT_PWM_MIN/MAX to 1000/2000 would cause a change in the range output to the motors and could lead to a motor stopping in flight.

**Comment by MallikarjunSE** [comment]
I feel users must be instructed to use MOT_PWM_MAX & MIN and remove use of RC3_MAX & MIN all together. 
I had a situation a month ago where I had initially setup copter with RC3 endpoints and when I put fixed PWM(flame ESC 1100-1940), the motors were beeping until I made ESC calibration again for MOT_PWN_MAX & MIN. 
Setup instruction should be like, Fix MOT_PWM_MAX & MIN and ESC calibration then forget it irrespective of change in RC.

**Comment by rmackay9** [comment]
FYI this is listed in the Tuning Process Instructions wiki but perhaps it should go on the [ESC calibration page](https://ardupilot.org/copter/docs/esc-calibration.html).
