### ISSUE TITLE
Arduplane 4.0.3 LAND_DISARMDELAY,  LAND_THEN_NEUTRL do not work

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/ardupilot#13433]
Bug report

**Issue details**
LAND_DISARMDELAY
LAND_THEN_NEUTRL
These do not work as prescribed in the wiky. After autoland the servos continued to move even though these parameters were set in order to stop their movement

LAND_DISARMDELAY
After a landing has completed using a LAND waypoint, automatically disarm after this many seconds have passed. Use 0 to not disarm.
LAND_THEN_NEUTRL: Set servos to neutral after landing
When enabled, after an autoland and auto-disarm via LAND_DISARMDELAY happens then set all servos to neutral.

**Version**
Arduplane 4.0.3 

**Platform**
Plane

**Airframe type**
A plane elevator rudder ailerons

**Hardware type**
Pixhack 2.8.4

[LOGS.zip](https://github.com/ArduPilot/ardupilot/files/4135897/LOGS.zip)

**Comment by IamPete1** [comment]
It does not disarm so never puts the servos to neutral. This is because you have `ARMING_REQUIRE` = 0.
