### ISSUE TITLE
AP_Motors: add CW_X for Hexa, Octa, OctaQuad

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13440]
We've got the [MOTOR_FRAME_TYPE_CW_X](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Motors/AP_Motors_Class.h#L60) implemented for quad frames but we should also implement it for Hexacopter, Octacopters and OctaQuadcopters.

Hexacopters and Octacopters are probably pretty straight forward, for OctaQuadcopters the top motor should be before the lower motor.  I.e. top front-right motor should be 1, bottom front-right should be 2, top back-right should be 3, etc..

We could also do Dodecahexa copters although the existing "X" implementation is the same.  So we could just have the case CW_X: just below the existing case X.

**Comment by rmackay9** [comment]
@rishabsingh3003 this one is quite similar to the PR you did a couple of days ago so this might be a good one for you.  No pressure though.

**Comment by rishabsingh3003** [comment]
@rmackay9 I would like to work on it! Will submit a PR soon. Thanks :)
