### ISSUE TITLE
Rallypoints do really belong in a mission plan.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#1345]
A Rallypoint needs to be limited by RALLY_LIMIT_KM
Also, they are programmed separatly. 
This opens for a bunch of errors, - some limits may need to be high, other times, there is a good chance of points being forgotten.

If they were moved to a mission plan, we could manage them using a lot more tools, and be more aware of them.

**Comment by abvgeej** [comment]
But what shall we do if there is no rallypoint in the range and we need to RTL?
And i am sure it should be possible to place a rallypoint in a mission plan, but they should not be completely moved there.
Its convinient when you can set up a huge map of safe landing points "all across your town" and forget about it. storing it completely separately from whatever mission you might be having right now.

**Comment by WickedShell** [comment]
Closing as this is really a GCS/presentation issue, rather then an autopilot issue. A GCS can make a list of rally points feel like a part of the mission, and has the flexibility to offer a lot of helpful tools. By keeping the rallys separate though we support other use cases such as the one abvgeej outlined.
