### ISSUE TITLE
Rover: add Loiter turns / circle mode

### ISSUE THREAD

**Issue by 3Denis** [ArduPilot/ardupilot#13466]
Loiter turns (aka circle mode) would be a great feature for Rover. Especially boats could benefit from that mode.

[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Comment by tzarjakob** [comment]
Can I work and be assigned on this one? I am also interested in this feature

**Comment by rmackay9** [comment]
@tzarjakob,

Sounds good.  Feel free to just start working on it and raise a PR when you're ready though, we don't often assign issues but instead the first PR to address the issue goes in.

**Comment by tzarjakob** [comment]
Ok perfect

**Comment by rmackay9** [comment]
We've added circle mode now to rover with PR https://github.com/ArduPilot/ardupilot/pull/23890
