### ISSUE TITLE
SITL should advise model options

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#13493]
This sitl message could be a lot more helpful by listing the options:
```
➜  ardupilot git:(master) ./build/sitl/bin/ardusub 
You must specify a vehicle model
```

`--help` output also does not show the options.

**Comment by jaxxzer** [comment]
Another thing that would be helpful to include in `--help` is the syntax for the `--uartX` options: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_SITL/UARTDriver.cpp#L73

**Comment by rishabsingh3003** [comment]
The entire list, especially for copter is quite big. I am not sure if we should include everything on the list? I think just one example per vehicle?
