### ISSUE TITLE
Copter: support variable pitch multicopters

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#135]

**Comment by R-Lefebvre** [comment]
No, has not been solved.  This is a complicated one for sure.  The crux of the problem is what happens with yaw reaction when the blade pitch is near zero.

This Issue would require a developer to have hardware to work with.

**Comment by auturgy** [comment]
Implemented.  https://github.com/ArduPilot/ardupilot/pull/6847
Close please.
