### ISSUE TITLE
Copter: allow throttle assist to be used in PosHold mode

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1353]
During AC3.2 testing a few users (nickthecook, Marco, George Randall, steveF11music) requested that PosHold should have a more natural feeling throttle (i.e. similar to stabilize) to better match the natural feeling roll and pitch of PosHold.
This could probably be accomplished by making Drift mode's throttle assist available in PosHold mode.  Note though that it would likely need to be optional because some users like the very sold alt-hold that's in AC3.2's PosHold mode.

**Comment by rmackay9** [comment]
pushing to AC3.4.  We're simply out of time for AC3.3.

**Comment by rmackay9** [comment]
I'm not sure when we're even going to get to this.  I'm not sure there's much demand.  In any case, we're out of time for AC3.4 so bumping to AC3.5.

**Comment by auturgy** [comment]
Stale / overtaken by events.  Tuning and pilot feel has evolved significantly since 2014.  Users should tune input shaping to their desired feel (https://ardupilot.org/copter/docs/input-shaping.html#input-shaping).
