### ISSUE TITLE
Firmware.ardupilot.org: make it easier to determine if all binaries have been built

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13532]
It's quite difficult to determine if all binaries have been built by looking at [firmware.ardupilot.org](https://firmware.ardupilot.org/Copter/beta/).

For example I have [this support request](https://discuss.ardupilot.org/t/copter-4-0-2-rc4-available-for-beta-testing/52008/26) in which a user says they can't download the beta binary but the only way that I know of to independently determine if all the binaries have been updated is to go through each directory one-by-one.

In discussion with @tridge and @peterbarker recently we found that changing the web based file viewer back to the default allowed sorting the directories by update date which would (I think) allow me to determine if all binaries had been updated.

**Comment by Pedals2Paddles** [comment]
Could whatever script is populating the files on the server create a running log that shows what it has spit out, preferably with most recent on top?  A CSV would be kind of useful and easy to analyze.

**Comment by rmackay9** [comment]
Related issue here: https://github.com/ArduPilot/ardupilot/issues/13132

**Comment by peterbarker** [comment]
@MichelleRos did this for us with `build_sizes.html` years ago,  Thanks Michelle!
