### ISSUE TITLE
Copter/Sub: Rename SYSID_SW_MREV to FORMAT_VERSION

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13546]
The SYSID_SW_MREV and FORMAT_VERSION parameters are there to force parameters to be wiped when users load a different vehicle firmware to the autopilot.

We should consolidate the name of this parameter across vehicles so they are consistent.

I've added DevCallTopic so we can decide which parameter name we want to use

EDIT: on the dev call we decided that we should call the parameter FORMAT_VERSION (although it's still not a great name)

**Comment by WickedShell** [comment]
Personally I find `SYSID_SW_MREV` to be a really confusing name for the param representing the internal storage format version number... Not saying `FORMAT_VERSION` is necessarily correct, I just think it's a lot less confusing then the other currently used one.

**Comment by tridge** [comment]
i'd be happy with either one

**Comment by rmackay9** [comment]
The nice thing about SYSID_ is that it hides the parameter in amongst other very rarely touched parameters while FORMAT_VERSION hangs out on it's own in the list.  I agree that it's not an easy to understand name though.

**Comment by rmackay9** [comment]
The bad thing about SYSID_SW_MREV is that it's not a mavlink system id which all the other parameters are that start with SYSID_.  if we were picking the parameter name again I'd probably call it BRD_EEPROM_FMTID or something similar.

FORMAT_VERSION is also not a great name 'cuz it's missing the most important thing which is the system that it applies to, i.e. eeprom!

**Comment by auturgy** [comment]
You might have answered your own question there Randy: new param name sounds sensible

**Comment by rmackay9** [comment]
@auturgy, I suppose although I hate to make @meee1 handle yet another parameter rename.

**Comment by peterbarker** [comment]
On Mon, 10 Feb 2020, Randy Mackay wrote:

> The bad thing about SYSID_SW_MREV is that it's not a mavlink system id which all the other parameters are that start with SYSID_. if we were picking the
> parameter name again I'd probably call it BRD_EEPROM_FMTID or something similar.
> 
> FORMAT_VERSION is also not a great name 'cuz it's missing the most important thing which is the system that it applies to, i.e. eeprom!

It probably *should* be BRD_ - but we store this value as a parameter 
rather than in any sort of magic.  We then format *all* of storage if it 
is different - not just the parameters but *everything*...  So yeah, it's 
all a bit strange....

Not sure what that means in terms of naming, 'though :-)

EEPROM_FMT_VER?

**Comment by rmackay9** [comment]
@peterbarker, not a bad name but then what will we do if we move parameter storage to the SD card? :-)
