### ISSUE TITLE
WS2812B (NeoPixel) Notify Sync loss

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/ardupilot#13563]
NeoPixels sometimes get out of sync with other notify LED's. They look to sometimes not get the correct command but will re-sync later. This seems to be related to IO load, it is reported to get worse when more serial ports are used. More info here:

https://discuss.ardupilot.org/t/ws2812b-neopixel-integration/48580/56?u=iampete
https://drive.google.com/file/d/18cYoKydri3AWCNSzsWD8SwTqXV0C41gy/view?usp=drivesdk
https://discuss.ardupilot.org/t/ws2812b-neopixel-integration/48580/74?u=iampete

**Comment by MallikarjunSE** [comment]
Hey @IamPete1 
I'm using Pixhawk 1 with fmuv2 firmware. My board is 1MB flash one. If you insist, I can try on CubeBlack or CubeOrange.
https://drive.google.com/open?id=12DvWVjWsykdbETWoXRXrgslGnfiLS377

**Comment by MallikarjunSE** [comment]
If possible we should add NTF_NEO_LEN to upcoming version of Arducopter. This is only available in AC4.0.3dev

**Comment by Another-Taipan** [comment]
I am using AP ver 4.0.3-dev on a Pixhawk 1 with fmuv3 firmware (a Pixhawk 2.4.8 with 2MB flash) and experience this same issue.
