### ISSUE TITLE
Copter: more wiki updates ahead of AC3.2

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1357]
- [x] 1. update battery failsafe page to show that RTL can be selected as an option (MP needs an issue added to show this in the drop-down as well)
- [ ] 2. Add SD card mention to this wiki page.  http://copter.ardupilot.com/wiki/common-pixhawk-wiring-and-quick-start/  (from Gary).
- [x] 3. external LEDS wiki page: http://copter.ardupilot.com/wiki/nav-leds/
- [x] 4. mission command list needs to mention that if do-set-roi's params all set to zero this ends the do-set-roi
- [x] 5. the compassmot has moved to be done over mavlink.  http://copter.ardupilot.com/wiki/ac_compasssetupupadvanced/#Compassmot_8211_compensation_for_interference_from_the_PDB_ESC_motors
- [x] 6. Pixhawk's BRD_PWM_COUNT parameter.  Perhaps add a description to the servo and/or relay wiki pages.  http://copter.ardupilot.com/wiki/common-relay/
- [x] 7. add new pre-arm checks to this page: http://copter.ardupilot.com/wiki/prearm_safety_check/
- [ ] 8. mission page: http://copter.ardupilot.com/wiki/common-planning-a-mission-with-waypoints-and-events/
- [x] 9. update radio/throttle failsafe page to mention the sends-no-signal variety of receiver
- [ ] 10. update Sport mode page. https://github.com/diydrones/ardupilot/issues/1064
- [x] 11. add PosHold to the flightmode landing page. http://copter.ardupilot.com/wiki/flight-modes/

**Comment by R-Lefebvre** [comment]
Pretty sure this can be closed.

**Comment by OXINARF** [comment]
@rmackay9 There are a couple of unchecked items in this list, but this is really old, can it be closed?

**Comment by peterbarker** [comment]
Really, really old.  Closing.
