### ISSUE TITLE
Plane: Add RCx_OPTION for Preflight Calibration

### ISSUE THREAD

**Issue by JoshWelsh** [ArduPilot/ardupilot#13593]
Having "Preflight Calibration" be an option for RCx_Option would be awesome, we could then trigger this from the radio when ready rather than being required to invoke it from the GCS.

**Describe the solution you'd like**
Provide as one of the options available in RCx_Option; primary use-case for me would be to zero out the airspeed sensor on a Plane, but having this available for all systems so that you can re-init Gyro, Accel, and Baro would be a good idea too.. Thanks @Pedals2Paddles for the question on that!

**Describe alternatives you've considered**
Mavlink command from Yaapu would be one alternative but isn't realistic as a solution for all applications, as not all RF links will support two-way telemetry through FrSky.

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Additional context**

**Comment by peterbarker** [comment]
On Mon, 17 Feb 2020, Josh wrote:

> Having "Preflight Calibration" be an option for RCx_Option would be awesome, we could then trigger this from the radio when ready rather than being
> required to invoke it from the GCS.

Which preflight calibration?

**Comment by Pedals2Paddles** [comment]
Also, why not call vehicles?  For example, gyro drift while warming up and baro drift with pressure is an all vehicles problem.

**Comment by JoshWelsh** [comment]
@peterbarker the one I'm most specifically interested in is the one for the Airspeed sensor, but I don't think I was aware that there were more than one.  My request would be for the switch to do whatever the Preflight-Calibration does to the target vehicle.

@Pedals2Paddles Matt good call, I hadn't considered that.  I was focused primarily on that airspeed sensor calibration being performed while I had a cover on the pitot-static port, but I hadn't really thought far enough ahead to think about the gyros and baro drift.  Glad you brought that up!  I am editing the original post to comment on that.

**Comment by EERomeo** [comment]
I had the same suggestion a few months ago, you can see here the whole discussion:
[https://github.com/ArduPilot/ardupilot/issues/12704](url)

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/12704
