### ISSUE TITLE
TradHeli: implement stability patch for tradheli servos

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#136]

**Comment by fhedberg** [comment]
@rmackay9 What is this?

**Comment by R-Lefebvre** [comment]
I believe what is desired, is that when any of the servos are driven beyond their full travel range, there will be a recalculation done to prioritize cyclic over collective.  For example, decreased collective travel to allow full cyclic range. This is done in the multirotor code already.  I've never bothered to implement it for a number of reasons.

1) Most helicopter setups are designed such that this shouldn't happen.  You should be able to have full cyclic and full collective together.

2) Helicopters have such vastly higher dynamic range than multicopters, it just didn't seem like an important problem to tackle.

3) I'm not sure... if a helicopter control system was not capable of handling full cyclic with full collective at the same time, should Cyclic really be given priority?

**Comment by ChristopherOlson** [comment]
This is a very old issue. And I don't think it's valid due to the only way it could be a problem is if a user has a bad mechanical setup. It is pointless to try to compensate for a bad mechanical setup in software. So I'm closing it.
