### ISSUE TITLE
AP_Proximity: add parameter to allow user to specify maximum reliable distance

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13612]
Unlike the rangefinder library, the proximity library does not have a user configurable maximum distance.  We should add parameters for minimum and maximum reliable distances.

Here are some options for the names of these new parameters:

- PRX_DIST_MAX, PRX_DIST_MIN (this is probably my favourite, these distances would be in meters)
- PRX_MAX, PRX_MIN
- PRX_MAX_CM, PRX_MIN_CM (consistent with AP_RangeFinder's parameter names)

**Comment by amilcarlucas** [comment]
I vote for the first

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/6583
