### ISSUE TITLE
Plane: Poor multi-link telemetry performance after upgrade from plane 3.9 to 4.0

### ISSUE THREAD

**Issue by MartinSollie** [ArduPilot/ardupilot#13625]
**Issue details**
The message rate and usability of multiple links appear to have become significantly worse after upgrading from plane 3.9 to 4.0.

Setup details: We are using a Pixhawk 1 with serial 1 connected to a SiK radio (57600 baud), serial 2 connected to an onboard Odroid XU4 (921600 baud) and serial 4 connected to a router used for an Ubiquiti Rocket M5 radio (115200 baud). 
On the ground we are using another SiK radio and a Rocket M5 connected to Mavproxy, which is then connected to MissionPlanner using TCP. The onboard Odroid sends commands to stream position, attitude and more at 25Hz.

With plane 3.9.11, this setup works alright for all links, although scheduling problems is apparent in the 25Hz position data, as the time between messages often increase with intervals corresponding to 1 loop (0.02s at 50Hz default loop rate), such that the time between messages regularly increase to 0.04, 0.06, 0.08s and such. With plane 4.0.3, this data drops to a rate of only ~2.5 Hz, but often has dropouts for several seconds (see plots below). Another way this problem is apparent is when loading parameters after connecting to MissionPlanner. With 4.0.3, this sometimes stops early and does not finish, or is just slower than usual. This has not occured with 3.9 for us.

Increasing SCHED_LOOP_RATE from the default 50 to 400 (default for copter) solves the problem, and all links work well. This parameter however cannot simply be increased as it also affects other things such as flight control, but probably means that copter users will not encounter the problem.

Today we also tested this with a Durandal, which works a lot better, although this still shows improvements when increasing SCHED_LOOP_RATE.

The problem is most likely related to https://github.com/ArduPilot/ardupilot/issues/13530 and https://github.com/ArduPilot/ardupilot/issues/12077#issuecomment-523222846, and the problems described on the forum [here](https://discuss.ardupilot.org/t/telem1-vs-telem2-getting-messages-from-pixhawk/51789).

Here are some plots showing the time between position messages, requested at 25Hz (so ideally the difference in timestamp should be 0.04s), from the onboard computer. Using the timestamps from this will introduce some jitter, but the difference is still very visible.
<img width="504" alt="Skjermbilde 2020-02-20 kl  14 48 26" src="https://user-images.githubusercontent.com/5480498/74939414-2074bf80-53f0-11ea-9d70-f5167653db20.png">
<img width="553" alt="Skjermbilde 2020-02-20 kl  14 05 25" src="https://user-images.githubusercontent.com/5480498/74938114-ae9b7680-53ed-11ea-9baf-e6506d320ecf.png">
<img width="497" alt="Skjermbilde 2020-02-20 kl  14 28 42" src="https://user-images.githubusercontent.com/5480498/74938129-b3602a80-53ed-11ea-85ec-8ff4c1cf9345.png">
<img width="561" alt="Skjermbilde 2020-02-20 kl  14 06 41" src="https://user-images.githubusercontent.com/5480498/74938100-aba08600-53ed-11ea-8124-7e851b6e240b.png">
<img width="556" alt="Skjermbilde 2020-02-20 kl  14 07 07" src="https://user-images.githubusercontent.com/5480498/74938083-a5120e80-53ed-11ea-88d8-13d971595ca8.png">

**Version**
_What version was the issue encountered with_
ArduPlane 4.0.3 (but I suspect this problem was introduced in the first 4.0.0 beta).

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Does not matter, this issue is visible also on ground without flying.

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Pixhawk 1, Durandal

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by peterbarker** [comment]
This may have been fixed with https://github.com/ArduPilot/ardupilot/pull/13662/commits

This did not make the Plane 4.0.5 stable, but it would be good to know if it fixes your issues as we can then stop looking for more problems.

**Comment by peterbarker** [comment]
@MartinSollie there's a Plane beta out which contains a fix for poor telemetry performance.  Is it easy for you to check to see if it fixes the problem you've been seeing?

**Comment by IamPete1** [comment]
No update from @MartinSollie, @peterbarker thinks its fixed.
