### ISSUE TITLE
Plane: implement set-target-location for Lua scripting

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13666]
PR https://github.com/ArduPilot/ardupilot/pull/13601 adds support for a Lua scripts to move a Copter or Rover to a specified lat/lon/alt.  We can extend this to work for Plane by implementing the AP_Vehicle::set_target_location method in Plane.

**Comment by rishabsingh3003** [comment]
@rmackay9 I think this was already added in this commit here https://github.com/ArduPilot/ardupilot/pull/13742/commits/f612358f4d0e03f3ee125c25bb5440ab942fac71? Thanks.

**Comment by hendjoshsr71** [comment]
Closing. Fixed here #13742
