### ISSUE TITLE
Rover: send text warning to user if they try to calibrate accels or compass while armed

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13663]
If a user tries to start an accelerometer or compass calibration while the vehicle is disarmed we should send a warning message to the user to tell them why the calibration won't start.

This is especially important on Rover which allows the user to disable the requirement for arming.  TBH, I'm not a fan of being able to disable arming but if we're going to continue to allow this then we should send a warning when the calibration can't be started

This issues is raised because of this discussion in the forums: https://discuss.ardupilot.org/t/here2-here-compass-problems-solved/52715

**Comment by rishabsingh3003** [comment]
Hi! Please assign this issue to me. I'd like to submit a patch for it. 
If I understand correctly, `gcs().send_text` is to be used to alert the user at GCS, in case they try to calibrate after arming the vehicle?
Thanks

**Comment by rmackay9** [comment]
@rishabsingh3003,

Yes, that's right.  Somewhere I think there should be somewhere in the compass calibration and accel calibration code that checks if the vehicle is soft armed.  Wherever that check is we should add a sent-text I think.
