### ISSUE TITLE
QuadPlane: improve landing detection by using filtered acceleration

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13664]
QuadPlane uses a similar landing detection algorithm as copter.  We should implement this recent (small) improvement https://github.com/ArduPilot/ardupilot/pull/13639 that was done for Copter which involves adding some filtering to the accelerations used in the update_throttle_mix method.

**Comment by IamPete1** [comment]
@rmackay9 I wonder if we can close this now? the linked plane PR is merged.

**Comment by peterbarker** [comment]
> @rmackay9 I wonder if we can close this now? the linked plane PR is merged.

Agreed, patch has been applied.
