### ISSUE TITLE
Relative aiding cannot be started for non-gps-navigation with wheel encoders, invalid comparison in readyToUseBodyOdm

### ISSUE THREAD

**Issue by pavloblindnology** [ArduPilot/ardupilot#13677]
## Bug report

**Issue details**
Relative aiding cannot be started for non-gps-navigation with wheel encoders.
The reason is because the next line always returns false
https://github.com/ArduPilot/ardupilot/blob/c6f12e519bb821db882be2875c6756f165a9a005/libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp#L429
Which, in turn, is because the latest wheel encoder reading `wheelOdmMeasTime_ms` is always a few ms fresher than the latest IMU reading `imuSampleTime_ms`, while the comparison is made for unsigned integers.
Casting the difference to signed integer solves the problem
`bool wencDataGood = ((int)(imuSampleTime_ms - wheelOdmMeasTime_ms) < 200);`

**Version**
ArduRover V4.0.0-rc2

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[*] Rover
[  ] Submarine

**Airframe type**
Rover

**Hardware type**
Pixraptor

**Comment by rmackay9** [comment]
Thanks very much for this report.  We've finally fixed the issue in master.
