### ISSUE TITLE
Copter: investigate Mode::get_alt_above_ground_cm()

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13675]
Copter's [Mode::get_alt_above_ground_cm()](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.cpp#L509) function's returns and altitude but it depends upon whether the vehicle is actively controlling it's horizontal position or not.  It seems very unintuitive that the return value should depend upon this. This issue was originally brought up by @peterbarker.

This question has been resolved:

- [x] it seems possible that the return value could be an uninitialised value off the stack if not navigating and the terrain database is disabled

**Comment by hendjoshsr71** [comment]
Looks like this was resolved. Reopen if I'm incorrect.
