### ISSUE TITLE
AP_RangeFinder: add support for SLEMTECH S1 Lidar (360 degree)

### ISSUE THREAD

**Issue by RoboDD** [ArduPilot/ardupilot#13687]
## Feature request
**Capability of SLEMTECH S1 Lidar (360 degree)**

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
**The S1 lidar is veery similar to RPLidar A2 360 degree lidar. The S1 lidar can get distance of 40 meters (twice than A2) and light-weight of 100g (almost a half weight of A2).**

There might be few lines of code need to be changed!

**Platform**
[  ] All
[  ] AntennaTracker
[√] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by EosBandi** [comment]
I just got my S1, the only difference is that it does not send out anything after reset. So ideally the change in the driver is only a couple lines of code (if keep using it in compatibility mode). Will do a flight test in the upcoming week(s) and then check in the changes to the driver.

**Comment by EosBandi** [comment]
PR added https://github.com/ArduPilot/ardupilot/pull/14527

**Comment by rmackay9** [comment]
ArduPilot 4.5 includes support for the S1 (see PR https://github.com/ArduPilot/ardupilot/pull/23749) so I'll close this, thanks!
