### ISSUE TITLE
Terrain upload spec 

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot#13691]
**Issue details**

Cross posting: https://github.com/mavlink/mavlink/issues/1314

**Version**
Master

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
All

**Comment by rmackay9** [comment]
I think we can go ahead and close this.  It's really a mavlink issue and I've answered on the other issue.
