### ISSUE TITLE
Loop-rate scheduled tasks always slip at 800Hz

### ISSUE THREAD

**Issue by andyp1per** [ArduPilot/ardupilot#13757]
I added a dummy callback to the runcam driver (doesn't matter where it is this was just convenient):

```
void AP_RunCam::dummy() {
}
```
I then included this in the vehicle schedule table at the loop rate:
```
SCHED_TASK_CLASS(AP_RunCam, &vehicle.runcam, dummy, LOOP_RATE, 50)
```
I then set ```SCHED_DEBUG = 2``` and ```SCHED_LOOP_RATE = 800```

The empty task is then reported to always slip:

```
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
Scheduler slip task[51-dummy] (2/1/50)
```

My suspicion is that this is because 800Hz is close to the backend IMU rate of 1000Hz. 800Hz gives a tick length of 1250us and the IMU period is 1000us. Since we always wait for an IMU sample before scheduling the next tick if we overrun by 250us I think we will always slip loop rate tasks. Just a theory.

@tridge @peterbarker I could use some help figuring this out

**Version**
4.0.4-dev

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
All

**Hardware type**
Tested on an omnibusF4pro

**Comment by andyp1per** [comment]
Effectively fixed by https://github.com/ArduPilot/ardupilot/pull/13758

**Comment by IamPete1** [comment]
fixed by https://github.com/ArduPilot/ardupilot/pull/13741
