### ISSUE TITLE
FLAPs with AILERON MIX. Could it be possible?

### ISSUE THREAD

**Issue by taedla01** [ArduPilot/ardupilot#1376]
Hello everyone,

On first, sorry if this is not the correct place for post this. Too much changes in Ardupilot world since my last post on DIYDrones @2012. So please be patient, my English and ilusion is actually very lazy due a long illness those two past years...

I have a Multiplex Cularis that has Ailerons and Flaps. For third person flights, it is recommended by Multiplex that you make a mixed mode with your transmitter for continuously use flaps as normal ailerons, i.e, flaps receive aileron input pwm and they act like ailerons. Just when you need, flaps act like “FLAPS” thanks a transmitter switch that put them in the proper configuration.
Well... I am pulling out my mind if could be possible implement this configuration in actual Ardupilot´s code. I know that there are several options available ( flaps, ailerons with input, differential spoilers, elevon, flaperon...) but nothing seems to be works like I need.

If I understand, FLAPERON is for apply Flaps configuration to normal Aileron servos, so I need that but only on independent and real Flap channel Outputs, in my case CH_5_OUT and CH_6_OUT.

My Setup:

APM 1 @2560 and APM 2.6 (Two Cularis airframes, same wings for both)
In Ch_1 Input : Aileron input from RX
In Ch_1 Output: Right and Left Aileron servos

In Ch_5 Input : Swicht to trigger camera (SEEMS NOT TO BE POSSIBLE WITH ACTUAL CODE)
In Ch_5 Output : Right Flap servo

In Ch_6 Input : Swicht to release bungee or launcher (SEEMS NOT TO BE POSSIBLE WITH ACTUAL CODE)
In Ch_6 Output : Left Flap servo

I will try to explain how it needs to be:

1-In normal operation, FLAPs will act as Ailerons.
2-In all flight modes (included in MANUAL, if is possible or secure), if actual Airspeed goes below FLAP_SPEED_1 and then below FLAP_SPEED_2, Ardupilot rest some percentage of the output pwm from centered trim to the Flaps control surfaces,examples:
    -In leveled flight, ailerons are centered and both flaps will be down (in two stages due FLAP_SPEED_1 & FLAP_SPEED_2).
-If we are turning to the left, on normal operation, left aileron will be up and left flap will be up too, minus a percent that represent the flap actuation (left aileron will be more up than left flap. Right Aileron and right Flap will be down, but right Flap will be more down than the Aileron because we have applied same percent than in left wing, representing indeed, the Flap actuation.
-If we are turning to left, control surfaces movement will be viceversa than last explanation.

Other question will be the possibility of make a CH_X_INPUT works without a result on CH_X_OUT (CH_5_INPUT to trigger the relay and CH_5_OUT to Flap). But this is for other post.

Thanks for your time and your effort.
Hope you not tire reading my explanation... 

Regards from Spain,
Dario.

**Comment by hiro2233** [comment]
Hi! @taedla01 there is a new place for discuss like this interesting project,  i'm sure that you will get help posting it in our new discuss forum http://discuss.ardupilot.org

Thanks you for your participation.
Good luck!

@OXINARF please close this.
Thanks.

**Comment by Naterater** [comment]
This is achievable with FLAPERONS assigned to the inner wing and FLAP_IN_CHANNEL set properly. You will have the desired output.
