### ISSUE TITLE
Copter-4.0 PRs delayed until early June

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13773]
These PRs have been delayed until early April so we can complete stabilizing Copter-4.0 ([issues](https://github.com/ArduPilot/ardupilot/issues/12547)) before making significant structural changes.

- [ ] Copter: refactoring about control_mode https://github.com/ArduPilot/ardupilot/pull/13431
- [ ] Copter: Summarize processes separated by the preprocessor https://github.com/ArduPilot/ardupilot/pull/13806
- [ ] AP_Math: judge isnan judgment before operation https://github.com/ArduPilot/ardupilot/pull/13807
- [ ] Libraries/Copter: Set the gravitational acceleration value to the defined value: https://github.com/ArduPilot/ardupilot/pull/13813
- [x] AP_Baro: Delete unnecessary return processing: https://github.com/ArduPilot/ardupilot/pull/13856
- [x] AP_Avoidance: Change division to multiplication and summarize processing. https://github.com/ArduPilot/ardupilot/pull/13891

**Comment by peterbarker** [comment]
- https://github.com/ArduPilot/ardupilot/pull/13856

**Comment by peterbarker** [comment]
https://github.com/ArduPilot/ardupilot/pull/13891

**Comment by amilcarlucas** [comment]
I vote to delay these a bit longer. The stable branch needs more time.

**Comment by rmackay9** [comment]
@amilcarlucas, thanks, I've changed the title a bit..

**Comment by WickedShell** [comment]
Closing as all linked PR's were either merged or closed.
