### ISSUE TITLE
AP_RangeFinder: Driver Request for Benewake new TF-Luna low-cost distance sensor

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#13790]
Benewake released their new distance sensor TF-Luna series SJ-GU-TF-Luna A01, target drone market.
Datasheet: https://1drv.ms/b/s!AmscxcpJYtuYmTcSOcB6W16AOyF0
https://www.compotek.de/news/tf-luna-lidar-module-fuer-erkennungsapplikationen/

**Comment by bkzspam** [comment]
@rmackay9 Hi, Is any update on this?

**Comment by mboland** [comment]
+1 for an update as I have purchased one and landed here looking for the reason it won’t be seen on serial.

**Comment by andyp1per** [comment]
I have on of these and I believe it is working fine?

**Comment by peterbarker** [comment]
We have support for this in master.

**Comment by bys1123** [comment]
@peterbarker Thank you! Is there any commits or PR related this driver?

**Comment by bys1123** [comment]
Ha, TF-luna changed the protocol to compatible with old driver.
