### ISSUE TITLE
ROVER 4.0.2 Encoder direction does not change when SERVO is reversed

### ISSUE THREAD

**Issue by albydnc** [ArduPilot/ardupilot#13818]
#### Bug report
I have a Rover 4.0.2 based on pixhawk 2.4.8 with differential steer. each of the two motors has an encoder and one motor rotation is corrected with SERVOx_REVERSE to 1. The encoder connected to this motor shows a negative distance when moving forward. I think the software should reverse its WENC direction when SERVOx_REVERSE is 1.
**Version**
Rover 4.0.2
**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
DOIT TS100 dual track differential steer rover
**Hardware type**
PixHawk 2.4.8

**Comment by IamPete1** [comment]
I don't think using the servo reverse will work, what if the servo and encoder are going in opposite directions, the reverse would reverse them both and it would still be wrong. 

To reverse the encoder you can swap the values of `WENC_PINA` and `WENC_PINB`
