### ISSUE TITLE
Coter: add support for external siren / Screamy

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1382]
Philip, Tridge and I had a talk about this and we decided:
- Tridge or Randy will make an AP_Notify object for an external buzzer.  It will take one parameter which will allow choosing which relay is used to sound the siren.
- Because of an issue with the relay pins always being pulled high when the pixhawk boots, the relay pin will be pulled _low_ when the siren should be sounded.  This means we will need a physical Relay to switch around the signal.
  http://www.ebay.com.au/itm/281257290325?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1439.l2649
- Randy will document how to connect the external buzzer on the wiki and we hope that some manufacturer will create a plug-and-play solution so that large numbers of people can enjoy the new feature
- This won’t make AC3.2 but will make AC3.3.

**Comment by rmackay9** [comment]
I haven't heard any more about screamy becoming availalble so pushing this to AC3.4 in the expectation that it won't be ready within the next 2 months.

**Comment by dragonavionics** [comment]
That's fine. The manufacturer is waiting on long lead parts right now.
It'll likely be 2 months...

Thanks Randy,

Kelly

**Comment by R-Lefebvre** [comment]
Didn't something similar to this just get added?

**Comment by rmackay9** [comment]
Not really.  There's the lost copter sound which uses the px4 buzzer.. but this is for an external device that's even loader.

**Comment by rmackay9** [comment]
It looks like the Scream is available from hobbyking now.  http://www.hobbyking.com/hobbyking/store/__78373__Screamy_Lost_Model_Alarm_With_Battery_Backup_And_Low_Voltage_Alarm.html

I wonder if perhaps there's no need to do any code enhancements to support it?  Maybe people just use the RC passthrough?

**Comment by MGornitzka** [comment]
I still think it is a good thing to have some kind of relay in case of radio- and GCS failsafe, autoland and other failsafes. It would make the controller more usable for professionals.

**Comment by dragonavionics** [comment]
I agree with Martin, though I share the sentiment of less work is better.
If it's not too much trouble, controlling Screamy via relay or PWM with a
Mission Planner setting to enable an external alarm via transmitter and
also directly from the GUI would be a useful feature. I like Martin's ideas
of automatic triggering.

Kelly

Thanks,

Kelly Miller
Dragon Avionics, LLC
(315) 254-9677
kelly@dragonavionics.com

**Comment by rmackay9** [comment]
@dragonavionics, how do you feel about sending me one to test with?  my email address is rmackay9 at yahoo.com in case that's a possibility.

**Comment by rmackay9** [comment]
I actually have one of these now but pushing to AC-3.5.

**Comment by Naterater** [comment]
@rmackay9, the hobbyking link above is broken. Did this ever get in?

**Comment by rmackay9** [comment]
Looks like the product has been discontinued so I guess we can close this.  https://hobbyking.com/en_us/screamy-lost-model-alarm-with-battery-backup-and-low-voltage-alarm.html.  Too bad, it was a very loud alarm.
