### ISSUE TITLE
AP_Scripting: create "scripts" directory if it doesn't exist

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13862]
I think we should automatically create the "scripts" directory on the SD card if it doesn't existe already whenever SCR_ENABLE = 1.

This issue came up after a user reported not having the "scripts" directory on [this discussion thread](https://discuss.ardupilot.org/t/lua-scripts-using-velocity-control/53677/18).

Until this is done I'll add a note to [the wiki](https://ardupilot.org/copter/docs/common-lua-scripts.html).

**Comment by tridge** [comment]
Good idea

**Comment by peterbarker** [comment]
@rishabsingh3003 did this.
