### ISSUE TITLE
swiftnav piksi gps rtk integration in mission planner/mavlink/pixhawk

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#1386]
Hello Guys!,

It will be cool that we can connect ground piksi gps rtk reference directly to laptop with mission planner and that it communicate over mavlink-3DR Radios to synchro rather than use rtk over other 3dr links...... and also that pixhawk root rtk packet to piksi gps embeded on the multirotor...

**Comment by amilcarlucas** [comment]
yes RTCM injection for RTK GPSs is now available in both MissionPlanner and mavproxy
