### ISSUE TITLE
Validate parameter values

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#13864]
## Feature request

**Is your feature request related to a problem? Please describe.**
Currently we only parse the parameter documentation.
We could easily parse and validate that we don't have duplicate value in @value fields

**Comment by rishabsingh3003** [comment]
Please assign me to this issue! I'd like to raise a PR :)

**Comment by rishabsingh3003** [comment]
@khancyr while fixing this issue I found out there are a number of duplicate values already present in the master. For eg: Copter has the following duplicates:

![image](https://user-images.githubusercontent.com/36970042/77314586-f171a680-6d2b-11ea-946c-c36ab7e32635.png)


Should the PR I push also fix these duplicates? Or should that be a separate PR?

**Comment by khancyr** [comment]
in same PR that is better, otherwise you won't pass the test ^^
