### ISSUE TITLE
EKF2: altitude climbing in first arm without takeoff

### ISSUE THREAD

**Issue by chobitsfan** [ArduPilot/ardupilot#13882]
## Bug report

**Issue details**
PosHold mode, tested indoor using att_pos_mocap
use RC to arm and then disarm (copter did not take off)
![Log Browser - 23 2020-3-25 上午 11-34-56 bin 2020_3_25 下午 01_47_00](https://user-images.githubusercontent.com/19793511/77505825-2a7e5800-6e9f-11ea-91ea-4781dabda2bf.png)
[log_disarm0.zip](https://github.com/ArduPilot/ardupilot/files/4379249/log_disarm0.zip)
ctun.alt climbing after first armed (throttle min). If you take copter off at this moment, it will rocketing into sky. But this behavior did not happen in following arm

It is strange that it is not happened if log_disarm = 1
[log_disarm1.zip](https://github.com/ArduPilot/ardupilot/files/4379251/log_disarm1.zip)

**Version**
4.0.4-dev

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quadcopter

**Hardware type**
kakute f7

**Comment by chobitsfan** [comment]
I am sorry. This seems a duplication of #11304

**Comment by AGurel** [comment]
I'm also getting this error. https://discuss.ardupilot.org/t/first-huge-climb-in-althold-flight-mode/54060/2

**Comment by chobitsfan** [comment]
Hi @AGurel 
It should be fixed in master by #14030 
Would you be able to test it again? thank you very much
