### ISSUE TITLE
Continue landing if RTL is triggered during a land

### ISSUE THREAD

**Issue by Dan-Moss** [ArduPilot/ardupilot#13889]
###Feature request
Continue landing if RTL is triggered during a land when in auto.

Today we were running auto missions and the battery fail-safe was triggered upon the final decent at about 5m off the ground. The drone elevated to the 15m altitude as per the failsafe, to then land at the same spot but just in RTL rather than land. I know smart rtl may solve this and could be the default in this case?

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by peterbarker** [comment]
The `FS_OPTIONS` parameter allows you to specify continue-landing-on-failsafe.  It is not set by default.

**Comment by Dan-Moss** [comment]
Not sure how i missed that. Thank you!
