### ISSUE TITLE
Need stack logging

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#13896]
We need to start logging stack usage of all threads, with a very visible warning if stack drops below a threshold. This will help find stack issues more quickly

**Comment by peterbarker** [comment]
On Thu, 26 Mar 2020, Andrew Tridgell wrote:

> We need to start logging stack usage of all threads, with a very visible 
> warning if stack drops below a threshold. This will help find stack 
> issues more quickly

Internal Errors count as "very visible".

So perhaps an AP_InternalError::error_t::soft_stack_smash

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/18587
