### ISSUE TITLE
Copter: Enhancement for survey mission,drone "invoke althold style mode" when cam trigger to not have to use gimbal

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#1392]
Idea, is that for auto mission where multi-rotor need to cover big area for survey, we can't embed gimbal due to its weight, and we install camera facing down on the frame without gimbal.

For camera take always photos oriented facing down during mission without gimbal, we could ensure that when cam trigger is invoked, the UAV enters in "althold style" mode for one second.

Drift due to a one second althold style mode remains acceptable.

This function could be activated by an optional parameter in the full parameter list that make that each time that cam trigger invoked, althold is triggered for the time

Could we commit this as enhancement for the 3.3 rev?

**Comment by IamPete1** [comment]
I'm going to close, I suspect there is no demand for this now with much wider availability of gimbals.
