### ISSUE TITLE
Existing alternate Board Config for MatekF405-Wing does not work

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#13935]
Alternate config for MatekF405-Wing enabling UART2 does not function. UART2RX input does not function.
Test to duplicate: enable ALT config, keep SBUS RX connected to SBUS input (there is an inverter between SBUSin and PA3), configured SERIAL2 to protocol 23....receiver not detected.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover
[  ] Submarine

**Comment by tridge** [comment]
It is SERIAL7 not SERIAL2

**Comment by Hwurzburg** [comment]
will update the documentation in the wiki

**Comment by Hwurzburg** [comment]
I will go back and review and update all boards that have alt configs in hwdef and update their pages also
