### ISSUE TITLE
AP_Math:: add comments above all Quaternion class methods

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13970]
A number of the [quaternion class](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Math/quaternion.h)'s methods were added without any comments above them.  We should add comments to help developer (including me!)

- void to_axis_angle(Vector3f &v);
- void from_axis_angle(Vector3f v);
- void from_axis_angle(const Vector3f &axis, float theta);
- void rotate(const Vector3f &v);
- void from_axis_angle_fast(Vector3f v);
- void from_axis_angle_fast(const Vector3f &axis, float theta);
- void rotate_fast(const Vector3f &v);

**Comment by peterbarker** [comment]
@rmackay9 was this fixed by the mentioned PR?

**Comment by rmackay9** [comment]
yes, thanks!
