### ISSUE TITLE
AntennaTracker: Modify SCAN mode

### ISSUE THREAD

**Issue by nhadrian** [ArduPilot/ardupilot#1399]
Hi,

I have an idea.
In the current version, once YAW reaches it's limit, servo moves back to the other end and starts "scan" again. This takes a long time, and if scan fails, yaw makes another full circle.
My idea is that after reaching the yaw limit on a side, start moving back till the mig point and then start scan to the other side, so make this kind of scan symmetrical. In  this way time of a complete move-back could be saved.

Regards
Adrian

**Comment by rmackay9** [comment]
This has been fixed in master (assuming I understand the problem correctly).  It now only switches to the other side when going to the other side actually gets the tracker pointing closer to the vehicle.
This will go out with Tracker-0.8.1
