### ISSUE TITLE
Plane: Loiter headings rely upon having GPS fix

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#14018]
## Bug report

**Issue details**

When verifying the loiter headings the GPS ground course is used, this should actually be fetched from the AHRS instead, so that a GPS outage doesn't break the loiter exit conditions. https://github.com/ArduPilot/ardupilot/blob/b9daae062c0fb6618a76626e853d3feebc0823cd/ArduPlane/mode_loiter.cpp#L55

**Version**
Master and stable

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Comment by rishabsingh3003** [comment]
@WickedShell I'd like to fix this issue. Can you please assign it to me?

**Comment by WickedShell** [comment]
Fixed in #14021
