### ISSUE TITLE
Copter: Loiter Turns does not point vehicle towards center

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14031]
Unlike the Circle flight mode, Auto's Loiter-Turns command with lat and lon position specified does not point the vehicle nose towards the center of the circle.  It should and I believe it once did but it seems a bug has been introduced that has broken the behaviour.

To recreate the problem in SITL do this:

- rm eeprom.bin to restore all parameters to their defaults
- create a mission with a takeoff, LoiterTurns and RTL commands
- run the mission, then vehicle will not point towards the center of the circle, instead it's heading will remain at whatever it was when it reached the edge of the circle.

![image](https://user-images.githubusercontent.com/1498098/78855849-fdfe3a80-7a5f-11ea-94ad-0fb91011394c.png)

**Comment by rishabsingh3003** [comment]
The issue might be somewhere else, but I believe this was the commit following which we have this bug:
https://github.com/ArduPilot/ardupilot/pull/5518/commits/bf7222dea52c581f1e9e6f82d0d5e75fa0fc33b9

**Comment by rmackay9** [comment]
Resolved by the linked PR, thanks!
