### ISSUE TITLE
Sitl two error[APM: PreArm: Throttle below Failsafe, Malformed SITL RC input (21)]

### ISSUE THREAD

**Issue by maerad7** [ArduPilot/ardupilot#14047]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**

**I want to fly with a simulation, but the following error pops up and it does not take off. Turn off the pre arm and issue a takeoff command to rotate the drone. It seems to be a SITL bug. Please tell me how to solve it.**

_Please describe the problem_

**Version**
_What version was the issue encountered with_
ardupilot_sitl
**Platform**
[  ] All
[  ] AntennaTracker
[ V ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Ardupilot sitl
**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Ardupilot sitl
**Logs**
_Please provide a link to any relevant logs that show the issue_
Malformed SITL RC input (21)
APM: PreArm: Throttle below Failsafe

![throttle+Malformed sitl rc input](https://user-images.githubusercontent.com/34180175/78966318-7d603c80-7b3a-11ea-8219-2e5f6399b852.png)

**Comment by rmackay9** [comment]
It seems like QGC is perhaps sending joystick commands to SITL but perhaps no joystick is connected?  In any case, it seems like the throttle being sent into SITL is too low.

I don't think this is an AP SITL but so I'll close this.  Also support issues should really go into the forums until they're confirmed bugs.

In any case, thanks for using AP and I'll monitor this thread for replies in case you run into more troubles.
