### ISSUE TITLE
AP_RangeFinder: support multiple MaxbotixI2C sonar

### ISSUE THREAD

**Issue by robynat** [ArduPilot/ardupilot#14069]
## Enhancement request

**Issue details**

Comments added by @rmackay9:
Copter-4.0.3 (and master) do not support multiple Maxbotix sonar.  We should enhance AP_RangeFinder.cpp so that it passes in the I2C address specified by the user (i.e. "params[instance].address").  We need to be careful though that users are not then forced to set the _ADDR parameter if the default I2C address is used.  I.e. we want to allow multiple MaxbotixI2C sonar to be used but the setup should not become more difficult for the average user.

---------------------------

Impostare piu MaxbotixI2C su arducopter 4.0.3 non funziona poichè anche se si cambiano gli indirizzi di ogni singolo modulo sonar e vengono inseriti nelle impostazioni  di arducopter 4.0.3 non funzionano poichè viene letto solo l'indirizzo di default (224) e non viene tenuto conto dei nuovi indirizzi impostati....mi chiedo se è possibile ottenere una correzione del firmware per gestire diversi di questi sonar contemporaneamente.....grazie

**Version**
_arducopter  4.0.3

**Platform**
[x] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
f airframe   quad

**Hardware type**
Pixhawk autopilot hardware

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
I've updated the subject line and contents a bit to translate to english but also specify what we need to do to support this.  It's not a big change actually.

**Comment by robynat** [comment]
ok....di certo per voi non è un grosso problema mentre per me è quasi invalicabile non conoscendo questo genere di programmazione .....resto in attesa di un vostro aggiornamento al firmware.......se invece avete qualche dubbio nel campo elettronico (e non credo visto lo sviluppo  continuo e costante del firmware) io potrei aiutarvi come elettronico specializzato in microelettronica in avionica.....grazie

**Comment by robynat** [comment]
Comunque ho costruito 3 droni con tre diversi fly controller ed oltre questo problema non ho riscontrato nessun'altra anomalia nel firmware 4.0.3 ...almeno per come li uso io...ancora grazie

**Comment by hendjoshsr71** [comment]
Closing. This was fixed here https://github.com/ArduPilot/ardupilot/pull/14636
