### ISSUE TITLE
COPTER 4.0.3 Add failsafe when rc_override latency goes above X ms

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#14061]
Hello,

We experience random lag issue when using RC override through 4G/3G connexion.

It's due to random lag in the 4G connexion, but there is possibility when manual flight mode set autopilot to no take the rc override commands when lag goes up set param (for example RCOVERRIDE_MAX_LATENCY) ? for example 200ms or 500ms. (for example in loiter, UAV hold it's position waiting that lag goes down).

And if lag goes upper, set another param that trigger failsafe action ?  (for example RCOVERRIDE_LAG_FAILSAFE) ? for example 600ms - 2 000ms

thank you.

PS: 

Today, lag is not checked by autopilot for RC OVERRIDE inputs…
This can be dangerous, because pilot send rc overide channels to drive it's UAV regarding this moment situation, and if lag goes UP this can conduct to crash due that input commands sent by PILOT are for many time before and UAV use it….…..
Also 4G link it's like buffered by the link provider, so this is a good point to no lost data, but for real time it's dangerous…..

This must be handled directly by autopilot.

**Comment by rmackay9** [comment]
@roque-canales, this doesn't seem correct to me.  If the RC failsafe (aka throttle failsafe) is enabled it should catch a laggy input from the pilot regardless of whether a regular TX/RX is used or a joystick connected to the GCS (aka "RC_OVERRIDES").

I think I'll close this issue but I'll keep monitoring for replies.

**Comment by roque-canales** [comment]
Thank you for this reply Randy, ok I will test with throttle failsafe activated.
Can you tell me if its possible to set the timeout ? Or what is hardcoded?
Thank you.
