### ISSUE TITLE
Rover: DPTH log message should include the rangefinder instance

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14081]
If a user sets up two (or more) downward facing echosounders, Rover will log two DPTH messages (one for each) but it won't be possible to determine which is which.  We should add the rangefinder's instance to the DPTH message to resolve this.

**Comment by shiv-tyagi** [comment]
Hey! I would like to work on this issue. I poked around and found the method which we are using to log depth. I can't understand how we are coding units while passing them to that method and what do `mults`, `fmt` mean. Also, which rangefinder property should I log to differentiate between multiple rangefinder instances. Please point me in right direction. Thanks in advance.

**Comment by IamPete1** [comment]
fixed by https://github.com/ArduPilot/ardupilot/pull/18751 thanks @shiv-tyagi !
