### ISSUE TITLE
Rover: Multiple Emergency Stop Buttons

### ISSUE THREAD

**Issue by nlgilbert** [ArduPilot/ardupilot#14087]
## Feature request

**Is your feature request related to a problem? Please describe.**
In the industry, ground vehicles tend to have a big red E-stop button on board which, when pressed, stops any potentially dangerous movement until the button is manually reset (typically by twisting it). For vehicles operated from an off-site location, there may also be a physical E-stop button at the operating station (next to the GCS) which should have the same functionality. Currently, the only E-stop functionality I'm aware of in Rover is via an auxiliary function on an RC channel. This does not allow for any form of physical E-stop button other than the RC remote.

**Describe the solution you'd like**
I would like ArduPilot to support multiple physical E-stop buttons, detecting which ones are pressed (if any). This could include an E-stop on-board the vehicle, an E-stop button at an off-site operating station (next to the GCS), or a remote e-stop. I would also like the option of adding support for other types of E-stop buttons (e.g. one that reports over a CAN bus, a standalone button for an operator to wear, etc.). My current application has need for 3-4 active E-stops, and want a little headroom for future applications.

To accomplish this, I was thinking of adding a sensor library (e.g. `AP_EmergencyStop`) which could support up to 8 E-stop buttons (arbitrary round number). Like other sensor libraries, there would be multiple backend drivers supporting different types of E-stop signals (GPIO, RC, MAVLink, CAN, etc.) and a frontend for managing a set of E-stop buttons. If any E-stop buttons are pressed, the frontend would call `SRV_Channels::set_emergency_stop()` (utilizing the functionality from #10290) and would also disarm the vehicle. Once the E-stop button(s) is reset, the operator could arm the vehicle to resume operation.

**Describe alternatives you've considered**
One alternative solution would be to bypass the autopilot altogether and cut off power to the motors. This would only allow for on-board E-stop buttons, and as mentioned in [a comment on a previous issue](https://github.com/ArduPilot/ardupilot/pull/10290#issuecomment-456540999), this could lead to integrator build-up in the EKF.

In issue #13526, @NickNunno suggested reworking the safety switch to be triggered by an E-stop button. This would only provide functionality for a single E-stop button. Perhaps the functionality of the safety switch could be extended to support other E-stop buttons rather than using `SRV_Channels::set_emergency_stop()`.

I'm also aware of `AP_AdvancedFailsafe` and its flight termination functionality. I'm not sure how much that applies to Rover, but it might be another option for stopping movement. I fear that the recovery after an E-stop button is reset may not be as smooth with this option.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Additional context**
As mentioned in #13526, E-stop buttons in industry typically have a normally-open switch (NO) and a normally-closed switch (NC), allowing the vehicle to detect if the E-stop button becomes disconnected. This could be used as a redundancy check for the GPIO E-stops driver.

In [this post](https://discuss.ardupilot.org/t/emergency-stop-button-for-large-rover/31877) on the ArduPilot discussion board, @rmackay9 said that a physical on-board emergency stop button would be an important feature to have. The original poster decided to go with the method of cutting off power to the ESC. As described above, this solution does not support off-board E-stop buttons.

About Me - I'm new to the ArduPilot development community. The Rover I'm working on is a large tracked vehicle. I'm open to discussing different approaches I could take for tackling this problem, functionality I should be made aware of, or any other suggestions on developing for ArduPilot.

**Comment by IamPete1** [comment]
AP_Button now supports E-Stop, see the `BTN_` params. I think that covers the use case your after? If not feel free to re-open.
