### ISSUE TITLE
Copter: I2C doesn't work

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#14118]
## Bug report

**Issue details**
I was trying to enable vl53l1x rangefinder, and never got the right result.
so i added some debug messages to I2CDevice.cpp,  when execute sensor->check_id() the iic _transfer function return false.

https://github.com/ArduPilot/ardupilot/blob/cac455ff2dc5ffe0ee4c6aea40ea0db48d7020a0/libraries/AP_HAL_ChibiOS/I2CDevice.cpp#L256, 

![image](https://user-images.githubusercontent.com/16251761/79521969-091f1f00-808d-11ea-958a-a8a05f9ff09b.png)

**Version**
copter 4.0.3
**Platform**
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Pixhawk, Cube(fmuv3)

**Comment by rmackay9** [comment]
@liang-tang, can you clarify a bit more what the issue is?  Are you saying that I2C never works?  Is it failing with just some sensors?  Is it failing to do some operation but it is difficult to notice?

**Comment by liang-tang** [comment]
@rmackay9 updated comment

**Comment by liang-tang** [comment]
> @liang-tang, can you clarify a bit more what the issue is? Are you saying that I2C never works? Is it failing with just some sensors? Is it failing to do some operation but it is difficult to notice?
Frist, I added debug message like below,
![image](https://user-images.githubusercontent.com/16251761/79524159-5ce03700-8092-11ea-81c3-b743b1934aa9.png)

Second, reset all params, just set RNGFND1_TYPE to 16, and reboot.
Thrid, connect fcu to serial tool, and got the log,  that means iic return fase when check VL53L1x's ID

> Successfully mounted SDCard (slowdown=0)
> 
> 
> Init ArduCopter V4.0.3 (ffd08628)
> 
> Free RAM: 154328
> FW Ver: 120
> ----------------------------------------
> 
> 
> load_all took 1532us
> 0 0 0 IOMCU: CRC ok
> Detected Pixhawk
> IOMCU startup
> _transfer 310
> _transfer 310
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> MS5611 found on bus 1 address 0x03
> AP_Logger_File: buffer size=16384
> _transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> disabling flow control on serial 2
> disabling flow control on serial 3
> _transfer 310
> ??_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> AK09916: Reset Failed
> _transfer 321
> AK09916: Reset Failed
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> _transfer 321
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ??_transfer 310
> _transfer 310
> _transfer 310
> _transfer 321
> _transfer 321
> 000------
> _transfer 321
> _transfer 321
> 000------
> _transfer 310
> ?Init Gyro_transfer 310
> *_transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> *_transfer 310
> _transfer 310
> _transfer 310
> *_transfer 310
> _transfer 310
> ?	*_transfer 310
> _transfer 310
> _transfer 310
> ?
> 
> 
> Ready to FLY _transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?
> _transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ??o_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> ?o_transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
> ?_transfer 310
> _transfer 310
> _transfer 310
> _transfer 310
>

**Comment by liang-tang** [comment]
works well now, because I forget set IIC addr....:: "><"
