### ISSUE TITLE
Vehicle name (brand?)

### ISSUE THREAD

**Issue by mrpollo** [ArduPilot/ardupilot#1411]
I would like to do a feature request to store and transmit the Vehicle (name, brand) on which the flight controller is being used, this would be useful to differentiate between logs.

@skelly [requested to differentiate Flight Controllers some time ago](https://github.com/diydrones/ardupilot/issues/57), I think the next step is to get different Vehicle names eg: 3DR IRIS, 3DR IRIS+, 3DR X8, 3DR Y6

This would greatly improve the quality of data out of log analysis tools and offer better control to people offering services like the [DroneAPI](https://developer.3drobotics.com/) and [DroneShare](http://www.droneshare.com/)

cc @geeksville

**Comment by magicrub** [comment]
The org/brand/model lookup table is nice for being machine friendly but it would also be nice to make a human friendly version which was just an arbitrary string of whatever the user wants such as "3dr iris+ Rufus 13" or a serial number.

**Comment by splenkingforth** [comment]
The ability to generate flight time logs for each aircraft would be an absolute godsend as far as we are concerned.

**Comment by magicrub** [comment]
Yes!

**Comment by Naterater** [comment]
Serial number and flight time are both implemented. Are those features enough to close this issue?

**Comment by IamPete1** [comment]
As Nate says we have serial number now, there has been no interest recently, I would quite like to close.

**Comment by mrpollo** [comment]
Please close thanks for checking
