### ISSUE TITLE
Add sim_vehicle.py opts arg to add additional gcs output

### ISSUE THREAD

**Issue by blaab2** [ArduPilot/ardupilot#14171]
## Feature request

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually type `output add 192.168.1.35:14550` shortly after I have restarted the SITL using cmd line and "arrow up".

**Describe the solution you'd like**
I would like to add an additional parameter to the sitl so I can write: `sim_vehicle.py ... --gcs-additionaloutput 192.168.1.35:14550`. In that case if I restart the SITL the additional output is added

**Platform**
[x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
I have allready added this additional parameter to my local repository. I will add a pull request if this is considered usefull.

**Comment by peterbarker** [comment]
ITYM `./Tools/autotest/sim_vehicle.py -v ArduCopter --mavproxy-args="--out localhost:7654"`
