### ISSUE TITLE
SITL: can't arm throttle and got "EKF2: variance" problem

### ISSUE THREAD

**Issue by wbzhang233** [ArduPilot/ardupilot#14209]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**

Actually, I want to make SITL  with gazebo, when I type commands below.
mode guided
arm throttle
takeoff 20

I type "takeoff 20" after "arm throttle" ASAP, but I always got a problem that "EKF2 : variance", then apm become DISAMRED. I can't arm this iris vehicle normally.

**Version**
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
You might be better off not running the EKF with gazebo. You could set `AHRS_EKF_TYPE` = 10, `EK2_ENABLE` = 0 and `EK3_ENABLE` = 0
