### ISSUE TITLE
Plane: RCx_Option, RTL and Auto do not work properly

### ISSUE THREAD

**Issue by lorbass** [ArduPilot/ardupilot#14218]
#13582 
When using RTL or Auto with the RCx_Option depending on the selected Modes according the Mode channel, sometime RTL or Auto works correct, sometimes not or it apears another Mode.
e.g. Flying with FBWB and switched Channel 7 to ppm2000, set for Option RTL, it reports via MavLink to MP Mode "FBWA"
In case of emergency not verry helpful.

_Please describe the problem_

**Version**
ArduPlane 4.0.5 Official

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
Pixhawk 1

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by peterbarker** [comment]
Logs?

**Comment by lorbass** [comment]
I made a workbench test of different Flight Modes.
RC7 is Auto, RC8 is RTL.
The Log is here: https://drive.google.com/open?id=1-b6KNTR461sg7b6Ww6QCNf9XtqWh-qky
As example at the beginning of the log selecting Auto as RC7 Option from QStabilize. One time correct, next wrong. Seems to be a timing issue. Not recognized with FBWA or FBWB as base.
![RC Option Issue](https://user-images.githubusercontent.com/7657148/80789377-1c9db000-8b8c-11ea-8ddb-ccaf1e585019.jpg)

**Comment by peterbarker** [comment]
Why is your main `FLTMODE_CH` channel and your `RCIN.C7` moving in concert?  I can see how you could get race conditions here:

![image](https://user-images.githubusercontent.com/7077857/80851773-06185700-8c67-11ea-8f4d-43946971f622.png)

**Comment by lorbass** [comment]
Hello Peter, thanks for the help. You checked the Log really careful and hit the nail. It was a bad setup in my Taranis TX from a early version. Now it works perfectly. Therefore no ArduPlane Issue. I will close the thread. Otto
