### ISSUE TITLE
LUA Script Servo Control 

### ISSUE THREAD

**Issue by MadRC** [ArduPilot/ardupilot#14216]
I have been testing the Lua script behaviour with servo outputs and as I understand it you can not control an output without assigning it to a script function.  

I.E setting the script to ID 94 will trigger Script function 1 

The issue with this is there is no way to manually take control of that servo output outside of the Lua script assigned channel for manual intervention as you can’t  control it via the servo buttons in Mission planner or assign it to a RC channel Or Mavlink command as it’s mapped to the Script function now. 

This could cause safety and usage issues as there is no option to take manual control. 

Ideally it would be better to be able to control outputs in Lua scripts via their standard ID without having to assigning them to a specific script function.  

Or allow multiple function assignments so separate ones for Lua script and manual control for the user.  

Also the Wiki command for servo control is wrong and is missing _pwm at the end of it. I will put a separate request in for that. 

Please let me know if my understand of this is wrong as this is from my own testing but there is little other info on this

**Comment by WickedShell** [comment]
Master just changed the behaviour to allow a script to override any servo, not just the scripting function ones. With this I think what you are asking for is actually resolved, so I've closed the issue. If I missed something please reopen it/let me know.

On the other side you can't take manual control of a normal flight control servo from the GCS either, and even if you could sending a MAVLink command can easily be overridden again by scripting. If you need to stop the script at that point then you just need to stop scripting (set the `SCR_ENABLE` parameter to 0 while running).

The wiki just got broken on the dev call :)
