### ISSUE TITLE
Add support for 16 input channels on pixhawk

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#1426]

**Comment by lvale** [comment]
@rmackay9 Now we have the support in place to use all the 16 channels but no user facing support to use them.
Perhaps extending the Option channels to go up to 16 ?

**Comment by amilcarlucas** [comment]
AFAIK copter supports 16 RC channels now

**Comment by rmackay9** [comment]
Yes and in master, all 16 channels can be used for auxiliary switches so we can close this now.

**Comment by rmackay9** [comment]
Yes and in master, all 16 channels can be used for auxiliary switches so we can close this now.
