### ISSUE TITLE
Plane allowed arming via GCS in manual mode with throttle up

### ISSUE THREAD

**Issue by jschall** [ArduPilot/ardupilot#14285]
#  Bug report

**Issue details**

_Please describe the problem_
Plane allowed arming via GCS in manual mode with throttle up. The reason I attempted this was because my throttle stick was reversed and I was unaware of this. Fortunately the only consequence was a wrecked prop and a gouge in a table.

**Version**
_What version was the issue encountered with_
somewhere around bd0ebb5778211c7fff4d35305b3b3866151e0bb0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Quadplane

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
CubeBlack

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by WickedShell** [comment]
Resolved by #14755
