### ISSUE TITLE
Copter: dataflash CTUN desired climb rate column incorrect in RTL, Auto, Guided

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1431]
In AC3.2's dataflash logs, the DCrt (desired climb rate) is not set during autopilot modes.  It's only updated in flight modes where the pilot sets the desired climb rate (Loiter, etc).

**Comment by OXINARF** [comment]
@rmackay9 This is still valid?

**Comment by rmackay9** [comment]
I think this is resolved, we just need to check the CTUN's.DCr and Cr columns are filled in during RTL, guided and Auto.

**Comment by OXINARF** [comment]
Climb rate is filled in independently from mode in the fast loop execution, so that's certainly working.
Desired climb rate is filled with information from PosControl - I'm pretty sure RTL, Guided and Auto use it so that should be working too, right?

**Comment by rmackay9** [comment]
This is resolved so closing
