### ISSUE TITLE
EKF: altitude source is inconstant with EK2_ALT_SOURCE

### ISSUE THREAD

**Issue by KimHyungSub** [ArduPilot/ardupilot#14319]
**Issue details**
As you know, EK2_ALT_SOURCE is primary altitude sensor used by the EKF. Also, this parameter requires reboot (#7035). But, when I changed the altitude source from barometer to GPS, the EKF followed height from GPS as shown below.
![Barometer_to_GPS](https://user-images.githubusercontent.com/21173273/81368662-5146c580-90be-11ea-9ad3-85537b741101.png)

On the other hand, I modified source code to make SITL executed with EK2_ALT_SOURCE = 2.
After that, I changed the altitude source from GPS to barometer, it did not follow the altitude from barometer as shown below.
![GPS_to_barometer](https://user-images.githubusercontent.com/21173273/81368674-59066a00-90be-11ea-83b7-339d60841f6d.png)

I know if users want to change the parameter, they need to reboot ArduPilot. However, there is still gap between these two cases. Plus, I wanted to test EK3_ALT_SOURCE, but there is no this parameter in source code so far even I can turn on EK3.

**Version**
Master

**Platform**
[  ] All
[  ] AntennaTracker
[V] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
ArduCopter

**Hardware type**
SITL

**Logs**
1. EK2_ALT_SOURCE 0 --> 2
https://drive.google.com/file/d/11SCLwCdJrlfO49RjRSIUT2O2lbUR7vhV/view?usp=sharing

2. EK2_ALT_SOURCE 2 --> 0
https://drive.google.com/file/d/1KqXLLD95jjamB8lM5vXIeix5_RRd1AdA/view?usp=sharing

**Comment by magicrub** [comment]
Are you saying that 0 -> 2 works without reboot and 2 -> 0 does not?

**Comment by rmackay9** [comment]
@KimHyungSub,

Thanks for this report!  Do you think you could test with EKF3?  The next official release will use the EKF3 by default so there's more of an appetite to ensure it's correct.

**Comment by KimHyungSub** [comment]
@magicrub Yes, that's correct!
@rmackay9 Sure. I will report the result after I test the EKF3.

**Comment by KimHyungSub** [comment]
I just tested the EKF3. The result is the same as the EKF2 cases.

1) I used the following commands to test altitude source change from barometer to GPS.
param set AHRS_EKF_TYPE 3
param set EK2_ENABLE 0
param set EK3_ENABLE 1
param set EK3_ALT_SOURCE 2

![Baro-to-gps](https://user-images.githubusercontent.com/21173273/89845250-f5238f80-db4b-11ea-8d34-be54656d1e35.png)

2) I modified the following source code.
Changing "AP_GROUPINFO("ALT_SOURCE", 9, NavEKF3, _altSource, 0)" to "AP_GROUPINFO("ALT_SOURCE", 9, NavEKF3, _altSource, 2)" at libraries/AP_NavEKF3/AP_NavEKF3.cpp.

I also used the following commands to test altitude source change from GPS to barometer.
param set AHRS_EKF_TYPE 3
param set EK2_ENABLE 0
param set EK3_ENABLE 1
param set EK3_ALT_SOURCE 0

![gps-to-baro](https://user-images.githubusercontent.com/21173273/89845367-459aed00-db4c-11ea-8e0e-f8a22422fd05.png)

* Log
1) EK3_ALT_SOURCE 0 --> 2 (from barometer to GPS)
https://drive.google.com/file/d/18N5eIrC_KCnCXveJ4p1m_Jc-q02nWAzE/view?usp=sharing

2) EK3_ALT_SOURCE 2 --> 0 (from GPS to barometer)
https://drive.google.com/file/d/15W-wPF4laznQXpGLYKstXgp4Ff3icgoo/view?usp=sharing

**Comment by rmackay9** [comment]
This is over my head so we probably need @priseborough to comment on this.

**Comment by priseborough** [comment]
Both EK2_ALT_SOURCE and EK3_ALT_SOURCE as specified in the parameter description require a reboot after being changed. The behaviour if this is not done is undocumented.

**Comment by KimHyungSub** [comment]
@priseborough 
Thank you for the feedback. So, would updating the document be the solution?

**Comment by priseborough** [comment]
@KimHyungSub Which document are you referring to? The parameter descriptions in the code specify a reboot is required.

**Comment by amilcarlucas** [comment]
Can this be closed?

**Comment by priseborough** [comment]
Yes.

**Comment by peterbarker** [comment]
Thanks @amilcarlucas , @priseborough
