### ISSUE TITLE
Building Docker image on Raspbian ( armhf ) fails

### ISSUE THREAD

**Issue by Glagnar** [ArduPilot/ardupilot#14358]
## Bug report

**Issue details**

Building docker image on raspberry pi fails with an error:
Package 'g++arm-linux-gnueabihf' has no installation candidate

**Version**
4.0.3 Release Candidate

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Logs**
<img width="1265" alt="Screenshot 2020-05-11 at 16 37 55" src="https://user-images.githubusercontent.com/5913559/81793002-1521c380-9509-11ea-9368-908f65d06b9d.png">
ow the issue_

**Comment by khancyr** [comment]
hello, thanks for the report, I will correct it. 
It comes from the fact that this toolchain doesn't exist on raspi as it is the default one.
As temp fix, I think you could remove it from the Tools/environemnent_install/install-prereqs-ubuntu.sh .

I will try to have a backport of the new dockerfile on the copter4.X serie to correct some other mistake

**Comment by Glagnar** [comment]
> hello, thanks for the report, I will correct it.
> It comes from the fact that this toolchain doesn't exist on raspi as it is the default one.
> As temp fix, I think you could remove it from the Tools/environemnent_install/install-prereqs-ubuntu.sh .
> 
> I will try to have a backport of the new dockerfile on the copter4.X serie to correct some other mistake

I removed the references from the file, and now it works on arm. Thanks.

**Comment by khancyr** [comment]
yep the old dockerfile isn't great, that is why I will try to backport the new version into the 4.X branch

**Comment by peterbarker** [comment]
@khancyr any movement on this one?

**Comment by IamPete1** [comment]
sounds like this issue is resolve on the newer version of the dockerfile, so I'm going to close.
