### ISSUE TITLE
Matlab Simlink GSoC goals

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/ardupilot#14384]
This is a issue to track the progress and goals of this summers GSoC project. The working folder can be  found [here](https://drive.google.com/open?id=1GoObAS1mY_UIy4GjSkuA8eMmTQkcaqG2). This is the [original proposal](https://drive.google.com/open?id=1vOrlrgndi7vvJZADg1RgwHroO83Syn8XQmQF872D3kI). The 'big picture' goal is to add and document Matlab Simulink support to Ardupilot. Starting with a SITL backend and depending on how long everything takes allowing control systems to be designed in Matlab, tested in SITL and deployed to ArduPilot.

- [x] JSON SITL backend using lock-step scheduling

- [x]  Matlab copter physics simulator to talk to JSON backend, using the minimum of extra toolboxes

- [x]  Fly SITL vehicle with low EKF innovations to verify the physics

- [x]  Implement other vehicle types

- [x] Duplicate Matlab funcatality in Octave or Python allowing for a JSON SITL autotest

- [ ] Man in the middle backend, allowing plotting and offsetting data

- [ ] Allow for alternate control systems in AP with frontend/backed split

- [ ] Allow for SITL Matlab control system

- [ ] Explore possibility of matching Matlab SITL backends to real vehicles using sys ID mode, allowing for ideal control systems / parameters to be found.

**Comment by bnsgeyer** [comment]
@IamPete1  How are things going with your GSOC project?  Sorry that I've been out of touch.  what is your next step?

**Comment by IamPete1** [comment]
@bnsgeyer Hi BIll, this plotting in MATLAB is that latest stuff. [Demo 1](https://youtu.be/m_cmR_wLe5c) and [Demo 2](https://youtu.be/3Q1a2skm17g ) The next step I was going to look at is hard coding the oscillation detection stuff and using it to implement a 'quick tune'.

**Comment by bnsgeyer** [comment]
@IamPete1  Do you think you will be able to look at having a library or mode coded up in simulink that would interface with AP in the SITL. That way users could use simulink to develop their control laws or library and be able to test it with SITL without having to autogenerate code from matlab and compile?  I think that would be a great capability for developers that like to use simulink.

**Comment by IamPete1** [comment]
@bnsgeyer Yeah, I can take a look, the tricky thing is pausing the vehicle code while talking to simulink. I'm not really sure the best way to approach that.

**Comment by IamPete1** [comment]
GSoC is now complete, see [GSoC 2020 – Matlab and Simulink conclusion](https://discuss.ardupilot.org/t/gsoc-2020-matlab-and-simulink-conclusion/61049)
