### ISSUE TITLE
Copter: gusty wind conditions can cause yaw to be dragged around

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1439]
AC3.2 allows the desired yaw to be dragged around by the actual yaw.  Normally this is a good safety feature to avoid sudden changes in yaw on take-off but perhaps we should always try to move back to the target especially in Auto flight modes.  Condition-yaw in particular only sets the target once so it's susceptible to this problem while the face-next-waypoint yaw is not because the target is constantly reset.

This issue might become less of a problem if we had an autotune on yaw to help people get good yaw gains.

**Comment by lthall** [comment]
We have an autotune now. I think we can close this. Auto will do this if it is controlling it's heading.
