### ISSUE TITLE
Error: Mag (0) bad radius xxx expected 222 (#14393)

### ISSUE THREAD

**Issue by profotoevideo** [ArduPilot/ardupilot#14415]
Hello! I'm Brazilian, I'm setting up a "Tarot - XS690", I bought a 3dxr "The Cube Black (AKA Pixhawk 2.1)" and "Here + V2 RTK GNSS (M8P)", And I can't do the compass calibration. A message always appears saying: "Mag (0) bad radius xxx expected 222" Remembering that "xxx" symbolizes a number that always changes. What should I do to fix it? My thanks to anyone who can help.
I uploaded the file to the wetransfer: https://we.tl/t-ryasxOyu7u
I ask you to be kind enough to check and thank you for your help, because here in my country (Brazil) there is no organized community to help.

**Comment by IamPete1** [comment]
Clossing, but feel free re-open or ask over on the forum.
