### ISSUE TITLE
Wrong target altitude after flip mode with GPS glitch

### ISSUE THREAD

**Issue by KimHyungSub** [ArduPilot/ardupilot#14425]
## Bug report

**Issue details**

While I experimented GPS glitch, I noticed that AC targeted wrong altitude after flip mode with GPS glitch.

This can be reproduced in SITL by doing the following:
- param set GND_TEMP 40
- param set GND_ALT_OFFSET 300
- param set GPS_POS1_Z 2.474742
- arm throttle
- rc 3 1900
- rc 3 1300
- rc 3 1500
- mode alt_hold
- mode flip

When I used default values for GND_TEMP and GND_ALT_OFFSET, this problem was not happened.

![3](https://user-images.githubusercontent.com/21173273/82620907-ae0aab80-9ba7-11ea-91b1-e834dda2e683.png)

![1](https://user-images.githubusercontent.com/21173273/82620595-e362c980-9ba6-11ea-808e-d3cddeaf8598.png)

**Version**
master

**Platform**
[  ] All
[  ] AntennaTracker
[V] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Copter

**Hardware type**
SITL

**Logs**
https://drive.google.com/file/d/1BSV_9DfzCv6YJk5pajEjFGvEOGbgQ6w5/view?usp=sharing

**Comment by IamPete1** [comment]
I don't think this is a realistic scenario that AP can be expected to deal with.
