### ISSUE TITLE
ArduSub 4.0.1 MS5837 works incorrect on fmu-v3

### ISSUE THREAD

**Issue by alphasion** [ArduPilot/ardupilot#14457]
MS5837 pressur sensor not works on fmu-v3 but works fine on fmu-v2
**Version**
4.0.1
**Platform**
[  ] Submarine
**Airframe type**
Vectored 6DOF
**Hardware type**
FMU-V3

**Comment by auturgy** [comment]
What autopilot hardware are you using?

**Comment by alphasion** [comment]
PixHack V3x,

**Comment by alphasion** [comment]
> What autopilot hardware are you using?
> […](#)
> On 27 May 2020, at 7:47 pm, alphasion ***@***.***> wrote: ﻿ MS5837 pressur sensor not works on fmu-v3 but works fine on fmu-v2 Version 4.0.1 Platform [ ] Submarine Airframe type Vectored 6DOF Hardware type FMU-V3 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
I'm using Pixhack V3x,and i checked GND_EXT_BUS and GND_EXT_PROBE also no working.
