### ISSUE TITLE
Problem of rangefinder in Auto mode

### ISSUE THREAD

**Issue by chris89116** [ArduPilot/ardupilot#14458]
Describe the problem :

In AUTO mode my rangefinder is not use.
On the other hand In LOITER mode and AltHold all work correctly and my proximity sensor work.

![image](https://user-images.githubusercontent.com/64551536/83034206-4b4a6180-a038-11ea-8b47-f21b1f0f5cf5.png)

I have also just tested the Auto mode by activating or deactivating WPNAV_RFND_USE and it is the same thing my proximity sensor is not used.

More informations here : [https://discuss.ardupilot.org/t/problem-of-rangefinder-in-auto-mode/55274](url)

**Version**
AC 4.0.3

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X6

**Hardware type**
(Drotek Pixhawk 3 Pro,Sirius RTK GNSS Rover (M8P)

**Logs**
http://dl.free.fr/sI6KSXCBO

**Comment by rmackay9** [comment]
Hi there, this is really a support question so glad that it was raised in the forums.  I've replied on the linked thread, thanks!
