### ISSUE TITLE
PWM Out 1-5 doesn't work with DShot on Kakute F7 Mini on Quad FRAME_CLASS

### ISSUE THREAD

**Issue by tenten8401** [ArduPilot/ardupilot#14475]
## Bug report

**Issue details**
When using my Kakute F7 Mini, DShot outputs 1-5 do not work at all even with SERVO_BLH_MASK set to 63. 6 does appear to work. I'm pretty confident it's a bug as the wiki says all 6 outputs are dshot capable and one of them seems to work.
![image](https://user-images.githubusercontent.com/6174343/83342460-c40e1f80-a2bd-11ea-90ac-704a3f4ee7bc.png)
![image](https://user-images.githubusercontent.com/6174343/83342463-c7a1a680-a2bd-11ea-8cb9-0fcc782a9eee.png)

**Version**
Copter v4.0.3

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
Kakute F7 Mini

**Logs**
![image](https://user-images.githubusercontent.com/6174343/83342462-c6707980-a2bd-11ea-9e43-56cca59914fc.png)

**Comment by rmackay9** [comment]
I'm glad the RCOut banner is included in this report and that it's useful.

**Comment by rmackay9** [comment]
@tenten8401, any chance you could post an onboard log file?

**Comment by tenten8401** [comment]
@rmackay9 Here you go
[log_0_UnknownDate.bin.zip](https://github.com/ArduPilot/ardupilot/files/4711202/log_0_UnknownDate.bin.zip)

**Comment by andyp1per** [comment]
@tenten8401 what version of blheli?

**Comment by tenten8401** [comment]
I believe BLHeli_S 16.7, but shouldn't matter because it does the banner thing regardless if an ESC is even plugged in or not.

**Comment by tenten8401** [comment]
I should also add that none of the protocols work besides PWM, oneshot included (except for output 6)

**Comment by tenten8401** [comment]
Hmm.. so I just re-flashed 4.0.3 fresh and all 6 outputs work with Dshot now.. It's something with my parameters because after applying them it goes back to not working again..
![image](https://user-images.githubusercontent.com/6174343/83558358-ecc22f00-a4e0-11ea-86bb-3d1804b454ac.png)

**Comment by tenten8401** [comment]
Found the issue I think, as soon as I set FRAME_CLASS = 1 outputs 1-5 stop working, if I set FRAME_CLASS = 2 (or any other value) they all work as expected. If I had to guess it's because of 1-3 and 4-5 not sharing one output group.

**Comment by IamPete1** [comment]
Can you try using PWM type to set dshot rather than the BLHeli mask. Once you set a frame class it auto assigns motors to outputs 1-4 (for a quad). This then means MOT_PWM_TYPE is applied. I suspect we have a conflict between the BLHMask and the PWM_TYPE.

**Comment by tenten8401** [comment]
@IamPete1 Yeah you're probably right, I didn't even know MOT_PWM_TYPE existed.
![image](https://user-images.githubusercontent.com/6174343/83949004-4a12f480-a7ef-11ea-9394-f2f3946049c4.png)

**Comment by peterbarker** [comment]
My reading here is that the issue was sorted.  Please re-open if I'm wrong.
