### ISSUE TITLE
Copter: reduce compile warnings

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1447]
We have a massive number of compile warnings which make it difficult to see real warnings and errors when compiling.  We should reduce these.

**Comment by magicrub** [comment]
Cloned for Plane #2034

**Comment by WickedShell** [comment]
Closing as there are both a lot less warnings then there used to be, and as was mentioned in #2304  this is a perpetual code cleanliness issue, rather then a something that can be specifically tracked here effectively.
