### ISSUE TITLE
Add support for Sagetech binary protocol for ADSB

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#14486]
Add support for Sagetech binary protocol for ADSB.

**Comment by magicrub** [comment]
Here's an open-source driver that is available
https://github.com/ugcs/sagetech-ardu

**Comment by gnac** [comment]
ICD is officially published at https://github.com/Sagetech-Avionics/sagetech-mxs-sdk/blob/main/doc/icd/ICD02373_MXS_Host_ICD.pdf

**Comment by peterbarker** [comment]
@magicrub did this years ago.  Thanks Tom!
