### ISSUE TITLE
Keller sensor bug for ArduSub

### ISSUE THREAD

**Issue by gezzuzz** [ArduPilot/ardupilot#14510]
**Issue details**
Keller sensor fails on read with Pixhawk 4 Mini

**Version**
4.0.0

**Platform**
[ X ] Submarine

**Hardware type**
Pixhawk 4 Mini

I am working on using Pixhawk 4 Mini with ArduSub. Had issue reading depth from keller senor.

Line 166 show
 if (!_dev->transfer(0x0, 1, data, sizeof(data))) {

should it be 
 if (!_dev->transfer(nullptr, 0, data, sizeof(data))) {

Im not very familiar with communication functions on the pixhawk. But is the 1 for write and 0 for read?  

Thank you

**Comment by jaxxzer** [comment]
Fixed [here](https://github.com/ArduPilot/ardupilot/commit/771666ee52c5cfa3b05d17b33ebcfba370e9c4a7)
thanks @peterbarker bro
