### ISSUE TITLE
Copter: AttitudeControl should use angle_max as a circular limit, rather than having a separate limit on roll and pitch

### ISSUE THREAD

**Issue by jschall** [ArduPilot/ardupilot#1451]

**Comment by R-Lefebvre** [comment]
I think this was completed?

**Comment by rmackay9** [comment]
No, it doesn't appear to be.  Looking in AC_AttitudeConrol.cpp we see lines like this:
// angle_ef_roll_pitch_rate_ef_yaw - attempts to maintain a roll and pitch angle and yaw rate (all earth frame)
void AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw(float roll_angle_ef, float pitch_angle_ef, float yaw_rate_ef)
{
    Vector3f    angle_ef_error;         // earth frame angle errors

    // set earth-frame angle targets for roll and pitch and calculate angle error
    _angle_ef_target.x = constrain_float(roll_angle_ef, -_aparm.angle_max, _aparm.angle_max);
    angle_ef_error.x = wrap_180_cd_float(_angle_ef_target.x - _ahrs.roll_sensor);

    _angle_ef_target.y = constrain_float(pitch_angle_ef, -_aparm.angle_max, _aparm.angle_max);
    angle_ef_error.y = wrap_180_cd_float(_angle_ef_target.y - _ahrs.pitch_sensor);

**Comment by R-Lefebvre** [comment]
This converts orthogonal angle limits into circular limits.

https://github.com/diydrones/ardupilot/commit/ecefe784178b0efe92c9d8aee901c4a0a4fb66eb

**Comment by OXINARF** [comment]
Is this fixed or not? It looks like it was fixed in Copter code instead of AttitudeControl, according to the commit referenced by @R-Lefebvre.

**Comment by lthall** [comment]
done
