### ISSUE TITLE
Plane: Too high Target PIDs when synthetic airspeed very different from real. Result - strong roll oscillation at launch.

### ISSUE THREAD

**Issue by hyperion11** [ArduPilot/ardupilot#14524]
## Bug report

**Issue details**

Too high Target PIDs when synthetic airspeed very different from real. Result - strong roll oscillation at launch.

**Version**
4.0.5

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
ZOHD Dart 250G, Stock ESC, motor and propeller 5inch.
No airspeed sensor
**Hardware type**
Pixracer 

**Logs**
https://1drv.ms/u/s!AuFPVI_eDaZbhMcZ5_ePPpgAVt860A?e=lgvbX4
In the beginning 2020-06-03 20-19-14.bin
![image](https://user-images.githubusercontent.com/13326299/83828441-e1eae280-a70a-11ea-87ec-58e614fc4f7a.png)
In this log GPS speed (and real speed, there is almost no wind) 5 times greater than Aspeed. 
Аfter the moment when the airspeed equals the GPS speed, oscillations gone. And during rest of flight not happens.
In another flight in the beginning 2020-06-03 20-29-39.bin
![image](https://user-images.githubusercontent.com/13326299/83828821-bfa59480-a70b-11ea-8da0-6f3e5f74c576.png) i also receive roll wiggle, but smaller. GPS.SPD in this situation higher than CTUN.Aspd ~4 times. And at the end of log file was third launch.
![image](https://user-images.githubusercontent.com/13326299/83828975-127f4c00-a70c-11ea-9825-fcafebab1f1e.png)
At this launch GPS.Spd not so greater than CTUN.Aspd and here is no wiggle. (2 times higher)
So i think PID scaling interconnected to synthetic or real airspeed and in some condition this process can produce twitching.
https://youtu.be/Gx-14xoEeDE?t=128
Twitching 2:08

Another finding:
In some cases PIDP.I at launch = 0. While it about zero CTUN.Aspd not reliable and oscillation occurs. If at launch PIDP.I !=0 and working properly, CTUN.Aspd close to GPS.Spd and no oscillations. I did not reveal any patterns when this occurs

**Comment by peterbarker** [comment]
@hyperion11 we've got this PR underway: https://github.com/ArduPilot/ardupilot/pull/15810 which should help with the oscillations by clamping the airspeed estimate.

If you're in a position to test that - experimental! - code, then that would help.

**Comment by hyperion11** [comment]
sorry, i can't reproduce this problem now :(

**Comment by peterbarker** [comment]
OK, thanks for reporting back.  Hopefully we've fixed the problem - or we do when we merge the linked PR.

Poke us again if you reproduce.
