### ISSUE TITLE
Arduplane 4.0.5 Matek F405 Wing - constant AHRS/GPS unhealthy message

### ISSUE THREAD

**Issue by jostak** [ArduPilot/ardupilot#14532]
Hi,
I just wanted to exchange the INav with latest Arduplane, to check the performance.
The plane ix Bix3 with installed Matek F405 Wing, Ublox 8 GPS, no Mag.
After the correct set up ( I used to fly with Ardu 3.9 for plane and copters in the past, so I have some expirience with Ardu family), I am able to Arm the plane but imediately there is the message about "GPS/AHRS unhelthy", the message comes during the entire flight, even if there is HDOP 0,6 and 22satelites visible. I also added the second GPS (Betian 220) and set up the system to use the better one, but still the same issue. Both GPSs have the solid 3D and the system returns unhealthy GPS/AHRS.
The gyro and acc do not show any issues or vibrations and the plane flights well on INav, but INav has this constant issue of horizon drift which at the end drives to unstable loitering.
This is why I wanted to check Arduplane, but here seems c to be the different problem.
Please, advice, what I did wrong.

**Comment by IamPete1** [comment]
were going to need a log
