### ISSUE TITLE
Several Runcam bugs - RC reversals ignored, exit command ignored by camera. 

### ISSUE THREAD

**Issue by ItsMeAubey** [ArduPilot/ardupilot#14540]
## Bug report

**Issue details**

**Issue 1**
Runcam camera control ignores RC reversals. 

Exact steps to reproduce:

1. Set elevator reversal **in transmitter** such that moving the pitch stick down produces a low response (stick all the way down = 1000us).
2. Set servo reversals **in ardupilot** so that control surfaces move properly. In my case this means setting pitch input to reversed. My control surfaces move properly in both FBWA and in manual at this step, this plane is set up correctly for flight. 
3. Power cycle the whole system to ensure all changes take affect. 
4. Enter runcam menu via inputting roll right, then yaw right. 
5. Move pitch stick up. The selected menu item moves down. 
6. Move pitch stick down. The selected menu item moves up. 
7. Invert whatever your servo reversal is in ardupilot on pitch channel. If reversed, unreverse. etc. 
8. Repeat steps 3-6. Behavior is identical, but physical pitch servo outputs are reversed, thus the runcam protocol ignores rc reversals. 

The only way to fix the direction that the menu selection moves is to reverse in-transmitter. This issue happens in both my runcam Micro Swift 3 and Phoenix Oscar Edition. 

**Issue 2**

Yaw left disconnects from runcam camera, but does not close the osd menu. This issue is present on my Micro Swift 3 but is NOT present on my Phoenix Oscar Edition. In the Phoenix, yaw left at any time fully exits the runcam osd and re-enables the built-in osd as expected. In the Micro Swift, yaw left at any time re-enables the built-in osd, but does not close the runcam osd. The runcam osd is still visible, still responds to pitch and roll inputs, but ignores yaw inputs. 

Exact steps to reproduce (using Micro Swift v3):

1. Enter runcam menu via inputting roll right, then yaw right. Notice that as soon as the roll right command is given, the onboard osd is disabled. 
2. At any time, in any sub menu, input yaw left. The onboard osd is re-enabled, but the camera is still connected, and the menu still responds to pitch and roll, but not yaw inputs. 

**Version**
Master, compiled for me for testing an unrelated change. https://github.com/ArduPilot/ardupilot/pull/14513#issuecomment-638567287

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

Have only tested with plane. 

**Hardware type**
Matek f765-wing, running ppm from a d4r-ii. There is nothing but the camera, a vtx, and a rx connected to the fc during my testing. 

My parameters are bone stock apart from setting up my current sensor.

**Comment by aaaaaaudrey** [comment]
![20200606_154537 - Copy](https://user-images.githubusercontent.com/35206674/83953356-dd5b2280-a80d-11ea-84b1-585339e20b85.jpg)

Image of issue 2.
