### ISSUE TITLE
IMU Values disappearing in Kakute F7 V1.5 (Non AIO)

### ISSUE THREAD

**Issue by NitinJSanket** [ArduPilot/ardupilot#14546]
## Bug report
The IMU values seem to be disappearing for a small-time when using Kakute F7 AIO V1.5 (Non AIO) version. This makes the quadrotor twitch and sometimes flip and crash. The problem is not observed on the AIO version however. 

**Version**
4.0.3 and 4.0.4dev

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X4.

**Hardware type**
Holybro Kakute F7 V1.5 Non AIO.

**Logs**
https://drive.google.com/file/d/1rZ9QKi2Y5MBkVWBRDMVS9TXJD5PNpas7/view?usp=sharing

**Comment by NitinJSanket** [comment]
Also been having same twitch issues with Kakute F7 Mini (cant log though).

**Comment by IamPete1** [comment]
Is this still a issue on 4.1?

**Comment by IamPete1** [comment]
No updates, so I'm going to close.
