### ISSUE TITLE
Copter: AttitudeControl could use a delayed target angle for feedback control to increase smoothness

### ISSUE THREAD

**Issue by jschall** [ArduPilot/ardupilot#1456]
AttitudeControl could wait until the copter is physically able to respond to an impulse produced by the feedforward component of the controller before applying a feedback correction.

The way it works now on my autotuned Y6 with a 540 deg/sec/sec acceleration limit is that a 3 degree spike in angle error is produced at the beginning of a step demand in roll. This angle builds up to 3 degrees over 100 milliseconds, and when you take that slope it is 30 degrees per second. When you multiply that by the stab P term, you get 300 degrees per second per second. So, instead of my 540 deg/sec/sec limit, it is increasing the velocity demand on the rate controller at 840 deg/sec/sec!!! I've heard users complain that ArduCopter feels like it is "unlocking" when you move the stick in stabilize. This is probably why.

So now, over the time that it takes to reach the angle target, the feedback controller closes that gap. What happens then? Well, the feedback controller has added so much velocity that the whole thing overshoots by a few degrees. Take a look at the attached image. Imagine shifting the green line to the right by 5 dots. First off, at the start of the curve the feedback controller wouldn't be messing with anything yet. Second off, if we were about to overshoot, the feedback controller would work to prevent that.

This would reduce twitching, reduce overshoot, and generally make AC smoother for the 80% of users that just want to fly as smoothly as possible (maybe we should do a poll on that to figure out what our priorities should be?)

![figure_1](https://cloud.githubusercontent.com/assets/1015761/4573391/d05df86c-4f91-11e4-8295-17556787482b.jpg)

**Comment by OXINARF** [comment]
Is this still applicable today or can it be closed?
