### ISSUE TITLE
Tools/AP_Bootloader/support.cpp:95:21: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]      while (reserved < FLASH_RESERVE_END_KB * 1024U)

### ISSUE THREAD

**Issue by pratik206** [ArduPilot/ardupilot#14596]
hello,

I am getting this error while building the bootloader for mRoControlZeroF7 device. Please help me.

[81/85] Linking build/mRoControlZeroF7/Tools/AP_Bootloader/liblibcanard.a
../../Tools/AP_Bootloader/support.cpp: In function 'void flash_init()':
../../Tools/AP_Bootloader/support.cpp:95:21: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     while (reserved < FLASH_RESERVE_END_KB * 1024U) {
                     ^
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors

Waf: Leaving directory `/root/GitHub1/ardupilot/build/mRoControlZeroF7'
Build failed
 -> task in 'bootloader/AP_Bootloader' failed (exit status 1):
        {task 139668615409008: cxx support.cpp -> support.cpp.2.o}
 (run with -v to display more information)

**Comment by peterbarker** [comment]
On Sat, 13 Jun 2020, pratik206 wrote:

> [81/85] Linking build/mRoControlZeroF7/Tools/AP_Bootloader/liblibcanard.a
> ../../Tools/AP_Bootloader/support.cpp: In function 'void flash_init()':
> ../../Tools/AP_Bootloader/support.cpp:95:21: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
> while (reserved < FLASH_RESERVE_END_KB * 1024U) {
> ^

Which compiler are you using?

**Comment by pratik206** [comment]
I am using gcc-arm-none-eabi-6-2017-q2

**Comment by pratik206** [comment]
Its working just by commenting that lines.

**Comment by peterbarker** [comment]
On Sat, 13 Jun 2020, pratik206 wrote:

> I am using gcc-arm-none-eabi-6-2017-q2

Well that's odd.  I'm using that compiler as well and can't provoke the 
problem.
