### ISSUE TITLE
Copter/Rover: add DO_SET_SPRAY command to enable and desable spray in mission or from GCS

### ISSUE THREAD

**Issue by framosnt** [ArduPilot/ardupilot#14590]
## Feature request

the sprayer drones In mission need to turn on and off the spray system, like photography SURVEY GRID, for this, we need new COMMAND "DO_SET_SPRAY" for use with SPRAY_PARAMETER for variable spray control. 

**Is your feature request related to a problem? Please describe.**
When drone will do turns to next strip, we need to turn off using RCx_Function = 15, but, we need to do this by command line in SURVEY MISSION, for example, to do complete spray mission.

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

**Comment by tatsuy** [comment]
I think that this is achieved by #14736 .
It has not been merged yet.

**Comment by amilcarlucas** [comment]
Got merged.
