### ISSUE TITLE
Compass Boot up Issues

### ISSUE THREAD

**Issue by ardisd** [ArduPilot/ardupilot#14612]
## Bug report

**Issue details**

I have 2 copter both with Cube Black and Here GPS after upgrading to 4.03 I have noticed an issue with the Compass ID on both copters if I boot the pixhawk using USB Power
COMPASS_DEV_ID1 = 466441
COMPASS_DEV_ID2 = 531465
If I boot using the main battery
COMPASS_DEV_ID1 = 531465
COMPASS_DEV_ID2 = 466441

Compass Type Mask is set to only allow HMC5883 and LIS3MDL

**Version**
4.03

**Platform**
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad and Octo

**Hardware type**
Cube Black and Here GPS

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
sorry we never got to this, please reopen if this issue is still present in 4.1
