### ISSUE TITLE
CI: display a PR's firmware size delta in the PR

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#14613]
As part of CI it would be great if after the compile it could compare the stm32 binary size diff.

Wishlist:
- Display filesize delta somewhere in the github PR conversation page.
- Compile PR'd branch with and without branch applied to get the diff

**Comment by magicrub** [comment]
I hear @chennighan might have found a way to do this

**Comment by giacomo892** [comment]
Should by closed.  Fixed by https://github.com/ArduPilot/ardupilot/pull/16597

**Comment by peterbarker** [comment]
Closing, thanks @giacomo892 (and @khancyr for actually doing the work ;-) )
