### ISSUE TITLE
AC_WPNav's get_wp_destination_loc does not set altitude frame

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14621]
AC_WPNav::get_wp_destination_loc() which is used by SmartRTL::get_wp() is not setting the destination altitude type.  It simply adds the altitude from "get_wp_destination()" which is an offset from the ekf origin to the passed in "destination" object's altitude meaning that if it was called over and over the altitude would constantly change.  We should probably set the frame to be either alt-above-ekf-origin (if _terrain_alt == false) or alt-above-terrain (if _terrain_alt is true).

It seems that SmartRTL::get_wp() is used by GCS_MAVLINK_Copter::send_position_target_global_int() and the mavlink specification says:

`Valid options are: MAV_FRAME_GLOBAL_INT = 5, MAV_FRAME_GLOBAL_RELATIVE_ALT_INT = 6, MAV_FRAME_GLOBAL_TERRAIN_ALT_INT = 11`

so I think we should then set the "frame" field to match the frame is of the Location object from get_wp() except if the frame is alt-above-ekf origin in which case we should use the Location object's get_alt_cm() conversion function to convert it to an alt-above-home.

**Comment by hendjoshsr71** [comment]
Closing. I believe this was fixed in SCurves.
