### ISSUE TITLE
Plane: RTL_Autoland = 2 causes mission restart

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#14639]
##Bug report

**Issue details**
RTL_Autoland = 2 causes a mission restart, not a jump to DO_LAND_START

**Version**
Plane 4.0.6 Beta

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Twin electric

**Hardware type**
Cube Orange

**Logs**
https://1drv.ms/u/s!AunBK4rE1ZDCgqhiWzefXKsRL26-Lw?e=CHAva5

**Comment by tridge** [comment]
I've reproduced the issue, it happens when MIS_RESTART=1

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/13652
