### ISSUE TITLE
I can't read analog data on adc pin for pixhawk 2.1 

### ISSUE THREAD

**Issue by omeralierdemir** [ArduPilot/ardupilot#14646]
Hello everyone!. I tried to read analog data on ADC pin for temperature sense.
I followed the steps on this site one by one: https://ardupilot.org/plane/docs/common-rangefinder-maxbotix-analog.html. I read the sonar voltage indicator values ​​steadily 1.19, but when I throw the sensation of temperature in pixhawk, I keep reading the analog data and I see the value reading on mission planner after making the parameter settings even if I don't connect the temperature sensor on the pixhawk cube board. Is this a bug of arduplot for pixhawk cube?
Actually, I want to ask how to read analog data temperature sense on mission planner?
Is it possible to read analog data on adc pins?

"The range is 0 to 3.3 volts. However you have to disable battery measurement if you want to be able to use the ADC inputs." (this is an excerpt) is this true?

Maybe i am setting wrong or missing parameter for pixhawk cube. 
Do you have any idea?

**Version**
V4.1.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Pixhawk 2.1 cube

**Comment by IamPete1** [comment]
The forum is a better place for such questions. https://discuss.ardupilot.org/
