### ISSUE TITLE
MAVFTP usability issues when combined with MP

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14643]
I am unsure if these are Mission Planner issues or flight code issues so I am documenting them both here and in the MP issues list: https://github.com/ArduPilot/MissionPlanner/issues/2413

All of these issues can be reproduced by doing the following:

- Open Mission Planner
- Open the Simulation page
- Ensure the "wipe" checkbox is checked
- Press the Copter icon at the bottom
- Open Config, MAVFtp

When trying to upload a Lua script to a copter in MP's simulator I've run into these problems:

- Click, "@ROMFS", then click on the unnamed (top directory?), 5 second delay before the directory listing is displayed.  5sec is not very long but it is very noticeably longer than if I click on one of the sub directories (i.e. logs) and then switch back to the top directory
![image](https://user-images.githubusercontent.com/1498098/85190872-8ec28380-b2f7-11ea-898b-e4a275274044.png)
- Attempting to create a directory with the same name as an existing directory causes MP to lock-up for 30 seconds.  The directory is not created and no error message is displayed
- Attempting to delete an empty directory causes MP to lock-up for 30 seconds.  A "Failed to delete file" message is displayed and the directory is not deleted
- Attempting to create the scripts directory under @ROMFS causes MP to lock-up for 30 seconds, the directory is not created and no error message is displayed

**Comment by tridge** [comment]
The ROMFS filesystem is read-only, creating files there doesn't make any sense. The files get created as part of the firmware build process

**Comment by rmackay9** [comment]
@tridge, ok thanks for the info.  I'm sure most people won't know this so we will need to protect them from their GCS locking up for 30sec.  I wonder if it's AP misbehaving and not providing a failure message or if it's MP not processing the failure.

@meee1 fyi

**Comment by davidbuzz** [comment]
RO stands for Read Only.

**Comment by rmackay9** [comment]
@davidbuzz, yes, that's understood and great but the GCS shouldn't lock up for 30seconds if the user clicks on the ROMFS directory.

**Comment by rmackay9** [comment]
MP issues now resolved so closing, txs!
