### ISSUE TITLE
Copter: GPS arming check fails when no GPS present despite good position from visual odometry

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/ardupilot#14661]
It is not possible to arm into loiter with no GPS, however once armed the vehicle will fly in loiter perfectly with position from visual odometry.

Not sure if its a good idea to just disable the GPS checks if there is no GPS, hopefully any lack of position should be caught by EKF/Visual Odom/Mandatory GPS checks.

Would be nice if we could display good position from visual odom with green 'GPS' light too.

Maybe we should look to separate the 'do I know where I am' checks from the GPS checks, in the future there are only going to be more ways of getting position that are not GPS.

**Comment by rmackay9** [comment]
@IamPete1, yes, I agree with all of this I think.  We should probably have different arming checks (and notification) based on whether the EKF has been configured to use the GPS or not.

**Comment by anbello** [comment]
@IamPete1 I am able to arm in Loiter using visual odometry. Which value do you use for GPS_TYPE and  EKx_GPS_TYPE ?

**Comment by IamPete1** [comment]
@anbello GPS_TYPE = 0, EK3_GPS_TYPE = 3, ARMING_CHECK = 1. I hit the low hdop pre arm. It would arm if I turned off the GPS arming checks, but I shouldn't have to. (I'm on Copter - dev)

**Comment by anbello** [comment]
@IamPete1 OK you are right, I forgot to have turned off the GPS arming check in the copter I use for Visual Odometry test.

**Comment by peterbarker** [comment]
Resolved by #22393
