### ISSUE TITLE
Copter: coaxial props could potentially be more efficient at different top-bottom throttle ratios

### ISSUE THREAD

**Issue by jschall** [ArduPilot/ardupilot#1467]
X8 copters may be able to hover longer if the ratio of top-bottom throttle in a hover is modified.

Finding the optimum hover ratio could be done by first making the ratio configurable at runtime and then doing a slow sweep in loiter and observing the hover watts.

**Comment by chapman** [comment]
Not 100% conclusive that it results in efficiency improvements with the rig I was testing, but it certainly functions well and could yield more improvements on other copters. Will post results with logs to dev group soon

**Comment by Naterater** [comment]
I think this discussion belongs over here: https://github.com/ArduPilot/ardupilot/issues/665
