### ISSUE TITLE
Can not connect to mission planner 

### ISSUE THREAD

**Issue by pratik206** [ArduPilot/ardupilot#14670]
hello everyone, I have deigned my own custom flight controller board using STM32F7. I have modified existing mRoX21-777 hwdef.dat file as per the ardupilot suggest. I build and flashed new bootloader and boards LED also blinking. then i used the bootloader to upload the firmware with Mission Planner.It is detecting the USB in windows device manager but the problem is connecting to Mission Planner. 

Can i use any APJ_BOARD_ID for this device ? Could you please suggest any necessary changes ?

**Comment by rmackay9** [comment]
@pratik206, this question may need to go into the [Mission Planner issues list](https://github.com/ArduPilot/MissionPlanner/issues) instead of here in the flight code issues list.

If that fails it may help to ask in the ArduPilot ChibiOS gitter channel: https://gitter.im/ArduPilot/ChibiOS
