### ISSUE TITLE
Copter: add exit() method to Mode class

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14689]
Copter's mode class ([see code here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.h#L49)) has an init() and run() function but is missing the exit().

We probably cannot completely remove the contents of the [Mode::exit_mode() function](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.cpp#L316) but we can probably move more than half to reside in each mode.

This should be a non-functional change so while relatively easy to implement make sure you test it!  Remember to check that any change in order of execution has no negative impacts.

**Comment by arshPratap** [comment]
@rmackay9  Sir, could you explain about moving contents of the [Mode::exit_mode()](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.cpp#L316) function.It would help me in understanding this issue. Thanks in advance!!
