### ISSUE TITLE
Change-Speed commands fail

### ISSUE THREAD

**Issue by stringdragon** [ArduPilot/ardupilot#14692]
Problem:
My Hexcopter was flying auto to check the flight stability according to the flight order.

It included changing the speed and altitude during the flight.

But the altitude actually changed, but the speed did not.
There was only one speed change in 10 attempts.

The speed parameters are as follows.
wpnav_speed = 5m/s

I tried to change the flight speed to 1m/s, 3m/s, 10m/s, but no command was executed, and I only flew at the set speed of 5m/s.

Simply put, MAV_CMD_DO_CHANGE_SPEED command during auto missions has some random effect on the copter speed. Sometimes the speed is changed after next waypoint, sometimes not at all.

Build:
Pixhawk2 Flight Controller running 4.0.3 firmware
FUTABA T16SZ radio with R7008SB S.Bus2 FASSTest Receiver
Here2 GPS/Compass
T-Motor MN-605S Kv 170 motors with ALPHA 60A HV ESC
12S lipo, 22000mAh battery (Tattu)
Configured using MissionPlanner version 1.3.70

I can not figure out the cause.

**Comment by IamPete1** [comment]
The forum is a better place for such questions https://discuss.ardupilot.org/
