### ISSUE TITLE
Keep returning error “prearm check failed - check messages”

### ISSUE THREAD

**Issue by 2020614** [ArduPilot/ardupilot#14760]
## Bug report
Keep returning error “prearm check failed - check message“
**Issue details**
![图片](https://user-images.githubusercontent.com/54102691/86596771-5f856500-bfcd-11ea-8cd8-212209c1e628.png)
![图片](https://user-images.githubusercontent.com/54102691/86597098-d7ec2600-bfcd-11ea-8f4b-5125a3309a2a.png)

_Please describe the problem_
Keep returning error “prearm check failed - check message“，and can't switch auto mode（returned messages “PreArm:Need postition Estimate”）

**Version**
ArduRover V4.1.0-dev
commit 6c9d756f11c8675ec59389ed2031bb09b64b665e

**Platform**
- [ ] Rover

**Hardware type**
CUAV V5+

**Logs**
[https://1drv.ms/u/s!AsRqGtahBmzMj2zD4l-ZuY053DIK?e=Af2IpR](url)

**Comment by amilcarlucas** [comment]
Auto mode is only available if position estimate (GPS has lock) is available.
So once you fix that, the error will go away. This is not a software bug.

**Comment by 2020614** [comment]
> 
> 
> Auto mode is only available if position estimate (GPS has lock) is available.
> So once you fix that, the error will go away. This is not a software bug.

Hello, I conducted the test again, the results show that the above situation will also occur in the case of GPS lock。

![微信图片_20200707222718](https://user-images.githubusercontent.com/54102691/86796305-0850c480-c0a1-11ea-89f7-6a65c2e8673f.jpg)

**Comment by peterbarker** [comment]
@amilcarlucas 's is a somewhat simplified version of reality.

What the vehicle needs is to know where it is; usually this is a GPS and sufficiently good other sensors.

In this case you do appear to have lots of satellites.  But you can also see that the vehicle is still unhappy with its position - "EKF failsafe" is a reasonable demonstration of that.

Often this is caused by a bad GPS fix, and often by poor sensor calibration.

That "Vibe" there may be an indication that the accelerometers are being swamped by the amount of vibration being dumped into your autopilot.  Is this running on a machine with an Internal Combustion Engine?

**Comment by 2020614** [comment]
> 
> 
> @amilcarlucas 's is a somewhat simplified version of reality.
> 
> What the vehicle needs is to know where it is; usually this is a GPS and sufficiently good other sensors.
> 
> In this case you do appear to have lots of satellites. But you can also see that the vehicle is still unhappy with its position - "EKF failsafe" is a reasonable demonstration of that.
> 
> Often this is caused by a bad GPS fix, and often by poor sensor calibration.
> 
> That "Vibe" there may be an indication that the accelerometers are being swamped by the amount of vibration being dumped into your autopilot. Is this running on a machine with an Internal Combustion Engine?

Thanks, he runs on a vehicle equipped with an internal combustion engine. The problem has been solved, it is caused by compass interference. The cause of interference may be vibration or surrounding magnetic field. and it is in use now “aka Moving Baseline”。

**Comment by rmackay9** [comment]
Just a small correct, the "Vibe" message on MP's HUD is always there.  It will turn orange or red if the vibration levels are too high.
