### ISSUE TITLE
SITL Build fails on macOS

### ISSUE THREAD

**Issue by harshitsankhla** [ArduPilot/ardupilot#14772]
## Bug report

**Issue details**
Building Plane for SITL

../../libraries/SITL/SIM_RichenPower.cpp:168:28: fatal error: use of undeclared identifier 'htobe16'
        packet.checksum += htobe16(checksum_buffer[i]);
                           ^
1 error generated.

Waf: Leaving directory `/Users/harshit/git/ardupilot/build/sitl'
Build failed
 -> task in 'objs/SITL' failed (exit status 1): 
	{task 4400494160: cxx SIM_RichenPower.cpp -> SIM_RichenPower.cpp.0.o}
 (run with -v to display more information)
SIM_VEHICLE: Build failed
SIM_VEHICLE: Killing tasks
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[*] Plane
[  ] Rover
[  ] Submarine

**Comment by andyp1per** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/14773
Thanks for the report!
