### ISSUE TITLE
In sitl simulation, I can only recognize the ID of the flight mode, but not the English letters of the flight mode

### ISSUE THREAD

**Issue by theonly-unicorn** [ArduPilot/ardupilot#14785]
My new flight mode can only recognize the ID of flight mode in sitl simulation, but can not recognize the English letters of flight mode. Why? How to solve this problem?

**Comment by peterbarker** [comment]
You need to patch `pymavlink` and install it.

Somewhere in these mappings: https://github.com/ArduPilot/pymavlink/blob/master/mavutil.py#L1913
