### ISSUE TITLE
Sub: add support for DO_REPOSITION

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14783]
We've recently [added support for MAV_CMD_DO_REPOSITION to Copter](https://github.com/ArduPilot/ardupilot/pull/14720) and Plane but we should also add it to Rover and Sub as well.

**Comment by muramura** [comment]
RTK and MICHIBIKI provide positional accuracy to the millimeter.
I think you should also support COMMAND_LONG.
What do you think?

**Comment by rmackay9** [comment]
Support for DO_REPOSITION for rover has been added to master so I've reduced the scope of this issue to only include Sub.
