### ISSUE TITLE
hwdef: KakuteF7 and KakuteF7mini motor ordering

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#14797]
This is definition in betaflight firmware:
![image](https://user-images.githubusercontent.com/4748411/87243798-64359780-c46b-11ea-8b9c-944649be9c60.png)
Which makes M1 is M1, M2 is M2, M3 is M3, M4 is M4

This is ArduPilot definition:
![image](https://user-images.githubusercontent.com/4748411/87243815-86c7b080-c46b-11ea-83ab-0fe4830c6e72.png)
I think this is the wrong way that makes the motor port hard match betaflight ordering, if user manually set FRAME_TYPE to 12 betaflightX, the ordering will be wrong. Or when user use Helicopter frame or Plane, the servo ordering are very confusing.

**Comment by andyp1per** [comment]
The only problem is that by changing it anyone who is using the current motor ordering will get a shock. I'm not sure what the right thing to do is - I agree that matching betaflight makes sense, just don't know how we get there safely

**Comment by IamPete1** [comment]
This is a long standing issue, i think the consern was that we would break peoples setups.

https://github.com/ArduPilot/ardupilot/pull/10363

**Comment by IamPete1** [comment]
I think were too late to fix this now, we cant make a change as it would mess up everyone's existing setup. 

The current pinout is documented on the wiki:
https://ardupilot.org/copter/docs/common-holybro-kakutef7aio.html#servo-output-mapping

Its not great but I don't think we can do anything better, so I'm going to close.
