### ISSUE TITLE
AC_Avoid: hide ANGLE_MAX, DIST_MAX and BEHAVE params on Rover

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14806]
Rover doesn't support quite as many avoidance options as Copter so we can hide the ANGLE_MAX, DIST_MAX and BEHAVE parameters.  We should have examples in other libraries where we hide parameters based on the vehicle type.  There's no need to actually remove the parameters, we can just hide them.

**Comment by rishabsingh3003** [comment]
Funny I was just thinking about this a couple of days back. I'll take this one in one of my PR's. We did the same for path planning stuff.

**Comment by rishabsingh3003** [comment]
@rmackay9 I think this can be closed now!

**Comment by rmackay9** [comment]
great, thanks!
