### ISSUE TITLE
ROS no data flow to GCS

### ISSUE THREAD

**Issue by manosmaroulis** [ArduPilot/ardupilot#14814]
## Bug report
Hello,i installed Cartographer with ros to a raspberry pi 3b+.I followed this commercial manual https://ardupilot.org/dev/docs/ros-cartographer-slam.html.I cannot see any data flow from ros to the GCS in the messages section and no visual position estimate in Mavlink inspector.Data is flowing from pixhawk to rpi3 and commands such as rosrun mavros mavsys mode -c 0 work.Thank you in advance

**Issue details**

_Please describe the problem_

**Version**
_What version was the issue encountered with_
apsynckakute
ros kinetic 
Ardurover 4.0.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
pixhawk
**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by khancyr** [comment]
Hello

You just need to ask for some message with `rosrun mavros mavsys rate --all 10 `, check our documentation at https://ardupilot.org/dev/docs/ros-data-from-ap.html !
I will close this as this is a support question and not an issue. Please use https://discuss.ardupilot.org/ for support. Thanks
