### ISSUE TITLE
Scripting compile error on Navio2

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14816]
We seem to be getting this Scripting related compile error on Navio2 on semaphore.

Generating C implementation in directory /home/runner/ardupilot/build/navio/libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega
../../libraries/AP_Scripting/generator/src/main.c: In function ‘handle_method’:
../../libraries/AP_Scripting/generator/src/main.c:649:10: warning: missing initializer for field ‘range’ of ‘struct type’ [-Wmissing-field-initializers]
   struct type arg_type = {};
          ^
../../libraries/AP_Scripting/generator/src/main.c:145:23: note: ‘range’ declared here
   struct range_check *range;
                       ^

**Comment by WickedShell** [comment]
Closing as transient. I can't find any openable semaphore results where this has failed since this was opened. If we get another one please link it here and reopen.
