### ISSUE TITLE
Here 2 gps Canbus vs serial status message

### ISSUE THREAD

**Issue by Vissie26** [ArduPilot/ardupilot#14850]
Hello,

I am using a Pixhawk Cube orange and a here 2 gps and I have a question about the functionality between serial and canbus.

When I connect my here 2 gps via serial. The gps status changes to 3D dgps (sbas correction) within 10 minutes. If I switch it over to Canbus it never happens and the gps status stays at 3 instead of 4. 

My question is: are those messages only sent via serial and not over canbus? It would be nice if that could be made possible.

Kind regards,

Jasper Vis

**Comment by WickedShell** [comment]
Here2 only sends GNSS_FIX, not GNSS_FIX2 over UAVCAN. Fix2 is the newer message which includes the extra bits to tell if it's better then a 3D fix or not. (GNSS_FIX was not a well defined message)
