### ISSUE TITLE
Enhancement - Artificial horizon ladder code correction (NTSC/PAL)

### ISSUE THREAD

**Issue by FasaArg** [ArduPilot/ardupilot#14853]
## Feature request - Artificial horizon ladder code correction (NTSC/PAL)

**Is your feature request related to a problem? Please describe.**
The code as it is now uses sine & cosine to do the math and assume that the pixel matrix as it have 1:1 aspect ratio. 
As is, it gives accurate results in 0 and 90 degrees but the gradient between those gives a drift because of the aspect relation of the characters and the lines of the video standard used (PAL/NTSC)
On 45 degrees, sine / cosine gives 1 and the code draws the ladder as if it were the exact diagonal character, (that would be perfect if the matrix have 1:1 aspect ratio in both standard)

In NTSC this gives 57 degrees of inclination instead of the required 45 degrees, and 51 degrees in PAL as you can see in the attached image.
<img width="1162" alt="pal-ntsc" src="https://user-images.githubusercontent.com/20319132/87863128-2bdffe80-c92e-11ea-9afb-dce8bfcc16eb.png">

**Describe the solution you'd like**
Now knowing the real aspect ratio of both standard (as shown in the previous image) you could correct this with a factor of 1:0.65 for NTSC (12/18.46) and a factor of 1:0.8 for PAL (12/15).
I´m not a developer or a math guy, I solved this as it came to my mind (but i don't know if it ok doing this in this way)

The code was:
<img width="590" alt="originalcode" src="https://user-images.githubusercontent.com/20319132/87863448-6a2aed00-c931-11ea-8a8f-6451e096785e.png">

And now for NTSC (mods marked in red rectangle)
<img width="565" alt="modifiedcode" src="https://user-images.githubusercontent.com/20319132/87863477-89297f00-c931-11ea-807c-4b5a7ae46ba9.png">

Here is a video of the code working on my F765 (arduplane 4.0.5 stable forked branch with personalized fonts)
https://youtu.be/hhxMhFO-05M

**Describe alternatives you've considered**
As i´am not a developer I lack the knowledge to do this, but could be interesting to make this automatically switchable depending on the standard detected, but this is way beyond my league. As far as i see, it should not be too complicated.

**Platform**
[ x ] All

If there is something wrong about any of this, or if there is a reason to do this in the original way, please accept my apologies in advance.
Sorry about my poor english.
Best regards.

**Comment by IamPete1** [comment]
Fix has been merged, Thanks!
