### ISSUE TITLE
MAVFTP: fails to create directory if "scripts" directory does not exist

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14860]
It seems that if a "scripts" directory does not exist on the SD Card, it is not possible to create any new directory using MAVFTP.

Method to recreate the problem:

- Using a CubeBlack set SCR_ENABLE = 1, TERRAIN_ENABLE = 0 and reboot the autopilot
- Use MP's Config >> MAVFtp screen to see if an APM/scripts directory exists
- If it exists:
   - Try to create a new directory called "test", this will succeed
   - Delete the "scripts" directory and any contents
   - reboot the autopilot, go to the APM directory and try to create a new directory called "test2", this will fail
- If it doesn't exist:
  - Open the APM directory and try and create a new directory called "test3", this will fail
  - Power off the autopilot, remove the SD card.  Use your PC to create an APM/scripts directory on the SD Card and insert it back into the AutoPilot
  - Power on the autopilot, use MAVFTP to create an APM/test4 directory, this will succeed

I find this very surprising but surely there is an explanation to do with scripting holding onto a filesystem handle or something like this.

**Comment by IamPete1** [comment]
Closed by #19267 and #19271
