### ISSUE TITLE
Copter: Internal Error 0x400 (constrained NaN) with mRo LocationOne GPS

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14879]
We have had two reports of Internal Error 0x400 when two mRo LocationOne GPSs are used with GPS blending.  The issue is that the LocationOne is shipping with an older version of AP_Periph which does not do dynamic node allocation.  The solution is probably to:

1. ask @pkocmoud to ensure the LocationOne is shipping with the latest AP_Periph
2. extend the wiki documentation to tell users how to upgrade the LocationOne firmware or manually set the node-id ([wiki issue](https://github.com/ArduPilot/ardupilot_wiki/issues/2557))
3. figure out why AP is coming up with a NaN value

- 1st report is here including logs: https://discuss.ardupilot.org/t/copter-4-0-0-released/50545/79
- 2nd report is here: https://discuss.ardupilot.org/t/copter-4-0-0-released/50545/95

This is also mentioned in the Copter-4.0 issues list (search for "LocationOne"): https://github.com/ArduPilot/ardupilot/issues/12547

**Comment by WickedShell** [comment]
Someone probably needs to audit that everything we actually use is filled in AP_Periph. A very quick audit of it shows that `pdop` in fix2 isn't populated for example, and we do use that inside ArduPilot until we've received the aux message, which would propagate bad data in.

**Comment by peterbarker** [comment]
tridge nailed this one with https://github.com/ArduPilot/ardupilot/pull/15871
