### ISSUE TITLE
AP_SerialManager: _PROTOCOL param descriptions missing for CSRF and Generator

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14871]
The title says it all pretty much but in any case, it seems the PRs for adding the CSRF and Generator support missed adding the parameter descriptions for SERIALx_PROTOCOL params.

**Comment by IamPete1** [comment]
I add them in https://github.com/ArduPilot/ardupilot/pull/14852 , of course we might what this fixed sooner than that

**Comment by peterbarker** [comment]
These `SERIALx_PROTOCOL` description strings are now present.
