### ISSUE TITLE
APM Plane: record a manual land during flight to be able to replicate in automatic

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#1488]
I think it's a nice feature, I often work in the same location and manually enter all the waypoint for the automatic landing.
It would be great if the software could record a manual landing and then be able to replicate automatically, for example by hanging at the end of a various mission in that area.
Similarly it might be interesting to record a manual flight to be able to replicate automatically, like with the copter ("SaveWP" function).
I don't think it is impossible to develop this thing, whereas now with the 32 bit board we have many events that can be recorded, throw this challenge to our dearest Tridge.

**Comment by Naterater** [comment]
I think this takes too much development effort for unpredictable results when environmental conditions change. The autoland parameters today have successfully landed many aircraft, and I don't think this would help that much.
