### ISSUE TITLE
Copter: land mode uses GPS even though gps hdop < GPS_HDOP_GOOD

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#1489]
When land mode is invoked by failsafe, even if GPS_HDOP_GOOD is not reached, Land mode try to maintain GPS position...........................

This cause crash!

Is it possible to not consider the GPS until it reaches GPS HDOP GOOD ? and by the way in this case engage LAND in INERTIAL mode ?

**Comment by lthall** [comment]
I think this has been take care of.
