### ISSUE TITLE
Ac4.0.3 tsyn dataflash log

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#14907]
Hello, I would like to know what report TSYN dataflash logs

**Comment by peterbarker** [comment]
On Sat, 25 Jul 2020, roque-canales wrote:

> Hello, I would like to know what report TSYN dataflash logs

https://ardupilot.org/plane/docs/logmessages.html#tsyn-time-synchronisation-response-information

**Comment by roque-canales** [comment]
Thank you.
