### ISSUE TITLE
EKF3 not doing 3D mag fusion

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#14905]
With a copter with EK3 enabled and COMPASS_SCALE=0 the EKF is not starting 3D mag fusion. magStateResetRequest is not being set.
Possibly introduced when GSF was added?

**Comment by tridge** [comment]
we never call calcQuatAndFieldStates in EKF3. That is the function that checks magFieldLearned and sets up the earth field.
It was removed when GSF went in

**Comment by priseborough** [comment]
calcQuatAndFieldStates should have been removed. It's functionality is performed now when magStateResetRequest is set. We need to ensure magStateResetRequest is called when required.

**Comment by priseborough** [comment]
I ended up rewriting calcQuatAndFieldStates so that ot only resets the mag field states and is called when required. See https://github.com/ArduPilot/ardupilot/pull/14906
