### ISSUE TITLE
Copter: add prearm check for home position set

### ISSUE THREAD

**Issue by jschall** [ArduPilot/ardupilot#1495]
We probably shouldn't be allowing an arm at all if home position is not set. RTL cannot work and there isn't really enough indication of that.

**Comment by R-Lefebvre** [comment]
This must be fixed by now?  You cannot arm without a good GPS fix, which should mean home is set on arming? The only exception would be no GPS, but then there's no home to be set anyway.

**Comment by OXINARF** [comment]
I'm closing this on two facts:

- you can't arm without a good GPS lock in modes that need GPS
- #910 is still open to track small issues that might still exist with setting home after takeoff

There has been requests to add a GPS pre-arm check for modes that don't need GPS, but that is a different issue - feel free to open a new issue for that.
