### ISSUE TITLE
Plane: auto mode loiter to alt uses incorrect reference frame to trigger completed

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/ardupilot#14951]
When using terrain following in auto loiter to alt works as expected, however the altitude relative to origin is used for the threshold rather than relative to terrain. This results in a endless loiter.

https://github.com/ArduPilot/ardupilot/blob/8f77536c08af9ffc01334736c92bb25be4c563e2/ArduPlane/navigation.cpp#L56

In that case should be using height above terrain rather than current_loc.alt. However are also other reference frames the mission could be using that would cause the same issue.  

I have a log, but cannot share publicity.

**Comment by tridge** [comment]
good find!
