### ISSUE TITLE
Copter: add pre-arm check that all motors are configured

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#14994]
We have had one report where a user accidentally modified the SERVOx_FUNCTION value that was used for a motor.  We should add a pre-arm check that all required motors are configured.

This issue can be easily reproduced in SITL:

- cd ArduCopter directory
- ../Tools/autotest/sim_vehicle.py --map --console
- param set SERVO4_FUNCTION 0
- arm throttle
- rc 3 1800

The vehicle will flip over on takeoff.

This change was most likely done using MP's gimbal setup screen as shown below.
![image](https://user-images.githubusercontent.com/1498098/89471469-3537ea80-d7b9-11ea-9955-5d3da23d8857.png)

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/21635
