### ISSUE TITLE
Parameter Diff All feature

### ISSUE THREAD

**Issue by InitialFPV** [ArduPilot/ardupilot#15002]
## Feature request
I'm looking for an Ardupilot equivalent to "diff_all" found in betaflight and inav.

This would take the full parameter list and export a list in some readable format of only the parameters that are different from their default/original values. This would be useful to diagnose problems when changing firmware or in my case when trying to diagnose a problem by simply starting from scratch. 

If this already exists I couldn't find it.

**Comment by rmackay9** [comment]
It's a good idea.  I normally keep a file around which is of the defaults and then I do a diff either using one of the buttons on the right side of MP's Full Parameter Tree screen or I use GitTortoise merge.

**Comment by auturgy** [comment]
In mavproxy you can use “param diff”

Regards,

James

**Comment by auturgy** [comment]
https://ardupilot.github.io/MAVProxy/html/uav_configuration/parameters.html#param-diff

**Comment by rmackay9** [comment]
I think it's fair to say that we don't have this request fully covered because the methods described by @auturgy and I involve the GCS which doesn't actually know what the defaults are for the vehicle and version on the autopilot.

**Comment by amilcarlucas** [comment]
@auturgy That link doe not work for me. Do you mean https://ardupilot.org/mavproxy/docs/uav_configuration/index.html ?

**Comment by auturgy** [comment]
No, the link was correct when I posted it. Stephen pulled docs down https://github.com/ArduPilot/MAVProxy/commit/ce8aa7b5c00b937e2297e20641462f7d7667e2e8#diff-2ed2ee3fc39e2c476fd0b5c7bfa24e69

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/20972
