### ISSUE TITLE
Tracker: Head tracking input

### ISSUE THREAD

**Issue by darvin** [ArduPilot/ardupilot#15000]
## Feature request

Head tracking is missing from Ardupilot ecosystem, let's add it

**Describe the solution you'd like**

Ground head tracking solution (for example, fat shark head tracker, or ark bird head tracker, or open source solution) connects to Ardupilot board with AntennaeTracker running on it. The headtracking data, together with USB joystick input connected to the Mission Planner ground station, is being transmitted to remote aircraft

**Describe alternatives you've considered**

External solution: headtracking being transmitted through crossfire module to aircraft's controller 

**Platform**
[  ] All
[ x] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
I'm not really sure how Antenna tracker is involved here, I'm not familiar with the head tracking solutions but it looks like you just plug them into your transmitter, no reason why this method wouldn't work on ArduPlane.

**Comment by StonedDawg** [comment]
assigning rcx_in to servo output does it, but it doesnt work very well since servo min and max limit is not very well adjustable (max at 2200 and min at 500), i can only get -60 to +60 on my 180degree servo...
