### ISSUE TITLE
Copter: aux servo position initialisation is messy

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1503]
The auxiliary servo position initialisation is slightly messy.  The issue is that the aux servos are only enabled when the one_hz_loop() calls RC_Channel_aux::enable_aux_servos().  This call accomplishes two things:
1. initialise the function_mask to map function to channel
2. it enables any channels with functions assigned to them.  at this point pwm values because flowing out to any attached servos.  The value that flows out will be the value set by any previous calls to hal.rcout->write().

The problem is that because the function_mask has not been initialised earlier, mount and parachute objects won't have know which rc-channels they own and thus not hal.rcout calls will have been made.  This means that some random (?) pwm value will be sent to the servos until the next call to the mount or parachute libraries at which time they will set the correct value.

The proper solution is probably to:
1. call RC_Channel::update_aux_servo_function (which is currently private) early in the autopilot initialisation to set-up the function-mask.
2. add init() functions to the mount, parachute, etc to allow them to initialise the servo values
3. call RC_Channel::enable_aux_servos() after the above is done (could be left in the one-hz-loop like it is currently).

One caveat is that I haven't actually 100% confirmed that a bad value gets sent to the servos but I'm pretty sure it does.  It's difficult to catch the bad output because it's very short lived (i think).

Note also that this probablem may not be noticed on Pixhawk with the safety-switch enabled because all outputs to the servos are ignored until the safety-switch has been pushed.

**Comment by auturgy** [comment]
Can this be closed?

**Comment by rmackay9** [comment]
@auturgy, I think we'd need to test whether it's still happening.. we've changed a lot of things but I can't think of any changes that will have improved this.

**Comment by rmackay9** [comment]
I think I'll close this ancient issue..
