### ISSUE TITLE
Alt controller bug during RTL

### ISSUE THREAD

**Issue by buckker** [ArduPilot/ardupilot#15054]
the flightcontroller does not hold the target altitude during RTL. I noticed this behavior on several drones over 200 flights. The drone climbs or descends a few meters on the last waypont and fly on this incorrect altitude to the start point. There is no sign, that the flighcontroller try to adjust the  altitude to the target altitude. This could be potentially dangerous, if the incorrect altitude leads to a crash we obstacles. 

The bug appears with 4.0.3 and 4.0.4

I allready posted the bug here: https://discuss.ardupilot.org/t/auto-mission-climb-after-last-wp-rtl/58362/5

From a flight today: 

![RTL Altitude Bug](https://user-images.githubusercontent.com/7835537/90254459-0e298a80-de43-11ea-937a-f9c69b5f9e16.jpg)

The mission in Mission Planner looks like that:
![Mission](https://user-images.githubusercontent.com/7835537/90254549-35805780-de43-11ea-9482-a358e6e9c470.jpg)

[00000109.zip](https://github.com/ArduPilot/ardupilot/files/5074818/00000109.zip)

**Platform**
[  ] Copter

**Comment by lthall** [comment]
This is because you have set your RTL alt to 3m (300). I suspect you meant to put it in as 30m (3000).

It should not change height but it does because the height reference frame changes but the height does not.

**Comment by IamPete1** [comment]
Sounds like this was a config error.
