### ISSUE TITLE
Completion Waf: complete --target

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#15053]
## Feature request

**Describe the solution you'd like**
We should completeing --target parameter on waf for easier build.

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by Notorious811** [comment]
i am not much familiar with using waf build process, but i can work around with those wscripts, i'm just not able to get what we really looking here by saying "completeing --target parameter on waf ", can you please describe a little

**Comment by khancyr** [comment]
If you are on bash or zsh you may have install our shell completion system : the thing that suggest word when you push the tab key. The support on waf is really basic and it would be good to add completion for the different target we have on waf.

**Comment by Notorious811** [comment]
Gotcha, like a custom bash tab completion script for waf build options for different program groups, i can give it a try

**Comment by NinaPacifier** [comment]
@khancyr I am new to open-source contributions and want to contribute to the ArduPilot organization. Can I work on this issue???

**Comment by khancyr** [comment]
@NinaPacifier sure, we don't have strict rules on assigning issue. So feel free to solve the ones you want to do !

**Comment by khancyr** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/16206
