### ISSUE TITLE
Copter: support change-alt command in Guided mode

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1507]
We simply ignore change-alt commands from the GCS at the moment.  We should either reject them (and send a rejection to the GCS) or add support.

We should certainly support this command in Guided mode and it would probably be quite straight-forward to handle it as a position request to move to the position that is at the current lat/lon position but using the command's altitude..
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/commands_logic.pde#L769

It's possible that we should add support in other modes too although i'm less certain about how it could be intuitively implemented.

**Comment by erikgraham** [comment]
If I understand this, i'd like to say this could lead to an extremely useful feature for end users for guided mode Follow Me. 

 Use case: Mountain Biker or Skier descending a hill. Currently drone will follow, but not adjust altitude.  Even a very basic altitude adjustment based on terrain data would be useful.  Something more sophisticated using sensors could be added later (example: comparing barometric pressure between follow me target and copter would be ideal... but only a few smart phones have barometers).

Video of my brother where this would be useful:

**Comment by GrahamDyer** [comment]
This is more to be able to change altitude during an auto type mission. 

Lets say the 'copter is in RTL and one realizes that just in the direction from which the 'copter will approach is a 16m tree (and your RTL alt is set to 15m), with this working you could command it to go to 25m for the duration of the RTL and be safe. 

Another eamxple is if you're in a LOITER_TIME taking a photo and you need to go higher or lower then this action is just a click away.

![change_alt](https://cloud.githubusercontent.com/assets/3287001/5992687/25c0beb6-aa3c-11e4-9ed8-9baa53847d8b.JPG)

**Comment by khancyr** [comment]
Already supported on Guided with setpoints
