### ISSUE TITLE
Plane: Allow model without rudder/yaw

### ISSUE THREAD

**Issue by TobiasBales** [ArduPilot/ardupilot#1508]
I would like to propose to add an option to disable rudder control for planes 
since I and a lot of other people have quite a few planes without a rudder (i.e. flying wings, skyhunter etc)
and I would like to use the extra channel for other things.

I would be willing to work on it but my guess is that a few pointers on where the code might affect other things would be really helpful.

**Comment by WickedShell** [comment]
Closing as I'm 90% confident this is managed after the servo output change where every channel function is remappable. If that's not true then please reopen.
