### ISSUE TITLE
Copter: don't load up navigation i-terms during take-off

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1511]
This issue came up while testing (in the simulator) takes-offs from a hill (i.e. the vehicle is leaning over).  The lean-angles are used to load up the lat/lon navigation I terms.  This causes the vehicle to initially take-off directly out from the hill instead of straight up.

We should probably test (in a real copter) whether it's better to load up the I-terms or not.  I suspect we shouldn't.

There's a somewhat related issue to the lean_angles_to_accel() function only being called when we switch to AUTO here: https://github.com/diydrones/ardupilot/issues/1477

**Comment by auturgy** [comment]
@lthall can this be closed now?

**Comment by rmackay9** [comment]
Thanks for the ping on this.  I think we can close this one now..
