### ISSUE TITLE
AP_GPS: compatibility issue with u-blox NEO-M9N GPS

### ISSUE THREAD

**Issue by anbello** [ArduPilot/ardupilot#15135]
## Bug report

**Issue details**

I am testing this [GPS](https://store-drotek.com/917-DP0801.html) that use this u-blox [module](https://www.u-blox.com/en/product/neo-m9n-module) (NEO-M9N) with Pixracer and ArduCopter V4.1.0-dev.

It is recognized and I see this msgs:
```
[MAV 001:1] GPS 1: detected as u-blox at 230400 baud
[MAV 001:1] EKF3 waiting for GPS config data
[MAV 001:1] u-blox 1 HW: 00190000 SW: EXT CORE 4.03 (6c5018)
```
But the configuration is not saved even with GPS_SAVE_CFG=1 and I have the following repeated msgs:

```
PreArm: GPS 1 failing configuration checks
GPS 1: u-blox solution rate configuration 0x10008
```

I cannot takeoff in LOITER but I was able to take off in ALTHOLD and then switch in LOITER with success.

The number of seen GPS was 16, that I think is low for this kind of GPS but it could be related to unsuccessful configuration.

**The problem should be here**
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/AP_GPS_UBLOX.cpp#L1181

F9 and M9 have the same `hwVersion`, Ardupilot try to config the M9 as an F9 and fails.

If I comment lines from 1182 to 1185 and change line 1186 in:
`_hardware_generation = UBLOX_M8;`
the M9 is configured as an M8, the configuration succeeds and it is saved.

Obviously this is not a fix, it serves only to point were the problem should be.

**Version**
ArduCopter V4.1.0-dev

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X

**Hardware type**
Pixracer

**Logs**
https://drive.google.com/file/d/17pOy13ih4HvFz3kv3uj_pgOPlL2dC7gO/view?usp=sharing

**Comment by anbello** [comment]
No one interested in M9 GPS (four simultaneous constellations and 25Hz Nav. update rate)?
https://www.u-blox.com/sites/default/files/NEO-M9N_DataSheet_%28UBX-19014285%29.pdf

There is this strange fact that M9 and F9 have the same hwVersion (00190000) but could not be configured the same way.

**Comment by anbello** [comment]
I think this issue is fixed by [this](https://github.com/ArduPilot/ardupilot/commit/8e08d93026b986c8f0c6bbeb4a9cf2af65536da8#diff-94452a535dc39cfc290c8900b32ea3775725649a9adf73666e55bd9467d8603b) commit.

I close it.

**Comment by Giorgo961** [comment]
Hello Anbello,
I am facing the same issue as you are describing above. I am using F765 (v.4.0.7) and with GPS M8Q all worked well. When I connected a new M9N, received the message _u-blox solution rate configuration 0x10008_.
Please, can you advise how can I solve this issue?

**Comment by anbello** [comment]
The issue was solved by the commit linked above. That commit is not included in stable release nor beta, you should use latest from [here](https://firmware.ardupilot.org/Plane/latest/) to have support for M9N, but as you can read [here](https://ardupilot.org/dev/docs/pre-built-binaries.html):
"latest: the most recent build of our git master branch, this contains the latest code. Use with caution, this version has undergone very little testing"

**Comment by Giorgo961** [comment]
Thank you for the information. So, I will wait up to this version will be at least in beta release.
