### ISSUE TITLE
Implement initial mode for Copter

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#15132]
## Feature request

**Is your feature request related to a problem? Please describe.**
There is no official way to set the initial mode in copter. Plane and Rover got a parameter and start on INITIALIZE mode.
On Copter, STABILIZE is set by default. The current method to set an initialization mode is to rely on FLTMODE1.

But in case FLTMODE_CH = 0, FLTMODE1 isn't called and you are stick to STABILIZE on each start.

**Describe the solution you'd like**
Having INTIALIZE mode + a parameter to select initialisation mode would benefit copter. 

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Platform**
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by muramura** [comment]
I have a PR that sets the initial flight mode according to the value of the RC when the FC is activated.
#13330

**Comment by khancyr** [comment]
@muramura the thing I want to avoid is to rely on RC value ... what append if you don't have RC ? you have the same unexpected behavior as currently. 
That why I think that we should do it in two step as in other vehicle : boot in INITIALIZE mode and then switch to the INITIAL_MODE . If you have an RC radio and the mode switch enable you could still override the INITIAL_MODE  with the mode switch.

**Comment by muramura** [comment]
@khancyr san. Will the value obtained from the receiver be indefinite when the propo is not connected?
I believe it is a stable value.
