### ISSUE TITLE
Sub: new frame defaults for ardusub 4.0 release

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#15167]
We need some new default parameter files for vehicles running ardusub 4: https://github.com/ArduPilot/ardupilot/tree/master/Tools/Frame_params/Sub

**Comment by patrickelectric** [comment]
From what I can see 4.0.0 is there, can we close this issue ?

**Comment by Williangalvani** [comment]
this got done in https://github.com/ArduPilot/ardupilot/pull/16022
