### ISSUE TITLE
AC4.0.3 BRD_OPTIONS watchdog  issue

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#15214]
Can anybody confirm that when this parameter is:
set to 0 watchdog is disabled ? 
and 
set to 1 watchdog is enabled ?

**Comment by IamPete1** [comment]
https://ardupilot.org/copter/docs/parameters-Copter-stable-V4.0.3.html#brd-options-board-options

Its a bitmask, bit 0 is watchdog. Mission planner has tick boxes to make it easy.

Because its bit 0 and there are no other bits, your correct, 0 is disabled and 1 is enabled
