### ISSUE TITLE
sdcard problem ChibiOS Plane 4.1.0dev

### ISSUE THREAD

**Issue by adezie** [ArduPilot/ardupilot#15249]
#15249 sdcard problem ChibiOS Plane 4.1.0dev

**Issue details**

recently I just made my own H743 flight controller, everything went well, I set the hwdef.dat file based on MATEKH743, at the first try, everything went well, serial communication, servo, telemetry, SPI, I2C, everything went well,
![asdas](https://user-images.githubusercontent.com/56856398/92317944-454d1f00-f030-11ea-8d6e-968f8dcce4b4.png)
but as soon as I put the sd card, strange things happened, it boot up to bootloader, and then this happens
![image](https://user-images.githubusercontent.com/56856398/92317954-5138e100-f030-11ea-8c85-f0dc126eff4b.png)
I’ve try to looking for trouble shoot, can’t find a clue, here’s what I’ve come up with,
there’s strange folder came up in the sd card called STRG_bak and it contains .bak files
![WhatsApp Image 2020-09-05 at 09 41 20](https://user-images.githubusercontent.com/56856398/92317956-5dbd3980-f030-11ea-8bff-a5329b19c5b3.jpeg)
![WhatsApp Image 2020-09-05 at 18 31 41](https://user-images.githubusercontent.com/56856398/92317958-5eee6680-f030-11ea-91d6-2be092f5b216.jpeg)

it seems like it just looping on storage backup and won't enter the main firmware when sd card is inserted

can anyone help ?
@tridge 

**Version**
4.1.0dev

**Platform**
[   ] All
[   ] AntennaTracker
[   ] Copter
[ x] Plane
[   ] Rover
[   ] Submarine

**Airframe type**
x

**Hardware type**
custom 
H743 based on MATEKH743

**Logs**
x

**Comment by IamPete1** [comment]
Since this board is not in tree I don't think this is really a AP issue. Of course if you can reproduce on a supported flight controller then feel free to re-open. The discord is great place to get help setting up new boards https://discord.gg/xMB9qFwC
