### ISSUE TITLE
Copter: The servo set value exceeds the maximum value.

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#15252]
## Bug report

I typed the command "servo set 9 2000" in SITL.
The output of the MAVLINK inspector servo 9 is set to 2000.
I believe that when the set value is greater than the maximum value, it is the maximum value and when it is less than the minimum value, it is the minimum value.

**Issue details**

SERVO 9 OUTPUT VALUE is 2000:
![Screenshot from 2020-09-06 17-50-02](https://user-images.githubusercontent.com/646194/92322388-e3120f80-f06b-11ea-90c4-41e2a82dfd88.png)

SERVO 9 MAX 1900, MIN 1100
![Screenshot from 2020-09-06 17-50-24](https://user-images.githubusercontent.com/646194/92322410-fa50fd00-f06b-11ea-8954-e4eb0fb50b89.png)

**Version**
ArduCopter V4.1.0-dev (65268ee3)

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

QUAD

**Hardware type**

SITL

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by Hwurzburg** [comment]
I may be mistaken, but I believe the current behavior is intended....and a change could impact users experience...

**Comment by rmackay9** [comment]
It's arguable either way but I probably agree with @muramura that we should enforce the limits when we receive a do-set-servo command.

**Comment by muramura** [comment]
@Hwurzburg san, @rmackay9 san.  Thanks for the comment, I've PR'd it and will close it.
