### ISSUE TITLE
Copter: add "report-only" to FS_BATT_ENABLE parameter values

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1530]
Setting FS_BATT_ENABLE does not completely disable checking of the battery voltage and capacity.  When the batt goes below the FS_BATT_VOLTAGE or FS_BATT_MAH the autopilot won't take control but it still will report the low volt or capacity to the user via LEDs, Buzzer, message to GCS and message in dataflash log.

To be more consistent with other failsafe, FS_BATT_ENABLE = 0 should probably completely disable the checking.  To take the place of the current default behaviour we should add a new "Report only" option.

**Comment by WickedShell** [comment]
Closing as a non issue/desired feature. If you don't want low battery reported then simply unset the triggers for it. If this is strongly disagreed with we can open and resume the debate at that point.

(Regarding the dual failsafes/cause these are available in copter 3.6.0)
