### ISSUE TITLE
Copter: add motor matrix support for decacopter (10 motors)

### ISSUE THREAD

**Issue by Moksh-2000** [ArduPilot/ardupilot#15308]
Hello , i hope all are good ☺️

I want to make decacopter but I still can't find how to do that , (last 2 weeks)  , some people say only motormatrix.cpp custom on your choice and convert into .apj is it right ? 
Can I hope someone help me ?

Thank you 🙂

**Comment by rmackay9** [comment]
@Moksh-2000, AP doesn't support decacopters at the moment.  It's not very difficult to add support but someone would likely need to do a little bit of development.

There's a video here from a pro user who made a custom motor matrix https://www.youtube.com/watch?v=c6aCwSHr_is although I suspect you've already seen this.

**Comment by Moksh-2000** [comment]
> @Moksh-2000, AP doesn't support decacopters at the moment. It's not very difficult to add support but someone would likely need to do a little bit of development.
> 
> There's a video here from a pro user who made a custom motor matrix https://www.youtube.com/watch?v=c6aCwSHr_is although I suspect you've already seen this.
> 
> By the way, AP already supports dodeca-hexacopters which have 12 motors. https://ardupilot.org/copter/docs/connect-escs-and-motors.html#dodecahexacopter

**Comment by Moksh-2000** [comment]
Sir this video already saw , and also comment on this guy on YouTube + our ardupilot discourse but no reply 😕 , sometime I'm very disappointing , and this topic great on 3weeks ago continuously I'm searching N searching When I got bored then reply to you.
Any help appreciated
Thank you 🙂

**Comment by muramura** [comment]
I got curious about the decacopter.
I discovered the motor layout from the video.
![Screenshot from 2020-09-13 17-14-47](https://user-images.githubusercontent.com/646194/93015393-0d2b7a80-f5f4-11ea-8b03-b6f96fe16b8a.png)

I created a table based on this layout.
![Screenshot from 2020-09-13 19-02-31](https://user-images.githubusercontent.com/646194/93015426-524fac80-f5f4-11ea-8ac2-9580c461d65c.png)

**Comment by Moksh-2000** [comment]
Can you show my decacopter design ? , And yes I saw this video after I inspired 😉 , I'm also curious about how it's perform on 9450 props with custom design my motors 😎 , do you have any idea to put in pixhawk ? Because I already done but I nothing find on any suggestions. I am very happy that your message came.
Thank you 🙂

**Comment by amilcarlucas** [comment]
I already explained exactly what lines to copy paste in the motors.cpp file and another user already told you how to change the code. The Wii explains how to compile the code from scratch.
We need you to tell us what exactly is not yet clear.

**Comment by muramura** [comment]
@Moksh-2000 san.  I have finished implementing the sitl environment.  I have added a new frame class 14.  sitl is not aware of this class.  I contacted discord.

**Comment by muramura** [comment]
I'm a source that has finished implementing the whole thing.
If you try to check the operation with SITL, the plane will become a plane.
I want to solve this problem.
Can you solve this problem?
https://github.com/ArduPilot/ardupilot/compare/master...muramura:AP_Support_decaCopter

Add DECAROTOR to the common.xml and minimal.xml of MAVLINK.
MAVLINK is another GITHUB.

![Screenshot from 2020-09-15 00-15-24](https://user-images.githubusercontent.com/646194/93104355-b3f14300-f6e8-11ea-90e3-aed0bc9038c9.png)
![Screenshot from 2020-09-15 00-15-16](https://user-images.githubusercontent.com/646194/93104361-b6539d00-f6e8-11ea-8a46-a401009af5a5.png)

**Comment by amilcarlucas** [comment]
Very nice work @muramura . @Moksh-2000 can you test the code on your copter?

**Comment by Moksh-2000** [comment]
@amilcarlucas I'm sorry for , im noob and also I don't have pc or laptop so I can't , all time pushing on Android as my pc , 
@muramura thank you soo much sir can you tell me how to download .apj file ? I will try on my copter , once again thank you ☺️

**Comment by muramura** [comment]
@Moksh-2000 san. You have the actual device, right?
If you check the operation with SITL and it works properly, it will be the actual device.
I have not been able to check it with SITL.
Can you find the reason why the icon is plain in SITL?

**Comment by Moksh-2000** [comment]
Sir as I mentioned i don't have pc or laptop so I can't check I'm soo sorry plz forgive me 😔 , i have ready my frame with preinstall pixhawk.
Thank you 🙂

**Comment by rmackay9** [comment]
@muramura, maybe you could create a PR with these changes?  I can create a binary for @Moksh-2000.  It's an unusual frame but it's fairly straightforward and doesn't take up a lot of flash space to add support for it.

**Comment by muramura** [comment]
@rmackay9 san. I will proceed with the PR work.

**Comment by muramura** [comment]
I have added a 10-rotor helicopter type DERCAROTOR to the MAVLINK protocol.
https://github.com/mavlink/mavlink/pull/1479

**Comment by muramura** [comment]
@Moksh-2000 san. 10 Rotacopters have been merged into the master. check it out and update us on the status.

**Comment by rmackay9** [comment]
I think I'll close this issue now.  Definitely we'd like to hear back from someone who actually has the vehicle to test with.
