### ISSUE TITLE
Incorrect information in Readme.txt

### ISSUE THREAD

**Issue by edusanketdk** [ArduPilot/ardupilot#15378]
## Bug report

**Issue details**

small modification in Readme.txt at https://github.com/ArduPilot/ardupilot/blob/1e41f7cc61436ac65fa046148bda0b848d640c04/libraries/SITL/examples/Webots/README.md

As suggested in the readme.txt file, `3- run ./libraries/SITL/examples/Webots/drone.sh`, actually it should be `3- run ./libraries/SITL/examples/Webots/dronePlus.sh` .

**Comment by peterbarker** [comment]
@edusanketdk you can make these suggestions as a pull request which we can then evaluate and merge.  It can all be done in the github interface.

The commit message would need to read something like, `SITL: correct Webots README.md`
