### ISSUE TITLE
Please Add support for MMC5883MA compass

### ISSUE THREAD

**Issue by ninja-zx11** [ArduPilot/ardupilot#15455]
## Feature request

Please add support for MMC5883MA magnetometer.This magnetometer is even less noisy than HMC5883L.
Driver is present on pixhawk:https://github.com/traxxas/PX4Firmware/commit/89fe5e7bdf7a91a5bed7a6c88f35a5b56dcbff98#diff-8989715f5461b08efdb89011d2e99b5c

**Platform**
[ * ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

![Compass comparison](https://user-images.githubusercontent.com/37225379/94473993-d459dc80-0181-11eb-962c-0d5670c872f5.png)

**Comment by auturgy** [comment]
what autopilot uses this sensor?

**Comment by pepak** [comment]
MMC5883MA driver has been added: [#16976](https://github.com/ArduPilot/ardupilot/pull/16976)

**Comment by ninja-zx11** [comment]
Thanks pepak. That's awesome. I will test my board soon.
