### ISSUE TITLE
Vibration induced EKF variance results in unnecesary GPS failsafe

### ISSUE THREAD

**Issue by brad112358** [ArduPilot/ardupilot#15489]
I have included links for two logs for flights in which vibration compensation failsafe was followed quickly by a GPS glitch then GPS failsafe resulting in switching from a GPS controlled mode to land mode.  I strongly suspect the position error was on the part of the EKF and not a real GPS glitch.  It seems to me that we should leverage compass and GPS data when EKF has trouble instead of ignoring it.  Shouldn't the position error required to trigger a GPS glitch be increased when EKF variance is high to avoid this cascading failsafe?

**Version**
4.0.x

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
210g 4 inch prop quad

**Hardware type**
Omnibus F4 nono V6

**Logs**
https://drive.google.com/file/d/1saTjRkaS0cboV-Zhy1M_ri2aMCVCc1QN/view?usp=sharing
https://drive.google.com/file/d/1c5jXscqNnUXMsJ1t7VjjAYslU6AVxV57/view?usp=sharing
I also posted about these logs, but haven't yet had much expert comment.
https://discuss.ardupilot.org/t/vibration-ekf-variance-and-associated-gps-glitch-results-in-cascading-failsafe/62244

**Comment by IamPete1** [comment]
sorry we never got to this.
