### ISSUE TITLE
Copter: In-Flight Watchdog reset, Hard fault

### ISSUE THREAD

**Issue by DanS87** [ArduPilot/ardupilot#15488]
Issue details
Autopilot was reset shortly before completing its flight. The Mission was controlled by a companion.

The watchdog error:
![](https://discuss.ardupilot.org/uploads/default/original/3X/e/a/eadfeda25a7daad11cbaf2e973ae1ad7d4b3c2e7.png)

Logs
[before reset](https://drive.google.com/file/d/1qZ_530QpTK0kgDvj7rmp3w4QYCwD_lJc/view?usp=sharing) 
[after reset](https://drive.google.com/file/d/1mIUm4VAYxgJcCe-b0gWDiSY1sMPrjl-C/view?usp=sharing)

second instance of the reset:
[before](https://drive.google.com/file/d/1jbwyZMUuoAq6_4cDWA_G_MWLeGdY3Ni4/view?usp=sharing)
[after](https://drive.google.com/file/d/10PQ9UmG4GdW--K76flKnyg31HyieGXgt/view?usp=sharing)

Version
ArduCopter 4.0.4

Platform
[ ] All
[ ] AntennaTracker
[X] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

Airframe type
Hexa

Hardware type
mro zero f7

**Comment by rmackay9** [comment]
Thanks very much for this report including the logs.  This is pretty serious of course so we are looking into this.

**Comment by DanS87** [comment]
We were able to reproduce the issue again:
Logfiles:
[before](https://drive.google.com/file/d/1jbwyZMUuoAq6_4cDWA_G_MWLeGdY3Ni4/view?usp=sharing)
[after](https://drive.google.com/file/d/10PQ9UmG4GdW--K76flKnyg31HyieGXgt/view?usp=sharing)

**Comment by rmackay9** [comment]
@DanS87,

Thanks again for the report.  It looks like Tridge may have a fix in this PR: https://github.com/ArduPilot/ardupilot/pull/15525

**Comment by IamPete1** [comment]
@DanS87 have you tested https://github.com/ArduPilot/ardupilot/pull/15525 ? (4.1 will include that fix)

**Comment by IamPete1** [comment]
@DanS87 any update?

**Comment by DanS87** [comment]
@IamPete1 
The issue did not occur again, so pretty sure its fixed
