### ISSUE TITLE
Plane: SBUS servo output repeatedly starts and stops working every 2 seconds after upgrade to 4.0.6

### ISSUE THREAD

**Issue by MartinSollie** [ArduPilot/ardupilot#15516]
## Bug report

**Issue details**
SBUS output to servos alternate between working for 2 seconds, and not working for 2 seconds after upgrade to Plane 4.0.6. For versions before this it worked fine. We are using the SBUS output port of a Cube Black connected to a[ PowerBox Mercury SRS](https://www.powerbox-systems.com/produkte/powerbox-systeme/powerbox-mercury-srs.html) which is connected to all servos. When the problem occurs, the Powerbox reports Failsafe and holds the last received servo positions. As the first of the oscilloscope images below show, the SBUS output stops working completely. We have not flown using this as we immediately saw on ground that this was not airworthy and downgraded. This happens for both manual and stabilized modes when testing on ground. 

Both BRD_SBUS_OUT = 1 and 5 have been tested with a similar result.

![20201006_120556](https://user-images.githubusercontent.com/5480498/95192570-b5d39100-07d2-11eb-88bb-affd41b2f64a.jpg)
![20201006_120617](https://user-images.githubusercontent.com/5480498/95193433-1ca57a00-07d4-11eb-940a-a6149cd0d513.jpg)

**Version**
Plane 4.0.6 and 4.0.7beta1 has the problem, versions 3.9.11, 4.0.3, 4.0.4 and 4.0.5 do not.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Flying wing

**Hardware type**
Cube Black

**Logs**
Parameter list: [sbus_bug_parameters.txt](https://github.com/ArduPilot/ardupilot/files/5333255/sbus_bug_parameters.txt)

**Comment by tridge** [comment]
this is fixed with this PR:
https://github.com/ArduPilot/ardupilot/pull/15523
we will be adding this fix into the next 4.0 beta releases
