### ISSUE TITLE
Airsim Simulation - [Errno 111] Connection refused sleeping

### ISSUE THREAD

**Issue by bilginmu** [ArduPilot/ardupilot#15574]
I try to use Airsim with ardupilot. I downloaded a precompiled Airsim binary(Africa). First I ran Airsim with below command
 ./Africa_001.sh -ResX=640 -ResY=480 -windowed
and then I started ardupilot with 
sim_vehicle.py -v ArduCopter -f airsim-copter --console --map
I get the error below:
![err_1](https://user-images.githubusercontent.com/48926254/95982744-2ad54500-0e29-11eb-98d9-c4af65969fd8.png)

**Comment by Abner0907** [comment]
Do you know what 's the problem? I have the same issues.

**Comment by hendjoshsr71** [comment]
@Abner0907  See here: https://ardupilot.org/dev/docs/building-setup-windows10.html#using-sitl-with-wsl-and-xwindows

"Install an XWindows application to run graphical programs such as SITL by installing VcXsrv, Cygwin X or Xming on Windows."

If we can make something clearer here let me know.
