### ISSUE TITLE
AntennaTracker: Add external LED support

### ISSUE THREAD

**Issue by nhadrian** [ArduPilot/ardupilot#1558]
Hi,

that would be really useful to add external LED support for AntennaTracker just like in ArduCopter, especially for GPS status.
Many tracker mechanics have closed housing, so the APM board is not visible during operation.

Regards
Adrian

**Comment by WickedShell** [comment]
Tracker has a notify object, and LED's are added based on the board type so this should be working. It will only reflect the same things normal LED's do at the moment (arming checks/disarmed/armed/gps lock etc).
