### ISSUE TITLE
UI obscured not easy to use on Parallels / Windows

### ISSUE THREAD

**Issue by reduxdj** [ArduPilot/ardupilot#15595]
## Bug report

**Issue details**
Parallels, UI Overlaps and is hard to use
_Please describe the problem_

**Version**
1.37563

**Platform**
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

<img width="1520" alt="Screen Shot 2020-10-17 at 6 37 26 PM" src="https://user-images.githubusercontent.com/322547/96356860-2ae37800-10a9-11eb-9cec-1390ff6a1671.png">

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by amilcarlucas** [comment]
This is a mission planner issue. Not an Arducopter firmware issue. Please report it to mission planner github.

**Comment by magicrub** [comment]
@reduxdj here's the link https://github.com/ArduPilot/MissionPlanner/issues/new
