### ISSUE TITLE
copter404 lua servo output issue

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#15601]
I set servo6_function param to 94

After I send below script:

local pwm = 1120
function update() -- this is the loop which periodically runs
  pwm = pwm + 1
  set_output_pwm(94, pwm)
  return update, 250 
end
return update()

It's what I get on GCS message, and script no work.
Lua: No scripts to run
19/10/2020 12:51:58 : Lua: /APM/scripts/tstgscxxx.lua:7: attempt to call

How to make it work?

I test other servo scripts that are shared on the https://ardupilot.org/copter/docs/common-lua-scripts.html
And it seems that lua servo functions are not enable on copter.......

It's terrible!!!

Thank you so much

**Comment by IamPete1** [comment]
you need to use
`servo.set_output_pwm(94, pwm)`

We have a section on the forum for such questions,

https://discuss.ardupilot.org/c/onboard-lua-scripting/156
