### ISSUE TITLE
Plane: Automatic landing with an enabled rangefinder causes immediate full descent into the ground

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#15608]
## Bug report
**Issue details**

Plane lands excellently using RTK. As soon as we plug in a rangefinder, the landing approach is hijacked and the airplane descends at full rate to the ground. RNGFND_LAND = 0 the whole time. Very repeatable. 

**Version**
4.0.7 beta 2

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Twin motor electric with reverse thrust

**Hardware type**
Cube orange, BlHeli ESC's with telemetry, mRo F9P GNSS with NTRIP RTK streamed

**Logs**
RTK successful landing AND Rangefinder plugged in landing:
https://1drv.ms/u/s!AunBK4rE1ZDCg4g8p77yzpds4a_oRg?e=XC341p

**Comment by peterbarker** [comment]
@Naterater 

![image](https://user-images.githubusercontent.com/7077857/96530459-3adea000-12d3-11eb-8de5-85549f773057.png)

Any idea what's going on there?  Those seem to be abnormally low readings for chunk of level flight?

**Comment by Naterater** [comment]
Don't get me wrong, we have issues to work out with the rangefinder providing better data, but until we enable that rangefinder for anything in the parameters... for example RNGFND_LANDING, I don't understand why any of that should matter.

**Comment by tridge** [comment]
@Naterater thanks for reporting this, I finally found the issue and I believe it is fixed here:
https://github.com/ArduPilot/ardupilot/pull/15710
there were two places where rangefinder data could affect landing when RNGFND_LANDING=0
