### ISSUE TITLE
Issue with SMBus read

### ISSUE THREAD

**Issue by nbelanger99** [ArduPilot/ardupilot#15616]
## Bug report

**Issue details**
When using  Rotoye Batmon smart battery, there's an occasional failure to read all cell voltages currectly (read as 0xFFFF 65535 decimal), about 1-2 times per minute. 

**Version**
(Not yet merged) 

**Platform**
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadcopter

**Hardware type**
Pixhawk 4

**Comment by nbelanger99** [comment]
@nbelanger99 @echoGee

**Comment by rmackay9** [comment]
Thanks for the feedback.  It's probably better to just comment in the PR comments: https://github.com/ArduPilot/ardupilot/pull/15612.

I think I'll close this issue.
