### ISSUE TITLE
SRx parameters forced to too high values when gimbal controller is connected using MNT_TYPE 4 (Mavlink)

### ISSUE THREAD

**Issue by hhackbarth** [ArduPilot/ardupilot#15634]
## Bug report

**Issue details**

When configuring AC 4.0.4 to MNT_TYPE 4 (serial communication to gimbal controller using MAVLink) and setting serial baud rate to 115 kbaud, the following SRx parameters are overriden (ignoring whatever you configured and wrote to manually) to the following values:
SRx_EXTRA1 = 20
SRx_POSITION = 10
SRx_RC_CHAN = 20
These are the recommended values you also find in the copter documentation but they cause a terrible amount of lost packets and parsing errors on the other side (SimpleBGC 32bit extended) making the communication unreliable.

In my opinion values like 20/5/10 would be sufficient in most situations and my guess is that there would be no communication overrun any more.

Problem is that setting the SRx Parameters to other values has no effect. As soon as the flight controller detects the gimbal on that serial port, the SRx parameters are overridden with 20/10/20 and so there is no way to cure the situation through configuration.

**Version**
ArduCopter 4.0.4

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quad (irrelevant for this issue)

**Hardware type**
Cube Orange

**Logs**

**Comment by IamPete1** [comment]
I suspect this is the gimbal setting the AP stream rates, does not look like were doing that on the AP side. 

Is this still a issue on 4.1?
