### ISSUE TITLE
GPIO do not work with MATEK 405 wing

### ISSUE THREAD

**Issue by rac4433** [ArduPilot/ardupilot#15644]
## Bug report

**Issue details**

_Please describe the problem_
GPIO outputs cannot be configured as relay for camera trigger . Matek F405 wing .Given the lack of runcam support here the only way left is to use a small relay ( SPST) and hack the runcams trigger switch . All works great on bench as far as operating camera by open/close relay contacts . I want to use GPIO to energize the relays coil . After 2 days of struggle with every conceivable setting it just does not work ! Everything comes from the radio as it should but this function does not work . Trying to make it work with board armed does nothing . I know the F405's firmware is "abbreviated" but nothing is mentioned about removing GPIO ability in Wiki

**Version**
_What version was the issue encountered with_
4.0.5 and 4.0.6
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
fixed wing
**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
matek f405 wing
**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
I suspect this is a BRD_PWM_COUNT issue. Sorry we didn't get to it at the time.
