### ISSUE TITLE
EKF Transition to secundary compass

### ISSUE THREAD

**Issue by fr-correia** [ArduPilot/ardupilot#15659]
## Bug report

Hi everyone,
I've had some problems with mags in the past and I may give you something new:
If you want to kill compasses in the SITL environment (or with your real aircraft) and force a switch between them, just start the takeoff (mags fusion may not work while on the ground), and pop some big offsets (manually) on the current mag COMPASS_OFFX, Y or Z. The innovations test ratio will grow above 1 for 10s if you insert the maximum values, (-400 or 400) in any of the components, leading to a change of compasses.

Also I found something interesting, whenever there is a switch of compasses, the boolean variable magStateReset is put to true, and can only be put to false again in the function controlMagYawReset(). In the cases of the airplanes the function returns always in the first condition of that function and never really resets the magStates!

**IMPORTANT**
The endgame for this condition is that whenever you change compasses, you never fuse data the same way. Instead of fusing in the FuseMagnetometer() function, it fuses the mag data in the fuseEulerYaw(), which I suppose should only be used when on ground? Maybe this needs to be fixed guys!

Hope i could be of any help! ;) Please give me some feedback about this fuseEulerYaw and FuseMagnetometer, I would dearly appreciate it! @tridge

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
flying wing

**Hardware type**
Pixhawk

**Comment by IamPete1** [comment]
Sorry we never got to this, I'm a little lost as to if this is a issue or not. If it still is maybe you could open a new issue and post some more information a ideally a log.
