### ISSUE TITLE
Copter: pre-arm check of GPS update rate

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1570]
We had one crash on AC3.2 testing because the GPS was updating at only 1hz instead of 5hz.  We should add a pre-arm check that the GPS update rate is ok.
http://diydrones.com/forum/topics/arducopter-3-2-beta-testing?xg_source=msg_com_forum&id=705844%3ATopic%3A1656303&page=257#comments

In that particular case the user was in Stabilize mode when taking off so normally we would not check the GPS but perhaps we should at least check the update rate if a GPS is attached and refuse to arm.

**Comment by WickedShell** [comment]
addressed by #3580 (tagging this so I remember to close the issue once 3850 is in (covers u-blox only, other drivers need to implement the changes after that))

**Comment by WickedShell** [comment]
Done in #6556 in a generic/all GPS manner.
