### ISSUE TITLE
New Motor Geometry Mixer

### ISSUE THREAD

**Issue by PASC-ERT** [ArduPilot/ardupilot#15700]
Feature Request:

We're working on a new copter design. It is a Tri-Copter (Y3 and Y6). There is already such a motor mix geometry. Ours is different in such a way that instead of the current geometry (2 motors in the front and one in the back) ours will have one motor in the front and 2 in the back.

Would it be possible to add this new geometry motor mix to the Y-Configuration pages.

Basically and ideally would be to take the current Y-Configuration with all the futures and flip it around 180 degrees on the X-Axis.

**Platform**
[ ] All
[ ] AntennaTracker
[X] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

**Comment by IamPete1** [comment]
https://discuss.ardupilot.org/t/reverse-tricopter-vtol-plane/39829

For a tradition Tri-Copter with a yaw servo, set FRAME_TYPE to 6.

I think this is what you want, or do you mean a coaxial Y6 with no servo?

**Comment by auturgy** [comment]
I think he means the y is flipped (V at back, I in front). The only real effect this has (on tri or y6) is inverting pitch response

**Comment by PASC-ERT** [comment]
I mean that when you look at a frame from above, the current config has 2 motors in the front and one in the back. The new proposed geometry is having 2 motors in the front and one in the back. Yaw servo on the front motor is acceptable. See attached diagram (not to scale)![image](https://user-images.githubusercontent.com/47184668/97823801-a3d4f900-1c7f-11eb-899b-a72a630fd5ad.jpeg)

**Comment by IamPete1** [comment]
Yes, that is already supported, setup as with normal tricopter and set FRAME_TYPE to 6.
