### ISSUE TITLE
ArduCopter: Using "Safe Path" during RTH

### ISSUE THREAD

**Issue by nhadrian** [ArduPilot/ardupilot#1571]
Hi,

I have an suggestion that could make RTH more safe, (and perhaps really unique in the market.)
I'm sure many of us had at least once a collision caused by obstacles in RTH path.

My idea is that after takeoff, store coordinates and altitude datas in preset time intervals (ie. 10s) like "Safe Points", and when RTL is activated, instead of flying back to home on a straight line, try to catch Safe Points.

Here is the calculation method I immagined. 
First, connect current position and home with a virtual line. Then check out what is the closest stored point within +-60 dergees range in vertical and within +-10 meters of altitude range, and perhaps between 10…30 m distance range. (These ranges are neccessry to avoid copter flying through the complete flight path, or have too much WPs on the safe RTH course) After valid point is found, define this point as the next Safe point. Before safe point is reached (ie. 5 m before), using the same method, check for the next valid safe point.

I'm interrested in your oppinion.

Regards
Adrian

**Comment by rmackay9** [comment]
Here's a somewhat related issue raised for Plane. https://github.com/ArduPilot/ardupilot/issues/2380

**Comment by rmackay9** [comment]
I'm afraid we're not going to get to this for AC-3.4 so bumping to AC3.5.

**Comment by rmackay9** [comment]
![safertl](https://cloud.githubusercontent.com/assets/1498098/21557264/622af0b8-ce6d-11e6-8400-c15e4d5c79a4.png)
Here's an image which shows how the bread-crumb algorithm might work.  The image on the left shows the path the vehicle might have taken starting from the house at the bottom.  As it moves into an area that it hasn't been before, it puts a number into the area equal to the previous location's number + 1.  If the vehicle ever moves into an area that already has a number in it, it compares to all neighbours and ensures number are never more than 1 higher or lower than each other.  If any squares numbers are reduced, it's neighbours must also be rechecked.

**Comment by magicrub** [comment]
See also, flood fill algorithm..

**Comment by magicrub** [comment]
Related issue https://github.com/ArduPilot/ardupilot/issues/2380

**Comment by amilcarlucas** [comment]
Implemented as SmartRTL
