### ISSUE TITLE
Parameter files does not share the same extension

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#15760]
## Bug report

ArduPilot repository does not have a consistent parameter file extension between vehicles

**Issue details**

The following extensions are being used:
 - `*.params`
 - `*.param`
 - `*.parm`

How to replicate:
`git ls-files "*.pa*"`

**Version**
All

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
All

**Hardware type**
All

**Comment by amilcarlucas** [comment]
I think:
* .parm is MavProxy
* .param is MissionPlanner

Have no clue about *params !

**Comment by IamPete1** [comment]
does this matter?

**Comment by IamPete1** [comment]
I'm going to close, please re-open if anyone feels particularly strongly about this.
