### ISSUE TITLE
Matek H743 Not Detecting SBUS RC Link

### ISSUE THREAD

**Issue by boodadude** [ArduPilot/ardupilot#15779]
## Bug report

**Issue details**

I will try to connect an SBUS reciever (FrSky R9) to the RX6 pin of the Matek H743 but the flight controller will not detect the signal. Occasionally the fc will detect the signal after  brand new flash of Arduplane 4.0.7, but loses the signal after restarting. The signal does not recover after this. I have also tried betaflight, where the signal is detected perfectly. For this reason I know it is not a hardware problem. I have had extended conversation with Matek on this issue, and they cannot find the problem. I was directed by them to here because we believe it is a bug in the software. If any more data is needed please let me know.

**Version**

4.0.7

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Flying Wing

**Hardware type**
Matek H743

**Logs**

Parameters: https://drive.google.com/file/d/1tDxTHcJ4iD8wreK5aWJXQ_6x5Lnw0Eax/view?usp=sharing

**Comment by IamPete1** [comment]
Sorry we never got to this, your param file has gone walkabout, please re-open if this issue persists on 4.1.
