### ISSUE TITLE
VFR_HUD.throttle incorrect during tailsitter transitions

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#15798]
VFR_HUD throttle reporting is incorrect during tailsitter transitions....reporting previous VTOL throttle position (last_throttle) for the first second of the transition
[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
This branch should fix, https://github.com/ArduPilot/ardupilot/compare/master...IamPete1:VFR_HUD_throttle

also that exiting throttle hover scaling issue I spotted while looking at #15794.

I will PR once I have tested in RealFlight
