### ISSUE TITLE
MSP with _OPTIONS = 1 and RSSI_TYPE = 1 causes board freeze

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/ardupilot#15824]
Accidentally stumbled upon this following local forum request. see https://github.com/ArduPilot/ardupilot_wiki/issues/3076 for reference.

once you set:
any serial port to PROTOCOL = 33 (MSP)
MSP_OPTIONS = 1 (telemetry bit)
RSSI_TYPE = 1 (analog)

you can reliably trigger a board freeze beyond recovery on subsequent reboot. only resolveable by DFU reboot and fw reflash. 

**Version**
master from oct 2nd up to current master as of nov 16th 2020

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
multiple F4 and F7 type boards (matek 765 wing, matek 405 wing, omnibusF4 etc.)

**Logs**
not applicable

**Comment by FlyEnjoy** [comment]
thanks Basti - posting this at the right place, 
I am eager to test any updates 
Rainer

**Comment by tridge** [comment]
i've reproduced on a CUAV-X7

**Comment by tridge** [comment]
fixed here:
https://github.com/ArduPilot/ardupilot/pull/15827
many thanks for reporting!
