### ISSUE TITLE
COM not changed after install firmware

### ISSUE THREAD

**Issue by moayyad57** [ArduPilot/ardupilot#15856]
i bought new pixhawk 2.4.8 

i connect it Successfully to mission planner  and the COM  status said : COM Quadrotor , when i installed hexacopter firmware legacy , and reconnect it , the status still : COM Quadrotor

how can i ensure that hexacopter firmware installed on it 

sorry im new to pixhawk

thanks

**Comment by IamPete1** [comment]
https://ardupilot.org/copter/docs/initial-setup.html

There is no hexacopter firmware, its all the same, you just have to configure it to suite. Forum is a great place to ask questions if the wiki is not clear.
