### ISSUE TITLE
Plane: Update altimeter (baro pressure) settings in flight

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#1586]
When flying long plane missions change in atmospheric pressure leads to a large error in altitude when landing. A typical mapping mission for our system is around 300 feet AGL, but after an hour of flight the altitude is over 50 feet off due to pressure changes. For extended operations it would be very nice to be able to update the barometric pressure reading (much the sameway that manned aviation does).

Using an additional APM on the ground as a known reference would be fine, although it would be nice if standard pressure could be entered from the surronding airports.

**Comment by lennoncork2** [comment]
I've been trying to get GND_ALT_OFFSET to work as expected. I've been using the ArduCopter 3.3.2 SITL simulator and changing GND_ALT_OFFSET doesn't seem to have any impact in the system. I would have expected a change in the reported altitude GLOBAL_POSITION_INT and the aircraft to track to the new height. I can however get the desired effect by setting GND_ABS_PRESS and GND_ABS_TEMP, however the jump in reported position looks a little severe (and make me wonder if it's a safe thing to do mid flight).

**Comment by magicrub** [comment]
@lennoncork2 what version are you running?

**Comment by magicrub** [comment]
Oh, somehow I missed that you said v3.3.2, my bad. Have you tried comparing your baro to GPS alt? You should see a difference when you apply GND_ALT_OFFSET.

**Comment by lennoncork2** [comment]
Thanks @magicrub, sorry for the simple question, but what message is specifically reporting the baro altitude. I have compared the altitude reported in GLOBAL_POSITION_INT to the altitude in GPS_RAW_INT, and see no relative change when setting GND_ALT_OFFSET. The aircraft (appears to) tracks the altitude reported in GLOBAL_POSITION_INT, and the details on Altitude Hold (http://ardupilot.org/copter/docs/altholdmode.html), say that the aircraft flies to barometric altitude, so I assumed that the reported altitude in GLOBAL_POSITION_INT was in-fact barometric (or some filtered variant of it).

**Comment by lennoncork2** [comment]
Also, when I set GND_ABS_PRESS, I see a change reported in GLOBAL_POSITION_INT, and the aircraft tracks to the new altitude.

**Comment by magicrub** [comment]
Maybe copter works differently than plane for this, not sure. Please start a new issue so it can be tracked instead of hijacking a closed issue.
