### ISSUE TITLE
Parametrer GND_EXT_BUS is hardcoded

### ISSUE THREAD

**Issue by kg9316** [ArduPilot/ardupilot#15887]
## Bug report

**Issue details**

Not possible to change parameter GND_EXT_BUS, makes it difficult to use other boards.

**Version**
Ardusub > 3.6.1 (maybe also from 3.5.1)

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[x] Submarine

**Airframe type**
Custom

**Hardware type**
mRoX21-777

https://github.com/ArduPilot/ardupilot/blob/ad9d6e96d95dc82c88b0f508d34c911b39eef135/ArduSub/system.cpp#L38-L53

**Comment by peterbarker** [comment]
Fix was merged.
