### ISSUE TITLE
CAN GPS instance assignment

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#15908]
If you have two CAN GPS modules then at the moment there is no way to guarantee which will be the first GPS and which will be the second. This is especially problematic if the GPS POS parameters are not zero.
We need a way to specify which GPS is which.
Here are a few possibilities:
 - we could add GPS1_DEVID and GPS2_DEVID, like we do for other sensors, then have a GPS_PRI1_ID and GPS_PRI2_ID, similar to compass
 - we could use GPS1_NODE and GPS2_NODE, so it only aligns on CAN node ID

the first method would also allow ordering of serial devices. The 2nd would only work for CAN

**Comment by tridge** [comment]
need to cope with same node ID on two different CAN buses

**Comment by priseborough** [comment]
I think we should avoid the implication of 'priority' in the parameter name if adopting the DEVID approach. With GPS, the parameters are assigning a SW instance to a physical device, not necessarily assigning a use priority.

**Comment by pompecukor** [comment]
Seems this can be closed now @tridge
https://github.com/ArduPilot/ardupilot/pull/16156

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/16156
