### ISSUE TITLE
MAVLINK RC CONTROL VIBRATION PROBLEM

### ISSUE THREAD

**Issue by eremteknoloji** [ArduPilot/ardupilot#15914]
There is no vibration when controlling the drone with the RC controller. However, when I rcoverride with serial connection, vibration occurs. I would be glad if you could help. Thank you.

**Comment by amilcarlucas** [comment]
If you do not provide us with more information, no we can not help you.

So please provide binary logs, pictures, firmware versions and hardware used, etc.
And post it on the support forum: https://discuss.ardupilot.org/

github is reserved for confirmed bugs.

**Comment by eremteknoloji** [comment]
Thanks Lucas. 

I'll be glad, if you help me.
