### ISSUE TITLE
GeoFence not being disabled in Auto mission during Vtol Land.

### ISSUE THREAD

**Issue by AdrianCou** [ArduPilot/ardupilot#15917]
## Bug report

**Issue details**

Using fully auto mission (Auto VTOL_TAKEOFF & VTOL_LAND) with GeoFence with a non-zero FENCE_MINALT.
Issue seems to occur with FENCE_AUTOENABLE set to 1 or 2 (as 3 cannot be used with a non-zero FENCE_MINALT).

During VTOL landing, aircraft passes through MIN_ALT and triggers a RTL response (FENCE_ACTION = 4).

Aircraft transitions back to fixed wing flight and then RTL's.. switches to QRTL (Q_RTL_MODE = 1) when within RTL_RADIUS (50m).

Aircraft descends in QRTL through MIN_ALT and triggers a RTL response and then repeats...

To land aircraft, had to disable FENCE_ACTION.

**Version**
Version 4.x of ArduPlane (Apologies, dont have access to autopilot at the moment).
Recreated in SITL / Mission Planner 1.3.74 build 1.3.7563.27684

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Fixed Wing VTOL

**Hardware type**
PixHawk Cube Black

**Logs**
Attached Log from SITL.

[2020-11-28 09-20-31.zip](https://github.com/ArduPilot/ardupilot/files/5609882/2020-11-28.09-20-31.zip)

[2020-11-28 09-20-31.log.zip](https://github.com/ArduPilot/ardupilot/files/5609887/2020-11-28.09-20-31.log.zip)

**Comment by lthall** [comment]
This seems to be a bug where the landing in quadplane is treated as normal flight causing a state loop.
