### ISSUE TITLE
Rover: pivot turns broken in master?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#15919]
It seems that at somepoint between Rover-4.0 and 4.1 we have broken pivot turns.

This can be recreated in SITL by running "rover-skid" with all default parameters and then creating a simple back-and-forth mission.  The results are shown below and we can see the vehicle is doing a regular turn at the corners instead of a pivot turn.

![image](https://user-images.githubusercontent.com/1498098/100492170-12b54d00-316d-11eb-8d5c-09d320834822.png)

This PR https://github.com/ArduPilot/ardupilot/pull/14970 (from me) is likely to blame somehow

**Comment by rishabsingh3003** [comment]
Was #15677 a consequence of this issue?

**Comment by rmackay9** [comment]
@rishabsingh3003, I'm really not sure yet actually.  When I did some testing on the weekend I was expecting pivot turns to not work if OA was enabled but I found they weren't working even with OS disabled.  I hope to look into it more this week..

**Comment by rmackay9** [comment]
This is fixed in master now so closing
