### ISSUE TITLE
Recognize intelligent payloads to change parameters

### ISSUE THREAD

**Issue by WeareGermans** [ArduPilot/ardupilot#1592]
Hi,

i'd love to see a possibility to recognize the payload.
Maybe via one PWM channel or better via IDs (which would need a controller on every Payload)

Goal is to load the respective config file (which needs to be able to have different configs available, maybe via SD card).

Example: You switch from a heavy camera rig with NEX or DSLR to a combination of a much smaller camera, an EPM grabber and maybe some search light. The weight distribution and amount of will be totally different. Even the setting of the outputs (not the motors of course) can be different, too.

It would be pretty neat if all this can be taken into account by just automatically change to another set of values (which of course should have been tested and calibrated before)

**Comment by WickedShell** [comment]
At this point I think you can actually manage this entirely with scripting if you wanted. If I missed something with that please feel free to reopen it for further discussion, but I think scripting is probably the best path for this type of payload awareness, particularly when you don't need to change it completely on the fly.
