### ISSUE TITLE
GPS glitches when using two GPS modules

### ISSUE THREAD

**Issue by hsteinhaus** [ArduPilot/ardupilot#1597]
A flight log with two active GPS modules shows 23 GPS glitches in 5 minutes of flight, while GPS conditions were OK (HDOP<2.0).

Flight log is available here: 
https://www.dropbox.com/s/9jp5dg32wzvu9bu/iris-dual-gps-326.BIN?dl=0

More information: https://groups.google.com/forum/?nomobile=true#!topic/drones-discuss/P5MqTgdF8N4

**Comment by silverburn** [comment]
Me too. 2x M8N's - plenty sats, no visible impact on flight. But *tons* of errors.
![1](https://cloud.githubusercontent.com/assets/4953257/6685489/8ab8df62-cc9a-11e4-95fc-d181e22234db.png)

**Comment by rmackay9** [comment]
These are support issues and really shouldn't be logged in the github issues list. Instead they should go on the APM Forum.  Sorry to be strict but we can't let the issues list become a support center.

**Comment by silverburn** [comment]
Happy to do that Randy, but I've tried posting on DIYdrones with no response, and in *my entire use* of ardupilot support, I've never had a response to any query; to the point I don't really post there anymore. (It's actually down at the moment as well). This appears to be the only place where an issue with dual GPS units is known.

**Comment by rmackay9** [comment]
This is strongly related to this other issue: https://github.com/diydrones/ardupilot/issues/1875

**Comment by magicrub** [comment]
will be fixed by https://github.com/ArduPilot/ardupilot/pull/5642

**Comment by rmackay9** [comment]
fixed in master so closing.
