### ISSUE TITLE
EKF3: fusing of last dead-reckoned yaw re-uses yawAngDataDelayed

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#16000]
EKF3's NavEKF3_core::SelectMagFusion() populates the yawAngDataDelayed variable in two ways:

- using storedYawAngle.recall (i.e. extracts the yaw from the storedYawAngle buffer at the delayed time horizon)
- using the previous EKF iteration's yaw as a way to store the last good dead-reckoned yaw

Although this seems to work I think the second way listed above is not good programming practice because:

- we don't do this kind of thing with any other "Delayed" variables in the EKF
- it makes it unclear to the reader what the source of yawAngleDataDelayed is
- the fusion of the dead-reckoned yaw angle held in yawAngDataDelayed is triggered by calling fuseEulerYaw(false, true) where the "true" essentially means "get the yaw angle from the yawAngDataDelayed structure".  This seems like a very non-standard way to pass data and we should instead pass a heading into fuseEulerYaw.
- the code is also duplicated twice within the SelectMagFusion function

I think we should replace the re-use of yawAngDataDelayed with a lastKnownYaw value similar to how we use  lastKnownPositionNE. to hold the last known horizontal position

**Comment by peterbarker** [comment]
Closing this as the related PR was merged - and it stopped reusing the variables.
