### ISSUE TITLE
Quadplane: VTOL_TAKEOFF altitude it is added to the current one in case of mission restart in flight

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#16049]
If reset a mission in flight and restart AUTO the declared height VTOL_TAKEOFF is no longer relative to the take-off height but to the current one during the flight.
Example, the quadplane is in fixed wing flight at a height of 40 meters and the VTOL_TAKEOFF in the mission is 30 meters, if i reset and restart the mission the quadplane switch to MC and will perform the MC->FW transition to 70 meters (40 + 30) and not 30 meters from zero of takeoff.
In this case being in fixed wing flight at 40 meters it should instead ignore the VTOL_TAKEOFF because it is lower and continue to the next event id in the mission.
Subsequent mission events respect their height regularly, only VTOL_TAKEOFF has this problem in case of mission restart.
Tested in the SITL with the latest master.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadplane

**Comment by robustini** [comment]
This log clearly shows the problem.

[2020-12-14 11-39-47.zip](https://github.com/ArduPilot/ardupilot/files/5688250/2020-12-14.11-39-47.zip)

**Comment by EERomeo** [comment]
The Vtol does not respect takeoff, like the plane does!
You have a parameter, 'respect takeoff frame' which is disabled by default, you have to enable it in parameters.

**Comment by robustini** [comment]
Damn, I missed that, thanks!
