### ISSUE TITLE
INITIALISING mode can be setted and allow arming

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#16043]
## Bug report

**Issue details**

testing https://github.com/ArduPilot/ardupilot/pull/15706, @rmackay9 notice that INITIALISING mode can be settled at anytime and also allow arming bypassing most check.

We should correct this by using the initialisation completion flag to prevent to enter into INITIALISING mode and disable arming support.
A solution could be to add INITIALISING to a black list to implement mandatory_checks() on each vehicle.

**Version**

https://github.com/ArduPilot/ardupilot/commit/ce87b62dcccb2c391d08bb5c78d0da00a3ceacd7 and surely since INITIALISING mode is implemented

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
aLL

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
fixed in master thanks
