### ISSUE TITLE
AC4.0.5 cannot access to serial port with lua script

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#16063]
I test the example:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/UART_log.lua
uploaded in SCRIPTS folder on the sdcard
I set serial 4 protocol to 28 and baud 9600, but this no work...
What I do bad?
Can anyone help?

Thank you so much.

**Comment by WickedShell** [comment]
The serial/uart stuff isn't available in the copter stable release, it's only in master at this point. I don't expect it to be backported so it will be available in Copter 4.1 or on master now.
