### ISSUE TITLE
Plane: Pitch controller - roll compensation math irregularity

### ISSUE THREAD

**Issue by fr-correia** [ArduPilot/ardupilot#16098]
## Bug report

**Issue details**

Hi guys, I found this problem when looking carefully to the pitch controller. So here is the thing: In the link https://ardupilot.org/plane/docs/roll-pitch-controller-tuning.html , you can find a general picture of the pid controllers used to control the several attitude angles. In the case of the pitch we have this:

![image](https://user-images.githubusercontent.com/64488595/102634451-c47ee280-4149-11eb-94d4-14c54af7cc20.png)

where in the inferior part of the image we can see that the roll compensation is something like: Roll compensation = PTCH2SRV_RLL * gravity / (airspeed * tan(bank angle) * sin(bank angle)).

When you search the code, things are a bit different. In AP_PitchController.cpp  the (tan(bank angle) * sin(bank angle))
 term is inverted and the formula gets to be (gravity/airspeed) * tan(bank angle) * sin(bank angle).

I'm reporting this because either the image is wrong or that term on the pitch controller is inverted. Hope I could be of any help.

**Version**
v4.01

**Platform**
[ ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
ALL

**Hardware type**
ALL

**Comment by khancyr** [comment]
hello,

The images are 5y old, so surely outdated. But it is worth checking !

**Comment by rmackay9** [comment]
Questions should go to discuss and/or discord instead of the issue list so I'm going to close this.  Sorry to be strict but otherwise our to-do list turns into another support forum.

Apologies, I hope someone has an answer though..

**Comment by fr-correia** [comment]
Hi @rmackay9 . I understand, still I had no success in having an answer to this issue. At the time, I decided to issue a report here as a bug, because it could potentially be major bug, just in case the figures show the real equations to be used.

**Comment by kniuk** [comment]
It looks straight forward to me as more up elevator (pitch up) needs to be added in higher bank angles.
Hence _tan(bank angle) * sin(bank angle)_ must be in nominator.  The way it is in the code. Bug in the drawing IMHO.

**Comment by fr-correia** [comment]
Thanks @kniuk ! I think I got it

**Comment by magicrub** [comment]
Any volunteers to help update the image?
