### ISSUE TITLE
Copter: Autotune enhancement, auto repositioning during the procedure

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#1609]
It would be interesting that the copter could go back to where you run Autotune alone, without having to manually reposition each time.
I think it would be quite easy and convenient, it's sufficient to define a radius (example, AUTOTUNE_RADIUS: 20 meters) beyond which the copter back perfectly on the initial virtual waypoint when engage Autotune and continued from where it left off.
Also at the end of the procedure may also perform an automatic Land on this waypoint, this may confirm that has been successful, in the negative case may be in Position Hold to indicate that there have been problems.
In which case the GPS doesn't work Autotune should behave as now.
Currently we don't have a feedback watching the drone when the process is complete.

**Comment by DanBar1971** [comment]
+1

**Comment by ajghor** [comment]
+1

**Comment by ErikGroeneveld** [comment]
+1

Op donderdag 28 mei 2015 heeft ajghor <notifications@github.com> het
volgende geschreven:

**Comment by netpaulus** [comment]
+1

Less commands to get the right position in autotune = less time to do it. This is a good idea.

Pierpaolo

**Comment by andrea25** [comment]
Good idea!

**Comment by veepee78** [comment]
+1

**Comment by amilcarlucas** [comment]
This has been implemented now.
