### ISSUE TITLE
3DR Radio: wireless encryption

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#1610]
We have discussed many times, in my country (Italy) and in many others in Europe we could not use APM Copter or Plane in critical restricted operations because the 3DR telemetry has no encryption level.
This unfortunately is castrating and company will push many to adopt other systems where this thing is doable.
I hope Tridge or Kevin can quickly find a solution to the problem or here the market of our drones inevitably will move to other platforms where this system exists (DJI for example).

**Comment by davidbuzz** [comment]
now available:  http://store.rfdesign.com.au/rfd-868-modem/

**Comment by naktinis** [comment]
@davidbuzz maybe you know what "software still in development for this" means in the product description page? Has anyone tested the encryption feature on RFD 868+?

**Comment by davidbuzz** [comment]
It's open source, and the code is available, and looking at the history of the commits, there appears to have been AES references in parts of the code from as far back as 2 years ago.  Maybe you should ask the manufacturer directly..?   https://github.com/RFDesign/SiK/tree/SiK/Firmware/radio/AES

**Comment by naktinis** [comment]
Yup, did it already, just thought someone actually used it.

**Comment by samacumen** [comment]
My comment comes 2 years after the last post on this page. RFD-868 seems to be 4 years old now in development, has AES encryption been enabled in it?

Has anyone used it? @naktinis , @davidbuzz

**Comment by amilcarlucas** [comment]
AFAIK The SiK firmware provides AES encription (for the 3DR modems), but you need to compile it from source because no official releases have it.
The last comit is over one year old because it has been working fine, so no need to fix it.

@tridge correct me if I am wrong.

**Comment by samacumen** [comment]
@amilcarlucas Thanks for the update. Have you tried using it on the standard 3DR modems, can they handle the encryption part? It makes me imagine encryption/decryption could be too heavy on the 3DR radios resulting in packet loss/lower practical baud-rate. Any views on this, I might be mistaken.

**Comment by magicrub** [comment]
This wasn't mentioned in this thread so I'll state it: ArduPilot itself has no encryption but the MAVLink 2.0 protocol used by ArduPilot can use SHA256 signing and that is passed over the 3DR radioes or anythign else using a serial port. So, it's not "encrypted" but it's close. This was implemented about 1.5 years ago. I suggest giving it a try.

**Comment by samacumen** [comment]
@magicrub Thanks for sharing, and yes I am aware of signing implementation and also have read the Google docs document here (https://docs.google.com/document/d/1ETle6qQRcaNWAmpG2wz0oOpFKSF_bcTmYMQvtTGI8ns/).

However, it might be easier for me to use an encrypted link (if feasible) as its for a product and signing could be hard to debug in case we fall into some packet loss issue (e.g. due to timestamp mismatch in the signing algorithm).

**Comment by samacumen** [comment]
Also, I found that there are two versions of RFD868 or RFD900 radios: **ending with "+" OR "x"**

AFAIK there is no easy way to encrypt the data link on the **RFD868+**, only the **RFD868x** has the built in AES encryption hardware. Without that you would need to encrypt the data stream that is being sent to the radio, the radio won't do the encryption for you.

**Comment by OXINARF** [comment]
Closing this as the radio encryption isn't related to ArduPilot. Also, for discussions like this please use the forum (http://discuss.ardupilot.org).

**Comment by magicrub** [comment]
This is the repo that hold the SiK firmware: https://github.com/ArduPilot/SiK but this is a bit more of a discussion item
