### ISSUE TITLE
Rudder disarm does not function in QACRO mode

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#16119]
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover
[  ] Submarine

Easily reproduced in SITL....change to QACRO, rudder arm, cannot rudder disarm

**Comment by IamPete1** [comment]
@Hwurzburg I cant reproduce in SITL anymore.  Maybe this is fixed?

**Comment by Hwurzburg** [comment]
me either...closing
