### ISSUE TITLE
Wrong/missing IMU in HWID page

### ISSUE THREAD

**Issue by hagove** [ArduPilot/ardupilot#16112]
## Bug report

I have ha 3DR Pixhawk Mini, flashed with the latest copter firmware, fmuv03 - 4.0.5
BRD_TYPE set to 5 (Pixhawk Mini)

This board has 2 IMU`s,: MPU9250 and ICM20608

The ICM20608 does not show up in the Mission Planner HWID page.
Instead a MPU6000 (Which is not on this board) show up in the list.

https://discuss.ardupilot.org/t/3dr-pixhawk-mini-which-firmware/62750/3?u=oveh

![hwid](https://user-images.githubusercontent.com/76400598/102862937-25503880-4432-11eb-8811-38dbc9310da8.png)

I have also tried the Pixhawk firmware.
On this firmware, only the MPU9250 shows up in the HWID page..

**Version**
4.0.5 (Have also tested several other version with same result)

**Platform**
Only tested on Copter

**Airframe type**
NA

**Hardware type**
3DR Pixhawk Mini

**Logs**
See attached picture

**Comment by magicrub** [comment]
@meee1 I wonder if this is actually a problem with Mission Planner, and not with the firmware?

**Comment by auturgy** [comment]
No, that’s in the code. 20608 will identify as a 6000.

Regards,

James

**Comment by auturgy** [comment]
https://github.com/ArduPilot/ardupilot/blob/c75848435eeac4ee75089a488e46a73ef8c4a89e/libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp#L220

Regards,

James

**Comment by magicrub** [comment]
@auturgy  ahh yes, that would do it. Thanks for finding that! Now, what to do about it?

**Comment by auturgy** [comment]
From memory there were issues with id’s for the 20608 and it’s better this way. It’s such a critical library that we’d need a very good reason to make a cosmetic but functional change.

**Comment by hagove** [comment]
So this only affects the DevType name in Misson Planner?
It will not affect the gyro scaling or IMU performance in any other way?

**Comment by auturgy** [comment]
No, everything is working and the driver is doing the right things. Very observant of you to notice by the way!
Do you mind if I close this?

**Comment by hagove** [comment]
No, I don't have any problems with you closing it, when I know why, and that it will function correctly anyway. 
But the wrong IMU type in the HWID page, made me a little bit concerned when first noticed.
Thank you for the clarification.
