### ISSUE TITLE
This is almost certainly a user configuration issue not a bug, so please raise in the forum - discuss.ardupilot.org

### ISSUE THREAD

**Issue by NitinJSanket** [ArduPilot/ardupilot#16147]
This is almost certainly a user configuration issue not a bug, so please raise in the forum - discuss.ardupilot.org

_Originally posted by @auturgy in https://github.com/ArduPilot/ardupilot/issues/16146#issuecomment-751429551_

Btw the same thing works in old firmware (4.0.0) without an issue.

**Comment by auturgy** [comment]
Feel free to comment on the previous issue.
