### ISSUE TITLE
4.0.6.rc1 Quad shoots into air when switched to AltHold

### ISSUE THREAD

**Issue by NitinJSanket** [ArduPilot/ardupilot#16146]
## Bug report

**Issue details**

The quadrotor shoots into the air with full throttle when switched from Stabilize to AltHold or Loiter. Using TFMini lidar indoor without GPS on a Holybro Kakute F7.

**Version**
4.0.6.rc1

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X4.

**Hardware type**
Holybro Kakute F7

**Logs**
https://drive.google.com/file/d/1YiMtv_jK7PZo-0LnQXtjZay-OFNNc5YN/view?usp=sharing

**Comment by auturgy** [comment]
This is almost certainly a user configuration issue not a bug, so please raise in the forum - discuss.ardupilot.org

**Comment by NitinJSanket** [comment]
I'm pretty sure it's not a user bug. I am attaching a few more snapshots. The AHR2 altitude looks perfect but the CTUN Alt is garbage.
![image](https://user-images.githubusercontent.com/12091857/103166322-e71a9680-47ee-11eb-8c5c-295d2530afaa.png)
![image](https://user-images.githubusercontent.com/12091857/103166331-f0a3fe80-47ee-11eb-98e9-1ea4dfa249ce.png)
