### ISSUE TITLE
Assign unique SYSTEMID to SITL and QGC.

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#16163]
## Feature request
I use SITL, MISSION PLANNER, QGROUNDCONTROL, and APM PLANNER2 to debug.
I have a communication anomaly with FC due to SITL's GCS, MISSION PLANNER, and QGROUNDCONROL using the same system ID.
I, APM PLANNER2, do not occur because of 252.
I think it is better to assign unique ID.

I will assign a unique ID, and if I really want to use 255, I will make it changeable.
SITL, MISSION PLANNER and QGROUNDCONTROL can be changed by the user.

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
![Screenshot from 2020-12-29 22-45-32](https://user-images.githubusercontent.com/646194/103288594-89718e80-4a28-11eb-80a5-6f034669950a.png)

**Comment by khancyr** [comment]
there is already unique identifier : 
https://mavlink.io/en/messages/common.html#MAV_COMPONENT for the routing and https://mavlink.io/en/messages/common.html#MAV_TYPE on the heatbeat

**Comment by muramura** [comment]
@khancyr san.
I am not able to set the component ID in the MISSION PLANNER, QGROUNDCONTROL settings.
SYSTEM ID is used for the following connections.
I think it is better to assign a unique ID to major GCS.
https://ardupilot.org/dev/docs/mavlink-routing-in-ardupilot.html

MISSION PLANNER
![Screenshot from 2020-12-30 08-30-43](https://user-images.githubusercontent.com/646194/103320870-6cfe4200-4a7a-11eb-9cb9-58f4c1c04888.png)


QGROUNDCONTROL
![Screenshot from 2020-12-30 08-31-27](https://user-images.githubusercontent.com/646194/103320886-81423f00-4a7a-11eb-80f4-adfb9538fba0.png)

**Comment by IamPete1** [comment]
I'm not really sure what the action we should take on this, so I'm going to close, @muramura please re open if there is some code change in AP that would revolve.
