### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by 1AwesomeDeveloper** [ArduPilot/ardupilot#16178]
## Feature request

**Is your feature request related to a problem? Please describe.**
I am new to ardupilot, so I was going through the documentation and on his page https://ardupilot.org/dev/docs/apmcopter-programming-libraries.html# , I found that the documentation didn't mention all the libraries that are in the code
**Describe the solution you'd like**
PLEASE UPDATE THE DOCUMENTATION, IF POSSIBLE PLEASE ADD  A BRIEF OF ALL THE REMAINING LIBRARIES

**Comment by magicrub** [comment]
For being an awesome developer, you should have made a pull request instead of an issue! :)

Take a look at this video
https://www.youtube.com/watch?v=fb73F8_MiMg

**Comment by 1AwesomeDeveloper** [comment]
HaHa, thank you, sir, will try to do it now but for that, I guess I need to know about all these libraries and that is why I was asking for documentation, 
Nevertheless, I will try to study code and see if I can submit a PR for the same 

Thank you

**Comment by IamPete1** [comment]
Closing, should be a issue over on the wiki repo, https://github.com/ArduPilot/ardupilot_wiki
