### ISSUE TITLE
PreArm: Internal errors (0x3000)

### ISSUE THREAD

**Issue by muntasir399** [ArduPilot/ardupilot#16231]
![Screenshot (68)](https://user-images.githubusercontent.com/77024864/103695480-d88a6700-4fc6-11eb-927f-87255ecc246b.png)

**Comment by muntasir399** [comment]
> Which hardware?

pixhawk 2.4.8

**Comment by rmackay9** [comment]
we actually have this issue now to collect up all the internal error reports: https://github.com/ArduPilot/ardupilot/issues/15916

**Comment by hendjoshsr71** [comment]
Should this one be closed? There is no log or info. And nothing got put into the Internal reporting page.

@muntasir399  Have you had this issue on recent versions of the software? Say Copter 4.1 betas or release candidates for example?

**Comment by IamPete1** [comment]
@muntasir399 if this is still a issue on 4.1, please re-open with some more information, ideally a log and param dump.

**Comment by ZhongmouLi** [comment]
Hi guys, I believe this happens also on Copter 4.4.0 and my hardware is KakuteH7.

**Comment by amilcarlucas** [comment]
@ZhongmouLi have you looked at #15916 ? you should.
