### ISSUE TITLE
Plane: reach the target altitude of the next waypoint immediately during AUTO and GUIDED, respecting the limits of the TECS

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#16248]
With Ardupilot while performing a waypoint flight, the plane flies along a virtual straight line between the previous and the next waypoint.
In the aeronautical world a new flight level is usually executed immediately.
It would therefore be interesting in Ardupilot there was an option to do the same thing.
Example:

- altitude of the waypoint just reached: 10 meters
- altitude of the waypoint to reach: 110 meters
- distance between the two waypoints: 1000 meters
- cruise nav speed: 20 m/s
- maximum height change (climb rate in this case) set in the TECS: 10 meters per second

Currently the plane would be 500 meters away (halfway) between the two waypoints after 25 seconds at a height of 60 meters.
Instead what it should do with the new feature is to reach an altitude of 110 meters only after 10 seconds, at a distance of 200 meters from the first waypoint.
Same thing will do if the next waypoint is at a lower height.
This is aeronautically more logical, the manned planes behave this way during a flight for example in IFR.
And of course this should be an option that can be activated with a parameter, perhaps that you can choose whether this behavior occurs only during a climb, a descent or both.
This solution could also optimize consumption and it might also be interesting for the Copter.
I'm aware that I can already do it now by adding intermediate waypoints, but it seems absurd to have to waste events for this, and it would get boring on a complex mission.
I ping @tridge and @magicrub because they sure could be involved in this.
I am attaching a simple sketch to better explain what I mean:

![wp](https://user-images.githubusercontent.com/3864712/103776128-4c605a00-502f-11eb-963c-2b297b7cc932.jpg)

**Comment by dcamatti** [comment]
@robustini , I fully agree with your request. I I want an altitude change, especially just after takeoff, I want to get rid of obstacles as soon as possibile using the max climb performance of the UAV. Like it is today I can use the max climb performance only by manually placing an additional wpt close enought to cause the UAV climb at max climb rate. Looking forward to have this implemented. Thanks - Daniele Camatti

**Comment by peterbarker** [comment]
On Wed, 6 Jan 2021, Marco Robustini wrote:

> Instead what it should do with the new feature is to reach an altitude of 110 meters only after 10 seconds, at a distance of 200 meters from the first
> waypoint.

I do like the idea.

I have concerns about changing the way the vehicle executes missions based 
on parameters.

Better to represent this in the mission IMO, in a standardised fashion. 
That should allow you to move the mission to another flight stack and get 
the same results.

There is precedence in do-change-speed.

Command could also set a percentage of your maximum climb (or sink) 
rate to be used to reach the new altitude.

Would also need a way to cancel the behaviour.

**Comment by robustini** [comment]
Hi @peterbarker! I really wanted to avoid this thing being implemented using further events, in complex missions you should use many, but as a last resort it can be fine.
In my opinion it would be more useful if this mode was selectable with a parameter, perhaps using an existing one that includes a bitmask.
Arduilot would also be less busy doing calculations, currently doing many more to maintain the line of flight between two waypoints at different heights.
My two cents...

**Comment by AndKe** [comment]
I wish for a smooth altitude change between two points, arduplane is now just climbing to target altitude of the next WP before arriving there.
Is GLIDE_SLOPE_MIN still the way to make it distribute the altitude change across the distance between the two waypoints?

**Comment by magicrub** [comment]
@AndKe did something change that I'm not aware of?

**Comment by AndKe** [comment]
Hi @magicrub  not really, I am not aware of any sudden change.
We are flying fast and low over an airstrip as a part of a research project.
Between certain waypoints, like WP10 to 11,  the plane is supposed to closely follow the gradient of the airstrip. 
We observe that it quickly climbs to the elevation of WP12, right after passing WP10.  - instead of climbing gradually to it's altitude.
See center of this graph:

![Screenshot from 2021-07-01 15-12-35](https://user-images.githubusercontent.com/1468842/124131257-e9043180-da7f-11eb-898c-cb7cab6107e4.png)

Log: https://drive.google.com/file/d/1Yo4zXbEi2yZXjywz2OkLQIav8RNsq_Ux/view?usp=sharing

**Comment by WickedShell** [comment]
We normally build a slope and want to arrive at the target altitude when we
reach the waypoint. GLIDE_SLOPE_MIN is used to say when we are this many
meters over the target slope to the next point, and we are trying to climb,
recompute the slope. It's mostly there for long climbs, or right after
takeoff when we'd rather not push the nose back down to perfectly
reintercept the slope and waste energy.

**Comment by AndKe** [comment]
@WickedShell   Thank you.
Please have in mind that this is not takeoff, just a low pass (coming from a higher alititude, flying low while following terrail altitudes, then climbing)
So the GLIDE_SLOPE_MIN requires 15m  to compute a glide slope, while the waypoints in question are at 10 and 14 meters (4 meters apart) 
What would be the downside of setting GLIDE_SLOPE_MIN to 3m ?
And why are we limiting the glide slope to changes greater than x meters ?

**Comment by IamPete1** [comment]
Same idea as https://github.com/ArduPilot/ardupilot/issues/18157

**Comment by lopsided98** [comment]
I believe the behavior @AndKe described is caused by this code: https://github.com/ArduPilot/ardupilot/blob/08f652fe2ca0bc9cb054b3557d8f58367712153b/ArduPlane/altitude.cpp#L63-L72

**Comment by AndKe** [comment]
@lopsided98 good catch!  I would like to see it removed, or disabled by default. This behavior is not described anywhere and makes it harder to understand the system unless told about. 
Good system-knowledge is essential for safety.

**Comment by shancock884** [comment]
Hi!
I've just come across this thread, as we had a similar question as @AndKe...
Ideally we would like to be able to use a glideslope when both ascending and descending, but from reading this, and looking at the code a bit, my understanding is that at present:
For descending:
- To always descend quickly, then fly flat, you can set GLIDE_SLOPE_MIN to 0 (or a big number).
- To descend on a glideslope as much as possible, you can set GLIDE_SLOPE_MIN to 1 (it looks to be an int16 param, so it would not be possible to set it less than 1m).
For ascending:
- Ascent will always ascent as quickly as possible, and then fly flat, and flying a climbing glideslope between waypoints is not supported.

Is my understanding correct? 
It would be nice if there could be a way to fulfil the wishes of both camps!

**Comment by lopsided98** [comment]
I believe you are correct except for this point:

> * Ascent will always ascent as quickly as possible, and then fly flat, and flying a climbing glideslope between waypoints is not supported.

The glide slope logic works the same for ascent as it does for descent, unless the aircraft altitude is below 20 meters, in which case it will climb as quickly as possible.

**Comment by shancock884** [comment]
Ah yes I see! Thanks a lot @lopsided98 - spot on! .... not sure why I got in a muddle reading that logic last night!!

**Comment by eppravitra** [comment]
I just made a PR #27477 which should do what has been suggested here.

**Comment by robustini** [comment]
> I just made a PR #27477 which should do what has been suggested here.

Thanks for the implementation!
