### ISSUE TITLE
Issue With MavLinkFTP for QGC

### ISSUE THREAD

**Issue by kshitizgoyal5** [ArduPilot/ardupilot#16268]
Hello, I am successfully doing FTP using PX4 and QGC. Now since my application is based on ardupilot stack, I need to use mavlink FTP with QGC but i am facing error as shown below.
![image](https://user-images.githubusercontent.com/43859091/104011121-a13cd580-51d3-11eb-8a72-20126d11dea9.png)
The image above shows that I get an error of noAvailableSessions (errno5).
Kindly refer to the following for exact understanding https://github.com/mavlink/qgroundcontrol/issues/9306

**Comment by liang-tang** [comment]
you can test it using missionplanner first.

**Comment by IamPete1** [comment]
QGC does not support ArduPilots FTP scheme. I think the general consensus is that AP is not going to support two FTP protocols. Instead we should work with QGC maintainers so they can add support for the AP protocol. You could open a issue over on the QGC GitHub, if there is not one already.
