### ISSUE TITLE
APM: PreArm: GPS is not healthy: airsim and ardupiot SITL

### ISSUE THREAD

**Issue by djdylex** [ArduPilot/ardupilot#16278]
## Bug report

**Issue details**

When i enter "python sim_vehicle.py -v ArduCopter -f airsim-copter --console --map" in the cygwin console in /tools/autotest, i am told "APM: PreArm: Need Position Estimate", 
"Got COMMAND_ACK: COMPONENT_ARM_DISARM: FAILED", and then
 "APM: PreArm: GPS is not healthy". 

The wierd thing is i could have sworn I had this working earlier, then all of a sudden it has broken.

**Version**
Master, latest commit.

**Platform**
[  ] Copter

**Airframe type**
Quad

**Hardware type**
SITL
Windows 10
Cygwin

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by fabioandraderj** [comment]
Any idea about how to go around this?

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/15329
