### ISSUE TITLE
add detection of airspeed blockage and switch to non-airspeed control

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#1628]
cope with water droplet blocking pitot

**Comment by priseborough** [comment]
This requires:

a) EKF to check for bad airspeed and provide its own estimate of airspeed. See https://github.com/priseborough/ardupilot/tree/airSpdFail-wip

b) Provide TECS with the EKF's airspeed health and estimate data. I have had some trouble with this and would like some advice.

c) Implement logic in TECS that checks for a inconsistent pitch angle, airspeed and throttle in addition to EKF fault status to declare the airpseed as faulty. If this happens, then TECS can either switch to an estimated airspeed from EKF or use the non-airspeed mode.

**Comment by magicrub** [comment]
I wrote up a little hack for this the other day but would much rather utilize flags from within EKK/AHRS than the way I implemented it.
https://github.com/Airphrame/ardupilot/commit/31b75e1ea579e0005dfc06132b23b24069ba3374#commitcomment-11895099

**Comment by magicrub** [comment]
The Syria Uplift project had a major crash causing a small brush-fire which may have been caused by flying without a pitot tube. They had previously crashed due to a pitot tube blockage and did not trust it any longer so they disabled it. It would have been much better if it auto-disables itself only if found to be supplying bad data.

This problem has happened to me too and I think if this is causing major crashes then we should put some effort into fixing it ASAP.

**Comment by Georacer** [comment]
Research on fault diagnosis on Pitot tubes was the subject of a PhD thesis
in Norway, a few years back. I'll try to track it down and post a link.

**Comment by magicrub** [comment]
That would be super, George. Thank you!

**Comment by Georacer** [comment]
Here you are:
http://orbit.dtu.dk/en/publications/fault-diagnosis-and-fault-handling-for-autonomous-aircraft%28176c69c3-4696-4e58-9d45-4cf2aa892987%29.html

The .pdf of the dissertation, which contains most of the papers, can be
found from that address.

**Comment by magicrub** [comment]
I'd really like to see this worked on soon. I'll do it if no one else is available/interested.

**Comment by kwikius** [comment]
FWIW,

I had a airspeed sensor blocked with mud after a failed takeoff. I noticed it when I decided to see how fast plane would go, so put in a vertical dive.( I figured it and stayed in manual then) The point is that the Airspeed went up, but stuck showing **High** when I levelled out, so It may not always read low if it's blocked

**Comment by Elios007** [comment]
I hope they will have a solution for that as we had the same issue with mud.

**Comment by magicrub** [comment]
This is next-ish on my to-do list.

**Comment by magicrub** [comment]
There is a partial solution to this via PR https://github.com/ArduPilot/ardupilot/pull/4122

**Comment by geofrancis** [comment]
now that pixhawk 2 has more than 1 i2c bus what about supporting dual air speed sensors?

**Comment by magicrub** [comment]
Even better, there are CAN airspeed sensors just around the corner...

**Comment by geofrancis** [comment]
can stuff has been around the corner for years, but its still rare and expensive.

**Comment by magicrub** [comment]
@proficnc care to chime in on an ETA on hardware delivery? Software has a separate ETA.

**Comment by geofrancis** [comment]
i2c sensors are already out there and the pixhawk2 has 2 i2c buses so would it not be easier to implement dual i2c sensors for now until CAN sensors become available?

**Comment by iskess** [comment]
I still have analog airspeed sensors on my aircraft. I'd like to add the new MS5525 I2C sensor as well. If going for redundancy, it seems a good idea to have one of the two airspeed sensors not on the I2C bus, a digital and an analog. I have found the analog sensors to be more reliable, but less accurate. 
I'm hoping that future code allows for dual airspeed sensors of various types.

**Comment by geofrancis** [comment]
yea i find it quite bizzare that something as crucial and prone to issues as the airspeed sensor doesnt have any redundancy other than to fly without it.

**Comment by EShamaev** [comment]
My guess that even one can be used and checked against EKF's calculated airspeed.
This requires some changes to EKF however.

**Comment by WickedShell** [comment]
@EShamaev something I've really wanted to see, but haven't gotten to do yet (or seen anyone else do), was see someone hack the EKF to do a ride along estimate next to the real sensor, so that we could compare them for accuracy.

**Comment by priseborough** [comment]
The true airspeed innovations are logged in  NKF3.IVT

There are the predicted - measured true airspeed.

**Comment by EShamaev** [comment]
Just to have one more link:
https://github.com/ArduPilot/ardupilot/pull/7738

**Comment by EShamaev** [comment]
Seems to be done.
