### ISSUE TITLE
KakuteF7Mini master copter failing to initialize

### ISSUE THREAD

**Issue by tenten8401** [ArduPilot/ardupilot#16326]
When powering on a freshly flashed KakuteF7Mini flight controller (1/14/20 nightly) I'm greeted with either:
> INS: Unable to initialize driver
> Config error: Fix problem and reboot

or

![image](https://user-images.githubusercontent.com/6174343/104664247-bebee300-569c-11eb-9e83-f812c898062f.png)
and it disconnects, always directly after baro calibration.

I don't think it's a flash space issue as I tried building fresh master (today 1/14/20) with a heap of features disabled (autotune, logging, optical flow) and it does the same thing.
[APM_Config.h](https://gist.github.com/tenten8401/b948cc265428f71a34205761c7431aa9)

There is nothing in logging dataflash and the initial flash was done with "full chip erase" in iNav configurator (yeah I know, it's not qgc or mp) via DFU. Custom build flash was done via `./waf copter --upload` and same thing.

I believe the change happened around 1/4/20 as I was helping test a new build and it was doing the same thing, while builds from a few days prior were working fine. Doesn't appear to be related to ce361e51bfc9975a9d4fef8a67570cb0c71ecf10 though.. (removed added lines and re-built to test, not sure if there's anything else I should try). Builds are only 809932 bytes out of 950272. I also tried changing FORMAT_VERSION = 0 to ensure internal flash got wiped.

**Comment by andyp1per** [comment]
I have three of these boards and as far as I know they are all fine. I'll double check tonite, but its worth seeing whether any of my changes are responsible

**Comment by andyp1per** [comment]
Maybe try gitblame on the hwdef to see if there is any correllation

**Comment by tenten8401** [comment]
I'll see what I can find.. I already looked thru github commit log for the hwdef folder but I'm not finding anything that sticks out.

**Comment by andyp1per** [comment]
This works fine for me. I suspect hardware failure. As a double check can you post your parameters for me to load as well?

**Comment by lavachemist** [comment]
The newest version (v3) of the Kakute F7 Mini has an F722. Only the previous versions are supported, because they had the F745. Maybe that is your issue?

**Comment by tenten8401** [comment]
@lavachemist This was fixed, turned out to be a DMA issue. All good now :)
