### ISSUE TITLE
uavcan library issue

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#16343]
When I was testing the rsc airspeed meter recently, I found that the temperature data is not continuous, usually at an interval of 2 degrees. 
![image](https://user-images.githubusercontent.com/16251761/104832950-46d8fe80-58d0-11eb-987c-46f7b71e1d8b.png)

So I did a series of tests and found that if the value sent is larger, the data interval will be larger, such as 0-20, the minimum interval is 0.1, 20-50, the interval is 0.2, 50-100, the interval is 0.5, 250 or more interval 2(4, 6, 8.....)

tested on commit 26a3a02c818352462d2516abc9f7a54e75bcb84e
tested via below:
![image](https://user-images.githubusercontent.com/16251761/104832409-d0d29880-58cb-11eb-8e70-a5716d306a7d.png)

some data here
![image](https://user-images.githubusercontent.com/16251761/104832527-a2a18880-58cc-11eb-8409-35568a0feeee.png)
![image](https://user-images.githubusercontent.com/16251761/104832548-c8c72880-58cc-11eb-8c25-b8dae968089e.png)
![image](https://user-images.githubusercontent.com/16251761/104832563-ded4e900-58cc-11eb-9310-1197117f286a.png)
![image](https://user-images.githubusercontent.com/16251761/104832634-71758800-58cd-11eb-93d2-b430e32e984c.png)

when i comment fix_float16,
    // fix_float16(pkt.differential_pressure);
    // fix_float16(pkt.static_air_temperature);
![image](https://user-images.githubusercontent.com/16251761/104832899-c1ede500-58cf-11eb-997c-a48467cef432.png)

![image](https://user-images.githubusercontent.com/16251761/104832824-09c03c80-58cf-11eb-913c-1a7ef5551e77.png)
![image](https://user-images.githubusercontent.com/16251761/104832829-147ad180-58cf-11eb-8c98-84f11e0c8155.png)

It seems that decimal data will be more accurate, and the data interval will be basically eliminated.
After testing and analysis, the possible result is that when sending float data, some data is abnormal.

Then I checked the version of uavcan in Ardupilot and found that they are all stuck in 2019. But the latest uavcan library is in 2020 and later, and I found that    [](url) https://github.com/UAVCAN/libcanard/blob/master/libcanard/canard_dsdl.c  has many floating-point number processing methods, is it necessary to update uavcan The version of the library?

Before the problem is completely solved, I will temporarily comment "fix_ Float16 "to solve this problem!

**Comment by Sypaq-MadMan** [comment]
Just commenting so I get updates regarding uavcan library.

**Comment by Sypaq-MadMan** [comment]
Just read this, I think uavcan v0 is here to stay for a bit. 
https://forum.uavcan.org/t/uavcan-v1-0-and-ardupilot/671/27

**Comment by magicrub** [comment]
if uavcan v0 was compatible to what all other hardware on the planet was using, it would have been an easy transition.

**Comment by IamPete1** [comment]
It sounds like this is a temperature issue limitation of the protocol, not something that can be fixed in isolation, I'm going to close this.
