### ISSUE TITLE
Arducopter default HILS firmware makes altitude go haywire

### ISSUE THREAD

**Issue by swaroophangal** [ArduPilot/ardupilot#164]
#1 If the default firmware using mission planner is uploaded on APM2.5+, on connect, the altitude shown is pure crap(in -ve!! seen till -40000!!). The same happens when the HILS code was compiled with the HIL_MODE_ATTITUDE in APM_config.h and uploaded.
#2 The wiki on googlecode page mentions --fdm-external for the FGFS startup options which IMHO it should not be used since the whole point of using FGFS is to get the attitude data from FGFS which it wont give when its FDM wont be running.

**Comment by OXINARF** [comment]
HIL is mostly broken and not considered fundamental anymore since SITL is a much better simulation environment. In any case #508 is open as an enhancement for someone that wishes to fix it.

**Comment by magicrub** [comment]
The SITL Staten we're using runs in lockstep so it is very good. I encourage you to take a look.
