### ISSUE TITLE
sitl heli cann't takeoff

### ISSUE THREAD

**Issue by addriumruss** [ArduPilot/ardupilot#16418]
![2021-01-22_164815](https://user-images.githubusercontent.com/35988105/105469030-a2412d00-5cd2-11eb-8371-2fccf6582502.jpg)

it's started by cmd "sim_vehicle.py -w -l 32.1291816,118.8849733,100,0 --model heli --frame heli --console --map"
any solutions?

**Comment by khancyr** [comment]
Hello,

Yes, you should disable the interlock as stated in the heli documentation !

**Comment by addriumruss** [comment]
@khancyr 
Truely thanks for the response!  
May I ask what url it is with the "heli documentation"? I found the copter and plane document, but cannot find the heli one.
