### ISSUE TITLE
Impact mini OSD font

### ISSUE THREAD

**Issue by Jetrell** [ArduPilot/ardupilot#16416]
This is a font found in iNav and Betaflight. 
Its a smaller font that doesn't take up as much screen area, while still being good to view at a glance.

This is a screen shot from iNav. To give an idea of what it looks like on a monitor or through goggles.

![impact mini](https://user-images.githubusercontent.com/47995726/105432503-d8b78180-5cab-11eb-8cf6-4ff9447ed523.JPG)

Here are the .PNG and .MCM files it suit Ardupilot, if anyone is interested and whats to merge it.
[Ardupilot Impact Mini.zip](https://github.com/ArduPilot/ardupilot/files/5853039/Ardupilot.Impact.Mini.zip)

**Comment by IamPete1** [comment]
You can put the font on the SD Card and load with the `OSD_FONT`. Convert to a .bin following these instructions: https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_OSD/fonts#adding-font-styles Call it `font4.bin` in the APM folder.

We don't have enough flash left to include any more in the build directly.
