### ISSUE TITLE
Integrate GSM modem support libraries from Andreas M. Antonopoulos for telemetry over IP

### ISSUE THREAD

**Issue by stevester91** [ArduPilot/ardupilot#1641]
His code is now over two years old forcing users wishing to use ip telemetry to use ardopilot 2.6. Would be nice to have his libraries integrated into the current code. Links: 

http://diydrones.com/group/telemetry-over-cellular-ip/page/testing-the-dronecell-or-other-gsm-modem?page=1

https://code.google.com/r/andreas-apm2-wip/source/browse/?name=modem_test

**Comment by hiro2233** [comment]
@stevester91 there is a new place to discuss it, i'm sure that you will get help posting it in our new discuss forum http://discuss.ardupilot.org

Thanks you for your participation.
Good luck!

@OXINARF please close this.
Thanks.

**Comment by Naterater** [comment]
Any updates to this? I have heard of a few users using GSM modems for telemetry recently.

**Comment by IamPete1** [comment]
Sorry we never got to this
