### ISSUE TITLE
site not linked to github account available on web page

### ISSUE THREAD

**Issue by keshavMarodia** [ArduPilot/ardupilot#16425]
it shows an error 404 when i click on the github icon on the website of the organization.

**Comment by amilcarlucas** [comment]
Which URL has the "website of the organization" ?

**Comment by khancyr** [comment]
Www.ardupilot.org

**Comment by keshavMarodia** [comment]
The Github link added in the footer component is not working properly at https://ardupilot.org/
For ref:

![Github footer](https://ibb.co/FWB8cpb)

**Comment by arshPratap** [comment]
We should replace the link in the footer from [https://ardupilot.org/github.com/ArduPilot](https://ardupilot.org/github.com/ArduPilot) to [https://github.com/ArduPilot](https://github.com/ArduPilot). Thanks

**Comment by peterbarker** [comment]
There is no longer a github link on ardupilot.org

Thanks for the report, 'though.
