### ISSUE TITLE
Pixhawk: "enhanced channel pass through"

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#1644]
Unfortunately the pass-through has limits, you can not "forward" a tx channel to the desired pwm output of Pixhawk.
For example I use sbus receiver (16 ch), the first 8 channels for basic APM functionality, and channels 9-16 for accessories (landing gear, video switch, three axis gimbal, etc).
The current pass-through forward the channel 9 to the Aux Port 1, 10 to Aux Port 2, etc., but the pwm output is only 50 Hz.
With quad frame i've the pwm motor output from 5 to 8 free and I would like to use these.
Currently i can do it from 5 to 7 enabling the gimbal, declaring manually the tx input with the "MNT_RC_IN" parameter, but it is quite uncomfortable and output n.8 i could still use.
My request is simple, have an advanced "forward pass-through" simply by declaring a parameter, for example with a quad frame:

RC9_FUNCTION, 101  (ch9 tx input pass-through to the first free pwm output, the number "5")
RC10_FUNCTION, 104  (ch10 tx input pass-through to the pwm output number "8")
RC11_FUNCTION, 105  (ch11 input pass-through to the Aux Port 1)
RC12_FUNCTION, 107 (ch12 input pass-through to the Aux Port 3)
Etc. etc.

Same example but related to hexa frame (the first six output are for the motors):

RC9_FUNCTION, 101  (ch9 tx input pass-through to the first free pwm output, the number "7")
RC10_FUNCTION, 104  (ch10  input pass-through to the Aux Port 3)
RC11_FUNCTION, 105  (ch11  input pass-through to the Aux Port 4)
RC12_FUNCTION, 107 (ch12  input pass-through to the Aux Port 6)

**Comment by bortek** [comment]
Hi
I have a R6308SBT receiver connected and working fine with Pixhawk via SBUS. I want to passthrough channel 7 or 8 and connect it to my gimbal input pins to control the pitch of my camera.
Still struggling to make this work on my Pixhaw, but no success yet. I cannot understand which of the RCx_FUNCTION are mapped to which AUX output on the Pixhawk? Please help!

**Comment by peterbarker** [comment]
I think this is either voided or completed by our rc/servo split (and the various servo functions).  Closing.
