### ISSUE TITLE
arduppm: s.bus support

### ISSUE THREAD

**Issue by KIrill-ka** [ArduPilot/ardupilot#1645]
Some time ago I released binary version of s.bus atmega32u2 encoder firmware in a forum post.
There were no complaints, so I think it works well. Personally I use it with frsky receivers.
The firmware is separate from pwm/ppmsum. Although it's possible to make single "jumper select" pwm/ppmsum/sbus firmware, I'm not sure it's worth the effort. 
Source code: f4b21fd296a123e2e764d1311c1535c7e8266d41
Please, consider providing s.bus support officially for APM2 boards in some form.

**Comment by peterbarker** [comment]
We have S.BUS support - thanks!
