### ISSUE TITLE
May I build a firmware mirror server in China

### ISSUE THREAD

**Issue by bys1123** [ArduPilot/ardupilot#1649]
It's very slow to download firmware and always timeout in china. So, I want to build a mirror server that chinese user can download firmare in MP form our mirror server.
1. I've find the firmware web page and upload to our server.
http://firmware.diywrj.com/
we will translate this page later.
2. Is the firmware server use Rsync? May I have a username that have permission to read the firmware folder, then I could sync the files to the mirror server.

I was posted my self intro and plan on Google drones-discuss.
https://groups.google.com/forum/#!topic/drones-discuss/EwZyt4S9bwI

**Comment by HunterApm** [comment]
😳What a coincidence

**Comment by bys1123** [comment]
Hi, nice to see you here, but I think it's not good to chat on github.
