### ISSUE TITLE
Plane: RTL causes the craft to ascend and then immediately descend to RTL alt

### ISSUE THREAD

**Issue by skorokithakis** [ArduPilot/ardupilot#16532]
## Bug report

**Issue details**

I ran into an issue where hitting the RTH switch caused the aircraft to rise 30m (as instructed by the `RTL_CLIMB_MIN` parameter), and then immediately descend to around 110m (with an RTL altitude set to 100m).

The odd thing is that plotting the log, I always see TAlt at the same value:

![image](https://user-images.githubusercontent.com/23648/107098348-ad8a7180-6817-11eb-9d16-e48ea6565091.png)

**Version**

V4.1.0DEV 7a72e6cf (base of a5a13f37c9 with Galileo autoconfig fix).

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[x] Plane
[ ] Rover
[ ] Submarine

**Airframe type**

Flying wing (FT Arrow).

**Hardware type**

An Omnibus F4 clone.

**Logs**

[log_10_2021-2-5-18-03-30.bin.zip](https://github.com/ArduPilot/ardupilot/files/5935764/log_10_2021-2-5-18-03-30.bin.zip)

**Comment by rmackay9** [comment]
This should probably go in the Plane forums for investigation first before being raised as an issue.  Sorry to be strict but otherwise our to-do list turns into another support forum. https://discuss.ardupilot.org/c/arduplane/plane-4-0/153

**Comment by skorokithakis** [comment]
Sure, that sounds fair, thanks.

**Comment by skorokithakis** [comment]
@rmackay9 I think I know what causes this (based on more testing): `RTL_CLIMB_MIN` isn't counted as "extra altitude".

Say my RTL altitude is 70 meters, `RTL_CLIMB_MIN` is 30, and my current altitude is 120 meters. If I activate RTL the wing climbs to 150 meters (because of `RTL_CLIMB_MIN`), then *immediately descends* to 120 meters again, and starts the linear descent from 150 meters to 70 meters over the home location.

This seems like a bug to me, the craft should not waste all that energy by diving to the altitude it had before the `RTL_CLIMB_MIN` climb.

**Comment by skorokithakis** [comment]
@rmackay9 @andyp1per can this be reopened? It seems like an actual bug.

**Comment by peterbarker** [comment]
I've reproduced this with an autotest in #16565 .

The code is quite clear here, and the behaviour is entirely explained by it.  The question is - why would we descend straight after the climb is complete?  If the goal is to clear surrounding obstacles, perhaps we *should* maintain the higher altitude for the duration of the RTL.

**Comment by skorokithakis** [comment]
Personally, I use this feature exactly for clearing obstacles. Mainly because, if there's going to be an obstacle when I initiate an RTL (manually or from a failsafe), the least likely place for an obstacle to be is in front of me.

So, I use the climb as a way to try to clear obstacles before starting to turn (which, in the worst case, would start to turn right into the obstacle that caused the failsafe).

This is itself a workaround for a feature Ardupilot lacks that other projects have, an option to climb *first* and then turn.  This is helpful because the first thing you want is to get to a safe altitude, and only then start performing maneuvers.

**Comment by peterbarker** [comment]
On Mon, 8 Feb 2021, Stavros Korokithakis wrote:

> This is itself a workaround for a feature Ardupilot lacks that other projects have, an option to climb first and then turn. This is helpful because the
> first thing you want is to get to a safe altitude, and only then start performing maneuvers.

Have you met the LEVEL_ROLL_LIMIT parameter?

Note that that will affect things other than RTL, however (auto takeoff 
and landing)

**Comment by skorokithakis** [comment]
Hmm, how does that help? You mean by making the turns very wide, giving the aircraft more time to climb before turning? That might help, though I find RTL_CLIMB_MIN a more effective workaround (if a bit wasteful because it climbs even if I'm above the desired altitude).

**Comment by skorokithakis** [comment]
This can be closed, I have tested it and can confirm it works.

As an aside, would it be possible/easy to implement a "climb before turn" setting? I used this setting to work around that, but it is a poor substitute in many cases.

**Comment by peterbarker** [comment]
Thanks @skorokithakis - the question you pose there is being attacked elsewhere.

**Comment by skorokithakis** [comment]
Yes, I implemented it in #16823, it works great.
