### ISSUE TITLE
AP_Button: BTN_FUNCx param descriptions should match RCx_OPTIONS

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#16533]
We can improve the ease-of-use of the Buttons feature ([see wiki here](https://ardupilot.org/copter/docs/common-buttons.html)) by allowing the user to directly select the function they want attached to the button instead of having to manually look up the number on the wiki page.  This should be possible by simply copying the RCx_FUNCTION parameter descriptions @Values field to the BTN_FUNC1/2/3/4 parameter description.

**Comment by 4kashyadav** [comment]
Hi there i want to work on this issue please assign me this!

**Comment by rmackay9** [comment]
ok!  good luck!

**Comment by YashMaxy** [comment]
@rmackay9  May I work on this issue?

**Comment by rmackay9** [comment]
@YashMaxy,

Sure, I haven't seen a Pr from @4kashyadav yet.  Whoever raises the PR first wins!

**Comment by YashMaxy** [comment]
Thank you @rmacky9 sir.
I am new to this codebase. Can you please help me to where to start?
