### ISSUE TITLE
Remove BRD_PWM_COUNT

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#16548]
We should remove the BRD_PWM_COUNT parameter and instead allow any ordering. If a SERVOn_FUNCTION is not set or if a GPIO is specifically set with a *_PIN parameter then it should be available as a GPIO and disabled as PWM.
This would make it more flexible, and prevent user problems with getting BRD_PWM_COUNT right

**Comment by rmackay9** [comment]
Sounds good.  if we do this we might consider extending the RCOUT banner to mention which pins are GPIO although then technically they are not RCOUTs anymore.

**Comment by magicrub** [comment]
Do the PWM groupings have any impact on GPIO usage?

**Comment by rain-er** [comment]
This would be quite helpful for a rover with "brushed with relay" motor and Neopixel on Matek H743.

Currently I need to reduce BRD_PWM_COUNT to 12 to free S13 for the GPIO62 for the brushed motor direction relay. But with this I also loose the possibility to connect Neopixel to the S13. And need to waste another complete timer group for Neopixel.

If I could set S1 for brushed-PWM and S2 for the direction relay-GPIO the timer group S1+S2 would be efficently used. And S13 as the only member of its timer group could still be used for Neopixel.
