### ISSUE TITLE
CTUN.ASPD dropped to 0 m/s and caused throttling to 100% that leaded to oscillation and crash.

### ISSUE THREAD

**Issue by zhaodelong** [ArduPilot/ardupilot#16589]
## Bug report
This has been reported to the Plane forums for investigation. Link: [https://discuss.ardupilot.org/t/failsafe-caused-ctun-aspd-dropping-and-throttle-increasing-to-100-and-crashed/67355](url) After investigation, several users thought the synthetically calculated airspeed erroneously goes down to 0 m/s is the cause. Not sure if this a regression in 4.0.8. So try to raise as an issue here to further investigation. 

**Issue details**
The synthetic airspeed is up to first 10 minutes completely correct. After that, it erroneously goes down to 0 m/s. Assuming a low speed, the amplitudes of the rudder servos are increased, which then leads to flutter at the actual high speed (20 m/s). This leads to 100% throttle and fluttering that leaded to crash. 

_Please describe the problem_
My Ar Wing Pro maiden crashed due to strange synthetically calculated airspeed dropping to 0. The wing uses Arduplane 4.0.8 on Matek h743 wing. The takeoff and autotune works perfectly. After that, I started an auto mission. During the mission, it triggered failsafe, but continue the auto mission which is expected with FS settings. But the synthetic airspeed started dropping (no airspeed sensor and GPS ground speed is correct) and FC increased throttling to 100%. The wing started oscillation and crashed due to loss of control. Need to investigate why the synthetically calculated airspeed was suddenly so wrongly low.

**Version**
_What version was the issue encountered with_
4.0.8 Arduplane

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Flying wing: Ar Wing Pro

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Matek h743 wing

**Logs**
_Please provide a link to any relevant logs that show the issue_
Here is the video. The first 10 minutes is perfect. The issue started at 10:30.
[https://www.youtube.com/watch?v=sDYNlZNP-g0&t=630s ](url)

Here are the bin and log files. [https://drive.google.com/file/d/1eySArkrL_u3JlKsY6F5DQ3M0tsnFMukr/view?usp=sharing](url)

![30dfa0162fb19d4d57cd0e43e588b62598f65792 (1)](https://user-images.githubusercontent.com/2042767/107575865-3cdfae00-6ba5-11eb-81a8-f287c061f460.jpeg)
![cc3006f906fbb51742d9932b3e00a79db3b1239a (1)](https://user-images.githubusercontent.com/2042767/107575868-3d784480-6ba5-11eb-9205-6bd98653c847.jpeg)
![294c8e1fb8a814d98afdf603cb39a03021685115](https://user-images.githubusercontent.com/2042767/107575869-3d784480-6ba5-11eb-9f1a-f0808c616e83.png)

**Comment by IamPete1** [comment]
The EKF was very upset due to Mag issues, Mission planner had a red EKF symbol and was showing ERROR COMPASS VARIANCE and BAD COMPASS HEALTH for the majority of the flight.

![image](https://user-images.githubusercontent.com/33176108/107585983-0894dd80-6bf7-11eb-90be-83c1db16bb21.png)

The EKF being confused caused the wind estimate to go bad and hence the airspeed estimate went to 0. At low airspeeds the control surface movement is amplified but because you were not at a low airspeed this pushed you into a pitch osculation.

**Comment by zhaodelong** [comment]
Thanks for the root cause analysis, Peter. I close this issue now.
