### ISSUE TITLE
12-bit ADC scaling. Division should be with 4095, instead of 4096, as max value is 4095

### ISSUE THREAD

**Issue by rotorman** [ArduPilot/ardupilot#16600]
https://github.com/ArduPilot/ardupilot/blob/e5844b775365641c4b4e17935ba6f531fb3789a3/libraries/AP_IOMCU/iofirmware/analog.cpp#L87

**Comment by amilcarlucas** [comment]
Can you create a PR? It is easier to disscuss it

**Comment by rotorman** [comment]
OK, done. Please see #16607
