### ISSUE TITLE
Reference to g.rc3.control in - bypasses channel map?

### ISSUE THREAD

**Issue by pwbecker** [ArduPilot/ardupilot#1662]
Line 92 of radio.pde reads
  if (g.rc_3.control_in > 0) {

Does this not bypass the channel mapping, and will fail if the throttle channel is not set to 3?

Also see the line just below:
 if (g.rc_4.control_in > 4000) {

**Comment by gmorph** [comment]
Hi PWBecker.  This is indeed a bug.  I'm submitting a patch and will update here once done.  Thanks!!

**Comment by pwbecker** [comment]
Thanks for your great response! It inspires me to look for more bugs.... :)
