### ISSUE TITLE
compiling with driver L3G4200D > fatal error 

### ISSUE THREAD

**Issue by c128** [ArduPilot/ardupilot#16620]
good morning ,
i get a compile error with this driver
I don't understand if it's my error or there is some problem on the drv.
Thank you

compilation terminated due to -Wfatal-errors with driver L3G4200D

in hwdef.dat add driver:
IMU L3G4200D I2C:0:0x69 I2C:0:0x53

compiling error
[601/652] Compiling libraries/AP_ADSB/AP_ADSB.cpp
[602/652] Compiling libraries/AP_GyroFFT/AP_GyroFFT.cpp
../../libraries/AP_InertialSensor/AP_InertialSensor.cpp: In member function 'void AP_InertialSensor::detect_backends()':
./hwdef.h:168:37: error: 'AP_InertialSensor_L3G4200D' has not been declared
#define HAL_INS_PROBE1 ADD_BACKEND(AP_InertialSensor_L3G4200D::probe(*this,GET_I2C_DEVICE(0,0x69),GET_I2C_DEVICE(0,0x53)))
^
../../libraries/AP_InertialSensor/AP_InertialSensor.cpp:800:61: note: in definition of macro 'ADD_BACKEND'
if (((1U<<probe_count)&enable_mask) && _add_backend(x)) {
^
./hwdef.h:169:28: note: in expansion of macro 'HAL_INS_PROBE1'
#define HAL_INS_PROBE_LIST HAL_INS_PROBE1
^~~~~~~~~~~~~~
../../libraries/AP_InertialSensor/AP_InertialSensor.cpp:815:5: note: in expansion of macro 'HAL_INS_PROBE_LIST'
HAL_INS_PROBE_LIST;
^

with generated  hwdef.h we have

#define HAL_INS_PROBE1 ADD_BACKEND(AP_InertialSensor_L3G4200D::probe(*this,GET_I2C_DEVICE(0,0x69),GET_I2C_DEVICE(0,0x53)))
#define HAL_INS_PROBE_LIST HAL_INS_PROBE1

#define HAL_MAG_PROBE1 ADD_BACKEND(DRIVER_HMC5843, AP_Compass_HMC5843::probe(GET_I2C_DEVICE(0,0x1e),false,ROTATION_YAW_270))
#define HAL_MAG_PROBE_LIST HAL_MAG_PROBE1

#define HAL_BARO_PROBE1 ADD_BACKEND(AP_Baro_BMP085::probe(*this,GET_I2C_DEVICE(0,0x77)))
#define HAL_BARO_PROBE_LIST HAL_BARO_PROBE1

driver HMC5843 and AP_Baro_BMP085 is ok
driver AP_InertialSensor_L3G4200D > error
-----

last version ardupilot in github

**Platform**
[X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Rover

**Hardware type**
Custom  STM32H743xx

**Comment by IamPete1** [comment]
A GitHub issue is not really the best place for code help, [jump over on the discord](https://discord.gg/tVE2fS5S), or the development category of the discourse forum, a link to your branch would also be usefull.
