### ISSUE TITLE
Manual flaps with flaperons fails to give spoilerons

### ISSUE THREAD

**Issue by pwbecker** [ArduPilot/ardupilot#1664]
In attitude.pde is the line
  if (abs(manual_flap_percent) > auto_flap_percent) {
which indicates that a negative manual_flap_percent is possible.

However, manual_flap_percent is set a few lines before via
  manual_flap_percent = flapin->percent_input();

And in libraries/RC_Channel/RC_Channel.h  is the definition
  uint8_t                                         percent_input();

Which indicates that manual_flap_percent will never be negative.  This could be why spoilerons fail to deploy.

**Comment by IamPete1** [comment]
The code has moved on so far from this I'm sure that this is no longer a issue.
