### ISSUE TITLE
Notch and other enhancements

### ISSUE THREAD

**Issue by andyp1per** [ArduPilot/ardupilot#16645]
## Feature request

A list of small features that are on my radar for visibility to others

- [x] Add support for notches on 8 motors
- [x] Don't run notches on the non-primary IMU to reduce CPU load
- [x] Add support for dshot rate (e.g. 2Khz) to increase telemetry feedback rate
- [x] Increase notch center update rate from 200hz to loop rate
- [x] Generic ESC RPM support to drive the notch
- [x] Solve the VTX spam issue when using "my VTX" on OpenTX with CRSF

**Platform**

- [ ] All
- [ ] AntennaTracker
- [X] Copter
- [X] Plane
- [ ] Rover
- [ ] Submarine

**Comment by IamPete1** [comment]
@andyp1per Any updates?

**Comment by andyp1per** [comment]
All done
