### ISSUE TITLE
Disabling rc_channels_override is not treated correctly

### ISSUE THREAD

**Issue by rrr6399** [ArduPilot/ardupilot#1667]
I believe I found a bug related to releasing an rc_channels_override with 3.2 I ran a case today with the R/C turned off where I overrode all channels to remove a behavior I reported on the forums that led to a crash last week:  http://diydrones.com/forum/topics/arducopter-3-2-beta-testing?commentId=705844%3AComment%3A1849532 

I changed the yaw and thrust from their nominal values and then released the yaw control by setting the yaw channel to 0 and left the thrust overridden. When I did that, the copter went to a max yaw condition rather than releasing the control. This didn't happen in 3.1 so it appears to be a bug in 3.2. The libraries/AP_HAL_PX4/RCInput.cpp appears to release the channel when its 0, but someplace else in the code its choosing to go to a maximum (or -maximum) condition. 

Here is a plot that shows the yaw channel going to 0 after I had been changing it via MAVLINK to around 1500 and then thing takes off rotating around its yaw axis (z):
![image](https://cloud.githubusercontent.com/assets/2707426/5325125/37da7486-7ca9-11e4-9191-a4d4372c974f.png)

**Comment by WickedShell** [comment]
[RC_CHANNELS_OVERRIDE](http://mavlink.org/messages/common#RC_CHANNELS_OVERRIDE) are not intended to be disabled with 0, the documentation states that it is `UINT16_MAX` and it is working appropriately.

**Comment by rrr6399** [comment]
Actually, 0 means to release override and UINT16_MAX means ignore the input for that channel. It doesn't appear in 3.6RC5 that the UINT16_MAX value  is checked and I don't see a check for 0 values either.  
https://mavlink.io/en/messages/common.html#RC_CHANNELS_OVERRIDE
Something has changed in the latest releases regarding R/C overrides.  I used to be able to set each channel individually with the other channels being set to UINT16_MAX.

I've also seen RTL messages now.

@WickedShell , would you point to the code that handles the 0 and UINT16_MAX values?
I followed this path and could not find any logic related to the two special values:
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L1032

**Comment by WickedShell** [comment]
@rrr6399 You know, I seem to have missed something as I can't actually find the UINT16_MAX handling anywhere (new or old). The changes in the overrides were done by me in #8518. I can't find a case before/after that PR that actually checked UINT16_MAX.

The 0 handling is done here: https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channel.cpp#L328 and setting the override to 0 would indeed return control of the channel to the RC input.

I need to track down the UINT16_MAX stuff, and come back to the issues you are reporting. Sorry about that.

**Comment by rrr6399** [comment]
@WickedShell I noticed some older code here that relies on the signed short overflowing to a negative number by the max unsigned short:
https://github.com/ArduPilot/ardupilot/blob/Copter-3.4/ArduCopter/GCS_Mavlink.cpp#L1152
https://github.com/ArduPilot/ardupilot/blob/Copter-3.4/libraries/AP_HAL_PX4/RCInput.cpp#L75
https://github.com/ArduPilot/ardupilot/blob/Copter-3.4/libraries/AP_HAL_PX4/RCInput.cpp#L84

Maybe that's why the UINT16_MAX did not explicitly exist in the older code? Perhaps this implicit logic didn't get  carried forward?

**Comment by rrr6399** [comment]
@WickedShell I also just came across the new RC_OVERRIDE_TIME setting. It is set to 3 seconds by default. It appears that once this timeout occurs, that the current radio values are used instead of the overrides. This  is likely a problem for the case where the R/C is turned off. It may cause a catastrophic crash if the receiver sets the PWM values of the radio to 0 rather than trim values or last known values.

I can work around it by increasing the timeout and periodically sending override values, but there are edge conditions like during a GCS failsafe that can lead to a crash if the copter is landing and then after the timeout, the invalid R/C values are used leading to a max yaw, pitch and roll situation. 

I think that if R/C failsafe is disabled or invalid R/C PWM values are detected that the overrides should not expire. Or, if timeout is set to a negative value, it never expires. 

I deal with the reenabling of the R/C by evaluating a channel not overridden (like channel 5) and then clearing overrides if the channel has a valid value. (The R/C is turned off and then during the flight, the R/C is turned on. There is a reason for this.)

**Comment by WickedShell** [comment]
> Maybe that's why the UINT16_MAX did not explicitly exist in the older code? Perhaps this implicit logic didn't get carried forward?

Highly possible. That is straightforward to fix now.

I'll have to give the RC/failsafe situation a bit more thought, I did my testing with a receiver which emits no data when the link is lost which means that the input value is never changed from the last override anyways. Off the top of my head though, if the RC failsafe is enabled this would mean that you would only have 200 milliseconds (on copter) before the failsafe behavior kicks in for you, although undefined behavior for that time period is definitely not something we want to embrace. The quick patch would be to add a special case to `RC_OVERRIDE_TIME` where a value of -1 means never timeout any active overrides. That probably gets you back to the desired behavior for your usage, while preserving the behavior I was trying to add.

I want to give the failsafe handling a bit more thought though before I send a PR in, as the above comments are just from the top of my head, and I could be missing something. And quickly slapping more special cases in isn't hugely appealing). @rrr6399 Any thoughts on the proposed solution?

**Comment by rrr6399** [comment]
> Highly possible. That is straightforward to fix now.

I tried this in RC_Channel.cpp and this may work for the ignore flag:

``void RC_Channel::set_override(const uint16_t v, const uint32_t timestamp_us)
{
    last_override_time = timestamp_us != 0 ? timestamp_us : AP_HAL::millis();
	if(v == UINT16_MAX)
	{
		return;
	}
    override_value = v;
}``

The Spektrum satellite receiver sends out 0 values if there is no R/C and the AR8000 just emits the last known values when the R/C is off except for throttle.  I have one copter with no receiver so the PWM values are zero for that case. (I learned the hard way about the Spektrum satellite receiver behavior with a number of bad crashes on takeoff and landing.)

I like the RC_OVERRIDE_TIME=-1 since I don't want to repeatedly send R/C override messages when nothing has changed and for my system the overrides will be cleared if the R/C is turned on. Can't a clear overrides switch be assigned to the R/C transmitter now?

**Comment by WickedShell** [comment]
Yeah, it's either teach RC_Channel.cpp that UINT16_MAX means don't do anything, or put it in the vehicles MAVLink layer. I'm inclined to actually do it in the MAVLink handling code, because the ignore channel mode is specifically imposed on us by the MAVLink spec, rather then anything in RC_Channel itself. It's a bit larger patch set to do this, but it aligns a lot better with the intended next steps for override consolidation between vehicles. (I'm mainly trying to use the MANUAL_CONTROL messages, and there are a number of bugs in that message, and signicifcant behaviour differences between vehicles, particularly with regards to the throttle handling that needs to be unified).

> and for my system the overrides will be cleared if the R/C is turned on

Is this a custom patch you have? To the best I can tell that won't happen now, and even before my current changes I couldn't get that to happen in SITL (overrides were simply honored forever regardless of RC presence).

> Can't a clear overrides command be assigned to a R/C transmitter switch now?

Yes, but it's problematic at the moment to add it to all the vehicles. I think waiting until after @peterbarker's unification of switch handling makes a lot of sense. There is some discussion of the switch in passing in #3356. That issue sort of wanders everywhere though, we should probably try and pin it down to a single solution.

**Comment by rrr6399** [comment]
> Is this a custom patch you have? To the best I can tell that won't happen now, and even before my current changes I couldn't get that to happen in SITL (overrides were simply honored forever regardless of RC presence).

The logic to detect the R/C is on the ground station side right now. Its based on the value of channel 5. If its an AR8000, that approach doesn't work, but that's OK for my case since overrides will only occur if the joystick is used and there is a button to release overrides. Having a switch on the R/C to release overrides will provide more robustness as well.

**Comment by WickedShell** [comment]
@rrr6399 I'm having a mental split on fixing the 65536 handling, and am curious what your opinion is. The spec states: `A value of `UINT16_MAX` means to ignore this field.`. If we take this very literally I just shouldn't update the last received value when `UINT16_MAX` comes in. The other option (which is what we used to do), is to say that on receiving `UINT16_MAX` on a channel that control should devolve back to the RC receiver.

I can see the merits to the first one as you could have a GCS which controlled channels 1-8 for normal flying, while an onboard companion computer might want to manipulate channels 9-14 for direct output control of some payload. But it means that the only way to relinquish control the the RC receiver would be to either wait for the timeout, or send a 0 on the channel (which isn't in the spec). Do you have any opinions on implementation?

**Comment by rrr6399** [comment]
@WickedShell  I would strongly recommend that the value remain unchanged for that channel. I use the ignore field on the channels that haven't changed, but it doesn't mean that the R/C should be used. Using the R/C value or 0 would be a disaster. 

If the channel should revert to the R/C value, the R/C override is set to 0.
https://mavlink.io/en/messages/common.html#RC_CHANNELS_OVERRIDE

Also, if the R/C is turned off and the R/C override is to to 0, I'd rather the value be set to trim or unchanged since a value of 0 for pitch, roll, yaw and throttle can be a disaster as well depending on the flight mode. (We learned the hard way that the default behavior for no R/C was to set the values to 0. This default behavior caused a rapid spinning on takeoff and a rapid spin, max pitch and max roll on landing leading to a crash.

**Comment by rrr6399** [comment]
@WickedShell I tried out the latest 3.6.4 firmware and it appears that it still doesn't respond to the ignore R/C override value (UINT16_MAX) correctly. Were your fixes merged into 3.6? If not, I'll just continue to use my own 3.6 branch with my fix in it.

**Comment by rrr6399** [comment]
@rmackay9 It looks like current 3.6 does not handle the ignore R/C override flag correctly and treats MAX_SHORT as an actual R/C value, which can yield disastrous results.

**Comment by rmackay9** [comment]
@rrr6399,

If you happy to create a PR against master that would be great.  Normally we fix the issues in master first and then backport them to the latest release.

**Comment by peterbarker** [comment]
On Fri, 18 Jan 2019, Randy Mackay wrote:

> If you happy to create a PR against master that would be great. Normally we
> fix the issues in master first and then backport them to the latest release.

master is already protected:

https://github.com/ardupilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channel.cpp#L336

@rrr6399 does this issue title need fixing?

**Comment by peterbarker** [comment]
This appears to have been fixed by PR.
