### ISSUE TITLE
Support maxbotix ezl4 lidar

### ISSUE THREAD

**Issue by bobertholomew** [ArduPilot/ardupilot#16749]
I am using an omnibus f4 pro that has very limited analog pins, however it has uarts to spare. If there was support for connecting a serial lidar sensor such as the maxbotix ezl4, then that would greatly increase the functionality of this fc

this would be good for quads or planes

**Comment by amilcarlucas** [comment]
This is a feature request. Please change the title to: "Support maxbotix ezl4 lidar". This has noting to do with omnibus f4 pro.

**Comment by amilcarlucas** [comment]
You can remove the Omnibus part, when it gets implemented it will be available for all boards.
