### ISSUE TITLE
ArduCopter:  MOUNT_STATUS not reporting in SITL 

### ISSUE THREAD

**Issue by eliao** [ArduPilot/ardupilot#1675]
With a GCS connected to SITL, I am able to get MOUNT_STATUS messages, but the values always seem to be 0, even if I have set an ROI.  I get values from a non-simulated vehicle.  Reproduced with @arthurbenemann.

**Comment by peterbarker** [comment]
This seems to work for me now:

```
STABILIZE> status MOUNT_STATUS
STABILIZE> 1489: MOUNT_STATUS {target_system : 0, target_component : 0, pointing_a : -15, pointing_b : 0, pointing_c : 921}
```

This was done simply by setting `MNT_TYPE`, `MNT_STAB_PAN` and `MNT_STAB_TILT`

Please reopen if I missed something.
