### ISSUE TITLE
Copter: gimbal servos sent to limits during startup

### ISSUE THREAD

**Issue by ethomas997** [ArduPilot/ardupilot#168]
Using ArduCopter v2.9.1, the camera gimbal servos run OK after the copter has finished its startup procedure, but during the startup the servos are sent to one end of travel.  It seems like the 'aux' servo outputs are enabled before they are commanded to any position.  I tried some different things with the code, but the best work-around I could come up with is to add these lines to the end of the 'init_rc_in()' function in "radio.pde":

```
RC_Channel_aux::move_servo(RC_Channel_aux::k_mount_roll, 500, 0, 1000);
RC_Channel_aux::move_servo(RC_Channel_aux::k_mount_tilt, 500, 0, 1000);
RC_Channel_aux::move_servo(RC_Channel_aux::k_mount_pan, 500, 0, 1000);
```

This initializes the mount servo outputs to the mid position, rather than defaulting to the end.  A copy of the v2.9.1 "radio.pde" file with the above work-around is available here:  http://www.etheli.com/miscfiles/radio_pde_mountFix.zip

A couple of other people have also had the same issue and posted in the comments here:  http://code.google.com/p/arducopter/wiki/AC2_Camera

--ET

**Comment by jmachuca77** [comment]
Refers to very old code I think this can be closed.

**Comment by ethomas997** [comment]
Agreed.
