### ISSUE TITLE
Sub: move forward/backwards pwm output bug

### ISSUE THREAD

**Issue by idorutm** [ArduPilot/ardupilot#16802]
## Bug report

While trying to manouver with my sub, I noticed the forward/backward(reverse) movements were half-powered.
So I looked at the servo_raw tab (photos attached) and saw that I only get a max of 1500 pwm value when doing that movement.
![move forward backward issue](https://user-images.githubusercontent.com/78803501/109814613-608f9480-7c37-11eb-87e2-8e14f38fff20.png)

When moving right/left this issue doesn't occur.
![move right left](https://user-images.githubusercontent.com/78803501/109814621-62595800-7c37-11eb-908a-11e5bee2e01a.png)

Can you please refer me to the code-line where this happens? or help me solve this issue?
Thanks in advance!

**Version**
4_2_0 DEV

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[ X ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_ 

BlueROV2/Vectored

**Hardware type**
Pixhawk 2.1 - Black Cube

**Comment by Williangalvani** [comment]
I believe it could be related to [this](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Motors/AP_Motors6DOF.cpp#L461).

That said, I'm unable to replicate your issue in SITL.
I have a few questions that could help diagnose the issue (a dataflash log would answer most of them).
What is your setup like?
What flight mode is this?
Do you have any code changes?
Why are your vertical thrusters maxed up?

**Comment by jmachuca77** [comment]
This is most likely a settings issue and not a bug in the code. Please post your issue on the user support forums. 

Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)

**Comment by rmackay9** [comment]
@Williangalvani,

As @jmachuca77 says this is probably a support call.  How do you feel about us creating a Sub section on our discourse server?  There would be no requirement for you to monitor it of course because I suspect you already have your own support servers on the BlueRov site.

**Comment by Williangalvani** [comment]
Right. @idorutm feel free to move this on to https://discuss.bluerobotics.com/

@rmackay9 I remember there used to be a Sub category in Ardupilot Discourse that redirected to Bluerobotic's. I guess that got lost somehow...

**Comment by idorutm** [comment]
> @Williangalvani,
> 
> As @jmachuca77 says this is probably a support call. How do you feel about us creating a Sub section on our discuss server? There would be no requirement for you to monitor it of course because I suspect you already have your own support servers on the BlueRov site.

is this a support call though? I am not using a bluerov's product...
