### ISSUE TITLE
Short term GPS glitch can cause long term EKF3 accel bias and attitude error

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#16814]
We have a bench test log showing EKF3 producing a long term 3.5 degree roll error, apparently due to a quite short (few second) GPS glitch. It is not a replay log.
![image](https://user-images.githubusercontent.com/831867/110037352-6483f980-7d92-11eb-8ba7-67e122fe8ab4.png)
![image](https://user-images.githubusercontent.com/831867/110037384-71085200-7d92-11eb-82c0-03e26ee619cb.png)
![image](https://user-images.githubusercontent.com/831867/110037421-7cf41400-7d92-11eb-889c-7ff32997afdd.png)
![image](https://user-images.githubusercontent.com/831867/110037451-87aea900-7d92-11eb-9681-5b628bcfb829.png)
the IMU data is steady, board was not moving in bench test.
The key concern is the persistence of the roll error from the accel bias estimate after such a short GPS event. 

update: upon reflection, I think this is expected behaviour, see comment below. We can close if Paul agrees

log is here:
http://uav.tridgell.net/EKF/ekf3-roll-offset-gps1.bin
ping @priseborough

**Comment by tridge** [comment]
part of the problem may be the degree that we trust the u-blox gps velocity accuracy data. With no movement in a bench test the EKF is starved of information for bias updates except when the GPS outputs false data.
So I suspect this is really just a bench test artefact and not of concern for flight

**Comment by priseborough** [comment]
This is expected behaviour. The biases will re-learn correctly and restore correct roll/pitch when vehicle starts manoeuvring with GPS enabled.
