### ISSUE TITLE
Plane: MIS_RESTART switch stays on - danger

### ISSUE THREAD

**Issue by JeyPi** [ArduPilot/ardupilot#16881]
Bug report
This is the second time it has happened to me. I threw the plane in to the headwind for an auto take off. The transmitter on the ground, had accidentally MIS_RESTART switch switched on, which happened when I laid it on to the grass.
The Auto-takeoff was performed perfectly. The auto-takeoff point was quite far, the plane small, basically it disappeared and never showed up, even through the next waypoint lead through the take off position. Here the horror starts. I could hear the plane but I could not see it. I took my bicycle and went to find it along the route, but it was not seen for an hour. RTL command did not work, the auto route was not flow. 
The battery would last for another 10 minutes when I finally saw it at 100m, switched to manual and landed safely.
The plane was nowhere far, but damn high. It repeated the takeoff procedure on and on and on.....It climbed each time 30m to finish the auto take off until it was so high that I am scared to post it here. When I was looking for it on the bike with the transmitter on my neck I somehow touched the MIS_RESTART switch and switched it off. The plane resumed the auto route and started to descend during which end I saw it. All the chain of events ended happily but it was luck. We all know how bad it could be.
My ideas to prevent this are:
Could the software take the resume mission switch as momentary switch. If it is on longer than a second than consider it off.
Next time the pilot needs to reactivate the mission the software needs to see the switch at least a second off before it is switched on again.
If a MIS_RESTART is left on in flight, the software gets somehow lost. I do not grasp why the RTL did not work.
I am not sending the log with the situation prescribed, as it is big and corrupted (probably by so many mission starts)  I am sending a log during which my MIS_RESTART switch was also changing the motor rotation. The plane was descending in manual mode, motor reversed, therefore the MIS_RESTART switch switched on. Suddenly it stopped descending, motor resumed normal rotation and the plane flew away without respecting the transmitter signal. Iswitched modes several times before I regained control. In the log it switchet to auto flight due to TX communication loss. But it was close, comfortably in the range.

**Version**
Ardulane V 4.0.9

**Platform**
Plane 

**Airframe type**
Delta wing (2 elevons+ reversible motor)

**Hardware type**
Pixracer

**Logs**
https://drive.google.com/file/d/1lXsXsPJkYlpuLjRKjpi_qgKz1zBSPrtQ/view?usp=sharing

**Comment by IamPete1** [comment]
The fix is stop using MIS_RESTART and use RCx_OPTION 24. We should just remove MIS_RESTART all together.
