### ISSUE TITLE
Copter: update wiki ahead of AC3.3

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1691]
This is a list of wiki page updates we need to make before the release of AC3.3:
- [ ] Changes to Pixhawk sounds including updating the video.  http://copter.ardupilot.com/wiki/common-apm-board-leds/
- [x] add optional hardware page for rob's landing gear.  http://copter.ardupilot.com/wiki/common-optional-hardware/landing-gear/
- [ ] mount changes after frontend/backend split and addition of MAVLink enabled gimbals
- [ ] documentation of jonathan's auto compassmot procedure
- [ ] EPM gripper mission commands should be updated to use do-gripper
- [x] alexmos gimbal setup
- [x] new options for aux switches (and number of switches) including e-stop, interlock
- [x] brake mode
- [x] smart battery.  http://copter.ardupilot.com/wiki/smart-battery/
- [x] AUTOTUNE_BITMASK to control which axis are tuned. http://copter.ardupilot.com/wiki/autotune/
- [x] add RCMAP documentation  http://planner.ardupilot.com/wiki/common-rcmap/
- [x] vibration monitoring (http://copter.ardupilot.com/wiki/ac_measuringvibration/)
- [ ] diagram to show how to connect px4flow sonar to pixhawk analog input to enable as analog sonar
- [x] tricopter setup - MOT_YAW_SV_MIN, MAX, REV, TRIM have changed since AC3.2.1  - http://copter.ardupilot.com/wiki/tricopter/
- [x] thrust curve

**Comment by rmackay9** [comment]
A few left-over issues from AC3.2.1 should be sorted too.
https://github.com/diydrones/ardupilot/issues/1357

**Comment by auturgy** [comment]
Closing as stale
