### ISSUE TITLE
AP_BattMonitor: Segfault with UAVCAN battery monitors.

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#16915]
## Bug report

If you are sending BatteryInfo messages over the UAVCAN bus already, and change the BATT_MONITOR type from anything other then 0 (IE you had already allocated a backend) to UAVCAN we will decide the previous battery monitor (such as analog) is actually a UAVCAN instance, and cast the driver to AP_UAVCAN and ask it to handle messages. This can lead to corrupting data, or segfaulting and watchdoging. It's a one time configuration error, but the data corruption should be avoided, and it makes a terrible user experience (particularly if the user sees the message).

The specific issue is triggered [here](https://github.com/ArduPilot/ardupilot/blob/40dbb316c1e4bc42cc4ca456453c831d00330371/libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp#L54) Rather then checking what the type parameter currently is, we should be storing the type on the AP_BattMonitor_Backend and asking the driver what type it is.

**Version**
6e85003b56 onwards, so all the 4.0 releases are affected

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by peterbarker** [comment]
I re-discovered this a little while ago.  I fixed it with https://github.com/ArduPilot/ardupilot/pull/27233
