### ISSUE TITLE
Copter: nested Do-Jumps don't work, Condition-Yaw stops do-jump from executing

### ISSUE THREAD

**Issue by paradisephill** [ArduPilot/ardupilot#1693]
I've done a lot of testing of the Condition-Yaw command in Arducopter along with the Do-Jump command and have some suggestions for updating the Wiki at:http://copter.ardupilot.com/wiki/mission-command-list/#Do-Jump with the following:

 Do-Jump restrictions:
1. No more that three (3) Do-Jump commands can be used in a mission, the fourth and subsequent Do-Jumps will be ignored.
2. Do-Jump sequences cannot overlap (no nested Do-Jumps).
3. If a Condition-Yaw command is still in progress when the Do-Jump command is reached, the Do-Jump will be skiped. Be sure to allow enough time for the Condition-Yaw to complete by putting a waypoint with a delay and zero altitude, lat and lon as in step 10 in the example below. Your delay length is dependant upon the size of the 'copter, the yaw tuning parameters and the wind conditions.
![do-jumpjpg](https://cloud.githubusercontent.com/assets/7903116/5464846/e89d90fe-8542-11e4-8c6e-22163889a0d2.JPG)

**Comment by IamPete1** [comment]
Have tested in SITL, 2 and 3 are now fixed and we can now do up to 15 jumps per mission.
