### ISSUE TITLE
Rover: support automatic trailer hitching

### ISSUE THREAD

**Issue by Supermagnum** [ArduPilot/ardupilot#16980]
## Feature request
Optically finding and hitching on to a trailer hitch.
(May cause issues with connections to the trailers lights and hydraulic brakes and systems )

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Comment by rmackay9** [comment]
I guess this is marked as "completed" because we've added "Dock" mode in 4.3 that supports reversing into a non-moving dock... which could be close to a trailer.  I'm not sure it will work quite well enough to actually allow fully autonomous trailer hitching but it's worth testing.
