### ISSUE TITLE
Calculating release point of a payload depending on ground speed, air speed and drift angle.

### ISSUE THREAD

**Issue by Supermagnum** [ArduPilot/ardupilot#16983]
## Feature request

The payloads impact point needs to be calculated based on changing flight conditions, payload weight and the drag coefficiency of the payload, also using altitude and airspeed to determine the angular velocity of the target.

By simply knowing the aircraft's altitude and heading, along with estimates of the wind speed and direction (in relation to the aircraft), the computer can automatically, and quickly, calculate the release point.

**Platform**
[  ] All
[  ] AntennaTracker
[ X] Copter
[ X] Plane
[  ] Rover
[  ] Submarine

This can also possibly be combined with a camera in a servo controlled pitch and yaw gimbal, and a Raspberry Pi 4 to emulate the behaviour of a Norden sighting system.

How that was used:
https://youtu.be/143vi97a4tY

It could be very funny for those having a B-25 Mitchell Bomber radio controlled aircraft or similar.

**Comment by rmackay9** [comment]
Thanks for the enhancement request.

We've discussed this kind of enhancement in the past but the dangers of the feature being used for purposes that conflict with our developer's code of conduct (i.e "Modifying ArduPilot code to intentionally support weaponization") means we are reluctant to make this enhancement.

Txs again but I think I'll go ahead and close this.
