### ISSUE TITLE
AC 4.0.7 Simple LUA rcin issue

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#16996]
hello,

I'm just attempting to make this work without successs.
At boot I read on message tab, no lua script to run.....

function update()
gcs:send_text(0, "hello, world") -- send the traditional message
pwm7 = rc:get_pwm(7)
 gcs:send_text(0, "RCIN 7:" .. tostring(pwm7))
return update, 1000 -- reschedules the loop
end
return update()

Please help.

**Comment by IamPete1** [comment]
Copter 4.0.7 does not have the RC input binding, you will have to use 4.1.dev.
