### ISSUE TITLE
LogAnalyzer: False Positive for BrownOut

### ISSUE THREAD

**Issue by ghost** [ArduPilot/ardupilot#1700]
Hi all
just out of curiosity I ran a log file (devbuild-jon-copter) through the Auto Analysis in Mission Planner (1.3.15.2) today. I was pretty shocked to see that the Brownout test failed "Ends while armed at altitude 3.35m".
But everything was fine in flight! I engaged RTL and the landing detector worked perfect. 
It was quite windy, which might be the cause. So it might be a good idea to apply some additional tests to check if the final altitude is an appropriate measure (well usually it is for sure).
Looking at RCOUT and/or some info of the landing detector (not sure if something like this exists) might be options.
Regards,
Thorsten

**Comment by peterbarker** [comment]
We've remove the LogAnalyzer now; the web-based tools are replacing it.
