### ISSUE TITLE
Plane: maximum altitude for FBWB and cruise  mode

### ISSUE THREAD

**Issue by Supermagnum** [ArduPilot/ardupilot#17019]
## Feature request

Maximum altitude in centimeters or meters that FBWB, and CRUISE modes will allow. If you attempt to ascend above this altitude then the plane will level off. A value of zero means no limit. 

**Platform**
[  ] All
[  ] AntennaTracker
[ ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

Useful where the law sets limitations on how high above ground it is permitted to fly.
Perhaps also useable for FBWA mode as it can be helpful for those who are learning to fly .

**Comment by IamPete1** [comment]
We have already, `ALT_HOLD_FBWCM` for a min height. We do also currently support a max alt geofence. It does not stop you braking the limit but will take over and fly you home.

**Comment by rmackay9** [comment]
Copter will already stop at the top of the altitude fence so removing the copter part of this request

**Comment by mmk0102** [comment]
Can I take this task?
I am a newcomer. It is enough to make it work:
- add method Plane::check_fbwb_maximun_altitude();
- add parametr ALT_HOLD_FBWCM_MAX ?

**Comment by IamPete1** [comment]
@mmk0102 that would be great, I would be tempted to rename the existing `check_fbwb_minimum_altitude` to `check_fbwb_altitude` and do them both in the one function. I the new param might as well be in meters, were not so constrained on param space as we were when the min param was added. Jump onto the AP discord if you need any pointers https://discord.gg/hTvezxYQ

**Comment by mmk0102** [comment]
Well, ALT_HOLD_FBWCM (min alt) will be in cm, ALT_HOLD_FBWCM_MAX (max alt) will be in meters, all right?
And check_fbwb_minimum_altitude() move to general check_fbwb_altitude().

**Comment by mmk0102** [comment]
And section **Fly-by-wire control** is full
// 120: Fly-by-wire control
 k_param_airspeed_min = 120,
...
k_param_use_reverse_thrust = 129,
I can use this (from Sensor parameters section):
 k_param_imu = 130,  // unused
 k_param_altitude_mix, // deprecated
or should I add it in the end ?

**Comment by IamPete1** [comment]
Yeah, you should add the new param at the end of the list. Feel free to open a draft PR of what you have, it will be easier to review changes that way.

**Comment by mmk0102** [comment]
Did it as draft PR.

**Comment by mmk0102** [comment]
Well, can we merge it? Or something still wrong?

**Comment by IamPete1** [comment]
@mmk0102 Your PR is still draft, you can convert it to a full PR once its ready

**Comment by Supermagnum** [comment]
How about the similar for FBWA ?

**Comment by Supermagnum** [comment]
Any news here? Is this resolved?

**Comment by IamPete1** [comment]
@Supermagnum No update, PRs welcome.

**Comment by Supermagnum** [comment]
> @Supermagnum No update, PRs welcome.

I hope someone resolves this soon.

**Comment by khanasif786** [comment]
@IamPete1 does the last changes done by @mmk0102 are Right. I am currently testing those.

**Comment by khanasif786** [comment]
I am a newcomer. While @mmk0102  has done most of the work on these. All credit goes to him. There was only 1 mistake, that instead of using 100 he used 1000 to change meter to cms. I have tested it in FBWB mode, it's working.  @IamPete1  Sir, Please suggest changes if any.

**Comment by Supermagnum** [comment]
Any progress on this? It looks like it's ready for merge.

**Comment by khanasif786** [comment]
@Supermagnum, Sorry for the late reply. It is in progress currently i was busy somewhere.. We are doing this using fence max and min altitude instead of adding a new parameter for fBWB limit.
