### ISSUE TITLE
[MAV 001:1] FAILURE: Unsupported CMD: 400 

### ISSUE THREAD

**Issue by ddworken** [ArduPilot/ardupilot#1701]
Whenever I try to arm, the arducopter fails to arm. This is reproducible on the newest Arducopter version (stable and beta) with APM Planner on Ubuntu 14.04 or Mission Planner on Windows 8.1. When trying to arm, APM Planner gives a Message Log of:

Code:
[MAV 001:1] Initialising APM... 
[MAV 001:1] Initialising APM... 
[MAV 001:1] Initialising APM... 
[MAV 001:1] Calibrating barometer 
[MAV 001:1] FAILURE: Unsupported CMD: 400 
[MAV 001:1] Initialising APM... 
[MAV 001:1] Initialising APM... 
(continuing forever)

This occurs every time I attempt to arm the drone. This issue started today after a reboot of the drone (no hard landing and no crash). 

Does anyone have any idea why this is happening?

**Comment by rmarcuzzi** [comment]
Is there a solution for this?
