### ISSUE TITLE
SET_MESSAGE_INTERVAL ignored by SITL after a few seconds 

### ISSUE THREAD

**Issue by Pokornz** [ArduPilot/ardupilot#17046]
Posting after asking at https://discuss.ardupilot.org/t/set-message-interval-ignored-by-sitl-after-a-few-seconds/69411

## Bug report

**Issue details**
When requesting a different rate of `GLOBAL_POSITION_INT` with `SET_MESSAGE_INTERVAL`, the rate changes, but after couple seconds goes back to default 4Hz. As you can see below, this interval varies a lot and is not frequency dependent.
It may be an issue with SITL in particular, because I don't see the same problem on a real FCU with Arducopter 4.0.7, but I was advised on the forum to create a bug report.

![Screenshot from 2021-03-30 09-35-28](https://user-images.githubusercontent.com/33861443/112953024-66489f00-913d-11eb-8e48-9022d4299360.png)
![Screenshot from 2021-03-30 09-34-42](https://user-images.githubusercontent.com/33861443/112953027-66e13580-913d-11eb-8203-15b1c1264509.png)
![Screenshot from 2021-03-30 09-33-29](https://user-images.githubusercontent.com/33861443/112953029-66e13580-913d-11eb-9d6f-2c972b8275c6.png)
![Screenshot from 2021-03-30 09-31-41](https://user-images.githubusercontent.com/33861443/112953030-66e13580-913d-11eb-9985-852141c1e891.png)

**Version**
4.1.0.dev

**Platform**
[ x ] Copter

**Airframe type**
Quad Plus

**Hardware type**
Arducopter SITL started with `sim_vehicle.py -w` on Ubuntu 18.04.5 LTS

**Comment by khancyr** [comment]
That is MAVProxy setting the default streamrate. Nothing to worries about.
