### ISSUE TITLE
EKF has erratic position behaviour on regain of GPS

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#17105]
## Bug report

**Issue details**

https://github.com/ArduPilot/ardupilot/pull/17104 contains an autotest which is currently failing - the EKF forces a second EKF failsafe where it probably should not, instead doing a position-reset or similar.

The issue can be reproduced in SITL by doing the following:

- Start SITL running Copter (e.g. cd ArduCopter; ../Tools/autotest/sim_vehicle.py --map --console)
- Guided (to switch the vehicle to Guided mode)
- arm throttle (to arm vehicle)
- takeoff 10 (to takeoff to 10m)
- param set GPS_TYPE 0 (to disable the GPS)
- wait 30 seconds as the vehicle enters Land mode and lands
- param set GPS_TYPE 2 (to re-enable the GPS)
- Guided
- arm throttle <-- this fails because EKF has lost its position estimate

**Version**
master

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quad

**Hardware type**
SITL

**Logs**

**Comment by peterbarker** [comment]
[ArduCopter-RefindGPS-00000003.TXT](https://github.com/ArduPilot/ardupilot/files/6257180/ArduCopter-RefindGPS-00000003.TXT)

That's actually a `LOG_REPLAY` .BIN file of the failing flight - not an 8.6MB text file :-)

**Comment by peterbarker** [comment]
![image](https://user-images.githubusercontent.com/7077857/113555692-ae385c00-963e-11eb-87aa-e13241c5ffa5.png)

**Comment by priseborough** [comment]
The EKF does start using GPS again based on innovation sequences and solution status.

![Screen Shot 2021-05-13 at 4 38 16 pm](https://user-images.githubusercontent.com/3596952/118087909-9f954f80-b409-11eb-9074-3d995e72d90d.png)

![Screen Shot 2021-05-13 at 4 38 36 pm](https://user-images.githubusercontent.com/3596952/118087941-ade36b80-b409-11eb-95f5-7c03aa73b243.png)

![Screen Shot 2021-05-13 at 4 39 00 pm](https://user-images.githubusercontent.com/3596952/118087977-b9cf2d80-b409-11eb-8ea7-f8aebe4218f3.png)

The solution status value of 107327 maps to the following flags true

        bool attitude           : 1; // 0 - true if attitude estimate is valid
        bool horiz_vel          : 1; // 1 - true if horizontal velocity estimate is valid
        bool vert_vel           : 1; // 2 - true if the vertical velocity estimate is valid
        bool horiz_pos_rel      : 1; // 3 - true if the relative horizontal position estimate is valid
        bool horiz_pos_abs      : 1; // 4 - true if the absolute horizontal position estimate is valid
        bool vert_pos           : 1; // 5 - true if the vertical position estimate is valid
        bool pred_horiz_pos_rel : 1; // 8 - true if filter expects it can produce a good relative horizontal position estimate - used before takeoff
        bool pred_horiz_pos_abs : 1; // 9 - true if filter expects it can produce a good absolute horizontal position estimate - used before takeoff
        bool using_gps          : 1; // 13 - true if we are using GPS position
        bool gps_quality_good   : 1; // 15 - true if we can use GPS for navigation
        bool initalized         : 1; // 16 - true if the EKF has ever been healthy

and the following false:

        bool terrain_alt        : 1; // 6 - true if the terrain height estimate is valid
        bool const_pos_mode     : 1; // 7 - true if we are in const position mode
        bool takeoff_detected   : 1; // 10 - true if optical flow takeoff has been detected
        bool takeoff            : 1; // 11 - true if filter is compensating for baro errors during takeoff
        bool touchdown          : 1; // 12 - true if filter is compensating for baro errors during touchdown
        bool gps_glitching      : 1; // 14 - true if GPS glitching is affecting navigation accuracy

Fault status is zero and the only timeout is for the missing airspeed sensor which doesn't affect copter.

**Comment by priseborough** [comment]
There are two short periods after regaining GPS where a different solution status is present:

111423 - touchdown goes true
109375 - takeoff goes true

**Comment by peterbarker** [comment]
![image](https://user-images.githubusercontent.com/7077857/118569443-4fc5d800-b7bd-11eb-943f-b9249cae08e4.png)

**Comment by peterbarker** [comment]
This also happens on EKF2.

**Comment by rmackay9** [comment]
I think we can close this can't we?  I think PeterB's test was simply trying to use the position estimate before the EKF had recovered.

**Comment by priseborough** [comment]
Agree

**Comment by peterbarker** [comment]
> I think we can close this can't we? I think PeterB's test was simply trying to use the position estimate before the EKF had recovered.

@rmackay9 actually, this issue got fixed sometime in master - the PR showing the bug up in an autotest was committed so it shouldn't reappear.
