### ISSUE TITLE
All/Enhancement: add RSSI via SBUS (counting drops)

### ISSUE THREAD

**Issue by multigcs** [ArduPilot/ardupilot#1711]
hi,
i wrote a patch (for 3.2) to use the drop-bit from SBUS to generate an rssi-value:

http://www.multixmedia.org/test/ardupilot-sbus-rssi.diff
http://www.multixmedia.org/test/PX4Firmware-sbus-rssi.diff

olli

**Comment by Naterater** [comment]
Isn't this handled by http://ardupilot.org/copter/docs/parameters.html#rssi-parameters?

**Comment by peterbarker** [comment]
@Naterater I think the concept was to synthesise an RSSI from SBUS packet drop rates.  That's not something we currently do (for any RC protocol).

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/2721
