### ISSUE TITLE
Tricopter Bug

### ISSUE THREAD

**Issue by batuhanAG** [ArduPilot/ardupilot#17129]
Bug report

I chose the tricopter frame. I connected the rear tail servo motor and made the necessary settings.
But 5 seconds after takeoff, the rear engine slows down the throttle and in addition to these, the plane works in the opposite axis to balance itself. opens up gas when the nose is down.

Version            Platform
                        
Copter 4.0.7     Copter

Airframe type
tricopter

Hardware type
pixhawk cube orange

**Comment by IamPete1** [comment]
This is a setup issue, double check your AHRS orientation and motor ordering.
