### ISSUE TITLE
Copter: NAV_LOITER_TURNS Broken on 4.1.0-DEV

### ISSUE THREAD

**Issue by giacomo892** [ArduPilot/ardupilot#17126]
## Bug report

NAV_LOITER_TURNS WP type doesn't work on master with default params.

The copter reaches the WP and waits there forever without starting to circle.

I've tracked down the issue in the fact that the navigation gets "stuck" inside the function:
bool ModeAuto::verify_circle(const AP_Mission::Mission_Command& cmd)

with copter.wp_nav->reached_wp_destination() being false.

working revision: 67f2c79717ff3385bd56ba5c27c0d8c920abf233 before the SCURVES PR

<img width="981" alt="image" src="https://user-images.githubusercontent.com/20860004/114049324-a5889580-988b-11eb-87aa-eb6dfb29a50c.png">

broken behaviour on master:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/20860004/114050252-64dd4c00-988c-11eb-84ea-a037f16ed960.png">

Waypoint file to test with

[way.txt](https://github.com/ArduPilot/ardupilot/files/6279608/way.txt)

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

I think @rmackay9 @lthall and @IamPete1 can have a say on this

**Comment by shellixyz** [comment]
I can reproduce the issue

**Comment by rmackay9** [comment]
Great, thanks for the report.  I've added this to the 4.1 issues list (https://github.com/ArduPilot/ardupilot/issues/16478) so it won't be forgotten.

**Comment by giacomo892** [comment]
Oddly enough it worked in real life but it is broken on SITL at least for me and @shellixyz ![Screenshot_20210410-091803.jpg](https://user-images.githubusercontent.com/20860004/114283829-1ecee680-9a4c-11eb-9e6d-37fa73b19cae.jpg)

**Comment by rmackay9** [comment]
@giacomo892,

thanks again for this report and I've got a fix now I think.  maybe you could give it a try when you get a second?
https://github.com/ArduPilot/ardupilot/pull/17142

The problem only happened if lat,lon,alt were specified so perhaps that's why it only happened in SITL.

**Comment by giacomo892** [comment]
My pleasure @rmackay9 ! It seems to work fine on SITL now. Will fly test it as soon weather allows. Thanks again for this prompt fix!

**Comment by rmackay9** [comment]
fixed in master, thanks for the report and testing!
