### ISSUE TITLE
Develop consistent units for PID logged items

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#17136]
**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

Define and update logging items

**Comment by lthall** [comment]
PID's are unitless so the only elements that can have units assigned at all are the inputs and outputs. Inputs and outputs depend on the the use of the pid object.

So the closest we can come to this is to specify the units of the input and output.
