### ISSUE TITLE
Copter Camera: automatically trigger the camera over and over while shutter is activated

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#172]
This request comes from Jan Matsuka here:
http://diydrones.com/forum/topics/arducopter-2-9-released?commentId=705844%3AComment%3A1172949

**Comment by enjoybeta** [comment]
Is this one supposed to be closed?

**Comment by jmachuca77** [comment]
I don't see any need for this anymore and its way too old, I think there are other/better ways to trigger a camera now. I think this can be closed.
