### ISSUE TITLE
Copter: Support light and small Proximity device LD06.

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#17211]
## Feature request
I am using an ArduCopter to improve my toy drone.
I was looking for a light and small Proximity device.
I found the LD06 on inno-maker.com.
I'm working on adding this device.

http://wiki.inno-maker.com/display/HOMEPAGE/LD06

Frame Data
![Screenshot from 2021-04-17 18-40-39](https://user-images.githubusercontent.com/646194/115108647-95b83200-9fac-11eb-84cb-ffd3576813bf.png)

Frame data is communicated in 2-3 milliseconds.
Frame data is communicated in 2-3 milliseconds.
Each frame contains 12 sets of distance and confidence values in an 8 degree range.

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by rishabsingh3003** [comment]
12 meters range, 360 degrees in about 100 dollars.. sounds like it'll do very well with our Avoidance libraries!

**Comment by matthewryanburgin191** [comment]
Hi,

How did this turn out?

Cheers
