### ISSUE TITLE
Can't create folders through MAVFtp on Pixhawk mini

### ISSUE THREAD

**Issue by rizvanovic** [ArduPilot/ardupilot#17257]
## Bug report

**Issue details**

_Trying to create a "scripting" folder in the APM directory results in an error message (see attached image). I could not find a way around this (I tried on different computers and versions of MP). Initially I feared the flash memory was too small on the PH mini but I haven't found any info confirming this.  _
![image](https://user-images.githubusercontent.com/77106148/115772419-612ee680-a3af-11eb-9f03-64c1f56bcd65.png)

**Version**
4.1.0 DEV Arduplane

**Platform**

[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_Tailsitter_

**Hardware type**
_PIxhawk mini 3DR (bought from holybro)_

**Comment by IamPete1** [comment]
related to https://github.com/ArduPilot/ardupilot/issues/14860

**Comment by tridge** [comment]
fixed by #19267
