### ISSUE TITLE
Smartaudio VTX control can't change band/channel

### ISSUE THREAD

**Issue by griffondrones** [ArduPilot/ardupilot#17266]
## Bug report

**Issue details**

When using smartaudio VTX control with a TBS UNIFY PRO32 HV VTX, changing bands or channels doesn't seem to work.
The connections and configuration appears okay, since pitmode works. 

**Version**
Latest 4.1.0 dev-version available 2021-04-24. ArduPlane build.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Flying wing

**Hardware type**
Matek F405-Wing
TBS UNIFY PRO32 HV

**Logs**
Nothing in the log points to a problem.

**Comment by andyp1per** [comment]
Please can you post your parameters

**Comment by griffondrones** [comment]
Ah, never mind, it seems like it sorted itself out somehow.  Possibly a bad connection for the SA pin..
