### ISSUE TITLE
Error path ./install-prereqs-ubuntu.sh: строка 284: /home/Tools/completion/completion.bash: Нет такого файла или каталога Resolved by deleting ../../ 

### ISSUE THREAD

**Issue by monogir** [ArduPilot/ardupilot#17265]
https://github.com/ArduPilot/ardupilot/blob/278593a6a02a021d3a4a85f1cdc9f88b448dc9c6/Tools/environment_install/install-prereqs-ubuntu.sh#L258

**Comment by khancyr** [comment]
Hello,

Could you details on which system you get this error and what instructions you were following?

**Comment by IamPete1** [comment]
Closing because no more information was provided by @monogir
