### ISSUE TITLE
Message appears to be too long: AutoTune: failing to level, manual tune may be req....uired

### ISSUE THREAD

**Issue by lthall** [ArduPilot/ardupilot#17278]
This message in Autotune appears to be too long making it hard to read:

27/04/2021 11:09:49 AM : uired
27/04/2021 11:09:49 AM : AutoTune: failing to level, manual tune may be req

![image](https://user-images.githubusercontent.com/100896/116171989-04358680-a749-11eb-9e9b-30b8bc236239.png)

**Comment by WickedShell** [comment]
With MAVLink 2 and a reasonably up to date GCS you should see these combined into a single message, but it's definitely not always going to be combined, and on a MAVLink 1 system, it will always look as you outlined. It's your guys call as the autotune maintainer how much you care about it being incorrect on MAVLink 1.

**Comment by peterbarker** [comment]
Well... the message chunks should really still be displayed in order IMO.

Pretty sure we spit them out in the right order :-)

**Comment by lthall** [comment]
I assume there is a maximum number of characters that we should use before this happens. It looks like about 50. Is there a specific number we should try to stay below or will it be variable based on what is in front or something?

**Comment by peterbarker** [comment]
50 is the magic number

But for low-bandwidth errors, clarity is a good thing for reducing user support.

Maybe if we poke @meee1 he might start reassembling messages.  Or emitting them in the right order :-)

**Comment by rmackay9** [comment]
Let's just shorten it.  How about, "AutoTune: failing to leve, please tune manually"?

**Comment by lthall** [comment]
Would it be acceptable to do a double message so it comes out as:
AutoTune: failing to level, 
manual tune may be required.

**Comment by peterbarker** [comment]
> Would it be acceptable to do a double message

Ewww :-)

We have facilities to chunk/reassemble longer messages which should be used for doing that.

Additionally two messages may still suffer from that reordering problem in MissionPlanner.

@rmackay9 's plan is probably the best.

**Comment by lthall** [comment]
> @rmackay9 's plan is probably the best.

I agree. 50 characters or less :)
