### ISSUE TITLE
Copter: allow configuring how much booster motor contributes to lift

### ISSUE THREAD

**Issue by sajjsamm** [ArduPilot/ardupilot#17293]
## Feature request

**Is your feature request related to a problem? Please describe.**
I'm playing around for a while with the booster engine function. It seems to me that `MOT_BOOST_SCALE` doesn't actually reduce the load on other motos. It only scales up the booster engine throttle for its output PWM.

I have a couple of powerful brushless motors along with bigger props on the center of my hexacopter which act as my booster engines as a coaxial design (one motor rotates CW and other CCW) that can provide more than enough lift thrust for my drone that I don't need the other 6 motors to do anything except for just controlling the attitude.

In an ideal situation, this drone should hover without even the other six motors spinning (or spinning with their arming speed which is very low and doesn't make much thrust) and we gonna need those motors ONLY for Roll and Pitch, and maybe Yaw movements.

**Describe the solution you'd like**
I'd like to have an extra option in the config section that let me decide to put more load on booster motors or the other six motors. Like if I increase that parameter the booster motors start to rotate faster to compensate for the gravity meanwhile the other six motors struggle more to keep the drone level and up against the wind or other things or to push the drone forward as the pilot commands.

**Describe alternatives you've considered**
Maybe you can merge those two functions (current boost throttle and the one I explained earlier) with each other and make the `MOT_BOOST_SCALE` act as normal like it is doing right now or make it differential (like the one I wanted) and let the user decide to choose the desired mode.

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
You may mention that this design is somehow useless because the non-booster motors will suffer to keep the drone's attitude under control. I must say the design has a pair of balancers to help to balance the drone.

**Comment by IamPete1** [comment]
This can be done with the new ability to set throttle factors from scripting we don't have a example, but it is quite straight forward. This is a example for a hex, The boost motor would be set to have zero roll, pitch and yaw factors. 

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/MotorMatrix_fault_tolerant_hex.lua

You would use:
`MotorsMatrix:set_throttle_factor(motor_num, throttle_factor)`

To set the throttle factors to 0 for the stabilization motors and 1 for the boost motor.

Happy to help with a example, but I'm going to close this issue.
