### ISSUE TITLE
Copter: add MOT_POW_MAX

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#17300]
Hello,

I have an issue seting this value, I want to set current limiting at 60A on 12S multirotor.
When uav is flying normally (10m/s) with little wind, I never get more than 60A, but at the end of battery, when battery remaining is below 40%, I can get 60A continuous and 70A spikes.

I expect that at below batterie low voltage treshold, current liming desactivate by itself.

I fear that if current limiting activiate at the end of flight my multirotor crash.

What is the expected behavior?

Thank you so much for your help.

Kind regards.

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/1670
