### ISSUE TITLE
Support for dual RTK GPS receivers

### ISSUE THREAD

**Issue by Supermagnum** [ArduPilot/ardupilot#17339]
## Feature request

If magnetometers are used near spinning metallic objects, these may interact with the earths magnetic field and mess up compass readings.

Two RTK GPS receivers  mounted on a vehicle can be used to accurately compute a heading angle (also an alternative to compass-based heading estimation), and correct the compass reading. The angle made by the baseline (the line between the two GPS antennas) relative to the vehicle x-axis must be taken in account.

**Platform**
[  ] All
[  ] AntennaTracker
[ X] Copter
[X] Plane
[X] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Already supported, see: https://ardupilot.org/copter/docs/common-gps-for-yaw.html
