### ISSUE TITLE
Penta6 motor mix

### ISSUE THREAD

**Issue by Riktor1990** [ArduPilot/ardupilot#17347]
Hello all,

following Randy suggestion, I open this request to integrate into the code the Penta6 configuration. 

motors are positioned on the edge of a pentagon, with 2 motor in Vtail configuration on the rear edge. 

I got already this setup working perfectly on BF and INAV, I think it will be a good add on on Arucopter. 

https://discuss.ardupilot.org/t/move-vtail-hexa-from-betaflight-to-arducopter/66768/5

```
MotorsMatrix:add_motor_raw(0, -1.000,  0.260,  0, 2)
MotorsMatrix:add_motor_raw(1,  1.000,  0.260,  0, 5)
MotorsMatrix:add_motor_raw(2,  0.570, -0.700,  1, 6) 
MotorsMatrix:add_motor_raw(3,  0.000,  1.000, -1, 2)
MotorsMatrix:add_motor_raw(4, -0.570, -0.700, -1, 1)
MotorsMatrix:add_motor_raw(5,  0.000,  1.000,  1, 4)
```

I use the standard hexacopter X as reference for motor order, same for test sequence. 

please let me know if you need further info. 

Kind regards, 

Lorenzo

**Comment by IamPete1** [comment]
Looks like you got this working via lua. I don't think there is much point in adding these unusual frames to AP directly when scripting offers so many more options. Maybe it would be a good idea to setup a repo of motor configuration scripts tho....
