### ISSUE TITLE
SITL: configuring with gimbal support causes frequent disconnections with GCS

### ISSUE THREAD

**Issue by tzuriel-spearuav** [ArduPilot/ardupilot#17354]
## Bug report

Followed instructions at [Adding a gimbal](https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html#adding-a-gimbal) to configure SITL with gimbal (note: due to missing params RC6_FUNCTION, RC7_FUNCITON, I followed this link - [What replaces RCx_FUNCTION?](https://discuss.ardupilot.org/t/what-replaces-rcx-function/18911), and switched to SERVO06_FUNCTION and SERVO7_FUNCTION). Then initiated SITL with -M switch, using the command:
`./tools/autotest/sim_vehicle.py -M -v ArduCopter --out=127.0.0.1:14550 --use-dir copter1 -I 1`

However, connection with either MissionPlanner or QGC shows the comm link is constantly breaking. While running without “-M” works perfectly fine, but without gimbal…

**Version**
ArduCopter V4.1.0-dev, QGC/MissionPlanner

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad copter, SITL

**Hardware type**
SITL software only

(also submitted as question in forum - https://discuss.ardupilot.org/t/running-sitl-with-gimbal-m-constantly-closes-connection/70281)

**Comment by IamPete1** [comment]
I'm afraid it looks like those instructions are just just hopelessly out of date. I'm going to close this issue and open one to update the instructions. 

https://github.com/ArduPilot/ardupilot_wiki/issues/3690
