### ISSUE TITLE
SITL: copter-optflow.param out-of-date

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#17400]
The [Tools/autotest/default_params/copter-optflow.parm](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/default_params/copter-optflow.parm) file is out-of-date now that we're using EKF3_SRC1_ parameters.

We should also update the "Using SITL" wiki page so I've added a to-do to the [4.1 wiki issue](https://github.com/ArduPilot/ardupilot_wiki/issues/1756).

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/17590
