### ISSUE TITLE
Rover: waypoint delay of -1 leads to delay of 65k seconds

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#17488]
If Rover's Auto waypoint command has a delay of "-1" this is interpreted as 65535 seconds when it should be treated as 0.

This was reported in this discussion:  https://discuss.ardupilot.org/t/delay-time-issue-at-a-waypoint/71410

**Comment by hendjoshsr71** [comment]
a user can also do this in Copter, Sub, & Plane with a few different waypoint types

**Comment by muramura** [comment]
No consideration is given to positive values. This limits the hold time.
