### ISSUE TITLE
Plane: add Smart RTL on Fixed Wing

### ISSUE THREAD

**Issue by sabyrne** [ArduPilot/ardupilot#17484]
Hi All

Is it possible to activate smart RTL on a fixed wing aircraft? I see it is available for multirotor.

Thank you

Steven Byrne

**Comment by rmackay9** [comment]
It's not supported on Planes so I've added the Enhancement label to this issue.  no promises on when/if it will be done but at least it's on the request list.  txs!

**Comment by rmackay9** [comment]
Ah, sorry, it's already here on the issues list so I will close this issue. https://github.com/ArduPilot/ardupilot/issues/2380
