### ISSUE TITLE
New Bootloader failure on USB on Trad Heli

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#17487]
Bootloader fails on trad heli 4.1.....Copter and Plane works, but probably has issue, just not fails

**Comment by vierfuffzig** [comment]
@Hwurzburg see ttps://github.com/ArduPilot/ardupilot/issues/17452
related?

**Comment by IamPete1** [comment]
@Hwurzburg any update? Did we fix this?

**Comment by hendjoshsr71** [comment]
@Hwurzburg ping again?

**Comment by auturgy** [comment]
No update for two years, and linked issue resolved. Closing.
