### ISSUE TITLE
Plane: `NAV_CONTROLLER_OUTPUT` appears to use incorrect units

### ISSUE THREAD

**Issue by arikrupnik** [ArduPilot/ardupilot#17584]
It appears that Plane reports airspeed errors in cm/s:
https://github.com/ArduPilot/ardupilot/blob/126456742a6a1f8a19cc9b187c0f59ea565e1d43/ArduPlane/GCS_Mavlink.cpp#L185

The relevant message definition in MAVLink specifies m/s: https://mavlink.io/en/messages/common.html#NAV_CONTROLLER_OUTPUT

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/7932
