### ISSUE TITLE
Remove internal error related to parameter reset

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#17628]
The parameter reset handling code has been out in the wild (with Copter-4.0.7) long enough that we are confident that it is working.  Let's remove the internal error so user's aren't unnecessarily concerned.

**Comment by IamPete1** [comment]
@rmackay9 On thie copter issues list it says "Randy and Tridge decided to leave this in place. It happens so rarely that it is not annoying for users." So we can close? Or is the plan still to remove it as some point in the future?

**Comment by rmackay9** [comment]
Yes, let's close this, thanks
