### ISSUE TITLE
SITL: tri model doesn't work

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#17645]
At some point the multicopter Tri frame type in SITL stopped working.  It may be just tuning but in any case, we really should get this working again.

autotest has a full list of vehicle frames that don't fly in SITL here: https://github.com/ardupilot/ardupilot/blob/master/Tools/autotest/arducopter.py#L6562

Note that this does not mean that the real vehicles don't fly.  It most likely just means the SITL parameter files are incomplete for these frames.

**Comment by tridge** [comment]
fix here: https://github.com/ArduPilot/ardupilot/pull/17695

**Comment by hendjoshsr71** [comment]
Closing. Fix merged in #17695

**Comment by rmackay9** [comment]
This issue may not be fixed at least according to this discussion: https://discuss.ardupilot.org/t/fly-away-in-land-mode/73001

**Comment by rmackay9** [comment]
I've investigated a bit and it is not the same issue as before so closing.  I'll create a new issue.
