### ISSUE TITLE
BLHeli Telemetry and Batt issues

### ISSUE THREAD

**Issue by Alexis-Stu** [ArduPilot/ardupilot#17656]
**Issue details**
Battery (BLHELI_Telemetry sum) reports the correct voltage but when amps are drawn, the percentage begins to fall too fast given the parameters and amps drawn.

ESC telemetry values appear to be recorded in one message in the log unlike the stable firmware that records a separate instance for each ESC. This may be causing a current draw issue that is reporting far too many mAh consumed compared to the amps drawn.

**Version**
4.1.0 Latest

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Twin engine electric

**Hardware type**
Pixracer Pro, Holybro BLHeli_32 ESC's.

**Logs**
https://1drv.ms/u/s!AunBK4rE1ZDChI8fAfDa9Yui6xwh9w?e=UKh1IS

**Comment by andyp1per** [comment]
@Alexis-Stu your log show multiple telemetry values:

![image](https://user-images.githubusercontent.com/2893260/120828628-a6206e00-c554-11eb-9708-edae5e38ecab.png)

can you explain a bit more what you think the problem is? Note that the consumption figure comes straight from BLHeli - we do not do any interpretation on it

**Comment by Naterater** [comment]
Look at the BAT.CurrTot message. It is not the sum of the ESC.Ctot messages. In just a few minutes at 0 throttle, it shows 3500mAh consumed. I also see DroneePlotter doesn't handle the instances very well. 

![image](https://user-images.githubusercontent.com/35429159/120837335-2f6f7a80-c52c-11eb-9cb4-76f9443ebcab.png)

**Comment by andyp1per** [comment]
Right, but this comes direct from BLHeli so I would say is a BLHeli issue

**Comment by Naterater** [comment]
No. BLHeli is telling us that a total of 10mAh have been consumed. The BAT.CurrTot tells us that 3500mAh have been consumed.

This works just fine in 4.0.9.

**Comment by andyp1per** [comment]
Oh sorry, now I see what you are saying. How do you have the battery monitor configured? Is it set to ESC?

**Comment by Naterater** [comment]
Yes. BATT_MONITOR is set to option 9

**Comment by Naterater** [comment]
Possible related issue I'm seeing; on some boots, the BATT doesn't even recognize the BLHeli voltage readings. It stays at 0 even though ESC 5 and 6 are showing voltage through Mission Planner.

**Comment by andyp1per** [comment]
Ok I see what is going on here: this should fix https://github.com/ArduPilot/ardupilot/pull/17657

**Comment by rmackay9** [comment]
I've added this to the 4.1 issues list .. looks like we have a fix in the works so hopefully we can include this in beta4

**Comment by andyp1per** [comment]
Hi @Naterater or @Alexis-Stu - are you able to try https://github.com/ArduPilot/ardupilot/pull/17657 ? I do not have ESCs that have current so cannot. I can do a build for you if you need.

In particular can you check that battery reset works correctly:

![image](https://user-images.githubusercontent.com/2893260/121387277-769da700-c942-11eb-8b9c-443944f480b3.png)

**Comment by Naterater** [comment]
Please send a mRo Pixracer Pro build and we'll get it tested today.

**Comment by andyp1per** [comment]
@Naterater:
[arducopter.zip](https://github.com/ArduPilot/ardupilot/files/6625277/arducopter.zip)

**Comment by Naterater** [comment]
@andyp1per, Sorry, plane please

**Comment by andyp1per** [comment]
Done

**Comment by andyp1per** [comment]
@Naterater any joy?

**Comment by Naterater** [comment]
@andyp1per, yes, that appears to have solved the issue.

**Comment by andyp1per** [comment]
@Naterater super! And battery reset works as expected?

**Comment by Naterater** [comment]
As far as I could tell, yes. We did reset it twice and it performed nominally.

**Comment by andyp1per** [comment]
Thanks @Naterater
