### ISSUE TITLE
use arduino (Control Specialist)

### ISSUE THREAD

**Issue by RuffaloLavoisier** [ArduPilot/ardupilot#17770]
## Feature request

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

No :)

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Arduino has a programming method for reading PWM signals. 
This allows the output device to be controlled on top of the Arduino.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

![issue](https://user-images.githubusercontent.com/66334969/121882035-fb296480-cd4a-11eb-8139-84be7eb3a7c1.JPG)

**Platform**
[ v ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

I have used this method as a personal project and I can actually solve the problem by connecting more various output devices.

**Comment by khancyr** [comment]
hello

I fail to see where does this connect to ArduPilot ? You could always use a Y cable to get two PWM signal from your receiver : on for the flight controler and the other on to an arduino board.

**Comment by RuffaloLavoisier** [comment]
The reason why I want to connect Arduino to the receiver is to allow the controller to program more features in Arduino using the value of 1000-2000 of the optional channel.

You can connect an extra channel to the receiver to the Arduino interrupt pin for use.
