### ISSUE TITLE
Implement canvas mode for HD OSD (for DJI goggles and Fatshark Sharkbyte)

### ISSUE THREAD

**Issue by wsalopek** [ArduPilot/ardupilot#17785]
## Feature request

**Is your feature request related to a problem? Please describe.**

(Long-time user of ardupilot, but I'm a noob at understanding the exact technical/programming issues involved, as well as how to use Github, but here you go):

Problem:  HD FPV systems currently require MSP to display OSD fields in HD goggles, which also requires the HD manufacturers (DJI and Fatshark) to update firmware.

**Describe the solution you'd like**

Implement "canvas" mode for OSD so users of DJI goggles and Fatshark's Sharkbyte system can display any/all OSD fields they like, just like they can with analog FPV systems, and without dependence on DJI and Fatshark firmwares.

**Describe alternatives you've considered**

Trying to make MSP work is hit and miss and feels much like a band aid until canvas mode is implemented.  Plus effectiveness depends and is limited by DJI and Sharkbyte to make firmware changes. 

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[ x ] Plane
[ x ] Rover
[ x ] Submarine

**Additional context**

Some discussion (MSP) is here:

https://discuss.ardupilot.org/t/msp-protocol-support/57944

**Comment by yaapu** [comment]
Canvas Mode is only supported by FatShark's SharkByte, DJI Gogglex V1 and V2 do not support it
