### ISSUE TITLE
Plane: OSDx_PLUSCODE_yyy not available

### ISSUE THREAD

**Issue by padcom** [ArduPilot/ardupilot#17780]
## Bug report

**Issue details**
When setting up OSD the PLUSCODE element is not available for planes. I have used it in copters though.

**Version**
4.1.0-dev from 2021-06-14

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Flying wing

**Hardware type**
Matek F405 WING

**Logs**
No logs needed

**Comment by rmackay9** [comment]
I think it would be best to open a topic in the new Plane 4.1 category on discuss instead of raising an issue. https://discuss.ardupilot.org/c/arduplane/plane-4-1/160

I'll leave this open 'cuz I'm not the plane maintainer but normally that's how we do it I think.

**Comment by IamPete1** [comment]
Plus-code is not enabled on the F405 wing to save flash. You can compile your own and change that here: https://github.com/ArduPilot/ardupilot/blob/a6e8f2e73bcf8fefd3b70e61346c5220d1395201/libraries/AP_OLC/AP_OLC.h#L24

Hopefully another thing the custom build server will fix, https://github.com/ArduPilot/ardupilot/issues/15179
