### ISSUE TITLE
Plane: Matek UAVCAN airspeed sensor fails to work with Pixhawk 4 Mini 

### ISSUE THREAD

**Issue by liamf555** [ArduPilot/ardupilot#17796]
## Bug report

**Issue details**

This issue relates to this forum post [https://discuss.ardupilot.org/t/ph4-mini-uavcan-wont-work/71210](url). When connecting over CAN, a Matek UAVCAN DLVR-10 airspeed sensor fails to work with a Pixhawk 4 Mini running Plane 4.0.9. The same sensor will work over CAN with a Cube Orange, running Plane 4.0.9. 

It seems to be a problem with the slow boot of the airspeed sensor, and a race condition with the airspeed initialisation. A temporary fix was to add a delay between the CAN init call and the airspeed initialisation in ArduPlane/system.cpp:

`hal.scheduler->delay(1000);` was added before the ` airspeed.init()` call.

When the airspeed sensor is being initialised, it wants to see that the “module” has a valid pointer to an AP_UAVCAN instance. (See line 51 of AP_Airspeed_UAVCAN). However, that only happens after a UAVCAN message is received (see line 100). If the init() (and subsequently probe()) call happens before a message is received, the airspeed backend isn’t ever set up properly.

**Version**
Plane 4.0.9

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Fixed-wing

**Hardware type**
Pixhawk 4 Mini

**Comment by IamPete1** [comment]
sounds like this could be resolved by setting `BRD_BOOT_DELAY` to 1000+
