### ISSUE TITLE
Rover: PANIC when running DO_SET_MODE mission in SITL

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#17816]
## Bug report

https://discuss.ardupilot.org/t/do-set-mode-does-really-works/72708
I saw this discus and PANIC when I run the DO_SET_MODE mission in SITL.
GCS continues to display NOLINK.
GDB is outputting PANIC.

mission
![Screenshot from 2021-06-20 18-31-04](https://user-images.githubusercontent.com/646194/122669277-89906100-d1f7-11eb-8d10-425827755053.png)

console:
![Screenshot from 2021-06-20 18-30-38](https://user-images.githubusercontent.com/646194/122669289-96ad5000-d1f7-11eb-9471-52778a2b44c1.png)

GDB:
![Screenshot from 2021-06-20 18-45-17](https://user-images.githubusercontent.com/646194/122669312-b17fc480-d1f7-11eb-949e-eb692331ff33.png)

**Issue details**

_Please describe the problem_

**Version**
ArduRover V4.1.0-dev (39c96f63)

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Airframe type**
Default

**Hardware type**
SITL

**Logs**

**Comment by rmackay9** [comment]
I've created an issue here for MP to remove DO_SET_MODE from the list of possible mission commands https://github.com/ArduPilot/MissionPlanner/issues/2652

I'll leave it for others to decide what to do about the PANIC.  My guess is that we want the panic in SITL so that autotest can catch cases where someone tries to use an unsupported command.

**Comment by muramura** [comment]
I would like to return the execution result.  I don't think it needs to be panic.  I think it's better for all gcs to return the result with fc than to do it with gcs.

**Comment by peterbarker** [comment]
Correct fix here is probably to just add the relevant string!

Even better would be to audit to ensure all are covered - but this is a SITL-only panic to pick up exactly what it did.
