### ISSUE TITLE
Copter: arming via switch enables airmode - but no way to disable

### ISSUE THREAD

**Issue by CJ-Davies** [ArduPilot/ardupilot#17836]
## Bug report

**Issue details**

Arming Copter via switch (RCx_OPTION = 41) also activates AirMode in Stabilize flight mode. This is documented behaviour [as per the wiki](https://ardupilot.org/copter/docs/airmode.html).

However there is no way to **disable/prevent** AirMode from activating in this scenario. You cannot use Stabilize without AirMode when arming via switch.

**Version**
4.0.7

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Tested on Y6B, but likely applies to all

**Hardware type**
Orange Cube

**Logs**

**Comment by IamPete1** [comment]
IMHO now we have a dedicated switch and param option we should just stop enabling it for switch arming.

**Comment by andyp1per** [comment]
Makes sense to me. I guess ideally we would need an option for stabilize as well.

**Comment by rmackay9** [comment]
@CJ-Davies, why would you not want airmode?  I would have thought that in general it is helpful the only downside is that it makes it difficult to disarm.

**Comment by CJ-Davies** [comment]
> @CJ-Davies, why would you not want airmode? I would have thought that in general it is helpful the only downside is that it makes it difficult to disarm.

A feature that makes disarming difficult shouldn't be forced upon setups that will never actually use that feature. Airmode provides no benefit whatsoever for setups that never perform zero throttle manoeuvres.
