### ISSUE TITLE
Compilation error while installing

### ISSUE THREAD

**Issue by huseyin-yildiz** [ArduPilot/ardupilot#17871]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

I cant install it today
like this entry https://discuss.ardupilot.org/t/sitl-linux-set-up-troubleshooting-error-in-the-ap-battmonitor-logging-cpp/73021

_Please describe the problem_
it gives an compilation error in  AP_BattMonitor_Logging.cpp file
**Version**
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[ x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Logs**

![image](https://user-images.githubusercontent.com/76514563/123549524-257b1900-d772-11eb-8462-d9308db8fa34.png)

**Comment by rmackay9** [comment]
This seems related to this discussion: https://discuss.ardupilot.org/t/sitl-linux-set-up-troubleshooting-error-in-the-ap-battmonitor-logging-cpp/73021
and this PR: https://github.com/ArduPilot/ardupilot/pull/17873

**Comment by IamPete1** [comment]
The PR fixing this has now been merged, if the issue remains feel free to re-open.
