### ISSUE TITLE
Low throttle stick on QLoiter descent inhibits yaw control

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#17885]
stick fully low on QLOITER inhibits yaw...DZ above and it works
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
QuadPlane

**Comment by IamPete1** [comment]
Do you have a log? Most likely were prioritizing roll/pitch above yaw because motors are saturated low, if that is the case its more or less a hardware limitation.

**Comment by Hwurzburg** [comment]
pretty sure its not saturating...here is a log....with default descent and very slow....slower doesn't stop the issue
[00000001.BIN.txt](https://github.com/ArduPilot/ardupilot/files/6733290/00000001.BIN.txt)
renamed to txt to attach

**Comment by Hwurzburg** [comment]
this does not happen with Copter only QuadPlane

**Comment by lthall** [comment]
![image](https://user-images.githubusercontent.com/100896/125077733-93bfc400-e100-11eb-809b-ddfb83b7403e.png)

The yaw rate has been commanded.

I will close this for now. Please open it again if we have a log showing the problem with the yaw stick in the neutral position.

**Comment by lthall** [comment]
Sorry my bad, this isn't associated with the yaw rate reset issue. This is caused by this line here that sets yaw rate to zero with zero throttle:
https://github.com/ArduPilot/ardupilot/blob/b8e934ccf122dcc5e10cce2953f4bd9d280c9023/ArduPlane/quadplane.cpp#L1600

So the question is, is this the intended behaviour.

**Comment by Hwurzburg** [comment]
this was the one that @tridge said we should try qualifying with if the descent rate was => max loiter Z speed, to not zero yaw....remember the landing detection discussion during the dev call?..on my list to try to do

**Comment by IamPete1** [comment]
https://github.com/ArduPilot/ardupilot/pull/18021 has been merged, is that a sufficient fix?

**Comment by Hwurzburg** [comment]
yep
