### ISSUE TITLE
AP_UAVCAN: Problem in BatteryInfoAux dsdl message

### ISSUE THREAD

**Issue by ZLL6** [ArduPilot/ardupilot#17897]
Question 1: In the file 1092.BatteryInfo.uavcan
I found that float16 remaining_capacity_wh # [Watt hours] Will be increasing during charging
float16 full_charge_capacity_wh # [Watt hours] Predicted battery capacity when it is fully charged. Falls with aging
The units of remaining_capacity_wh and full_charge_capacity_wh are Wh. Wh will produce a larger error. My suggestion here is to use Ah.
Question 2: In the 1091.CircuitStatus.uavcan file
In line 13 uint8 ERROR_FLAG_UNDERCURRENT = 8; What is the concept of undercurrent? The battery industry does not have this concept. I don’t know if I can explain what it means.

**Comment by IamPete1** [comment]
Unfortunately we cant really change messages no devices are out in the wild. You could add a new message with the changes you need, but then other device would also have to add the same message. 

This is not really the best place for issues related to the UAVCAN dsdl, the AP discord is a better place for help, we have a canbus channel. https://discord.gg/E6Dh2tv8
