### ISSUE TITLE
About the communication function between the flight controller and the battery device

### ISSUE THREAD

**Issue by ZLL6** [ArduPilot/ardupilot#17898]
I have a set of communication protocols between the flight controller and the battery equipment for reference. I hope to promote the unification of the communication between the battery and the flight controller as soon as possible.

[BMS-6S_CAN_Communication.docx](https://github.com/ArduPilot/ardupilot/files/6732264/BMS-6S_CAN_Communication.docx)

**Comment by ZLL6** [comment]
https://github.com/ZLL6/Communication-protocol-between-battery-and-flight-controller/blob/main/BMS-6S_CAN_Communication.docx

**Comment by IamPete1** [comment]
Your best bet is to open a PR over on our UAVCAN repo, https://github.com/ArduPilot/uavcan

Feel free to drop in to the CANBUS channel on discord for help. https://discord.gg/E6Dh2tv8
