### ISSUE TITLE
When using two different airspeed sensors,airspeed sensors 1 cannot get the proper ratio

### ISSUE THREAD

**Issue by cuhome** [ArduPilot/ardupilot#17919]
I used two different airspeed sensors (MS4525 and MS5525); MS4525 is airspeed sensor 0 and MS5525 is airspeed sensor 1; after turning on the automatic calibration airspeed sensor, after the flight, I found that the MS5525 did not get a suitable ratio.
This is the flight log:
[flight log](https://drive.google.com/file/d/1S6HTSU1-Nx9ihc6xXqQOVaAHtXfMmFXw/view?usp=sharing)

**Comment by IamPete1** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/20772
