### ISSUE TITLE
Plane: Training mode wrong "Pitch/Roll not neutral" message when trying to arm 

### ISSUE THREAD

**Issue by Rolf-G** [ArduPilot/ardupilot#17925]
## Bug report

**Issue details**

When trying to arm in Training mode, this does not succeed, since "PreArm: Pitch (RC2) is not neutral" and
"PreArm: Roll (RC1) is not neutral" messages appear. although RC1/RC2 are neutral in the DZ area. 
Arming in other modes works.

**Version**
Ardupilot 4.1.0beta2

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
glider

**Hardware type**
Matek F405 Wing

**Logs**
Log can be uploaded if needed
![Training](https://user-images.githubusercontent.com/15328249/124362101-4ab8cd00-dc33-11eb-999d-a5d62e62c147.JPG)

**Comment by rmackay9** [comment]
Thanks for this.  By the way, I think in general it is best to report issues with the beta in the beta testing thread here: https://discuss.ardupilot.org/c/arduplane/plane-4-1/160.
