### ISSUE TITLE
fix handling of lidar I2C nack 

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#1793]
the ll40ls lidar sometimes fails, possibly due to not correctly handling I2C nack responses. We need to investigate and fix

**Comment by rmackay9** [comment]
I think this is a duplicate of this existing issue.  https://github.com/diydrones/ardupilot/issues/1770
I've closed the other one.

**Comment by magicrub** [comment]
is this considered done?

**Comment by Naterater** [comment]
Might this be fixed with recent PR's such as https://github.com/ArduPilot/ardupilot/pull/9794?

**Comment by IamPete1** [comment]
I'm going to close. Please re-open if this is still a problem.
