### ISSUE TITLE
Copter: 4.1 is not ignoring pilot yaw during takeoff

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#17951]
Copter-4.1 adds a GUID_OPTIONS parameter that includes a bit to ignore pilot input.  This is exposed to the rest of the vehicle code using the ModeGuided::use_pilot_yaw() method but this is not used in ModeGuided::takeoff_run() probably because this makes use of the more general "auto_takeoff_run()".  We will likely need to extend auto_takeoff_run to accept an "ignore_pilot_yaw" boolean argument (perhaps default it to false).  I suspect that ModeAuto may also require this change (but I haven't checked).

**Comment by Gone4Dirt** [comment]
Was this issue created as a feature request?  I am just checking because we are going to be changing the expected behaviour for users who have already used this and there may be some users who reposition yaw/heading on takeoff but have it switched off in the rest of the flight.

**Comment by rmackay9** [comment]
@Gone4Dirt,

Guided mode's "ignore pilot input" feature is new for 4.1 but it is slightly incomplete because it doesn't cover the takeoff.
