### ISSUE TITLE
[Plane] No servo control when in Initializing mode

### ISSUE THREAD

**Issue by giacomo892** [ArduPilot/ardupilot#17966]
## Bug report

Pilot should have control of surfaces if the plane reboots midair (brownout?) and the gyro cannot calibrate.

**Version**
Plane 4.1 (master)

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
https://github.com/ArduPilot/ardupilot/issues/10128

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/10128
