### ISSUE TITLE
Mamba f405 basic MK3 support

### ISSUE THREAD

**Issue by FairyTalesl** [ArduPilot/ardupilot#17989]
I want Ardupilot for Mamba f405 basic Mk3 board. The previous Mk2 version of this card is supported. Barometer is added in Mk3 version but no Ardupilot software. Can you help me with these with a little touch to the Mk2 software?

https://www.diatone.us/collections/basic/products/mamba-basic-f405-mk3-40a-6s-8bit-flight-controller-stack

**Comment by tenten8401** [comment]
Working on it right now for one of my quads, in the 20x20 version which uses the same target :)
![F405 Basic MK3.5](https://cdn.discordapp.com/attachments/674039678982422579/863578877028728852/IMG_20210710_203321.jpg)
If you could help me test once I get an initial hex built that'd be great

**Comment by FairyTalesl** [comment]
Ok I'm ready to test I'm looking forward to the hex file

**Comment by tenten8401** [comment]
@FairyTalesl this hex should work :)
Based on copter 4.1
[arducopter.zip](https://github.com/ArduPilot/ardupilot/files/6797000/arducopter.zip)
You may or may not have to use mavproxy to change frame_class to 1 before it will work. Try it and see.
![image](https://user-images.githubusercontent.com/6174343/125197916-a84daa80-e22d-11eb-9c23-8b73b99da779.png)
![image](https://user-images.githubusercontent.com/6174343/125197971-e0ed8400-e22d-11eb-8bf4-65626ba1ec9c.png)

**Comment by tenten8401** [comment]
Actually, use this one instead. Just fixed gyro yaw rotation issue
[arducopter_with_bl.zip](https://github.com/ArduPilot/ardupilot/files/6797035/arducopter_with_bl.zip)
