### ISSUE TITLE
No GPS telemetry data in passthrough protocol via FPORT

### ISSUE THREAD

**Issue by Seeelefant** [ArduPilot/ardupilot#17997]
## Bug report
Currently I do not get GPS sensor telemetry data in passthrough protocol via FPORT, however all other 14 sensors. In Missionsplanner 21 sats are shown.
![IMG_2189](https://user-images.githubusercontent.com/30323691/125198880-10b77e80-e264-11eb-8ce4-8f9c811cf174.jpg)
![IMG_2190](https://user-images.githubusercontent.com/30323691/125198905-22008b00-e264-11eb-96cc-8a8b214ec7ae.jpg)
![IMG_2188](https://user-images.githubusercontent.com/30323691/125198889-19a85000-e264-11eb-8c58-4808a8694941.jpg)

**Issue details**

_Please describe the problem_

**Version**
Copter 4.1.0-beta5 30-Jun-2021

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X4

**Hardware type**
Pixracer/FrSky R-XSR via FPORT/Taranis XD9+
**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
@yaapu Another one in your area, I'm not even sure if this is expected to work?

**Comment by yaapu** [comment]
@Seeelefant  missed this one, sorry.

in fport GPS would be the ONLY sensor you shoud get, are you running my script?

**Comment by Seeelefant** [comment]
Dear @yaapu, yes I am running your script. Finally got this working by using a 3,9k pull-up resistor.

**Comment by yaapu** [comment]
great news! glad you got iy working!
