### ISSUE TITLE
Log file date/time 'properties' does not respect BRD_RTC_TZ_MIN

### ISSUE THREAD

**Issue by andypnz** [ArduPilot/ardupilot#18016]
## Bug report

**Issue details**

When a log file is written to SD card, the date/time properties of the file do not respect BRD_RTC_TZ_MIN

(the date/time data inside the file do reflect BRD_RTC_TZ_MIN)

**Version**
4.1.0 master

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Wing

**Hardware type**
KakuteF7

**Logs**
![file-info](https://user-images.githubusercontent.com/11356342/125695648-ee5845b3-27ea-4c86-b5e6-0ba7689b3e7a.jpg)

**Comment by vierfuffzig** [comment]
@andypnz afaik as for now the onboard OSD clock panel is the only caller to the get_local_time method.

**Comment by vierfuffzig** [comment]
i‘ll close this as log time stamps in UTC is desired behavior. feel free to comment and reopen if required.
