### ISSUE TITLE
SITL: add backtrace output when exception occurs

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1806]
SITL is more strict about floating point exceptions (and other types of exceptions) meaning it can abort the testing with an "ERROR: Floating point exception - aborting".

It would be convenient if the line number where the failure happened was displayed.

**Comment by IamPete1** [comment]
You can get this with `-D -G`  I think that is sufficient?

**Comment by IamPete1** [comment]
Please re-open if you think the current options are not sufficient
