### ISSUE TITLE
AP_Viso: add MYNT EYE Standart (no IR) support

### ISSUE THREAD

**Issue by framosnt** [ArduPilot/ardupilot#18074]
## Feature request

I like have a library to use MYNT EYE Standart ROS camera to use in Ardupilot  !

https://www.mynteye.com/products/mynt-eye-stereo-camera?variant=13183676973079

**Platform**
[  ] All
[  ] AntennaTracker
[x  ] Copter
[x ] Plane
[x  ] Rover
[  ] Submarine

**Additional context**

**Comment by rmackay9** [comment]
Thanks for the request.  

This doesn't actually require any ardupilot development I think and we have this existing issue here https://github.com/ArduPilot/ardupilot/issues/16632 so if it's OK I think I will close this item.
