### ISSUE TITLE
Tools: add auto test to ensure do-change-speed mission commands are not broken (again)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#18078]
It seems that in Copter-4.1 we've broken support for do-set-speed mission commands and possibly immediate commands during auto missions.  @lthall and I think it is broken from inspecting AC_WPNav::update_track_with_speed_accel_limits and AC_WPNav::set_speed_xy which don't seem to be updating the position controller with the new speed limits.

**Comment by peterbarker** [comment]
arducopter.py now contains a `DO_CHANGE_SPEED` autotest.
