### ISSUE TITLE
Please add date panel on an OSD display

### ISSUE THREAD

**Issue by ninja-zx11** [ArduPilot/ardupilot#18124]
## Feature request

I would like to request a feature to add date panel on an OSD screen. There was some work done by Basti here:

https://github.com/ArduPilot/ardupilot/pull/12741

**Comment by IamPete1** [comment]
https://github.com/ArduPilot/ardupilot/issues/12706

**Comment by IamPete1** [comment]
Closing in favor of https://github.com/ArduPilot/ardupilot/issues/12706
