### ISSUE TITLE
Copter: Add parameter to disable surface tracking.

### ISSUE THREAD

**Issue by zhouzhiwen2000** [ArduPilot/ardupilot#18165]
## Feature request

**Is your feature request related to a problem? Please describe.**
I am using the drone indoors and I am using the rangefinder as the EKF altitude source. I don't want the surface tracking feature enabled to mess with the target ALT. However, in order to disable it, I have to assign a switch just for this. Is it possible to add an option for surface tracking in the parameters?

**Describe the solution you'd like**
An option for surface tracking in the parameters.

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by shiv-tyagi** [comment]
Hey! I tried to work on this issue. I added a parameter for the same and used it to initialise the surface property of surface tracking class. Please review if I did it correctly.

**Comment by zhouzhiwen2000** [comment]
Maybe start a pull request? The code looks fine to me, but I myself is new to ardupilot code.

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/18716
