### ISSUE TITLE
Plane new land flight mode

### ISSUE THREAD

**Issue by mirko91** [ArduPilot/ardupilot#1819]
I'm thinking about a new Land flight mode that will work the following way:
-one parameter to set if the landing spot will be the same as the home location or a new one
-if it is the same as the home the plane will do 4 loiter turns at 40m AGL with the home on the centre like RTL and calculate the wind direction and fly 200m away from the spot and land against the wind
-else if the land location is not the home point it'll be the point where the mode will be triggered, than the land procedure will be the same as above

I think that with this method the landing will be more accurate and fully autonomous

**Comment by tridge** [comment]
Hi Mirko,
I think we need to first document and complete the DO_LAND_START support that was added recently. That isn't the same as what you propose, but it does offer a flexible way of setting up auto lands.
I'll add this as something to be reviewed for 3.2.2
Cheers, Tridge

**Comment by mirko91** [comment]
Thanks Tridge, 
Really appreciate what the APM team is doing! Looking forward to see what DO_LAND_START is capable of. Cheers!

**Comment by Naterater** [comment]
Landing is a part of AUTO mode and has been fully implemented and mostly documented.
