### ISSUE TITLE
EKF3: yaw source can only be set to GSF a few times (see EK3_GSF_RST_MAX param)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#18200]
In Copter-4.1 (and on other vehicles), the EK3_SRCx_YAW parameters along with source switching can be used to change the active yaw source inflight.  GSF is one of the possible sources but (probably because GSF was initially implemented only for emergency situations) the yaw source can only be switched to GSF a few times based on the EK3_GSF_RST_MAX parameter.

We should probably change this so that the parameter is not used when the user proactively switches the source.

This issue is discussed here in the Copter-4.1 forums: https://discuss.ardupilot.org/t/loss-of-correction-after-switching-couple-times-between-yaw-compass-source-and-gsf-source/72687/18

**Comment by peterbarker** [comment]
A fix for this has been merged into master: https://github.com/ArduPilot/ardupilot/pull/18225

That PR has been marked as needing backport, so I think we can close this issue now.
