### ISSUE TITLE
A widely used standard UAV smart battery UAV can communication protocol

### ISSUE THREAD

**Issue by ZLL6** [ArduPilot/ardupilot#18260]
Hope to be promoted
[https://discuss.cubepilot.org/t/standard-uav-intelligent-battery-uavcan-communication-protocol/6986](url)

**Comment by peterbarker** [comment]
Insufficient information; link appears to have been killed on the cubepilot forums for whatever reason.

Document in the forum post is also garbage AFAICS.

**Comment by peterbarker** [comment]
Please reopen with more information.
