### ISSUE TITLE
from_rotation_matrix()

### ISSUE THREAD

**Issue by apm0x400** [ArduPilot/ardupilot#18359]
Dear friend:
I thinks from_rotation_matrix() comment is misunderstanding。
 ardupilot/libraries/AP_Math/quaternion.h   Line70

` // return the rotation matrix equivalent for this quaternion
    void		from_rotation_matrix(const Matrix3<T> &m);`
this should return quaternion equivalent for this rotation matrix

**Comment by peterbarker** [comment]
@apm0x400 It could be better.  Check the linked PR, please.

**Comment by apm0x400** [comment]
OK,Thanks,also need to change libraries/AP_Math/quaternion.h

**Comment by peterbarker** [comment]
> OK,Thanks,also need to change libraries/AP_Math/quaternion.h

Fair point, done.

There are many other descriptions in that file that could do with some help, however.

Feel free to raise PRs to fix this sort of thing rather than just raising issues - its not that much harder :-)
