### ISSUE TITLE
STIL in Mac OS X 10.10 

### ISSUE THREAD

**Issue by capaulson** [ArduPilot/ardupilot#1838]
I wanted the ability to run flight sims in the field (concurrent with real flights) and set about trying to run this natively on 10.10. I encountered five issues in the process of getting the code running, and thought I would submit  a bug report. It would be great to have a true cross-platform STIL capability. 

sim_vehicle.sh script issues:
1) the default OS X readlink has a truncated set of command line options. The '-e' is the offender here. For mac, install coreutils from HomeBrew and use greadlink instead. greadlink has equivalent functionality to the linux version. 

2) For killall, the '-q' command line argument isn't supported in Mac OS X, works fine if omitted. This option specifies a quite output. 

3) The script assumes ArduPlane.elf lives in /tmp/ArduPlane.build. However, the actual location on mac is in /var/folders/(some lengthy path). I haven't figured out where this path came from, so for now, I just copied the directory to /tmp.

Source Code Issues:
1) feenableexcept not supported by mac. I haven't found a good solution to this yet. For now, I've commented out lines 212-216 of ardupilot/libraries/AP_HAL_AVR_SITL/Scheduler.cpp.

2) ArduPlane.elf doesn't accept any parameters, claims they're all 'unknown parameters.' Still working on why this is the case.

These changes have made everything up to sim_vehicle.sh -w work.

I hope these observations help anyone trying to STIL in Mac.

**Comment by peterbarker** [comment]
SITL works on MacOSX, which is nice.
