### ISSUE TITLE
OSD: var_info2 elements parameters display on OSD{2,3,4} even if they are disabled

### ISSUE THREAD

**Issue by giacomo892** [ArduPilot/ardupilot#18418]
On master, I have OSD screens 2 3 4 disabled:

```
OSD2_ENABLE      0
OSD3_ENABLE      0
OSD4_ENABLE      0
```

But the LINK_Q parameters for those disabled OSDs still show as parameters while they shouldn't:

```
OSD2_LINK_Q_EN   0
OSD2_LINK_Q_X    1
OSD2_LINK_Q_Y    1
OSD3_LINK_Q_EN   0
OSD3_LINK_Q_X    1
OSD3_LINK_Q_Y    1
OSD4_LINK_Q_EN   0
OSD4_LINK_Q_X    1
OSD4_LINK_Q_Y    1
```

@tridge added a new bank of settings and perhaps he has overseen something in the process.

**Comment by hendjoshsr71** [comment]
Something similar reported on discord: 

@tridge 
I still see the LINK_Q params on master for disabled sensors in SITL?

![image](https://user-images.githubusercontent.com/69225461/159765933-17059525-7779-4be2-be47-7df65dd6b1c8.png)
