### ISSUE TITLE
default battery params not loading from ROMFS

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#18430]
PR #17820 broke the loading of default values for analog pins and multipliers from defaults.parm embedded in ROMFS. When booting a board that sets these pins in defaults.parm we see this on the console:
```
Ignored unknown param BATT_VOLT_PIN from embedded region (offset=234)
Ignored unknown param BATT_VOLT_PIN from embedded region (offset=234)
Ignored unknown param BATT_CURR_PIN from embedded region (offset=251)
Ignored unknown param BATT_CURR_PIN from embedded region (offset=251)
Ignored unknown param BATT_VOLT_MULT from embedded region (offset=273)
Ignored unknown param BATT_VOLT_MULT from embedded region (offset=273)
Ignored unknown param BATT_AMP_PERVLT from embedded region (offset=296)
Ignored unknown param BATT_AMP_PERVLT from embedded region (offset=296)
```
The problem is that the param sub-table isn't loaded when we load defaults.parm. This affects a lot of boards
example: CubeOrange: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm#L4
ping @hendjoshsr71

**Comment by tridge** [comment]
turns out it is not an issue. They do load when param sub-table is created

**Comment by hendjoshsr71** [comment]
Oh sorry I misunderstood what you meant here!

I thought the bug was about those warnings being generated in cases where
the param tree won't exist. And not wanting to bug the user for those.

 Not that the parameters weren't getting loaded when the analog monitor
does exist.
