### ISSUE TITLE
Timesync seems to return Tc1 as time since boot in nanoseconds

### ISSUE THREAD

**Issue by mcelhennyi** [ArduPilot/ardupilot#18474]
## Bug report

**Issue details**
I am having issues with time sync returning me a time since boot ns time as the tc1 time. Per the docs and mavros timesync implementation it seems like it should be the epoch time (?) of the AP. 

During my investigation into the cause of this I have noticed a issue that seems related to this as well. As you can see here:  
https://github.com/ArduPilot/ardupilot/blob/3d1ed896c850b33664e991d41ffb88b0960acc16/libraries/GCS_MAVLink/GCS_Common.cpp#L2835   
the function name is `timesync_receive_timestamp_ns` implying a nanosecond return. However if you look at the default return when fetching the system time is 0 it returns micros64.  
https://github.com/ArduPilot/ardupilot/blob/3d1ed896c850b33664e991d41ffb88b0960acc16/libraries/GCS_MAVLink/GCS_Common.cpp#L2839

So my question is, does the [AP_HAL::micros64()](https://github.com/ArduPilot/ardupilot/blob/8deeae7146147e0071b069aa2fe0f13559f9856f/libraries/AP_HAL_ChibiOS/system.cpp#L274) for ChibiOS send me the time since boot and only time since boot? Interestingly it seems like I am receiving a nano second version of time since boot on my timesync return messages. Which doesnt align with this function (I think?).

Also, what is this line doing:  
https://github.com/ArduPilot/ardupilot/blob/3d1ed896c850b33664e991d41ffb88b0960acc16/libraries/GCS_MAVLink/GCS_Common.cpp#L2837  
It seems like it should be fetching the epoch based current time if you go off the spec of the timesync message. I cannot quite understand what is going on [here](https://github.com/ArduPilot/ardupilot/blob/f71b951cb23adc3404259ac5003f12a2a0cf1cbd/libraries/AP_HAL_ChibiOS/UARTDriver.cpp#L1542) to know if there are any other issues that would cause what I am seeing.

**Version**
8deeae71 (my current rover firmware) & master (links ^ are for master)

**Platform**
[ X ] All

**Comment by peterbarker** [comment]
> I am having issues with time sync returning me a time since boot ns time as the tc1 time. Per the docs and mavros timesync implementation it seems like it should be the epoch time (?) of the AP.

Which documentation?  There's nothing in the XML.... in fact, we consider these values to be opaque, with their only utility being the round-trip time.

> During my investigation into the cause of this I have noticed a issue that seems related to this as well. As you can see here:
> 
> https://github.com/ArduPilot/ardupilot/blob/3d1ed896c850b33664e991d41ffb88b0960acc16/libraries/GCS_MAVLink/GCS_Common.cpp#L2835
> 
> the function name is `timesync_receive_timestamp_ns` implying a nanosecond return. However if you look at the default return when fetching the system time is 0 it returns micros64.

That value is multiplied by 1000 as part of the return.

> So my question is, does the [AP_HAL::micros64()](https://github.com/ArduPilot/ardupilot/blob/8deeae7146147e0071b069aa2fe0f13559f9856f/libraries/AP_HAL_ChibiOS/system.cpp#L274) for ChibiOS send me the time since boot and only time since boot? Interestingly it seems like I am receiving a nano second version of time since boot on 

time-since-boot.  In fact, given it is the round-trip-time which is important, the values can be considered opaque.

> my timesync return messages. Which doesnt align with this function (I think?).

It does :-)  It's *1000 in the return line.

> https://github.com/ArduPilot/ardupilot/blob/3d1ed896c850b33664e991d41ffb88b0960acc16/libraries/GCS_MAVLink/GCS_Common.cpp#L2837
 
> It seems like it should be fetching the epoch based current time if you go off the spec of the timesync message. I cannot quite understand what is going on [here](https://github.com/ArduPilot/ardupilot/blob/f71b951cb23adc3404259ac5003f12a2a0cf1cbd/libraries/AP_HAL_ChibiOS/UARTDriver.cpp#L1542) to know if there are any other issues that would cause what I am seeing.

This message is missing the usual verbiage around "epoch time if available, boot-time otherwise".  Given it is round-trip time which is interesting, its really neither here nor there.

The message you're after for setting the time is `SYSTEM_TIME` - which we should also be sending.  You need to combine it with the use of `TIMESYNC` to work out what you should roughly adjust it for (with the possible addition of the receive-time-constrain algorithm to tighten that estimate).

**Comment by mcelhennyi** [comment]
Thanks, I am blind and for some reason thought I saw 
`return AP_HAL::micros64();` not `ret = AP_HAL::micros64();`

Thanks for the response @peterbarker
