### ISSUE TITLE
Failsafe + DO_LAND_START

### ISSUE THREAD

**Issue by lcasassa** [ArduPilot/ardupilot#1849]
- Mission has a DO_LAND_START with a landing secuence.
- Failsafe on
- Plane changes to RTL after 20 segs
- *\* Plane hits Home point and switchs to AUTO mode where the DO_LAND_START is.
- Recovers from failsafe, plane will keep being in AUTO mode
- Failsafe on
- Plane will enter CICLE and then RTL and go pack to point **

Can we ignore the second failsafe and continue the landing auto mission?

**Comment by lcasassa** [comment]
Even more, if the mission has a DO_LAND_START, the plane changes from RTL to AUTO and we could get a failsafe in AUTO that will end on a RTL and restart the DO_LAND_START. So we would have a loop and the plane never landing.

Workaround would be to turn off the radio but on the landing this would be unsafe.

**Comment by lcasassa** [comment]
I was playing with the SITL trying to reproduce a crash I had and got to this problem.

**Comment by tridge** [comment]
I think we could definitely be smarter about this, though we'll need to think about the exact semantics. I'll add it as a 3.2.2 issue

**Comment by Naterater** [comment]
Implemented. See RTL_AUTOLAND parameter: 

![image](https://user-images.githubusercontent.com/35429159/49329554-42152d00-f546-11e8-8e8f-45fe287cee56.png)
