### ISSUE TITLE
FENCE_AUTOENABLE + DO_LAND_START

### ISSUE THREAD

**Issue by lcasassa** [ArduPilot/ardupilot#1850]
With FENCE_AUTOENABLE = 1, only a LAND will disable the fence.

After a RTL mode, it switches to AUTO mode where the DO_LAND_START is and the waypoints could be out of the fence. It would be good to have a disable fence command or simply disable it for all the DO_LAND_START mission.

**Comment by tridge** [comment]
yes, good point, thanks! I'll add it for 3.2.2

**Comment by Naterater** [comment]
Is there still no check for this? I don't recall, but there may be some sanity checks for waypoints outside of fences.

**Comment by IamPete1** [comment]
Looks like fence is now disabled for both VTOL landing and forward flight landings. I'm not sure it's really a good idea to disable the fence for the whole of a do land start, that should be inside the fence too surely?

**Comment by peterbarker** [comment]
> Looks like fence is now disabled for both VTOL landing and forward flight landings. I'm not sure it's really a good idea to disable the fence for the whole of a do land start, that should be inside the fence too surely?

Agreed.

Closing this now - if people can make a case for disabling all fences when landing, please re-open.
