### ISSUE TITLE
Build failed for waf copter

### ISSUE THREAD

**Issue by simon88** [ArduPilot/ardupilot#18549]
## Bug report

**Issue details**

I'am trying to build copter on Windows 10 env, I've followed this tutorial [https://ardupilot.org/dev/docs/building-setup-windows-cygwin.html#building-setup-windows-cygwin](url), but when I try to build with Waf I got an build failed. I've configured waf for CubeOrange `./waf configure --board CubeOrange` everyting works I got succes

**Version**
Windows 10

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Logs**

Checking for env.py
env added OPTIMIZE=-O2
env added WITH_FATFS=1
env added PROCESS_STACK=0x1C00
env added MAIN_STACK=0x600
env added IOMCU_FW=0
env added PERIPH_FW=0
env added HAL_NUM_CAN_IFACES=2
env added BOARD_FLASH_SIZE=2048
env added EXTERNAL_PROG_FLASH_MB=0
env appended CPU_FLAGS=['-mcpu=cortex-m7', '-mfpu=fpv5-d16', '-mfloat-abi=hard', '-DARM_MATH_CM7', '-u_printf_float']
env added CORTEX=cortex-m7
env added APJ_BOARD_ID=140
env added APJ_BOARD_TYPE=STM32H743xx
env added USBID=0x2dae/0x1016
env added BOOTLOADER_EMBED=1
env added FLASH_RESERVE_START_KB=128
env added FLASH_TOTAL=1966080
env added HAS_EXTERNAL_FLASH_SECTIONS=0
env added DEFAULT_PARAMETERS=/home/Quentin/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
env added CHIBIOS_BUILD_FLAGS=USE_FATFS=yes CHIBIOS_STARTUP_MK=os/common/startup/ARMCMx/compilers/GCC/mk/startup_stm32h7xx.mk CHIBIOS_PLATFORM_MK=os/hal/ports/STM32/STM32H7xx/platform.mk MCU=cortex-m7 ENV_UDEFS=-DCHPRINTF_USE_FLOAT=1
Padded 16 bytes for bootloader.bin to 17376
Embedding file bootloader.bin:/home/Quentin/ardupilot/Tools/bootloaders/CubeOrange_bl.bin
Embedding file hwdef.dat:/home/Quentin/ardupilot/build/CubeOrange/hw.dat
Embedding file io_firmware.bin:Tools/IO_Firmware/iofirmware_highpolh.bin
[807/810] Linking build/CubeOrange/bin/arducopter
[808/810] apj_tool build/CubeOrange/bin/arducopter
Loaded binary file of length 4076980
Setting defaults from /home/Quentin/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
Saved binary of length 4076980
[809/810] Generating bin/arducopter.bin
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/cygdrive/c/Program Files (x86)/GNU Tools ARM Embedded/6 2017-q2-update/bin/arm-none-eabi-objcopy -O binary /home/Quentin/ardupilot/build/CubeOrange/bin/arducopter /home/Quentin/ardupilot/build/CubeOrange/bin/arducopter.bin'

Waf: Leaving directory `/home/Quentin/ardupilot/build/CubeOrange'
Build failed
-> missing file: '/home/Quentin/ardupilot/build/CubeOrange/bin/arducopter.bin'

**Comment by IamPete1** [comment]
Jump on the discord for developer support, https://discord.gg/x6abtzm3

WSL is the goto for windows 10, should be easier to setup than cygwin. 

https://ardupilot.org/dev/docs/building-setup-windows10.html
