### ISSUE TITLE
AP_RangeFinder: handle lightware SF11 output of 130m on loss of signal

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#18602]
The lightware SF11C (at least) outputs 130m "on lost signal" so we should handle this in the AP_LightwareSerial driver.

Here's the relevant line in [the SF11 datasheet](https://www.documents.lightware.co.za/SF11%20-%20Laser%20Altimeter%20Manual%20-%20Rev%2010.pdf):

![image](https://user-images.githubusercontent.com/1498098/132422655-007e6212-ffd5-4c69-a37d-0eb4f09885a0.png)

As mentioned by @wynn4 this issue https://github.com/ArduPilot/ardupilot/issues/7756 if we don't handle this out-of-range value then it can incorrectly be summed with good values and lead to an incorrect result.

Unfortunately this means we need to go through all the lightware datasheets for other products that use the same serial protocol to see if they are consistent (I'll bet they're not!).

**Comment by Shyam-Sunder-saini** [comment]
i want work on it

**Comment by shiv-tyagi** [comment]
@Shyam-Sunder-saini Are you still working on this issue?

**Comment by Shyam-Sunder-saini** [comment]
Yes why not i am super excited for this

**Comment by shiv-tyagi** [comment]
@rmackay9 I would like to work on this issue. I have gone through documentation of almost all Lightware lidars and unfortunately I did not find any mention of "on lost signal" in any of the documentations except the one for SF11. I doubt if this "on lost signal" thing is specific for SF11 (being a newbie, I am not much sure about it). I propose to add parameter in Lightware library that helps us to differentiate between different models and handle 130 m output for SF11. Adding parameter will also help us to implement other model specific features (if any) in future. Your views about it?

**Comment by shiv-tyagi** [comment]
After a lot of searching, I found out following things:-
- "on signal lost" outputs different values for different models.
- On some models this setting can be changed, on some it can't.

We can either add a parameter to differentiate between different models and handle settings for that lidar or we can ask lidars about their models using commands and then handle the behaviour for each model.

Currently, I don't have any hardware to test my results. This would make it difficult for me to fix this. If someone want to work on this issue, here is the reply of a mail I wrote to lightware customer support which might help.
<img width="786" alt="Screenshot 2021-10-19 at 4 23 05 PM" src="https://user-images.githubusercontent.com/67995771/137896185-0f7bd932-d8b3-40c8-84e8-80499f07598e.png">
This tells about other lidar models which have this setting (apart from SF11).

**Comment by wynn4** [comment]
@shiv-tyagi Thank you for providing this info from LightWare. I have some hardware (although only one of these rangefinders--the SF11/C) and so I'm going to take a whack at addressing this issue.

My thinking is that we avoid extra talking back/forth with the rangefinder, and also avoid adding an extra parameter. Instead, we do some extra checks using these known "lost signal" flags. I've implemented this and done a successful build of my solution. I'll test soon using the hardware I have, and if successful, I'll submit a PR.

**Comment by wynn4** [comment]
PR #19191

**Comment by hendjoshsr71** [comment]
This was fixed with PR #19191.

Thank you @wynn4 !!
