### ISSUE TITLE
Plane recovered in inverted flight after a stall spin, FBWA flight mode - slow roll

### ISSUE THREAD

**Issue by dramida** [ArduPilot/ardupilot#18634]
I have a Believer 1960 twin motor, well tuned. After a **induced stall** in FBWA, **it recovered in inverted flight** and flew like this plunging to earth until I forcefully rolled right 180 degrees. Plane obeyed **roll command slowly**, it flew for a while in knife edge.
Happily it was 350m AGL when I start stall and recovered at 80m.
20 seconds of terror.
![spin recovery anormal](https://user-images.githubusercontent.com/7262167/132861547-a784be2d-3637-44aa-bca0-475d811ea369.jpg)

Flight was 41 min long, the issue is clearly visible at 18:47:10
Logs on the drop box here:
https://www.dropbox.com/sh/z31fwh8sgw4j2aq/AABPlImAwZGUy8e47La_RIefa?dl=0

**Comment by IamPete1** [comment]
AP was giving full aileron and full elevator, not very much more that it can do. 

![image](https://user-images.githubusercontent.com/33176108/132890295-13012447-974c-4aec-89a4-50e90edd9bea.png)

**Comment by IamPete1** [comment]
I don't think thinks is a bug, so I'm going to close, the forum is the the best place for advice on such things. https://discuss.ardupilot.org/
