### ISSUE TITLE
Enable gps based compass / heading estimation while disarmed

### ISSUE THREAD

**Issue by jaroszmm** [ArduPilot/ardupilot#18651]
## Feature request
Enable heading estimation based on GPS in planes with no compass at disarmed state
**Is your feature request related to a problem? Please describe.**
I noticed on OSD that the compass only starts showing correct heading when plane has been thrown and is flying. Before that it just rotates based on North set during power up.

**Describe the solution you'd like**
I believe if Ardu could estimate heading after power up it would help in auto takeoff modes to keep the takeoff line straight. By simply walking with the plane to the lauch place or just making a few steps it should be enough for the system to estimate the correct heading.

**Platform**

[  ] Plane

**Comment by IamPete1** [comment]
Try enabling the GSF. https://ardupilot.org/plane/docs/common-compassless.html#gsf
