### ISSUE TITLE
Rover: add mechanical brake support in rover 

### ISSUE THREAD

**Issue by stevefoxuk** [ArduPilot/ardupilot#18678]
Rover does not support a mechanical brake, this means vehicles running an IC engine have no braking option and electric vehicles which have a mechanical brake cannot make use of it.

Please add support for braking , I know others would like to see this feature too.

**Comment by rmackay9** [comment]
This is a duplicate of https://github.com/ArduPilot/ardupilot/issues/7040 so I will close this one as is our normal practice (oldest one remains)
