### ISSUE TITLE
Diatone Mamba F405 MK2 Support with Ardupilot// Autopilot

### ISSUE THREAD

**Issue by renzovidaurre** [ArduPilot/ardupilot#18675]
I had been working with Mamba F405 Mk2,the firmware that are i am using know is Ardupilot,but when i want to setup the motors output it doesn not spin.

**Comment by IamPete1** [comment]
The forum is the best place for such setup questions. Create a post over there with a details of the ArduPilot version, your ESC type, how they are connected and your params. https://discuss.ardupilot.org/

I'm sure you have found the wiki page for the Mamba https://ardupilot.org/copter/docs/common-mamba405-mk2.html
