### ISSUE TITLE
replace printf_P with print_P or println_P if possible

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1867]
There are many cases where we use printf_P(PSTR("blah")) but where we don't actually pass in any argument (like "%d").  In these cases we could replace the printf_P call with a print_P or println_P.

Similarly we could replace some instances of printf_P() with println_P() and remove the final "\n" from the provided string.

The prin_log_menu in Log.pde is a prime example of this.
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/Log.pde#L38

**Comment by OXINARF** [comment]
We don't have these methods anymore, it is all printf or vprintf now.
