### ISSUE TITLE
Rover: brushed bipolar motor is outputting SERVOx_MIN at startup instead of SERVOx_TRIM

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#18729]
This was raised as part of Rover-4.1.0 beta testing here: https://discuss.ardupilot.org/t/brushedbipolar-pwm-problem/76153

**Comment by IamPete1** [comment]
I cant reproduce on master, I don't see any path for the trim param to be changed. I could believe that were outputting normal PWM for a bit before switching to `BRUSHED_BIPOLAR`.

**Comment by IamPete1** [comment]
Its falling fowl of this trim set. https://github.com/ArduPilot/ardupilot/blob/d853d16c42acc21ce762a8db8299926f752b71a4/libraries/SRV_Channel/SRV_Channel_aux.cpp#L255
