### ISSUE TITLE
plane tailsitter reset yaw target can lead to large rates

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#18782]
As seen in #18778 a attitude_control->reset_yaw_target_and_rate() can lead to a very large rate demand in tailsitters. We need some way to constrain this.
That PR fixed it for the particular case of an VTOL_LAND, but it could still happen with other mode changes from fixed wing to a mode that uses QPOS_POSITION1
ping @lthall @IamPete1

**Comment by IamPete1** [comment]
Another report of this from @Hwurzburg 

https://discord.com/channels/674039678562861068/783141293445480470/942530685095272468
