### ISSUE TITLE
Problem at register_periodic_callback

### ISSUE THREAD

**Issue by hathach23** [ArduPilot/ardupilot#18791]
## Bug report

**Issue details**

_Please describe the problem_
I would like to report the problem. The function register_periodic_callback . As i tried to call it in my init()-function, the device could not be connected to the mission planer (wire connect) and if i removed it, the CubeOrange could be connected as usual

**Version**
_What version was the issue encountered with_
4.0.7

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
hex

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
CubeOrange

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
This is probably not the place to ask questions, maybe try on discuss or discord.

I don't fully understand the report but perhaps the issue is that you can only read and write to serial ports using the same thread that executed the "begin" on the serial port.
