### ISSUE TITLE
DJI-HDL SBUS baud fast protocol support

### ISSUE THREAD

**Issue by Luix333** [ArduPilot/ardupilot#18802]
Feature request

Hi, newbie here. I came this way from the ardupilot blog after being told this is the right place to ask people way smarter than me to add a new feature.

I noticed that, when using my DJI transmitter, I have to avoid using DJI's SBUS Baud Fast protocol since it isn't currently supported on Ardupilot. In Betaflight it can be enable through "set sbus_baud_fast = ON", but as far as I could see, this is not supported currently on Ardupilot.

**Describe the solution you'd like**

It's pretty simple really (to ask). I want to request support for DJI-HDL SBUS BAUD FAST protocol to be added to Ardupilot. 

According to someone on the blog, this should be "fairly trivial" to do (I assume he meant for someone far more smart and skilled than me) 

**Platform**
[ x ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by hendjoshsr71** [comment]
Link to the relevant ArduPilot Discuss post: [here](https://discuss.ardupilot.org/t/dji-hdl-protocol-in-ardupilot/76373)
Link to the relevant BetaFlight PR that added this feature: [here](https://github.com/betaflight/betaflight/pull/7881/files)

**Comment by peterbarker** [comment]
@Luix333 it would be nice if you could test the referenced PR to see if it Works For You(tm).
