### ISSUE TITLE
Plane: MIS_RESTART blocks RTL_AUTOLAND

### ISSUE THREAD

**Issue by lcasassa** [ArduPilot/ardupilot#1883]
With MIS_RESTART set to 1 will not work with RTL_AUTOLAND set to 1 and with a DO_START_LAND in the mission.

This is because, when it starts the landing sequence it enters AUTO mode and restarts to waypoint #1 instead of continuing the landing.

**Comment by lcasassa** [comment]
How about making a new mode like RTL_LAND? We could easily fix the issue where the failsafe kicks in while doing the landing sequence so that it does not restart the RTL/landing sequence (Issue #1849 ).

**Comment by aldofad** [comment]
Dear developers, 
has this issue been resolved?

Cheers,
aldo

**Comment by ClockeNessMnstr** [comment]
Also struggling with this today on plane. Will need to try and setup rst channel instead but it would be nice not to need an extra channel setup.

**Comment by ClockeNessMnstr** [comment]
> Dear developers,
> i see the issue is still open and I confirm it is present in Arduplane 4.0.2, just impacted during this days :)
> 
> Cheers,
> aldo

As a work around you should be able to set an extra channel to reset the auto mission If you have a channel available.

**Comment by IamPete1** [comment]
This should have been fixed by https://github.com/ArduPilot/ardupilot/pull/13652
I'm going to close this, if anyone can confirm its still a issue please re-open.
