### ISSUE TITLE
Arduplane 4.1.0 Parachute BUG

### ISSUE THREAD

**Issue by bugalaws** [ArduPilot/ardupilot#18843]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**

After I install the arduplane 4.1.0 the parachute is automaticaly deployed when we plug the battery or when we send the reboot comand via arduplane, this feature is great for some trouble in case the pixhawk got a unexpected reboot middle the flight,  but when i trying to deploy the parachute via RC doesn't work. 

In the messages I got :

04/10/2021 12:40:52 : ParachuteRelease LOW
04/10/2021 12:40:51 : ParachuteRelease HIGH

That is, the arduplane are receiving de parachute command but doesn't are release the servo.

**Version**
4.1.0

**Platform**
[  ] All
[  ] AntennaTracker
[ ] Copter
[ * ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Flying Wing

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Pixhawk Cube

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by tridge** [comment]
many thanks for this bug report! We have a fix here: #19282 
this fix will be in the 4.1.4 stable release, I expect within the next 2 weeks
