### ISSUE TITLE
disable stall prevention for ground testing of surface movement

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#1892]
users find it confusing that the surfaces don't move very far on the ground, which is caused by the stall prevention code

**Comment by magicrub** [comment]
Is_flying() may come in handy here.

**Comment by magicrub** [comment]
this seems simple to implement

**Comment by magicrub** [comment]
is this still valid? The surfaces move fine to me

**Comment by WickedShell** [comment]
I don't think this is still valid. I fly with STALL_PREVENTION 1, and on the ground I can get the surfaces to hit full travel limits that match the actual aircraft surface limits. Closing unless someone else feels differently.
