### ISSUE TITLE
AP_Baro: KellerLD Vented Gauge Offset Should Update

### ISSUE THREAD

**Issue by ES-Alexander** [ArduPilot/ardupilot#18968]
## Bug report

**Issue details**

The Vented Gauge type measures zero when pressure on both sides is equal. Currently the (enclosure internal pressure) offset is set to a constant value (standard atmospheric pressure at sea level), but it should actually be regularly updated (i.e. track the flight controller's absolute barometer), to handle changing pressure due to temperature etc.

This was brought up and discussed with @hendjoshsr71 [here](https://github.com/ArduPilot/ardupilot/pull/18010#pullrequestreview-739769560).

I'm planning to fix this, but it's in my TODO list as non-critical because at this stage there are no known users of vented-gauge KellerLD sensors (KellerLD is primarily (/only?) used by Sub at this point, which only uses the Sealed Gauge type). Vented Gauge was recently added as an option at initialisation because the rest of the sensor functionality is the same, and the gauge type is already being parsed from EEPROM.

**Version**

4.2.0 / `master` branch.

**Platform**
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[x] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

All/any

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

All/any

**Comment by hendjoshsr71** [comment]
Done! Thank you @shiv-tyagi !
