### ISSUE TITLE
Filter: Template class still poorly implemented and not compatible with the operators (vector)

### ISSUE THREAD

**Issue by dgrat** [ArduPilot/ardupilot#1897]
What's the reason to implement a filter class with a template argument when:

```
float           _base_value;
```

Additionally, the implementation of:
_base_value = _base_value + _alpha \* ((float)sample - _base_value);
will not work with a vector. Change pls the order, to make it compatible with the operator implementation of your vector class.

**Comment by peterbarker** [comment]
Filters are all templated now, and we use several with vectors.
