### ISSUE TITLE
GCS_Console.cpp: backend_read and backend_write are called but not defined anymore.

### ISSUE THREAD

**Issue by dgrat** [ArduPilot/ardupilot#1899]
backend_read and backend_write are called but not defined anymore.
This leads to compiler error.

**Comment by peterbarker** [comment]
Nobody appears to have been bothered by this.  Should we fix it or remove GCS_Console?

**Comment by tridge** [comment]
i think we should removed GCS_Console

**Comment by magicrub** [comment]
result of dev-call discussion: @peterbarker will "Nuke GCS_Console from Orbit"

**Comment by dgrat** [comment]
Wow, this post is nearly three years old :D

**Comment by peterbarker** [comment]
On Tue, 9 Jan 2018, Daniel Frenzel wrote:

> Wow, this post is nearly three years old :D

All issues address in a timey manner ;-)
