### ISSUE TITLE
Copter 4.1 be able to set 34° virtual angle on Heli H4 swashplate 

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#19000]
Hello,

I don't find param for set the virtual angle on H4 swashplate.

There  is only 45 or 90° on H_SW_TYPE  param, but my heli is 34°....

I also found param: H_SW_H3_SV1_POS (AP_MotorsHeli_Single): H3 Generic Servo 1 Position and the same params to set 3 servo on H3 swashplate, but I'm in H4 swashplate with 4 servos......

can I use theses params? 

I need help to set my swash plate.

Thank you ardupilot team.

**Comment by rmackay9** [comment]
@bnsgeyer is probably best placed to answer this.
By the way, this should probably be asked in the TradHeli forum.  Be try to keep this issues list limited to known bugs or enhancements.  Sorry to be strict but if we're not then it turns into a support forum and we lose track.
