### ISSUE TITLE
Search for and remove empty constructors

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#19026]
## Cleanup request

Many places in the code we declare constructors which do nothing except call their parent-class constructor with all the same arguments, like this:

```
MyClass::MyClass(OtherClass &otherclass, uint8_t myint) :
   MyParentClass(otherclass, myint)
{ }
```

C++ has the `use` keyword which allows us to remove these in favour of saying, "just use this code over here:
```
use MyParentClass::MyParentClass;
```

https://github.com/ArduPilot/ardupilot/pull/19025 shows a PR removing these in the GPS library.

The WheelEncoder_Quadtrature class at time has these in them:

```
// constructor
AP_WheelEncoder_Quadrature::AP_WheelEncoder_Quadrature(AP_WheelEncoder &frontend, uint8_t instance, AP_WheelEncoder::WheelEncoder_State &state) :
    AP_WheelEncoder_Backend(frontend, instance, state)
{
}
```

In addition, sometimes the constructors are doing initialisation of members that can be done in the class definitions themselves - so the body of the constructor can be trivially made empty.

The request is that the code is search for all places where we have these empty constructors and replace them with `use`.  It saves bytes and removes code.

**Comment by hendjoshsr71** [comment]
Just an additional note for anyone else that looks at completing parts of this issue. 

There is a possible bug in G++6 that doesn't allow for example the changes in #19085 & #19087 to compile. G++6 is the older compiler for flight hardware that we need to still support.  The current arm compiler we use is G++10.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67054

**Comment by peterbarker** [comment]
I think we can call this issue "done" - now just a matter of stopping more creeping in :-)

Thanks @Divyateja04 !
