### ISSUE TITLE
AP_Arming: pre-arm checks of rangefinder should trigger if "no data"

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#19036]
The current arming checks for rangefinder only check if the driver has been loaded but they should also detect whether the rangefinder is providing data by check that the status is *not* No data.

Below is a copy-paste of the current check as a reference.

```
bool RangeFinder::prearm_healthy(char *failure_msg, const uint8_t failure_msg_len) const
{
    for (uint8_t i = 0; i < RANGEFINDER_MAX_INSTANCES; i++) {
        if (((Type)params[i].type.get() != Type::NONE) && (drivers[i] == nullptr)) {
          hal.util->snprintf(failure_msg, failure_msg_len, "Rangefinder %X was not detected", i + 1);
          return false;
        }
    }

    return true;
}
```

**Comment by shiv-tyagi** [comment]
@rmackay9 I would love to work on this issue.
Should we trigger failure for all rangefinder status except good (i.e., NoData, NotConnected, OutOfRangeHigh and OutOfRangeLow)? We expect no good data from RF for all such status.

**Comment by rmackay9** [comment]
@shiv-tyagi,

Sure, go for it.  I think the arming check should only trigger if the status is "NoData".  I think it would be too annoying to have it trigger for the other statuses because on a copter, for example, the legs might not be long enough to allow the range finder to get to a "Good" status while it is on the ground.

**Comment by rmackay9** [comment]
Resolved by the above linked PR, txs!
