### ISSUE TITLE
Add more verbosity to lua scripting

### ISSUE THREAD

**Issue by drtrigon** [ArduPilot/ardupilot#19041]
## Feature request

When running lua scripts it's sometimes hard to figure out whats going on.

I thinks it would be helpful to get some info on scripts that stoped due to any reason. Also getting some hint on what the reason or cause for script termination was.

Something like `LUA: Script 'blabla.lua' stopped execution. Reason: ...` would be very helpful. Reasons might include "Regular Termination", "Not enough memory", "Syntax error", etc.

I am not aware whether `SCR_DEBUG_LVL` already provides such a behaviour but as I cannot find a documentation on options and values available in `SCR_DEBUG_LVL` I cannot figure that out by myself.

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by drtrigon** [comment]
Ok, this is a bit embarrassing to have opened this issue for nothing. You are right: the messages are there! This is good!

I tested it in detail and got the same message as you. Also a message for not enough memory was raised. However it might be very early in the boot process and thus can easily be missed (at least by me as it seems). So this is ok for me. (except the fact that I should may be go to the doctor ;)

However may be we can still make some good out of this issue report - there are 2 things I noted:
* `SCR_DEBUG_LVL` is not documented: what do they different levels mean?
* the `no scripts to run` messages spam/flood the system: could that be changed? e.g. an option to disable them? or reduce the interval?

**Comment by IamPete1** [comment]
For `no scripts to run` just set `SCR_DEBUG_LVL` to 0 and it will go away. 

Your right, we should document it better. 

On master you will see the error messages re-printed every 10 seconds 10 times, so they should be much harder to miss. 

Thanks for following up, I'm going to close this.

**Comment by drtrigon** [comment]
> For `no scripts to run` just set SCR_DEBUG_LVL to 0 and it will go away.

Yes, but I don't like this solution as I still would like to get other messages. Also `no scripts to run` is useful, but not that often. I would like it to be handeled like the other error messages. (see below)

> On master you will see the error messages re-printed every 10 seconds 10 times, so they should be much harder to miss.

That is nice!
