### ISSUE TITLE
BDSHOT label/firmware and DSHOT DMA issues

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#19043]
Topic for discussion...given the issues with BDSHOT, that firmware for certain boards are not backward compatible, its been suggested that this feature be labelled EXPERIMENTAL in wiki and perhaps firmware be segregated somehow....
Also, users are finding that DSHOT does not work on all outputs....because they do not get DMA assigned...its been suggested that a pre-arm failure for those cases is needed..
[  ] All
[  ] AntennaTracker
[x] Copter
[x] Plane
[x] Rover
[  ] Submarine

**Comment by auturgy** [comment]
Suggest close
