### ISSUE TITLE
Copter: Land initiated from a failsafe should hold alt for 10sec, also recover if failsafe clears

### ISSUE THREAD

**Issue by govsux** [ArduPilot/ardupilot#1905]
Anytime the code sees a problem and initiates land mode it instead goes in alt hold for 10 seconds. If the problem has gone away continue in whatever mode it was in. If the problem persists then lands.

**Comment by rmackay9** [comment]
It has a 4 second delay at the moment by the way.  It will not recover though

**Comment by lthall** [comment]
old
