### ISSUE TITLE
SIM_RC_FAIL = 2 does not trigger RC failsafe

### ISSUE THREAD

**Issue by shiv-tyagi** [ArduPilot/ardupilot#19119]
## Bug report

**Issue details**

`SIM_RC_FAIL` parameter when set to 2 (i.e., SITL_RCFail_Throttle950) does not trigger throttle failsafe. 

Steps to reproduce:
- param set FS_THR_VALUE 960
- param set FS_THR_ENABLE 1
- param set SIM_RC_FAIL 2
- arm throttle (to confirm if arming checks fail because of below acceptable throttle)
<img width="1440" alt="Screenshot 2021-11-02 at 10 45 49 PM" src="https://user-images.githubusercontent.com/67995771/139914006-8895a3cf-253a-42fb-a9f9-b343a5ccc69d.png">

**Version**
master

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by rmackay9** [comment]
I did a quick test with master Copter and it works OK.
![image](https://user-images.githubusercontent.com/1498098/139999868-979a000d-7c5b-46b0-9f87-a09b5ced3d56.png)

**Comment by shiv-tyagi** [comment]
@rmackay9 I tested it again and found one interesting thing. It does not work if you set guided mode and try to takeoff with `takeoff` command but it works when we takeoff by manually setting throttle channel to some value in a mode like loiter (maybe this is how you tested it).
I am not sure if we need to worry about this behaviour.

**Comment by rmackay9** [comment]
@shiv-tyagi,

This is probably the expected behaviour but maybe have a peek at the FS_OPTIONS parameter.
