### ISSUE TITLE
Deinitialization in Linux

### ISSUE THREAD

**Issue by staroselskii** [ArduPilot/ardupilot#1914]
Linux boards launch APM as a separate process that can eventually be killed. Thus, I believe, some clean-up work upon termination is needed. All modules do have `init()` method but they lack a `deinit()`. 
It's relatively easy to add `deinit()` to libraries. But I don't see a clean way to call it in the vehicle specific code.  Do you have any suggestions about the proper implementation of deinitialization? 
It doesn't really make sense on old non-Linux boards, though.

**Comment by magicrub** [comment]
I'm not a linux master, but for what you're looking for I would point at
adding a decontstructor in HAL_Linx_Class.cpp which could call your new
function deinit.

**Comment by staroselskii** [comment]
Fixed with #5090
