### ISSUE TITLE
Add autotesting for Devo telemetry

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#19174]
## Feature request

**Is your feature request related to a problem? Please describe.**
Devo Telemetry is not tested in autotest

**Describe the solution you'd like**
Testing of Devo telemetry by adding a simulator similar to frsky, crsf, ltm etc

Basically a clone of the ltm telemetry test, I would imagine.

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by hendjoshsr71** [comment]
Fixed in the linked PR. Thanks @shiv-tyagi !
