### ISSUE TITLE
[VTOL] Q_TAILSIT_GSCMSK it also acts on the PIDs of the Plane 

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#19175]
Tested with the current master in Realflight with CAT Tailsitter, with also PR 19171. 
This scaling should in my opinion only work for the copter part, not performing any scaling on the plane whatever bitmask we choose, but I have evidence that something touches instead.
In the attached log I make changes to this parameter during a simple automatic mission.
Roll attitude of the plane without scaling:

![immagine](https://user-images.githubusercontent.com/3864712/140610015-a16961fe-9c15-4bc8-91ae-7de3036d547e.png)

With Q_TAILSIT_GSCMSK set to 4:

![immagine](https://user-images.githubusercontent.com/3864712/140610021-0cb466d3-5836-4813-9cd0-1068e7bb00af.png)

**Comment by robustini** [comment]
The log: https://drive.google.com/file/d/1EqvC65qi4Ipb0kOeNwc3Cglyc1iD8eFY/view?usp=sharing

**Comment by robustini** [comment]
Another small log, in the first part parameter set to 4 and then to 13, the problem is evident.
Then set to 15, the problem disappears.
Rightly this goes to alter the VTOL, but it is evident that something also happens in the Plane. 

[00000003.ZIP](https://github.com/ArduPilot/ardupilot/files/7490487/00000003.ZIP)

**Comment by IamPete1** [comment]
Looks like your just in Q assist, it is expect behavior to use Q params when in assist. 

![image](https://user-images.githubusercontent.com/33176108/140614694-cf6a4e4d-d8e1-4558-a47e-f05551e70450.png)

You can see that as soon as your airspeed increases above your set `Q_ASSIST_SPEED` of 11 assistance stops and the oscillation goes away. 

So either setup the Q params so there is no oscillation, or reduce/turn off `Q_ASSIST_SPEED`
