### ISSUE TITLE
mavlink: Reboot/boot not announced in HEARTBEAT.system_status as expected.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#19214]
## Bug report

In case of a preflight reboot, HEARTBEAT.system_status is supposed to be able to indicate 0=unintialized, 1=booting, 2=calibrating …according to
https://mavlink.io/en/messages/common.html#MAV_STATE

SITL proves that this is not the case, except for a short jump to "4" (Active/airborne)
it is hard to determine that the system is rebooted.

Please tell if you know a reliable way for the payload to detect a reboot.

**Version**
AC 4.2.0-dev

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
(default SITL vehicle)

**Hardware type**
SITL

**Logs*
To reproduce:
reboot SITL vehicle using "reboot" command and observe system_status.

![Screenshot from 2021-11-10 14-36-30](https://user-images.githubusercontent.com/1468842/141122915-5c55de31-fb95-45c7-95d5-b151fde572c3.png)
*

**Comment by peterbarker** [comment]
We do now go through an "initializing" state in mavlink now, so I think we can close this.

You can't really rely on heartbeats to detect reboot - you may not get one before the system is fully functional (which can happen in case of a watchdog reset, for example).  You can look for the `time_boot_ms` fields unreasonably wrapping to be more reliable about detecting reboots.
