### ISSUE TITLE
Error in RC_Channel.h description  (AUTO RTL via DO_LAND_START)

### ISSUE THREAD

**Issue by Dmitrykrz** [ArduPilot/ardupilot#19272]
## Bug report
According to https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channel.h
There is servo function 99 witch says  AUTO RTL via DO_LAND_START.
But according to https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channel.cpp#L100
The ArduPlane has no function 99, it is only for ArduCopter.
But copter has no  DO_LAND_START, this is a plane feature.
There are 2 explanations:

1. There is en error in RC_Channel.h (do_land_start should be removed)
2. There is no error in RC_Channel.h but plane documentation must have info on function 99

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Docs are correct, copter can do use DO_LAND_START in auto RTL mode. Plane can also do DO_LAND_START but not via swtich.
