### ISSUE TITLE
Rover: boats should switch to Loiter by default at end of mission

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#19305]
The default MIS_DONE_BEHAVE value for Rovers and Boats is 0 ("Hold" mode).  For boats we should make the default Loiter to avoid the boat drifting off.

**Comment by rmackay9** [comment]
I'd recommend using AP_Param::set_default_by_name and put the new call at the bottom of Rover::load_parameters.  It should be set when FRAME_CLASS = 2 (Boat).

**Comment by hendjoshsr71** [comment]
Completed! Thanks @shiv-tyagi !
