### ISSUE TITLE
sim_vehicle.py could start mavproxy before ArduPlane has started and is waiting for connection causing premature exit

### ISSUE THREAD

**Issue by mrherman** [ArduPilot/ardupilot#19314]
## Bug report
sim_vehicle.py could start mavproxy before ArduPlane (or other vehicle) has completely started and is waiting for connection.  This will cause mavproxy to fail connecting to it and then exit prematurely.  The slow startup of ArduPlane is prevelent on remote systems with a larger than normal latency (I think the delay mostly comes from starting the xterm window on the local system).

I can add a sleep(15) in the sim_vehicle.py code right before starting mavproxy and get everything up and going before mavproxy is called, but that is obviously system/timing dependent and there is probably a better way to check that ArduPlane is up before launching mavproxy.

mavproxy trys connecting for a few seconds before giving up, in most cases for most people this is fine and everything will launch as expected; however, it is not always fine.

**Version**
4.1

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

(Probably all)
**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by Bavesh01** [comment]
We have the same issue running ArduCopter, wherein MAVProxy starts before and exits prematurely. Is there anything you have done to solve the issue?
Thank you so much!
