### ISSUE TITLE
waf: `sizeof-pointer-div` causes build failures on Ubuntu 18.04

### ISSUE THREAD

**Issue by sypaq-nexton** [ArduPilot/ardupilot#19362]
## Bug report

**Issue details**

PR #19351 added the `-Werror=sizeof-pointer-div` compiler option when building for `gcc` versions greater than or equal to v7.4. However, this option is not available in v7.4. As such, a build on the Ubuntu 18.04 LTS (which by default uses `gcc` v7.5) will fail.

Note: I haven't confirmed _exactly_ which `gcc` includes the `sizeof-pointer-div` option:
* it _is not_ present in v7.5
* it _is_ present in v8.4

**Version**
`master`

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
N/A

**Hardware type**
N/A

**Logs**
N/A

**Comment by sypaq-nexton** [comment]
I'll raise a PR shortly...

**Comment by peterbarker** [comment]
PR merged - thanks!
