### ISSUE TITLE
Vagrant default config builds both bionic64 & bionic64-desktop

### ISSUE THREAD

**Issue by peterb154** [ArduPilot/ardupilot#19374]
## Bug report

Cloning a fresh copy of ardupilot and running `vagrant up` creates 2 virtual machines a terminal version and a desktop version when only one is required. 
![image](https://user-images.githubusercontent.com/989984/143685777-8ef109f4-d955-48c1-8d7f-1a9c32e80c30.png)

This significantly increases the time to get the environment up and running and takes 2x the resources. 

It appears that the line that defines the bionic64-desktop image:
`config.vm.define "bionic64-desktop", primary: true do |bionic64|`
is configured to autostart, where none of the other desktop images do this. 

I am suggesting the following change be made to the bionic64-desktop declaration below. I'll submit a PR for this. 
```
  # 18.04 LTS EOL April 2023
  config.vm.define "bionic64", primary: true do |bionic64|
    bionic64.vm.box = "ubuntu/bionic64"
    bionic64.vm.provision :shell, path: "Tools/vagrant/initvagrant.sh"
    bionic64.vm.provider "virtualbox" do |vb|
      vb.name = "ArduPilot (bionic64)"
    end
  end

  # 18.04 LTS EOL April 2023
  config.vm.define "bionic64-desktop", autostart: false do |bionic64|
    bionic64.vm.box = "ubuntu/bionic64"
    bionic64.vm.provision :shell, path: "Tools/vagrant/initvagrant-desktop.sh"
    bionic64.vm.provider "virtualbox" do |vb|
      vb.name = "ArduPilot (bionic64-desktop)"
      vb.gui = true
    end
  end
````

Also, as a side note, it took a while for my copy to come up and I had to increase the timeout value. 
`config.vm.define "bionic64", primary: true do |bionic64|`

**Version**
latest master branch of ardupilot as of 11/27/21
```
$ vagrant --version
Vagrant 2.2.14
```

**Platform**
[ x ] All

**Airframe type**
ALL

**Hardware type**
PC / SITL

**Logs**
```
$ vagrant up
Bringing machine 'bionic64' up with 'virtualbox' provider...
Bringing machine 'bionic64-desktop' up with 'virtualbox' provider...
==> bionic64: Checking if box 'ubuntu/bionic64' version '20211025.0.0' is up to date...
==> bionic64: Machine already provisioned. Run `vagrant provision` or use the `--provision`
...
```

**Comment by nkruzan** [comment]
Looks like this issue can be closed, as the fix PR was merged.
