### ISSUE TITLE
AP_BatteryMonitor: remove AP_BattMonitor_MPPT_PacketDigital class

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#19453]
Now that the latest versions of the PacketDigital MPPT hardware supports UAVCAN (see PR https://github.com/ArduPilot/ardupilot/pull/19404) we can remove the older class [AP_BattMonitor_MPPT_PacketDigital](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BattMonitor/AP_BattMonitor_MPPT_PacketDigital.h) to save a little flash.

@magicrub you're happy with this?  I think you may have been the only user.

**Comment by magicrub** [comment]
I'm happy with it, and confirmed with the mfgr that its ok to remove.
