### ISSUE TITLE
GPIO on 4.2 is totally broken

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot#19516]
Using a fresh instal of rover 4.2 DEV on pixhawk 1 2mb with nothing else changed, setting any servo to -1 for GPIO results in immediate crash and reboot loop. I had to flash to antenna tracker and back again to reset the parameters and get it starting again.  It has to be something in the last 18 days, that was when the previous working install of 4.2 was done.

https://youtu.be/SDuEhWJPN78

Done some more testing,

trying to set -1 on servo in ardurover 4.2 results in a failure to set parameter and reboot loop
trying to set -1 on servo in arducopter 4.2 results in a failure to set parameter and instant reboot.
trying to set -1 on servo in arduplane 4.2 results in a failure to set parameter , reboot then crash

**Comment by tridge** [comment]
thanks for reporting! I've reproduced and will fix soon

**Comment by geofrancis** [comment]
@tridge It looks like the problem has gone now, whats changed?

**Comment by rmackay9** [comment]
@geofrancis, I think it was this fix https://github.com/ArduPilot/ardupilot/pull/19524.  Sorry for not posting it when we resolved it.
