### ISSUE TITLE
Copter: ENHANCEMENT flight replay from logging file but be able to change flight parameters to see what if

### ISSUE THREAD

**Issue by hotelzululima** [ArduPilot/ardupilot#1953]
Hi All,
       this may be in a FAQ or the wiki.. I did  not see it so will ask if this can be a possibility.

Is it possible to use the bin log to simulate a flight in toto(similar to SITL) while changing parameters such as failsafes in various parts of the flight  to see if the flight has a different ending and what that would be.
Its would seem that this would not be impossible given the components and data to work with..
I am thinking about something similar to exmaps.com  but with the ability to alter flight parameters in the simulated FC..

Any interest in this type of feature set? .. or did someone already do this, feel free to close this issue if this is redundant and provided already.

**Comment by robustini** [comment]
I like it...

**Comment by hotelzululima** [comment]
can it be done with tlog already Marco?  any urls?

     hzl

**Comment by hotelzululima** [comment]
I tried modeling my issue on http://www.exmaps.com/uploads/11257  but of course no way to do whatif modeling with the loaded parameters failsafes and PIDS, I suspect we can get farther by using SITL to setup the simulation  checking on that now...

**Comment by hotelzululima** [comment]
Hi marco..
 found this http://dev.ardupilot.com/wiki/simulation-2/sitl-simulator-software-in-the-loop/using-sitl-for-ardupilot-testing/  but they DON'T have a facility for rc_transient errors looking at code now to see how hard to simulate that  and making sure there is a test case for same...

     hzl

**Comment by robustini** [comment]
No, that's another thing.
It would be very interesting if the Planner could load the logs as it does with the tlog (Play, Pause, etc.).

**Comment by hotelzululima** [comment]
looks like this may be it though http://dev.ardupilot.com/wiki/simulation-2/testing-with-replay/

**Comment by hotelzululima** [comment]
just need to make sure I can 3.2.1 release.. and wondering how it will sim the rcrf transient error from the bin log.. 

also need to see if the  FS was triggered even if set to do nothing is logged for what I am looking for..
     hzl

**Comment by hotelzululima** [comment]
replay does not look like it either... some combo of it an SITL perhaps

**Comment by peterbarker** [comment]
Modern Replay allows you to rerun sensor data through the EKF estimators with different parameter values to see how it would have performed.

Our normal SITL environments allow for re-running of mission files, and addition of a physics backend of suitable fidelity allows for reasonable flight reproduction which could be used for testing different parameters.

Pretty sure there's nothing in-between.

Closing this now - it's very old and the ecosystem has evolved a rather large amount making the question out-of-date.  Its really more of a forum question anyway :-)

**Comment by robustini** [comment]
https://plot.ardupilot.org/#/
