### ISSUE TITLE
Rover: maximum steering deflection is reduced at higher speeds on Ackermann vehicles

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#19535]
The steering input is constrained (in some modes at least) to +-4500 before being passed into the motors library.  Within the motors library it then scales this down further (on Ackermann steering vehicles) if the vehicle's velocity is above MOT_SPD_SCA_BASE.

This means that the maximum movement of the steering is reduced at higher speeds.  Instead we should perform the scaling before the limiting so that the maximum range is always available.

Thanks very much to mroberts for uncovering this issue here https://discuss.ardupilot.org/t/understanding-history-and-logic-of-mot-spd-sca-base/79450/11

**Comment by mikerob** [comment]
Note that to successfully test in sim, you will need to bump up the turning circle of the sim Rover to 10m or so in order for the FF gain to be high enough to show the effect.

**Comment by rmackay9** [comment]
This is now resolved in master so closing.
