### ISSUE TITLE
Handle scenario where SDCard is mounted but we can't write logs to it

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#1955]
Perhaps develop a method "DataFlashHealthy" or something like that to monitor that we can actually write logs to the SDCard successfully.  If the thread which does that hangs we could kill it off and restart it or try to format the SDCard first or other options.

**Comment by WickedShell** [comment]
Error messages are emitted if we are unable to communicate with the IO thread, and there is a SYS_STATUS bit for logging health.
