### ISSUE TITLE
dis-Compatibility to documentation 

### ISSUE THREAD

**Issue by galdalali** [ArduPilot/ardupilot#19597]
The `MAV_MOUNT_MODE_MAVLINK_TARGETING` should receive it's target in degrees according to [documentation](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_MOUNT_CONTROL).
The ArduPilot [code ](https://github.com/ArduPilot/ardupilot/blob/312604f57773cce100bd8e5e6b4224cd8f49fe18/libraries/AP_Mount/AP_Mount_Backend.cpp#L67)from the other hand expect to receive it in centi-degrees

**Comment by amilcarlucas** [comment]
We are using our own [mavlink fork](https://github.com/ArduPilot/mavlink/) and [as you can see](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1049) use a different definition for that message.

Pull request correcting the documentation are very welcome.

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/21530
