### ISSUE TITLE
MacOS: Arm Builds for same Board Type and GIT Hash are Different Sizes

### ISSUE THREAD

**Issue by hendjoshsr71** [ArduPilot/ardupilot#19616]
@shiv-tyagi was testing some changes for me on MacOS  and noticed that the build size between his MacOS and Linux were coming out with different sizes by about 2KB on the the same GIT hash.

We checked his `./waf configure --board=CubeOrange` and this is his configuration output for mac:
[message.txt](https://github.com/ArduPilot/ardupilot/files/7783059/message.txt)

He is using: gcc-arm-none-eabi-10-2020-q4-major , g++ 10.2.1 

Here are the summaries from the two different .apj's

MacOS
```bash
    "board_id": 140,
    "magic": "APJFWv1",
    "description": "Firmware for a STM32H743xx board",
LEFT OUT IMAGE of course
    "extf_image": "eNoDAAAAAAE=",
    "summary": "CubeOrange",
    "version": "0.1",
    "image_size": 1752588,
    "extf_image_size": 0,
    "flash_total": 1966080,
    "image_maxsize": 1966080,
    "flash_free": 213492,
    "extflash_total": 0,
    "extflash_free": 0,
    "git_identity": "281f041a",
    "board_revision": 0,
    "USBID": "0x2dae/0x1016"
}

```

Linux
```bash
{
    "board_id": 140,
    "magic": "APJFWv1",
    "description": "Firmware for a STM32H743xx board",
    "extf_image": "eNoDAAAAAAE=",

    "summary": "CubeOrange",
    "version": "0.1",
    "image_size": 1750852,
    "extf_image_size": 0,
    "flash_total": 1966080,
    "image_maxsize": 1966080,
    "flash_free": 215228,
    "extflash_total": 0,
    "extflash_free": 0,
    "git_identity": "281f041a",
    "board_revision": 0,
    "USBID": "0x2dae/0x1016"
}
```

So the MacOS one is 1736 B bigger

**Comment by amilcarlucas** [comment]
What gcc-arm version are you using?

**Comment by khancyr** [comment]
what is the python version ?

**Comment by hendjoshsr71** [comment]
@shiv-tyagi Would please try this out again for us? 

And upload the text from `./waf configure --board=CubeOrange` for both your linux and MacOS. 

Also the .apjs from each for say copter.

**Comment by shiv-tyagi** [comment]
[Mac.zip](https://github.com/ArduPilot/ardupilot/files/7805209/Mac.zip)

**Comment by hendjoshsr71** [comment]
@shiv-tyagi Thanks again for testing the MacOS stuff!

**Ubuntu**
You are using g++ 9.2.1 for your arm compiler on Ubuntu. Likely the preinstalled version? You need to be sure to use the project supplied compiler here, gcc 10.2.1, https://firmware.ardupilot.org/Tools/STM32-tools/

 I think we can close this as your Mac APJ is very close, within  around 180 bytes, to when I built it on WSL. We could figure out why is different because I believe it should be exact? But it is a lot less worrying that the 2+ KB difference which is likely due to your complier difference,
