### ISSUE TITLE
SIM_WIND_DIR and WIND.direction are reversed

### ISSUE THREAD

**Issue by phelpsw** [ArduPilot/ardupilot#1963]
Based on SITL testing, it appears SIM_WIND_DIR represents the direction the wind is blowing rather than the standard approach of the direction the wind is originating from. WIND.direction uses the latter convention which is more commonly used to describe wind conditions.

I have confirmed in flight testing that WIND.direction operates by this standard convention.  The problem is clearly with SIM_WIND_DIR.

**Comment by Naterater** [comment]
After testing in SITL in Mission Planner yesterday, I can confirm that the wind directions is now correct. Remember that the direction is the azimuth that the wind is coming FROM.
