### ISSUE TITLE
AP-Periph Neopixel broken on F412 node

### ISSUE THREAD

**Issue by MallikarjunSE** [ArduPilot/ardupilot#19644]
## Bug report

**Issue details**
Neopixel on F412 node works on AP_Periph v1.2 stable but not on latest master. F405 works fine on master, but have issue only on F412 nodes. 
Link to video:
https://photos.app.goo.gl/9Vez2s4ke6GU5LYT7 
Left is F405, Right is F412. 
hwdef is changed according to this PR  #16113

_Please describe the problem_

**Version**
AP_Periph v1.3 dev

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
DroneCAN node

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by tridge** [comment]
it should be fixed in this PR:
https://github.com/ArduPilot/ardupilot/pull/19875
