### ISSUE TITLE
AP_Proximity: remove AP_Proximity_LightWareSF40C_v09

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#19697]
We are running out of flash space on some boards so let's remove the older lightware SF40c driver. https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Proximity/AP_Proximity_LightWareSF40C_v09.h

FYI @muramura

**Comment by peterbarker** [comment]
On Wed, 5 Jan 2022, Randy Mackay wrote:

> We are running out of flash space on some boards so let's remove the older lightware SF40c driver. https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Proximity/AP_Proximity_LightWareSF40C_v09.h

Shouldn't we just put it behind AP_PROXIMITY_LIGHTWARE_F40C_ENABLED - and 
default it to 0 ?

**Comment by rmackay9** [comment]
@peterbarker, no, I think we should just remove it.  beyond the flash cost there is a software maintenance cost.

**Comment by khanasif786** [comment]
@peterbarker @rmackay9 Please have a look at this. #19707

**Comment by rmackay9** [comment]
Thanks to @khanasif786 for resolving this!
