### ISSUE TITLE
ArduCopter 4.2 No Mavlink Data for MinimOSD for Pixhawk 1-1M

### ISSUE THREAD

**Issue by lion13ch** [ArduPilot/ardupilot#19699]
ArduCopter 4.2 "No Mavlink Data" for MinimOSD (Telem2 port used at Pixhawk 1-1M).
ArduCopter 4.1.3 works fine.

**Comment by IamPete1** [comment]
@lion13ch we changed the default serial protocol to MAVLink 2, you might have to change it back to mavlink 1.

**Comment by lion13ch** [comment]
At ArduCopter 4.1.3 config for SERIAL2 port serial_protocol is 2 (MAVLink 2). But it works fine. Did MAVLink 2 changed at 4.2?

**Comment by IamPete1** [comment]
@lion13ch sort of, on 4.1 MAVLInk 2 was only active once a MAVLink 2 message was received. So AP was checking to make sure the other end of the connection was capable. On 4.2 we removed the check to allow streaming of MAVLink 2 on a one way link. 

So as I say, try setting it to MAVLink1.

**Comment by lion13ch** [comment]
Thanks a lot!

**Comment by hendjoshsr71** [comment]
@lion13ch Is your issue fixed and can we close this?
