### ISSUE TITLE
MAV_CMD_DO_AUTOTUNE_ENABLE.param2 now includes axes to tune

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#19702]
## Feature request

Autotuning allows you to specify the axes to use for tuning. This is currently done using parameters. 

The latest version of [MAV_CMD_DO_AUTOTUNE_ENABLE](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_AUTOTUNE_ENABLE) allows the GCS to specify the axes as a bitmask in `param2`. Zero indicates "do all" or "do default".

The action is to update the stack to use the `MAV_CMD_DO_AUTOTUNE_ENABLE.param` values if specified and appropriate. 

This applies to all versions.

**Comment by peterbarker** [comment]
One important thing to note here is that autotune in ArduPilot is seldom enabled via this command.  We have explicit modes set aside for autotuning.

Also, more a feature request that a bug report IMHO :-)

**Comment by hamishwillee** [comment]
How rude :-). I've changed to a feature request to make you happy.

**Comment by amilcarlucas** [comment]
Thanks for fixing the bitmask

**Comment by hamishwillee** [comment]
You're welcome. Schoolboy error.

**Comment by khanasif786** [comment]
@peterbarker Sir, I think this PR #19742 should work.

**Comment by hendjoshsr71** [comment]
Are we going to close this issue since it was determined it wasn't worth the flash space for plane? Or leave it open for other vehicles?

**Comment by rmackay9** [comment]
I'm going to close this.
