### ISSUE TITLE
Matek H743 build failed on master

### ISSUE THREAD

**Issue by chobitsfan** [ArduPilot/ardupilot#19765]
## Bug report

**Issue details**
https://github.com/ArduPilot/ardupilot/pull/19706/commits/83cb5c96b045e9b35988b74c80971a1c82be5802 add following code 
https://github.com/ArduPilot/ardupilot/blob/d9c562cfae63281f1c14572c84a96cfc440902d0/libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py#L1102-L1105
In Matek H743, it reduce `flash_size` from 2048KB to 1792KB (`offset`), substract 256KB from 2MB flash
But later in origin code
https://github.com/ArduPilot/ardupilot/blob/d9c562cfae63281f1c14572c84a96cfc440902d0/libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py#L1128
`flash_reserve_end` is 256KB. So `flash_length` is 1408 which is incorrect. And it cause build failed
[813/816] Linking build/MatekH743/bin/arducopter
/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:common.ld:201 cannot move location counter backwards (from 0000000008198200 to 0000000008180000)
collect2: error: ld returned 1 exit status

**Version**
master

**Platform**
All

**Hardware type**
Matek H743

**Comment by tridge** [comment]
@chobitsfan thanks for looking at this! I've done an alternative fix in #19769 that just removes the duplicate counting of the flash reserve
