### ISSUE TITLE
after setting set_message_interval to certian rate, it reverts back after a few seconds

### ISSUE THREAD

**Issue by DoneMan** [ArduPilot/ardupilot#19761]
## Bug report

**Issue details**
after connecting to sitl to mavros, i am setting "set_message_interval" to 30 hz on all topics. it increases to 30hz for about 3 seconds, but then reverts back to default.

**Version**
Copter-4.1.3

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
sitl quad

**Hardware type**
sitl board

**Comment by khancyr** [comment]
hello,
Do use mavproxy (--no-mavproxy on sim_vehicle.py, or connect on tcp:5762) or disable Mavproxy streamrate control (set streamrate -1)

**Comment by DoneMan** [comment]
> hello, Do use mavproxy (--no-mavproxy on sim_vehicle.py, or connect on tcp:5762) or disable Mavproxy streamrate control (set streamrate -1)

hi thanks for the help
