### ISSUE TITLE
Manual altitude control in Auto mode (or a new mode)

### ISSUE THREAD

**Issue by JacksonUAS** [ArduPilot/ardupilot#19823]
## Feature request

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
Have had a number of requests over last year for autonomous waypoint flights (simple grid etc) that allows manual heigh control. Applications such as aerial spraying would benefit greatly from it. Similar functionality to current yaw control, but allow ascent and descent via pilot input (perhaps within a range of x).

**Comment by rmackay9** [comment]
Hi @JacksonUAS,

Thanks for the enhancement request.  Indeed this has been asked for many times and we've got a to-do on the issues list already here: https://github.com/ArduPilot/ardupilot/issues/11251

I'll go ahead and close this if that's OK.
