### ISSUE TITLE
Ac4.1 Lua scrip how to prohibit arming

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#19827]
I m trying to prohibit arming with lua scripting

In Function of boolean variable I want to prohibit arming on multicopter.

i found : 
include AP_Arming/AP_Arming.h

singleton AP_Arming alias arming
singleton AP_Arming method disarm boolean AP_Arming::Method::SCRIPTING'literal
singleton AP_Arming method is_armed boolean
singleton AP_Arming method arm boolean AP_Arming::Method::SCRIPTING'literal
singleton AP_Arming method get_aux_auth_id boolean uint8_t'Null
singleton AP_Arming method set_aux_auth_passed void uint8_t 0 UINT8_MAX
singleton AP_Arming method set_aux_auth_failed void uint8_t 0 UINT8_MAX string

But i dont know how to use it.

does anyone can help me to achieve this ?

**Comment by rmackay9** [comment]
Hi @roque-canales,

We have a couple of examples that could help

- https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/arming-check-batt-temp.lua
- https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/arming-check-wp1-takeoff.lua

I might close this issue if that's OK (but I'll still see responses and comments) because i think this is more of a developer or support question rather than an issue or enhancement request... at least for now.

**Comment by roque-canales** [comment]
Thank you perfect!

Envoyé de mon iPhone

Le 19 janv. 2022 à 00:38, Randy Mackay ***@***.***> a écrit :

﻿

Closed #19827<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArduPilot%2Fardupilot%2Fissues%2F19827&data=04%7C01%7C%7Ca230f657ca1b49f18e3308d9dadb98eb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637781458959928746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PUhc4LE%2FkZx5EeGcdXo%2BixS%2BuPA%2B3lYw71zffYMZ%2Bgw%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArduPilot%2Fardupilot%2Fissues%2F19827%23event-5914051768&data=04%7C01%7C%7Ca230f657ca1b49f18e3308d9dadb98eb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637781458959938742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MGqJ2ElQfiLzzx8JDnMdRclVkYN6zdaGcibJD0s82B0%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACANFUFXGX7B33TJGCDEZQTUWX2WLANCNFSM5MICOMOQ&data=04%7C01%7C%7Ca230f657ca1b49f18e3308d9dadb98eb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637781458959948736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q3QLQYm2dBEREGQw9pPo8AZQSS6YiFAs313AzkpqDQI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca230f657ca1b49f18e3308d9dadb98eb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637781458959948736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FH8ri1M%2Fm%2BWkP21%2FdPXSUJO%2FgS%2FXVjTB0%2FuJl1Hg3WI%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca230f657ca1b49f18e3308d9dadb98eb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637781458959958728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FBjHPDFv%2FQBTwnE1EA%2BkryoYCN02p9nuGTze7QJuMMQ%3D&reserved=0>.
