### ISSUE TITLE
change to 16g in all INS accel drivers

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#1984]

**Comment by magicrub** [comment]
To my knowledge this is complete although it has a Linux tag so maybe not. @tridge and @rmackay9  please confirm and close this or at least note what additional work is needed.

**Comment by OXINARF** [comment]
Closing this as I believe we have changed to 16G in all possible drivers (only one that seems missing is combined driver for L3G4200D and ADXL345 - named L3G4200D - which isn't used by any board and has a comment saying it should never be used in production).
