### ISSUE TITLE
drawing polygon using python commands 

### ISSUE THREAD

**Issue by montathar111** [ArduPilot/ardupilot#19852]
## Feature request

Dear sir 
I hope you are doing well. I am working in drone programming by python. I am using dronekit and mavlink commands. I want to draw a polygon using python is it possible ? I mean I want to give 4 coordinates as an input then apply the polygon command to draw the path for survey. How can I do it in python. or what are the other alternatives ?
regards  

**Platform**
[  ] Copter

**Comment by IamPete1** [comment]
https://github.com/ArduPilot/ardupilot_wiki/issues/4063#issuecomment-1019307512
