### ISSUE TITLE
Control of VTX channels, band via sticks or LUA script from Remote

### ISSUE THREAD

**Issue by MikhailSeregin** [ArduPilot/ardupilot#19935]
## Feature request

**What I want:**
Add possibility of switching VTX channels via Remote.

**How to do this:**
Just add an OSD menu, where we can change the VTX settings (channels, bands) similar to Betaflight. Or adjust it via LUA script from remote.

**Platform**
I'm interesting of the:
[  ] Copter
[  ] Plane

Thank you and best regards!

**Comment by andyp1per** [comment]
@MikhailSeregin you can do this already - just use the OSD module in mavproxy to setup the VTX parameters you want to change.
