### ISSUE TITLE
ADD Full Passthrough capability

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#1994]
Following Marco idea but extending it to CH7 an CH8

for example regarding QUADROTOR:
for CH7 passthrough over AUX 4 CH7 Fonction set to 108
for CH7 passthrough over RCOUT 5 CH7 Fonction set to 101

for example  regarding HEXAROTOR:
for CH8 passthrough over AUX 2 CH7 Fonction set to 104
for CH8 passthrough over RCOUT 7 CH7 Fonction set to 101

**Comment by WickedShell** [comment]
This appears to have been done as a side effect of the servo split. `SERVOn_FUNCTION` can be set from 51-66 to map from RCIN1 to RCIN16.
