### ISSUE TITLE
HERE3 GPS supports PPK ???

### ISSUE THREAD

**Issue by hassan-mushtaq** [ArduPilot/ardupilot#19947]
## Need General Information

I need to get information whether HERE3 GPS supports PPK ??? If Yes then ### **HOW**

_Please describe the problem_

**Platform**
[  ] All
[  ] AntennaTracker
**[x] Copter
[x] Plane**
[  ] Rover
[  ] Submarine

**Hardware type**
Pixhawk orange + Here3 GNSS_

**Comment by IamPete1** [comment]
Try asking on the Cubepilot forum, https://discuss.cubepilot.org/

**Comment by rmackay9** [comment]
We have some information on the Here+ on the wiki here https://ardupilot.org/copter/docs/common-here-plus-gps.html
