### ISSUE TITLE
Tools: Plane's Landing-Drift auto test is flapping

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20054]
The autotune for Plane called Landing-Drift fails quite often.  We should figure out why and fix it or disable it.

**Comment by wp0351034** [comment]
您的邮件已经收到，尽快给您回复。北京堂仁翔科技有限公司联系人：王鹏  电话：135 2058 1985 ***@***.***网址：www.trxchn.comQQ:191896104地址：北京市海淀区花园北路14号环星大厦A座8层888室

**Comment by peterbarker** [comment]
@samuelctabor FYI - we'd like to get this test fixed.  Ping me if you'd like some help looking at failing logs.

**Comment by rmackay9** [comment]
It's just a guess but it may depend upon the state of the test run before it.

**Comment by samuelctabor** [comment]
That's fine @rmackay9 .

It doesn't seem to be leftover state, the test resets SITL at the start and I ran it a few times locally without seeing the issue.

@peterbarker not sure how I can proceed without getting logs from the server

**Comment by samuelctabor** [comment]
@rmackay9  @peterbarker  reminder . . . I could use the help getting this test enabled again.

**Comment by rmackay9** [comment]
@samuelctabor @peterbarker this is fixed now right?

**Comment by tridge** [comment]
seems to be fixed

**Comment by peterbarker** [comment]
Re-opening this as this is still in the "Disabled" list (which is not a fix :-) )

@Georacer also found this is related to a partner issue.
