### ISSUE TITLE
Copter: keep logging after parachute release

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#2011]
We probably want to keep logging after a parachute release in order to capture the impact in the logs.
Request from Roberto N.

**Comment by robustini** [comment]
+1

**Comment by jmachuca77** [comment]
Seems easy to continue logging by adding a flag and set it when the parachute is released, and use this to continue logging. But when should we stop logging then?

**Comment by aercamti** [comment]
+1
logging can stop when the conditions of the crash check have been reached, which should indicate a landing.

**Comment by rmackay9** [comment]
This is resolved in master and went out with Copter-4.0.0.

**Comment by peterbarker** [comment]
This is fixed in (e.g.) Copter-4.0 - tridge's log-after-disarm changes.
