### ISSUE TITLE
Copter: Sudden jump in desired altitude when switching to auto

### ISSUE THREAD

**Issue by Hasi123** [ArduPilot/ardupilot#20142]
## Bug report

**Issue details**

Create a mission starting with a takeoff command using TERRAIN altitude frame. Takeoff manually and fly to a location (using guided, loiter, etc.), where the terrain is higher or lower than at takeoff. Now switch to AUTO and observe a sudden jump in desired altitude and climb rate with an agressive reaction from the copter. If the terrain is lower than at takeoff the initial jump is upwards and if the terrain is higher (so when you fly up the mountain), the initial jump goes down which can cause a crash. First encountered this problem during an actual flight, then also reproduced it in SITL.

**Version**
4.1.3, 4.1.5

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
any copter

**Hardware type**
CubeBlack, SITL

**Logs**
[logs.zip](https://github.com/ArduPilot/ardupilot/files/8117159/logs.zip)

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/20285
