### ISSUE TITLE
Replay broken when setting EKF source sets

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#20168]
## Bug report

**Issue details**

There's no logging into the DAL of calls to `void setPosVelYawSourceSet(uint8_t source_set_idx);`

That means that if something calls that function - script, switch, mavlink-message, button - then the replay log will simply not work as that call will not be replayed

The fix for this will be something like this call when something sets the EKF's origin:

```
AP::dal().log_SetOriginLLH3(loc);
```

**Version**
master

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
N/A

**Hardware type**
All

**Logs**
N/A

**Comment by tridge** [comment]
fixed by #20862
