### ISSUE TITLE
Copter: incorrect navigation with DO_JUMP

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#20167]
s-curve navigation doesn't work correctly with DO_JUMP 
copter s-curve normally smoothly goes between waypoints with no pause. With a DO_JUMP it does pause.
This was noticed with follow, and the pause disrupted the speed of the 3 copter formation
http://uav.tridgell.net/tmp/copter-do-jump-pause.bin

**Comment by tridge** [comment]
turns out to be a mission plan bug, closing

**Comment by rmackay9** [comment]
Yeah, couldn't be an scurves issue because Copter navigation doesn't even see the do-jump... it's all hidden.
