### ISSUE TITLE
Rover: When the ship (outboard engine) is in loiter mode, the steering is full stroke and the ship keeps turning.

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#20179]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**

_Please describe the problem_

**Version**
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[x ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
Can you share a log of this.

I suspect it is simply that we do not boost throttle to re-gain steering control.

**Comment by geofrancis** [comment]
there is a lua script to fix this issue with lack of steering authority at low throttle, ideally there should be an option for this in the firmware.
https://discuss.ardupilot.org/t/improve-steering-if-motor-throttle-is-off/74572/5

**Comment by xianglunkai** [comment]
@[geofrancis](https://github.com/geofrancis) Thank you very much! For those gasoline engines,frequent gear switching is not allowed during loiter. herefore, appropriate coordinated control of throttle and steering gear is very important!

**Comment by xianglunkai** [comment]
By the way, why not control the bow to align with the loiter point when the ship loiter in the area, and direction of water flow changes?     [_desired_yaw_cd = rover.current_loc.get_bearing_to(_destination);]
