### ISSUE TITLE
EKF3: indexing error

### ISSUE THREAD

**Issue by liyue75** [ArduPilot/ardupilot#20180]
https://github.com/ArduPilot/ardupilot/blob/f79c43eebdd1e446c5c11a52cedf8666e5686fce/libraries/AP_NavEKF3/AP_NavEKF3_core.cpp#L1948

Should the **1** here be **i**?

**Comment by IamPete1** [comment]
Looks like a bug to me, thanks for the report!

**Comment by tridge** [comment]
fixed here:
https://github.com/ArduPilot/ardupilot/pull/20197
@liyue75 well spotted! how did you find this?

**Comment by liyue75** [comment]
@tridge Hi, I'm now looking at the source code of **ekf3** and trying to rewrite it in C.
