### ISSUE TITLE
GCS TCP reconnection failed

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#20209]
If the GCS TCP connection（like tcp:0.0.0.0:14550） is abnormally disconnected, the controller cannot be connected again for a long time. Through netstat command, I can see that the port is occupied. Could we set the TCP disconnection detection time in the program？

**Comment by amilcarlucas** [comment]
What controller? What program?

**Comment by xianglunkai** [comment]
@[amilcarlucas](https://github.com/amilcarlucas) Txs! 
ardurover 4.2dev 
I think that is a common problem with linux.
