### ISSUE TITLE
Fence/Log: log polygon and circular fences

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20213]
For support purposes it is good to know where the fences are (polygon, circular, inclusion/exclusion) so we should log these somehow.  Perhaps when the log file is first started.

This comes from this discussion https://discuss.ardupilot.org/t/no-polygone-fences-in-the-dataflash-logs/82566/2

**Comment by peterbarker** [comment]
This should working like the existing `_writeentiremission` and `_writeallrallypoints` LoggerMessageWriter objects already present in `LoggerMessageWriter.h` and `.cpp`

**Comment by IamPete1** [comment]
I have a PR, https://github.com/ArduPilot/ardupilot/pull/18892 was held up on issues with the build environment. I will try and get it working with a dummy class or similar.
