### ISSUE TITLE
Test environment setup is failing

### ISSUE THREAD

**Issue by amilcarlucas** [ArduPilot/ardupilot#20265]
## Bug report

**Issue details**

Test environment setup is failing with the message:
```
you need to install pexpect with 'python -m pip install pexpect'
```

**Version**
master

**Platform**
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
All

**Hardware type**
All

**Logs**
https://github.com/ArduPilot/ardupilot/actions/workflows/test_environment.yml

**Comment by khancyr** [comment]
yep it is quite old, I need to find some time to fix this

**Comment by peterbarker** [comment]
.... I think this is all working now-adays.
