### ISSUE TITLE
Copter: Auto takeoff gets stuck if alt-above-home is positive and takeoff alt is terrain

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20277]
As reported by @Hasi123 [here](https://github.com/ArduPilot/ardupilot/commit/fb6c3ebb729a4b428da5dd14832cd95d71709a1e#commitcomment-68370961) Auto mode (and presumably Guided as well) can get stuck on a takeoff command if an alt-above-terrain is used.  To reproduce the issue in SITL do this:

- Start SITL copter at the regular location
- create a short mission with a takeoff command followed by a Waypoint command where both have altitude frames of "AGL/Terrain

![image](https://user-images.githubusercontent.com/1498098/157648431-34c1344e-a0dc-4a9c-a134-52e053dc0831.png)

- long MAV_CMD_DO_SET_HOME 0 0 0 0 -35.363 149.165 575  <-- to set a home altitude 
- param set AUTO_OPTIONS 3 <-- to allow arming and taking off in Auto
- auto
- arm throttle

You should see the Copter gets stuck and won't proceed to the waypoint command

**Comment by rmackay9** [comment]
This is maybe fixed by https://github.com/ArduPilot/ardupilot/pull/20153

**Comment by Hasi123** [comment]
I would like to add, that it only gets stuck if you start the mission (switch to AUTO) somewhere, where the terrain is lower than at home. So to reproduce:

- Start SITL in a hilly/mountainous environment
- Create and upload a mission starting with a takeoff command in AGL/terrain frame and a waypoint (doesn´t matter if its terrain/relative/absolute)
- Arm & takeoff in loiter/guided and fly downhill (somewhere, where the terrain is lower than at home)
- switch to AUTO and copter will get stuck after climbing to target altitude

**Comment by rmackay9** [comment]
@Hasi123,

You probably saw my ping already but maybe you could confirm that this issue is resolved in master now?

**Comment by Hasi123** [comment]
I'll only be able to test it next week.

**Comment by Hasi123** [comment]
> @Hasi123,
> 
> You probably saw my ping already but maybe you could confirm that this issue is resolved in master now?

Just tested it in SITL, seems to be working now as intended.

**Comment by rmackay9** [comment]
@Hasi123, great! thank you very much for finding this issue and helping us fix it!
