### ISSUE TITLE
Arming and disarming in autonomous flight is not working in the new version

### ISSUE THREAD

**Issue by Faruck-G** [ArduPilot/ardupilot#20278]
here you guys see the newer version code 153 for arming and disarming in an autonomous flight but it is not working properly and the older version code 41 worked properly and didnot make any problem but in the newer version the new code153 is not working and the mission planner is not responding to the code in any  manner. if any of you have any solution for me please be show some idea about . thanks and regards.
https://github.com/ArduPilot/ardupilot/blob/9eb5c93c553568226eae43268be014431ee673a3/libraries/RC_Channel/RC_Channel.h#L219

**Comment by IamPete1** [comment]
See param description:
`41:ArmDisarm (4.1 and lower)`
`153:ArmDisarm (4.2 and higher), 154:ArmDisarm with Quadplane AirMode (4.2 and higher)`
