### ISSUE TITLE
floating pt error in NavEKF

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#2031]
numerical error in SITL with IrisRos sim
#0  0x000000000044ec10 in sq (v=-6.99298053e+23)

```
at /home/tridge/project/UAV/APM/libraries/AP_Math/AP_Math.cpp:156
```
#1  0x00000000004510eb in Quaternion::length (this=0x6fd218 <ahrs+632>)

```
at /home/tridge/project/UAV/APM/libraries/AP_Math/quaternion.cpp:214
```
#2  0x0000000000451178 in Quaternion::normalize (this=0x6fd218 <ahrs+632>)

```
at /home/tridge/project/UAV/APM/libraries/AP_Math/quaternion.cpp:224
```
#3  0x000000000048b7e0 in NavEKF::FuseVelPosNED (this=0x6fd208 <ahrs+616>)

```
at /home/tridge/project/UAV/APM/libraries/AP_NavEKF/AP_NavEKF.cpp:2196
```
#4  0x000000000045e5db in NavEKF::SelectVelPosFusion (this=0x6fd208 <ahrs+616>)

```
at /home/tridge/project/UAV/APM/libraries/AP_NavEKF/AP_NavEKF.cpp:877
```
#5  0x000000000045e01f in NavEKF::UpdateFilter (this=0x6fd208 <ahrs+616>)

```
at /home/tridge/project/UAV/APM/libraries/AP_NavEKF/AP_NavEKF.cpp:734
```
#6  0x00000000004320ee in AP_AHRS_NavEKF::update (this=0x6fcfa0 <ahrs>)

```
at /home/tridge/project/UAV/APM/libraries/AP_AHRS/AP_AHRS_NavEKF.cpp:90
```
#7  0x0000000000407938 in read_AHRS ()

```
at /home/tridge/project/UAV/APM/ArduCopter/ArduCopter.pde:1268
```
#8  0x000000000040720b in fast_loop ()

```
at /home/tridge/project/UAV/APM/ArduCopter/ArduCopter.pde:948
```
#9  0x00000000004071d0 in loop ()

```
at /home/tridge/project/UAV/APM/ArduCopter/ArduCopter.pde:927
```
#10 0x00000000004079ba in main (argc=2, argv=0x7fffffffd2b8)

```
at /home/tridge/project/UAV/APM/ArduCopter/ArduCopter.pde:1286
```

(gdb) p *this
$6 = {q1 = -6.99298053e+23, q2 = -1.04953138e+23, q3 = 2.19607912e+23, 
  q4 = 8.86328313e+22}

**Comment by magicrub** [comment]
I imagine it would be worthwhile for some critical parts to use double precision to reduce round-off errors, would probably help in dead-reckoning as well.

**Comment by WickedShell** [comment]
Closing as EKF1 was removed with bb29c74e52
