### ISSUE TITLE
Rover: add support COLREGs avoidance for dynamical avoidance

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#20366]
As the simulation shows, bendyruler local avoidance is not compliance with COLREGs，and dynamical obstacle avoidance effect is poor.
Do we need to adjust the course and speed according to the relative speed, and add the planning of speed.

**Comment by rmackay9** [comment]
@xianglunkai, txs very much for the suggestion.

For others reading here is a link (just the first one I found) for [COLREGs](https://www.imo.org/en/About/Conventions/Pages/COLREG.aspx) which describes how boats should avoid hitting each other.

**Comment by xianglunkai** [comment]
Recently, I developed an obstacle avoidance algorithm based on speed obstacle method. This method complies with maritime rules on a wide sea surface, but it still needs to be improved in the face of crowded lakes.
By the way, do we need to use AIS as an other input for AP_Avoidance，so that boat at sea or on the river also be helpful!

**Comment by bijuthaj** [comment]
Just curios...Is COLREG support is added for rover? @xianglunkai @rmackay9
