### ISSUE TITLE
ROI with Arduplane - Get the GPS coordinate where the Pan-tilt Camera is looking at.

### ISSUE THREAD

**Issue by Elios007** [ArduPilot/ardupilot#2041]
HI, 

We would like to have the ROI feature in arduplane with Advanced options.

We would like to know GPS coordinates for the location of the crosshairs of a PTZ camera, otherwise known as ROI or Geo-pointing.  This will essentially give us the LAT/LONG of what we are looking at. 

![image](https://cloud.githubusercontent.com/assets/8313659/6962969/641414bc-d942-11e4-9dd5-22410c180fa0.png)

![image](https://cloud.githubusercontent.com/assets/8313659/6958113/81bd0830-d90f-11e4-9c8d-d5fd3170f104.png)

![image](https://cloud.githubusercontent.com/assets/8313659/6958116/a2de2864-d90f-11e4-8999-b164b87e0940.png)

The Brushless Gimbal will be connected to the Pixhawk so the Pixhawk knows where it is looking, and because there is a terrain following inside the Pixhawk, so we will combine both feature to get us where the camera is looking at regardless the direction and position of the plane.

Some Options how to use this new ROI inside the Arduplane:

Scenario 1: If someone is searching for a missing person in a mountain or any place, the plane does not need to fly over the found person to get his GPS coordinate because when he saw him in the camera the OSD and Ground station will show his GPS coordinate because the Camera is looking at him. It can save time by sending his coordinates to the ground team to go and get him and the plane will save time to go and search for other missing people.

Scenario 2: If we know the GPS Coordinate of an accident, we can add them into the mission planner and the plane will go there but it's not the same existing "fly-to-here" feature, because we will define the altitude and the ground distance for the plane to be away from the accident, which means the Gimbal Camera will look at the accident from a certain defined distance and altitude instead of being above the accident and the plane will continue doing loiter or flying manually...

I hope you will be able to help us in this feature as it can save lives.

**Comment by magicrub** [comment]
That's a pretty major feature. Would love to see it in ArduPilot.
Auto-search mode!

**Comment by tridge** [comment]
To do this properly with arbitrary terrain is a ray casting problem, which is quite tricky to do on the STM32, especially as we may not have all the terrain data paged in from microSD
It may be better to do this on the GCS. The GCS already has all the information it needs, but it will also have 30m grid terrain data, and lots of CPU and memory to do the ray casting

**Comment by magicrub** [comment]
What if we don't use terrain and assume a flat earth?

**Comment by Elios007** [comment]
Hi Tom

It won't work if it is only flat because there are mountains and valleys.

Regards
Elie Waked
skype: DonElie
00441212868687

**Comment by Elios007** [comment]
Because the GPS will be wrong if you assume it is flat while there is a
mountain.

Regards
Elie Waked
skype: DonElie
00441212868687

**Comment by magicrub** [comment]
Right, which makes it a harder, and less probable to get implemented,
problem. However, if we start with the framework and get the simple case
working then adding elevation info is just an enhancement and less
daunting. Baby steps!

**Comment by Elios007** [comment]
Well, we are trying to do it on the mission planner now. The Pixhawk will send to the MP the gimbal information as it is connected to, and the MP will do the calculation needed to know the GPS where the camera is looking at. We will know in 2 weeks if it will work. We hope so,

**Comment by lvale** [comment]
@tridge The original question made at RCGroups also had a 10x Zoom Camera involved in the equation....

**Comment by ionoy** [comment]
Are you using Mavlink to send gimbal orientation down to GCS? I'm actually implementing similar solution on my own, but I've decided to use separate link for gimbal communication at the moment, because ArduCopter doesn't have a good solution for sending this kind of data from UserCode.

I would love to see some extension points accessible from UserCode to receive and send packets of data.

**Comment by Elios007** [comment]
HI, we are working on it and we will try it withing the next 2 weeks, we hope it will work.

**Comment by Elios007** [comment]
@ionoy, were you able to get the desired result by using your own solution? would you share it with us, please.

**Comment by squilter** [comment]
related to #510

**Comment by ionoy** [comment]
@Elios007 At the moment our software is closed, sorry.

**Comment by raptortrias** [comment]
This function is of interest, has any functionality been implemented

 thanks

**Comment by TunaLobster** [comment]
The first part of this was implemented with 6d65b351cd848a3dd14a39fd47689b52cc1f0eb1. Adding in the terrain data to account for a large change in altitude from the home position has not been implemented.

**Comment by amilcarlucas** [comment]
I think Scenario 2 is already implemented in the current set ROI command

**Comment by rmackay9** [comment]
Knowing the lat, lon, alt of what the gimbal is pointing at is available using the mount-poi Lua script.  We have a c++ solution coming in 4.5 once this PR is merged https://github.com/ArduPilot/ardupilot/pull/24657

**Comment by peterbarker** [comment]
We have a merged solution for this now, so closing.
