### ISSUE TITLE
Support for IRC Tramp protocol to control VTX parameters

### ISSUE THREAD

**Issue by Inv3nt0r1** [ArduPilot/ardupilot#20438]
## Feature request

**Is your feature request related to a problem? Please describe.**
Not really. I want the VTX to run in Pit mode until I arm. When I am on the bench, the VTX gets really hot.

**Describe the solution you'd like**
Just like Smart Audio, I would like Ardupilot to support the IRC Tramp protocol to control VTX parameters like frequency and power level. An option to keep the VTX in pit mode until we arm.
I see more VTXes coming to support IRC tramp compared to Smart Audio.
Currently, betaflight and Inav support it. Being an Ardupilot pilot, I would like to have these features in my FPV drones having IRC Tramp VTX. 

**Describe alternatives you've considered**
NA

**Platform**
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
PR of IRC Tramp in betaflight: https://github.com/betaflight/betaflight/pull/2106

**Comment by zxt2010** [comment]
I had the same problem with my panda vt5804.It only supports the IRC TRAMP protocol.

**Comment by GaryWarren55** [comment]
I have just started using Ardupilot It has so many features. But Yes i agree this feature would solve my ability to control power levels on all my Matek 1.3 Vtxs a standard feature on Betaflight.

**Comment by palladin82** [comment]
+up
Need to run in pit mode using IRC tramp when disarmed.
