### ISSUE TITLE
Failsafe mode addition

### ISSUE THREAD

**Issue by Angus-TStop** [ArduPilot/ardupilot#20446]
Can the option of maintaining a hover be added to failsafe modes? This is particularly important if operating from a moving platform over water ie from a boat. Clearly landing whilst over water is not an option and RTL is no good and could make things much worse given that the take off platform may well have moved a great deal.

Another scenario where this would be good is if flying in a wooded area (assuming not too dense to block GPS). RTL is clearly a no go and landing may not be desirable due to terrain thus hovering would be great. This would at least give the operator the chance to reduce distances to the drone to try and attempt to regain a radio link.

**Comment by peterbarker** [comment]
We now have a failsafe mode which will leave you in "BRAKE" mode, which would appear to close this issue.

Closing this now.
