### ISSUE TITLE
F4 FC Logging Fail

### ISSUE THREAD

**Issue by ralphwu** [ArduPilot/ardupilot#20455]
## Bug report

**Issue details**
F4 FC Logging Fail

**Version**
4.1.5 and 4.2 Beta 3

**Platform**
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X

**Hardware type**
Mini Pix
Omnibus F4 Pro

**Logs**

**Comment by hendjoshsr71** [comment]
Hi,

We need more information than this to be actionable. A bin and a more complete issue description. 

If you have feedback on 4.2 Beta we prefer reports first go to our Discuss forum post here. https://discuss.ardupilot.org/t/copter-4-2-0-beta3-released-for-beta-testing/83622
