### ISSUE TITLE
Ac4.2 Modalai voxl cam test issue

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#20481]
Hello i’m trying to make the voxl cam work with ac4.2.

connexion is well established but i get issue:
![image](https://user-images.githubusercontent.com/8442576/162223722-39a1eafa-02c3-4f77-9fb3-6a8bf6b71c30.jpg)
Issue is that voxl tell that ap is upside down….
All is standard and viso orientation is set to forward
![image](https://user-images.githubusercontent.com/8442576/162224112-c01f7220-a49a-4ff0-8e27-2d38c53e1ea2.jpg)
So i dont understand how to resolve this…
Can you help?
maybe @Tridge know how to do that if he can share with us ;)
also i confirm that i have good link between cube and modalai
 
![image](https://user-images.githubusercontent.com/8442576/162224957-0257e01e-ff87-4b99-970a-5cc51fa0474f.jpg)

**Comment by rmackay9** [comment]
Hi @roque-canales, thanks for giving this a try.  The "can't initialise" message is not from ArduPilot but instead it comes from voxl.  Maybe the system is upside-down?  Seems unlikely and I'm sure confirmed the orientation yourself.

**Comment by roque-canales** [comment]
Hello Randy, I also pushed issue on the modal ai gitlab:
https://gitlab.com/voxl-public/voxl-sdk/services/voxl-vision-px4/-/issues/6

I saw that tridge also tested voxl cam, it would be greacefull if he can help us on this testing.

Rgds

**Comment by rmackay9** [comment]
Hi @roque-canales,

I think you've already noticed that we've fixed up the AP support for the ModalAI and created [a wiki page here](https://ardupilot.org/copter/docs/common-modalai-voxl.html).  The fixes are in Copter-4.3.2 which is available for beta testing now so if it's OK I will close this issue.  I will monitor for replies though so if you find problems I'm very happy to investigate.
