### ISSUE TITLE
EKF: "GPS Glitch" warning can be misleading because it's not always the GPS that is misbehaving

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20527]
"GPS Glitch" is displayed to the user if the EKF fails to fuse a GPS sensor value (or perhaps several sensor values) because they are too far from it's current position estimate.  This inability to fuse though isn't always caused by the GPS glitching however so the message can be misleading it can cause the user to investigate their GPS quality when in fact the issue is that the vehicle's heading is off (e.g. a compass issue).

We should either make the message more vague (e.g. "position estimate glitch") or try and add some heuristics to better judge if the issue is actually GPS or is perhaps compass/heading sensor.

This issue can be re-created in SITL by setting up a large magnetic anomaly when close to the ground and then arm and takeoff in Loiter mode

- param set SIM_MAG_ALY_HGT 10
- param set SIM_MAG_ALY_X -700
- param set SIM_MAG_ALY_Y -300

In this case there is nothing wrong with the GPS signal but the "GPS Glitch" message appears as shown below.

![image](https://user-images.githubusercontent.com/1498098/163654971-cf63f4ba-5971-4f76-b2f1-20ea89ddb020.png)

**Comment by khanasif786** [comment]
@rmackay9 Sir, Please take a look.
![Screenshot from 2022-04-22 21-22-24](https://user-images.githubusercontent.com/66586970/164764335-ead41999-eb5d-4329-af40-f1ca3770a5b7.png)

**Comment by rmackay9** [comment]
@khanasif786, very impressive!

**Comment by Hwurzburg** [comment]
@rmackay9 is this same message used if vibrations are affecting position also?

**Comment by rmackay9** [comment]
@Hwurzburg,

Yes, the message could also be displayed if vibrations are pulling the position estimate away from the GPS.  We discussed this possibility just before merging this PR and we decided that if vibrations were the problem there would be lots of indications to the pilot of the problem so we figured we didn't need to add "vibration" to this message.
