### ISSUE TITLE
ArduPlane 4.1.7 Mavlink Home Position not Being Sent

### ISSUE THREAD

**Issue by pilotnbr1** [ArduPilot/ardupilot#20564]
Using OpenHD with arduplane 4.1.7 the MAVLINK_MSG_ID_HOME_POSITION messages are not being received.

When upgrading to arduplane to 4.3.0dev, MAVLINK_MSG_ID_HOME_POSITION messages are being received again.

**Comment by IamPete1** [comment]
How about 4.2? I don't think we would do a new 4.1 release to fix this.

**Comment by peterbarker** [comment]
Quite sure this stuff works on master, and all releases mentioned in here are defunct.

Closing this now :-)
