### ISSUE TITLE
Diatone Mamba MK4 H743 Support

### ISSUE THREAD

**Issue by Sekilsgs2** [ArduPilot/ardupilot#20587]
Please add Diatone Mamba MK4 H743 to supported boards.

BF target - 

https://github.com/betaflight/unified-targets/blob/master/configs/default/DIAT-MAMBAH743.config

**Comment by Allentgt** [comment]
Any update on support for this board? Is this being looked into?

**Comment by andyp1per** [comment]
I have the mini so will port that when I have done the H743 which is proving more difficult that I thought

**Comment by Allentgt** [comment]
That's great. I was just asking because I'm not able to get my hands on the matek h743 and this seemed like a good alternative.

**Comment by Sekilsgs2** [comment]
Wow super thanks!

**Comment by redbananamoon** [comment]
Please change the name of this FC in your documentation and firmware files. The name "Mamba H743 v4" is
likely to cause a lot of confusion, especially now that there is a "Mamba MK4 H743 V2". Also on this topic, is the newer "Mamba MK4 H743 V2" supported by the same firmware?

**Comment by andyp1per** [comment]
Mk4 v2 is supported by the same firmware
