### ISSUE TITLE
Copter-4.05 loiter BUG

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#20594]
I use copter-4.05 code. Firstly I take off normally in loiter mode, and then fly the waypoint mode for a period of time. After landing, I take off in loiter mode, shaking left and right

**Comment by lixiaowei123** [comment]
[https://www.bilibili.com/video/BV1LR4y1K7VD/](url)

**Comment by amilcarlucas** [comment]
It might be a bug, but before we investigate, we need you to test it with version 4.1.5.
If the problem persists there, we investigate it further.

**Comment by IamPete1** [comment]
As @amilcarlucas says, update to 4.1 and post a log over on the fourm.

https://discuss.ardupilot.org/
