### ISSUE TITLE
AP_Button: internal error triggered if no PWM input

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20609]
I can easily recreate an internal error using AP_Button if setup to use PWM input but the PWM input is zero.  This bug is new in 4.2 (I tested with 4.1.5 and it didn't occur).

PreArm: Internal errors 0x2000000 l:554 gpio_isr

I've passed a log to @peterbarker in the hopes that he can help track down the issue.

**Comment by peterbarker** [comment]
Is the PWM input zero or floating?

What you're seeing is the ISR flood counter tripping - it's an explicit check for receiving an interrupt way, way too often.

We might be able to get this if we're emitting data on the same pad - any d-shot involved or something?

**Comment by rmackay9** [comment]
This only seems to happen when my servo tester is powered off but still connected to the autopilot's PWM input pins.  If the servo tester is disconnected or powered on then it's fine.  I've also checked that the pull-up is working so I think what we're seeing is a fight between the autopilot's pull-up and the servo tester when powered off.

Anywya, I think this is a hardware specific issue and is not a real problem so closing. txs!
