### ISSUE TITLE
AP_Scripting/AP_Vehicle/Copter/Rover: add do-change-speed binding

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20618]
We should allow lua scripts to easily adjust the speed of the vehicle (Copter, Rover, etc) by adding a change-speed binding equivalent to the mavlink do-change-speed command.

This enhancement request comes from [this discussion](https://discuss.ardupilot.org/t/do-change-speed-not-working-in-auto/84521/10).

**Comment by yuri-rage** [comment]
PR forthcoming for `set_desired_speed(float)`.
Set the nav speed (m/s) in assisted modes for Rover and in auto mode for Copter.

**Comment by yuri-rage** [comment]
PR submitted:
https://github.com/ArduPilot/ardupilot/pull/21115

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/21115
