### ISSUE TITLE
Waypoint Acceptance While Disarmed and Outside Acceptance Radius (Copter 4.2.0-rc1)

### ISSUE THREAD

**Issue by AndersonRayner** [ArduPilot/ardupilot#20655]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

I was testing out APM:Copter 4.2.0-rc1 and as part of my pre-flight checks, switched into AUTO mode (while disarmed) to check my flight modes were set up correctly.  The waypoints immediately started to cycle through, despite being outside the acceptance radius for each of the waypoints.  This is also a change to the expected behaviour I get with APM:Copter 4.1.X.  I did not check the waypoint following in flight (potential risk to the aircraft).

I checked this behaviour using the SITL simulator (Latest (dev)) this morning and the issue can be reproduced.  The waypoints cycle quickly while disarmed, however the behaviour is as expected while flying (correctly managing the waypoints).  The reprouction steps are:
* Start SITL (latest dev)
* Upload a simple waypoint mission
* Switch to AUTO mode while disarmed

**Version**
APM:Copter 4.2.0-rc1

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Standard Hexacopter

**Hardware type**
Cube Orange

**Logs**
A link to the BIN file is at https://1drv.ms/u/s!Alh-LrfPZRJvoN87gxrAfk6MpnG2sg?e=fTQk9c (captured with LOG_DISARM=1).  I have the tlog file as well if that will help, just let me know and I can trim it down.

**Comment by muramura** [comment]
I retrieved the flight plan from the bin file.
I ran this flight plan with SITL.
I had a flight plan executed with the arm disarmed.
I think this is a bug.


FIRMWARE: ArduCopter V4.3.0-dev (6e609e09)

BIN FILE TO MISSION: 
QGC WPL 110
0	1	0	16	0	0	0	0	34.1342911	-118.1270976	229.38999938964844	0
1	0	3	16	1	0	0	0	34.1344729	-118.1272329	10	3
2	0	3	178	0	2	0	0	0	0	0	0
3	0	3	115	90	0	0	0	0	0	0	0
4	0	3	16	1	0	0	0	34.1344706	-118.1267408	10	3
5	0	3	115	90	0	0	0	0	0	0	0
6	0	3	16	1	0	0	0	34.1344729	-118.1272329	10	3
7	0	3	115	90	0	0	0	0	0	0	0
8	0	3	16	1	0	0	0	34.1346094	-118.1272329	20	3
9	0	3	115	90	0	0	0	0	0	0	0
10	0	3	16	1	0	0	0	34.1346149	-118.1267300	20	3
11	0	3	115	90	0	0	0	0	0	0	0
12	0	3	16	1	0	0	0	34.1346094	-118.1272329	20	3
13	0	3	115	90	0	0	0	0	0	0	0
14	0	3	16	1	0	0	0	34.1347504	-118.1272329	30	3
15	0	3	115	90	0	0	0	0	0	0	0
16	0	3	16	1	0	0	0	34.1347526	-118.1267300	30	3
17	0	3	115	90	0	0	0	0	0	0	0
18	0	3	16	1	0	0	0	34.1347504	-118.1272329	30	3
19	0	3	115	90	0	0	0	0	0	0	0
20	0	3	16	1	0	0	0	34.1348879	-118.1272329	40	3
21	0	3	115	90	0	0	0	0	0	0	0
22	0	3	16	1	0	0	0	34.1348858	-118.1267408	40	3
23	0	3	115	90	0	0	0	0	0	0	0
24	0	3	16	1	0	0	0	34.1348879	-118.1272329	40	3
25	0	3	115	90	0	0	0	0	0	0	0
26	0	3	16	1	0	0	0	34.1350246	-118.1272329	50	3
27	0	3	115	90	0	0	0	0	0	0	0
28	0	3	16	1	0	0	0	34.1350234	-118.1267300	50	3
29	0	3	115	90	0	0	0	0	0	0	0
30	0	3	16	1	0	0	0	34.1350246	-118.1272329	50	3
31	0	3	115	90	0	0	0	0	0	0	0

LOCATION:
![Screenshot from 2022-04-29 21-56-09](https://user-images.githubusercontent.com/646194/165948964-deeb9de7-ec13-4d84-8fb1-49d44d777f43.png)

DISARMED and Flight mode  to AUTO
![Screenshot from 2022-04-29 21-56-29](https://user-images.githubusercontent.com/646194/165949239-62184a19-f53e-486c-9d4e-868be9af81ba.png)

**Comment by jackhong12** [comment]
The issue happened after the commit [0ce44ad](https://github.com/ArduPilot/ardupilot/commit/0ce44ad1ba22b8c117b83e020bd5d28dccccc000). The function `reached_wp_destination` will always return true because the variable `reached_destination` was set to true in the function `AC_WPNav::wp_and_spline_init`. The function `verify_nav_wp` will also return true, so the flight plans will keep executing.

```c++
// verify_nav_wp - check if we have reached the next way point
bool ModeAuto::verify_nav_wp(const AP_Mission::Mission_Command& cmd)
{
    // check if we have reached the waypoint
    if ( !copter.wp_nav->reached_wp_destination() ) {
        return false;
    }
    ...
}
```

I fix this bug by changing `reached_destination` back to false. But I'm not sure whether there are other purposes to set `reached_destination` to true here.

- [fix](https://github.com/jackhong12/ardupilot/commit/76dc37d1aefc49b19c03c915d33ab048c9ca662b)

**Comment by muramura** [comment]
I set _flags.reached_destination to TRUE when I have achieved WP.
However, setting it to TRUE on initialization has made the rest of the process incorrect.
I think I am fine with making it FALSE.

I hope to PR this as soon as possible.

![Screenshot from 2022-04-30 07-48-23](https://user-images.githubusercontent.com/646194/166077891-7879a461-2295-4949-946d-15110cfbc25e.png)

**Comment by muramura** [comment]
I thought it would be better to PR and let the maintainer make the decision.
I think I am setting TRUE in the wrong place.

**Comment by AndersonRayner** [comment]
The other option to fix the issue could be to check if the vehicle is disarmed, and only accept waypoints have been reached if the vehicle is armed.  The only issue here is if you want to check the behaviour by walking the UAV through the flight plan beforehand as some kind of check. 

As a side note, I ran an auto mission yesterday and the vehicle behaved as expect, so this problem only turns up (both in SITL and experimentally) if the vehicle is disarmed.

**Comment by AndersonRayner** [comment]
This issue appears to have been fixed with the release of Copter 4.2 official.  I think we can safely close it now :).

**Comment by rmackay9** [comment]
I somehow completely missed this report so I've added it to our [4.2 issues list](https://github.com/ArduPilot/ardupilot/issues/20192).

I'm actually surprised that this bug has been fixed because we haven't been modifying AC_WPNav in the last month.

**Comment by AndersonRayner** [comment]
I ran a couple more tests in SITL via Mission Planner and Copter (stable).  The first mission item is a DO_CHANGE_SPEED which is automatically accepted on a switch to AUTO (even when disarmed), and it will then wait to do the second mission item (which is a waypoint).  I can then arm the quad, takeoff (in guided) and then switch to auto, and the speed changes as expected.
