### ISSUE TITLE
Writing UART Sensor Driver

### ISSUE THREAD

**Issue by TzionCastillo1** [ArduPilot/ardupilot#20662]
Hi,

I am attempting to write a sensor driver for a water parameter sensor that operates over UART for an ArduRover Boat project I have. The documentation for doing this is very limited and confusing, so I wanted to see if anybody could point me in the correct direction. I have the sensors datasheet, and have used it successfully on an arduino, but I am getting confused with the frontend-backend concepts in Ardupilot.

Any help is appreciated.

**Comment by IamPete1** [comment]
Scripting is recommended if its just logging or reporting. See:

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/UART_log.lua

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/SN-GCJA5-particle-sensor.lua

If your still stuck ask over on the forum, https://discuss.ardupilot.org/
