### ISSUE TITLE
Code issue on get_num_logs()

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#20686]
## Bug report

**Issue details**

https://github.com/ArduPilot/ardupilot/pull/20555 introduce a weird calculus for log counting. 
https://github.com/ArduPilot/ardupilot/commit/93b55e367e4be5cffa76991bd0340ee1fe6c3109#diff-5308132bb6ab11ef56b79bd165f5808c96e47bc42f1695e59ec3157e8d4e7631R700 
We start with uint16_t smallest_above_last = 0;  and uint16_t thisnum so thisnum is always >=0
So smallest_above_last != 0 is always false and thisnum < smallest_above_last is always false as thisnum cannot be negative and smallest_above_last initialize at 0. Therefor the if test is is always negative and we never set smallest_above_last.
Moreover smallest is never used. 

I don't understand full what the intend was there but the logic tends to show we got an issue.

**Version**
master

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by tridge** [comment]
fixed
