### ISSUE TITLE
Sbus rc input do not work

### ISSUE THREAD

**Issue by NSG-666** [ArduPilot/ardupilot#20713]
## Bug report

**Issue details**

**1.I use a AC900 receiver for my kakutef7mini, and set the RC Input follow below step(select the sbus way), it do not work:**
![image](https://user-images.githubusercontent.com/18585840/167280113-e7c8f98e-123a-4fa8-9ea7-d9c1a85e0d83.png)
![image](https://user-images.githubusercontent.com/18585840/167279259-0e66543d-a3b6-427e-ad17-4143561f6bb3.png)

**2.So i try to go back to the old RC input way, i change the hwdef.h to use EICU to process RC input, it work good:**
![image](https://user-images.githubusercontent.com/18585840/167279520-6c5720c3-42cf-40c5-9015-88f1b71eeb56.png)
![image](https://user-images.githubusercontent.com/18585840/167279840-2e251e6e-10b2-4d1b-b5f8-8a7828b65d3b.png)

**Version**
ardupilot rover 4.1.5

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[*] Rover
[  ] Submarine

**Airframe type**
rover undefined

**Hardware type**
kakutef7mini

**Logs**
1.I use jlink to hardware debug online to see the rc data;
2.This is my hardware system:
![6a389b1b80136b22608bd410ea49b31](https://user-images.githubusercontent.com/18585840/167279971-d50960fe-3f40-4e73-b3df-334ee7841562.jpg)

**Comment by Vkd4U2NtVkZOVg** [comment]
Hi @NSG-666, May I ask you the configuration about the online debug with the cubeide? Is there a way to contact you? maybe a wechat?

**Comment by NSG-666** [comment]
> Hi @NSG-666, May I ask you the configuration about the online debug with the cubeide? Is there a way to contact you? maybe a wechat?

I just use it to debug the elf file.

**Comment by rmackay9** [comment]
I know this is a very old report but we have made some changes to the SBUS support in 4.5.x.  I wonder if you'd be willing to give it a try?

**Comment by peterbarker** [comment]
Ping @NSG-666 - can you test 4.5.x please?

**Comment by peterbarker** [comment]
Closing this one - no response from author.

Would be nice to get feedback.  Please re-open if problems are still present on 4.5.x (or the 4.6 beta)
