### ISSUE TITLE
QGC connected to multi-UAVs cannot be displayed

### ISSUE THREAD

**Issue by YM-98** [ArduPilot/ardupilot#20736]
Ubuntu20.04 QT5.15.2 qgroundcontrol master gazebo
Autopilot firmware: ArduPilot.

I am following the steps of the official website to build a platform, and QT can successfully compile the source code.
Then I open three terminals and type in each：
../Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris -I0 --sysid=1
../Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris  -I1 --sysid=1
../Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris  -I2 --sysid=1
gazebo --verbose iris_ardupilot.world

RESULT:
All of these operations are successful, and the connection is successful.
Running QT to open QGC will automatically connect to a plane, I turned off the auto connection.Add ports 14550, 14560, and 14570 over UDP for communication connections.The connection can be successful when connecting a single UDP, but when connecting multiple UDP, the multi-vehicle mode does not appear, and the UAV icon keeps bouncing on the map, which should be caused by the switching of multiple UAVs.

I do not understand why such a phenomenon occurs, and I failed to solve it by referring to the data. I hope you can help me, thank you very much.

**Comment by rmackay9** [comment]
My guess is the vehicles haven't been setup with unique mavlink system ids so the ground station can't tell them apart.

I'm going to close this because this sounds like a support issue and is unlikely to be related to the flight code, which is what this issues list is for.  Sorry to be strict.
