### ISSUE TITLE
Bug when switch on and off the Bluerov2

### ISSUE THREAD

**Issue by AndreaSchenato** [ArduPilot/ardupilot#20747]
Hi All,

i just bought a BLUEROV2.
When it's all connected and i open QGC i have the video but no communication, i can't operate the ROV.
To re-gain the communication i have to connect the laptop (MACBOOK) directly to the fathom X interface board (in the ROV) and then the communication is ok and everything back to normal. 
When i turn off the ROV i have to do this process again or there is nothing i can do to re establish the full connection.
Only the video is always there stable.

Any idea ?

Thank you
Andrea 

## Bug report

**Issue details**

_Please describe the problem_

**Version**
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by hendjoshsr71** [comment]
Hi! 
This sounds like a user support request and not an ArduPilot software bug report. I'm going to close this issue as we are quite strict about the issues that get opened.

The best place to get help for your BLUEROV2 is from BlueRobotics' discuss forums here: https://discuss.bluerobotics.com/
