### ISSUE TITLE
EKF3 and EKF2 does not without GPS in arduplane

### ISSUE THREAD

**Issue by moreba1** [ArduPilot/ardupilot#20769]
Hi

I noticed that in arduplane EKF3 and EKF2 does not without GPS but it started in arducopter after starting autopilot. i need EKF for calculating accurate roll, pith and yaw in VTOL FW during hovering without GPS . also i think by losing GPS we need EKF.

How can i change the parameters or ardupilot code to enable EKF without GPS ? 

Thanks

**Comment by rmackay9** [comment]
Txs for using AP.  I think you've [created a topic in the support forums](https://discuss.ardupilot.org/t/ekf3-and-ekf2-does-not-without-gps-in-arduplane-20769/85511) which is the right thing to do so I'll close this issue.
