### ISSUE TITLE
STM32F405's Neopixel not working with plane 4.2

### ISSUE THREAD

**Issue by Vkd4U2NtVkZOVg** [ArduPilot/ardupilot#20768]
## Bug report
worked with 4.1.7, worked with master but not 4.2.0
**Issue details**
It's not flashing the correct color

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Comment by MallikarjunSE** [comment]
https://github.com/ArduPilot/ardupilot/issues/20583
Similar?

**Comment by andyp1per** [comment]
Does it work on 4.3-dev?

**Comment by andyp1per** [comment]
Incidentally I tested this on an omnibus F4 pro (F405) and it worked fine for me

**Comment by Vkd4U2NtVkZOVg** [comment]
> Does it work on 4.3-dev
Yes, It is worked with 4.3-dev, could you please tell me which pr fixed it? maybe I can fixed it for myself?

**Comment by Vkd4U2NtVkZOVg** [comment]
> #20583 Similar?
Yes, The led is flashing, but the color is wrong, and It seems only on the STM32F4. I test it with F7 was fine.

**Comment by Vkd4U2NtVkZOVg** [comment]
> #20583 Similar?

Yes, The led is flashing, but the color is wrong, and It seems only on the STM32F4. I test it with F7 was fine.

**Comment by andyp1per** [comment]
You could try this: https://github.com/ArduPilot/ardupilot/pull/20432 it's not the PR I was thinking of, but might be worth trying

**Comment by Vkd4U2NtVkZOVg** [comment]
@andyp1per  thanks a lot! after apply the change from the pr you mentioned, the led works right.

**Comment by andyp1per** [comment]
@rmackay9 FYI

**Comment by rmackay9** [comment]
ok noted.. we can try and get this into Copter/Rover-4.2.1.  I think the boat has sailed on 4.2.0 unless something really serious turns up.
