### ISSUE TITLE
GARMIN LidarLite V2 broken on Cube ORANGE

### ISSUE THREAD

**Issue by patrickpoirier51** [ArduPilot/ardupilot#20778]
This issue has been reported on some occasion on the forum.

_Please describe the problem_
Using type 3 or 15 as rangefinder device and provide sufficient power as per wiki
Distance reading is ok but there are numerous jumps to "9509"   making it unusable.

_What version was the issue encountered with_
Tested with current release 4.1.5 and Beta 4.3.0
Tested with and without pull-up resistors on clk-data
Have similar issue on CUAV NORA
Works flawlessly on PixHawk 2.4.8 

**Logs**
![image](https://user-images.githubusercontent.com/12484190/168600210-a653d03d-f9b2-40df-97f4-be519076c83a.png)

**Comment by tridge** [comment]
randy will test

**Comment by patrickpoirier51** [comment]
Thanks to @rmackay9  for testing.

I decided to order a new Garmin LidarLite and it worked as expected.
Really curious that the old unit works fine with Arduino and STMF3 based FC... but anyway , time to close this bug report

![image](https://user-images.githubusercontent.com/12484190/173825575-43a31527-c7d6-4073-8d7d-43eac59e6452.png)
