### ISSUE TITLE
AP_OSD: add new copter flight modes to FLTMODES array

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20800]
For whatever reason the AP_OSD_ParamSettings.cpp has a list of copter flight mode names in an array but it hasn't been updated recently so it is missing entries for AUTO_RTL  and TURTLE mode.

- [The list of Copter flight modes can be seen here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.h#L15)
- [AP_OSD's flight mode list is here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_OSD/AP_OSD_ParamSetting.cpp#L201)

I suspect the [AUX_OPTIONS array](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_OSD/AP_OSD_ParamSetting.cpp#L187) also needs to be updated and the arrays for other vehicles may also be out of date.

This was reported as part of [Copter-4.2 beta testing](https://discuss.ardupilot.org/t/suggestion-being-able-to-define-an-rtl-approach-path-i-e-approach-rtl/85470/12).

**Comment by andyp1per** [comment]
I forgot about this, will fix.
