### ISSUE TITLE
Rover: Encoder bad timestamp 

### ISSUE THREAD

**Issue by MagicHardware** [ArduPilot/ardupilot#20880]
**Issue details**
https://discuss.ardupilot.org/t/wheel-rate-control-tuning-problem/85863

Ther is a bad timestamp in the encoder code. It should be converted to ms, now it is us. The error affects WRC and EKF. There get wrong rate of wheels. I checked the fix and it seems to work well.

In code:
https://github.com/ArduPilot/ardupilot/blob/e71ced798486bbee47247e1f2c8a15b7b6a6e11f/libraries/AP_WheelEncoder/WheelEncoder_Quadrature.cpp#L141

Should be:
`irq_state.last_reading_ms = timestamp * 1e-3f;`

**Version**
Rover 4.1
Rover 4.2
master

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Airframe type**
Tested on : skid steer rover

**Hardware type**
Tested on: CUAV V5 Plus

**Logs**

**Comment by rmackay9** [comment]
@MagicHardware,

Oh my, yes indeed that looks like a bug.  Thanks very much for finding this.  The timestamp argument is very badly named.  It's a uint32_t so normally that would mean milliseconds.. but it's micros.  thanks again.

**Comment by MagicHardware** [comment]
No problem 😄

**Comment by IamPete1** [comment]
A PR would be great, 

https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html

**Comment by rmackay9** [comment]
This is fixed in master now so closing.  Thanks @MagicHardware!
