### ISSUE TITLE
SERIALx_OPTIONS "don't forward" breaks MAVLink gimbals

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20886]
While working on improving our MAVLink gimbal support (in particular the Gremsy gimbal) I've found that setting SERIALx_OPTIONS = 1024 completely breaks the ability to use mavlink gimbals.  It seems that messages are not being passed between the autopilot and the gimbal once this option is turned on.

This is quite annoying because there are tons of messages sent between the gimbal and autopilot.  Not being able to stop the messages from the gimbal being forwarded to the GCS means the GCS<->autopilot bandwidth is completely consumed by the gimbal mavlink traffic.

After discussing with @peterbarker the issue appears to be that find_by_mavtype() doesn't work because the routing tables are not populated when this SERIALx_OPTION is set.  I confirmed this by bypassing the find_by_mavtype().

Related issue https://github.com/ArduPilot/ardupilot/issues/20723

**Comment by muramura** [comment]
Is it MOUNT_ORIENTATION that is using a lot of bandwidth?
Can you identify the version of the gimbal that is causing this?

GIMBAL SETUP:
https://support.gremsy.com/support/solutions/articles/36000189926-how-to-setup-gremsy-gimbal-with-pixhawk-cube-

**Comment by rmackay9** [comment]
This is fixed in master now so closing.

@muramura, sorry I didn't see your report.  The [setup instructions for the new gremsy driver are here](https://discuss.ardupilot.org/t/ardupilot-4-3-gremsy-gimbal-improvements-testers-wanted/86479).  I'm not sure exactly which messages from the gimbal consume the most bandwidth but I suspect it is the attitude reporting messages.
