### ISSUE TITLE
QUIKTUNE adjusts all axes filters at start

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#20906]
Each axis should be setup as it starts its tune to prevent non tune axes behaviour change while tuning the axis...also this allows tuning single or dual axes without changing param of un-tuned axes ..
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Comment by tridge** [comment]
fixed by #20933
