### ISSUE TITLE
QUIKTUNE script adjusts I on FF axes if P is lowered

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#20904]
I should not be changed if FF is non zero when lowering P in D stage
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

log https://www.dropbox.com/s/fbygyb9ld52q4i7/log_4_2022-6-3-14-16-34.bin?dl=0

**Comment by tridge** [comment]
fixed
