### ISSUE TITLE
Copter: ascending in circle mode ignoring altitude fence limit.

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#20939]
## Bug report

**Issue details**

In circle mode, when throttle is increased, it rises ignoring the fence.
FENCE action is report only.
I raise the vehicle in LOITER mode.
I confirm that the vehicle stops at the altitude fence upper limit altitude.

**Version**

ArduCopter V4.3.0-dev

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

Copter quad

**Hardware type**

SITL

**Logs**
![Screenshot from 2022-06-09 06-59-44](https://user-images.githubusercontent.com/646194/172725641-a6b574e5-2fd3-4f4e-bf98-7979f628390d.png)

**Comment by rmackay9** [comment]
@muramura,

Great, thanks for finding this.  I'm sure the issue is that we are missing a line like this:

```
        // get avoidance adjusted climb rate
        target_climb_rate = get_avoidance_adjusted_climbrate(target_climb_rate);
```

Do you want to create a PR for this?  No pressure of course..

**Comment by muramura** [comment]
@shiv-tyagi san, @rmackay9 san. I could confirm the renovation with SITL. Thanks.
