### ISSUE TITLE
VTX stick menu does not work with HDZERO (and a fix sort of)

### ISSUE THREAD

**Issue by pbreed** [ArduPilot/ardupilot#20955]
## Bug report
The VTX stick menu is not accessible using HDZERO and likely not for ANY vtx using MSP
It is not accessible because the code is not correctly processing VTX MSP requests.

**Issue details**
Three errors, all three need fixed for this to work.
1)Error # 1
Iibraries/AP_MSP/AP_MSP_Telem_Backend.cpp
In the 
void AP_MSP_Telem_Backend::process_incoming_data()
function we have code:
            const uint8_t c = _msp_port.uart->read();
This is an error if you look at libraries\AP_HAL_ChibiOS\UartDriver.h you will see that
    int16_t read() override;
This returns a SIGNED value not an unsinged one.
For certain error conditions it returns -1.
The system should not try and parse -1 so I did this:
			int16_t rv= _msp_port.uart->read();
			if(rv>=0){   
				uint8_t c=rv;
				msp_parse_received_data(&_msp_port, c);
		
            if (_msp_port.c_state == MSP_COMMAND_RECEIVED) {
                msp_process_received_command();
            }

2(Error #2 Why is read returning -1?
\AP_HAL_ChibiOS\UartDriver.cpp
In the function :
ssize_t UARTDriver::read(uint8_t *buffer, uint16_t count)
This ( check  is failing:
    if (lock_read_key != 0 || _uart_owner_thd != chThdGetSelfX()){
        return -1;
    }
 Specifically if I comment out the uart_owener_thd check it works.
 After some more digging .... the core problem is this:
 libraries\AP_OSD\AP_OSD_MSP_DisplatPort.cpp

 bool AP_OSD_MSP_DisplayPort::init(void)
This calls: 		_displayport->init_uart();
Alas this is call in the setup, it is not called from the scope of the thread that will do the processing.
So the uart thread owner is set wrong!
I see two ways to fix this.....
Way #1
I added a _bInitedUart member variable to AP_OSD_MSP_DisplayPort class.
init init I set it to false then in the function
void AP_OSD_MSP_DisplayPort::flush(void)
I added:
    if(!_bInitedUart)
	{
		_bInitedUart=true;
		_displayport->init_uart();
	}

way #2
The other way potentially touches more things but might be a cleaner runtime fix as it eliminates 
an init check every flush cycle.
Add a backend thread_init() function called in 
void AP_OSD::osd_thread()
before it gets into the while loop.

 
 3)Error #3
 Per the MSP V1 specification the packet starts with 
 $M< for packets going to the master
 $M> for packets  coming from the master //I may have this backwards
 and $M! for errors.

 libraries\AP_MSP\msp.cpp 
 bool MSP::msp_parse_received_data(msp_port_t *msp, uint8_t c)
Only handles headers with <

So I changed :
    case MSP_HEADER_M:      // Waiting for '<'
        if (c == '<') {
 to:
    case MSP_HEADER_M:      // Waiting for '<' or '>'
            if ((c == '<') || (c=='>')){ 

These three changes fixed the issue for me and VTX stick menu now works.

**Version**

**Platform**
[X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
All

**Hardware type**
MATEK H743 likelt all STM32 based FC

**Logs**
NA

**Comment by yaapu** [comment]
Thread ownership issue confirmed

**Comment by yaapu** [comment]
Fix proposed here https://github.com/ArduPilot/ardupilot/pull/20997

**Comment by yaapu** [comment]
@pbreed can you please check if the fix solves the issue?
thanks
