### ISSUE TITLE
Copter: support triggering two separate cameras

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#2095]
This would require:
1. a "frontend/backend" split of the camera library.
2. a new aux switch option for "Camera Trigger 2"
3. modify the do-digicam-control to accept a camera instance (at this moment param7 could be used)

**Comment by markwbrown** [comment]
Any progress here?

**Comment by amilcarlucas** [comment]
I think this is now implemented. Can you test ArduCopter 4.4.1 or later?

**Comment by rmackay9** [comment]
This is not actually complete yet but should be soon.

Part1 is done.
Part2 will probably never be done because we will instead rely on GCS buttons.
Part3 is partially done.  The mavlink change is in (https://github.com/ArduPilot/mavlink/pull/328) but we still need to do the ardupilot flight code change

**Comment by rmackay9** [comment]
Part 3 is done in master now so I will close this.
