### ISSUE TITLE
Support Serial control of  Hoverboard controllers for rovers

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot#21044]
Hoverboards can be used as the propulsion system for rovers with just a firmware flash. they are extremely cheap and can be found just about everywhere, you can essentially get 2x motors, 2 wheels, 2x FOC controllers with telemetry, a battery and a charger for 100usd or 20usd if you hunt around for a broken one.
they can be used with a standard RC PWM interface but its very unstable and requires solder modifications to stabilise it.

its serial interface supports 2 channel input for either speed and turning or left and right motor and its telemetry supports: Left speed, Right speed, Voltage and temperature.

https://github.com/EFeru/hoverboard-firmware-hack-FOC

https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/main/Arduino/hoverserial/hoverserial.ino

**Comment by khancyr** [comment]
Aren't hoverboard generally build around VESC ?
