### ISSUE TITLE
Copter: circle mode can't point vehicle at center if CIRCLE_RATE > ATC_SLEW_YAW

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#21098]
As discovered in this [discussion](https://discuss.ardupilot.org/t/strange-behaviour-in-circle-mode/87110/10) if the CIRCLE_RATE is higher than ATC_SLEW_YAW then the vehicle's yaw will not be able to keep pointed at the circle's center.  Most of the time the CIRCLE_RATE is much lower than the ATC_SLEW_YAW so this hasn't been noticed before.

We should probably do one of the following:

1. add a note to the CIRCLE_RATE parameter description <-- I think I like this idea best
2. limit the CIRCLE_RATE to be no more than ATC_SLEW_YAW (I'm not a fan of this idea)
3. print a warning to the user when they enter circle mode for the first time that CIRCLE_RATE is too high
4. add a pre-arm check in the parameter section

**Comment by timtuxworth** [comment]
Number 3 and/or 4 could be implemented in Lua script - so they can be enabled/disabled without being baked into the firmware. I have a draft PR for this concept here https://github.com/ArduPilot/ardupilot/pull/20930

**Comment by mohitkenia7** [comment]
Hi 
I want to work on this

**Comment by mohit-marathe** [comment]
Hey @rmackay9, I'm new here and want to work on this issue. Can you help me with where I should get started?

**Comment by Bhawna1203** [comment]
Hii,
I am working on this issue
