### ISSUE TITLE
ChibiOS: add ethernet support

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#21101]
## Feature request

**Is your feature request related to a problem? Please describe.**

FMUV5X and FMUV6X implement Ethetnet devices.
RASPBERRY PI and FC are connected via UART.
RASPBERRY PI uses MAVPROXY and the internal application uses TCP/IP for telemetry communication.

**Describe the solution you'd like**

If FC Ethernet communication is available, faster communication than UART is possible.
Also, if ETHERNET communication is available, we can build an intranet for drones.
Please support Ethernet communications.

**Describe alternatives you've considered**

None

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
![IMG-8964](https://user-images.githubusercontent.com/646194/176991745-a74bd73b-b23e-4cc0-9aeb-d2e0d84b2bae.jpg)
![IMG-8966](https://user-images.githubusercontent.com/646194/176991748-f54b9db4-630e-44ba-8cc5-b2de12dd46d9.jpg)

**Comment by timtuxworth** [comment]
This is my blog post about UARTs - which asks the question, why are we not using more modern, reliable, faster, bus based communications like Ethernet (among others). https://timtheplaneman.com/uarts-on-flight-controllers-huh/

**Comment by muramura** [comment]
UART is specified for connection to companion computers and telemetry devices.
These devices are connected at 921600 bps or faster.
115200 bps was a few years ago.

Companion Computers
https://ardupilot.org/dev/docs/companion-computers.html

**Comment by rmackay9** [comment]
Yes, we have work that's ongoing to add ethernet support to ArduPilot for the STM32 based autopilots (the Linux flight controllers already support ethernet).  I suspect that will be included in 4.3 although I can't 100% guarantee that.

**Comment by muramura** [comment]
Thanks for the comment, I appreciate it.

**Comment by magicrub** [comment]
The Ethernet code that @bugobliterator and I are working on have significant changes. I don't think it will make it into 4.3 in time.

**Comment by timtuxworth** [comment]
It will be great to have it whenever it's ready!

**Comment by Ryanf55** [comment]
> The Ethernet code that @bugobliterator and I are working on have significant changes. I don't think it will make it into 4.3 in time.

Do you think it could make 4.5 so it can be used in DDS by #23283?

**Comment by peterbarker** [comment]
We have ethernet support now.
