### ISSUE TITLE
ArduCopter OMNIBUSF7V2-bdshot fails to link multiple definition of `VectorA0'

### ISSUE THREAD

**Issue by freddybloggs** [ArduPilot/ardupilot#21119]
## Bug report

**Issue details**
./waf copter causes OMNIBUSF7V2-bdshot fail to link compiles fine but fails to link OMNIBUSF7V2 links okay MatekF765-SE links ok
OSX gcc etc all up to date 

_Please describe the problem_
when building the bdshot version of OMNIBUSF7V2 for arducopter ie ./waf configure --board=OMNIBUSF7V2-bdshot then ./waf copter I get :-

[786/789] Linking build/OMNIBUSF7V2-bdshot/bin/arducopter
modules/ChibiOS//libch.a(stm32_isr.o): In function `VectorA0':
/Volumes/Pseudopolis/Copter/32STM/Ardu/ardupilotstig3/build/OMNIBUSF7V2-bdshot/../../modules/ChibiOS/os/hal/ports/STM32/LLD/TIMv1/stm32_tim1_9_10_11.inc:223: multiple definition of `VectorA0'
modules/ChibiOS//libch.a(hal_eicu_lld.o):/Volumes/Pseudopolis/Copter/32STM/Ardu/ardupilotstig3/build/OMNIBUSF7V2-bdshot/../../modules/ChibiOS/os/hal/ports/STM32/LLD/TIMv1/hal_eicu_lld.c:461: first defined here
common.ld:201 cannot move location counter backwards (from 0000000008109660 to 0000000008100000)
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/Volumes/Pseudopolis/Copter/32STM/Ardu/ardupilotstig3/build/OMNIBUSF7V2-bdshot'
Build failed
 -> task in 'bin/arducopter' failed (exit status 1): 
	{task 4446625104: cxxprogram AP_Arming.cpp.45.o,AP_Rally.cpp.45.o,AP_State.cpp.45.o,Attitude.cpp.45.o,Copter.cpp.45.o,GCS_Copter.cpp.45.o,GCS_Mavlink.cpp.45.o,Log.cpp.45.o,Parameters.cpp.45.o,RC_Channel.cpp.45.o,UserCode.cpp.45.o,UserParameters.cpp.45.o,afs_copter.cpp.45.o,autoyaw.cpp.45.o,avoidance.cpp.45.o,avoidance_adsb.cpp.45.o,baro_ground_effect.cpp.45.o,commands.cpp.45.o,compassmot.cpp.45.o,crash_check.cpp.45.o,ekf_check.cpp.45.o,esc_calibration.cpp.45.o,events.cpp.45.o,failsafe.cpp.45.o,fence.cpp.45.o,heli.cpp.45.o,inertia.cpp.45.o,land_detector.cpp.45.o,landing_gear.cpp.45.o,mode.cpp.45.o,mode_acro.cpp.45.o,mode_acro_heli.cpp.45.o,mode_althold.cpp.45.o,mode_auto.cpp.45.o,mode_autorotate.cpp.45.o,mode_autotune.cpp.45.o,mode_avoid_adsb.cpp.45.o,mode_brake.cpp.45.o,mode_circle.cpp.45.o,mode_drift.cpp.45.o,mode_flip.cpp.45.o,mode_flowhold.cpp.45.o,mode_follow.cpp.45.o,mode_guided.cpp.45.o,mode_guided_nogps.cpp.45.o,mode_land.cpp.45.o,mode_loiter.cpp.45.o,mode_poshold.cpp.45.o,mode_rtl.cpp.45.o,mode_smart_rtl.cpp.45.o,mode_sport.cpp.45.o,mode_stabilize.cpp.45.o,mode_stabilize_heli.cpp.45.o,mode_systemid.cpp.45.o,mode_throw.cpp.45.o,mode_turtle.cpp.45.o,mode_zigzag.cpp.45.o,motor_test.cpp.45.o,motors.cpp.45.o,navigation.cpp.45.o,precision_landing.cpp.45.o,radio.cpp.45.o,sensors.cpp.45.o,standby.cpp.45.o,surface_tracking.cpp.45.o,system.cpp.45.o,takeoff.cpp.45.o,terrain.cpp.45.o,toy_mode.cpp.45.o,tuning.cpp.45.o -> arducopter}
 (run with -v to display more information)

**Version**
_What version was the issue encountered with_
4.30dev git pull 05072022

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
quad
**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
OMNIBUSF7V2
**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by andyp1per** [comment]
Apologies, we could never get bdshot to work on this board and they are no longer making them so I was unable to source a board - so it is essentially unsupported and we won't be fixing.
