### ISSUE TITLE
Official Firmware List

### ISSUE THREAD

**Issue by billbonney** [ArduPilot/ardupilot#2118]
Currently in apm_planner project we only provide easy install of the current stable and the next beta release. What we really need is a list of official stable firmware release and locations so they can be easily downloaded by the user and installed

**Comment by gmorph** [comment]
Hi Bill.  How would you like the list.  Some kind of XML format with release version and filename and location on the server?  
Other suggestions welcome.
Thanks, Grant.

**Comment by malcom2073** [comment]
Something I stumbled upon when I was trying to figure out if there was such a list, https://github.com/diydrones/ardupilot/releases
If you upload the hex files associated with those tags and make them actual "releases", then there's already a github api to grab that information, as well as links to the hex files on github.

**Comment by peterbarker** [comment]
I think this solves the initial request: http://firmware.ap.ardupilot.org/manifest.json.gz
