### ISSUE TITLE
Cant Perform Compass Calibration

### ISSUE THREAD

**Issue by r1gron9** [ArduPilot/ardupilot#21225]
## Bug report

**Issue details**

Can't perform normal compass calibration.
when clicking 'start' nothing happens. 
Large vehicle calibration is working.

**Version**
4.2.0-beta1

**Platform**
[  ] All
[X] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Antenna Tracker

**Hardware type**
Cube Orange

**Logs**

**Comment by IamPete1** [comment]
Manually disarm the vehicle.
