### ISSUE TITLE
Unstable braking (yaw spin) after cruising in POSHOLD at over 60 km/h

### ISSUE THREAD

**Issue by andrefreitas97** [ArduPilot/ardupilot#21250]
## Bug report

**Issue details**

Yesterday I decided to test the max speed of my quadcopter while cruising in POSHOLD trying different angle_max settings. When I tested at 30º of angle max I was achieving over 60kmh in straigh line but then a problem appeared. I noticed that sometimes at this speed if I released the pitch stick the drone would not brake smoothly but instead do what seemed to be an uncontroled yaw spin (~180º) and then stabilize.

I would expect the drone to brake "smoothly", keeping its current heading without the unexpected yaw spin.

I suspected the culprit may be the PID settings of my build: 5 inch drone with ~850g. I tried increasing P values in all axis but with no success. Someone also sugested me the problem could be magntometer interference but i am not sure how to check this in the log file. This said, I am not sure what is the true source of the problem and would like to know if anyone already faced this problem and how to solve it.

**Version**
4.2.2

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Logs**
https://mega.nz/file/EYZ0nQwT#sLnq6TH9vOX2pltlzgv-PRDbd-f4M2I02AYFNtXr44M

**Comment by IamPete1** [comment]
Looks like motor saturation on the lower limit. There is quite a big pitch imbalance in hover, make sure your GC is in the middle. 

In anycase this is not the place for setup issues, post over on the forum. https://discuss.ardupilot.org/ Some pictures of the vehicle might help diagnose the issue too.
