### ISSUE TITLE
Using 20 hz GPS 

### ISSUE THREAD

**Issue by moreba1** [ArduPilot/ardupilot#21351]
Hi 

I will use a 20 HZ CUAV GPS . I Connected it and it works but i will increase input data rate to 20 hz . in parameters GPS_RATE_MS has 5 HZ , 8 HZ and 10 hz . can i set it manually to 20 hz ? Will there be any problem with EKF? what is meaning of "impact performance" in this text (increase or decrease) ?

GPS_RATE_MS:
"Controls how often the GPS should provide a position update. Lowering below 5Hz(default) is not allowed. Raising the rate above 5Hz usually provides little benefit and for some GPS (eg Ublox M9N) can severely impact performance."

**Comment by amilcarlucas** [comment]
This is a support question, not a bug. Please post support questions on the forum, where it belongs.
