### ISSUE TITLE
AP_Param::set_float fails for big values on AP_Int32 parameters

### ISSUE THREAD

**Issue by mentonin** [ArduPilot/ardupilot#21364]
## Bug report

**Issue details**

Setting a very large (close to or over 2^31) value to an `AP_Int32` parameter escapes the bounds check and causes `Arithmetic exception`.

It looks like values are first constrained as `float`s, then converted to `int32_t`. Values close to or larger than 2^31 are restricted to 2.14748365e+09 (after rounding) instead of 2147483647.0, and then failing to cast to `int32_t`

This can be triggered by changing any `AP_Int32` parameter on MAVProxy Parameter Editor to a value larger than 2^31

**Version**
_What version was the issue encountered with_

**Platform**

[XX] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
SITL

**Comment by IamPete1** [comment]
https://github.com/ArduPilot/ardupilot/issues/20784
