### ISSUE TITLE
Copter: pre-arm check that throttle is high should be skipped if arming in Auto

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#21415]
AP_Arming_Copter::arm_checks() skips over the pilot's throttle position checks if arming in Guided mode from a GCS.  I think we can also skip these checks if the vehicle is arming in Auto mode.  [See code here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/AP_Arming.cpp#L633).

**Comment by AltonNewbie** [comment]
Can ardu be used in conjunction with NVIDIA JETSON NANO for a lawn mower installation so it will (Recognize obstacles with cams/sensors on nvidia side and ai memorize mowing around object?
Though I first load mowing parameters (object stop it) I feel nvidia takes over to go around object and back in line with ardu parameters to continue mowing.
Plus I would code in the nvidia to identify all objects for safety.  If dog or human approaches, power off mower “UNTIL” HUMAN OR ANIMAL IS ATLEAST 40 FEET AWAY FROM MOWER.
PLEASE ADVISE..
ALTON


Smart AssistAlton D Davis Jr483 LAMKIN RDHARLEM GA 30814.     (770) 651-7009. [10am -10pm Eastern]

On Friday, August 12, 2022, 1:56 AM, Randy Mackay ***@***.***> wrote:




AP_Arming_Copter::arm_checks() skips over the pilot's throttle position checks if arming in Guided mode from a GCS. I think we can also skip these checks if the vehicle is arming in Auto mode. See code here.

**Comment by agising** [comment]
Thumbs up, I want this feature. Actually in my checklist I have 'throttel to mid-stick" prior to gcs takeoff

**Comment by magicrub** [comment]
looks like @prathamesh7255 has a fix for this in PR https://github.com/ArduPilot/ardupilot/pull/22676

**Comment by khancyr** [comment]
We got to PR that are the same and work, but it need some param change : 
AUTO_OPTIONS 1 to allow arming
RC_OPTIONS 32 to disable throttle arming check on RC lib.

**Comment by rmackay9** [comment]
Opps, @khancyr you think the earlier PR isn't sufficient?

**Comment by khancyr** [comment]
It is needed but that isn't enough on its own as the rc_options check will trigger  but that is just param so the PR was good
