### ISSUE TITLE
create_terrain.py does not work on windows

### ISSUE THREAD

**Issue by Rand0409** [ArduPilot/ardupilot#21449]
## Bug report

**Issue details**

Using create_terrain.py with "python .\create_terrain.py --lat=40.776676 --lon=-73.971321 --radius=1 --spacing=30", after several minutes downloading, the .DAT file size reached 31724KB, and the (lat_e7, lon_e7) in function create_degree reached to (41, -74). The script stopped downloading, and started looping "waiting on downloading of 41,-74". 
Should it be stopped automatically or forever loop?   
The tile value seems equals 0 forver, I also tried --test arguments, same looping result "waiting of download of 41, -71" was obtained.

**Version**
latest create_terrain.py code from github  AP_TERRAIN/tool/create_terrain.py

**Platform**
Windows 11, python3

**Airframe type**
no drone used yet

**Hardware type**
no hradware used yet, only on windows

**Logs**
a clip of the outputs
e7 set 409998306 -739964293
e7 set 409998306 -739960722
e7 set 409998306 -739957152
e7 set 409998306 -739953581
e7 set 409998306 -739950010
e7 set 409998306 -739946439
e7 set 409998306 -739942869
e7 set 409998306 -739939298
e7 set 409998306 -739935727
e7 set 409998306 -739932156
e7 set 409998306 -739928586
e7 set 409998306 -739925015
e7 set 409998306 -739921444
e7 set 409998306 -739917873
e7 set 409998306 -739914303
e7 set 409998306 -739910732
e7 set 409998306 -739907161
e7 set 409998306 -739903590
e7 set 409998306 -739900020
e7 set 409998306 -739896449
e7 set 409998306 -739892878
e7 set 409998306 -739889307
e7 set 410001001 -740000000
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0
waiting on download of 41,-74
0

**Comment by stephendade** [comment]
You may need to install the latest version of MAVProxy (1.8.54), as some of the terrain support libraries have been changed recently.

**Comment by Rand0409** [comment]
> 

I will try that, thank you!

**Comment by Rand0409** [comment]
> 

Hi I tried with 1.8.54 version MAVProxy, still same issue happens

**Comment by stephendade** [comment]
Ahh, just realised that you're using Windows. I've now confirmed that ``create_terrain.py`` doesn't work on Windows.

We do have an online terrain server at https://terrain.ardupilot.org/

**Comment by Rand0409** [comment]
Hi,  I will try on Ubuntu, thank you very much!

**Comment by Rand0409** [comment]
It is now working properly on Ubantu, python2, MAVProxy 55 version
