### ISSUE TITLE
hwdef/KakuteH7: RSSI_ADC PIN 8 broken in latest dev builds

### ISSUE THREAD

**Issue by Nutz-E** [ArduPilot/ardupilot#21452]
## Bug report
**Issue details**
Kakute H7 v1.2: RSSI ADC PIN 8 has become undefined in latest dev builds.  KakuteH7-bdshot.

I suspect it is caused by the updated KakuteH7v2 hwdef addtion.
./ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7v2.

Should the current hwdef "KakuteH7v2" actually be named "KakuteH7-bdshot" (it includes BIDIR's for PWM 5-8)?
Should the include for "KakuteH7v2" be "include ../KakuteH7/hwdef.dat" and not 
"include ../KakuteH7-bdshot/hwdef.dat"?
Referring to this hardware rev v1.2 board as "V2" might create naming challenges if/when the hardware rev becomes v2.0. 

**Version**
Latest Dev

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quad

**Hardware type**
Kakute H7 v1.2

**Comment by andyp1per** [comment]
I just tried both KakuteH7 and KakuteH7-bdshot - both have RSSI pin 8 defined

v2 is an actual board that is about to be released by Holybro
