### ISSUE TITLE
The UART3 serial port in CUAV Nora is not functional

### ISSUE THREAD

**Issue by maciek252** [ArduPilot/ardupilot#21468]
## Bug report

The UART3 serial port (the one on the longer side) in CUAV Nora is not functional. The discussion is here:
https://discuss.ardupilot.org/t/nora-serial-port-numbering/73906/9
(it was mentioned in the final post that this issue will be fixed in the new firmware, but it has not been so far)

**Version**
4.2.0 and later

**Platform**
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by maciek252** [comment]
After submitting I've found this one:

https://github.com/ArduPilot/ardupilot/pull/20395

but I can't see this fix mentioned in the release notes, and the port is still not functional in 4.2.2

**Comment by peterbarker** [comment]
No answer from original author, and I'd be astonished if this port wasn't functional.

Closing this one now - feel free to re-open if the port doesn't work on 4.5.7 (or the 4.6 beta)
