### ISSUE TITLE
request for target : copter Cuav Nora bdshot

### ISSUE THREAD

**Issue by maciek252** [ArduPilot/ardupilot#21463]
## Feature request

Adding the bidirectional (bdshot) option for the Cuav Nora flight controller.

On an X8 copter, I cannot get working neither the blheli_32 telemetry nor the passtrough. I'm using the Tekko 32 F4 ESCs with the latest 32.9 blheli_32 version.

I would be interested in adding the bidirectional (bdshot) option to enable the telemetry at least.

I've tried the serial-based blheli telemetry but it used to be unreliable for the earlier versions of AP and/or blheli_32, and for the most recent versions it does not work at all.

link to the forum:
https://discuss.ardupilot.org/t/bdshot-option-in-the-custom-firmware-builder/89019/2

[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by peterbarker** [comment]
We have a bdshot target for this board now.
