### ISSUE TITLE
Copter: precision landing initialised with hard-coded 400hz update rate

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#21523]
Copter initialises the precision landing object with a hard-coded 400hz update rate ([see code here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/precision_landing.cpp#L11)).  This is incorrect if the scheduler's main loop rate is lowered below 400.

**Comment by rmackay9** [comment]
Sorry, this is not a bug because it is handled inside of AC_PrecLand::init()

**Comment by khancyr** [comment]
I think this is still necessary to run the mini ekf with IRLock
