### ISSUE TITLE
Tools: install scripts for ubuntu needs to include install of dronecan

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#21538]
New installs apparently need the python "dronecan" package to be installed or else a "No module named 'dronecan" appears when the user first tries to compile.  This should be included in the environment install scripts for ubuntu and perhaps other environments as well.

https://github.com/ArduPilot/ardupilot/blob/master/Tools/environment_install/install-prereqs-ubuntu.sh

![image](https://user-images.githubusercontent.com/1498098/186582631-549136d3-65ef-45da-8445-7860e8871de7.png)

**Comment by khancyr** [comment]
What were you trying to build ? 
It looks like our env tester do catch this

**Comment by rmackay9** [comment]
@khancyr,

I was running this on my Windows11 machine's WSL2 environment.

**Comment by khancyr** [comment]
I don't have dronecan and it is working fine on my side to build SITL.
What target you are building ? SITL ?
We should surely add dronecan but I would like to know what lead to trigger this error to add it to test suite

**Comment by rmackay9** [comment]
@khancyr,

txs. I was running sim_vehicle.sh..

**Comment by khancyr** [comment]
I cannot reproduce with `sim_vehicle.py -v ArduCopter `

**Comment by rmackay9** [comment]
@khancyr, Perhaps it only happens with a fresh install?  .. or a distclean?  I'm not sure but the issue certainly happened because the evidence is above.

**Comment by khancyr** [comment]
ok we need to add it. I manage to reproduce on SITL. 
AP_OpenDroneID support make it mandatory.

**Comment by LouisRenWeiWei** [comment]
dronecan==1.0.8
