### ISSUE TITLE
ImmersionRC Ghost Support

### ISSUE THREAD

**Issue by NulliFieDFPV** [ArduPilot/ardupilot#21588]
## Feature request
Hi,  I am using tue Ghost Eco system and would love to use It's protocol in Ardupilot, too. Right now I am using s.bus but want to change to a bidirektional configuration. Sadly srxl2 doesnt work in my setup for some reason.

**Platform**
[ X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

 Thx!

**Comment by andyp1per** [comment]
I've not been able to get equipment, but it's now back in stock

**Comment by peterbarker** [comment]
We have Ghost support now-adays.  Closing this one.
