### ISSUE TITLE
AC3.3 control_althold.pde should check EKF's altitude state

### ISSUE THREAD

**Issue by John-Ingersoll** [ArduPilot/ardupilot#2160]
ArduCopter AC_PosControl::update_z_controller uses the filter's _inav position and velocity component s to help control altitude.  The althold_init function makes no checks to see that the _inav object has a good solution for altitude prior to entrance.  Typically the Altitude is OK since there is the inertial, baro, and sonar altitudes to constrain any errors.

I have had several crashes where the EKF maxed out the Z bias (bad cal maybe) and VD went to crap but there was no negative indication on the vehicle at the time AltHold was entered.  The latest 3.3-RC1 seems to notify this with the red-yellow indicators but they were not present at the time of these crashes so may be deficient.

In the crashes, the hexacopter was flown in stabilize without issue and then immediately upon entrance to AltHold it turned off the motors on the first flight  and dropped 6 ft to the ground, had a hick-up on on entrance alt hold on the second flight that was recoverable, shot straight up 40 ft into the ceiling of the closed arena I was in on the third flight with catastrophic consequences.

VD cannot exceed vehicle dynamics and could be used as a check as well.  Can't fall faster than terminal velocity and can't rise faster than motors carry you.  The VD parameter had integrated off to 150m/s

Solution:
Add Position_OK type checks to Althold_init to ensure Alt and VD are not crazy.
Add EKF Checks to look at valid ZBias estimates (not railed).

**Comment by lthall** [comment]
I am sure this has been done now.
