### ISSUE TITLE
Latest firmware won't work with the Matek F405 WTE Flight Controller

### ISSUE THREAD

**Issue by Isaac542** [ArduPilot/ardupilot#21649]
## Bug report

**Issue details**
I am flashing the Matek F405 TE firmware, which is recommended by the manufacturer. I can connect to the board right after flashing but if I disconnect it from USB and plug it back in the board is not recognized by my computer. There is no issue with the board it works just fine with INav firmware.

**Version**
4.2.3
I have also tried other versions with no luck.
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Vtol
**Hardware type**
Matek F405 WTE
**Logs**

**Comment by adalta87** [comment]
Did you flash thr firmware with the bootloader usually xxxx_bl.hex

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Isaac542 ***@***.***>
Sent: Tuesday, September 6, 2022 1:03:25 PM
To: ArduPilot/ardupilot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ArduPilot/ardupilot] Latest firmware won't work with the Matek F405 WTE Flight Controller (Issue #21649)


Bug report

Issue details
I am flashing the Matek F405 TE firmware, which is recommended by the manufacturer. I can connect to the board right after flashing but if I disconnect it from USB and plug it back in the board is not recognized by my computer. There is no issue with the board it works just fine with INav firmware.

Version
4.2.3
I have also tried other versions with no luck.
Platform
[ ] All
[ ] AntennaTracker
[ ] Copter
[ x] Plane
[ ] Rover
[ ] Submarine

Airframe type
Vtol
Hardware type
Matek F405 WTE
Logs

**Comment by Isaac542** [comment]
I was using the hex file with no bootloader before. I tried it and it works with the bootloader file. Thanks for the help.
