### ISSUE TITLE
Rover: how to simulate the newly added dock mode

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#21657]
Can we use the simulated environment to guide the vehicle to a given position and direction by setting a point and direction？

**Comment by rmackay9** [comment]
This is for @shiv-tyagi to answer I think.  As a side note, this question should really be in the [Rover forum](https://discuss.ardupilot.org/c/ardurover/rover42/162)..

**Comment by xianglunkai** [comment]
I'm sorry. I'll pay attention
