### ISSUE TITLE
The airspeed meter of msp protocol does not work

### ISSUE THREAD

**Issue by Lance0724** [ArduPilot/ardupilot#21778]
## Bug report
The airspeed meter of msp protocol does not work

**Issue details**
When I tried to use the msp protocol airspeed meter, I ran into a problem while testing it on the ground.

The airspeed meter of the msp protocol sends the air pressure difference normally.

However, the airspeed displayed in GCS can only be displayed normally for a few seconds, then it will become 0 and then continue to display the effective value and then become 0, repeating.

The same msp airspeed meter works fine in inav. I also checked the code of the airspeed meter, and debugged the msp output, and did not see any problem.

I am using the protocol of msp v2.
https://github.com/gioclava/barometer

**Version**
Plane-4.2.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ 1 ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
flying wing

**Hardware type**
MatekF405WING

**Logs**

**Comment by yaapu** [comment]
Can you give more details about your setup?
Are you polling for 0x1F06 frames?

**Comment by Lance0724** [comment]
> 

There is no polling from airspeed's meter.
Just only send 0x1F06 frames.

What is the correct working sequence between the MSP's airspeed meter and the flight controller(ardupilot)?

I don't know much about how to interact correctly, and I can't find any relevant information.

Regards.

**Comment by yaapu** [comment]
That's correct you can't poll for that sensor, Ardupilot can consume it if using an external MSP Airspeed sensor running AP_periph.
What is your setup? Which devices are you using, how are they connected and please provide a dump of your related params

**Comment by Lance0724** [comment]
I'm trying to make a msp protocol airspeed sensor, but not based on AP_periph, because the MCU is ESP8285.

This airspeed sensor is developed based on esp8285. After esp8285 obtains the air pressure difference through the sensor, it pushes the air pressure difference and temperature to the flight controller through the serial port using the msp protocol.

Then I can see the airspeed value calculated by the flight controller through the mission plan, but the displayed airspeed value will change to 0 after a few seconds, and then the displayed value will change back to 0 again, and so on repeat.

**Comment by yaapu** [comment]
Ok I see, this is not an issue but rather a support request for developing a new MSP Airspeed sensor :-)

**Comment by yaapu** [comment]
What I would do is flash a board with AP_Periph, enable Airspeed over MSP, trace the output and compare

**Comment by Lance0724** [comment]
Thanks very much for the time your put into this.
I really can't find where the problem is, I also read some code about msp in ardupilot, but my ability is very limited.

**Comment by yaapu** [comment]
I built latest master MatekF405-Wing copter and plane that outputs some debug about MSP AirSpeed data, by looking/tweaking the code you should be able to debug your issue.

https://github.com/yaapu/ardupilot/blob/938df192fa5eaccfb97fc340c8eace4e3d41774b/libraries/AP_Airspeed/AP_Airspeed_MSP.cpp#L38-L67

[matekf405-wing_msp_arspd_debug.zip](https://github.com/ArduPilot/ardupilot/files/9767040/matekf405-wing_msp_arspd_debug.zip)

**Comment by yaapu** [comment]
for this kind of dev support you should really use discord :-)

**Comment by Lance0724** [comment]
The problem is that the msp sending frequency of the airspeed meter module is too low. 
There is no problem if the sending frequency is increased.
This issue can be closed.

@yaapu  Thanks again for your support，
