### ISSUE TITLE
AP_GPS: Auto baud detection broken for SBF, Novatel, GSOF, SITL

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#21771]
## Bug report

Auto baud detection for the GPS units that don't have detection is broken. It looks like from e858a0fab70

What happens is it continually detects at the same baud rate the whole time, and fails to cycle the array as it should. What you should see on a working unit if you set `GPS_TYPE` 15 (novatel), and don't have anything connected is a status text every 4 seconds that looks like `GPS 1: detected as NOVA at 9600 baud` and then 4 seconds later the baud should be different.

**Version**
eed638c237c7f

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Novatel, Septentrio, GSOF, SITL

**Comment by peterbarker** [comment]
This patch:

```
diff --git a/libraries/SITL/SIM_GPS.cpp b/libraries/SITL/SIM_GPS.cpp
index 5e45104178b..183c4d15364 100644
--- a/libraries/SITL/SIM_GPS.cpp
+++ b/libraries/SITL/SIM_GPS.cpp
@@ -57,6 +57,24 @@ GPS::GPS(uint8_t _instance) :
 #endif
 }
 
+uint32_t GPS::device_baud() const
+{
+    switch ((Type)_sitl->gps_type[instance].get()) {
+        case Type::NOVA:
+            return 19200;
+        case Type::NONE:
+        case Type::UBLOX:
+        case Type::NMEA:
+        case Type::SBP:
+        case Type::SBP2:
+#if AP_SIM_GPS_FILE_ENABLED
+        case Type::FILE:
+#endif
+            return 0;  // 0 meaning unset
+    }
+    return 0;  // 0 meaning unset
+}
+
 /*
   write some bytes from the simulated GPS
  */
diff --git a/libraries/SITL/SIM_GPS.h b/libraries/SITL/SIM_GPS.h
index dd2fa3d0f3e..ccf104af7cd 100644
--- a/libraries/SITL/SIM_GPS.h
+++ b/libraries/SITL/SIM_GPS.h
@@ -68,6 +68,8 @@ public:
 
     ssize_t write_to_autopilot(const char *p, size_t size) const override;
 
+    uint32_t device_baud() const override;  // 0 meaning unset
+
 private:
 
     uint8_t instance;
```

on top of https://github.com/ArduPilot/ardupilot/pull/21810 recreates this problem.
