### ISSUE TITLE
Getting "Sending unknown message (50) " continously on 4.3.0 custom build

### ISSUE THREAD

**Issue by Ltomi78** [ArduPilot/ardupilot#21817]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**
I ve got information from Randy Mackay the reason is there is a coding error in this line in custom fw.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L5752
_Please describe the problem_
I upload 4.3.0 custom build fw https://custom.ardupilot.org/ and now getting this message continously: 
"Sending Unknown message (50)"
Setup is: Fc matek f405 wing + gps and compass
**Version**
4.3.0 build with custom fw builder for matek f405 wing target 

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
flying wing

**Hardware type**
_What autopilot hardware was used? 
Matek F405 wing

**Logs**
_Please provide a link to any relevant logs that show the issue_
![received_2193420617483978](https://user-images.githubusercontent.com/34459398/192491171-bfbda702-a398-4c36-8425-c6ca909fa3c9.jpeg)
https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L5752

**Comment by macfly1202** [comment]
I have this error on MATEK F405 target too, with custom firmware ArduPlane V4.3.0dev (f9bc7e44). 
Displayed on DJI FPV OSD. 

![Capture](https://user-images.githubusercontent.com/6387630/192881719-3ede4c1c-1a81-4893-86f4-7ed07ac34bab.PNG)

**Comment by IamPete1** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/21828

**Comment by Ltomi78** [comment]
> I have this error on MATEK F405 target too, with custom firmware ArduPlane V4.3.0dev ([f9bc7e4](https://github.com/ArduPilot/ardupilot/commit/f9bc7e44f85266abd66fe59a93d0e75de3a7b645)). Displayed on DJI FPV OSD.
> 
> ![Capture](https://user-images.githubusercontent.com/6387630/192881719-3ede4c1c-1a81-4893-86f4-7ed07ac34bab.PNG)

 Today the devs fixed it...you can build a 4.4.0 dev from the builder without this issue😉
![received_756605252070822](https://user-images.githubusercontent.com/34459398/192900945-5e10634a-a83b-49ef-b6b2-edaec0620862.jpeg)
