### ISSUE TITLE
Do not allow copies can use CLASS_NO_COPY() macro

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#21837]
A search for "Do not allow copies" in the code turns up a number of places where we could use the CLASS_NO_COPY() macro.  This would be a non-functional change.

- ArduCopter/AP_Arming.h
- ArduCopter/AP_Rally.h
- ArduCopter/avoidance_adsb.h
- ArduPlane/AP_Arming.h
- ArduPlane/avoidance_adsb.h
- ArduPlane/mode.h
- Blimp/AP_Arming.h
- etc, etc

**Comment by jackhong12** [comment]
Hi @rmackay9, I would like to take a look at this issue. Could you assign this issue to me?

**Comment by rmackay9** [comment]
@jackhong12,

Sure, thanks!

**Comment by shiv-tyagi** [comment]
@rmackay9 The PR linked with this issue has been merged. Can we close it now?

**Comment by rmackay9** [comment]
yes, closing, thanks!
