### ISSUE TITLE
AP_Proximity/AP_Airspeed: uart::read() returns int16_t

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#21836]
A number of drivers are using the incorrect return type when calling uart::read()

- AP_AirSpeed_NMEA (uses char)
- AP_Proximity_Cygbot_D1 (uses uint8_t)
- AP_Proximity_RPLidarA2 (uses uint8_t)
- AP_Proximity_TeraRangerTower (uses char)
- AP_Proximity_TeraRangerTowerEvo (uses char)

**Comment by i-m-karanagarwal** [comment]
Is this issue Still open to contribute? If yes, please assign it to me.

**Comment by hendjoshsr71** [comment]
Yes, it is still open I think. I've assigned it to you.

Thank you for your efforts!

**Comment by i-m-karanagarwal** [comment]
Hy @hendjoshsr71, could you refer to the file where _uart might be defined?
