### ISSUE TITLE
AUTOTUNE: CPU FAILed and crashed while performing AUTOTUNE at SITL

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#21853]
## Bug report

**Issue details**

I performed an AUTOTUNE of QUADCOPTER for RF on ArduPilot at SITL.
The vehicle crashed during the execution.
I looked at the log.
In this log, there was an error "CPU: Failed to init".

![Screenshot from 2022-10-02 10-27-03](https://user-images.githubusercontent.com/646194/193434386-5d09b821-c23d-47d8-8ed5-64c290b2e1d8.png)

The AUTOTUNE function includes a process to FAIL the CPU.

**Version**

ArduCopter V4.4.0-dev (c566937f)

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

QUADCOPTER

**Hardware type**

SITL

**Logs**

**Comment by peterbarker** [comment]
OK, so those init strings didn't existin in 3.6, let along modern-stable.

I think we have to close this one; certainly the error can't happen anymore as written.

Please open a fresh issue if you ever see this again on a modern autopilot.

Thanks for the report, but closing this one.
