### ISSUE TITLE
Copter: RC not found pre-arm if only RC_OVERRIDES are used

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#21921]
Testing latest Cotper-4.4.0-dev I've found that if only a joystick is used (from MP, aka RC_OVERRIDES) then a pre-arm failure appears, "PreArm: RC not found".  I can see the RC values changing in MP's Setup >> RC Calibration screen and RC failsafes are triggered or cleared as the joystick is enabled or disabled.

![image](https://user-images.githubusercontent.com/1498098/194707499-40ab4b43-e08c-4438-aa2b-4651c6ae5fca.png)

![image](https://user-images.githubusercontent.com/1498098/194707518-3741988d-5d4f-4da0-a961-9e2a9a9aab67.png)

**Comment by muramura** [comment]
This error occurs when the radio signal is not received regularly.
This can help detect a problem with the radio's receiver.
MAVLINK communication is OK within 5 seconds, assuming there is a delay.
When doing RC_OVERRIDE with MAVLINK communication, I think it is necessary to assume this delay in the task ('output' the same value as the previous one until a new signal arrives).

**Comment by rmackay9** [comment]
@muramura,

thanks for the feedback but this is not the issue actually.  This is a real bug because the new check added in this PR https://github.com/ArduPilot/ardupilot/pull/21554 is only checking if a real receiver has ever been connected.  It will never return true if only RC overrides have been used.
