### ISSUE TITLE
EFI_tester.lua issue copter 4.2.3

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#21943]
Hello,

I try to test the lua script:
https://github.com/ArduPilot/ardupilot/blob/ArduPlane-stable/libraries/AP_Scripting/examples/EFI_tester.lua

I set before the EFI_TYPE to UAVCAN and the src param to enable.

I launch it, all seems to be fine, no lua script default message..., but I not retreive any data on the mission planner status tab EFI values....

What I need to do more for get the EFI values ?

Please let me know.

Kind regards.

**Comment by IamPete1** [comment]
That script is a simulator that uses loop back to the genuine scripting driver from here: https://github.com/ArduPilot/ardupilot/tree/ArduPlane-stable/libraries/AP_Scripting/drivers
