### ISSUE TITLE
4.3 Rover EKF issue

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#21949]
4.3 Rover. During testing several navigation failures were encountered. Working with Randy this particular one seems to be a real estimation failure....note GPS position vs EKF estimate....GPS position and compass heading were observed to be correct although progressing steadily away from the mission... Randy says its an estimation issue

log:https://www.dropbox.com/s/0icz987jzz9mc47/4.3-ublox-navfail.bin?dl=0

**Comment by tridge** [comment]
looks like a bad compass calibration

**Comment by rmackay9** [comment]
I think I will close this issue now because it's very old and I think we determined above that it was a compass issue.
