### ISSUE TITLE
NMEA GPS granularity

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#21950]
Observed while testing Rover 4.2.1 and 4.3, the Blicube NMEA GPS lat/lon is very granular....dont know if its an issue in the Moving Baseline GPS with YAW device itself or in AP....if the GPS is reporting incorrectly, we need to inform BliCube

log: https://www.dropbox.com/s/8w7vkevdasxl4qu/4.2.1-NMEAabs-then-NMEArelative.bin?dl=0

**Comment by rmackay9** [comment]
Here's a picture from MP's logs showing the granularity of the GPS (in blue) vs the EKF's nice smooth line (in red)
![image](https://user-images.githubusercontent.com/1498098/195472105-601be262-4a43-433e-b383-20869a0aecd5.png)

**Comment by WickedShell** [comment]
I see a lot of what looks like single precision math in the location parsing in the NMEA driver (look at `AP_GPS_NMEA::_parse_degrees()`), I don't have the time to work through the induced accuracy lost, but I could believe it easily creates results as seen above. (NMEA is among the worst GPS drivers we support). It could also be a function of the GPS unit's reporting accuracy as initially theorized.

**Comment by Hwurzburg** [comment]
![image](https://user-images.githubusercontent.com/6076534/196007276-c6ead613-2c21-4f97-9232-9d8cf26ef535.png)
Tridge's fix worked....closing
