### ISSUE TITLE
SOARING in FBWB can initiate a Stall

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#21979]
Apparently when throttle surpressed in FBWB, the STAB_PITCH_DOWN value (normally subtracted in low throttle in stabilized modes) is not being added to the "level" pitch target which can stall some planes...not an issue in speed controlled modes like AUTO or CRUISE

discovered this in SITL with DG800 RF glider....STAB_PITCH_DOWN had no effect on pitch when gliding...and the model started stalling and recovering...

this should also be applied to THERMAL mode when entered manually when no speed control is active (have not checked if entering manually from CRUISE maintains speed control, it should)

**Comment by samuelctabor** [comment]
Did you resolve this? In general soaring should have no affect on pitch control

**Comment by Hwurzburg** [comment]
Yes....the airspeed sensor had been disabled....worked fine once re-enabled
