### ISSUE TITLE
TECS target altitude changes on its own

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#21984]
after an RTL AUTOLAND the CRUISE mode target altitude changes without elev stick input and resists the stick demands on occasion and the initial target altitude when changing into loiter or cruise is sometimes much lower than the entry altitude at mode change

log: https://www.dropbox.com/s/eq5pm2fuvca536y/TECS-hdem-failure.bin?dl=0

Master plus a small gcs message txt change to report airspeed cal offset

**Comment by shellixyz** [comment]
I have also seen this issue. The target altitude is offset from the current altitude by a fixed offset every time when switching from a manual throttle mode to cruise. Then after a power cycle it is gone or at least imperceptible

**Comment by Hwurzburg** [comment]
@shellixyz if you could rebase your custom code on master, it now has new logging to capture information on target altitude inputs into TECS to help Tridge figure out these issues...a log of this behaviour with those new messages will help him...I cant refly until later this week, myself

**Comment by shellixyz** [comment]
@Hwurzburg Yes I saw it I will rebase my code to include the new logging info :+1:

**Comment by shellixyz** [comment]
I just flew again this time it was going up every time I switched to cruise

![image](https://user-images.githubusercontent.com/4030264/196505712-a82686d4-137f-4b75-b37b-b4b4f0d6f056.png)

[log_98_2022-10-18-19-11-18.bin.zip](https://github.com/ArduPilot/ardupilot/files/9813806/log_98_2022-10-18-19-11-18.bin.zip)

**Comment by Hwurzburg** [comment]
fixed by #22306
