### ISSUE TITLE
"Prearm: Internal error" changing from RTL to Smart RTL

### ISSUE THREAD

**Issue by andrefreitas97** [ArduPilot/ardupilot#22007]
## Bug report

**Issue details**

When changing from RTL flight mode to SmartRTL for the second time (ex: RTL->SmartRTL->RTL->SmartRTL) i get the following error:
"PreArm: Internal errors 0x100000 l:125 flow_of_ctr"

**Version**
4.2.3

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadcopter

**Hardware type**
KakuteH7

**Comment by rmackay9** [comment]
I think this issue is a duplicate of https://github.com/ArduPilot/ardupilot/issues/17416
