### ISSUE TITLE
Invensense V3 no gyro AAF/NF

### ISSUE THREAD

**Issue by fvantienen** [ArduPilot/ardupilot#22010]
https://github.com/ArduPilot/ardupilot/blob/3521090dd5d5a5f5345d3cf437d9657f7b00630e/libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp#L581

Isn't this driver missing the configuration for `INV3REG_GYRO_CONFIG_STATIC2`, to unset the `GYRO_AAF_DIS` and/or `GYRO_NF_DIS`? Currently only the AAF is enable on the accelerometer and not the gyro.

**Comment by andyp1per** [comment]
No, the bit layouts for gyro and accel are different

**Comment by fvantienen** [comment]
<img width="661" alt="Screenshot 2022-10-20 at 19 02 49" src="https://user-images.githubusercontent.com/1078038/197013283-8ebdab1f-d5b5-49d1-9e5f-112920170abb.png">
As you can see this is not correct for the **ICM-40605** and the **ICM-40609D**, there the register is reset to 0x3 which disables both the AAF and NF. I'm not sure that was intended?

**Comment by andyp1per** [comment]
You are right the defaults are different on these two boards vs the 42688

**Comment by andyp1per** [comment]
I have created a PR to fix this.
