### ISSUE TITLE
git submodule update --init --recursive failed

### ISSUE THREAD

**Issue by QingliZeng** [ArduPilot/ardupilot#22019]
when I run git submodule update --init --recursive

## Bug report
fatal: reference is not a tree: 103745afb42f15f83d49fc23530f7fe2c11358b8
Unable to checkout '103745afb42f15f83d49fc23530f7fe2c11358b8' in submodule path 'modules/libcanard/dsdl_compiler/pyuavcan/uavcan/dsdl_files'
Failed to recurse into submodule path 'modules/libcanard/dsdl_compiler/pyuavcan'
Submodule path 'modules/mavlink': checked out 'a09b54f513facafc53c67fc1f8af88ec09c174ae'
Submodule path 'modules/mavlink/pymavlink': checked out '57a6ab0e64468f214c1bfc8ed36fe0e2a900b2e7'
fatal: reference is not a tree: 3ef4b88d96466bbcf886f74d0ae169a4c8c1bdb0
Failed to recurse into submodule path 'modules/libcanard'
Unable to checkout '3ef4b88d96466bbcf886f74d0ae169a4c8c1bdb0' in submodule path 'modules/uavcan'

I tried a lot of ways to correct it, but no use.

**Comment by idk-278** [comment]
hey @QingliZeng, i am experiencing the same issue. Did you find any solution yet?
