### ISSUE TITLE
ROS simulator Iris frame does not work in SITL

### ISSUE THREAD

**Issue by saihv** [ArduPilot/ardupilot#2205]
The IrisRos parameter for the SITL frame option that links to iris_ros.py results in SITL failing with no link established. I was just wondering if this is still a work in progress, or if I am initializing it wrongly. I started SITL with the -f IrisRos option and the Iris simulator parallelly on ROS.

**Comment by khancyr** [comment]
The irisRos solution is really outdated, but there is a gazebo on working now : see http://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html . Closing
