### ISSUE TITLE
BNO055 will take a lot of load from the processor

### ISSUE THREAD

**Issue by hannes-m** [ArduPilot/ardupilot#22068]
## Support of BNO055 

**Is your feature request related to a problem? Please describe.**
No Problem at all...

**Describe the solution you'd like**
The BNO055 (9 axis IMU) will unload the processor a lot because it is calculating the Euler angles itself including all the necessary filters and is providing an automatic yaw drift-correction with the onchip compass.
The use of much slower processors for ArduPilot will be possible with this device.

**Describe alternatives you've considered**
Leave it as it is, Ardupilot is great also without enhancements.

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by IamPete1** [comment]
100hz update rate is not sufficient to fly a vehicle. In any-case it cannot calculate such good values as we can in AP as we have access to additional sensors, such as GPS and additional information to get better filtering, such as RPM feedback from motors.
