### ISSUE TITLE
VTOL - Wrong use of attitude control function may cause vtol transition fail

### ISSUE THREAD

**Issue by skoch1s** [ArduPilot/ardupilot#22103]
Hi! i found a issue of target body angle velocity, this can make yaw rate uncontrolled when transition to fixed wing.

https://github.com/ArduPilot/ardupilot/blob/58cdf8154adbb0390abee310a4e3878e5ab9853d/ArduPlane/quadplane.cpp#L1609

https://github.com/ArduPilot/ardupilot/blob/58cdf8154adbb0390abee310a4e3878e5ab9853d/ArduPlane/quadplane.cpp#L1675

**Comment by MasterMENGJIAN** [comment]
rate_bf_yaw_target need target body angle velocity in centidegrees, but here input angle velocity in rad/s.

**Comment by IamPete1** [comment]
Yep, can you do a pr to correct the units?
