### ISSUE TITLE
Sub: motor N0.5 does not start

### ISSUE THREAD

**Issue by suitangxiaoyi** [ArduPilot/ardupilot#22276]
## Bug report

**Higher version motors do not work properly**

When I use Ardusub version 4.1 and above, the  motor NO.5 does not start. And when I use the 4.0.3 stable version, the motor NO.5  works normally.

**Version**
>Ardusub4.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
BlueRov2 Heavy

**Hardware type**
BlueRov2 Heavy , Pixhawk

**Comment by Williangalvani** [comment]
This turned out to be a parameter issue and was handled in discuss:
https://discuss.bluerobotics.com/t/motor-control-issues-with-the-latest-version/13261/7
