### ISSUE TITLE
Under Arduplane 4.3.3 OSD_* parameters all disappeared

### ISSUE THREAD

**Issue by iskymaster** [ArduPilot/ardupilot#22345]
## Bug report

Noticed under Arduplane 4.3.3 the support for parameter OSD_* completely disappeared under this build.

You can look up these parameters under 4.2.2

**Issue details**

Please check this post on Ardupilot

https://discuss.ardupilot.org/t/bug-in-ardu-plane-4-3-1-all-osd-parameters-disappeared/93888/15

_Please describe the problem_

https://discuss.ardupilot.org/t/bug-in-ardu-plane-4-3-1-all-osd-parameters-disappeared/93888/15

**Version**
_What version was the issue encountered with_

4.3.3

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

Flying wing

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

Pixhawk 2.4.8

**Logs**
_Please provide a link to any relevant logs that show the issue_

Not applicable.

**Comment by IamPete1** [comment]
Now resolved, see discord link
