### ISSUE TITLE
Sub: paramftp: bad count 1272 should be 1268

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#22357]
Running Sub in SITL on master produces this error which I guess is coming from MAVProxy.  This apppears to be the problem PR https://github.com/ArduPilot/ardupilot/pull/21662

![image](https://user-images.githubusercontent.com/1498098/206052897-4b1d16ef-c344-4e1a-a7f9-d1dba7cd65c9.png)

**Comment by andyp1per** [comment]
My guess is you need a param cache flush somewhere like runcam got recently

**Comment by magicrub** [comment]
Should be fixed via https://github.com/ArduPilot/ardupilot/pull/22386
