### ISSUE TITLE
Specifying Message Rates in a File Not Working Via SD

### ISSUE THREAD

**Issue by holden-zenith** [ArduPilot/ardupilot#22361]
## Bug report

**Issue details**
[This](https://discuss.ardupilot.org/t/specifying-message-rates-in-a-file/93859)
[That](https://discuss.ardupilot.org/t/setting-mavlink-intervals-with-txt-file-doesnt-work-with-mp-or-qgc/83928)

**Version**
Any post this [commit](https://github.com/ArduPilot/ardupilot/commit/3f37a21aafebc9ab875ea4d4bcbda2345b21005b)

**Comment by peterbarker** [comment]
I responded on that Discuss post like this:
```
I note that your parameters still have stream rates set to non-zero values - these are the SRn_* parameters.

Have you tried setting all of the SR1_ parameters to zero, for example (and made sure they stay zero :wink: )
```

Waiting to hear back.

**Comment by holden-zenith** [comment]
I actually tried that and had the same issue

**Comment by peterbarker** [comment]
I've responded separately to both of the Discuss posts linked here.  I've attempted to replicate both problems without success so far.

**Comment by holden-zenith** [comment]
I was placing it manually on the SD Card in the APM folder. I assume ftp put places it in the same folder? The image [here](https://ardupilot.org/mavproxy/docs/modules/ftp.html) looks like APM is a subdirectory of the directory that ftp put places the file in by default since ftp list and ftp list APM point to two different directories.

**Comment by peterbarker** [comment]
> I was placing it manually on the SD Card in the APM folder. I assume ftp put places it in the same folder? The image [here](https://ardupilot.org/mavproxy/docs/modules/ftp.html) looks like APM is a subdirectory of the directory that ftp put places the file in by default since ftp list and ftp list APM point to two different directories.

The files go in the root directory o the SD card.  I did consider putting them in the APM subdir but was talked out of it at DevCall.

**Comment by rmackay9** [comment]
@peterbarker,

Txs for the continued investigation of this.  Can you tell me again where on the dev wiki the instructions are?  I looked for them again just now but couldn't find them.  In particular I was looking to see if the location of the file was specified in those instructions.

**Comment by rmackay9** [comment]
I've created a PR to correct the documentation on the wiki so I'll go ahead and close this issue if that's OK.

Now of course if @holden-zenith replies here that this does not fix the problem I'll re-open this issue.

Thanks again @holden-zenith for finding this problem!
