### ISSUE TITLE
Copter: terrain offset clamped when using Non-GPS navigation

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#22392]
When testing Non-GPS navigation using the [ModalAI VOXL camera](https://ardupilot.org/copter/docs/common-modalai-voxl.html) I noticed that our terrain offset clamping triggers meaning that if a user attempts an autonomous mission with terrain altitudes the vehicle could fly incredibly high.

The underlying issue may be that Mission Planner (and perhaps other GCSs) do not provide an accurate altitude when they set the origin.  They may set the altitude as zero.

![image](https://user-images.githubusercontent.com/1498098/207280412-29ef8ac6-8897-4a3e-ab42-c6b8cebc8ab2.png)

This issue can be recreated in SITL by starting up Copter using Vicon ([see wiki here](https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html#testing-vicon-aka-vision-positioning)) and then set the origin using MAVProxy's right-mouse-button menu's "Set Origin" option (not "Set Origin (with Height)").

![image](https://user-images.githubusercontent.com/1498098/208056584-1b12ae13-2398-4541-893b-d8b7f6933a62.png)

**Comment by alfiianaa** [comment]
how about using GPS navigation ?

**Comment by rmackay9** [comment]
It turns out the issue is in Mission Planner and I've raised an issue https://github.com/ArduPilot/MissionPlanner/issues/3083

When using GPS navigation the "clamping" message can still be dangerous in that the vehicle may fly at the wrong altitude if it is executing auto mode missions with altitude type set to Terrain.  We recently relaxed the limit to make this less likely and this change will be included in 4.4. https://github.com/ArduPilot/ardupilot/pull/23176
