### ISSUE TITLE
HAL_Linux should support --serialx cmdline arguments

### ISSUE THREAD

**Issue by Williangalvani** [ArduPilot/ardupilot#22462]
[They are implemented currently only for SITL](https://github.com/ArduPilot/ardupilot/blob/Sub-4.1/libraries/AP_HAL_SITL/SITL_cmdline.cpp#L96-L104). And this is a lot more user-friendly.

**Comment by khancyr** [comment]
good idea !

**Comment by peterbarker** [comment]
It now does support --serial0 etc
