### ISSUE TITLE
Notch Filtering seems broken

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#22543]
while setting up a miniquad to get some wiki screenshots of using pre/post batch sampling for notch filter setup, found that the throttle notch did not seem to work....I tried a fixed notch also, same results...here are the FFTs using mavfft_isb.py:

Pre filter sampling:
![PreFilter](https://user-images.githubusercontent.com/6076534/210149864-d1e96609-7cc5-4847-8a99-09b537d9e545.png)
Post filter sampling with no notch enabled:
![Postfllter-notchoff](https://user-images.githubusercontent.com/6076534/210149884-1e4eab44-47dd-4fe2-bf6c-ee9e10276c83.png)
Post filter with notch enabled and set to fixed at 178Hz, but only the 20Hz LPF seem active:
![Postfllter-notchon](https://user-images.githubusercontent.com/6076534/210149898-7c441eb9-d82b-48ff-a2d3-4271e5eceab1.png)
Notch supposedly active at 178Hzfrom the logging of FTNS.NF:
![FTNS NF](https://user-images.githubusercontent.com/6076534/210149923-2de5c917-e5e4-4bc4-bb48-7be1b06ec4f6.png)
Notch params:
MAV> INS_HNTC2_ENABLE 0.000000 # Disabled
INS_HNTCH_ATT    40.000000
INS_HNTCH_BW     90.000000
INS_HNTCH_ENABLE 1.000000 # Enabled
INS_HNTCH_FM_RAT 1.000000
INS_HNTCH_FREQ   178.000000
INS_HNTCH_HMNCS  3.000000 # 1st harmonic|2nd harmonic
INS_HNTCH_MODE   0.000000
INS_HNTCH_OPTS   0.000000 # 
INS_HNTCH_REF    1.000000

**Platform**
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
this is on master as of 12/30/2022

**Comment by andyp1per** [comment]
@Hwurzburg please retry with a much higher LPF - 20Hz is not really going to allow you to see what the notch is doing. Please also do a long hover to see the effect (e.g. 2mins). We have tests that indicate that the notch is working, so will need a bit more proof than this.

**Comment by Hwurzburg** [comment]
with higher LPF and longer hover, I can see the gyro notch now....need to change the wiki a bit in light of this and make sure that increasing the LPF cutoff is needed to help see the results and is the point of the notches....thanks
