### ISSUE TITLE
IdData() function not defined in sid_pre.m (line - 446)

### ISSUE THREAD

**Issue by neom89** [ArduPilot/ardupilot#22594]
## Bug report
I was trying to run the simulink model in the Tools section of the repository. The function IdData is not defined in the folder. There is iddata() function in the system identification toolbox of matlab but the arguments are completely different from that of IdData() function.

**Version**
Latest master

@fbredeme @peterbarker

**Comment by fbredeme** [comment]
IdData was actually a class that I used for another project. This has to be removed. I'll fix this issue today.
