### ISSUE TITLE
Gimbal control

### ISSUE THREAD

**Issue by m98cami** [ArduPilot/ardupilot#22629]
I want to send a hexadecimal message using the MAVLINK protocol in order to control a gimbal, where specifically could I modify the information in the message to include my hexadecimal string?

**Comment by IamPete1** [comment]
This is not the place for questions. We do have a discord and a fourm. 

https://ardupilot.org/dev/docs/common-contact-us.html

**Comment by rmackay9** [comment]
@m98cami,

As IamPete1 says, the forum is probably a good place to ask.  Maybe ask in the [copter-4.3 forum](https://discuss.ardupilot.org/c/arducopter/copter43/167) and feel free to put "@rmackay9" in your message so I'm alerted.  I'm doing a lot of work on gimbal support these days so I think I can help.
