### ISSUE TITLE
Always armed airunit

### ISSUE THREAD

**Issue by goshangFPV** [ArduPilot/ardupilot#22642]
I have instal wtfos on my air unit installed on ardupilot 4.3.2, every time when i power it up, it dont show message "low power mode, unable to record videos". Temperature control is on.
What should i do, to run it on low power when i turn my plane on?

OSD_TYPE = 5
MSP_OPTIONS = 42

**Version**
Ardupilot 4.3.2

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Flying wing

**Hardware type**
Matek h743
Dji Air unit

**Comment by rmackay9** [comment]
Hi @goshangFPV,

Thanks for the report but really it should go into our support forums first.  Probably the [Hardware/OSD section is best](https://discuss.ardupilot.org/c/hardware-discussion/osd-video/122).

Sorry to be strict but if we're not then our to-do list (e.g. bugs and enhancements list) turns into a support forum.
