### ISSUE TITLE
copter flight modes not available until FRAME_CLASS set

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#22657]
When first installing FRAME_CLASS won't be setup. Until it is setup the user cannot setup flight modes, which can be confusing as the link between them is not at all obvious
![image](https://user-images.githubusercontent.com/831867/212497186-f37d2260-ec9c-49a8-abfd-808905368997.png)
we should make flight modes setup work before FRAME_CLASS is set
Note that with MissionPlanner even if you set FRAME_CLASS you have to know to then disconnect/reconnect before flight modes can be displayed

**Comment by IamPete1** [comment]
Fixed by: https://github.com/ArduPilot/MissionPlanner/pull/2972

Do you need to disconnect and reconnect or is a param re-fresh enough?

**Comment by tridge** [comment]
> Do you need to disconnect and reconnect or is a param re-fresh enough?

you need to disconnect/reconnect, which is really non-obvious

I like your MissionPlanner PR, but it won't work for some builds as they override the strings (vendors often do this)

I think we should do this too: https://github.com/ArduPilot/ardupilot/pull/22658
