### ISSUE TITLE
Compilation Errors in Simulink model provided in tools

### ISSUE THREAD

**Issue by n-shubham** [ArduPilot/ardupilot#22681]
I am facing trouble running the simulink model due to some errors with the usage of min() and max() functions in simulink. 

For instance, in the block `arducopter/radioIn to controlIn/MATLAB Function`, we have the following function - 

```
function angleIn = pwm_to_angle_dz(rcIn, deadZone, radioMin, radioMax, trim, reversed, highIn)
coder.extrinsic('MException');
angleIn = single(0);
radioTrimHigh = trim + deadZone;
radioTrimLow = trim - deadZone;
if reversed
    reverseMul = -1;
else
    reverseMul = 1;
end
% Dont allow out of range values
rcIn = max(min(rcIn, radioMax), radioMin);
if rcIn > radioTrimHigh && radioMax ~= radioTrimHigh
    angleIn = reverseMul * highIn * (rcIn - radioTrimHigh) / (radioMax  - radioTrimHigh);
elseif rcIn < radioTrimLow && radioTrimLow ~= radioMin
    angleIn = reverseMul * highIn * (rcIn - radioTrimLow) / (radioTrimLow - radioMin);
else
    angleIn = single(0);
end
```

The error trace from the Diagnostic Viewer is as follows - 

> === Model Save (arducopter) (Elapsed: 0.991 sec) ===
> === Simulation (Elapsed: 1 sec) ===
>     Error:Function 'evalin' not supported for code generation.
>     
>     Function 'narginchk.m' (#1453.38.64), line 2, column 8:
>     "evalin('caller', 'nargin')"
>     Launch diagnostic report.
>     Error:Undefined function or variable 'narg'. The first assignment to a local variable determines its class.
>     
>     Function 'narginchk.m' (#1453.69.73), line 3, column 4:
>     "narg"
>     Launch diagnostic report.
>     Error:Undefined function or variable 'narg'. The first assignment to a local variable determines its class.
>     
>     Function 'narginchk.m' (#1453.164.168), line 5, column 8:
>     "narg"
>     Launch diagnostic report.
>     Error:Function 'MException' is not supported for code generation. Consider adding coder.extrinsic('MException') at the top of the function to bypass code generation.
>     
>     Function 'narginchk.m' (#1453.279.296), line 10, column 15:
>     "MException(me{:})"
>     Launch diagnostic report.
>     Error:Function call failed.
>     
>     Function 'min.m' (#1454.266.280), line 10, column 1:
>     "narginchk(1,5)"
>     Launch diagnostic report.
>     Error:Function call failed.
>     
>     Function 'radioIn to controlIn/MATLAB Function' (#792.521.540), line 20, column 12:
>     "min(rcIn, radioMax)"
>     Launch diagnostic report.
>     Error:Undefined function or variable 'rcIn'. The first assignment to a local variable determines its class.
>     
>     Function 'radioIn to controlIn/MATLAB Function' (#792.557.561), line 22, column 4:
>     "rcIn"
>     Launch diagnostic report.
>     Error:Undefined function or variable 'rcIn'. The first assignment to a local variable determines its class.
>     
>     Function 'radioIn to controlIn/MATLAB Function' (#792.644.648), line 23, column 38:
>     "rcIn"
>     Launch diagnostic report.
>     Error:Undefined function or variable 'rcIn'. The first assignment to a local variable determines its class.
>     
>     Function 'radioIn to controlIn/MATLAB Function' (#792.704.708), line 24, column 8:
>     "rcIn"
>     Launch diagnostic report.
>     Error:Undefined function or variable 'rcIn'. The first assignment to a local variable determines its class.
>     
>     Function 'radioIn to controlIn/MATLAB Function' (#792.789.793), line 25, column 38:
>     "rcIn"
>     Launch diagnostic report.
>     Error:Errors occurred during parsing of MATLAB function 'arducopter/radioIn to controlIn/MATLAB Function'
>     Error:Errors occurred during parsing of MATLAB function 'arducopter/radioIn to controlIn/MATLAB Function'

The main error is in the folllowing line :
`rcIn = max(min(rcIn, radioMax), radioMin);`
As the function call to min() is failing, it leads to further undefined references to the rcIn variable.

Here is a screenshot of the function report : 
![image](https://user-images.githubusercontent.com/98383716/213178819-45da02c2-d393-426e-b855-ec0338194f33.png)

Similar errors occur in calls to min() and max() functions in all MATLAB Function blocks in the model.

@fbredeme @peterbarker, are there any additional configuration steps required to run the Simulink model? Please advise how to fix this error.

**Comment by n-shubham** [comment]
![MatlabError3](https://user-images.githubusercontent.com/98383716/213376068-a7545956-5654-452d-9024-68583217f701.png)


Here is another example of a function call that is failing, this time to the mod() function. Such behaviour is encountered in several function calls in several blocks in the model.

**Comment by fbredeme** [comment]
Hi @n-shubham 
A few questions: 
Which MATLAB version are you using?
Did you add line 7 (coder.extrinsic('MException')) to the function pwm_to_angle_dz?
Have you logged all the relevant dataflash messages, most importantly 'RCIN'? The respective LOG_BITMASK parameter is given in the README

**Comment by n-shubham** [comment]
Hi,

I'm using R2022a
Yes, I did add that line, as per the suggestion message on Line 4 of the all messages section in the function report. Adding or removing that line does not show and change in behaviour.
Yes, the RCIN messages are logged.

**Comment by fbredeme** [comment]
I'm using MATLAB 2021a and I don't have any issues, so I'm a little bit confused about these errors. You could try to initilize the variables first that are being references in the error messages. So, for example, define the variable "mult" in "toAxisAngle" first with "mult = single(0);". Do the same for pwm_to_angle_dz, but create a new variable instead of using "rcIn" since this is the input signal. Maybe this will help.

**Comment by n-shubham** [comment]
For some reason, this seems to be a machine-specific issue. I can reproduce this issue only one a single machine with the model working as expected on other machines. Closing.
