### ISSUE TITLE
What is the reason for the speed converters? One rotates at 5% thrust and the rest at 14% thrust. Quadcopter

### ISSUE THREAD

**Issue by hilmi988** [ArduPilot/ardupilot#22699]
What is the reason for the speed converters? One rotates at 5% thrust and the rest at 14% thrust. Quadcopter

**Comment by IamPete1** [comment]
Sounds like you need to calibrate your ESC's. 

https://ardupilot.org/copter/docs/esc-calibration.html

The forum is the correct place for such questions.

https://discuss.ardupilot.org/
