### ISSUE TITLE
Debug pin HAL_GPIO_PIN_JTCK_SWCLK,HAL_GPIO_PIN_JTMS_SWDIO gives problem when initialise as Input

### ISSUE THREAD

**Issue by 8-DK** [ArduPilot/ardupilot#22867]
## Bug report

**Issue details**

Problem at **board_init_debug()** in file **Ap_BoardConfig/board_drivers.cpp**. Debugger start as expected with breaks at AP_HAL_MAIN_CALLBACKS(&copter). but after run program debugger notify with following error and device restart debugging.
  https://github.com/ArduPilot/ardupilot/blob/34e8e02c48d2982d722b982e1bfac5581d4401ae/libraries/AP_BoardConfig/board_drivers.cpp#L60
- Hardware used : CubeOrangePlus
- IDE                   : STM32CubeIDE
- Programmer     : STLinkv2
- Debug Interface : SWD(without reset pin, Software Reset) with OpenOCD

**- Error Logs From OpenOCD**

Open On-Chip Debugger 0.12.0-rc1+dev-00061-g5e9b46d77 (2022-10-20-14:47) [https://github.com/STMicroelectronics/OpenOCD]
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
stm32h7x_cti_prepare_restart_one
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : STLINK V2J40S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.244444
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
Info : clock speed 4000 kHz
Info : stlink_dap_op_connect(connect)
Info : SWD DPIDR 0x6ba02477
Info : [STM32H753VITx.cm7] Cortex-M7 r1p1 processor detected
Info : [STM32H753VITx.cm7] target has 8 breakpoints, 4 watchpoints
Info : gdb port disabled
Info : starting gdb server for STM32H753VITx.cm7 on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
Info : Device: STM32H74x/75x
Info : flash size probed value 2048k
Info : STM32H7 flash has dual banks
Info : Bank (0) size is 1024 kb, base address is 0x08000000
Info : Device: STM32H74x/75x
Info : flash size probed value 2048k
Info : STM32H7 flash has dual banks
Info : Bank (1) size is 1024 kb, base address is 0x08100000
Info : New GDB Connection: 1, Target STM32H753VITx.cm7, state: unknown
Warn : GDB connection 1 on target STM32H753VITx.cm7 not halted
undefined debug reason 8 - target needs reset
Info : accepting 'gdb' connection on tcp/3333
Info : New GDB Connection: 2, Target STM32H753VITx.cm7, state: running
Warn : GDB connection 2 on target STM32H753VITx.cm7 not halted
undefined debug reason 8 - target needs reset
[STM32H753VITx.cm7] halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08020dec msp: 0x30000600
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
[STM32H753VITx.cm7] halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08020dec msp: 0x30000600
**Error: Fail reading CTRL/STAT register. Force reconnect**
Warn : target STM32H753VITx.cm7 is not halted (gdb fileio)
Polling target STM32H753VITx.cm7 failed, trying to reexamine
Error: Fail reading CTRL/STAT register. Force reconnect
Examination failed, GDB will be halted. Polling again in 100ms
Error: Fail reading CTRL/STAT register. Force reconnect
Error: Fail reading CTRL/STAT register. Force reconnect
Error: Failed to read memory and, additionally, failed to find out where
Error: Fail reading CTRL/STAT register. Force reconnect
Polling target STM32H753VITx.cm7 failed, trying to reexamine
Error: Fail reading CTRL/STAT register. Force reconnect
Examination failed, GDB will be halted. Polling again in 300ms
Error: Fail reading CTRL/STAT register. Force reconnect
Polling target STM32H753VITx.cm7 failed, trying to reexamine
Error: Fail reading CTRL/STAT register. Force reconnect
Examination failed, GDB will be halted. Polling again in 700ms
Error: Fail reading CTRL/STAT register. Force reconnect
Polling target STM32H753VITx.cm7 failed, trying to reexamine
Error: Fail reading CTRL/STAT register. Force reconnect
Examination failed, GDB will be halted. Polling again in 1500ms
shutdown command invoked
Error: Fail reading CTRL/STAT register. Force reconnect
Error: Fail reading CTRL/STAT register. Force reconnect
Error: Failed to read memory and, additionally, failed to find out where
Error: read_memory: read at 0xe00e4000 with width=32 and count=1 failed
Error executing event gdb-detach on target STM32H753VITx.cm7:

**Solution**
-After commenting 
`palSetLineMode(HAL_GPIO_PIN_JTCK_SWCLK, PAL_MODE_INPUT);
palSetLineMode(HAL_GPIO_PIN_JTMS_SWDIO, PAL_MODE_INPUT);
`
Debuger works as expected

**Version**
Copter-4.3.3

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by andyp1per** [comment]
You need to set BRD_OPTIONS = 8. My chibios PR does this automatically for debug builds.
