### ISSUE TITLE
Sub: 4.0 - 4.1 changed from earth to body frame control without warning

### ISSUE THREAD

**Issue by ES-Alexander** [ArduPilot/ardupilot#22896]
## Bug report

**Issue details**

Sub <= 4.0 used earth frame for manual control, which is generally less intuitive than body frame control, but the earth frame yaw control served as a convenient proxy for roll control during highly pitched inspections, especially since ArduSub currently [only accepts joystick control of `R+P / V+Y` _OR_ `F+L / V+Y` at a given point in time](https://discuss.bluerobotics.com/t/poll-controlling-roll-pitch/12883). Recent versions of Sub have changed to only supporting body frame, which is problematic when the old behaviour was being relied upon.

[Relevant forum discussion](https://discuss.bluerobotics.com/t/weird-behavior-after-change-to-navigator-from-pixhawk1/13553)

---

Current proposed solution is to add a parameter that allows selecting the current control frame, and makes use of a subset of the [`MAV_FRAME`](https://mavlink.io/en/messages/common.html#MAV_FRAME) enum as the supported options.

(@Williangalvani)

**Version**
Sub >= 4.1

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[x] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Anything with 6-axis control

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Pixhawk / Navigator

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by Williangalvani** [comment]
closing this as that change has been reverted, but I do intend to re-write it in the near future.
