### ISSUE TITLE
Multiple Lidar Lite LL40LS on I2c

### ISSUE THREAD

**Issue by MakerMark** [ArduPilot/ardupilot#2291]
Hi, there aren't nothing schedule for connecting multiple Lidar Lite with a NXP PCA 9548??? i find this Pulsed Light tutorial sketch

https://github.com/PulsedLight3D/LIDARLite_MultiSensor_w_PCA9544A_Multiplexer

**Comment by Naterater** [comment]
I think this is now an option. See https://discuss.ardupilot.org/t/how-to-make-the-tfmini-rangefinder-talk-i2c/24403 for some really good discussion on multiple lidar units.
