### ISSUE TITLE
MAVSDK and Arducopter SITL incompatibility

### ISSUE THREAD

**Issue by kripper** [ArduPilot/ardupilot#22966]
**Issue details**

MAVSDK and Arducopter SITL incompatibility.

**Version**

Arducopter SITL binary release installed by latest Mission Planer binary for Windows.
There is no version information in the Arducopter.exe binary nor `-V` or `--version` options in Arducopter.exe 👎 

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

`FRAME_TYPE	0`

**Hardware type**

SITL

**Logs**

We are testing MAVSDK to send a QGC mission to [Arducopter SITL](https://firmware.ardupilot.org/Tools/MissionPlanner/sitl/) (using `fly_qgc_mission.cpp`).
We identified at least two issues:

- ISSUE 1: `telemetry.health_all_ok()` in MAVSDK is always `false`
- ISSUE 2: Arducopter SITL doesn't start the mission but disarms.

Everything works fine sending the mission from QGC to Arducopter SITL instead of using `fly_qgc_mission.cpp`. I believe QGC was fine tuned to workaround Arducopter's standard-MAVLink incompatibilities.
I'm trying to understand why this two opensource projects don't speak the same language.

```
Output of fly_qgc_mission.cpp (MAVSDK official example):

	Waiting to discover system...
	Discovered autopilot
	Waiting for system to be ready	<--- BUG 1: blocks on while (!telemetry.health_all_ok())
	(Waiting disabled by me, for testing)
	System ready
	Importing mission from mission plan: /data/data/com.termux/files/home/imatronix/server/test/p9-quillota.plan
	Found 10 mission items in the given QGC plan.
	Uploading mission...Mission uploaded.
	Arming...
	Armed.

Output of arducopter.exe:

	...
	AP: EKF3 IMU0 is using GPS
	AP: EKF3 IMU1 is using GPS
	AP: Terrain: clamping offset 435 to 15
	AP: Arming motors
	ARMED
	Mode AUTO
	AP: Mission: 1 Takeoff
	waypoint 1
	
	(little pause, probably a timeout)
	
	AP: Disarming motors	<--- BUG 2: Unexpected disarm. Why? There is no problem when sending the same mission from QGC
	AP: Mission: 1 Takeoff
	DISARMED
```

**Comment by 41Mo** [comment]
Greetings. I am currently working with ardupilot and mavsdk.


I might help you with second issue, You may turn [AUTO_OPTIONS](https://ardupilot.org/copter/docs/parameters.html#auto-options-auto-mode-options) bit 1. 


As about first issue. There are some issues in mavsdk with ardupilot compatibility. You may check mavsdk issue tracker.


I am able to successfully pass health check, while using build, based on latest mavsdk [commit](https://github.com/mavlink/MAVSDK/commit/d3115f547f8a7dee4b6c61dea1211ca80101d4b9)

**Comment by kripper** [comment]
Thanks @41Mo. Bit 1 was not enaugh, but enabling the 3 flags with `AUTO_OPTIONS 10` solved Issue #2.
But sending the mission directly from QGC doesn't need to configure Arducopter, which means that QGC is doing something different to satisfy Arducopter.

Do you know how to enable verbose logging for Arducopter?

**Comment by 41Mo** [comment]
@kripper 
I'm not sure if the arducopter has any other option for verbose logging. For simple applications you may use mavlink messages. You may find them by pressing this button
![image](https://user-images.githubusercontent.com/40123891/219878666-4a777440-cbd9-4169-b198-c0190259f123.png)

Another option to explore logs - arducopter [dataflash logs](https://ardupilot.org/copter/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html#downloading-and-analyzing-data-logs-in-mission-planner). Dataflash logs are most detailed logs. But you can explore then only after flight.

As for handling mission start.
When QGC starts mission it quickly changes mode to GUIDED then sends takeoff command and then toggles mode back to AUTO, thats why, while using QGC there is no need to change AUTO_OPTION.

**Comment by kripper** [comment]
Thanks

**Comment by julianoes** [comment]
Can you explain what AUTO_OPTION 10 does for ArduPilot?

**Comment by kripper** [comment]
> Can you explain what AUTO_OPTION 10 does for ArduPilot?

https://ardupilot.org/copter/docs/parameters.html#auto-options-auto-mode-options

**Comment by julianoes** [comment]
So 10 means 0b10 then? Or 10 as in 0b1010?

I assume the former, so:
```
Bit 1: Allow Takeoff Without Raising Throttle
```

**Comment by 41Mo** [comment]
@julianoes I dont know what exactly @kripper  means, but in my case setting first two bits is enough.
![image](https://user-images.githubusercontent.com/40123891/222383369-1c1f09ba-97bc-423e-a1d0-d7d855d5b1fb.png)

**Comment by kripper** [comment]
You are right. 10 probably means bits 2 and 4, so only bit 2 is needed, ie "Allow Takeoff Without Raising Throttle".
