### ISSUE TITLE
'PRE ARM: GPS2: NOT HEALTHY' message keeps when using two Here3+ GPSes

### ISSUE THREAD

**Issue by NXPLM** [ArduPilot/ardupilot#23063]
## Bug report

**Issue details**

An issue that I believe to be a bug when using two Here3+ GPS modules. In the process of modernizing our drone, we've upgraded GPS modules from one Here+ and one Here2 module to two Here3+ GPS modules. In the new configuration, we get a 'PRE ARM: GPS2: NOT HEALTHY' message. The configuration of the GPS modules is: one mounted close to the wing tip, and one mounted centrally on the wing. When updating the firmware, GPS2 was designated to be the one mounted near the wing tip. When the message showed up we checked the performance of this GPS by disassembling it from the plane and checking its performance in isolation with another Cube running the same firmware and parameters. There were no errors and the GPS performance was excellent (more than 17 satellites and HDOP<1). After mounting it back onto the plane, we checked both GPSes in isolation and none of them showed any errors when arming when using only one GPS, both were performing very well. The issue however persisted when using two GPSes. I tried changing parameters regarding GPS configuration however no matter what combination of parameters I used the message 'PRE ARM: GPS2: NOT HEALTHY' kept appearing. I then tried starting fresh, I flashed the latest version of ArduCopter and went back to ArduPlane v4.3.3 for a clean installation. After flashing previously saved parameters and powering up the plane, GPS2 (in the firmware) was designated to be the one centrally mounted on the wing, so their designation switched. Previously GPS2 was the one mounted near the wing tip. Despite the configuration looking OK and nothing more being changed after flashing the firmware the message 'PRE ARM: GPS2: NOT HEALTHY' appeared again. This lead me to believe that this issue is software related as I didn't find any problems configuration of the autopilot and by isolating specific hardware components I did not find any problems as well. The way I was able to tell which GPS1 and GPS2 correspond to which GPS mounted on the plane was by checking their addresses via SLCAN and comparing them to the messages that appear when powering up the plane. This issue may be related to the combination of parameters that I use however I wasn't able to definitely tell when testing.  I've opened a thread on ArduPilot discuss forum previously:  https://discuss.ardupilot.org/t/pre-arm-gps2-not-healthy/97259 . After further testing described above I believe this issue to be a bug. 
 
**Version**
ArduPilot v4.3.3, Here3+ latest available firmware version v4.19

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadplane: OCTAQUAD/X

**Hardware type**
Cube Blue, custom carrier board, two Here3+ GPS

**Logs**
https://drive.google.com/file/d/1TUVphQtfbAE_LRDMEXnqNe5ao4DEZ5jh/view

**Comment by Muruganantham09** [comment]
HI,
I am also facing the same issue, did you find any solution for this problem ??
If you did it please tell me the solution it will be very helpful for me.

**Comment by Mithun-HR** [comment]
Even I am facing the same issue..
Prearm: GPS2: not healthy
Please help

**Comment by rmackay9** [comment]
Hi there, this really is a support issue so ideally it should be raised in one of the support forums.

So for example, if you're using [Copter-4.5 then here is a good place](https://discuss.ardupilot.org/c/arducopter/copter-45/174).

For [Plane-4.5 here is the best place](https://discuss.ardupilot.org/c/arduplane/plane-45/176).

I know this is an old issue and sorry to be strict but if we're not then our to-do list turns into another support forum.  If its confirmed to be a real bug then we can re-open the issue.  I'm sure that two Here3 GPSs work though so this is most likely to be a configuration error.  Perhaps GPS_TYPE2 was not set?
