### ISSUE TITLE
Copter: Is there any problem in function euler_accel_limit() ? version-2

### ISSUE THREAD

**Issue by luweiagi** [ArduPilot/ardupilot#23117]
I think there is a bug in this function:
[AC_AttitudeControl::euler_accel_limit(const Vector3f &euler_rad, const Vector3f &euler_accel)](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_AttitudeControl/AC_AttitudeControl.cpp#L908)

In 2017, I had issued this question: [Copter: Is there any problem in function euler_accel_limit()?](https://github.com/ArduPilot/ardupilot/issues/23117), but not figure out.

These days I have looked again at this function, and I finally find bug in it. details as follow([details](https://luweiagi.github.io/machine-learning-notes/#/autopilot/navigation/coord-trans-and-euler-kinematics-equation/coord-trans-and-euler-kinematics-equation)):
![image](https://user-images.githubusercontent.com/19629731/223306542-24de969b-b4f6-4c2a-8bce-752a2c036bd7.png)

So, we can get the roll, pitch, yaw max acc limit:
![image](https://user-images.githubusercontent.com/19629731/223308550-1d0a4fce-0ab0-4c98-802c-f73a4d1a4736.png)

So, the function code can be written as:
```(c++)
Vector3f AC_AttitudeControl::euler_accel_limit(const Vector3f &euler_rad, const Vector3f &euler_accel)
{
    float sin_phi = constrain_float(fabsf(sinf(euler_rad.x)), 0.1f, 1.0f);
    float cos_phi = constrain_float(fabsf(cosf(euler_rad.x)), 0.1f, 1.0f);
    float sin_theta = constrain_float(fabsf(sinf(euler_rad.y)), 0.1f, 1.0f);
    float cos_theta = constrain_float(fabsf(cosf(euler_rad.y)), 0.1f, 1.0f);

    Vector3f rot_accel;
    if (is_zero(euler_accel.x) || is_zero(euler_accel.y) || is_zero(euler_accel.z) || is_negative(euler_accel.x) || is_negative(euler_accel.y) || is_negative(euler_accel.z)) {
        rot_accel.x = euler_accel.x;
        rot_accel.y = euler_accel.y;
        rot_accel.z = euler_accel.z;
    } else {
        rot_accel.x = euler_accel.x;
        rot_accel.y = MIN(euler_accel.y / cos_phi, euler_accel.z / sin_phi);
        rot_accel.z = MIN(MIN(euler_accel.x / sin_theta, euler_accel.y / (sin_phi * cos_theta)), euler_accel.z / (cos_phi * cos_theta));
    }
    return rot_accel;
}
```
Is above right?

==============================

Another question:
I think this function euler_accel_limit(...) is to translate the angle accel limitations from body frame to euler frame.
So, the actual meaning of function paramitor euler_accel is body accel(derivation of bady angel velocity p, q, r), so why call them euler_accel not body_accel? And rot_accel in this function should be renamed as euler_accel because they are trully roll pitch yaw angle accel rate.
```
Vector3f AC_AttitudeControl::euler_accel_limit(const Vector3f &euler_rad, const Vector3f &euler_accel)
```

@lthall  and @rmackay9

**Comment by lthall** [comment]
I believe this is correct. I am sorry it took so long to get to this. It has been on my lists of things to do!!

**Comment by lthall** [comment]
#23321

**Comment by luweiagi** [comment]
> I believe this is correct. I am sorry it took so long to get to this. It has been on my lists of things to do!!



> I believe this is correct. I am sorry it took so long to get to this. It has been on my lists of things to do!!

Thanks for your reply. These years I always remember this bug/problem. Now my suggestion is accepted, I feel happy although this is a very tiny problem.

I think fix this bug can enhance copter maneuverability by releasing the limit.

**Comment by luweiagi** [comment]
> I believe this is correct. I am sorry it took so long to get to this. It has been on my lists of things to do!!

Thanks for your reply. I am happy for being accepted. These years this problem/bug is always in my head. Although it is a tiny bug with little affect on maneuverability, but let me be happy for a while.

**Comment by luweiagi** [comment]
I reply https://github.com/ArduPilot/ardupilot/pull/23326 at here:

**Comment by rmackay9** [comment]
Can we close this now that https://github.com/ArduPilot/ardupilot/pull/23326 has been merged?
