### ISSUE TITLE
AP_NMEA_Ouput Has some strange assignments 

### ISSUE THREAD

**Issue by lbullard-c2** [ArduPilot/ardupilot#23157]
## Bug report

**Issue details**

The AP_NMEA_Output library has some unusual assignments to message contents, and some seemingly nonstandard message contents.

**Version**
Current 

**Platform**
[x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
N/A
**Hardware type**
N/A

**Logs**
N/A

I have required the NMEA output function for an external sensor, which is seemingly very fussy about the messages it receives. Further investigation of the AP_NMEA_Output.cpp file reveals some odd values, especially in the GPGGA message.
Reference for the GPGGA Message: https://docs.novatel.com/OEM7/Content/Logs/GPGGA.htm

The GPS quality field is only ever 0 or 1, despite this data being present in the AP_GPS library - as with number of satellites, which bizarrely reports 3 sats with no fix, and 6 sats with a fix, never more or less. Hdop is always reported as 2.0

`gga_length = nmea_printf_buffer(gga, sizeof(gga),`
                                    `"$GPGGA,%s,%s,%s,%01d,%02d,%04.1f,%07.2f,M,0.0,M,,",`
                                   `tstring,`
                                 `lat_string,`
                                    `lng_string,`
                                   `pos_valid ? 1 : 0,  // GPS fix type 0 if no gps, 1 if any fix`
                                    `pos_valid ? 6 : 3, // Number of satellites 3 if no gps, 6 if any fix`
                                   `2.0, // HDOP always 2.0, even if no gps fix at all`
                                 `loc.alt * 0.01f);`

This data is also often reported in higher precision than the standard - for example, utc time should have the format of hhmmss.ss, but the tstring variable is formatted in AP_NMEA_OUTPUT.cpp as hhmmss.sss - my peripheral for example rejects this message due to the extra value after the decimal point.

I have implemented fixes for these issues locally and am happy to submit a pull request once the code is cleaned up, as well as the implementation of the GPGST message. Just wanted to raise this first to double check there isn't an obvious reason why the messages are setup this way.

**Comment by IamPete1** [comment]
Please open a PR, makes it much easier to review each issue.

**Comment by magicrub** [comment]
@lbullard-c2 wow, I never noticed that! If you want to make a PR, great. if not, I'll whip one up quickly. I can't believe it's been like that this whole time

**Comment by rmackay9** [comment]
I've added this to the 4.3 issues list so it is not forgotten.

**Comment by lbullard-c2** [comment]
I have added the pull request now

**Comment by rmackay9** [comment]
That PR has been merged so I will close this now. Please tell me if you think this is incorrect.
