### ISSUE TITLE
Copter:Pixhawk:bug: All AUX ports can output mount tilt/roll signals except AUX5

### ISSUE THREAD

**Issue by cmanley** [ArduPilot/ardupilot#2315]
In 3.2 I could set any AUX output's RC*_FUNCTION to 7 or 8 (for mount tilt/roll) and only on AUX5 (RC13) no signal is output. The other AUX ports (including AUX6/RC14) output the tilt or roll values just fine. Unfortunately for me, the only unoccupied AUX ports are RC13 (AUX5) and RC14 (AUX6), since I use a 12 channel SBUS RC system and pass channels 9 through 12 through the Pixhawk to things such as lights, buzzer, camera switch, etc. 
B.t.w. I tried 2 different Pixhawks b.t.w. to exclude the possibility of hardware damage of the AUX5 (RC13) port.

With 3.3-rc4, the situation became worse, with the exact same parameters file imported: No matter on which AUX output I set the RC*_FUNCTION to 7 or 8, no signal is output.

I have BRD_PWM_CNT set to 6, but I've also tried other values to no avail.

How are gimbal users supposed to get the mount tilt and roll values out on AUX ports for RC13 and RC14 if all other RC outputs are occupied?
The gimbal documentation doesn't go into much detail on this matter.
Mission Planner's gimbal configuration tab doesn't even allow the selection of RC ports above 11, so I perform this configuration in the parameters tree/list.

**Comment by Naterater** [comment]
I have a feeling that this is no longer an issue, and the SERVOn_FUNCTION parameters have been very effective at controlling outputs lately. Please re-open if this behavior is confirmed on a more recent firmware.
