### ISSUE TITLE
Plane: Loiter heading verification radius bug

### ISSUE THREAD

**Issue by FiercedLight** [ArduPilot/ardupilot#23194]
## Bug report
Loiter "exit tangent" option checks if the next waypoint is in loiter radius, if so it skips heading verification. However it uses WP_LOITER_RAD as radius value and this produces unwanted behavior such as stuck in loiter indefinitely or exiting loiter early.

**Issue details**
In mode_loiter.cpp @~Line40(isHeadingLinedUp())  **https://github.com/ArduPilot/ardupilot/blob/052114541a69f543523c511236b2a97e26813266/ArduPlane/mode_loiter.cpp#L40** if next wp is inside loiter circle skips heading verification. However it checks this using default loiter radius(WP_LOITER_RAD param) instead of waypoint's radius parameter. If mission waypoint radius parameter and WP_LOITER_RAD parameter is different this code produces unwanted results. The plane might get stuck on loiter or might break out of loiter early.

This check should use current active loiter radius value.
FYI
**Version**
ArduPlane 4.3, 4.2

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Comment by 007harshmahajan** [comment]
I guess in this https://github.com/ArduPilot/ardupilot/blob/7563dcd916bcd72eb1a4688f38a15f3d26683586/Tools/autotest/arduplane.py#L2013
we have to replace WP_LOITER_RAD with WP_RADIUS
