### ISSUE TITLE
AP_DDS: Add support for PoseStamped

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot#23278]
While #23277 adds support for WGS-84 position reporting, the PoseStamped message is used to report position+orientation in a local coordinate system following ENU convention for ROS2 consumers. 

This is commonly used as the position+orientation component an Odometry message in ROS2, when combined with the appropriate velocity message.

**Comment by pedro-fuoco** [comment]
I'd like to look into it. Can you assign me ? @Ryanf55 
For this first PR should I add support for EKF2, EKF3 and ExternalAHRS ? From what I understand I would need to extract the NED data from one of them and convert it to ENU depending on which one the vehicle is currently using

**Comment by Ryanf55** [comment]
Just talked to @tridge. We are good to continue with only ENU support. Since the conversion is usually trivial, and most ROS community is already in ENU, ArduPilot will expose ENU.

If we need NED, ArduPilot should follow ROS REP 103/105/147 by adding the `_ned` suffix to the frame ID. Perhaps enabled with a parameter so there isn't duplicate data.  Not a priority for now unless someone makes a strong case for it.
