### ISSUE TITLE
Copter: a bug in AC_AttitudeControl::attitude_controller_run_quat(): limit doesn't satisfy SQRT controller

### ISSUE THREAD

**Issue by luweiagi** [ArduPilot/ardupilot#23308]
code: https://github.com/ArduPilot/ardupilot/blob/6839f6c89b51aa94a3961c0ea03470e84409b5f8/libraries/AC_AttitudeControl/AC_AttitudeControl.cpp#L772
```
    // Limit Yaw Error based on maximum acceleration - Update to include output saturation and maximum error.
    // Currently the limit is based on the maximum acceleration using the linear part of the SQRT controller.
    // This should be updated to be based on an angle limit, saturation, or unlimited based on user defined parameters.
    Quaternion yaw_vec_correction_quat;
    if (!is_zero(_p_angle_yaw.kP()) && fabsf(attitude_error.z) > AC_ATTITUDE_ACCEL_Y_CONTROLLER_MAX_RADSS / _p_angle_yaw.kP()) {
        attitude_error.z = constrain_float(wrap_PI(attitude_error.z), -AC_ATTITUDE_ACCEL_Y_CONTROLLER_MAX_RADSS / _p_angle_yaw.kP(), AC_ATTITUDE_ACCEL_Y_CONTROLLER_MAX_RADSS / _p_angle_yaw.kP());
        yaw_vec_correction_quat.from_axis_angle(Vector3f{0.0f, 0.0f, attitude_error.z});
        attitude_target = attitude_body * thrust_vector_correction * yaw_vec_correction_quat;
    }
```

The comment sayes Currently the limit is based on the maximum acceleration using the linear part of the SQRT controller, but the related code is `AC_ATTITUDE_ACCEL_Y_CONTROLLER_MAX_RADSS / _p_angle_yaw.kP()` which I think is not correct.

because:  

In SQRT controller, the linear limit is $2 \times \frac{1}{2} \cdot a \cdot dt^2 = a \cdot dt^2$, so similarly, in here, limit should be `AC_ATTITUDE_ACCEL_Y_CONTROLLER_MAX_RADSS / (_p_angle_yaw.kP() * _p_angle_yaw.kP())`. But in code, it is `AC_ATTITUDE_ACCEL_Y_CONTROLLER_MAX_RADSS / (_p_angle_yaw.kP()`

p.s. We treat _p_angle_yaw.kP() as $1/dt$,

=========================================================

It seems no body see this bug, But I think it may be reasonable:

[Copter: Is there any problem in function euler_accel_limit() ? version-2](https://github.com/ArduPilot/ardupilot/issues/23117)

**Comment by rmackay9** [comment]
Thanks for the report.

We get similar queries about the attitude and position controller fairly regularly and most often they aren't actually bugs but instead are just a misunderstanding of the code.  In any case, I'll leave this one for @lthall to reply to.

**Comment by luweiagi** [comment]
> Thanks for the report.
> 
> We get similar queries about the attitude and position controller fairly regularly and most often they aren't actually bugs but instead are just a misunderstanding of the code. In any case, I'll leave this one for @lthall to reply to.

Aha, I see. Thanks for your reply. Maybe I am wrong but at present I think it may be right and fell anxious without any confirmation. Sorry to disturb you.

**Comment by lthall** [comment]
You are correct in your assessment of the code.

However, this part of the code needs more work as the comments above suggest. This limit should be based on the position error that would saturate the output.

If we assume saturation with static zero yaw rate and linear controllers for example it would be:
1/(_p_angle_yaw.kP() * get_rate_yaw_pid().kP())

With the square root controller it would be something like:
1/(inv_sqrt_controller(_p_angle_yaw.kP(), bla, bla) * get_rate_yaw_pid().kP())

It will limit the angle to something like 10 to 30 degrees.

@luweiagi Thank you for your effort in highlighting problems that you see in the code.

**Comment by lthall** [comment]
#23321
