### ISSUE TITLE
ArduCopter always turning ccw

### ISSUE THREAD

**Issue by Chepa14** [ArduPilot/ardupilot#23322]
## Bug report

**Issue details**

_I'm using ArduCopter ( -f airsim_copter) and it's always spinning CCW, especially in guided mode. I found that parameter ATC_SLEW_YAW is an influence on it - if I put 0 to it, a copter stop spinning. BUT the problem is that in other cases of drone usage it can't change own YAW..._

**Version**
_I'm using latest master branch changes on 24.03.23.
Info from SITL Console:
AP: ArduCopter V4.4.0-dev (467cb75e)
AP: Frame: QUAD/X_

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_AirSim copter_

**Logs**
_Video of flight by [this link](https://drive.google.com/file/d/1cSWGSJ9SGcKbJ06Zu5I_iYJyyc0LmSX_/view?usp=sharing)_

**Comment by lthall** [comment]
There is no sign this is a bug.

Please go to the discuss forum for help.
