### ISSUE TITLE
AP_DDS: Add support for sensor_msgs/BatteryState

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot#23360]
## Feature request
Add support in DDS for publishing Battery Voltage from Ardupilot. Similar to NavSatFix, only use the first battery. Handling multiple GPS's or multiple batteries can be solved later. 

**Describe the solution you'd like**

Publish battery information at a low rate (1Hz). 

**Describe alternatives you've considered**

This is an alternative to mavlink

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by pedro-fuoco** [comment]
I'll take a look
