### ISSUE TITLE
Create doc strings for SITL SIM* variables and autogenerate docs

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#2338]
It would be useful to document the variables that can be used in simulation. 

The documentation should cover which variables are implemented/work for each platform. It should include units and possible range values where appropriate. Ideally it should be generated in one document in the Dev Wiki.

**Comment by amilcarlucas** [comment]
I think this one can be closed now

**Comment by peterbarker** [comment]
Duplicate of https://github.com/ArduPilot/ardupilot/issues/22903

... there are ~200 to document, but we have a ratchet so they get better over time.

The parameters appear in our normal parameters section.
