### ISSUE TITLE
Copter: attitude_error from axis_angle in thrust_vector_rotation_angles() may have problem

### ISSUE THREAD

**Issue by luweiagi** [ArduPilot/ardupilot#23386]
Copter: function AC_AttitudeControl::thrust_vector_rotation_angles( ) may be wrong.

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_AttitudeControl/AC_AttitudeControl.cpp#L780

```
void AC_AttitudeControl::thrust_vector_rotation_angles(const Quaternion& attitude_target, const Quaternion& attitude_body, Quaternion& thrust_vector_correction, Vector3f& attitude_error, float& thrust_angle, float& thrust_error_angle) const
{
    ...
    // calculate the angle error in x and y.
    Vector3f rotation;
    thrust_vector_correction.to_axis_angle(rotation);
    attitude_error.x = rotation.x;   // <=================
    attitude_error.y = rotation.y;  // <=================

    // calculate the remaining rotation required after thrust vector is rotated transformed to the body frame
    // heading_vector_correction
    Quaternion heading_vec_correction_quat = thrust_vector_correction.inverse() * attitude_body.inverse() * attitude_target;

    // calculate the angle error in z (x and y should be zero here).
    heading_vec_correction_quat.to_axis_angle(rotation);
    attitude_error.z = rotation.z;  // <=================
    ...
}
```
here, the code thinks that body angle error is attitude_error.x.y.z, but attitude_error.x.y.z is mixer of body angle error and yaw rotation.
like:
![thrust-tilt-separation](https://user-images.githubusercontent.com/19629731/229661088-b5f2d2bb-42c0-4463-a756-44b3e3ea04e1.png)
i.e. 
```
    attitude_error.x = rotation.x;   // <=================
    attitude_error.y = rotation.y;  // <=================
```
this means body error in x, y axis, witch is not roll and pitch in euler frame.
but 
```
    attitude_error.z = rotation.z;
```
this means body error in z axis, which means yaw in euler frame. BUT, it should be the body error like rotation.x and rotation.y.

Here is difficult to describe, but I will try to say more clear:

Let's think roll pi/6(30 degrees) and yaw pi/4(45 degrees) rotation in XYZ(NOT ZYX) euler frame, which is shown as above figure
```
        % from XYZ euler to quat
        quat_roll = quaternion([pi/6, 0, 0], 'euler', 'XYZ', 'frame')  % 0.96593+0.25882i+0j+0k
        quat_yaw = quaternion([0, 0, pi/4], 'euler', 'XYZ', 'frame')  % 0.92388+0i+0j+0.38268k
        %  get final quat from two middle quat
        %  roll 30 deg, then yaw 45 deg
        quat_ry_q = quat_roll * quat_yaw  % 0.8924+0.23912i-0.099046j+0.36964k
        % from quat to euler (XYZ)
        euler_xyz_q = eulerd(quat_ry_q,'XYZ','frame')  % [[roll=30, pitch=0, yaw=45]
        % get angle (NOT euler angel) with no order
        angle_xyz = rotvecd(quat_ry_q) % 28.4280  -11.7753   43.9459
```
So, we can see that if rotate as the order of roll pi/6(30 degrees) and yaw pi/4(45 degrees) rotation in XYZ(NOT ZYX) euler frame, we can get the angle error [28.4280  -11.7753   43.9459] in body frame.
We want the body frame angle error for control, so we should not use euler frame angle, but use body angle error. i.e.[28.4280  -11.7753   43.9459].
If we follow current apm code logit, the angle error for control is [roll=30, pitch=0, yaw=45], but the right answer is [28.4280  -11.7753   43.9459].
I think I have already explained it very clearly.

So, in AC_AttitudeControl::thrust_heading_rotation_angles( ) (I use old version just for convenient), we should repalce the last code from A to B:
A:
```
    Quaternion heading_quat = thrust_vec_correction_quat.inverse()*att_from_quat.inverse()*att_to_quat;

    Vector3f rotation;
    thrust_vec_correction_quat.to_axis_angle(rotation);
    att_diff_angle.x = rotation.x;
    att_diff_angle.y = rotation.y;

    heading_quat.to_axis_angle(rotation);
    att_diff_angle.z = rotation.z;

    if(!is_zero(_p_angle_yaw.kP()) && fabsf(att_diff_angle.z) > xxx){
        att_diff_angle.z = constrain_float(wrap_PI(att_diff_angle.z), -xxx/_p_angle_yaw.kP(), xxx/_p_angle_yaw.kP());
        heading_quat.from_axis_angle(Vector3f(0.0f,0.0f,att_diff_angle.z));
        att_to_quat = att_from_quat*thrust_vec_correction_quat*heading_quat;
    }
```
B:
```
    Quaternion heading_quat = thrust_vec_correction_quat.inverse()*att_from_quat.inverse()*att_to_quat;

    Vector3f rotation;
    thrust_vec_correction_quat.to_axis_angle(rotation);
    att_diff_angle.x = rotation.x;
    att_diff_angle.y = rotation.y;

    heading_quat.to_axis_angle(rotation);
    att_diff_angle.z = rotation.z;

    if(!is_zero(_p_angle_yaw.kP()) && fabsf(att_diff_angle.z) > xxx){
        att_diff_angle.z = constrain_float(wrap_PI(att_diff_angle.z), -xxx/_p_angle_yaw.kP(), xxx/_p_angle_yaw.kP());
        heading_quat.from_axis_angle(Vector3f(0.0f,0.0f,att_diff_angle.z));
        att_to_quat = att_from_quat*thrust_vec_correction_quat*heading_quat;
    }
    (thrust_vec_correction_quat*heading_quat).to_axis_angle(rotation);
    att_diff_angle.x = rotation.x;
    att_diff_angle.y = rotation.y;
    att_diff_angle.z = rotation.z;
```

**Comment by lthall** [comment]
Yes, this is an interesting decision I made. This is done as a two rotation system. The first removes error in roll and pitch, then the second removes the yaw error afterwards. This is for two reasons, roll and pitch is both the most important control axis and the fastest to respond. Second is we must expect to loose control of yaw completly during a motor loss. This approach lets me prioritise roll and pitch attitude control over yaw, without compromise.

So to try to summarise. We control roll and pitch like there is always zero yaw error, or we don't care about yaw angle. Then we control yaw like there is no roll and pitch error under the assumption that yaw is much slower or less accurate than roll and pitch.

**Comment by luweiagi** [comment]
> Yes, this is an interesting decision I made. This is done as a two rotation system. The first removes error in roll and pitch, then the second removes the yaw error afterwards. This is for two reasons, roll and pitch is both the most important control axis and the fastest to respond. Second is we must expect to loose control of yaw completly during a motor loss. This approach lets me prioritise roll and pitch attitude control over yaw, without compromise.
> 
> So to try to summarise. We control roll and pitch like there is always zero yaw error, or we don't care about yaw angle. Then we control yaw like there is no roll and pitch error under the assumption that yaw is much slower or less accurate than roll and pitch.

Thank you for the very patient and affable reply! 

Now I figure out why it is always said that there is a sequence: first roll/pitch and then yaw. I used to think it was an instantaneous mathematical process.

Now I kown the reason is roll/pitch change is fast because motor force derectly change roll/pitch, and yaw change is slow because it relys on the torque difference of motors which is indirectly and not enough. So it creats a physical-existing sequence of "roll/pitch change first and yaw change second".

**Comment by lthall** [comment]
>> @lthall Thank you for the very patient and affable reply!

Mate, I am very appreciative of your willingness to read through the code so thoroughly and bring anything that doesn't look quiet right to my attention. People like yourself make a very significant contribution to this code base!!

You are more than welcome to reach out to me for any help you need, or questions you have!

**Comment by esaldiran** [comment]
@luweiagi There are multiple academical study that goes deep into mathematical derivation of this approach such as [Tilt-prioritized quadrocopter attitude control](https://ieeexplore.ieee.org/abstract/document/8556372). I hope you find it helpfull.

**Comment by lthall** [comment]
@esaldiran Thanks for that link. The abstract of that paper does seem to describe something similar to the approach I took here. However, none of my work has been inspired by, or based on, any academic paper so I am not sure how close the math of this approach and my approach are.

**Comment by luweiagi** [comment]
> 


Thanks! I have download this paper http://brescianini.info/wp-content/uploads/publications/breTCST18.pdf, and will read it when I have time.
> @luweiagi There are multiple academical study that goes deep into mathematical derivation of this approach such as [Tilt-prioritized quadrocopter attitude control](https://ieeexplore.ieee.org/abstract/document/8556372). I hope you find it helpfull.

**Comment by luweiagi** [comment]
> Mate, I am very appreciative of your willingness to read through the code so thoroughly and bring anything that doesn't 

@lthall  Thanks, I feel interesting and happy to try to understand how anthor thinks when he is writing code.

There is a question I have never understood for several years. I haven't found a suitable opportunity to consult you. This problem has been bothering me for a long time. I am very curious about it and want to know why you write this code.

In function attitude_controller_run_quat():
https://github.com/ArduPilot/ardupilot/commit/ad6e2eeed838e734fba5c946874e2bd2ef3ad1ed

![image](https://user-images.githubusercontent.com/19629731/230892992-1217afbf-c2a5-49c8-89be-fc57376dc9c5.png)

**Comment by lthall** [comment]
This was something I was unsure if it was good or bad and I eventually decided it was the wrong thing to do.

In the case of lost yaw control this keeps the roll and pitch angle error constant-ish so that the attitude controller doesn't need to be as fast. My concern was that if the aircraft was rotating at say 1 Hz or faster the latency in the attitude controller could result in the corrections being out of phase.

I tried a number of times over the years to establish if it made things better or not but I couldn't satisfy myself that it was the right way to go. I couldn't justify it, it is not clear to others what it is doing, I removed it.

**Comment by lthall** [comment]
I think we are fine to close this now @luweiagi. Let me know if I should reopen.

**Comment by lixiaowei123** [comment]
> @esaldiran Thanks for that link. The abstract of that paper does seem to describe something similar to the approach I took here. However, none of my work has been inspired by, or based on, any academic paper so I am not sure how close the math of this approach and my approach are.
Hello, I would like to know how you came up with this method at that time. Is there no reference available
