### ISSUE TITLE
AP_DDS: Publish GPS sensor transform with ROS 2 static transform broadcaster

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot#23393]
## Feature request

**Is your feature request related to a problem? Please describe.**
Right now, AP_DDS publishes the location of the first GPS receiver. The LLA coordinates are in the frame of the GPS. In order to do any fusion of this GPS, the location of it relative to the aircraft origin needs to be known by the companion computer.

**Describe the solution you'd like**
AP_DDS implements a static transform broadcaster. Using the following params, publish the transforms, on boot. If params are updated at runtime, re-publish the static transform. Abide by ROS 2 QoS for transform broadcaster.

* GPS_POS1_X
* GPS_POS1_Y
* GPS_POS1_Z
* GPS_POS2_X
* GPS_POS2_Y
* GPS_POS2_Z

Since there are no orientation params for the GPS, assume it's pointing up and also assume that any rotational offset is negligible to the solution

**Describe alternatives you've considered**
Exposing the params over DDS and letting the consumer query them directly. 

**Platform**
[x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

https://docs.ros.org/en/humble/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.html

**Dependencies**
#23277 
#23259

**Comment by srmainwaring** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/23412
