### ISSUE TITLE
Latest ChibiOS update in master branch breaks PPM sum RC input on MatekH743 Wlite

### ISSUE THREAD

**Issue by casrya** [ArduPilot/ardupilot#23404]
## Bug report

**Issue details**
Latest ChibiOS update in master branch breaks PPM sum RC input on MatekH743 Wlite

_Please describe the problem_
After Master commit 1e164c5221e619a42dfdf85bfd423b555c009a88, PPM sum input on PC7 (USART6/SERIAL7) stopped working.

I got a no RC input pre arm error and received no mavlink RC messages to ground station.

I looked through the recent commits and was able to identify that the problem occurred at commit 1e164c5221e619a42dfdf85bfd423b555c009a88.

Luckily, after looking at the specific commit, I was able to fix it by adding the following to hwdef.dat
      STM32_PWM_USE_TIM3 TRUE

That said, I could not actually work out why the specific commit caused the problem because it was the STM32_EICU_USE_TIM3 check that was added in the commit and this was already defined in the generated hwdef.h. That said, I don’t have a lot of experience with ChibiOS so if anyone can shed light on why this particular commit broke the PPM it would be appreciated in case I need to do any further debugging down the line and it might help others as well!

Anyway, perhaps PPM is uncommon these days but it works well enough that I had planned on using it until it breaks :) 

P.S I generally run my own code base but tested this issue against a freshly cloned master to make sure that it wasn’t something specific to my build.

**Version**
_What version was the issue encountered with_
Master at commit 1e164c5221e619a42dfdf85bfd423b555c009a88

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Quad X4

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
MatekH743 W-lite and 8ch PPM sum decoder for old Spektrum RC

**Logs**
_Please provide a link to any relevant logs that show the issue_

I don’t have a log but if needed I can set LOG_DISARMED and flash the unfixed firmware again and get a log but I think is really a case of @andyp1per (the author) or someone who is more familiar with ChibiOS taking a look at the code.

**Comment by andyp1per** [comment]
Thanks for the report. The EICU port was untested as I didn't know how and the driver is very old, so the port was quite complicated. Apologies for the inconvenience - I think you have hopefully provided enough experience for me to fix this.

**Comment by casrya** [comment]
Hi Andy, thanks for looking into it and getting back so quickly and let me know if I can help with anything. I have been searching through the code trying to find out why the STM32_PWM_USE_TIM3 had any effect since looking at AP_HAL_ChibiOS/RCInput.cpp I see it only uses EICU or ICU (the latter is macro’d out for my case) and the generated RC config in hwdef.h looks ok. So I am pretty stumped but hopefully you can work it out and I am happy to test anything if needed :)

**Comment by andyp1per** [comment]
Can you try https://github.com/ArduPilot/ardupilot/pull/23405 ? I think I kow what is going on

**Comment by casrya** [comment]
Tested and confirmed fixed, thanks :)
