### ISSUE TITLE
AP_DroneCAN : SITL build fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by FatihBaykal** [ArduPilot/ardupilot#23522]
![image](https://user-images.githubusercontent.com/107719593/232341685-43a32b77-c7f8-4385-945c-3256bdff48ad.png)

I am encountering this error. Can someone help?

**Version**
ArduCopter V4.4.0

**Platform**
[  ] All
[  ] AntennaTracker
[ x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
N/A

**Hardware type**
N/A

**Logs**
N/A

**Comment by MinGiKYUNG** [comment]
I have same problem

**Comment by IamPete1** [comment]
Will be fixed soon, https://github.com/ArduPilot/ardupilot/pull/23494

**Comment by IamPete1** [comment]
Fixes is merged, you should be able to build again if your rebase on master.
