### ISSUE TITLE
AP_DDS: Support publishing GeoPoseStamped

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot#23534]
I always viewed `NavSatFix` as rawish sensor data more than an actual position output.
Similar to the way for orientation we use a `Pose` message with a `Quaternion` field, and not, say, a `MagneticField` (https://docs.ros2.org/foxy/api/sensor_msgs/msg/MagneticField.html) message.

As it's appropriate here, I'll mention the option of using the `geographic_msgs` `GeoPoseStamped` (https://github.com/ros-geographic-info/geographic_info/blob/ros2/geographic_msgs/msg/GeoPoseStamped.msg) type.

_Originally posted by @russkel in https://github.com/ArduPilot/ardupilot/issues/23277#issuecomment-1499895214_

This ticket is to add GeoPoseStamped support, which is the fused GPS position of the vehicle (from AHRS).

**Comment by pedro-fuoco** [comment]
I'll look into it!
