### ISSUE TITLE
Sign error in ellipsoid height calculation

### ISSUE THREAD

**Issue by makeller1** [ArduPilot/ardupilot#23613]
## Bug report

**Issue details**
Seeing a sign error on how the ellipsoid height is calculated.
[The undulation is subtracted from alt here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/AP_GPS.cpp#L1421)
`height_elipsoid_mm = loc.alt*10 - undulation*1000;`

Which doesn't make sense considering the alt is calculated as [height - undulation](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/AP_GPS_SBF.cpp#L418)
`state.location.alt = (int32_t)(((float)temp.Height - temp.Undulation) * 1e2f);`

That would imply ellipsoid height = height - 2 * undulation. 

@hendjoshsr71 

**Version**
Master

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by rmackay9** [comment]
This is probably one for @tridge, @hendjoshsr71 and/or @BluemarkInnovations to look into as the code was added in PR https://github.com/ArduPilot/ardupilot/pull/21075

**Comment by makeller1** [comment]
Addressed by PR https://github.com/ArduPilot/ardupilot/pull/23942.

**Comment by tridge** [comment]
thanks! fixed with your PR
