### ISSUE TITLE
Copter: stability patch for Tri to allow 100% Throttle

### ISSUE THREAD

**Issue by Johnex** [ArduPilot/ardupilot#2363]
Hi!
Unfortunately it seems like the tricopter code in some areas gets left behind :(
I hope Randy can rework the tricopter stability patch to allow 100% throttle, from the max 80% now.

**Comment by davidbuzz** [comment]
it looks to me like Tri-copters got their "stability patch" in https://github.com/diydrones/ardupilot/commit/78acea820fbcdd26ad442f5ff3856d26f513d545   and https://github.com/diydrones/ardupilot/issues/537.   Is there any reason they are still limited to 80% throttle?

**Comment by lthall** [comment]
done
