### ISSUE TITLE
Unable to use ST24 receiver

### ISSUE THREAD

**Issue by lipper-chengdu** [ArduPilot/ardupilot#23740]
## Bug report

**Issue details**
Unable to use ST24 receiver
I found a bug in the ST24 receiving and processing code. I will fix it

**Version**
ArduCopter V4.4.0-dev

**Platform**
[*] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
Pixhawk
**Logs**
AP_RCProtocol_ST24.cpp

**Comment by peterbarker** [comment]
You fixed this!
