### ISSUE TITLE
Storm32 mavlink gimbal initialises incorrect tilt without RC input

### ISSUE THREAD

**Issue by fnoop** [ArduPilot/ardupilot#2375]
Hi, I'm using the storm32 mavlink mount setup with 3.3rc5.  If I turn the copter on without turning the transmitter (taranis/rx8) on, after the gimbal has gone through it's calibration/initialisation and beeped to say it's ready, it then tries to move pitch to an impossibly minimum position (it pitches down and backwards until it's physically stopped).    As soon as the tx is turned on, it moves back to the ch6 position as expected.  Everything is setup exactly as described in the apm/storm32 wiki page, and works as expected apart from this little issue.

**Comment by khancyr** [comment]
It should have been solve by #9953, please reopen if not
