### ISSUE TITLE
test.Plane: TestGripperMission  is failing repeatedly

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot#23754]
## Bug report

**Issue details**

The gripper tests for ArduPlane are flaky, and preventing me from merging PR's. The below log is attempt 4. This is hindering development because I can't merge a PR with a failing test. 

**Version**

`master` on hash `c1fe95f726a34534c1d8ef774748c851d4315f04`

**Platform**

[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Logs**

(https://github.com/ArduPilot/ardupilot/actions/runs/4940550757/jobs/8839478028)

```
AT-1563.5: mavproxy_start was called 3 times
AT-1563.5: Supplied terrain data to autopilot in 840 messages
Had to force-reset SITL 2 times
>>>> FAILED STEP: test.Plane at Thu May 11 07:03:31 2023
Failure Summary:
  test.Plane:
    TestGripperMission (Test Gripper mission items) (Failed to receive text: auto disarmed) (see /tmp/buildlogs/ArduPlane-TestGripperMission.txt)
    FRSkyPassThroughSensorIDs (test FRSKy protocol's telem-passthrough functionality (sensor IDs)) (Expected MAV_RESULT_ACCEPTED got MAV_RESULT_FAILED) (see /tmp/buildlogs/ArduPlane-FRSkyPassThroughSensorIDs.txt)
FAILED 1 tests: ['test.Plane']
```

**Comment by peterbarker** [comment]
I don't think this one is flapping any more
