### ISSUE TITLE
Dangerous altitude oscillations in AUTO mode but not in RTL and Guided modes

### ISSUE THREAD

**Issue by jankrystianserafim** [ArduPilot/ardupilot#23866]
## Bug report

**Issue details**

We are having an issue with altitude oscillations. There is some high magnitude oscillations in altitude in AUTO mode while the drone is approaching or leaving a waypoint. These oscillations start after the drone has completed the VTOL to Fixed-Wing transition, and they only happen in AUTO mode (the drone flies perfect in RTL and Guided). I am attaching a screenshot of the log so you can see the problem, as well as the parameters from the drone.

 It is worth adding that this problem did not occur during flights in Poland, it only started during flights in Gambia. We did not change any parameters when we went from Poland to Gambia. 
 
So my question boils down to - **what are the differences in altitude / airspeed control in AUTO vs RTL and Guided modes?** Because our drone is flying great in RTL, but the altitude oscillations in AUTO are unacceptable. 

Also, since the drone is flying fine in RTL mode, we have to rule out any hardware/physical issues (e.g. the elevator is damaged or the drone cannot fly fast enough) unless these issues would cause a problem for AUTO mode without causing any issues to RTL.

**Version**
ArduPlane 4.1.1

**Platform**
Plane

**Airframe type**
QUADPLANE

**Hardware type**
Cube Orange

**Logs**
(The blue line = GPS 1 altitude , green and red = barometer 1 and 2 altitude)
![image](https://github.com/ArduPilot/ardupilot/assets/56222672/8401defc-4683-4ba8-8717-ddcb6cdce96b)
I am attaching the .BIN files of a nice flight from Poland and then the flight from Gambia with the altitude oscillations here: https://drive.google.com/file/d/1msVq3OpRVRa69oCSxSKgj0tP96VXikU4/view?usp=sharing
https://drive.google.com/file/d/1SJcTrP1oALMBRMx-r2gHOMffP2emk4Ub/view?usp=sharing

**Comment by IamPete1** [comment]
Looks like the vehicle is just not stable in forward flight, the "oscillations" are caused by the forward flight control diverging and then the VTOL motors kicking in and saving it. The "RTL" is actually a "QRTL" its fine there because its VTOL flight.

I would guess your left and right V tail servos got swapped at some-point.

**Comment by jankrystianserafim** [comment]
@IamPete1  Thanks for the quick reply. I am attaching a picture of our drone here. If I am understanding you correctly, then you're suggesting that the marked elevator servos got swapped?

<img width="220" alt="image" src="https://github.com/ArduPilot/ardupilot/assets/56222672/338df482-fac2-452c-b437-aae1cc89ab63">

**Comment by IamPete1** [comment]
That was just a guess, fixed wing pitch control is certainly not working correctly. Could be CG position, loose connection to the servos. The reported servo voltage looks OK. As you said no changes in the params between those flights that would cause this problem, such as a servo being reversed in software. 

The other half of the RC check is to make sure the vehicle does the correct control moment to recover from a disturbance. Other wise you may be suffering from the double reverse where both the RC input and the servo outputs are reversed such that it looks correct in manual mode.

**Comment by jankrystianserafim** [comment]
@IamPete1 . Would the way to test that we don't have a double reserve problem we to power up the drone , put it into QLOITER mode while disarmed, and then tilt it around on the ground by hand and see if the elevator / aileron response is correct?

With regard to source of the error, we think its due to some EKF issues. Take a look at what happens in this .tlog between when VTOL takeoff is completed and QRTL happens (you can watch the .tlog from 54% to 60%). Do you think that's a possibility? 
https://drive.google.com/file/d/17PtoWT18nTbLFMu_7qmKM_b8z6PIWZ0e/view?usp=sharing

**Comment by IamPete1** [comment]
FBWA would be the mode to use to test control surface moment. Q modes do control surfaces a little differently. But yeah, leave the sticks neutral and move the vehicle about. 

Its fundamentally a pitch control problem, EKF issues are a side effect.

![image](https://github.com/ArduPilot/ardupilot/assets/33176108/765881df-d3f2-4a9d-9133-64cc363be16e)

**Comment by jankrystianserafim** [comment]
@IamPete1 We just tested this in AUTO mode with the drone disarmed and on the ground. The behavior appears to be correct. When we move the nose down, both of the elevators on the tail move up, and when we move the nose up, both the elevators on the tail move down. (We also made sure that the roll and the ailerons were fine). 

Should we test again in FBWA, or is testing this in AUTO mode sufficient? Should we conduct the test when the drone is armed or does it not matter if its disarmed or armed?

**Comment by IamPete1** [comment]
Disarmed in auto should be fine.

**Comment by jankrystianserafim** [comment]
@IamPete1 That's what we did. No issues, the drone behaved correctly. Any ideas what the problem could be given its not this double reverse issue?

**Comment by jankrystianserafim** [comment]
Maybe some of the local ArduPilot experts could help us out with their insights here? @tridge , @peterbarker , @rmackay9 , @lucasdemarchi , @WickedShell, @khancyr @bugobliterator  ? Thanks!

**Comment by khancyr** [comment]
Could you please not spam everybody?

And support question belong to discuss, issue ok GitHub are for code issues. You will find there numerous experts even from the community 
Thanks

**Comment by jankrystianserafim** [comment]
@khancyr I did not mean to spam everybody, I just know you guys have expertise here, that's all!

**Comment by jankrystianserafim** [comment]
A suggestion that came in based on the observation that the desired pitch was far different to the actual pitch. Maybe there is an issue with the mission that the drone is flying in AUTO mode? (This would also then explain why it flies fine in RTL and Guided, when there is no mission).

![image](https://github.com/ArduPilot/ardupilot/assets/56222672/82279e11-0ebd-43cb-bb8e-37789bf87220)

**Comment by jankrystianserafim** [comment]
Hi All,

We are looking for urgent (paid!) support with this issue. Here are the details. Please share this or contact me for details - thank you!

https://discuss.ardupilot.org/t/urgent-paid-offer/101529

**Comment by jankrystianserafim** [comment]
Greetings All,

Firstly, I want to thank @tridge for the amazing support with resolving this problem. My team and I appreciate it greatly.

Now, I'd like to dive into what the root of the problem actually was, and how we solved it.

1. @tridge noticed some non-official ArduPlane parameters pertaining to quadplane behaviour in our drone parameters. Q_ASSIST_ALT_MOD gave away the fact that this was some heavily customised firmware that the manufacturer had flashed onto the drone (of course without advertising this anywhere beforehand or even notifying any of our pilots).

2. The firmware that had been flashed onto this drone by its manufacturer (YANGDA) has come to be called "Hong Kong Chris" firmware and has a terrible PID controller, as well as a few other oversights that aren't present in official ArduPlane firmware.

3. YANGDA's tune of this drone was hanging on a thread, but they managed to somehow get it to appear to fly fine (visually that is).

4. When we moved this drone (the FW320 VTOL) to West Africa for our flight operations here, the tune was simply too bad to handle the change in conditions and caused the drone to behave like I described earlier in this thread.

5. The usual TECS / PID etc tuning that would address such issues on a drone with official firmware were not working, as despite some of these parameters existing on the drone they actually had no effect, which made the drone nearly impossible to tune.

**Solution?** 
Reflashing the Cube Orange with official ArduPlane v4.3.5 firmware and pretty much stock PIDs with only a bit of tuning of the ARSPD_RATIO based on logs. From a tuning standpoint, the drone now flies amazing.

**Comment by jankrystianserafim** [comment]
I hope this helps anyone who finds themselves granted the great "pleasure" of working with a drone flashed with "Hong Kong Chris" firmware. 

From what I know, these will be many older Foxtech models, as well as YANGDA models (pretty much all ArduPlane VTOLs sold before 2023, but possibly some sold later as well).

**Comment by IamPete1** [comment]
Thanks for the update!

**Comment by HECTOPGEO** [comment]
Dear jankrystianserafim. I have the same problem as you. VTOL from Foxtech, AYK -2500, YANGDA has an analogue of YANGDA Sky Fury. If you have the same plane, could you give the firmware number and the Parameter file? Thank you.
