### ISSUE TITLE
Copter/Rover-4.5.0-DEV: Here3 GPS LEDs not working

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#23978]
A change has gone into master recently which has broken the Here GPS LEDs for CubeOrange using DroneCAN (at least).  Some extra info:

- so far only CubeOrange and CubeBlack are affected.  CubeOrangePlus is fine
- affects both Copter and Rover (and probably all other vehicles)

Copter/Rover-4.4.0-beta2 is fine.  Stable is also fine.

**Comment by peterbarker** [comment]
@bugobliterator 
![image](https://github.com/ArduPilot/ardupilot/assets/7077857/bccbf7d3-64bc-41a6-be6c-46386f7741c6)

**Comment by tridge** [comment]
fixed in #24133
