### ISSUE TITLE
Copter: do_user_takeoff needs Heli runup integration.

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#2403]
Currently, appears like issuing a do_user_takeoff will cause heli to try to take off prematurely.

**Comment by R-Lefebvre** [comment]
Same issue with MAV_CMD_MISSION_START

**Comment by peterbarker** [comment]
@R-Lefebvre We appear to have protection for both these cases now:

https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode_auto.cpp#L178
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/takeoff.cpp#L31

Closing.
