### ISSUE TITLE
AP_Camera: support the CAMERA_FOV_STATUS message

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#24038]
The [CAMERA_FOV_STATUS](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L5839) message tells the GCS the Location (e.g. lat, lon and alt) of what the camera is looking at.

We could add support for this message by converting the [mount-poi](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/applets/mount-poi.lua) Lua script to C++.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
I want to work over this @rmackay9  can I be assigned this ?

**Comment by rmackay9** [comment]
@SANTHOSH-MAMIDISETTI,

Sure, go for it.  In general we review and (hopefully) merge whichever PR gets raised first though.. still, I don't know of anyone else working on this issue.

**Comment by rmackay9** [comment]
Support for this has been added now so closing.
