### ISSUE TITLE
Copter/Plane: "CAM_TRIG_TIMER" parameter

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#2410]
One nice feature is being able to take photos in sequence by delaying the shutter with a timer parameter.
Some cameras (like Sony A5000) don't have this functionality in the firmware, i think it's simple to implement, and very usefull.
"CAM_TRIG_TIMER" it could be a settable parameter in second (with decimal unit), for example "1.5" takes a photo every 1.5 seconds.
Obviously "CAM_TRIG_DIST" should take priority, in all cases.
With some tx this function is easy to implement, such as with the Taranis (using the "Camera Trigger channel"), but obviously not with all.
It would also be interesting if this feature could turn on or off by tx (with CH7/8 option).

**Comment by iskess** [comment]
What would be a scenario where you would prefer an intervelometer over distance based triggering? 
I just thought of one, a copter is hovering and measuring change on the ground. It seems video would suffice in that example. For mapping, I can't think of any advantages of using an intervelometer.

**Comment by robustini** [comment]
In some situations it can be very convenient.
Of course, i also use "CAM_TRIG_DIST" for mapping.

**Comment by AndKe** [comment]
@robustini  - take a look at this https://github.com/diydrones/ardupilot/pull/3222   - when I made it, I thought it could could be used as intervalometer too, just set a very short CAM_TRIG_DISTANCE , and use MIN_INTERVAL to define time between.

Speaking about camera trigging: any idea what's my problem here ?  http://ardupilot.com/forum/viewtopic.php?f=111&t=15166

**Comment by Naterater** [comment]
The delay is currently active as CAM_MIN_INTERVAL and is effective. I have personally tested it. http://ardupilot.org/plane/docs/parameters.html#cam-min-interval-minimum-time-between-photos
