### ISSUE TITLE
Plane: GCS only operation now broken

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#24136]
While checking what if anything needs to be updated in the wiki for your PR #23189 , I discovered that GCS only operation is now broken....if you set THR_FAILSAFE to 0 and arming checks to 65470 (although setting to 1 makes no difference, you can still arm), then it displays in the HUD "No RC receiver" even if RC Protocols is 0, but does not prevent arming....
once armed, 100% of the time you get a "Unhealthy AHRS" it drops to DCM and never recovers....if disarmed it bounces back to EKF3
happens in 4.3.7 and in master...may try to bisection it if I get time
I checked as far back as 4.1.7....same behaviour....

video demo using master
https://www.dropbox.com/s/zbzgw2pubf23sq1/norcmp4.mp4?dl=0

**Comment by rmackay9** [comment]
I think this only affects Plane so I've changed the title and added a label.

**Comment by Hwurzburg** [comment]
red herring....this was compassless on the bench...no yaw source=unhelathy AHRS
