### ISSUE TITLE
HAL: Clear HAL dependencies on other files

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#24163]
I saw that in AP_ HAL and AP_ HAL_ Linux related files need to include Header file from other libraries. I think this is unreasonable. We need to reduce this dependency as much as possible?

**Comment by khancyr** [comment]
hello,

Yes, we agree, but something that isn't possible. We got a background task to restructure everything but it takes time.
New contribution on this sens are welcome!

**Comment by xianglunkai** [comment]
@khancyr 
Txs! I think PX4 is good on this point, but i like ardupilot stye in C++.
