### ISSUE TITLE
Builds are generating object files in working directory

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#2417]
Since the recent PX4 merge a "make px4-v2" will dump object files (*.o and *.d) into the working directory which makes things quite messy. They should go into /obj or /temp or somewhere other than the working directory and also be cleaned correctly.

**Comment by lucasdemarchi** [comment]
@magicrub what does "quite messy" look like?

**Comment by magicrub** [comment]
my /ArduPlane folder triples in file count with every .cpp file now having a .cpp.d and .cpp.o file which then refreshes my eclipse folder browser. Also, searches done in Eclipse now include those files.

**Comment by lucasdemarchi** [comment]
@magicrub ok, makes sense.

**Comment by magicrub** [comment]
@guludo is this something in your realm of expertise?

**Comment by lucasdemarchi** [comment]
@magicrub this is caused by PX4's build system.  It will eventually go away when waf is driving the PX4 build through its cmake integration.

**Comment by lucasdemarchi** [comment]
@magicrub meanwhile you could also add exclusion filters in eclipse so it doesn't look for these files in the browser or search

**Comment by magicrub** [comment]
Got it, thanks.

**Comment by guludo** [comment]
@magicrub, sorry for the delayed answer. But as @lucasdemarchi said, that should be fixed when PX4 build is integrated in waf. :-)

**Comment by OXINARF** [comment]
@magicrub Do you still want this open? waf build system uses a build folder for all produced files, but Make still pollutes the source dir.

**Comment by magicrub** [comment]
This should stay open as long as we support make

**Comment by khancyr** [comment]
make isn't support anymore, closing
