### ISSUE TITLE
Add pre-arm check for PID sanity

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot#2424]
As written [on DIYD](http://diydrones.com/profiles/blogs/on-the-importance-of-being-thorough-when-setting-up-your-uav), I had a mild copter crash due to me inadvertently setting all THR_\* PIDs to zero. In this context, Randy suggested a basic PID sanity pre-arm check on the dev list to make sure, important PIDS do make some basic sense.
Not sure how much sense that would make for Plane and Rover but for Copter and Tradheli, it probably would make lots of sense.

**Comment by rmackay9** [comment]
Bumping to AC-3.5.  We're simply out of time for AC-3.4.

**Comment by lthall** [comment]
I don't think you should include the D term as some of the Copter aircraft don't use them. If the FF is set then you should ignore the PID too.
