### ISSUE TITLE
Small Documentation and Parameter Typo

### ISSUE THREAD

**Issue by SuperSox** [ArduPilot/ardupilot#24265]
## Bug report

**Issue details**
Small Typo in a parameter. Per link A, the Batt_Volt_Mult parameter is 11.5. It also says the parameter should already be a default in the default config parameters. However, When I look at the default config parameters in mission planner, the value is actually 11.05. A zero got added or subtracted - I don't know which.  

Link A: https://ardupilot.org/rover/docs/common-speedybeef405wing.html

**Version**
ArduPlane V4.5.0-dev on a SpeedyBee WingF405 board.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Plane

**Hardware type**
SpeedyBee WingF405 board.

**Logs**
None

**Comment by Hwurzburg** [comment]
fixed wiki doc
