### ISSUE TITLE
Camera Trigger GPS Logging with Gimbal

### ISSUE THREAD

**Issue by Jman841** [ArduPilot/ardupilot#2435]
I am not 100% sure if this is already implemented but I believe it is not.

Would it be possible if using the pixhawk for gimbal stabilization to take the roll of the gimbal into account for the GPS IMU data when doing mapping missions?

I am currently hesitant to add a roll axis gimbal (using a servo and the pixhawk) to our camera because I believe the roll axis of the GPS data will be that of the pixhawk and not of the gimbal (IE the photo) so it may skew the results even further in the photogrammetry software.

Would it be possible to account for this to predict what the true axis of the camera is based on the gimbal correction from the pixhawk and the IMU data?

**Comment by Naterater** [comment]
This mount information is available in the logs.
