### ISSUE TITLE
loiter mode _brake_timer update

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#24400]
if (!is_zero(desired_speed))
    {
        Vector2f desired_vel_norm = desired_vel / desired_speed;

        // calculate a drag acceleration based on the desired speed.
        float drag_decel = pilot_acceleration_max * desired_speed / gnd_speed_limit_cms;

        // calculate a braking acceleration if sticks are at zero
        float loiter_brake_accel = 0.0f;
        if (_desired_accel.is_zero())
        {
            if ((AP_HAL::millis() - _brake_timer) > _brake_delay * 1000.0f)
            {
                float brake_gain = _pos_control.get_vel_xy_pid().kP() * 0.5f;
                loiter_brake_accel = constrain_float(sqrt_controller(desired_speed, brake_gain, _brake_jerk_max_cmsss, dt), 0.0f, _brake_accel_cmss);
            }
        } else
        {
            loiter_brake_accel = 0.0f;
            _brake_timer = AP_HAL::millis();
        }
        _brake_accel += constrain_float(loiter_brake_accel - _brake_accel, -_brake_jerk_max_cmsss * dt, _brake_jerk_max_cmsss * dt);
        loiter_accel_brake = desired_vel_norm * _brake_accel;

        // update the desired velocity using the drag and braking accelerations
        desired_speed = MAX(desired_speed - (drag_decel + _brake_accel) * dt, 0.0f);
        desired_vel = desired_vel_norm * desired_speed;
    }
////////////////////////////////////////////////////////

Should updates be made during initialization and else？
    else
    {
    	_brake_timer = AP_HAL::millis();
    }

/////////////////////////////////

void AC_Loiter::init_target(const Vector2f& position)
{
    sanity_check_params();

    // initialise position controller speed and acceleration
    _pos_control.set_correction_speed_accel_xy(LOITER_VEL_CORRECTION_MAX, _accel_cmss);
    _pos_control.set_pos_error_max_xy_cm(LOITER_POS_CORRECTION_MAX);

    // initialise position controller
    _pos_control.init_xy_controller_stopping_point();

    // initialise desired acceleration and angles to zero to remain on station
    _predicted_accel.zero();
    _desired_accel.zero();
    _predicted_euler_angle.zero();
    _brake_accel = 0.0f;
    _brake_timer = AP_HAL::millis();
    // set target position
    _pos_control.set_pos_target_xy_cm(position.x, position.y);
}

/////////////////////////////////
void AC_Loiter::init_target()
{
    sanity_check_params();

    // initialise position controller speed and acceleration
    _pos_control.set_correction_speed_accel_xy(LOITER_VEL_CORRECTION_MAX, _accel_cmss);
    _pos_control.set_pos_error_max_xy_cm(LOITER_POS_CORRECTION_MAX);

    // initialise position controller and move target accelerations smoothly towards zero
    _pos_control.relax_velocity_controller_xy();

    // initialise predicted acceleration and angles from the position controller
    _predicted_accel.x = _pos_control.get_accel_target_cmss().x;
    _predicted_accel.y = _pos_control.get_accel_target_cmss().y;
    _predicted_euler_angle.x = radians(_pos_control.get_roll_cd()*0.01f);
    _predicted_euler_angle.y = radians(_pos_control.get_pitch_cd()*0.01f);
    _brake_accel = 0.0f;
    _brake_timer = AP_HAL::millis();
}

**Comment by xianglunkai** [comment]
@lixiaowei123 
You should accurately describe your problem, such as current phenomena, expected phenomena, possible problems, and possible measures

**Comment by lthall** [comment]
No response from feedback.
