### ISSUE TITLE
CAN2 - Failed to register CANSensor

### ISSUE THREAD

**Issue by Sekilsgs2** [ArduPilot/ardupilot#24402]
When using can2 for benewake protocol (or USD1) - gives a sensor registration error - 
```
26.07.2023 22:21:58 : Failed to register CANSensor Benewake
```

if using can1 - no problems
DroneCAN working good for can2 but rangefinders no. Im think this is related to canSensor module

Cuav X7 pro
Arducopter 4.3.5 or master
![image](https://github.com/ArduPilot/ardupilot/assets/5908468/5ef4cf3f-9c50-4fa4-b5bd-17f3da5b192b)

**Comment by xianglunkai** [comment]
@Sekilsgs2 
Perhaps you can connect a console to see the current working status or errors of all CANs

**Comment by xianglunkai** [comment]
Or view relevant records in the corresponding log

**Comment by xianglunkai** [comment]
One possible reason is that you may only have one CAN when building the system. You can use candump can1 to view the current status, if your system is Linux

**Comment by Sekilsgs2** [comment]
> @Sekilsgs2 Perhaps you can connect a console to see the current working status or errors of all CANs

DroneCAN working good for can2 but rangefinders with can protocol benewake or usd1 -not working.

**Comment by Sekilsgs2** [comment]
https://github.com/ArduPilot/ardupilot/issues/24415
