### ISSUE TITLE
AP-4.5.0-dev: dual CAN support broken

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#24415]
Latest (aka "master", aka "4.5.0-dev") cannot support two separate CAN interfaces when using DroneCAN (and perhaps other versions of CAN as well).

The issue can be replicated by connected a DroneCAN GPS to the CAN2 port of a CubeOrange (or probably any other autopilot) and then set:

- CAN_D1_PROTOCOL = 1 (DroneCAN)
- CAN_P1_DRIVER = 1 (First Driver)
- CAN_D2_PROTOCOL = 1 (DroneCAN)
- CAN_P2_DRIVER = 2 (Second Driver)

The GPS, compass and notify LEDs will not work.  Next set the parameter below so that there is only one CAN bus (with two ports)

- CAN_P2_DRIVER = 1 (First Driver)

.. and the GPS will start working.

If these tests are repeated on 4.4.0 (or earlier) the GPS works in both cases.

**Comment by xianglunkai** [comment]
@rmackay9 
I feel that this issue is somewhat related to the following issue:
https://github.com/ArduPilot/ardupilot/issues/24402

At the same time, I compared the version of rover4.3 with current master version in APCANManager and AP_ HAL.
The changes do not seem to have made significant changes, but for some details.
 I have made minor modifications that have delayed the current lack of hardware testing and cannot determine whether these modifications will help solve this problem.
https://github.com/ArduPilot/ardupilot/pull/24419

**Comment by Sekilsgs2** [comment]
> @rmackay9 I feel that this issue is somewhat related to the following issue: #24402
> 
> At the same time, I compared the version of rover4.3 with current master version in APCANManager and AP_ HAL. The changes do not seem to have made significant changes, but for some details. I have made minor modifications that have delayed the current lack of hardware testing and cannot determine whether these modifications will help solve this problem. #24419

Ok im test and reply.

**Comment by Sekilsgs2** [comment]
```
In file included from ../../libraries/AP_CANManager/AP_CANManager.h:26,
                 from ../../libraries/AP_CANManager/AP_CANDriver.cpp:19:
../../libraries/AP_CANManager/AP_CANDriver.cpp:36:98: error: cannot convert 'AP_CAN::Protocol' to 'const float' in initialization
   36 |     AP_GROUPINFO("PROTOCOL", 1, AP_CANManager::CANDriver_Params, _driver_type, AP_CAN::Protocol::DroneCAN),
      |                                                                                ~~~~~~~~~~~~~~~~~~^~~~~~~~
      |                                                                                                  |
      |                                                                                                  AP_CAN::Protocol
../../libraries/AP_Param/AP_Param.h:123:118: note: in definition of macro 'AP_GROUPINFO_FLAGS'
  123 | #define AP_GROUPINFO_FLAGS(name, idx, clazz, element, def, flags) { name, AP_VAROFFSET(clazz, element), {def_value : def}, flags, idx, AP_CLASSTYPE(clazz, element)}
      |                                                                                                                      ^~~
../../libraries/AP_CANManager/AP_CANDriver.cpp:36:5: note: in expansion of macro 'AP_GROUPINFO'
   36 |     AP_GROUPINFO("PROTOCOL", 1, AP_CANManager::CANDriver_Params, _driver_type, AP_CAN::Protocol::DroneCAN),
      |     ^~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

**Comment by xianglunkai** [comment]
@Sekilsgs2 
oh, that is my mistake! you could write :
AP_GROUPINFO("PROTOCOL", 1, AP_CANManager::CANDriver_Params, _driver_type, float(AP_CAN::Protocol::DroneCAN))

**Comment by xianglunkai** [comment]
@rmackay9 
By the way, it's clearly Int_ 8. Why do we need to use float for strong rotation?

**Comment by Sekilsgs2** [comment]
> @Sekilsgs2 oh, that is my mistake! you could write : AP_GROUPINFO("PROTOCOL", 1, AP_CANManager::CANDriver_Params, _driver_type, float(AP_CAN::Protocol::DroneCAN))

Ok. Now DroneCAN working if i'm using driver number 2 for can2 but benewake can sensor not working for can1 and can2 - silent - i'm add debug log to benewake can sensor driver and handle_frame never invoking...

**Comment by Sekilsgs2** [comment]
I'm sorry maybe my can hub was broken - need time.. maybe all working.. reply later

**Comment by Sekilsgs2** [comment]
YES ALL working NOW  - can1 - DroneCAN and can2 Benewake. 
THANKS

**Comment by xianglunkai** [comment]
@Sekilsgs2 
good!

**Comment by rmackay9** [comment]
OK, I'm going to close this issue now because I think the original issue I reported is resolved.  @xianglunkai and @Sekilsgs2 thanks for the additional testing!
