### ISSUE TITLE
IMU Data Loss in Copter 4.3.7 Stable (mRoControlZeroH7)

### ISSUE THREAD

**Issue by joshanne** [ArduPilot/ardupilot#24423]
## Bug report

**Issue details**

**Version**
Copter-4.3.7
Copter-4.4 beta3 (sha: 3c4abe469a47965eb76788d148a88045c0697344)

**Platform**
[?] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

Note: This seems likely to affect all platforms that do not contain the proposed fix commit.

**Hardware Configuration**
* mRoControlZeroH7 (Copter-4.3.7 - latest stable release)
* mRo SAM GPS + IST8308 Mag (Full Size) M10037 (See: https://store.mrobotics.io/product-p/m10037a.htm)

**Description**

We are experiencing data loss for the IMUs when the Flight Controller is configured with External GPS/Compass module. When the module is not present, there is no data loss in the IMUs.

We can replicate (and validate the proposed solution) with the following parameter set.

```
EK3_IMU_MASK  7
LOG_REPLAY 1
```

1. Enable `LOG_DISARMED`
2. Reboot
3. Generate ~1min log data
4. Disable `LOG_DISARMED`
5. Reboot
6. Download log and check with `graph sum(RISI[0].DADT,1) sum(RISI[1].DADT,2) sum(RISI[2].DADT,3) IMU[0].TimeUS/1E6`

Looking at the log, we observe a time slip in the recorded data.

![image](https://github.com/ArduPilot/ardupilot/assets/12959316/2fc1f223-8203-429d-aced-0c36f78c26e9)

**Solution**

It appears for this flight controller the I2C DMA is interfering with the IMUs, resulting in data loss.

Cherry-picking these upstream commits (on top of Copter-4.3.7) addresses the issue seen. https://github.com/ArduPilot/ardupilot/pull/23568/commits

With these changes, we can see all three IMUs are being read without data loss, and the accumulated time rises at the same gradient as elapsed time.

![image](https://github.com/ArduPilot/ardupilot/assets/12959316/071e4cef-abf7-4052-961d-ad5ac578667f)

Two log files are attached in this zip. They contain:
1. The issue present, on Copter-4.3.7 stable (_log-copter-4.3.7-issue-present.bin_)
2. The issue resolved, Copter-4.3.7 with cherry-picked commit (log-copter-4.3.7-fixed-with-cherrypick-commits)

[log-copter-4.3.7.zip](https://github.com/ArduPilot/ardupilot/files/12190867/log-copter-4.3.7.zip)

**Comment by joshanne** [comment]
@rmackay9 Just checked and this is appears to still be an issue in Copter 4.4 beta3 (latest available beta for Copter).

**Comment by andyp1per** [comment]
Can you try this change with 4.4? https://github.com/ArduPilot/ardupilot/pull/24454 - I think the problem is the DMA sharing

**Comment by tridge** [comment]
@andyp1per I think this alternative should be better:
https://github.com/ArduPilot/ardupilot/pull/24456

**Comment by joshanne** [comment]
Given this was picked up in Copter-4.4.0, happy to close this off.
