### ISSUE TITLE
Copter: Guided Mode MAV_CMDs should all be sendable from COMMAND_LONG

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#2446]
Almost all MAV_CMDs are processed in guided mode when sent inside a COMMAND_LONG (see MAVLINK_MSG_ID_COMMAND_LONG in [GCS_Mavlink.cpp](https://github.com/diydrones/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L967). 

There are a couple of exceptions, which makes the API a little inconsistent. Recommendation is that all MAV_CMDs be processed inside COMMAND_LONG. These are the "missing ones" I know about
- MAVLINK_MSG_ID_DIGICAM_CONFIGURE
- MAVLINK_MSG_ID_DIGICAM_CONTROL
- MAVLINK_MSG_ID_MOUNT_CONFIGURE
- MAVLINK_MSG_ID_MOUNT_CONTROL

@rmackay9 That is all the MAV_CMDs in the handler.

**Comment by OXINARF** [comment]
The mentioned "missing ones" aren't MAV_CMDs but independent messages and for that reason they can't be handled inside the COMMAND_LONG processing. That shouldn't stop them from being handled in Guided mode though, and looking at code they seem to be.

In any case those messages are deprecated and replaced with similar MAV_CMDs which are handled in the COMMAND_LONG section.
