### ISSUE TITLE
In SITL simulation Q_HOVER or Q_STABLIZED can not hold altitude?

### ISSUE THREAD

**Issue by yjy19999** [ArduPilot/ardupilot#24579]
## Bug report

I was attempted to simulate a quadplane in SITL environment. When the plane tooked off and fly to the desired place, I switched to Q_STABLIZED mode and found the altitude is decreasing slowly. The Q_HOVER mode behaved the same. I wonder if there is a bug in simulation lead to this phenomenon or my parameter setting lead to this problem

**Version**
I started from bacea2ec branch on 19 July 2023

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadplane with Quad Q_FRAME_CLASS

**Hardware type**
SpeedBee F405Wing

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by sdeal110** [comment]
You might need to set up a joystick with the sitl simulation. QHover and QStabilized modes rely on pilot input for the altitude and position commands so what I've found is the vtol flight modes don't work correctly in sitl unless there is a joystick acting as the rc control

**Comment by yjy19999** [comment]
Thanks for this advice. Maybe you are right. My elrs was malfunctional recently. This also pushed me to do some simulation only with the software. I will simulate it again once I get my joystick. You can close this issue now and if the problem remains. I will open a new one.



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 17, 2023 22:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ArduPilot/ardupilot] In SITL simulation Q_HOVER or Q_STABLIZEDcan not hold altitude? (Issue #24579)




 
You might need to set up a joystick with the sitl simulation. QHover and QStabilized modes rely on pilot input for the altitude and position commands so what I've found is the vtol flight modes don't work correctly in sitl unless there is a joystick acting as the rc control

**Comment by yjy19999** [comment]
sdeal110 solved this issue perfectly and thanks again for he/she.
