### ISSUE TITLE
rover-quicktune: abnormal crash

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#24689]
During the simulation test, there was a sudden setting crash. As I am unfamiliar with Lua, I will report this issue first。
<img width="227" alt="图片1" src="https://github.com/ArduPilot/ardupilot/assets/48796694/97eebd2a-ac08-41a4-8a60-32d32e2cc1a5">
<img width="316" alt="图片2" src="https://github.com/ArduPilot/ardupilot/assets/48796694/6b0a770c-bd12-44ff-b3b2-5c9abc51d307">

**Comment by rmackay9** [comment]
Hi @xianglunkai,

This looks like line [510 failed](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/applets/rover-quicktune.lua#L510C111-L510C124) which makes me think that the version of the software used doesn't have the latest bindings.  Can you check that you used Rover-4.4.0-beta or a recent version of latest?

I think this is really a support issue and it should be reported first [here in the forums](https://discuss.ardupilot.org/t/rover-boat-quiktune-alpha-testers-wanted/101989/75).

Sorry, I'm going to go ahead and close this until we confirm it is a real issue.  I will still see replies posted here.
