### ISSUE TITLE
EKF3 IMU0  in-flight yaw alignment complete

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#24823]
Can I turn off this feature

**Comment by IamPete1** [comment]
no

**Comment by rmackay9** [comment]
It is possible to turn off the realignment that happens soon after takeoff though using the EK3_MAG_CAL parameter. https://ardupilot.org/copter/docs/parameters.html#ek3-mag-cal-magnetometer-default-fusion-mode

This is really a support question so I'll go ahead and close this issue.
