### ISSUE TITLE
narrowing conversion of 'fmax

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#24865]
![1693791706656](https://github.com/ArduPilot/ardupilot/assets/16605202/738b45fc-93bb-4257-bedc-5c6f167b3214)

copter-4.3.8 build fmuv5/CUAV-X7. Compiling firmware shows an issue

/AP_Math/ftype.h:24:24: error: narrowing conversion of 'fmax(fmax(((double)magVar.Vector3<float>::x), ((double)magVar.Vector3<float>::y)), ((double)magVar.Vector3<float>::z))' from 'double' to 'float' inside { } [-Werror=narrowing]
 #define fmaxF(x,y) fmax(x,y)
                        ^
../../libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp:620:9: note: in expansion of macro 'fmaxF'
         fmaxF(fmaxF(magVar.x,magVar.y),magVar.z),

**Comment by IamPete1** [comment]
What is the output of your configure step?

**Comment by peterbarker** [comment]
I think this looks like a valid warning; the `mavlink_ekf_status_report_t` we are assembling really only has room for a float but we're trying to shove a double in there (`fmaxF` sometimes doing that....).

We should not be using `fmaxF` there - the type is clearly float IMO.  https://github.com/ArduPilot/ardupilot/pull/24918

I am *really* interested in the output of that configure step which @IamPete1 requested!

**Comment by lixiaowei123** [comment]
thank you,Gcc version issue

**Comment by IamPete1** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/24918
