### ISSUE TITLE
Enhancement: separate controls for 2nd gimbal

### ISSUE THREAD

**Issue by srobi** [ArduPilot/ardupilot#2488]
RCx parameters offer mount2 pan/tilt/roll control but control input channel and stabilize axis setting dependent on the setting of mount1 and cannot be set independently.

**Comment by amilcarlucas** [comment]
I think this has now been fully implemented. Can you test ArduCopter 4.4.0 ?

**Comment by rmackay9** [comment]
Yes, this is definitely done so let's close this one.
