### ISSUE TITLE
copter compile bootloader BUG

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#24903]
![1694076208438](https://github.com/ArduPilot/ardupilot/assets/16605202/3dd19d16-9a0f-4cae-ac79-0e4db8dac86d)

./Tools/scripts/build_bootloaders.py fmuv5

**Comment by peterbarker** [comment]
> ![1694076208438](https://user-images.githubusercontent.com/16605202/266259512-3dd19d16-9a0f-4cae-ac79-0e4db8dac86d.png)
> 
> ./Tools/scripts/build_bootloaders.py fmuv5

Define a ZGPIO.  Any GPIO.

**Comment by lthall** [comment]
No reply to question.
