### ISSUE TITLE
Copter firmware MatekF405-TE-bdshot on FC "Matek F405-miniTE" does not initialize Dshot on Servo3

### ISSUE THREAD

**Issue by dejero13** [ArduPilot/ardupilot#24931]
## Bug report

**Issue details**
I wanted to use four motors on the copter with BDshot, but the firmware MatekF405-TE-bdshot on FC "Matek F405-miniTE" does not initialize Dshot on Servo3 (regardless of servo_blh _bdmask), there are no problems with Servo1,2,4. With firmware MatekF405-TE all Servo1,2,3,4 work, but there is no BDshot. I also checked the FC on the Betaflight firmware, where all 4 motors work with BDshot.
I attach a screenshot of the MissionPlanner messages and a param file.

**Version**
MatekF405-TE-bdshot 4.4.0

**Platform**
[  ] All
[  ] AntennaTracker
[+] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
Matek F405-miniTE

**Attach**
![2023-09-09_19-29-47 (2)](https://github.com/ArduPilot/ardupilot/assets/57988069/69e672e2-2534-49c1-849d-252b9e52f391)

[MatekF405-TE-bdshot_4.4.0.param.zip](https://github.com/ArduPilot/ardupilot/files/12566460/MatekF405-TE-bdshot_4.4.0.param.zip)

**Comment by dejero13** [comment]
On the Mateksys website there is a note to this FC with a similar solved problem for Inav:
"INAV firmware, S3, S5,S7 DSHOT not working because of DMA clash,  pls use ONESHOT or MULTISHOT and calibrate ESC PWM range.
This DMA clash will be fixed from INAV 7.x.x."

[FLIGHT CONTROLLER F405-MINITE](http://www.mateksys.com/?portfolio=f405-minite)

**Comment by dejero13** [comment]
Perhaps this Inav topic has just solved the current problem.
[Timer N channel fix](https://github.com/iNavFlight/inav/pull/9276)

**Comment by andyp1per** [comment]
This is by design - PWM3 uses a timer that makes bdshot not possible - you should use another channel for a motor
