### ISSUE TITLE
ICM42688 "stuck" gyro values

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#25025]
This is to track an issue seen on 3 vehicles where the ICM42688 can get "stuck" gyro data.
First seen on a CubeOrangePlus copter first IMU Y axis in this log:
![image](https://github.com/ArduPilot/ardupilot/assets/831867/a5f2c068-2891-4a99-a511-8a65243041f8)
next seen on an OctoQuad copter, also with CubeOrangePlus, this time on X axis:
![image](https://github.com/ArduPilot/ardupilot/assets/831867/aa9507ca-4e1a-4f98-9a81-174e2597d16e)
this was with raw logging, and the raw values show the repeated data is bitwise identical:
![image](https://github.com/ArduPilot/ardupilot/assets/831867/cd2f6bd9-9476-4297-9eb1-170d87609807)
next seen on a MatekH743-bdshot first IMU (also an ICM42688), with batch logging. After unwinding the batch logging we see:
![image](https://github.com/ArduPilot/ardupilot/assets/831867/d300e774-504d-4892-ad3c-66639c354f21)
![image](https://github.com/ArduPilot/ardupilot/assets/831867/e0646fb7-707f-4831-9efb-1354e4dce6e7)

update: now reproduced in bench testing by waving the board by hand. Added logging of gyro at 8kHz here:
https://github.com/tridge/ardupilot/tree/ICM42688-test
analyse with: https://github.com/ArduPilot/pymavlink/blob/master/examples/dup_samples.py
![image](https://github.com/ArduPilot/ardupilot/assets/831867/5a9b394f-6390-49da-8af2-9f620e6dff85)
![image](https://github.com/ArduPilot/ardupilot/assets/831867/0e39431c-2f8e-419b-af11-dd70201b9f7f)
![image](https://github.com/ArduPilot/ardupilot/assets/831867/ad35b692-3bb1-4d94-a13a-43d5663264ad)
![image](https://github.com/ArduPilot/ardupilot/assets/831867/4edcbdfc-593e-49b4-aed7-b7d4cfb443b5)

**Comment by tridge** [comment]
changed ODR to 32kHz and see 45 identical samples in a row:
![image](https://github.com/ArduPilot/ardupilot/assets/831867/1e53ae98-8432-40bd-a222-b7bd3e6b4fd1)

**Comment by tridge** [comment]
the timestamp in the FIFO packet doesn't do anything strange when we get the stuck values:
![image](https://github.com/ArduPilot/ardupilot/assets/831867/aa65a16d-8452-4b67-8691-f7eaa8191464)
but it is interesting that at 8kHz we don't get 125 difference in timestamp values:
![image](https://github.com/ArduPilot/ardupilot/assets/831867/28f7f054-e1ae-49b0-8528-677ccfda2960)

**Comment by vgade-invn** [comment]
The problem is most likely caused by AFSR mode of the sensor. 

AFSR is a sensor setting used to fine-tune the device for lower noise density at lower measurement ranges, while still providing the full sensor range. At around 100 dps, you can observe the sensor switching from low-range (low noise) to high-range (higher noise) mode. When you disable the AFSR, the device will always be in high-range mode, with a slight reduction in noise density at FSR < 100 dps.

To disable AFSR, set bit [7:6] = 01 at the address of 77 at bank 0 register. The default bit [7:6] = 10 which enables AFSR.

Thanks,
Vishal Gade,
TDK Invensense.

**Comment by tridge** [comment]
@vgade-invn many thanks!
does this only apply to the ICM42688 or does this affect some other parts as well?

**Comment by vgade-invn** [comment]
This applies to all ICM-42xxx and IIM-42xxx parts.

Thanks,
Vishal.

**Comment by tridge** [comment]
> This applies to all ICM-42xxx and IIM-42xxx parts.

@vgade-invn we have not seen the issue on other than the ICM42688. Could it be that this setting applies to all the IxM-42xxx, but the actual "stuck" data issue is ICM42688 specific?
