### ISSUE TITLE
ArduCopter 4.4 list non-exist SPI compass

### ISSUE THREAD

**Issue by mw66** [ArduPilot/ardupilot#25041]
## Bug report

**Issue details**

https://discuss.ardupilot.org/t/copter-4-4-cannot-find-compass-3-while-3-6-12-has-no-problem/106423

Basically, ArduCopter 4.4 list non-exist SPI compass.
it says cannot find compass 3 (SPI, LSM303D):

Please see the comparison between 4.4 and 3.6.12 screenshot on the above page.

**Version**
ArduCopter 4.4

**Platform**
[X ] Copter

**Hardware type**

Pixhawk 2.4.8 

https://discuss.ardupilot.org/t/copter-4-4-cannot-find-compass-3-while-3-6-12-has-no-problem/106423

**Comment by mw66** [comment]
I know, but is this a software bug? why that chip (SPI, LSM303D) is listed at all?

**Comment by amilcarlucas** [comment]
Probably a bug in 3.6 that no longer is present in 4.4.

**Comment by rmackay9** [comment]
Hi @mw66,

We keep the older compasses around in the list so that if they re-appear the user doesn't have to re-do the calibration.  On the MP screen there is also a button to remove the old ones in case they're getting in the way for some reason.
