### ISSUE TITLE
ekf3 attitude bad （Abnormal high-frequency oscillation attitude settlement in ekf3）

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#25063]
Without using GPS and compass, quickly and forcefully smash the flight control onto the table, then quickly flatten the flight control, causing the flight control posture to diverge

**Comment by amilcarlucas** [comment]
AFAIK that is normal behavior if you do not have a compass

**Comment by lixiaowei123** [comment]
@amilcarlucas Without a compass, roll and pitch should not be affected

**Comment by lthall** [comment]
This is expected behaviour.
