### ISSUE TITLE
AP:: micros() should be used with caution

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#25132]
Due to the fact that the maximum storage time of uint32 is only about one hour, this is not suitable for certain timescale timing and calculation time differences.

I suggest that micros use uint64 storage uniformly！

**Comment by rmackay9** [comment]
Hi @xianglunkai,

Thanks for the advice.  Are there any particular lines of concern in AP?  I'm just wondering what we should do with this issue.  It's good advice but normally we reserve the issues list for enhancements requests and bug reports.

I might go ahead and close this but we can re-open if there are particular lines of concerns.
