### ISSUE TITLE
ArduPilot should test for valid input on takeoff

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#2515]
ArduPilot does not check for NaN or Inf (infinity) values for the takeoff parameter command, and could potentially fly to a random location if such input was received (according to @billbonney ). Testing using dronekit shows that float("nan") is denied by arducopter but float("inf")) crashes arducopter or SITL.

Dronekit now checks against the invalid input (i.e. programmatic errors https://github.com/diydrones/dronekit-python/issues/174) and we think ArduCopter probably should too.

Further, we think that it might be useful to have a parameter defining a reasonable maximum value if the Geofence altitude is not set.

**Comment by magicrub** [comment]
This is a problem for all vehicles, basically we need to sanity check the float inputs better.
