### ISSUE TITLE
@sharable parameters

### ISSUE THREAD

**Issue by davidbuzz** [ArduPilot/ardupilot#252]
if user/s download a bixler.param, or flamewheel.param and naively expect it to "just work" they'll be in trouble.  ( as it will messup the radio calibrations and compass offsets, etc )   we need the ability to save a standard subset of non-user-specific sharable/tunable parameters that will make it easy to share the relevant parameters .....

**Comment by R-Lefebvre** [comment]
Is the Copter side of this as simple as going into the relevant parameter instances and adding a:

// @Shareable

to any appropriate params?  If so, I can probably undertake that for copter.

**Comment by geeksville** [comment]
yep - but we should get GCSes to look for this tag.

**Comment by R-Lefebvre** [comment]
Ok, so I can undertake thing one.  At least on the Copter side.

**Comment by OXINARF** [comment]
We now have Volatile and ReadOnly (although most likely not all parameters that should have them are marked), I think that covers what was proposed in this issue.

I believe that marking parameters correctly is always an on-going task and PRs are welcome to improve our documentation.

For these reasons I'm closing this. If you feel that's wrong please comment here.
