### ISSUE TITLE
BMI088

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#25246]
![1697112923584](https://github.com/ArduPilot/ardupilot/assets/16605202/8fce3691-436b-48b4-abe7-ae51e8d34747)

![2ab1af75463a1bf8c8e872f6144ba39](https://github.com/ArduPilot/ardupilot/assets/16605202/b2a46a7e-59db-4b2f-afd5-8ab1318fbde6)
Why is it necessary to modify this here

**Comment by lthall** [comment]
This is not a support forum.
