### ISSUE TITLE
Using heading decomposition attitude angle about loiter control

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#25266]
![1697336250012](https://github.com/ArduPilot/ardupilot/assets/16605202/264aa5a2-feab-449b-98f2-0e61b4099993)
![1697336299714](https://github.com/ArduPilot/ardupilot/assets/16605202/8383603a-d9b6-42a6-bf5c-4acdba919e5a)
this should probably be based on the desired heading not the current heading,but I did use the actual heading recorded in the log, so there is a problem with position control

**Comment by lthall** [comment]
I put that note in there to remind me to come back and examine this decision.

Using desired heading results in a lower noise target attitude command. However, it also means that loss of yaw control will mean loss of position control.

My initial thought is that we are probably better off using current heading and accepting the noisier attitude target so that we maintain position control when we have lost yaw control.

So the fix in this case would be to remove the comment.

**Comment by lixiaowei123** [comment]
> I put that note in there to remind me to come back and examine this decision.
> 
> Using desired heading results in a lower noise target attitude command. However, it also means that loss of yaw control will mean loss of position control.
> 
> My initial thought is that we are probably better off using current heading and accepting the noisier attitude target so that we maintain position control when we have lost yaw control.
> 
> So the fix in this case would be to remove the comment.

When the actual heading is lost, the actual heading will be 0. Then, directly determine whether it is possible to modify the target heading to 0 when the heading is lost

**Comment by lthall** [comment]
>> When the actual heading is lost, the actual heading will be 0. Then, directly determine whether it is possible to modify the target heading to 0 when the heading is lost

Sorry but I don't understand what you are saying. If we loose our actual heading we can't navigate at all. If we loose heading control we can navigate.

I don't see any situation where we can benefit from setting the heading to zero.

**Comment by lixiaowei123** [comment]
@lthall Why not use the target heading，

**Comment by lixiaowei123** [comment]
px4 use target heading

**Comment by lixiaowei123** [comment]
PX4 target heading

**Comment by lthall** [comment]
I explained that:

> Using desired heading (target heading) results in a lower noise target attitude command. However, it also means that loss of yaw control will mean loss of position control. My initial thought is that we are probably better off using current heading and accepting the noisier attitude target so that we maintain position control when we have lost yaw control.

> px4 use target heading

I aspire to much higher performance than PX4 is capable of. This is just one more list thing on the list of things they do wrong.

I am closing this as I can see this is not going anywhere.

**Comment by lixiaowei123** [comment]
Thank you ,Looking forward to you making better loiter brakes, similar to DJI

**Comment by lthall** [comment]
I suspect your loiter breaking issues is a result of poor tuning and setup and nothing to do with the code. However, this isn't a support forum. You would get better results and waist less time by posting questions on the support forums.
