### ISSUE TITLE
uav level calibration causes locking on the ground and nav issue

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#25279]
I deliberately raised the front of the plane a bit, with an error of about 6deg, and then I clicked on the horizontal calibration. Locking on the ground will be abnormal

**Comment by lthall** [comment]
Please stop spamming the issues.

**Comment by lixiaowei123** [comment]
You don't understand my thoughts at all

**Comment by lthall** [comment]
Then put more effort into expressing your thoughts.

**Comment by lixiaowei123** [comment]
Can you tilt and level the plane to see if it can be locked when landing

**Comment by lixiaowei123** [comment]
Can you tilt the plane and click on the horizontal calibration to see if it can be locked when landing

**Comment by lixiaowei123** [comment]
You raise the plane a little bit and then click on the horizontal calibration. After calibration is completed, place it on a horizontal plane and you will notice that there may be issues with the fused acceleration
![d2691f1cc5c3e97f6de06f857c809eb](https://github.com/ArduPilot/ardupilot/assets/16605202/94878324-fde8-45e4-b9b5-15301626d14e)
![2bb764839913659dc26e5f6fd1466a7](https://github.com/ArduPilot/ardupilot/assets/16605202/0dc8697f-ab03-480c-8ab4-da74034b5d06)
I hope you don't just close the issues submitted by others, you don't even know the bugs that exist

**Comment by lixiaowei123** [comment]
Some developers may be too idealistic and lack practical experience. Don't just think you're amazing, but you're actually average

**Comment by lthall** [comment]
>> Some developers may be too idealistic and lack practical experience. Don't just think you're amazing, but you're actually average

You may need to be a little more self aware mate.

**Comment by rmackay9** [comment]
I'm going to close this discussion 'cuz it looks like it's tending towards getting personal which is where things start going badly.,
