### ISSUE TITLE
Copter: Arming check doesn't check RC failsafe if armed from GCS

### ISSUE THREAD

**Issue by squilter** [ArduPilot/ardupilot#2529]
This issue was first identified at DroidPlanner/DroneKit-Android#151.  I was able to reproduce it using AC3.3rc7, `ARMING_CHECK`=1

Turn off the RC, or disconnect the receiver from the pixhawk.
The GCS will report "RC Failsafe".
Sending the arming packet will still allow it to arm.

**Comment by R-Lefebvre** [comment]
I'm not sure this is undesired.  We do attempt to support flight without a traditional RCTx.

**Comment by squilter** [comment]
@R-Lefebvre My understanding was that this is the desired behaviour when `ARMING_CHECK`= -65 (Skip RC)

**Comment by Pedals2Paddles** [comment]
Closing due no longer an issue. Copter will not arm by GCS (or anything else) if in RC Failsafe without disabling the arming check bit.
