### ISSUE TITLE
EKF_Buffer: there is a bug in ekf_imu_buffer::push_youngest_element(const void *element)

### ISSUE THREAD

**Issue by luweiagi** [ArduPilot/ardupilot#25316]
Hi, in ekf_imu_buffer::push_youngest_element(const void *element):
https://github.com/ArduPilot/ardupilot/blob/5b34a9bf1370186c1aafe7f9f35dc77235401a9f/libraries/AP_NavEKF/EKF_Buffer.cpp#L159
```
void ekf_imu_buffer::push_youngest_element(const void *element)
{
    if (!buffer) {
        INTERNAL_ERROR(AP_InternalError::error_t::flow_of_control);
        return;
    }
    // push youngest to the buffer
    _youngest = (_youngest+1) % _size;
    memcpy(get_offset(_youngest), element, elsize);
    // set oldest data index
    _oldest = (_youngest+1) % _size;
    if (_oldest == 0) {                    // <=============BUG!!!
        _filled = true;
    }
}
```
, I think 
```
    if (_oldest == 0) {
        _filled = true;
    }
```
should be modified as:
```
    if (_oldest == 1 || _size == 1) {
        _filled = true;
    }
```

Why?

because when push, the first element is pushed into pos 1 NOT pos 2:
```
_youngest = (_youngest+1) % _size;  // here _youngest is initialized as 0, so the first elem pos is 1 not 0
```

so when _oldest is 0, there is N-1 elem not N elem in buffer:
` _oldest = (_youngest+1) % _size;` 
In fact, the buffer is not full.

I use a pic to describe this bug:
![image](https://github.com/ArduPilot/ardupilot/assets/19629731/65b54a3a-bd66-48a0-b801-9f6dccb9263b)

**Comment by amilcarlucas** [comment]
Even better than a bug report is a pull request. Can you make one?

**Comment by luweiagi** [comment]
> Even better than a bug report is a pull request. Can you make one?

OK, I have make a PR:
fix imu_buffer _filled=true logic in EKF_Buffer.cpp #25323
https://github.com/ArduPilot/ardupilot/pull/25323

**Comment by peterbarker** [comment]
Thanks @luweiagi , real bug and I merged a slightly different fix + regression tests as part of the other PR.

**Comment by luweiagi** [comment]
@peterbarker @rmackay9 Hi, I think the following fix is more correct:
