### ISSUE TITLE
EKF3 Accel  delVel bias bug

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#25435]
[log.zip](https://github.com/ArduPilot/ardupilot/files/13226334/log.zip)

I have optimized the acceleration offset bug handled on the latest official website using Copter-4.0.7, but the following issues still occur
![1698837696327](https://github.com/ArduPilot/ardupilot/assets/16605202/f52aabe0-e23d-47f4-907d-393301afe2c8)

![1698837826597](https://github.com/ArduPilot/ardupilot/assets/16605202/0022c36c-a824-4ed5-8d69-cda8b31191ee)

**Comment by IamPete1** [comment]
Can you proved more detail and re-test on Copter 4.4.

**Comment by lixiaowei123** [comment]
> Can you proved more detail and re-test on Copter 4.4.

This kind of problem doesn't happen every time, it's not like the latest version appears，There must have been a problem with the code, regardless of which version,

**Comment by lixiaowei123** [comment]
> > Can you proved more detail and re-test on Copter 4.4.
> 
> This kind of problem doesn't happen every time, it's not like the latest version appears，There must have been a problem with the code, regardless of which version,

@priseborough

**Comment by IamPete1** [comment]
Sorry, I still don't understand the issue your trying to report. 

Under what circumstances does it happen?
What happens?
What do you expect to happen?
What tests have you done to narrow it down?
Does it happen on more than one flight controller?
Does it happen in the simulator?

Your plots seem to be comparing accelerations and velocities from the EKF? What are they showing?

**Comment by lixiaowei123** [comment]
> Sorry, I still don't understand the issue your trying to report.
> 
> Under what circumstances does it happen? What happens? What do you expect to happen? What tests have you done to narrow it down? Does it happen on more than one flight controller? Does it happen in the simulator?
> 
> Your plots seem to be comparing accelerations and velocities from the EKF? What are they showing?

I have been working normally in the morning, but I just unlocked it in the afternoon and there was a surge。What I want to express is that there is a bug in the calculation of acceleration velocity increment deviation

**Comment by lixiaowei123** [comment]
![1698894613577](https://github.com/ArduPilot/ardupilot/assets/16605202/3d6415dc-ef3f-4a03-8f74-c2bbd596b9cf)
![1698894652347](https://github.com/ArduPilot/ardupilot/assets/16605202/934e46a3-aa8c-4892-8e5c-941e5e2424d2)

**Comment by lixiaowei123** [comment]
In either case, the vertical acceleration in the geographic coordinate system should be -9.8. You can see in the log that the acceleration anomaly in the geographic coordinate system is caused by the offset of the acceleration velocity increment

**Comment by lthall** [comment]
> I have optimized the acceleration offset bug handled on the latest official website using Copter-4.0.7, but the following issues still occur

> This kind of problem doesn't happen every time, it's not like the latest version appears，

It appears you are using your own custom version of the code and are not able to reproduce on master or 4.4. If you are able to produce logs and demonstrate the problem on 4.4 or master we can reopen the issue.

**Comment by lixiaowei123** [comment]
Is it necessary to go to the latest testing for every version with problems? What is the logic behind this

**Comment by lthall** [comment]
There is no point trying to fix a problem that we have already fixed or doesn't exist in the latest version of the code. This issue list isn't for your custom version of the code or for old versions of the code.

**Comment by lixiaowei123** [comment]
I have reviewed the latest bug fix and it does not fundamentally solve this problem

**Comment by lixiaowei123** [comment]
![1699003540114](https://github.com/ArduPilot/ardupilot/assets/16605202/0062cd6b-cfa3-4f3b-b558-f347eb7644fb)
![1699003583557](https://github.com/ArduPilot/ardupilot/assets/16605202/393cae61-3c46-48fb-873c-507c0cce7bc7)
![1699003625033](https://github.com/ArduPilot/ardupilot/assets/16605202/080ce883-c2b9-4eff-83ae-918b9cb5d305)

I have fixed all these issues and verified multiple times. My version is already the same as here, and the latest version on the official website has not resolved this issue

**Comment by lixiaowei123** [comment]
I only have a set of IMUs, and there won't be the bug above

**Comment by lthall** [comment]
If you can clearly articulate the problem and show provide a replay log using 4.4 or master we can re-open the issue.
