### ISSUE TITLE
Add signal_quality to RangeFinder_State

### ISSUE THREAD

**Issue by clydemcqueen** [ArduPilot/ardupilot#25528]
## Feature request

**Is your feature request related to a problem? Please describe.**

Background: several rangefinder backends support signal quality (BLPing, LightWareSerial, MAVLink). For these backends the distance and signal quality are stored separately: distance is copied from the backend to the frontend by `update()` but signal quality remains in the backend and is accessed by `get_signal_quality_pct(...)`.

The problem: the backend API doesn't support a way to get the (distance, signal quality) tuple. Callers can get the distance from the frontend and the signal quality from the backend, but they might be out of sync. This is OK for most use cases, but it is hard to reason about and it makes testing tricky.

**Describe the solution you'd like**

Add a field `signal_quality` to `RangeFinder_State`.

**Describe alternatives you've considered**

Add a method `AP_RangeFinder_Backend::get_measurement(uint16_t &distance_cm, int8_t &quality_pct)`.

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

Signal quality is very important for sub use cases.

This came up while working on a Lua rangefinder simulator that supports signal quality: the idea is to simulate sensor delay, different seafloor types, etc. Writing a nice autotest for this is tricky.

**Comment by Williangalvani** [comment]
done in #25550
