### ISSUE TITLE
Error in DroneCAN module while building

### ISSUE THREAD

**Issue by vhytyk** [ArduPilot/ardupilot#25681]
## Bug report

**Issue details**

Trying to build SITL on Windows WSL1 (Ubuntu):

1. git clone --recurse-submodules https://github.com/ArduPilot/ardupilot.git
2. cd ardupilot
3. ./waf configure --board sitl
4. ./waf copter

And it fails processing module DroneCAN (logs below)

**Version**
latest

**Platform**
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
flying

**Hardware type**
sitl

**Logs**
~/ardupilot$ python3 waf copter
Waf: Entering directory `/home/vic/ardupilot/build/sitl'
Embedding file locations.txt:Tools/autotest/locations.txt
Embedding file models/Callisto.json:Tools/autotest/models/Callisto.json
Embedding file models/plane-3d.parm:Tools/autotest/models/plane-3d.parm
Embedding file models/plane.parm:Tools/autotest/models/plane.parm
Embedding file models/xplane_heli.json:Tools/autotest/models/xplane_heli.json
Embedding file models/xplane_plane.json:Tools/autotest/models/xplane_plane.json
[5/7] Processing dronecangen: modules/DroneCAN/DSDL/.github modules/DroneCAN/DSDL/ardupilot modules/DroneCAN/DSDL/com modules/DroneCAN/DSDL/cuav modules/DroneCAN/DSDL/dronecan modules/DroneCAN/DSDL/mppt modules/DroneCAN/DSDL/tests modules/DroneCAN/DSDL/uavcan
expanding ardupilot.equipment.trafficmonitor.TrafficReport
expanding com.hobbywing.esc.SetThrottleSource
expanding com.xacti.GnssStatusReq
expanding dronecan.protocol.Stats
expanding dronecan.remoteid.SecureCommand
expanding uavcan.equipment.actuator.ArrayCommand
expanding uavcan.equipment.air_data.IndicatedAirspeed
expanding uavcan.equipment.air_data.StaticPressure
expanding uavcan.equipment.camera_gimbal.Status
expanding uavcan.equipment.gnss.Fix2
expanding uavcan.equipment.power.PrimaryPowerSupplyStatus
expanding uavcan.navigation.GlobalNavigationSolution
expanding uavcan.protocol.Panic
expanding uavcan.protocol.AccessCommandShell
expanding uavcan.protocol.debug.LogLevel
expanding uavcan.protocol.dynamic_node_id.server.Discovery
expanding uavcan.protocol.enumeration.Indication
expanding uavcan.protocol.file.Write
expanding uavcan.protocol.param.NumericValue
expanding uavcan.tunnel.SerialConfig
expanding ardupilot.equipment.proximity_sensor.Proximity
expanding ardupilot.indication.Button
expanding com.himark.servo.ServoCmd
expanding com.hobbywing.esc.StatusMsg1
expanding com.hobbywing.esc.SetDirection
expanding com.hobbywing.esc.GetMajorConfig
expanding com.xacti.GimbalControlData
expanding dronecan.remoteid.BasicID
expanding dronecan.remoteid.System
expanding uavcan.CoarseOrientation
expanding uavcan.equipment.ahrs.MagneticFieldStrength
expanding uavcan.equipment.air_data.AngleOfAttack
expanding uavcan.equipment.air_data.StaticTemperature
expanding uavcan.equipment.device.Temperature
expanding uavcan.equipment.esc.Status
expanding uavcan.equipment.hardpoint.Command
expanding uavcan.equipment.ice.FuelTankStatus
expanding uavcan.equipment.indication.LightsCommand
expanding uavcan.equipment.power.BatteryInfo
expanding uavcan.protocol.NodeStatus
expanding uavcan.protocol.RestartNode
expanding uavcan.protocol.DataTypeKind
expanding uavcan.protocol.debug.KeyValue
expanding uavcan.protocol.dynamic_node_id.server.AppendEntries
expanding uavcan.protocol.file.Delete
expanding uavcan.protocol.file.Error
expanding uavcan.protocol.param.ExecuteOpcode
expanding ardupilot.equipment.power.BatteryPeriodic
expanding com.xacti.GnssStatus
expanding cuav.equipment.power.CBAT
expanding uavcan.equipment.actuator.Status
expanding uavcan.equipment.ahrs.RawIMU
expanding uavcan.equipment.camera_gimbal.Mode
expanding uavcan.equipment.indication.BeepCommand
expanding uavcan.equipment.indication.RGB565
expanding uavcan.equipment.power.CircuitStatus
expanding uavcan.equipment.safety.ArmingStatus
expanding uavcan.protocol.GetNodeInfo
expanding uavcan.protocol.SoftwareVersion
expanding uavcan.protocol.dynamic_node_id.server.RequestVote
expanding uavcan.protocol.file.BeginFirmwareUpdate
expanding uavcan.protocol.file.Read
expanding uavcan.protocol.param.Empty
expanding uavcan.tunnel.Broadcast
expanding uavcan.tunnel.Call
expanding ardupilot.equipment.power.BatteryCells
expanding ardupilot.gnss.Heading
expanding ardupilot.gnss.RelPosHeading
expanding com.himark.servo.ServoInfo
expanding com.hobbywing.esc.RawCommand
expanding com.hobbywing.esc.SetLED
expanding com.hobbywing.esc.SetAngle
expanding com.xacti.CopterAttStatus
expanding dronecan.remoteid.Location
expanding mppt.Stream
expanding uavcan.equipment.ahrs.MagneticFieldStrength2
expanding uavcan.equipment.air_data.Sideslip
expanding uavcan.equipment.camera_gimbal.AngularCommand
expanding uavcan.equipment.esc.RPMCommand
expanding uavcan.equipment.gnss.RTCMStream
expanding uavcan.equipment.gnss.ECEFPositionVelocity
expanding uavcan.equipment.ice.reciprocating.Status
expanding uavcan.protocol.GetDataTypeInfo
expanding uavcan.protocol.GlobalTimeSync
expanding uavcan.protocol.CANIfaceStats
expanding uavcan.protocol.debug.LogMessage
expanding uavcan.protocol.dynamic_node_id.server.Entry
expanding uavcan.protocol.file.GetInfo
expanding uavcan.protocol.file.EntryType
expanding uavcan.protocol.file.Path
expanding uavcan.protocol.param.Value
expanding uavcan.tunnel.Targetted
expanding ardupilot.equipment.power.BatteryInfoAux
expanding ardupilot.gnss.Status
expanding ardupilot.indication.SafetyState
expanding com.hex.equipment.flow.Measurement
expanding com.hobbywing.esc.StatusMsg2
expanding com.hobbywing.esc.SetID
expanding com.hobbywing.esc.SetReportingFrequency
expanding com.hobbywing.esc.GetMaintenanceInformation
expanding com.xacti.GimbalAttitudeStatus
expanding dronecan.protocol.CanStats
expanding dronecan.remoteid.ArmStatus
expanding dronecan.sensors.rc.RCInput
expanding uavcan.Timestamp
expanding uavcan.equipment.actuator.Command
expanding uavcan.equipment.air_data.TrueAirspeed
expanding uavcan.equipment.air_data.RawAirData
expanding uavcan.equipment.esc.RawCommand
expanding uavcan.equipment.gnss.Auxiliary
expanding uavcan.equipment.hardpoint.Status
expanding uavcan.equipment.ice.reciprocating.CylinderStatus
expanding uavcan.equipment.indication.SingleLightCommand
expanding uavcan.equipment.range_sensor.Measurement
expanding uavcan.protocol.GetTransportStats
expanding uavcan.protocol.HardwareVersion
expanding uavcan.protocol.dynamic_node_id.Allocation
expanding uavcan.protocol.enumeration.Begin
expanding uavcan.protocol.file.GetDirectoryEntryInfo
expanding uavcan.protocol.param.GetSet
expanding ardupilot.equipment.power.BatteryContinuous
expanding ardupilot.gnss.MovingBaselineData
expanding ardupilot.indication.NotifyState
expanding com.hobbywing.esc.GetEscID
expanding com.hobbywing.esc.StatusMsg3
expanding com.hobbywing.esc.SetBaud
expanding com.hobbywing.esc.SelfTest
expanding com.volz.servo.ActuatorStatus
expanding dronecan.remoteid.SelfID
expanding dronecan.remoteid.OperatorID
expanding dronecan.sensors.hygrometer.Hygrometer
expanding mppt.OutputEnable
expanding uavcan.equipment.ahrs.Solution
expanding uavcan.equipment.camera_gimbal.GEOPOICommand
expanding uavcan.equipment.gnss.Fix
expanding uavcan.tunnel.Protocol
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'
Caught exception! 'dict' object has no attribute 'unknownScriptName'

Traceback (most recent call last):
  File "/home/vic/ardupilot/modules/DroneCAN/dronecan_dsdlc/dronecan_dsdlc.py", line 195, in <module>
    assert not buildlist-builtlist, "%s not built" % (buildlist-builtlist,)
AssertionError: {'com.hobbywing.esc.SetDirection', 'uavcan.protocol.dynamic_node_id.Allocation', 'com.xacti.GnssStatus', 'uavcan.equipment.esc.RawCommand', 'com.hobbywing.esc.SetLED', 'com.xacti.GimbalAttitudeStatus', 'uavcan.protocol.AccessCommandShell', 'com.hobbywing.esc.GetMaintenanceInformation', 'uavcan.tunnel.Targetted', 'uavcan.equipment.camera_gimbal.Status', 'uavcan.equipment.ahrs.MagneticFieldStrength', 'com.hobbywing.esc.StatusMsg2', 'ardupilot.equipment.power.BatteryContinuous', 'uavcan.equipment.air_data.AngleOfAttack', 'ardupilot.equipment.proximity_sensor.Proximity', 'uavcan.tunnel.Protocol', 'uavcan.protocol.CANIfaceStats', 'uavcan.equipment.air_data.TrueAirspeed', 'uavcan.equipment.actuator.Command', 'com.hex.equipment.flow.Measurement', 'uavcan.equipment.indication.LightsCommand', 'uavcan.protocol.Panic', 'dronecan.remoteid.Location', 'com.volz.servo.ActuatorStatus', 'uavcan.protocol.param.Empty', 'uavcan.protocol.file.BeginFirmwareUpdate', 'uavcan.protocol.param.GetSet', 'dronecan.remoteid.SecureCommand', 'com.hobbywing.esc.RawCommand', 'mppt.Stream', 'uavcan.equipment.power.PrimaryPowerSupplyStatus', 'uavcan.protocol.NodeStatus', 'dronecan.remoteid.BasicID', 'ardupilot.equipment.trafficmonitor.TrafficReport', 'ardupilot.gnss.MovingBaselineData', 'uavcan.protocol.enumeration.Indication', 'uavcan.equipment.gnss.RTCMStream', 'uavcan.equipment.gnss.Auxiliary', 'uavcan.equipment.air_data.Sideslip', 'uavcan.equipment.camera_gimbal.GEOPOICommand', 'uavcan.equipment.esc.RPMCommand', 'dronecan.protocol.Stats', 'uavcan.equipment.ahrs.MagneticFieldStrength2', 'uavcan.protocol.SoftwareVersion', 'uavcan.protocol.param.Value', 'uavcan.equipment.gnss.Fix2', 'uavcan.CoarseOrientation', 'uavcan.equipment.ice.reciprocating.Status', 'uavcan.protocol.param.NumericValue', 'uavcan.protocol.file.Delete', 'com.xacti.GimbalControlData', 'uavcan.protocol.debug.LogLevel', 'uavcan.protocol.GlobalTimeSync', 'com.hobbywing.esc.SelfTest', 'uavcan.equipment.indication.RGB565', 'uavcan.equipment.power.BatteryInfo', 'uavcan.protocol.dynamic_node_id.server.Entry', 'com.hobbywing.esc.StatusMsg1', 'dronecan.remoteid.SelfID', 'com.hobbywing.esc.SetBaud', 'uavcan.equipment.actuator.Status', 'com.hobbywing.esc.GetEscID', 'dronecan.remoteid.OperatorID', 'uavcan.equipment.air_data.IndicatedAirspeed', 'com.hobbywing.esc.SetAngle', 'uavcan.protocol.file.GetInfo', 'uavcan.protocol.dynamic_node_id.server.RequestVote', 'ardupilot.equipment.power.BatteryPeriodic', 'com.hobbywing.esc.StatusMsg3', 'com.hobbywing.esc.GetMajorConfig', 'dronecan.protocol.CanStats', 'uavcan.protocol.RestartNode', 'uavcan.protocol.HardwareVersion', 'uavcan.protocol.file.Write', 'uavcan.protocol.GetDataTypeInfo', 'uavcan.tunnel.SerialConfig', 'uavcan.equipment.range_sensor.Measurement', 'uavcan.protocol.enumeration.Begin', 'uavcan.tunnel.Broadcast', 'ardupilot.indication.NotifyState', 'uavcan.protocol.file.Path', 'uavcan.protocol.file.Read', 'uavcan.equipment.air_data.RawAirData', 'ardupilot.indication.Button', 'com.xacti.GnssStatusReq', 'uavcan.navigation.GlobalNavigationSolution', 'uavcan.equipment.air_data.StaticPressure', 'uavcan.equipment.device.Temperature', 'dronecan.remoteid.ArmStatus', 'ardupilot.gnss.RelPosHeading', 'uavcan.equipment.indication.BeepCommand', 'uavcan.equipment.indication.SingleLightCommand', 'uavcan.protocol.GetTransportStats', 'uavcan.protocol.file.Error', 'uavcan.equipment.air_data.StaticTemperature', 'uavcan.equipment.camera_gimbal.AngularCommand', 'uavcan.equipment.hardpoint.Command', 'uavcan.tunnel.Call', 'uavcan.equipment.ahrs.Solution', 'uavcan.protocol.debug.LogMessage', 'com.hobbywing.esc.SetID', 'com.himark.servo.ServoInfo', 'com.xacti.CopterAttStatus', 'uavcan.equipment.hardpoint.Status', 'uavcan.protocol.param.ExecuteOpcode', 'uavcan.protocol.GetNodeInfo', 'uavcan.equipment.camera_gimbal.Mode', 'ardupilot.equipment.power.BatteryCells', 'uavcan.equipment.gnss.ECEFPositionVelocity', 'cuav.equipment.power.CBAT', 'uavcan.equipment.gnss.Fix', 'uavcan.protocol.dynamic_node_id.server.Discovery', 'com.hobbywing.esc.SetReportingFrequency', 'uavcan.equipment.safety.ArmingStatus', 'ardupilot.gnss.Status', 'ardupilot.indication.SafetyState', 'uavcan.equipment.actuator.ArrayCommand', 'uavcan.protocol.file.EntryType', 'uavcan.equipment.ahrs.RawIMU', 'uavcan.Timestamp', 'uavcan.equipment.esc.Status', 'uavcan.equipment.power.CircuitStatus', 'uavcan.protocol.DataTypeKind', 'uavcan.protocol.file.GetDirectoryEntryInfo', 'dronecan.sensors.rc.RCInput', 'uavcan.equipment.ice.reciprocating.CylinderStatus', 'uavcan.equipment.ice.FuelTankStatus', 'com.hobbywing.esc.SetThrottleSource', 'uavcan.protocol.dynamic_node_id.server.AppendEntries', 'ardupilot.gnss.Heading', 'dronecan.sensors.hygrometer.Hygrometer', 'com.himark.servo.ServoCmd', 'uavcan.protocol.debug.KeyValue', 'ardupilot.equipment.power.BatteryInfoAux', 'dronecan.remoteid.System', 'mppt.OutputEnable'} not built

dronecangen returned 1 error code
Waf: Leaving directory `/home/vic/ardupilot/build/sitl'
Build failed
 -> task in 'dronecan' failed (exit status 1):
        {task 140352272713200: dronecangen .github,ardupilot,com,cuav,dronecan,mppt,tests,uavcan -> }
 (run with -v to display more information)

**Comment by Rongylab** [comment]
I've got the exact same error. The interesting part of it, the build process is working fine in virtual machine (using virtualbox and Ubuntu 22.04.3), however in the same OS without virtualization, this kind of build is failed. 
I hope somebody knows why.

**Comment by oceanomatics** [comment]
Same here with sitl, tried rover copter and sub, droneCAN module error. 
Caught exception! 'dict' object has no attribute 'unknownScriptName'

Try to disable that sub-module, but no entirely sure where to look at in the waf configure.

**Comment by Serbanica123** [comment]
Hello! I am getting the same error, did you find any solution for this?

**Comment by rmackay9** [comment]
Master is compiling fine for me so I think some step has been missed somehow.

If you're having troubles can you try running, "./Tools/gittools/submodule-sync.sh".  This should run [this script](https://github.com/ArduPilot/ardupilot/blob/master/Tools/gittools/submodule-sync.sh).

**Comment by Serbanica123** [comment]
The new change fixed the master branch, I just tested it and now it works as supposed, thanks!

**Comment by tmcayden** [comment]
I've been running into this issue for the last few days as well. Unfortunately, downgraded to Ubuntu 18.04 isn't an option. Are there other things that could help?

**Comment by spachev** [comment]
You can just install Python 3.6 and switch to it. No need to switch Ubuntu to 18.

**Comment by aogrcs** [comment]
I use this script, but it does not work for matser and sitl, but I find this link works
https://discuss.ardupilot.org/t/dronecangen-returned-1-error/109920/6
