### ISSUE TITLE
Min_ALT fence breaches on Mode takeoff with autoenable set

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#25783]
Simple to demo in SITL...from defaults set FENCE_AUTOENABLE, just the MIN ALT fence and FENCE_ALT_MIN to 25m

arm and mode change to MODE takeoff, fence actives during climb to 50m while still below ALT_MIN and changes to RTL

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

log https://www.dropbox.com/scl/fi/e8eaikn75l0jm72d2k9ir/00000003.BIN?rlkey=guv3shv328rgp64jkijw0jhfw&dl=0

**Comment by peterbarker** [comment]
@Hwurzburg could you confirm this is fixed by @andyp1per 's recent fence efforts, please?

**Comment by Hwurzburg** [comment]
fixed
