### ISSUE TITLE
Powerflag 0x16 on pixhawk 6c constantly upped

### ISSUE THREAD

**Issue by prima-bez** [ArduPilot/ardupilot#25840]
## Bug report

**Issue details**

Hello! Powerflag 0x16 *MAV_POWER_STATUS_PERIPH_HIPOWER_OVERCURRENT=16, /* hi-power peripheral supply is in over-current state | */* is always upped, even fc is connected via USB to PC

**Version**
ArduCopter V4.3.2 (fcef79e7)
ChibiOS: 66e5de0d

**Platform**
[  ] All
[  ] AntennaTracker
[ *] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Hexacopter

**Hardware type**
Pixhawk 6C
**Logs**
As we can see [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C/hwdef.dat) analog inputs are defined
```
# power sensing
PE3 VDD_5V_PERIPH_nOC INPUT PULLUP
PF13 VDD_5V_HIPOWER_nOC INPUT PULLUP
```
But STM32H743 (TFBGA100) doesnt have PF13)) Actually fault signal from ic bq24315DSG goes to pin B8 (PC11)

![photo_2023-08-18_13-45-07](https://github.com/ArduPilot/ardupilot/assets/142419832/bcff684a-b9fe-470a-b788-5522f37642fd)

PE2 (A3) - nVDD_5V_PERIPH_EN  OUTPUT HIGH
PE3 (B3) - VDD_5V_PERIPH_nOC INPUT PULLUP
PC10 (B9) - nVDD_5V_HIPOWER_EN OUTPUT HIGH
PC11 (B8) - VDD_5V_HIPOWER_nOC INPUT PULLUP

**Also!!**
Fault pin of bq24315DSG  is pulled up by 47K resistor. In same time STM input is pulled up logicaly.
Thats why STM will never detect low level on its pins))
![Screenshot_20230818_133849](https://github.com/ArduPilot/ardupilot/assets/142419832/e7f2a4ad-e3f5-4fc4-813f-544171420993)

**Comment by xfacta** [comment]
I second this bug - I've seen a couple of Pixhawk 6C logs with powerflag 16 even when everything is checked and external devices are powered by their own BEC.
I wasnt aware of the internal detail though - thanks prima-bez
