### ISSUE TITLE
Protocol st24 work master but not stable

### ISSUE THREAD

**Issue by romucifer** [ArduPilot/ardupilot#25956]
Hello rc protocol  st24 work in master firmware but not work in stable firmware 

 Input Rc protocol st24 in stable version

_Please describe the problem_
Rc protocol st24 not work in stable firmware 

**Platform**

[  ] Rover

**Airframe type**
Boat
Pixhawk 1m
**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by yuri-rage** [comment]
This is a user request to backport PR https://github.com/ArduPilot/ardupilot/pull/23742 to Rover stable (4.4).

See discussion: https://discuss.ardupilot.org/t/protocol-rc-st24-firmware-stable/111570

**Comment by rmackay9** [comment]
OK, I've added it to the 4.4 project so it will be considered for 4.4.5.

**Comment by romucifer** [comment]
Thank youvery much

**Comment by lipper-chengdu** [comment]
> OK, I've added it to the 4.4 project so it will be considered for 4.4.5.

https://github.com/ArduPilot/ardupilot/pull/23914
Can this PR be merged? Enable ST24 to support failsafe check and Status BackHaul RC.
