### ISSUE TITLE
Tools: delete unused emitxml_mp.py

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#25998]
I've checked with @meee1 and Mission Planner uses the default parameter definition files (for example [apm.pdef.xml](https://autotest.ardupilot.org/Parameters/ArduCopter/apm.pdef.xml)) produced by the emitxml.py script so we can delete [emitxml_mp.py](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/param_metadata/xmlemit_mp.py).  It seems this python script was never actually used.

As a side note, it's odd that we have output files with two dots in the filename.  I think we should have named these files apm_pdef.xml instead of apm.pdef.xml.

**Comment by peterbarker** [comment]
This was done.
