### ISSUE TITLE
Debug build failed on copter v4.4.4

### ISSUE THREAD

**Issue by ManishSakharwade** [ArduPilot/ardupilot#25997]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**
Debug build failed on **copter v4.4.4**

_Please describe the problem_
I am able to compile release firmware v4.4.4 properly, but when i tried to compile debug build i am getting this error.
[ 908/1006] Compiling libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
[ 909/1006] Compiling libraries/AP_NavEKF3/AP_NavEKF3_GyroBias.cpp
[ 910/1006] Compiling libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
…/…/libraries/AP_UAVCAN/AP_UAVCAN.cpp: In member function ‘virtual void AP_UAVCAN::init(uint8_t, bool)’:
…/…/libraries/AP_UAVCAN/AP_UAVCAN.cpp:571:1: **error: the frame size of 2296 bytes is larger than 2200 bytes [-Werror=frame-larger-than=]**
}
^
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors

I run this commands to compile debug build

./waf distclean
./waf configure --board CubeOrangePlus --debug
./waf copter
**Version**
_What version was the issue encountered with_
Copter-4.4.4
**Platform**
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
CubeOrangePlus

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
The debug build uses more memory, you will have to bump the value here:

https://github.com/ArduPilot/ardupilot/blob/5d7fb310fb2e1e89bf34e0b0845d146ff8abf2d0/libraries/AP_UAVCAN/AP_UAVCAN.cpp#L302
