### ISSUE TITLE
Dshot buzzer not working

### ISSUE THREAD

**Issue by GalacticGreg** [ArduPilot/ardupilot#26051]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**

I have DShot buzzer enabled on 4.5 dev, bluejay .19.2, and get no arming (or other) beeper sounds. Lost copter switch doesn't cause a beep either.

**Version**
4.5-dev on Omnibusf4, custom hardware inf. With Bidir Dshot enabled and custom features removed/enabled.

**Platform**
[  ] All
[  ] AntennaTracker
[X  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X4

**Hardware type**
Custom omnibusf4

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by andyp1per** [comment]
Do you have SERVO_DSHOT_ESC set? It needs to be for dshot commands to work. I don't think bluejay supports the dshot command for beeper.

**Comment by lthall** [comment]
Hi @GalacticGreg,

I think we really need to see a log for this. Ideally support issues should be raised in the forums first and then once they're confirmed issues we raise issues.

Sorry to be strict but if we don't then the issues list just turns into a support forum.

I'm going to go ahead and close this and maybe you can create a discussion here in the [Copter-4.4 category](https://discuss.ardupilot.org/c/arducopter/copter-44/169)? We will also hopefully start 4.5 beta testing within a week or two.

**Comment by GalacticGreg** [comment]
Servo_dshot_rate=5

The beeper worked in Betaflight so bluebay must have the command for it.

**Comment by GalacticGreg** [comment]
Servo_dshot_esc=4

**Comment by andyp1per** [comment]
I would  be grateful if you could test my fix

**Comment by GalacticGreg** [comment]
Hi Andyp1per,
I'm grateful that you made a fix! Would you still like me to test? If so I'll work on it tonight. Can I compile from the master branch or is it not merged? (Sorry I'm new to git)

**Comment by GalacticGreg** [comment]
I figured it out. Your fix works. Thanks again Andyp1per!
