### ISSUE TITLE
Bootloader data writing protocol needs to be improved

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#26050]
The protocol for writing data to bootloader needs to be improved. By default, it is verified after writing. I think this is very unsafe and requires verification every frame.

![1705901335669](https://github.com/ArduPilot/ardupilot/assets/16605202/c946189f-783e-41ad-911d-b952144effb4)

**Comment by peterbarker** [comment]
I don't know how checking after every write helps at all.

Your bootloader is hosed after a single bad write - whether we detect that straight-away or by doing the checksum isn't important.

Given you also need to erase entire sectors to fix the bad write, even working out that a particular page write failed isn't helpful.

Perhaps I'm misunderstanding the problem you're outlining.

**Comment by peterbarker** [comment]
Closing this as NeedAnswer for several weeks.

@lixiaowei123 if you think I'm wrong, please reopen!
