### ISSUE TITLE
Yaapu receiving out of order/missing mavlink messages through fport telemetry.

### ISSUE THREAD

**Issue by GalacticGreg** [ArduPilot/ardupilot#26053]
## Bug report

**Issue details**

I have the newest yaapu release (Mar 2023) for my taranis X7 accst with an R-XSR in fport mode (using inverted solder pad) on an omnibusf4. Mavlink messages are corrupted. I tried every permutation of pull-up on the TX pin, fport pad option and both 57600 and 115200 baud rates so far and the corruption remains.

**Version**
4.5dev, edgetx 2.9.2, RXSR fport solder pad v. 2.1.1 firmware, yaapu 2.0

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X4

**Hardware type**
Custom hardware definition omnibusf4.

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by GalacticGreg** [comment]
Just a note to anyone in the same situation, downgrading to R-XSR F.Port firmware version 2.1.0 from 2.1.1 fixes this issue. I believe 2.1.1 was supposed to fix no output from the receiver during a failsafe, but I can confirm that when failsafe is set to "no pulses" then arducopter detects the failsafe properly.

**Comment by mpjf01** [comment]
#25546 might be related

**Comment by GalacticGreg** [comment]
I don't think it is mpjf01. In #25546 the issue was with ardupilot only and with the newer ACCESS firmware.

My problem is with the older ACCST firmware and even Betaflight users are having problems with telemetry in 2.1.1 firmware as per reports from 3 years ago. Frsky was releasing beta versions of the firmware to address this issue at the time then gave up, closed their beta repository and ghosted anyone complaining about ACCST firmware problems to focus on the newer ACCESS, leaving behind bugs they introduced while trying to fix other problems.

This issue is not worth addressing through ardupilot, I'm going to close it. At least it is documented for anyone else stuck with old hardware like me and wondering what's going on.
