### ISSUE TITLE
Throw mode goes way too high.

### ISSUE THREAD

**Issue by GalacticGreg** [ArduPilot/ardupilot#26052]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

**Issue details**

Throw mode goes really high before it stops. it would be nice if it stops raising altitude once it is horizontally stable, but it goes about 20m high before it switches to brake mode (which I have it set to).

**Version**
4.5 dev.

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X4

**Hardware type**
Custom omnibusf4

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
Hi @GalacticGreg,

I think we really need to see a log for this.  Ideally support issues should be raised in the forums first and then once they're confirmed issues we raise issues.

Sorry to be strict but if we don't then the issues list just turns into a support forum.

I'm going to go ahead and close this and maybe you can create a discussion here in the [Copter-4.4 category](https://discuss.ardupilot.org/c/arducopter/copter-44/169)?  We will also hopefully start 4.5 beta testing within a week or two.
