### ISSUE TITLE
Driver for Ouster OS1 Lidar

### ISSUE THREAD

**Issue by ehsankf** [ArduPilot/ardupilot#26121]
## Feature request

**Is your feature request related to a problem? Please describe.**
I was wondering if there is a driver for Ouster OS1 Lidar.
https://ouster.com/products/hardware/os1-lidar-sensor

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by Ryanf55** [comment]
This cannot run on ArduPilot. Use the supplied driver and run it on Linux. 
https://github.com/ros-drivers/ros2_ouster_drivers

ArduPilot doesn't have 3D point cloud support. Feel free to use a supported sensor here (2D).
https://ardupilot.org/copter/docs/common-rplidar-a2.html
