### ISSUE TITLE
Reference frames: AION R1 params sorely outdated

### ISSUE THREAD

**Issue by yuri-rage** [ArduPilot/ardupilot#26192]
## Bug report

**Issue details**

This still has 3.x in the header comment and contains many parameters that either no longer exist or are in need of update:
https://github.com/ArduPilot/ardupilot/blob/master/Tools/Frame_params/AION_R1_Rover.param

**Version**
4.4+

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ x] Rover
[  ] Submarine

**Airframe type**
Rover

**Hardware type**
All

**Logs**
N/A

**Comment by rmackay9** [comment]
This request comes from this discussion https://discuss.ardupilot.org/t/no-pwm-output-from-skid-steer-rover/112986/6
