### ISSUE TITLE
GPS: Don't send full config string if only looking for a single type of GPS

### ISSUE THREAD

**Issue by suraqis** [ArduPilot/ardupilot#2622]
When using other NMEA GNSS receiver than specified in code (SIRF, MTK, U-Blox)  autopilot tries to configure it with initialisation messages. Some receivers can't ignore that messages and fail their initialization even already configured. We need to have "generic NMEA" in order not to send any initialization messages when initializing GNSS receiveer.

**Comment by rmackay9** [comment]
I think you should be able to set the GPS_TYPE parameter to specify that you only want to use NMEA GPS and then it will only send the init string for the NMEA.  I could be wrong but I'm wondering if you've tried this to see if it works?

**Comment by suraqis** [comment]
I set GPS_TYPE to 5 (NMEA) and it sends something to my receiver that makes it crazy. Now I just disconnect tx pin of autopilot's serial port to have it working.

**Comment by WickedShell** [comment]
What receiver? The entire auto detection/configuration sequence is dependent upon the reciever ignoring any message it doesn't understand. All the configure stuff sent at the start is a binary message for ublox and then a bunch of P messages for ublox, sirf, mtk etc.

**Comment by WickedShell** [comment]
While you're GPS should ignore the other messages coming in as they are all manufacturer specific messages/binary you're also correct that the entire auto config blob is sent regardless of what GPS type you select. I renamed the issue to make it clearer.

**Comment by suraqis** [comment]
Sorry for ignoring previous question. That receiver was Novatel OEM module based device. It sends correct NMEA sequences but can't ignore config strings. I'd like to have "NMEA without configuration" type of GNSS receiver. That means that user should correctly setup receiver for NMEA operations.

**Comment by WickedShell** [comment]
Yeah there isn't a NMEA config string, at least not on the autodetect level which is what I think was messing you up. All the config strings are for the other drivers... I don't actually know whats in the NMEA driver after that, but lets start with the first step of not sending the autodetect.

**Comment by mr337** [comment]
I agree, this just bit me yesterday and is messing up my Eclipse receivers. I'll be whipping up a PR to not send the config string. Initially I thought the GPS_AUTO_CONFIG was an issue but looking at the code is only used for UBLOX recievers. Everything gets send the blob regardless.
