### ISSUE TITLE
Copter: add support for CONDITION_CHANGE_ALT

### ISSUE THREAD

**Issue by nraines2002** [ArduPilot/ardupilot#26227]
NOTE:

Sending CONDITION_CHANGE_ALT is not yet supported but similar commands are. 
See wiki: [https://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html](https://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html)

## Bug report

**Issue details**

Sending MAVLink messages via Command_Int is returning COMMAND_ACK:[COMMAND_NAME]:UNSUPPORTED. I am using MAVROS built using ROS2 Foxy to pack and send these commands, using the Command_Long MAVROS service to send a Set_Mode message works but returns COMMAND_ACK:DO_SET_MODE:DENIED. I have sent the message with frames, MAV_FRAME_GLOBAL, MAV_FRAME_LOCAL_NED, MAV_FRAME_MISSION, MAV_FRAME_GLOBAL_RELATIVE_ALT, MAV_FRAME_GLOBAL_RELATIVE_ALT_INT to no avail.

Current usage:

`auto request = std::make_shared<mavros_msgs::srv::CommandInt::Request>();`
`                request->frame = mavros_msgs::msg::Waypoint::FRAME_GLOBAL_REL_ALT;`
`                request->command = 113;`
`                request->current = 0;`
`                request->autocontinue = 0;`
`                request->param1 = 0;`                        
`                request->param2 = 0;`                        
`                request->param3 = 0;`                        
`                request->param4 = 0;`                        
`                request->x = 0;`                        
`                request->y = 0;`                        
`                request->z = alt; (altitude in meters)`
`                                                                      `
`                auto result = comm_client_->async_send_request(request);`

**Version**
Copter-4.4/4.3/4.2

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
SITL

**Hardware type**
None, used SITL

**Logs**

Current usage:

**Comment by rmackay9** [comment]
@nraines2002,

Which version of AP is on the autopilot?  4.5.0 is required for many commands when using command_int.

**Comment by amilcarlucas** [comment]
This is a support question that I already answered on the forum.

**Comment by nraines2002** [comment]
> @nraines2002,
> 
> Which version of AP is on the autopilot? 4.5.0 is required for many commands when using command_int.

I was trying various different versions and just tried 4.5.0 with no luck.

![image](https://github.com/ArduPilot/ardupilot/assets/96854114/343244b1-0194-439b-8c51-7017f199322c)

**Comment by amilcarlucas** [comment]
Then that command is not yet supported.You should change the title of this issue to:
CONDITION_CHANGE_ALT COMMAND_INT unsupported

**Comment by rmackay9** [comment]
OK, good that we're getting to the real issue now.

@nraines2002, have you seen [this wiki page that documents how copters can be controlled using MAVLink](https://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html)?

I'm not too enthusiastic about adding support for [CONDITION_CHANGE_ALT](https://mavlink.io/en/messages/common.html#MAV_CMD_CONDITION_CHANGE_ALT) when we already have so many more capable alternatives.

**Comment by nraines2002** [comment]
@rmackay9 I haven't seen that wiki, that's exactly what I needed.

The MAV_CMD_DO_REPOSITION command is all I need, thank you.

**Comment by rmackay9** [comment]
@nraines2002,

great stuff.  I'll go ahead and close this issue then.  Txs for using AP!
