### ISSUE TITLE
Sending unknown message (37) error with custom server build of 4.5.0-beta2

### ISSUE THREAD

**Issue by DavideLentini** [ArduPilot/ardupilot#26358]
## Bug report

**Issue details**

Hi all , I programmed the drone with firmware 4.5.0-beta2 using these definitions , to remove the items I don't need/interest . 
[custum_hwdef_build.txt](https://github.com/ArduPilot/ardupilot/files/14448191/custum_hwdef_build.txt)

Loading the firmware , the drone seems to work without problems , but it returns every 2/3 seconds this message : 

![image](https://github.com/ArduPilot/ardupilot/assets/74407457/a73a25de-d166-4522-bac3-c65252c29f5f)

Loading clean firwmare 4.5.0-beta2 , this problem does not occur . It could be caused by my definitions but without a definition of the error I wouldn't really know where to look . Thanks

**Version**
4.5.0-beta2

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
It was rangefinder, we forgot to tell it not to try sending the message if rangefinder is not there. fix here: https://github.com/ArduPilot/ardupilot/pull/26361

**Comment by IamPete1** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/26361
