### ISSUE TITLE
Copter automatically turns north when switching to GUIDED_NOGPS

### ISSUE THREAD

**Issue by ShevaDavid** [ArduPilot/ardupilot#26357]
## Bug report

**Issue details**
This issue follows up the discussion with Leonard
https://discuss.ardupilot.org/t/set-attitude-target-with-guided-no-gps-lack-of-documentation/111845/24
When I switch to GUIDED_NOGPS, the copter automatically turns north, because this is how attitude quaternion is initialized (1, 0, 0, 0) in angle_control_start method. So I just replaced it with zero quaternion (0, 0, 0, 0) and now there is no automatic north rotaion.

**Version**
4.5

**Platform**
[  ] Copter

**Comment by rmackay9** [comment]
Hi, thanks for the report. I've added this to the Copter-4.5 issues list although I guess the issue also exists in 4.4.  Txs again

**Comment by lthall** [comment]
PR #26407

**Comment by lthall** [comment]
This has now been fixed.
