### ISSUE TITLE
CRSF module into bind mode with software

### ISSUE THREAD

**Issue by SPooKfpv** [ArduPilot/ardupilot#26363]
## Feature request

**Is your feature request related to a problem? Please describe.**
Our fleet of drones all use crossfire. Our operational team often have to rebind controllers, and as a test pilot I need to bind crossfire almost daily, both for new builds and services. The modules we use vary, but they are all a bit hard to get to, or have a pinhole made for the sole purpose of getting to the bind button. On our 4kg drone we also use a small RX with those tiny buttons that we keep breaking and having to replace.  
Binding with hardware buttons is  nuisance, and a weak point, that have caused a lot of downtime for our operators. 

**Describe the solution you'd like**
Get CRSF module into bind mode with software. Like in Betaflight you have the CLI command rx_bind, and no need to use hardware button. . Both over mavlink and CRFS we want to be able to trigger the binding. 

**Describe alternatives you've considered**
Don't see any other options then todays hardware binding, and a potential awesome software binding that we can implement in our QGC :) 

**Platform**
Useful for all platforms, we need it for Copter.
[ X ] All

**Additional context**
![image](https://github.com/ArduPilot/ardupilot/assets/86800677/5540b73a-3e23-4b23-beab-13caff8e76a1)

**Comment by andyp1per** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/26375
