### ISSUE TITLE
Traditional Heli Auto tune

### ISSUE THREAD

**Issue by Jman841** [ArduPilot/ardupilot#2639]
Would it be possible to add an Auto-Tune function for traditional heli's as well?

**Comment by R-Lefebvre** [comment]
It's probably possible, but difficult. I think that it would be most plausible to auto-tune the feedforward.

It's a big job though, and could cost a lot in hardware.

**Comment by Jman841** [comment]
Hey Rob, I closed this issue becuase I realized I had another issue opened on the same topic

**Comment by magicrub** [comment]
@Jman841 when you close an issue like this due to a duplicate that you found/knowOf, please link it here so everyone else who's searching for it in the future can find it too. Thanks!
