### ISSUE TITLE
the two terms has different units they cannot be subtracted

### ISSUE THREAD

**Issue by itayguy** [ArduPilot/ardupilot#26502]
https://github.com/ArduPilot/ardupilot/blob/9feccd6671f0f810a2f1380e1ead29c0931ffba2/ArduCopter/mode_flowhold.cpp#L405

**Comment by lthall** [comment]
Can you please explain this in a little more detail where you think the bug is?

The two functions both appear to return rad/s.

`    // flowRate - returns the raw movement from the sensor in rad/s
    const Vector2f& flowRate() const { return _state.flowRate; }

    // bodyRate - returns the IMU-adjusted movement in rad/s
    const Vector2f& bodyRate() const { return _state.bodyRate; }`
