### ISSUE TITLE
Handling mavlink message `MAV_CMD_COMPONENT_ARM_DISARM` is inconsistent with the requirement of mavlink protocol

### ISSUE THREAD

**Issue by NumbNutN** [ArduPilot/ardupilot#26521]
## Bug report

**Issue details**

Hi, I'm using `Ardupilot in STIL` and use mavlink commands to perform an offboard control.
As main program loop cannot run at the required frequency in my SITL environment, Ardupilot fails the safety checks, I need to add a `Force` parameter in arming/disarming command to make it work.
I've follow the Mavlink Message Definition to pack a mavlink packet:
https://mavlink.io/en/messages/common.html#MAV_CMD_COMPONENT_ARM_DISARM

I use a mavproxy command line tool to test the command:
```
GUIDED> message COMMAND_LONG 0 0 400 0 1 21196 0 0 0 0 0
```
I'm confused that it actually didn't work, until I search for the source code and find the `magic number definition`:

https://github.com/ArduPilot/ardupilot/blob/b316b3ab46074d2499c0143cd2fdc7c69dc5a8a9/libraries/GCS_MAVLink/GCS.h#L728-L729

But Mavlink does required the second parameter to be `21196` to force arming/disarming the vehicle.
For what reason is force arming to actually use another parameter?

The document seems to be misleading:
https://ardupilot.org/dev/docs/mavlink-arming-and-disarming.html

**Platform**
[  ] All
[  ] AntennaTracker
[ Tick ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by peterbarker** [comment]
https://github.com/ArduPilot/ardupilot/pull/27716 fixes this issue.

I think your problems around forced arming are besides the point, however.

Your external program should be waiting until the prearm bit in sys_status goes healthy before trying to arm the vehicle.

Force-arming the vehicle is not something to do as a matter of course or people end up with a face full of propeller.  Virtual propeller in the case of SITL.
