### ISSUE TITLE
Sub: if origin.alt == 0, field elevation is set to 0 at 1Hz while vehicle is disarmed

### ISSUE THREAD

**Issue by clydemcqueen** [ArduPilot/ardupilot#26645]
## Bug report

**Issue details**

[Edited to clarify the conditions.]

If origin.alt == 0, then the field elevation will be set to 0 at 1hz while the vehicle is disarmed.

This affects all vehicles, but most vehicles will not see origin.alt == 0. Also most vehicles are sitting on the ground while they are disarmed.

I stumbled upon while testing ORIGIN_LAT/LON/ALT parameters for sub, with default values of 0. It is also possible to reproduce this by sending a SET_GPS_GLOBAL_ORIGIN message with altitude == 0.

In general, I don't think the BARO_FIELD_ELV feature is useful for sub, so a quick fix for sub is to `#ifdef` out this feature.

**Version**

All sub versions > 4.1.x, e.g., 4.5

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[ x ] Submarine

**Airframe type**

All

**Hardware type**

All

**Logs**

This is a [lightly edited] SITL run:

AP: ArduSub V4.6.0-dev (bc29550c)
AP: 5b736df2fa0c4554bc0d10d618c974d5
AP: Frame: VECTORED
AP: Barometer 1 calibration complete
AP: Barometer 2 calibration complete
AP: ArduPilot Ready
AP: AHRS: DCM active
paramftp: bad count 1361 should be 1357
AP: ArduSub V4.6.0-dev (bc29550c)
AP: 5b736df2fa0c4554bc0d10d618c974d5
AP: Frame: VECTORED
AP: EKF3 IMU0 initialised
AP: EKF3 IMU1 initialised
AP: AHRS: EKF3 active
Received 1361 parameters (ftp)
Saved 1361 parameters to mav.parm
AP: EKF3 IMU0 tilt alignment complete
AP: EKF3 IMU1 tilt alignment complete
AP: EKF3 IMU0 MAG0 initial yaw alignment complete
AP: EKF3 IMU1 MAG0 initial yaw alignment complete
AP: GPS 1: probing for u-blox at 230400 baud
AP: GPS 1: detected u-blox
param set GPS1_TYPE 0
MANUAL> param set EK3_SRC1_POSXY 0
MANUAL> fence present
Flight battery 100 percent
reboot
MANUAL> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
EOF on TCP socket
Attempting reconnect
[Errno 111] Connection refused sleeping

Init ArduSub V4.6.0-dev (bc29550c)

Free RAM: 131072
Booting 0/0
0 0 0 AP_Logger_File: buffer size=204800
AP: Barometer 1 calibration complete
AP: Barometer 2 calibration complete
AP: ArduPilot Ready
AP: AHRS: DCM active
AP: EKF3 IMU0 initialised
AP: EKF3 IMU1 initialised
AP: AHRS: EKF3 active
AP: EKF3 IMU0 tilt alignment complete
AP: EKF3 IMU1 tilt alignment complete
AP: EKF3 IMU0 MAG0 initial yaw alignment complete
AP: EKF3 IMU1 MAG0 initial yaw alignment complete

_Send SET_GPS_GLOBAL_ORIGIN message with altitude = 0_

AP: EKF3 IMU0 origin set
AP: EKF3 IMU1 origin set
AP: Field Elevation Set: 0m
AP: Field Elevation Set: 0m
AP: Field Elevation Set: 0m
AP: Field Elevation Set: 0m
AP: Field Elevation Set: 0m

**Comment by rmackay9** [comment]
Hi @clydemcqueen,

Could you clarify what the issue is with having the field elevation set while disarmed?  Is it just the message is annoying?  Does it cause problems in some way?

**Comment by clydemcqueen** [comment]
Hi @rmackay9 -- it re-calibrates the barometer so that the barometer reports origin.alt (0 in this case) at the current pressure. So the sub thinks it has teleported to the surface.

**Comment by rmackay9** [comment]
@clydemcqueen,

Ok, thanks for the clarification.  So this would only happen if the user disarmed while deep underwater though wouldn't it?

**Comment by clydemcqueen** [comment]
Yes, it is only a problem for sub if the user disarms while submerged. The sub still operates fine, but the user doesn't know how deep it is.

**Comment by Williangalvani** [comment]
I want to point out that is pretty common for me to disarm the rov while submerged. Most of them are slightly buoyant, so it usually just means they will slowly surface.

**Comment by clydemcqueen** [comment]
Fixed via https://github.com/ArduPilot/ardupilot/pull/26658
