### ISSUE TITLE
Copter: warn when single motors reaches throttle limits as it's a sign the motor is failing

### ISSUE THREAD

**Issue by hsteinhaus** [ArduPilot/ardupilot#2666]
I just had a crash due to a burnt motor. The copter was set up to fly in a range of 50-60% throttle, with peaks usually going to no more than 80% at maximum speed and full climb during Loiter and Auto . 

During the last flight, the logs reveal that the throttle level of  motor no. 2 suddenly rises to nearly constant 100% for almost a minute. Then the copter went out of control (tipped over motor no. 2). Obviously the motor now had failed completely. The coils of the motor were made by multi-strand wire - I guess one or more single wires of the coil broke/failed just as the output power reduced. In the following minute, the remaining wires began to overheat and finally burnt completely. The drive setup has been tested on the ground with continuous 100% throttle without any issues for 5 minutes.

![figure_1](https://cloud.githubusercontent.com/assets/3057137/9106416/75cac656-3c20-11e5-9c79-4c9c6eda5940.png)

I think the crash could have been avoided easily with a warning to the operator about the unusually high throttle output. What do you think about adding a GCS/telemetry warning as soon as the throttle limits are reached during Loiter and Auto? Even a failsafe/land action might be useful in this situation to prevent a crash or a fly-away.

**Comment by rmackay9** [comment]
A "Thrust Loss (4)" message appears in Copter-4.0 (and higher) so I will close this I think.
