### ISSUE TITLE
Missing barometer telemetry values in AP Plane, yaapu and ExpressLRS.

### ISSUE THREAD

**Issue by ghost** [ArduPilot/ardupilot#26699]
In my opinion, flying a plane the barometer values Alt and VSpd are essential. Especially with a powered glider trying to do some thermal flying. Just learned, that the combination AP Plane, yaapu and ExpressLRS does NOT support the transmission of those values.

https://discuss.ardupilot.org/t/variometer-output-on-crsf-telemetry-for-gliders/115656

In the yaapu github I found this issue, but there Alessandro is pointig over to AP.

yaapu/FrskyTelemetryScript#210

Therefore I post this issue/feature request here ......

br Kalle

**Comment by Merga189** [comment]
Hope, someone here read that discussion at https://github.com/ExpressLRS/ExpressLRS/issues/2644
