### ISSUE TITLE
AP_HAL_ChibiOS: add support for FMUv3 or CUAV Pixhack V3x with 3 IMUs

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#26697]
We have a [request here](https://discuss.ardupilot.org/t/ardupilot-custom-firmware-builder-fmuv3-missing-necessary-for-cuav-pixhack-v3x/115823) to add Custom Build Server support for the FMUv3 so that the CUAV Pixhack V3x firmware supports 3 IMUs.

While [custom build server issues should be logged over here](https://github.com/ArduPilot/CustomBuild/issues) I've raised it here because I think we would not want to enable FMUv3 because we prefer that all boards are named properly.  So instead we should add a new build target for the CUAV Pixhack V3x (perhaps simply inheriting from FMUv3) and then it should automatically appear in the custom build server's list of available autopilot.

**Comment by Harald69** [comment]
I think to add CUAV Pixhack V3x as a named build would be excellent.

**Comment by Harald69** [comment]
Thanks a lot
