### ISSUE TITLE
FoxeerF405V2 hwdef issues

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#26715]
The recently merged board has several issues relating to its shown application/wiring diagram not being consistent with its hwdef:

1. ~~GPS is shown as UART5 which will not work without changing UART3 AND UART4 default(GPS) and setting UART5 to GPS. This should be fixed.~~
2. UART3 is shown as TRAMP but that protocol is not set as default in hwdef 
3. ~~UART1 is shown as ESC telem but default protocol not set~~
4. UART4 is shown as DJI connection, but default protocol not set to DJI or, preferably, Displayport. also alternate SBUS input on RX6 needs to be noted in readme for this connector
5.~~LED will not work unless appropriate params set and then~~ output5 must be noted in readme  not to be useable except as LED output also.
6. in Readme FRsky telem setup will not work...those params are for H7 only, not F4. F4 needs external bidir inverter and different params
7. Foxeer site implies PPM input on SBUS pin which would require RX2 to be a TIM9 int input with alt config to normal UART...I don't think PPM is required, just noting BF migratotrs could be surprised
8. The board has switchable camera inputs which are not included in the hwdef

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by andyp1per** [comment]
Hi @Hwurzburg there was actually an update that got merged that already fixes most of these - could you check it please? Thx

**Comment by Hwurzburg** [comment]
a couple have been fixed, but several remain
