### ISSUE TITLE
Add a new brakes mode loiter

### ISSUE THREAD

**Issue by lixiaowei123** [ArduPilot/ardupilot#26758]
When can we add a good braking mode on the official website? The loiter and poshold brakes are really bad

**Comment by rmackay9** [comment]
Hi @lixiaowei123,

Can you be more specific about what issue you're seeing?  Also I think we need to see an onboard log to clarify if it is really a flight control issue or a tuning issue.

I'm going to go ahead and close this but please feel free to create a discussion in the [support forums](https://discuss.ardupilot.org/c/arducopter/copter-45/174).  After we confirm this is a real issue or enhancement request we can re-open or create a more detailed issue.

I'm sure you've already seen it but [here's our Loiter wiki page](https://ardupilot.org/copter/docs/loiter-mode.html#loiter-mode) with some tuning parameters explained.
