### ISSUE TITLE
AP_VisualOdom.h：a bug in get_delay_ms(), return type error

### ISSUE THREAD

**Issue by luweiagi** [ArduPilot/ardupilot#26800]
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_DAL/AP_DAL_VisualOdom.h#L21
![image](https://github.com/ArduPilot/ardupilot/assets/19629731/f2e59226-55f3-4fb4-9e53-ad46e0ae53af)
 
This function is used at:
https://github.com/ArduPilot/ardupilot/blob/5a21d0cb8a859b293eea087fb8c9be150c0ca910/libraries/AP_NavEKF3/AP_NavEKF3_core.cpp#L83
![image](https://github.com/ArduPilot/ardupilot/assets/19629731/223b4b61-66f7-4b45-88b9-1270dbacb8c4)

We can see that its return should be uint16_t or uint32_t, not bool.

@peterbarker

**Comment by rmackay9** [comment]
That does indeed look like a bug.  Thanks @luweiagi!

**Comment by tridge** [comment]
@luweiagi great catch!

**Comment by peterbarker** [comment]
Good find.  4-year-old bug!

**Comment by rmackay9** [comment]
Fixed in master and this will go out with 4.5.2-beta1.  @luweiagi thanks again!
