### ISSUE TITLE
SBUS Output: Channel 5 also being output on Channel 13

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#26815]
In Copter-4.5 (and higher) the SBus output feature ([perhaps best described on the wiki here](https://ardupilot.org/copter/docs/common-sbus-out.html)) is outputting the Channel 5 value to Channel 13 as well.  There are likely other channels that are being output incorrectly as well.

This bug was reproduced on two daisy-chained CubeOrangePlus autopilots by doing this:

1. Loaded 4.6.0-dev onto both autopilots, wiped parameters, performed accel, compass and RC calibration
2. 1st autopilot's parameters were set:
    - BRD_SBUS_OUT = 3 (100hz)
    - SERVO5_FUNCTION = (RCIN6)
3. 1st autopilot's SBus out was connected to 2nd autopilot's RCIN port
4. 1st autopilot's RC input port was connected to an RC receiver and the transmitter's tuning knob was used to change the RC 6 input and thus SERVO5's output
![Copter1-ch5-output](https://github.com/ArduPilot/ardupilot/assets/1498098/27f4f11d-a432-483d-9f22-6d694dd51d02)
5. When the 1st Copter was running Copter-4.4.4 the 2nd autopilot's RC input correctly shows only channel 5 changing
    ![Copter2-1st-on-444](https://github.com/ArduPilot/ardupilot/assets/1498098/161a2209-73d0-4cfc-84d6-167d6f02d6f5)
6. When the 1st Copter was running Copter-4.6.0-dev the 2nd autopilot's RC input shows both channel 5 and 13 changing
    ![Copter2-1st-on-460](https://github.com/ArduPilot/ardupilot/assets/1498098/d8ba6a68-bad3-4639-b691-981904727bce)

BTW, it did not matter what AP version was on the 2nd autopilot which I believe means the issue must be in the output (not the input).

This PR is the most likely candidate but it is NOT the cause (I've tested before and after) https://github.com/ArduPilot/ardupilot/pull/25169

This bug was first reported [here on the Copter-4.5 forum](https://discuss.ardupilot.org/t/copter-4-5-0-released/115614/21)

**Comment by andyp1per** [comment]
I would think that the most likely candidate as a cause for this are the iomcu changes

**Comment by tridge** [comment]
this is worth more investigation, a Saleae trace on the sbus out with 4.5.1 would be good, see what the bits actually look like

**Comment by tridge** [comment]
@rmackay9 the duplication of the lower 8 channels to upper 8 channels is just a read of the reg_direct.pwm values which are next in line in ram. It will not cause a crash, and it will always be that with this bug the upper 8 channels are a copy of the lower 8 channels
