### ISSUE TITLE
SBus Output missing for channel 9 ~ 16

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#26851]
As reported [here on the Copter 4.5 forums](https://discuss.ardupilot.org/t/copter-4-5-0-released/115614/89), it seems that SBus output for channel 9 to 16 is not working in 4.5.0.

The testing setup was similar to that used for issue https://github.com/ArduPilot/ardupilot/issues/26815 which is namely one CubeOrange's SBus output was connected to another CubeOrange's SBus input.

Autopilot 1 was setup so that the RC input from channel 6 was output on channels 5, 8, 9 and 16
![image](https://github.com/ArduPilot/ardupilot/assets/1498098/c578ac55-a09a-4d63-aab5-2954cf50511c)

Autopilot 2's RC input was connected to Autopilot 1's SBus output.  With Autopilot 1 running 4.4.4, Autopilot2's RC input showed channel 5, 8, 9 and 16 correctly.
![image](https://github.com/ArduPilot/ardupilot/assets/1498098/808a0a9a-96ed-4325-a231-4d7209a727b4)

With Autopilot 1 running 4.6.0-dev, Autopilot 2's RC input showed channel 8 to 16 were not being output
![image](https://github.com/ArduPilot/ardupilot/assets/1498098/e233f0ae-b586-4ef3-a014-d6d1a9c5df66)

**Comment by andyp1per** [comment]
Fixed by #26898
