### ISSUE TITLE
memory issue for debug build

### ISSUE THREAD

**Issue by ManishSakharwade** [ArduPilot/ardupilot#26884]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

**_https://github.com/ArduPilot/ardupilot/issues/25997_**

## Bug report

**Issue details**

_Please describe the problem_

**_i am compiling debug build for cubeorangeplus and i got error_** 
../../libraries/AP_UAVCAN/AP_UAVCAN.cpp: In member function 'virtual void AP_UAVCAN::init(uint8_t, bool)':
../../libraries/AP_UAVCAN/AP_UAVCAN.cpp:571:1: error: the frame size of 2296 bytes is larger than 2200 bytes [-Werror=frame-larger-than=]

**_then i increases the frame size 2200 to 2300.
this solution given in my previous issue._**

**_after increasing size i am getting error after compiling all files._**

Linking build/CubeOrangePlus/bin/arducopter
common.ld:211 cannot move location counter backwards (from 0000000008200f80 to 0000000008200000)
collect2: error: ld returned 1 exit status

**_i have to debug the firmware but i could not able to do coz of this error._**

**Version**
_What version was the issue encountered with_
v4.4.4 copter

**Platform**
[  ] All
[  ] AntennaTracker
[ *] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
You ran out of flash. You will have to turn off some features to get it to fit. 

Same as: https://github.com/ArduPilot/ardupilot/issues/26731
