### ISSUE TITLE
Rover: SITL RTL_SPEED only allows 1m/s increments contrary to description

### ISSUE THREAD

**Issue by Kraligor** [ArduPilot/ardupilot#26995]
## Bug report

**Issue details**

Setting RTL_SPEED <1 will result in RTL_SPEED not being used at all. Setting RTL_SPEED to any float will result in the decimal places being ignored and only the integer-part being used (e.g. 0.9 will result in 0, 4.6 will result in 4).

This is contradictory to the description in Parameters.cpp:
```c++
// @Units: m/s
// @Range: 0 100
// @Increment: 0.1
```

**Version**
ArduRover V4.6.0-dev

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[x] Rover
[  ] Submarine

**Airframe type**
SITL
**Hardware type**
SITL

**Logs**
https://discuss.ardupilot.org/uploads/short-url/xgXJUfS4ldgNkxtRu4D4jsJzZ42.tlog
https://discuss.ardupilot.org/uploads/short-url/gksP74ZXbpDt6plsYPHjsrjEkbM.param

Associated forum thread: https://discuss.ardupilot.org/t/rover-rtl-speed-issue/117281

**Comment by rmackay9** [comment]
I've reproduced this issue in master and Rover-4.4 so this is really a bug.  This is very surprising and I don't immediately see the cause but clearly something is going wrong.

Thanks for finding this.
