### ISSUE TITLE
AP_Mount: add support for Siyi ZT6

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#27060]
Whenever Siyi releases a new model of camera we need to update two parts of the Siyi driver:

1. Add a new entry to [the HardwareModel enum](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_Siyi.h#L163)
2. Add a new entry to the [hardware_lookup_table](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_Siyi.cpp#L26) which maps the 2 byte hardware id provided by the gimbal itself to the model name displayed to the user
3. Update get_zoom_mult_max() with the maximum zoom level for the camera
4. Search for any other uses of "HardwareModel"

For reference these are the things we need to know about the camera:

1. 2 byte hardware id
2. model name
3. zoom max (e.g. 30x)
4. focal length in mm (e.g. 21, 5.15)
5. does it have a rangefinder?
6. does it have multiple lenses?

This request comes from [this discussion](https://discuss.ardupilot.org/t/gimbal-zoom-type-issue/117708)

**Comment by peterbarker** [comment]
Randy gave us support for this camera, closing this issue.
