### ISSUE TITLE
COPTER / KAKUTE F7 buzzer startup scream on kakute F7 

### ISSUE THREAD

**Issue by brocciu** [ArduPilot/ardupilot#27120]
I updated my quad with 4.4 then 4.5 but the buzzer don't stop screaming when the batterie is pluged. Probably the buzzer pin status in the bootloader.

**Comment by rmackay9** [comment]
Thanks for the report, I've added it to the Copter-4.5 issues list.

**Comment by brocciu** [comment]
I think it is solved. I reduced the size of my custom ardupilot build. I also added a few fonctionalities. I don't know what did the trick but everything is back to normal.
I have trouble with telemetry via CRSF and no more OSD but the rest is ok.

**Comment by F11ff** [comment]
embedded SIM" وهي عبارة عن رقاقة إلكترونية مضمنة داخل الجهاز تعمل ك

**Comment by rmackay9** [comment]
Hi @brocciu, ok, good news.  Thanks for the feedback and I've closed the issue.
