### ISSUE TITLE
ChibiOS: bi-directional dshot capable in iomcu-f103-dshot and iomcu-f103-8Mhz-dshot

### ISSUE THREAD

**Issue by burgeruser** [ArduPilot/ardupilot#27154]
Before:
![before](https://github.com/ArduPilot/ardupilot/assets/93718551/920496d3-ea11-4d6f-8d88-5a19ab86dc8d)

After I have changed:
[PR](https://github.com/ArduPilot/ardupilot/pull/27087)
![after](https://github.com/ArduPilot/ardupilot/assets/93718551/b3c2ce62-9b01-4c98-920f-7b5559e175a9)

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
There is a PR already,  better to track it in one place.
