### ISSUE TITLE
iomcu reset with bdshot on 6X

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#27171]
With a CUAV 6X with Pixhawk6X-bdshot firmware, with 6 blheli32 ESCs connected on a hexacopter (4 ESCs on main, 2 on aux) I get a reproducible internal error 0x1000 for IOMCU reset after arming. The copter still flies fine, but we need to find the cause of this.
Logs here:
https://drive.google.com/drive/folders/1fveumuzs7zw7zCqw7jKLHqiaXxx3k5nC?usp=drive_link
ping @andyp1per

**Comment by burgeruser** [comment]
I encountered a similar issue earlier, and my solution was either to exclusively use D-shot outputs from the IOMCU or have the MAINMCU handle all D-shot outputs. I frequently ran into error code 0x1000 back then.
