### ISSUE TITLE
MR72 Radar driver does not add obstacles to the OA database

### ISSUE THREAD

**Issue by Sekilsgs2** [ArduPilot/ardupilot#27216]
the driver is simply missing a line

// push to OA_DB
database_push(yaw, objects_dist);

please fix this.

**Comment by rmackay9** [comment]
I've added this to [the 4.5 issues list](https://github.com/ArduPilot/ardupilot/issues/26103).

@rishabsingh3003 are you happy to tackle this one?

**Comment by rmackay9** [comment]
@Sekilsgs2, thanks very much for finding this issue!

**Comment by rishabsingh3003** [comment]
I only tested the the sensor with Simple avoidance so I did not face this issue. 
This is my mistake and I will certainly fix it. Thanks, @Sekilsgs2 for finding it!

**Comment by peterbarker** [comment]
I've merged the fix for this; thanks for the report @Sekilsgs2 - and thanks for the fix, @rishabsingh3003 !
