### ISSUE TITLE
Problem with micro ros. (won't publish the topic).

### ISSUE THREAD

**Issue by AlexanderBVKtex** [ArduPilot/ardupilot#27314]
## Bug report

**Issue details**
When following the instructions ([ROS2 with sitl](https://ardupilot.org/dev/docs/ros2-sitl.html#ros-2-with-sitl)), micro ros does not publish the topic. This is due to the error "micro ros agent" appearing in the terminal.

**Version**
Ardupilot 4.5.4; Some previous versions do not have this problem

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**System**
Ubuntu 22.04 arm64
SITL with ROS2

**Logs**
[logs.txt](https://github.com/user-attachments/files/15859880/logs.txt)

**Comment by rmackay9** [comment]
FYI @Ryanf55 @srmainwaring

**Comment by rmackay9** [comment]
@AlexanderBVKtex,

Thanks for the report.  In general it is better to post in the support forums first and then after they've been confirmed as real bugs or enhancement requests we can add them here.

**Comment by Ryanf55** [comment]
The change was not backported to 4.5 to remove the refs file. I'm on vacation for the next two weeks, but in the mean time, please try removing that argument in your command.

**Comment by Ryanf55** [comment]
See https://github.com/ArduPilot/ardupilot/pull/27145

**Comment by rmackay9** [comment]
Great, I will go ahead and close this although we will still see replied. txs!
