### ISSUE TITLE
ArduPilot should flash green lights when AHRS-is-happy, *not* GPS-is-happy

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#27320]
## Feature request

**Is your feature request related to a problem? Please describe.**
The most visible sign that a Copter is ready to go is the flashing light.

Which is blue if you're good to arm but don't have a good GPS fix.

Which is flashing-green if you're good to arm and the GPS prearms are passing.

Just because your GPS prearms are passing doesn't mean that your vehicle knows where it is and has set its home location.

The latter would seem to be much more useful information than "have GPS lock".  It should reflect whether the vehicle can do waypoint navigation, not whether the GPS is talking to us and has a reasonable fix.

**Describe the solution you'd like**
Change the AP_Notify library's gps-checks-passing to ahrs-checks-passing-and-home-is-set.

**Describe alternatives you've considered**
None

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by okok125** [comment]
Thank You  Peter BarKer.

**Comment by rmackay9** [comment]
I'm pretty sure that for Copter, it needs to have a good position estimate for the LEDs to go green.  It's not just that it has good GPS signal.

**Comment by okok125** [comment]
This is the vedio that I wanna reflect. 
[https://youtu.be/UFu3tds1VjA](url)

**Comment by peterbarker** [comment]
> I'm pretty sure that for Copter, it needs to have a good position estimate for the LEDs to go green. It's not just that it has good GPS signal.

That depends on which mode you are in.

Try this experiment:
```
./Tools/autotest/sim_vehicle.py -v ArduCopter --rgbled --console
param set SIM_GPS_NUMSATS 3
reboot
```

The EKF will never be happy with less than 6 satellites, even if everything else looks good.  This is a reasonable simulation for someone starting up their vehicle in a marginal GPS environment - 'though the EKF would usually reject for poor GPS error estimates rather than number-of-sats with modern equipment.

Wait for the vehicle to stabilize.

Now flip between `LOITER` and `STABILIZE`.

In `STABILIZE` mode the lights will flash green (rapidly as they will have fix-type 6)
In `LOITER` mode the lights will flash yellow indicating a lack of lock.  Adding an enabled inclusion fence will do the same thing (make the lights flash yellow) as AHRS position is then required.

This also appears in the console:
![image](https://github.com/ArduPilot/ardupilot/assets/7077857/3f598d90-dea1-4403-be9d-f163a519f821)

... so in this state someone can boot in stabilize, see green lights, arm and fly - but their RTL function will definitely not work well for them!

BTW, I've just put into words/SITL-instructions what @okok125 showed in his video.  He's showing that to know whether it's "good" to take off he has to flip between the two modes.  Their customers aren't doing that and their vehicles are not always coming back....

Thus my suggestion that stabilize mode should not be flashing green.

**Comment by rmackay9** [comment]
@peterbarker,

Thanks for verifying.  I agree that a copter in stabilize mode should not show green LEDs unless it has a good position estimate.  My guess is that to fix this, we will need to pass a new flag into AP_Notify and use it to control the LED colour.  I don't think we will be able to fix this within the arming checks because the arming checks are actually fine as they are.
