### ISSUE TITLE
8266 based ELRS or mavesp8266 fails due to DEFAULTGPIO driving their TX lines low in bootloader

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#27360]
Within the last year many boards started using the DEFAULTGPIO.....LOW instruction in their bootloaders. Recently Andy Piper got reports that ELRS modules would not work with ArduPilot and has started adding commands on "likely" RCIN UART RX pins to pull high in the bootloader. Discussing with the ELRS devs, it seem that an ESP8266 will enter a hardware test mode that cannot be exited except by reboot if its UART TX is pulled low on power up. This means that if an ESP8266 is attached to an ArduPilot autopilot, either as a MAVESP telem wifi or ELRS, it will lock in a hardware selftest mode rendering it useable. 
Andy's solution is not really viable unless you pull ALL UART RX pins high or tristate during bootloader. This would be a massive code effort. Alternatively, we could remove all DEFAULTGPIO statements from the bootloader code....or change to tristate?
We need a viable solution...

Why hasn't this come up before? most ELRS are ESP32 based and don't have this issue and the MAVesp is not widely used either, but ELRS has been ported to R9 modules and others now and they are ESP8266 based, as I understand it...so just now starting to emerge

**Platform**
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by tridge** [comment]
as far as I can see there is only one board with a DEFAULTGPIO before the MCU statement in a hwdef-bl.dat, the BlitzF745AIO
@andyp1per I think this should be removed, so it is floating. I think we have to rely on the makers of the devices having a weak pullup so we should float
