### ISSUE TITLE
decompile the apj file

### ISSUE THREAD

**Issue by Mahdikh7** [ArduPilot/ardupilot#27420]
hi
Is it possible to decompile the apj file?
We had already done customization in the framework, but now we don't have access to our main codes b
Thank you for your guidance on how we can get from apj to c++ codes

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ * ] Plane
[  ] Rover
[  ] Submarine

**Comment by rmackay9** [comment]
Hi @Mahdikh7,

No, I'm afraid not.  It might be possible to find programs on the internet that turn the binary into C++ but it won't look anything like the original C++.
