### ISSUE TITLE
Copter: if SmartRTL is interrupted on its path home, it should restore the last waypoint it was heading to

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#27517]
When SmartRTL is on its way home, removes a point from the return path and gives it to the navigation controller.  The problem is that if the user switches out of SmartRTL to another mode, that point is not restored back onto the return path.  This means that it is lost and when the user switches back into SmartRTL again, it will skip that point

An extreme situation should be reproduce-able in SITL.  Fly a path in a manual-ish mode (like Loiter) with some noticeable corners.  Engage SmartRTL but then engage Brake mode soon after.  Repeat switching between SmartRTL and Brake and with each switch a point should be lost.  Eventually the vehicle should attempt to fly straight home (which is not good)

**Comment by rmackay9** [comment]
I believe I have a fix for this issue now https://github.com/ArduPilot/ardupilot/pull/27619

**Comment by peterbarker** [comment]
We've merged Randy's fix now.
