### ISSUE TITLE
Possible bug when handling HIL_GPS message?

### ISSUE THREAD

**Issue by matanj83** [ArduPilot/ardupilot#27707]
Why is the 'alt' field divided by 10 rather than by 1000? 
https://github.com/ArduPilot/ardupilot/blob/602f5bc61c260b11e8b61dcba68f4e898a54ee4f/libraries/AP_GPS/AP_GPS_MAV.cpp#L165

Shouldn't it be converted from [mm] to [m]?

**Comment by IamPete1** [comment]
Alt is stored in cm.
