### ISSUE TITLE
Copter 4.5.5 MiniPix BlueJay BLHeli_S DShot 600 timing 

### ISSUE THREAD

**Issue by ralphwu** [ArduPilot/ardupilot#27814]
## Bug report

**Issue details**

Motors not response in motor test

**Version**
4.5.5

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X

**Hardware type**
MiniPix BlueJay BLHeli_S

**Logs**
Not available

**Comment by peterbarker** [comment]
Have you raised this on the forums?  You are more likely to get help with this sort of issue over there.
