### ISSUE TITLE
Ardupilot 4.5.5 - Kamera Gimbal Display doesn´t work

### ISSUE THREAD

**Issue by HengisHorsa** [ArduPilot/ardupilot#27835]
## Bug report

Like in all versions after 4.2.3 the camera gimbal gui doesn´t work in 4.5.5. It was said that it should work otherwise it is a bug to be reported. 

_Please describe the problem_

![Screenshot 2024-08-14 093404](https://github.com/user-attachments/assets/9c26a13a-9cd1-40fe-92e3-412a5a217108)

4.5.5
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[x ] Copter
[x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
PX4 and C6

**Comment by rmackay9** [comment]
Thanks for the report.  This is a known issue with Mission Planner (not the flight code) so I will close this issue.
https://github.com/ArduPilot/MissionPlanner/issues/3049

Sorry to be strict but it's best to have the issue recorded in the most relevant part of the system
