### ISSUE TITLE
Navio RC_Input add S-Bus Support

### ISSUE THREAD

**Issue by jmachuca77** [ArduPilot/ardupilot#2795]
S-Bus input on the NAVIO board is not working. What is missing to add this support? I might be able to help out with this.

**Comment by lucasdemarchi** [comment]
@jmachuca77 navio uses the PCM hardware to get the time of the rise and fall edges of a single pin. I'm not sure how S-Bus works and if it can use only this information. Do you have the protocol explained somewhere?

Anyway, if you want to take a look, you will probably need to adapt these lines: 
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_HAL_Linux/RCInput_Navio.cpp#L492-L517

**Comment by lucasdemarchi** [comment]
@staroselskii any idea?

**Comment by staroselskii** [comment]
This is not relevant anymore as most of the users are now using Navio 2 either way.
