### ISSUE TITLE
no gps data

### ISSUE THREAD

**Issue by Andreipoe1** [ArduPilot/ardupilot#27976]
## Bug report

**Issue details**

I've tried connecting a 6C Mini autopilot to an M8N GPS module with a compass, but I'm not receiving any data. The status shows "GPS: No GPS," even though the GPS module is connected, blinking blue, and the compass is functioning properly.
**Version**
_What version was the issue encountered with_
Mission Panner 1.3.82
ArduPlane V4.5.5

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Pixhawk

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by amilcarlucas** [comment]
This is not a bug, this is a support question. Please post support questions in the forum
