### ISSUE TITLE
HIGHRES IMU MAVLink Message

### ISSUE THREAD

**Issue by KoehlerT** [ArduPilot/ardupilot#28082]
## Feature request

**Is your feature request related to a problem? Please describe.**

Multiple researchers and makers get frustrated with only getting rounded IMU data for applications like SLAM or trajectory reconstruction. Currently logfiles have to be downloaded from an SD Card and fed into scripts, retrieving the unrounded data.

**Describe the solution you'd like**

The MAVLink `HIGHRES_IMU` functionallity included in a **stable** release of ArduPilot.
Meaning the integration of Commits b159eccd260d612902552030f8a71ee25f25fd7d and 40314a551249cdc130527edff8369efdc3887854.

**Describe alternatives you've considered**
The alternatives are: Using `SCALED_IMU3`, or `RAW_IMU` MAVLink messages or retrieving the data from logs on a SD Card (offline).
Those are suboptimal, because the values are either rounded, uncalibrated or come with a lot of effort, respectively.

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
Legacy PR #24258 
Recent PR #27007 
Fix PR #28058 

This issue is meant for discussion and coordination of this effort.
I am open for implementing additional functionality when given clear directions on how to (I am new to ArduPilot development and the MAVLink Protocol)

**Comment by KanzJ** [comment]
Thank you for creating this issue. We are working with Ardupilot-based systems for remote sensing applications. Scaled/rounded IMU data does not work there as it is not precise enough...

The HIGHRES_IMU funcionality would help us a lot.

**Comment by tejalbarnwal** [comment]
> The HIGHRES_IMU funcionality would help us a lot.

I second this!

**Comment by IamPete1** [comment]
If I understand correctly the development branch already supports everything you need? We branch master for each new major release, 4.6 is not too far away.

**Comment by KoehlerT** [comment]
I misunderstood the process. Thought every release is from master 🥇
