### ISSUE TITLE
Can't set 100Hz for MAVLINK_MSG_ID_HIGHRES_IMU on Rover

### ISSUE THREAD

**Issue by lida2003** [ArduPilot/ardupilot#28101]
**Setup:**

- latest 4.6-dev
- 921600 (UAVT, MAVLinkv2)

same code from setting MAV_CMD_SET_MESSAGE_INTERVAL,MAVLINK_MSG_ID_HIGHRES_IMU to 100Hz, which is 10000 us.

**Result:**
- F435 Copter 100Hz OK
-  H743 Copter 100Hz/200Hz OK
- H743 Rover NG about 50Hz

PS: Previous discussion here[Can't set 100Hz for MAVLINK_MSG_ID_HIGHRES_IMU?
#4](https://github.com/chobitsfan/mavlink-udp-proxy/issues/4).

**Comment by stephendade** [comment]
Just a guess, but the loop rate in Rover ``SCHED_LOOP_RATE`` is 50 by default. Trying increasing this to 100 or 200.

**Comment by lida2003** [comment]
I successfully set 10Hz(actually 9Hz), 25Hz(actually 24Hz), 50Hz(actually 49~50Hz), but I can't set 40Hz, 100Hz, 200Hz.

But it works for copter code 4.6-dev(same git commit code). It might be copter handles this command different from rover. I'm NOT digging into the code right now. 

Just post this question here, maybe someone can take care of it when have time.

**Comment by stephendade** [comment]
Ok, I've done some digging and created a patch in #28144.

I've confirmed by initial guess that Ardupilot is indeed capping the message rate at ``SCHED_LOOP_RATE``. Try setting this parameter to 250Hz and try your message rates again.

**Comment by lida2003** [comment]
I'll do the test tomorrow and get back to you soon.

**Comment by stephendade** [comment]
> Is there any api for changing "SCHEDULER_LOOP_RATE"?

That's just an Ardupilot parameter that you can set via your GCS.

**Comment by lida2003** [comment]
Thanks.
![图片](https://github.com/user-attachments/assets/b2ac5b33-270e-4f61-b803-f1f41d6dc841)
