### ISSUE TITLE
Copter-4.6.0-dev: DroneCAN over MAVLink broken?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#28175]
Copter-4.6.0-dev seems to have broken something that causes MP's DroneCAN/UAV screen to be unable to communicate DroneCAN enabled devices (e.g. a Here4 GPS)

This is what MP's screen shows when Copter-4.6.0-dev (on a CubeOrange with Here4 GPS:
![image](https://github.com/user-attachments/assets/412b1acc-7a58-4af3-b3a7-47cb3a3ffea0)

This what it looks like using Copter-4.5.6.
![image](https://github.com/user-attachments/assets/b42bbe1a-e5e4-48ac-901d-67246620366b)

**Comment by robertlong13** [comment]
Problems occur with DroneCAN GUI Tool too.

Connect with mavcan over USB, autopilot shows up correctly.
![Screenshot 2024-09-21 111832](https://github.com/user-attachments/assets/b71a1a42-7f8e-41e7-9506-a97e16e9642f)

Switch to bus 2, all traffic disappears
![Screenshot 2024-09-21 111843](https://github.com/user-attachments/assets/835a20a3-11f7-42a4-a67e-7b3c20bf4884)

Switch back to bus 1, all traffic still gone
![Screenshot 2024-09-21 111858](https://github.com/user-attachments/assets/105d0088-a7d2-45f9-b338-47a97db58ca1)

This persists until you reboot the autopilot.

You can connect initially on bus 2, and get the correct traffic, but if you switch busses, it locks up until you reboot.
