### ISSUE TITLE
Copter will do RTL when landed

### ISSUE THREAD

**Issue by owenson** [ArduPilot/ardupilot#2819]
Hi

My TX wont let me set a failsafe level for throttle so I have the mode switch set to RTL when the receiver detects a lost signal.  Unfortunately, this has resulted in repeated injuries as I've landed the hex and then switched the TX off without disarming - it then attempts to take off often when I'm right up close.  

I don't know if being able to trigger RTL when landed is a necessity?

I appreciate the principle problem is my stupidity - but as it's happened so many times I wonder if it might be considered.

Many thanks
Gareth

**Comment by rmackay9** [comment]
I think it would be best to resolve the underlying issue which is that the failsafe is not setup in the recommended way.  Copter supports two types of radio failsafe, either the receiver can stop sending pwm signals or it can set the throttle level very low.  If the transmitter/receiver isn't capable of either of these methods then I think replacing it is the best solution.

Whether or not RTL should simply disarm if it's already landed is a good question.  Maybe this should be discussed on drones-discuss@googlegroups.com
