### ISSUE TITLE
Arduplane.elf problems with make in Windows

### ISSUE THREAD

**Issue by kah413** [ArduPilot/ardupilot#2821]
I run make sitl -j4 in the ArduPlane directory and get to the very end with an error of two unknown references to healthy (line 77) in AP_RPM.h.

**Comment by magicrub** [comment]
Does the usual SITL script work?

**Comment by kah413** [comment]
No it still fails at the previous mentioned line of code.

**Comment by kah413** [comment]
Also are you referring to the sim_vehicle script? If I run either of these this is the exact error I get.
 
![image](https://cloud.githubusercontent.com/assets/14191314/9778278/dd5e92d8-5733-11e5-8f57-287e84ac6438.png)

**Comment by magicrub** [comment]
Have you tried cleaning lately? Also, try updating your git submodules

**Comment by kah413** [comment]
I ran make clean in the ardupilot directory and a make px4-clean since those were the only files that showed updating. Still same error. Also I was using git submodule init. Downloaded it fresh on a different computer and am getting same error as well.

**Comment by ericjswenson15** [comment]
I'm getting the exact same error unfortunately:/

**Comment by rmackay9** [comment]
the -j4 option can't be used with windows I'm afraid.

**Comment by magicrub** [comment]
You can use -j when using the sim_vehicles.sh script, but I do it in a
virtual machine on my windows computer so maybe that's why it works.

I thought the -j parallel threads problem was related to nuttx, building
SITL slips that so there shouldn't be a problem even on windows.

**Comment by ericjswenson15** [comment]
I patched the problem by going into AP_RPM and forcing the function that has line 71 to return -1.

**Comment by WickedShell** [comment]
Unable to reproduce on master (as of a couple of months ago)
