### ISSUE TITLE
only 4 rc chan send via msp displayport telemetry

### ISSUE THREAD

**Issue by whoim2** [ArduPilot/ardupilot#28276]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

## Bug report

only 4 rc chan send via msp displayport telemetry

im connect logic to serial4 (tx3 pin) of matek h743 wing, serial4_proto: Displayport.
This data:

```
0x24
0x4D
0x3E
0x08 //len (4 * sizeof(uint16_t)
0x69 //MSP_CMD_RC 105
0x5B //ch1_lo
0x06 //ch1_ho
0x5E //ch2
0x06
0xB8 //ch3
  0x06
0xC6 //ch4
0x07
0x1B //crc
```
Only 4 ch of 16 in packet, where im may see another 10 channels?

**Version**
4.5 plane

**Platform**
[x] Plane

**Airframe type**
wing

**Hardware type**
matek h743 wing v3

**Logs**
[untitled.txt](https://github.com/user-attachments/files/17210964/untitled.txt)

**Comment by whoim2** [comment]
https://github.com/ArduPilot/ardupilot/blob/b73bef5b133fed8b480737f06555ee85607df088/libraries/AP_MSP/AP_MSP_Telem_Backend.cpp#L1068

Yes, only 4 channels..

**Comment by whoim2** [comment]
[AP_MSP_Telem_Backend.zip](https://github.com/user-attachments/files/17244512/AP_MSP_Telem_Backend.zip)

this fix

**Comment by xx3dge** [comment]
> [AP_MSP_Telem_Backend.zip](https://github.com/user-attachments/files/17244512/AP_MSP_Telem_Backend.zip)
> 
> this fix

How can I add this to arduplane 4.7  for a matwk h743 wing lite?this is  way over my head. I need channels 7 and 8 to run my zoom camera.
