### ISSUE TITLE
help to build custom board

### ISSUE THREAD

**Issue by Lynklee321** [ArduPilot/ardupilot#28304]
## Bug report
I try to build my h743 custom board but it can't config the gyro  MPU.

**Platform**
[  ] Copter

**Hardware type**
Weact H743 - MPU6500

[hwdef.txt](https://github.com/user-attachments/files/17259920/hwdef.txt)
[hwdef-bl.txt](https://github.com/user-attachments/files/17259921/hwdef-bl.txt)

**Comment by andyp1per** [comment]
I'm afraid we have many boards using these devices. We need to keep the issues list to actual issues so closing
