### ISSUE TITLE
Feature request: Support negative RPM for dynamic harmonic notch

### ISSUE THREAD

**Issue by RickReeser** [ArduPilot/ardupilot#28303]
Copter 4.5.6

Some specifications allow ESC telemetry to send negative RPM if the motor is spinning backwards (or just clockwise vs. counter-clockwise, as in my case), e.g. DroneCAN esc status message. RPM-tracking notches do not use negative RPM and they will just sit at the minimum frequency:
![image](https://github.com/user-attachments/assets/6e61ef29-186b-48c8-9359-bb7272332b6c)

Suggestion:
I suppose the naive solution of using the absolute value of RPM would suffice?

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Comment by andyp1per** [comment]
Certainly some judicious fabsf() would probably fix this and would be easy to do.

**Comment by andyp1per** [comment]
Please can you try

**Comment by RickReeser** [comment]
Yeah, I will look into it today. I don't have any familiarity with the filtering classes, but I suppose this will be a good introduction.

**Comment by andyp1per** [comment]
> Yeah, I will look into it today. I don't have any familiarity with the filtering classes, but I suppose this will be a good introduction.

Did you see the PR I did?

**Comment by RickReeser** [comment]
Nope, just saw it. Will try your PR now.
