### ISSUE TITLE
Plane doesn't fly forward on FWBW

### ISSUE THREAD

**Issue by IvanLeu** [ArduPilot/ardupilot#28388]
I ran into a problem, when on FWBW mode and when GPS isn't used, the plane starts to fly in the circle with huge radious. Seems like vibrations of the plane itself cause that effect or engine torque. Is there a way to fix this?

**Comment by Georacer** [comment]
Hello!

In theory FBWB should maintain at least heading. Can you provide a log where this happens? Even in a simulation environment.
