### ISSUE TITLE
NMEA-decode.lua example script does not work

### ISSUE THREAD

**Issue by BasvanH** [ArduPilot/ardupilot#28407]
## Bug report

Running the libraries/AP_Scripting/examples/NMEA-decode.lua LUA script on an OrangeCube gives errors and does not work.

```
15-10-2024 10:56:18 : .lua exc
15-10-2024 10:56:18 : PreArm: Scripting: /APM/scripts/Show_NMEA_Messages
15-10-2024 10:55:47 : .lua exc
15-10-2024 10:55:47 : PreArm: Scripting: /APM/scripts/Show_NMEA_Messages
15-10-2024 10:55:33 : time limit
15-10-2024 10:55:33 : Lua: /APM/scripts/Show_NMEA_Messages.lua exceeded 
15-10-2024 10:55:23 : time limit
15-10-2024 10:55:23 : Lua: /APM/scripts/Show_NMEA_Messages.lua exceeded 
15-10-2024 10:55:16 : .lua exc
15-10-2024 10:55:16 : PreArm: Scripting: /APM/scripts/Show_NMEA_Messages
```

**Version**
Ardurover V4.5.6

**Platform**
Rover

**Hardware type**
OrangeCube

SCR_HEAP_SIZE = 204800

**Comment by IamPete1** [comment]
Add a few zeros to `SCR_VM_I_COUNT` to increase the time limit. The script is expecting quite slow data rates, so it can timeout if there is too much. You could also try decreasing the callback time here:
https://github.com/ArduPilot/ardupilot/blob/81768b26ff447c7a8684c75f03fe6db941846b92/libraries/AP_Scripting/examples/NMEA-decode.lua#L113

EG:
`return update 10`
