### ISSUE TITLE
arm motor the log will cause the main thread to stuck

### ISSUE THREAD

**Issue by UAVcihang** [ArduPilot/ardupilot#28445]

**Comment by IamPete1** [comment]
Please re-open with more information. Which version of ArduPilot? Which flight controller? Does it happen all the time or just once?

**Comment by UAVcihang** [comment]
copter-4.0.7 ，F4,Unlocking the drone for the first time

**Comment by IamPete1** [comment]
> copter-4.0.7

Please update to the latest table release (4.5.7) and re-test.
