### ISSUE TITLE
ROS2 and Gazebo Frame odom doesn't exist iris model

### ISSUE THREAD

**Issue by RoyAmoyal** [ArduPilot/ardupilot#28511]
I followed the installation guide for ROS2 along with SITL and Gazebo from the ArduPilot documentation [here](https://ardupilot.org/dev/docs/ros.html). After running the command:

`ros2 launch ardupilot_gz_bringup iris_runway.launch.py
`everything seems to work fine initially. However, I am encountering some issues, as shown in the attached screenshot.
![Screenshot from 2024-10-31 18-40-36](https://github.com/user-attachments/assets/ca550dcd-2059-4cae-85c5-148dd2fc785d)

In the terminal, I see the following warnings:
```

[ruby $(which gz) sim-1] Msg [NameManager::issueNewName] (Skeleton::BodyNode | iris::iris_with_standoffs) The name [base_link] is a duplicate, so it has been renamed to [base_link(1)]
[ruby $(which gz) sim-1] Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | iris::iris_with_standoffs) The name [base_link:base_collision] is a duplicate, so it has been renamed to [base_link:base_collision(1)]
```

When I run 'ros2 launch ardupilot_gz_bringup iris_maze.launch.py ' I get the next error:
![image](https://github.com/user-attachments/assets/51cb80c0-240c-4e07-bfc4-d33a11d07cc9)

I am using Ubuntu 22.04 and ROS Humble.

Could you please provide guidance on this issue? Thank you!

**Comment by Ryanf55** [comment]
Duplicates the same bug on the correct repo:
https://github.com/ArduPilot/ardupilot_gz/issues/60
