### ISSUE TITLE
HERE4FC: It functions as a GNSS receiver.

### ISSUE THREAD

**Issue by muramura** [ArduPilot/ardupilot#28519]
## Feature request

**Is your feature request related to a problem? Please describe.**

When HERE4 is used as a flight controller, it does not become a GNSS receiver.
To make it a GNSS receiver, rewrite the firmware.

**Describe the solution you'd like**

I want to use it as a GNSS receiver without rewriting the firmware.

**Describe alternatives you've considered**

I inform FC of the telemetry message “GPS_INPUT” used by the GPS MAVLINK driver.

https://mavlink.io/en/messages/common.html#GPS_INPUT

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

**Comment by rmackay9** [comment]
Can I ask why would you want the Here4FC to act as both an autopilot and as a GPS for another autopilot?

**Comment by muramura** [comment]
@rmackay9 san.
I find it tedious to convert the HERE4 flight controller into a GNSS receiver by rewriting the firmware, and I would like to simplify this process.

Additionally, I believe it is possible to transmit telemetry from other sensors, such as the barometric sensor, to the MAVLink barometric sensor driver in a similar manner.

**Comment by peterbarker** [comment]
GPS_INPUT is probably the wrong way to go about this.

Having the vehicle firmware emit (and consume) all the same DroneCAN messages as the AP_Periph firmware is probably the correct way to do this.  That's not just GPS data, BTW - there are magnetometers and baros and whatnot too.

**Comment by rmackay9** [comment]
We already have the ability to output NMEA from an autopilot (see https://ardupilot.org/copter/docs/common-serial-options.html) so I guess this request could be that we output DroneCAN or MAVLink.

It's a bit hard to justify the development effort to do this just to save flashing time for the user so I think I will go ahead and close this, sorry!

If the request was that AP simulate an ExternalAHRS (like a VectorNav) then I'd totally support that but this is a little different
