### ISSUE TITLE
AC3.3 RC10 disarming issue with lidar lite V2

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#2853]
Hello,

Lidar lite V2 works well with AC3.3 in I2C. (no freez, and no bad values)

But we need to disable prearm check to be able to arm drone with it. In my drone lidar lite v2 is at 20cm from ground.

Also, manual disarm after landing and auto disarm (rtl) no work..drone make bumppy throttle and disarm after 30 second or even no disarm and make jump and roll braking it's props....

Is this is due to min sonar range param? it's possible to skirt this issue by setting offset alt?

also there is there trigonometric correction to alt from lidar lite regarding lean angle from drone?

**Comment by Naterater** [comment]
@roque-canales, I think you may have much better luck with those questions at discuss.ardupilot.org.

As far as the disarming issue, I'm confident that this is no longer the case as of Plane 3.9.
