### ISSUE TITLE
There is a fatal bug in task scheduling

### ISSUE THREAD

**Issue by UAVcihang** [ArduPilot/ardupilot#28579]
![1731309927894](https://github.com/user-attachments/assets/a5995c81-c231-41c3-ba70-54c5a433087d)

As long as one task list times out, the order of other tasks cannot be guaranteed. This is a false design and should be designed so that each task is independent. It is recommended to cancel this task list and replace it with a timer task

**Comment by rmackay9** [comment]
Hi @UAVcihang,

I don't think this is a problem in practice.  The scheduler does not guarantee that all tasks will complete in a single loop.  Instead if a single task consumes all the time then the next loop, the remaining tasks will be run.

Of course, if you add very slow tasks into the scheduler then the vehicle will perform badly but the we also have higher level checks to warn the user if the main loop is not running at the desired rate.

I think I will close this but I'll see replies as will other developers.

Also if you can show that the scheduler is not performing as desired we can re-open the issue
