### ISSUE TITLE
LOG_REPLAY creating 100+ cores

### ISSUE THREAD

**Issue by h4writer** [ArduPilot/ardupilot#28586]
## Bug report

**Issue details**

I created a log with LOG_REPLAY=1 and LOG_DISARMED=2 in order to better understand an issue I'm seeing. I hoped to be able to play with the code of EKF3 a bit. 

I've run "build/sitl/tool/Replay xxx.bin" which did work.

Now when looking at the log (using APM Planner, sorry oldschool) I see (C:0-102):
![image](https://github.com/user-attachments/assets/6cbb3bac-e896-424f-add2-a48652ee973a)

When reading the documentation I should only have C:0,1,2 and C:100,101,102

A second thing that seems odd, is the fact that C:0,1,2 should just be the original numbers? If I understand correctly. But when I look at the values I see the values jumping between values. Which the original bin file doesn't do.

![image](https://github.com/user-attachments/assets/14c43243-abef-47e6-b8d5-95b331d4062b)

**Version**
Bin has been created with ardupilot4.4.4
Tried replay on 4.4.4 and 4.5.7, both gave this issue.

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quadcopter

**Hardware type**
Cube orange

**Logs**
https://www.dropbox.com/scl/fi/x12kgwk3c3nlegpcx5ox8/24-11-08_13-15-02_1.bin?rlkey=dfp0v671n6jny4yerh5kyncw1&st=gg2ewjti&dl=0

**Comment by Georacer** [comment]
Hello!

Perhaps you uploaded the wrong log?
When I open this one I see only 3 cores: 
![image](https://github.com/user-attachments/assets/68c30583-696e-42e5-90e3-71faa4415101)

**Comment by h4writer** [comment]
The log I uploaded, is the input to the replay.

This is the output after running it through Replay:
https://www.dropbox.com/scl/fi/aoavck3nfyoawcpslz9oy/00000001.BIN?rlkey=4zbpxtalspb4iuxd4ij3pxwob&st=6bj85xfv&dl=0

**Comment by Georacer** [comment]
It's probably a bug with APM Planner.

I'm seeing the correct cores with PlotJuggler:
![image](https://github.com/user-attachments/assets/1bb4e9e0-bfb6-4224-936f-500e353caf44)

**Comment by h4writer** [comment]
Thanks for the plug to PlotJuggler. In PlotJuggler I also see the correct data!
