### ISSUE TITLE
Copter: add passthrough of channel 6 to any output channel

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#286]
For ppm users who cannot connect their external device directly to the receiver, an direct pass through from ch6 to any output channel would be useful.

Device for which this would be useful include the Boscam HD19 which takes a pwm input.
http://www.boscamhobby.com/hd19.html

**Comment by R-Lefebvre** [comment]
Ties in with Input Manager

**Comment by auturgy** [comment]
@rmackay9 @OXINARF suggest close against AC3.5

**Comment by OXINARF** [comment]
Yes, this can now be done with SERVOx_FUNCTION. Thanks @auturgy!
