### ISSUE TITLE
Fences ignored despite being enabled

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot#28666]
## Bug report

**Issue details**

FENCE_ENABLE = 1
The plane is flying in TAKEOFF mode.
The plane is breaching the fence every rotation.
There is no indication in MAVProxy the fence is being breached.
MAVProxy shows `FEN` in gray, which I thought meant disabled.

**Version**
`master` today, hash f08a2120a8ce990e3939496dbe50ea1d4cae9fcb
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
SITL

**Hardware type**
N/A
**Logs**

[logs.zip](https://github.com/user-attachments/files/17795178/logs.zip)
[fence-items.txt](https://github.com/user-attachments/files/17795183/fence-items.txt)

I found this trying to test the vehicle behavior with a non-[simple](https://en.wikipedia.org/wiki/Simple_polygon) polygon fence. 

**Screenshot**
![image](https://github.com/user-attachments/assets/eee3ad16-8520-4f87-9005-4d680f2f2d7e)

**Comment by Ryanf55** [comment]
I've reproduced this with a simple polygon (square) fence. 
![image](https://github.com/user-attachments/assets/5bfc8517-9230-4c8d-8479-40c9b907cea1)


From peter barker: `Not yet AFAIK.  It may even be two issues; in my case it might be a change in the edge-triggering of the RC fence switch.  In tridge's case it might be FENCE_AUTOENABLE not working.  In any case - not a <#715368769983348806> issue 🙂`

**Comment by tridge** [comment]
@Ryanf55 in your screenshot fence is disabled:
![image](https://github.com/user-attachments/assets/0ec006ff-6a26-466a-80bc-a2b39efdfeff)

**Comment by Ryanf55** [comment]
> @Ryanf55 in your screenshot fence is disabled: ![image](https://private-user-images.githubusercontent.com/831867/387144205-0ec006ff-6a26-466a-80bc-a2b39efdfeff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDgwODYsIm5iZiI6MTczMTk0Nzc4NiwicGF0aCI6Ii84MzE4NjcvMzg3MTQ0MjA1LTBlYzAwNmZmLTZhMjYtNDY2YS04MGJjLWEyYjM5ZWZkZmVmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNjM2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzhkOTk2YmE3NGVkODE5ZGRkZmJjZGZmYTQzZDA3MDVkMmY3YzYzYzFkNDU5ZTc2N2M3N2FhYTFiY2M4YWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n7g5KR1NwAyfR1iAoxM1WDzdCetGppDC2s42nEv5u44)

Yes, but the parameter says it's enabled. It's conflicting info.

**Comment by Ryanf55** [comment]
I can't reproduce this despite numerous attempts on the same hash with both inclusion and exclusion fences. 

I have found plenty of other fence issues, but not this specific one.
