### ISSUE TITLE
Wrong SIM_PLD_xxx_LIMIT parameter names

### ISSUE THREAD

**Issue by shalomcrown** [ArduPilot/ardupilot#28697]
## Bug report

**Issue details**
In SITL, Copter-4.5.7:

SIM_PLD_DIST_LIMIT and SIM_PLD_ALT_LIMIT  are spelled incorrectly in the documentation, they should be SIM_PLD_ALT_LMT and SIM_PLD_DIST_LMT respectively (without the 'I').

**Version**
4.5.7

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X

**Hardware type**
SITL

**Comment by amilcarlucas** [comment]
Merged
