### ISSUE TITLE
Changing SIM_IMU_POS_X/Y causes the Copter to deviate from its original flight path during turns and crash

### ISSUE THREAD

**Issue by wyunc** [ArduPilot/ardupilot#28720]
## Bug report

**Issue details**

When I set up a rectangular flight mission and set SIM_IMU_POS_X to 50, I noticed that at the corners of the rectangle, the drone suddenly switched to Land mode, significantly deviated from the flight path, and ultimately crashed. (Reproduction: `param set SIM_IMU_POS_X 50`)

As shown in the figure below, while flying along the vertical yellow flight path to a waypoint and making a right-angle turn, the drone was expected to continue flying leftwards. However, it actually deviated towards the bottom-right of the map (creating an arc in the air).
![2-1fly](https://github.com/user-attachments/assets/4cad2116-e908-43bd-9825-89161c6b3a7c)
![2-2bugoccur](https://github.com/user-attachments/assets/29638722-f1d4-41c4-9be2-9905e7de1f76)

In the end, it significantly deviated from the original flight path and crashed.
![2-3hitground](https://github.com/user-attachments/assets/2cc5003b-3421-4579-8bac-bd51e2814617)

Similarly, we wondered if the same issue would occur with SIM_IMU_POS_Y. We found that when SIM_IMU_POS_Y was set to 50, the drone also deviated towards the bottom-left of the map during right-angle turns.
![1bugoccur](https://github.com/user-attachments/assets/a6f6b611-c4bc-4c98-a46d-050b192cd03b)
![1hitground](https://github.com/user-attachments/assets/be5ce406-94d9-4f20-a5a2-7e6b555cfcc7)

I am unsure whether this is a bug or an issue with my settings. I am more inclined to believe this is a bug because there is no [documentation](https://ardupilot.org/copter/docs/parameters.html#sim-imu-pos-x-imu-offsets) imposing restrictions on these parameters.

**Version**
4.6.0

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
SITL

**Logs**
[hitground.zip](https://github.com/user-attachments/files/17892762/hitground.zip)

**Comment by wyunc** [comment]
Additionally, when SIM_IMU_POS_Z is set to 50, the drone suddenly disconnects just before reaching a turning point, and its position on the map stops updating. This behavior is entirely different from the effects of X/Y, so I believe this might be another type of bug?
![2bug](https://github.com/user-attachments/assets/aceb37d6-6a9f-47c3-9be5-63c092924b59)

**Comment by IamPete1** [comment]
I don't think its reasonable to expect AP to work with a 50 meter IMU offset. Try 5 meters or less.

**Comment by wyunc** [comment]
Hi @IamPete1,
I set SIM_IMU_POS_X = 5 and found that the issue still exists. The degree of deviation becomes smaller, but the drone still ends up hit the ground. However, when SIM_IMU_POS_X is set to 1, the issue no longer occurs, although there is still some deviation from the flight path.
![3-changeX5](https://github.com/user-attachments/assets/d79238f1-8110-4bfa-80c4-bea3e5308b32)
![3-changeX5hitground](https://github.com/user-attachments/assets/3ba98a54-4048-4dbe-b7f6-6ba68b958d9d)

**Comment by IamPete1** [comment]
Did you also set INS_POS1_X, INS_POS2_X, INS_POS3_X? See:
https://ardupilot.org/plane/docs/common-sensor-offset-compensation.html

**Comment by wyunc** [comment]
> Did you also set INS_POS1_X, INS_POS2_X, INS_POS3_X? See: https://ardupilot.org/plane/docs/common-sensor-offset-compensation.html

No, their values are all 0. The only parameter I changed was SIM_IMU_POS_X/Y/Z; all other parameters remain at their default values. You can find the log data for both(SIM_IMU_POS_X=50 and SIM_IMU_POS_Y=50) scenarios in the hitground.zip file I provided.

**Comment by IamPete1** [comment]
If you have a 5 meter position offset and you don't tell AP about it I think that is a miss configuration. Hopefully that will fix it.

**Comment by rmackay9** [comment]
Thanks for the report.

I'm going to go ahead and close this because it's really a developer support issue and we just need to try and keep our to-do list (which is what the issues list is) free of support calls.  We will still see replies though.  Txs again for using AP!

**Comment by rmackay9** [comment]
Hi @wyunc,

I think it's best to do testing in "master" which is now 4.7.0-dev because this is the active branch and is where any bugs would be fixed first.  Normally any fixes are applied to "master" and then back-ported to the latest beta or stable branch.

**Comment by wyunc** [comment]
> Hi @wyunc,
> 
> I think it's best to do testing in "master" which is now 4.7.0-dev because this is the active branch and is where any bugs would be fixed first. Normally any fixes are applied to "master" and then back-ported to the latest beta or stable branch.

Got it, thanks a lot!
