### ISSUE TITLE
undefined reference to "XGBoosterCreate".

### ISSUE THREAD

**Issue by XuYiZh** [ArduPilot/ardupilot#28741]
i am trying to use **xgboost** in a c++file. i also add **CXXFLAGS+=[ "-I/xgboost/include","-L/xgboost/lib",'-lxgboost']** in wscript . but when run with **./Tools/autotest/sim_vehicle.py -v ArduCopter --console --map**,it still run error .undefined reference to "XGBoosterCreate".
anyone meet the same question ?
i want to ask for a solution,thank you very much!

**Comment by Ryanf55** [comment]
We don't yet support linking Ardupilot to external libraries like this. Sorry!

**Comment by peterbarker** [comment]
`boost` isn't going to work on embedded.

As @Ryanf55 says - sorry, we don't support this sort of thing.

Closing this one now.
