### ISSUE TITLE
Format Position in JSON simulation of SITL

### ISSUE THREAD

**Issue by Saleh-At** [ArduPilot/ardupilot#28784]
How to convert LLA (lat lon alt) to `position (north, east, down) (m) earth frame` for [JSON](https://github.com/ArduPilot/ardupilot/tree/master/libraries/SITL/examples/JSON)

I'd like use LLA as (deg deg meter) in FDM and send to ardupilot.

Or I must to convert first position as home to ECEF and new position to another ECEF and with different of two points to NED?!!

**Platform**
[ * ] All
[  ] AntennaTracker
[  ] Copter
[ ] Plane
[ ] Rover
[ *] Submarine

**Comment by khancyr** [comment]
Not a bug. Please use discuss. Thanks
