### ISSUE TITLE
Copter: AutoTune produces ridiculously small ACCEL_MAX values

### ISSUE THREAD

**Issue by mbuzdalov** [ArduPilot/ardupilot#28799]
## Bug report

**Issue details**

In my 2" whoop-sized quad, running AutoTune produces nice enough rate and angle PIDs, but too small maximum accelerations.

Example: `ATC_ANG_RLL_P` of 25+, but `ATC_ACCEL_R_MAX` of around 1000, written as 4000 because it was clamped from below.

These values are not safe to fly.

**Version**

GitHub master, commit 3ed6ada2e316c52ee9ebae4202c99c681e891693.

**Platform**
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

Quadcopter.

**Hardware type**

FlywooF405S-AIO

**Logs**

Two logs are attached, for roll and yaw. They are filtered to 5Hz because the flash chip is very small, but should likely be enough for analysis.

[24-12-03_22-19-27_roll.bin.gz](https://github.com/user-attachments/files/18000663/24-12-03_22-19-27_roll.bin.gz)
[24-12-03_22-56-20_yaw.bin.gz](https://github.com/user-attachments/files/18000664/24-12-03_22-56-20_yaw.bin.gz)

**Comment by tpwrules** [comment]
This is reproducible in SITL, on 4.5 `ATC_ACCEL_(R|P)_MAX` are around 500k but on master they are 20k.

**Comment by mbuzdalov** [comment]
#28800 fixes this issue nicely.
