### ISSUE TITLE
rc input not working

### ISSUE THREAD

**Issue by Lalbabu2001** [ArduPilot/ardupilot#28928]
## Bug report

**Issue details**
rc PPM input on foxeer f405 v2 flight controller is not working 
However sbus is working.
_Please describe the problem_
the ardupilot page for the same flight controller says that the ppm and sbus will not work , however sbus is working fine , whereas ppm is not working the mission planner the parameter rc_protocols has options for ppm as well then why ppm is not working?
**Version**
_What version was the issue encountered with_

**Platform**
[  y] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by andyp1per** [comment]
PPM is not supported, only serial input is supported. You would need a different hwdef to support PPM.
