### ISSUE TITLE
Stabilize_Init() is not run on start-up.

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#2899]
Since the flight mode initializes as Stabilize, and the mode Init() functions are only run when processing a mode change, if a system boots up in Stabilize mode it will not run the stabilize_init() function, possible missing important functionality, (but there is no real problem now).

**Comment by rmackay9** [comment]
bumping to Copter-3.5.

**Comment by shinjanxp** [comment]
@rmackay9 @peterbarker I would like to take up this issue. Could you please refer to which files I should look at to solve this? Thank You.

**Comment by peterbarker** [comment]
ArduCopters system.cpp in `init_ardupilot()`.  It may be as simple as a call to `flightmode->enter()` - but it needs to be tested!

If you don't have a SITL environment yet - get one :-)

**Comment by rmackay9** [comment]
I think @tridge's idea is good and it also consistent with how Rover does it.. and growing consistency between the vehicles is great for us all

**Comment by int-smart** [comment]
Hi
I created a Pull request after making the changes and successfully building and testing it for the different plarforms. Here is the pull request number "ArduCopter: Changed the ArduCopter code to include INITIALISING mode …" #9633. Let me know if any changes have to be made.

**Comment by peterbarker** [comment]
https://github.com/ArduPilot/ardupilot/pull/15706/files means we now run the relevant init code
