### ISSUE TITLE
DO_LOITER_TO_ALT not radius not implemented

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#2905]
https://pixhawk.ethz.ch/mavlink/

specifies that param1 decides if exit only when heading is toward next WP,   param2 is radius and direction.

Arduplane uses param1 for direction, and ignores wp2.

**Comment by Naterater** [comment]
Is this still a problem @AndKe?

**Comment by WickedShell** [comment]
Loiter to alt has radius (rounded to 1 meter resolution), loiter time does not have radius support (just direction) different issue though.
