### ISSUE TITLE
INS_USEx=0 paramaters not working correctly

### ISSUE THREAD

**Issue by N-Z-N** [ArduPilot/ardupilot#2918]
v3.3.rc12 using Gyro2 as an example.
Tested on Pixhawk with faultily Gyro2.
Gyro2 show's wild values, that jump in large increments.

Set INS_USE2=0, is suppose to completely disable the number 2 gyro.
This only partly works.
Upon initial boot of Pixhawk, the gyro values are still taken into calculations.
The result is Gyro and EKF errors.
The HUD also goes wild, showing massive movements in all directions.

Only resolution is to reboot Pixhawk several times until gyro shows stable.

**Comment by peterbarker** [comment]
Modern ArduPilot has no problem working around faulty gyros.

No response from original submitter, closing this one.
