### ISSUE TITLE
consolidate sonar health checks between plane and copter

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#2944]
Copter makes the sonar healthy when the reported range is between MIN and MAX*0.6.
Plane uses a check that the reported range has changed by 5%.
https://github.com/diydrones/ardupilot/blob/master/ArduPlane/altitude.cpp#L566

**Comment by magicrub** [comment]
Plane also has a count (SONR.cnt) that checks for 10 good samples

**Comment by rmackay9** [comment]
ok.  Copter requires just 3 good samples.. so more room for convergence.

**Comment by IamPete1** [comment]
I suspect this problem has been solved, in any case this issue is so out of date I'm going to close.
