### ISSUE TITLE
EKF pre-arm checks should be moved to AP_Arming library

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#2957]
GPS pre-arm checks were extended in the EKF as part of this PR.  We should move these into the AP_Arming library.

https://github.com/diydrones/ardupilot/pull/2884

**Comment by rmackay9** [comment]
Sadly we need to bump this to AC3.5.

**Comment by WickedShell** [comment]
@rmackay9 is this done now that copter is using AP_Arming?

**Comment by peterbarker** [comment]
These checks are being done in modern ArduCopter.  Please reopen if I'm wrong.
