### ISSUE TITLE
Copter: ch7/ch8 save-wp feature deletes waypoints if held in on position for x-seconds

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#298]
short CH8 pulse : save waypoint
long CH8 pulse (more than 3,10 or 15 seconds) : waypoint list erase

**Comment by Naterater** [comment]
Is this still wanted... almost 6 years later? haha

**Comment by rmackay9** [comment]
I'm not a fan of this suggestion actually because we support far more auxiliary switches now so we can have a separate switch to clear the list rather than overloading a single switch.. let's close this..
