### ISSUE TITLE
Antenna Tracker for APM/Pixhawk

### ISSUE THREAD

**Issue by artemen** [ArduPilot/ardupilot#2998]
Continuous Pan Servos are expensive, however almost ANY regular servo can be EASILY, WITHOUT soldering gun/ programmer modified for continuous rotation use. Please, add such support at least for APM/Pixhawk based tracker. 
https://www.youtube.com/watch?v=XUm2nj7te8E

**Comment by earsneyes** [comment]
Continuous Rotation Servos are already supported in the last version but Manual mode doesn't work with CR servos it think. 

Look for the SERVO_TYPE parameter.

0=Position - traditional standard servo
1=OnOff 
2=ContinuousRotation

**Comment by artemen** [comment]
Well, in the sense of ability to cotrol those servos -yes, but yaw is still limited to 360 degrees by the YAW_RANGE max value 360.

**Comment by Naterater** [comment]
Continuous servos have been available for antenna tracker for a few years now.
