### ISSUE TITLE
Rover should be able to learn both speed and position when learning waypoints

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#30]
Should add LEARN_WP_SPEED boolean option

**Comment by gmorph** [comment]
I believe this feature means when learning waypoints we also want to record the speed.  Not sure why we would record the position as this will already be recorded by the learning of the waypoint.  Assigning to myself for actioning.

**Comment by rmackay9** [comment]
is it OK if I close this?  Rover-3.2 (and higher) allows learning the cruise speed and cruise throttle with the ch7 switch.  Its also documented on the wiki.

Actually i think I'll close this so I dont forget but we can re-open if people object.
