### ISSUE TITLE
DataFlash_File::find_first_log incorrect

### ISSUE THREAD

**Issue by jschall** [ArduPilot/ardupilot#3009]
I'm pretty sure the patch to ensure 10% free space on the SD card is buggy - at least, find_first_log should probably start at lastlog+1 and increment until it finds the first log, looping around at 500.

**Comment by OXINARF** [comment]
@jschall Is this still valid?

@peterbarker What's your input here?

**Comment by peterbarker** [comment]
Looks like it was addressed with e481497574806636269b98d11d9daaf04131534b

Belated thanks to @jschall for reporting the problem!
