### ISSUE TITLE
Rover: Steering mode problems

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#3034]
Numerous users have reported issues with Steering mode.  See here for an example.
http://ardupilot.com/forum/viewtopic.php?f=112&t=13983
I need to sort this out.
Thanks, Grant.

**Comment by OXINARF** [comment]
@gmorph This is quite old and very unspecific. Should it stay open?

**Comment by gmorph** [comment]
As part of the latest Rover work Steering mode is undergoing a lot of testing so I will close this and create a new one later if Steering is still sub optimal.
