### ISSUE TITLE
Rover: MIssion reset doesn't appear to be working correctly

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#3035]
I have had 2 reports of the mission resetting not working correctly in Rover.  See here:
http://diydrones.com/group/ardurover-user-group/forum/topic/show?id=705844%3ATopic%3A1931044&xg_source=msg
https://github.com/DroidPlanner/Tower/issues/1434
I need to investigate.
Thanks, Grant.

**Comment by khancyr** [comment]
It has been solve with https://github.com/ArduPilot/ardupilot/pull/5739
