### ISSUE TITLE
If source is checked out only one level deep build fails

### ISSUE THREAD

**Issue by anathan** [ArduPilot/ardupilot#3038]
Build Environment: Windows 10 x64 - PX4 Console (Msys)

Repro: Checkout (master) to /c/repo/ardupilot
cd /c/repo/ardupilot/Arducopter
make px4-v2

observe: Make/Sh.exe terminate and dump stacktrace after errors printed about finding nuttx config tool.

Take the exact same repo, move it to /c/repo/test/ardupilot and run the same commands, builds fine.

**Comment by rmackay9** [comment]
Not sure what the issue is but it could be that the directory capitalisation is incorrect.
Perhaps it should be ArduCopter instead of Arducopter.

**Comment by magicrub** [comment]
If you're playing musical directories you should do a clean.

**Comment by WickedShell** [comment]
This is a support issue, and best handled on https://discuss.ardupilot.org (although I believe the capitalization issue probably is the cause)
