### ISSUE TITLE
Copter: add set-mode reason code

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#3052]
Each caller to set-mode should provide a reason code.  These reasons would include:
1. set by pilot via RC
2. set by pilot via GCS
3. set by battery failsafe
4. set by gps failsafe

This would allow us some additional complexity in failsafe logic such as checking whether the user has overriden/cancelled the failsafe by changing modes.

**Comment by R-Lefebvre** [comment]
Great idea.

**Comment by R-Lefebvre** [comment]
Would the reason code be stored permanently, so we can always make intelligent decisions in the future based on who/why the vehicle is in the current mode?

I wonder if current mode, and current reason, should be stored as arrays that keep on being bumped back, so we could maintain a history of modes and reasons, and really make intelligent decisions? (ie: we have a battery failsafe event, but every time we do the user switches to manual control, we should stop doing failsafes.)  Something like that.

**Comment by rmackay9** [comment]
this is in master now.
