### ISSUE TITLE
RNGFND_PIN documentation does not document pin 14

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#3085]
For analog connections it we often recommend using 2nd pin of ADC connector. This corresponds to RNGFND_PIN=14. However this is [not documented](http://copter.ardupilot.com/wiki/arducopter-parameters/#rangefinder_pin_rngfnd_pin).

**Comment by peterbarker** [comment]
Documented here: https://ardupilot.org/copter/docs/common-rangefinder-maxbotix-analog.html
