### ISSUE TITLE
Power module voltage readings on Pixhawk with USB incorrect  Arducopter 3.3

### ISSUE THREAD

**Issue by JSGordon** [ArduPilot/ardupilot#3093]
USB voltage reading problem reported by several

My testing 
Setup Pixhawk with stable 3.3 release. X hexacopter, APM battery monitor using only monitor not BEC portion, Castle 50 lite escs
Pixhawk connected to PC via USB initially then battery is connected. The battery monitor measures voltage correctly.  Leaving it on for extended periods of time voltage monitoring remains correct. About 25.2 currently and verified externally
If I press safety switch to arm escs the voltage immediately starts to drop down to about 21 V and will stay at this point.  Voltage verified to Still be 25.2.
If I disarm the safety switch measured voltage stays the same at about 21V.
If I disconnect the battery and reconnect at this point the voltage returns to actual 25.2 until the safety switch is armed.
If the copter is powered by battery first then connected to the PC via USB the voltage reads 21. But if unplugged and plugged back in the voltage reads correctly.
This is repeatable.  
Changing Voltage monitor does not change results.
I have not encountered this before but perhaps someone has had a similar experience.  I don't think there is any electrical change in voltages supplied between the two states of voltage measurement so I am leaning to a software/firmware issue. I have reloaded firmware with no change in behavior. 
Immediate solution for proper voltage feedback during flight is to calibrate the battery monitor after arming the Safety Switch.
This seems to work but the root issue still needs remedying as this may cause some premature low voltage failsafe if they calibrate on USB before arming with safety switch.

**Comment by WickedShell** [comment]
This is a stale support issue. The only explanations I can come up with are all hardware/powering issues. For more support please go to discuss.ardupilot.org.
