### ISSUE TITLE
Add support  for monitoring voltage and current of multiple batteries

### ISSUE THREAD

**Issue by nenadvi** [ArduPilot/ardupilot#310]
Hi
It will be fine that APM 2.5 have support  for multiple batteries.
and getting it over MAVLink 

Nenad vi

**Comment by rmackay9** [comment]
This is in AC3.3 (fast CPU boards only) except that we don't send the current for the 2nd battery down.  But we easily could.

**Comment by WickedShell** [comment]
This has been done for awhile now.
