### ISSUE TITLE
List of Pixhawk-only features to port to Linux

### ISSUE THREAD

**Issue by lucasdemarchi** [ArduPilot/ardupilot#3216]
This is a list to keep track of the features available on PX4 that need to be ported to Linux.
- [ ] **Perf counters**: missing command to get them from the flight stack
- [ ] **Arming switch**
- [ ] **PWM input**: See pwminput driver for PX4 - Need HW support and probably kernel driver
- [ ] **SW control of RCOutput enable/disable**
- [ ] **Sensor auto-detection**: see rc.APM, but should be done inside the flight stack
- [ ] **Runtime driver allocation**: need INI parser + ifdef removal
- [ ] **IO mixed pass-thru in case the main FMU fails**: need proper HW support, can be done by raspilot
- [X] **Support for up to 14 PWM outputs**: #3358 
- [ ] **Interface for time capture**: Same as PWM input, need proper HW and kernel driver
- [ ] **Sanitize analog input**: should use ADC rather than GPIO interface
- [x] **UAVCAN**
- [ ] **Relay support**
- [ ] **Debug shell**: needed? "out-of-band" shell already covers use cases
- [ ] **OVERRIDE_CHAN**
- [ ] **IRLock**
- [ ] **RPM sensor**
- [ ] **Power and ESC status writing to dataflash log**
- [ ] **Power status sent through mavlink**

**Comment by lucasdemarchi** [comment]
Just updated the issue to turn it into a task list

**Comment by EShamaev** [comment]
UAVCAN:
https://github.com/ArduPilot/ardupilot/pull/7466

**Comment by auturgy** [comment]
@lucasdemarchi can you update or close?
