### ISSUE TITLE
SYSID_MYGCS docs a bit confusing

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#3226]
[SYSID_MYGCS](http://copter.ardupilot.com/wiki/arducopter-parameters/#my_ground_station_number_arducoptersysid_mygcs) states:

> "Allows restricting radio overrides to only come from my ground station"
1. I presume this means that if the value is set, RC overrides can only be set by a ground station with this ID?
2. Is there any checking of the origin other than using the ID? So for example if a dronekit app and GCS assert their id is this value then will the autopilot just accept the commands?
3. What is the value for "accept rc overrides from any GCS"? "Empty" or 0 or something else?
4. This only applies to rc overrides. Is there any mechanism for other commands. The use case is to allow a script and a GCS to assert they have control over a vehicle in guided mode.

If my assumptions above are correct, we should probably change this to something like:

> The autopilot will only accept radio override changes from GSCs (MAVLink sources) with the specified ID. If empty then rc overrides can come from any source.

**Comment by auturgy** [comment]
Closing.
