### ISSUE TITLE
EKF Parameters do not appear to be showing up in Copter

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#3248]
The AHRS_EKF_USE and EKF_CHECK_THRESH parameters are not showing up in the [Copter Parameters](http://copter.ardupilot.com/wiki/arducopter-parameters/).

**Comment by OXINARF** [comment]
This was for the old Wiki and should be fixed - those parameters don't even exist anymore :slightly_smiling_face:
