### ISSUE TITLE
Implement MAV_CMD_PREFLIGHT_CALIBRATION for rc calibration

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#3287]
This could be used to remove the possibility of arming while doing an RC Calibration. QGroundControl already support this mechanism.

**Comment by peterbarker** [comment]
Sub has this.  Swipe it for the other vehicle types.

**Comment by bCamba** [comment]
@peterbarker I can do that, but how can I test this? (I am new to ArduPilot community)

**Comment by IamPete1** [comment]
duplicate of https://github.com/ArduPilot/ardupilot/issues/8735
