### ISSUE TITLE
Add bootloader Firmware integrity check

### ISSUE THREAD

**Issue by Olivier-ADLER** [ArduPilot/ardupilot#332]
We should check for firmware integrity before starting it. A CRC value could be stored in the Flash area.

**Comment by gmorph** [comment]
Currently there is no checksum done of the FMU firmware.
We do check the CRC of the IO firmware and we check it matches the CRC in RomFS.  If it doesn't it tries to update to the correct firmware.
Thanks, Grant.

**Comment by auturgy** [comment]
@tridge thoughts?  Between compile and upload checks, there are already a couple of barriers in place.  We'd need to identify what specific set of circumstances could result in a corrupted firmware being loaded, and that firmware still being armable.  If such an edge case exists, it should be fixed.  If it doesn't, this issue should be closed.

**Comment by WickedShell** [comment]
@auturgy this is still valid. The ChibiOS IO uploader maintains a failure boolean so we can actually track if we have a bad/unexpected CRC on the IO firmware. Flying with a mismatched IO/FMU firmware can be catastrophic and should be prevented from arming. Similarly I think there is still value on checking the over flash checksum at boot, as corruption here can have subtle effects.

**Comment by jmachuca77** [comment]
@tridge thoughts?

**Comment by tridge** [comment]
@WickedShell we now check the CRC on the IO firmware

**Comment by WickedShell** [comment]
Yeah, that is a good improvement. It would still be nice if the actual bootloader checksummed that the flashed image matches an expected value, but it probably requires a slight set of bootloader changes.

**Comment by peterbarker** [comment]
Where would the bootloader stash the correct value on firmware-flash?

Our new bootloader doesn't currently have support for `BOOT_DELAY_ADDRESS`, which would be the nearest thing I can think of.

**Comment by peterbarker** [comment]
@WickedShell https://github.com/ardupilot/Bootloader/blob/master/bl.c#L657 <- that's the code I was refering to

**Comment by Naterater** [comment]
Does the new ChibiOS IO address this integrity check?

**Comment by peterbarker** [comment]
A suitably paranoid user can now achieve this using `AP_CheckFirmware` (check_good_firmware_unsigned).

I think we can close this one.  Any objections?

**Comment by peterbarker** [comment]
No objections, closing this one now.
