### ISSUE TITLE
Cannot simulate gimbal operation

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#3322]
The correct way to simulate a gimbal is to pass the -M option to sim_vehicle.sh. Unfortunately this results in MAVProxy not being able to connect to SITL.

This was tested on Windows with latest master build of Copter.

**Comment by peterbarker** [comment]
Seems to work OK under Linux, master Copter build.

**Comment by Naterater** [comment]
@hamishwillee, is gimbal operation simulation still an issue?

**Comment by hamishwillee** [comment]
Not for me - that's 2 years old and came up while documenting gimbal behaviour. Given that I won't have time to retest, I will  close this. Users can reopen or create a new one if they discover it is still a problem.

**Comment by peterbarker** [comment]
https://github.com/ardupilot/ardupilot/blob/master/Tools/autotest/arducopter.py#L2059 <- that's the autotest for the simulated gimbal.
