### ISSUE TITLE
Plane: Airspeed calibration msg is not sent via GCS channel

### ISSUE THREAD

**Issue by SamuelDudley** [ArduPilot/ardupilot#3378]
The airspeed calibration msg is currently not routed. This issue popped up having superclassed GCS_Mavlink to support low rate sending of filtered messages. This particular message was still being sent at a high rate (above a set airspeed) as it is currently being written directly to the channel. 
As all other messages are handled via a GCS channel I expect this is a bug.

See: https://github.com/diydrones/ardupilot/blob/master/ArduPlane/GCS_Mavlink.cpp#L2049

**Comment by magicrub** [comment]
Here's a working link
<https://github.com/diydrones/ardupilot/blob/master/ArduPlane/GCS_Mavlink.cpp#L2049>
