### ISSUE TITLE
Copter: IR-Lock sensor health variable should reflect whether the sensor is operating or not

### ISSUE THREAD

**Issue by derekxm** [ArduPilot/ardupilot#3505]
IR-Lock health variable in AP_IRLock should reflect whether IR-Lock sensor is operating or not. Presently, this variable is alway true, even when the sensor is not connected. 
See pull request #3501 when this issue is discovered.

**Comment by IamPete1** [comment]
fixed by, https://github.com/ArduPilot/ardupilot/commit/c6ea451c56ae766ecec02b70bbd21f075ae4267 sensor will now stop being healthy is there is no data for more than 0.1s
