### ISSUE TITLE
Make Use of SBGC_lib From AlexMos GitHub Repo 

### ISSUE THREAD

**Issue by davidbitton** [ArduPilot/ardupilot#3519]
I was looking over the code for [AP_Mount_Alexmos](http://tro.pe/1Rw0ASF) and I noticed that the code does not take advantage of the [SBGC_lib](http://tro.pe/1RvZQwT) from alexmos's [SimpleBGC Serial API examples and libraries](http://tro.pe/1Rw0H0A) repo. Would it make sense to use their lib for defines et al? I'm willing to take on the rework if it's something the collective deems a worthy effort. Thanks!

**Comment by rmackay9** [comment]
@davidbitton, I think that might make sense.  You'd use a git submodule to link it?  So it could appear in this directory.  https://github.com/diydrones/ardupilot/tree/master/modules

**Comment by davidbitton** [comment]
Yes.

Sent from my mobile device.

Please excuse its brevity and/or typographical errors.

On Jan 19, 2016, at 12:34 AM, Randy Mackay <notifications@github.com> wrote:

@davidbitton <https://github.com/davidbitton>, I think that might make
sense. You'd use a git submodule to link it? So it could appear in this
directory. https://github.com/diydrones/ardupilot/tree/master/modules

—
Reply to this email directly or view it on GitHub
<https://github.com/diydrones/ardupilot/issues/3519#issuecomment-172743618>.

**Comment by davidbitton** [comment]
Which repo should I work from for my Pixhawk?

**Comment by davidbitton** [comment]
I tried to add their code as a submodule and add it to the build process; too confusing. can you help with adding it into the Makefiles?

**Comment by OXINARF** [comment]
@davidbitton Can we close this? I think that adding a dependency on a simple helper library doesn't bring much benefit to be honest. Also, we have a PR (#5297) that improves Alexmos support and brings new definitions in.

**Comment by davidbitton** [comment]
done.
