### ISSUE TITLE
CI Enhancement : Considering switch to travis trusty 

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#3534]
Hi,

I just made some test on travis trusty and it works building APM!
https://github.com/khancyr/ardupilot/tree/test_travis_trusty
https://travis-ci.org/khancyr/ardupilot/builds/104040447

With the current config, it doesn't seem to improve build speed, but it should with some tuning and using trusty package (and it is closer to user configuration) .

**Comment by magicrub** [comment]
What's different about Travis trusty vs regular Travis?

**Comment by khancyr** [comment]
Actually travis is running ubuntu 12.04 "precise" , switching to trusty should simplify ci a little by using up to date package (and over use apt-get ) and maybe build a little faster

**Comment by lucasdemarchi** [comment]
@khancyr I don't think it will speed up the build, unless travis is giving preference to machines using it. Anyway, if it builds fine, we can switch.  Could you send a PR?

**Comment by lucasdemarchi** [comment]
@khancyr btw, recently we added support to semaphoreci as well, which is currently building the code way faster than travis

**Comment by magicrub** [comment]
Please provide a reason for closing.

**Comment by khancyr** [comment]
Using trusty on travis is quite slower to start and the transition will not be that simple. So this proposal should be close for now until some made a PR for using trusty
