### ISSUE TITLE
AC 3.3.2 Gimbal BUG Verified by 3 different copter and user

### ISSUE THREAD

**Issue by andrea25** [ArduPilot/ardupilot#3535]
Good Morning,
I have found a bug.
Or at least I think so.
I and 3 different Italian friend have found this probem.

This is the Planner Screenshot
![gimbal setting](https://cloud.githubusercontent.com/assets/10176752/12508731/f0db0628-c0fd-11e5-9b3e-844daac4809d.jpg)

This is the full parameter list.
![fullparam](https://cloud.githubusercontent.com/assets/10176752/12508736/f365bfaa-c0fd-11e5-93fc-91e44dceee43.png)

The Gimbal does NOT move when I change the CH6 IN PWM.
I can move the potentiometer but the gimbal does not move.
I have already tested the gimbal with a servo tester and it does move.
And also if I change the servo MIN and the servo MAX PWM I can move the gimbal. But I can not move by using CH6 on the radio.

I think this is a bug.
With AC 3.2.1 this does not happen.

**Comment by auturgy** [comment]
Closing.
