### ISSUE TITLE
MAVLINK_COMM_NUM_BUFFERS define not used consistently

### ISSUE THREAD

**Issue by kwikius** [ArduPilot/ardupilot#3545]
ArduPlane. The number of GCS_MAVLINK structures is assumed to depend on the MAVLINK_COMM_NUM_BUFFERS define:

https://github.com/diydrones/ardupilot/blob/master/ArduPlane/Plane.h#L258

but then the define is ignored and it is assumed that all boards have 4 gcs

https://github.com/diydrones/ardupilot/blob/master/ArduPlane/system.cpp#L138

**Comment by WickedShell** [comment]
Was fixed in #3752
