### ISSUE TITLE
Using of isnan function

### ISSUE THREAD

**Issue by approximator** [ArduPilot/ardupilot#3553]
Hi,

File: https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Math/quaternion.h#L53
Comment: https://github.com/diydrones/ardupilot/commit/c7d5f06b21fa4f4df53a414909bc477c481c2bad#commitcomment-15622602

I am wondering why isnan is used here instead of std::isnan? 
Now it can't be compiled with mingw32 compiler.

I understand that it is not supposed to be compiled with mingw, but I just curious if there is a reason to call isnan in a such way.

Thank you in advance.

**Comment by lucasdemarchi** [comment]
Is this the only reason?

Some functions are missing on some toolchains, particularly the GCC 4.9.3 the PX4 port is using.  If you just replace with std::isnan and it works everywhere it could probably be used.

**Comment by rpadovani** [comment]
I have the same problem with _ g++ 5.3.1_

There is anything I can do without having to change each file to `sdt::isnan()` ? (or `using std::isnan()`)?

**Comment by OXINARF** [comment]
See #3878. We are deprecating the use of make build system for Linux, you should start using waf.

**Comment by lucasdemarchi** [comment]
And
http://discuss.ardupilot.org/t/waf-to-become-default-build-system-for-linux/8451/8

On Mon, Apr 18, 2016 at 2:25 PM, Francisco Ferreira <
notifications@github.com> wrote:

> See #3878 <https://github.com/ArduPilot/ardupilot/pull/3878>. We are
> deprecating the use of make build system for Linux, you should start using
> waf.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ArduPilot/ardupilot/issues/3553#issuecomment-211484969>
>



-- 
Lucas De Marchi

**Comment by OXINARF** [comment]
Closing this in favor of #4026
