### ISSUE TITLE
Copter: MissionPlanner: Enhancement: Adding/Use of rangefinders

### ISSUE THREAD

**Issue by datamann** [ArduPilot/ardupilot#3558]
[ArduPilotMissionPlannerEnhancement.pdf](https://github.com/diydrones/ardupilot/files/107220/ArduPilotMissionPlannerEnhancement.pdf)

ArduPilot/Mission Planner Enhancement 

I will here try to describe a “new” feature that I would like to see in Pixhawk. I say new in quotes because the feature partly exist already.

I'm trying to build an inspection drone and with an inspection drone, the pilot needs to be fully aware of the  sorundings when flying. For that I would like to be able to add rangefinders on all axis except underneath where a lidar is probably better.

I would like to able to use these rangefinders for:
1. Navigation 
          The purpose of navigation is for automatic obstacle avoidance. 
2. Report Only
          The purpose of “Report Only” is to able to get the distance of all rangefinders in the OSD.
3. Both
          Both navigation and reporting.

I would also like to see an alarm function. So that I can set an alarm if an object is closer than e.g. 2 meters pr. axis.

I would like to be able to add rangefinders in Mission Planner, in some way like the image:

Se document with [images:](https://docs.google.com/document/d/1-k4XKf7n2-YuE1c2zOt6B7xRXKAWO718vxEUTJyKg5g/edit?usp=sharing) 

See image in document

Mission Planner OSD with rangefinder data. Written number in meters/inch/feet could also be over the range indicator:

See image in document

I will add this enhancement in the MinimOSD but it seems like it is abandoned.  If that's the case I will find another OSD or add the feature my self in minimOSD.

<image in document>
minimOSD with rangefinder data. Written number in meters/inch/feet could also be over the range indicator

Thanks for the good job you all are doing!

Regards
Stig Sivertsen
Norway, 27.01.2016

**Comment by IamPete1** [comment]
we now support a number of avoidance schemes.

https://ardupilot.org/copter/docs/common-simple-object-avoidance.html
