### ISSUE TITLE
EKF2 and mavlink status message inconsistency

### ISSUE THREAD

**Issue by priseborough** [ArduPilot/ardupilot#3569]
EKF2 is sending true airspeed normalised innovations, Mavlink is expecting a 'terrain altitude variance'.

Noting that we should be sending airspeed innovation variance in addition to the existing messages.

**Comment by priseborough** [comment]
Partially fixed by #3570 .

**Comment by hendjoshsr71** [comment]
Closing this as this was added [here](https://github.com/ArduPilot/mavlink/blob/68f8e38eda2eb00f4d056186d58a5e768085037e/message_definitions/v1.0/ardupilotmega.xml#L1471) and is being sent in each EKF type
