### ISSUE TITLE
Plane: geofencing at the size of a country causes sim floating point overflow

### ISSUE THREAD

**Issue by marcmerlin** [ArduPilot/ardupilot#3581]
I use a country-size fence because of setting min and max altitudes without a fence isn't possible currently ( https://github.com/diydrones/ardupilot/issues/2984 )
@tridge said that it was worth looking into while huge fences causes floating point errors in the sim though.

**Comment by marcmerlin** [comment]
Hi Tridge, you asked me to file this. You can decide if it's still a problem, or not.

**Comment by Naterater** [comment]
Just want to follow up on this as well if possible.

**Comment by rmackay9** [comment]
I suspect the underlying floating point overflow does happen in Copter as well (so we should fix that) but at the same time Copter also allows setting up just an altitude fence so the work around to set a huge horizontal fence isn't required (for Copter).

**Comment by amilcarlucas** [comment]
@joshanne I think your PRs #15568 and #15288 fixed this.
@marcmerlin can you test this with the latest master

**Comment by marcmerlin** [comment]
Thanks for taking care of this. This bug was 5 years ago though, I'll be honest that I haven't been flying in a while, so unfortunately I can't test this, but since you've just fixed min/max altitude triggers without needing a country-wide fence, my guess is that this won't be an issue anymore.
Thanks for your work.

**Comment by IamPete1** [comment]
Sounds like we can close this
