### ISSUE TITLE
Update parameter in-source docs to reflect new stream rates supported

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot#3591]
E.g. @alduxvm The doc says the range is 0 to 10Hz in  http://plane.ardupilot.com/wiki/arduplane-parameters/#raw_sensor_stream_rate_sr2_raw_sens and other stream control parameters

50Hz now supported for at least some of these.

**Comment by IamPete1** [comment]
All of the stream rate param now show 0 to 50 hz range. EG:

https://github.com/ArduPilot/ardupilot/blob/0b0ca6a9e99e5f22621af1d0199f008ce1c786d0/ArduCopter/GCS_Mavlink.cpp#L345
