### ISSUE TITLE
Arduplane Firmware 3.5 don't work with ESC HobbyWing Skywalker

### ISSUE THREAD

**Issue by mulysatest** [ArduPilot/ardupilot#3629]
Our plane working flawlessly with Firmware 3.1.x but once we upgrade to Firmware 3.5.0 seems like it cause the ESC to behave very weird. The once try to speed up the motor it end up that the motor would keep spinning about 30 secs, but after that it stop completely. But once downgrade to 3.1.x it does work again. 

Please note that our ESC is ESC HobbyWing Skywalker.

**Comment by marcmerlin** [comment]
I'm jusre helping to triage, but whoever can look at this will most likely need a dataflash log from you to see what the inputs/outputs look like.

**Comment by marcmerlin** [comment]
Without datalog, this can't be look into. I'm going to close this.
