### ISSUE TITLE
Copter: PILOT_VELZ_MAX for up and down speeds

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#366]
In AC2.9.1b and 3.0-rc5 the PILOT_VELZ_MAX applies to both maximum climb and descent but in fact most copters can climb much faster than they can descend so we should separate the parameter into a max climb and max descent.

Requested by Graham Dyer

**Comment by gaucho1978** [comment]
Was this request processed? I understood that actually the max climbing speed with the mission planner is 5m/s but I need at least a climbing speed of 8m/s. Is this achievable with ardupilot? 
Thank you for the support.

**Comment by rmackay9** [comment]
@gaucho1978, you can set the PILOT_VELZ_MAX to any value using the MP's full param list (or full param tree) screen.  So set it to 800 and you'll get 8m/s.  That'll be up and down though so it'll fall quickly as well.
This issue is still open so we haven't addressed it yet.

**Comment by gaucho1978** [comment]
Thank you, on the wiki it says 500cm/s,  may be it is better to write the real limit.

**Comment by magicrub** [comment]
The limit is not on the autopilot, it is on the physical hardware.

**Comment by rmackay9** [comment]
This has been completed now and will go out with Copter-3.6
