### ISSUE TITLE
Trone driver

### ISSUE THREAD

**Issue by abencomo** [ArduPilot/ardupilot#3670]
Will it be possible to duplicate the [Trone](https://github.com/diydrones/PX4Firmware/tree/62d935eb1665a74ca9a40ea1438121a594027327/src/drivers/trone) driver into the ardupilot/libraries/ so it is included in the Navio / Linux builds?

**Comment by peterbarker** [comment]
@abencomo I believe we have Trone support now.  Please reopen if I'm in error.
