### ISSUE TITLE
MAV_CMD_CONDITION_DELAY enhancement

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#3675]
I need to perform automatic events at fixed times.
Chatting with Randy was right to me to be simple, and it would be interesting to implement it.
Using "MAV_CMD CONDITION DELAY" where instead of declaring the seconds of pause just enter a UTC time in 24h format (es. 13:00:15), detected by gps so absolutely reliable.
I believe that this feature will be very interesting, especially in the swarming and autonomous flights (where permitted).

**Comment by magicrub** [comment]
+1 Love the idea!

**Comment by robustini** [comment]
An alternative, to avoid using too many events, would be to be able to set a fixed time for each type of event, but perhaps at programming level would be more complicated.
I hope Randy and Michael implement as soon as possible this thing.

**Comment by DonLakeFlyer** [comment]
My only comment would be to implement it as a new command, not as a one-off of MAV_CMD_CONDITION_DELAY

**Comment by robustini** [comment]
MAV_CMD_CONDITION_TIME...?

**Comment by rmackay9** [comment]
After our discussion on the dev call I think we decided to create a new navigation command (instead of a "do" or "conditional" command).  So a good name might be MAV_CMD_NAV_DELAY.

Here's another related issue: https://github.com/ArduPilot/ardupilot/issues/3675

**Comment by robustini** [comment]
Really nice, i wait the integration (also inside the Planner), thanks Randy!

**Comment by rmackay9** [comment]
Closing this issue because this was implemented with the NAV_DELAY command.  I've added the need to add documentation in this other issue.  https://github.com/ArduPilot/ardupilot/issues/4674
