### ISSUE TITLE
ArduPlane 3.5 firmware doesn't work with FlightGear HITL

### ISSUE THREAD

**Issue by jinchengde** [ArduPilot/ardupilot#3690]
Hi
  I'm using ArduPlane 3.5 firmware for HITL with FlightGear, but the board is still in Initliseing States after we start the Sim Link. change the version to 3.4 is OK.
  Does anyone see that before?

**Comment by magicrub** [comment]
I'll let @tridge chime in on this before I close but I think HITL (Hardware-in-the-loop) is generally broken right now. The SITL tools have gotten good enough that we have no longer needed it and so it has not been maintained properly.

**Comment by jinchengde** [comment]
@magicrub @tridge 
I means the HITL with FlightGear, not SITL , sorry for mistake.
I think the HITL is more important for us because we can test it with Dronekit and observer the servo action. hopefully to hold this function in further.

**Comment by magicrub** [comment]
SITL will work with dronekit and you can plot and log the servo output.
