### ISSUE TITLE
TradHeli Throttle Output Min/Max Not Respected

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#3695]
In AC3.3 there are some parameters H_THR_MIN and _MAX which are used to set the min and max of the output channel for throttle servos.  The min/max was supposed to be independent of the input channel min/max, because in copter we generally do not require users to know how to change any settings in their Tx (such as shrinking endpoints) and then redoing the RC Calibration to set up some function.

This is currently broken in AC3.4.

**Comment by rmackay9** [comment]
This is fixed in master with the addition of the H_RSC_PWM_MIN, H_RSC_PWM_MAX and H_RSC_PWM_REV parameters.  We just need to update the wiki to reflect this and then we can close the issue.
