### ISSUE TITLE
Plane: Cruise Mode Throttle/Pitch Behaviour Different to RTL

### ISSUE THREAD

**Issue by SlipstreamFPV** [ArduPilot/ardupilot#3720]
On Arduplane 3.5 I noticed that the way the cruise throttle behaves is different to other auto modes such as loiter and RTL. The output differs as does the speed scaling. 

On RTL mode mid throttle = TRIM_ARSPD_CM, on Cruise mode mid throttle = Speed 1/2 way between  ARSPD_FBW_MAX and ARSPD_FBW_MIN.

Also cruise appears to be subject to more noise than RTL and Loiter throttle:

Cruise Pitch:
![cruise pitch](https://cloud.githubusercontent.com/assets/6742745/13595017/fbdeaf8c-e553-11e5-837e-3b24bdfee80a.png)

RTL Pitch:
![rtl pitch](https://cloud.githubusercontent.com/assets/6742745/13595020/fdf3bdf8-e553-11e5-9b2e-a43e32a1baf9.png)

Cruise Throttle:
![cruise throttle](https://cloud.githubusercontent.com/assets/6742745/13595018/fcee5300-e553-11e5-8673-df2780fa70a5.png)

RTL Throttle:
![rtl throttle](https://cloud.githubusercontent.com/assets/6742745/13595022/ff1c56c2-e553-11e5-907f-d8bf78398b7d.png)

Cruise Requested Throttle vs Airspeed:
![cruise speed vs throttle input](https://cloud.githubusercontent.com/assets/6742745/13595468/5fd510aa-e557-11e5-874a-ba37cde36968.png)

RTL Requested Throttle vs Airspeed
![rtl speed vs throttle input](https://cloud.githubusercontent.com/assets/6742745/13595491/8ae44cca-e557-11e5-80e6-5144debcded3.png)

Notice that in Cruise despite the demanded throttle being lower the airspeed is still higher.

It would be good if all auto modes functioned the same regarding use of the throttle as the wiki pages suggests they should.

Using the users TRIM_THROTTLE setting as the middle point in all auto modes makes sense. TRIM_ARSPD_CM should be used as the speed the autopilot will fly at when the throttle is at this point. After the throttle has not been moved by the user in an auto mode for more than 2 seconds a deadband of 10/20us should be set around that point to prevent CRUISE adjusting the throttle due to small output dither from the controller Tx.

**Comment by magicrub** [comment]
Do you fly with an air-speed sensor? ARSPD_ENABLE=1 and ARSPD_USE=1?

**Comment by SlipstreamFPV** [comment]
Yes, I fly with the digital airspeed sensor and it has been tuned. The tuned value is very close to the default of 2.0.

**Comment by SlipstreamFPV** [comment]
Just to clarify the "yes" means yes to all of your questions :) I can't edit the previous comment on my phone browser.

**Comment by IamPete1** [comment]
@SlipstreamFPV is this still a issue on 4.1?

**Comment by SlipstreamFPV** [comment]
I will test. I know there was another issue about this that is more recent, I will try and find the post.

**Comment by peterbarker** [comment]
@SlipstreamFPV any update?

**Comment by peterbarker** [comment]
Closing this as it's had NeedAnswer on it for years.
