### ISSUE TITLE
Plane: More failsafes

### ISSUE THREAD

**Issue by jcooper21** [ArduPilot/ardupilot#3742]
Wind - It would be nice to have updated failsafes in APM Plane such as an RTL option if high winds are detected mid flight. The plane could come back and circle overhead or land. 

GPS - It would also be nice to have an RTL option if GPS signal starts deteriorates (RTL before the signal is completely gone). 

Motor Failsafe - If the motor fails in flight is it possible to make the plane orientate itself to the home position and glide towards it? This operation would cancel if the motor started up again.

**Comment by magicrub** [comment]
Can you define "starts to deteriorate"?

**Comment by jcooper21** [comment]
For GPS sat count reducing below X sats and hdop increasing. Other manufacturers have implemented these failsafes nicely such as sensefly.

**Comment by magicrub** [comment]
Have you looked at the AFS params?
http://plane.ardupilot.com/wiki/arduplane-parameters

see AFS_MAX_GPS_LOSS and AFS_GPS_LOSS. This kicks in if we've lost lock on
GPS for 3 seconds.

-TomP

**Comment by jcooper21** [comment]
That isn't proactive. GPS is gone once that failsafe kicks in, a deteriorating signal would allow for safer failsafe instead of once GPS is gone.

**Comment by jcooper21** [comment]
I forgot to mention motor failsafe. If the motor fails in flight is it possible to make the plane orientate itself to the home position and glide towards it? This operation would cancel if the motor started up again.

**Comment by rmackay9** [comment]
I think it might be a decent idea to look at the copter GPS/EKF failsafe which triggers when the EKF's position and velocity "innovations" climb above 0.8.  I think this is a better predictor than the number of satellites or hdop value.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (436/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:33212 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNc-000ay5-FJ
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:19 +0100
Date: Sun, 13 Mar 2016 09:27:36 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457886456;
	bh=VzBDCjUCJb6V+lMmuHuwmhrnjuV44JPg+dwQSdH4C8Q=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=G1/xzq6qsV2NdNWEdsNtn/Gg4wZTF+tX/HoZUcN2zG7fHJPJ/EGzlaIsItdFUlpTh
	 +30+ykBUN1/+o8IklhfqKoxpJIUPmlSJTzDgIOuH3NG1McADQLscZXuRF3QpG/kG5/
	 zqHWdEkvUJbcHAOIjcZVyn7XY1egCaoMUcex2hic=

**Comment by Naterater** [comment]
I think this multi-faceted issue should be closed in favor of the following issues:
https://github.com/ArduPilot/ardupilot/issues/4491
https://github.com/ArduPilot/ardupilot/issues/3456

The EKF failsafe issue on GPS could probably be re-created as its own issue if somebody wanted.

**Comment by IamPete1** [comment]
This issue is covered by the existing issues linked above.
