### ISSUE TITLE
Quadplane: FENCE_AUTOENABLE not triggered on VTOL

### ISSUE THREAD

**Issue by JMare** [ArduPilot/ardupilot#3757]
Plane has FENCE_AUTOENABLE to allow auto landings and takeoffs through a geofence with a FENCE_MINALT. 
We would like to use this with Quadplane missions, but the quadplane auto takeoff and landing do not trigger the this. (Tested in SITL)

Seems like Quadplane::verify_vtol_takeoff() lacks the logic to do this that is found in Plane::verify_takeoff(). Looks fairly simple to implement.

Happy to help implement this but will need some guidence as I am new to the codebase.

Thanks

**Comment by marcmerlin** [comment]
Hi @tridge , I created a new quadplane label for you :)

**Comment by tridge** [comment]
thanks! I've pushed a fix to master for 3.7.0
