### ISSUE TITLE
Question! example sketch(AHRS_Test, gps_test, etc) code error 

### ISSUE THREAD

**Issue by sgh055** [ArduPilot/ardupilot#3787]
I uploaded to AHRS_Test-v2.px4 file on pixhawk

I connect to console, there is no response and nsh shows following message.

`AP_I2C on I2C bus 1 at 0x00 (bus: 100 KHz, max: 400 KHz)
rgbled on I2C bus 2 at 0x55 (bus: 100 KHz, max: 100 KHz)
[init] looking for microSD...
[init] card mounted at /fs/microsd
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
[init] USB interface connected
Running rc.APM
Mounting binfs
binfs mounted OK
nsh: rm: unlink failed: No such file or directory
Detected FMUv2 board
uorb started OK
Trying PX4IO board
PX4: param_find(SYS_RESTART_TYPE)
PX4: param_find(RC_RSSI_PWM_CHAN)
PX4: param_find(RC_RSSI_PWM_MAX)
PX4: param_find(RC_RSSI_PWM_MIN)
PX4: param_find(CBRK_IO_SAFETY)
px4io default PWM output device
PX4: param_find(CBRK_FLIGHTTERM)
PX4IO board OK
PX4: param_find(RC_DSM_BIND)
PX4: param_find(BAT_V_SCALE_IO)
PX4: param_find(RC_FAILS_THR)
PX4: param_find(RC_FAILS_THR)
PX4: param_find(CBRK_FLIGHTTERM)
PX4: param_find(RC_RSSI_PWM_CHAN)
PX4: param_find(RC_RSSI_PWM_MAX)
PX4: param_find(RC_RSSI_PWM_MIN)
PX4: param_find(PWM_MAIN_REV1)
px4io: CRCs match
PX4: param_find(PWM_MAIN_REV2)
PX4IO CRC OK
PX4: param_find(PWM_MAIN_REV3)
PX4: param_find(PWM_MAIN_REV4)
PX4: param_find(PWM_AUX_REV1)
PX4: param_find(PWM_MAIN_REV5)
PX4: param_find(PWM_AUX_REV2)
PX4: param_find(PWM_MAIN_REV6)
PX4: param_find(PWM_AUX_REV3)
PX4: param_find(PWM_MAIN_REV7)
PX4: param_find(PWM_AUX_REV4)
PX4: param_find(PWM_MAIN_REV8)
PX4: param_find(PWM_AUX_REV5)
PX4: param_find(TRIM_ROLL)
PX4: param_find(PWM_AUX_REV6)
PX4: param_find(TRIM_PITCH)
Set FMU mode_pwm4
PX4: param_find(TRIM_YAW)
started mtd driver OK
PX4: param_find(PWM_SBUS_MODE)
reading /fs/mtd expecting 32768 bytes
readtest OK
mtd readtest OK
rwtest /fs/mtd testing 32768 bytes
rwtest OK
mtd rwtest OK
Starting APM sensors
MS5611_SPI on SPI bus 4 at 2 (20000 KHz)
ms5611: no device on bus 4
MS5611_SPI on SPI bus 1 at 3 (20000 KHz)
ms5611: no device on bus 1
ms5611: no device on bus 2
ms5611 started OK
adc init done
adc started OK
Starting FMUv2 sensors
hmc5883: no device on bus 2
No external hmc5883
hmc5883: no device on bus 1
No internal hmc5883
mpu6000: driver start failed
mpu9250: driver start failed
No MPU6000 or MPU9250 external
MPU6000 on SPI bus 1 at 4 (1000 KHz)
Found MPU6000
L3GD20 on SPI bus 1 at 1 (11000 KHz)
l3gd20 started OK
LSM303D on SPI bus 1 at 2 (11000 KHz)
lsm303d started OK
ets_airspeed: no ETS airspeed sensor connected
meas_airspeed: no MS4525 airspeed sensor connected
meas_airspeed: no MS4525 airspeed sensor connected
ll40ls: driver start failed
ll40ls: driver start failed
trone: driver start failed
mb12xx: driver start failed
px4flow: scanning I2C buses for device..
started pwm_input driver
oreoled: autoupdate enabled
oreoled on I2C bus 2 at 0x68 (bus: 100 KHz, max: 100 KHz)
oreoled started OK
batt_smbus on I2C bus 2 at 0x0b (bus: 100 KHz, max: 100 KHz)
Found batt_smbus
irlock: failed to initialize device, stopping driver
Starting ArduPilot /dev/ttyACM0 /dev/ttyS1 /dev/ttyS2
Starting AHRS_Test uartA=/dev/ttyACM0 uartC=/dev/ttyS1 uartD=/Assertion failed at file:armv7-m/up_hardfault.c line: 184 task: AHRS_Test
sp:     2000c810
IRQ stack:
  base: 2000c85c
  size: 000002e8
2000c800: 080692ca 2000c810 1000f4c8 0804513f 08069390 000000b8 0803ec45 00000010
2000c820: 2000b18c 00000003 00000000 080453c9 080453b5 0805263b 1000f480 0804f4fd
2000c840: 00000000 20005a80 00000001 20020000 00000000 08045339 1000f3ac 00000000
sp:     1000f480
User stack:
  base: 1000f4c8
  size: 00001ffc
1000f480: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
1000f4a0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 0803ff49
1000f4c0: 00000000 00000000 ffffffff 61fce46a aef706d5 73b6fac1 00000410 80002010
R0: 1000cf84 00000000 20005f5c 080594f2 20005a80 00000001 20020000 00000000
R8: 00000000 00000000 00000000 00000000 20008528 1000f480 0800e685 20020000
xPSR: 20000000 BASEPRI: 00000000 CONTROL: 00000000
EXC_RETURN: ffffffe9`

What I missing? 

Sorry for newbie question.

**Comment by magicrub** [comment]
questions like this will get more attention in the forums at http://discuss.ardupilot.org, this is the developer TODO list.

closing.
