### ISSUE TITLE
MAVLink: Create an enum for flight modes

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#3788]
Currently we report the current flight mode as a custom_mode in the heartbeat, which is fine, but the different vehicles (copter/plane/rover) all use different values for what each mode is. We should have an enum in the ardupilotmega.xml that indicates what flight mode we are in, this way the GCS isn't dependent upon hard coding that  on plane custom mode of 4 is acro while on copter that is guided. If we could move this all to a common enum that all vehicles share this would help on the GCS side a lot.

Because of the intrusiveness of the change this might be best rolled out with MAVLink 2, or some other major GCS breaking update.

**Comment by rmackay9** [comment]
a fine idea!

**Comment by WickedShell** [comment]
Enum was created and accepted, the decision was that vehicle code does not reference it, but otherwise is complete.
