### ISSUE TITLE
Copter: 3.3 autotest fly.ArduCopter failed

### ISSUE THREAD

**Issue by busyStone** [ArduPilot/ardupilot#3797]
I checkout Copter 3.3.2 and run `autotest.py build.ArduCopter fly.ArduCopter`, SITL is running but test failed.

<img width="689" alt="2016-03-25 8 52 06" src="https://cloud.githubusercontent.com/assets/1464948/14044435/b04cb0f2-f2cb-11e5-969f-22de3c72c3a4.png">

I don't know why. But with debug i found there is no `MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE` message to flight controller `GCS_MAVLINK::handleMessage`.

**Comment by lthall** [comment]
I will close this because of the age of the issue and it is for 3.3.
