### ISSUE TITLE
Copter: Allow Ch6 to optionally have the same choices as Ch7 and not to be used for tuning parameters.

### ISSUE THREAD

**Issue by igortep** [ArduPilot/ardupilot#380]
With version 3.0, tuning parameters seems to be less nessasary. At the same time, having access to advanced functions directly from the radio makes flying much more versatile and fun. Having flexibility to set dedicated switches for RTL, motor kill, set/clear waypoint, etc. would be great.

Need a setting to choose how Ch6 is used and the ability to assign choices now available for Ch7 and Ch8 to Ch6.

**Comment by marimach77** [comment]
+1

**Comment by lvale** [comment]
@R-Lefebvre 
Hi Rob. shouldn't this be "incorporated" on the redesign of the Aux switches, and one of the Aux functions become "Tuning" ?? Or just close it :)

**Comment by R-Lefebvre** [comment]
Yeah, it was basically done. But what I did wasn't accepted into master. I will have to try again.

**Comment by rmackay9** [comment]
pushing to AC3.4.

**Comment by R-Lefebvre** [comment]
Randy, I'd be happy to do what I tried to do before, but in Input Manager this time?  Basically, make all the Aux Channels (6-16) operate the same way, Any channel can be assigned as a function switch, Or, used for up to 3 Tuning functions at the same time.

Should I go for it?

**Comment by lvale** [comment]
Great idea @R-Lefebvre 

versatility and functionality :)

**Comment by rmackay9** [comment]
bumping to AC-3.5

**Comment by gluca** [comment]
bacporting to 3.2?
