### ISSUE TITLE
I2C connection Question

### ISSUE THREAD

**Issue by sgh055** [ArduPilot/ardupilot#3807]
Hello 

I have a question. 

Pixhawk support some sonar sensor. But I want to use MLX90614(temperature sensors) using I2C.

Is this possible connection?

If you know way to connect please tell me some link or data. thank you.

**Comment by Jasonsiu** [comment]
what do you want to do by MLX90614?Althold?obstacle avoidance?

**Comment by jpkh** [comment]
Long ago ardupilot was using thermopiles but that support has been dropped as currently we are using gyros/accels to determine orientation. @sgh055 I would suggest you to write your own library support for this thermopile sensor.

**Comment by sgh055** [comment]
@Jasonsiu I would just measure the air temperature for embers detection

@jpkh Then I'd get where did the information on i2c library of ardupilot?

**Comment by jpkh** [comment]
@sgh055 naturally from here on [Ardupilot](https://github.com/ArduPilot/ardupilot) repository
