### ISSUE TITLE
RFE: AP 3.5.2: RTL and other auto modes should have an option to turn off motor when above target altitude

### ISSUE THREAD

**Issue by marcmerlin** [ArduPilot/ardupilot#3812]
My motor glider doesn't need motor power to fly at all times, and there are 2 clear cases
1) try to maintain altitude (cruise) but in an updraft
2) RTL or AUTO and above target altitude

Taking the easy case of RTL above target altitude, it consistently uses motor for me.
Like here, target RTL altitude is 100m, I'm at 145m, and motor is at 43%
![rtl](https://cloud.githubusercontent.com/assets/1369412/14085882/396714d8-f4d7-11e5-8cc2-69c1cbe7f3e2.jpg)

Turning off power to 0% may not be desirable for all airframes, but definitely for motor gliders if you're well above target altitude.
There is of course the trick of how much airspeed you want to keep before your turn the motor back on, so maybe some
FBW_GLIDE_AIRSPEED
If airspeed is above that, and we're above target altitude, keep airspeed at this setting and glide down.
If airspeed is decaying below that speed, pitch down further
If target altitude (below) is about to be reached and airspeed is around FBW_GLIDE_AIRSPEED, turn the motor back on.
Sounds fair?

**Comment by marcmerlin** [comment]
@WickedShell asked for an example with log, so the screenshot above was taken from this flight log: http://marc.merlins.org/tmp/7_RTL_USES_MOTOR_ABOVE_ALT.BIN
Hope this helps.

**Comment by marcmerlin** [comment]
By the way, the plus from adding a new FBW_GLIDE_AIRSPEED is that it would default to 0, and disable the feature of turning the motor off in AP controlled flight modes. That way, nothing changes by default, and people with good glide ratios, can choose to enable it.
Does it sound like a good idea?

**Comment by geofrancis** [comment]
my plane would turn off the motor when it was decending in RTL.

**Comment by marcmerlin** [comment]
@geofrancis : do you have throttle nudge enabled?
I do, and RTL turns the motor on even if my throttle is 0%

**Comment by magicrub** [comment]
Marc, you must have some param set somewhere strange. If you have plenty of
airspeed, and descending in a loiter, then the motor should be off.

**Comment by marcmerlin** [comment]
Ah, I am not hitting the descending into a loiter case. I'm hitting the "flying to the RTL point, but my glide ratio is 10:1, and I don't need motor to arrive there with sufficient altitude"
Has anyone gotten their plane to glide in the direction to the RTL point (not in loiter above the RTL point)?

**Comment by geofrancis** [comment]
try calibrating your ESC.

**Comment by magicrub** [comment]
What does that do?

**Comment by marcmerlin** [comment]
So I did a test yesterday evening, flew over the RTL point, switched to RTL, and the plane did indeed circle down without using the motor, so that's good.
Now, the logic just needs to be a bit smarter and try to glide down to the RTL location without motor power if some heuristics say it can, and FBW_GLIDE_AIRSPEED is set.

**Comment by geofrancis** [comment]
i think i had throttle nudge enabled so if i hit RTL and i wanted to fly at minimum airspeed i would have to put the throttle to 0. 

i would have thought with it disabled and using the airspeed sensor it would default to your cruse airspeed.

**Comment by marcmerlin** [comment]
@geofrancis thanks for those pointers. Now, should TRIM_THROTTLE only be relevant if I'm trying to maintain altitude?
If I'm in RTL and I need to travel to a point, while losing altitude, should it still apply? (I think not)
I have: TRIM_THROTTLE   40.000000

I could try setting that to 0, but is that the right/safe thing to do, just so that RTL can go down with throttle off? If so, I'll give it a shot.

**Comment by geofrancis** [comment]
i would lower it a little first rather than jump to 0

**Comment by Buljan** [comment]
Hi guys,

I''m doing a high altitude balloon airplane launch, and the project is on a standstill until we figure out how to RTL the plane with no motor running- while being 20km above the Home position.  
This topic is the best discussion that i found, is there any progress? 

Or, do you guys have a alternate solution?

Thanks,
Josip

**Comment by geofrancis** [comment]
just set trim throttle to 0 and it will try and cruse with no throttle if you dont have an airspeed sensor.

**Comment by Buljan** [comment]
Hey, thanks for the reply, but i do have an airspeed sensor installed. :/

any tips?

**Comment by geofrancis** [comment]
if you have an airspeed sensor then it should keep the throttle at zero as long as you are above minimum air speed.

**Comment by magicrub** [comment]
We've had other people do balloon drops and I don't recall this being a
problem. Does anyone else know they that did it? Can we contact any of them?

**Comment by geofrancis** [comment]
if your FBWB_CLIMB_RATE is too low then it will run the throttle to stop the plane decending too fast.

**Comment by IamPete1** [comment]
This can be achieved with soaring support. (also lots of other cool stuff)

https://ardupilot.org/plane/docs/soaring-4_1.html
