### ISSUE TITLE
GPS Test

### ISSUE THREAD

**Issue by smoi** [ArduPilot/ardupilot#3818]
Now that the CLI was removed on the 3.2 how can I test if the GPS is working well? 
Below the 3.2 I was using the terminal to see if the data was received correctly or not but now I can't do this anymore. The light is green on the GPS but I'm not receiving coordinates on the apm planner so I need something to check if the connection from the GPS to the board is working

**Comment by WickedShell** [comment]
You can review the logged messages (GPS/GPA messages). If using a new enough build and a u-blox GPS, the driver will attempt to verify the configuration of the GPS. You can also checkout the mavlink GPS_RAW_INT messages sent down by the aircraft as well. If you want to thoroughly check the GPS you can use the pass through options as documented here: http://ardupilot.org/rover/docs/common-ublox-gps.html

Closing this as github isn't for support issues, and I've outlined the above ways to check the gps.
