### ISSUE TITLE
Waf name convention

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#3823]
Hi,

Not sure if it is an issue or not but actually when building with waf for rover, we got ardurover.px4 in ardupilot/build/px4-v2/bin, when it should be APMrover2-v2.px4 .

Actually, it is the same thing for copter....

Is that right ? or the naming convention will change with waf builds ?
Adding a page about waf on the new wiki could be usefull !

**Comment by gmorph** [comment]
Hi Gustavo.  Can you check this please?
Thanks, Grant.

**Comment by guludo** [comment]
@khancyr Yes, the binaries names and paths are using a different convention.

History regarding paths: https://github.com/ArduPilot/ardupilot/pull/3481 (maybe it's a good idea to follow the older versions of the PR :-))

About the binaries names: only those of the "main" products where changed. The PR that introduced that is https://github.com/ArduPilot/ardupilot/pull/3518 . There haven't been much discussion on that matter, but I personally think the new names are nicer and more consistent with what is used for common binaries.

Regarding the creation of a wiki page, I agree it would be useful. Let's create an issue for that. In the meantime, people can use https://github.com/ArduPilot/ardupilot/blob/master/README-WAF.md .

**Comment by magicrub** [comment]
Please provide a reason for closing.

**Comment by khancyr** [comment]
see Guludo answer
