### ISSUE TITLE
breakpoint debugging 

### ISSUE THREAD

**Issue by sgh055** [ArduPilot/ardupilot#3829]
I am currently analyzing arducopter sourcecode, but I don't know code flow.

is there any method for breakpoint? like a Visual studio?

**Comment by WickedShell** [comment]
Issues are for reporting bugs/feature requests in the code base. Try getting in contact with someone via gitter or mumble.

http://ardupilot.org/dev/docs/debugging-with-gdb.html is relevant, and if you want to debug on sitl you can launch SITL with -G to enable connecting GDB after launch.
