### ISSUE TITLE
AP_InertialNav class definition in v3.3.X

### ISSUE THREAD

**Issue by mtsakaguchi** [ArduPilot/ardupilot#3838]
Hello,

I am working on a project where custom changes have been in ArduCopter firmware version 3.1.5 to have position feedback coming from a vision positioning system. I am looking to upgrade to ArduCopter v3.3.1 to take advantage of some upgrades to Guided mode and need to implement the same changes in v3.3.1 that were in v3.1.5. One of the files that was altered in v3.1.5 was "AP_InertialNav.cpp", however in v3.3.1 that file has been renamed to "AP_InertialNav_NavEKF.cpp" which states that it acts as a wrapper around the AP_InertialNav class. Can anyone point me to where this AP_InertialNav class is defined in v3.3.1? More specifically I would like to add changes to AP_InertialNav::init(), AP_InertialNav::update(), AP_InertialNav::check_gps(), AP_InertialNav::correct_with_gps(), AP_InertialNav::check_bar(), AP_InertialNav::correct_with_bar(), and AP_InertialNav::update_gains() functions that were present in "AP_InertialNav.cpp" in v3.1.5.

Any help would be greatly appreciated.

**Comment by amilcarlucas** [comment]
This is not a bug, I think this belongs in the forum, and not here.

**Comment by OXINARF** [comment]
I agree with @amilcarlucas, this issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).
