### ISSUE TITLE
Plane: Parachute always released before motors are off

### ISSUE THREAD

**Issue by naktinis** [ArduPilot/ardupilot#3852]
How we want this to work (I assume):
 - parachute release sequence initiated (`parachute.release()`)
 - throttle suppressed (`suppress_throttle` code checks if parachute released initiated)
 - parachute triggered (servo or relay triggered, `parachute.released()` starts returning true)

How it currently works:
 - parachute release sequence initiated (`parachute.release()`)
 - parachute triggered (servo or relay triggered, `parachute.released()` starts returning true)
 - throttle suppressed only after `parachute.released()` is true (that is, it waits until servo or relay is actually triggered, see `suppress_throttle` definition)

Proposed fix: add new method `parachute.release_inititated()`, `suppress_throttle` should check if `parachute.released_initiated()` instead of `parachute.released()`.

Correct me if my assumption is wrong. Otherwise, I'm happy to contribute a fix.

**Comment by magicrub** [comment]
There is probably about 100ms between those checks, are you saying that the throttle is giving you problems and you need that extra 100ms ?

**Comment by naktinis** [comment]
I'm saying that, from what I understand, throttle is currently not suppressed until the parachute is actually deployed. And I think we want to first suppress the throttle and only then deploy the parachute.

**Comment by naktinis** [comment]
Should be fixed by df922dacfa.
