### ISSUE TITLE
Copter: allow repositioning in CIRCLE mode

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#386]
User inputs should move the center of the circle around

**Comment by shortstheory** [comment]
I worked on a patch to change the radius of the circle from pitch input. The center of the circle can be changed from roll inputs, so I'll take care of this one too

**Comment by night-ghost** [comment]
Is not it better to the roll be control the rotation speed, and for repositioning to use the additional channel 7/8 mode, as it was in the original FeatureRequest - https://github.com/ArduPilot/ardupilot/issues/5450 ?

**Comment by Pedals2Paddles** [comment]
I would probably favor the roll input increasing or decreasing the ground speed rather than re-positioning too.  I'm not sure how you could use a single axis stick to re-position a copter in 2 axes of flight.

**Comment by shortstheory** [comment]
Seeing there isn't an issue for changing the angular velocity with the roll stick, can I file a PR for it anyway?

**Comment by Pedals2Paddles** [comment]
(To clarify, I think repositioning would be a great feature. I just don't think the roll axis is the solution, and the roll axis would be better suited for speed, which is another great feature). Repositioning requires 2 axes of control and is likely going to be much more complicated to do. 

> Seeing there isn't an issue for changing the angular velocity with the roll stick, can I file a PR for it anyway?

Absolutely. There isn't actually a requirement for a PR to have a corresponding issue.

**Comment by Naterater** [comment]
I really don't favor repositioning the circle. I think the industry standard (somewhat set by DJI's POI mode) has been that the stick inputs kind of override the aircraft/camera positioning, but do not affect the center of the circle. It would be difficult to know how much the center has been adjusted until 1/2 of a circle would be complete anyway.

**Comment by rmackay9** [comment]
Yes, I agree users probably don't actually want the center to move around.  they want the radius to be changeable easily.
