### ISSUE TITLE
Motor Test is broken in trunk (3.4)

### ISSUE THREAD

**Issue by rrr6399** [ArduPilot/ardupilot#3868]
We updated a couple of different Hexacopters this week with the 3.4 firmware from 4/4/2016. When we tried to run the motor test, it refused to run due to being at too low an altitude.Arming and everything else works fine.

**Comment by rmackay9** [comment]
Ok, thanks.  I suspect we have to set the desired-spool state to be "throttle-unlimited".

**Comment by magicrub** [comment]
There was a recent bugfix by Tridge for quadplane (https://github.com/ArduPilot/ardupilot/commit/9933069679caf5b6e77018093d780707e45130d4). Maybe it's related?

**Comment by OXINARF** [comment]
@rrr6399 Can you confirm this is still happening?

**Comment by rmackay9** [comment]
I've just tested the motors test on a quad with the latest beta and it seems to work.  The report that "altitude is too low" is very odd.  I can imagine that "throttle too low" could be a report.
In any case, it seems to work as far as I can tell so without any recent feedback that it's broken I'm going to close this issue.

**Comment by rrr6399** [comment]
I'll test it out this week once I get my hexacopter working again. I imagine if its working for Randy it should work for me as well.

**Comment by rrr6399** [comment]
Looks like it does work, although the initial power setting in Mission Planner isn't high enough to move the motors.
