### ISSUE TITLE
GPS arming check does not provide user feedback as to why it's failing

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#3879]
The ublox authentication of settings is working well, but users who encounter an arming issue due to it not being funny configured are left unsure how they are failing to configure it, and there are no meaningful messages to allow us to easily help them. Easily addressed with a LUT between the bitmask of what needs to be configured and messages. (Will only return the message for the first bit that needs configuration still)

**Comment by magicrub** [comment]
Make sure it will notify if a second GPS is not configured if enabled as
auto. That seems to be a popular problem.

**Comment by WickedShell** [comment]
This is in master
