### ISSUE TITLE
Guided Takeoff Crashes Hexacopter sometimes in 3.4

### ISSUE THREAD

**Issue by rrr6399** [ArduPilot/ardupilot#3881]
For firmware versions from at least since February 1/2016 and as recent as 4/2/2016, I've observed 3 crashes on two different S900 Hexacopters when performing the following MAVLINK actions:

1.) Arm in stabilize
2.) Switch to guided mode
3) Send msg_command_long with the following attributes set:
        msg_command_long cmd = new msg_command_long(this.systemId, componentId);
        cmd.target_component = MAV_COMPONENT.MAV_COMP_ID_SYSTEM_CONTROL;
        cmd.target_system = targetSystem;
        cmd.command = MAV_CMD.MAV_CMD_NAV_TAKEOFF;
        cmd.param3 = 0.0f;
        cmd.param4 = 0.0f; // yaw angle not used  currently
        cmd.param5 = (float)latitudeDeg;  // not used currently
        cmd.param5 = 0f;
        cmd.param6 = (float)longitudeDeg; // not used currently
        cmd.param6 = 0f;
        cmd.param7 = (float)2.0;
        cmd.confirmation=0;
        this.sendCommand(cmd);

When the command was issued the copter immediately yawed, rolled and pitched wildly until I disarmed it as shown here:
![yaw-pitch-roll](https://cloud.githubusercontent.com/assets/2707426/14405626/6349d09e-fe58-11e5-9fd4-8d26ecf497b4.png)

There are many other times, that this process has worked perfectly.  The only thing I noticed that may have contributed to the behavior was that the barometer was not zeroed during arming and registered 2.5 meters or so . I'm not sure what the takeoff mode would do if the copter needed to drop in altitude to achieve the takeoff altitude when it was already on the ground. Here's the altitude history:

![altitude-crash](https://cloud.githubusercontent.com/assets/2707426/14405667/7495d676-fe59-11e5-98bb-f7f21fb8e94f.png)

Here's the RCOUT history:
![rcout](https://cloud.githubusercontent.com/assets/2707426/14405688/89d2debc-fe59-11e5-83dd-3406412096eb.png)

Here's a set of graphs from a second S-900 copter that crashed using guided takeoff as well. This one's altitude was below 2 m initially so the initial altitude being higher than the target altitude may not be the problem:

![s900-1-crash-yaw-pitch-roll](https://cloud.githubusercontent.com/assets/2707426/14405790/8287792c-fe5b-11e5-83c0-83d682d32447.png)

![s900-1-altitude](https://cloud.githubusercontent.com/assets/2707426/14405791/8867ecaa-fe5b-11e5-98ab-e25a76fd52f0.png)

Also, both copter's accelerometers and compasses were calibrated prior to this test. They also flew perfectly if controlled by the R/C in Loiter mode.

**Comment by rrr6399** [comment]
In both crashes, it looks like the copter started spinning in yaw soon after the takeoff command was issued.

**Comment by rrr6399** [comment]
BTW, two of the three crashes had the R/C turned off. Don't think that's the problem the takeoff command has worked on my F550 without the R/C turned on. Also, the following fail safes were disabled:  FS_THR_ENABLE, FENCE_ENABLE. One copter had WP_YAW_BEHAVIOR=0 and the other had it set to 2. There appears to be some logic related to yaw where set_auto_yaw_mode(AUTO_YAW_HOLD). 

There was no RC INPUT for yaw registered in the logs as well.

**Comment by rrr6399** [comment]
I noticed that even though the target altitude was 2m, the design altitude grew to 4.54 m
![design-alt-to-barometric-alt-crash](https://cloud.githubusercontent.com/assets/2707426/14415679/65abbd4c-ff67-11e5-8d6f-51a7008b75fe.png)

**Comment by rrr6399** [comment]
I noticed that barometric and relalt pressure is off by a meter initially. The target altitude starts off at 1 m and then ramps to the actual target of 2m.
![alt-relalt-desalt](https://cloud.githubusercontent.com/assets/2707426/14415990/dd88c708-ff6a-11e5-80a3-9efb898576cb.png)

**Comment by rrr6399** [comment]
I noticed that the FCS seems to want to yaw after guided mode even though the pilot didn't command any yaw and there should be no yaw angle targeted:
![yaw-vs-design-yaw](https://cloud.githubusercontent.com/assets/2707426/14416038/667368fc-ff6b-11e5-8762-92037fc8ac45.png)

**Comment by rrr6399** [comment]
Here is how the yaw, pitch, roll and altitude history looks for the same copter during a successful guided takeoff:
![altitude-history-successful-guided-takeoff](https://cloud.githubusercontent.com/assets/2707426/14430728/5b741912-ffc8-11e5-85d2-1366efab26c0.png)
![roll-pitch-history-successful-guided-takeoff](https://cloud.githubusercontent.com/assets/2707426/14430734/5ffa9d8a-ffc8-11e5-92c5-3a0420914266.png)
![yaw-history-successful-guided-takeoff](https://cloud.githubusercontent.com/assets/2707426/14430736/62f7f7b2-ffc8-11e5-9939-129fbe213f96.png)

**Comment by havarjoh** [comment]
funny thing - same happens to me and this other guy, only it happens every time - and in gazebo: http://discuss.ardupilot.org/t/gazebo-sitl-drone-cant-controlled/8051
No resolution though.

**Comment by rrr6399** [comment]
havarjoh, did you notice the copter yawing hard on takeoff similar to the attached plots?

**Comment by havarjoh** [comment]
jup, but looking at the plots I have more extreme values. I almost got it working (no yawing) sending a "level" mavros command before "arm throttle" and "takeoff 2". Only it didn't stop on 2 meters, just kept on rising until it went crazy again (heavy yawing). Think I'll give px4 stack a try, documentation seems better on Gazebo stuff (though not so on other items).

**Comment by rrr6399** [comment]
@rmackay9 One pattern I'm seeing is that when channel 4 (yaw) of RCIN is 0 due to the R/C transmitter being turned off, sometimes the yaw rate is maxed out when switching to the guided mode takeoff. Could there be a bug where a RCIN value of 0 for Yaw is being mapped to a maximum Yaw (PWM 0) rather than PWM 500? I have seen these types of issues in the past where a 0 YAW or Pitch value is understood as maximum left yaw or maximum pitch.

It seems to only happen in certain conditions though since I have now seen the problem with an Iris and an S900, but not my F550. I never turn on the R/C with the F550 and have never seen the maximum yaw rate commanded on guided takeoff.

BTW, WP_YAW_BEHAVIOR is typically set to 0 and most of the fail safes are turned offf.

**Comment by rmackay9** [comment]
@rrr6399, yes it's quite possible that that's happening.  the desired-yaw (in the ATT) message should make it clear if that's happening.
There's currently two other issues that we're working on that are problems with Copter-3.4 so it's certainly not completely stable.  https://github.com/ArduPilot/ardupilot/pull/4046
I guess I'm just saying that although I haven't investigated this issue you're reporting much yet, it's still on my to-do list and I think we will get to the bottom of it before too long (some time during the beta testing period which is coming soon).

**Comment by rrr6399** [comment]
Here's a good example with the desired yaw, actual yaw and RC4 input for the problematic case where the R/C was turned off:
![yaw-history](https://cloud.githubusercontent.com/assets/2707426/15090069/e356a6a2-13e5-11e6-823a-e393b3c4ae8c.png)

**Comment by rrr6399** [comment]
@rmackay9 Any news on this? I am going to try duplicating it on my F550. The problem is easy to duplicate on an Iris and S900 for far by commanding a guided takeoff with the R/C turned off.

**Comment by rrr6399** [comment]
Another variable in the mix of these copters is the type of R/C receiver, which may explain the difference for my F550. My F550 uses the Spektrum AR8000 receiver coupled to the satellite receiver. When the R/C transmitter is turned off, the AR8000 sends the FS PWM of 913 for the throttle and also the last know PWM settings for all the other channels. For instance, YAW would be 1500 rather than 0. 

The S900 uses the Spektrum satellite receiver only, which I believe does not send any FS values. It sends no-data when the R/C transmitter is turned off. I believe the Pixhawk will still detect this as a loss of signal, but all the other channels may be 0 rather than the last known good position. 

I'm not sure how the Iris receiver radio responds to a turned off transmitter, but my guess is that it is similar to the Spektrum satellite receiver.

Also, during arming, my GCS sends the release R/C control message to the Pixhawk to guarantee that the GCS doesn't  still have control over the throttle, yaw, pitch and roll from a previous run (if the operator decided to use the GCS to control those functions.)

**Comment by govsux** [comment]
have you tested the RTL being triggered by shutting off the TX with a receiver set to no pulses???

**Comment by rrr6399** [comment]
More details are documented in this discussion.

**Comment by OXINARF** [comment]
@rrr6399 Like we came to the conclusion in the thread this was caused by you using no RC receiver and not using override values for all channels. You are free to open an issue requesting an enhancement to improve flying without an RC receiver.
