### ISSUE TITLE
Tools: install-prereqs-ubuntu.sh  script fails , needs updating

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#3894]
Tested on fresh install of Ubuntu 16.04
First : python-wxgtk2.8  is no longer available,  python-wxgtk3.0  should be  used.
Then the script command "sudo pip2 -q install $PYTHON_PKGS"   fail with :
"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o9DnpF/pymavlink/"

if the script got past that, next issues are:
Add /opt/gcc-arm-none-eabi-4_9-2015q3/bin to your PATH [Y/n]?Y
./install-prereqs-ubuntu.sh: line 85: grep: command not found
Add /home/andre/prog/ardupilot/Tools/scripts/ardupilot/Tools/autotest to your PATH [Y/n]?Y
./install-prereqs-ubuntu.sh: line 94: apt-cache: command not found

**Comment by magicrub** [comment]
> python-wxgtk2.8 is no longer available, python-wxgtk3.0 should be used

Is this a Python 2.x to 3.x change? That sounds like a significant change.

**Comment by AndKe** [comment]
no, nothing that drastic,  the default python is still 2.7.11  - just some upgraded libraries.

**Comment by lucasdemarchi** [comment]
@AndKe and you don't have grep in Ubuntu 16.04 even after installing build-essentials? Or is it because the apt-get call failed and then things weren't installed... ?

**Comment by AndKe** [comment]
@lucasdemarchi of course there is grep , it's used in many of my scripts all the time, - I assume it's something trivial with the syntax or something - that I can figure out in a spare moment..

**Comment by lucasdemarchi** [comment]
./install-prereqs-ubuntu.sh: line 85: grep: command not found

**Comment by AndKe** [comment]
@lucasdemarchi - yes, I do still see it, - let's forget the trivial stuff, (if that's a problem om more than one test computer, I'll fix it)
Now, if we can focus on a solution for the library-issue.  :)

**Comment by lucasdemarchi** [comment]
The thing is that I think the apt-get failed and then things that are needed weren't installed.

**Comment by AndKe** [comment]
sure it failed :)   - because python-wxgtk2.8 is not in 16.04 ...  :)   so  - what can we do about that ?

**Comment by lucasdemarchi** [comment]
Probably the same we did in CI scripts to differentiate 14.04 and 12.04: we parse the distro name from /etc/os-release and install the different SW based on that. If mavproxy (the one that actually use python-wxgtk) works with both versions, then we are done. Otherwise we would need some patches there, too.

**Comment by lucasdemarchi** [comment]
I can take a look into this on Monday if nobody implements it before.

**Comment by AndKe** [comment]
do we know all parts that need python-wxgtk2.8 , and whatever they do work with 3.0 ? (I am familiar with python dependencies & backwards compatibility)

**Comment by AndKe** [comment]
I can confirm that mavproxy (and --console) works fine with python-wxgtk3.0  
- will make a PR with the fix tomorrow.

**Comment by AndKe** [comment]
here: https://github.com/ArduPilot/ardupilot/pull/3917

**Comment by peterbarker** [comment]
I think we must be all good for this by now :-)
