### ISSUE TITLE
Feature Request, Rallypoint Pass through to Home

### ISSUE THREAD

**Issue by Jman841** [ArduPilot/ardupilot#3895]
Currently from my understanding if I set a rallypoint with Arduplane the plane will hit RTL then go to this point and loiter there until I give it another command. I would like the desired action for the plane to go first to the nearest rallypoint then continue to Home. This is desired just in case for some reason I do not have telemetry link at the desired rallypoint. or for some reason I need to use the RC Controller but the rally point is at a point that is beyond line of sight.

Platform: Copter and Plane

Thank you,

Jason

**Comment by iskess** [comment]
This would also help when flying alongside a tall mountain ridge. An RTL to home could cause the plane to turn into the cliff wall. Rally Points could be used to assure that with a radio failsafe at any point, the closest heading to is always away from the cliff. 
This request would allow the plane to then return home after the rally. 
Actually this is still just a work around. A better solution to my case would be general Cardinal direction that could be entered to control the direction of the initial turn of an RTL.

**Comment by iskess** [comment]
Maybe we just need to incorporate DO_LAND_START to work with a Rally point so the plane will head to the approach sequence which is at home.

**Comment by Jman841** [comment]
I don't want it to start the landing sequence right away. I always set RTL before beginning the landing to ensure everyone is ready and the runway is clear. Simply for it to use the rally point as a pass through in case there is an obstacle where a direct line back to RTL is not a good option, then head to RTL. The only thing I would like to see is the set altitude for the rally point to be maintained all the way through to RTL.

**Comment by IamPete1** [comment]
I think the existing DO_LAND_START functionality would allow this?

**Comment by peterbarker** [comment]
@IamPete1 pretty sure.

Closing this.
