### ISSUE TITLE
Req: CAMERA_FEEDBACK should contain shutter count

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#3903]
Shutter feedback should be counted and a part of this message.
This way operator could easily see not only how many times camera was expected to shoot (img_idx) , but also how many time the shutter actually operated.

![screenshot from 2016-04-15 14-42-46](https://cloud.githubusercontent.com/assets/1468842/14561677/5f10e642-0318-11e6-90bd-4e618021bac5.png)

**Comment by WickedShell** [comment]
Agreed, this is a very good canidate for MAVLink 2 extensions. This is actually on my radar, and will probably be what forces me to implement Java MAVLink2 support.

**Comment by AndKe** [comment]
:+1:

**Comment by AndKe** [comment]
compiled master today. 
All I see in mavproxy is:
CAMERA_FEEDBACK.alt_msl        CAMERA_FEEDBACK.foc_len        CAMERA_FEEDBACK.pitch          CAMERA_FEEDBACK.yaw
CAMERA_FEEDBACK.alt_rel        CAMERA_FEEDBACK.img_idx        CAMERA_FEEDBACK.roll           
CAMERA_FEEDBACK.cam_idx        CAMERA_FEEDBACK.lat            CAMERA_FEEDBACK.target_system  
CAMERA_FEEDBACK.flags          CAMERA_FEEDBACK.lng            CAMERA_FEEDBACK.time_usec 

why ?

**Comment by OXINARF** [comment]
@AndKe Probably because you didn't enable MAVLink2.

**Comment by AndKe** [comment]
@OXINARF 
I connected to current AC master in SITL: - (all links set to Mavlink2 & restarted)  (then let QGC connect using UDP to run the mavlink inspector for graphic presentation:)
![screenshot from 2018-03-20 17-39-43](https://user-images.githubusercontent.com/1468842/37668967-f80388e6-2c65-11e8-8864-03d0e44ae283.png)

**Comment by OXINARF** [comment]
It's quite likely that QGC doesn't support the MAVLink extension yet.

**Comment by AndKe** [comment]
QGC got it's submodules updated recently, but more importantly:

I've also build mavproxy from master, and:  (it's not even an option)  - actually, that's where I tried first.

```
STABILIZE> graph CAMERA_FEEDBACK.
CAMERA_FEEDBACK.alt_msl        CAMERA_FEEDBACK.flags          CAMERA_FEEDBACK.lat            CAMERA_FEEDBACK.roll           CAMERA_FEEDBACK.yaw            
CAMERA_FEEDBACK.alt_rel        CAMERA_FEEDBACK.foc_len        CAMERA_FEEDBACK.lng            CAMERA_FEEDBACK.target_system  
CAMERA_FEEDBACK.cam_idx        CAMERA_FEEDBACK.img_idx        CAMERA_FEEDBACK.pitch          CAMERA_FEEDBACK.time_usec 
```     
Do we agree that mavproxy has updated mavlink2 ?

**Comment by WickedShell** [comment]
@AndKe I haven't upstreamed the extensions to the mavlink/mavlink repo yet. At the moment they are living in https://github.com/ArduPilot/mavlink and QGC doesn't point at that mavlink fork. I can't speak to where MAVProxy/pymavlink are drawing the protocol files from...

**Comment by AndKe** [comment]
Ah, thanks - in that case, I should be more patient :)

**Comment by OXINARF** [comment]
MAVProxy uses pymavlink and, AFAIK, there hasn't been a pymavlink release that includes the updated message. You can install a development version of pymavlink and then try again with MAVProxy (make sure it is using MAVLink2, I'm not sure if you need to pass `--mav20` or not).
