### ISSUE TITLE
Stay-out zones for geofencing

### ISSUE THREAD

**Issue by acetylcysteine** [ArduPilot/ardupilot#391]
It would be great if you could create a fence that instead of keeping you inside, kept you outside. For example, there is a huge tree in the middle of an open field. Create a radius and altitude fence around this tree so if you start flying into it the aircraft is redirected.

**Comment by aerodolphin** [comment]
This is a very good feature to add. Will increase the safety of flights. It will be very useful to mark on the mission map no-fly zones (set with a radius and height or a polygon and height) to mark tall buildings, trees, antennas or other places.

**Comment by FLYBYME** [comment]
+1

**Comment by dscassid** [comment]
I agree! Is there any progress on this?

**Comment by kd5ftn** [comment]
I have an application where I would like autonomous flight over an area but would like to avoid pre-defined tall objects such as towers or particular trees. A "keep out" or exclusion zone would be sort of an inverse geofence, so if the Path between waypoint 1 and 2 were to intersect this zone, the autopilot would maintain distance and either follow the perimeter of the zone, or compute a more efficient route that avoids it entirely. Is anyone actively working on this? I may be able to help fund development of this feature.

**Comment by magicrub** [comment]
Sounds like a great feature

**Comment by rmackay9** [comment]
I'm tentatively targeting Copter-3.4 for this feature but no promises

**Comment by rmackay9** [comment]
Pushing to AC3.5.  We just ran out of time for AC3.4.

**Comment by lvale** [comment]
@rmackay9 

I might be seeing this issue wrong, but don't we already have all the code infrastructure validated, verified and in place for this ? If the polygon fence checks if it's inside, couldn't we just check if we're outside. Than we could even use a fence type to determine if it's a fly inside/fly outside polygon fence ??

**Comment by rmackay9** [comment]
@lvale, yes, we have about 70% of what we need.  What we're missing is just a way to store lots of individual shapes to act as stay-out-zones.  So that's probably going to need some new mavlink messages and some work on storing the shapes.  A lot of re-use of the polygon fence code is possible.

**Comment by lvale** [comment]
@rmackay9 I would start with a KISS approach. One single polygon stay-out zone. I sincerely think that it would cover a large percentage of the use cases and would gets us some time to rethink (if required) a more comprehensive approach. All the current options (except height) used for fence could be re-used but with reversed functionality, ie stay-out instead of stay-in

**Comment by DonLakeFlyer** [comment]
We whould merge this in with the discussion around standardizing the mavlink protocol for sending fence points.

**Comment by Naterater** [comment]
Did the outback challenge "Exclusion zones" have any affect on this?

**Comment by auturgy** [comment]
Leave this open unless there’s a duplicate.
There was a bunch of work (mainly by Don, input from @wickedshell) to design a new fence protocol that facilitates this, which is implemented in qgc but not ArduPilot. The OBC work is part of the way to getting it in, but that work hasn’t been merged.

**Comment by NoYoungRea** [comment]
> Leave this open unless there’s a duplicate.
> There was a bunch of work (mainly by Don, input from @WickedShell) to design a new fence protocol that facilitates this, which is implemented in qgc but not ArduPilot. The OBC work is part of the way to getting it in, but that work hasn’t been merged.

it is possible in the qgc? new fence protocol? how can i do that? i already download qgc, but i can't find that function!

**Comment by auturgy** [comment]
I’m not sure of the current status.
@peterbarker has been working on it.

**Comment by lvale** [comment]
> it is possible in the qgc? new fence protocol? how can i do that? i already download qgc, but i can't find that function!

At the moment ArduPilot fence is not supported on QGC

**Comment by rmackay9** [comment]
Support for inclusion and exclusion polygon and circles is in master for Copter and Rover and will go out with version 4.0.0 in the coming weeks.  Thanks @peterbarker!

**Comment by DonLakeFlyer** [comment]
Thanks everyone
