### ISSUE TITLE
Common: Implement Follow-me by Mavlink msg

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#3929]
Now that the accorded Mavlink message has gone into Mavlink, we should think on implementation on Copter/Plane/Rover

https://github.com/mavlink/mavlink/pull/526/files

**Comment by lvale** [comment]
Having this @rmackay9 would be a solution for the users that were using the broken Tower solution

**Comment by lvale** [comment]
@peterbarker would enable a free alternative solution to use follow-me on mobile devices

**Comment by peterbarker** [comment]
On Mon, 20 Aug 2018, Luis Vale Gonçalves wrote:

> @peterbarker would enable a free alternative solution to use follow-me on
> mobile devices

Sorry, I wasn't clear.

If Tower already supports these messages then yes, supporting those 
messages in AP would allow a follow-me.

However, if Tower doesn't already support those then it could just as 
easily support follow-mode by broadcasting its position and setting the 
parameters appropriately.

**Comment by lvale** [comment]
Sorry I wasn't clear also.
QGC supports this now, and it could be an alternative on mobile devices.

**Comment by auturgy** [comment]
No reason to close. It’s a valid enhancement request.

**Comment by rmackay9** [comment]
I think this is a duplicate of this other issue so let's close it: https://github.com/ArduPilot/ardupilot/issues/8517
