### ISSUE TITLE
sim_vehicle.sh rebuilds library on reboot

### ISSUE THREAD

**Issue by arashn** [ArduPilot/ardupilot#3936]
sim_vehicle.sh rebuilds the library every time the system is rebooted. This happens because the compiled files are stored in the /tmp directory, which is cleared upon a reboot.

This happens on a machine running Fedora 23.

**Comment by guludo** [comment]
@arashn We'll soon rewrite sim_vehicle to a python version and use Waf for building. That problem should be solved by then.

**Comment by arashn** [comment]
Testing with the latest version of ArduPilot, this issue has been fixed. Thank you.
