### ISSUE TITLE
change Default BRD_SERX_RTSCTS to 0

### ISSUE THREAD

**Issue by falconunmanned** [ArduPilot/ardupilot#3940]
#### Issue details
We run the pixhawk comm through modems using only the TX/RX/GND pins.  We used to see that about 1 out of 10 boots of the autopilot the Commport did not boot properly (witnessed as no data over a serial terminal program).  After being pointed at the BRD_SERX_RTSCTS param we change ours from what was the default of 2 to 0.  I completed 50 reboots using this "0" setting and did not see an issues.

#### Version
Currently running Copter 3.2 and Plane 3.2.2 on Pixhawk

#### Platform
Currently running Copter 3.2 and Plane 3.2.2 on Pixhawk

#### Airframe type
Plane and Copter for me

#### Hardware type
Currently running Copter 3.2 and Plane 3.2.2 on Pixhawk

#### Logs
Not Applicable.

**Comment by magicrub** [comment]
This flow-control bug was reported here (https://github.com/ArduPilot/ardupilot/issues/2532) and fixed here (https://github.com/ArduPilot/ardupilot/pull/2556) so it was fixed after Copter 3.2 and Plane v3.2.2 releases so I'm closing this. @falconunmanned please update to Plane v3.5.2 and use BRD_SERx_RTSCTS=2 and reopen if you're still having problems.
