### ISSUE TITLE
Building ArduPilot for Pixhawk/PX4 on Linux with Make

### ISSUE THREAD

**Issue by sgh055** [ArduPilot/ardupilot#3999]
Hi, I have some problem.

I followed Building ArduPilot for Pixhawk/PX4 on Linux with Make(http://ardupilot.org/dev/docs/building-px4-for-linux-with-make.html). but When I make px4-v2, I got a error message.
How can i fix that? I installed all of them

This message.
![image](https://cloud.githubusercontent.com/assets/15629613/14873956/83505bd2-0d36-11e6-86f5-c721dec00271.png)

**Comment by kwikius** [comment]
It looks like arm-none-eabi-gcc which is the compiler for this board is not installed correctly. Check the bin directory the messages are telling you and see if there is a arm-none-eabi-gcc ( and other similar tools) in there

**Comment by sgh055** [comment]
@kwikius 
![20160428_130731](https://cloud.githubusercontent.com/assets/15629613/14875883/5663d7de-0d4a-11e6-99f3-3d2e9eb1a348.jpg)
I try to this command 'arm-none-eabi-gcc --version' but they say "no such file or directory"

however, there exist file.
![20160428_130853](https://cloud.githubusercontent.com/assets/15629613/14875941/fbf6ed6c-0d4a-11e6-9f6f-91e7e8be3eaa.jpg)
what is mean??

**Comment by WickedShell** [comment]
It's not being found in the search path. Check where you're $PATH points,
it needs to point into that directory for the tools to be found.

**Comment by sgh055** [comment]
![image](https://cloud.githubusercontent.com/assets/15629613/14878798/bd66c7dc-0d60-11e6-93e0-f49bb3c55349.png)
@WickedShell  you say this? ~/.profile

**Comment by OXINARF** [comment]
I think you need to install libc6-i386

**Comment by sgh055** [comment]
@OXINARF Thank you! OXINARF
It is working!
