### ISSUE TITLE
potential ekf2 height estimate source issue

### ISSUE THREAD

**Issue by haogodent2** [ArduPilot/ardupilot#4013]
#### Issue details
EK2_ALT_SOURCE = 0 doesn't seem to be respected. following graph indicate that the estimate uses GPS height rather than BARO height. Please let me know if I'm missing something.

![ekf height estimate tracks gps alt ek2_alt_source 0](https://cloud.githubusercontent.com/assets/3250056/14927818/06c8a988-0e09-11e6-9ef2-a5a5472947f0.PNG)

#### Version
modified version of plane 3.5.0 without modifications to EKF2

#### Platform
- [ ] Plane

#### Airframe type
flying wing

#### Hardware type
pixhawk

#### Logs
https://drive.google.com/open?id=0ByzCCFD6pQ3zMXZMa2tXTnl0bjA

**Comment by tridge** [comment]
The GPS.RAlt field is not from the GPS, despite the name. That is the current relative alt. It is GPS.Alt that is from the GPS.
I've actually removed the RAlt field last week, as it was just confusing.
