### ISSUE TITLE
Rover: fix up the SPEED2THR_ parameter and associated documentation

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#4014]
#### Issue details

Currently in the Rover in the Parameters.cpp file there is no doco associated with SPEED2THR PID controller and there needs to be.
#### Version

All
#### Platform

Rover

**Comment by rmackay9** [comment]
I think I'll close this.  Rover-3.2 has all new controllers so this parameter doesn't exist any more.  I think all the parameter descriptions are visible for the new controllers.
