### ISSUE TITLE
waf: reconfigure should be automatic

### ISSUE THREAD

**Issue by lucasdemarchi** [ArduPilot/ardupilot#4025]
Whenever the waf's wscripts change (or any waf tool) we need to reconfigure automatically with the last configuration passed.

This is because calling "waf configure" explicitly should be done only when the user want to change some thing, and not when he rebased his branch and possibly got updates from upstream.

Probably this info helps:
https://groups.google.com/forum/#!topic/waf-users/XQDz5VDQSr8

**Comment by OXINARF** [comment]
I think this was done in #4367
