### ISSUE TITLE
Copter: Prevent Auto-Mode Tipovers caused by missing takeoff command

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#4039]
Currently, it is possible to have a mission programmed, where the first command is a waypoint.  And it is possible to begin the mission while the copter is sitting on the ground.  This will cause the copter to tip over as it tries to fly laterally while still on the ground.

We should protect against this.

I had one mission which began with a takeoff, and then fly around.  I began the mission, it took off, started flying, and then I aborted the mission for another reason.  I flew it back manually, landed, but did not disarm.  I then switched back to auto, and this is when it tried flying to the next waypoint.  So we need to protect for this scenario.

The system should deny a mode switch to auto any time it is on the ground and the next command results in lateral flying.

**Comment by OXINARF** [comment]
Fixed by #4102.
