### ISSUE TITLE
Trigger camera directly from APM/PX4  for Canon, Ricoh cameras

### ISSUE THREAD

**Issue by clipo** [ArduPilot/ardupilot#407]
While the current code allows a servo and relay type triggers for a camera, some cameras can be triggered directly with combinations of binary signals. These are a bit different than the CHDK type triggers available for Canon.  For example, Ricoh cameras -- excellent choices for photogrammetric purposes given their weight, simple trigger, quality lens and other features -- are triggered with a 150 ms high value followed by series of 30ms release pulses (from http://infar.be/index.php?/archives/765-Arduino-as-a-remote-shutter-release-for-RICOH-cameras.html) . The code is shown below. Right now one could rig up a separate arduino micro to listen for the signal and then do a subsequent camera trigger but that seems like an unnecessary addition requiring power, more wires and so on. In the long run it would be better to allow the APM to do the triggering itself (since its now getting to the point where the auto triggering by distance should work well and provide great coverage). 

I can imagine having a series of signals for IR leds as well - many cameras can be triggered through IR. See http://sebastian.setz.name/arduino/my-libraries/multi-camera-ir-control/ for a huge list of cameras and the IR codes needed to trigger them.

Could this be added to the current code base? It seems like the best way would be to abstract the triggers (both servo, relay and other) from the cameras and then allow different configurations for different camera set ups. What would be the best way to do this?

// example of trigger
void loop()
{
     fullpress();
     release();
     sleep(2000);
}

//--------------------------------------------------------------------|
// For Ricoh cameras -- trigger the photo to be taken
// Sends a 150ms pulse to indicate full press                         |
//--------------------------------------------------------------------|
void fullpress(void)
{
  digitalWrite(outPin, HIGH);
  delay(150);
  digitalWrite(outPin, LOW); 
}

//--------------------------------------------------------------------|
// Sends two 30ms pulses to indicate button release                   |
//--------------------------------------------------------------------|
void release(void)
{
  digitalWrite(outPin, HIGH);
  delay(30);
  digitalWrite(outPin, LOW); 
  delay(30);
  digitalWrite(outPin, HIGH); 
  delay(30);
  digitalWrite(outPin, LOW);
}

**Comment by jmachuca77** [comment]
Camera trigger boards have taken care of this thus far. I think we can close this issue. Please reopen if not true
