### ISSUE TITLE
How to use ADC in APM 2.7.1

### ISSUE THREAD

**Issue by sriramgbhagwat** [ArduPilot/ardupilot#4089]
#### Issue details
i want to use the ADC to read the voltage and also to display the voltage in mission planner for example i want to use a temperature sensor to give voltage as input and want to see that values in Mission planner can this be possible? Also can i add new ADC value in status bar? please guide me how to do this.....thank you. 

#### Version
_What version was the issue encountered with_

#### Platform
[ ] Copter

#### Hardware type
_What autopilot hardware was used? (APM 2.7.1)

**Comment by magicrub** [comment]
Hi there,
You've asked a help question through the developers bug tracking system.
Please use the forums instead at http://discuss.ardupilot.org
