### ISSUE TITLE
sim_vehicle.py /w waf /w eclipse project broken on Cygwin

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4093]
![simvehiclepyfail](https://cloud.githubusercontent.com/assets/4782875/15187982/5fbf6a56-1758-11e6-90d2-35904a2095e3.png)

When using sim_vechile.py, which defaults to using waf, the build fails because it is confused about eclipse project files.

**Comment by OXINARF** [comment]
#4099 seems to be another case of this problem

**Comment by lucasdemarchi** [comment]
This should now be fixed by #4111 and the double configure I see in the image above by #4100.
