### ISSUE TITLE
Need ratio for different throttle output for coaxial copter

### ISSUE THREAD

**Issue by lokanaft** [ArduPilot/ardupilot#4130]
#### Platform
- [x] Copter
#### Airframe type

Coaxial

I test two coaxial motors on thrust stand with different throttle level and found with same thrust 500gr:

| Throttle level _M1 / M2_ | Current |
| --- | --- |
| 50% / 50% | 2A |
| 47% / 52% | 1.85A |
#### How I see to use it:
1. Set "Ch6 Opt" for this ratio function parameter
2. In flight "Loiter" try different ratio with Ch6
3. After, open log and find minimal current, find for this moment Ch6 level and set value for this parameter forever

**Comment by lthall** [comment]
Duplicate #2479

**Comment by lokanaft** [comment]
No, not duplicate, absolutely different

**Comment by IamPete1** [comment]
This is possible in flight via the new dynamic scripting motors back-end, happy to help with the lua script if anyone wants to give it a try. In the mean time I will close this.
