### ISSUE TITLE
Copter: support acceleration control via SET_POSITION_TARGET_LOCAL_NED

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#4134]
Add support for acceleration targets (from the GCS or companion computer) received via the SET_POSITION_TARGET_LOCAL_NED and SET_POSITION_TARGET_GLOBAL_INT commands.
http://mavlink.org/messages/common#SET_POSITION_TARGET_LOCAL_NED
http://mavlink.org/messages/common#SET_POSITION_TARGET_GLOBAL_INT
#### Version

These are not supported in Copter-3.4
#### Platform
- [ x] Copter

**Comment by jagrandle** [comment]
+1  This would be a great enhancement. We would like to be able to set yaw speed as desired.

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/17539
