### ISSUE TITLE
Question - Source for SET_POSITION_TARGET_LOCAL_NED

### ISSUE THREAD

**Issue by alexblack** [ArduPilot/ardupilot#4153]
Hi, I'm trying to get my 3DR Solo drone to make precise movements (without GPS) by sending the `SET_POSITION_TARGET_LOCAL_NED` message.

Where can I find the source for this so I can get a better sense of how its implemented? I am not familiar with the ArduPilot source yet.

Thanks!

**Comment by rmackay9** [comment]
I'm afraid the EKF only knows it's position and velocity if it has a GPS attached (or an optical flow).  It's not possible for it to know these values just from the IMU.

As a side note, we get this question pretty much once per week at the minimum.  We should probably put something on the wiki somewhere to answer this.

**Comment by alexblack** [comment]
Thanks for the response Randy, my question was about where to find the source, any suggestions?

**Comment by rmackay9** [comment]
@alexblack, Ah ok.  I was perhaps jumping ahead.  In any case, here's where the POSITION_TARGET message comes in. https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L1691

**Comment by alexblack** [comment]
Cool, thanks @rmackay9 !
