### ISSUE TITLE
Make an option to have Home be 'Permanent' if within 200m of current location at boot.

### ISSUE THREAD

**Issue by KD2DEY** [ArduPilot/ardupilot#416]
I am creating a new request that was originally made by me in August 2010 in the original Ardupilot issues section here. http://code.google.com/p/ardupilot/issues/detail?id=12

Things have changed somewhat since I originally requested this feature back in 2010. It appears that the feature was added at some point, but no-one seems clear on its operation.
This is what I suggest; we need something both convenient and safe. Since a large number of users tend to fly at the same field repeatedly, and their flying sites have rules not allowing flight behind the flight line, I would suggest the following:

1) The mission planner be used to set the desired home position along with a mission file, which can then be uploaded to the APM.

2) Upon boot and 3D lock the APM checks the stored home position and compares it's location to the current location. If the stored location is within 200m of the current location, wag the ailerons, then use the stored location. If the stored location is greater than 200m from the current location, wag the elevator, then overwrite the stored location with the current location and use it as home.

I think 200m is a safe distance, keeping the plane within sight at all times while not being overly close at the same time. The user might have a home location he defines in the MP where his loiter radius is 45m and he sets home at 80m (by mouse click). Or he might choose to place home further out, so long as he doesn't exceed 200m from the location where the APM boots up. Then on subsequent flights either on the same day or on other days he would retain the stored home location as long as the boot location was within 200m and the mission file hadn't changed. This would also require that the mission planner always uploads a home location.

NOTE: For those that don't use the Mission Planner or Telemetry, this feature should probably have a parameter allowing the user to either turn it on or off.

This feature has been discussed recently here http://diydrones.com/forum/topics/creating-a-switch-to-set-home?commentId=705844%3AComment%3A1314169&xg_source=msg_com_forum .

**Comment by rmackay9** [comment]
This related issue: #1677 is in master now and will go out with AC3.3.  It still relies on GCS changes to send the do-set-home message when we want to "lock" the home position.
This isn't implemented for plane at the moment.

**Comment by jmachuca77** [comment]
Support implemented on #1677
