### ISSUE TITLE
How to set pwm output range

### ISSUE THREAD

**Issue by RaviPrasadWA** [ArduPilot/ardupilot#4167]
#### Issue details
I want to control servo from ch1 , ch2 , ch3 , ch4 the servo i think respond to timing between 0-1024 so is there a way in the code libraries/AP_Motors to set RC_Output range or map( scale) the output to 0-1024 range ?

#### Version
v3.2.1

#### Platform
- [ ] All
- [ ] AntennaTracker
-  [x] Copter
- [ ] Plane
- [ ] Rover

#### Hardware type
ArudpilotMega APM2

**Comment by OXINARF** [comment]
@RaviPrasadWA We don't support APM boards anymore. Also this issues list is used as a TODO list for the developers, not for questions. You can post in the forums (http://discuss.ardupilot.org) or you can try to get an answer in Gitter.
