### ISSUE TITLE
ArduPlane: Set displayed altitude to zero on 3D GPS lock?

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/ardupilot#417]
Currently on ArduPlane, once a 3D GPS lock is attained, the HUD altitude lists altitude above sea level (ASL) by default. There is an option however, to go to the Flight Data screen, find the Actions tab and then click on "Set Home Alt" which sets the HUD altitude to zero. 
This ensures that all subsequent altitude (and OSD) readings are relative to the ground/takeoff position or AGL.

In ArduCopter this is the default.

Please could the same be done in ArduPlane?

**Comment by MR444** [comment]
Hi, today I built my first airplane with arduplane so I found this thread.

In OSD setting, I set up home altitude and above sea level but both are almost the same. Home altitude shows 73m and above sea 76m. Why is home altitude not set to zero? With all my copters, home altitude is always zero after GPS lock.

So I do not understand why this should be an ground station issue.
Arduplane V3.8.5 - fixed wing with Pixhawk

![alt osd](https://user-images.githubusercontent.com/17322455/39668613-525ebce4-50d2-11e8-9f19-2b306897990e.JPG)
