### ISSUE TITLE
RC_UART

### ISSUE THREAD

**Issue by parvu** [ArduPilot/ardupilot#4170]
#### Issue details

tried to run RC_UART on PX4-V1 with input data from qualcomm snapdragon.
can not get ESC_MAGIC  F7 
#### Version

_What version was the issue encountered with_
#### Platform
- [ ] All
- [ ] AntennaTracker
- [ ] Copter
- [ ] Plane
- [ ] Rover
#### Airframe type

_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
#### Hardware type

qualcomm snapdragon + px4-v1
#### Logs

_Please provide a link to any relevant logs that show the issue_

**Comment by WickedShell** [comment]
Closing as support for Qualcomm snapdradon has been dropped.
