### ISSUE TITLE
Copter: implement failsafes simulation through CH7 and CH8.

### ISSUE THREAD

**Issue by Olivier-ADLER** [ArduPilot/ardupilot#419]
Some users are testing the radio failsafe strategy powering off the transmitter.

This is a dangerous situation because :
- some transmitters are manipulating channels in a hazardous way during power off, inducing some wrong channels value at the receiver side just before receiver failsafe. This can translate to a disarm during flight : if the receiver switch to acro or stabilize mode just before receiver failsafe (throttle = 900) and unfortunately the user did have throttle low when he did switch off the receiver.
- it is very long (many seconds) to power on a transmitter and pair it with the receiver if something goes wrong.

Using a clean failsafe simulation using CH7 or 8 will be a safe way to test failsafe behavior.

**Comment by OXINARF** [comment]
This is an old issue and although we don't usually close feature requests, I'm closing this one for the following reasons:

- after almost 4 years, it doesn't seem in high demand (nobody commented on it and I haven't seen a similar request anywhere recently)
- I don't see how it could be safely implemented: ArduPilot supports two ways that the radio receiver can communicate it lost contact and there is no way ArduPilot can know which one the user is using; this means we could simulate a radio contact loss but then in real flight the receiver used another that didn't work correctly
- most of the time it is the receiver that is improperly configured and simulating a radio contact loss doesn't test the receiver configuration

Testing radio failsafe shouldn't be too hard, I think that if a user disables the automatic disarm feature, it can even be tested on the ground.

If you feel this is still in need, please comment and we can further discuss it.
