### ISSUE TITLE
Mavlink 2.0 not found

### ISSUE THREAD

**Issue by Shaofuhw** [ArduPilot/ardupilot#4207]
#### Issue details
Hi, updated to current master today, and tried to build the code, but:
include/mavlink/v2.0/ardupilotmega/version.h: No such file or directory.
If you go to the include directory, there's only a v1.0 folder, with is currently this one:
https://github.com/ArduPilot/PX4Firmware/tree/49988db62fd11c9c512cfba8fa8257f1290a6f9c/mavlink/include/mavlink

#### Version
master

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quad

#### Hardware type
Pixhawk

**Comment by OXINARF** [comment]
That MAVLink isn't used, our own submodule is. Have you updated the submodules?
This isn't the place for support questions, so if you need any help you are welcome to post in our forums (http://discuss.ardupilot.org) or in Gitter.
