### ISSUE TITLE
Copter pulses on Motor test

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#4212]
#### Issue details
While performing motor test via MP all the motors twitch a little when a motor test button is clicked
#### Version
3.4master 25-5

#### Platform
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quad
#### Hardware type
PixRacer

#### Logs
N/A

Already discussed and detected that a pulse is sent to all the motors
Using BLHeli 14.6 firmware on ESC's (Silabs CPU - XRotor20A) - using OneShot and THR_MIN/MAX 1000/2000 manually set both on the ESC and Ardupilot
<img width="800" alt="screen shot 2016-05-26 at 03 01 12" src="https://cloud.githubusercontent.com/assets/3130363/15561541/fa69bd4e-22ee-11e6-8d44-9aab5cc85523.png">

**Comment by tridge** [comment]
Hi Luis, I think this is fixed now. Can you please test master again on your quad?
I'd also like to know if OneShot125 is working for you again

**Comment by lvale** [comment]
Stranger...

Cleared everything, redid calibrations (radio and accels) and I've setup the parameters as in the file attached.

Attached logic analyses reflects the following actions:
Plugin battery, Wait for the ready tone on the Racer, press the safety button, motors start twitching, even not armed. Armed and raised throttle to max twice and motors still twitching. Disarmed and motors still twitching. Pressed safety switch and motors keep twitching. 

Only way to stop is to disconnect battery.


[GH issue.zip](https://github.com/ArduPilot/ardupilot/files/283394/GH.issue.zip)

**Comment by lvale** [comment]
https://github.com/ArduPilot/ardupilot/commit/53fc095d4ce6ac0783acfb7394d3187502a43530

should be enough to address issue
