### ISSUE TITLE
Using compass with no compass connected is buggy

### ISSUE THREAD

**Issue by dgrat** [ArduPilot/ardupilot#4215]
#### Issue details

Setting a primary compass leads to UB if the compass is not connected.
E.g. the barometer calibration starts in endless loop :D
#### Version

Emlid master version
#### Platform

Probably all, but tested with Copter.
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

X4
#### Hardware type

Navio2
#### Logs

_Please provide a link to any relevant logs that show the issue_

**Comment by peterbarker** [comment]
We've rewritten compass detection several times since this was created.  Should be good now.
