### ISSUE TITLE
ArduCopter-quad FrSky Telemetry Support Telem2 port output protocol 3 or 4

### ISSUE THREAD

**Issue by philippelecoq** [ArduPilot/ardupilot#4220]
#### Issue details
ArduCopter-quad  FrSky Telemetry Support Telem2 port output protocol 4 don't support all mavlink messages:
You can read here : http://ardupilot.org/copter/docs/common-frsky-telemetry.html
Missing: GPS date&time  , AccelX,Y,Z  , CELLS  , RPM  , Air speed  , Vertical speed 
I note that there is still more missing values :
With NAVIO+ and ArduCopter-quad 3.4 dev  I can read only 9 telemetry values : **Galt , Alt, Hdg, Tmp2, Tmp1, VFAS, GPS, Curr, Gspd ** 
compared  with AIREBORNE converter  https://www.airborneprojects.com/product/apm-mavlink-to-frsky-smartport-converter/ I can read 14  telemetry values 

Could you explain why only 9 telemetry values with output protocol 4 Telem2 port ?

#### Version
ArduCopter-quad 3.4 dev
NAVIO+
TARANIS X8R (protocol 4) / X9D
www.mypidrone.com

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
QUAD

#### Hardware type
RASBERRY PI2 NAVIO+ / raspian Jessie kernel 4.4

#### Logs
no log

**Comment by OXINARF** [comment]
This isn't the proper place for making questions, for that you should use the forum (http://discuss.ardupilot.org) or, in last case, Gitter.

The FrSky protocol has specific telemetry it looks for. You can hack it to send other values, and ArduPilot already does that for some values, but it isn't the perfect solution. Anyway, there are, at least, two open PRs to improve the FrSky library.
