### ISSUE TITLE
Copter: 3.4-rc1 safety switch not obeyed on pixracer

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#4242]
[bin_tlog_param.zip](https://github.com/ArduPilot/ardupilot/files/293140/bin_tlog_param.zip)

#### Issue details
Safety switch action, Can arm without safety switch enabled. Safety switch does not switch off motors if armed.

#### Version
3.4RC1
#### Platform
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Copter Quad
#### Hardware type
PixRacer

**Comment by WickedShell** [comment]
Any more details? I have no clue what this is about...

**Comment by lvale** [comment]
Safety switch is ignored. I'm in the process of retrieving logs.

**Comment by magicrub** [comment]
Doh!

**Comment by magicrub** [comment]
I made a change to this recently so I must have broke it. Sorry!
On Jun 1, 2016 7:46 AM, "Tom Pittenger" <tom@airphrame.com> wrote:

Doh!

**Comment by magicrub** [comment]
I just tested it in plane and it works fine. Can someone else test master
on copter and report back?

**Comment by lvale** [comment]
What was the change that caused the issue ?? I can try it as soon as the build server has a copter-quad version, my compilation environment is broken :)

**Comment by magicrub** [comment]
This commit:
https://github.com/ArduPilot/ardupilot/commit/67aaf7e226fd1ac9d6acd3589a53e962dab91588

**Comment by lvale** [comment]
I was talking with Tom, and the issue is NOT common to all the FC. It only happens on the PixRacer.

**Comment by rmackay9** [comment]
This is fixed now I think right?
