### ISSUE TITLE
NMEA mode don't work with multi-system modules (eg. mt3333)

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/ardupilot#4243]
#### Issue details
because in AP_GPS_NMEA.cpp data compared with GPVTG GPRMC etc so ARDUPILOT want to listen NMEA v2. But new multi-system modules emits NMEA v4 where messages has prefix GA for Galileo, GN for Glonass and GL for unified data.

#### Version
all versions

#### Platform
[ * ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

Here is small patch to correct this.
----- cut here ---
--- AP_GPS_NMEA.cpp.orig   2016-06-01 17:28:22.351546727 +0500
+++ AP_GPS_NMEA.cpp        2016-06-01 17:31:56.599765010 +0500
@@ -93,9 +93,9 @@
.
 // NMEA message identifiers ////////////////////////////////////////////////////
 //
-const char AP_GPS_NMEA::_gprmc_string[] = "GPRMC";
-const char AP_GPS_NMEA::_gpgga_string[] = "GPGGA";
-const char AP_GPS_NMEA::_gpvtg_string[] = "GPVTG";
+const char AP_GPS_NMEA::_gprmc_string[] = "RMC";
+const char AP_GPS_NMEA::_gpgga_string[] = "GGA";
+const char AP_GPS_NMEA::_gpvtg_string[] = "VTG";
.
 // Convenience macros //////////////////////////////////////////////////////////
 //
@@ -339,12 +339,12 @@
     }
.
     // the first term determines the sentence type
-    if (_term_number == 0) {
-        if (!strcmp(_term, _gprmc_string)) {
+    if (_term_number == 0 && _term[0]=='G') {                // check is it really the first character "G"?
+        if (       !strcmp(_term+2, _gprmc_string)) {        // ignore gp gn gl prefixes detect rmc gga or vtg string
             _sentence_type = _GPS_SENTENCE_GPRMC;
-        } else if (!strcmp(_term, _gpgga_string)) {
+        } else if (!strcmp(_term+2, _gpgga_string)) {
             _sentence_type = _GPS_SENTENCE_GPGGA;
-        } else if (!strcmp(_term, _gpvtg_string)) {
+        } else if (!strcmp(_term+2, _gpvtg_string)) {
             _sentence_type = _GPS_SENTENCE_GPVTG;
             // VTG may not contain a data qualifier, presume the solution is good
             // unless it tells us otherwise.
----- up to here ---

**Comment by OXINARF** [comment]
This has been fixed in master in April 18 (https://github.com/ArduPilot/ardupilot/commit/2a214f1e46f54194e1dc579ec0bc88d532a5c4f7), so please look at it before opening an issue. Also, if it indeed wasn't solved and you have a patch, it was better to open a PR.
