### ISSUE TITLE
Flight time reduced in half 

### ISSUE THREAD

**Issue by gfunas** [ArduPilot/ardupilot#4245]
#### Issue details
I had Naza v2. and flight time was about 17-18min, recently decided to try APM 2.8 3.3.3v for quadrocopter. After couple test i see that flight time now is about 9-10 min, and extra weight only +50gr.
In my FPV screen I see about 50-55% of battery and i loose throttle. Its like not enough power to the engines and cannot take off. Maybe i miss something in configuration ?

#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
This isn't the place for support questions. Please post in the forums: http://discuss.ardupilot.org
