### ISSUE TITLE
AntennaTracker not forwarding Mavlink to GCS in master

### ISSUE THREAD

**Issue by TimothyGold** [ArduPilot/ardupilot#4246]
After changes in the Mavlink libraries over the last several weeks and changes in GCS_Mavlink.cpp I noticed that AntennaTracker in master is no longer forwarding packets to the GCS.  In Mission Planner the Antenna Tracker is the only ID that is discovered.

Version - 
ArduPilot/ardupilot/master/AntennaTracker

#### Platform
[X] AntennaTracker

**Comment by rmackay9** [comment]
This is fixed in master now.  Tridge fixed the issue a few days ago.  I think you'll find the newest beta works again.  I'll close this but please tell me if you think I'm wrong.

**Comment by TimothyGold** [comment]
Last night I was able to merge the Ardupilot/master into my fork.  I was able to compile and try it, but I ran into the same result. In the GCS only Tracker shows up.  I will try again from the main repository of Ardupilot/master tonight.

**Comment by TimothyGold** [comment]
Last night I was able to merge the Ardupilot/master into my fork.  I was able to compile and try it, but I ran into the same result. In the GCS only Tracker shows up.  I will try again from the main repository of Ardupilot/master tonight.

**Comment by rmackay9** [comment]
@TimothyGold, ok.  When we first pulled in Tridge's fix we also didn't see the vehicle.  We had to do a "make px4-clean" and perhaps a "submodule update --recursive" to make sure we got the fix which is actually in mavlink.
Just to be 100% sure it's not a build problem, I think loading up the 0.7.7 beta using Mission Planner would be best (the binary can also be found on firmware.ardupilot.org).

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (405/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:49892 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1b8IRd-002Bqc-2R
	for yann.dupuy@zyapps.com; Thu, 02 Jun 2016 04:33:23 +0200
Date: Wed, 01 Jun 2016 19:32:30 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1464834750;
	bh=DuyvU8lqo+kP/Bi/ToaMsXB3NCATQi7Rhdr+f0UObKc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=rRdXOXpMyEpScFGLd+pHuhTWJu1FttPBRLZASaWEPdGNhPTonbWwLWnR1i1DPn+eY
	 9pdIEG3tqt0zbTYZxydRMHq3jEHfBh7mm5Wxyz2MC86LQ0h7SblXx03RqAKoBxOqzx
	 pwJ6dr1gEN1dpbgiBPs0z4hKb3+266aQv5dEBvwo=

**Comment by TimothyGold** [comment]
@rmackay9, that was it.  I did do a clean build but I completely forgot about the potential submodules that I would need to update.  Thanks for your help.
