### ISSUE TITLE
Quadplane: is_flying=true is inhibiting RC disarm

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4250]
#### Issue details
Quadplane: is_flying=true is inhibiting RC disarm. 
Offending code lines are:
`if (quadplane.is_flying()) {
        is_flying_bool = true;`
near https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/is_flying.cpp#L31

causing this to always fail
`} else if (arming_rudder == AP_Arming::ARMING_RUDDER_ARMDISARM && !is_flying()) {`
near https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/radio.cpp#L148

#### Version
Plane v3.6.0beta1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover

#### Airframe type
quadplane

**Comment by magicrub** [comment]
The problem is not in radio.cpp. It is the is_flying=true override for quadplane

**Comment by tridge** [comment]
this was fixed with the update to is_flying in quadplane 
you can now rudder disarm in quadplane modes if at zero throttle
