### ISSUE TITLE
Plane: Logging Issues

### ISSUE THREAD

**Issue by SlipstreamFPV** [ArduPilot/ardupilot#4272]
#### Issue details

My logs contain random glitches. Almost every value has some spikes that are unaccounted for. For example my 5V line reported a maximum of 461V which obviously isn't right.
![0](https://cloud.githubusercontent.com/assets/6742745/15808597/5b68ddaa-2bbe-11e6-99d0-5c4001030017.JPG)

I question if the glitches are read as data by the autopilot as well and used for navigation and other vital functions or if they are just errors in the log. For example in this flight the Baro reported 0m altitude twice.
![10](https://cloud.githubusercontent.com/assets/6742745/15808584/07a8d8e6-2bbe-11e6-847e-14aed9874517.JPG)

Would this also go on to effect the flight control?

Sometimes immediately following a glitch I think I can see bad data being put through on other parts of the navigation system. For example in the attached pictures and log you can see that CTUN.NavRoll usually sits within the constrained limits but during the glitch both NavRoll and Roll peak past 300 and -300.
![2](https://cloud.githubusercontent.com/assets/6742745/15808519/9143991c-2bbc-11e6-987a-c0866c8b415a.JPG)
Normal:
![3](https://cloud.githubusercontent.com/assets/6742745/15808520/9148aac4-2bbc-11e6-8ec9-80c1d3407903.JPG)
Glitch:
![4](https://cloud.githubusercontent.com/assets/6742745/15808518/913de49a-2bbc-11e6-9c6f-4a81071a061e.JPG)

Other times a system seems to get out of whack for a while like the speed demand and takes some flight mode switching or throttle changes in auto modes to get it to "reset".
![5](https://cloud.githubusercontent.com/assets/6742745/15808588/338e28bc-2bbe-11e6-8801-71daca0e2381.JPG)
#### Version

3.5.2
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
#### Airframe type

My Twin Dream
#### Hardware type

Pixhawk, Dual GPS, Dual ACC, Dual Compass, Digital Airspeed Sensor, Mauch Power Module, RMRC 5V BEC, EZUHF
#### Logs

https://drive.google.com/open?id=0B7z1ne03SLaSclVFWkRMZ3lBMGs

**Comment by magicrub** [comment]
As the project grows, and log more things.  It's getting to the point that
some sd cards can't write error free.

**Comment by magicrub** [comment]
Logging is usually the raw data, but the filtered data is what the control system uses. Both are not always logged. Mission Planner has done a better job at removing massive spikes which are glitches to SDcard writing on slow SD cards. 

Is this issue still a problem? If not then it should be closed.
