### ISSUE TITLE
Plane: arming check for if the mixer has been uploaded successfully

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#4276]
#### Issue details
It's possible to arm without having successfully uploaded the mixer. Making the issue to I remember to track this...

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

#### Hardware type
PX4

**Comment by magicrub** [comment]
fixed via https://github.com/ArduPilot/ardupilot/commit/f0247a7be1668ba1edcf5139325289c86e670806
