### ISSUE TITLE
ArduPlane Ruder Disarming does not consider trim 

### ISSUE THREAD

**Issue by estebanavv** [ArduPilot/ardupilot#4290]
#### Issue details

When ARMING_RUDDER is set to 1 or 2 and RC4_TRIM deviates too much from 1500 the plane cannot be armed or disarmed depending which way is the trim set 
#### Version

3.5.3
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
#### Airframe type

All
#### Hardware type

Tested on Pixhawk probably all are affected
#### To reproduce

Set ARMING_RUDDER = 1 set RC4_TRIM  with a value like 1440 . Try to arm. If it works change RC4_TRIM to 1560, and try again. You will notice that in one of these cases you won't be able to arm.
#### Current Workaround

Center the rudder trim arm or disarm the plane and set back the ruder trim to the original value

**Comment by WickedShell** [comment]
This was fixed at somepoint with the change to a RC_Channels object, and making all the vehicle code use the RC_Channel object rather then asking the HAL for the values.
