### ISSUE TITLE
Optical Flow mode

### ISSUE THREAD

**Issue by raptortrias** [ArduPilot/ardupilot#4301]
#### Issue details
Would it be possible to re-introduce an Optical Flow (PX4FLOW) stabilised arducopter flight mode, dedicated for flight without GPS and magnetometer

#### Version
Any

#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
We support the PX4 flow sensor.  instructions are here: http://ardupilot.org/copter/docs/common-px4flow-overview.html.  Please give it a try and if you have problem feel free to report back.
