### ISSUE TITLE
Missing stream rate SRx parameters for serial4 and serial5

### ISSUE THREAD

**Issue by Pedroalbuquerque** [ArduPilot/ardupilot#4303]
#### Issue details
although I can choose serial 4 and 5 for Mavlink using the Qgroundcontrol GCS, then I don't see how to control the stream rate control for it. there is only SR0 to SR3 set of parameters.

Assuming SR0 is for USB, SR1 for Serial1 etc, then what is sent to Serial 4 and Serial 5 ?

I have been using serial4 to connect to strom32 gimbal through Mavlink and is working ok for that propose. Now experimenting with a arduino on serial4 instead of storm32 to study the protocol, and i'm getting unwanted messages from copter. I looked for a way to control stream rate info, and didn't find. Also could not find clear information on the relation from SRx to Serialx . 

Digging into code (parameters.cpp) could only find SR0 to SR3 which is according to WIKI.

#### Version
Copter V 3.3 (and master ?)

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quad

#### Hardware type
pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

#### Evidences
from github ardupilot/arducopter/parameters.cpp

>     // @Group: POSCON_
>     // @Path: ../libraries/AC_AttitudeControl/AC_PosControl.cpp
>     GOBJECT(pos_control, "PSC", AC_PosControl),
> 
>     // @Group: SR0_
>     // @Path: GCS_Mavlink.cpp
>     GOBJECTN(gcs[0],  gcs0,       "SR0_",     GCS_MAVLINK),
> 
>     // @Group: SR1_
>     // @Path: GCS_Mavlink.cpp
>     GOBJECTN(gcs[1],  gcs1,       "SR1_",     GCS_MAVLINK),
> 
>     // @Group: SR2_
>     // @Path: GCS_Mavlink.cpp
>     GOBJECTN(gcs[2],  gcs2,       "SR2_",     GCS_MAVLINK),
> 
>     // @Group: SR3_
>     // @Path: GCS_Mavlink.cpp
>     GOBJECTN(gcs[3],  gcs3,       "SR3_",     GCS_MAVLINK),
> 
>     // @Group: AHRS_
>     // @Path: ../libraries/AP_AHRS/AP_AHRS.cpp
>     GOBJECT(ahrs,                   "AHRS_",    AP_AHRS),
> 
> #if MOUNT == ENABLED
>     // @Group: MNT

**Comment by magicrub** [comment]
Only 4 Mavlink ports can be active: usb(sr0), telem 1(sr1), telem2(sr2),
and either serial 4 or 5 (sr3).
