### ISSUE TITLE
AP_Mission: DO_JUMP isn't sanity checked on mission load

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#4304]
#### Issue details
DO_JUMP is range checked at runtime when it gets to the command, but it should be checked when submitted to the autopilot so that a mission can be rejected as invalid, rather then being a silent failure at runtime. (Checking this at mission load does not allow us to remove the runtime check)

**Comment by magicrub** [comment]
closed via https://github.com/ArduPilot/ardupilot/commit/cadd95fdd859e6dac21eaa37f58f057113bb3344
