### ISSUE TITLE
RCn_TRIM not working AP 3.6.0

### ISSUE THREAD

**Issue by Autonomost** [ArduPilot/ardupilot#4314]
#### Issue details
When I am trying to trim the RCn_ ouputs it will only trim one of the two servos. Even selecting different servos within mission planner it still will not trim the correct one. 

#### Version
AP 3.6.0 and AP 3.5.0 at 0.75

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

#### Airframe type
Plane with Two Elevators, Rudder, Two Ailerons, Two Flaps. Supercub 

#### Hardware type
Pixhawk

#### Logs

[test.txt](https://github.com/ArduPilot/ardupilot/files/314010/test.txt)

**Comment by gmorph** [comment]
This isn't the place for support issues - please raise this request in the support forums.
http://discuss.ardupilot.org/
Thanks.

**Comment by Autonomost** [comment]
I was just about to take it down. Sorry. 

Evan Hammac
