### ISSUE TITLE
Strange lost of altitude behavior resulting in crash

### ISSUE THREAD

**Issue by maribeiro** [ArduPilot/ardupilot#4344]
#### Issue details
Using the ardupilot simulator and qgroundcontrol I am seeing an unusual behavior. I start by arming, then takeoff to 10meter and right after I switch to Loiter mode I see that the quad starts loosing altitude and crashs into the ground. Same thing happens if I switch to alt hold. Why this is happening ?

#### Version
APM:Copter V3.4-dev (978a89ef)

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
quad

#### Hardware type
Laptop running arducopter simulation

#### Logs
[17.BIN.zip](https://github.com/ArduPilot/ardupilot/files/323395/17.BIN.zip)

**Comment by OXINARF** [comment]
You have throttle at a minimum, so when you switch to a mode that has throttle input it will naturally descend.
Also, this is a support question and those should be posted at the forum (http://discuss.ardupilot.org)
