### ISSUE TITLE
Heli: v3.4 ALT_HOLD has severely limited roll/pitch limits

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#4346]
Doing heli testing in current master ALT_HOLD in copter has severely limited roll/pitch limits. With ANGLE_MAX=4500 I get a maximum of 6 degrees left roll and 12 degrees right roll. The collective is a long way from maximum.
In STABILIZE it works as expected.

**Comment by rmackay9** [comment]
This is fixed in master now and will go out with Copter-3.4-rc2.

**Comment by magicrub** [comment]
would be nice in cases like this that the primary commit that fixes it be
posted when we close issues.
