### ISSUE TITLE
YAW reverse Differential Spoilers Flying wing

### ISSUE THREAD

**Issue by raptortrias** [ArduPilot/ardupilot#4349]
#### Reversed YAW

Differential spoilers (@ AUX9 and AUX10) have been setup on Flying wing .

 Can obtain correct YAW movement with RC, however autopilot recognizes opposite YAW movement (arming requires full left) and YAW correction in FBWA is opposite to what it should be.

 Have tried reversing YAW on RC and RC4_REV but it won't fix the problem. 

PS Probably doing something silly here myself (?)
#### Version

Plane 3.6.0
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
#### Airframe type

Flying wing
#### Hardware type

pixhawk
#### Logs

NA

**Comment by magicrub** [comment]
Please post your param file

**Comment by raptortrias** [comment]
@magicrub  Either rudder arm would work correctly or RC YAW


[FW_21_6_2016.zip](https://github.com/ArduPilot/ardupilot/files/325164/FW_21_6_2016.zip)

Thanks

**Comment by DavidIngraham** [comment]
Closing, as this appears to be a setup issue. Also, not relevant after the Servo Split
