### ISSUE TITLE
Plane: Log target loc to NTUN

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#4358]
#### Issue details

When trying to diagnose controlled fly aways or navigational errors from DF logs it would be valuable to know where the plane was attempting to fly.
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

**Comment by magicrub** [comment]
+1

**Comment by enjoybeta** [comment]
why not adding into tlogs if you lost the plane?

**Comment by enjoybeta** [comment]
I think it's done. WpDist, TargBrg, and NavBrg can be found in NTUN, this issue can be closed

**Comment by WickedShell** [comment]
WpDist, TargBrg, NavBrg aren't sufficient you really need to know lat/lon/alt.

**Comment by enjoybeta** [comment]
You mean the target lat/lon/alt? I don't think it's avilable for all modes. For what mode can we get target lat/lon/alt? AUTO? Any more?

**Comment by WickedShell** [comment]
It's available for rtl, guided, cruise, loiter at a minimum.

**Comment by enjoybeta** [comment]
Do you know which funtion logs the data for NTUN? Is is inside DataFlash class? I am trying to work on it.
