### ISSUE TITLE
How to compile the master version code about ardupilot

### ISSUE THREAD

**Issue by zhuyinbo** [ArduPilot/ardupilot#4363]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by magicrub** [comment]
Please visit ardupilot.org and click on dev->building the Code.
