### ISSUE TITLE
Plane Bug: Zubax compass calibration and geotagging bug

### ISSUE THREAD

**Issue by jcooper21** [ArduPilot/ardupilot#4381]
With Zubax GNSS 2 there is a GPS time stamp issue and compass calibration issue resulting in many compass errors and unable to geotag photos. APM Plane 3.6.

**Comment by WickedShell** [comment]
There is a pr pending that should address this.

https://github.com/ArduPilot/ardupilot/pull/4300

**Comment by hsteinhaus** [comment]
I guess it will - geotagging was the way I got aware about this bug. 

Potential workaround until the fix got merged: downgrade the compiler (however I cannot recommend a specific version).

**Comment by WickedShell** [comment]
@jcooper21 was this fixed on plane 3.7.0 for you?

**Comment by WickedShell** [comment]
Closing as #4300 should have fixed the handling of the time stamp overflows, and it's never been reported back as a problem since then. (And I've at least had a Zubax connected on the bench without seeing any problems).
