### ISSUE TITLE
Check for toolchain don't see failure

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/ardupilot#4396]
#### Issue details

Check for toolchain in mk/find_tools.mk don't see failure because it checks CXX: 

```
ifeq ($(CXX),)
$(error ERROR: cannot find the compiler tools for $(TOOLCHAIN) anywhere on the path $(TOOLPATH))
endif
```

while CXX defined as

`CXX = $(CCACHE) $($(TOOLCHAIN)_CXX)`

so it always not empty if CCACHE found

to resolve one need to change checking to 
`ifeq ($(AS),)`

**Comment by WickedShell** [comment]
Relevant file no longer exists, and make is no longer used.
