### ISSUE TITLE
Separate vertical speed limit for loiter and alt hold

### ISSUE THREAD

**Issue by kudykam** [ArduPilot/ardupilot#4401]
#### Issue details

Enhancement: ALT HOLD mode vertical speed is limited by pilot_velz_max, horizontal speed is not limited. LOITER mode limits horizontal speed and should have its own vertical speed limitation as well. 
LOITER mode is great for beginners and for situation with sensitive controlling. Even with throttle to zero, quad would descent vertically safely.

If I limit it only by pilot velz max, then flying in alt hold would be very slow in vertical way.
If i set pilot_vlz_max to 4m/s, which is ok when copter is moving horziontally, in zero speed it will result in vortex ring. But when switched to loiter (with limited vertical speed) it woudl be fine.
#### Version

all
#### Platform

[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover

**Comment by IamPete1** [comment]
I think having the same limits is more intuitive, if we were to change the limits you have to re-learn what the stick does per mode. I'm not sure I understand the explanation, if you can get into vortex ring in loiter with 4m/s decent you can get into it alt hold too. 

If your desperate you use scripting to set the velocity limits per mode. 

I think I will close, but feel free to re-open.
