### ISSUE TITLE
Plane: do not scale loiter radius via altitude

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4416]
This line is very surprising to me. The mission should not have a changing radius. If there are turn radius concerns due to altitude it needs to be solved some other way.

Referring to these lines here in the L1:

> float AP_L1_Control::turn_distance(float wp_radius) const
> {
>     [wp_radius *= sq(_ahrs.get_EAS2TAS());](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_L1_Control/AP_L1_Control.cpp#L85)
>     return MIN(wp_radius, _L1_dist);
> }

and

/ / scale loiter radius with square of EAS2TAS to allow us to stay
/ / stable at high altitude
[radius *= sq(_ahrs.get_EAS2TAS());](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_L1_Control/AP_L1_Control.cpp#L269)

**Comment by WickedShell** [comment]
Duplicate issue of #5809, but more activity there so closing this.
