### ISSUE TITLE
TradHeli: make compassmot work

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#442]
To allow it to work properly for traditional helicopter we should:
1. exit immediately if a power module is not enabled
2. modify the cli compassmot so that it watches the input channel 8 instead of ch3 (throttle/collective pitch) if rsc is enabled.  If it's not enabled just ask the user to raise the tx channel that is directly connected to the esc.
3. implement throttle_pass_through() function in the AP_MotorsHeli class which checks the rsc_mode and passes input channel 8 to output channel 8.  This will also need to allow the user to control the servos

**Comment by gmorph** [comment]
Rob - does this work in TradHeli?

**Comment by R-Lefebvre** [comment]
@gmorph No, I don't think so at all.

**Comment by Naterater** [comment]
Considering how throttle and current are not often as linearly related, It could affect the results (or at least the default parameters) for making this work. Sounds useful to me.

**Comment by auturgy** [comment]
@bnsgeyer is this still relevant?

**Comment by bnsgeyer** [comment]
@auturgy  I have no idea.  In most cases, I instruct users to use only the external compass.  From the wiki, it sounds like even multi users don't use this much.  I guess I would ask @rmackay9 since he was the original author of this issue.

**Comment by IamPete1** [comment]
IMHO a on the ground run up for compass mot on a heli is going to be way to sketchy. We can now fit with the tool include in MAVExpolorer. 

https://ardupilot.org/copter/docs/common-magfit.html

**Comment by rmackay9** [comment]
@peterbarker, Yes I think you're right that we probably won't ever implement compass mot for tradheli's for safety reasons.
