### ISSUE TITLE
Saving and retrieving Missions/Polygon Fences/Rally Points/No fly zones to/from the microSD card

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#4424]
#### Issue details

Implementation of saving and retrieving an entire mission/Polygon fence/Rally points/No fly zones to and from the onboard sdcard.

Mission would be saved on SD card and possibly a Mavlink command to save and retrieve an entire Mission from the SD card.

As a cautionary step the first implementation would only allow this to happen when disarmed/on the ground. Missions before loading from the SD card would be required to respect some TBD parameters for validity
#### Version

New feature
#### Platform

[X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

All
#### Hardware type

All
#### Logs

N/A

**Comment by freyapilot2002** [comment]
Is there any chance this is going to be implemented?
Everyone's comeback is always "use the distance trigger".
Distance trigger is a cool implementation but it is not always the answer.

**Comment by freyapilot2002** [comment]
If it is not a global change is there a developer that is willing to change the code for a custom firmware?

**Comment by magicrub** [comment]
@freyapilot2002 To get features added to Ardupilot, either in the master code base or not, there are a few options:

1. make an issue and hope someone volunteers their time to do it (like you've done here so far)
2. write it yourself
3. encourage another company to do it if they think it's worth their time (this is similar to # 1)
4. pay someone to write it - See http://ardupilot.org/dev/docs/common-commercial-support.html

Option # 4 is become more popular as there are more and more commercial demand for specific features that a wider audience does not benefit from but certain individuals/companies do

**Comment by freyapilot2002** [comment]
Thank you for the great suggestions. I will pursue #4.

**Comment by DonLakeFlyer** [comment]
Would be great to do this using standard mavlink messages (new ones) so it can become a common feature.

**Comment by auturgy** [comment]
No reason to close. It’s a valid enhancement request.

**Comment by reubenfinch** [comment]
Has there been any development on this? I'm unsure if the current storagemanager is even making full use of the larger RAM offerings in newer flight controllers. The Pixhawk4 has 512K, but we're only making use of around 128K from my reading of the code.

**Comment by peterbarker** [comment]
We can do all of this using scripting; there are examples (or applets?) that do so.

We can also use SD card or storing these items just generally now.
