### ISSUE TITLE
Copter: allow Fence max distance to be set from CH7/CH8

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#443]
Switch that would allow fence distance to be captured as the current distance when the ch7 or ch8 switch is switched.

**Comment by peterbarker** [comment]
@rmackay9 still think this is a good idea?  Easy enough with the RC channel option stuff.

**Comment by rmackay9** [comment]
@peterbarker, I haven't seen any users request this so closing.
