### ISSUE TITLE
Plane differential spoilers additional mixing options

### ISSUE THREAD

**Issue by raptortrias** [ArduPilot/ardupilot#4442]
#### Issue details

Currently diferential spoilers with elevon_output move in both roll and pitch.

For high aspect ratio flying wings this can be a problem especially in pitch response as it effectively reduces the pitching moment (when full span elevon/spoilers are used).

 It would be nice to have additional control of how the spoilers move as percentage mixing in roll and diffferent for pitch
#### Version

3.6.0
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[x ] Plane
[  ] Rover
#### Airframe type

Flying wing
#### Hardware type

Pixhawk
#### Logs

_Please provide a link to any relevant logs that show the issue_

**Comment by Naterater** [comment]
Is this still an issue with the new additions - crow flaps, etc?

**Comment by IamPete1** [comment]
With the new [Differential Spoiler options](https://ardupilot.org/plane/docs/differential-spoilers.html#differential-spoiler-options) I think this is fixed
