### ISSUE TITLE
Quadplane: Add Land Abort Functionality

### ISSUE THREAD

**Issue by iskess** [ArduPilot/ardupilot#4446]
#### Issue details

When using the Q_LAND mode or VTOL_LAND command, full throttle stick should signal the pilot's intention to immediately stop the descent. What happens next depends on the aircraft design and pilot's intentions. I propose a new parameter Q_LAND_ABORT. 
If Q_LAND_ABORT = 0, then throttle stick is ignored ( current behavior )
If Q_LAND_ABORT =1, then >95% throttle stick switches to Q_LOITER mode. 
If Q_LAND_ABORT =2, then >95% throttle stick commands a vertical climb back up to either VTOL TAKEOFF altitude, or if none then Q_LAND_FINAL + 5m, then executes a VTOL TAKEOFF. 

Actually on second thought, we don't know what heading is safe for a takeoff transition unless there is a VTOL_TAKEOFF in the flight plan. Into the wind might not be a safe assumption. Unless someone has another idea, Q_LAND_ABORT =2 should operate as =1 unless there is a VTOL_TAKEOFF to take information from. 
#### Version

3.6
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
#### Airframe type

Quadplane
#### Hardware type

Pixhawk

**Comment by magicrub** [comment]
+1

**Comment by peterbarker** [comment]
We have OPTION_THR_LANDING_CONTROL now to allow the pilot to control the vehicle's height during landing.  It is up to the pilot as to what to do after they've achieved the height they want - possibly reorient plane and re-transition, for example.

Closing this one.
