### ISSUE TITLE
ZUBAX GNSS2 don't fix position

### ISSUE THREAD

**Issue by Habitatea** [ArduPilot/ardupilot#4449]
#### Issue details

Hello, I bought two zubax gnss2 for two of my planes to renplacing the zubax gnss1 (that work fine) but when plug and turned on my plane with pixhawk and AP 3.5 and AP 3.6, mission planner detected GPS but don't fix possition, the all leds are ok on red board.
I erased on CLI mode but all continue equal
On APM I had GPS_TYPE = 9 and BRD_CAN = 1 (on param list only give me two options 0 or 1 not 2, with 2 CAN1 led didn´t blink, but with 1 blink ok)

[On this post I speak with zubax people about this issue ](https://productforums.zubax.com/viewtopic.php?f=4&t=26)
#### Version

AP 3.5 or 3.6
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
#### Airframe type

trainer
#### Hardware type

pixhawk
#### Logs

_Please provide a link to any relevant logs that show the issue_

**Comment by WickedShell** [comment]
Closing as this is a support question and the entire CAN structure in master is different at this point in time (and I've had Zubax GNSS 2 reporting fix correctly with it).
