### ISSUE TITLE
Add capability for use or no use range finder in flight

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#4451]
Add capability to activiate or desactivate using range finder instead of baro in flight.

Actually, when range finder is connected, EK2 alt source is always range finder, and cannot be changed in flight.

Also, even if you desactivate range finder as ALT source for EK2, and you set baro as alt source, it still using it.

Today, there's needed to disconnect range finder and set EK2 params when we want to use baro and vice et versa..

So there's possible to add software feature instead of actual solution?

**Comment by IamPete1** [comment]
You can now set this up on a `RCx_OPTION` see: https://ardupilot.org/copter/docs/terrain-following-manual-modes.html
