### ISSUE TITLE
RelAlt above Home not logged in AC 3.4

### ISSUE THREAD

**Issue by ThorstenDP** [ArduPilot/ardupilot#4468]
#### Issue details

Hi All,

in AC 3.3 RelAlt above Home was logged in the GPS data. This hase been removed in May by @tridge .
[https://github.com/ArduPilot/ardupilot/commit/7ab1367ec44bd256d419f36ad9c6854b8aacc712](https://github.com/ArduPilot/ardupilot/commit/7ab1367ec44bd256d419f36ad9c6854b8aacc712)

RelAlt above home is the auto mission altitude so it is important for several use cases. Currently it is only recorded in the CAM log. But a CAM_TRIGG is not relevant for many types of missions and as soon as CAM_TRIGG_DIST is set to 0, RelAlt above Home is not recorded.

Instead we have RelAlt above the EKF origin recorded. But there are differences of several meters to RelAlt above Home. So it is not showing the values used in Mission Planning. See [http://discuss.ardupilot.org/t/relalt-disparity/10132](http://discuss.ardupilot.org/t/relalt-disparity/10132) for some logs and discussion with @OXINARF 

Would be great if RelAlt above Home could be logged for the entire flight in AC 3.4 - maybe as an additional RelAlt value in the POS message.

Thanks a lot in advance!
Thorsten
#### Version

AC3.4
#### Platform

[?] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
#### Logs

 [http://discuss.ardupilot.org/t/relalt-disparity/10132](http://discuss.ardupilot.org/t/relalt-disparity/10132)

**Comment by WickedShell** [comment]
@ThorstenDP POS does have a RelHome altitude. And in 3.5 it even has one relative to aircraft home vs origin home.

**Comment by ThorstenDP** [comment]
@WickedShell thanks for the hint about 3.5! I must have missed that... But I just started tesing 3.5. In 3.4 I guess only RelAlt above EKF origin is logged in POS, which might be off about several meters compared to RelAlt above home.

**Comment by OXINARF** [comment]
I think it's not in 3.5-rc1, but it will be in 3.5-rc2 and final release.

Anyway, since this in master I'm closing this.

**Comment by rmackay9** [comment]
In case it helps, the alt above home is also in the CTUN message in all versions.

**Comment by OXINARF** [comment]
@rmackay9 Are you talking about the Alt field? Because that's altitude above origin. We have BAlt but that comes directly from the baro and it's not always exactly the same.

**Comment by rmackay9** [comment]
Ah, @OXINARF is absolutely right.

**Comment by ThorstenDP** [comment]
@OXINARF Thanks! I wanted to test master anyway the next days. I'll make some tests.
