### ISSUE TITLE
DataFlash: Don't log rangefinder/sonar if the sensors aren't present

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#4490]
#### Issue details

While reviewing my logs today I noticed that I have rangefinder and sonar messages in them even though I have neither device connected or configured. As they aren't present (and thus the data is nil except for timestamp) emitting them just consumes storage and bandwidth that could easily be avoided.
#### Version

Master
#### Platform

[x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by magicrub** [comment]
This seems like a bug and should be an easy fix.

**Comment by WickedShell** [comment]
This was done awhile ago (#7064)
