### ISSUE TITLE
Plane: Add wind failsafe

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#4491]
#### Issue details

Failsafe should activate when the wind is detected to be above a set threshold for > 5 seconds. This is particularly of relevance for any time during loss of link  operations, and adds a way to help ensure the aircraft is safely returned.
#### Version

Master
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

**Comment by magicrub** [comment]
Are you already working on this? It's on my todo list but I haven't started.

**Comment by WickedShell** [comment]
Not yet it's high on my to-do list but over a week before I'm even back at
a compiler

**Comment by Naterater** [comment]
This is still probably a good feature, but because the wind estimate is so slow to respond, I would recommend at least 30 seconds.

**Comment by IamPete1** [comment]
We have a scripting example for this.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/plane-wind-failsafe.lua

**Comment by peterbarker** [comment]
Closing this one; the LUA script @IamPete1 can provide this functionality in a much more flexible way than we could easily put in the C++ code.
