### ISSUE TITLE
EKF nav fails after a crash

### ISSUE THREAD

**Issue by mkschreder** [ArduPilot/ardupilot#4594]
I experience a complete loss of control on quadcopter after a mid air crash when I would expect the copter to try to level itself in mid air. It is as though it starts to think that up is down.. It needs to be placed level in order to reset itself. I can not arm again for a while either because of the "EKF variance" error. 

Why does this happen and how can this be fixed?

**Comment by OXINARF** [comment]
This is a support question and those should be posted at the forum (http://discuss.ardupilot.org).

I will say that, since you crashed, you probably messed up EKF and it wouldn't know how to keep it level anymore. But you need to post the log file when do these questions (in the forum).
