### ISSUE TITLE
Plane: remove AP_Airspeed dependency on Airspeed Calibration

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4631]
remove AP_Airspeed dependency on Airspeed Calibration. This is a value that can just get passed into the update() call.

**Comment by gmorph** [comment]
I think the dependency is there so we can't use the airspeed unless the calibration has happened.

**Comment by magicrub** [comment]
Opps, I phrased the title wrong. I changed it. Also, it's already fixed [here](https://github.com/ArduPilot/ardupilot/commit/ce7b766d8b2316fbc5d89dc2ec8c08b259c7f647) so I'm closing :)
