### ISSUE TITLE
fix signed compare warning in HAL_SITL/UARDriver::write()

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4632]
../../libraries/AP_HAL_SITL/UARTDriver.cpp:148 warning: comparison between signed and unsigned integer expressesion

size_t UARTDriver::write(const uint8_t *buffer, size_t size)
{
    if (txspace() <= (ssize_t)size) {
        size = txspace();
    }

Seems the (ssize_t) cast just needs to be removed. Can one of the Linux folks jump on this low-hanging fruit please? It's causing warnings in SITL compiles.

**Comment by lucasdemarchi** [comment]
Indirectly fixed by https://github.com/ArduPilot/ardupilot/pull/4593
