### ISSUE TITLE
GPS: UAVCAN GPS should not be forced to be second GPS

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4637]
GPS: UAVCAN GPS should not be forced to be second GPS

**Comment by WickedShell** [comment]
UAVCAN isn't forced to be the second GPS. The only time where this is true is if you plug the serial GPS into the GPS port. (Then GPS1 will always lock the first available serial port for it's use, GPS2 will take the second one). However the UAVCAN GPS can be found on either one.

Closing as a non issue for now, this is only a issue for specifying which GPS should be used in a non swap configuration, and I believe there is an issue open for that already.

**Comment by magicrub** [comment]
Can you crosslink that issue?
