### ISSUE TITLE
Copter 3.4 add capability to handle moving base rtk for yaw estimation

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#4646]
today navspark ns-hp rtk solution offer this capability.

Tomorrow ublox m8p rtk will also offer this capability

It will be nice to handle nmea yaw from nshp rtk solution to better estimate yaw and also autocalibrate and handle magnetometet issue

**Comment by IamPete1** [comment]
https://ardupilot.org/copter/docs/common-gps-for-yaw.html
