### ISSUE TITLE
Copter 3.4 dev: Y6B YAW problem. Yawing left - goes down and another way around

### ISSUE THREAD

**Issue by amusinov** [ArduPilot/ardupilot#4652]
#### Issue details
Hi guys!

Have built Y6 1.3m on Navio2 and RPi3, ArduCopter 3.4-dev. 
In stabilize mode it flies more then awesome in any direction except yaw control. When I push yaw left - drone turns and goes down a bit. When yaw right - goes up.

In AltHold mode the drone tries to stick the altitude but goes up-down at the same time while yawing. The same in Loiter, of course.

All the props are from one order 9" (35% hover throttle), all ESCs are well calibrated. No yaw mixing on the RC. Problem is still exists after motors moved twice close to the center.

Tried to tune PIDs for yaw, not precise, but it doesn't help a lot.

#### Version
ArduCopter Y6 Navio2 3.4-dev (before 12-08-16)

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Y6 (B)

#### Hardware type
Navio2, RPi3

#### Logs
Ready to reveal on request.

**Comment by rmackay9** [comment]
@amusinov, thanks for using ArduPilot.
It's best to raise support issues in the forums here: http://discuss.ardupilot.org/c/arducopter/copter34
Please include a dataflash log as well.
Really though, it's most likely just tuning.  Have you tried during an autotune?  You'll find some instructions on the wiki.
