### ISSUE TITLE
Plane: make control_mode enum list order arbitrary

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4656]
Most of the code uses:
`if (control_mode == BLAH1 || control_mode == BLAH2)` 

but in some places it's
`if (control_mode >= BLAH)`

which requires a strict ordering in the modes. This is currently used as >= FBWA or >= AUTO which means throttle-controlled and/or throttle is airspeed controlled. There needs to be a mode_controls_throttle() function that is a big switch statement listing every mode returning bool.

Most of this conversion has happened, I only see this problem in 2 places now.

**Comment by peterbarker** [comment]
@magicrub anything to PR for this?

**Comment by magicrub** [comment]
I see 3 cases still remaining. I'll PR them.
