### ISSUE TITLE
sim_vehicle.py is not killing old  instances before rerunning

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#4699]
On cygwin when I run sim_vehicle.py and then exit mavproxy.exe via ctrl-c, the process will often stay active. When active, it stays alive forever. When re-running sim_vehicle there's no warning, it just runs like normal but what you're seeing is the *old* instance still running. The process has to be killed in Windows Task Manager before any new code changes take effect

**Comment by OXINARF** [comment]
@peterbarker Can you look at this?

**Comment by peterbarker** [comment]
@oxinarf Once I get this old laptop installed with Windows (poor thing).
