### ISSUE TITLE
frame reference clarification 

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#4717]
#### Issue details

My question is about difference about local_ned and body_ned.
We got two definitions : 
https://github.com/ArduPilot/ardupilot/pull/4716 
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L1717

And the wiki state another : 
http://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html#copter-commands-in-guided-mode-set-position-target-local-ned

For me MAV_FRAME_BODY_NED is wrong in wiki : should be 

```
Positions are relative to the vehicle’s home position in a frame based on the vehicle’s current heading
```

instead of 

```
Positions are relative to the vehicle’s home position in the North, East, Down (NED) frame.
```

Then for MAV_FRAME_BODY_NED we should not apply offset correction from current pose but home pose.

What do you think ?

**Comment by OXINARF** [comment]
I agree with @khancyr that BODY_NED definition on the wiki (and the way we handle it in Copter) seems wrong to me and should instead be what @khancyr wrote, relative to home in a frame based on vehicle's heading.
In my opinion, MAVLink definitions are terrible and don't help here at all, but maybe that's just me.

**Comment by IamPete1** [comment]
Sounds like this is a wiki issue?

**Comment by rmackay9** [comment]
I agree this is a wiki issue so I'll close this.  I hope that in the near-ish future I will find the time to update this relevant wiki page: https://ardupilot.org/dev/docs/mavlink-commands.html
