### ISSUE TITLE
Porting to OrangePi

### ISSUE THREAD

**Issue by xtr0d3m0n** [ArduPilot/ardupilot#4729]
#### Issue details

any body working on porting over the HAL to this cheap opensource SBC?It more power full than Raspbery pi and  1/3 of the cost.if you guys want to do some coding I will be happy to do testing I can easily rig up some IMU breakout boards etc and its pin compatible with Rpi so I guess u can use existing hats?.  http://www.orangepi.org/
#### Version

_What version was the issue encountered with_
#### Platform

[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
#### Hardware type

_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
#### Logs

_Please provide a link to any relevant logs that show the issue_

**Comment by cudnn** [comment]
i have port to banana pi.  a20 cpu

**Comment by xtr0d3m0n** [comment]
@cudnn AWESOME !! link please

**Comment by magicrub** [comment]
If it's Rpi compatible, what if anything needs to change? Does installing
the RPi shield and loading the RPi code work?

**Comment by xtr0d3m0n** [comment]
I ordered a board ..let see

**Comment by lucasdemarchi** [comment]
> If it's Rpi compatible, what if anything needs to change? Does installing
> the RPi shield and loading the RPi code work?

Except for RCInput and some other things that are rpi-specific (actually SoC-specific), yes.
