### ISSUE TITLE
sim_vehicle.py - be able to pass flags to waf configure and build steps

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#4749]
We need a way to pass options through to waf from sim_vehicle.py?  I need to pass the "--check-cxx-compiler g++" option to the waf configure step but not the build step.  We already have --mavproxy-args and --sitl-instance-args, so could we have --configure-args and --build-args ?

Peter has volunteered :-)

Thanks, Grant.

**Comment by peterbarker** [comment]
Done.
