### ISSUE TITLE
Copter: 3.4-rc2 - reload fence if necessary when checking if point is outside of fence

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#4751]
Reported by @OXINARF.

The problem is that when we receive new points we mark it to reload but when we check if a point is outside the fence (check_destination_within_fence) we don't look for that. There's also another bug in check_fence line 213, it should be just an if, not an else if

**Comment by peterbarker** [comment]
So far out of date it isn't funny; we've rewritten this code several times since this was raised :-)
