### ISSUE TITLE
Copter-3.4-rc3: alt hold target is being reset to current when switching modes

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#4775]
When users switch between alt-hold and loiter, the current altitude target is reset to the current altitude.  In stead we should probably check if the alt-hold controller is active, and if  'yes' keep using the existing target.

**Comment by R-Lefebvre** [comment]
Good idea.

**Comment by rmackay9** [comment]
This is resolved with this commit: https://github.com/ArduPilot/ardupilot/commit/5894a54a16d007dacbf228355c727917f8153b6f
