### ISSUE TITLE
Copter: head to home using compass when GPS fails

### ISSUE THREAD

**Issue by skoubri** [ArduPilot/ardupilot#478]
I would like to propose if possible to have a failsafe kind option during a mission or RTL mode... I almost got to loose my quad today as the GPS stopped during flight... Probably it switched to stabilize but i had strong wind and the quad was going away!... So i wonder what about if the GPS stops or loosing fix, instead of stabilize, use the last value of heading to home (GPS) and use the compass to put that heading and starting to travel there... of course it won't stop anywhere but all i want is to come near to me so i take control as soon as i have its orientation visible...

Thanks in advance!

**Comment by piningforfjords** [comment]
This is an old thread but I will relay a solution we came up with on a commercial system.  We had a reasonably good estimate for wind strength and direction (something that is useful for the pilot to know from a vehicle security and rtl time home point of view).  This is something that could be calibrated during the tuning phase provided there was some wind.  When we would loose GPS we would apply a thrust vector to counter act the last known wind vector.  The pilot could then click on the map and adjust that vector to steer the vehicle back home.  It was advanced training but generally people got it once they practiced it.  We had a mode where the user could practice it.
