### ISSUE TITLE
add support for MANUAL mavlink message

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#4788]
We should support the MANUAL_CONTROL message to improve our support of ROS.
http://mavlink.org/messages/common#MANUAL_CONTROL

**Comment by DonLakeFlyer** [comment]
That would also get you QGC joystick support.

**Comment by peterbarker** [comment]
This was implemented for Sub; the code should be moved up to GCS_MAVLink

**Comment by Ridhwanluthra** [comment]
I would like to work on this, could you please point me in the direction of the relevant documents in order to do this?

**Comment by khancyr** [comment]
hummm, unless I mistake but we already support this on all vehicles !

**Comment by rmackay9** [comment]
Yes, looks like this item was completed by Francisco so closing.
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L790
