### ISSUE TITLE
Copter: Allow sending desired altitude and desired vertical speed to UAV while in alt hold mode

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot#485]
It currently is not (Copter) or only in a limited way (Plane) possible to send simple flight commands like course or altitude to APM via telemetry. In many aspects, however, that would be beneficial AND it is a common autopilot function in professional UAVs and full-size aircraft.

Sending desired altitude and VS to the UAV while in ALTH mode should be the easiest to implement of all options, hence I would like to suggest implementation.

After sending an altitude / VS command to the APM it would move to the desired altitude at the desired speed and remain there until a new command is sent or the user initiates ascend/descent via the sticks.

**Comment by khancyr** [comment]
Done by guided mode
