### ISSUE TITLE
AP_HAL_Linux: Interrupted: Window changed crash

### ISSUE THREAD

**Issue by samirbonnet** [ArduPilot/ardupilot#4850]
Details:
Linux threading model issue
Hardware type:
Emlid Navio+ on Raspberry pi 3

-> While running Ardupilot on Navio1 over a SSH connection
 If I resize the terminal that runs the Ardupilot binary
  the following crash happens: 

Output:
$> arduplane -A udp:192.168.0.15:14550 
Raspberry Pi 2/3 with BCM2709!
**_{{I resize the ssh terminal now}}**_
Interrupted: Window changed
Interrupted: Segmentation faultInterrupted: Segmentation fault

-> Once in a while, gdb is able to provide some hints:

Output:
(gdb) info thread
  Id   Target Id         Frame 
  9    Thread 0x7527f400 (LWP 910) "ap-i2c-1" 0x76d39d14 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  8    Thread 0x752bf400 (LWP 909) "ap-io" 0x76db8730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
  7    Thread 0x752ff400 (LWP 908) "ap-tonealarm" 0x76db8730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
 [6]    Thread 0x75448400 (LWP 907) "ap-rcin" 0x000b9bf8 in Linux::RCInput_RPI::_timer_tick() ()
  5    Thread 0x75488400 (LWP 906) "ap-uart" 0x000be140 in Linux::UARTDriver::_timer_tick() ()
  4    Thread 0x754c8400 (LWP 905) "ap-timer" 0x76db8730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x763f2400 (LWP 904) "arduplane" syscall () at ../ports/sysdeps/unix/sysv/linux/arm/syscall.S:37
  2    Thread 0x76bf2400 (LWP 903) "arduplane" syscall () at ../ports/sysdeps/unix/sysv/linux/arm/syscall.S:37
  1    Thread 0x76bf4000 (LWP 902) "arduplane" 0x76f6fb00 in ?? () from /usr/lib/arm-linux-gnueabihf/liblttng-ust.so.0

-> Ok let's see what's wrong on thread 6

Output:
(gdb) thread 6
[Switching to thread 6 (Thread 0x75448400 (LWP 907))]
#0  0x000b9bf8 in Linux::RCInput_RPI::_timer_tick() ()

(gdb) bt
0  0x000b9bf8 in Linux::RCInput_RPI::_timer_tick() ()
1  0x000bd5a4 in Linux::PeriodicThread::_run() ()
2  0x000bd6fc in Linux::Thread::_run_trampoline(void*) ()
3  0x76dafe90 in start_thread (arg=0x75448400, 
    arg@entry=<error reading variable: Cannot access memory at address 0x42f4e2cc>) at pthread_create.c:311
4  0x76d39698 in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92 from /lib/arm-linux-gnueabihf/libc.so.6

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x75448400 (LWP 898)]
0x000b9bf8 in Linux::RCInput_RPI::_timer_tick() ()

Remote connection is able to mess with BCM DMA PPM Thread Timing I think. 
And another BCM DMA related issue so I am very sorry, can't do a PR.

IMHO this issue is critical because some event, (someday it may be something very different), is able to take down the Ardupilot Linux threading model very easily. Securing it would be great.

**Comment by lucasdemarchi** [comment]
This was fixed by ignoring the right signals.
