### ISSUE TITLE
Plane: motor spins when disarmed

### ISSUE THREAD

**Issue by Autonomost** [ArduPilot/ardupilot#4875]
#### Issue details
When the plane is disarmed and on the ground the user is able to spin up the motor by simply reversing the throttle in mission planner. This has also been confirmed in SITL.
#### Version
3.7.0 

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
Fixed wing

#### Hardware type
Pixhawk

#### Logs
https://www.dropbox.com/sh/yli8inghb2ynx6x/AAAJHA72az1cDROwp4z7M9Uma?dl=0

**Comment by MRazgunas** [comment]
I think it is normal behavior. When you reverse throttle channel ArduPlane assumes that idle throttle is MAX channel value. Maybe this could be improved with more warnings in GCS side.

**Comment by magicrub** [comment]
Firstly, there's nothing the flight controller can do about this with PWM based ESCs. When configuring motors it is expected you are changing the settings to match your ESC. If you are changing them to something else then I'm not sure what behavior you would expect. With a digital ESC, such as UAVCAN, then we should handle this. I don't have an ESC to check, would be nice if someone could do that same test on that hardware.

closing.

**Comment by magicrub** [comment]
Also, to be clear, this effects all platforms on all PWM ESCs on all autopilots (not just ArduPilot)
