### ISSUE TITLE
 PixHawk crashed while ground testing 

### ISSUE THREAD

**Issue by kwikius** [ArduPilot/ardupilot#4888]
#### Issue details

From 
http://discuss.ardupilot.org/t/pixhawk-crashed-while-ground-testing/11638/1
http://discuss.ardupilot.org/t/gps-horizon-error/11684
#### Version

3.4-rc5
#### Platform

[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

Octa
#### Hardware type

Pixhawk
#### Logs

http://discuss.ardupilot.org/uploads/default/original/2X/f/f78d3c160b71117c00d5fb5bc301458e36bdc7c0.zip

**Comment by Naterater** [comment]
Was there any resolution of this?

**Comment by mboland** [comment]
Yes. It turned out to be some insidious bug in the SBF drivers.
