### ISSUE TITLE
Bug in NavEKF median filtering RangeFinder data

### ISSUE THREAD

**Issue by johnhump** [ArduPilot/ardupilot#4898]
#### Issue details
Starting at line 5137, of ver 3.4, master branch, AP_NavEKF_core.cpp, this logic block is incorrect:
if (storedRngMeas[0] > storedRngMeas[1]) {
                minIndex = 1;
                maxIndex = 0;
            } else {
                maxIndex = 0;
                minIndex = 1;
}
Regardless of the if statement, maxIndex is always set to 0 and minIndex is always set to 1.  This is a small and easy change and I'm not motivated to learn the pull request process.

#### Version
First saw on 3.3.2, apparently still exists on 3.4

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by magicrub** [comment]
Thanks for the find, we'll look into it!

**Comment by priseborough** [comment]
Thats in the old EKF - I will check to see if it appears in EKF2

**Comment by priseborough** [comment]
Thanks for that @johnhump, it affected the new filter as well. I've submitted a PR.

https://github.com/ArduPilot/ardupilot/pull/5020

**Comment by rmackay9** [comment]
Fixed in master and will go out with -rc7 within a week.
