### ISSUE TITLE
Better error output for rally point problems

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#4899]
If you look here: 
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L2027 
you'll see that the error message "Bad rally point message ID" can mean two things:
1) There is a protocol problem in that the point index is greater than the RALLY_TOTAL param.
2) The number of rally points exceeds the maximum allowed.

In both of these case the error message shown to the user is not very useful to help them understand what is going on. They should really say what the actual problem is:
1) "Rally point count exceeds RALLY_TOTAL"
2) "Rally point count exceeds maximum allowed"

Also the message is sent as MAV_SEVERITY_NOTICE when in reality this is an error. That should be changed as well.

If you look a few lines down from the link I provided you'll see a similar case for:

```
        if (packet.count != copter.rally.get_rally_total()) {
            send_text(MAV_SEVERITY_NOTICE,"Bad rally point message count");
            break;
        }
```

This should also use update both on MAV_SEVERITY_NOTICE and the error wording.

I haven't checked if the ArduPlane code has the same problem but I assume so.

**Comment by IamPete1** [comment]
This seems to have been fixed at some point, that error message is long gone.
