### ISSUE TITLE
AP_Notify should be statusing filter status not GPS status

### ISSUE THREAD

**Issue by John-Ingersoll** [ArduPilot/ardupilot#4909]
#### Issue details
AP_Notify subclass RGBLED reports the status of GPS to the pilot.   Pilots assume that this is directly reflective of the EKF filter performance to allow different nav modes (Alt Hold, Loiter, Auto).  This breaks the encapsulation of the filter because it reproduces similar but not quite exact duplicate logic as all of the SetAidingMode and application level *_init functions.  AP_Notify should work on the outputs of the EKF to state that certain modes are available.  (Ideally, the AP_Notify wouldn't even know that but would rather just have states like NormalMode[0-4] and AlarmMode, FailsafeMode and events like Accept, Deny, Warn) 

Since RGBLed replicates some but not all of the other filter code, it provides a wrong green light when in non-gps configurations such as OF modes and other custom sensors.

The LED should status the three capabilities of navigation:
Failsafe mode = Red/Yellow blink
No flight capable (pre-arm checks fail) = Yellow blinks

When disarmed:
Direct flight capable (stabilize, acro, land no gps  possible) = Yellow blinking fast
Altitude control (land with gps, alt hold possible) =  blue blinking
full control possible (loiter, auto, RTL, guided possible) = green blinking

When armed colors would be solid and not blinking.

**Comment by John-Ingersoll** [comment]
Oops,  mostly duplicative of #2168

**Comment by magicrub** [comment]
Closing in favor of https://github.com/ArduPilot/ardupilot/issues/2168
