### ISSUE TITLE
ArduPlane v3.7.0 - Sends mavlink messages with two different system ids

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#4912]
#### Issue details
Steps:
* Flash ArduPlane 3.7.0 to Pixhawk
* Boot QGC (with Pixhawk disconnected)
* Connect Pixhawk to QGC via USB

Result:
ArduPlane sends mavlink messages with sysid of 7 and 1. 1 is the correct system id. This causes QGC to think there are two different vehicles connected and shows all it's multi-vehicle ui. Pretty bad bug for any groundstation that supports multiple vehicles. The mavlink messages with id 7 are sent first during board boot I believe, then it switches to 1.

Here is QGC mavlink inspector showing the messages:
![screen shot 2016-09-30 at 3 57 48 pm](https://cloud.githubusercontent.com/assets/5876851/19009293/26c7ec84-8727-11e6-9c54-78c22c1ac17e.png)

**Comment by DonLakeFlyer** [comment]
ArduCopter 3.3 doesn't do this. ArduPlane didn't used to do this in older versions.

**Comment by mboland** [comment]
Arducopter does this in 3.4, QGroundControl and Mission Planner

**Comment by tridge** [comment]
thanks for letting me know, I'll fix this now

**Comment by rmackay9** [comment]
I tried to set this to Copter-3.4 milestone but github doesn't accept two milestones so resetting to plane only.

**Comment by KIrill-ka** [comment]
As a workaround, I set MAV sysid to 7 :)

**Comment by DonLakeFlyer** [comment]
Ah, thanks for the suggestion! Helpful for my testing.

**Comment by OXINARF** [comment]
Fixed in master.

**Comment by rmackay9** [comment]
Oh, excellent that it's fixed!
