### ISSUE TITLE
needing help on setting up landing gear 

### ISSUE THREAD

**Issue by gwthorn8280** [ArduPilot/ardupilot#4914]
#### Issue details
dont under stand how to hook up landing gear to a apm 2.8.1 like to use radio switch but wont to make sure they will come down with RTL and fail safe

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover

#### Airframe
Quanum 680pro hex

#### Hardware type
apm 2.8.1
firmware 3.2.1
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This is a support question and those should be posted at the forum (http://discuss.ardupilot.org).
