### ISSUE TITLE
Inconsistent time in mavlink GPS messages

### ISSUE THREAD

**Issue by BinhSw** [ArduPilot/ardupilot#4924]
#### Issue details
I am noticing something strange when reading the telemetry data for GPS, and Attitude of the airplane. I am using the mavlink_global_position_int_t message for GPS data, and mavlink_attitude_t for attitude data. When I plot the time interval between the time_boot_ms of the GPS messages, it wasn't consistent between each message, but there was a pattern.
![screenshot at oct 03 15-58-40](https://cloud.githubusercontent.com/assets/20650611/19053845/4b262a70-8982-11e6-8f24-b4f4eeb6ea13.png)
Does this have to do with how ardupilot schedules the sending of mavlink messages?

#### Platform
Ardu Plane

#### Airframe type
Fixed wing aircraft

#### Hardware type
Ardupilot Mega 2.6

**Comment by magicrub** [comment]
Hi @BinhSw , thanks for taking the time to post this error you found. I see you're using APM 2.6 hardware which means you're using old firmware so this problem has most likely been fixed already. However, before I close this issue it would be nice for our GPS maintainer, @WickedShell, to chime in to confirm.

**Comment by BinhSw** [comment]
Thanks for replying quickly!
I will probably upload the latest version of the software.
It would be great if they fixed this in the new version.

**Comment by WickedShell** [comment]
@BinhSw I'd guess that this is just a telemetry scheduling issue. If you look in the dataflash logs do you see this same oscillation? (I'm guessing it will disappear)

**Comment by BinhSw** [comment]
Sorry, I am new to the ardupilot.
How do you view the dataflash logs?

**Comment by magicrub** [comment]
http://ardupilot.org/planner/docs/common-diagnosing-problems-using-logs.html

**Comment by BinhSw** [comment]
I just uploaded the latest version of arduplane, and the problem seems to have been fixed.
I set the GPS telemetry rate to 10hz, and the time intervals between messages are consistently 200, 0, 200, 0, 200 milliseconds. Is this because the GPS only updates 5hz?
The attitude update intervals seem to be good too, 100 +- 3 ms.

**Comment by magicrub** [comment]
Glad you confirmed it was fixed! The GPS update rate depends on the GPS, but yes 5 Hz is common. Closing...

**Comment by WickedShell** [comment]
global_position_int != GPS postion for the record, so 10Hz is totally
reasonable. It's the position from the AHRS rather then the GPS.

**Comment by BinhSw** [comment]
If it is the AHRS, why is the time interval between messages 200, then 0? Is the position from AHRS more accurate than from GPS?

**Comment by WickedShell** [comment]
AHRS is the result from fusing in the EKF or DCM with the accelerometers.
(On a APM 2.6 you can't run the EKF so it's just the DCM).
