### ISSUE TITLE
safety switch not disabling  twin engine plane

### ISSUE THREAD

**Issue by yak-54** [ArduPilot/ardupilot#4950]
[qb60.param.zip](https://github.com/ArduPilot/ardupilot/files/518563/qb60.param.zip)

Issue details

Ok i have twin engine plane running 3.7.0 and 3DR pixhawk
 i have throttle in one in RC3 and the other RC11 and RC11_FUNCTION: is set to 70 throttle all work's fine but i was testing power system with a watt meter then i finished pressed the safety switch  i hit the throttle by mistake and the plane took off into the wall the left throttle [ RC11 ] does not disarms pressing safety switch 

Version
plane 3.7.0

Platform
 Plane

Airframe 
Fixwing

3DR pixhawk

**Comment by magicrub** [comment]
Thanks, Colin! Do you have a params file you can share so we can see your configuration?

**Comment by yak-54** [comment]
yep can do all done

**Comment by magicrub** [comment]
@tridge I can look into this for you

**Comment by yak-54** [comment]
some else i have notice that none of the AUX channels get disabled as i do have 
left Ail in RC9
left Elev in RC10
left throttle in RC11
the resign why i did run Y leads on the servo's till i had one blown  the fuse on a pixhawk i lost the hole plane

**Comment by gmorph** [comment]
Any updates?

**Comment by yak-54** [comment]
not yet but i have found out that it does not disable any of the AUX channels there all still live

**Comment by gmorph** [comment]
Any updates or can we close this out?

**Comment by yak-54** [comment]
have not tested it yet will do to night they say its fixed the plane  just been hanging from the roof waiting for a fix :)

**Comment by yak-54** [comment]
i will test it out tonight

**Comment by yak-54** [comment]
just put 3.7.1 still the same does not disarms by pressing hardware switch and disarming in mission planer

**Comment by WickedShell** [comment]
@tridge was this fixed as part of the SRVChan stuff?

**Comment by tridge** [comment]
I believe this is fixed now, but I'd appreciate confirmation from @yak-54. Please test the latest build of master and see if its OK now.

**Comment by yak-54** [comment]
Good will test it tonight when i get home from work :)

**Comment by OXINARF** [comment]
@yak-54 Yes, latest Plane beta should work.

**Comment by yak-54** [comment]
Yep all good thanks  safety switch is now disabling all servo output 
thank you all 
now just have to work out why i am getting bad log error

**Comment by WickedShell** [comment]
Thanks for verifying it works correctly now! I'd post a topic on discuss if you can't resolve the bad logging warning yourself.
