### ISSUE TITLE
Copter-3.4: allow auxiliary channels to move before safety switch is pressed

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#4955]
In Copter-3.3.3 the auxiliary RC outputs output values even before the safety switch is pressed.  In Copter-3.4-rc5 (and earlier) they do not.

**Comment by rmackay9** [comment]
I'm not sure if Tridge or I will implement this.

**Comment by tridge** [comment]
the issue doesn't explain what behaviour you want, we want it configurable I assume? with default with aux enabled?

**Comment by tridge** [comment]
this is now in master, with automatic setting of the BRD_SAFETY_MASK for multicopters.
Needs testing!

**Comment by rmackay9** [comment]
Thanks!  Closing (we can re-open if testing fails).
