### ISSUE TITLE
DISARM_DELAY is broken 

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#4985]
#### Issue details
Setting DISARM_DELAY to 0 don't let  the drone armed on GUIDED mode
#### Version
lastest master
#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

####
Procedure to see the error : 
sim_vehicle.py --console --map -S 10 -v ArduCopter -w 
(speedup 10 to accelerate things)
 then mode guided
arm throttle
(it should disarm imediately)
param set DISARM_DELAY 0
param show DISARM_DELAY
(should be 0)
arm throttle
(it disarm directly)

Log show it trigger GCS failsafe
Test on e71c71fcac1a8a43a65a874d12fb9fedc937d19e    https://github.com/ArduPilot/ardupilot/commit/e71c71fcac1a8a43a65a874d12fb9fedc937d19e

**Comment by magicrub** [comment]
please provide a procedure that displays incorrect behavior. Also, saying "latest master" when looking back a year from now doesn't help. Please be specific on the build (date, hash, whatever).

**Comment by rmackay9** [comment]
I think @khancyr found out the issue (it was the GCS failsafe jumping in and disarming the vehicle) so closing this issue.
