### ISSUE TITLE
Can’t see new parameter in mission planner 

### ISSUE THREAD

**Issue by hamididari** [ArduPilot/ardupilot#4996]
hi guys
I have recently added a parameter to Ardupilot using http://dev.ardupilot.com/wiki/code-overview-adding-a-new-parameter/1 as a guideline. Somewhere on these boards but I can't see my new parameter in full parameter list in mission planner. what would i do to see my new parameter in mission planner?

i use Copter and pixhawk

**Comment by magicrub** [comment]
Please post a link to your branch so we can see what changes you made.

**Comment by hamididari** [comment]
i made a mistake in code
tnx a lot for replying
