### ISSUE TITLE
Manual start position not working on 1.0.0

### ISSUE THREAD

**Issue by zverugaz** [ArduPilot/ardupilot#5007]
#### Issue details

When I not connenct a GPS to my Pixhawk with Antenna Tracker firmware and set START_LONG/START_LAT to some position (40 and 40 for example) a AT icon still show on map on position 0 for latitude and 0 for longitude (left from Africa). When I install a 0.8 version everything work well - AT show himself on correct postition.
#### Version

1.0.0
#### Platform

[  ] All
[ X ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

Octa
#### Hardware type

pixhawk
#### Logs

https://www.dropbox.com/s/5ogze7lzfgknycf/2016-10-17%2020-26-42.tlog?dl=0

**Comment by Naterater** [comment]
Is this still an issue with any more recent firmwares?

**Comment by rmackay9** [comment]
I don't know, we'd need to investigate probably as part of a new Tracker beta period and release.

**Comment by IamPete1** [comment]
looks like this issue is still present, I will see what I can do

**Comment by IamPete1** [comment]
fixed
