### ISSUE TITLE
Param file : allow to have sub parameter file

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#5013]
Currently, we have a set of default parameter files that are update on need (Lets call them master)
But we also get some sub parameter file : like gazebo one, that only change some parameters from default. This is problematic since those type of file don't follow their master.

We should create a way to load default file first and then sub parameter. That way sub parameter stay minimal and got improvement from their master

**Comment by OXINARF** [comment]
This was done in #5162
