### ISSUE TITLE
Writing Servo pwm

### ISSUE THREAD

**Issue by hamididari** [ArduPilot/ardupilot#5029]
#### Issue details
hi guys 
I wrote this code for write pwm in aux pin0 but I couldn't see pwm signal in this pin with oscope.
```
#ifdef USERHOOK_SUPERSLOWLOOP
uint16_t pwm = 2000;
void userhook_SuperSlowLoop()
{
uint8_t _channel=9;
pwm = 3000 - pwm;
hal.rcout->enable_ch(_channel-1);
hal.rcout->write(_channel-1, pwm);
}
#endif
```
and I defined USERHOOK_SUPERSLOWLOOP the loop work correctly
any idea about my problem?
tnx
#### Version
last Version

#### Platform
Copter

#### Hardware type
pixhawk

**Comment by OXINARF** [comment]
You already posted in the forum and that is the correct place for a question like this. You can also try Gitter.
The issues list is for confirmed bugs or feature requests.
