### ISSUE TITLE
Copter: Yaw to Initial Heading during Landing Near Home

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#504]
Currently, when doing an RTL, the copter will automatically yaw to face the initial heading that was saved when the copter was armed.   This is a nice feature that makes for a really professional looking landing, and can help pilot maintain orientation during this critical phase.

However, if running a mission using the Land command, the yaw does not yaw back to face initial location.

It would be nice if we could do a check, whereby, if we are doing a Land command where the landing location is maybe 5 or 10m from the Home position, then we can assume the pilot would like to yaw back to initial heading.

Alternatively, could this be an option in the Landing command?  0 for Yaw Hold, 1 to return to initial heading on any landing?

**Comment by lthall** [comment]
Hasn't this been done?

**Comment by CetINV** [comment]
I'm guessing its still the manual waypoint way to achieve such a landing behavior? 

Otherwise we could use an RTL but we'd have to make sure the RTL is set to happen at the height of the mission or at the desired RTL height.

**Comment by peterbarker** [comment]
You can get the desired effect on modern ArduPilot by setting `WP_YAW_BEHAVE` to the value 1, "point to next waypoint".

The default value for this is "point to next waypoint except when doing the RTL"  a value of 4.

I think we can close this one.  Does anyone disagree?

**Comment by rmackay9** [comment]
I think it's OK to close this
