### ISSUE TITLE
Feature request: External I2C Buzzer for Pixhawk Lite

### ISSUE THREAD

**Issue by thecodingfrog** [ArduPilot/ardupilot#5059]
#### Issue details
As Pixhawk Lite does not have any buzzer pin, it would be cool to use board like MCP4725 to add an I2C buzzer

#### Version
All

#### Platform
[ * ] All
[  ] AntennaTracker
[ * ] Copter
[ * ] Plane
[ * ] Rover

#### Airframe type
All

#### Hardware type
Pixhawk Lite

**Comment by lvale** [comment]
The PixHawk lite is a stripped down version of the original version and it is sold as such. Some of the things that were removed are, the buzzer and also UAVCan support.

I don't believe that we should support/circumvent something that the OEM chose to remove, and it is clearly indicated on the sites where it is sold that it lacks the buzzer.

(Note) I have one of these boards
