### ISSUE TITLE
problem in make ardupilot in windows

### ISSUE THREAD

**Issue by hamididari** [ArduPilot/ardupilot#5077]
hi guys

i try to make ardupilot in windows from [this](http://ardupilot.org/dev/docs/building-px4-with-make.html)
but i got this err 
![image](https://cloud.githubusercontent.com/assets/13236906/19760078/c4d43ec6-9c3c-11e6-85ca-8fd5aa92353b.png)

any idea about my problem ?
i use pixhawk and ArduCopter
thanks

**Comment by khancyr** [comment]
hi did you install lastest toolchain and  use git submodule update --init --recursive ? 
The error looks like missing mavlink header, but it should have been generated before compiling

**Comment by hamididari** [comment]
i uninstall my px4 tool chain and install the last version and make again but i got the same err again

**Comment by khancyr** [comment]
Sorry I don't use windows for that, a more qualified person should answer.
If you change the toolchain to lastest, do a make clean to remove previous compiled filed and retry

**Comment by rmackay9** [comment]
Maybe try a "make px4-clean" and "make clean" and/or delete the /modules/PX4Firmware and mavlink directories.  I compile all the time with Windows using the latest toolchain which is here:http://firmware.ap.ardupilot.org/Tools/PX4-tools/

**Comment by OXINARF** [comment]
This is more of a support question and not a bug so I'm closing this. Feel free to post in our forum (http://discuss.ardupilot.org) or chat with us in Gitter (http://gitter.im/ArduPilot/ardupilot) if you still need help.
