### ISSUE TITLE
MAVLink: Update GPS_RTCM_DATA documentation/descriptions

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#5083]
#### Issue details

We extended the meanings of the GPS_RTCM_DATA flags field but never updated the common.xml. We need to grab the bits and mark the usage of the fragmenting.

**Comment by rrr6399** [comment]
Saw this info in Mission Planner:
https://github.com/ArduPilot/MissionPlanner/blob/master/Mavlink/MAVLinkInterface.cs#L2502
```
                    // check if its a fragment
                    if (len > 1)
                        gps.flags = 1;
                    else
                        gps.flags = 0;

                    // add fragment number
                    gps.flags += (byte)((a & 0x3) << 1);

                    // add seq number
                    gps.flags += (byte)((inject_seq_no & 0x1f) << 3);
```

**Comment by rrr6399** [comment]
Its also confusing as to whether the data field should be a constant size of 180 or match the actual size of the RTCM payload.

**Comment by WickedShell** [comment]
Match the size the payload

**Comment by WickedShell** [comment]
Done in https://github.com/ArduPilot/mavlink/pull/28, upstreamed in https://github.com/mavlink/mavlink/pull/692
