### ISSUE TITLE
Copter: (de)activate gimbal stabilization from transmitter

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot#509]
It would IMHO be useful to be able to (de)activate gimbal stabilization via a Ch7/Ch8 switch.

**Comment by Naterater** [comment]
I'm not sure if I understand why this is necessary. Not much conversation on it in the last few years. This is a candidate for closing again, and a lot has changed on RC input functions recently.

**Comment by rmackay9** [comment]
I guess this might make sense for a servo gimbal (not a brushless gimbal) where the user wants to lock the camera in place for some reason.  I'm not sure why a user would want to do this but perhaps there's a reason...

**Comment by peterbarker** [comment]
The `MOUNT_RETRACT` RC channel option does this.
