### ISSUE TITLE
Dataflash: CMD message should include altitude type

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#5115]
Copter-3.4 includes terrain following in AUTO mode but we currently cannot see if the mission commands recorded in the dataflash are relative-to-home, above-sea-level or above-terrain.  This can make handling support calls like this one difficult: http://discuss.ardupilot.org/t/cant-use-waypoints-with-sbf-gps-enabled-3-4-rc7-no-terrain-data-error/12474

**Comment by peterbarker** [comment]
This is a duplicate of #5975

**Comment by enjoybeta** [comment]
#7936 just noticed this pull
