### ISSUE TITLE
send mavlink_msg_gps_input,but don't receive any gps data.

### ISSUE THREAD

**Issue by icyore** [ArduPilot/ardupilot#5121]
I send the fakeGPS by mavlink. As the plugin of mavros_extra, I can't not receive any GPS data on the pixhawk and the LED don't turn green. I am comfused.

mavlink_message_t msg;
mavlink_msg_gps_input_pack_chan(
UAS_PACK_CHAN(uas),
&msg,
ros::Time::now().toNSec()/1000,
0,
32767,
0,
0,
2,
int32((lat_rad * 180 /M_PI)*10000000),
int32((lon_rad * 180 /M_PI)*10000000),
float(alt),
0.5,
1.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
11);
UAS_FCU(uas) -> send_message(&msg);

ardupilot ArduCopter 3.4.0 rc 7 quadrotor
pixhawk 
ttyUSB0 connect to the telem2

**Comment by OXINARF** [comment]
This is a support question and those should be posted at the forum (http://discuss.ardupilot.org). You can also talk to developers in Gitter.
