### ISSUE TITLE
[Plane][VTOL]Motor configuration X,H,Hexa,Octa selectable on the GUI of Mission Planner

### ISSUE THREAD

**Issue by andrea25** [ArduPilot/ardupilot#5129]
#### Issue details
I suggest that motor configuration should be selectable on the GUI of the Mission Planner insted of going on the full param list to do this.
With the GUI interface to select the airframe type (X,H,Hexa,Octa) this process can be more easy also for the beginner.

#### Version
ArduPlane 3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover

#### Airframe type
QuadPlane 

#### Hardware type
PixFalcon

#### Logs
NoLogs

**Comment by OXINARF** [comment]
This is an issue with Mission Planner, you should post that in the respective repository (https://github.com/ArduPilot/MissionPlanner).
