### ISSUE TITLE
LogAnalyzer: Vcc check for plane is out of date

### ISSUE THREAD

**Issue by Georacer** [ArduPilot/ardupilot#5134]
#### Issue details
Reading the test code for the [Vcc test](https://github.com/ArduPilot/ardupilot/blob/master/Tools/LogAnalyzer/tests/TestVCC.py) I noticed that it reads Vcc from the CURR message, instead of the POWR message.
The related fields are not found in the CURR message anymore.
This change was introduced at least from here: https://github.com/ArduPilot/ardupilot/commit/3ed2fafefa2981d9ea720b552ba405dbeae37eca

#### Version
At least v3.5.2 and forward

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
All

#### Hardware type
N/A

#### Logs
N/A

**Comment by OXINARF** [comment]
This has been fixed by @peterbarker with f1641161d76b6640fef8f658051264ff5022335e and 0168493d8a5439a5694d03b65625be1bd41dfe5e. It can still be made better by not checking that CURR is available, but instead that we have Vcc info, but this bug specifically is fixed.
