### ISSUE TITLE
APM:Copter  3.4.1   RC7_FUNKTION = 32 not working anymore

### ISSUE THREAD

**Issue by ManfredDick** [ArduPilot/ardupilot#5185]
I run APM:Copter  3.3.3   on a 600 size heli with direct tail drive.
H_Tail_TYPE =2 and RC7_FUNKTION = 32 was set and it worked fine with Copter 3.3.3
After upgrading to Copter 3.4.1 the direct tail drive does not work anymore, RC7 is 0.

**Comment by OXINARF** [comment]
@rmackay9 @tridge @R-Lefebvre Can any of you check this?

**Comment by ChristopherOlson** [comment]
@ManfredDick we have a fix for this in the works for Copter. Sorry it has been ignored. I think Fred will be contacting you with more information on it. A PR has been submitted for it, but is still under review.

**Comment by ChristopherOlson** [comment]
I'm closing this. Was fixed by PR #7281
