### ISSUE TITLE
AUTOTEST: map don't get close when using --map

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#5187]
#### Issue details
using something like
python Tools/autotest/autotest.py --map -j2 build.APMrover2 drive.APMrover2  
don't close map, so many maps are open.

#### Version
master (tested on https://github.com/ArduPilot/ardupilot/commit/4bf6eb173660413f99bde647a990efca87ee2b6d)

#### Platform
[ X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by Naterater** [comment]
Any updates @khancyr?

**Comment by khancyr** [comment]
it is working now
