### ISSUE TITLE
SITL with x-plane does not connect to mission planner

### ISSUE THREAD

**Issue by Abdullah1990** [ArduPilot/ardupilot#5221]
#### Issue details
As I Run the SITL using mission planner with the x-plane selected as model type. The arduplane.exe wont connect to the ground station. As if it's not sending any heartbeats to the ground station. I tried the SITL with the PLANE it works fine. It seems that when the Arduplane.exe connects with x-plane thru UDP it wont connect to the ground station  (Mission planner 1.3.42) using TCP.

-- If a run the Arduplane.exe from command line with parameter --model PLANE  it works fine. 
but if I run it with --model XPLANE mission planner can not connect to mission planner

-- The TCP  port to connect to missiion planner is port # 5760
#### Version
The SITL that is used Arduplane v3.8 (Beta1 (c0303ffe))

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

#### Airframe type
Fixed win

**Comment by ayoubzar** [comment]
did you finnd any solution I am facing the same problem again ???

**Comment by DawoodTaii** [comment]
By experience, just make sure that x-plane is running before connecting to SITL. Once x-plane is started with correct configuration there should be no problem.

**Comment by IamPete1** [comment]
Sorry we never got to this.

**Comment by Abdullah1990** [comment]
That is ok, I think it has been fixed.
