### ISSUE TITLE
about make px4-v2 issues

### ISSUE THREAD

**Issue by skyyuzhang** [ArduPilot/ardupilot#5257]
#### Issue details
_Please describe the problem, or desired feature_
When I run  order "make px4-v2" at PX4Console in Windows 10 . I always  run into some trouble , every time, at last it always show me "  **+ echo' init of mavlink failed'**  " .I don't konw how to fix it.
So please help me  help! help!
#### Version
APM Copter 3.4

#### Platform
[  ] All
[  ] AntennaTracker
[ 1 ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This a development support question and those should be posted at the forum (http://discuss.ardupilot.org) or asked about in Gitter (http://gitter.im/ArduPilot/ardupilot). When you do, share a more complete error report, otherwise it's hard to help.
