### ISSUE TITLE
Plane: PX4 mixer can still fail (and never be corrected)

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#5263]
#### Issue details
PX4IO mixer can still perpetually fail as of the released Plane 3.7.0 firmware version. (And nothing major has happened since then w/ regards to mixer failing/recovering).

#### Version
ArduPlane V3.7.0 (2e240699)

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

#### Hardware type
Pixhawk

**Comment by Naterater** [comment]
Can this close since the PX4IO firmware is no longer?
