### ISSUE TITLE
make DO_SET_HOME take effect immediately if already heading home

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#527]

**Comment by Naterater** [comment]
Is this still relevant?

**Comment by rmackay9** [comment]
In Copter we certainly still have this issue although no user has complained as far as I know.  The issue is that if home is moved after the vehicle has switched to RTL, it will still return to the position home was at when RTL was initiated.

**Comment by Naterater** [comment]
I don't think changing the home point in the middle of heading home is a good idea though... could you help me understand why that's useful and the safe thing to do?

**Comment by auturgy** [comment]
This is needed for mobile home positions (ships, trucks, etc).

**Comment by peterbarker** [comment]
This is complicated by our rally-point logic.  If home is reset (e.g. via a GCS `DO_SET_HOME`) while a vehicle is in RTL, do we absolutely use that home position as where to go, or do we still go to the *nearest* rally-point-or-home?

**Comment by auturgy** [comment]
Two realistic choices: a param to let the user decide, or the new home.
If home is changed during an RTL, I think it’s reasonable to assume (but still document) that they’ve done it on purpose and want the vehicle to go to the new location.

**Comment by magicrub** [comment]
I'm in favor of simply changing the home position, no rally logic changes needed. No param.

**Comment by peterbarker** [comment]
@WickedShell mentioned that he's also seen users shift a rally point around which a plane is circling, expecting the vehicle to orbit the new location of that rally point.  That's a whole new level of state-keeping if we wanted to allow that.  Similarly for waypoints, I guess.  Not trying to scope-creep this PR, just trying to ensure we don't stuff up possible future enhancements.
