### ISSUE TITLE
need help, what should i do?

### ISSUE THREAD

**Issue by hussein-hamadi** [ArduPilot/ardupilot#5273]
![sans titre](https://cloud.githubusercontent.com/assets/23615290/20601233/db62307c-b257-11e6-9861-4f4920ec5fa4.png)
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This is a development support question and those should be posted at the forum (http://discuss.ardupilot.org) or asked about in Gitter (http://gitter.im/ArduPilot/ardupilot).

Regarding your error, make sure you have correctly updated your local copy. You can also try a `make clean` and then try again. We build and run SITL everyday and it is working.
