### ISSUE TITLE
Copter: support MAV_CMD_DO_SET_MODE

### ISSUE THREAD

**Issue by credtiger96** [ArduPilot/ardupilot#5281]
#### Issue details
Ardupilot code use 
MAVLink uses mavlink message SET_MODE (#11) to change vehicle's mode, but according to mavlink document, 
it is deprecated and recommended to use COMMAND_LONG with MAV_CMD_DO_SET_MODE.
but ardupilot seems that dose not support that interface. 
is it intended? or should I contribute to it? 

#### Version
_What version was the issue encountered with_
latest version

#### Platform
[  ] All
[  ] AntennaTracker
[  o ] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
It looks like only Copter doesn't support it (although support in the other vehicles could probably be better). PRs are welcomed.

**Comment by peterbarker** [comment]
I believe all vehicles now support this.

**Comment by josezy** [comment]
> I believe all vehicles now support this.

since which version for ArduCopter?
