### ISSUE TITLE
ArduPlane: QuadPlane, ATT.DesYaw is not logged

### ISSUE THREAD

**Issue by ferdicakmak** [ArduPilot/ardupilot#5302]
#### Issue details
Hello,

I am using Pixhawk with ArduPlane V3.7.1 for QuadPlane setup. I see that ATT.DesYaw is logged as 0 in dataflash along the whole flight, when in QSTABILIZE, QHOVER and FBWA (other modes are not tested). Other variables of ATT like DesRoll, Roll, DesPitch and Pitch are fine.

![image](https://cloud.githubusercontent.com/assets/8240355/20759271/23a21538-b725-11e6-9608-bc3cedebc706.png)

Any suggestions or solutions?

Thanks,
Ferit.

#### Version
ArduPlane V3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
QuadPlane

#### Hardware type
Pixhawk

#### Logs
-

**Comment by expntly** [comment]
@magicrub @tridge Any idea why this is not being logged?  Would be helpful for yaw tuning.  Happy to try putting together a PR if the change doesn't require much knowledge.

**Comment by expntly** [comment]
@peterbarker maybe knows?

**Comment by ferdicakmak** [comment]
I think it is fixed in ArduPlane 3.8.0beta5. ATT.DesYaw is logged correctly.

**Comment by peterbarker** [comment]
Commit fedabd1ace23797d6eeb75b351f7d72029e93881 added this logging.

**Comment by expntly** [comment]
Just loaded 3.8.0-beta6.  Is this really working?

<img width="1121" alt="screen shot 2017-07-15 at 2 08 14 pm" src="https://user-images.githubusercontent.com/6870452/28242061-3521654e-6967-11e7-8508-9a689cbe69b2.png">

**Comment by expntly** [comment]
Here's another flight and its log.  Logging isn't empty at least like before but I'm seeing strange spikes.

<img width="980" alt="screen shot 2017-07-16 at 1 03 14 pm" src="https://user-images.githubusercontent.com/6870452/28250089-29a43eec-6a27-11e7-8a53-4a4f09d65ca3.png">

DF log: https://www.dropbox.com/s/v644adu7iu7lss8/00000028.BIN?dl=0

**Comment by OXINARF** [comment]
@expntly I don't see anything strange. Yaw range is [0; 360[ so when it is around 0/360 it will show those "spikes" in the log.

**Comment by expntly** [comment]
@OXINARF I see.  I guess I was also surprised by DesYaw and Yaw not following one another like Roll/DesRoll and Pitch/DesPitch would.  DesYaw is so flat that I'm suspecting something is wrong and this is not related to tuning?

**Comment by expntly** [comment]
@peterbarker Looking at a log file I have with a transition from VTOL to cruise, ATT.DesYaw goes to 0 after the transition to cruise.  Is that expected?  Roll and Pitch are logged just fine in both modes.

See below at around 3.35, then it comes back at around 3.44 when de-transitioning.

<img width="1207" alt="screen shot 2017-11-10 at 6 14 45 pm" src="https://user-images.githubusercontent.com/6870452/32683732-2b88e758-c643-11e7-9b21-171e0a950e03.png">

ArduPlane V3.8.2.

**Comment by peterbarker** [comment]
On Sat, 11 Nov 2017, expntly wrote:

> @peterbarker Looking at a log file I have with a transition from VTOL to
> cruise, ATT.DesYaw goes to 0 after the transition to cruise. Is that
> expected? Roll and Pitch are logged just fine in both modes.

It's expected:

https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/Log.cpp#L16
