### ISSUE TITLE
AP_Landing: Lift all the landing flight stages into just stage LAND

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#5323]
#### Issue details
AP_Landing should manage all the finer details of the different steps in a landing, and there should only be a single FLIGHT_STAGE_LAND which signifies to call into AP_Landing to do work. This is needed to allow other landing types.

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

**Comment by magicrub** [comment]
I like that. Each landing type has its own state machine and mini stages. What about flaps? Right now they're purely airspeed controlled, think that should go down in there too?

**Comment by WickedShell** [comment]
I think it should. float AP_Landing::get_flap_percentage() comes to mind...
(I think its a percent that it wants right?) Would allow the different
landing types to pick what they need easily, and possibly apply it
elsewhere (not sure why they would want to apply it elsewhere yet, but need
to be able to opt out of it if you don't want them)

**Comment by WickedShell** [comment]
This was done, we never closed the issue.
