### ISSUE TITLE
Plane: QuadPlane sluggish at WP before next command 

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#5326]
#### Issue details
In a AUTO mission with the vehicle asked to move to a WP in VTOL, it will stay and hover at that WP for a while before it does anything else.  Sometimes it stays stuck there for up to a minute.

Here's a mission example where it stays stuck at command 3:
<img width="316" alt="screen shot 2016-12-04 at 3 07 29 pm" src="https://cloud.githubusercontent.com/assets/6870452/20869998/c9508dd2-ba33-11e6-9f7f-af03ba779527.png">

Here's another one where it stays stuck at command 3:
<img width="320" alt="screen shot 2016-12-04 at 3 24 47 pm" src="https://cloud.githubusercontent.com/assets/6870452/20870077/15955bc6-ba36-11e6-8fb5-b0426de7c0c9.png">

The expected behavior instead is that it starts executing the next command as soon as it enters the WP radius (or passes the orthogonal line) without any delay.

#### Version
3.7.0

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
QuadPlane

#### Hardware type
Pixhawk

#### Logs

It can be reproduced in the simulator by creating a mission such as the ones above.

**Comment by expntly** [comment]
@OXINARF I wouldn't categorize it as an "Enhancement".  There's an issue somewhere, I haven't figured what it is yet.

**Comment by OXINARF** [comment]
@expntly Not saying it isn't an issue, but it looks like the system works although it can be improved/enhanced to remove the delay.

**Comment by IamPete1** [comment]
I cant replicate this in SITL, I'm going to close, if someone has a log that shows the issue on 4.1 we should re-open.
