### ISSUE TITLE
compiler warnings - memset size 0

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#5339]
I'm seeing a compile warnings in EKF that may be a bug:
Search "In function `SoloGimbalEKF::reset()" in any linux Travis build like this one:
https://api.travis-ci.org/jobs/181633324/log.txt?deansi=true

Warning is:
lib/libap.a(SoloGimbalEKF.cpp.0.o): In function `SoloGimbalEKF::reset()':
SoloGimbalEKF.cpp:(.text._ZN13SoloGimbalEKF5resetEv+0x4a): warning: memset used with constant zero length parameter; this could be due to transposed parameters

And [here's that source](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/SoloGimbalEKF.cpp#L41) which looks OK, so not sure what to do to fix.

**Comment by WickedShell** [comment]
Fixed in dda7c615a8
