### ISSUE TITLE
How to change default channel_in in SITL?

### ISSUE THREAD

**Issue by nocternal** [ArduPilot/ardupilot#5352]
#### Issue details
In Ardu Plane SITL, I find that every time when it run, the channels in values are not changed,
ch1_in=1500
ch2_in=1500
ch3_in=1000
ch4_in=1500
ch5_in=1800
ch6_in=1000
ch7_in=1000
ch8_in=1800
...
It's not a proplaem for most of times, but now I want to use ch6_in as an angle command（-90~90 degree），so I can set it's radio_min to 1100, radio_max to 1900, and radio_trim to 1500. I also want default command of channel 6 is 0 degree, means PWM 1500.

I have to tap in
`rc 6 1500` every time I run SITL because it's default value is 1000

Where to change every channel's default in value? I search whole documant and find no code to set default value of SITL channel in. Can anyone help me?

#### Version
Win10 
use MAVProxy
ArduPlane-V3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

**Comment by magicrub** [comment]
Please post help questions on the forum discuss.ardupilot.org. Github is the developer bug reporting and feature request area. You can also ask on http://gitter.im/ardupilot

**Comment by magicrub** [comment]
Please post help questions on the forum discuss.ardupilot.org. Github is the developer bug reporting and feature request area. You can also ask on http://gitter.im/ardupilot
