### ISSUE TITLE
Setting of COMPASS_EXTERNAL params must use set_and_notify() 

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#5364]
The timing of the COMPASS_EXTERNAL params seems to be problematic. Here is what can happen:
* Boot QGC
* Connect vehicle over USB (which powers it up)
* Vehicle connects, QGC download params
* On my Pixracer all three compasses are marked as internal
* Wait a little bit, refresh params
* Now internal/external are marked correctly

Leads to incorrect information shown to the user. Also leads to incorrect processing during calibration/setup since values are stale.

**Comment by rmackay9** [comment]
so I guess we can close this now?
