### ISSUE TITLE
ARMING_REQUIRE=2 and auxiliary throttle channels

### ISSUE THREAD

**Issue by mothacehe** [ArduPilot/ardupilot#5369]
#### Issue details
Hi all,

When setting ARMING_REQUIRE to 2, no pwm is sent to throttle channel (3 by default) while disarmed. When adding an auxiliary throttle channel (e.g RC5_FUNCTION=70), a min pwm is always sent even with ARMING_REQUIRE=2 on this channel.

To prevent accidental auxiliary motor launch, wouldn't it be a better idea for auxiliary throttle channel 
to behave like the main throttle channel ?

Thanks,

Mathieu

#### Version
master

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
Disco

#### Hardware type
Disco

**Comment by WickedShell** [comment]
@tridge Is this fixed with the SRVChan stuff?

**Comment by tridge** [comment]
I haven't specifically tested this case, but the SRV_Channels change should mean it is consistent. @mothacehe, can you please test the latest master?

**Comment by IamPete1** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/18050 we now treat throttle left and right the same as main throttle and they all honor the safety mask.
