### ISSUE TITLE
Traditional Helicopter: 4 swash servos

### ISSUE THREAD

**Issue by 0n3-70uch** [ArduPilot/ardupilot#5370]
#### Issue details
Hello, I want to add a 4th swash servo to the arducopter code. I changed the code in "AP_MotorsHeli_Single.cpp" and "AP_MotorsHeli_Single.h". Here you can find the code with a 4th swash servo (how can I add this code directly without google drive):
https://drive.google.com/drive/folders/0B_Ez_duqb1SDVmoyZ0JGeTlsLWs?usp=sharing

I want to compile this code but I receive this error:
`/home/fabian/Downloads/ardupilot/libraries/AP_Motors/AP_MotorsHeli_Single.cpp: In member function 'virtual void AP_MotorsHeli_Single::calculate_roll_pitch_collective_factors()':
/home/fabian/Downloads/ardupilot/libraries/AP_Motors/AP_MotorsHeli_Single.cpp:332:25: error: array subscript is above array bounds [-Werror=array-bounds]
         _rollFactor[CH_4] = cosf(radians(_servo4_pos + 90 - _phase_angle));`

How can I fix this error?
Greetings Fabi

#### Version
3.4.3

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Traditional helicopter with four swash servos

#### Hardware type
pixhawk (px4-v2)

#### Logs
no log needed

**Comment by fhedberg** [comment]
https://github.com/ArduPilot/ardupilot/pull/3245

**Comment by 0n3-70uch** [comment]
Nice to see that there are some other guys with the same idea.

**Comment by OXINARF** [comment]
This is a development question and those should be posted at the forum (http://discuss.ardupilot.org) or asked about in Gitter (http://gitter.im/ArduPilot/ardupilot).

Look at the PR @fhedberg posted for a correct implementation.

**Comment by 0n3-70uch** [comment]
Ok thank you.
