### ISSUE TITLE
Copter necessarily will crash in case if device on the I2C bus hangs.

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/ardupilot#5376]
Because main loop will stop working by bus_i2c_reset() which will cause stop of motors  in Copter::failsafe_check(). It is clear that we here can do little, but at least if the parachute present code should to release it.

#### Version
git

#### Platform
[  ] All
[  ] AntennaTracker
[ x] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
Can you explain better what you are requesting? Is it that you want parachute released when the failsafe check is activated?

**Comment by night-ghost** [comment]
At least yes - because we CAN to have parachute system but not release it in case of problems. So 
1) throttle should be not in minimum but rather THR_MID or slightly less
2) just after disarm parachute should be released (may be with standard check about altitude and position that were remembered).  Errorneous parachute release is much less problem than the copter with all  equipment fallen from the sky.

**Comment by IamPete1** [comment]
`bus_i2c_reset` is gone, I'm not %100 sure what the relation to parachute is, I'm going to close, feel free to re-open if there is still issue.
