### ISSUE TITLE
new defined library cause param_loader(var_info) problem in copter.cpp constructor

### ISSUE THREAD

**Issue by CrazyPopLin** [ArduPilot/ardupilot#5381]
#### Issue details
I've already write a AP_LIDARScanner library and works fine. And I want to use another library named AP_VFH invoke data from AP_LIDARScanner. Both of files in the same folder. the code is below, it's simple and just setup. But when I compile it, I got error like:  
> ../../ArduCopter/Copter.cpp: In constructor 'Copter::Copter()':
> ../../ArduCopter/Copter.cpp:116:26: error: no matching function for call to 'AP_VFH::AP_VFH()'
>      param_loader(var_info)
>                           ^  

I just comfused because I did use param right now and no invoke to any library of that. And none of AP_LIDARScanner. It's seem a problem of constructor. When I uncomment the every thing of private member which is `AP_LIDARScanner` in AP_VFH, it compile fine. 
Any suggestions will be appreciated.
**header file**
```
#pragma once

#include <AP_Math/AP_Math.h>
#include <AP_HAL/AP_HAL.h>
#include <stdio.h>
#include "AP_LIDARScanner.h"

class AP_VFH {
private:
    const AP_LIDARScanner &_lidarscanner;
public:
    // Constructor
    AP_VFH(const AP_LIDARScanner &lidarscanner);
    void init();
    void update();
};
```
**cpp file**
```
#include "AP_VFH.h"
#include <AP_HAL/AP_HAL.h>

AP_VFH::AP_VFH(class AP_LIDARScanner &lidarscanner) :
    _lidarscanner(lidarscanner)
    {

    }
void AP_VFH::init()
{
}
void AP_VFH::update()
{
}
```
#### Version
master

#### Platform
[  ] Copter

#### Airframe type
quad

#### Hardware type
pixhawk

**Comment by magicrub** [comment]
You've posted a help question in the developer bug tracker area. Instead, please post a link to your branch on the forums discuss.ardupilot.org or in the chat gitter.im/Ardupilot/Ardupilot
