### ISSUE TITLE
Take into account the resistance of the battery in the Battery Failsafe check

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/ardupilot#5395]
AP_MotorsMulticopter.cpp calculates internal battery resistance, but only for own needs.

I think that it will be better to use this resistance to make voltage correction in AP_BattMonitor::exhausted() :

not
`if ((state[instance].voltage > 0) && (low_voltage > 0) && (state[instance].voltage < low_voltage))`

but instead
```
float volt = state[instance].voltage;
if(volt>0 && (low_voltage > 0)) {
 volt+= ([calculate voltage sag]);
 if ((volt < low_voltage) ...
```

This allows more precisely monitor low battery state, especially for batteries with high internal resistance. For now in [such](http://www.banggood.com/Hubsan-X4-Pro-H109S-RC-Quadcopter-Spare-Parts-11_1V-7000mAh-25C-Battery-p-1050441.html) battery it is about 30% of the energy when triggered auto landing at 3.5 volts per cell because it has ~1v voltage drop at hovering current.

#### Version
git

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by lthall** [comment]
I thought we have done this already when we put the impedance in there in the first place. I will check.
