### ISSUE TITLE
Incorrect Altitude being reported in ADS-B Mavlink Msg's

### ISSUE THREAD

**Issue by jwuavionix** [ArduPilot/ardupilot#5424]
In mavlink 2's ADS-B send_dynamic_out msg, the GNSS Altitude is being reported in decimeters instead of the correct mm's.  

Also, the pressure Altitude isn't implemented and is always being sent as invalid.

Arduplane V3.7.1 and Arducopter 3.4.3 on a pixhawk

**Comment by magicrub** [comment]
Hi Jeff, 

Here's the problem code: 
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_ADSB/AP_ADSB.cpp#L472

And 
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_ADSB/AP_ADSB.cpp#L519


The GPS alt unit is an easy fix, my bad! The pressure alt one is less obvious. I did not implement it because it wasn't clear what the data was. 

I can fix the GPS alt right away, would you be able to supply the description of the pressure sensor data?

**Comment by magicrub** [comment]
GPS alt is fixed via https://github.com/ArduPilot/ardupilot/commit/372837b959db8a2a59a2a92dfbef73d3afd6aedd

**Comment by jwuavionix** [comment]
The pressureAltitude reported should be calculated using a standard reference pressure of 1013.25mbar.  I've attached a little doc that describes the calculation which is already referenced to this reference.
[pressureAltitude.pdf](https://github.com/ArduPilot/ardupilot/files/664815/pressureAltitude.pdf)

**Comment by magicrub** [comment]
@jwuavionix I just noticed this is still lingering. Please assist on what the data is supposed to be, I want to make sure it's correct.

per the [mavlink packet](https://github.com/ArduPilot/mavlink/blob/e08439ef3d4a98dd9482d446ede78eaf1633f109/message_definitions/v1.0/uAvionix.xml) note: <field type="int32_t" name="baroAltMSL">Barometric pressure altitude relative to a standard atmosphere of 1013.2 mBar and NOT bar corrected altitude (m * 1E-3). (up +ve). If unknown set to INT32_MAX</field>
      
So is it feet above sea level?

**Comment by jwuavionix** [comment]
I left a comment on Dec 20th that attached an equation that is used to calculate the standard pressure altitude from the compensated(temp) baro pressure.  This isn't AGL or MSL and should be calculated using the equation attached and just the baro pressure.

**Comment by magicrub** [comment]
is it OK if it is temperature compensated?

**Comment by jwuavionix** [comment]
yes, the equation needs to use temperature compensated baro pressure as the input.

**Comment by magicrub** [comment]
great! Then I think this ends up being easier than we thought. I was thinking into it too much. Thanks @jwuavionix !

**Comment by magicrub** [comment]
See PR https://github.com/ArduPilot/ardupilot/pull/5761
