### ISSUE TITLE
SITL: unable to trigger EKF failsafe by disabling gps

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#5425]
#### Issue details
Using SITL and SIM_GPS_DISABLE, or SIM_GPS_GLITCH_X/Y or SIM_GPS_NUMSATS, the ekf failsafe cannot be trigger with default param

I haven't check with real drone but I assume it is only a SITL bug 

#### Version
https://github.com/ArduPilot/ardupilot/commit/372837b959db8a2a59a2a92dfbef73d3afd6aedd

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
Closing this one as Randy made a new one (#5428) with more information. Thanks for catching this!
