### ISSUE TITLE
Rover: make use of Inertial nav

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#5431]
#### Issue details
Currently, rover use AHRS , a switch to inertial nav could permit (if I understand correctly the difference) more precise behaviour in case of weak gps.
This will also unlock the works done on copter for avoidance

**Comment by OXINARF** [comment]
We have talked before about merging AP_InertialNav into AP_AHRS because the first is a very tiny layer now that has little purpose as a separate library. Given that, I think it would make more sense for someone to do that work and then Rover could take advantage of any new APIs in AP_AHRS.

**Comment by amilcarlucas** [comment]
There is a PR now to remove inertialNav from Copter. Should this be closed ?

**Comment by peterbarker** [comment]
@amilcarlucas I think so.  Let's see if anyone notices.

**Comment by gmorph** [comment]
I noticed - but I agree that it should be closed :-)
