### ISSUE TITLE
How to build ArduPlane-release-AVR or master-AVR?

### ISSUE THREAD

**Issue by zhxzsh** [ArduPilot/ardupilot#5449]
#### Issue details
Every teacher:I download ArduPlane-realease-AVR archive,and Don't know how to build the archive.I have a  APM2 board not PX4. who tell me?thanks!

ERROR message:

make -C ArduPlane apm2
make: Entering directory '/home/zhx/ardupilot-master-AVR/ArduPlane'
fatal: Not a git repository (or any of the parent directories): .git
../mk/find_arduino.mk:45: *** ERROR: Cannot find Arduino on this system, please specify on the commandline with ARDUINO=<path> or on the config.mk file。 STOP。
make: Leaving directory '/home/zhx/ardupilot-master-AVR/ArduPlane'
_What version was the issue encountered with_

#### Platform
[* ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
APM2
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This is a development support question and those should be posted at the forum (http://discuss.ardupilot.org) or asked about in Gitter (http://gitter.im/ArduPilot/ardupilot). Be aware that you are trying to build something quite old, so help is going to be probably scarce.
