### ISSUE TITLE
Copter: compiling with disabled proximity fails

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/ardupilot#5464]
#### Issue details
Trying to compile with

#define PROXIMITY_ENABLED     DISABLED

causes

Parameters.cpp: In constructor 'ParametersG2::ParametersG2()':
Parameters.cpp:1058:7: error: class 'ParametersG2' does not have any field named 'proximity'
     : proximity(copter.serial_manager),
       ^

#### Version
git

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
Fixed with #5488
