### ISSUE TITLE
Compiling with disabled rally points fails

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/ardupilot#5465]
#### Issue details
compiling with

#define AC_RALLY              DISABLED

results error

Log.cpp: In member function 'void Copter::Log_Write_Vehicle_Startup_Messages()':
Log.cpp:923:31: error: 'rally' was not declared in this scope
     DataFlash.Log_Write_Rally(rally);

#### Version
git

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
Fixed with #5486
