### ISSUE TITLE
Compiling with disabled camera fails

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/ardupilot#5466]
#### Issue details

compiling with
#define CAMERA                DISABLED

cause error

commands_logic.cpp:1104:73: error: no 'void Copter::do_digicam_configure(const AP_Mission::Mission_Command&)' member function declared in class 'Copter'
 void Copter::do_digicam_configure(const AP_Mission::Mission_Command& cmd)
                                                                         ^
commands_logic.cpp:1118:71: error: no 'void Copter::do_digicam_control(const AP_Mission::Mission_Command&)' member function declared in class 'Copter'
 void Copter::do_digicam_control(const AP_Mission::Mission_Command& cmd)
                                                                       ^
commands_logic.cpp: In member function 'void Copter::log_picture()':
commands_logic.cpp:1144:10: error: 'camera' was not declared in this scope
     if (!camera.using_feedback_pin()) {

#### Version
git

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
Fixed with #5485
