### ISSUE TITLE
Copter: separate RC_FEEL for YAW

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#5554]
In the release of Copter it would be useful to have separate RC_FEEL for YAW.
In a multicopter the rc roll/pitch feeling is quite similar since almost always the system is balanced, but the yaw might want to set differently.

**Comment by ChrisBird** [comment]
It appears that from what I can see the roll and pitch are smoothed out with RC_FEEL but the yaw is using a slew rate limiter for most modes.  So in essence the RC_FEEL has no bearing on the yaw axis for most flight modes.  It does appear to be used on the more autonomous modes such as auto, autotune, circle, flip, guided and rtl from what I can see.

Is the slew rate limiter not enough for this?  When flying in stabilize or poshold the RC_FEEL should have no bearing on the yaw output.

**Comment by lthall** [comment]
We now have a seperate rate, expo, and acceleration parameter for yaw. I believe this will address this issue.
