### ISSUE TITLE
EZ-UHF PPM Not Detected (Pixracer)

### ISSUE THREAD

**Issue by brizey02** [ArduPilot/ardupilot#5569]
#### Issue details
EZ-UHF is not detected on the RC In, Confirmed Taranis, EZ-UHF is working and setup. 

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quad

#### Hardware type
 pixracer,

**Comment by OXINARF** [comment]
Our dev team member @lvale tested this and it worked for him. According to the post in our forum it was found to be a bad clone.

**Comment by brizey02** [comment]
Thanks, Sorry I just found out it was a clone a few hours ago!

**Comment by lvale** [comment]
Responding to your question on RCG I'm using these http://www.immersionrc.com/fpv-products/ezuhf-4ch-receiver/
with these modules
http://www.immersionrc.com/fpv-products/ezuhf-jr-module/
These are configured to only 8 PPM channels

**Comment by brizey02** [comment]
Thanks, hope to get a real pixracer soon and get up and going on my ez-uhf!
