### ISSUE TITLE
Feature request: crash prevention when switching from Auto to Stabilize with zero throttle

### ISSUE THREAD

**Issue by rsilk1949** [ArduPilot/ardupilot#5580]
#### Issue details
After writing about my experience on rcgroups, it turns out that this situation has occured multiple times before and is a predictable crash event. Although this is pilot error, it is a crash situation which should be entirely preventable.
In my case I switched from Auto to Stabilize without realizing the throttle was at zero. The quad fell 20 metres causing extensive damage to itself but fortunately not to property or life.
Proposed solution: a new selectable failsafe parameter which specifies the maximum rate of descent which if exceeded would switch the current mode to AltHold since AltHold can control descent (and ascent) speeds via PILOT_VELZ_MAX.

#### Version
3.3.32

#### Platform
[  ] All
[  ] AntennaTracker
[X  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
X Quad

#### Hardware type
Pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
Sorry for your crash.  I have to admit that it's happened to me as well.
This is actually a duplicate issue.  The original from marco is here: https://github.com/ArduPilot/ardupilot/issues/1797
