### ISSUE TITLE
Non-Persistent control params since RC Channel Split

### ISSUE THREAD

**Issue by jberaud** [ArduPilot/ardupilot#5585]
#### Issue details
From commit https://github.com/ArduPilot/ardupilot/commit/e85df47b065d5a426a57404bf45c3ec438a2e825 ATC_RAT_* and some other params have become non persistent, i.e writing them has no effect after relaunching arducopter.
Then after commit https://github.com/ArduPilot/ardupilot/commit/d430cd62a6915cb5bc0e379f9ffe63106ac9bfba params are not loaded from default file when they are already present. The effect is that they are not even loaded from default param file but remain at their default value (hardcoded).

#### Version
master

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Bebop

#### Hardware type
Bebop

**Comment by gmorph** [comment]
Do we know if this is this only occurring on the Bebop?
Thanks, Grant.

**Comment by tridge** [comment]
i've reproduced the problem with changing ATC_RAT_RLL_P in SITL on master. I'm working on finding the issue and fixing
Thanks for letting us know!

**Comment by tridge** [comment]
a PR is pending to fix this in #5586

**Comment by tridge** [comment]
this is fixed in master now. Very good catch Julien!
