### ISSUE TITLE
make px4-v3-upload doesn't upload

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#5593]
#### Issue details
`make px4-v3-upload` should upload to the board on successful compilation.  It doesn't seem to attempt to upload.

#### Version
master

#### Platform
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by OXINARF** [comment]
#5917 was a duplicate of this and was fixed with #5919, closing.
