### ISSUE TITLE
ArduCopter: message "perf_begin() called twice on perf_counter_t(EK2_Test2)" shown in GCS while in flight

### ISSUE THREAD

**Issue by nacho-carnicero** [ArduPilot/ardupilot#5603]
Hi, 

this afternoon, while flying a copter I got some time after taking off the following message continuously:
```
perf_begin() called twice on perf_counter_t(EK2_Test2)
```

I'm using a Navio autopilot and running the version 3.4.3. It is the first time I got this message, and the only modification I had done to my hardware was to include a 3DR external magnetometer. I landed the drone as soon as I got the message, although it didn't seem to have stabilization problems (I was able to land in `LOITER`). 

Is this message important? Or is it just a kind of debugging message that I can ignore? I saw that the issue #5523 might be related to this topic, although I'm not sure we are in the same case.

Cheers

Nacho.

P.S: the message was only shown in MAVProxy, in QGroundControl there was no message shown.

**Comment by priseborough** [comment]
It is a debugging message.  It was fixed here: a63eac8073e7e89d8b0a8da8bce3822abd72be41
