### ISSUE TITLE
AC_PrecLand doesn't consume distance from landing_target messages

### ISSUE THREAD

**Issue by fnoop** [ArduPilot/ardupilot#5636]
#### Issue details
AP_PrecLand ignores distance parameter from landing_target mavlink messages in Companion backend and instead requires a working rangefinder.  PR to follow.

#### Version
3.5-dev

#### Platform
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Copter(all)

#### Hardware type
SITL/Pixracer, not relevant

#### Logs
n/a

**Comment by OXINARF** [comment]
This was fixed with PR #5637. Thanks @fnoop!
