### ISSUE TITLE
all: rc_override_active not properly managed

### ISSUE THREAD

**Issue by geeksville** [ArduPilot/ardupilot#565]
So current top of tree (@ab71f2e) shows an interesting problem.  I don't see any place in plane that is setting rc_override_active.  This is probably a mistake because it means that it won't do the failsafe action if it loses GCS heartbeat.

~/development/drone/ardupilot$ grep -R "rc_override_active =" \* 
APMrover2/APMrover2.pde:static bool rc_override_active = false;
APMrover2/system.pde:    rc_override_active = hal.rcin->set_overrides(rc_override, 8);
ArduCopter/GCS_Mavlink.pde:        ap.rc_override_active = true;
ArduCopter/GCS_Mavlink.pde~:        ap.rc_override_active = true;

**Comment by R-Lefebvre** [comment]
Believe RC_Override is now cancelled if GCS heartbeat is gone.

Also, discussed on 9/3/2015 dev call, that we are going to elminate RC Overrides and go with Control commands instead.

**Comment by rmackay9** [comment]
pushing to AC3.4.

**Comment by rmackay9** [comment]
pushing to AC3.5.

**Comment by OXINARF** [comment]
This is an old issue that isn't very clear on what was wrong. It has been postponed several times, but without any further comment that identifies any current code that is wrong.

For these reasons I'm closing this. If you feel there is still something wrong in RC overrides handling please open a new issue clearly identifying the problem.
