### ISSUE TITLE
Implement DShot

### ISSUE THREAD

**Issue by Deathstroke5467** [ArduPilot/ardupilot#5652]
While I realize skepticism that was previously present when you, as the devs, were asked to incorporate oneshot. I would venture to say DShot is about as big a breakthrough as BLHeli_S was itself and is an ESC protocol that would be very complimentary to ArduPilot. Why is it so much better you may ask.

It switches from a analog signal to a digital signal. This means:

Exact values
Less affected by electrical noise
Safer, with CRC
And many more benefits...

This means less motor noise and vibration in addition to more fluid movement and higher safety. Additionally, apperantly this requires a bit less power from the ESC as it does not have to work as hard to receive data (as far as I understand). 

Essentially it is doing what BLHeli_S did for firmware/hardware with ESC protocol. This in combination with BLHeli_S could give much more reliable, quiet, and fluid machines.

Beyond this the applications are many and I hope to see this feature implemented!

**Comment by gmorph** [comment]
There is already an open issue for this - #5300
