### ISSUE TITLE
Arduplane RPM logging only works for non-zero values

### ISSUE THREAD

**Issue by Georacer** [ArduPilot/ardupilot#5660]
#### Issue details
The RPM sensing (at least the RPM1 measurement) works ok when a non-zero RPM signal is fed onto Pixhawk.
However, when the propeller is stopped, instead of measuring 0 RPM, there simply is no measurement. 
This gets worse, as Mission Planner displays the same running value if no updated value is received, so if your engine dies mid-air, you will never get a 0 RPM reading on the GCS.

I have the following theory: If the RPM measurement function is interrupt-based, then if no interrupt is triggered (0 RPM), then no new RPM measurement shall be generated. But I'm just guessing.

A demo plot from a .tlog is shown below. Notice how there are samples (triangles) only for non-zero measurements. When the RPM is 0, there is simply no data point.
![rpm](https://cloud.githubusercontent.com/assets/3149996/22595935/265d983e-ea32-11e6-90c9-c19be28e451e.png)

I could not find an RPM reading in my .BIN log, perhaps I need to turn on some logging flag. I'm happy to reproduce the test if needed.

NOTE: I have implemented an inverting optocoupling circuit between the engine ignition and the Pixhawk, so the RPM signal normal level is LOW (<500mV).

#### Version
ArduPlane 3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
Pilatus Porter with DLA 32cc IC engine and an optocoupled RPM output.

#### Hardware type
Pixhawk 1

#### Logs
[rpm.zip](https://github.com/ArduPilot/ardupilot/files/750778/rpm.zip)

**Comment by magicrub** [comment]
I'll take a look

**Comment by Georacer** [comment]
Should I "bump" this while it's warm?

**Comment by magicrub** [comment]
I actually looked at this today and then got side tracked. I'll do it now. Sorry for the delay!

**Comment by Georacer** [comment]
Hey, no problem! It's not like I paid you for it or anything ;)

**Comment by magicrub** [comment]
confirmed, if you stop getting signals, or get them slower than 1 Hz, then it sets the "quality" to zero and the healthy goes false and it will no longer log it. So, values of zero can never be logged. I'll (or someone else?) have to figure out a way to fix it later, but for now a workaround is to set RPM_MIN_QUAL=0. That forces it to be healthy all the time.

**Comment by Georacer** [comment]
Is there an actual logged value (albeit unhealthy) if you stop getting pulses? What is its value?

**Comment by Georacer** [comment]
A friend helped me realize that RPM_MIN_QUAL is a parameter, not a program variable. I'll test it and answer the question myself.

**Comment by magicrub** [comment]
fixed via https://github.com/ArduPilot/ardupilot/commit/67486dc3f0f82fef8077494ebcf6dd4ffdedc4f1 by always logging when enabled instead of when healthy. After fixing it I went to check on copter to fix it there too and it was already doing the enabled check!

**Comment by Georacer** [comment]
Wouldn't it be better if the rpm measurements were also sent via mavlink, as well as logged? I.e. do the same with the GCS library.

**Comment by magicrub** [comment]
yes, we should do that too.. just like copter! Fixed via https://github.com/ArduPilot/ardupilot/commit/69a10042eb8234ed5b55075cf9e33e1ab85025c9

Thanks @Georacer !

**Comment by Georacer** [comment]
Thank **you**
