### ISSUE TITLE
barometer alt invalid on commit ac90527d

### ISSUE THREAD

**Issue by budebulai** [ArduPilot/ardupilot#5679]
#### Issue details
I downloaded ArduPilot with master version commit ac90527d
This version can't measure altitude from barometer.
ArduPlane has not this problem.
What's wrong with this version?

#### Version
commit ac90527d

#### Platform
[  ] Copter

#### Hardware type
pixhawk

**Comment by budebulai** [comment]
https://github.com/ArduPilot/ardupilot/issues/4225

**Comment by OXINARF** [comment]
That's a very old version from master. Please update to a current master, then if there's an issue report back. For now, I'm closing this.

**Comment by budebulai** [comment]
At first I didn't know this bug, so I develop on this version, using rtk and gps heading, adding some code to ekf2, and everything is ok when gps is valid. 
One day, quadcopter fell down when gps lost abruptly, and I realised baro altitude was not useful.
I guess there is something wrong with ekf2


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Francisco Ferreira <notifications@github.com>
时间：周二 2月7日 22:02
收件人：ArduPilot/ardupilot <ardupilot@noreply.github.com>
抄送：budebulai <zhaolun26@163.com>,Author <author@noreply.github.com>
主题：Re: [ArduPilot/ardupilot] barometer alt invalid on commit ac90527d (#5679)

**Comment by OXINARF** [comment]
If you don't want to worry about bugs like that you shouldn't develop on top of master but on top of a stable branch, like Copter-3.4.

Master changes fast and, although we try not to introduce bugs, it can happen. We appreciate bug reports about issues in master, but not from a version that is more than 6 months old. There was 3065 commits, 1687 changed files (with 80513 additions and 45751 deletions) after that...
