### ISSUE TITLE
Feature Request: option to disable usb failsafe bypass

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot#5692]
#### Issue details
i am conncting a raspery pi to my pixhawk and I was just going to connect it via USB, but as far as i know there is no way to stop it bypassing the pre arm checks and failsafes when usb is connected. so having this usb behavior optional would be useful for when the need for usb telemetry is required in flight.
#### Version
All

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[x] Plane
[x] Rover

#### Hardware type
pixhawk

**Comment by OXINARF** [comment]
Related to #5680
