### ISSUE TITLE
Copter: merge Solo and Maxell smart battery drivers

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#5693]
In the AP_BattMonitor directory we have two smart battery drivers, they are:

- Solo uses internal I2C bus, PEC (error correction) and reads manufacturer specific values for current, battery capacity and "is button pushed"
- Maxell uses the external I2C bus and simply reads voltage and current using standard registers

We should be able to merge these two if we can:

- tell them apart which should be possible using the manufacturer name register
- use the SpecificationInfo command and checking the revision number to see if PEC is used

**Comment by geofrancis** [comment]
specifically what maxell sensor will be supported? would it now be possible to do a diy smart battery and would this work with multiple batteries?

**Comment by rmackay9** [comment]
@geofrancis, I'll be writing up a wiki page once I've collected all the info on these Maxell batteries.  I suspect the new Maxell driver will actually work with many smart batteries.
We support two battery monitors but the problem is conflicting SMBus/I2C addresses.  So unless the battery itself can be configured to use a non-standard address only one could be attached.  The other alternative is to use the internal I2C bus but that's not exposed on most flight controllers.

**Comment by rmackay9** [comment]
After thinking about this more, at this stage I don't think we should try and merge the Maxell and Solo smart battery drivers.  They're simply too different.  When other smart batteries become common and we write drivers for them, we should try and extend either the Solo or the Maxell driver instead of adding yet another driver.
