### ISSUE TITLE
Params: Warn when writing to full eeprom

### ISSUE THREAD

**Issue by goochpw** [ArduPilot/ardupilot#571]
It seems that some parameters are not saved to the APM 2.6 module.   For example, mag_enabled will not save no matter how I change it... the various methods of modifying parameters.   I think this bug has been around for at least several versions.

**Comment by WickedShell** [comment]
Is this still a concern on Pixhawk hardware onwards? If not then we can go ahead and close it

**Comment by hiro2233** [comment]
@WickedShell @rmackay9 @squilter it's working on APM 2.6 with EEPROM very good using methods of modifying parameters indeed. please close it.

@goochpw Thanks you for your participation.
Good luck!

**Comment by rmackay9** [comment]
So I think we've recently had a case of this happening for someone on a Pixhawk when loading a lot of parameters from a file.  So it's likely we still have this issue and should provide a warning to the user.

**Comment by Naterater** [comment]
@rmackay9, i haven't ever heard of this recently. Is filling EEPROM still a potential issue?

**Comment by peterbarker** [comment]
I believe we will, in fact, get an error when parameter storage is full.

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_Param/AP_Param.cpp#L1123 - that message will be emitted if storage for parameters is full.

I artificially reduce the amount of storage space by modifying StorageManager and loaded a whole bunch of parameters:

![image](https://user-images.githubusercontent.com/7077857/84622744-163b7b80-af21-11ea-9204-58c8bdb830ef.png)

So if we do have a parameter-saving problem, it's not this.

The issue subject is that we don't have a warning.  We clearly do, so I'm closing this one as "fixed".
