### ISSUE TITLE
COPTER V3.4.4: Can not ARM in Loiter Mode, even when the green light is on

### ISSUE THREAD

**Issue by dongfang-a** [ArduPilot/ardupilot#5711]
#### Issue details
I cannot ARM my Quad Copter, even when the green light is ON, in Loiter Mode.

Mission planner told me error message: "GPS2 miss configure. " However, I don't have GPS2(I had another GPS before(dual GPS), but removed it a long time ago). I tried to set  GPS_TYPE2 to disable.  But after that, I cannot let the green light ON in Loiter Mode (it is always blue).

#### Version
COPTER V3.4.4

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quad Copter

#### Hardware type
Pixhawk
GPS Port: M8N GPS
Telem1 Port: 3dr Radio
Telem2 Port: Micro mini OSD

#### Logs
Please find my config in attached Logs

[51.zip](https://github.com/ArduPilot/ardupilot/files/769760/51.zip)

**Comment by rmackay9** [comment]
It should be displayed on the ground station "HUD" what the reason for the arming failure.  By the way, normally we don't do support in GitHub.  It's better to raise issues in the forums so I'll close this.
http://discuss.ardupilot.org/c/arducopter/copter34

**Comment by WickedShell** [comment]
No messages about arming failure in the log either.
