### ISSUE TITLE
Acknowledgement of mavlink msg 243

### ISSUE THREAD

**Issue by majorpr13** [ArduPilot/ardupilot#5718]
#### Issue details
Would be nice to have an acknowledgement or a publish of new vehicle home when calling github SET_HOME_POSITION ( #243 ).  Currently based on the code below pulled from master there is no acknowledgement. 
    case MAVLINK_MSG_ID_SET_HOME_POSITION:
    {
        mavlink_set_home_position_t packet;
        mavlink_msg_set_home_position_decode(msg, &packet);
        if((packet.latitude == 0) && (packet.longitude == 0) && (packet.altitude == 0)) {
            copter.set_home_to_current_location_and_lock();
        } else {
            // sanity check location
            if (!check_latlng(packet.latitude, packet.longitude)) {
                break;
            }
            Location new_home_loc;
            new_home_loc.lat = packet.latitude;
            new_home_loc.lng = packet.longitude;
            new_home_loc.alt = packet.altitude / 10;
            if (copter.far_from_EKF_origin(new_home_loc)) {
                break;
            }
            copter.set_home_and_lock(new_home_loc);
        }
        break;
}

#### Version
3.4

#### Platform
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
All

#### Hardware type
Pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/commands.cpp#L106 <- Do you mean this?
