### ISSUE TITLE
Switching between two GPS smoothly Now in AC3.4.4？

### ISSUE THREAD

**Issue by ranqingfa** [ArduPilot/ardupilot#5747]
as described in the title

 AC3.4.4

Pixhawk

[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover

X4

**Comment by OXINARF** [comment]
This list is for confirmed bugs and feature requests. For user support please post at the forum (http://discuss.ardupilot.org).

To answer your question, nothing changed with using two GPS in 3.4. If you searched the forum you would have found that answer.

**Comment by ranqingfa** [comment]
OK  thanks
@OXINAF
