### ISSUE TITLE
AP_GPS: Log delta time between updates

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#5749]
#### Issue details
When reviewing a log with high rate logging because of data loss its hard to distinguish if there was a loss of communication to the GPS or if it just lost some intermediate data. Tracking the delta between updates would allow us to state which happened with confidence

#### Version
Master

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

**Comment by rmackay9** [comment]
In addition, for Copter we should log an ERR message if it's slow.  Doing this makes it really obvious to someone analysing the logs at least if they're using Mission Planner which displays the errors very obviously.

**Comment by gmorph** [comment]
why wouldn't we log a message for all vehicle types and not just copter?

**Comment by WickedShell** [comment]
Done in #6556
