### ISSUE TITLE
External LED on FMU-I2C1 turn blue blink while no TF card, but internal LED red solid,  normal?

### ISSUE THREAD

**Issue by ranqingfa** [ArduPilot/ardupilot#5752]
External LED on FMU-I2C1 turn blue blink while no TF card, but internal LED on FMU-I2C2 red solid, other color is all the same, is this normal?

[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

fix wing

pixhawk

**Comment by ranqingfa** [comment]
plane firmware 3.71

**Comment by magicrub** [comment]
Yes, normal. Please insert an SD card.
