### ISSUE TITLE
My plane crashs with nothing warning and abnormal? 

### ISSUE THREAD

**Issue by ranqingfa** [ArduPilot/ardupilot#5754]
It flys all well, and suddenly the motor stops, and with firmware 3.7 it seems a lot new strange problem happens.

3.7.1

[  ] All
[  ] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover

fix wing

pixhawk

#### Logs
http://pan.baidu.com/s/1dFCBZQ5
TLOGS
http://pan.baidu.com/s/1pLpXbwn

**Comment by ranqingfa** [comment]
crash video
http://pan.baidu.com/s/1eSsXkdk

**Comment by ranqingfa** [comment]
same plane #5753

**Comment by magicrub** [comment]
Please post help questions in the forum at discuss.ardupilot.org
The GitHub issues are for feature requests and confirmed/defined bugs.

**Comment by ranqingfa** [comment]
This is not a bug?

**Comment by magicrub** [comment]
If it is, what is it? This is not the area for troubleshooting. The forums are.

**Comment by magicrub** [comment]
This log has 2 problems:
1) it doesn't have much in it so please enable your log bitmask so it will including helpful data
2) you're flying in MANUAL the whole time - the crash is pilot error.

**Comment by ranqingfa** [comment]
But in tlog, it is in AUTO mode and crash in auto mode

**Comment by ranqingfa** [comment]
Actually, its AUTO - FBWA - RTL - AUTO (switch waypoint) - crash, and Im confused too why only manual mode in log
