### ISSUE TITLE
Rover: Disarm by radio is broken

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#5764]
#### Issue details
unable to disarm with radio, reproducible in sitl . Go Manual, arm throttle, set rc 3 1500, rc 1 1000

#### Version
master https://github.com/ArduPilot/ardupilot/commit/67486dc3f0f82fef8077494ebcf6dd4ffdedc4f1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ X] Rover

**Comment by ncx94** [comment]
If i remember well, that was disactivated on purpose as for a skid steering rover, a 0 throttle full Turn is a perfectly correct maneuver...

Because of that, you can't really use it to disarm. Maybe set a parameter that enables it on non-skid steering rover?

**Comment by khancyr** [comment]
Closed as the bug has been solved
