### ISSUE TITLE
Plane: Solo Cube lights don't go out

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#5772]
#### Issue details

http://discuss.ardupilot.org/t/how-do-i-install-apmrover-2-in-pixhawk-2/14394/6

A user (and I've replicated) pulled a Pixhawk Solo Cube out of a Solo and tried to install Rover on it.  The lights don't work once ArduPilot has finished booting.

Addendum:  Apparently this is the correct behaviour as the lights interfere with the compass however using Plane firmware the lights remain on and they probably shouldn't.

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover

#### Hardware type
Solo Pixhawk Cube

**Comment by peterbarker** [comment]
On Wed, 22 Feb 2017, Grant Morphett wrote:

> A user (and I've replicated) pulled a Pixhawk Solo Cube out of a Solo and
> tried to install Rover on it. The lights don't work once ArduPilot has
> finished booting.


That's be design.  The interfere with the compasses.

**Comment by gmorph** [comment]
Really - they stay'ed on in Plane.  I didn't test Copter.

**Comment by gmorph** [comment]
Should I raise it as a plane issue?

**Comment by gmorph** [comment]
I've raised it as a plane issue.

**Comment by proficnc** [comment]
This is 100% by design.  This issue should be closed

**Comment by gmorph** [comment]
Close the issue.  Still not sure why its ok for the lights to go out on Rover but stay on in Plane however clever people then I say its ok so closing.

**Comment by peterbarker** [comment]
On Fri, 24 Feb 2017, Grant Morphett wrote:

> Close the issue. Still not sure why its ok for the lights to go out on Rover
> but stay on in Plane however clever people then I say its ok so closing.

The lights go out on Plane when I load that firmware onto a PixHawk2 here.
