### ISSUE TITLE
ll40ls: inmediate read failed: try again.

### ISSUE THREAD

**Issue by marv3** [ArduPilot/ardupilot#5785]
Hey, I'm using a Lidar Lite v3 but when I try to test this(ll40ls test i2c), nsh displays:

ll40ls: inmediate read failed: try again.

I tried a lot of times and it doesn't work.
Can you help me? Please.

(I' using a hexacopter with a pixhawk)
THANKS.

#UPDATE 1: When I try using "ll40ls info i2c" there is a distance parameter which displays the measured distance (I tried in two different positions). But, this "distance" doesn't change if I change the position of the lidar (to measure other distance), when I try with "ll40ls info i2c" the display for "distance" is the same.
HELP! and thanks again.
![1 1](https://cloud.githubusercontent.com/assets/23424511/23413447/8b90b998-fd8d-11e6-8d8c-c5896eac1f31.png)
![1 2](https://cloud.githubusercontent.com/assets/23424511/23413478/9ec5c170-fd8d-11e6-94a7-1530102a1a48.png)

**Comment by OXINARF** [comment]
Several points:

- user issues should be posted at the forum (http://discuss.ardupilot.org) and not here
- we don't use that PX4 driver anymore, we use our own drivers now
- Lidar Lite v3 isn't supported yet

**Comment by marv3** [comment]
Thanks for your answer and sorry for posting here (first time mistake).
Can you answer just a last question, please? I really need to know how to work.
I tried with the beta version released 7 days ago and it doesn't work (thanks for the third point).
Is there a guide to develop drivers or something like that? I really need to work with the Lidar Lite v3.

Thank you and sorry again.

**Comment by OXINARF** [comment]
If you want to compile it yourself, supporting **just** v3 is fairly easy. You need to remove the [hardware/software version check](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.cpp#L153-L161) and then make [`v2_hardware == true`](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.cpp#L164).
