### ISSUE TITLE
Plane: battery failsafe alarm when plug the main power

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#5787]
I noticed that was removed this feature, which alerts with beeps and warning the planner when connecting a main power battery with lower voltage than the failsafe setting.
If possible it would be better to restore this thing, in the Copter code is enabled by default.
The buzzer warning is amazing, don't know why this feature was removed.

**Comment by magicrub** [comment]
Hi @robustini , does pending PR (https://github.com/ArduPilot/ardupilot/pull/5680) fix this? That PR is Plane only but the same problem may apply to copters too.

**Comment by robustini** [comment]
No, yestarday i crash a VTOL during takeoff due battery failsafe.
I know there's new parameter that prevents to arm the system when the battery has too low, but it would be preferable to have this indication before arming, the buzzer helps a lot.

**Comment by robustini** [comment]
With the copter (battery failsafe set to "21V")...


![Uploading copter_battery_failsafe.jpg…]()

**Comment by robustini** [comment]
This issue is solved with another parameter, added in the latest release of the plane.
