### ISSUE TITLE
BARO_generic Failed to test

### ISSUE THREAD

**Issue by Ahrovan** [ArduPilot/ardupilot#5801]
'build' finished successfully and 
Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.

but after run mavproxy.py --setup --master /dev/serial/by-id/usb-3D_Robotics_PX4_FMU_v2.x_0-if00
can not see any serial output..
INS_generic has serial output successful!

**Comment by OXINARF** [comment]
@Ahrovan Not sure if it was clear, but this was fixed by #5826, thanks for the report!
