### ISSUE TITLE
Plane: reconsider loiter radius that is altitude dependent

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#5809]
Plane: reconsider loiter radius that is altitude dependent

**Comment by geofrancis** [comment]
this could be done by having a high and low loiter altitude/radius.

if low was set to 20m/20m and high to 100m/100m

then it would loiter at 20m radius until its over 20m in altitude then make the circle bigger as it gains altitude until it hits 100m altitude with 100m radius then it will keep the 100m radius until it decends below 100m.

**Comment by magicrub** [comment]
The problem is you say to loiter at 50 and you end up loitering at 65 or whatever. It rarely does what you command it to.

**Comment by WickedShell** [comment]
Was addressed in https://github.com/ArduPilot/ardupilot/pull/5909
