### ISSUE TITLE
APMRover2: motors ouput can be more than 20ms

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#5817]
#### Issue details
Ouput can be more that 2000 on skid steer config...
To reproduce on sitl: arm throttle, rc 1 2000, rc 3 2000
![pb_rover](https://cloud.githubusercontent.com/assets/705341/23578869/8a80e4a0-00e0-11e7-99cb-8ea5db181cfb.png)

So it doesn't respect servo_out min and max value ...
#### Version
master : https://github.com/ArduPilot/ardupilot/commit/2631bdbe64e32a9607bda642125a87f5979aafc6

Not present on release APMrover 3.1.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ X] Rover

**Comment by OXINARF** [comment]
@khancyr Can you improve the title of this issue? It's not descriptive at all.

**Comment by khancyr** [comment]
@OXINARF yep sorry, forget to fill it correctly

**Comment by khancyr** [comment]
solve with SRV_Channel: limit pwm_from_angle return to +/-high_out #6190
