### ISSUE TITLE
motor_test app not found

### ISSUE THREAD

**Issue by limhyon** [ArduPilot/ardupilot#5825]
#### Issue details
I've updated with most recent commit of Ardupilot, it does not show "motor_test" app.
However, most stable version (83d39) shows motor_test app correctly.

#### Version
c1fa54 (does not show motor_test app)
83d39 (shows motor_test app correctly)

#### Platform
[  ] All
[  ] AntennaTracker
[V] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quad

#### Hardware type
PX4 FMU V4

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by lvale** [comment]
I believe you must be referring to a problem on the GCS (Mission Planner?). Please check the support forae on discuss.ardupilot.org and if required check the appropriate GCS repository for pending issues.
