### ISSUE TITLE
RangeFinders using I2C (Maxbotix I2C, LightwareI2C) should be supported on 2nd I2C bus for Pixhawk2

### ISSUE THREAD

**Issue by cjneal** [ArduPilot/ardupilot#5831]
#### Issue details
Have multiple airframes using Maxbotix I2C EZ4 sonars for auto landing.  Just converted to PH2.1 and am no longer getting any reading from the rangefinder.  Other I2C items (airspeed) work just fine, so I assume this is a software problem.  Have tried multiple planes and multiple sonar units.

#### Version
PH 2.1
AP 3.7.1
MP 1.3.44

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Multiple...pusher flying wing (X8), custom puller aircraft, and others

#### Hardware type
PH2.1

**Comment by proficnc** [comment]
its possible that this driver is only checking the first I2C bus. 

that being said, I would not recommend a sonar on any airframe if you can avoid it.

**Comment by magicrub** [comment]
@proficnc Looks like you're right. That driver seems to be hardcoded to a single i2c bus:

See example of a different driver correctly checking both buses - try 0 then try 1:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/RangeFinder.cpp#L615

Maxbotix driver checking single bus - assume 1:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/RangeFinder.cpp#L619
which calls
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarI2CXL.cpp#L38

**Comment by cjneal** [comment]
@proficnc Why do you suggest avoiding sonar on planes?  I do understand why the lidar options are better in general, but for small planes where I want to avoid the weight and size I've had great luck as long as the landing params are tuned well.  Is there some reliability or performance reason?

**Comment by proficnc** [comment]
If it's working for you, then great! But I find we have less complaints from lidar users...

**Comment by magicrub** [comment]
looks like PR https://github.com/ArduPilot/ardupilot/pull/6260 may fix this. @jschall please confirm

**Comment by bhollehday** [comment]
That would be awesome Im trying to get my maxbotic sonar's working again. I cant find a simple way of getting any obstacle avoidance read through AP.

**Comment by cjneal** [comment]
@magicrub 
@jschall 

Is there a status update on PR #6260 ?  I'm looking for a version of Plane 3.7.1 with I2C working for either Maxbotix or (maybe preferably) Lightware SF11.  Is there someone who could build/compile a one-off variant of 3.7.1 with @jschall 's changes?

**Comment by proficnc** [comment]
Any updates?

**Comment by Tom-Shen** [comment]
Any conclusion? I have the same issue when I connected sonar to Pixhawk2
