### ISSUE TITLE
BAD Accels Health & Accel Calibration FAILED after ENABLE Optical Flow

### ISSUE THREAD

**Issue by Ahrovan** [ArduPilot/ardupilot#5854]
After Enable optical flow, See Bad accels Health and can not calibrate that with calibrate process, i use Arducopter 3.5 with pixhawk hardware.

**Comment by magicrub** [comment]
Do you have a log?

**Comment by OXINARF** [comment]
This is a support question and those should be posted in the forum (http://discuss.ardupilot.org).

**Comment by Ahrovan** [comment]
[2017-03-11 16-19-31.tlog.txt](https://github.com/ArduPilot/ardupilot/files/836341/2017-03-11.16-19-31.tlog.txt)
Remove ".txt" from file name to use .tlog for MP
