### ISSUE TITLE
auto thruttle problem

### ISSUE THREAD

**Issue by moreba1** [ArduPilot/ardupilot#5855]
#### Issue details
i have a problem with pixhawk . the throttle cut in auto and and rtl mode  . auto thruttle dont work in failsafe and ..
#### Version
_What version was the issue encountered with_

#### Platform

[  ] Plane

#### Airframe type
flying wing

#### Hardware type
pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by magicrub** [comment]
Please provide more details and, hopefully, a log.

**Comment by OXINARF** [comment]
This is a support question and those should be posted in the forum (http://discuss.ardupilot.org).
