### ISSUE TITLE
FrSky telemetry: MAVLink messages aren't null terminated when there are 50 characters

### ISSUE THREAD

**Issue by OXINARF** [ArduPilot/ardupilot#5862]
Catched by Coverity Scan (CID 137344).

In https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp#L442 it says _we've reached the end of the message (string terminated by '\0')_ but that's not true because the messages are saved as MAVLink statustext messages.

MAVLink spec says that there's maximum of 50 characters and when that limit is reached no null terminator character is needed - the maximum is 50, so anyone using MAVLink should know that either a null terminator or the character 50 ends the string.

**Comment by floaledm** [comment]
Thanks Francisco! I don't have merge privileges, so someone else needs to do it...
