### ISSUE TITLE
Ardupilot does not respond to TIMESYNC mavlink messages

### ISSUE THREAD

**Issue by fnoop** [ArduPilot/ardupilot#5884]
#### Issue details
Ardupilot should respond to TIMESYNC messages by signing the message with the current timestamp and sending it back.  This is vital for synchronising timestamps between the flight controller and other components.

#### Version
master (3.5)

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
n/a

#### Hardware type
SITL

#### Logs
n/a

**Comment by rmackay9** [comment]
Sounds good.. and doesn't sound too hard really.

**Comment by ptsneves** [comment]
What does it mean to sign the message? To answer?

**Comment by khancyr** [comment]
@fnoop can you let a message on why you are closing it ?

**Comment by fnoop** [comment]
Oops sorry, 'cos it was implemented :)
https://github.com/ArduPilot/ardupilot/pull/5944
