### ISSUE TITLE
Unexpected Error while compass calibration.

### ISSUE THREAD

**Issue by mrprole** [ArduPilot/ardupilot#5905]
#### Issue details
Unexpected Error while compass calibration.

#### Version
APM:Copter V3.5.0-rc2 Quad

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
X - Type

#### Hardware type
ArduPilotMega

#### Logs
![calibration_error](https://cloud.githubusercontent.com/assets/25525606/24084078/23a9d206-0cec-11e7-97e9-1569132c9fa8.jpg)

**Comment by WickedShell** [comment]
This is a Mission Planner problem not an ArduPilot problem, and a support issue first. Support issues should be handled here first: http://discuss.ardupilot.org (I think this was already addressed, but someone there could assist you further with that)
