### ISSUE TITLE
CAN bus interfaces>1 and UAVCAN protocol redundancy

### ISSUE THREAD

**Issue by EShamaev** [ArduPilot/ardupilot#5907]
In Pixhawk and several other boards there are several CAN bus interfaces that can bu used. UAVCAN library supports redundancy for them.
However both autopilot and a remote device have only one MCU that has these two interfaces.
MTBF of cabling and connectors (if made right) is several orders higher than the MTBF of autopilot and remote device altogether.
This renders the need for redundant cabling unnecessary.

Proposed is following:
1. Provide an option to use single UAVCAN instance on both interfaces for cabling redundancy as it is implemented in UAVCAN library.
2. Provide an option to have 2 (or more) UAVCAN instances on 2 (or more) separate CAN bus interfaces and provide user a possibility to connect different devices to different buses. For example bus A used for high speed servo/ESC communication and bus B used for GNSS, baro, mag, battery monitoring, etc.

**Comment by tridge** [comment]
yep, sounds like a very good thing to support
