### ISSUE TITLE
AP_Camera doesn't have a disable option and can inadvertently turn a relay on

### ISSUE THREAD

**Issue by OXINARF** [ArduPilot/ardupilot#5926]
While talking in Gitter about how a GCS can "detect" the presence of a camera (interesting bits start at https://gitter.im/ArduPilot/ardupilot?at=58d2df22a84f611959d243bf), I found out that AP_Camera doesn't have a disabled option - also there isn't any to change the trigger pin if using a relay type, it always uses the first relay.

Although AP_Camera type defaults to Servo type, if someone changes it to Relay type (for example, to experiment - and why change back to Servo?), and because RELAY_PIN isn't disabled by default for some boards, it looks like it is possible the camera will be triggering and turning the relay on - that relay may be configured for something else though? Like a parachute (which also defaults to first relay)?

**Comment by rmackay9** [comment]
This is resolved now that the linked PR has been merged, thanks!
