### ISSUE TITLE
 XY Position moved for no_gps

### ISSUE THREAD

**Issue by Ahrovan** [ArduPilot/ardupilot#5932]
When we set ekf_gps_type to no_gps, use Optical flow, the best situation for see position moved from take-off (zero pos) to target position is simple XY coordinates ..

**Comment by rmackay9** [comment]
@Ahrovan, could you clarify a bit more?

I guess you're using the Copter firmware... which flight mode are you using?  I guess you're using Guided mode and perhaps dronekit to send movement comments?  .. or are you clicking on a map?  what ground station are you using?

**Comment by Ahrovan** [comment]
Yes. Arducopter 3.5 rc2. Loiter flight mode with no_gps (optical flow)
I am useing mission planner .. but for optical flow (indoor) movment clicking on the map and NED coordinates is meaningless (?) But i think change NED to xy coordinates is usefull

**Comment by Ahrovan** [comment]
@rmackay9 
I tested PE,PN,PD values, but with optic flow, error is Greater that 0.5m
![blob 1](https://cloud.githubusercontent.com/assets/5772832/24330186/4f55862e-122e-11e7-8813-1f835de68e1b.png)
![blob](https://cloud.githubusercontent.com/assets/5772832/24330185/4ef63232-122e-11e7-8fd4-25215af19a92.png)

**Comment by rmackay9** [comment]
So what you're trying to do is use optical flow in Loiter mode using AC3.5.

You've gone through the calibration described on this page?
http://ardupilot.org/copter/docs/common-px4flow-overview.html

Optical flow reports the vehicle's velocity and then we integrate that to get a position so the position drifts.  The amount it drifts can depend upon the lighting and the surface it's looking at.  Also the range finder needs to be accurate as well.

The graph you've posted doesn't look too bad.  It looks like at the end of the test it's within about 1m of it's original position.  That's not bad I think.

Reports on beta software should be posted to our discourse server here: http://discuss.ardupilot.org/c/arducopter/copter-3-5... so I will close this issue but feel free to raise a new discussion over there.
