### ISSUE TITLE
Arduplane 3.7.1 is not accepting serial and i2c output of light ware range finder

### ISSUE THREAD

**Issue by kalai1219** [ArduPilot/ardupilot#5937]
I have tried to connect SF10/B and SF1/C range finder sensor pixhawk 1 using serial 2,4 port as well as I2C port.

I have enabled RNG LANDING also to 1.

But it not showing lidar output also it shows bad lidar health.

What could be the problem 

ARDUPLANE 3.7.1

[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

Fixed wing airplane

Pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This is a support question and those should be posted in the forum (http://discuss.ardupilot.org). Post a log with it there.
