### ISSUE TITLE
Need help with Pixhawk Serial 4/5

### ISSUE THREAD

**Issue by filthros** [ArduPilot/ardupilot#5948]
Hi,

I need to connect the storm32 controller to the serial port 5 of the pixhawk in order to control the gimbal using the RC.

I have tried with two different pixhawk and I am not able to carry out this task.

Configuring serial ports 4 and 5 with the storm32 gimbal serial protocol and with baudrate 115, port 4 works correctly and I am able to move the gimbal but not on port 5.

I am wondering if the serial port 5 of the pixhawk is ready for this, since it does not work for me in any of my two pixhawks.

I am using the latest version of arducopter 3.4.6 Hexa and mission planner 1.3.45

My real problem is that, due to the great integration of systems in the pixhawk, I do not have enough serial ports to connect some of them, such as gimbal, is there any way to solve this problem?

Thank you very much.

**Comment by OXINARF** [comment]
This is a support question and those should be posted in the forum (http://discuss.ardupilot.org)

Port 5 is the debug console port, it's not available to be used by anything else.
