### ISSUE TITLE
Copter: slight change to rotor-spin on arming

### ISSUE THREAD

**Issue by JoshWelsh** [ArduPilot/ardupilot#595]
Can the arming procedure that spins the props on arming has a variable set by the user that maxes out the spin-up time?  Perhaps I just wanted a .5-second pulse rather than having them running at 10% for 10 seconds while I get my goggles on, etc.  Just a thought?  Also, if a mechanism isn't already built in, I thought this would be a good way to prevent props continuing to spin in the event of a hard and/or inverted crash..

much love guys!

Josh

**Comment by OXINARF** [comment]
Copter has now:

- auto-disarming enabled by default and configurable with a parameter
- crash checks
- landing checks
- parameter to configure the spin when armed

I think this pretty much covers this old issue. If you feel there are still something missing in current code, please comment.
