### ISSUE TITLE
ATC_SLEW_YAW issue

### ISSUE THREAD

**Issue by 9653chris** [ArduPilot/ardupilot#5963]
#### Issue details
_Please describe the problem, or desired feature_

Yaw speed problem in automatic flight with UGCS
I set the value of ATC_SLEW_YAW to a low value.
In the loiter, slowly changing the yaw speed
In auto mode, however, the heading still changes sharply.
I do not know why it works.
Are there any other related parameters?

#### Version
_What version was the issue encountered with_
3.4.6ver.
#### Platform
[  ] All
[  ] AntennaTracker
[ v ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
x8 and x4
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
pixhawk
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This issues list is just for confirmed bugs or feature requests. This is a support question and those need to be posted in the forum (http://discuss.ardupilot.org).
