### ISSUE TITLE
Fix Oreo LED and beepers for Solo running master

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/ardupilot#5986]
#### Issue details
Follow up the 4/3/2017 dev call per @tridge .  The Oreo LED needs some updates in order for them to work properly with a 3DR Solo running Arducopter master.

#### Version
3.5+

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
3DR SOlo

#### Hardware type
Pixhawk 2 & Pixhawk 2.1

#### Logs
N/A

**Comment by OXINARF** [comment]
@Pedals2Paddles This is done right?

**Comment by Pedals2Paddles** [comment]
Yep! Happily closed!
