### ISSUE TITLE
PWM output for industrial drives

### ISSUE THREAD

**Issue by proficnc** [ArduPilot/ardupilot#5990]
#### Issue details
_Please describe the problem, or desired feature_
Adding the capability to drive industrial servos directly from Ardupilot.

the desire here is to have the option of a signal that has a duty cycle from 10% to 90% with no gap between.

![pwm](https://cloud.githubusercontent.com/assets/4628419/24641091/d67a2a48-193f-11e7-8558-0c3720170cb6.jpg)

so for a 400Hz signal, this would be 
full reverse...  400us on, 3600us off
stopped        2000us on, 2000us off
full forward   3600us on, 400us off

at 20Hz it would be
full reverse... 2ms on 18ms off
stopped...     10ms on 10ms off
Full forward.. 18ms on 2ms off

this change allows us to control all manner of off the shelf motor drive systems.

#### Version
_What version was the issue encountered with_
Master

#### Platform
[  ] All
[X] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
The Cube, or any other Pixhawk compatible system
#### Logs
_Please provide a link to any relevant logs that show the issue_

[Clearpath-Driver.pdf](https://github.com/ArduPilot/ardupilot/files/892029/Clearpath-Driver.pdf)

@NickNunno

**Comment by proficnc** [comment]
possibly related to

https://github.com/ArduPilot/ardupilot/issues/5341

**Comment by NickNunno** [comment]
The graph is a bit misleading. This particular drive will read from .1 to 99%. Absolute 1% and 100% are read as a dead band but any duty cycle between is an acceptable control range.

**Comment by EShamaev** [comment]
From the same PDF.
![image](https://cloud.githubusercontent.com/assets/7996972/24722506/9a0e491e-1a4c-11e7-9566-6204380602cb.png)

Maybe support that one initially?

**Comment by NickNunno** [comment]
Frequency input mode or unipolar pwm input mode require a dedicated pin as a directional trigger. Input High/Low = Direction A/B

**Comment by EShamaev** [comment]
As far as I understand in AntennaTracker there are plenty outputs that are free?

**Comment by NickNunno** [comment]
@proficnc is the lead on this project. 

I've yet to test frequency input mode on the drive but if this mode, with directional pin is easier to facilitate and maintain within rover code and has a higher degree of accuracy, I don't see why that wouldn't be a better option.

**Comment by khancyr** [comment]
Done ! starting from https://github.com/ArduPilot/ardupilot/commit/d525c0bffb5a0d561dacef5eec154aed9d6ada26
