### ISSUE TITLE
bbbmini

### ISSUE THREAD

**Issue by awright424** [ArduPilot/ardupilot#6006]
#### Issue details
I need to know where and what files the pru for the bbbmini should be compiled and installed to for those not using the precompiled bbbmini image for the beaglebone black.

#### Version
ardcuopter 3.4

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover

#### Airframe type
quad

#### Hardware type
beaglebone black bbbmini cape

#### Logs
no relevant logs, arducopter fails to start due to missing pru firmware.

**Comment by OXINARF** [comment]
This list is for confirmed bugs or feature requests. User issues need to be posted in the forum (http://discuss.ardupilot.org). Also, you have a problem with the BBBmini, not exactly ArduPilot.

I'll leave you with two links:

- https://github.com/ArduPilot/ardupilot/tree/master/Tools/Linux_HAL_Essentials/devicetree/bbbmini
- https://github.com/mirkix/BBBMINI
