### ISSUE TITLE
EKF3 get the IMU data , the data is delayed ,the delay time is 260ms? why? 

### ISSUE THREAD

**Issue by AiPanPan** [ArduPilot/ardupilot#6010]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This list is for confirmed bugs or feature requests. User issues should be posted in the forum (http://discuss.ardupilot.org). Also you haven't described any problem and the title is incomprehensible to me.
