### ISSUE TITLE
HexaCopter armed and telemetry connected but motors are not spining at all and are completely unresponsive to Turnigy 9x controller.

### ISSUE THREAD

**Issue by Inventor10** [ArduPilot/ardupilot#6023]
#### Issue details
_Please describe the problem, or desired feature_
Motors are not sniping at all and are completely unresponsive to Turnigy 9x controller when hexacopter is armed. ESC calibrations seem to not be working as well. I tried radio and accelerometer calibrations which had no affect at all. I'm pretty desperate now any help is appreciated.
#### Version
_What version was the issue encountered with_
Mission Planer 1.3.45
#### Platform
Copter

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
hex F550
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
APM flight control
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
@Inventor10,

Sorry to be annoying but support questions should first go into the support forums.
http://discuss.ardupilot.org/c/arducopter/copter34

We use this issue list for confirmed bugs and enhancement requests.
Sorry to be strict but if we don't do this our to-do list turns into a support forum.

Thanks for using ArduPilot!
