### ISSUE TITLE
no rangfinder log shown in dataflash of log

### ISSUE THREAD

**Issue by CrazyPopLin** [ArduPilot/ardupilot#6038]
#### Issue details
When I review the data of rangefinder in dataflash. I didn't find the **rng** row. The version is 3.4.6 from mission planner. The rangefinder I used is Maxbotic sonar. When I connect it to Pixhawk and chosen **px4-I2C** or **apm2-MaxboticI2C**. Both of connection I can get data in mission planner. The wired thing is my friend can get rangefinder data in dataflash. Also I tried his sonar, same problem.   
We check the parameters, also same. Is that any parameters I need to check to shown data in dataflash? any suggestions. thx. 

#### Version
3.4.6

#### Platform

[  ] Copter

#### Airframe type
quad

#### Hardware type
pixhawk

#### Logs

####Screen shots of mission planner of RNGFND Param
<img width="987" alt="screen shot 2017-04-12 at 11 50 21 am" src="https://cloud.githubusercontent.com/assets/11235093/24940548/5c3c325c-1f76-11e7-91f0-d02d07198573.png">

**Comment by CrazyPopLin** [comment]
I found 3.4 version don't have follow : 

>     if (rangefinder.num_sensors() > 0 &&
>         should_log(MASK_LOG_CTUN)) {
>         DataFlash.Log_Write_RFND(rangefinder);
>     }  

But master version has, so that should be fix my issue.

**Comment by rmackay9** [comment]
Yes.  Thanks for figuring this out.  Even in AC3.4.6 it's possible to see the range finder altitude though by looking at the CTUN.SAlt field.  That may be tilt corrected though while the RNGD dataflash message will not be.
