### ISSUE TITLE
AP_Compass_HMC5843

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/ardupilot#6039]
#### Issue details
in AP_Compass_HMC5843.cpp, see below

#### Version
master

#### Platform
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
all

#### Hardware type
hmc58x3 compass

#### Logs
-

In AP_Compass_HMC5843.cpp:

Bug?: Here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Compass/AP_Compass_HMC5843.cpp#L448 numAttempts should be changed to num_samples, IMHO. Otherwise, if the compass isn't responding >2 times at the beginning wrong values would be digested.

Suggestion: Here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Compass/AP_Compass_HMC5843.cpp#L335-L363. It is documented in the datasheet that the sequence of data is x, z, y axis, and not x,y,z. To me it thus looks more natural to change the val structure to x,z,y, and to not correct for that irregular sequence later in lines 349,350.

**Comment by olliw42** [comment]
added suggestions: Here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Compass/AP_Compass_HMC5843.cpp#L448 one may want to change, for stylistic reasons:
* numAttempts to num_attempts
* int numAttempts = 0, good_count = 0;  to uint8_t num_attempts = 0, good_count = 0;

**Comment by tridge** [comment]
> Bug?: Here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Compass/AP_Compass_HMC5843.cpp#L448 numAttempts should be changed to num_samples, IMHO. Otherwise, if the compass isn't responding >2 times at the beginning wrong values would be digested.

I agree. Would you like to do a PR?

> Suggestion: Here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Compass/AP_Compass_HMC5843.cpp#L335-L363. It is documented in the datasheet that the sequence of data is x, z, y axis, and not x,y,z. To me it thus looks more natural to change the val structure to x,z,y, and to not correct for that irregular sequence later in lines 349,350.

yep, agreed as well

**Comment by olliw42** [comment]
I can't, sorry, I'm a git illiterate

**Comment by amilcarlucas** [comment]
@tridge didn't you fix this already ? Can this be closed ?

**Comment by OXINARF** [comment]
No, this isn't fixed.

**Comment by olliw42** [comment]
closing it since really outdated :)
