### ISSUE TITLE
QuadPlane Pitch and Altitude Sustained Oscillation in QRTL while approaching landin point

### ISSUE THREAD

**Issue by ferdicakmak** [ArduPilot/ardupilot#6046]
Hello,

When flying Quadplane in AUTO mode, aircraft swithces to QRTL after flying in RTL as fixed wing, which is fine until now. 

In QRTL mode, aircraft tries to reach Home point by pitching down (negative) the aircraft for maintaining Q_WP_SPEED = 5m/s, where the wind makes the aircraft loose altitude abruptly (causing QTUN.THR to 1) and cause pitch up and gain altitude (causing QTUN.THR to 0). Thus, while approaching to HOME point in QRTL, the aircraft moves like a dolphin. This oscillation stops when HOME point is reached and aircaft lands vertically.

![image](https://cloud.githubusercontent.com/assets/8240355/25010796/d9095604-2073-11e7-9394-306932b0baf9.png)

I had about 10 flights like this and observed same pattern in 9 of them. Same pattern occurs even when Q_RTL_ALT = ALT_HOLD_RTL. I even tried Q_VFWD_GAIN : 0,05 with FW motor active but couldnt see any improvement. 

QTUN.ThrOut, QTUN.DCRt and QTUNCrt data from logs show that THR switches between maximum and minimum while trying to reach Home point with Q_WP_SPEED. 

![image](https://cloud.githubusercontent.com/assets/8240355/25010807/e2dfec7e-2073-11e7-8198-1f944f7145b0.png)

You can also see oscillations in pitch angle due to THR changes.

![image](https://cloud.githubusercontent.com/assets/8240355/25010815/ebcec166-2073-11e7-9aef-e21fd9452aef.png)

Any suggestion to improve this behaviour is welcome.
Best Wishes,
Ferit.

#### Version
ArduPlane v3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X ] Plane
[  ] Rover

#### Airframe type
QuadPlane

#### Hardware type
PixHawk

**Comment by iskess** [comment]
Excellent write up and analysis. I've been puzzled by this behavior.

**Comment by magicrub** [comment]
Agreed, great write up.  Do you have logs to share?

**Comment by ferdicakmak** [comment]
You can see that even when RTL alt and QRTL alt is the same, i experienced same behaviour due to an altitude difference of 4m.

![image](https://cloud.githubusercontent.com/assets/8240355/25036486/cc520ab2-20fc-11e7-9393-82ada6f5953b.png)

I believe that the problem may be the desired climb rate downside (2 m/s) may be too much to handle for quadplane while in quad mode with a level velocity demanded (5m/s). When level velocity becomes 0, then no problem with descent rate. 

In my parameters for Quadplane, Q_WP_SPEED_DN = 150cm/s, Q_WP_SPEED_UP = 200cm/s and Q_VELZ_MAX = 200cm/s. So I believe in QRTL, flight controller uses Q_VELZ_MAX while approaching to HOME point, and Q_WP_SPEE_DN for initial landing. Thus I am planning on changing Q_VELZ_MAX = 100cm/s for the next flight.

You can find log file, parameters, kmz, and gpx files below.
[19_RAPTOR_VTOL_2_DolphinMove.zip](https://github.com/ArduPilot/ardupilot/files/921701/19_RAPTOR_VTOL_2_DolphinMove.zip)

You can also see the video of the final phase of the flight below.
[19_RAPTOR_VTOL_2_DolphinMove_Video.zip](https://github.com/ArduPilot/ardupilot/files/921713/19_RAPTOR_VTOL_2_DolphinMove_Video.zip)

**Comment by iskess** [comment]
This is still happening in beta 3.8r6.

**Comment by magicrub** [comment]
added to next devcall topic

**Comment by ferdicakmak** [comment]
I believe such behaviour should be expected, due to contradicting response of VTOL and FW control elements in the transition manuever from FW to VTOL. I was able to minimize this behaviour by decreasing vertical speed limits.

I believe that, the firmware this can be improved by gradually increasing vertical speed limits during transition.

**Comment by iskess** [comment]
Sorry I must amend my comment. The title of this issues says "sustained oscillation". I'm not seeing this but maybe it because I'm using Hybrid RTL so there isn't much distance to cover to reach the descent point. 
What I'm seeing it a big pitch up zoom climb when trying to lock on to the RTL point.  I suppose I posted in the wrong place. I'll upload a log here soon in case that helps.

**Comment by iskess** [comment]
This was a VTOL_LAND. Transition starts at line 295, the pitch is ok during transition. At line 315 the pitch gets up to 41 deg. This exceeds the attitude limits set.  
![image](https://user-images.githubusercontent.com/4913946/28035170-54427290-654f-11e7-868b-646a32cd9c26.png)

There are 2 similar VTOL_LAND attempts in this .bin
https://www.dropbox.com/s/0xj06lflpyv9xmy/00000039.BIN?dl=0

**Comment by expntly** [comment]
I've seen this happen a few month ago with a vehicle I built, and this also happened today with another vehicle, ArduPlane 3.8.0-beta6, as I was trying QRTL.  I've also seen somebody discuss this on discuss.ardupilot.org somewhere so this is a known bug that's been around for a while.

**Comment by IamPete1** [comment]
Sorry we never got to this, I'm afraid there has been so many changes to the Q logic that this report is now of limited use.
