### ISSUE TITLE
Gazebo Simulator with SITL Doesn't WORK

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#6053]
spy@spy-CW65S:~/workspace/Gitlab_source/ardupilot/Tools/autotest$ python sim_vehicle.py -f gazebo-iris -D --console --map -v ArduCopterSIM_VEHICLE: Start
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at -35.363261,149.165230,584,353 (CMAC)
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/spy/workspace/Gitlab_source/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl" "--debug"
Setting top to                           : /home/spy/workspace/Gitlab_source/ardupilot 
Setting out to                           : /home/spy/workspace/Gitlab_source/ardupilot/build 
Autoconfiguration                        : enabled 
Setting board to                         : sitl 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for need to link with librt     : not necessary 
Checking for HAVE_CMATH_ISFINITE         : yes 
Checking for HAVE_CMATH_ISINF            : yes 
Checking for HAVE_CMATH_ISNAN            : yes 
Checking for NEED_CMATH_ISFINITE_STD_NAMESPACE : yes 
Checking for NEED_CMATH_ISINF_STD_NAMESPACE    : yes 
Checking for NEED_CMATH_ISNAN_STD_NAMESPACE    : yes 
Checking for header endian.h                   : yes 
Checking for header byteswap.h                 : yes 
Checking for program 'python'                  : /usr/bin/python 
Checking for python version >= 2.7.0           : 2.7.12 
Source is git repository                       : yes 
Update submodules                              : yes 
Checking for program 'git'                     : /usr/bin/git 
Checking for program 'size'                    : /usr/bin/size 
Benchmarks                                     : disabled 
Unit tests                                     : enabled 
'configure' finished successfully (0.698s)
SIM_VEHICLE: Building
SIM_VEHICLE: "/home/spy/workspace/Gitlab_source/ardupilot/modules/waf/waf-light" "build" "--target" "bin/arducopter"
Waf: Entering directory `/home/spy/workspace/Gitlab_source/ardupilot/build/sitl-debug'
Waf: Leaving directory `/home/spy/workspace/Gitlab_source/ardupilot/build/sitl-debug'

BUILD SUMMARY
Build directory: /home/spy/workspace/Gitlab_source/ardupilot/build/sitl-debug
Target          Text     Data  BSS    Total  
---------------------------------------------
bin/arducopter  1789069  2136  35552  1826757

Build commands will be stored in build/sitl-debug/compile_commands.json
'build' finished successfully (1.921s)
SIM_VEHICLE: Using defaults from (/home/spy/workspace/Gitlab_source/ardupilot/Tools/autotest/default_params/gazebo-iris.parm)
SIM_VEHICLE: Run ArduCopter
SIM_VEHICLE: "/home/spy/workspace/Gitlab_source/ardupilot/Tools/autotest/run_in_terminal_window.sh" "ArduCopter" "/home/spy/workspace/Gitlab_source/ardupilot/build/sitl-debug/bin/arducopter" "-S" "-I0" "--home" "-35.363261,149.165230,584,353" "--model" "gazebo-iris" "--speedup" "1" "--defaults" "/home/spy/workspace/Gitlab_source/ardupilot/Tools/autotest/default_params/gazebo-iris.parm"
SIM_VEHICLE: Run MavProxy
SIM_VEHICLE: "mavproxy.py" "--master" "tcp:127.0.0.1:5760" "--sitl" "127.0.0.1:5501" "--out" "127.0.0.1:14550" "--out" "127.0.0.1:14551" "--map" "--console"
RiTW: Starting ArduCopter : /home/spy/workspace/Gitlab_source/ardupilot/build/sitl-debug/bin/arducopter -S -I0 --home -35.363261,149.165230,584,353 --model gazebo-iris --speedup 1 --defaults /home/spy/workspace/Gitlab_source/ardupilot/Tools/autotest/default_params/gazebo-iris.parm
Traceback (most recent call last):
  File "sim_vehicle.py", line 1007, in <module>
    start_mavproxy(cmd_opts, frame_infos)
  File "sim_vehicle.py", line 802, in start_mavproxy
    run_cmd_blocking("Run MavProxy", cmd, env=env)
  File "sim_vehicle.py", line 645, in run_cmd_blocking
    p = subprocess.Popen(cmd, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
SIM_VEHICLE: Killing tasks

**Comment by OXINARF** [comment]
This issues list is for confirmed bugs and feature requests. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter (http://gitter.im/ArduPilot/ardupilot).

From your log, it looks like you don't have MAVProxy installed. You either install it or use the `--no-mavproxy` command-line option.
