### ISSUE TITLE
px4fmu-v2 nuttx-configs DMA configure error?

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#6077]
hello all,
    i found something strange here

> 226 /* UART RX DMA configurations */
227 #define DMAMAP_USART1_RX DMAMAP_USART1_RX_2
228 #define DMAMAP_USART6_RX DMAMAP_USART6_RX_2

> 275 #ifdef CONFIG_STM32_SPI_DMA
276 /*
277   only enable DMA on the sensor bus and external for now. We don't
278   have enough spare DMA channels for the other buses
279  */
280 # define DMACHAN_SPI1_RX DMAMAP_SPI1_RX_1
281 # define DMACHAN_SPI1_TX DMAMAP_SPI1_TX_2
282 # define DMACHAN_SPI2_RX DMAMAP_SPI2_RX
283 # define DMACHAN_SPI2_TX DMAMAP_SPI2_TX
284 # define DMACHAN_SPI4_RX DMAMAP_SPI4_RX_2
285 # define DMACHAN_SPI4_TX DMAMAP_SPI4_TX_2
286 #endif

I found that `281 # define DMACHAN_SPI1_TX DMAMAP_SPI1_TX_2
`  is same as `#define DMAMAP_USART1_RX DMAMAP_USART1_RX_2`, both of them configure as `DMA2 STREAM5.` So configuration error, or something i missed?

**Comment by OXINARF** [comment]
I was missing it too, USART1_RX DMA was disabled: https://github.com/ArduPilot/PX4Firmware/commit/be35c1add5f2f172e3d26271fbed76685512dac1#diff-5f4336ea3104c72204f9a740ce909d73R300
