### ISSUE TITLE
Remove internal / external bussing on Toshiba led driver

### ISSUE THREAD

**Issue by proficnc** [ArduPilot/ardupilot#6088]
#### Issue details
The LED driver is forcing a board specific behaviour on all boards
This looks for an led on the "external bus" and only if it doesn't find one will it try the internal bus.

We would like to ensure that if the LED is found on both busses, that it functions.

While discussing this issue, it was noted that some users prefer to have the internal LED turned off on the Pixhawk 1 due to a heating issue that is said to affect temperature stability of the IMU's 

So it has been suggested, that adding a parameter to selectively enable each or all busses would be good. The drivers can still be running at this stage. 

#### Version
_What version was the issue encountered with_
ALL

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
All
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
Pixhawk ALL especially 2

**Comment by dinardip** [comment]
+1  being able to select status lights, should be an option.

**Comment by IanP13** [comment]
I agree that there should be a parameter to selectively enable each or all busses rather than a default behaviour that is hard coded.

**Comment by tridge** [comment]
yep, it should be on both buses, if found

**Comment by lakshaydang** [comment]
when this would be available for use in the firmware ?

**Comment by NickNunno** [comment]
I'd agree that this seems like a very logical implementation.

**Comment by yak-54** [comment]
+1 agree 
i have this issue as i have GPS puck fitted inside a fuselage of a plane and an i have one external on the Ic2 bus and the one on the here GPS take's Priority

**Comment by hdtechk** [comment]
I would really like to see  a fix for this hope someone can find way to do PR

**Comment by proficnc** [comment]
@tridge Any movement on this one? 
Got quite a few people still asking for this as they are running the dual GPS.

**Comment by robustini** [comment]
I'm one of this few people...

![af52b609ea20b6e73f91454b9f9e830de5fc66d7a8e17d0709 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/3864712/28746176-531617cc-7487-11e7-9b84-554df1cde905.jpg)

**Comment by tridge** [comment]
i can fix it, yes, but not for the plane 3.8 release, as I'm finalising that already

**Comment by OXINARF** [comment]
This is now supported in master (via #6910).
