### ISSUE TITLE
Copter: send MAVLink feedback when a command in Guided mode is finished

### ISSUE THREAD

**Issue by adrianhsm** [ArduPilot/ardupilot#6095]
#### Issue details
in auto mode, when a way point reaches, we could reach an indication message, but if in guided mode, no message when a mission item is reached

#### Version
all

#### Platform
[  ] All
[  ] AntennaTracker
[*] Copter
[  ] Plane
[  ] Rover

#### Airframe type
quad

#### Hardware type
pixhawk

#### Logs
no

#### ps
I have written the codes to implement this, if you think this feature should be there, I will create a pull request for it, if not, please tell me your concern as we may sometimes want to have this feature on.

**Comment by OXINARF** [comment]
Related to #3416 and #6094

**Comment by amilcarlucas** [comment]
Implemented in master as of today
