### ISSUE TITLE
Teraranger One I2C Conflict with 3DR Compass

### ISSUE THREAD

**Issue by tcheehow** [ArduPilot/ardupilot#6109]
#### Issue details
Teraranger One and compass doesn't work together. Suspected I2C conflict as each can work independently if the other is removed from the I2C bus.

#### Version
Latest master

#### Platform
[  ] Copter

#### Airframe type
QUAD

#### Hardware type
Tested on Pixhawk and Pixhawk Mini

**Comment by OXINARF** [comment]
@tcheehow I'm not sure what this report is about. If the I2C addresses are the same there is nothing ArduPilot can do about it, they need to be different.

**Comment by rmackay9** [comment]
I think all we can do is update the wiki to tell people how to change the I2C address of the terrarange.  I'll take this one... maybe @tcheehow can give us details on how to modify the sensor's address.

**Comment by Galaxy88** [comment]
To change the address of the TeraRanger One, you need to send the Change_Base_Address command 0xA2 followed by the new address to set, eg. send 0x42 if you want base address 0x42 (ignoring read/write bits). 

After sending the command, power cycle the device. It will join the I2C bus as a slave on the new address. 

[Source](https://www.terabee.com/wp-content/uploads/2017/09/TR_One_Manual_FW5.0.Version1_0_0.pdf)

**Comment by peterbarker** [comment]
@Hwurzburg this could be a useful thing to document @Galaxy88 's fix in the Wiki somewhere.

In any case, not something for the ArduPilot repo.
