### ISSUE TITLE
Copter: twitch during AUTO when changing from spline to straight waypoint

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#6115]
In AC3.5 (and earlier) during missions, if a Spline waypoint is followed by a straight line waypoint the vehicle will twitch during the transition.

There are two causes:

- the straight line waypoint controller's "leash" was "L" shaped while the spline controller's was a straight line.  This is resolved by this PR: https://github.com/ArduPilot/ardupilot/pull/6116
- in AC_WPNav.cpp's, "set_wp_origin_and_destination" function, the "speed_along_track" and "_limited_speed_xy_cms" variables are calculated using the vehicle's current velocity.  Instead these should be calculated using the final velocity of the target point during the previous segment (if there was one).  We cannot simply copy the previous segments velocity however, we only take the component of that velocity which aligns with our new segment.

**Comment by lthall** [comment]
All this code has been rewritten in 4.1 with more stringent initialisation.

If this is still a problem we can reopen.
