### ISSUE TITLE
Compass calibration issue

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#6141]
#### Issue details
My  second compass xmag almost -900, and when calibrated done, got a large offset data.  now mag2's data was weird, i set offset to 0 by manual, it beame normal again.
![untitled2](https://cloud.githubusercontent.com/assets/16251761/25518879/283c0f5e-2c28-11e7-96b5-b1cb9c0eccb3.png)
![untitled](https://cloud.githubusercontent.com/assets/16251761/25518888/2efec976-2c28-11e7-917b-fe3073be2a4a.png)
![untitled3](https://cloud.githubusercontent.com/assets/16251761/25518891/31edd3c0-2c28-11e7-8ae3-9bec9d89df4b.png)

what issue is here ?

#### Version
3.5 rc4
#### Platform
 Copter

**Comment by OXINARF** [comment]
@liang-tang This is a support question and those should be posted in the forum (http://discuss.ardupilot.org).
