### ISSUE TITLE
Plane: add protection against bad GPS positions

### ISSUE THREAD

**Issue by goochpw** [ArduPilot/ardupilot#617]
I had a good plane mission going and all of a sudden the plane began roller coastering.  I got it down safely, checked the logs, and found that Hdrop value had gone from 1.78 to 3.18 and I satellite count from 8 to 7.   Anything you can do to help in this situation?

**Comment by WickedShell** [comment]
To the best of my knowledge this is handled about as well as it can be, but the EKF can reject inconsistent GPS data, and is aware of the estimated accuracies of the data. At least I'm flying GPS altitude and have had some significant GPS upsets in the past with plane and haven't had it develop into a unstable situation, so I'm closing this for now. Feel free to reopen it if someone disagrees.
