### ISSUE TITLE
mavlink issue with companion computer

### ISSUE THREAD

**Issue by RoelHelsen** [ArduPilot/ardupilot#6191]
#### Issue details
Whenever I connect my companion computer to my flight controller, my ground station (missionplanner or qgroundcontrol) sees 'multiple' systems and has problems to display telemetry. The companion computer uses mavros and I set a system ID of 1 (same as the drone) and a component ID of 240, as target IDs I use two times 1.

Is there any setting that I can change to solve this? Or does this require reprogramming in the mavlink processing?

#### Version
Copter 3.4.6

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
octa-quad

#### Hardware type
pixhawk 2

**Comment by rmackay9** [comment]
Normally the vehicle and companion computer should use the same system id but have different component ids.  It sounds like you've done this so I think the real issue is in the ground stations.  I think ardupilot is doing what it should which is pass all the information to the ground stations.
