### ISSUE TITLE
What is the meaning of rc in rc_calibration_checks?

### ISSUE THREAD

**Issue by Boeing738ng** [ArduPilot/ardupilot#6204]
#### Issue details
I read the code in section Acupoint/ArduCopter/AP_Arming.cpp and found that the meaning of rc_calibraton wasn't understood.
#### Version
1.0

#### Platform
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
quad

#### Hardware type
pixhawk

**Comment by rmackay9** [comment]
"RC" is for "radio control" so that covers the stick inputs from the pilot.

**Comment by OXINARF** [comment]
@Boeing738ng For these type of questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot), here is only for feature requests or confirmed bugs.
