### ISSUE TITLE
Rover: Need to add support for battery failsafe

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#6208]
Rover currently doesn't support battery failsafe.  Not a huge issue for Rovers as they don't fall out of the sky when the battery goes flat but some users have requested it RTL when the battery is low.

**Comment by mikerob** [comment]
I think this is more important than you have stated. For IC powered rovers, loss of battery does not necessarily mean they will stop - if the servos stop in place you will hold throttle and steering at whatever setting. 

Is it possible to default it to active and go into "HOLD" to be on the safe side?

Mike

**Comment by gmorph** [comment]
We can't default it to active as we don't know the lower voltage threshold.  For a 3S it might be 10.5v but for a 4S it might be 14v.

Thanks, Grant.

**Comment by WickedShell** [comment]
This was done in #7213
