### ISSUE TITLE
Tools: change to using waf for building releases

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#6210]
#### Issue details
We currently use the make build system for creating the binray releases for firmware.ardupilot.org.

make is also (soft) deprecated.

We should stop using the make build system for the releases as a prerequisite for removing the make build system

**Comment by OXINARF** [comment]
I'll just clarify that only PX4 boards are built using the Make build system, all others are using waf.

**Comment by magicrub** [comment]
I think we should add some text suggesting to use waf on any make build with the equivalent command shown. Maybe even a Press Enter To Continue nag prompt to ensure it is seen.

**Comment by amilcarlucas** [comment]
Aren't the releases done in waf now ?

**Comment by magicrub** [comment]
Peter would be the one who knows... And he opened the issue so I'd say it's still valid.

**Comment by OXINARF** [comment]
Yes, this is done, all releases are now done with waf (well, except AVR, but that's another branch).
