### ISSUE TITLE
Arducopter documentation needs info about autotakeoff

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#6230]
There is no documentation on autotakeoff, (as part of mission or otherwise) - nowhere users can see info about required throttle stick position, or how to do it at all.

**Comment by OXINARF** [comment]
@AndKe Can you please open this issue in the wiki repo? That's the correct place for this. Thanks.

**Comment by AndKe** [comment]
thanks - I were not aware of it's existence until I searched now.
