### ISSUE TITLE
APM issues about Firmware-3.7.1 on Ubuntu.

### ISSUE THREAD

**Issue by fightinghui** [ArduPilot/ardupilot#6241]
#### Issue details
1.
     makefile is "
all: sitl

px4-v2: TARGET=sitl
px4-v2: plane copter rover antennatracker

linux: TARGET=linux
linux: plane copter rover antennatracker

clean: TARGET=clean
clean: plane copter rover antennatracker

.PHONY: plane copter rover antennatracker

plane:
	$(MAKE) -C ArduPlane $(TARGET)

copter:
	$(MAKE) -C ArduCopter $(TARGET)

rover:
	$(MAKE) -C APMrover2 $(TARGET)

antennatracker:
	$(MAKE) -C AntennaTracker $(TARGET)
". I want to know whether makefile need to be revised "
all: px4-v2

px4-v2: TARGET=px4-v2
......".

2.
make[4]: *** No rule to make target `/home/zyf/APM2/ardupilot/libraries/AP_HAL/board/px4.h', needed by `/home/zyf/APM2/ardupilot/ArduPlane/afs_plane.cpp.o'.  Stop.
make[4]: Leaving directory `/home/zyf/APM2/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build/home/zyf/APM2/ardupilot'
make[3]: *** [/home/zyf/APM2/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build//home/zyf/APM2/ardupilot/module.pre.o] Error 2
make[3]: Leaving directory `/home/zyf/APM2/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build'
make[2]: Leaving directory `/home/zyf/APM2/ardupilot'
make[1]: Leaving directory `/home/zyf/APM2/ardupilot/ArduPlane'
make[2]: *** [/home/zyf/APM2/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build/firmware.px4] Error 2
make[1]: *** [px4-v2] Error 2

3.
    I want to know how to set my airframe  as SkyWalker X8.
#### Version
ArduPlane-3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Plane

#### Hardware type
Pixhawk2 Standard

I'm looking forward to your reply.Thanks.

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

Answering your questions:

- I don't know where you see that Makefile, ours in 3.7.1 is at https://github.com/ArduPilot/ardupilot/blob/ArduPlane-3.7.1/Makefile and doesn't have that code
- recommended way to build using Make is to enter the vehicle directory (ArduPlane, ArduCopter, etc.) and execute the make command there
- your build error will probably be fixed once you use the recommended way to build
- I don't really understand your last question, you don't set any airframe type, you set parameters to match your frame needs

If you have more questions use the channels mentioned above.
