### ISSUE TITLE
Optical Flow keeps resetting

### ISSUE THREAD

**Issue by caoshiyue** [ArduPilot/ardupilot#6242]
#### Issue details
I have PX4FLow connected to Pixhawk(run Copter 3.6-dev) via I2C. I set the FLOW_ENABLE to 1 via USB. Then reboot and check opt_m_x opt_m_y and opt_qua, the value never changed but not 0. Every time I unplug USB and power by battery, FLOW_ENABLE is set to 0, no other settings are reset. If downgrade to Copter 3.4.6, it works well.
It is related to this 
http://discuss.ardupilot.org/t/flow-setting-keeps-resetting/16332
Is there any problem I did wrong?  Thank you.

#### Version
Copter 3.6-dev
#### Platform
 [ ] Copter
#### Airframe type
QUAD
#### Hardware type
Pixhawk

**Comment by rmackay9** [comment]
It seems to be working ok for me so I'm going to close this issue until we confirm it's a code bug.  Let's discuss in the linked thread.
