### ISSUE TITLE
"ERR" values of position setpoint in guided mode

### ISSUE THREAD

**Issue by Shpiler** [ArduPilot/ardupilot#6247]
When flying in guided mode using Dronekit on RPi i met the following issue:
As you can see on screen-shot the value of target altitude become "ERR" at T+3384s. The same is true also for x and y position setpoints. Also overall drone behavior was.. lazy, so this resulted in a crash.
![2017-05-15 14-37-29](https://cloud.githubusercontent.com/assets/5054881/26057028/65adbd3c-3980-11e7-9134-6d3c5648721b.png)

Any ideas what could cause this?  The full log is also attached.

#### Version
3.4.5
#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
"X"

#### Hardware type
Pixhawk

#### Logs

[69.zip](https://github.com/ArduPilot/ardupilot/files/1001002/69.zip)

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).

I've looked at your log with Mission Planner and I don't see any error in your last GUID line, with a value of -413.2533 for  pZ. Regarding pX and pY it looks like you are sending strange values in some packets.
If you need more help, do as said above.
