### ISSUE TITLE
AP_Landing: Deepstall: Support CCW loiters

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#6251]
#### Issue details
Deepstall gets stuck in a CCW landing pattern, and makes several bad assumptions about the handling of loiter radii. (This is my fault, opening the issue to track it for future reference).

#### Version
Master

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

**Comment by magicrub** [comment]
get'r'done! :)

**Comment by WickedShell** [comment]
This was done in #7080
