### ISSUE TITLE
Use GPS time rather than time since boot in GPS_RAW_INT message

### ISSUE THREAD

**Issue by rrr6399** [ArduPilot/ardupilot#626]
Based on my testing, it appears that the time_usec in the GPS_RAW_INT MAVLink message contains the time since boot rather than GPS time. Please use the GPS time for time_usec or add another field for the true GPS time. (I have not found any MAVLink message yet that contains the true GPS time in practice.)

**Comment by jasonbeach** [comment]
Just curious--so it looks like the system time message has the full unix time, but the GPS raw message still has microseconds since boot.  Is there a reason the GPS raw message doesn't have GPS time in it?
