### ISSUE TITLE
Include Graupner HOTT telemetry support into code tree

### ISSUE THREAD

**Issue by msk7-ripe** [ArduPilot/ardupilot#631]
Some time ago Adam Majerczyk wrote HOTT support for AP 2.7 (https://code.google.com/p/hott-for-ardupilot/). It worked for me in 2.9.1 and (with minor changes) now works in 3.0.1 though I never updated project tree. Now I'm trying to implement HOTT in current AC version. There are some problems cause timer driven proc is needed to fulfill tight HOTT timings and in newer versions timer ticks slower. Graupner RC is popular and valuable, so I suggest including HOTT support into main APM tree. If sources working with 3.0.1 are needed, contact me.

**Comment by j-lang** [comment]
What is the current state of this geat extension? Is there a plan for integration into APM and Pixhawk firmware? I had a prior version on apm 2.8 running and it is so useful - as long your Hott receiver works you have info about the current state of the copter - especially without additional hardware.  My 3dr radio looses  connection over 200m - 300m and have mount the smartphone to the RX, whats not recommended by all RC equipment producers. :+1:

**Comment by AndKe** [comment]
due to the lack of RX/TX control in pixhawk (disable RX while transmitting) I am using an external device, http://madhacker.org/mavlink-to-hott-adapter/  
Still - I would love to see Pixhawk capable of this.
