### ISSUE TITLE
problem about rudder move with aileron ,and the elevator servo movement range is too long

### ISSUE THREAD

**Issue by bluecat1997** [ArduPilot/ardupilot#6328]
#### Issue details
I'm preparing China aero design challenge competition .we have designed a fixedwing.and when work with the pixhawk we met several questions.
1.when we move the aireron the rudder will move with the aireron.how to disconnected the aileron and rudder

2.in manual mode and stabilize mode we just use 30% of elevator servo movement range.so we set channel 2 to 30% on our transmitter.but after radio calibration on mission planner .in fbwa mode we pull the elevator stick full downthe elevator servo still can move to 100%

#### Version
Arduplane 3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ √ ] Plane
[  ] Rover

#### Airframe type
fixedwing with typical elevator and rudder

#### Hardware type
pixhawk

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).

**Comment by magicrub** [comment]
problem is you're mixing on the transmitter. Don't do that.  Use the params. Search the param page for the word "mix" for various methods. KFF_RDDRMIX is a good start. Look at them all. 
http://ardupilot.org/plane/docs/parameters.html
