### ISSUE TITLE
Allow APM to start-up even if Baro fails initialisation

### ISSUE THREAD

**Issue by proficnc** [ArduPilot/ardupilot#634]
I had an interesting issue today.  I was setting up a customers APM2.5 and it kept jamming up....

after trying with Plane firmware, I got the following errors in CLI

```
Init ArduPlane?<w?
Press ENTER 3 times to start interactive setup

3Demo Servos!=@//3Warming up ADC...C")"4 )% 3Demo Servos!//?3Demo Servos!"
//3 3Beginning INS calibration; do not move planeN?3
Initialising APM...*E2"//-?Init Gyro//??//D*R//&//Zv3Initialising APM... Kb//&1*y//?   w/?/8? //{?!i"//?3#Initialising APM...N3$Initialising APM...?%&//nPANIC: AP_Baro::read     unsuccessful for more than 500ms in AP_Baro::calibrate [1]
```

same in copter...

```
Init ArduCopter V3.0.1
Free RAM: 2060
FW Ver: 120
---------------------------------------------------------------

load_all took 1336us

Press ENTER 3 times to start interactive setup

3Calibrating barometer Q///+?PANIC: AP_Baro::read unsuccessful for more than 500ms in AP_Baro::calibrate [1]
```

Suggestion........
that even with this error, that ArduPilot starts, but sends an error to the GCS saying Baro Failure.

unfortunately, this lockup stops you from loading firmware, and is hard to catch in CLI.

After some further experimenting, this also affects the gyro, and accel if they happen to totally fail too.

**Comment by hiro2233** [comment]
@proficnc Hello, on the lastest AC and AP APM version it working very good.

@OXINARF Please close it.
