### ISSUE TITLE
Copter: support yaw, yaw-rate fields of SET_POSITION_TARGET mavlink messages

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#6357]
Copter supports the SET_POSITION_TARGET_LOCAL_NED and SET_POSITION_TARGET_GLOBAL_INT mavlink message in Guided mode but ignores the yaw and yaw-rate fields.  We should add support for controlling the vehicle's heading using these two fields.

http://mavlink.org/messages/common#SET_POSITION_TARGET_LOCAL_NED
http://mavlink.org/messages/common#SET_POSITION_TARGET_GLOBAL_INT

**Comment by jagrandle** [comment]
+1  This would be a great enhancement. We would like to be able to set yaw speed as desired.

**Comment by rmackay9** [comment]
This is resolved now in master and the change will probably go out in an AC3.5 point release.
