### ISSUE TITLE
How to set Waypoints in RAM (volatile)

### ISSUE THREAD

**Issue by RQRobert** [ArduPilot/ardupilot#6383]
#### Issue details
I am having trouble in AUTO mode, 
When i trigger AUTO ,  i forget to update waypoints
and my quad flies to the previous waypoints (location) .
I have 2 crashes due to this and i feel PX4 firmware has solution to this problem.
But PX4 firmware is not as stable as Arducopter , also i m using Arducopter since 2013.

So , How to set Waypoints in RAM (volatile)  just like PX4 Firmware??????

#### Version

ArduCopter 3.4.6

#### Platform
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Copter

#### Hardware type
Pixhawk

**Comment by magicrub** [comment]
By saying "in ram" you mean "clear on reboot", right?

**Comment by RQRobert** [comment]
Yes exactly

**Comment by magicrub** [comment]
How about a new param called "MIS_RETAIN" which defaults to 1 (enabled) which is the current behavior. When set to 0 it wipes the mission on boot.

**Comment by RQRobert** [comment]
In addition to wiping out mission , also home location should clear too ?????

**Comment by khancyr** [comment]
home position is reset on the arming position normaly !

**Comment by RQRobert** [comment]
So the only thing left is a parameter like "MIS_RETAIN" , which solves the issue.

**Comment by rmackay9** [comment]
Something similar came up in a discussion with @DonLakeFlyer.  Apparently QGC has a clear mission feature but it sometimes doesn't work with Copter because after an RTL, we sometimes consider that the mission is still running (I think).  So perhaps this could be a ground station feature and we just need to fix this bug that Don has raised?

**Comment by RQRobert** [comment]
Randy

I was mainly interested in volatile nature of Waypoints (waypoints to be stored in RAM instead of FRAM).

**Comment by magicrub** [comment]
They will never "be in RAM". We support huge mission lengths..

**Comment by OXINARF** [comment]
There is already an issue requesting this, #5743, so I'm closing this one.
