### ISSUE TITLE
when will the copter3.5-rc5  be stable?

### ISSUE THREAD

**Issue by colorfuljune** [ArduPilot/ardupilot#6385]
when will the copter3.5-rc5  be stable?now it is beta

**Comment by khancyr** [comment]
When we will have suffisant testing and confidence that it is really stable with no annoying bug !

This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).
