### ISSUE TITLE
EKF2 not disable more noisy IMU2 on pixracer, causing altitude rise.

### ISSUE THREAD

**Issue by hyperion11** [ArduPilot/ardupilot#6393]
#### Issue details
EKF2 not disable more noisy IMU2 on pixracer, causing altitude rise.
As i think if IMU1 less noisy EKF2 must work with it then work with more noisy IMU2, isn't?
Or EKF2 is discounted, and i need try EKF3?

#### Version
3.5-rc7

#### Platform
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quad

#### Hardware type
Pixracer

#### Logs
http://discuss.ardupilot.org/uploads/default/original/2X/0/0fd5fe8d52481da65d994b2a2b1d9e804f3d122c.bin
![34281113493_06a7627be1_o](https://user-images.githubusercontent.com/13326299/26858810-bce5dbf4-4b5d-11e7-88fd-39e657e992ad.jpg)

**Comment by OXINARF** [comment]
I'm not sure what you are reporting here. EKF doesn't disable IMUs, it chooses the best to work with.

It looks like you've posted in the forum, where this needs to be handled, this issues list is for feature requests and confirmed bugs.

**Comment by hyperion11** [comment]
So is it normal that EKF chooses an IMU with higher vibrations instead of selecting IMU with lower ones?

**Comment by OXINARF** [comment]
Where is it choosing to use the second IMU?

**Comment by hyperion11** [comment]
i see bad vibration level on imu2, and acceptable vibration level on imu1. But copter rise up. I think this is because ekf chooses a more noisy accelerometer. Or I'm wrong? 
Where in the logs we can see what data of which accelerometer at a particular time is used for INS?

**Comment by OXINARF** [comment]
Look at the NKF4.PI field. Again, this is appropriate in the forum, not here.

**Comment by hyperion11** [comment]
thank you. Sorry for possible offtopic here, but i have blank NKF4.PI and NKF9.PI field
![c1f8cc5d884a49520d4e21148f9e2801aaaf71f3](https://user-images.githubusercontent.com/13326299/26957530-d6236f26-4cef-11e7-8399-cea1be611b39.png)

**Comment by OXINARF** [comment]
It's not blank, it is zero, meaning it is using the first IMU, not the second... Now, continue in the forum please.
