### ISSUE TITLE
Arduplane: add COMPASS_USE=2 for auto switch between GPS and compass

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#64]
In ArduPlane there is a choice between navigation primarily by GPS and primarily by compass. Right now users need to make a choice before takeoff, by setting COMPASS_USE=0/1. I think a COMPASS_USE=2 option meaning "auto" makes sense, where the compass would be always enabled for takeoff (where GPS makes no sense, due to low ground speed), and GPS would be used when the GPS fix is high quality, and the plane is travelling well above the minimum speed.
I also think this should be the default for ArduPlane.

**Comment by artemskorsky** [comment]
Hi Tridge,  on mission planner for COMPASS_USE only 0/1 values available. if i set to 2 it will be in "Auto" mode?     I am having 360 roll problem (*crash) during take off .   after disabling COMPASS_USE seems this problem has gone.
