### ISSUE TITLE
How to understande (hgtErr*velDErr > 0.0f) in FuseVelPosNED() in EKF?

### ISSUE THREAD

**Issue by luweikxy** [ArduPilot/ardupilot#6419]
Hi, guys, does anyone kown FuseVelPosNED() in EKF2? I cannot understand this piece of code in FuseVelPosNED() as follow:

        if (useGpsVertVel && fuseVelData && (frontend->_altSource != 2)) {
            // calculate innovations for height and vertical GPS vel measurements
            float hgtErr  = stateStruct.position.z - observation[5];
            float velDErr = stateStruct.velocity.z - observation[2];
            // check if they are the same sign and both more than 3-sigma out of bounds
            if ((hgtErr*velDErr > 0.0f) && (sq(hgtErr) > 9.0f * (P[8][8] + R_OBS_DATA_CHECKS[5])) && (sq(velDErr) > 9.0f * (P[5][5] + R_OBS_DATA_CHECKS[2]))) {
            	badIMUdata = true;
            } else {
                badIMUdata = false;
            }
        }

Why there is hgtErr*velDErr > 0? I think it is because if hgtErr exits, it means that there is a error in height, and if sign of velDErr is same as hgtErr, then it means that this error in height has a trend of extending and there is a divergency. This is my first question.

And my second question is if "if ((hgtErr*velDErr > 0.0f) && ...)" is true, why it can be confirmed that IMU is bad, Is there any other reasons such as GPS is bad or Baro is bad?

Thanks a lot!

**Comment by OXINARF** [comment]
As I've told you earlier, this issues list isn't the correct place for questions. You either post in the forum or ask in Gitter chat (which you had already).
