### ISSUE TITLE
Add support for FrSky Telemetry

### ISSUE THREAD

**Issue by vizual54** [ArduPilot/ardupilot#643]
It would be nice to have telemetry from the APM to the radio TX without the hassle of having to connect with mission planner to get the data going or changing cables depending on if you're going connect with mission planner or not. 

A suggestion is to use uart2 on the APM for this and create a lightweight protocol that sends the most important information. This could then be decoded on for example a arduino pro mini or teensy. Data could be sent at low rate like 5Hz or even 1Hz. The arduino can then implement different telemetry protocols like frsky, spektrum, openlrs etc. This way the telemetry for the radio is always working, whether we have mission planner connected or not. 

We can of course do a lot of other fun things like controlling leds based on received data. Sending data to a gsm/gprs card that can send positions to us when we're out radio range via sms or gprs.

Below is some sample code that I have been running, though not yet had the time to test in flight. And I have not yet measured if this is faster than running a second mavlink on uart2. Guess you can see what protocol that inspired me. 
At https://github.com/vizual54/APM-Simple-Telemetry-to-FrSky there is ongoing work to convert the data received from the APM to FrSky protocol.

static void send_simple_telemetry()
{
    Vector3f accel = ins.get_accel();
    int16_t battery_current = -1;
    int8_t battery_remaining = -1;

```
if (battery.monitoring() == AP_BATT_MONITOR_VOLTAGE_AND_CURRENT) {
    battery_remaining = battery.capacity_remaining_pct();
    battery_current = battery.current_amps() * 100;
}

char buffer[128];
snprintf(buffer, 128, "$%d,%d,%hd,%hu,%ld,%ld,%ld,%d,%hd,%lu,%ld,%ld,%ld,%hd,%ld,%d,%d,%d,%d*",
            (int16_t)battery.voltage(),         // Main battery voltage in V
            battery_current,                    // Battery current in mA
            battery_remaining,                  // Battery remaining in %
            g_gps->status(),                    // GPS Status 0:No Fix, 2:2D Fix, 3:3D Fix
            g_gps->latitude,                    // GPS Latitude in decimal degrees
            g_gps->longitude,                   // GPS Longitude in decimal degrees
            g_gps->altitude_cm,                 // GPS Altitude in cm
            g_gps->hdop,                        // GPS hdop
            g_gps->num_sats,                    // GPS Number of satelites in view
            g_gps->ground_speed_cm,             // GPS Ground speed in cm/s
            g_gps->ground_course_cd,            // GPS Course in 1/100 degree
            current_loc.alt,                    // Altitude in cm
            home.alt,                           // Home altitude in cm
            control_mode,                       // APM mode
            ahrs.yaw_sensor,                    // Compass
            g.rc_3.servo_out,                   // Throttle out
            (int16_t)(accel.x * 1000.0f),
            (int16_t)(accel.y * 1000.0f),
            (int16_t)(accel.z * 1000.0f)
            );

// Calculate and add checksum
int i = 1;
uint16_t checksum = 0x0000;
while (buffer[i] != '*')
{
  checksum ^= buffer[i++];
}
if (checksum < 0x10)
{
  sprintf(&buffer[i+1], "0%x", checksum);
}
else
{
  sprintf(&buffer[i+1], "%x", checksum);
}

hal.uartC->printf(buffer);
```

}

**Comment by gchiham** [comment]
Is it possible to send new waypoint or new Return to Home cordinates via SMS ?
