### ISSUE TITLE
AC3.5rc8 Need SF40C driver upgrade

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#6452]
Using SF40C if bad readings occur, SF40C return ZERO values,.....

This induce wooble and jearky  drone when using avoidance in althold, wich is very uncomfortable and make unusable avoidance feature.

It seems that filter is incorporated in loiter mode. So loiter mode avoidance with SF40C is usable.

Idea will be to filter this bad readings ZERO values that not match reality.

You will find attached log, and between log line 20K and 40K you can see bad readings zero value and non zerovalue that mach reality.
[2017-06-17 13-03-27.zip](https://github.com/ArduPilot/ardupilot/files/1082675/2017-06-17.13-03-27.zip)

**Comment by OXINARF** [comment]
@rmackay9 Any input on this?

**Comment by rmackay9** [comment]
Yes, we should make this fix.  I didn't see this issue so I created another one.  I'm going to close mine ('cuz earlier one is the one we normally keep).
https://github.com/ArduPilot/ardupilot/issues/6539

**Comment by rmackay9** [comment]
I've added a fix to master and this should go out with AC3.5.1.
https://github.com/ArduPilot/ardupilot/commit/d636e85eac4fb81081fad7f38ca3cffc2730fcee

Thanks again for the report.

**Comment by roque-canales** [comment]
I think that it must be better to add as for the RNGFND, min and max value filtered by for example:
PRX_READ_MIN
PRX_READ_MAX.

Like this each one can set it as it wants for improve integration.
