### ISSUE TITLE
APM RSSI 3.3V input (feature request)

### ISSUE THREAD

**Issue by branob** [ArduPilot/ardupilot#648]
The current RSSI_PIN expects RSSI signal from 0V to 5V. The new FrSky X8R receiver has RSSI output signal with 0V to 3.3V levels.

It would be nice if the RSSI_PIN had option to re-scale (software re-scaling) the input level to 0-5 to get accurate readings.
something like
if (RSSI_RANGE is 3.3) then RSSI = RSSI \* 5 / 3.3;

This should require one additional RSSI_RANGE parameter and one or two simple lines of code.

As of now, the RSSI_PIN works with X8R receiver but when at MAX it obviously shows only 66% signal strenght.

**Comment by gbstar** [comment]
I understand you can now connect the frsky x8r RSSI to the Pixhawk Sbus, although I can't find enough information on how to make this work. Does anyone know?

**Comment by CodeChief** [comment]
Without any modifications connect the RSSI port of the X8R to the SBUS of the Pixhawk. Don't get confused with the SBUS of the X8R, we're talking about two servo cables now connecting the receiver and Pixhawk as below:

Receiver <-> Pixhawk
SBUS -- RC
RSSI -- SBUS

If you are using MinimOSD you will only get RSSI passed through on the first telemetry port, so would have to move any radio/downlink to the second telemetry port.

However the future path is to just use an SmartPort (the third interface port besides servos on the X8R) and directly exchange MavLink messages with Pixhawk.

This is my current favourite: https://github.com/wolkstein/MavLink_FrSkySPort

But the future path integrated with Pixhawk is here: https://github.com/diydrones/ardupilot/issues/1587#issuecomment-72365015

**Comment by gbstar** [comment]
WOW, that was quick and very helpful. I did as you described and changed the settings in pixhawk using mission planner. But I can't see the RSSI information on the planner screen, there is no reference to it? Is there something I am not setting up? I connected the RSSI out on the x8r to the sbus on the pixhawk using a servo lead?

**Comment by CodeChief** [comment]
Right-click the "Quick" (status) in the "Info View" window of APM Planner 2.0, select "Add/Remove Items" then select "RC_CHANNELS" -> "rssi (unit8_t)". You should see a value up to 255 meaning 100%.

**Comment by gbstar** [comment]
Thank you very much. I could see the RSSi in the action panel didn't know how to make it show up on the main screen, thanks to you I now can see it lol. It's always good to get help from someone woo knows what they are doing. 

Next I am going to use the x8r's s-port to attach a board to pixhawk, to get the telemetry to my taranis. I know there are a couple of options, one being a Teensy 3.1 or maybe this one http://copter.ardupilot.com/wiki/common-frsky-telemetry/.
