### ISSUE TITLE
AP_Proximity: add missing informations and update documentation

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#6481]
#### Issue details
Information missing : 
Sensor_type : MAV_DISTANCE_SENSOR enum

Documentation miss the fact that the sensors id send is the orientation id + PROXIMITY_SENSOR_ID_START = 10

**Comment by amilcarlucas** [comment]
Can you do a PR ?

**Comment by IamPete1** [comment]
I'm not sure which documentation this is referring to?
