### ISSUE TITLE
Cannot checkout ArduPlane stable commit

### ISSUE THREAD

**Issue by Georacer** [ArduPilot/ardupilot#6493]
#### Issue details
I am not able to checkout and compile SITL for the latest stable ArduPlane version (3.7.1).
Steps:
* Have a local ardupilot git repo
* `git checkout ArduPlane-3.7.1`
* `git submodule update --init --recursive` This fails with the following error message:
```
$ git submodule update --init --recursive
Submodule path '../modules/PX4Firmware': checked out 'c4dfb9bfd468d6bb88d3c641eb69904380dd5b48'
Submodule path '../modules/PX4NuttX': checked out '258f22578c4d11543a0811a04b30647c13c34c54'
error: The following untracked working tree files would be overwritten by checkout:
[...]
Please move or remove them before you can switch branches.
Aborting
Unable to checkout '381586ce0e527e64007ebd85ca87ba52ade39f2a' in submodule path '../modules/mavlink'
```
* Compilation with `sim_vehicly.py -w` also fails when parsing pymavlink-related files

#### Version
ArduPlane 3.7.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
N/A

#### Hardware type
N/A

#### Logs
N/A

**Comment by OXINARF** [comment]
pymavlink wasn't a submodule back then. When going to such an old commit it is always best to clean the submodules with `git submodule deinit -f .` and then update them again after the checkout.
