### ISSUE TITLE
Will the PID performance change if  I  increase the cruise airspeed of airplane from 14m/s(H0m) to 18m/s（H5000m）? 

### ISSUE THREAD

**Issue by yuxiqun** [ArduPilot/ardupilot#6508]
Issue details
    I want to test my plane in altitude 5000m ,becase of the air density will decrease, I must incresase the cruise airspeed for sufficient lift .
    However,from the ardupilot wiki，I find a sentence which say "changing scaling_speed  will affect all PID values". The scaling_speed is same as the cruise airspeed in horizontal flight of airplane.
     So an issue comes, it is that should I need to tune PID performance of my airplane again ?

   Version
   3.7

    Platform
    Plane

 Airframe type
  flying wing

 Hardware type
 pixhawk

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
