### ISSUE TITLE
PX4 Battery monitor current sense not working - fw 2.75

### ISSUE THREAD

**Issue by MrMap** [ArduPilot/ardupilot#653]
Upon bench testing my PX4 after firmware upgrade to 2.75 and MP 1.2.85 I am unable to get any battery current reading, using the Battery monitor function.

The pin selected is still 101, as before.
Last time I played with it was some time agon, on 2.74 and then it worked, so I suspect firmware / software issue here.

![batterymonitormp](https://f.cloud.github.com/assets/5843103/1467122/d834907a-457c-11e3-8251-c6ccd85df3b7.PNG)

![parametercurr](https://f.cloud.github.com/assets/5843103/1467128/1562aac2-457d-11e3-8ab0-380b4d12350d.PNG)

**Comment by abencomo** [comment]
I don't think this fix was ever applied to the diydrones repository.

It's here:
https://github.com/3yc/hott-for-ardupilot/blob/cb57931a748056419d92f5c155df32d28a7f7584/PX4/hott-px4-code/PX4Firmware/src/drivers/boards/px4io-v1/board_config.h

But, not here:
https://github.com/diydrones/PX4Firmware/blob/ArduCopter-3.2.1/src/drivers/boards/px4io-v1/board_config.h

**Comment by kallaspriit** [comment]
How about this issue? Still experiencing it on APM:Copter V3.3.2.

**Comment by totaltmega** [comment]
I have not checked it and have since a setup like hsteinhaus below:

hsteinhaus commented on 8 Nov 2013
Same problem here. Quick workaround: use one of the analog inputs of the FMU (I used the 6.6V input and adjusted the BATT_AMP_PERVOLTn param).

Would be good to have it working non the less!

**Comment by kallaspriit** [comment]
Seems like a really simple fix to just merge with the diydrones repo, any reason this has not been done?

**Comment by rmackay9** [comment]
@kallaspriit, are you using the older PX4 or a Pixhawk? See links below and scroll down a bit to see the pictures.
Pixhawk: http://copter.ardupilot.com/wiki/common-pixhawk-overview/
PX4: http://copter.ardupilot.com/wiki/common-px4fmu-overview/

If you're using a Pixhawk I'm certain that current monitoring is working.

**Comment by kallaspriit** [comment]
I'm using the older PX4FMU+PX4IO combination.
