### ISSUE TITLE
integrating mission planner with Network simulation

### ISSUE THREAD

**Issue by werkineh** [ArduPilot/ardupilot#6532]
I MSc. student in Computer Networking. by now am doing my thesis on a supersonic speed flying ad hoc network. in my thesis, I propose that the aircraft will exchange their mission in Battlefield. and the mission is described as a set of waypoints or Gps coordinate that aircraft will follow for the future. my question is as follows
1: can I simulate supersonic speed flying ad hoc network in mission planner 
2: can I integrate it with networking simulator software such as ns2 and ns3 like taking mission plan data to ns2 or3?
please help me it is urgent. I only have two months for implementation

**Comment by OXINARF** [comment]
Besides this not being the [Mission Planner repository](https://github.com/ArduPilot/MissionPlanner), this issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/MissionPlanner).
