### ISSUE TITLE
Add support for High-G accels

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#6537]
Some applications would like to measure high-G (>50G?). Don't necessarily need to navigate using this accel, but would like to at least log it and stream it over mavlink.

**Comment by WickedShell** [comment]
Isn't this a hardware issue not anything code wise? (Or at least primarily a hardware one first?)

**Comment by magicrub** [comment]
yup. I added the driver label. This is a TODO item.

**Comment by WickedShell** [comment]
My point being that it's not a driver issue until someone has a hardware board that we could actually measure this on?

**Comment by proficnc** [comment]
Will be using the ICM20649 on the upcoming Cube Red. It's 30G... if someone wants to preempt this and write a driver, that would be appreciated :)

**Comment by magicrub** [comment]
@WickedShell I anticipate someone working on this soon, I'll let him chime in when he's ready. He has hardware for an accel that goes up to 400G. Accel only, no gyro. e wants it as a ride-along sensor.

**Comment by WickedShell** [comment]
Well never mind, there ya go just drivers.

**Comment by magicrub** [comment]
@proficnc great news! See @WickedShell , this is why I made an issue for it.. to start a discussion :)

**Comment by peterbarker** [comment]
We support the ICM20649.

There's something else we support with a higher range than that.

I'm closing this as I think a new issue requesting support for specific sensors would make sense - otherwise we've got a "length of string" problem.
