### ISSUE TITLE
MAVLink rangefinder use id number

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#6540]
#### Issue details
Currently we update all mavlink rangefinder type each time a distance sensors message arrived. We should only update if the instance number match the id 

Maybe also drop old message ?

**Comment by Ridhwanluthra** [comment]
hey i would like to work on this, please tell me what is to be done

**Comment by peterbarker** [comment]
@Ridhwanluthra Looks like we need an additional check here: https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_RangeFinder/AP_RangeFinder_MAVLink.cpp#L55 that the incoming message is, indeed, for this backend.

However, @khancyr will have to help here - as he owns this issue ATM!

**Comment by IamPete1** [comment]
@khancyr I wonder if https://github.com/ArduPilot/ardupilot/pull/18513 would be sufficient to close this?

**Comment by IamPete1** [comment]
@khancyr I think we can close now?
