### ISSUE TITLE
High pitch down right at VTOL_TAKEOFF in AUTO mode

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#6543]
#### Issue details
Right when switching to AUTO mode, with VTOL_TAKEOFF being the first command, the X8 motors start but it seems like the rear ones are revving up much quicker and this ends up sending the vehicle into a high pitch down attitude (> 90 deg).

Flying the vehicle in QSTABILIZE just before worked fine.

The vehicle is pretty overpowered (flying empty without payload for now).  Params are in the logs (see below) but I had seen this behavior the flight just before and dialed down the following: Q_ACCEL_Z, Q_VELZ_MAX, Q_VZ_{P,I,D}, Q_AZ_{P,I,D}.  Didn't help.

@peterbarker @tridge @WickedShell ?

#### Version
ArduPlane 3.7.1.

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover

#### Airframe type
X8 octo quadplane.

#### Hardware type
PixHawk 2.1

#### Logs
DF logs: https://drive.google.com/open?id=0B9UhUyOiU9LpM0Q0ZjNGaGtsVzQ

**Comment by peterbarker** [comment]
On Wed, 5 Jul 2017, expntly wrote:

> Right when switching to AUTO mode, with VTOL_TAKEOFF being the first command, the X8 motors start but it seems like the rear ones are revving up much quicker and this ends up sending the vehicle into a high pitch down attitude (> 90 deg).

It looks like you might have lost power on C6.  ESC sync, perhaps?

**Comment by expntly** [comment]
Can you tell by looking at RCOU.C6 or elsewhere?  C6 and C9 PWM's are way up in the logs.

Also not sure what you mean by ESC sync?

Thanks

**Comment by expntly** [comment]
@peterbarker -- Is there a way we could throttle down the ramp up in PWM sent to the VTOL motors at take off?  e.g. instead of going from 0 to 90% throttle in 500ms, do it in 2s?

**Comment by magicrub** [comment]
I think this was previously reported and already fixed in v3.8beta but can't find the issue to look here. Are you able to test on the beta and report back?

**Comment by expntly** [comment]
@magicrub Any idea which commit(s) or github issue #?  This has caused a lot of damage in a few instances where the vehicle actually flipped over.

**Comment by magicrub** [comment]
Seems related to these: https://github.com/ArduPilot/ardupilot/issues/6046 and https://github.com/ArduPilot/ardupilot/issues/5335 which are still open

**Comment by expntly** [comment]
@magicrub Definitely not related to #5335 (which I authored) :-).  The other issue also seems unrelated I think, this is QRTL specific stuff I've seen before.

Would limiting Q_THR_MAX_PWM help when the vehicle is overpowered?

**Comment by IamPete1** [comment]
sounds like this has been fixed, if not a 4.1 log of this issue will help us diagnose.
