### ISSUE TITLE
Ardupilot + only RPi Zero (W) 

### ISSUE THREAD

**Issue by karu2003** [ArduPilot/ardupilot#6548]
Hello,

I'm a beginner in the world Ardupilot and I want to start with a simple one.
Help me make configuration for a very simple Ardupilot + RPi Zero (Linux).
I have only RPi Zero. I want to use PPM_in on GPIO4, i have two motors.
I will use PWM (RCOutput) on GPIO12 and GPIO13. 

Thanks for the help.
Andrew.

**Comment by hiro2233** [comment]
Hello, try to test with urus board, this one have the input ppm and gpio in/out enabled onlt enabled. Tested with RPi B+, but this should work for RPi Zero. For now it's in development.

**Comment by karu2003** [comment]
Thank you,

I found in HAL_Linux_Class.cpp for RCInput. But, I can not find it for RCOutput.

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

I suggest you start by reading the developer wiki: http://ardupilot.org/dev/index.html
I have to say that starting by adapting to a new board isn't certainly a simple one.

**Comment by rmackay9** [comment]
Here is the list of flight controller boards we support. http://ardupilot.org/copter/docs/common-autopilots.html

For RPi2 or RPI3, the NAVIO2 is my personal favourite.
