### ISSUE TITLE
Rover: wiki updates for new version

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#6582]
#### TODO :
[  ] PWM type
[  ] New skid steer
[  ] Motor test
[  ] Wheel encoder
[  ] Proximity
[  ] Fence
[  ] Avoidance
[  ] New rangefinder

**Comment by rmackay9** [comment]
My feeling is we can probably close this issue now. We've updated the wiki quite a bit.. for the most part, the bits that haven't been updated (proximity, etc) haven't been implemented in Rover-3.2.

**Comment by khancyr** [comment]
yep agree, thanks you having doing that!
