### ISSUE TITLE
AP_Proximity: add MIN and MAX valid distance values

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#6583]
Following  #6452

Zero value is to much limited......
It must be better to add as for the RNGFND, min and max value filtered by for example:
PRX_READ_MIN
PRX_READ_MAX.
Like this each one can set it as it wants for improve integration.
and if value is below MIN or above MAX, copter use the last readed value waiting new value entering between MIN and MAX.

**Comment by rmackay9** [comment]
Here is a related issue: https://github.com/ArduPilot/ardupilot/issues/8958

**Comment by peterbarker** [comment]
Each backend is responsible for reporting distance-min and distance-max in the proximity sensor library.

Do we really need more parameters to override the backend's idea of what its limits are?

**Comment by rmackay9** [comment]
@peterbarker, yes, I think we do unfortunately.  It keeps coming up in the forums that people want to limit the minimum range so that close obstacles that are actually on the vehicle are ignored.  The maximum range is also requested sometimes I think.

**Comment by peterbarker** [comment]
On Thu, 29 Jul 2021, Randy Mackay wrote:

> @peterbarker, yes, I think we do unfortunately. It keeps coming up in the forums that people want to limit the minimum range so that close obstacles that are actually on the vehicle are ignored. The maximum range is also requested sometimes I think.

The "ignore zones" aren't enough for the short zones?

**Comment by peterbarker** [comment]
We have MIN and MAX parameters now in Proximity.
