### ISSUE TITLE
AC 3.5rc8 PRECISION GPS2 RTK position big offset with POS

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#6584]
Hello,

I test precision survey with NOVATEL RTK dual frequency GPS, and I found that copter offset POS by 60cm regarding GPS2.
[2017-06-20 15-13-40.zip](https://github.com/ArduPilot/ardupilot/files/1141664/2017-06-20.15-13-40.zip)

Main error is in Z axis. 

Could we make sure that when GPS2 is in RTK FIX state, EKF use GPS RTK ALT ?

But I also see error on X and Y by more than 15cm with POS regarding GPS2 (RTK)

Maybe I make mistake entering GPS_POS2_X GPS_POS2_Y GPS_POS2_Z ?
Centroid of antenna is centered with CG, but it's 20cm above the CG, so following documentation I set GPS_POS2_Z à -0.2m ?

it's ok or there is the mistake ?

You will find attached the log.

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).

I can't answer a lot of your questions, without understanding why you are using GPS2. Please post in the forum with more details on what you are trying to do.
