### ISSUE TITLE
Copter: mode at start-up determined by TX/RX flight mode switch

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#660]
This will be a problem if the user is not using a TX/RX because the flight mode will be initialised to the flight mode corresponding to channel 5's default input (i.e. 0 in case of ppmsum, or 1555 in case of APM2 with ppmencoder attached).

Perhaps we should default to Loiter if there is no TX/RX.

**Comment by R-Lefebvre** [comment]
I think this should be forced to Loiter if there is no RC Input (Ch5 should be zero, at least in the case of my hardware? I'm not sure what happens in all cases?) Regardless of other hardware, if Ch5 is zero, then it's safe to assume the RCTx is not turned on, and mode should be forced to Loiter.  Agree?

**Comment by rmackay9** [comment]
@R-Lefebvre, Apparently >1 year ago I also thought Loiter was a decent idea (see above).  Another option would be to create a new "uninitialised" flight mode and force the GCS to switch the flight mode to whatever it wants to use to take-off.

I sort of think that Loiter is another pilot-controlled flight mode and if we're moving away from rc-overrides, I'm not sure it makes sense to use Loiter if there's no TX/RX.  In some ways, Guided would make more sense.

**Comment by magicrub** [comment]
Rover has this issue called INITIAL_MODE
http://rover.ardupilot.com/wiki/apmrover2-parameters/#initial_driving_mode_apmrover2initial_mode

**Comment by rmackay9** [comment]
Pushed to AC3.4.

**Comment by R-Lefebvre** [comment]
Randy, we still thinking that it should default to Loiter, or should it be settable via param?

**Comment by salonijain12** [comment]
@rmackay9 and @R-Lefebvre, please suggest if the approach is being decided ? 
Do we need to create a new param (INITIAL_MODE) and a new flight mode "uninitialised" at startup  as in case of rover and handle the case when receiver is not present, or should we default it to any other mode if  receiver is not present.

**Comment by rmackay9** [comment]
Pushing to Copter-3.5.  We're simply out of time for AC3.4.

**Comment by Naterater** [comment]
I think INITIAL_MODE still needs to make its way to copter as it already exists on plane.

**Comment by IamPete1** [comment]
We now have `INITIAL_MODE` on all vehicles
