### ISSUE TITLE
Copter: cannot access ch7/ch8 options through tablet

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#661]
Many auxiliary functions such as enable/disable sonar, fence, autotune, etc are accessible only through the auxiliary switches ch7/ch8 which are only available through the TX/RX.

We probably need to create some mavlink messages to allow access to these additional features.

**Comment by auturgy** [comment]
Is any of this still outstanding? @rmackay9

**Comment by rmackay9** [comment]
I haven't heard people ask for this in a few years so perhaps we can close it.
