### ISSUE TITLE
Rover: remove Alt requests when planning a mission

### ISSUE THREAD

**Issue by ncx94** [ArduPilot/ardupilot#6632]
#### Issue details
When planning a mission on MP, or adding a waypoint, it always asks for an altitude.. Althoughthis is fine on a plane or copter, it makes no sense on a rover.. Maybe there could be a way to get mission planner to change the request when a rover is connected?

#### Version
maste
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover

**Comment by OXINARF** [comment]
This looks like a request for Mission Planner, which should be at https://github.com/ArduPilot/MissionPlanner/issues, not here.

Feel free to comment if I'm mistaken and I'll reopen..
