### ISSUE TITLE
Compass offsets too high Problem

### ISSUE THREAD

**Issue by Ahrovan** [ArduPilot/ardupilot#6638]
#### Issue details
Compass offsets too high occur always with internal compass sensor ( z value are larger than 500), but when add external compass and re calibrate, in this case internal compass calibrate true (with true offsets value) but external compass say "Compass offsets too high Problem , z value are larger than 500".
#### Version
Copter-3.5.0
#### Platform
[*] Copter - Quad PX4v3 
#### Logs
[3 1-1-2000 1-57-42 PM.bin.zip](https://github.com/ArduPilot/ardupilot/files/1165038/3.1-1-2000.1-57-42.PM.bin.zip)

![image](https://user-images.githubusercontent.com/5772832/28461849-c9bd7a1a-6e2d-11e7-8ce1-64d87da2343b.png)

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
