### ISSUE TITLE
Add 4 wheel steering to the ArduRover2 firmware

### ISSUE THREAD

**Issue by TC3** [ArduPilot/ardupilot#664]
Hi Tridge,
A rover user has requested that 4 wheel steering be added to the ArduRover2 code. He wants to be able to steer the rear wheels on a rover without having to add a servo reversing cable to do so.
Regards,
Tom C ArduRover2 Developer

**Comment by gmorph** [comment]
Rob, are you going to look into this or should I take it?

**Comment by OXINARF** [comment]
According to @gmorph, Rover can now be configured to do this, so I'm closing it. If you have any difficulty setting it up, please use our forum (http://discuss.ardupilot.org).
