### ISSUE TITLE
Mission Planner - compass Live calibration button not activated

### ISSUE THREAD

**Issue by ThomasH3** [ArduPilot/ardupilot#6648]
#### Issue details
I've tested Mission planer 1.3.48 and 1.3.49 - FW 3,49 and 3,50
for options compass calibration button (Live Calibration) is deactivated in Mission Planner
Pic attached 

#### Version
MP 1.3.48 + 1.3.49
FW 3.4.9 + 3.5
#### Airframe type
y3 + x

#### Hardware type
Pixracer, PX4
[calibration.docx](https://github.com/ArduPilot/ardupilot/files/1167146/calibration.docx)

**Comment by OXINARF** [comment]
This isn't the Mission Planner repository so this doesn't belong here. But to answer your problem, live calibration isn't shown on purpose, you should use the better onboard calibration.
