### ISSUE TITLE
Copter: Support different motor speeds for upper/lower motors

### ISSUE THREAD

**Issue by arnoldpycho** [ArduPilot/ardupilot#665]
The Problem is, that the Efficiency with a x8 copter is bad if you run the upper Motors(Motor 1-4) und the lower Motors(Motor 5-8) at the same rpm. With the x8 configuration you have different loads on the upper and lower Levels. To avoid that, you have to run the lower Motors with about 10% more rpm than the uppers ones.

Is there a possibility to adust the rpms?

**Comment by Naterater** [comment]
I think this is something that's a bit old, and I haven't seen many requests for this recently. As such, I believe this issue should be closed unless there is significant data backing the request.

**Comment by rmackay9** [comment]
I got another request from a user two days ago to add this so I think we should leave it open.  Even though nobody is rushing to implement it, it at least provides a blackboard for people to write, "I'd like this too!".

**Comment by IamPete1** [comment]
This is now possible via the setting of throttle factors from the scripting matrix backed. We don't have a example but it is very straight forward. One would copy the motor setup from `c++` and put it into a script like this one:

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/MotorMatrix_fault_tolerant_hex.lua

Then before the init use:
```MotorsMatrix:set_throttle_factor(motor_num, throttle_factor)```

Where the throttle factor would be 1 for the lower motor numbers and 0.9 for the upper motors.

**Comment by rmackay9** [comment]
@IamPete1,

I think we shouldn't be too aggressive about closing all requests that "could be done with scripting" unless we're also providing a script because not everyone is capable of making their own Lua programs.  Another alternative is to leave it open and suggest an implementation could be done in scripting just like it could be done in C++.

I guess my point or question is, are we going to close every enhancement request that could be done in scripting even though there's no script that people could actually use?

**Comment by IamPete1** [comment]
@rmackay9 I don't see much point in doing generic example scripts that will get no testing, I'm happy to help someone set this up if there is interest, then we can have a proven example. This one is really not that far from the examples we do have. 

I think that in the case that it is supported by scripting and scripting is the best solution then we should close. The point of scripting is to stop us having to implement all these odd ball cases in c++. 

If something is technically possible in scripting, but is a bit of a hack then the issue should remain. 

I guess the real solution here would be to have a separate example scripts repo, where people could ask for examples, along with some nice instructions to get people started. We could then keep the AP examples repo to a clean and basic example of each binding.
