### ISSUE TITLE
Copter: improve GPS Glitch handling and reporting

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#6650]
With Copter-3.4.6 (or was it 3.3?) we moved the GPS glitch detection into the EKF.  The EKF certainly handles glitches better than the older inertial nav ever could but we've lost some reporting to the pilot.

We should add:

- [x] pre-arm check that the GPS isn't glitching
- [x] dataflash logging whenever a glitch occurs
- [ ] failsafe to allow momentary switching to AltHold if in Loiter, PosHold, etc.

**Comment by OXINARF** [comment]
Related to #6063. I think @priseborough has a good idea there with AHRS providing an error estimate of position and velocity, then vehicles can decide what to do based on that.

I think that going back to a specific GPS glitch failsafe isn't the best idea, but a position failsafe would certainly be worthy - the reason being that we can lose GPS but still have good position estimate if, for example, we have optical flow installed.

Also, I'm not sure about backporting this to 3.5, I think it needs quite a bit of testing before putting it in a stable release.

**Comment by peterbarker** [comment]
I've updated the initial post for this one as we have 2 of the three items done.

Haven't got custom GPS-glitch failsafe actions yet.

**Comment by rmackay9** [comment]
AltHold is an option in FS_EKF_FAILSAFE so I think we can close this.
