### ISSUE TITLE
Plane, vectored Tailsitter, Q_M_THST_HOVER has no effect in Q_STABILIZE

### ISSUE THREAD

**Issue by lorbass** [ArduPilot/ardupilot#6652]
#### Issue details
In mode Q_STABILIZE the parameter Q_M_THST_HOVER has no effect on the thrust output.
e.g. even with 0.8 (80%) Ch5out and Ch6out has 1500 ppm  while Ch3in has 1500 (Stick mid Position)
instead of 1800.
This makes the mode change form Q_STABILIZ to Q_HOVER and back difficult.

![issue a_m_thst_hover](https://user-images.githubusercontent.com/7657148/28510438-bbf8b71a-7048-11e7-81da-a046dccb37dd.jpg)

#### Platform
Plane

#### Airframe type
Wing, belly sitter, vectored Tailsitter
#### Hardware type
Pixracer v4

**Comment by tridge** [comment]
indeed, Q_M_THST_HOVR is not expected to do anything in QSTABILIZE. It is only used when we are in an altitude hold mode.
We could add input curves in quadplanes, but I'm not totally sure we want to, especially with hover learning. If it learnt a bad hover value then it could become hard to control

**Comment by tridge** [comment]
I'll close as this is expected behaviour

**Comment by lorbass** [comment]
Thank you for this expanation. Otto
