### ISSUE TITLE
ArduSub compile error: 'class GCS' has no member named 'send_message'

### ISSUE THREAD

**Issue by itayguy** [ArduPilot/ardupilot#6679]
#### Issue details
 error: 'class GCS' has no member named 'send_message'
ArduSub/GCS_Mavlink.cpp:11:11: 

#### Version
.dev
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[X] Sub

**Comment by jaxxzer** [comment]
Builds for me, and https://travis-ci.org/ArduPilot/ardupilot/builds/257295368. Try `make clean` and `make px4-clean` from the ArduSub directory.

**Comment by itayguy** [comment]
px4-v2

**Comment by peterbarker** [comment]
On Fri, 28 Jul 2017, itayguy wrote:

> px4-v2

Unable to replicate.

Please try doing a "make px4-clean" and retry.

If using waf, please execute a "waf clean" and retry.

If it still fails - what git hash are you trying to compile?

**Comment by itayguy** [comment]
it works thanks!
