### ISSUE TITLE
Copter: Loiter velocity doesn't increase fast enough when WPNAV_LOIT_SPEED = 7000

### ISSUE THREAD

**Issue by lthall** [ArduPilot/ardupilot#670]
We need to test this in the simulator. It appears like the deceleration is correct but the desired velocity doesn't increase fast enough. We can't work out why.

Logs here:
https://groups.google.com/group/drones-discuss/attach/64fe6d21206034c2/2013-11-04%2019-36%2015.log?part=4&authuser=0

**Comment by gmorph** [comment]
Any chance you can re-test?

**Comment by R-Lefebvre** [comment]
@lthall is this still open?

**Comment by OXINARF** [comment]
@lthall Is this still valid?

**Comment by lthall** [comment]
This can be closed as I am rewriting loiter for the next release anyway.
