### ISSUE TITLE
Copter/QuadPlane: parameter to define the motor ramp curve speed during takeoff

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#6724]
#### Issue details
For automatic takeoff during AUTO/PosHold/Alt-Holde/Loiter flight mode, in some configurations it would be necessary tune better the ramp speed curve of the motors, 
During this phase the Alt-Hold intertial controller comes into play, and with some hardware setup doesn't work very well, sometimes the drone takes off too fast and tilted.
And some ESCs don't like a pwm ramp too fast, some go to desync.
So what I think is missing is a parameter to define the speed curve of this ramp when the drone is already armed at the "min throttle" and breaks out of the ground, or a better management of the Alt-Hold controller, even in the land phases.
"MOT_SPOOL_TIME" and "MOT_SPIN_ARM" don't solve the problem, they have to act on something else, not in what I mean.

#### Version
Copter V3.5.1
Plane V3.8.0 RC6

#### Platform
[ x ] Copter
[ x ] QuadPlane

#### Airframe type
Is irrelevant

#### Hardware type
Is irrelevant

#### Logs
Available on request, also video documentation

**Comment by robustini** [comment]
Please @OXINARF can you add also the "Copter" label to this issue?
Thanks!

**Comment by OXINARF** [comment]
@robustini Done 🙂

**Comment by lvale** [comment]
discussed this with @robustini.

**Comment by robustini** [comment]
Thanks @lvale!

**Comment by tridge** [comment]
Why isn't MOT_SPOOL_TIME what you want?

**Comment by robustini** [comment]
Because "MOT_SPOOL_TIME" is the time in seconds to spool up the motors from zero to min throttle, and not "min throttle to takeoff throttle".

**Comment by tridge** [comment]
> Because "MOT_SPOOL_TIME" is the time in seconds to spool up the motors from zero to min throttle (MOT_SPIN_ARM), and not "min throttle to takeoff throttle".

its actually both. It controls both the rise time to the min throttle, plus also a rise time from there to full throttle control. 
Here is a graph of a LOITER takeoff on a quad with MOT_SPOOL_TIME=5
![mot_spool_time_5](https://user-images.githubusercontent.com/831867/30301278-1a5a7bce-979d-11e7-9928-87459e8eba31.png)
you can see the initial 5 second ramp to min throttle, then a subsequent ramp (also of 5 seconds) to full throttle.

**Comment by tridge** [comment]
the documentation does need an update though

**Comment by tridge** [comment]
on the call we discussed adding a MOT_SPOOL_TIME_H, default to 0. If it is zero it uses the MOT_SPOOL_TIME (so current behavior). Otherwise it controls the 2nd half of the ramp

**Comment by robustini** [comment]
Thanks Andrew, i wait the new parameter!

**Comment by robustini** [comment]
@tridge, no news about that?

**Comment by maciek01** [comment]
Hi . Any update on this? I have the same issue. Motors spool up fine in stabilized mode but in any of the autonomous modes mentioned above 4 out of 6 ESCs are desyncing and motors shut off.
The only way I can use loiter is takeoff in stabilized then switch the mode. Things were fine with xrotor hobbywing 40a. Then I switched to 50a red bricks (https://www.banggood.com/Red-Brick-50A-ESC-Brushless-ESC-OPTO-NO-BEC-50AOPTO-p-77969.html?utm_design=41&utm_source=emarsys&utm_medium=Shipoutinform171129&utm_campaign=trigger-emarsys&utm_content=Winna&sc_src=email_2671705&sc_eh=19ca7d4d939002cd1&sc_llid=7184001&sc_lid=104858042&sc_uid=mWbUCsvi4i) and started facing this issue.

**Comment by chobitsfan** [comment]
> its actually both. It controls both the rise time to the min throttle, plus also a rise time from there to full throttle control.
Here is a graph of a LOITER takeoff on a quad with MOT_SPOOL_TIME=5

I tested it with current master, CubeBlack, arm and takeoff in guided mode, MOT_SPOOL_TIME = 3

![Log Browser - 2022-07-08 10-28-02 bin - ArduCopter V4 3 0-dev (717a7291) 2022_7_8 下午 01_45_12](https://user-images.githubusercontent.com/19793511/177925561-2e2b0b7d-d601-48e4-b339-feb2eea43480.png)

It takes 3 sec to min throttle, but only 1 sec to full throttle. I look at code and it seems MOT_SPOOL_TIME is only use in SPOOLING_UP stage ?

**Comment by lthall** [comment]
I didn't know about his issue but this is my next development project is to specifically handle the transition between landed and flying. The plan is to provide a throttle ramp time and then detect the moment we start to climb and then switch to the Alt_Hold controller for vertical control.

This will give the users direct control over the take-off transition. It will also handle variable take off weight more elegantly. Finally and most importantly it will mean the take-off behaviour is independent of the vertical height controllers.

**Comment by lthall** [comment]
This is the pull request that should resolve this issue if anybody wants to take a look. #21158

**Comment by lthall** [comment]
I think this has been addressed and merged. We can open it again if I am mistaken.
