### ISSUE TITLE
UAVCAN: Hangup upon unknown message

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/ardupilot#6762]
#### Issue details
It seems that when there is a UAVCAN message on the CAN bus which is not known by ArduPilot, then it hangs up.

#### Version
AC3.6-dev

#### Platform
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover
but probably valid for all airframes

#### Airframe type
IMHO irrelevant

#### Hardware type
IMHO irrelevant, but seen on pixracer, AUAV-X2 with DIY can

**Comment by EShamaev** [comment]
Please provide more information on what exact message lead to hangup.
I did tests with different messages not processed by AP and none hangs up.
Also please specify the version of AP that you use for that (Commit number)

**Comment by EShamaev** [comment]
@olliw42 can the problem be reproduced?

**Comment by EShamaev** [comment]
Tested with many messages that are not known to AP and was not reproduced.
If the answer is provided - can be reopened.
