### ISSUE TITLE
Autotest manifest files broken

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/ardupilot#6767]
The [firmware-version.txt](http://firmware.us.ardupilot.org/Plane/latest/PX4/firmware-version.txt) files say
`Unknown vehicle (.) (be in a vehicle directory or supply a vehicle type as an argument)`

Also, there used to be a line at the bottom of git-version.txt that said `APMVERSION...` and that is not there anymore. QGC uses these APMVERSION lines to parse the available fws to flash, so some of them (stable Copter or any Vehicle on master) are unavailable for download in QGC for now.

http://firmware.us.ardupilot.org/Plane/stable/PX4/ has the APMVERSION line in git-version.txt
where 
http://firmware.us.ardupilot.org/Copter/stable/PX4/ does not, so it would seem the change was introduced sometime between Aug 5 and 14.

**Comment by peterbarker** [comment]
Incidentally, these aren't the manifest files; that's manifest.xml :-)

**Comment by peterbarker** [comment]
... or is it json? ;-)

**Comment by jaxxzer** [comment]
Where is manifest.xml? Also, I don't get the insinuation, sorry. Is it relevant?

**Comment by jaxxzer** [comment]
[From what I can tell](https://github.com/ArduPilot/ardupilot/blob/master/Tools/scripts/build_binaries.sh#L154) we should still be adding the version info in the locations I mentioned.

**Comment by peterbarker** [comment]
Quick update.
 - I've fixed the corruption on the server.
 - I've pushed in two commits to try to stop it happening again

More corruption may occur until we get past my commits.

**Comment by peterbarker** [comment]
http://firmware.ardupilot.org/manifest.json.gz is supposed to be a one-stop shop for working out what can be downloaded in terms of ArduPilot *stuff*

"insinuation"?  I just forgot it was JSON rather than XML...

We *should* be adding the information to those files.  But we had a few bugs...

**Comment by jaxxzer** [comment]
Ok, thank you. This is the first I have seen the manifest.json. cool.

**Comment by OXINARF** [comment]
@jaxxzer This should be fixed, have you checked everything is working?

**Comment by jaxxzer** [comment]
Looks good.
