### ISSUE TITLE
ROS waypoint navigation for ardupilot with apm

### ISSUE THREAD

**Issue by medhijk** [ArduPilot/ardupilot#6778]
Hi,
I am having trouble sending waypoints through ROS commands to the arducopter. I followed the instructions to connect ardupilot with ROS from [ROS with SITL](http://ardupilot.org/dev/docs/ros-sitl.html). I launched my copter session using 
`sim_vehicle.py -v ArduCopter --console --map`
To connect mavros to SITL, I did
`roslaunch apm.launch`
Now I need to give waypoints to the copter using ROS messages. I know I can load the waypoints using `wp load ../Tools/autotest/ArduPlane-Missions/CMAC-toff-loop.txt` as described in an example in ardupilot documentation but I want to send the coordinates through ROS commands and not through a text file. Can anyone tell me how to do it? I am using ROS indigo on ubuntu 14.04

**Comment by khancyr** [comment]
Hello,
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
But about your question see : http://wiki.ros.org/mavros#mavros.2BAC8-Plugins.waypoint
