### ISSUE TITLE
Feature request: use aux pin relay out for led and buzzer

### ISSUE THREAD

**Issue by geofrancis** [ArduPilot/ardupilot#6846]
The way the old APM would drive it's external leds and its buzzer was very useful, since it was just a pin going high/low you could make it run any kind or colour of lights you want using an external driver. 

The pix hawk has relay pins that very few people use so why not allow them to be used for driving buzzers and leds like an APM.

**Comment by sashan13** [comment]
Totally agree. I guess it may also be possible to reconfigure ADC pins as output?

**Comment by 007trains** [comment]
Has anyone looked into this? I'd like to be able to trigger a relay in on my plane. Similar to the ch7, ch8 aux funtions in Arducopter

**Comment by peterbarker** [comment]
@007trains You should already be able to use those channels for relays on Plane.  Looks for the RELAY* parameters.

My PR to clean up the buzzer sequence code enables use of the buzzer (as opposed to the "tonealarm" you usually hear on a PixHawk) on all platforms: https://github.com/ArduPilot/ardupilot/pull/9534

**Comment by 007trains** [comment]
@peterbarker Ah i see what you mean, i guess my issue is more like #7071, i have setup the servox_function to relay but cannot set RCn_OPTION as it does not appear in the parameters list

**Comment by peterbarker** [comment]
We allow setting this stuff through auxillary pins on stm32 hardware in the hwdef files.
