### ISSUE TITLE
Copter: compilation failed

### ISSUE THREAD

**Issue by zhangwunian** [ArduPilot/ardupilot#6876]
#### Issue details
when I compile my code(copter-3.4.6),the following error occurred,but I can not  found include/mavlink/v2.0 directory, Who can tell me where it is?  Or what's the cause of the problem?  thanks a lot!!

copter-3.4.6-0901/libraries/GCS_MAVLink/GCS_MAVLink.h:25:56: fatal error: include/mavlink/v2.0/ardupilotmega/version.h: No such file or directory

#### Version
copter-3.4.6

#### Platform

Copter

#### Airframe type
hex

#### Hardware type
pixhawk

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot). Wherever you ask for help you have to give more detail, you don't say how you are building, on what OS, etc.
