### ISSUE TITLE
How to put two drones in one Gazebo simulation?

### ISSUE THREAD

**Issue by cnpcshangbo** [ArduPilot/ardupilot#6887]
Hello guys,
I have went through some tutorials to run a Gazebo simulation with a drone in it.
However, what I need is to have two drones in one Gazebo simulation and use two ROS to control it. In the control part I am going to use MATLAB Robotics System Toolbox to communicate with the two drones.
Anybody has some ideas on how to finish that two drone simulation?
Thanks,
@cnpcshangbo

**Comment by lvale** [comment]
Support questions should go to discuss.ardupilot.org.

Thanks
