### ISSUE TITLE
Copter: allow start and end alt to Loiter Turns command

### ISSUE THREAD

**Issue by TheMightyThor1212** [ArduPilot/ardupilot#689]
"Warning #4: loiter turns does not maintain altitude.  This bug will be fixed in AC-3.0.2." is a Bug, 

is there any chance altitude params can be added to that function?
I am thinking how useful it would be if i could Send params that says Start at this Altitude, then End at this Altitude, Always point nose to the Way Point Center..

I am asking this because as a camera person, I would find this a very cinematic shot.
If those params arent changed, it would just circle at its current altitude.  if it cant be done, i understand, i am sure you have more pressing issues, i was looking for a script for this but thats harder to find than to ask this question.

**Comment by hiro2233** [comment]
@rmackay9 it has yet implemented on the lastest AC version.

@TheMightyThor1212 Thank you very much for your colaboration.

**Comment by jmachuca77** [comment]
Can this be accomplished by the loiter to alt command and the set condition yaw? I believe those are both now implemented and would solve this issue. I'll wait a few days for comments and if there is no contest I'll close this issue.
