### ISSUE TITLE
Add code to Waf list

### ISSUE THREAD

**Issue by OscarJGV26** [ArduPilot/ardupilot#6894]
#### Hardware type
Linux - Beaglebone Blue

Hi there,

This is something probably very very simple but I just don't know how to do it since I have no clue what exactly is ./waf doing. 

I just want to know what do I need to do to add to the waf list a code of my own that I want to execute. 

For example, I modified an example code, say example/Printf which is in /libraries/AP_HAL/examples.... to do what I want. And now, it does absolutely nothing related to printing but what I want my actual code say main.cpp to do.... 

So... how to add my main.cpp code which currently compiles correctly in example/Printf to the waf list? And where can I put this code... 

I mean I can keep doing it like this, but I would just like to know.

Regards,
Oscar

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).
