### ISSUE TITLE
AC3.5 Upgrade proximity driver

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#6898]
Zero value filter is not enough.....
It must be better to add as for the RNGFND, min and max value filtered by for example:
PRX_READ_MIN
PRX_READ_MAX.
Like this each one can set it as it wants for improve integration.
and if value is below MIN or above MAX, copter use the last readed value waiting new value entering between MIN and MAX.

**Comment by OXINARF** [comment]
What driver needs this? Why do we need to have MIN/MAX if all drivers know the min/max distances the device supports?

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/6583
