### ISSUE TITLE
Add libraries to the ardupilot building/compiling commands....

### ISSUE THREAD

**Issue by OscarJGV26** [ArduPilot/ardupilot#6900]
#### Hardware type
Linux - Beaglebone Blue

I would like to know how can I add libraries to the building/compile/make/waf (whatever) commands of ardupilot. In my previous post I mentioned about my code not compiling because of missing -lrt, but now I am thinking about adding roboticscape.h or other libraries of my own. 

I am thinking just by adding them to the libraries folder in ardupilot won't work but I might be wrong.

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).
