### ISSUE TITLE
Unable to compile external library that has already been tested succesfully.

### ISSUE THREAD

**Issue by OscarJGV26** [ArduPilot/ardupilot#6901]
#### Hardware type
Linux - Beaglebone Blue

I am having problems compiling a library of my own that I added to the libraries folder of the ardupilot. 

The error I am getting is,

[477/835] Compiling libraries/MPC/GetSS.cpp
../../libraries/MPC/GetSS.cpp: In function ‘void GetSS(const float*, const int*, const float*, const int*, float*, int*, float*, int*, float*, int*)’:
../../libraries/MPC/GetSS.cpp:120:64: error: array subscript is above array bounds [-Werror=array-bounds]
       A[(i1 + b_result) + 5 * i0] = varargin_2_data[i1 + i * i0];
                                                                ^
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors

This library has already been tested outside the ardupilot libraries folder with the following makefile where the target Main.cpp includes the MPC library that I am trying to execute, and the MPC library includees all the other libraries such as, in this case, GetSS.cpp

TARGET = Main

CC		:= g++ -std=c++11
LINKER		:= g++ -o
CFLAGS		:= -c -Wall -g
LFLAGS		:= -lm -lrt -lpthread -lroboticscape

SOURCES		:= $(wildcard *.cpp)
INCLUDES	:= $(wildcard *.h)
OBJECTS		:= $(SOURCES:$%.cpp=$%.o)

prefix		:= /usr/local
RM		:= rm -f
INSTALL		:= install -m 4755
INSTALLDIR	:= install -d -m 755 

LINK		:= ln -s -f
LINKDIR		:= /etc/roboticscape
LINKNAME	:= link_to_startup_program

# linking Objects
$(TARGET): $(OBJECTS)
	@$(LINKER) $(@) $(OBJECTS) $(LFLAGS)

# compiling command
$(OBJECTS): %.o : %.cpp $(INCLUDES)
	@$(CC) $(CFLAGS) -c $< -o $(@)
	@echo "Compiled: "$<

all:
	$(TARGET)

debug:
	$(MAKE) $(MAKEFILE) DEBUGFLAG="-g -D DEBUG"
	@echo " "
	@echo "$(TARGET) Make Debug Complete"
	@echo " "

install:
	@$(MAKE) --no-print-directory
	@$(INSTALLDIR) $(DESTDIR)$(prefix)/bin
	@$(INSTALL) $(TARGET) $(DESTDIR)$(prefix)/bin
	@echo "$(TARGET) Install Complete"

clean:
	@$(RM) $(OBJECTS)
	@$(RM) $(TARGET)
	@echo "$(TARGET) Clean Complete"

uninstall:
	@$(RM) $(DESTDIR)$(prefix)/bin/$(TARGET)
	@echo "$(TARGET) Uninstall Complete"

runonboot:
	@$(MAKE) install --no-print-directory
	@$(LINK) $(DESTDIR)$(prefix)/bin/$(TARGET) $(LINKDIR)/$(LINKNAME)
	@echo "$(TARGET) Set to Run on Boot"

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).
