### ISSUE TITLE
Building for Pixhawk on Windows10 with Bash on Ubuntu,build failed

### ISSUE THREAD

**Issue by BreederBai** [ArduPilot/ardupilot#6909]
When I use ./waf compiler source code, there is an error，I use the windows10 with Bash Ubuntu：

Waf: Leaving directory `/mnt/d/code/V3.5/20170818/build/px4-v2'
Build failed
 -> task in 'bin/arducopter' failed (exit status 2):
        {task 140165176561744: cmake_build_task  -> }
['/usr/bin/cmake', '--build', '/mnt/d/code/V3.5/20170818/build/px4-v2/modules/PX4Firmware', '--target', 'b
uild_firmware_px4fmu-v2']

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

There is no error in what you posted, that just says what command failed, not why - you need to look up in the console for the error description.
