### ISSUE TITLE
[Bug] NSH sending nsh> \0x1b[K every line

### ISSUE THREAD

**Issue by whyscience** [ArduPilot/ardupilot#6913]
The latest master, here is the bug

- For cutecom
![screenshot from 2017-09-07 16-39-45](https://user-images.githubusercontent.com/3918941/30154327-2acec53c-93ec-11e7-9c92-907de9dbda6a.png)

- For SecureCRT
![screenshot from 2017-09-07 16-42-35](https://user-images.githubusercontent.com/3918941/30154330-2dc0e0f4-93ec-11e7-9d24-26db6d2fd0c4.png)

> nsh> \0x1b[K
nsh> \0x1b[K
nsh> \0x1b[K
nsh> \0x1b[K
nsh> \0x1b[K
nsh> \0x1b[K
nsh> \0x1b[Kls
/:
 bin/
 dev/
 etc/
 fs/
 obj/
nsh> \0x1b[K

**Comment by whyscience** [comment]
There is no this bug on ArduCopter v3.5

**Comment by peterbarker** [comment]
Check your terminal settings emulation settings.  This is a valid escape sequence, so it should be being displayed.

**Comment by whyscience** [comment]
However there is no such character before.
And secureCRT is Not normal

2017年9月7日 下午6:44，"Peter Barker" <notifications@github.com>写道：

**Comment by kingdwd** [comment]
you should  delet     ‘“ hal.uartF->begin(57600); ” in function "static int main_loop(int argc, char **argv) " in HAL_PX4_Class.cpp

**Comment by VikingDai** [comment]
You should delete “ hal.uartF->begin(57600); ” in function "static int main_loop(int argc, char **argv) " in HAL_PX4_Class.cpp, the driver "ttys5"  reinited

**Comment by OXINARF** [comment]
Like @peterbarker said, this is an ASCII escape sequence, you need to check your terminal settings to allow it, this isn't a bug.
