### ISSUE TITLE
VTOL Loiter Turns 

### ISSUE THREAD

**Issue by Ferruccio1984** [ArduPilot/ardupilot#6915]
#### Issue details
In Auto, using Q_GUIDED set to 1, Loiter_Turns MP command doesn't work as expected. Once the waypoint for Loiter turns has been hit, plane enters an infinite series of turns, ignoring the preset loiter center point, turn radius and direction.
I observed that the turning radius seems strictly related to the bank angle the plane has when it hits the loiter_turn wp, and it doesn't continue the mission, enters a sort of CIRCLE_MODE. 
The Loiter_turns works as expected, instead, if the Q_Guided is set to 0, but then we lose the ability to smooth hover transitions during auto missions.
Regards

#### Version
3.7.1 and 3.8

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
plane converted to VTOL

#### Hardware type
Pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
looks like this has been fixed by https://github.com/ArduPilot/ardupilot/pull/13545
