### ISSUE TITLE
Copter: Ch7/Ch8 switch to allow different features at middle and top

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#694]
This request is from Marco, Gary and perhaps some others to allow individual and separate features to be assigned to the middle and upper switch positions for ch7 and ch8.
So a random example would be to assign Sonar ON to the top position and AutoTune to the middle position.  The result would be:'
Switch at bottom: AutoTune and Sonar are off
Switch in middle: AutoTune is on, Sonar is off
Switch at top: AutoTune is off, Sonar is on

**Comment by lthall** [comment]
This is an old request and has been superseded by a lot of the button code that Tridge has done.
