### ISSUE TITLE
[Copter] Building Code with Make error

### ISSUE THREAD

**Issue by Senwe** [ArduPilot/ardupilot#6940]
#### Issue details
I've followed the intructions in the Building ArduPilot for Pixhawk/PX4 on Windows with Make page, however, whenever I run the command make px4 the code doesn't compile and the following error is shown:
make px4-v1                                                                                                             
make[1]: Entering directory `/c/Users/María/Desktop/ardupilot/ArduCopter'                                               // BUILDROOT=/c/Users/María/Desktop/ardupilot/Build.ArduCopter HAL_BOARD=HAL_BOARD_PX4 HAL_BOARD_SUBTYPE= TOOLCHAIN=NATIVE EXTRAFLAGS=-DGIT_VERSION="b1d1b512" -I/c/Users/María/Desktop/ardupilot/libraries/AP_Common/missing -DMAVLINK_PROTOCOL_VERSION=2 -DNUTTX_GIT_VERSION="2f230473" -DPX4_GIT_VERSION="0384802e" -DUAVCAN=1 -D__STDC_FORMAT_MACROS -DHAVE_STD_NULLPTR_T=0 -DHAVE_ENDIAN_H=0 -DHAVE_BYTESWAP_H=0 -DHAVE_OCLOEXEC=0 -I/c/Users/María/Desktop/ardupilot/Build.ArduCopter/libraries/GCS_MAVLink/include/mavlink -I/c/Users/María/Desktop/ardupilot/modules/uavcan/libuavcan/include -I/c/Users/María/Desktop/ardupilot/modules/uavcan/libuavcan/include/dsdlc_generated                                                       Checking modules                                                                                                        
echo "Generating MAVLink headers..."                                                                                    
Generating MAVLink headers...                                                                                           
#goto mavlink module directory and run the most recent generator script                                                 echo "Generating C code using mavgen.py located at" /c/Users/María/Desktop/ardupilot/modules/mavlink/                   
Generating C code using mavgen.py located at /c/Users/María/Desktop/ardupilot/modules/mavlink/                          PYTHONPATH=/c/Users/María/Desktop/ardupilot/modules/mavlink/ python /c/Users/María/Desktop/ardupilot/modules/mavlink//pymavlink/tools/mavgen.py --lang=C --wire-protocol=2.0 --output=/c/Users/María/Desktop/ardupilot/Build.ArduCopter/libraries/GCS_MAVLink/include/mavlink/v2.0 /c/Users/María/Desktop/ardupilot/modules/mavlink/message_definitions/v1.0/ardupilotmega.xml; if [ $? -le 0 -o $? -gt 128 ]; then echo "mavgen: success"; exit 0; else echo "mavgen: failed"; exit 1; fi      Validating c:/Users/MarÝa/Desktop/ardupilot/modules/mavlink/message_definitions/v1.0/ardupilotmega.xml                  Parsing c:/Users/MarÝa/Desktop/ardupilot/modules/mavlink/message_definitions/v1.0/ardupilotmega.xml                     Note: message DATA64 is longer than 64 bytes long (74 bytes), which can cause fragmentation since many radio modems use 64 bytes as maximum air transfer unit.                                                                                  Note: message DATA96 is longer than 64 bytes long (106 bytes), which can cause fragmentation since many radio modems use 64 bytes as maximum air transfer unit.                                                                                 Note: message REMOTE_LOG_DATA_BLOCK is longer than 64 bytes long (214 bytes), which can cause fragmentation since many radio modems use 64 bytes as maximum air transfer unit.                                                                  Note: message DEVICE_OP_READ_REPLY is longer than 64 bytes long (143 bytes), which can cause fragmentation since many radio modems use 64 bytes as maximum air transfer unit.                                                                   Note: message DEVICE_OP_WRITE is longer than 64 bytes long (187 bytes), which can cause fragmentation since many radio modems use 64 bytes as maximum air transfer unit.                                                                        Traceback (most recent call last):                                                                                        
File "c:/Users/MarÝa/Desktop/ardupilot/modules/mavlink/pymavlink/tools/mavgen.py", line 30, in <module>                   mavgen.mavgen(args, args.definitions)                                                                                 File "c:\Users\MarÝa\Desktop\ardupilot\modules\mavlink\pymavlink\generator\mavgen.py", line 91, in mavgen                 fname = os.path.join(os.path.dirname(x.filename), i)                                                                  File "c:\pixhawk_toolchain\Python27\lib\ntpath.py", line 108, in join                                                     
path += "\\" + b                                                                                                    
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)                      mavgen: failed                                                                                                          
make[1]: *** [/c/Users/María/Desktop/ardupilot/Build.ArduCopter/libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega/mavlink.h] Error 1                                                                                                     
make[1]: Leaving directory `/c/Users/María/Desktop/ardupilot/ArduCopter'                                                make: *** [px4] Error 2                                                                                                 a/Desktop/ardupilot/ArduCopter 

#### Version
3.5.1

#### Platform
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

You have the code inside your user folder which has a Unicode character (you can see the `í` being changed to a `Ý` on that log) and Python doesn't like it. My recommendation is to put the code in `C:\`, it should give you less trouble.
