### ISSUE TITLE
Once per second frame overrun introduced since Copter 3.5.2

### ISSUE THREAD

**Issue by priseborough** [ArduPilot/ardupilot#6946]
#### Summary

When logging replay data using ArduCopter master at 58dec08 it was noticed that once per second the EKF IMU input is running 3 msec late.  

<img width="843" alt="screen shot 2017-09-13 at 4 02 05 pm" src="https://user-images.githubusercontent.com/3596952/30362489-a74899aa-989f-11e7-8b58-57d9c9ea338f.png">

The same parameters and hardware setup on Copter 3.5.2 stable gives:

<img width="853" alt="screen shot 2017-09-13 at 4 03 19 pm" src="https://user-images.githubusercontent.com/3596952/30362528-cc37de38-989f-11e7-923f-aa1064d0f78d.png">

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
N/A - bench test of autopilot

#### Hardware type
Pixracer with dual UBlox GPS connected to GPS and  TELEM2 port.

#### Parameters

[param.txt](https://github.com/ArduPilot/ardupilot/files/1298422/param.txt)

**Comment by OXINARF** [comment]
Copter 3.5.2 is quite far away from master, we should figure out what is wrong, but it's possible we'll need to narrow the commit range.

**Comment by amilcarlucas** [comment]
Is this maybee the reason why PH2.1 enters "rodeo mode" when navigating in spline waypoints ?

I have [log of PH2.1 misbehaving on spline waypoints](https://github.com/ArduPilot/ardupilot/files/1333590/00000050.log) . It should always point (yaw) at the middle of the circle, but it instead it flyes fine for the first 535 seconds and after that tuns 90° off center. And @rmackay9 thinks that is not related to #6633

**Comment by peterbarker** [comment]
We're definitely not getting this any more.  Closing.
