### ISSUE TITLE
Copter: beep on radio or GCS failsafe

### ISSUE THREAD

**Issue by geeksville** [ArduPilot/ardupilot#695]
An idea for improving the APM code would be an option that automatically activates the beeper any time it doesn't have an RC or telemetry link. 

This would help people find vehicles after they are lost in high grass etc.  Just turn off your RC xmitter or your telemetry link and the vehicle starts beeping.  This would also warn the user when they don't have RC (and if expected) telemetry on.

**Comment by enjoybeta** [comment]
I think its implemented, can be closed

**Comment by rmackay9** [comment]
OK, txs, closed.
