### ISSUE TITLE
RC Roll not Configured

### ISSUE THREAD

**Issue by dturetsky** [ArduPilot/ardupilot#6952]
#### Issue details
_Please describe the problem, or desired feature_
We have just updater our Pixhawk to AC3.5 with out any other changes.  When trying to fly our multi rotor we are getting a "RC Roll not configured".  We did some research and found many people who have verified the error as a bug in version 3.5.
#### Version
_What version was the issue encountered with_
3.5.2 
#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Octocopter
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
Pixhawk
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).

RC Roll not configured means that your min and max roll parameters (usually RC1_MIN/MAX) aren't changed from the default values. If for some reason the min or max values for your transmitter are the same as the default you'll need to change them to a different value, save it and then put the correct value again and save it.
