### ISSUE TITLE
QuadPlane: THR_SLEWRATE not working as documented

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#6957]
#### Issue details

Documentation says:

> THR_SLEWRATE: Throttle slew rate
> maximum percentage change in throttle per second. A setting of 10 means to not change the throttle by more than 10% of the full throttle range in one second.

I performed some tests with SITL.

Here's THR_SLEWRATE=100:

<img width="1611" alt="screen shot 2017-09-14 at 8 48 54 pm" src="https://user-images.githubusercontent.com/6870452/30462875-325f0620-998e-11e7-8be3-99c318726648.png">

Takes 1.2 seconds to ramp up to max throttle, as expected.

And here's THR_SLEWRATE=1

<img width="1614" alt="screen shot 2017-09-14 at 8 49 06 pm" src="https://user-images.githubusercontent.com/6870452/30462885-473ccb68-998e-11e7-9108-543ec1e38afa.png">

Takes 3.3 seconds to ramp up to max throttle, not as expected.

Some params:
> RC3_MAX          2000.000000
> RC3_MIN          1000.000000
> THR_MAX          100.000000
> THR_MIN          0.000000

I was expecting the second test to take 100 seconds to go from 1000 PWM to 2000 PWM, 10 PWM at a time.

#### Version
Plane 3.7

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
QuadPlane in SITL.

#### Logs

DF log with THR_SLEWRATE=1%:  https://www.dropbox.com/s/0uu4q5qmnbrk9bb/9.BIN?dl=0
DF log with THR_SLEWRATE=100%: https://www.dropbox.com/s/rgoo79qjef2n90w/10.BIN?dl=0

**Comment by expntly** [comment]
Any update?  Thanks

**Comment by tridge** [comment]
there is a lower limit of 1 PWM unit per loop. This is because the PWM value is stored as an integer, so if we allowed for a change of less than 1 then it would never change at all (as it would get rounded down).
On a quadplane the loop rate is 300Hz by default, so slew rate min is 300 PWM per second, which means 3.3 seconds for 1000 PWM.
We should update the docs, but its not actually a bug

**Comment by tridge** [comment]
I've added a note on this to the docs

**Comment by kimkim999x** [comment]
hi, i have got a smimlar issue, I am testing my IC Engine on the ground, when I modify the parameter THR_SLEWRATE to 20 and test it with manual and FBWA, it doesn’t seems to slow down at all and still reach idle/full throttle at a split of a second, when I test it with SITL its doing the same…am I setting some parameters wrong or these flight mode does not support slew? if so how should I test the suitable slewrate…, thanks for helping

**Comment by peterbarker** [comment]
@kimkim999x do you have a dataflash log of that happening?

**Comment by vierfuffzig** [comment]
@kimkim999x @peterbarker THR_SLEWRATE is applied in auto throttle modes only

**Comment by kimkim999x** [comment]
@peterbarker i am currently still doing it on SITL.. Will try it on the actual thing
@vierfuffzig Thanks for the advice and it is working indeed!!! but may i ask how will you test the right Slewrate for the IC engine indeed, with FBWB mode?
