### ISSUE TITLE
QuadPlane 3.8.1: lost track of next WP in AUTO nav

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#6959]
#### Issue details
As the plane was navigating in AUTO, it seems like it suddenly lost track of its next WP and drifted further away from it, until taken over in QLOITER.

Flight plan with waypoints:

<img width="394" alt="screen shot 2017-09-15 at 12 28 28 pm" src="https://user-images.githubusercontent.com/6870452/30496171-3636a39e-9a14-11e7-8f57-dc9bad26de22.png">

Actual track showing how it made the left turn but then half-way through started drifting north instead of going south:

<img width="1451" alt="screen shot 2017-09-15 at 12 48 01 pm" src="https://user-images.githubusercontent.com/6870452/30496152-2b9538a6-9a14-11e7-8e48-f8c1569d04fd.png">

Somehow it seems to happen right when target bearing wraps around from -180 to 180, but I'm not sure this is related as I looked at another log file that also looks similar and the vehicle made the turn successfully.

Also worth mentioning is that the vehicle didn't transition to cruise as it should have (issues with push prop), so perhaps this confused the FC?

#### Version
ArduPlane 3.8.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
OctaQuadPlane

#### Hardware type
Pixhawk2.1

#### Logs

https://www.dropbox.com/s/s8jk4bo7boz6bgy/00000175.BIN?dl=0

**Comment by IamPete1** [comment]
sorry we never got to this.
