### ISSUE TITLE
Copter: RPM and Current feedback from ESC

### ISSUE THREAD

**Issue by bstott** [ArduPilot/ardupilot#696]
Is it possible to receive motor feedback from the ESCs through the signal line?

 If yes, add this APM firmware feature:
- During transition from pre-operation to flight as the throttle is being initiated have the APM run a quick feedback check and compare on the ESCs for motor current draw. This could effectively be a propeller check to verify proper installation, condition and matching. If the results are not within X% of each ESCs the APM would alarm and disarm. This capability could stop some of the flips received from improper propeller installations. Note: With the manner that firmware 3.0.1 rc5 spins up propellers the APM could possibly do this check upon the first momentary fast propeller spin before the propellers settle to their default slow spin. ???

The idea is that a propeller turning in the opposite direction of design would create a measurably different current draw (thrust) as a properly spinning propeller. This would be easily recognized electronically from a comparison to the other running motors and could stop the APM from arming the vehicle in a faulty configuration. Thus, eliminate some machine flips or for the hex and oct stop them flying with improper configurations. Of course - if the props do not cause a motor current draw difference then all these words are ---- just words.

**Comment by palm369** [comment]
I think we can close this topic and go further with this one: #4135
