### ISSUE TITLE
Confused in AP_IRLock. Need HELP!

### ISSUE THREAD

**Issue by duy1102002** [ArduPilot/ardupilot#6966]
#### Issue details
What is the theory of IRLock in method "pixel_to_1M_plane",which prototype is "void AP_IRLock_I2C::pixel_to_1M_plane(float pix_x, float pix_y, float &ret_x, float &ret_y)"
#### Version
3.3 or above

#### Platform
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Matters
The methods above really confused me for a long time. I can't figure out what it has done. Input vararible values is pixels address , but out put is another address.
The only thing I can understand is that it does some transform from pixel to distance and some distortion calibration. But could you give some details in this work？like some theory or formula.

Thanks!

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

Given the nature of your question forum is probably better so it doesn't get lost in time. I suggest you tag @jschall in the forum post, he is the original author of that: https://github.com/ArduPilot/PX4Firmware/commit/21bf00e10b8847cb9d45aa20e3f9114ca63e3a0c
