### ISSUE TITLE
Rover : pivot turn only works in manual

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#6972]
#### Issue details
3 users reports broken pivot turn in the beta 3.2 
https://discuss.ardupilot.org/t/skidsteering-is-behaving-strange/21132/7 
#### Version
beta 3.2
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ X ] Rover
[  ] Submarine

#### Airframe type
Tank

**Comment by NickNunno** [comment]
Pierre, thanks for looking into this.

**Comment by rmackay9** [comment]
This is fixed now I think so closing.
