### ISSUE TITLE
Arduplane - Quadplane RTL not reaching completion during mission

### ISSUE THREAD

**Issue by nick2204** [ArduPilot/ardupilot#6974]
#### Issue details
After running an auto mission takeoff-> several waypoints -> RTL, the vehicle never re-enters the landed state.

When reattempting to arm in Guided mode, throttle goes to 100%

#### Version
Arduplane 3.8.2-dev (running in SITL)
Q_enable =1 (quadplane)
Q_guided_mode = 0 (FW loiter)
Q_RTL_mode = 1 (land in VTOL once RTL reached)

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quadplane

#### Hardware type
SITL

#### Logs

[00000007.zip](https://github.com/ArduPilot/ardupilot/files/1313010/00000007.zip)

**Comment by nick2204** [comment]
Also checked that doing RTL in the guided state, does not get it stuck in this state.

**Comment by tridge** [comment]
I'm having difficulty reproducing this issue in SITL. I've used your parameters and your mission and it doesn't show any problems.
Could we worth through this together sometime so I can reproduce?

**Comment by nick2204** [comment]
Sure I'll give you a Skype call Monday if you're free.
On 22 Sep 2017 4:39 p.m., Andrew Tridgell <notifications@github.com> wrote:I'm having difficulty reproducing this issue in SITL. I've used your parameters and your mission and it doesn't show any problems.
Could we worth through this together sometime so I can reproduce?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ArduPilot/ardupilot","title":"ArduPilot/ardupilot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ArduPilot/ardupilot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tridge in #6974: I'm having difficulty reproducing this issue in SITL. I've used your parameters and your mission and it doesn't show any problems.\r\nCould we worth through this together sometime so I can reproduce?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ArduPilot/ardupilot/issues/6974#issuecomment-331363616"}}}

**Comment by nick2204** [comment]
An extension to preventing some undesired behaviours for particular Quadplane airframes, it would be great to be able to:

1. Disable standard Fixed-wing takeoff for air frames with no wheels - prevent accidental forward motor arming on the ground

2. Disable navigation (other than position hold at home) within some 3D bounding box of arming location - prevent dragging landing gear sideways across the ground

3. Disable use of guided waypoints until after the vehicle has taken-off - prevent sudden movement as vehicle leaves the ground

**Comment by magicrub** [comment]
@nick2204 those are all good ideas. Could you make 3 new issues so we can track those feature requests? Bonus points if you paste the URLs here for reference :)

**Comment by nick2204** [comment]
@magicrub done :)
https://github.com/ArduPilot/ardupilot/issues/7048
https://github.com/ArduPilot/ardupilot/issues/7049
https://github.com/ArduPilot/ardupilot/issues/7050

**Comment by DavidIngraham** [comment]
@nick2204 Are you still seeing this issue?

**Comment by nick2204** [comment]
hey @DavidIngraham , most of the problems were fixed by @tridge in 3.8.3
at least i never saw the problem again after this.
The major change that prevented some of this behaviour was the addition of Q_options:
[Q_options](http://ardupilot.org/plane/docs/parameters.html#q-options-quadplane-options)

**Comment by IamPete1** [comment]
seems to have been fixed?
