### ISSUE TITLE
Add support for CRSF

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#7006]
Add support for new data protocol CRSF.
http://www.team-blacksheep.com/products/prod:crossfire_tx

3x faster version of SBUS.

**Comment by magicrub** [comment]
Here's a PR from BetaFlight adding support:
https://github.com/betaflight/betaflight/pull/4199

**Comment by ufoDziner** [comment]
Just curious if this is going to get implemented.  Thanks.

**Comment by rmackay9** [comment]
@ufoDziner, it's hard to say.  It just takes one developer being interested in doing the implementation for it to happen... sometimes that person appears immediate, sometimes it takes a while... Sometimes a company (like one of our Partners) sponsors a developer to do the work... we plan out the big stuff at our annual conference but not the smaller items so much.  This is probably too long an answer but..

**Comment by auturgy** [comment]
I’ll tag @tridge as he has the hardware now.
It’s definitely on the list, but can’t predict a date.

**Comment by ufoDziner** [comment]
Thanks you two!  It would be awesome to get it implemented.

**Comment by Target0815** [comment]
Ardupilot doesn't lack various protocols, but it would be nice if you could keep up with the times and implement current developments.

Therefore +1 for the CRSF protocol.

**Comment by CodingGhost** [comment]
If somebody that know the AP code well points me in the right direction, I could try it.

**Comment by andyp1per** [comment]
I'm thinking of doing this when I have finished the runcam support. It won't be too dissimilar https://github.com/ArduPilot/ardupilot/pull/12810

**Comment by CodingGhost** [comment]
@andyp1per, any ETA? I could help if you want, we need this! :)

**Comment by andyp1per** [comment]
Sorry, I'm busy implementing SRXL2, will get to it eventually

**Comment by andyp1per** [comment]
This is a start. https://github.com/ArduPilot/ardupilot/pull/14257 Lacking a protocol spec so can't do the VTX part and lacking hardware so can't test the RC part!

**Comment by CodingGhost** [comment]
@andyp1per I will test it for you!! I have all the hardware. I can try to get the protocol spec also, I have some connections ;)

**Comment by CodingGhost** [comment]
you can shoot me a message via email

**Comment by jelkins8** [comment]
I can also test if needed.
