### ISSUE TITLE
not logging MODE on re-arm

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#7010]
problem: arm, then disarm, then change mode, then arm again
it does not log the mode on the 2nd arm
needs fixing for plane 3.8.3 as this leads to very misleading logs

**Comment by OXINARF** [comment]
Probably a simple fix can be done for Plane 3.8.3 but I think this is a larger problem. When we disarm and then re-arm we don't rewrite the initial messages - it's possible that, in that interim, mission, parameters, mode, etc. were changed. In my opinion the correct fix would be to rewrite the initial messages, except the FMT ones.

**Comment by peterbarker** [comment]
Current thinking for Plane 3.8.3 is that we'll write out critical messages even when disarmed.

Sounds easy, right?

I've previously had a patch which added `LOG_BITMASK_DSRM` (or something...).  This would supplant the `LOG_DISARMED` argument.

tridge and I threw around the concept of writing out all of the initial messages.  Amusingly, you do have to worry about formats due to `Log_Write(format, ...)`

**Comment by OXINARF** [comment]
> Current thinking for Plane 3.8.3 is that we'll write out critical messages even when disarmed.
>
> Sounds easy, right?

It doesn't and looks even harder than writing all startup messages again. But you know the DataFlash library much better than me.

> tridge and I threw around the concept of writing out all of the initial messages. Amusingly, you do have to worry about formats due to Log_Write(format, ...)

Ah I forgot about that. That means we can have logs now that are missing FMT messages, right?

**Comment by peterbarker** [comment]
On Thu, 28 Sep 2017, Francisco Ferreira wrote:

> Ah I forgot about that. That means we can have logs now that are missing FMT
> messages, right?

Indeed.

**Comment by OXINARF** [comment]
> Ah I forgot about that. That means we can have logs now that are missing FMT messages, right?

@peterbarker did @tridge's commit fix the issue above?

**Comment by tridge** [comment]
yes, this is fixed with the commit to log critical msgs while disarmed, closing
