### ISSUE TITLE
Fast descend when loiter / RTL

### ISSUE THREAD

**Issue by gui2dev** [ArduPilot/ardupilot#7018]
#### Issue details

While descending in RTL or LOITER, I experienced a sudden increase of vertical speed and no throttle response on RC. This happens two times in a row after several normal flights.
I could not find any decent explaination in the logs. So I suppose this could be a bug ?

#### Version
Arducopter 3.5.2

#### Platform
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Hexa

#### Hardware type
PIxhawk 2

#### Logs

https://1drv.ms/u/s!AnS3nHy1xzlAlgz14N2OZ3HMA9hp

**Comment by rmackay9** [comment]
It's almost guaranteed to be high vibration levels.
