### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jayjagtap** [ArduPilot/ardupilot#7024]
#### Issue details
I am following the installation guide as on the http://ardupilot.org/dev/docs/sitl-native-on-windows.html
I am stuck at this point : Download and make ardupilot
Using Windows 10

git submodule update --init --recursive

Everytime I fore this command on cygwin after following all the prior instructions it fails with following output:

hp@LAPTOP-59TH2EJC ~/ardupilot
$ git submodule update --init --recursive
Submodule 'modules/PX4Firmware' (git://github.com/ArduPilot/PX4Firmware.git) registered for path 'modules/PX4Firmware'
Submodule 'modules/PX4NuttX' (git://github.com/ArduPilot/PX4NuttX.git) registered for path 'modules/PX4NuttX'
Submodule 'modules/gbenchmark' (git://github.com/google/benchmark.git) registered for path 'modules/gbenchmark'
Submodule 'gtest' (git://github.com/ArduPilot/googletest) registered for path 'modules/gtest'
Submodule 'modules/mavlink' (git://github.com/ArduPilot/mavlink) registered for path 'modules/mavlink'
Submodule 'modules/uavcan' (git://github.com/ArduPilot/uavcan.git) registered for path 'modules/uavcan'
Submodule 'modules/waf' (git://github.com/ArduPilot/waf.git) registered for path 'modules/waf'
Cloning into '/home/hp/ardupilot/modules/PX4Firmware'...
Cloning into '/home/hp/ardupilot/modules/PX4NuttX'...
Cloning into '/home/hp/ardupilot/modules/gbenchmark'...
Cloning into '/home/hp/ardupilot/modules/gtest'...
Cloning into '/home/hp/ardupilot/modules/mavlink'...
Cloning into '/home/hp/ardupilot/modules/uavcan'...
Cloning into '/home/hp/ardupilot/modules/waf'...
Submodule path 'modules/PX4Firmware': checked out '0384802e81330751f39550a0804357d8b04f278a'
Submodule 'Tools/gencpp' (https://github.com/ros/gencpp.git) registered for path 'modules/PX4Firmware/Tools/gencpp'
Submodule 'Tools/genmsg' (https://github.com/ros/genmsg.git) registered for path 'modules/PX4Firmware/Tools/genmsg'
Submodule 'mavlink/include/mavlink/v1.0' (git://github.com/mavlink/c_library.git) registered for path 'modules/PX4Firmware/mavlink/include/mavlink/v1.0'
Submodule 'src/lib/DriverFramework' (https://github.com/PX4/DriverFramework.git) registered for path 'modules/PX4Firmware/src/lib/DriverFramework'
Submodule 'src/lib/ecl' (https://github.com/PX4/ecl.git) registered for path 'modules/PX4Firmware/src/lib/ecl'
Submodule 'src/lib/matrix' (https://github.com/PX4/Matrix.git) registered for path 'modules/PX4Firmware/src/lib/matrix'
Submodule 'src/modules/uavcan/libuavcan' (git://github.com/UAVCAN/libuavcan.git) registered for path 'modules/PX4Firmware/src/modules/uavcan/libuavcan'
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/Tools/gencpp'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/ros/gencpp.git' into submodule path '/home/hp/ardupilot/modules/PX4Firmware/Tools/gencpp' failed
Failed to clone 'Tools/gencpp'. Retry scheduled
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/Tools/genmsg'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/ros/genmsg.git' into submodule path '/home/hp/ardupilot/modules/PX4Firmware/Tools/genmsg' failed
Failed to clone 'Tools/genmsg'. Retry scheduled
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/mavlink/include/mavlink/v1.0'...
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/src/lib/DriverFramework'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/PX4/DriverFramework.git' into submodule path '/home/hp/ardupilot/modules/PX4Firmware/src/lib/DriverFramework' failed
Failed to clone 'src/lib/DriverFramework'. Retry scheduled
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/src/lib/ecl'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/PX4/ecl.git' into submodule path '/home/hp/ardupilot/modules/PX4Firmware/src/lib/ecl' failed
Failed to clone 'src/lib/ecl'. Retry scheduled
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/src/lib/matrix'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/PX4/Matrix.git' into submodule path '/home/hp/ardupilot/modules/PX4Firmware/src/lib/matrix' failed
Failed to clone 'src/lib/matrix'. Retry scheduled
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/src/modules/uavcan/libuavcan'...
Cloning into '/home/hp/ardupilot/modules/PX4Firmware/Tools/gencpp'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/ros/gencpp.git' into submodule path '/home/hp/ardupilot/modules/PX4Firmware/Tools/gencpp' failed
Failed to clone 'Tools/gencpp' a second time, aborting
Submodule path 'modules/PX4NuttX': checked out '1bcae90b334206c92d57298f5b957247a8f3a85e'
Submodule path 'modules/gbenchmark': checked out '006d23ccca1375a973b7fae0cc351cedb41b812a'
Submodule path 'modules/gtest': checked out 'c99458533a9b4c743ed51537e25989ea55944908'
Submodule path 'modules/mavlink': checked out 'a722c139a07ac39b8941db58496ce74942088785'
Submodule 'pymavlink' (git://github.com/ArduPilot/pymavlink.git) registered for path 'modules/mavlink/pymavlink'
Cloning into '/home/hp/ardupilot/modules/mavlink/pymavlink'...
Submodule path 'modules/mavlink/pymavlink': checked out '6135d77151a775603c58c4d41d8b42ad28f461c4'
Submodule path 'modules/uavcan': checked out '9d75eba870e3b3935346229267ecee2c499f6575'
Submodule 'dsdl' (https://github.com/UAVCAN/dsdl) registered for path 'modules/uavcan/dsdl'
Submodule 'libuavcan/dsdl_compiler/pyuavcan' (https://github.com/UAVCAN/pyuavcan) registered for path 'modules/uavcan/libuavcan/dsdl_compiler/pyuavcan'
Cloning into '/home/hp/ardupilot/modules/uavcan/dsdl'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/UAVCAN/dsdl' into submodule path '/home/hp/ardupilot/modules/uavcan/dsdl' failed
Failed to clone 'dsdl'. Retry scheduled
Cloning into '/home/hp/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/pyuavcan'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/UAVCAN/pyuavcan' into submodule path '/home/hp/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/pyuavcan' failed
Failed to clone 'libuavcan/dsdl_compiler/pyuavcan'. Retry scheduled
Cloning into '/home/hp/ardupilot/modules/uavcan/dsdl'...
fatal: Unable to find remote helper for 'https'
fatal: clone of 'https://github.com/UAVCAN/dsdl' into submodule path '/home/hp/ardupilot/modules/uavcan/dsdl' failed
Failed to clone 'dsdl' a second time, aborting
Submodule path 'modules/waf': checked out '73163ef5c117a51f29546d17c2bb2041aecefcdd'
Failed to recurse into submodule path 'modules/PX4Firmware'
Failed to recurse into submodule path 'modules/uavcan'

#### Version
I am using the latest versions of MAVProxy and cygwin

###Note
While installing cygwin , there was no package which exactly matched : 

automake | Devel | automake: Wrapper scripts for automake and aclocal 

so to be safe, I installed all packages with automake.

Please help me out. I have tried this process several times.Thanking you in anticipation

**Comment by lvale** [comment]
Please refer to discuss.ardupilot.org to support questions

Thank you.
