### ISSUE TITLE
[Arducopter ] Crash Detection during Flight

### ISSUE THREAD

**Issue by arkro99125** [ArduPilot/ardupilot#7039]
During the landing procedure, close from 3 meters high, the copter simple disarmed indicating crash!!! Is possible to see sigficant difference between desired pitch and actual pitch, but the copter was in normal flight.  

#### Version
3.5.3

#### Platform
[ x ] Copter

#### Airframe type
Quad 

#### Hardware type
Pixracer

#### Logs

[Logs_crash_in_flight.zip](https://github.com/ArduPilot/ardupilot/files/1357833/Logs_crash_in_flight.zip)

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
