### ISSUE TITLE
Copter: External Led indication for GPS Lock and HDOP <= GPS_HDOP_Good

### ISSUE THREAD

**Issue by RogerHill** [ArduPilot/ardupilot#704]
I would like to propose a change to the operation of the GPS external led (A6)

Instead of "will flash with no GPS lock, solid with GPS lock" as currently defined in the Wiki, I propose the following: Led Off for no lock, Flash for lock and Solid for lock and HDOP <= GPS_HDOP_GOOD.

**Comment by lthall** [comment]
Done
