### ISSUE TITLE
Rover : fix skid_steer_in

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#7041]
#### Issue details
skid_steer_in is broken since the introduction of AP_motorUGV

#### Version
rover beta 3.2
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[X] Rover
[  ] Submarine

**Comment by gmorph** [comment]
Skid steering is working now right? I'll close this and if I'm mistaken please re-open and provide more elaboration and a log on how its broken.  Thanks.
