### ISSUE TITLE
Disable standard Fixed-wing takeoff for Quadplane with no wheels

### ISSUE THREAD

**Issue by nick2204** [ArduPilot/ardupilot#7048]
#### Issue details
Improvement for specific Quadplane configurations
Disable standard Fixed-wing takeoff for air frames with no wheels - prevent accidental forward motor arming on the ground.

Possibly combined in a config word with various other vehicle specific settings.

#### Version
Arduplane 3.8.2-dev (running in SITL)
Q_enable =1 (quadplane)
Q_guided_mode = 0 (FW loiter)
Q_RTL_mode = 1 (land in VTOL once RTL reached)

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quadplane

#### Hardware type
PH2.1
SITL

**Comment by tridge** [comment]
this is fixed in 3.8.3 using Q_OPTIONS
