### ISSUE TITLE
Disable navigation within some 3D bounding box of arming location 

### ISSUE THREAD

**Issue by nick2204** [ArduPilot/ardupilot#7049]
#### Issue details
Improvement for specific Quadplane configurations
Disable navigation (other than position hold at home) within some 3D bounding box of arming location - prevent dragging landing gear sideways across the ground

Possibly combined in a config word with various other vehicle specific settings.

#### Version
Arduplane 3.8.2-dev (running in SITL)
Q_enable =1 (quadplane)
Q_guided_mode = 0 (FW loiter)
Q_RTL_mode = 1 (land in VTOL once RTL reached)

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quadplane

#### Hardware type
PH2.1
SITL

**Comment by peterbarker** [comment]
This is `Q_NAVALT_MIN`, I believe.

Reopen if I'm wrong, please.
