### ISSUE TITLE
in L1_Control, the constrain Nu angle is not  in agreement with the comments

### ISSUE THREAD

**Issue by luweikxy** [ArduPilot/ardupilot#7054]
Hello, when I was reading the L1 code, I found that:

https://github.com/ArduPilot/ardupilot/blob/2894b7cbea4f158e064d4b4d86ecaf6461163a6d/libraries/AP_L1_Control/AP_L1_Control.cpp#L319

> //Limit Nu to +-pi
> Nu = constrain_float(Nu, -1.5708f, +1.5708f);

in commits, it says that limit Nu to **+-pi**, but in the code, Nu is limited to **+-pi/2**.

so which may be more appropriate?

Thanks!

**Comment by magicrub** [comment]
I don't know the answer off-hand, but typically the code is what's up-to-date and the comment is old.

**Comment by luweikxy** [comment]
@magicrub OK, gotcha. Thanks!
