### ISSUE TITLE
add apj firmware editor

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#7057]
We should create an apj firmware editor which allows for parameter files to be added to an apj file, to make frame specific firmwares.
Features:

- work with any existing GCS
- extract current default parameters
- add new parameters
- support a string identifier in the parameters to display to GCS and log

**Comment by Pedals2Paddles** [comment]
Thanks for taking this on Tridge!

**Comment by peterbarker** [comment]
@Pedals2Paddles Can this be closed?

**Comment by Pedals2Paddles** [comment]
I think so. It's done, merged, and working nicely.

**Comment by WickedShell** [comment]
#7216 added the script for editing it, at this point GCS's need to pick it up and make nice UI's for it, but I agree that the issue as presented is done.
