### ISSUE TITLE
QuadPlane: Q_YAW_RATE_MAX doesn't take effect

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#7066]
#### Issue details

It seems changing Q_YAW_RATE_MAX doesn't actually change the yaw rate.  Here's an AUTO mission with a 90-degree turn.  The flight at the top is with Q_YAW_RATE_MAX=20, the one at the bottom is with Q_YAW_RATE_MAX=10.

<img width="1677" alt="screen shot 2017-10-11 at 9 21 31 am" src="https://user-images.githubusercontent.com/6870452/31446608-b268ddbe-ae65-11e7-8fb8-c8f3fee90daf.png">

#### Version
ArduPlane-3.8.1 SITL

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
QuadPlane

#### Hardware type
Happening with Pixhawk2.1, but reproduced with SITL.

**Comment by nick2204** [comment]
Are you sure that the this is the limiting factor? 
How fast is it yawing? never seen a quad plane be able yaw too fast except when it yaws one way much faster than the other from mechanical alignment issues.

**Comment by tridge** [comment]
Q_YAW_RATE_MAX is a scaling factor for pilot input on rudder stick. It doesn't affect AUTO missions.
I'll update the docs

**Comment by tridge** [comment]
docs have been updated, closing
