### ISSUE TITLE
[sugestion] native frsky telemetry 

### ISSUE THREAD

**Issue by finos2** [ArduPilot/ardupilot#7076]
in my opinion the mavlink to frsky adapters must be incorporated on the main firmware and have output on an aux chanel and/or a uart I think can be done pixhawk 1 and surly pixhawk 2 has the balls to do it on top of averything else .. pixracer does it ! , also it would be great to control what Is send back to the s.port !
e.g : 
https://www.airborneprojects.com/product/apm-mavlink-to-frsky-smartport-converter/

**Comment by geofrancis** [comment]
that has been avalible for a long time now. 
http://ardupilot.org/copter/docs/common-frsky-telemetry.html

**Comment by auturgy** [comment]
Close.

**Comment by amilcarlucas** [comment]
Already implemented
