### ISSUE TITLE
Arducopter Oscillates in Loiter Mode

### ISSUE THREAD

**Issue by JoseOcasio** [ArduPilot/ardupilot#7110]
#### Issue details
Pixhawk/Arducopter oscillating with beacons inputs via gps connection. I'm using a beacon and it has a 1cm accuracy values, but it looks like GPS code in arducopter can't handle values that accurate. So while it flies fine with an outdoor GPS, when I fly indoors with beacon, the copter kind of hovers in a 1m circle, and as it hits the perimeter, it then adjusts. This repeat, causing it to basically drift for 1m then correct. So it's never really still. Anyone know how to adjust the firmware code to always correct location so it can hover in place? I've tried modifying every GPS, ek3, ek2, and ekf value in the parameter to no avail.

I have also tried to flash the latest firmware, but it is even worse.

#### Version
APM Copter 3.6-dev

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad X

#### Hardware type
Pixhawk
GPS-Marvelmind

**Comment by magicrub** [comment]
Several people are using beacons without this problem so please check the forums at http://discuss.ardupilot.org . Once you post there, please post a link to the forum post here to connect the dots. This issues list is for confirmed bugs and feature requests.

A couple clues to start you off:

>I have also tried to flash the latest firmware, but it is even worse.

It's always recommended to use the latest version, especially on new technologies/features. And "latest version" is sometimes relative to developers, its *much* easier for everyone to just say the version number.


>I've tried modifying every GPS, ek3, ek2, and ekf value in the parameter to no avail.

This is probably making things worse for you. Check the forums


I don't see any logs attached, those are super helpful for others to help you. You say beacons, but did not mention any details about the beacons! What brand? How are they distributed? Geometry matters..
