### ISSUE TITLE
Arduplane simple relative to home dist/alt geofence...like copters tincan

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#713]
would be nice set and forget boundary to prevent flyaways when using AUTO as FS to allow mission to complete if radio is lost...lie behind hills, etc....rtl on breach until toggle out of AUTO mode.....would be nice for use with CRUISE also...letting it Cruise to the fence distance and then rtl, could do spaced radial mapping missions repeatedly with only the fence distance setup and no CGS setup/intervention...

**Comment by Naterater** [comment]
Fence is in plane.

**Comment by auturgy** [comment]
Plane has polygon fence, not radius.
Perhaps check the the OP is happy with that before closing?
