### ISSUE TITLE
Copter: automatic takeoff without using the throttle safety (only for AUTO flight mode)

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#7156]
#### Issue details
As is known "Ardupilot QuadPlane" (VTOL) is able to takeoff automatically during AUTO mission with a Mavlink command without the "throttle safety", using only the "VTOL_TAKEOFF" event.
Most existing copter can takeoff on an automatic mission without using the tx throttle stick, only with a tx button or with a groundstation command.
In the Copter this security has always existed, it would be interesting to disable it with an option.
From the wiki:

"If starting the mission while the copter is on the ground the pilot should ensure the throttle is down, then switch to the Auto flight mode, then raise the throttle. The moment that the throttle is raised above zero, the copter will begin the mission"

It would be interesting to disable throttle safety, only during "Auto" mode with a takeoff event and with a parameter for disable it.
Conceptually to standardize the Ardupilot systems or remove it from QuadPlane or put it in the Copter... :-)
Now there're other security upstream (safety button, arming option), so I think this can even be removed.
@rmackay9, what do you think?

#### Version
3.5.3

#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by rmackay9** [comment]
I think in Copter's possible to take-off without the pilot having to raise the throttle if a command-long is sent with either a TAKEOFF or MISSION_START command within it.

**Comment by robustini** [comment]
In SITL it doesn't work, I want to arm from the Planner, and choose AUTO, the Copter should start the mission if the first event is "TAKEOFF", and it doesn't happen.

**Comment by rmackay9** [comment]
Thanks for closing this.  We have AUTO_OPTIONS in 4.1 which allows this now I think.
