### ISSUE TITLE
Plane: create new flight mode - TAKEOFF

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#7182]
Create new plane flight mode "TAKEOFF" that will:
- act like an AUTO mission executing NAV_TAKEOFF
- fly up to the RTL altitude (ALT_HOLD_RTL)
- then head home and loiter forever (like RTL_AUTOLAND=0 behavior)

**Comment by WickedShell** [comment]
Duplicate of #2811 which has far more discussion.

**Comment by magicrub** [comment]
THERE it is. I knew one was around but I couldn't find it. Thx.
