### ISSUE TITLE
5525 airspeed i2c noise

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#7188]
We need a way to filter noise on the MS5525 airspeed sensor. On the 4425 we can use double reads to detect errors. On the MS5525 we can't do that, as a 2nd read will always give zero. This is a log of a flight leading to a stall and crash due to extreme i2c noise.
![ms5525-airspeed-noise](https://user-images.githubusercontent.com/831867/32433558-79d3b878-c32f-11e7-90e0-9f2763b8c562.png)

Log is here: http://uav.tridgell.net/DaleRogers/00000021.BIN

**Comment by magicrub** [comment]
what about comparing current sample to a high-passed previous sample? Or if delta between samples is large, use previous sample.

**Comment by kd0aij** [comment]
Are these errors solely attributable to bad I2C wiring/routing, or is there a problem with the voltage levels on the bus?

**Comment by WickedShell** [comment]
@kd0aij looks similar to the problems I was having with the MS4525 which were all I2C interference related: See [here](https://github.com/ArduPilot/ardupilot/pull/5935#issuecomment-290006665) and [here](#5950) (second link has a scope trace of what the bus looks like during one of the bad reads)

**Comment by kd0aij** [comment]
If this data is from an old 3DR sensor, this might be the root cause: https://github.com/PX4/Hardware/issues/55

**Comment by WickedShell** [comment]
@kd0aij it wasn't, was from a MRo and jDrones airspeed + compass board. Both exhibited the same noise for me (as did a 3DR one).

**Comment by kd0aij** [comment]
Were you unable to eliminate the noise by shortening or shielding the I2C cable?

**Comment by WickedShell** [comment]
Not possible due to mounting constraints on the first one, the second didn't seem to have any useful effect, however all shielding was an improve affair and not great. Also tested the differential encoder pair from MRo but didn't seem to see any benefit from it. (It was tested before I had identified the actual line level problem). It's worth noting that the log this issue is open from is not mine, and the pair of PR's I linked you completely resolved all my I2C airspeed problems.

**Comment by kd0aij** [comment]
Your second link is circular, so I haven't seen your scope trace, but this is definitely a good reason to move to CAN for larger aircraft. But I've not observed this problem at all in my little E-flite Convergence

**Comment by WickedShell** [comment]
@kd0aij oops! Sorry, I've updated the link, it was PR #5950

**Comment by lucamax** [comment]
I'm using the Mro  Ms5525 sensor since a while but do not ever saw any problem.
I'm using a  Mro  X2.1 Rev. 2 board with 20 cm I2C cable.
![gkrellshoot_12-10-17_203737](https://user-images.githubusercontent.com/17679013/33808627-428e1f22-ddea-11e7-8e5a-ef7cd83daefc.jpg)

**Comment by DavidIngraham** [comment]
![image](https://user-images.githubusercontent.com/2849049/33843798-9a92627a-de5b-11e7-8a7d-da742136476d.png)
We have been seeing this issue on several of our vehicles as well. We have a custom avionics board with the MS5525 mounted on the same circuit board as the Cube, so I'm surprised that electrical interference is affecting it. We are seeing it very infrequently (the above image shows a 2 hour flight)

I support the idea of sanity checking against past values. Rejecting sensor measurements with a delta of over ~30 m/s over an average of previous readings would fix the issue that we are seeing.

**Comment by tridge** [comment]
@DavidIngraham wondered if it could be a software issue, so I've created a branch here that logs the raw data from the I2C bus:
https://github.com/tridge/ardupilot/commits/plane38-ms5525-logging
the log will allow us to check the software side and ensure we're not doing something like mixing up P and T values

**Comment by DavidIngraham** [comment]
![image](https://user-images.githubusercontent.com/2849049/34234481-9a69a28c-e5a8-11e7-8bd3-8e190473fb5c.png)
When investigating the log further we discovered that the "noise" was alternating between the temperature and pressure readings. This seems to suggest that there may be a bug in the driver contributing to the noise we are seeing.

We are going to attempt to reproduce this issue on the ground using the fork @tridge linked above.

**Comment by tridge** [comment]
I've created a PR to fix this:
https://github.com/ArduPilot/ardupilot/pull/7440
many thanks for the log from @DavidIngraham  showing that it was a timing issue and not bus noise

**Comment by custeve** [comment]
@tridge @magicrub - Running 3.9.6, I may have reproduced the same or similar issue. Investigating a possible bad trace on a custom avionics board. Nonetheless, this flight caused a forced landing. See attachment, MS5525 reports noisy readings, then holds. Log file is >10mb, so I couldn't upload.


![image](https://user-images.githubusercontent.com/24815380/54827352-615fd380-4c77-11e9-991d-0d06570c65ff.png)

**Comment by lukedempsey** [comment]
I have recently experience similar intermittent issues but with a 4425. 

The artifacts I'm seeing are in the scope trace below. It only seems to happen when the SCL is already low and the SDA line goes high.

Have tried with multiple pixhawks and multiple 4425 sensors.

![MVIMG_20190618_132423_2](https://user-images.githubusercontent.com/10955380/60570483-04ff6a80-9db5-11e9-93d5-3debc8f5f455.jpg)
