### ISSUE TITLE
MAVLink: send_to_components( ) fails for MAVLink 2 messages

### ISSUE THREAD

**Issue by SamuelDudley** [ArduPilot/ardupilot#7207]
#### Issue details
I'm unsure if this is an ArduPilot code specific issue, MAVLink issue or just a repeated failure on my behalf (hopefully someone wiser than me will spot the mistake if that is the case! :) )

During ArduPilot development I noted that MAVLink 2 messages sent via GCS::send_to_components() fail to be decoded correctly on the receiving end **only** when they have been sent from hardware.
For example I have added the following code into AP_Camera:
```
// send camera feedback to message to components of this system
void AP_Camera::send_feedback_ahrs() {

    mavlink_message_t msg;
    mavlink_camera_feedback_ahrs_t camera_feedback_ahrs = { };

    camera_feedback_ahrs.img_idx = _image_index;
    camera_feedback_ahrs.trigger_time = _camera_feedback_time;
    camera_feedback_ahrs.sample_time = _ahrs_summary.ahrs_update_time;
    camera_feedback_ahrs.x = _ahrs_summary.ned_pos_rel_home.x;
    camera_feedback_ahrs.y = _ahrs_summary.ned_pos_rel_home.y;
    camera_feedback_ahrs.z = _ahrs_summary.ned_pos_rel_home.z;
    camera_feedback_ahrs.vx = _ahrs_summary.velocity.x;
    camera_feedback_ahrs.vy = _ahrs_summary.velocity.y;
    camera_feedback_ahrs.vz = _ahrs_summary.velocity.z;
    camera_feedback_ahrs.q1 = _ahrs_summary.quat.q1;
    camera_feedback_ahrs.q2 = _ahrs_summary.quat.q2;
    camera_feedback_ahrs.q3 = _ahrs_summary.quat.q3;
    camera_feedback_ahrs.q4 = _ahrs_summary.quat.q4;
    camera_feedback_ahrs.home_lat = _ahrs_summary.home.lat;
    camera_feedback_ahrs.home_lon = _ahrs_summary.home.lng;
    camera_feedback_ahrs.home_alt = _ahrs_summary.home.alt;
    camera_feedback_ahrs.lat = _ahrs_summary.location.lat;
    camera_feedback_ahrs.lon = _ahrs_summary.location.lng;
    camera_feedback_ahrs.alt = _ahrs_summary.location.alt;
    camera_feedback_ahrs.target_component = _vision_feedback_target_component;

    // encode camera feedback ahrs into MAVLink msg
    mavlink_msg_camera_feedback_ahrs_encode(0, 0, &msg, &camera_feedback_ahrs);

    // send to all components
    GCS_MAVLINK::send_to_components(&msg);
}
```

If I define ` camera_feedback_ahrs` as a MAVLink 2 message and flash the code onto hardware, `camera_feedback_ahrs` messages will appear as `BAD_DATA` after failing a CRC check (pyMAVLink). 
```
<message id="21111" name="CAMERA_FEEDBACK_AHRS">
      <description>Camera feedback that is synchronised with AHRS data</description>
      <field type="uint8_t" name="target_component">Component ID</field>
      <field type="uint16_t" name="img_idx">Image index</field>
      <field type="uint64_t" name="trigger_time" units="us">Autopilot time when the feedback event occured</field>
      <field type="uint64_t" name="sample_time" units="us">Autopilot time when the AHRS data was sampled</field>
      <field type="float" name="x" units="m">X Position</field>
      <field type="float" name="y" units="m">Y Position</field>
      <field type="float" name="z" units="m">Z Position</field>
      <field type="float" name="vx" units="m/s">X Speed</field>
      <field type="float" name="vy" units="m/s">Y Speed</field>
      <field type="float" name="vz" units="m/s">Z Speed</field>
      <field type="float" name="q1">Quaternion component 1, w (1 in null-rotation)</field>
      <field type="float" name="q2">Quaternion component 2, x (0 in null-rotation)</field>
      <field type="float" name="q3">Quaternion component 3, y (0 in null-rotation)</field>
      <field type="float" name="q4">Quaternion component 4, z (0 in null-rotation)</field>
      <field type="int32_t" name="lat" units="degE7">Latitude, expressed as degrees * 1E7</field>
      <field type="int32_t" name="lon" units="degE7">Longitude, expressed as degrees * 1E7</field>
      <field type="int32_t" name="alt" units="mm">Altitude in meters, expressed as * 1000 (millimeters), AMSL (not WGS84 - note that virtually all GPS modules provide the AMSL as well)</field>
      <field type="int32_t" name="home_lat" units="degE7">EKF home latitude, expressed as degrees * 1E7</field>
      <field type="int32_t" name="home_lon" units="degE7">EKF home longitude, expressed as degrees * 1E7</field>
      <field type="int32_t" name="home_alt" units="mm">EKF home altitude in meters, expressed as * 1000 (millimeters), AMSL (not WGS84 - note that virtually all GPS modules provide the AMSL as well)</field>
    </message>
```
Connected to hardware: 
```
BAD_DATA {invalid MAVLink CRC in msgID 119 0xb73c should be 0xda4a, data:['fe', '53', '8', '0', '0', '77', '78', '69', 'f4', '2', '0', '0', '0', '0', 'e1', '5f', 'f4', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '80', '3f', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'e9', '0', 'bf', '3c', 'b7']}
```
Note that other MAVLink 2 messages are received and parsed fine by the same message definitions leading me to believe that the CRC error is unique to messages sent via the `GCS_MAVLINK::send_to_components()` method.

- This error does **not** occur when running the ArduPilot code in SITL (messages are received correctly irrespective of the MAVLink version)
- This error **only** occurs when the message is defined as a MAVLink 2 message (the same message definition as a MAVLink 1 message works on both hardware and SITL)

**EDIT**
For testing / debugging the following simplified message also has a similar issue:

Message definition: 
```
    <message id="11021" name="test">
      <description>a test message to produce a CRC error</description>
      <field type="uint64_t" name="time_usec">timestamp</field>
      <field name="field1" type="float">test field 1</field>
      <field name="field2" type="float">test field 2</field>
    </message>
```

Code to send message:
```
    mavlink_message_t msg;
    mavlink_test_t test = { };
    
    test.time_usec = AP_HAL::micros64();
    test.field1 = 12.34;
    test.field2 = 56.78;

    mavlink_msg_test_encode(0, 0, &msg, &test);
    GCS_MAVLINK::send_to_components(&msg);
```

Connected to SITL:
```
TEST {time_usec : 111775000, field1 : 12.3400001526, field2 : 56.7799987793}
TEST {time_usec : 111795000, field1 : 12.3400001526, field2 : 56.7799987793}
```

Connected to hardware: (I can confirm that the same message defn file is being loaded by pyMAVLink)
```
BAD_DATA {unknown MAVLink message ID 13, data:['fe', '10', 'b', '0', '0', 'd', '56', '5e', 'bb', '4', '0', '0', '0', '0', 'a4', '70', '45', '41', 'b8', '1e', '63', '42', 'fc', 'f0']}
BAD_DATA {unknown MAVLink message ID 13, data:['fe', '10', 'c', '0', '0', 'd', '66', '40', 'c0', '4', '0', '0', '0', '0', 'a4', '70', '45', '41', 'b8', '1e', '63', '42', '47', '5d']}
```
Interestingly this message is causing a unknown MAVLink message error rather than the CRC error I observed previously with the camera_feedback_ahrs message. So perhaps its a message ID mangling problem? 

#### Version
Current master

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
N/A

#### Hardware type
PX4-V3 / the cube

#### Logs
N/A

**Comment by SamuelDudley** [comment]
I can confirm that the `TEST` message defined above is received correctly using this sending method from the cube:
```
    mavlink_msg_test_send(chan,
        AP_HAL::micros64(),
        3.0,
        4.0);
```
decoded result:
```
TEST {time_usec : 50500552, field1 : 3.0, field2 : 4.0}
```

While the the same message fails to be decoded using the send to components method from the cube:
```
    GCS_MAVLINK::send_to_components(&msg);

    mavlink_message_t msg;
    mavlink_test_t test = { };
    test.time_usec = AP_HAL::micros64();
    test.field1 = 1.0;
    test.field2 = 2.0;

    mavlink_msg_test_encode(0, 0, &msg, &test);
    GCS_MAVLINK::send_to_components(&msg);
```
Decoded result:
```
BAD_DATA {unknown MAVLink message ID 13, data:['fe', '10', '5', '0', '0', 'd', '39', '30', '0', '0', '0', '0', '0', '0', '0', '0', '80', '3f', '0', '0', '0', '40', '28', '50']}
```

**Comment by OXINARF** [comment]
I think the issue is that `send_to_components` is acting like it is re-sending a message, but, in reality, this method is used to send new messages to just components of the system (vs broadcast in all MAVLink ports). That means it doesn't finalize the message, but instead tries to send it as is.

**Comment by SamuelDudley** [comment]
Glad it's not just me! Based on a quick dig into the different paths the messages take to be sent I will agree with your comment. Unfortunately I won't be of any further help here, but I'm happy to test a patch once it becomes available. Thanks.

**Comment by magicrub** [comment]
What is the expected behavior? How is send_to_components() different than any given _send() function?

**Comment by SamuelDudley** [comment]
My understanding is that `send_to_components( )` allows messages to be sent on channels which have been identified to have a component of that system attached to it. For example I'm sending a message at ~30Hz to a companion computer using `send_to_components( )` to avoid flooding the GCS telemetry channel with unnecessary data. As another example it's also used in `AP_Camera` to send trigger events to attached MAVLink enabled cameras.

From my point of view working behaviour would allow me to send a valid MAVLink 2 message using `send_to_components( )` in the same way it is currently possible with a MAVLink 1 message.

**Comment by tridge** [comment]
@SamuelDudley 
I've done a commit here to fix this:
https://github.com/tridge/ardupilot/commits/pr-send-components
I haven't tested it though, if you could please test it before we put it in master that would be appreciated

**Comment by SamuelDudley** [comment]
Thanks, doing a drive from VIC to SA today but will test tomorrow.

**Comment by SamuelDudley** [comment]
@tridge With the patch applied MAVLink2 messages are now received and decoded via `send_to_components()` when using hardware, however the values of the message fields are incorrect for both SITL and hardware:

```
    mavlink_msg_test_send(chan,
        AP_HAL::micros64(),
        3.0,
        4.0);
```
results in (for both SITL and hardware)
```
TEST {time_usec : 338018226, field1 : 3.0, field2 : 4.0}
```
So that is still fine as per before, however
```
    mavlink_message_t msg;
    mavlink_test_t test = { };
    test.time_usec = 12345;
    test.field1 = 1.0;
    test.field2 = 2.0;

    mavlink_msg_test_encode(0, 0, &msg, &test);
    GCS_MAVLINK::send_to_components(&msg);
```
results in (for both SITL and hardware)
```
TEST {time_usec : 281475261828256, field1 : 3.95394858849e-39, field2 : 1.72990295421e-41}
```
So message framing is seems correct, but the payload is invalid when using `send_to_components()`.

**Comment by peterbarker** [comment]
I think I may have fixed this with
```
commit a96a4c05101d637c0e25cb6d70634a193075e73b
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Thu Oct 17 18:07:23 2019 +1100

    GCS_MAVLink: correct encoding used for send_to_components
    
    These have to be packed onto the channel - otherwise they may ge
    tencoded as mavlink1 instead of mavlink2 (or vice-versa)
```

Please reopen if that's incorrect.
