### ISSUE TITLE
Plane: Force Clockwise/CCW Loiter with 3rd field of Loiter command

### ISSUE THREAD

**Issue by iskess** [ArduPilot/ardupilot#721]
I have been trying to get my plane to loiter counter-clockwise to match the left hand traffic pattern at my local field. According to the Wiki:
 "If you set this value to a negative number then the default loiter direction will be counter-clockwise instead of clockwise".
I entered a value of -50 meters into WP_LOITER_RAD. I wrote my flight plan to the APM, and then read it back again to MP. I didn't notice that it had changed the 3rd column of the Loiter_Turns command, which represents the radius, to 205 meters. I was very suprised to see the plane start a 90 degree turn so far away from the loiter waypoint, but I let it go and soon realized it was wanting to make a giant loiter. The turn was still clockwise.
The 3rd column of Loiter_Turns is not labeled, and really should be, but that is a MP issue. 
I duplicated the issue again by creating a new Loiter_Turn leaving that 3rd column at its default of 0, and wrote it to the APM. Upon reading it back, again the 3rd column had changed to 205. 
![loiter radius jumps to 205](https://f.cloud.github.com/assets/4913946/1665050/fd0ec1b6-5c30-11e3-8948-6a2fbe429d94.JPG)

Next I tried to edit the loiter radius directly in the flight plan by entering -50 in the 3rd column. The plane still loitered clockwise and got stuck in an endless loiter. I had only commanded 1 loiter turn.

**Comment by iskess** [comment]
@Tridge,
Is this still on your list? It's quite old. 
I've been playing with HITL and I'm focusing on loiter issues right now. 
Thank you. 

The 3rd field for the Loiter_XXX command should allow 3 options.
1 = Force Clockwise
0 = Refer to direction specified in the WP_Loiter_Rad parameter
-1 = Force Counter Clockwise

**Comment by tridge** [comment]
I agree on the feature, but it is harder to do than it looks, as we currently only have a 1 bit flag to store the loiter direction. We'd need to add another flag if we have a spare bit.
Eventually we want to store the full mavlink command msg to the mission store in eeprom/fram, but that is quite a lot of work to implement

**Comment by iskess** [comment]
If there is only 1 bit available then perhaps it should be:
0 = Loiter direction as specified in parameters
1= Loiter opposite direction. 
The column should be labeled Reverse Direction, or Rev Turn.

**Comment by magicrub** [comment]
storing the extra bit is related to: https://github.com/diydrones/ardupilot/issues/2391

**Comment by WickedShell** [comment]
This has been supported for quite awhile.
