### ISSUE TITLE
px4fmu-v2  usart1_rx DMA config is unused

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#7226]
px4fmu-v2  usart1_rx DMA config is unused,

board config is set here,
https://github.com/ArduPilot/PX4Firmware/blob/fc46919934b82f3fa64a9b99f5ebe33de8bf6ab0/nuttx-configs/px4fmu-v2/include/board.h#L227

defconfig is not set.
https://github.com/ArduPilot/PX4Firmware/blob/fc46919934b82f3fa64a9b99f5ebe33de8bf6ab0/nuttx-configs/px4fmu-v2/nsh/defconfig#L300

**Comment by OXINARF** [comment]
This is on purpose. That stream is being used for SPI DMA. We could remove the definition from board header, but there is no need since we disabled the USART1 DMA in the board configuration.
