### ISSUE TITLE
Problems with building example sketches on Windows

### ISSUE THREAD

**Issue by Kamil8** [ArduPilot/ardupilot#7228]
#### Issue details
System can't use waf commands. 
![image](https://user-images.githubusercontent.com/33666613/32794983-add3e382-c96a-11e7-9227-26c6f216e178.png)

Dev documentation didn't help.

For me only solution was change operating system to ubuntu. There was no problem to build it, except missing compiler for pixhawk.

**Comment by auturgy** [comment]
Need more details please.
Operating system? which instructions did you follow?

**Comment by auturgy** [comment]
Waf with Windows is a known issue. You can use WSL, to use waf, or build with make. Instructions for both are in the wiki.  If you have suggestions to make the wiki clearer, please submit a pr :)
Thanks.

**Comment by OXINARF** [comment]
Closing this after more than one month without any answer.
