### ISSUE TITLE
RPM problem

### ISSUE THREAD

**Issue by lutinplunder** [ArduPilot/ardupilot#7233]
I am trying to integrate an rpm sensor into my heli code. It is working fine but when I reboot (hard or soft) it gets disabled and I have to manually go into the parameters list and disable the rpm pin and then re-enable it to get it working again.

#### Version
3.5.4.rc1

#### Platform
[  ] All
[  ] AntennaTracker
[ x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Heli_Dual

#### Hardware type
Pixhawk 2.1

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

You are quite likely doing something wrong. Publish your branch on GitHub and ask for help in Gitter, someone will try to look at it.
