### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by acwatkins** [ArduPilot/ardupilot#7242]
#### Issue details
A Dockerfile for easy container creation

#### Platform
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

I noticed there is a Vagrantfile. Is there opposition to adding a Dockerfile for Docker users? I have this file setup for contribution if it is wanted.

**Comment by lvale** [comment]
IMHO that will be a excellent addition

**Comment by magicrub** [comment]
+1

**Comment by lvale** [comment]
@magicrub 
Already a PR https://github.com/ArduPilot/ardupilot/pull/7244#discussion_r151874325 here

**Comment by peterbarker** [comment]
@khancyr gave us a Dockerfile
