### ISSUE TITLE
Copter: code in GCS_Mavlink is always false

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#7272]
MAVLINK_MSG_ID_SET_POSITION_TARGET_GLOBAL_INT handling got unreachable code : 
https://github.com/ArduPilot/ardupilot/blob/46ac0e45aa87873bf46915fcdf9780001ee6b7d3/ArduCopter/GCS_Mavlink.cpp#L1535

**Comment by OXINARF** [comment]
I've changed the title to reflect what actually happens. The code is reachable, it just is always false. I think the yaw_relative can be removed from the SET_POSITION_TARGET_GLOBAL_INT, I would say that in that case it is always a global (not relative) yaw.
