### ISSUE TITLE
Rover: add support for SmartRTL

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7275]
Rover should get SmartRTL so it's less likely to bump into things on it's way home.

**Comment by amilcarlucas** [comment]
Will this require the removal of inertialNav ?

**Comment by rmackay9** [comment]
@amilcarlucas, thankfully "no".  SmartRTL (the library portion at least) was written without any dependency on inertial nav.

**Comment by rmackay9** [comment]
This is in master now.
