### ISSUE TITLE
copter version tags

### ISSUE THREAD

**Issue by mikkab** [ArduPilot/ardupilot#7276]
#### Issue details
Found no git tags for Copter-3.5.3 and Copter-3.5.4. Is there any changes in release procedure?
ArduCopter-stable is latest 3.5.4 only, 3.5.3 is not available

#### Version
3.5.3 and 3.5.4

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
copter

#### Hardware type
pixhawk, pixracer

#### Logs
git log --graph --all --decorate --oneline --simplify-by-decoration

* 917d984 (HEAD -> master, origin/master, origin/HEAD) SITL: support AHRS_ORIENTATION in SITL
| * 284349c (tag: ArduCopter-stable-heli, tag: ArduCopter-stable, origin/Copter-3.5) Copter: version to 3.5.4
| * a5f9c24 (tag: ArduCopter-beta-heli, tag: ArduCopter-beta) Copter: version to 3.5.4-rc2
| * 4322ffd (tag: Copter-3.5.2) Copter: version to 3.5.2
| * c58403a (tag: Copter-3.5.2-rc1) Copter: version to 3.5.2-rc1
...

**Comment by rmackay9** [comment]
Sorry, added!
