### ISSUE TITLE
Ublox AssistNow (AGPS)

### ISSUE THREAD

**Issue by lacion** [ArduPilot/ardupilot#729]
it would be very interesting for mission planner to be able to send A-GPS data to the Ublox GPS 

from http://www.u-blox.com/en/assisted-gps.html AssistNow there is a free version.

this will improve GPS fix times a lot.

**Comment by WickedShell** [comment]
Closing as this won't be implemented at the autopilot level, however the GCS could leverage the GPS injection streams to send the data, so I don't see any ArduPilot specific support required to enable this.
