### ISSUE TITLE
sr0 and sr1 Parameter Description is not visible in in Mission Planer

### ISSUE THREAD

**Issue by bazooka32** [ArduPilot/ardupilot#731]
Hi Dev Team,

the sr0 and sr1 Parameter Description is not visible in Mission Planer

**Comment by WickedShell** [comment]
The documentation is present on the params in the group, looks like its a problem in the parsing script as I don't see it anywhere in the result XML.

**Comment by WickedShell** [comment]
No longer a problem, was fixed some time ago.
