### ISSUE TITLE
Support HIGH_LATENCY data stream

### ISSUE THREAD

**Issue by envirover** [ArduPilot/ardupilot#7341]
#### Issue details
Currently HIGH_LATENCY MAVLink message is not supported by ArduPilot. HIGH_LATENCY message is used by global satellite telemetry SPL (see https://github.com/envirover/SPLRadioRoom). The current implementation of SPL RadioRoom composes HIGH_LATENCY messages from several different messages by requesting multiple data streams. This is not a very efficient and reliable solution.

#### Version
All

#### Platform
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
All

#### Hardware type
All

**Comment by DavidIngraham** [comment]
I would like to +1 this. We will soon have vehicles using iridium, and this message would simplify things greatly.

It will also require support on the GCS side.

**Comment by dagar** [comment]
I'll likely be adding QGC support for the basic HIGH_LATENCY message in the near future. https://github.com/mavlink/qgroundcontrol/pull/4443

The harder part will be making it aware of the special connection type and acting accordingly.

**Comment by DavidIngraham** [comment]
How would heartbeats be handled when sending this message? Would we only send the heartbeat to initiate the connection, then treat the HIGH_LATENCY message as the heartbeat from then on? The GCS will need a heartbeat in the beginning to establish the autopilot family, vehicle type,  and protocol version.

**Comment by dagar** [comment]
Partially TBD, but what I've discussed with Don is making HIGH_LATENCY (or a slightly changed 2nd iteration) a substitute for HEARTBEAT.

**Comment by dagar** [comment]
Working on a second iteration of HIGH_LATENCY to fix a few shortcomings. https://github.com/mavlink/mavlink/pull/814

**Comment by amilcarlucas** [comment]
HIGH_LATENCY is now deprecated, please implement HIGH_LATENCY2 instead

**Comment by peterbarker** [comment]
This was implemented in #17390
