### ISSUE TITLE
Pixhawk: "rgb led and internal led" parallel support

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#735]
I connected the external I2C rgb led with the external compass integrated in the gps unit, simply by making a parallel between the cables (i don't have the I2C splitter here), unfortunately known that when the external led disables the internal one.
I think it is very useful instead leave them both enabled, a split view is always better than one.

**Comment by OXINARF** [comment]
There is a newer issue requesting this (#6088) so I'm closing this one.
