### ISSUE TITLE
ArduCopter: unable to change sounds

### ISSUE THREAD

**Issue by kane111** [ArduPilot/ardupilot#7378]
I want to add custom sounds to my Pixhawk2 board running ArduCopter firmware. I have followed the guide mentioned below but the changes do not reflect when the upload the custom compiled firmware.

http://diydrones.com/forum/topics/px4-star-wars-startup-tone

Can someone help me out?

**Comment by khancyr** [comment]
not an issue but user related question. Moreover, tune handling as change to something simplier, so this isn't relevant anymore. closing
