### ISSUE TITLE
ArduPlane/quadplane: vehicle jerks when executing VTOL_LAND

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#7393]
#### Issue details
In an AUTO mission, as soon as the vehicle reaches the VTOL_LAND waypoint, it looks like it switches controller and jerks for a couple of seconds, causing high pitch+roll+yaw, until it gets back to level and starts descending.

<img width="1182" alt="screen shot 2017-12-11 at 4 57 45 pm" src="https://user-images.githubusercontent.com/6870452/33858214-73ac32ba-de94-11e7-9b39-09e3bfbd8b6e.png">

#### Version
3.8.2-dev

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
X8 quadplane

#### Hardware type
PH2.1

**Comment by DavidIngraham** [comment]
Can you provide a log of the flight? Also, I'm not sure that I understand exactly what the problem is.

**Comment by IamPete1** [comment]
not much we can do without the log, if this is still a issue please re-open and share a 4.1 log.
