### ISSUE TITLE
log power sources on PX4/Pixhawk

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#740]
log what power source we are using on boards that support sensing supplies
we may need a parameter for what power supplies we expect to have, so if on backup then refuse to arm
we also need to log the servo power rail voltage

**Comment by OXINARF** [comment]
We log a POWR message that has a Flags field saying what power sources are being sensed. In the same message we log the servo rail voltage.
So this looks done. Feel free to re-open if you think something is missing.
