### ISSUE TITLE
Rover: support optical flow

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7420]
At least one user has asked that we add support for optical flow in Rover.  With some upcoming changes from Paul, we should be able to support optical flow sensors facing in any direction which will likely make it more useful for Rover.

**Comment by MDB22** [comment]
@rmackay9 any word on whether Rover does/will support PX4 Flow?

**Comment by rmackay9** [comment]
@MDB22, It hasn't been added yet.  I'm not actively working on it actually, for me there are a number of higher priority tasks including improving object avoidance so I can't make any promises on when this will be added.  Maybe another developer will take this task on .. I can't say really..

**Comment by MDB22** [comment]
@rmackay9 thanks for your response, I saw a separate thread with several developers making progress on it, but nothing concrete for the main branch. Thanks anyway :)

**Comment by rmackay9** [comment]
After only 5 years this task has finally be completed with PR https://github.com/ArduPilot/ardupilot/pull/21510.  This will go out with Rover-4.4.0 which should enter beta testing in early Jan 2023.
