### ISSUE TITLE
Pixhackv3 onboard compass issue

### ISSUE THREAD

**Issue by urlu75** [ArduPilot/ardupilot#7431]
#### Issue details
Issue concerns the PIxhackv3 board.
Only one compass is detected. 
with AC3.4.6, both internal compass are detected.

#### Version
AC3.5.4

#### Platform
[X] All
[  ] AntennaTracker
[ ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
HEXA

#### Hardware type
Pixhack v3 

#### Logs
3.5.4 console log : [3.5.4.txt](https://github.com/ArduPilot/ardupilot/files/1573570/3.5.4.txt)

3.4.6 console log : [3.4.6.txt](https://github.com/ArduPilot/ardupilot/files/1573571/3.4.6.txt)

**Comment by IamPete1** [comment]
sorry we never got to this.
