### ISSUE TITLE
Climb rate and Thr.out issue when switching from RLT to Loiter

### ISSUE THREAD

**Issue by SergeyBokhantsev** [ArduPilot/ardupilot#7435]
#### Issue details
Steps:
1. Initialize RTL. Copter climbs to RTL heigth, moves to launch location and begins descending.
2. At RTL-descending phase switch to Loiter

Result: I can hear motors cut-off for a moment (CTUN.ThO = 0 in log), then copter stabilizes.

Two issues here:
- Why CTUN desired climb rate goes down rapidly after switching to Loiter
- Why CTUN throttle out goes zero when my THR_MIN > 0?

Some additional info here: https://discuss.ardupilot.org/t/throttleout-is-zero-for-a-moment-when-switched-from-rtl-to-loiter/22663/3

#### Version
3.5.3

#### Platform
[ x] Copter

#### Airframe type
X

#### Hardware type
Pixracer

#### Logs
https://www.dropbox.com/s/zfacgo25mcm448i/00000022.BIN?dl=0

**Comment by lthall** [comment]
I understand what is happening here. This will be fixed.

**Comment by SergeyBokhantsev** [comment]
hi @lthall, what is the current status of this?

**Comment by rmackay9** [comment]
I think this issue is fixed in master and Copter-3.6.  Below is a SITL test in which I switched the vehicle into Loiter mode a couple of times as it was descending in RTL.  No throttle spike as far as I can see.

![thr-rtl-to-loit](https://user-images.githubusercontent.com/1498098/47474736-55502100-d853-11e8-96e9-6197945dcc35.jpg)

**Comment by rmackay9** [comment]
.. although it's possible that the way I'm testing is the problem.  From looking at the logs from @SergeyBokhantsev above, it's clear the desired climb rate was not being initialised correctly.
![sergey-desclimbrate](https://user-images.githubusercontent.com/1498098/47474899-33a36980-d854-11e8-8960-41844508c3c6.jpg)

I'll check with @lthall if he remembers the status of this.  @SergeyBokhantsev if you could try to reproduce this with Copter-3.6 that would also be great.  I think we should continue this discussion in the support forums so I've created a topic [here](https://discuss.ardupilot.org/t/throttle-drop-when-switching-to-loiter-from-rtl/34388).

**Comment by SergeyBokhantsev** [comment]
@rmackay9 
Test to repro: https://www.dropbox.com/s/tne9o1r46nogoia/test.txt?dl=0
Produces the same issue with SITL:
![image](https://user-images.githubusercontent.com/9112882/48511789-6394ca00-e860-11e8-8f8c-04f10596ef5f.png)

Also I've run same test with [this condition](https://github.com/ArduPilot/ardupilot/blob/e702ca7202b8deaf3141a3829f7377b7d9396ab4/ArduCopter/mode_loiter.cpp#L28) removed (but not the condition body).
This change does fix the issue 
![image](https://user-images.githubusercontent.com/9112882/48512126-5f1ce100-e861-11e8-8a35-a51ff8ab7a26.png)

thought I'm not sure why that condition here and if this is correct way to fix. Another concern is that the same pieces of code are in another modes init().

**Comment by lthall** [comment]
All this code has been rewritten in 4.1 with more stringent initialisation.
