### ISSUE TITLE
ardurover not respond to control signals by using mavros

### ISSUE THREAD

**Issue by wael-abdin** [ArduPilot/ardupilot#7456]
#### Issue details
i am new in mavros, and i want to control a motor by using mavros, 
i have APM V2.5 and flash it by ardurover by using Mission planner
i connect this APM by ESC using output channel No 1 and connect a motor to the ESC

my problem is when i run the mavros node the motor start run in a fixed speed and not change it's speed although i sent cmd to change the speed of the motor
the following lines explaining what i did in details;

I run the following command to run the mavros;  
`roslaunch mavros apm2.launch fcu_url:=/dev/ttyACM0:115200`
after executing the motor run in a fixed speed

then i transfer the mode to Guided by using the following cmd;
`rosrun mavros mavsys mode -c GUIDED`

then i puplished the following data to /mavros/rc/override by the following cmd;
`rostopic pub /mavros/rc/override mavros_gs/OverrideRCIn "channels: [1200, 1200, 1200, 1200, 1200, 1200, 1200, 1200]"`
i changed the data many times but the problem is the motor speed always constant

the following is the data show after run the mavros cmd;
`wael@wael-Inspiron-N5010:~/catkin_ws$ roslaunch mavros apm2.launch fcu_url:=/dev/ttyACM0:115200
... logging to /home/wael/.ros/log/6ef236ba-e971-11e7-92f7-606720841920/roslaunch-wael-Inspiron-N5010-6737.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wael-Inspiron-N5010:32868/

SUMMARY

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 0.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 0.0
 * /mavros/fcu_url: /dev/ttyACM0:115200
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: fcu
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/plugin_blacklist: ['actuator_contro...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.0
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    mavros (mavros/mavros_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[mavros-1]: started with pid [6756]
[ INFO] [1514210227.514842219]: FCU URL: /dev/ttyACM0:115200
[ INFO] [1514210227.515260751]: serial0: device: /dev/ttyACM0 @ 115200 bps
[ INFO] [1514210227.515767402]: GCS bridge disabled
[ INFO] [1514210227.559659364]: Plugin 3dr_radio loaded and initialized
[ INFO] [1514210227.559949979]: Plugin actuator_control blacklisted
[ INFO] [1514210227.559979137]: Plugin altitude blacklisted
[ INFO] [1514210227.618908755]: Plugin cam_imu_sync loaded and initialized
[ INFO] [1514210227.625284410]: Plugin command loaded and initialized
[ INFO] [1514210227.625420237]: Plugin distance_sensor blacklisted
[ INFO] [1514210227.625445699]: Plugin ftp blacklisted
[ INFO] [1514210227.635965601]: Plugin global_position loaded and initialized
[ INFO] [1514210227.636906269]: Plugin hil_controls loaded and initialized
[ INFO] [1514210227.637044504]: Plugin image_pub blacklisted
[ INFO] [1514210227.644655900]: Plugin imu_pub loaded and initialized
[ INFO] [1514210227.653388163]: Plugin local_position loaded and initialized
[ INFO] [1514210227.654404590]: Plugin manual_control loaded and initialized
[ INFO] [1514210227.654539809]: Plugin mocap_pose_estimate blacklisted
[ INFO] [1514210227.658188033]: Plugin param loaded and initialized
[ INFO] [1514210227.658312716]: Plugin px4flow blacklisted
[ INFO] [1514210227.662886059]: Plugin rc_io loaded and initialized
[ INFO] [1514210227.663027752]: Plugin safety_area blacklisted
[ INFO] [1514210227.667174828]: Plugin setpoint_accel loaded and initialized
[ INFO] [1514210227.667234123]: Plugin setpoint_attitude blacklisted
[ INFO] [1514210227.673783633]: Plugin setpoint_position loaded and initialized
[ INFO] [1514210227.687578301]: Plugin setpoint_raw loaded and initialized
[ INFO] [1514210227.690639482]: Plugin setpoint_velocity loaded and initialized
[ INFO] [1514210227.697211827]: Plugin sys_status loaded and initialized
[ INFO] [1514210227.701536919]: Plugin sys_time loaded and initialized
[ INFO] [1514210227.702975027]: Plugin vfr_hud loaded and initialized
[ INFO] [1514210227.703122576]: Plugin vibration blacklisted
[ INFO] [1514210227.703162309]: Plugin vision_pose_estimate blacklisted
[ INFO] [1514210227.703196554]: Plugin vision_speed_estimate blacklisted
[ INFO] [1514210227.707718556]: Plugin waypoint loaded and initialized
[ INFO] [1514210227.707913116]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1514210227.707957012]: Built-in MAVLink package version: 2017.12.12
[ INFO] [1514210227.707987431]: Built-in MAVLink dialect: ardupilotmega
[ INFO] [1514210227.708016127]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ERROR] [1514210230.739177581]: FCU: Calibrating barometer
[ INFO] [1514210230.743176587]: CON: Got HEARTBEAT, connected. FCU: ArduPilotMega
[ERROR] [1514210231.778468060]: FCU: command received: 
[ INFO] [1514210231.786587190]: VER: 1.1: Capabilities 0x0000000000000000
[ INFO] [1514210231.786747897]: VER: 1.1: Flight software:     00000080 (705d3d56)
[ INFO] [1514210231.786921200]: VER: 1.1: Middleware software: 00000000 (        )
[ INFO] [1514210231.787078035]: VER: 1.1: OS software:         00000000 (        )
[ INFO] [1514210231.787151379]: VER: 1.1: Board hardware:      00000000
[ INFO] [1514210231.787196496]: VER: 1.1: VID/PID: 0000:0000
[ INFO] [1514210231.787239551]: VER: 1.1: UID: 0000000000000000
[ WARN] [1514210231.787510768]: CMD: Unexpected command 520, result 0
[ERROR] [1514210232.101673461]: FCU: Warming up ADC...
[ERROR] [1514210232.600966732]: FCU: Beginning INS calibration; do not move vehicle
[ERROR] [1514210232.740213029]: FCU: <startup_ground> GROUND START
[ERROR] [1514210234.737536396]: FCU: Initialising APM...
[ERROR] [1514210235.842738787]: FCU: 
 Ready to drive.
[ WARN] [1514210235.863226846]: GP: No GPS fix
[ WARN] [1514210235.887751514]: TM: Wrong FCU time.
[ERROR] [1514210240.794844952]: FCU: ArduRover v2.51-beta (705d3d56)
[ERROR] [1514210240.839692691]: FCU: Failsafe trigger 0x1
[ INFO] [1514210244.797719972]: PR: parameters list received
[ INFO] [1514210245.767647510]: WP: mission received
`

The following data is the state subscribe

`header: 
  seq: 47
  stamp: 
    secs: 1514208890
    nsecs: 197449012
  frame_id: ''
connected: True
armed: True
guided: True
mode: GUIDED
---
`

#### Version

Ubuntu 14.04
Ros Indigo

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[x] Rover
[  ] Submarine

#### Airframe type
ardurover
#### Hardware type
APM V2.5 and flashing it by ardurover by using Mission planner

how can i do this;
and also is there any related tutorial can help me
thank you in advance

**Comment by rmackay9** [comment]
Hi there.  so the APM hardware is very old now - our last firmware for it was written about 3 years ago.  It would be much better to buy a more powerful flight controller.  The Pixhawk/Cube is the most popular but there are other options:  http://ardupilot.org/rover/docs/common-autopilots.html

Once you have one of those, if you load the lastest beta (Rover-3.2.0-rc3) it should work.

Support request should really go into the forums here so I will close this request.  https://discuss.ardupilot.org/c/ardurover/rover-3-2

Thanks for using ArduPilot!
