### ISSUE TITLE
How to change px4 microprocessor

### ISSUE THREAD

**Issue by afeizinejad** [ArduPilot/ardupilot#7465]
#### Issue details
Hello.
I'm going to change the Pixhawk processor from stm32f4 to stm32f7. How do I change the code to be compatible with the new processor?
Any help would be appreciated.
Thanks.

#### Version
ArduCopter V3.0.1

#### Platform

[  ] Copter

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
pixhawk

**Comment by magicrub** [comment]
already done. 

make px4-v4

**Comment by auturgy** [comment]
V4 is just another f4 target.
The v5 is an f7, but I think there are only 20 of them, and no ArduPilot build target yet.

Regards,

James

**Comment by DavidIngraham** [comment]
Hello @afeizinejad, Support for F7 processors is being added through the ChibiOS port. I encourage you to look at the ArduPilot Chibios gitter channel for support: https://gitter.im/ArduPilot/ChibiOS

The chibios team is creating tools that make it trivial to port ArduPilot to new STM32 processors. That effort is well tracked, so I think we can close this issue now.
