### ISSUE TITLE
Send MAVLINK_MSG_ID_GPS_GLOBAL_ORIGIN message on home position update

### ISSUE THREAD

**Issue by billbonney** [ArduPilot/ardupilot#747]
Currently in the GCS to update the home position, we need to read WP0 from the vehicle. If APM could actually send the update using the GPS_GLOBAL_ORIGIN message, it would make this much easier to implement.

Also adding the SET_GPS_GLOBAL_ORIGIN would allow the GCS to set the home position. (This probably benefits plane/rover, since Copter sets the home position on armed)

Is this a good idea, what are the challenges?

**Comment by WickedShell** [comment]
What is better? HOME_POSITION or GPS_GLOBAL_ORIGIN they both are fairly similar, in someways HOME_POSITION is better for copter (copter could report the slope of what its taking off from).

I'm not sure which we want to go with, but I would like to get this in master soon.

**Comment by rmackay9** [comment]
Either works for me.  Just from the name I prefer the HOME_POSITION message.  Somewhat strange that there are two.  Maybe the GPS_GLOBAL_ORIGIN is meant to be used for the EKF origin?  That would seem to make sense to me.  in which case we could send both.  There's a set_home() function in Copter's commands.cpp file that could be updated to send the messages.

**Comment by DonLakeFlyer** [comment]
QGC uses HOME_POSITION for showing home on the map.

**Comment by WickedShell** [comment]
HOME_POSITION appears to be sent by all vehicles, I'm opposed to duplicating GPS_GLOBAL_ORIGIN for the same information. Reporting the EKF origin with it is definitely possible, do people feel thats valuable/worth implementing? I'd like to close the issue otherwise.

**Comment by WickedShell** [comment]
HOME_POSITION covers this, closing out as done.
