### ISSUE TITLE
Plane: add support for multiple airspeed sensors

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#7479]
#### Issue details
This is a feature request :-)

Since airspeed sensors / pitot tubes are pretty crucial for fixed wing flights and that a malfunction will very likely lead to a crash, it would be great to add support for multiple airspeed sensors.

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Comment by magicrub** [comment]
Closing, duplicate of https://github.com/ArduPilot/ardupilot/issues/6670

**Comment by WickedShell** [comment]
Worth noting the PR for this is #7174 and already submitted.

**Comment by magicrub** [comment]
ahh yes, there it is. I thought there was a PR about that!
