### ISSUE TITLE
Copter: Thr Max Affects Alt_Hold Climb Rate

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#748]
If user enters a reduced Thr Max, such as 800, in order to control an overpowered quad in Stabilize mode, then the climb rate in Alt Hold is reduced by the same fraction.  

I believe this is because the g.rc3.range is set using Thr Max as the upper end: 

g.rc_3.set_range(g.throttle_min, g.throttle_max);

But this line in get_pilot_desired_climb_rate() does the scaling on the incoming throttle assuming it has a full 1000 PWM range:

desired_rate = (int32_t)g.pilot_velocity_z_max \* (throttle_control-THROTTLE_IN_DEADBAND_TOP) / (THROTTLE_IN_MIDDLE - THROTTLE_IN_DEADBAND);

There are a number of possible solutions to this.  My preferred one would be to do something like what TradHelis do now with StabCol.  That is, g.rc3 range is always set to 1000, and we simply scale the manual throttle output by a ratio of ThrMin to ThrMax.

It is probably still appropriate to use ThrMax as a constrain on the output of the auto-throttle.

output =  constrain_float(p+i+d+g.throttle_cruise, g.throttle_min, g.throttle_max);

**Comment by lthall** [comment]
old
