### ISSUE TITLE
There is too many submodule, but all of them are useful?

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#7480]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
`
"Submodule 'modules/PX4Firmware' (git://github.com/ArduPilot/PX4Firmware.git) registered for path 'modules/PX4Firmware'
Submodule 'modules/PX4NuttX' (git://github.com/ArduPilot/PX4NuttX.git) registered for path 'modules/PX4NuttX'
Submodule 'modules/gbenchmark' (git://github.com/google/benchmark.git) registered for path 'modules/gbenchmark'
Submodule 'gtest' (git://github.com/ArduPilot/googletest) registered for path 'modules/gtest'
Submodule 'modules/mavlink' (git://github.com/ArduPilot/mavlink) registered for path 'modules/mavlink'
Submodule 'modules/uavcan' (git://github.com/ArduPilot/uavcan.git) registered for path 'modules/uavcan'
Submodule 'modules/waf' (git://github.com/ArduPilot/waf.git) registered for path 'modules/waf'
Cloning into 'modules/PX4Firmware'...
Submodule path 'modules/PX4Firmware': checked out 'fc46919934b82f3fa64a9b99f5ebe33de8bf6ab0'
Submodule 'Tools/gencpp' (https://github.com/ros/gencpp.git) registered for path 'Tools/gencpp'
Submodule 'Tools/genmsg' (https://github.com/ros/genmsg.git) registered for path 'Tools/genmsg'
Submodule 'mavlink/include/mavlink/v1.0' (git://github.com/mavlink/c_library.git) registered for path 'mavlink/include/mavlink/v1.0'
Submodule 'src/lib/DriverFramework' (https://github.com/PX4/DriverFramework.git) registered for path 'src/lib/DriverFramework'
Submodule 'src/lib/ecl' (https://github.com/PX4/ecl.git) registered for path 'src/lib/ecl'
Submodule 'src/lib/matrix' (https://github.com/PX4/Matrix.git) registered for path 'src/lib/matrix'
Submodule 'src/modules/uavcan/libuavcan' (git://github.com/UAVCAN/libuavcan.git) registered for path 'src/modules/uavcan/libuavcan'
Cloning into 'Tools/gencpp'...
Submodule path 'modules/PX4Firmware/Tools/gencpp': checked out '26a86f04bcec0018af6652b3ddd3f680e6e3fa2a'
Cloning into 'Tools/genmsg'...
Submodule path 'modules/PX4Firmware/Tools/genmsg': checked out '72f0383f0e6a489214c51802ae12d6e271b1e454'
Cloning into 'mavlink/include/mavlink/v1.0'...
Submodule path 'modules/PX4Firmware/mavlink/include/mavlink/v1.0': checked out 'bf251caef3dbf610e5152115a2d81e00e54ab7e7'
Cloning into 'src/lib/DriverFramework'...
Submodule path 'modules/PX4Firmware/src/lib/DriverFramework': checked out 'd6ef668f4564e1c158910c52df7d71114bd2ca4e'
Submodule 'cmake_hexagon' (https://github.com/ATLFlight/cmake_hexagon.git) registered for path 'cmake/cmake_hexagon'
Submodule 'dspal' (https://github.com/PX4/dspal) registered for path 'dspal'
Cloning into 'cmake/cmake_hexagon'...
Submodule path 'modules/PX4Firmware/src/lib/DriverFramework/cmake/cmake_hexagon': checked out 'ba681fcd0d4c5ac95636dd8e9d8536dbd81beabd'
Cloning into 'dspal'...
Submodule path 'modules/PX4Firmware/src/lib/DriverFramework/dspal': checked out '8f39699c6b79447f32f0714629da790bbf271aa5'
Submodule 'test/dspal_tester/cmake_hexagon' (https://github.com/ATLFlight/cmake_hexagon.git) registered for path 'test/dspal_tester/cmake_hexagon'
Cloning into 'test/dspal_tester/cmake_hexagon'...
Submodule path 'modules/PX4Firmware/src/lib/DriverFramework/dspal/test/dspal_tester/cmake_hexagon': checked out 'ba681fcd0d4c5ac95636dd8e9d8536dbd81beabd'
Cloning into 'src/lib/ecl'...
Submodule path 'modules/PX4Firmware/src/lib/ecl': checked out 'f86ef3478219b4b1c31e17b8f308df4b69eda2f7'
Submodule 'matrix' (https://github.com/PX4/Matrix) registered for path 'matrix'
Cloning into 'matrix'...
Submodule path 'modules/PX4Firmware/src/lib/ecl/matrix': checked out '95e3d7d6ce5274d9b7fec76c0093dc5eaa381abf'
Cloning into 'src/lib/matrix'...
Submodule path 'modules/PX4Firmware/src/lib/matrix': checked out '07fba8322a16cb2dac47e6a8ac7d21ec346313ff'
Cloning into 'src/modules/uavcan/libuavcan'...
Submodule path 'modules/PX4Firmware/src/modules/uavcan/libuavcan': checked out '702f6f05608885d3be993edb01394212bd2dade1'
Submodule 'dsdl' (https://github.com/UAVCAN/dsdl) registered for path 'dsdl'
Submodule 'libuavcan/dsdl_compiler/pyuavcan' (https://github.com/UAVCAN/pyuavcan) registered for path 'libuavcan/dsdl_compiler/pyuavcan'
Cloning into 'dsdl'...
Submodule path 'modules/PX4Firmware/src/modules/uavcan/libuavcan/dsdl': checked out '9804a3e6972825586be252ce08dd899f44994b14'
Cloning into 'libuavcan/dsdl_compiler/pyuavcan'...
Submodule path 'modules/PX4Firmware/src/modules/uavcan/libuavcan/libuavcan/dsdl_compiler/pyuavcan': checked out 'c58477a644d20ccf95a20c151f3a0402f271c3b8'
Submodule 'dsdl' (https://github.com/UAVCAN/dsdl) registered for path 'dsdl'
Cloning into 'dsdl'...
Submodule path 'modules/PX4Firmware/src/modules/uavcan/libuavcan/libuavcan/dsdl_compiler/pyuavcan/dsdl': checked out 'fd12483ddd4e58242d61d74a163e7aeaa1e0f466'
Cloning into 'modules/PX4NuttX'...
Submodule path 'modules/PX4NuttX': checked out '1bcae90b334206c92d57298f5b957247a8f3a85e'
Cloning into 'modules/gbenchmark'...
Submodule path 'modules/gbenchmark': checked out '006d23ccca1375a973b7fae0cc351cedb41b812a'
Cloning into 'modules/gtest'...
Submodule path 'modules/gtest': checked out 'c99458533a9b4c743ed51537e25989ea55944908'
Cloning into 'modules/mavlink'...
Submodule path 'modules/mavlink': checked out 'a8bb1bf5d4915862eb9c6f4c8ad6cdb7acee56ef'
Submodule 'pymavlink' (git://github.com/ArduPilot/pymavlink.git) registered for path 'pymavlink'
Cloning into 'pymavlink'...
Submodule path 'modules/mavlink/pymavlink': checked out '6135d77151a775603c58c4d41d8b42ad28f461c4'
Cloning into 'modules/uavcan'..."
`

**Comment by magicrub** [comment]
All of them are there for a reason. Is there a problem with them?
