### ISSUE TITLE
ArduCopter AP_Arming: "Arm" instead of "PreArm"

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/ardupilot#7487]
here https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/AP_Arming.cpp#L581 it propably should be "Arm: Compass..." instead of "PreArm: Compass...".

**Comment by auturgy** [comment]
Happy New Year Olli!
Thanks for pointing that out, I think you’re right. Any chance you might be willing to use this as GitHub PR practice?

**Comment by lvale** [comment]
@olliw42 Yes, a nice easy soft one to start 

Happy New Year :)

**Comment by olliw42** [comment]
Happy New Year too, to both of you, and anyone else :)

there is soo many other stuff I would want to do too

**Comment by rmackay9** [comment]
Yup, closing!
