### ISSUE TITLE
How to store previous parameter and then get it later?

### ISSUE THREAD

**Issue by hujin9190** [ArduPilot/ardupilot#7497]
#### Issue details
I want to store a PWM value in a parameter and then get the value later. I followed the tutorial and created a parameter. Then, I used set_value and get_value functions to operate the value. However, it still gets zero each time rather than the set value. Can anyone help?

#### Version
It doesn't matter

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
It doesn't matter

#### Hardware type
pixhawk

**Comment by hujin9190** [comment]
I need to do some calculation during the flight and get the new PWM based on the previous one. Thus, I need to store the previous status value first. If anyone can help, I very appreciate it.

**Comment by peterbarker** [comment]
On Sat, 6 Jan 2018, hujin9190 wrote:

> I need to do some calculation during the flight and get the new PWM based
> on the previous one. Thus, I need to store the previous status value first.
> If anyone can help, I very appreciate it.

Have a look at the way hover throttle is done.

**Comment by WickedShell** [comment]
This is a support topic rather then a feature request/issue. Please take it to [gitter](gitter.im/ardupilot/ardupilot) or [discuss](https://discuss.ardupilot.org) if you still need more help.
