### ISSUE TITLE
ArduPlane: aggressive throttle changes when straight and level 

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#7499]
#### Issue details
During flight in AUTO cruise and on a straight and level leg, I noticed our current goes up and down by quite a bit all the time.  Looking at RCOU.C3 shows me the FC keeps changing the throttle, rather aggressively.  Very little wind.

Here's an example showing 20A+ jumps within 1-2s:

<img width="1232" alt="screen shot 2018-01-06 at 8 52 22 pm" src="https://user-images.githubusercontent.com/6870452/34646045-89dfb20c-f323-11e7-8fe6-07c02ad8e4bc.png">

This seems inefficient.

Is it trying too hard to keep the airspeed constant?

For what it's worth I use

> THR_SLEWRATE=20

#### Version
ArduPlane 3.8.2

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Fixed wing

#### Hardware type
PH2.1

**Comment by magicrub** [comment]
With THR_SLEWRATE=20 then your throttle is not capable of changing very fast. Heavily slewed. The current chasing stuff is often a sign of other tuning issues needing tweaking, such as the pitch. Have you played with the TECS controller much?

**Comment by magicrub** [comment]
Without a log, I'm guessing.. but generally speaking if you do then it's using the throttle to maintain airspeed. If airspeed is sloppy then throttle will be sloppy (and vice versa). There's a coupling there. Could be sensor problem or it could be pitch/throttle/tuning settings.

**Comment by expntly** [comment]
@magicrub 

Here's a log (250MB): https://drive.google.com/open?id=1ls9yVhjSz35V6mwTIUgS5fO6wtWALJdg

Haven't played much with TECS, but that might be a good idea.  I just stumbled upon TECS_THR_DAMP, currently at default 0.5.  I'll try and see if that helps in the meantime.  Thanks!

**Comment by expntly** [comment]
@magicrub 

So I've been able to reproduce with SITL.

I've played with a few TECS parameters and TECS_TIME_CONST seems to help but I feel like it's hiding the underlying issue.

Here's with TECS_TIME_CONST=5 (default): 
<img width="1538" alt="screen shot 2018-01-15 at 10 19 36 pm" src="https://user-images.githubusercontent.com/6870452/34971747-3df99bfc-fa42-11e7-990a-34795e3f7d0a.png">
Log: [00000008.BIN.zip](https://github.com/ArduPilot/ardupilot/files/1633617/00000008.BIN.zip)

Here's  with TECS_TIME_CONST=10: 
<img width="1526" alt="screen shot 2018-01-15 at 10 19 47 pm" src="https://user-images.githubusercontent.com/6870452/34971748-4110948a-fa42-11e7-9f10-a6856d1e2ff3.png">
Log: [00000009.BIN.zip](https://github.com/ArduPilot/ardupilot/files/1633618/00000009.BIN.zip)

Plotting pitch related data seems to be quite correlated, but I can't figure out which direction the causality goes.

Any ideas?

**Comment by magicrub** [comment]
@expntly Well done! Having a repeatable SITL test is surely the way to help us track this down. Thank you!

**Comment by expntly** [comment]
I'd be curious to see if other people have seen it in their logs, especially on a "long" straight and level flight?

**Comment by SlipstreamFPV** [comment]
I've had this issue too. It's very hard to get AUTO and CRUISE to fly efficiently as the motor is constantly accelerating. Good work expntly, hopefully the devs can track it down now.

**Comment by magicrub** [comment]
I'm terribly sorry we haven't looked into this yet. Thank you @expntly for the logs. We'll get to it!

**Comment by expntly** [comment]
We're flying with TECS_TIME_CONST at 7 but we're still seeing the throttle all over the place.

@magicrub Anything you'd like us to test?

**Comment by expntly** [comment]
@magicrub Do you know if there's been commits around this issue?  Happy to go out there and try if there is.

**Comment by Naterater** [comment]
This is my opinion that I have gained with testing data. Low-pitch props are VERY sensitive to airspeed and often make the current very noisy. Higher pitch props really level-out that current curve and prevent spikes. 

I can't say I have the same experience with the throttle changing so rapidly. Maybe we all need to just increase TECS_THR_DAMP. Mine is at 0.8, and my TECS time constant is 5.

30 minutes of data:
![image](https://user-images.githubusercontent.com/35429159/50720952-d2321f00-107c-11e9-8a1d-1baa70cbec48.png)

For 2 minutes of data:
![image](https://user-images.githubusercontent.com/35429159/50720978-30f79880-107d-11e9-8c7c-50b250efda08.png)

I really think this may be a setup/support/tuning issue that doesn't require a code change. Maybe the defaults should change?

**Comment by SlipstreamFPV** [comment]
Agreed.

**Comment by IamPete1** [comment]
Since there has been no further reports and @Naterater thinks this we should probably not a code issue, I think we should close.

**Comment by SlipstreamFPV** [comment]
Just to check, this isn’t related to the TECS issue with throttle input noise being amplified by the system leading to an oscillation of the throttle/pitch control loop?

**Comment by IamPete1** [comment]
@SlipstreamFPV That sounds like a separate issue. Maybe you could open a new issue to track it if there is not one already.
