### ISSUE TITLE
Copter: teachable Simple

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#750]
It would be very useful to redefine the direction of flight of the Simple bow without necessarily landing, move the multirotor, rearm and takeoff again.
This feature already exists on other famous electronic flight, is called "teachable carefree".
To activate the new bow during flight is necessary that the code reads the change high/low in the pwm state of CH7 (assigned to Simple or SuperSimpe) for "x seconds", for example by switching from 1100 to 1520 pwm (medium range) or from 1100 to 1940 (max range) for 3 or 4 times in less than two seconds.
This simple method would avoid to use another channel for this feature.

**Comment by Naterater** [comment]
I'm not sure I understand. Simple mode has been around for a while based on the takeoff location. I'm unsure why the direction of the simple mode would need to change. Can you explain this a little more and tell me if its still relevant?

**Comment by robustini** [comment]
> 
> 
> I'm not sure I understand. Simple mode has been around for a while based on the takeoff location. I'm unsure why the direction of the simple mode would need to change. Can you explain this a little more and tell me if its still relevant?

Simple, being able to set the bow direction in flight as a reference for the Simple, skipping the one stored during take-off.
With DJI it can be done.
