### ISSUE TITLE
Quadcopter: One motor may stop intermittently during flight when I set MOT_SPIN_MIN = MOT_SPIN_ARM = 0 

### ISSUE THREAD

**Issue by gostil** [ArduPilot/ardupilot#7503]
#### Issue details
I set MOT_SPIN_MIN = MOT_SPIN_ARM = 0 to start with no running motors. When I increase the throttle sometimes any one of the quad motors would not run, or stop running after a while. This is more apparent when I slightly increase the throttle, after which the rpm of the motors automatically starts increasing in the stabilize mode. 
#### Version
APM Copter V 3.5.4 Quad. (Frame type H)

#### Platform
[  ] Copter

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Quad H type

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
pixhawk,
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by kd0aij** [comment]
Since MOT_SPIN_MIN is zero, shouldn't you expect this to happen?

**Comment by lthall** [comment]
This is expected. I term build up will take one of the motors to zero again unless you are in the air.
