### ISSUE TITLE
Documentation: Need to Modify Readme.md to remove references to DroneCode

### ISSUE THREAD

**Issue by lordneeko** [ArduPilot/ardupilot#7512]
#### Issue details
ArduPilot and DroneCode have gone separate ways. References should be removed where appropriate.

**Comment by Pedals2Paddles** [comment]
Where? I don't see any reference to DroneCode anywhere in the readme file.

**Comment by lordneeko** [comment]
totally my bad. I was looking on a fork. the ArduPilot master doesn't have it ><
