### ISSUE TITLE
Copter: Additional Hex propeller configuration

### ISSUE THREAD

**Issue by lthall** [ArduPilot/ardupilot#7524]
Add hex propeller configuration that may be less susceptible to motor failure:

To quote @tuloski -
Basically changing the standard configuration of hexa with alternating propellers rotation PNPNPN, using a configuration PPNNPN can ensure that in 4 failures you keep the controllability, in 2 failures you don't. It is very interesting to implement probably. And btw in the two cases where you don't have full controllability, you can still loose yaw control, but land safely having the thrust, roll and pitch.

https://arxiv.org/pdf/1403.5986.pdf

This may require come creative coefficient selection to achieve the best results.

The propeller arrangement should be from front right CW, CW, CCW, CW, CCW, CCW

**Comment by abhayjindal51** [comment]
Hi,@Ithall I want to work on this issue.

**Comment by lthall** [comment]
Hi @abhayjindal51 I just saw your reply as you got my name wrong :)
