### ISSUE TITLE
Problems with tailsitter-plane configuration

### ISSUE THREAD

**Issue by illu92** [ArduPilot/ardupilot#7530]
Hi! i am trying a tailsitter drone with 2 motors (without tilt rotation)[servo function 73 and 74] and 2 ailerons, that works as elevons [servo function 77 and 78]

#### Issue details
My problem is when I tried to fly it, in Qhover mode (or QLoiter) it is super instable.

What I see, in FWBA mode (like a plane) when i move the controls in my RC, the elevons move normally.
But when I put QHover mode, if i move very little the rc control (like 1% or 2%) it is translated to a huge movement in the elevon (like a 60 - 70 %)

How can i solve it?

#### Version
3.8.3

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Tailsitter

#### Hardware type
Pixhawk

#### Logs
i don't have log for the moment

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
