### ISSUE TITLE
quadplane plugin for gazebo

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#7544]
#### Issue details
Is there a quadplane model for gazebo?
We have QuadPlane models for RealFlight  [SITL Models](https://github.com/ArduPilot/SITL_Models/tree/master/RealFlight/Tridge) , but we don't have similar models for gazebo.
**RealFlight is not free for customers.**
#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
No, there isn't one. Please ask these questions in Gitter chat (http://gitter.im/ArduPilot/ardupilot) or do a post in the forum (http://discuss.ardupilot.org).
