### ISSUE TITLE
Plane: make it easier to add a control mode

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#7547]
It is easy to add Copter control modes (like AUTO, ACRO.. ) but for Plane it is hard. It shouldn't be. Let's fix it!

Some work has already gone into it in set_mode() where we configure control_mode specific behaviors with 
```
throttle_allows_nudging = true;
auto_throttle_mode = true;
auto_navigation_mode = false;
```
but what we need is to do that for ALL behaviors and remove all other control_mode checks. Then all the behaviors can be defined in one location so adding or changing behavior is obvious and straight-forward.

**Comment by peterbarker** [comment]
This was done.

It's an ongoing thing, but @magicrub got the base stuff in.
