### ISSUE TITLE
AP_Mount: Isn't DataFlash a singleton and _dataflash superflous?

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/ardupilot#7550]
I think DataFlash is now a singleton, and accessible as DataFlash_Class::instance(). In my limited understanding I would thus think that the  DataFlash_Class *_dataflash; field in AP_Mount.h is superfluous, and DataFlash_Class::instance()->XXX should be used instead of _dataflash->XXX.

If so, these two lines should be removed:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount.h#L186
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount.cpp#L418

and here _dataflash should be replaced 4 times by DataFlash_Class::instance():
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_SoloGimbal.cpp#L117-L135

This would be all changes in the AP_Mount library folder.

**Comment by magicrub** [comment]
Sounds like you know what needs fixing. Why not create a Pull Request? Would you like some help creating a PR?

**Comment by peterbarker** [comment]
On Tue, 16 Jan 2018, olliw42 wrote:

> I think DataFlash is now a singleton, and accessible as DataFlash_Class::instance(). In my limited understanding I would thus think that the
> DataFlash_Class *_dataflash; field in AP_Mount.h is superfluous, and DataFlash_Class::instance()->XXX should be used instead of _dataflash->XXX.
> 
> If so, these two lines should be removed:
> https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount.h#L186
> https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount.cpp#L418
> 
> and here _dataflash should be replaced 4 times by DataFlash_Class::instance():
> https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_SoloGimbal.cpp#L117-L135
> 
> This would be all changes in the AP_Mount library folder.

Yes, that all sounds reasonable!

This isn't the only place in the code where we're passing around objects 
we now have singletons for - the fixes usually make the code much nicer, 
of course!

Did you want to put a PR together for this (with or without help)?
