### ISSUE TITLE
Rover: allow Steering, Auto using non-GPS navigation

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7554]
Rover currently requires GPS (not just a good position estimate) to enter Steering, Auto, Guided, RTL and SmartRTL.  We need to modify the "enter_gps_checks" message so that it checks for a good position estimate rather than the state of the GPS.

It may also be required to modify the AHRS so that it doesn't switch back to use DCM when there is no GPS.

**Comment by peterbarker** [comment]
@rmackay9 See discussion with @OXINARF on https://github.com/ArduPilot/ardupilot/pull/7402

**Comment by peterbarker** [comment]
On Wed, 17 Jan 2018, Randy Mackay wrote:

> Rover currently requires GPS (not just a good position estimate) to enter Steering, Auto, Guided, RTL and SmartRTL. We need to modify the
> "enter_gps_checks" message so that it checks for a good position estimate rather than the state of the GPS.

Some things require you to have a position from origin.

Others really do require you to know your GPS coordinates.

Should we add "requires_latlon()" and "requires_ekf_origin_position()" 
("requires_relative_position"?) in place of "requires_gps"?

After all - auto mode strictly requires latlon in our current 
implementation I think.

**Comment by rmackay9** [comment]
I think we require the EKF origin to be set before any of these modes will work (we should) so that means that we already know our lat/lon position.

It's true there is a slight advantage to having "requires_relative_position" for Steering and Acro modes.  If that's easy-ish then that sounds like a good thing to add.  It's less critical an issue than not being able to switch into Auto, Guided, RTL, SmartRTL without a GPS though.

**Comment by rmackay9** [comment]
This is (mostly) fixed in master now and Rover-3.2.1-rc1.
