### ISSUE TITLE
Passthrough FrSky Telemetry

### ISSUE THREAD

**Issue by lthall** [ArduPilot/ardupilot#7557]
Master does not appear to work with Passthrough FrSky Telemetry.

I have tested it against Copter 3.5.4 but upgrading to current master does not work. I have tested with both px4 build and ChibiOS.

**Comment by floaledm** [comment]
I'll look into it and report back asap.

**Comment by lthall** [comment]
Hey @floaledm, are you from Craft and Theory?

**Comment by floaledm** [comment]
Hi Leonard, yes.

**Comment by floaledm** [comment]
@lthall Tested the px4-v2 firmware found here (Jan 20) without issue: http://firmware.ardupilot.org/Copter/latest/PX4/

I went from 3.5.4 stable to 3.6-dev.

You could email me the FWs you're using, or suggest another approach to testing...

**Comment by lthall** [comment]
Hmmm, ok.

I will have to go back to defaults on 3.6 dev and see if I can get it working.

**Comment by floaledm** [comment]
Didn't change the parameters. Just flashed 3.6-dev.

Don't hesitate to email me anything you think might be relevant to test.

**Comment by DavidIngraham** [comment]
@lthall Can you confirm if there is still a problem?

**Comment by lthall** [comment]
Yes, I am still having an issue but I have not been able to work out why yet. There is something in my settings that stops it working. I need to look into it further.

**Comment by peterbarker** [comment]
This works in master; tested it the other day.  I hope Leonard got to the bottom of this eventually :-)
