### ISSUE TITLE
Nano Drone Making 

### ISSUE THREAD

**Issue by salil0001** [ArduPilot/ardupilot#7560]
I want to make a project regarding nano drones. The drones are programmed in such a way that it is connected to wifi or Bluetooth and it will scan the whole room and doesn't strike to walls. It will scan the faces in such a way that the image which will match the drone will land on that palm.

Topics covered in this 
Image Processing 
IR sensor's programming
Automation(no controller required, Controlled by gestures).

Will your team help me out in this and can we make this?

**Comment by DavidIngraham** [comment]
Thank you for your interest in the ArduPilot Project! This page is for reporting confirmed bugs and requesting specific enhancements to the project. Your question is better suited for the ArduPilot forums (discuss.ardupilot.org). I recommend that you post your question over there.
