### ISSUE TITLE
Rover: nudging minor bug for negative target speeds.

### ISSUE THREAD

**Issue by pavloblindnology** [ArduPilot/ardupilot#7566]
`fabsf(target_speed)` should be used instead of `target_speed`. Though the returned value will be the same.
https://github.com/ArduPilot/ardupilot/blob/700171a0fc28d650cd1c1d2d371d9af132ba9530/APMrover2/mode.cpp#L268

**Comment by rmackay9** [comment]
Fixed thanks!
https://github.com/ArduPilot/ardupilot/commit/6ce9b47807b54a3a3fd2da2dbd1c348683390c88
