### ISSUE TITLE
ArduPlane: CH7_Option

### ISSUE THREAD

**Issue by JNJO** [ArduPilot/ardupilot#757]
These exist in ArduCopter 3.x and I find them very useful:

```
Inflight tuning of selected parameters over Channel 6. http://copter.ardupilot.com/wiki/arducopter-parameters/#Channel_6_Tuning_ArduCopterTUNE
Selectable functions via Channel 7. http://copter.ardupilot.com/wiki/arducopter-parameters/#Channel_7_option_ArduCopterCH7_OPT
```

Inflight tuning is currently possible over telemetry, but that usually means taking focus away from the plane or FPV monitor to change parameters or gains in the ground station.
To maintain safety, a second person is needed to manage the ground station.
Tuning a parameter or gain with a potentiometer on the TX would feel much safer and could be done while observing the plane directly, giving an instant feedback on the changes, and can be done by one person only.

The CH_7_Option could, for example, be used to free up a flight mode that is otherwise used for RTL, and add quick functions like Save WP, Camera Trigger, Save Trim. These functions can easily be changed via GCS in pre-flight to fit the given mission profile.

**Comment by DavidIngraham** [comment]
Closeable, this was added in Plane 3.6: https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/release-notes.txt#L466

**Comment by JNJO** [comment]
The new SERVOx_FUNCTION introduced in Plane 3.8.0 can be used for at least some of the CH7_Options listed above. Very nice. :)

**Comment by jmachuca77** [comment]
Looks like most of this has already been implemented, in plane 3.8.0. If there are no objections, I'll close this issue in a few days.

**Comment by rmackay9** [comment]
The SERVOx_FUNCTIONS are for output mapping.  This request is for mapping an input channel to a function.  Peter has a PR that accomplishes what this issue requests but it hasn't been tested nor merged yet.

**Comment by Naterater** [comment]
The channel options are now in Master for plane.
