### ISSUE TITLE
Twin engine plane ESC Beep when safe (Arming Require error)

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#7577]
#### Issue details
When servos are set to 73 or 74 (left or right throttle), then Arming Require = 1 does not have the desired effect (sending minimum pwm) when the safety switch disables the servos.

This also happens to 1 ESC if the ESC's are connected to the board separately, both set to 70 (throttle). The higher channel # receives a PWM_MIN signal while the other receives nothing.

#### Version
Plane 3.8.4

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Twin

#### Hardware type
Pixhawk 2.1

**Comment by IamPete1** [comment]
Fixed by #18050 we now treat throttle left and right the same as main throttle and they all honor the safety mask.
