### ISSUE TITLE
Copter/Rover: move AC_AttitudeControl::sqrt_controller to AP_Math

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7584]
AC_AttitudeControl::sqrt_controller is used by Rover and Copter now so it should be moved to a more centralised location (AP_Math?) so that Rover's dependency on AC_AttitudeControl can be removed (there are some includes of AC_AttitudeControl in Rover and it also appears in the waf and make build files)

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_AttitudeControl/AC_AttitudeControl.h#L223

I'm certainly open to suggestions on where this belongs.  It could be AP_Math/AP_Math.h or maybe a new file within the AP_Math library folder

**Comment by IamPete1** [comment]
Looks like it is now in `AP_Math/control.cpp` I guess as part of S-Curves. I'm going to close.
