### ISSUE TITLE
Plane: handle position control PID move for quadplane

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7593]
As part of this PR (https://github.com/ArduPilot/ardupilot/pull/7551) we moved the position control PID objects from the main vehicle class into the AC_PosControl library.

The parameter conversion for Copter was completed but it was not clear how to do the parameter conversion for quadplanes.

This issue is to record that we need to do this conversion.

**Comment by WickedShell** [comment]
Done in #7602
