### ISSUE TITLE
ArduPlane: Flaperons appear to be broken, or, Wiki needs updating.

### ISSUE THREAD

**Issue by JNJO** [ArduPilot/ardupilot#760]
The flaperon function in ArduPlane appears to be broken, or, the Wiki needs to be updated if I'm not using the correct procedure.

Description:
I've set a mix in Radio TX to add 20% to Ch 1 and Ch 5 when flap switch is toggled on.

I have two aileron servos.
Starboard servo connected to APM output 1.
Port servo connected to APM output 5
RC_5_FUNCTION set to 5 (Flaperons)
Setup like this the Port servo does not move with aileron input in any flightmode.
It is also not responding to attitude changes in any of the auto modes. (Loiter, Auto, Cruise)

If I change RC_5_FUNCTION to 18 (Aileron With Input), the Port servo respond aileron-wise as expected in Manual, Stab and FBWA, but in Stab and FBWA it seems that Radio input 5 is ignored.

The result of this setting is that the flaperons function as intended in Manual mode, but in FBWA and Stab the flaperon function on the Port servo is reversed causing the ailerons to be set for a roll.

Firmware: ArduPlane 2.76
Board: Arduflyer 2.5.2
Radio TX: Turnigy 9XR
Radio RX: FrSky DR4-II set to 8ch PPM.

**Comment by smr277** [comment]
Tested Flaperons according to the Wiki with FLAPERON_OUTPUT to 4, RC6_FUNCTION to 24. I'm not getting any movement when I move the aileron stick nor when I move the flaps switch. This is what I tested:
RC6_FUNCTION = 2 (set to flaps) makes the flap switch work (moving the flap switch moves the servos)
RC6_FUNCTION = 4 (ailerons) makes the aileron stick work (moving the aileron stick moves the servos)
FLAPERON_OUTPUT = 1,2,3,4 and RC6_FUNCTION = 24,25 (flaperon1,2) nothing happens when aileron stick or flap switch moves
I am running ArduPlane from commit 44d2ae06fb on PixHawk. 
Any other testing ideas? I'd be happy to upload or change stuff, I have a forked repo (that is up to date with the master 44d2ae06fb).

**Comment by smr277** [comment]
Found the problem, and I personally think it should be fixed (or at least documented).
Line 664 of Attitude.pde:
if (!RC_Channel_aux::function_assigned(RC_Channel_aux::k_flaperon1) ||
        !RC_Channel_aux::function_assigned(RC_Channel_aux::k_flaperon2))
If you only have a single flaperon setup for testing, the func returns nd doesn't pass flaperon values . Therefore, you need to have BOTH flaperons setup for flaperons to work at all. I personally think this should be documented or changed.

**Comment by magicrub** [comment]
There is a pending pull request to fix flaperons, not sure of it addresses
this particular bug though. If you're feeling up to it, please take a look
and report back.

**Comment by marcmerlin** [comment]
But just to be clear, flaperon 1 cannot be set on channel 1 where my aileron is, so if you use flaperons, you have to move your aileron away from channel 1?
If so, that sounds very suboptimal.
I've filed a related bug about this and making mode 18 easier to use if you can't use the current flaperon support: https://github.com/diydrones/ardupilot/issues/2186

**Comment by marcmerlin** [comment]
Ok, good news. Wiki will get updated I believe, but in the meantime, I wrote a full set of instructions here: http://marc.merlins.org/perso/rc/post_2015-08-04_Using-Flaperons-With-Ardupilot.html

**Comment by Ryanf55** [comment]
Sorry to grave dig, but I feel there's still some limitations here not addressed in the wiki. I'm trying to setup a full-house electric aircraft with the ailerons run as "ailerons" in pixhawk, and the flaps run as "flaperons" in the pixhawk. I'm using 4 servo outputs on the pixhawk, and feel like I'm running into limitations of the mixer and assumptions it makes, such as " If you have both a FLAP_IN_CHANNEL set and a Flap_auto output function set then the amount of flap applied is the higher of the two." This seems to be causing a bug in only one of the flaps.
