### ISSUE TITLE
Rover: support balance bots

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7625]
We should add support for Balance Bots ([description from make magazine](https://makezine.com/projects/arduroller-self-balancing-robot/)).  This will likely involve:

- extending the AR_AttitudeControl library to add a pitch angle to throttle/acceleration control.
- ensure all existing drive modes work with balance bots.
- document the setup on our wiki.

Some more concrete steps to get started are below.  These steps outline how to get a balance bot standing in Manual mode.

- in [APM_Control/AR_AttitudeControl](https://github.com/ArduPilot/ardupilot/blob/master/libraries/APM_Control/AR_AttitudeControl.h) add a new AC_PID object called something like _bb_pitch_to_throttle.
- in the same library add a "get_throttle_out_from_pitch()" method that accepts a desired pitch angle and outputs a throttle value from -1 to +1.  This method could be similar to the existing get_throttle_out_speed but the error passed into the PID controller will come from the difference between the desired pitch angle and the actual angle (which you should be able to get from the _ahrs.pitch or _ahrs.pitch_sensor attibute.
- in Rover's [ModeManual::update](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/mode_manual.cpp) method call the above get_throttle_out_from_pitch() passing in a desired pitch angle of 0 and then add the output to the "desired_throttle" returned by "get_pilot_desired_steering_and_throttle" and then pass into the g2.motors.set_throttle() method.

**Comment by jmachuca77** [comment]
Cool video, I had read the article but I had not seen the video. I wonder if Jason’s code could be a starting point for this

**Comment by rmackay9** [comment]
Jason's code will be very old now but if we could find it, it's probably a very good place to start.  It would have the basic control stuff in there.  @tridge has found this repo from @jschall which has some balance-bot code it in as well: https://github.com/jschall/ardupilot/tree/balancebot

**Comment by auturgy** [comment]
Jason’s code is here: https://github.com/jason4short/ardupilot/tree/ArduRoller

Regards,

James

**Comment by jschall** [comment]
If there's any interest in hardware for this, let me know. I have designed a 2m tall direct-drive brushless balance bot. They're pretty expensive and time consuming to print and build, but I would be willing to provide one to someone who wants to make it work with APM:Rover.

**Comment by Linjieqiang** [comment]
Nice.

**Comment by mundsen** [comment]
Hi, I have started planning a "ArduRoller 32" build (using PixHawk/PixRacer not the old controller) inspired by the old ArduRoller project.
I have ordered 120mm rubber wheels, but find it hard to decide if I should base the bot on Nema17 or 6V / 12V Geared DC motors with encoders like in the original ArduRoller??

Hope the PixHawk get balance bot support soon.

Great if anyone can held me decide so I can order the parts..

**Comment by rmackay9** [comment]
Support for balance bots isn't perfect yet but the basics are in and will be released with Rover-3.5.  Future improvements to the balance bot code can be handled as new issues.  Thanks @EbinPhilip!
