### ISSUE TITLE
Copter: reduce chance of EKF losing attitude estimate during fast rotations

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#7629]
#### Issue details
I've a really bad crash yestarday with "Ardupilot: Copter V3.5.5 RC1" during a "Simple Mode" demonstration in "Stabilize" flight mode, performing continuous yaw rotations as I often show in a lot of my videos.
But imho this time EKF has failed.
The quad started to take a direction increasing the angle more and more, and from the log instead the EKF show the electronics leveled while instead the copter is tilting and acquiring speeds at over 15 m/s, so I completely lost control and the possibility of recovering it.
It had been years since I had such a serious problem like this.
During this maneuver i see a lot of EKF errors of Position and Velocity, compass switch, it seems that the EKF goes crazy and totally loses the attitude, not understand the real level of the IMUs inside the flight control (Pixhawk 2.1).
All the compass are calibrated before takeoff, I see Z mag values in the log that strangely arrive at absurd limits.
Compasses may fail but the quad must remain leveled in "self level" mode, IMUs can not be deceived until they lose their attitude.
Really dangerous, need investigation, so at the moment I advise against using "Simple" feature.
It is obvious that this type of maneuver, performed also very quickly, is not conventional in normal use, but it doesn't have to happen anyway.
Here the moment when the quad is tilted in flyaway at over 40° angle, really tilted, see the hud horizont, for the EKF is levelled:

![ekf_crazy](https://user-images.githubusercontent.com/3864712/35556198-ec842bd2-05a1-11e8-9807-11ee2fcaee44.png)

#### Version
Ardupilot: Copter V3.5.5 RC1

#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad

#### Hardware type
Pixhawk 2.1, Here+ RTK (primary) and Here GPS (secondary)

#### Logs

https://drive.google.com/drive/folders/1DZVZhTtlN7vptDb-kv8xQMEt-Ds2DVeo

**Comment by priseborough** [comment]
This is  a known vulnerability of the EKF2 formulation. For rotating airframes (which is what you have effectively created with spinning continuously in simple mode), I recommend you use EKF3 which handles that type of motion better or reduce the max spin rate. I could add support for spinning airframes by 'de-spinning' the sensor data before use in the EKF, possibly using an approach similar to https://discuss.ardupilot.org/t/gyropter-monocopter-support-with-the-help-of-a-fourier-based-transform or by adding another state, but that will require significant effort for what is a niche use case.

**Comment by priseborough** [comment]
Also note that the max sustained yaw rate that can be tolerated also depends on the offset of the IMU from the spin axis and the GPS offset from the IMU and whether the IMU and GPS position offset parameters have been set.

**Comment by night-ghost** [comment]
> I could add support for spinning airframes by 'de-spinning' the sensor data before use in the EKF

It woud be great for failsafe in case of motor loss [as here](https://www.youtube.com/watch?v=bsHryqnvyYA)

**Comment by R-Lefebvre** [comment]
I'm pretty sure that spin rate would saturate the gyros, and then it's done.  Most of that work was done in a Vicon lab with ~1000Hz external pose estimates?  

Also never seen this demonstrated with larger systems (ie: can motor response rate of 12+" propellers keep up with stabilize something spinning that fast)

All interesting ideas of course.  But every time I see somebody point to that I have to bring up the reality.

**Comment by night-ghost** [comment]
>But every time I see somebody point to that I have to bring up the reality.

this allows ideas to be born!

>Most of that work was done in a Vicon lab with ~1000Hz external pose estimates?

if to believe the text below the video, this is a usual pixhawk and proprietary software. So it can be done by Ardupilot team too

**Comment by IamPete1** [comment]
sounds like the solution is to use EKF3, it is the default now in any-case.
