### ISSUE TITLE
A small bug in AP_PitchController::_get_rate_out().

### ISSUE THREAD

**Issue by luweikxy** [ArduPilot/ardupilot#7630]
# Site:
https://github.com/ArduPilot/ardupilot/blob/023e3b6e30dae577247fa3360cd1ee244cdd9292/libraries/APM_Control/AP_PitchController.cpp#L220

# Bug describe:
When roll angle reaches 90, the roll_prop is not equal to 1, which will cause _last_out is not zero.
```
float roll_prop = (roll_wrapped - (aparm.roll_limit_cd+500)) / (float)(9000 - aparm.roll_limit_cd);
```
# Example:
For example: roll_wrapped = 9000, aparm.roll_limit_cd = 7000, then 
roll_prop =  (9000- 7500) / (9000 - 7000) = 1500 / 2000 = 0.75 != 1;
and then based on
```
_last_out *= (1 - roll_prop) 
```
_last_out = _last_out *  (1 - roll_prop) = _last_out *  (1 - 0.75)  != 0
# How to fix:
Maybe we can rewrite #L220 as:
```
float roll_prop = (roll_wrapped - (aparm.roll_limit_cd+500)) / (float)(9000 - aparm.roll_limit_cd+500);
```

**Comment by IamPete1** [comment]
Looks like this was fixed as part of https://github.com/ArduPilot/ardupilot/pull/15377 We now subtract the same value on the denominator and numerator. Please re-open if my read of the code is wrong. 

It can now be found here: 

https://github.com/ArduPilot/ardupilot/blob/f20644b6cf87b53c2394ad1ff07673c5ae657864/libraries/APM_Control/AP_PitchController.cpp#L338
