### ISSUE TITLE
Correct Parameters for Camera_Feedback_Msg

### ISSUE THREAD

**Issue by redline870** [ArduPilot/ardupilot#7637]
I am trying to write GPS data to my pictures that are being taken. The way this is happening is to send the camera_feedback_msg via telemetry Line to the Flir Vue Pro. Once i send the message I take the picture by sending the PWM Signal with the correct duty cycle. I have verified that i am taking the picture and that it works correctly, but i am not sure if the way i am sending the message with the data is correct or if the order that i am sending it in is correct. Below is the code that i am doing to pack and send the message:

int count = 1;
mavlink_message_t msg;
uint8_t len;
uint8_t buf[MAVLINK_MAX_PACKET_LEN];

mavlink_msg_camera_feedback_pack     (0,100,&msg,30,1,0,count,43.040813,-76.129793,0.15,0.15,-2.82,-0.38,301.74,0.00,0);

 len = mavlink_msg_to_send_buffer(buf,&msg);
Serial1.write(buf,len);

**Comment by WickedShell** [comment]
We try to not do support on the issue list. This sounds like an issue with some custom hardware som I'm closing this now, please open a topic on discuss ( http://discuss.ardupilot.org/ ) if you need more help.

(Having said that last time I used a Flir Vue it was accepting the GPS data from the autopilot without an issue. I'm not sure if it was using the feedback message though, or actually just reading the position/attitude from other messages).
