### ISSUE TITLE
Rover: report MAV_TYPE as Boat when FRAME_CLASS =2

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7646]
As we get more serious about supporting boats we should make boats appear as boats on the ground station map.  To allow the ground stations to know it is a boat we should report the vehicle's MAV_TYPE (held in the heartbeat message i think) as MAV_TYPE_SURFACE_BOAT if FRAME_CLASS = 2 (aka "Boat").

There will probably need to be a follow-up issue raised for the mission planner and other GCSs along with providing them with a boat icon.

**Comment by starlord1311** [comment]
can i take up this issue? @rmackay9

**Comment by rmackay9** [comment]
@starlord1311, yes, please!

**Comment by starlord1311** [comment]
can you help me with what i am supposed to do?

**Comment by khancyr** [comment]
Hello,

You need to correct the vehicle type reported first. Currently it is always MAV_TYPE_GROUND_ROVER. There is at least two place to change : see  https://github.com/ArduPilot/ardupilot/search?utf8=%E2%9C%93&q=MAV_TYPE_GROUND_ROVER&type= for example. A simple if case should be enough. 
On second time, you need to correct the GCS (Mission Planner and mavproxy). Well this can be uneasy, so opening an issue on mission planner explaining what the change should, is already a good start. On mavproxy, you need to find the function in charge of loading the vehicle image and change it to a new boat image !

**Comment by starlord1311** [comment]
So i just need to add MAV_TYPE_SURFACE_BOAT next to MAV_TYPE_GROUND_ROVER wherever it is used? @khancyr

**Comment by rmackay9** [comment]
@starlord1311, I think that's probably all that's required.  I've raised an issue for Mission Planner so hopefully @mee1 can add the icon for boats somehow.  Maybe someone will need to make a little icon for him.  That's beyond the scope of this vehicle related change though.

**Comment by rmackay9** [comment]
fixed in master.
