### ISSUE TITLE
Strange behavior of uart alternate function

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#7647]
#### Issue details
  There is strange behavior of uart of our custom board, dms_init function could change ALT function of GPIOA0 from ALT8(uart4_tx) to ALT0, details as below:
![uart](https://user-images.githubusercontent.com/16251761/35718934-c2af4a80-0821-11e8-9de3-feefdad0ed7d.PNG)
![uart](https://user-images.githubusercontent.com/16251761/35718941-c85f08bc-0821-11e8-9198-9c00a1666af4.PNG)
![sbus](https://user-images.githubusercontent.com/16251761/35718947-cde641a6-0821-11e8-97d5-f0824be08c58.PNG)
![debug](https://user-images.githubusercontent.com/16251761/35719003-06d0dd00-0822-11e8-83ff-f170489a8565.PNG)
![default](https://user-images.githubusercontent.com/16251761/35719007-0b8c214c-0822-11e8-8019-5786007ac6c8.PNG)

#### Version
3.8.4

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
custom board

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by liang-tang** [comment]
But when i set GPIO_USART1_TX to GPIO_USART1_TX_2, everything is ok, PA0 alternate function won't be changed. How could it be? I can't understand why.

**Comment by liang-tang** [comment]
@tridge

**Comment by magicrub** [comment]
Why did you close? Was this resolved?

**Comment by liang-tang** [comment]
Ignore this issue, because we will switch to ChibiOS platform.
