### ISSUE TITLE
Waf upload do a rebuild on px4-v3

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#7650]
#### Issue details
The waf upload command is acting weird with upload on px4-v3 target.
It build the code, upload, then rebuild the code. 
#### Version
https://github.com/ArduPilot/ardupilot/commit/f189ce5c68c8da96e035a1bcefbe82973e787fc0

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment]
I used to get this behaviour, it seems to have been fixed sometime recently as I no longer see it. Please reopen it if you are still seeing the issue.
