### ISSUE TITLE
Copter, Rover: add support for DO_SET_ROI_LOCATION

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7658]
We should add support for the new ROI messages to Copter and Rover that can be found [here](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ROI_LOCATION)

- [x] DO_SET_ROI_NONE - cancels the ROI
- [ ] DO_SET_ROI_WPNEXT_OFFSET
- [x] DO_SET_ROI_LOCATION

Note that these should both be immediate commands and mission commands.

**Comment by drprofpatrick** [comment]
Has this been solved yet? This would be very useful for work.

**Comment by rmackay9** [comment]
@drprofpatrick, no i'm afraid not.  the regular DO_SET_ROI works of course though so I think it's possible to use this existing command to do the same thing.  It just requires a little more work creating the mission because the user will need to input the lat/lon.

**Comment by rmackay9** [comment]
We've got partial support this in Copter/Rover-4.0 because we support MAV_CMD_DO_SET_ROI_LOCATION.  We still don't support these variations:

- MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET
- MAV_CMD_DO_SET_ROI_NONE

**Comment by billc303** [comment]
Any update as to when QGC structure scan might be implemented in Ardupilot?

**Comment by rmackay9** [comment]
I think I'll close this issue and add a link to the PR to the gimbal enhancement list.
