### ISSUE TITLE
Plane: Add ability to trigger camera via RC

### ISSUE THREAD

**Issue by Raviu8** [ArduPilot/ardupilot#7666]
I want to be able to trigger the camera using a switch on my remote control, along with the ability to do this with GCS or auto mission.
When the switch is turned on, it should do the same action as when you do "Trigger camera Now" action from MissionPlanner.
Switching off should have no effect.

**Comment by Pedals2Paddles** [comment]
This is already implimented.  See the CH7_OPT through CH12_OPT parameters. http://ardupilot.org/copter/docs/parameters.html#ch7-opt-channel-7-option.  Fully described in the wiki. http://ardupilot.org/copter/docs/common-camera-shutter-with-servo.html.

Additional support and help can be found in the discuss forums: https://discuss.ardupilot.org/

**Comment by geofrancis** [comment]
none of that works with plane.

**Comment by Pedals2Paddles** [comment]
Ah, well in that case...

**Comment by Raviu8** [comment]
Actually I don't fly copters. This is no such thing in plane

**Comment by DawoodTaii** [comment]
There is an old issue #1158 related to this.
Why not just allow the same RC/Servo mapping as per other control surface. So when servo8 is selected for camera trigger, RC8 should trigger camera - once - when above 1750 ?

**Comment by amilcarlucas** [comment]
You only need to add AP_CAMERA support to plane.

**Comment by robustini** [comment]
Related issue #7071.
