### ISSUE TITLE
Onboard OLED Display: enable for Plane

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/ardupilot#7710]
#### Issue details
Enable the OLED onboard display in ArduPlane as described here: http://ardupilot.org/copter/docs/common-display-onboard.html for ArduCopter 

#### Version
All versions

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Fixed wing

#### Hardware type
AUAV-X1

#### Logs
N/A

**Comment by magicrub** [comment]
Oh, this doesn't work for plane right now? I bought a few of those oleds but never got around to using them. I assumed they were working. Aaaand now I get to use them!

**Comment by GrahamDyer** [comment]
Hi Tom, they work well in ArduCopter but the parameter NTF_DISPLAY_TYPE doesn't appear in Plane so I guess the code isn't there.

**Comment by Naterater** [comment]
I thought precision hawk had the feature built in to their airframes. I never flew one though, so maybe I'm wrong, and maybe it was a special version.

**Comment by magicrub** [comment]
@GrahamDyer There's nothign in the drivers that make copter special, it should work on all vehicles. I also see it in the auto-generated parameters list for plane [here](http://ardupilot.org/plane/docs/parameters.html#ntf-display-type-type-of-on-board-i2c-display) so the source says that parameter exists for plane so please double and triple check. All indicators say it should work equally on all vehicles.

**Comment by GrahamDyer** [comment]
![ntf](https://user-images.githubusercontent.com/3287001/36211218-4a0ad400-11a9-11e8-9870-0b7f0a9dc88f.jpg)
The NTF_DISPLAY_TYPE parameter isn't there. I'll load the latest version of AP and check again...

**Comment by DavidIngraham** [comment]
Hmm, could this be specific to the AUV-X1? It works for me on the Cube.

**Comment by GrahamDyer** [comment]
OK, I managed to get it working. Seems the version of AP that I was using didn't have it. Apologies. Thank you for looking at this.
