### ISSUE TITLE
How to build an antenna tracking with APM 2.8?

### ISSUE THREAD

**Issue by rdioses** [ArduPilot/ardupilot#7715]
Hello friends, I have an Ardupilot 2.8 and I want it to work as an antenna tracker, I know all about the frame and those things, what I can not do is configure the APM, I have managed to load the firmware of the antenna tracker in the APM from mission planner, and I soldered a bridge on pins TX2 and RX2 on the board, but then I do not have any information on how to set it up, does anyone kindly help me set it up?
psdt: I do not intend to use a separate servo driver, I want to use only the ardupilot board.

**Comment by magicrub** [comment]
Hi @rdioses , you've posted a HOWTO question in the developer bug tracker system. Please post questions in [the forums](http://discuss.ardupilot.org). To get started, take a look at [the Wiki](http://ardupilot.org/antennatracker/index.html).
