### ISSUE TITLE
Plane: add support for External LED

### ISSUE THREAD

**Issue by vindolin** [ArduPilot/ardupilot#772]
It would be really nice to be able to install an external LED or buzzer for the GPS fix signal.
As I understand, arducopter has that with LED_MODE.

**Comment by ferret-guy** [comment]
@rmackay9 it seems that Plane is using AP_Notify, and it also seems that is now baked into AP_GPS as well and thus I assume the functionality noted [here](http://ardupilot.org/copter/docs/common-external-leds.html) should be the same as it is for plane now.

**Comment by rmackay9** [comment]
yes, I think we can close this.  now.. thanks!
