### ISSUE TITLE
Config.h Feature Request/Suggestion

### ISSUE THREAD

**Issue by bstott** [ArduPilot/ardupilot#773]
Take a look at what a 3D printing firmware team (Repetier) are doing for automating the setups for their firmware compile use - http://www.repetier.com/firmware/v091/

It runs you through several pages of web based forms to generate a good configuration file from which the firmware is then generated for the specific 3D printer.

Question: Did you release a link last year to a web based configuration tool?

Thanks for all your great efforts.

Brian Stott

**Comment by Naterater** [comment]
I'm not sure this strategy goes along with ardupilot's stragegy. This would be a big change, and the web-based configuration tools (firmware.ardupilot.org) helps users find the proper firmware pretty well. Changed default parameters can now be added with specific builds too.

Do you mind if this suggestion is closed as the new firmware build server has been implemented?

**Comment by auturgy** [comment]
Leave this open.
It’s a very useful suggestion and completely aligned with our intent.
The apj tool is a part-way solution, and at some point providing a web interface to it would enable users and/or users to bake a firmware with their own settings as it’s defaults.

**Comment by Naterater** [comment]
Wouldn’t a parameter generation tool be easier?

**Comment by IamPete1** [comment]
The custom firmware page is now live:
https://custom.ardupilot.org/
