### ISSUE TITLE
Unable to update submodule

### ISSUE THREAD

**Issue by virendrasuryavanshi** [ArduPilot/ardupilot#7736]
The Error message that i get is:
Cloning into 'modules/ChibiOS'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out
github.com[1: 192.30.253.113]: errno=Connection timed out

fatal: clone of 'git://github.com/ArduPilot/ChibiOS.git' into submodule path 'modules/ChibiOS' failed

**Comment by lvale** [comment]
please post support questions at discuss.ardupilot.com
