### ISSUE TITLE
Plane: DO_VTOL_TRANSITION to VTOL stopped working

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#7748]
#### Issue details
Following what's documented here: http://ardupilot.org/plane/docs/quadplane-auto-mode.html#mixing-vtol-and-fixed-wing-flight
with the exact same waypoints, it seems that DO_VTOL_TRANSITION to VTOL (3) stopped working correctly.  The plane de-transitions and makes a 180deg turn back towards where it started the de-transition, then a few seconds later makes another N degree turn.  If the next WP is straight ahead, this effectively means a full 360 as the plane is de-transitioning!

#### Version
Tested on 3.8.2

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
SITL

#### Hardware type
SITL

**Comment by IamPete1** [comment]
This sounds like the transition deceleration was set wrong so the vehicle overshot the target and had to go back. 

Anyway there is not much to go on in this issue so I'm going to close.
