### ISSUE TITLE
Copter: move Log_Write_AutoTune to mode_autotune.cpp

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7759]
As part of the Copter flight mode restructuring the autotune mode's logging was moved into the autotune mode class but the implementation (i.e. Copter::ModeAutoTune::Log_Write_AutoTune) was left in Log.cpp.  We should move this to mode_autotune.cpp.

This should be a non-functional change

**Comment by naveentrtumkur** [comment]
@rmackay9  Can I take up this issue and start working on this?

**Comment by lthall** [comment]
That should be fine @Naveentrtumkur

**Comment by naveentrtumkur** [comment]
@rmackay9  Do we also need to move Log_Write_AutoTuneDetails from Log.cpp to mode_autotune.cpp?

**Comment by sarthak268** [comment]
Is this still open?
If yes, please assign

**Comment by MohamedAliRashad** [comment]
#10847 I think this PR close the issue.
