### ISSUE TITLE
I2c bus locks up and stops working

### ISSUE THREAD

**Issue by yak-54** [ArduPilot/ardupilot#7776]
Issue 
I2c bus locks up when the here gps and the Maxbotic I2C EZ4 sonar plug in led on the here gps is bright yellow and stops flashing 
but if i remove one from the I2c bus it works fine 
does not matter which one is removed

the work around for me was Pixhawk’s ADC 3.3V port Analog port

Version
Plane 3.8.4

Platform
Plane

Hardware pixhawk with here Gps and Maxbotic I2C EZ4 sonar

**Comment by yak-54** [comment]
fixed

**Comment by tecnic08** [comment]
> fixed

What did you do to fix the problem?

**Comment by mboland** [comment]
If this was the I2C storm bug then just use the latest Stable release.
