### ISSUE TITLE
Quadplane/Tailsitter: automatic landing with side wind for VTOL Tail Sitters

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#7786]
#### Issue details
It is known that the "Tail Sitters VTOL" suffer from wind direction during automatic landing.
In the "non-vectored" versions the pitch control in Copter mode is quite precarious without the motors tilt system, while the roll using the revs variation of the motors is quite reactive and allows excellent corrections of the attitude.
What I propose is therefore the possibility of better automatic attitude by rotating the Tail Sitters after the automatic transition "FW->MC", so that it has the side wind, to prevent it from overturning when it touches the ground, and ensuring a better correction when reaching the home.
It is well known that Ardupilot recognizes the wind direction after a few turns in plane so I don't think it's a big deal to implement this feature, and I think it is very important for a perfect ground touch with a lot of wind.
So, in the case of RTL (or automatic landing) the logic should be:

- "FW->MC" transition when hit the home radius
- YAW rotation to have the side wind
- the rest of the procedure to get to the home and land

#### Version
Plane V3.8.5 Beta 1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Tail Sistters VTOL

**Comment by palm369** [comment]
Absolutly. And also need some logic which instantly kills throttle if plane falls over while landing.

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/19859
