### ISSUE TITLE
Rover: path between waypoints should use previous waypoint as origin

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7796]
In Rover-3.2.1 the path that the vehicle follows between waypoints has an "origin" which is the vehicle's position at the moment it entered the waypoint-radius around the previous waypoint.  This should be changed so the origin is the previous waypoint.

![rover-path-fix](https://user-images.githubusercontent.com/1498098/36717698-75fb8940-1be2-11e8-9b53-4a4d87a93b09.png)

One way to fix this issue could be to:

- create a new Mode::set_desired_location() method that accepts an origin and destination as arguments.  This new method would set the Mode::_origin based on what's passed in instead of using "rover.current_loc" (see [here](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/mode.cpp#L101))
- in Rover's commands_logic.cpp's Rover::do_nav_wp() method, use AP_Mission's get_prev_nav_cmd_index() or get_prev_nav_cmd_with_wp_index() to determine if we were already executing a navigation command.  If yes, then go get that mission command's location and pass it in as the origin.  Alternatively a new "get_desired_location" method could be added to the Mode class which returns the current _destination.  This could then be passed in as the _origin for the new call to Mode::set_desired_location()

**Comment by khancyr** [comment]
yep the origin for the nav_controller path calculation should be the real wp1 and not the point we consider as "we pass on the waypoint"
A nice addition could be to have an accuracy estimation so the rover could dynamically adjust the wp_radius and try to go as close as possible to the real waypoint coordinate without overshooting much

**Comment by rmackay9** [comment]
This is fixed in master and will go out in the next release.
