### ISSUE TITLE
Support LED stripes

### ISSUE THREAD

**Issue by micropet** [ArduPilot/ardupilot#781]
Hello,

it would be nice if we get back ports for GPS and Arming status on PIXHAWK.

eg.
AUX OUT 1 on the PIXHAWK corresponds to the A7 (arming) on the APM
AUX OUT 2 on the PIXHAWK corresponds to the A6 (GPS) on the APM

So we could continue to use our old hardware. The external RGB Led is not yet available.

regards Peter

**Comment by davidbitton** [comment]
@rmackay9 Do you think we could use the OreoLED driver to drive a [PROGRAMMABLE MOTOR LED RING](http://tro.pe/1LKbt1d) from [RTFQ](http://tro.pe/1LK8Qwt)? RTFQ claims there's an Atmel chip onboard and the ring can be run in WS2812 mode. RTFQ pushes you to [FastLED](http://tro.pe/1LKbUbV) for driver software. Do you think this could be done? Thanks.

**Comment by msdigi** [comment]
I need this funktion! (on a AUAV-X2).
On my quad i have 4 LED-stripes (single color) and i want to switch them ON when armed, and OFF when disarmed.

**Comment by Naterater** [comment]
@proficnc, aren't you releasing some LED's in the future, possibly related to this?

I also noticed that single LED's can be connected, however I don't think that solves this specific issue. http://ardupilot.org/copter/docs/common-external-leds.html

**Comment by auturgy** [comment]
A diy solution is here: https://github.com/prickle/Mavpixel

It’s possible to roll support for ws2812 or APA102 style LEDs in (@bugobliterator has such a branch iirc).

**Comment by proficnc** [comment]
Yes, the profiLEDs are already available from resellers and can be run using @bugobliterator ‘s code. (These are NOT ws2812 LEDs, they are not good for a flight computer as their timing requirements are too strict)

**Comment by auturgy** [comment]
The only (strictly) tight timing on ws2812 is max length of a 0 bit, 500ns. We achieve far tighter timing with DShot 1200, which is about 300ns iirc.
DShot and ws2812 wasn’t practical to attempt under nuttx, but under ChibiOS it’s more a matter of developer priority than any technical constraint.

**Comment by proficnc** [comment]
An esc is flight critical... an LED is not. This was covered a long time ago (back in 3DR days) when we decided not to support the WS... LEDs. This is why we developed the ProfiLED, it has zero timing requirements, so can be run as a low priority thread.

**Comment by auturgy** [comment]
Closed https://github.com/ArduPilot/ardupilot/pull/11870
