### ISSUE TITLE
Plane: QuadPlane code failed de-transition with LOITER_TIME command

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#7814]
#### Issue details
As explained here http://ardupilot.org/plane/docs/quadplane-auto-mode.html#hovering-in-a-mission, we set Q_GUIDED_MODE=1 and tried an AUTO mission with a LOITER_TIME command.  This did not go well.  Within 4 seconds, the vehicle de-transitioned, entered hard left+right rolls, came down immediately and crashed.

This is a vehicle that has been doing lots of flying and transitions/de-transitions without problem.  Could there be an issue with LOITER_TIME and how de-transition is handled?  @tridge?

Thanks!

#### Version
3.8.2

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
octa quad plane

#### Hardware type
PH2.1

#### Logs
https://drive.google.com/open?id=1mZi9mrij_aSz5EY0EfqxtIXXUTdrNfOI

**Comment by IamPete1** [comment]
sorry we never got to this, I cant replicate in SITL, please reopen if this is still a issue on 4.1
