### ISSUE TITLE
AP_Follow: account for timing jitter in global-position-int transmission time

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7830]
Follow mode (which is entering master with this PR: https://github.com/ArduPilot/ardupilot/pull/7655) should attempt to compensate for timing jitter in the time it takes for the global-position-int message to be sent from the leader to the follower.

I do not know exactly how this should be done but I think within AP_Follow::handle_msg method, we should record the message's time_boot_ms field (i.e. "packet.time_boot_ms") to a new uint32 variable called _last_location_update_remote_ms.

We should not expect the follower's system time to be the same as the leaders.  I.e. following vehicle's AP_HAL::millis() could be completely different than the GLOBAL_POSITION_INT message's time_boot_ms field.  Still, the value of follow's AP_HAL::millis() - GLOBAL_POSITION_INT.time_boot_ms should be relatively stable and when it's not we should somehow account for this when estimating the lead vehicle's position.

**Comment by IamPete1** [comment]
Looks like this was fixed in https://github.com/ArduPilot/ardupilot/pull/10138
