### ISSUE TITLE
reading apm2.5 sensors using arduino ide 

### ISSUE THREAD

**Issue by amitmanish** [ArduPilot/ardupilot#7833]
I am trying to read apm2.5 sensor data like mpu6000,ms5611 and hmc5843. I have successfully read mpu data but could not read barometer and compass. Any help would be appreciable.

**Comment by magicrub** [comment]
Are you asking how to do it from ArduPilot? You've posted a help question in the bug tracker for ArduPilot. Sounds like what you're wanting is the Arduino forums but if it's actually an ArduPilot question please check with our forums at discuss.ardupilot.org
