### ISSUE TITLE
Camera trigger type 'Relay' does not function with Pixhawk

### ISSUE THREAD

**Issue by austinforsyth** [ArduPilot/ardupilot#785]
We have been flying an APM2 quad with a relay triggered CHDK camera for several weeks, but we are running into a roadblock when configuring our Pixhawk (Iris platform) to perform camera triggering via relay.

In my tests I have been able to set CAM_TRIGG_TYPE to 0 for servo, CH7_OPT to 9 for camera trigger, then RC9_FUNCTION to 10 for camera trigger. Using a multimeter I am able to observe a change in DC voltage between the - and S "Aux Out 1" pins on the Pixhawk, when triggering via CH7, and the duration of this voltage change will properly correspond to the CAM_DURATION value.

However, with CAM_TRIGG_TYPE set to 1 for relay, RELAY_PIN* to 13 for APM2 A9 pin, CH7_OPT still set to 9 for camera trigger, and RC9_FUNCTION set to 0 for disable I am unable to observe any change in DC voltage between the - and S "Aux out 1" pins on the Pixhawk.

* - the RELAY_PIN value may be the culprit here? The options for RELAY_PIN in Mission Planner are documented as follow:

13:APM2 A9 pin
47:APM1 relay
111:PX4 FMU Relay1
112:PX4 FMU Relay2
113:PX4IO Relay1
114:PX4IO Relay2
115:PX4IO ACC1
116:PX4IO ACC2

I have tried all of these values and been unable to observe any response on the Aux Out 1 pins while triggering via CH7.

So while I have been able to configure servo triggering on RC9 / Aux 1, I have not been able to achieve relay triggering or find definitive information as to what RELAY_PIN value(s) are valid for the Pixhawk and their corresponding physical pins.

Looking in the AP_Relay.cpp code for ArduCopter-3.1 shows definitions for APM1, APM2 and PX4:

#if CONFIG_HAL_BOARD == HAL_BOARD_APM1
#define RELAY_PIN 47
#elif CONFIG_HAL_BOARD == HAL_BOARD_APM2 || CONFIG_HAL_BOARD == HAL_BOARD_AVR_SITL
#define RELAY_PIN 13
#elif CONFIG_HAL_BOARD == HAL_BOARD_PX4
#define RELAY_PIN 111
#else
// no relay for this board
#define RELAY_PIN -1
#endif

Elsewhere in the code, specifically AP_BattMonitor.h there is a singular reference to Pixhawk with HAL_BOARD_PX4 combined with ARCH_BOARD_PX4FMU_V2:

#elif CONFIG_HAL_BOARD == HAL_BOARD_PX4 && defined(CONFIG_ARCH_BOARD_PX4FMU_V2)
// pixhawk
#define AP_BATT_VOLT_PIN 2
#define AP_BATT_CURR_PIN 3
#define AP_BATT_VOLTDIVIDER_DEFAULT 10.1
#define AP_BATT_CURR_AMP_PERVOLT_DEFAULT 17.0

And while I will be the first to say that I am not familiar with the code and libraries for ArduCopter, I have to wonder if for Pixhawk's hardware there just has not been any implementation for RELAY_PIN yet?

Thank you,

Austin Forsyth

**Comment by jordantkirby** [comment]
@tdeberle did you ever end up getting yours to work with that step-up converter?

**Comment by austinforsyth** [comment]
@jordantkirby 

People have been using Marco's circuit with home made cables since his post.

You can buy one from Tuffwing if you prefer not to fiddle with the circuit:

http://www.tuffwing.com/store/store.html#PixHawk_Camera_Trigger_Cable

**Comment by rscarawa** [comment]
Cannot get my camera to cycle no matter what pin I use not configuration?   Should I not be able to get the camera to cycle with just a regular usb cable with a servo plug on it?  If I have a bec on the servo rail, why would a regular cable not work?  What is the trick?  I can cycle the camera with a battery on my cable.  Which rc connector should I use?  The documentation and samples seem to be all over the place.  Mission planner says to use rc7.  Some people use aux2/rc10.  The pix docs show using aux5.  Any help would be appreciated unless this is just nonfunctional.  Thx

**Comment by R-Lefebvre** [comment]
What voltage level is your system outputting?  (see above discussion)

**Comment by rscarawa** [comment]
5.07v last I measured it.  It is powering the output Vail via switching bec regulator.

**Comment by R-Lefebvre** [comment]
That is the signal level, or the voltage on the rail?

**Comment by rscarawa** [comment]
Voltage on the rail.

**Comment by rscarawa** [comment]
To be specific, it is measuring the voltage between to and middle pin.

**Comment by R-Lefebvre** [comment]
I hesitate to continue this discussion here because it's definitely a support issue now. You're not doing it right.  The voltage on the rail, is not the same as what is coming out of the signal pin.  You need to use a level converter, as detailed above.

**Comment by WickedShell** [comment]
This is all support problems/wiring problems, not a code issue. Camera triggers are working correctly without a problem on Pixhawk.

**Comment by austinforsyth** [comment]
I'm going to hop in here to mention that 2+ years ago it was indeed a code issue - 

"I am unable to observe any change in DC voltage" (No AUX pin code originally)

 - with 3DR selling Pixhawk units without the existence of supporting software (and documentation) for features previously in use on other boards, but with the marketing hype and salesmanship to insist it was all there. Thank you for recognizing 3DR's continuing failure to provide commercial support for a commercial product, seeing as people return to this thread for answers.

Also not entirely surprised that the code base is so poorly maintained that a 2+ year old issue is just now being closed?
