### ISSUE TITLE
gps fuse error

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#7853]
#### Issue details
use EKF2
![_20180306133730](https://user-images.githubusercontent.com/16251761/37015669-8bbc94ac-2143-11e8-8efc-8674422e5b3f.png)

![_20180306133418](https://user-images.githubusercontent.com/16251761/37015617-2d226b60-2143-11e8-8680-c76cc478550d.png)

#### Version
3.8.4

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ * ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
quadplane

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by liang-tang** [comment]
@priseborough

**Comment by priseborough** [comment]
Please provide a link to your flight log.

**Comment by liang-tang** [comment]
here is the link
https://drive.google.com/file/d/1ur8YvJdgiL2j6a1g4urNe1h7oqq2HYJi/view?usp=sharing

**Comment by liang-tang** [comment]
another log，same issue，both of them， at the end of log 
[log2 link](https://drive.google.com/open?id=10FSemdYmC3wyMsGeEGu_FkgQ7lLpfGpA)

**Comment by liang-tang** [comment]
![image](https://user-images.githubusercontent.com/16251761/37070044-d4c9a16e-21f0-11e8-95d6-6e1cef3088c1.png)
