### ISSUE TITLE
External compass orientation separation from AHRS orientation

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#7859]
#### Issue details
Right now, COMPASS_ORIENT is combined with AHRS orientations (According to the complete parameter list wiki). I think it should be separated for EXTERNAL compasses and reference the frame rather than the flight controller.

For internal compasses, the compass orientation parameters could be ignored and reference the AHRS_ORIENTATION so users can't mess that up.

In addition, the reverse transformations from the flight controller could get complicated if the AHRS orientations are expanded to include custom orientations as was proposed in the dev call on 3/5/2018.

#### Version
All

#### Platform
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by Naterater** [comment]
It may just be a documentation issue. Either way, it should be clarified.

![image](https://user-images.githubusercontent.com/35429159/37062997-aca52a3e-215d-11e8-84ca-888273440055.png)

**Comment by rmackay9** [comment]
Yes, I'm 99% sure that they're already separate for external compasses so I think we can close this.  If it's a documentation issue then probably belongs on the wiki issues list (or maybe just go ahead and change it).
