### ISSUE TITLE
UAVCAN for SITL

### ISSUE THREAD

**Issue by khancyr** [ArduPilot/ardupilot#7913]
#### Issue details
UAVCAN is available on linux and working wuth socketcan. This allows to simulate CANbus over socket on a computer. 
Then it would be interesting to get an inclusion of some UAVCAN nodes into SITL. 

This should modify sitl_state and register uavcan as new external device on sitl model. This will allow to update SITL with simulated CAN and provide feedback to controler.

**Comment by magicrub** [comment]
+1

**Comment by auturgy** [comment]
Can this be closed?

**Comment by khancyr** [comment]
@auturgy It has been done yet !

**Comment by auturgy** [comment]
Sorry. Just found it. https://github.com/ArduPilot/ardupilot/pull/8509 hasn’t been merged yet.

Regards,

James

**Comment by IamPete1** [comment]
We have SITL CAN now with https://github.com/ArduPilot/ardupilot/pull/14477
