### ISSUE TITLE
PLANE: BRD_SAFETY_MASK Defaults to 1 but should be 0

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#7921]
#### Issue details
Channel 1 is not affected by the safety switch by default. Change the defaults so that it is.

#### Version
Plane 3.8.4

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Traditional with Aileron set to channel 1

#### Hardware type
Pixhawk and Pixhawk 2.1

#### Logs
N/A

**Comment by magicrub** [comment]
Looks like the default is 0 for all hardware and all vehicles. I also just did a reset on a cube running Plane 3.8.4 and it is 0.

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BoardConfig/AP_BoardConfig.cpp#L149

Closing.

Where do you see it being 1?
