### ISSUE TITLE
Rover: move methods in commands_logic.cpp to mode_auto

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7978]
This is quite similar to [this Copter issue](https://github.com/ArduPilot/ardupilot/issues/7707).

We've restructured the Rover so that all the modes are classes (see mode.h, mode_auto.cpp, etc).  As a follow-up we should move the contents of the [commands_logic.cpp](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/commands_logic.cpp) file into [mode_auto.cpp](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/mode_auto.cpp).

This will include:

- moving the method definitions from [Rover.h](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/Rover.h#L404) into [mode.h](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/mode.h#L185).
- move the implementations from [commands_logic.cpp](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/commands_logic.cpp) to [mode_auto.cpp](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/mode_auto.cpp) and change the class the methods belong to so instead of starting with "Rover::" they start with "ModeAuto::".
- ensure the order that the methods appear in mode.h matches the order within mode_auto.cpp

After performing the move, ensure it compiles and it would be best to run a simple Rover mission.

**Comment by bCamba** [comment]
@rmackay9 I have a question about the third bullet point. Should I change the methods order in mode.h file to match mode_auto.cpp or the other way around?

I worked on the Copter related issue #7707 so I can work on this one as well

**Comment by naveentrtumkur** [comment]
@bCamba I would like to take up this issue. I'm getting familiar with arduPilot codebase and SITL testing. Solving bugs like this would be a good start for me. If you haven't started working on this, may I take up this issue?

**Comment by rmackay9** [comment]
@bCamba, I think for the most part, the .h file has a good order so making the .cpp match the .h is best.

@naveentrtumkur, we have lots and lots of issues so let's see if we can find you another one :-).

**Comment by bCamba** [comment]
@naveentrtumkur, I have not started yet. Feel free to tackle this one :)

**Comment by naveentrtumkur** [comment]
@rmackay9 As part of this issue re-working, I was studying the different modes available. I didn't clearly understand loiter mode. It says "automatic horizontal acceleration with automatic throttle". My understanding was : In loiter mode, there would be automatic horizontal acceleration of vehicle with pauses after specific duration. Can you breifly explain loiter?

**Comment by sarthak268** [comment]
Is this still open? If yes, please assign

**Comment by peterbarker** [comment]
@cindyywang do you have a PR for this issue?

**Comment by sarthak268** [comment]
Please assign

**Comment by peterbarker** [comment]
@sarthak268 I've assigned this to me on the assumption you'll poke it.

**Comment by sarthak268** [comment]
Thanks

**Comment by sarthak268** [comment]
What all still needs to be done in this issue?

**Comment by MohamedAliRashad** [comment]
#10847 I think this PR close the issue.

**Comment by OXINARF** [comment]
This was done by #8019/#8023/#10827.
