### ISSUE TITLE
Rover: update scheduler's task list's function run time estimates

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7986]
The scheduled tasks list  ([found in APMrover2.cpp](https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/APMrover2.cpp#L45)) has 3 columns, the last column holds the estimated time that the function will take.  The estimates are overly conservative which likely leads to tasks not being run when they actually could be.

We should go through the list and time each function on a standard Pixhawk.  When I do this I add some code like below to the top and bottom of each function (I do one at a time).  This sends the time the function took to the ground station (using mavlink) at about 1hz.  I then take the average of these calls, add 20% or so and then update the expected time in the scheduler.  There may be better ways to do this (@peterbarker, any better way?)

> uint32_t start = AP_HAL::micros()
> ....regular function contents are here....
> static uint32_t counter = 0;
> counter++;
> if (counter > 50) {
>    counter = 0;
>    uint32_t time_diff_us = AP_HAL::micros() - start;
>    gcs().send_text(MAV_SEVERITY_INFO, "t:%lu",(unsigned long)time_diff_us);
> }

**Comment by peterbarker** [comment]
@rmackay9 I usually use the performance counters for this.

If you `set SCHED_DEBUG` >=1 you get all sorts of cool stuff.

You have to use the nsh console's `perf` command to get at the good stuff, 'though:

```
nsh> 
perf
.
.
twentyfive_hz_logging: 1676 events, 0 overruns, 5555us elapsed, 3us avg, min 2us max 184us 9.716us rms
ten_hz_logging_loop: 671 events, 0 overruns, 6287us elapsed, 9us avg, min 6us max 179us 18.004us rms
update_trigger: 3348 events, 0 overruns, 6921us elapsed, 2us avg, min 1us max 208us 6.605us rms
update: 3352 events, 0 overruns, 3754us elapsed, 1us avg, min 1us max 177us 5.686us rms
gcs_data_stream_send: 3337 events, 0 overruns, 558980us elapsed, 167us avg, min 21us max 2422us 398.309us rms
gcs_send_deferred: 3345 events, 0 overruns, 13855us elapsed, 4us avg, min 3us max 202us 10.621us rms
gcs_send_heartbeat: 67 events, 0 overruns, 8966us elapsed, 133us avg, min 104us max 324us 51.091us rms
gcs_check_input: 26282 events, 0 overruns, 615739us elapsed, 23us avg, min 12us max 1711us 81.801us rms
lost_vehicle_check: 671 events, 0 overruns, 1280us elapsed, 1us avg, min 1us max 140us 7.624us rms
landinggear_update: 671 events, 0 overruns, 846us elapsed, 1us avg, min 1us max 38us 1.715us rms
gpsglitch_check: 671 events, 0 overruns, 1699us elapsed, 2us avg, min 1us max 209us 10.227us rms
ekf_check: 671 events, 0 overruns, 1420us elapsed, 2us avg, min 1us max 107us 5.590us rms
one_hz_loop: 67 events, 0 overruns, 219173us elapsed, 3271us avg, min 2932us max 5146us 365.251us rms
update: 3359 events, 0 overruns, 31823us elapsed, 9us avg, min 6us max 179us 13.906us rms
fourhundred_hz_logging: 26759 events, 0 overruns, 58514us elapsed, 2us avg, min 1us max 224us 7.521us rms
.
.
.
```

**Comment by khancyr** [comment]
can we have nsh like on SITL :-P ?

**Comment by rmackay9** [comment]
This has been fixed in master.
