### ISSUE TITLE
Arduplane/jsbsim

### ISSUE THREAD

**Issue by yahyaelabiad** [ArduPilot/ardupilot#7990]
Hi 
i'm trying to start JSBSIM with arduplane using sim_vihecle -f jsbsim:Rascal 
and and getting output on flightgear who is in another network 
can anyone help me please ? what i have to do

**Comment by khancyr** [comment]
Hello, 
As said yesterday, we don't do support here. This place is for issue and code improvement. Please ask your question on https://discuss.ardupilot.org/ . Thanks

**Comment by magicrub** [comment]
I don't know anyone using flight gear. Have you tried Real Flight? http://ardupilot.org/dev/docs/sitl-with-realflight.html There's also the normal sim. Please post your forum link here
