### ISSUE TITLE
Flight Time Counter

### ISSUE THREAD

**Issue by aerodolphin** [ArduPilot/ardupilot#800]
I would be nice to have a flight time counter. We have an UAV that would like to loan but this will require a way to count the flight time.

After the loan we check the flight time counter. Off course that should be difficult to erase or modify that data. The idea is to never be possible to erase the counter, at least without a password.

**Comment by peterbarker** [comment]
We now have a flight-time counter.

If people want the counter to be non-resettable, please open a new issue for that.  I can't see a way of reliably doing that with PixHawk as it currently stands; a user could reasonably snapshot the PixHawk's universe and reinstate it undetectably after many flights.  This is only hard for the first person; all subsequent people attempting to subvert it just follow the YouTube video instructions.

Presumably you could implement something harder to subvert on Linux-based autopilots using e.g. intel's tamper-proofing technology.

Frankly, probably better to trust your customer and offer services associated with their usage of the vehicle (e.g. post-flight analysis and vehicle health monitoring).

Again, please open another issue if you want tamper-proof counters.
