### ISSUE TITLE
RC failsafe and battery failsafe are not working

### ISSUE THREAD

**Issue by gouri1694** [ArduPilot/ardupilot#8005]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
 Copter

#### Airframe type
_What type of airframe (X_quadcopter)_

#### Hardware type
_What autopilot hardware was used? (pixhawk)_

#### Logs
_Please provide a link to any relevant logs that show the issue_
 I have set up parameters of battery and RC, even then failsafe is not working
Whenever i turn off my transmitter, the copter will be in arming. Please help

**Comment by auturgy** [comment]
Please post your issue, with log files if you can, to discuss.ardupilot.org
If the problem is code related, we can raise an issue here when it is identified, but initial user help is best sourced from the forum.
Thanks.

Regards,

James
