### ISSUE TITLE
adafruit ADS115 (ADC)

### ISSUE THREAD

**Issue by rayanPrish** [ArduPilot/ardupilot#8007]
is there any driver to use adafruit ADS115 (ADC) or I can use the example of analogic drivers

**Comment by auturgy** [comment]
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_ADC/AP_ADC_ADS1115.cpp

For your application also look here: 
https://aerotenna.readme.io/docs/external-battery-monitor-with-adc

For the future, help requests should go in the forum discuss.ardupilot.org
