### ISSUE TITLE
TradHeli: Support 135/140 pure inputs

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#8012]
Support "pure inputs" without scaling.

before 3.3 that had adjustable pitch/roll compensation this would be possible

**Comment by ChristopherOlson** [comment]
This is a preliminary WIP patch to support the Thunder Tiger style reverse collective swashplates.
https://github.com/ChristopherOlson/ArduHeli/commit/c2563027a5ed1bde605886b3aa81425df9e4d671

To Do: determine scaling for the 135/140 layout with mechanical mixing

**Comment by lvale** [comment]
on 3.6 RC
