### ISSUE TITLE
Change behavior of BRD_SAFETYENABLE = 0

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#8016]
Change behavior of BRD_SAFETYENABLE = 0 (DISABLE) so that it is actually disabled. Right now it means to boot in a disabled state but if it is connected it can still change the arming state.

new behavior: 0 (DISABLED) means button input is ignored. Truely disabled/ignored..

**Comment by magicrub** [comment]
this issue was created from the problem discussed in issue https://github.com/ArduPilot/ardupilot/issues/7985

**Comment by Naterater** [comment]
I would still like a 2-step arming process without the potential to have the switch activated mid-flight.

BRD_SAFETYENABLE = 2 (ONLY WHEN DISARMED)?

**Comment by DavidIngraham** [comment]
Closing, as this was addressed in #8156
