### ISSUE TITLE
Copter: move get_default_auto_yaw_mode from mode_auto.cpp to mode.cpp.

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#8018]
At the very [bottom of mode_auto.cpp](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode_auto.cpp#L1882) we have a few functions that are part of the Copter class than we should be able to move to the Mode class (i.e mode.h, mode.cpp) or move to Attitude.cpp (@peterbarker do you know where they belong?).

- get_default_auto_yaw_mode
- set_auto_yaw_mode
- set_auto_yaw_rate
- get_auto_heading
- get_auto_yaw_rate_cds

- set_auto_yaw_look_at_heading  <-- called from GCS_MAVLink.cpp
- set_auto_yaw_roi <-- called from GCS_Mavlink.cpp

**Comment by peterbarker** [comment]
@rmackay9 Yes, I know how this stuff should be cleaned up (IMO): https://github.com/ArduPilot/ardupilot/pull/7458

**Comment by amilcarlucas** [comment]
@rmackay9 just approve #7458.
Then I can do some PRs on top of that. ;)

**Comment by sarthak268** [comment]
Is this still open? If yes, please assign it to me.

**Comment by peterbarker** [comment]
@sarthak268 Thanks for the interest, but these have been dealt with; these have all been collected into `autoyaw.cpp` IIRC.
