### ISSUE TITLE
JR Xbus support on PixHawk

### ISSUE THREAD

**Issue by chandruth** [ArduPilot/ardupilot#804]
Hi
Other than sbus any chance of JR Xbus support being added. The link posted below shows that Xbus mode b is quite similar to sbus.

http://www.rcgroups.com/forums/showthread.php?t=2018101&page=2

Having Xbus work on pixhawk will be a great help with wire management for those of us using new JR transmitters like XG14 as the ppm encoder solution is very messy on small frames with all those wires.
Regards
Chandruth

**Comment by omcaree** [comment]
I have just submitted a pull request to the PX4Firmware repository which adds XBus support to the Spektrum port. Tested and working with the XG14 transmitter

**Comment by Naterater** [comment]
Does the JR Xbus protocol work in the newer firmwares?

**Comment by OXINARF** [comment]
According to code comments, we do support it. If it doesn't work, it's a bug. Given no answer in 6 months, I gather interest in this is low anyway.

Closing it.
