### ISSUE TITLE
AP_NavEKF: Optical flow fusion has dead assignments

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/ardupilot#8040]
#### Issue details
A local is set, and then promptly discared in optical flow fusion in both ekf2/3. I'm guessing we can remove the code, but wanted to touch base with @priseborough that these aren't actually supposed to be useful values.
libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp:576
libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp:422

Found by clang static analysis.

#### Version
428682c8e92c2

#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Too much code change to tell if this has been resolved or not just from the line number, so I'm going to close.
