### ISSUE TITLE
ardupilot copter 3.5 build error 

### ISSUE THREAD

**Issue by amitmanish** [ArduPilot/ardupilot#8055]
I am trying to build copter 3.5 in linux but getting error "Not a git repository " while using submodule update. Can anyone help me.

**Comment by auturgy** [comment]
This is a support question, not an actual issue, so please post it in our forum discuss.ardupilot.org
I also suggest you read the wiki from here: http://ardupilot.org/dev/docs/where-to-get-the-code.html
