### ISSUE TITLE
Copter: add loiter to battery failsafe options

### ISSUE THREAD

**Issue by britdavis** [ArduPilot/ardupilot#807]
[enhancement request]

Would it be possible to add Loiter in the Battery Failsafe actions list? I'd prefer to have this available, especially for testing, and think it might be a safer way to get comfortable with failsafe actions.

It would also be useful by allowing me to switch my Tx to high power and/or resolve my radio issue without it descending into a lake(always land) or beginning a nav-guided path (always RTL).

**Comment by jmachuca77** [comment]
Most likely will be closed by #8536

**Comment by peterbarker** [comment]
We currently allow a battery failsafe option of `set_mode_brake_or_land_with_pause`.

I think that's probably close enough to the original intent of this PR, an option to have the vehicle hold still while the user figures things out.

Does anybody disagree?

**Comment by rmackay9** [comment]
I agree.  I think you're reviewing the issues list so I'll just put a thumbs-up/down from now on your comments.
