### ISSUE TITLE
Cant Compile "Master" Arducopter

### ISSUE THREAD

**Issue by shaddow501** [ArduPilot/ardupilot#8071]
Hello

When I try to compile make PX4-V4 I get this error:

GCS_Mavlink.cpp:32:13: error: declaration of 'base_mode' shadows a member of 'this' [-Werror=shadow]
     uint8_t base_mode = MAV_MODE_FLAG_STABILIZE_ENABLED;

**Comment by OXINARF** [comment]
This is now fixed.

**Comment by shaddow501** [comment]
Thanks
