### ISSUE TITLE
Ardupilot tunning in mission mode

### ISSUE THREAD

**Issue by Oussalvatore** [ArduPilot/ardupilot#8094]
#### Issue details
What I understood after reading the Ardupilot docs and some issues in github, in mission mode and before reaching a targeted waypoint (fast waypoint) the UAV will start decreasing the speed to ensure a seamless transition to the next waypoint, the value of the new speed depends on the angle between the current line tracking and the next line tracking.  My questions are :

1) At which point the speed will be adjusted ??
2) How to calculate this point ??
3) How the value of the new speed is mapped to the angle ?? do you have any formula ??

Thank you.

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Hardware type
SITL simulator

**Comment by magicrub** [comment]
@Oussalvatore Hi there. You've posted a Help or HOWTO question in the github bugtracker. Please repost it at the forums at discuss.ardupilot.org.
