### ISSUE TITLE
All motors with pixhawk is not roatating in quad rotor, rotating ambigiously

### ISSUE THREAD

**Issue by ARPIT355** [ArduPilot/ardupilot#8103]
I have install pixhawk and tried to takeoff with raspberry pi 3 but all motors are not rotating . Kindly help me , my project submission date is near... I have same setup as yours plzzz help me out. Is it related to wrong configuration  or any parameter??﻿

**Comment by proficnc** [comment]
Please ask your questions on the discuss.ardupilot.org forum or Facebook.

I would suggest calibration of your ESC’s

GitHub issues are not for support requests
