### ISSUE TITLE
Development of Firmware for own airframe

### ISSUE THREAD

**Issue by akshaytimmalapur** [ArduPilot/ardupilot#8152]
#### Issue details
Hello,

I am working on the design of a new airframe and hence I would like to write a firmware for that particular airframe design. 

I am using dropix v2 (PX4) as a flight controller and mission planner as a ground station. I need to write the firmware and use mission planner to upload firmware on flight controller.

I am new to mission planner and have never written a firmware or worked on firmware before. Hence I don't know what and where to begin. Can you please help with this difficulty and help me commence with something?

#### Version
flight controller - dropix v2 (PX4)
mission planner - 1.3.56 build 1.3.6672.30243

#### Platform
Copter

#### Airframe type
M working on completely new and different airframe design

#### Hardware type
dropix v2 (PX4FMU)

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by auturgy** [comment]
I’m going to close this, as it’s not an issue, but a help request.
But: welcome, and thanks for choosing ArduPilot!
Developer support is best through gitter: 
https://gitter.im/ArduPilot/ardupilot
The forum is also very active (discuss.ardupilot.org).

Regards,

James
