### ISSUE TITLE
Copter: 3.6 RangeFinder_VL53L0X stop working could be related to I2C scheduler !! 

### ISSUE THREAD

**Issue by shaddow501** [ArduPilot/ardupilot#8159]
Hello

I have encountered an issue when the RangeFinder VL53L0X is connected together with Toshiba LED.

it seems that when the Toshiba LEDis connected the VL53L0X hangs / freezes and stop working.

From my investigation it is not a hardware issue but a software issue.

Things I did to investigate:
First we know that the AP_Notify Toshiba_LED_I2C is looking for "ack" from the 0x55 address to find out if the LED is exist.

1. I powered on the PixRacer without the Toshiba LED while the GPS and VL53L0X was connected and it ran without any failures for couple of hours.
2. Powered on the PixRacer with the Toshiba LED + GPS + VL53L0X and the VL53L0X stopped working after a few minutes (more or less 10 min it worked till it stop getting data - seen by "sensorrange" in "Mission planner"

Then I thought that It might be a hardware issue, And to verify if it is hardware or code issue I turned on the PixRacer with the Toshiba LED waited till it recognized it (by flashing the LEDs) and then disconnected it, this was to emulate that the code will continue to send I2C data to the Toshiba LED.

The VL53L0X stopped working a few minutes later!

So I am now sure that something with the Toshiba LED driver/code cause interference with the VL53L0X.

**UPDATE:**
Where can I find how I2C schedule the commands since it seems to me that it doesnt wait till the line is free since every sensor has = dev->register_periodic_callback(20000/33000/50000                                    FUNCTOR_BIND_MEMBER
And sometimes it causes that sensors stop working if they fall into schedule of something else...
When I add 2 sensors that has 50000 scheduling it seems that one of them fall and wont recover.

**I have noticed that issue when setting the VL53L0X instead of the 33000 (33ms) to 50000  (50 ms) and at this point the MaxsonarI2C that worked before for couple of hours without any issues stated failing, didnt give measurements anymore.**
I have noticed that the MaxsonarI2C also have the 50000 (50ms) timing... 
When I changed the VL53L0X timing to about 70000 (70ms) the MaxsonarI2C  again worked without any issue.
I have changed the VL53L0X timing since the toshiba led runs at 20000 (20 ms) timing and that cause the VL53L0X  to stop working after a few min...

**Comment by rmackay9** [comment]
I've added a wiki to-do issue to improve the wiki page for this lidar: https://github.com/ArduPilot/ardupilot_wiki/issues/1216

**Comment by auturgy** [comment]
Does https://github.com/ArduPilot/ardupilot/pull/9024 fix this?

**Comment by rmackay9** [comment]
@auturgy, yes definitely.  Let's close this issue and we can re-open if we find the next release candidate still doesn't work.  The next release candidate will be released tomorrow or the day after and should be called Copter-3.6.0-rc7
