### ISSUE TITLE
Dataflash Logs attitude rate parameters

### ISSUE THREAD

**Issue by adrianobrum** [ArduPilot/ardupilot#8178]
#### Issue details
I'm doing a project based on autopilot, but I need to know some information which I cannot find documentation about. I need the information from the IMU, the flight dynamics, more specifically the attitude and the rate attitude. I suppose that the attitude I can get from the ATT parameter, but the rate attitude I saw two parameters from RATE and IMU, which one will give me the desired information? What units were used?

One more question, I'm making a new form of controller, but I need to reach the PID file, but I can't find it.

#### Version
Copter 3.4

#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quadcopter

#### Hardware type
Pixhawk

**Comment by rmackay9** [comment]
this isn't really the place for asking these sorts of questions so I'll close this issue if that's OK.  for developer questions either the discuss forums or gitter are better places.

the IMU will have the raw sensor information including the data from the gyros which will have the rate info in them.  The RATE message will have this same information but it will be corrected by the EKF (i.e. bias correction added).  My guess is the RATE message is in degrees/second.
