### ISSUE TITLE
Hexarotor: Crashed in Althold mode with GPS glitch (firmware: Copter 3.5.5)

### ISSUE THREAD

**Issue by churl11** [ArduPilot/ardupilot#8203]
#### Issue details
We tested the duration of the Hexarotor UAV in althold mode, in order to improve the altitude hold performance, we disable EKF2 and enable EKF3, so the autopilot could run under EKF3 with GPS 3D fix.
The accident is that when there is a GPS glitch, the measured altitude (Dalt in CTUN) is suddenly rising up with 100% motor's bursting. Unfortunately, the pilot didn't change althold mode into stabilized mode. the UAV hit the building and crashed.
We think there may be some mistake for altitude fusion algorithm related to GPS glitch under EKF3.

#### Version
Copter 3.5.5

#### Platform
[  ] All
[  ] AntennaTracker
[*] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Hexarotor UAV

#### Hardware type
Pixhawk 1

#### Logs
https://drive.google.com/file/d/1XPqZCMwQl8stCfSoejI4Dw-dr_ILOvU2/view?usp=sharing

**Comment by Kiwa21** [comment]
Did you use RTK GPS? How did you conclude there was a GPS glitch?

**Comment by IamPete1** [comment]
I'm not sure there is much we can learn from this log now were on copter 4.1. Sorry no one ever looked at it.
