### ISSUE TITLE
Preparing to add external SPI IMU for better flight

### ISSUE THREAD

**Issue by zarathustr** [ArduPilot/ardupilot#8211]
Hi guys, we have released a new external IMU consisting of ADI gyros and accelerometers. The flight experience has been improved. Also the control performance is better now. We are going to upload the source codes to APM for further support. As is known, the Pixhawk, Pixhawk 3 Pro and Pixhawk 4 all have onboard external SPI connector. The IMU is then applied to these platforms with sampling frequency of 1000Hz. 

The following is a typical sampling via the PX4 with 3 ADXRS620 gyros
![image](https://user-images.githubusercontent.com/15649421/39091429-63c8a5be-4626-11e8-92d7-e4b79014cbee.png)

With the onboard MPU6000 and external IMU, two test flights have been conducted. For the first one, the MPU6000 is used for computing attitude. The control performances are shown as follows:

![image](https://user-images.githubusercontent.com/15649421/39091497-9d24107c-4627-11e8-9a9e-c1fe2e4caa8a.png)

![image](https://user-images.githubusercontent.com/15649421/39091499-a6edec0e-4627-11e8-9923-2ba42b94c53b.png)

![image](https://user-images.githubusercontent.com/15649421/39091503-af37bd4a-4627-11e8-8a17-1461c09b475a.png)

![image](https://user-images.githubusercontent.com/15649421/39091505-b70323b6-4627-11e8-9c38-42cf754dd97c.png)

# **While for the external IMU, the performances are:**

![image](https://user-images.githubusercontent.com/15649421/39091514-e9205314-4627-11e8-87c1-4f53345cb7ab.png)

![image](https://user-images.githubusercontent.com/15649421/39091521-f7968756-4627-11e8-864b-5bc8994c46a3.png)

![image](https://user-images.githubusercontent.com/15649421/39091524-02aaabe0-4628-11e8-83d2-3d4c4777b12c.png)

![image](https://user-images.githubusercontent.com/15649421/39091527-09ee2b02-4628-11e8-94c4-8201c2de82d6.png)

Note that here during the two flights, the parameters are default and the quadrotor is operated at the same position so the comparison is fair. It is obvious that the attitude rates control using ADI IMU is better which leads to better controlling behaviour on the roll and pitch. The basic version containing 3 ADXRS620 gyros and two ADXL203 accelerometers will be priced at 1999 RMB (317.7707 USD) while for the medium version it would be 2999 RMB (476.7355 USD) which replaces the yaw gyro with ADXRS642. **All the sensors have been factory calibrated** including factors, misalignment, biases and temperature drift. We hope that this is going to improve the flight experience of APM in the future!

PS: The test PX4 ulog files can be downloaded on: [website](https://github.com/zarathustr/ext_imu_test)

**Comment by geofrancis** [comment]
very cool, those gyros are nice but well outside my price range, but it got me thinking does arducopter support any of the hobby grade gyros externally on the spi port? trying to vibration isolate a pixhawk is very difficult when you have lots of wires attached to it but being able to soft mount a external gyro somewhere on the airframe would do a lot of good.

**Comment by rmackay9** [comment]
@zarathustr, Ok,very interesting.  looking forward to the pull request.  Please consider doing a blog post as well on ardupilot.org.

@geofrancis, ardupilot supports quite a wide range of IMUs but normally I think we only look on the internal SPI port so some code changes would be required to make it look on the external port.  The code changes would be quite small though I think.

**Comment by geofrancis** [comment]
@rmackay9 I was thinking being able to mount an external IMU right in the CG could also be used to compensate for builds where the pixhawk is mounted far away from the CG.

**Comment by auturgy** [comment]
@zarathustr have you progressed this?

**Comment by Kiwa21** [comment]
@zarathustr Any updates ?

**Comment by niusanku** [comment]
any updates？

**Comment by trollp** [comment]
Is there any further information about the implementation?

**Comment by frontw** [comment]
> Is there any further information about the implementation?

+1

**Comment by neibrasil** [comment]
Any updates?

**Comment by rmackay9** [comment]
I might close this issue because it's really more of a notification instead of an enhancement or bug report and there is a similar enhancement request to add support for high-end (aka expensive) IMUs or even full AHRSs here: https://github.com/ArduPilot/ardupilot/issues/11479.

By the way, there are some new IMUs from Invensense (and perhaps other manufacturers as well) that have a higher range (30G instead of the 16G of older IMUs) and these should improve the vehicle's resistance to high vibrations.  These IMUs are starting to appear on new flight controllers like the Holybro Durandal and the Hex CubeOrange.
