### ISSUE TITLE
issue of Airspeed SDP3X

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#8220]
#### Issue details
I tested SPD33 airspeed yesterday, Flight was well. But SDP33 airspeed seems weird at low airspeed(below 1 pa), Bounce between 1.85 and 0 and discrete. Today I tested it again,  got the same result, but when i comment the `AP_Airspeed_SDP3X::_correct_pressure(float press)`, result is successive. So I geuss something wrong with `_correct_pressure`. 

#### Version
3.8.5beta2 release

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ * ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by liang-tang** [comment]
Flight test yesterday, ARSP is MS4535DO, ASP2 is SDP33 from drotek.
![1ea1eea6e96031c1186ba7d771c53fa](https://user-images.githubusercontent.com/16251761/39163464-3291d85c-47ad-11e8-9a9f-42342180e911.png)

Comment VS not Comment (_correct_pressure)

![317ff7eb26cb9861725868ad772b0ec](https://user-images.githubusercontent.com/16251761/39163529-852f5e04-47ad-11e8-872c-bb354b2fb43a.png)
![fe50964666a49ea94f278212f35f530](https://user-images.githubusercontent.com/16251761/39163538-8e78dd6e-47ad-11e8-98f6-aed54f62a618.png)

**Comment by WickedShell** [comment]
@liang-tang we need a raw log. There are a couple of known issues with this sensor and driver at this point that we are looking into. (Dataflash logs would be helpful for reviewing changes).

**Comment by liang-tang** [comment]
@WickedShell Test log of the last  two pictures.
https://drive.google.com/open?id=16dqQGCcCDowIrtNSARsal4suJcGBozhg
https://drive.google.com/open?id=1_BD4MoOvPqnDPH5DTc54dYZOxrqYsk52

**Comment by liang-tang** [comment]
change the follow line 
https://github.com/ArduPilot/ardupilot/blob/29e8866ea910b6b5ce31f416ec048b6ba1a6b53e/libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp#L255
to `float dp_pitot = 28557670.0f * (1.0f - 1.0f / (1.0f + (float)powf((flow_SDP3X / 5027611.0f), 1.227924f)));`
 can solve this  problem. I dont konw why , but it works actually.

**Comment by liang-tang** [comment]
PR 

> https://github.com/ArduPilot/ardupilot/pull/8229

Test log

> https://drive.google.com/open?id=14wWUNQ7xnyFeHHD8vgJphzxa3UIQTxIv

![1aa6584fa5c7e494d5380e8cef18f58](https://user-images.githubusercontent.com/16251761/39224797-96f0a5a2-487b-11e8-88fb-dac2969882a3.png)

**Comment by Naterater** [comment]
I've had a lot of good flights with this sensor, and seeing how the PR was merged, I'm going to close this issue.
