### ISSUE TITLE
Pixracer won't put spectrum receiver in bind mode

### ISSUE THREAD

**Issue by sher1ock** [ArduPilot/ardupilot#8241]
#### Issue details
The pixracer board won't put a spectrum receiver in bind mode. 
Everything is setup correctly and if I bind it before connecting it works normally.
I can flash px4 with no hardware changes and the bind function works just fine.
Tested with current versions of Plane, Copter, and Rover. 
#### Version
Plane: 3.8.5
Copter: 3.5.5
Rover: 3.2.3
#### Platform
[x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
N/A
#### Hardware type
pixracer r14 from [mRobotics](https://store.mrobotics.io/mRo-PixRacer-R14-Official-p/auav-pxrcr-r14-mr.htm)
#### Logs
N/A

**Comment by IamPete1** [comment]
sorry we never got to this, please open a issue if this is still a problem in 4.1
