### ISSUE TITLE
Pixhawk doesn't recgonise two rangefinders (sonar: Maxbotix I2CXL EZ4) as collision avoidance. 

### ISSUE THREAD

**Issue by deepanshidrone** [ArduPilot/ardupilot#8250]
#### Issue details
Hello, I would be really grateful if anyone could help me with this issue. 
I'm currently trying to set two sonars (Maxbotix I2CXL EZ4) as rangefinders for collision avoidance in quadcopter that has a Pixhawk as flight controller. I am obviously using an I2C splitter to connect all the stuff. First of all, how does the Pixhawk know which sonar is the number 1 and which is the number 2, as they are both connected in the I2C splitter? When I have a look to the rangefinder logs, the first one works properly but the second one seems to don't be recognized by the Pixhawk, what is the problem?

Thanks.

#### Version
Mission planner 1.3.56

#### Platform
[  ] Copter

#### Airframe type
Quadcopter

#### Hardware type
Pixhawk

**Comment by auturgy** [comment]
User support requests are best made on the forum (discuss.ardupilot.org), so I’m closing this.
You need to change the i2c address on one device (and then associated param to match). The maxbotix datasheet explains how to change the i2c address.
