### ISSUE TITLE
px4 toolchain git repository fatal

### ISSUE THREAD

**Issue by emretuncay** [ArduPilot/ardupilot#8278]
#### Issue details
I am trying to custom octo copter using ardupilot on pixhawk.I installed px4 toolchain and I changed mixfile based on my octocopter.When I make px4-v2 I get some fatal like below
![image](https://user-images.githubusercontent.com/38782255/39515640-6a4d2e84-4e03-11e8-9436-93b2847262ce.png)
How can I solve this fatal.Can you help you.
Thank you

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
octa

#### Hardware type
pixhawk

**Comment by amilcarlucas** [comment]
You did not read the instructions :)
Please issue a `git submodule update --init --recursive` in the root directory of ardupilot

**Comment by khancyr** [comment]
Hello,
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).

**Comment by emretuncay** [comment]
Thank you amilcarlucas 
I read the instructions and submodule worked 🥇
