### ISSUE TITLE
Mavlink OSD throttle always at 50% with twin engine setup

### ISSUE THREAD

**Issue by kingdraki** [ArduPilot/ardupilot#8292]
#### Issue details
With twin engine setup, 
SERVOn_FUNCTION = 73, 
SERVOn_FUNCTION = 74, 
throttle reported at Mavlink OSD is always 50% when no SERVOn_FUNCTION = 70 is present at setup.
When i put SERVOn_FUNCTION = 70 on an unused servo port OSD is working again.

#### Version
3.8.4 & 3.8.5

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Twin Engine Plane

#### Hardware type
Pixhawk

#### Logs
PARAM File:
[20180501_ardupilot_384.zip](https://github.com/ArduPilot/ardupilot/files/1972426/20180501_ardupilot_384.zip)

**Comment by yak-54** [comment]
I have the same issue my twin engine planes  3.8.4 & 3.8.5

PARAM File:

[rycbo-19-4-18-22-41-32.zip](https://github.com/ArduPilot/ardupilot/files/1976145/rycbo-19-4-18-22-41-32.zip)

**Comment by IamPete1** [comment]
I'm not really sure what we can do about this in AP, it sounds like a the OSD id just looking at the wrong thing? Maybe it is fixed now?

**Comment by IamPete1** [comment]
This is a issue with the MAVLink OSD. Happy to work with a OSD dev to get this fixed, but as I said, I'm not sure what we can do in AP to resolve this.

**Comment by yak-54** [comment]
its been fixed in 4+

**Comment by IamPete1** [comment]
Well, I'm surprised.
