### ISSUE TITLE
How to get the full parameters---STEER2SRV_P???

### ISSUE THREAD

**Issue by 1102sc** [ArduPilot/ardupilot#8302]
#### Issue details
How to get the STEER2SRV_P???
STEER2SRV_P = the smallest circle diameter of the plane in meter   or    must be  around 4 meters????   

#### Version
3.8.1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[√] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
flying wing

#### Hardware type
pixhawk

#### Logs
no log

**Comment by rmackay9** [comment]
It's best to ask questions in the [forums](https://discuss.ardupilot.org/c/arduplane).  Sorry to be strict but if we're not then our issues list (which is for bugs and enhancements) just turns into a support forum.
