### ISSUE TITLE
Skyviper keeps unbinding from transmitter

### ISSUE THREAD

**Issue by lordneeko** [ArduPilot/ardupilot#8305]
#### Issue details
When loaded from the AC master (last tried with http://firmware.ardupilot.org/Copter/2018-05/2018-05-04-11:05/skyviper-v2450/) the skyviper will not stay bound to the transmitter. It'll bind for a few seconds, and then at random intervals will lose, and you have to do a bind action again.

#### Version
http://firmware.ardupilot.org/Copter/2018-05/2018-05-04-11:05/skyviper-v2450/

#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter - Skyviper
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Skyviper

#### Hardware type
stock Skyviper hardware

#### Logs
The logs don't appear to show the unbinding. Even Tower HUD didn't report a RC Failsafe when it occurred. 
Here is the log from when it happened, but i dont' see anything.
https://drive.google.com/open?id=1Zc0WMloyNs7vRgUx6INL1uWOKMeuaHiv

**Comment by khancyr** [comment]
I agree this is a bug. Easy to reproduce : compile master and load it on skyviper the radio won't keep blinking ... The official firmware is working well.

I am pretty sure it was working before https://github.com/ArduPilot/ardupilot/commit/bccea9c8b933e281629b905d43ef7fceaf370eb4 ,I tried to revert it but it doesn't fix the problem. But I am pretty confident that the problem is around that time . On april 12th it the bug was already there (asked for confirmation but nobody anwser)

**Comment by lordneeko** [comment]
The last "master" that i tried before trying the one earlier was March 22 (not sure exactly which CI build i used).  But that one worked just fine with absolutely no issues. Randy made a Blog post about it being available in master a few days later and that's when he updated the wiki as well.

**Comment by khancyr** [comment]
nice ! So the error should be between march 22th and april 12th !

**Comment by mirkix** [comment]
Can confirm this issue, with ArduCopter 3.6-rc1 ChibiOS build.

![bildschirmfoto vom 2018-05-08 21-16-32](https://user-images.githubusercontent.com/10398007/39777887-24924cf6-5305-11e8-956d-533bb29619b6.png)

**Comment by khancyr** [comment]
@mirkix, with skyviper?

**Comment by lordneeko** [comment]
I'm out of town for a while. Can't confirm until I get back. I think there
were others that confirmed the bug as well

**Comment by mirkix** [comment]
@khancyr I will check it the next days with a testflight, but so far it seems to be solved. Tested only inside my lab.

**Comment by lordneeko** [comment]
I flew the v2450 tonight for quite a while on the latest master and had no transmitter issues. I think this can be closed. However I want to open a discussion in the discuss about how I could do a PR to update default parameters in !aster for the SV. It has a lot of alarms going off because of the new battery params and such. I'd like to fix those for future users.
