### ISSUE TITLE
Copter: Save trim & auto trim doesn’t have effect

### ISSUE THREAD

**Issue by Newton787** [ArduPilot/ardupilot#8309]
#arducpter3.5.5 #pixhawk #tricopter 
 
after performing these steps http://ardupilot.org/copter/docs/autotrim.html#save-trim1

"1. Check that your CH7 switch goes above 1800 on the MissionPlanner’s Hardware > Mandatory Hardware > Radio Calibration screen.

Set the CH7 Option to Save Trim on the Software > Copter Pids screen and press the “Write Params” button.

With your CH7 switch in the off position, fly your copter in Stabilize mode and use your transmitters’s roll and pitch trim to get it flying level.

Land and put your throttle to zero
5. Release the roll and pitch sticks and switch the CH7 switch high for at least 1 second.

Reset your transmitters roll and pitch trims back to the center and fly again and it should fly level now. If it does not repeat steps 3, 4 & 5."
My tricopter continues drift, BUT when I follow 1 at 5 step, and no reset all transmitters roll and pich trims the tricopter fly well

can i fly in auto mode, position hold and loiter with this situation ?

i put the log files to see
https://1drv.ms/u/s!AjRz1CCw8R2dg7AbTXojhdZjy1Bbhg

PICH LINES
[https://discuss.ardupilot.org/uploads/default/original/3X/6/6/66cd44a3285b31a1d1fe60e8f34b652f0933a760.PNG](url)
ROLL LINES
[https://discuss.ardupilot.org/uploads/default/original/3X/0/c/0c2a74f74c87a4e4b9eb728162e51750fb2f3c10.PNG](url)
UPDATE
This are settings in FUTABA T8J for de tricopter fly well

TRIM VALUES
[https://discuss.ardupilot.org/uploads/default/original/3X/8/0/80a9a6f84734b44f3ab32dceb0051cc07d72cb3d.jpg](url)
SUB TRIM VALUES
[https://discuss.ardupilot.org/uploads/default/original/3X/7/c/7cc18dd1a7358f10403e754c195af499b1e3c6a0.jpg](url)
Note i use elavon sub trim for the tricopter don’t fly back when i center the sticks on radio

i cam trim after AHRS_TRIM_X (Roll) and AHRS_TRIM_Y (Pich) for trimed tricopter, with these parameters the drone flies level without drift, but the HUD is not level anymore.
[https://discuss.ardupilot.org/uploads/default/original/3X/d/1/d1533bdb8bd7a86936f621e97d6fa075a51ecf8a.PNG](url)

currently the values are;
AHRS_TRIM_X = 0,09162576
AHRS_TRIM_Y = -0,3315797

when i use “calibrate level” to level the HUD on Mission Planner, the AHRS values is change and the drone back flies with drift before

**Comment by IamPete1** [comment]
I cant replicate this issue.
