### ISSUE TITLE
Servo gimbal not working if ESCType OneShot125

### ISSUE THREAD

**Issue by SergeyBokhantsev** [ArduPilot/ardupilot#8314]
#### Issue details
Having camera tilt servo function on out #5
If in MP set ESC Type = OneShot125 => camera servo goes crazy (moves out of limits)
If set ESC Type = Normal => gimbal servo works ok.

#### Version
3.6-rc1, Nuttx

#### Platform
[x] Copter

#### Airframe type
Quad copter X

#### Hardware type
Pixracer

**Comment by SergeyBokhantsev** [comment]
also, here is how MP ServoOutput screen looks like with Normal ESC type:
![image](https://user-images.githubusercontent.com/9112882/39676789-dbc1b71a-5178-11e8-93d1-e2f2e9723be7.png)

And here how its looks with OneShot125:
![image](https://user-images.githubusercontent.com/9112882/39676791-ec49bfe2-5178-11e8-9f91-315fa77ff3e2.png)

**Comment by OXINARF** [comment]
@SergeyBokhantsev Does this also happen with ChibiOS?

**Comment by SergeyBokhantsev** [comment]
@OXINARF no issue with ChibiOS, fixed :)
