### ISSUE TITLE
Save SITL state and resume later

### ISSUE THREAD

**Issue by welkerCode** [ArduPilot/ardupilot#8331]
#### Issue details
I am currently working on developing a planner for quadcopters using an RRT ("Rapidly Exploring Random Tree").  To do this, I will need to run SITL thousands, if not millions of times to explore different GPS locations, and save the state of the quadcopter (things like GPS location, airspeed, battery level, etc...).  However with the current version of ArduPilot, I have noticed that as I have tried to save the quadcopter parameters at certain waypoints, and then load them again into a new SITL simulation, its GPS, battery, etc... doesn't change to reflect that of the waypoint (it appears that parameters like GPS_POS1_X or SIM_GPS_POS_X don't change throughout the simulation).

Is there already a way to essentially take a snapshot of the quadcopter (its position, dynamics, battery, etc...), and then start SITL again with these parameters so that it can pick up where it left off?  This would be useful for exploring multiple paths from the same point in the mission.

#### Version
_What version was the issue encountered with_
APM:Copter V3.6-dev (6536bf39)

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Frame: QUAD

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
pixhawk/sitl

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by peterbarker** [comment]
Apologies for the rather delayed reply here.

checkpoint/restore of SITL's process state would be a massive undertaking - essentially a complete rewrite if we were to attempt to do it ourselves.  Projects like CRIU (https://en.wikipedia.org/wiki/CRIU) might be able to do this - but attempts to do that are essentially outside ArduPilot's domain (unless specific patches pop up to aid support for this process).
