### ISSUE TITLE
SITL installation on Ubuntu 18.04 Error: Package 'realpath' has no installation candidate

### ISSUE THREAD

**Issue by agtbaskara** [ArduPilot/ardupilot#8377]
I tried to setup SITL on my freshly installed Ubuntu 18.04 by following the instruction from http://ardupilot.org/dev/docs/setting-up-sitl-on-linux.html and when I run the install-prereqs-ubuntu.sh script there is an error that says realpath package is not available.

Output From Terminal:

Package realpath is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  manpages-pl manpages-fr-extra

E: Package 'realpath' has no installation candidate

**Comment by khancyr** [comment]
Hello, 
thanks for the report ! Please install "coreutils" 
I will update the script!
