### ISSUE TITLE
Copter: WPNAV_SPEED value is changed by switching to RTL mode

### ISSUE THREAD

**Issue by horiuchi4dn** [ArduPilot/ardupilot#8390]
#### Issue details
If RTL_SPEED is set to a value other than 0, switching to RTL mode changes the WPNAV_SPEED to the RLT_SPEED value, and the speed of subsequent missions is affected by that value.

This behavior causes surprises when resuming the mission from the RTL state.

#### Version
Copter 3.5.5
Copter 3.6-dev

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by khancyr** [comment]
Hello, 

I confirm the bug. It can be easily reproduce on SITL. Set a mission, set RTL_SPEED to 250 , launch the mission (the default speed is 500) , change mode to RTL, wait 5s, get back to auto, the mission will continue but at 250cm/s

**Comment by IamPete1** [comment]
@rmackay9 's fix has been merged, so I guess this issue is resolved.
