### ISSUE TITLE
Rover: add PIVOT_TURN_RATE parameter to control max rotation rate of pivot turns

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#8404]
This issue was raised [here in the discuss forums](https://discuss.ardupilot.org/t/skid-steer-mower-overshooting-pivot-turns/28910/18).

In Rover-3.3.1 the vehicle attempts to do pivot turns at the maximum rotation speed of the vehicles (held in the ATC_STR_RAT_MAX parameter) which is too high for some users.  We should add a new PIVOT_TURN_RATE parameter which holds the desired rate in degrees/second.  We could set the default to some reasonable value (90deg/sec perhaps?) or we could default it to zero in which case the vehicle would use the ATC_STR_RAT_MAX parameter as the rotation rate.

To help with the implementation:

- [there is advice here on adding parameters to Copter](http://ardupilot.org/dev/docs/code-overview-adding-a-new-parameter.html).  Rover is very similar.
- we should add a new "rate_max" (or similarly named) argument to mode.h/mode.cpp's calc_steering_to_heading function and APM_Control/AR_AttitudeControl's get_steering_out_heading() that allows the caller to specify the maximum rotation rate.  Inside the AR_AttitudeControl::get_steering_out_heading() we should add some limiting to the desired rate in the same way we limit the desired_rate using the ATC_STR_RAT_MAX parameter.

**Comment by rahulgo** [comment]
Hi I'm new to Open Source development. Would this be something I can tackle?
Thanks

**Comment by rmackay9** [comment]
@rahulgo, you can definitely give it a try!
