### ISSUE TITLE
[Plane]Desired Pitch rate cann't minus Gyro_y to get servo output

### ISSUE THREAD

**Issue by luweikxy** [ArduPilot/ardupilot#8431]
in fuction [stabilize_pitch()](https://github.com/ArduPilot/ardupilot/blob/512b327cd4f1bd7d33720107078d30bb11165711/ArduPlane/Attitude.cpp#L93), we call [AP_PitchController::get_servo_out(pitch_angle_err)](https://github.com/ArduPilot/ardupilot/blob/512b327cd4f1bd7d33720107078d30bb11165711/ArduPlane/Attitude.cpp#L107) to get servo output of pitch.
Then in [AP_PitchController::get_servo_out()](https://github.com/ArduPilot/ardupilot/blob/023e3b6e30dae577247fa3360cd1ee244cdd9292/libraries/APM_Control/AP_PitchController.cpp#L297),  we get desired_pitch_rate
``` C++
// Calculate the desired pitch rate (deg/sec) from the angle error
float desired_rate = angle_err * 0.01f / gains.tau;
```
And then we call _get_rate_out(desired_rate) to get servo output of pitch.
``` C++
return _get_rate_out(desired_rate, scaler, disable_integrator, aspeed);
```
in [_get_rate_out(desired_rate)](https://github.com/ArduPilot/ardupilot/blob/023e3b6e30dae577247fa3360cd1ee244cdd9292/libraries/APM_Control/AP_PitchController.cpp#L114)
``` C++
// Calculate the pitch rate error (deg/sec) and scale
float achieved_rate = ToDeg(omega_y);
float rate_error = (desired_rate - achieved_rate) * scaler;
```
, we want to calculate the pitch rate_error, **BUT**,:
#### however, achieved_rate = omega_y = _ahrs.get_gyro().y;, witch is in the body frame,
So, the problem is , desired_rate and achieved_rate are in two different frams, so they cann't do minus operation without  coordinate transformation.

**Comment by rmackay9** [comment]
maybe best is @lthall answers this one..
