### ISSUE TITLE
Rover: accel/decel limiting issues

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#8448]
There are at least four cases where the acceleration limiting is not working properly:

- [x]  while in Auto (but disarmed) the desired_speed is allowed to accelerate up to full speed meaning the vehicle immediately jumps to full speed once armed
- [x]  RTL-within-Auto jumps to Hold mode as soon as the vehicle reaches the wp-radius around home which leads to throttle jumping immediately to zero
- [ ]  the slow-down calculations in calc_reduced_speed_for_turn_or_distance use the distance to the waypoint but this tends to overestimate the remaining distance because the vehicle is always slightly off the path.  We should probably instead use the remaining-distance-along-path (i.e. use "location_path_proportional") so that we reduce the vehicle's speed to _desired_speed_final just as we decide we have passed the waypoint.

Update: these issues have been resolved in master:

- [x]  it immediately decelerates to zero after reaching a waypoint
- [x]  it does not correctly decelerate to zero before reaching a sharp turn on pivot-steering vehicles

**Comment by rmackay9** [comment]
1 and 2 are resolved in this branch: https://github.com/rmackay9/rmackay9-ardupilot/commits/rover-stop-fix

**Comment by IamPete1** [comment]
@rmackay9 any update? Was that branch mereged? it seems to be gone.

`calc_reduced_speed_for_turn_or_distance` function is not in master anymore.

**Comment by rmackay9** [comment]
@IamPete1, thanks for finding this.  I've just re-tested and as expected the top two issues have also been resolved so I'll close this.

Below is a picture dhowing the desired speed gently climbs and descends.
![image](https://user-images.githubusercontent.com/1498098/131423611-d520ee73-0a26-4d60-8f02-fe37e06c32e5.png)
