### ISSUE TITLE
AP_Declination generate.py AttributeError: 'int' object has no attribute 'ravel'

### ISSUE THREAD

**Issue by WyseNynja** [ArduPilot/ardupilot#8451]
#### Issue details
I tried to run generate.py, but got an error

#### Version
git master, cc899d74e2713c2ce15378da4956f627373a09f7

#### Platform
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Logs

```
$ python --version
Python 3.6.5

$ pip freeze
numpy==1.14.3
pyigrf12==1.2.1
python-dateutil==2.7.3
pytz==2018.4
sciencedates==1.3.5
six==1.11.0

$ ./generate/generate.py 
Traceback (most recent call last):
  File "generate/generate.py", line 40, in <module>
    intensity_table = np.empty((NUM_LAT, NUM_LON))
TypeError: 'float' object cannot be interpreted as an integer
```

I tweaked generate.py to cast NUM_LAT and NUM_LON to ints, but that breaks later:

```
Traceback (most recent call last):
  File "./generate/generate.py", line 48, in <module>
    x, y, z, f, d = igrf.gridigrf12(date, isv, itype, alt, lat, lon)
  File "/usr/local/lib/python3.6/site-packages/pyigrf12/__init__.py", line 16, in gridigrf12
    colat,elon = latlon2colat(glat.ravel(), glon.ravel())
AttributeError: 'int' object has no attribute 'ravel'
```

I think casting to an int is the wrong thing to do because with pyigrf12 1.2, the function was changed: `def gridigrf12(date:datetime, glat:float, glon:float, alt:float, isv:int=0, itype:int=1):`

Looks like `numpy` and `pyigrf12` changed since generate.py was written.

**Comment by WickedShell** [comment]
#9344 got the actual fixes for this in.
