### ISSUE TITLE
Copter: "Brake" mode does not respond to config.h parameter

### ISSUE THREAD

**Issue by GekoCH** [ArduPilot/ardupilot#8461]
**Issue details**

I use now the brake mode from time to time however the braking is really strong so I looked into the code whether we're able to reduce the braking force.
Sure in the config.h file of the ArduCopter there is a parameter called BRAKE_MODE_DECEL_RATE.
I tried to reduce it even down to 100cm/s/s however without success.
My copter still decelerates with approx 650 to 700 cm/s/s according to the log files.

I even tried to hardcoded some values into the control_brake.cpp file but it seems like those functions are not used by the brake algorithm since the copter still decelerates with the same strength as ever before...

**Platform**
[ ] All
[ ] AntennaTracker
[X] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

**Comment by IamPete1** [comment]
I cant replicate this in SITL, I suspect at least part of the issue is that PSC logs do not really show acceleration. They include the acceleration required to overcome drag, so we would not expect to see them flat line at the accel limit like we would see for the angle limits for example.
