### ISSUE TITLE
why function get_delta_angle_dt use _primary_accel, but not _primary_gyro?

### ISSUE THREAD

**Issue by Gangti** [ArduPilot/ardupilot#8463]
Hi, all

I'm reading following source, and see that function get_delta_angle_dt is using _primary_accel.
Should it use _primary_gyro?

https://github.com/ArduPilot/ardupilot/blob/b014b6c85720aaa1459112e404443212c786244f/libraries/AP_InertialSensor/AP_InertialSensor.h#L111

**Comment by peterbarker** [comment]
@Gangti well, turns out we do agree with you here - well spotted!

I've created a PR to fix the problem.
