### ISSUE TITLE
Send mavlink message through another serial port

### ISSUE THREAD

**Issue by rayanPrish** [ArduPilot/ardupilot#8466]
how can I send a mavlink message ( I need just one ) through another serial port while another continue to continously send to GCS. I have changed “chan” into MAVLINK_COMM_1 and MAVLINK_COMM_2 but nothing appears. any idea ? Also I don't found where i can change the path for serial port.
I use a raspberry pi3

**Comment by belaidH** [comment]
when you launch arducopter you can add arguments like "-A /dev/ttyPS0 -C /dev/ttyS3  -D /dev/ttyS6  " where A, B and C  define the path for the UART with same Name (A,B or C).
UARTC and D is usually used for telemetry.

**Comment by rayanPrish** [comment]
thanks it works perfectly
