### ISSUE TITLE
RELATED TO ARDUCOPTER

### ISSUE THREAD

**Issue by Rounakagrawalchirawa** [ArduPilot/ardupilot#8468]
#### Issue details
ARDUCOPTER CODE IS NOT ATTACHED WITH ARDUINO - ARDUCOPTER IDE. We are fetching code from your website https://github.com/ArduPilot/ardupilot but it is not giving us exact code for flying quad copter.

#### Version
ARDUINO - ARDUCOPTER

#### Platform

[ 4 ] Copter

#### Airframe type
_What type of airframe (FLYING QUAD)_

#### Hardware type
arducopter

**Comment by rmackay9** [comment]
ArduPilot (despite the name) isn't Arduino anymore.  We stopped supporting the Arduino boards (i.e. those with AVR CPUs) almost 3 years ago.
