### ISSUE TITLE
arducopter

### ISSUE THREAD

**Issue by Rounakagrawalchirawa** [ArduPilot/ardupilot#8470]
#### Issue details
i just want to fly and balance my quadcopter, and i am notable to find the perfect code for arducopter , please help me and provide the required code for this.

#### Version
_arduino arducopter APM 2.6

#### Platform
[ 1 ] Copter

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
This looks mostly like support, so I think it should be raised in [the forums](https://discuss.ardupilot.org/c/arducopter).  Sorry to be strict but if we're not, then our to-do list just becomes another support forum and the developers lose track of what needs doing.
