### ISSUE TITLE
Frsky Passthru library does not report vertical speed when in DCM mode

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot#8484]
All versions:
When in DCM mode, FRSky passthru does not report vertical speed (climb rate).
At least baro rate should be reported in this mode.
It is reported in VFR_HUD mavlink packets.

Discovered flying F4light HAL version on Omnibus F4 Pro since it must be flown in DCM mode until EKF issues with baro glitches are resolved.

**Comment by floaledm** [comment]
Hi Henry,

Thanks for reporting this!

It might be a good idea to first discuss whether DCM mode should be supported here. In essence, maybe we should think twice about a fix that will be resolved by a larger fix?.. as we may end up introducing code that ultimately will not be useful (once the larger fix is issued). I think it would be good to get some more perspective before anyone works on a PR to address this. Just my thoughts...

**Comment by Hwurzburg** [comment]
DCM has always been a fallback mode for EKF operation.....why stop sending telemetry in a valid mode?

Sent from Yahoo Mail on Android 
 
  On Thu, May 24, 2018 at 2:26 PM, Florent Martel<notifications@github.com> wrote:   
Hi Henry,

Thanks for reporting this!

It might be a good idea to first discuss whether DCM mode should be supported here. In essence, maybe we should think twice about a fix that will be resolved by a larger fix?.. as we may end up introducing code that ultimately will not be useful (once the larger fix is issued). I think it would be good to get some more perspective before anyone works on a PR to address this. Just my thoughts...

**Comment by Hwurzburg** [comment]
not sure of order of fallback, but whatever excessive innovations/divergence contributed to the EKF to stop aiding (excessive vibs, GPS dropouts, baro shift,etc.), its always possible to fallback to DCM temporarily in flight....thats why its still there and hasnt been removed...at least that is my understanding....

**Comment by WickedShell** [comment]
Looked into this briefly, as long as GPS is available then DCM will report a velocity NED which is how FrSky is getting the vertical speed, however if you are in DCM because you don't have GPS, then DCM does not have an estimate to provide you.

**Comment by yaapu** [comment]
why not fall back to baro climb rate like in the OSD code?
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_OSD/AP_OSD_Screen.cpp#L726

```
    if (ahrs.get_velocity_NED(v)) {
        vspd = -v.z;
    } else {
        auto &baro = AP::baro();
        WITH_SEMAPHORE(baro.get_semaphore());
        vspd = baro.get_climb_rate();
    }

```
