### ISSUE TITLE
Restore MNT_MODE and MNT2_MODE once auto mode is aborted, DO_MOUNT_CONTROL upload BUG

### ISSUE THREAD

**Issue by nhadrian** [ArduPilot/ardupilot#853]
Hi,

There is some BUG around MNT_MODE, because once ROI mission ends or is aborted, the MNT_MODE stays in ROI state, and camera mount can't be controlled again till next power on. 
(Additionally, camera not only stays in center but continues to look towards ROI, which is quite funny during flight... :) )

So probably the MNT_MODE and MNT2_MODE stored in the EEPROM should be restored once auto mode ends, or is aborted.

I found another BUG, DO_MOUNT_CONTROL uploading is has a BUG in MissionPlanner, because it writes 0,0,0,0 whatever I set up as mount mode in first number. I don't know wether the BUG is in AC or in MP.

Best regards
Adrian

**Comment by OXINARF** [comment]
@nhadrian Is this still a problem in a recent version of Plane?

**Comment by nhadrian** [comment]
Hi all, unfortunatelly I doesn 't have a working APM for a while. The problem was in Copter, if I remember I modified fw to enable two mounts, one was for sending frame positions to the gimbal controller (32 bit alexmos without frame imu) for follow frame mode and the second mount controlled the camera positions. Regards Adrian

**Comment by OXINARF** [comment]
Well if this was for Copter then it wasn't an issue in code in master. We still only support one mount in Copter. If you ever modify the firmware again to suite your needs and need some help, please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).
