### ISSUE TITLE
Copter: MAV_ROI_WPNEXT with no WP causes uncontrolled yaw

### ISSUE THREAD

**Issue by dergrunepunkt** [ArduPilot/ardupilot#854]
I had a problem that kept me busy for a week, it may not be a bug but I'm due to inform it.

I had no WP and I enabled (accidentally) MAV_ROI_WPNEXT flag/parameter, this caused the Quad to revolve (yaw) out of control on it's Z axis, would be nice to add a check to avoid this behavior, I don't have the skills to do it, but I know it's trivial to someone who has it.

I use 3DR APM v2.6 with FW v3.2.1

cheers!

**Comment by jmachuca77** [comment]
Any chance of giving a more detailed explanation on how to reproduce this? What mode was the copter in? how was MAV_ROI_WPNEXT enabled? I tried to reproduce this in SITL but was not successful, seems like an old issue and have not heard other reports of this anymore. So if no instructions are provided in the next few days I will close this issue.

**Comment by dergrunepunkt** [comment]
This was 4 years ago, I don't really remember.

Feel free to close the issue.
