### ISSUE TITLE
how to connect quad using APM 2.6 with pc via usb and get its position

### ISSUE THREAD

**Issue by Rounakagrawalchirawa** [ArduPilot/ardupilot#8540]
#### Issue details
_WE ARE SING DRONEKITS FIRMWARE AND WANT TO GET ALL PARAMETERS RELATED TO QUAD HAVING APM 2.6 ON GIT BASH. HOW CAN WE DO SO?_

#### Version
_APM 2.6_

#### Platform

[ ] Copter

#### Airframe type
_QUAD_

#### Hardware type
_ARDUPILOT APM 2.6_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by auturgy** [comment]
Please use the forum at discuss.ardupilot.org for support. The issues list is for bug reports or feature requests
