### ISSUE TITLE
Implement HoTT telemetry

### ISSUE THREAD

**Issue by Reddi82** [ArduPilot/ardupilot#856]
Hey! 

I hope I'm here right: I'm actual program a cpp class to send flightdata to my HoTT remote control via telemetry-receiver gr-12/16/24/...The class is now installed on an arduino where is only rx/tx connected to the receiver. (my plan was to integrate mavlink and then to use this arduino as a converter between copter and remote control.) I can send the most data blocks prepared for this modules: gps-module, general air module, electric air module and vario module. It would be great, if we can implement this class in an arducopter version in future. actual i will develop an interaction: my target ist to get the pushed buttons (for telemetry options) from the remote control. then i could realize e.g. (all) pid-settings via remote control telemetry... it needs only an rx/tx serial port to connect to the telemetry port from the receiver. If you interested to my class, let me know it. to my person: i still programm since a few years and now i am a study for informatics b.sc.. and i am a big fan of your software. :-)

sorry about my english ;-)

best regards from germany

**Comment by Ralfde** [comment]
how could the HoTT Telemetry activated in the actual arducopter 3.4.6?
Would be nice, if it would be selectable in the Mission planer like the other telemetries.

**Comment by auturgy** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/13160
