### ISSUE TITLE
Reverse Thrust using DShot

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#8579]
#### Issue details
DShot support does not currently support reverse thrust. The current behavior from BLHeli_32 ESC's is to ramp to full reverse thrust at about 49% input and then drop to slow forward thrust at 51% input. PWM input works as intended, but DShot would be desirable. 

This should open the doors to doing upside-down hovering with multicopters too!

#### Version
Plane 3.9 beta 1.
https://www.getfpv.com/lumenier-36a-blheli-32-32bit-2-6s-w-telemetry.html?utm_source=google&utm_medium=cpc&adpos=1o1&scid=scplp7847&sc_intid=7847&gclid=CjwKCAjw6djYBRB8EiwAoAF6oeCeEC8FclSl5bqbRb7lJNXFrs4e7Y0wg96wx8_vnUgk3h8RTbFEVRoCG7sQAvD_BwE

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[X] Plane
[X] Rover
[  ] Submarine

#### Airframe type
Traditional Plane. Eventually Twin. Right now I'm using a benchtop test rig though.

#### Hardware type
The Cube & BLHeli_32 ESC's flashed with the latest firmware.

#### Logs
N/A - @tridge confirmed the behavior was expected. Will wait for future improvements before released as beta.

**Comment by Naterater** [comment]
Bump on DShot Reverse thrust. This should open the doors to a lot of options including upside-down flying on multirotors.

**Comment by Naterater** [comment]
I'm ready to begin testing this on plane whenever it can be developed.

**Comment by Kelly-Foster** [comment]
I am also ready to test any enhancements here.

Kelly

**Comment by Naterater** [comment]
Bump for DShot reverse thrust.

**Comment by Naterater** [comment]
https://github.com/ArduPilot/ardupilot/pull/9743

**Comment by R-Ronald** [comment]
I was attempting to configure reverse thrust on a plane today and can confirm that Arduplane 4.1.6 doesn't work properly using Dshot150.  As the throttle advances past mid-stick, it goes from full speed to very slow.

Simply changing SERVO_BLH_OTYPE back to 0 (thus reverting from Dshot150 back to PWM) makes it work properly, The throttle sets forward motor speed for the entire throw and reverse functions properly when the channel assigned the 64 function is actuated.

I believe that this is related to an improper TRIM setting for the throttle SERVO channels. Trim is set to 1000 when Dshot is enabled. If one manually changes the throttle SERVO TRIM to 1500, the Dshot configuration works! But the TRIM value is changed back upon reboot to the value of 1000 and the error returns as well.
