### ISSUE TITLE
Rover: acceleration/deceleration bug in GUIDED

### ISSUE THREAD

**Issue by pavloblindnology** [ArduPilot/ardupilot#8594]
Currently, Rover cannot be accelerated in guided mode with zero acceleration specified.
According to [manual](http://ardupilot.org/rover/docs/parameters.html) for `ATC_ACCEL_MAX` you need to use `0 to disable acceleration limiting`.
But after last changes the check for zero values was removed
https://github.com/ArduPilot/ardupilot/blob/520e33261a1a89b01489e0a856162944f25457a2/libraries/APM_Control/AR_AttitudeControl.cpp#L516

Also, speed acceleration limiting is called twice during workflow:
inside `calc_throttle`
https://github.com/ArduPilot/ardupilot/blob/520e33261a1a89b01489e0a856162944f25457a2/APMrover2/mode.cpp#L227
and inside `get_throttle_out_speed`
https://github.com/ArduPilot/ardupilot/blob/520e33261a1a89b01489e0a856162944f25457a2/libraries/APM_Control/AR_AttitudeControl.cpp#L347
Is it really needed?

**Comment by rmackay9** [comment]
This is now fixed in master and will go out in a Rover-3.4 point release (like 3.4.1 perhaps)
