### ISSUE TITLE
Log_Write_RFND is called without checking if any data has actually been received neither does it check the same

### ISSUE THREAD

**Issue by Galaxy88** [ArduPilot/ardupilot#8605]
#### Issue details
Unless this is intentional, Log_Write_RFND is called in sensors.cpp of ArduCopter without checking if any data has actually been received, the function itself does not check this either but logs whatever value is returned by distance_cm(). 

This has the effect of the log files appearing to show the rangefinder outputting constant distance values which makes debugging issues that much more difficult. Literally unplugging the rangefinder will produce steady horizontal lines instead of indicating communication error/failure. 

#### Version
3.6.0.rc2

#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
Pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by peterbarker** [comment]
We log the status in the rangefinder message.

We could potentially log NaN, but logging the actual return value from `distance_cm` is more appropriate.
