### ISSUE TITLE
Feature Request: PPM rxrssi

### ISSUE THREAD

**Issue by wunderlins** [ArduPilot/ardupilot#861]
Hi All

I just got a immersionRC LRS TX/RX combo (433mHz). To me, it makes a lot of sense to feed the RSSI data the RX makes available into APM for better failsafe handling.

The RX is configurable, One output channel can be set to output RSSI or link quality as PPM signal. Or it can be configured to be included in the PPMsum signal.

Somebody has already written a patch for APM:Plane 2.74b:
http://www.diydrones.com/forum/topics/editing-ardupilot-code-for-pwm-rssi-input

Would it be possible to have this feature included in the mainline APM code? It is especially useful for APM:Plane I guess.

I think it would be useful to have 3 configurable values:
- input channel - on which channel the RSSI signal is received
- min PWM
- max PWM

for now, I am using a low pass filter connected on an R/C output to an analog pin, this seems to be a bit ugly :-1: 

Thanks for considering this feature request.

Best
-S

**Comment by StewLG** [comment]
This has finally been accomplished here:

https://github.com/diydrones/ardupilot/pull/2770
