### ISSUE TITLE
Pixhawk 2.1, no servo output

### ISSUE THREAD

**Issue by HUNTERUAV** [ArduPilot/ardupilot#8614]
#### Issue details
Servos not working on Pixhawk 2.1 (cube),  Im using Flysky Transmitter and IA6B receiver, when I tried to calibrate I found none of the servos were working even after using the arming switch. But I used the same setup with APM flight controller everything seems fine. Can someone help me on this?

#### Version
Arduplane v3.8.5

#### Platform
Plane
#### Airframe type
Fixed wing (conventional model) MTD 1800

#### Hardware type
Pixhawk Cube 2.1

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by magicrub** [comment]
They work. You have a configuration problem somewhere. Please post help questions on discuss.ardupilot.org
