### ISSUE TITLE
POWR. logs off by x100

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#8617]
#### Issue details
Power.VCC is 0.05v

V.Servo is now logged as .05 v instead of 5.0 v.
(my logs have the servo rail at 8.4v, but it logs as 0.084v)

#### Version
Plane 3.8.5 beta 1 chibios

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
N/A

#### Hardware type
Cube autopilot, Castle power supply

#### Logs
https://www.dropbox.com/s/nreknqh244o06q9/00000066.BIN?dl=0

**Comment by WickedShell** [comment]
@Naterater this is an issue with whatever tool you used to look at the log.

![figure_1-35](https://user-images.githubusercontent.com/567688/41205134-770e395c-6ca2-11e8-927c-03ef18077709.png)

**Comment by Naterater** [comment]
@WickedShell,

I realized that I provided a link to the wrong file. Could you double-check this log? Go ahead and close again if it's good.

https://www.dropbox.com/s/ikuqniqgqodr109/00000008.BIN?dl=0

**Comment by WickedShell** [comment]
You're actually on a newer log tool then I am. @peterbarker got the units wrong on that one by accident and applied a 1e-2 scaler that your log tool was aware of... #8638 resolves it.

**Comment by peterbarker** [comment]
@Naterater Which tool are you using?

**Comment by Naterater** [comment]
I am using mission planner's dataflash log viewer. Did you guys check GPS speed as well?
