### ISSUE TITLE
Rover: ignores DO_CHANGE_SPEED command if before first nav command

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#8619]
To recreate the issue do this in SITL:

- set WP_SPEED to 5 (m/s)
- create a mission with at least two commands:
  - first command is DO_CHANGE_SPEED with 2nd column set to 2 (m/s)
  - second command is a waypoint some distance away
- execute the mission, the vehicle will drive at 5m/s

As a side note, it appears if the vehicle completes the mission at which point it switches to HOLD mode.  If the vehicle is put back into AUTO it will drive the mission at the specified speed.

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/12772
