### ISSUE TITLE
Plane on APM2 won't switch flight mode; Copter works fine

### ISSUE THREAD

**Issue by jackcarrozzo** [ArduPilot/ardupilot#8626]
Apologies if this is the wrong venue for this q!

With any ArduCopter firmware I've tried on my APM2.6, flight mode changes with input to channel 5, confirmed by the green bar changing the highlighted mode in APM Planner 2.

I have tried the _stable, _latest, and _beta versions of the Plane firmware, and cannot for the life of me get modes to change. No other apparent issues. What am I missing?

**Comment by WickedShell** [comment]
Hi @jackcarrozzo, support questions should go to [discuss](https://discuss.ardupilot.org).
