### ISSUE TITLE
Resource leak in srxl.cpp

### ISSUE THREAD

**Issue by KimHyungSub** [ArduPilot/ardupilot#8640]
#### Issue details
A FILE pointer variable (*f) is declared at line 460 of ardupilot-Copter-3.6/libraries/AP_HAL/utility/srxl.cpp.
But, the file stream is not closed.
Adding the following a statement at line 513 resolved the issue for me:
fclose(f);

#### Version
ardupilot-Copter-3.6

#### Platform
[V] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by OXINARF** [comment]
Fixed via #8691
