### ISSUE TITLE
missing '{' in libraries/AP_HAL_F4Light/Semaphores.cpp

### ISSUE THREAD

**Issue by KimHyungSub** [ArduPilot/ardupilot#8645]
#### Issue details
At line 82 in ardupilot-Copter-3.6/libraries/AP_HAL_F4Light/Semaphores.cpp, there is a missing *'{'*.
*save_log(enum Sem_OP op, bool result)* function is opened by using *'{'*.
But, the function is never close using *'}'*.
---------- Original source code ----------
```
#ifdef SEM_DEBUG
void Semaphore::save_log(enum Sem_OP op, bool result){
    Sem_Log *lp = sem_log[sem_log_ptr++];
    if(sem_log_ptr >= SEM_LOG_SIZE) sem_log_ptr=0;
    
    lp.time=Scheduler::_micros();
    lp.sem  = this;
    lp.task = Scheduler::get_current_task_isr();
    lp.op = op;
    lp.result=result;
    
#endif
```
#### Version
ardupilot-Copter-3.6

#### Platform
[V] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment]
Closing as F4Light isn't a valid target anymore.
