### ISSUE TITLE
Uninitialized variable in libraries/AP_IOMCU/fw_uploader.cpp

### ISSUE THREAD

**Issue by KimHyungSub** [ArduPilot/ardupilot#8646]
#### Issue details
At line 371 of ardupilot-Copter-3.6/libraries/AP_IOMCU/fw_uploader.cpp, the code uses an uninitialized variable (*count*).
---------- Original source code ----------
```
bool AP_IOMCU::verify_rev2(uint32_t fw_size)
{
    ssize_t count;
    ...
    sent += count;
}
```

#### Version
ardupilot-Copter-3.6

#### Platform
[V] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment]
Not a problem in master. @rmackay9 probably worth backporting to the copter release.
