### ISSUE TITLE
Leddar One is not working with Intel Aero RTF

### ISSUE THREAD

**Issue by trgiman** [ArduPilot/ardupilot#8649]
#### Issue details
@lucasdemarchi I was wondering if you have ideas in regards of the issue below. I am not able to connect Leddar One to serial port on Telem of Intel Aero RTF. Serial port on Telem works correctly. I was trying to listen for Mavlink messages and switching it off and on or setting it work with Lidar param (value 9) according Ardupilot guidehttp://ardupilot.org/copter/docs/common-leddar-one-lidar.html . Is LeddarOne driver starting automatically on ArduPilot FC? Suggestions appreciated. Sonarrange and Sonarvoltage in MissionPlanner both show 0. Sensor itself works correctly when connected to notebook. Thank you.

#### Version
3.5.5

#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Intel Aero RTF

#### Hardware type

AscTec

**Comment by IamPete1** [comment]
Sorry we never got to this, please re-open if this is still a issue on 4.1.
