### ISSUE TITLE
Rover: Mode triggered pins 

### ISSUE THREAD

**Issue by NickNunno** [ArduPilot/ardupilot#8658]
Allow analog/pwm control of channel state based on mode. 

Auto= On, Other mode= Off

This would be super helpful for safety type features we may not want to script into each and every mission. 

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ X] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
This can be done by scripting, I think its too nuanced a feature to try and configure with parameters. The script can do the thing you actually want too, rather than having some 2nd piece of hardware looking at those pins.
