### ISSUE TITLE
Copter: sport mode not limited by angle max

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#8661]
In SITL (using USB joystick input) , Acro and Sport levels does autolevel as if they were "Stabilize".
Sport also ignores ANGLE_MAX , and goes way over it's setting.

**Comment by geofrancis** [comment]
have you disabled acro trainer?

**Comment by AndKe** [comment]
@geofrancis Of course, you are right, ACRO , were just limited by ACRO_TRAINER.

So, the only actual issue is why Sport is not limited by ANGLE_MAX

**Comment by IamPete1** [comment]
You blow right past angle max and fly upside down if your `ARCO_RP_P` is big enough.

**Comment by rmackay9** [comment]
I don't think Sport mode should be limited by ANGLE_MAX actually.  It is essentially Acro mode with altitude control.  I would actually like to remove this mode because I think it is not very useful.. at least not many people seem to use it.
