### ISSUE TITLE
FMUV2 chirps normal on usb boot... but without SD card

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#8668]
#### Issue details
My pixhawk 2.4.8 boots with the normal chirps even though it has no SD card. I remember that without the SD card, the boot chirps should be different

#### Version
Plane chibios 3.9 beta 1

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
benchtop test

#### Hardware type
pixhawk 2.4.8

**Comment by proficnc** [comment]
Try with USB plugged in

**Comment by Naterater** [comment]
The chirps are not the same as NuttX. The chibios tone is similar, but it doesn't change when there is no SD card inserted.

**Comment by WickedShell** [comment]
You duplicated your own issue ( #9215 ). Closing this one as the other has more discussion.
