### ISSUE TITLE
QuadPlane: Q_WP_RADIUS has no effect on quadplanes

### ISSUE THREAD

**Issue by Abismo** [ArduPilot/ardupilot#8677]
#### Issue details
When flying Auto missions with a quadplane on VTOL mode, it doesn't use Q_WP_RADIUS to approach waypoints, but instead uses WP_RADIUS as if it was on plane mode.

#### Version
3.8.5
3.9.0

#### Platform
[ ] All
[ ] AntennaTracker
[ ] Copter
[*] Plane
[ ] Rover
[ ] Submarine

#### Airframe type
Quadplane

**Comment by disgruntled-patzer** [comment]
Am also experiencing issues with this, appreciate if the developers could look into it!

For more info see my post on the following forum thread: https://discuss.ardupilot.org/t/what-is-q-wp-radius-supposed-to-do/29984/4
