### ISSUE TITLE
Gimbal tilt control doesn't work when using PPM input from RX

### ISSUE THREAD

**Issue by tensafefrogs** [ArduPilot/ardupilot#868]
I was just trying to set up gimbal tilt control via channel 6 on my TX but couldn't get it to work. I suspect that the issue was because I'm using PPM input from my RX to the APM (2.6).

APM versions: 3.1 and 3.1.2 (I tried upgrading just in case it was a recently fixed issue)

My setup is as follows:
- Using PPM from the RX (openLRSng) to APM via CH5, with PPM jumper set on APM
- Checking radio calibration does show that CH6 (and 7 and 8) all work when moving knobs or whatever on the TX
- Connecting the A10 and A11 outputs to a brushless gimbal controller (in this case a HobbyKing Martinez/Brugi clone) should allow gimbal tilt control via the PWM output from A10/A11. I just wanted tilt control so used A11 as output and selected "RC6" as the input on the Gimbal page of APM. When changing the min/max values on the gimbal screen I would see the gimbal move, but moving the CH6 knob on my TX would not move the gimbal.

As a workaround (and so I know the gimbal does work), I've connected my RX directly to the gimbal tilt control input, bypassing APM altogether. But if there is better ROI support in the future (or just for cleanliness) it would be nice to connect it all up through APM.

Let me know if you have any q's or need me to try some other config. I'll see if I can verify that it all works when not using PPM if I have some time this week to tinker with it.

**Comment by jgeragi** [comment]
I have exact same issue as tensafefrogs. Same setup as well. I notice that stabalize does not seem to be working on the roll axis as well? If I change the servo limits the servos move. I used to be able to pick up while disarmed and see servos moving to stabilize camera but this is not happening. I too am unable to control via CH 6 but I suspect it will work if I connect as tensafefrogs did, but what about stabilize??
