### ISSUE TITLE
Support UAVCAN ArmingStatus message.

### ISSUE THREAD

**Issue by edwinhayes** [ArduPilot/ardupilot#8704]
### Feature request

The UAVCAN ArmingStatus message seems like it isn't broadcast by the flight controller: per #6081, @EShamaev indicated it wasn't required since no hardware supported it.

Could this please be added?  Even a 1Hz publishing rate would be fine.

**Platform**
[?] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by WickedShell** [comment]
This was done in #16423, I didn't realize there was an issue for it.
