### ISSUE TITLE
Copter: AUTO check that waypoints are all within a reasonable distance

### ISSUE THREAD

**Issue by R-Lefebvre** [ArduPilot/ardupilot#871]
Currently, it is possible that a user could load a mission into Arducopter one day, then move locations, possibly 100's of miles away.  Then accidentally invoke the old mission and have the copter head off to the old flying location.  It would be great if there was a parameter which could be used to prevent this, whereby the user can set the maximum waypoint distance beyond which the copter will not fly in auto.  Maybe default it to 1km or something.  This would also prevent accidents when setting way points (ie: waypoint target at 0,0)

**Comment by lthall** [comment]
[Duplicate](https://github.com/ArduPilot/ardupilot/issues/1348)

**Comment by jmachuca77** [comment]
there are at least 3 issues that reference this behavior, I will close this on as the others have more recent activity and are more active. #1348, #4701
