### ISSUE TITLE
No SERVO_BLH_ parameters?

### ISSUE THREAD

**Issue by manotroll** [ArduPilot/ardupilot#8720]
How do I download a revision that has this parameter for quadcopterios?
would it be just to configure update ESC

**Comment by amilcarlucas** [comment]
You will need to compile a ChibiOS version of master in order to do that.
Instructions on how to do that are on the wiki.
http://ardupilot.org/copter/docs/common-dshot.html?highlight=chibios
https://discuss.ardupilot.org/t/chibios-port-of-ardupilot/20491
