### ISSUE TITLE
AutoTune usability

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#8734]
Just got done doing an AutoTune with ArduCopter 3.6. I think a few simple changes would make it better. Currently the AutoTune success and params saved STATUS_TEXT messages are sent with normal priority. It would be way better if they were sent with high prio so QGC would pop up messages for them and also read them out via speech. Would make it easier to know when it was done and you did the right thing to get the params saved.

**Comment by rmackay9** [comment]
this fix will go out with -rc3 in a few days.  I hope NOTICE is high enough.. if not we should change it again.

**Comment by DonLakeFlyer** [comment]
NOTICE works for QGC, thanks.
