### ISSUE TITLE
RC Cal Safety/Usability to prevent arming

### ISSUE THREAD

**Issue by DonLakeFlyer** [ArduPilot/ardupilot#8735]
Would be awesome if ArduPilot supported MAV_CMD_PREFLIGHT_CALIBRATION.param4=1/0 to start stop radio calibration. Mavlink spec is not super specific by in QGC this causes the motors to not arm when you are doing RC cal. This way you don't have to take props off during RC cal.

**Comment by IamPete1** [comment]
@DonLakeFlyer AP should now support this, is there any change required to QGC to enable sending the message? I could not seem to get it to send.

**Comment by DonLakeFlyer** [comment]
I'll take a look. It's a bit tricky since it's firmware version specific. But good safety thing so I'l try to get it supported in this next stable which I'm working on right now.

**Comment by DonLakeFlyer** [comment]
I looked, yes this does require a QGC change. It's currently not sent for ArduPilot only PX4.

**Comment by peterbarker** [comment]
On Mon, 1 Nov 2021, Don Gagne wrote:

> I looked, yes this does require a QGC change. It's currently not sent for ArduPilot only PX4.

Hopefully this is just removing special-case code :-)

**Comment by DonLakeFlyer** [comment]
> Hopefully this is just removing special-case code :-)

Not quite. What's going to be the version number for firmware for which this command is supported? I need to special case to that version since it's the only way to know if this is supported or not.

**Comment by IamPete1** [comment]
Should be OK to go with 4.2 and newer. Unfortunately we were using the param incorrectly in the past, so sending it on older versions will do the wrong thing.

**Comment by DonLakeFlyer** [comment]
> Unfortunately we were using the param incorrectly in the past, so sending it on older versions will do the wrong thing.

Oh, crap. That means my pull will be wrong for versions < 4.2

**Comment by DonLakeFlyer** [comment]
@IamPete1 Isn't 4.2 the current stable? If so it seems like this change just went in a few weeks ago which would seem to mean it's not in stable until 4.3?

**Comment by IamPete1** [comment]
@DonLakeFlyer 4.1.x is current stable. 4.2.dev is master.

**Comment by DonLakeFlyer** [comment]
Crap sorry. I was off by one! Anyway I'll fix up QGC to only turn this one when running 4.2+. Right now the code does it for all versions which is bad since older firmwares do something odd with it.

**Comment by IamPete1** [comment]
@DonLakeFlyer Thank you
