### ISSUE TITLE
Uninitialized pointer variable in modules/PX4NuttX/misc/pascal/plink/plsym.c

### ISSUE THREAD

**Issue by KimHyungSub** [ArduPilot/ardupilot#8767]
### Bug report

**Issue details**
At line 341 in ardupilot-master/modules/PX4NuttX/misc/pascal/plink/plsym.c, *newsym* is an uninitialized pointer variable.
I think that it is better to initialize the *newsym*.
---------- Original source code ----------

```
  symContainer_t *newsym;    // here
   ...
  if (curr == NULL)
    {
      /* The symbol goes at the end of the list */

      newsym       = makeSymContainer(sym);
      newsym->next = NULL;
      newsym->prev = prev;
      symTail      = newsym;

      if (prev)
        prev->next = newsym;
      else
        symHead    = newsym;
    }
```

**Version**
ardupilot-master

**Platform**
[V] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

**Hardware type**

**Logs**

**Comment by WickedShell** [comment]
PX4 builds are no longer being maintained on ArduPilot.
