### ISSUE TITLE
Analog input pin logging and MAVLink transmission

### ISSUE THREAD

**Issue by messmc9** [ArduPilot/ardupilot#877]
It would be nice to have additional analog inputs available on APM which can be enable for arbitrary sensors. i.e. I would like to run by FPV battery through a voltage divider and display its voltage in the HUD in addition to my main flight battery and on my gas plane I want to display the receiver battery voltage as well as a fuel level sensor.

I would like to see parameters for each analog pin that allow enable/disable and input range (0-5V, 0-3.3V, etc).

**Comment by hiro2233** [comment]
@hiro2233

**Comment by jaxxzer** [comment]
I'm interested in taking this up.
Here's what I propose:

A new mavlink message ANALOG_VALUE with two fields:
uint8_t id
float voltage

**Comment by jaxxzer** [comment]
Need to figure out a way of how to enable/disable reading and reporting of these values.

Maybe something like a parameter-per-instance so on the pixhawk it would look like:
ANALOG_1_ENABLE (3v3 #1)
ANALOG_2_ENABLE (3v3 #2)
ANALOG_3_ENABLE (6v6)

**Comment by jaxxzer** [comment]
I can start on this as soon as there is some opinion on the direction I should take.

**Comment by jaxxzer** [comment]
If we simply report an adc voltage value, then users can easily play with or obtain useful data for any sensor that has an analog output. Developers can use the same functionality to do quickly evaluate new sensors to determine if their performance warrants dedicated support and explicit integration.

**Comment by jaxxzer** [comment]
Any analog inputs @ArduPilot/ardupilot-maintainers?

**Comment by OXINARF** [comment]
@jaxxzer I would say to label it as DevCallTopic, more chances of input there.

**Comment by jaxxzer** [comment]
@OXINARF ok, I was trying to have a PR together by that time.

**Comment by jaxxzer** [comment]
Use existing AP_ADC message

[This](https://github.com/SkyRocketToys/ardupilot/blob/skyviper2018/libraries/AP_HAL_ChibiOS/AnalogIn.cpp#L288) bit of code is of interest.

Will add to sub data stream by default for now.

**Comment by geofrancis** [comment]
how far along is this? I was looking at using one of the ADC pins to log and monitor a sensor on a plane, currently im using it via a frsky receivers ADC port but i would prefer it through mission planner.

**Comment by jaxxzer** [comment]
Stalled out till we have a new ADC interface in the HAL. That could take quite some time.

**Comment by geofrancis** [comment]
looks like im going to have to bodge batt2 input to get the readings,

**Comment by alessandrogenoni** [comment]
Hello! Any update on this topic? I would love to see it fully implemented!

**Comment by rmackay9** [comment]
I suspect the best way to handle this is using a lua script.  [We have a simple example here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/analog_input_and_GPIO.lua).

**Comment by alessandrogenoni** [comment]
And then should I add a MavLink message to map this reading?

**Comment by rmackay9** [comment]
@alessandrogenoni, I'm not sure of what would be the best way to send this info... I would re-use some other message that AP doesn't normally use or maybe there is a way to send a custom field.  I'm sure I saw a message that allowed sending a string and a value but I can't immediately find it again.

**Comment by alessandrogenoni** [comment]
@rmackay9 thank you very much for the info.
Just to understand, is this request currently being worked on? (still marked as open).
Another option to achieve a similar results would be to allow the implementation of new MavLink messages through LUA scripts (https://discuss.ardupilot.org/t/lua-script-send-mavlink-command-to-fc/64965).
Is any of this feasible? I'm in the need for an analog sensor logging and mavlink transmission for an external sensor and I'm currently not skilled enough to go and change the source code without risking major issues and general malfunctioning of my vehicle, so an integrated way as suggested by @jaxxzer or anything similar would be excellent.
Thank you all

**Comment by rmackay9** [comment]
@alessandrogenoni,

I don't think that anyone is working on this at the moment and I don't think there is actually an easy way to know if any particular item is being actively worked on.

Lua scripts can't create new mavlink messages I'm afraid because both sides need to know the format of the message in advance.  MAVlink is not what we'd call a "self describing protocol".

I wish I had better news but you know.. there are just so many enhancement requests..

**Comment by IamPete1** [comment]
We now have analog inputs in scripting and the ability to send named value floats, these can be disaplayed with the correct name by both Mission planner and MAVProxy. 

Analog input example here:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/analog_input_and_GPIO.lua

Sensor reporting back using named floats here:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/SN-GCJA5-particle-sensor.lua
