### ISSUE TITLE
Rover: improved error message when log download fails because vehicle is armed

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#8914]
With Rover's it's quite common for users to try and download a log while the vehicle is armed.  The failure (viewed in MP) does not make it very clear that this is the issue.  I'm unsure if it's a mission planner issue or an ArduPilot issue but I'm adding it here in any case.

**Comment by hdtechk** [comment]
There is a similar issue 1880 for mission planner

**Comment by peterbarker** [comment]
Should we just issue a statustext?

**Comment by tajisoft** [comment]
I think ArduPilot and Mission Planner are refusing to download logs in Armed state. What is the reason for denying downloads in Armed state? Is it dangerous?
https://github.com/ArduPilot/ardupilot/blob/master/libraries/DataFlash/DataFlash_MAVLinkLogTransfer.cpp#L34
https://github.com/ArduPilot/MissionPlanner/blob/5b8c2a415d2d2fb5490b4be345842061df6ef179/ChangeLog.txt#L121

**Comment by peterbarker** [comment]
On Sat, 27 Oct 2018, tajisoft wrote:

> I think ArduPilot and Mission Planner are refusing to download logs in Armed
> state. What is the reason for denying downloads in Armed state? Is it
> dangerous?

Only for anything underneath the vehicle :-)

Generally we avoid doing anything more complicated that writing to a file 
in dataflash while armed.  Doing so can cause signficiant scheduling 
issues - and if something goes wrong while working with the filesystem 
when downloading files the main loop may stop running - generally a bad 
thing.
