### ISSUE TITLE
Support for Spektrum DX9 (and more Channels)

### ISSUE THREAD

**Issue by zumbrunnen** [ArduPilot/ardupilot#892]
Hi there

I have a DX9 and connected a paired satellite receiver directly to Pixhawk (Arducopter 3.1.2). Unfortunately, this is not supported (Pixhawk sees not RC input at all). As a solution, I bought a DX6i and with it the setup works fine :disappointed: 

It's mentioned in forums throughout the web that Spektrum greater than 8 channels (>= DX9) are not supported, but it seems to be on a todo list (according to @Craig3DRobotics  from 3D Robotics, see: http://ardupilot.com/forum/viewtopic.php?f=21&t=5828&start=10).

Is this a hard thing to do? This is implemented on the "original" Pixhawk firmware. E.g. I found this: https://github.com/PX4/Firmware/blob/master/src/modules/px4iofirmware/dsm.c#L159

Unfortunately, I have no knowledge about Arduino coding & building, so I think I cannot file a PR. But if someone could do the code and send me the binary, I could test it on my DX9.

**Comment by marcmerlin** [comment]
I can confirm that with AP 3.4, I can receive 16 channels when sending SUMD via the satellite port from an openlrsng module.
