### ISSUE TITLE
Request to support FrSky F.PORT protocol

### ISSUE THREAD

**Issue by flybabo** [ArduPilot/ardupilot#8922]
### Feature request
FrSky introduced the F.PORT protocol which combines the SBUS and S.PORT telemetry into a single stream.  It also includes the RSSI info.
By using the F.PORT protocol, RX and FC can be connected through a single wire to a TX pin of UART when it operates as a half-duplex mode.

https://github.com/betaflight/betaflight/wiki/The-FrSky-FPort-Protocol
https://www.propwashed.com/frsky-fport/

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Comment by Shackmeister** [comment]
+1
This would be a great addition!

**Comment by wolfpackt99** [comment]
Agree. Full telem back to radio would be aewsome.

**Comment by mclarenman01** [comment]
One less connection to make is always welcome!

**Comment by davidngrc** [comment]
+1 one less wire, telemetry without extra hardware, nice.
anyone working on this?

**Comment by x4FF3** [comment]
+1 already using it with inav builds. would appreciate it for my arduplane builds, too :)

**Comment by yssaril** [comment]
+1 one less wires and and a free Uart if this can be added to the sbus/ppm-sum port

link to the FrSky anouncement [https://www.frsky-rc.com/frsky-betaflight-introduction-of-f-port-protocol/](https://www.frsky-rc.com/frsky-betaflight-introduction-of-f-port-protocol/)

**Comment by utkinpol** [comment]
ditto, old request but if it needs more votes to get done - my vote is here as well. to have f.port would be convenient.

**Comment by razorbac91** [comment]
I'm waiting it :)

**Comment by maroquio** [comment]
I think this is one of the most important things to be supported to avoid telemetry issues. I hope you do it soon!

**Comment by bugobe** [comment]
+1 for wanting this feature added. With the Frsky 900mhz radios becoming more popular, I think arduplane /f-port would be very popular for medium range aircraft.

**Comment by ninja-zx11** [comment]
+1 for the need of this feature.Please add if possible!!

**Comment by GregCovey** [comment]
F.Port would be a nice feature on some of these supported F4 boards with limited UARTs.

**Comment by ignaciobfp** [comment]
This would be a nice addition, for simplicity and to bring telemetry to lots of users with less time/knowledge

**Comment by sincoder** [comment]
+1 , with fport , telemetry become very simple !

**Comment by PHMT** [comment]
Would be a helpful feature.  One less UART used (and available for something else) is very nice.

**Comment by gregbiv** [comment]
+1 on this! I wish we can have it one day

**Comment by sincoder** [comment]
+1 anyone could port FPORT from betaflight to Ardupilot ?

**Comment by zingaros** [comment]
+1

**Comment by CpeDratDoPC** [comment]
I think this is one of the most important things to be supported to avoid telemetry issues.

**Comment by Basti77** [comment]
Oh yes, that's my wish too. so I can save the smart port adapter cable and have one UART free. one less source of error.

**Comment by maroquio** [comment]
+1 vote!

**Comment by jace26** [comment]
+1 also, get rfd900x to support passthrough of f.port, and frsky to support f.port redundancy (does this exist yet?)

**Comment by MFlghts** [comment]
+1 waiting hard for this

**Comment by athertop** [comment]
Yes, this would be a great feature to have, saving an extra uart.

**Comment by MoriXTV** [comment]
+1 F.Port would be amazing as we would be able to switch between iNav and ArduPlane just by flashing a new Firmware

**Comment by Dronotique** [comment]
+1, should be a great feature

**Comment by tridge** [comment]
sorry for the delay on this, I now have a F.Port RX and I plan to do an implementation soon

**Comment by MFlghts** [comment]
Great news! Thank you very much!

**Comment by mclarenman01** [comment]
> sorry for the delay on this, I now have a F.Port RX and I plan to do an implementation soon

Fantastic news! Thank you @tridge

**Comment by variostudio** [comment]
It would be a nice feature

**Comment by tridge** [comment]
PR to add FPort support here:
https://github.com/ArduPilot/ardupilot/pull/12945

**Comment by tridge** [comment]
FPort support is now in master.
Discussion and setup guide for testers here:
https://discuss.ardupilot.org/t/frsky-fport-support-testers-wanted/50669
