### ISSUE TITLE
Arming error msg misleading re GPS "speed"

### ISSUE THREAD

**Issue by Kelly-Foster** [ArduPilot/ardupilot#8930]
With all pre-arm checks enabled, ArduPlane master latest (as of last night) won't arm due to HDOP being above 1.5.  Problem is the misleading message:  "PreArm: GPS speed error 1.9 (needs < 1.5)" .  Speed should be changed to HDOP.

**System info:**
MatekF405-Win 001F003B 35485011 2036365
ChibiOS: 6686ee8a
ArduPlane V3.10.0-dev (0f758660)

Kelly

**Comment by hdtechk** [comment]
I believe gps speed says you have bad velocity variance on your gps nothing to do with hdop.

**Comment by WickedShell** [comment]
It is referring to the GPS's internal estimate of velocity accuracy. The message is correct.
