### ISSUE TITLE
Mission Planner: no option for onboard mag cal with wifi connection

### ISSUE THREAD

**Issue by kd0aij** [ArduPilot/ardupilot#8951]
### Bug report

only live cal available with wifi, only onboard when connected via USB

**Version**
master
![mp_wifi](https://user-images.githubusercontent.com/2300221/42914229-76836ff2-8ab6-11e8-8885-8ddf842ab1d4.PNG)
![mp_usb_onboard_cal](https://user-images.githubusercontent.com/2300221/42914258-a6ba1284-8ab6-11e8-8700-e1a7f1c4b7c9.PNG)

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quad X

**Hardware type**
Pixracer/ESP8266 with external I2C compass/GPS

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
Looks like a valid issue but it should probably be raised in the [Mission Planner's issues list](https://github.com/ArduPilot/MissionPlanner/issues) so I'll close this one if that's OK.

**Comment by kd0aij** [comment]
result from that :) "how uptodate is your esp8266? this is likerly the esp8266 nothing to do with missionplanner"

**Comment by auturgy** [comment]
Onboard Mag cal uses a mavlink2 message.
Older mavesp8266 is mavlink1 only.
That might explain the issue: updating the esp8266 firmware may well solve this.

Regards,

James

**Comment by WickedShell** [comment]
> Onboard Mag cal uses a mavlink2 message.

No it doesn't, there are recent MAVLink 2 extensions to it, but the message is MAVLink 1.

**Comment by kd0aij** [comment]
I guess this explains why I can start mag cal using QGC, but get no feedback (progress bar never moves).

**Comment by WickedShell** [comment]
@kd0aij I'm sorry, maybe I missed something but I don't see an explanation why QGC would have a problem with mag cal.

**Comment by rmackay9** [comment]
I'm guess but perhaps the old mavesp firmware didn't forward messages that it didn't recognise.  It's a guess but I suspect that using the new firmware described on the [ArduPilot ESP8266 wiki page](http://ardupilot.org/plane/docs/common-esp8266-telemetry.html) will fix the problem... and no amount of extra work in the GCSs will solve the problem.

**Comment by kd0aij** [comment]
Is it possible that onboard cal feedback requires mavlink 2? That would explain the problem with QGC.

**Comment by WickedShell** [comment]
@kd0aij nope, it is not possible, feedback is a MAVLink 1 message. https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/ardupilotmega.xml#L1363 The recent extensions are on the report message only (and are only needed for the orientation estimation)

**Comment by kd0aij** [comment]
Then I guess this is evidence of incompatibility with the version of firmware on my old ESP8266. Should we just say it's not supported by ArduPilot?
