### ISSUE TITLE
Copter: allow user to control altitude with transmitter in Auto

### ISSUE THREAD

**Issue by a2sandres** [ArduPilot/ardupilot#8960]
**Feature request**

I would like to implement manual altitude control while in auto mode. This probably can be implemented as a part of AUTO mode where you will have a param flag saying AUTO_MAN_ALTCTRL
 **I am willing to pay for some help, please contact me.**

**Platform**
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/11251
