### ISSUE TITLE
Limit Descend Speed in Manual mode (loiter, posHold)

### ISSUE THREAD

**Issue by mshajeehm** [ArduPilot/ardupilot#8962]
Is there any possibility of addition of a new parameter named "Loiter_Max_Descend_Speed" in  **Copter**. This is to limit descend speed thus enabling smooth landing even if you pull the throttle stick to zero (accidentally or by choice) during mission. This will surely help in reduced number of accidents due to high landing speeds otherwise. 
The solution might be the incorporation of same concept as "Land_speed" used in RTL mode which limits the max descend speed.

`Plateform: Copter`

**Comment by jmachuca77** [comment]
Loiter and posh old already have this. Please read http://ardupilot.org/copter/docs/altholdmode.html#altholdmode-controls

**Comment by mshajeehm** [comment]
These adjustments are for climb and descend both. What if I want to climb at a faster rate with throttle to 100% however on throttle down to zero, descend slowly?

**Comment by jmachuca77** [comment]
Pretty sure WPNAV speeds apply there

**Comment by rmackay9** [comment]
It's included in Copter-3.6.  the params are renamed to PILOT_SPEED_UP and PILOT_SPEED_DN.
