### ISSUE TITLE
Flight Mode: HORIZON (Feature request)

### ISSUE THREAD

**Issue by netinetwalker** [ArduPilot/ardupilot#897]
It comes from multiwii ... 
HORIZON - A mixture between ACRO and ANGLE modes. Combining the stabilising effect with calm rc sticks and acrobatics with busy rc sticks 
STABLE MODE mode when PITCH/ROLL sticks are centered. ACRO MODE mode when full PITCH or ROLL sticks are applied, allowing flips.

on multiwii 0%-80% stabilized ... 80-100% acro
on tau labs its a smouth transition

return from 80-100% to 0%-80%
on multiwii it feels like if i return between 0-80 it takes 1 secound to go back to stabilized
on tau labs it should be a smouth transition...

http://www.multiwii.com/wiki/index.php?title=Flightmodes <- Horizen Mode
https://github.com/TauLabs/TauLabs/wiki/Flightmode-Settings <- Horizen Mode
http://diydrones.com/profiles/blogs/tau-labs-has-multiwii-style-horizon-mode

It would be nice to have this mixed flight mode on apm ...

**Comment by netinetwalker** [comment]
anyone looking at this?

**Comment by Naterater** [comment]
I think this is similar to the ACRO trainer function, isn't it? Unless someone can explain the difference, I think this should be closed.

**Comment by kd0aij** [comment]
I flew horizon mode on betaflight several years ago and it was very similar to ArduCopter's acro trainer mode 1. I don't see a significant advantage to adding more options here.

**Comment by Naterater** [comment]
So it sounds like this is already is a function of ACRO mode with trainer. If it’s alright, I’ll close this request then.

**Comment by lthall** [comment]
Modes like this are a gimmick mode and I personally don't like them. However this is also something at could be done well by a potential new developer and would not impose on the code in general. I would therefore suggest we leave it here.
