### ISSUE TITLE
Plane:  vehicle loses control in AUTO VTOL loiter commands

### ISSUE THREAD

**Issue by expntly** [ArduPilot/ardupilot#8975]
#### Issue details

This is in AUTO.  Here's the mission

<img width="299" alt="screen shot 2018-07-20 at 2 22 07 pm" src="https://user-images.githubusercontent.com/6870452/43021190-55e2d54e-8c28-11e8-980e-7ed836e2ba95.png">

<img width="765" alt="screen shot 2018-07-20 at 2 02 21 pm" src="https://user-images.githubusercontent.com/6870452/43020419-8ed43c4c-8c25-11e8-9b40-a43bc9528f88.png">

In SITL, the moment the vehicle switches to WP5 (LOITER_TO_ALT 10m), it goes from very stable to losing its mind as can be seen here:

<img width="777" alt="screen shot 2018-07-20 at 2 14 19 pm" src="https://user-images.githubusercontent.com/6870452/43020893-3fd452ec-8c27-11e8-919b-c375b1c0e651.png">

I have Q_GUIDED_MODE=1, and Q_ENABLE=2.

Sometimes it works and just climbs back up, but most of the time it acts up as described above.

#### Version
AP385

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quadplane X4 (in SITL)

#### Hardware type
N/A -- SITL

#### Logs

DF log from SITL (5MB) : [00000012.BIN.zip](https://github.com/ArduPilot/ardupilot/files/2215107/00000012.BIN.zip)

**Comment by IamPete1** [comment]
Sorry we never got to this, feel free to re-open if the issue remains on 4.1.
