### ISSUE TITLE
V-tail rudder-only plane ACRO mode no roll control

### ISSUE THREAD

**Issue by padvinder95** [ArduPilot/ardupilot#9008]
See https://discuss.ardupilot.org/t/acro-with-rudder-only-no-roll-yaw-response/31189/2

### Bug report

**Issue details**

With a V-tail plane, rudder-only (so no ailerons), in ACRO mode, there is no control over roll, while it does work in FBWA.
FBWA: stabilize() first calls roll PID and then yaw stabilizer. The latter mixes aileron into rudder (with KFF_RDDRMIX), thereby coupling roll control into the V-tail.
ACRO: stabilize_acro() _doesn't_ call stabilize_yaw but passes through RC input directly, thereby never mixing the roll PID output into the Vtail (Vtail mixes elevator and rudder).

Proposed solution: if rudder_only (or better: if no aileron outputs defined), then in acro also do stabilize_yaw() or at least mix roll PID output into rudder output.

**Version**
The forum posts is about Plane 3.7.3, but I've looked at the code for 3.8.5 and I think the issue still stands.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Fixed-wing V-tail, no ailerons. [edit] Come to think of it, this of course holds for all rudder-only planes, e.g. EasyStar-like.

**Hardware type**
Pixhawk 2.4.8

**Logs**
n/a; please see linked forum post

**Comment by IamPete1** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/17125, Just need to set the new  `FLIGHT_OPTIONS` "5: Enable yaw damper in acro mode" bit.

**Comment by dmrelashvili** [comment]
Quick question: Does ardupilot work as autopilot on the V-tail planes with JUST L and R V tail inputs (no aelerons)?
