### ISSUE TITLE
Bad Baro Health when UAVCAN is Enabled

### ISSUE THREAD

**Issue by rhenetouv** [ArduPilot/ardupilot#9030]
### Bug report

**Issue details**

I encountered bad baro health when enabling UAVCAN, after I changed the `BRD_CAN_ENABLE` parameter either to 1 or 2. I tried to find some solutions to this problem but no luck to find it. Sorry If this issue has been solved before

**Version**
Arducopter 3.5.6

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X

**Hardware type**
Pixhawk

**Comment by lvale** [comment]
Please report your problem at the discuss forum, where it will likely be viewed by a wider audience. Don't forget to add relevant info and logs.
Thanks
