### ISSUE TITLE
Arducopter for Matek F722?

### ISSUE THREAD

**Issue by Seeelefant** [ArduPilot/ardupilot#9043]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REQUEST WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please do a careful search before opening this, there are already a lot of feature requests**_
If there was a previous discussion in the forum, link to it

### Feature request

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Platform**
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._
There is an excellent new FC from Matek http://www.mateksys.com/?portfolio=f722-std. Is there any chance to get Arducopter ported to that?

**Comment by auturgy** [comment]
The matek F722 only has 512k of flash, so a normal, full featured port won’t fit.

Regards,

James

**Comment by rmackay9** [comment]
Mateksys is apparently working on an STM F7 based flight controller with more RAM though..

**Comment by Seeelefant** [comment]
Ok, thank you. Just as my last question: There is the AnyFC F7: https://quadmeup.com/hands-on-anyfc-f7-from-banggood/ which has enough memory. Is that an interesting target?

**Comment by auturgy** [comment]
I have a WIP hwdef for the anyfcf7. Just need to test it.

Regards,

James

**Comment by auturgy** [comment]
The anyfc f7 doesn’t have an onboard barometer or compass though, so be aware of that - it needs external peripherals to function fully.

Regards,

James

**Comment by Seeelefant** [comment]
Yes, unfortunately, I am aware of this.  However the board is highly interesting in terms of price and computational power and connectivity.....
Regards
--Wolfgang

**Comment by Seeelefant** [comment]
Hi James,
can you send me you WIP hwdef?
Regards
--Wolfgang

**Comment by mgrimes1907** [comment]
Did he ever get a version for Anyfc F7 going?

**Comment by auturgy** [comment]
There’s a pr in for that

Regards,

James

**Comment by auturgy** [comment]
With the f722, the mcu needs to be supported before the hwdef is useful.
UAVChallenge is over now, so I’ll look at it again.
Due to flash constraints (512k on the F722), it’s unlikely to be a very useful board, but might be ok for non gps stuff, or with a companion computer.

Regards,

James

**Comment by Seeelefant** [comment]
Hi James,
it is an F745, it has 1MB flash at a rather modest price.
Regards
--Wolfgang

**Comment by Seeelefant** [comment]
...the AnyFC F7 one :-)

**Comment by auturgy** [comment]
Yup, sorry if the thread got confused!
A pr is in with a hwdef.dat for the AnyFC F7. It boots, connects etc, but I had to wait for an external barometer so I can properly test it.
I have that now, and UAV Challenge is over, so I hope to get it merged over the next week or so. Other testers welcome!
https://github.com/ArduPilot/ardupilot/pull/9246

The matek F722 I’m interested in doing, but as above it has some limitations and is a bit more work. 

Regards,

James

**Comment by Seeelefant** [comment]
Yeps, originally the AnyFC F7 had a baro but it was optimized away by our chinese friends :-( , you can add an external baro via I2C or if you have very good soldering skills you will even find the baro pads on the board.

**Comment by auturgy** [comment]
The ms5611, which the anyfc has pads for, is very susceptible to damage whilst soldering. I added an external bmp280 (actually I found a gps with a compass AND a baro, so am using that).

Regards,

James

**Comment by rmackay9** [comment]
@andresiko, I've heard they have one available although I'm not sure if it is available from their website yet.  I'm afraid none of the AP developers have received theirs yet

**Comment by Seeelefant** [comment]
There is another quite recent  F7 flightcontroller which looks interesting http://www.holybro.com/product/59, maybe it´s worth a try.

**Comment by auturgy** [comment]
The Kakute F7 (both versions) are supported. They use an F745, like the AnyFC.

Regards,

James

**Comment by andresiko** [comment]
Is there any F7 with dual camera selection available? not yet, isnt it? (I assume that the dual camera thingy is not yet suported by ardupilot, but also asume that will be a matter of time!)

**Comment by auturgy** [comment]
I’m not aware of any F7 with dual camera inputs that isn’t an F722, so not on the ArduPilot radar just yet.

Regards,

James

**Comment by amznHendes** [comment]
@auturgy Any progress on the F722 with Plane? Dying to try it out if it can fit on flash.

**Comment by wiistriker** [comment]
Interested in Ardupilot on Matek F722 too

**Comment by auturgy** [comment]
I haven’t looked at F722 for a while.
I’ve looked at what needed to happen to fit ArduPilot on the F412 for Skyrocket, and just don’t think people would be interested in ArduPilot without GPS functionality.
Someone else can have a crack of course, but I don’t see it getting to the top of my pile anytime soon

**Comment by cheshira** [comment]
Wow! Matek F722-Wing is so popular now, but is not supported by Ardupilot? I saw this topic about a year ago and I saw that there are limitation with flash size, but that was not a stumbling-block matter.  So a year later I thought this matter is already solved, but no, it is not, unfortunately. Despite the grown popularity of Matek F722!

**Comment by bavariaaa** [comment]
What is the problem? Can't we disable  parts of the firmware to make it fit for 512k of flash in the f722?
