### ISSUE TITLE
Arducopter and Lightware LW20/C version

### ISSUE THREAD

**Issue by rdesgagn** [ArduPilot/ardupilot#9075]
### Bug report

**Issue details**

Hi everyone,

I have bought 3 Lightware LW20/C. With this new version, the user can select Serial or I2C interface. However, from what I can understand, the protocol (serial or i2c) that will be used for the communication between arducopter and the LW20/C relies on the first command received by the LW20/C. I don’t think in the current arducopter implementation that there is any command send to any rangefinder on the i2c bus. Because of that, I get 0.00 readings on the sonar range. 

**Version**
Ardupilot 3.6-rc5

**Platform**
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Hexa Plus 

**Hardware type**
Pixhawk 2.1 and Lightware LW20/C

**Comment by rmackay9** [comment]
this should be resolved in Copter-3.6.x so closing but please tell me if I'm wrong.
