### ISSUE TITLE
Add support for custom frame configurations/motor locations and orientations

### ISSUE THREAD

**Issue by NullVoxPopuli** [ArduPilot/ardupilot#908]
This is my copter: http://i.imgur.com/Ky3US7c.jpg
it uses the Lynxmotion Hunter VTail 400 frame.

It would be cool if there was an option in the frame settings area to just be able to click and drag for motor placements / angles, etc. This would reduce hard coded values for motor mixing (what I've seen people do when they modify source to get their VTails working with the APM)

**Comment by rmackay9** [comment]
Pushing to AC-3.5.  We're simply out of time for AC-3.4.

**Comment by veshnu** [comment]
is this feature gonna be pushed?

**Comment by Naterater** [comment]
This feature is actually becoming more and more relevant from the VTOL and transition systems coming up recently.

**Comment by IamPete1** [comment]
We now support custom frame types via scripting, https://github.com/ArduPilot/ardupilot/pull/15708
