### ISSUE TITLE
Copter: vehicle twitches when do-change-speed command is executed

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#9085]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

### Bug report

**Issue details**
comment line

> copter.wp_nav->set_fast_waypoint(true);

and WPNAV_SPEED set to 500cm/s,  DO_CHANGE_SPEED set to 1m/s， when implement DO_CHANGE_SPEED，vehicle got a shock。

**Version**
3.6.0 rc6
**Platform**
[  ] All
[  ] AntennaTracker
[ * ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
SITL

**Logs**
[2018-08-02 16-28-47.zip](https://github.com/ArduPilot/ardupilot/files/2252768/2018-08-02.16-28-47.zip)

**Comment by liang-tang** [comment]
![46e9e0742f062340949da30b2d1e8c6](https://user-images.githubusercontent.com/16251761/43573581-a3f6f232-9674-11e8-994a-9810fcc54444.png)

**Comment by liang-tang** [comment]
![30ce439f71b8cfbff544fe551fe2b6d](https://user-images.githubusercontent.com/16251761/43573888-5f79b792-9675-11e8-9fda-5d8cff66b708.png)

**Comment by liang-tang** [comment]
1.3.57 version test result
![d2f84c908c4f6e13d54e3f729d5ccc1](https://user-images.githubusercontent.com/16251761/43694349-865d0114-9965-11e8-8920-21146460fd4f.png)
![6f3783e49b444a56b9ec158a80f000e](https://user-images.githubusercontent.com/16251761/43694350-87622b20-9965-11e8-8b11-455555ab7bf9.png)

**Comment by rmackay9** [comment]
@liang-tang, thanks for that evidence.  The vehicle will need to slow-down to the new speed of course, so it makes sense that it will lean back for a bit.  The question is whether that's too rough or not.

**Comment by liang-tang** [comment]
sorry about the graph, it's pitch angel.

**Comment by liang-tang** [comment]
All test in SITL, execute  LOITER_TURNS command.
**Copter 3.5.7**
![495838fd1db824f7e059e07e9eac295](https://user-images.githubusercontent.com/16251761/43694963-7831b186-9968-11e8-929f-46df705cbdf7.png)

**Copter 3.6.0 rc6**
  
![6b41f9e81dd570b78722095ede88d22](https://user-images.githubusercontent.com/16251761/43695004-a098b7fa-9968-11e8-8116-1b2ec2ea39d5.png)

**WP**
![cc445db27535bf5d3bf9a9c456b4b10](https://user-images.githubusercontent.com/16251761/43694794-b321375e-9967-11e8-8b3e-7f74acedcf2d.png)

**Comment by liang-tang** [comment]
@lthall  any idea about this？

**Comment by RickReeser** [comment]
Is this the same issue as #8627?

**Comment by IamPete1** [comment]
closing in favor of https://github.com/ArduPilot/ardupilot/issues/8627
