### ISSUE TITLE
Plane: Relay broken for trigger

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#9090]
#### Issue details
Plane 3.9.0beta6 ChibiOS does not allow a relay for photo capture. When I flashed 3.8.5 NuttX, everything worked normally. Something is going on with using the Auxillary 1 channel for relay-tirggering cameras with a cube autopilot.

@WickedShell @tridge 

#### Version
3.9.0beta6 ChibiOS
Works on 3.8.5 NuttX

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane (haven't tried others)
[  ] Rover
[  ] Submarine

#### Airframe type
Bench Test

#### Hardware type
Cube Black

#### Logs
Relevant Parameters: https://www.dropbox.com/s/5gofdfcpq859wez/TriggerWorking3.8.5.txt?dl=0
All Parameters: https://www.dropbox.com/s/t7cp594454if83g/00000015.BIN.param?dl=0

**Comment by tridge** [comment]
BRD_PWM_COUNT is 7, so aux pins can't be used
