### ISSUE TITLE
I wrote a serial driver of AP_RangeFinder, but compile failed, who can help me look at it? 

### ISSUE THREAD

**Issue by 295951389** [ArduPilot/ardupilot#9122]
Issue details
Hi ,
I'm new for ardupilot. I wrote  a serial driver of AP_RangeFinder of  “AP_RangeFinder_NRA24Serial.cpp”  , when I use the command of "./waf --target bin/arducopter --uoload" there has something wrong I could not to solve . Someone can help me ?

This is the build error:
Waf: Leaving directory `/home/b/ArduPilot/build/px4-v2'
Build failed
 -> task in 'objs/AP_RangeFinder' failed (exit status 1):
        {task 139914955347280: cxx AP_RangeFinder_NRA24Serial.cpp -> AP_RangeFinder_NRA24Serial.cpp.0.o}
/home/b/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-g++ -DCONFIG_ARCH_BOARD_PX4FMU_V2 -D__STDC_FORMAT_MACROS -D__PX4_NUTTX -D__DF_NUTTX -g -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -Wall -Werror -Wextra -Wno-sign-compare -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self - ......

Version
ArduCopter 3.2.1
Platform
[ ] All
[ ] AntennaTracker
[*] Copter
[ ] Plane
[ ] Rover
[ ] Submarine
Airframe type
What type of airframe (flying wing, glider, hex, Y6, octa etc)
Hardware type
pixhawk

**Comment by auturgy** [comment]
Can you link your code (either your repo, or a PR against ArduPilot)?
Are you from NanoRadar?

**Comment by rmackay9** [comment]
it's better to bring this up on Gitter or in the developer discussion forums so I'll close this hear.
https://gitter.im/ArduPilot/ardupilot
