### ISSUE TITLE
Plane: SITL (jsbsim) seriously messed up with default parameters. Flys away from waypoints

### ISSUE THREAD

**Issue by cheintz** [ArduPilot/ardupilot#9152]
### Bug report

Default jsbsim model flies away from waypoints, doesn't leave the ground. Would immediately crash or not leave the ground if it were a real model

**Version**
V3.10.0-dev (f2b4e06a)
V3.9
WORKS in V3.8.5 (7dc5e04)

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
jsbsim 'test' model

**Hardware type**
SITL under Ubuntu 16

**Logs**
Attached
[00000007.zip](https://github.com/ArduPilot/ardupilot/files/2268560/00000007.zip)

**Comment by peterbarker** [comment]
I've just tested this on master and its working fine.

Please reopen if you find there's still a problem.
