### ISSUE TITLE
Copter: Flight timer

### ISSUE THREAD

**Issue by jason4short** [ArduPilot/ardupilot#916]
On DP2 I implemented a flight timer. It looks at the throttle output of the vehicle to increment a timer. If the output is near MIN, it stops and if it if above it runs. This allows the user to see a flight timer similar to an RC controller, but it's more accurate since it takes into account AP flight modes. Only issue is being out of range or knowing when to rest the clock. On vehicle it would be easy to reset the clock with each battery.

Could this be added to Mavlink and sent every so often?

**Comment by govsux** [comment]
Same subject.... An hour meter like in boats and construction equipment would be nice. I think some nylon props have a limited life span with fatigue. It would be nice to have the controller recording the total hours of flight so one could decide to change the props every X hours...  same idea as above but a longer time frame... not just one flight but add them all together as an option.

**Comment by rmackay9** [comment]
Pushing to AC3.5, sorry!

**Comment by rmackay9** [comment]
This is in master now and will go out with AC3.5.
