### ISSUE TITLE
Plane: RC output delay on Arduplane V3.9

### ISSUE THREAD

**Issue by zjl715** [ArduPilot/ardupilot#9162]
I upgraded to arduplane 3.9 from 3.8.5 on a tailsitter VTOL. There was a noticable delay on all RC output which made it really difficult to  control. Delay is present in all output which included two elevons, a rudder, and the throttle. This delay was not present on 3.8.5 I reverted back and the delay is gone.
#### Version
Arduplane 3.9
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Tailsitter

#### Hardware type
Pixracer R14

**Comment by rmackay9** [comment]
it's better to report support issues in the forums rather than on the issues list so I'm going to close this.  sorry to be strict but if we're not then the issues list turns into a support forum.
