### ISSUE TITLE
Mavlink Geofence Protocol

### ISSUE THREAD

**Issue by kfruson** [ArduPilot/ardupilot#9171]
#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Issue details
What is the protocol on the ArduCopter for uploading a Geofence to the vehicle through the Mavlink protocol? For PX4 it was straightforward as using the Mission protocol and setting the mission_type to geofence and the vehicle accept it. This is not the same for the ardupilot Copter and can not seem to find any documentation on how to do this. Any insight on how to upload a **POLYGON** geofence waypoints through the mavlink protocol would be much appreciated. Thanks.

**Comment by OXINARF** [comment]
@kfruson Please don't open issues to ask questions. We have a Gitter channel for that (http://gitter.im/ArduPilot/ardupilot).

Here is a quote I have from giving this explanation for someone else:

>ArduPilot has supported geofence/polygon fence in Plane for a long time. Copter has circle and altitude fence for a long time, but polygon fence exists only since version 3.4 (released about two years ago). Since we were the first project to do it, we made our own messages for it and that’s what we still use:
>
>- FENCE_POINT (http://mavlink.org/messages/ardupilotmega#FENCE_POINT) for points of the geofence
>- FENCE_FETCH_POINT (http://mavlink.org/messages/ardupilotmega#FENCE_FETCH_POINT) to request points from vehicle
>
>I will explain the protocol further below.
>
>As said, besides polygon fence, Copter also supports two other types of fence: a circular fence, with origin at home point, and an altitude fence. All of them are possibly enabled or disabled by the bitmask parameter FENCE_TYPE – all are enabled by default. The fence system should also be generally enabled to work (disabled by default), by setting FENCE_ENABLE parameter to 1 (command MAV_CMD_DO_FENCE_ENABLE also works but only for that “session”, after a vehicle reboot the param value will be restored).
>
>FENCE_ACTION parameter isn’t very relevant now, since the vehicle will try to avoid crossing the fences (as long as AVOID_ENABLE has bit 0 set, as is by default), but basically it is the action to take if the fence is actually crossed – this can be just report via MAVLink statustext message (value 0) or “RTL or Land” (in case it can’t RTL) (value 1).
>All other FENCE_* parameters seem self-explanatory but let me know any doubt you have.
>
>As for the protocol to upload the fence:
>
>- Set FENCE_TOTAL parameter to the total number of points (return point + fence points + 1)
>- Upload points using the FENCE_POINT message (index 0 is the return point; last point should be the same as the first fence point, hence the plus one above)
>
>To get the fence back:
>
>- Get FENCE_TOTAL parameter value to know the number of points
>- Send a FENCE_FETCH_POINT message for each point (reminding that last point should be same as first), which vehicle will send in a FENCE_POINT message
>
>Return point isn’t actually used in Copter, but you need to send a point inside the fence – usually either home is used or the center point of the polygon.

If you still have doubts, go to our Gitter channel and I'm happy to answer your doubts.
