### ISSUE TITLE
Apm is armed but disarming automaticaly after 2 sec of arming

### ISSUE THREAD

**Issue by hamzahack11** [ArduPilot/ardupilot#9180]
dear
i am the beginner i am having issue with my APM 2.8 with arducpter 3.5.7 version that when ever i try to arm it does not armed easily after two or three try make my apm armed but it disarmed automatically after 2 or 3 sec of arming tell me what is the issue but keap in mind that some time it armed perfectly but some time disarm why this strange behaviour plzz help me to troubleshoot this iss
![asdasasa](https://user-images.githubusercontent.com/42303091/44001390-8a6fad30-9e4a-11e8-8e27-6c7fde1f5872.png)
![dasdas](https://user-images.githubusercontent.com/42303091/44001391-8ece06a6-9e4a-11e8-9529-177b3b7acd42.png)
![untitled](https://user-images.githubusercontent.com/42303091/44001393-9585a6ca-9e4a-11e8-8bc7-0df657acd186.png)

ue

**Comment by WickedShell** [comment]
This is a support issue (on unsupported hardware at this point). Please take it to discuss.ardupilot.org.
