### ISSUE TITLE
Copter: gimbal twitch only in Chibios (Copter 3.6)

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/ardupilot#9181]
### Bug report

This has been happening since I first put 3.6 ChibiOS onto my copter.  It did not do this on 3.6 NuttX or Copter 3.5.  Whether sitting on the table or in flight, the gimbal randomly twitches once or twice per minute.  Its very hard and fast microseconds twitch.  The kind you can hear.  It shows up in the log (`GMB`) as desired.  There corresponding vibration on the IMU, but not sure if that is sensing the gimbal twitch or causing it. 

![gmb1](https://user-images.githubusercontent.com/8234496/44003519-bdf38470-9e21-11e8-9eb9-2904cc4ead19.png)

**Version**
Copter 3.6 Chibios

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
Cube 2.1

**Logs**

[Gimbal Twitch.zip](https://github.com/ArduPilot/ardupilot/files/2281054/Gimbal.Twitch.zip)

**Comment by mtbsteve** [comment]
I can confirm that defect on my copter running RC8 ChibiOS

**Comment by rmackay9** [comment]
@Pedals2Paddles, @mtbsteve, This is only on a Solo right?

**Comment by Pedals2Paddles** [comment]
As far as I know.

**Comment by mtbsteve** [comment]
@tridge
I just tested  3.7 Dev CiBiOS on my Solo. 
The Gimbal issue significantly worsened compared to 3.6.1 CiBiOS. The gimbal is erratically twitching and moving around all axis while with 3.6, I experience a slight twitch only 1-2 times per minute as described in the OP.

**Comment by Pedals2Paddles** [comment]
@mtbsteve The new severe degradation of the gimbal in master is because of this: https://github.com/ArduPilot/ardupilot/issues/9763.  All the RC channels going bonkers.  The twitch issue is still there.  But the RC issue just makes the whole thing go nuts.  Once the RC gets fixed, we still need to figure out what's causing the twitching.

**Comment by mtbsteve** [comment]
Thanks for digging into this!

**Comment by Pedals2Paddles** [comment]
Completed with https://github.com/ArduPilot/ardupilot/pull/9875 and https://github.com/ArduPilot/ardupilot/pull/9909
