### ISSUE TITLE
Plane: use acro roll limit in roll PID in ACRO mode

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#9192]
we should override the roll rate limit to match the ACRO_ROLL_RATE when in ACRO mode. See 
https://discuss.ardupilot.org/t/chibios-port-of-ardupilot/20491/70?u=tridge

**Comment by Naterater** [comment]
Where is RLL2SRV_RMAX used? It was my understanding that automatic missions, etc. did immediate stepped roll commands instead of ramped changes that were clamped by this parameter. If we just removed RLL2SRV_RMAX, wouldn't that accomplish the same thing?

**Comment by Hwurzburg** [comment]
This still is popping up in the RCG threads....personally, I think that ACRO rates should apply (ie override the x_RMAXs) to both ACRO and STABILIZE since they are both aerobatic modes (ie 2D and 3D in other FC parlance)....

**Comment by IamPete1** [comment]
i have done a fix for the roll limit, it seems that the pitch limit already works as it should. @Hwurzburg Is this in line with what is being reported?

**Comment by Hwurzburg** [comment]
Not sure, most complaints were about roll since that is always much faster than pitch in a plane due to axis stability differences....does this fix also allow stability mode to roll as fast as ACRO?

**Comment by IamPete1** [comment]
this is just a acro mode bug fix to match the param descriptions currently, stabilize mode would be a change of behavior, not that we shouldn't do that too but i think should be a different PR

**Comment by IamPete1** [comment]
PR merged, acro roll rate limit should now over ride RLL2SRV_RMAX in acro mode
