### ISSUE TITLE
Method to avoid bad RC trims

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#9214]
This is a proposed method to avoid people having bad RC trims. 
The idea is to add an arming check that checks if the roll/pitch and yaw sticks have been within the dead-zone for at least 2 seconds continuously since boot. If they haven't been, then give a RC calibration error on arming.
This idea was inspired by issues with people using the trim tabs to trim planes, but this also applies to copters.
Related to this is to have an option to behave like we do on the skyviper, which is to automatically set the roll/pitch and yaw trim if a radio is connected and the values don't change at all for 2 seconds, and the values are within 25% of center.

**Comment by peterbarker** [comment]
On Fri, 17 Aug 2018, Andrew Tridgell wrote:

> This is a proposed method to avoid people having bad RC trims.
> The idea is to add an arming check that checks if the roll/pitch and yaw
> sticks have been within the dead-zone for at least 2 seconds continuously
> since boot. If they haven't been, then give a RC calibration error on
> arming.

So the obvious question... why not throttle?

Perhaps skip the automated update of that one, 'though....

**Comment by peterbarker** [comment]
We have had within-deadzone arming checks for years now, so this one's done.
