### ISSUE TITLE
SD card absence not recognized by startup tones

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#9215]
### Bug report

**Issue details**

Latest startup tones do not reflect "NO SD CARD" like NuttX. The normal startup trill is heard and no indication is given until an attempt to arm. I thought the tones were going to be like the old NuttX version.

**Version**
Plane 3.9.1 beta2

**Platform**
[?] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Traditional Electric Twin

**Hardware type**
Cube black

**Logs**
None - because SD card not installed.

**Comment by Naterater** [comment]
Yes, but having the tones recognize that there is no SD card is also desired by many. That should not have changed. I would like to be able to recognize that I don't have an SD card installed when I boot.

**Comment by proficnc** [comment]
That’s fair

**Comment by Naterater** [comment]
No longer an issue with 4.x releases.
