### ISSUE TITLE
Eclipse Setup problems with PixHawk; flashing issues

### ISSUE THREAD

**Issue by i-sheremet** [ArduPilot/ardupilot#922]
Hello, dear developers. 

I'm recently start writing my master project and my goal is to create a plane and make some researches based on PixHawk. I have an experience with C++ and some work with APM 2.5, but only via MisPlanner. 

I have few (I belive) basic questions, and maybe they are depending on each other. So I will try to brief not to take a lot of your time.

My goals are: build a plane and connect some additional sensors to it; learn how to add func to main code in order to collect the date on SD card; look into all the source code and understand the way it works.

I have been working last week learning http://pixhawk.org/dev/ and http://dev.ardupilot.com/ pages to fulfill my desires and I got this questions:
- what does command "clean" do http://dev.ardupilot.com/wiki/building-px4-with-make/ in point 6-3. It's written that it should clean ardupilot directory, but it doesn't even delete ArduPlane-v2.px4 file that I made by Ecliplse.
- When I try to build a project Arduplane in Eclipse Project Explorer menu,  just by clicking right button -> Build Project it gives this error 
  "../mk/find_arduino.mk:45: **\* ERROR: Cannot find Arduino on this system, please specify on the commandline with ARDUINO=<path> or on the config.mk file.  Stop."
  I wrote in ardupilot\config.mk the right path to my Arduino IDE (as it said in point 5, link mentioned above), but nothing changes. And I also tried to put just random path to PX4_ROOT and NUTXX, but nothing changes - the same mistake. Why it doesn't influence anything? 
- Why #include files in Eclipse are still underlined as unresolved problem, if I add the includes directory as it said here:  http://dev.ardupilot.com/wiki/editing-the-code-with-eclipse/ ?

Thank you in advance for your attention!

**Comment by chasenmoses** [comment]
Ilia-sheremont, did you ever find a solution to your second bullet point?  I too am having build errors (make and eclipse) in regards to the path to the Arduino IDE.  Any help would be much appreciated.  Thanks,
Chasen

**Comment by squilter** [comment]
@chasenmoses On what operating system?

**Comment by chasenmoses** [comment]
Hello Sebastian,
   I am using windows OS.  I managed to mitigate the original issue in
eclipse by modifying the project's (c++) build properties to include an
environment variable ARDUINO with a value
of /cygdrive/c/ArduPilot-Arduino-1.0.3-windows.  However, now I am getting
a lot of errors that all say the same thing "recipe for target
'/tmp/ArduPlane.build/altitude.o' failed" and "recipe for target
'/tmp/ArduPlane.build/altitude.elf' failed".  Thanks for your response.  I
imagine getting up and running the first time has a steep learning curve
but should be smooth sailing after I get these issues worked out.
Chasen

**Comment by squilter** [comment]
I can't help too much with windows setup.  I'll have to direct you to dev.ardupilot.com.  However, do note that arduino is no longer supported.
