### ISSUE TITLE
ARMING_CHECK: -26, what does that mean?

### ISSUE THREAD

**Issue by MR444** [ArduPilot/ardupilot#9224]
I wanted to change some parameters and saw that ARMING_CHECK is set to -26. What does that mean?

#### Version
2.5.5

#### Platform
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad

#### Hardware type
Dropix

![arming check](https://user-images.githubusercontent.com/17322455/44302726-25564000-a32f-11e8-9845-1c88f23444be.JPG)

**Comment by lvale** [comment]
sorry,

can you post your question on the support forum ? 
https://discuss.ardupilot.org

thanks

and closing
