### ISSUE TITLE
ChibiOS: log download speed just around 100~120kb/s

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#9245]
### Bug report

**Issue details**
download 17293312 bytes log take 162s, 106k/s
download 24072192 bytes log take 210s,  114k/s
download 17412096bytes log take 150s, 116k/s
**Version**
master branch , commit id :519be92
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ * ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
Pixhawk

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by liang-tang** [comment]
Nuttx test result:
    download 9973760 bytes take 55s

**Comment by peterbarker** [comment]
Yes, this has indeed been killed recently.

44fd85ff2965948b79a540ec626db5bdc57de0a1 Downloading log6.bin - 1224704/0 bytes 53.8 kbyte/s
44fd85ff2965948b79a540ec626db5bdc57de0a1^ Downloading log6.bin - 831488/0 bytes 269.8 kbyte/s (0 retries 0 missing)

**Comment by liang-tang** [comment]
https://github.com/ArduPilot/ardupilot/commit/7897fbc3c16f359c0f9859eb5994cd7b7d5bf2c9  alive again.
