### ISSUE TITLE
terrain following using lidar not working in auto mode

### ISSUE THREAD

**Issue by amitmanish** [ArduPilot/ardupilot#9247]
Hello everyone,
I am trying to enable terrain following in autonomous mode using TF 02 Lidar.
I have configured lidar on telem2 port at 115200 baudrate and i am receiving distance in mission plannner and its working in loiter mode. I tried enabling terrain following in auto mode but could not get it working.

My setting are:

rangefinder type = 9
using Serial 2 with 115200 baudrate
rangefinder orientation = 25 (downward)
Terrain enable = 0
Terrain follow = 0
Rangefinder max_distance = 10m
Rangefinder min_distance = 5cm
Ground clearance = 20cm
Now, I am confused if i should enable Terrain enable = 1 as it is stated in ardupilot site that it is used for getting terrain data using google maps.
While switching from loiter to auto i am constantly getting 2 errors: 1) Terrain Data missing
2) Bad Lidar Health

**Comment by rmackay9** [comment]
support questions really need to go into the forums.  Sorry to be strict but otherwise our to-do list just turns into a support forum.  Here's a link to the Copter support forum: https://discuss.ardupilot.org/c/arducopter
