### ISSUE TITLE
ChibiOS: can't load invisible param in default.param file when startup.

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#9248]
### Bug report

**Issue details**
![342dfd387d5653e8f770751c6faff8f](https://user-images.githubusercontent.com/16251761/44449416-a60f8780-a620-11e8-9c8d-862cc5add2e8.png)

_Please describe the problem_
can't parse invisible param.
**Version**
master branch , commit id :519be92

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ * ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by liang-tang** [comment]
when switch back to nuttx（Plane 3.8.4），same issue. but when reset all params to default using MP，this issue can be solved，this is a param incompatible issue between chibios and nuttx？

**Comment by peterbarker** [comment]
I think this was a parsing problem, and I vaguely recall it being fixes.
