### ISSUE TITLE
Differential spoilers and crow brakes for landing cannot mix both at same time

### ISSUE THREAD

**Issue by jgilbertfpv** [ArduPilot/ardupilot#9259]
### Feature request

I've been trying to set up differential spoilers AND crow brake mixing together on a fx-79 buffalo, i've seen mentions on but nothing like exactly what i'm needing it to do. I've gotten everything moving right with differential spoilers and yaw control going the right way.

I'd like to have differential spoilers working as they currently are, but also be able to have crow braking via switch so that the servos act like they do with yaw command, but on both wings together. I followed this guide here setting up so far, http://ardupilot.org/plane/docs/differential-spoilers.html and the page after refers to setting up crow brakes with a flaperon mix, but not with diff spoilers

Does a mix need to be made in the radio instead? right now i have AETR1234 should i do rc-in1, rc-in2, and so on and set up all of my elevon/crow mixing in the taranis?

**Platform**
[ x ] Plane

I have also checked the post here https://github.com/ArduPilot/ardupilot/pull/2935 but still doesn't seem to be for crow braking

**Comment by Naterater** [comment]
Merged into master, this will make its way to beta and stable releases soon. https://github.com/ArduPilot/ardupilot/pull/9391
