### ISSUE TITLE
Pixhawk 12 and 14 PPM channels freezing

### ISSUE THREAD

**Issue by shaggee** [ArduPilot/ardupilot#929]
Pixhawk have trouble with 12 and 14 channels connected via PPM. Signal sometimes freezes for 2sec. Sometimes all channels shows 0. Its not receiver error or RC link loss. 8 channels and sBUS working well but PPM 12 and 14 channels not. This issue turns on failsafe.
LRS receiver PPM output spec: 2ms*number of channels +4ms, negative polarization.

There is a video: https://www.youtube.com/watch?v=Fguq8rzL6Gs
Logs: http://ardupilot.com/forum/viewtopic.php?f=21&t=6669&sid=441737aaf1dd49b7ba9e71f2df07db2e

**Comment by OXINARF** [comment]
@shaggee Is this still valid?

**Comment by shaggee** [comment]
@OXINARF Fixed. It was LRS SBUS polarisation problem.

**Comment by OXINARF** [comment]
Thanks, closed then.
