### ISSUE TITLE
ServiceCaller.on_call_service_button_clicked(): error calling service "/mavros/set_mode":

### ISSUE THREAD

**Issue by chrismath** [ArduPilot/ardupilot#9311]
#### Issue details
_Please describe the problem, or desired feature_
I am not able to put the Arducopter in 'Guided ' mode . As I am trying to call the ROS service "/mavros/set_mode" there is an error as shown
ServiceCaller.on_call_service_button_clicked(): request:
base_mode: 0
custom_mode: "GUIDED"
ServiceCaller.on_call_service_button_clicked(): error calling service "/mavros/set_mode":
unable to connect to service: remote error reported: client wants service /mavros/set_mode to have md5sum e4f18fa93379f9ff1780d270ce110203, but it has 48ecf639e39052f8856a839dcddf826a. Dropping connection.

#### Version
I am trying to do sitl with iris quadrotor model. It is on a Ubuntu 16.04 ROS] Kinetic Kame
#### Platform
[  ] All
[  ] AntennaTracker
[ x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
I kindly request you to help me out.

**Comment by khancyr** [comment]
Hello, 
this error belong to mavros issue.
About the issue, you get two different definition of mavros message, are you sure that you have source the good catkin workspace ? If you compile mavros from source, clean the install and recompile, it should solve the issue.
