### ISSUE TITLE
Copter: heading turns towards next WP before vehicle reaches waypoint

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#932]
The command (or waypoint) is considered complete when the target point that the copter is chasing reaches the waypoint.  This target point can be 10m ~ 20m ahead of the copter depending upon the WPNAV_SPEED parameter.  The vehicle will start pointing towards the next waypoint from the moment the command is completed so this leads to it turning towards the next waypoint 10m ~ 20m early.
It would be better to instead point the vehicle in the direction it's travelling which is the direction from the vehicle to the target point.

https://github.com/diydrones/ardupilot/issues/465

**Comment by rmackay9** [comment]
Pushed to AC3.4.

**Comment by OXINARF** [comment]
This should be fixed with #6143, which is now on master and will be on 3.5
