### ISSUE TITLE
mavlink_msg_uavcan_node_status file not found

### ISSUE THREAD

**Issue by hanliyao** [ArduPilot/ardupilot#9324]
### Bug report

**Issue details**
           mavlink_msg_uavcan_node_status.h: No such file or directory

**Platform**
[  ] All
[  ] AntennaTracker
[*] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
   Pixhawk

**Comment by WickedShell** [comment]
Appears to be a support/tooling problem, but there is not nearly enough details in this issue to do anything, and UAVCAN is building in master and stable releases successfully.
