### ISSUE TITLE
Chibios, Revo mini // Feature Request: one more Uart

### ISSUE THREAD

**Issue by RMFPV** [ArduPilot/ardupilot#9326]
**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Additional context**
Please add one more Uart to the free PWM, or better RC-in pins to be used for frsky passthrough.
Assuming that Flexi port is set for i2c.

**Comment by IamPete1** [comment]
see: https://github.com/ArduPilot/ardupilot/pull/8984

I have gps, passthrough telemetry and wifi telemetry running on mine, its a fairly straight forward edit of the hwdef.dat and recompiling. I do think the 3 UARTS and rc in on the 2nd rc in pin should be the default.

**Comment by MFlghts** [comment]
Please add changes of the hwdef.dat here for the third Uart.

**Comment by IamPete1** [comment]
A hwdef.dat for three UARTS is in the linked pull request

**Comment by MFlghts** [comment]
Thank you!

**Comment by IamPete1** [comment]
Looks like we now have three serial ports, and you can have four via alt-config. 

https://ardupilot.org/copter/docs/common-openpilot-revo-mini.html

In any-case I'm not sure you can even buy this board anymore.

**Comment by RMFPV** [comment]
I don't see any changes in docs about that.
Can you please describe what exactly is alt-config now?

Yes it's not easy to buy it, but some people still use it, as it's a small, nice and reliable fc.
