### ISSUE TITLE
Can NVidia TX2 Communicate with Ardupilot via FTDI Cable or USB to Serial interface？

### ISSUE THREAD

**Issue by bssung** [ArduPilot/ardupilot#9327]
In this guild http://ardupilot.org/dev/docs/companion-computer-nvidia-tx2.html， NVidia TX2 Communicate with Ardupilot via AuVidea.eu’s J120 carrier board，but I don‘t have a J120 board. Anyone konws how to use FTDI Cable or USB to Serial interface to do the mavlink communication?  THX

**Comment by rmackay9** [comment]
It's probably better to ask this question in the [APsync/CompanionComputer discussion forum](https://discuss.ardupilot.org/c/apsync-companion-computers) so I'll close this issue if that's OK.
