### ISSUE TITLE
failsafe with DJI RE ocusync air unit

### ISSUE THREAD

**Issue by mmormota** [ArduPilot/ardupilot#9331]
#### Issue details
The DJI RE air sytem (HD digital video transmission system with uplink) provides sbus signal on the air side. Unfortunately I can’t set a proper failsafe using this stream.

I did some oscilloscope tests on the sbus stream. When the connection broken, nothing happens for 3 secs, then the sbus stream stops, 0 Volts on the sbus output. The “frame loss” and “failsafe” flag is not set properly even in that 3 secs.
The DJI RE has no programmable channel values for failsafe condition.

So, checking it in mission planner, the autopilot holds the last channel values in case of broken connection. **This makes the usual throttle failsafe unusable.**

The autopilot detects the broken connection and warns “no rc receiver”, unfortunately it doesn’t initiate failsafe condition.

I know that it's mostly an incorrect sbus stream, dji's fault. However:
- I think a "no rc receiver" inflight condition (because of the lost sbus stream) is more then enough for failsafe
- there are many DJI RE ocusync air units out there

#### Version
Arduplane 3.9
#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
glider

#### Hardware type
Radiolink Mini Pix

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by mmormota** [comment]
Yes. 
It is connecting to the DJI RE goggle using undocumented COFDM signal, the link is two way. The goggle has a jack input for cppm signal, it is connected to the RC radio's buddy port. The Tx of the RC radio is disabled. The goggle sends the RC channels up to the air unit.

**Comment by mmormota** [comment]
DJI's primary focus is racing (that's why the RE), FPV features are a bit pour, for example the OSD is missing mandatory data like home arrow and distance. But the picture quality and the range is rather good, the device is small and compact, so it's interesting for FPV too.

**Comment by jmachuca77** [comment]
Yeah! I like the idea, I just did not know you could also send the RC signals. I coincidentally just bought a Mavic2 with the RE Googles, though I think the version that comes with the bundle doesn't come with the air unit. So I might get one and test this.

**Comment by IamPete1** [comment]
Since it was reporting “no rc receiver” I suspect it is just a matter of setting the fail-safe settings correctly. I'm going to close but feel free to re-open if this is still as issue on 4.1.
