### ISSUE TITLE
No flap option with differential spoilers

### ISSUE THREAD

**Issue by jgilbertfpv** [ArduPilot/ardupilot#9332]
Why no option for landing flaps when using differential spoilers mix? can this be added to the servo.cpp file somehow in the differential spoilers section? 
if (flap > 0) {
// apply flap to right wing
dspoiler1_right = constrain_float(elevon_right + flap, -4500, 4500);
dspoiler2_right = constrain_float(elevon_right - flap, -4500, 4500);
// apply flap to left wing
dspoiler1_left = constrain_float(elevon_left + flap, -4500, 4500);
dspoiler2_left = constrain_float(elevon_left - flap, -4500, 4500);
}

#### Version
Arduplane - all

[  ] Plane

#### Airframe type
Flying wing with differential spoilers for crow mix. One side crows at a time for yawing but no landing flaps option
#### Hardware type
Px4

**Comment by IamPete1** [comment]
[Differential Spoilers & Full House Wing](https://ardupilot.org/plane/docs/differential-spoilers.html#differential-spoiler-options) we now have some options for this
