### ISSUE TITLE
Copter: allow reversing pitch input through parameter

### ISSUE THREAD

**Issue by matthewlloyd** [ArduPilot/ardupilot#935]
This is a long-standing issue (more than a year old) that was never migrated from Google Code to GitHub. I'm reopening since it still seems to be an issue in AC 3.1.2, as I just discovered when testing out my quad for the first time. The user expects pushing the pitch stick up to pitch the copter forward, which is a standard convention set by pretty much every other multicopter flight controller out there.

Here's the original text from Google Code (https://code.google.com/p/arducopter/issues/detail?id=531):

"
It has been discussed already in many forum posts, like:
http://diydrones.com/forum/topics/pitch-direction-and-yaw
http://diydrones.com/forum/topics/pitch-is-reversed-where-should-i-fix-it
http://diydrones.com/forum/topics/recommended-settings-for

In the first a developer acknowledges it as a bug:
"Jason, this sort of confusion is a long-standing issue, I'm sure there's already an issue report done.
We really need to rethink how all of this is done in Arducopter.  We were sort of stuck with the RC_Channel library from Arduplane, which had a different intended use, and I think that's why we are stuck with it.
Nobody should have to reverse channels in their Tx for Arducopter.  They should all be straight-up, and all reversing be done in the software."

The AC2 Manual (http://code.google.com/p/arducopter/wiki/AC2_First) says that the pitch channel does pitch forward with low PWM and pitch backward with high PWM, but is definitely counter-intuitive.
So either the code is fixed (which IMHO is the best solution), or it has to be specified very clearly in the manual that the pitch channel has to be reversed (or maybe doing it automatically in the Mission Planner).
"

**Comment by UltiFix** [comment]
I am still experiencing this issue with apm 2.6 running arducopter 3.2.1

**Comment by magicrub** [comment]
APM 2.6 has run out of memory long ago. No new features are able to be
added. Please move up to the current hardware: pixhawk.

**Comment by rmackay9** [comment]
@UltiFix, we recommend that people just reverse the pitch channel in the transmitter.  Pretty much all transmitters support this.

**Comment by magicrub** [comment]
Close?

**Comment by R-Lefebvre** [comment]
I.... ugh...

I think those are my comments referenced above.  And they still make sense.  It doesn't make sense that we make all users go into their TX and reverse the pitch channel.

However, fixing this would mean that ALL past users would be required to go back into their radio and un-reverse the pitch channel when they update their firmware.  That's a nightmare scenario.  Surely some people will miss the instruction, and promptly crash into themselves on their first take-off.  In other cases, users who bought RTF systems complete with pre-programmed Tx, will have no idea how to even do this, or what "reverse the channel" even means.

We could simply add a parameter to reverse the channel (or respect the existing reversing parameter) but we got rid of this for a valid reason.  That is the problem with people double-reversing the channels, ie: reverse the Tx output, and then reverse the input in AC.  Even worse than that, we've had people triple reverse in helicopters, reverse the Tx, reverse the input, and then reverse the servo outputs.  Now the swashplate moves in the correct direction to pilot input, but operates backwards from the PID, which I've then seen people solve by using NEGATIVE numbers in the PID!

It's madness, and we have to break the chain somewhere.

**Comment by magicrub** [comment]
Rob, you just blew my mind. I've never heard of a negative PID value.

**Comment by UltiFix** [comment]
Wow, that is crazy!
I ended up just reversing the channel on my FrSky gear.

**Comment by R-Lefebvre** [comment]
@magicrub, yep, blew me away that somebody would do that.  But, these are simply floats, and there's no checking for it, so you can just do it and it works.

**Comment by magicrub** [comment]
Negative negative feedback <facepalm>

**Comment by danieltwagner** [comment]
I just set up my first quad and ran into this and cannot believe this is not documented more prominently (or indeed fixed). May I suggest an alternative way of RC calibrating as a somewhat elegant solution to this issue? If the instructions were to "yaw left", "pitch forward", etc. then it would be trivial to detect which direction the user intends their sticks to work. Nothing would have to change for existing users but all new users would "magically" get the correct setup for whatever their TX is configured to.

**Comment by Evidlo** [comment]
I did RC calibration and accelerometer calibration and ran into this same issue on my first quad.

**Comment by UltiFix** [comment]
Yea this should definetely be documented more. Was it atleast easy to find with google?

Wow time flys. I can't believe this was 2 years ago.

**Comment by Naterater** [comment]
RCn_REVERSED does this.
