### ISSUE TITLE
Blheli pass through not working since last release of arduplane 

### ISSUE THREAD

**Issue by zingaros** [ArduPilot/ardupilot#9350]
### Bug report

**Issue details**

I’m using arduplane chibiOS 3.9.1 on a mini pix from radiolink
With firmware 3.9 blheli passthrought was working oob (without need for a special configuration), since I updated to 3.9.1 blheli config refuse to connect properly. Log of blheli says the com port open but it is then unable to read the config of the ESC.
I tried with blheli suite without success, same when enabling SERVO_BLH_AUTO

**Comment by Kelly-Foster** [comment]
I have been able to use BLHeliSuite through a very recent version of ArduPlane.  Connection was slightly hit and miss, but nothing like it was months ago.  Overall it was working well for me, both in Suite tuning of parameters, and in ESC/motor operation in flight, with telemetry on the OSD.

Kelly

**Comment by zingaros** [comment]
Hello @Kelly-Foster , sorry not not have followed up earlier.

So i did the test with 2 different hardware on chibios release of arduplane 3.9.1: mini pix and fkk omnibus. same results and no success. I even reverted back to inav to confirm my hardware is not the issue.

Here are the logs on **BL Heli configurator** on chrome and below after the one on BHelisuite.
On Bheli configurators, all seems fine except it nerver display the configuration.
Running - OS: Windows, Chrome: 69.0.3497.100, 
Configurator: 1.1.0 
Running - OS: Windows, Chrome: 69.0.3497.100, 
Configurator: 1.1.0 
Connecting to: COM12 SERIAL: Connection opened with ID: 1, Baud: 115200 Serial port successfully opened with ID: 1 
MultiWii API version received - 1.37.0 Flight controller info, identifier: ARDU, version: 3.3.0 Running firmware released on: Mar 16 2018 08:42:29 Board: ARCH, version: 0 Unique device ID received - 0x2a00243037470f34393338 
Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished Reading setup Reading setup finished

**BL Heli suite**
![warningserialinterfacearduconn_181007_1](https://user-images.githubusercontent.com/15964221/46583303-18afb780-ca55-11e8-8429-081448ddc1c6.png)

**Comment by Bumerangas** [comment]
same problem BLHeli Pass-Through not working on Arducopter 3.6.7 just on Arduplane some of older builds.
