### ISSUE TITLE
The Angle of IST8310 Compass on pixhawk2

### ISSUE THREAD

**Issue by jamming** [ArduPilot/ardupilot#9356]
The angle of pixhawk4 GPS(with IST8310 compass) are different against the old one(with HMC5883/5983 compass). When using the pixhawk4 GPS on a pixhawk2 flight-controllor, we have to change the angle of external compass  manually.  After selecting Yaw270, Mission Planner don't pop " compass inconsistent" message again. I think that maybe a bug.

**Comment by rmackay9** [comment]
@jamming, if you are using Copter, could you try with Copter-3.6.0-rc8?  It's available through the mission planner's install firmware screen after pressing the "Beta Firmwares" link.  If this link isn't visible then please go to Config/Tuning >> Planner and set the "Layout" drop-down to "Advanced".

This is beta firmware so it hasn't completed all testing.  It seems stable but please be careful.

**Comment by IamPete1** [comment]
@jamming has this been resolved?

**Comment by jamming** [comment]
Not yet. I had tested the arducopter-latest firmware and the arducopter-4.0.7 stable firmware,&nbsp; the angle of IST8310 was still Yaw270.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Aug 30, 2021 02:51 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ArduPilot/ardupilot] The Angle of IST8310 Compass on pixhawk2 (#9356)

&nbsp;



 
@jamming has this been resolved?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IamPete1** [comment]
@jamming Thanks for the update. To be clear is this a external compass on a GPS unit? Not the compass internal to the flight controller?

**Comment by jamming** [comment]
Yes, it is a&nbsp;external compass on a GPS unit for pixhawk2.&nbsp;
There is a&nbsp;&nbsp;IST8310 internal to pixhawk4,pixhawk4-mini and Durandal, but there is no IST8310 internal to pixhawk2.
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;&nbsp;
Date: &nbsp;Mon, Aug 30, 2021 08:11 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ArduPilot/ardupilot] The Angle of IST8310 Compass on pixhawk2 (#9356)

&nbsp;



 
@jamming Thanks for the update. To be clear is this a external compass on a GPS unit? Not the compass internal to the flight controller?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IamPete1** [comment]
I don't think there is anything we can do to help with the orientation of compass in a external GPS. We have auto rotation now, that should pick up the correct orientation when calibrating.
