### ISSUE TITLE
Copter: Ch 7/8 options for two/three way switch

### ISSUE THREAD

**Issue by britdavis** [ArduPilot/ardupilot#936]
I've found that I prefer to not have Land or RTL modes as part of the same 6-way FM switch I use for in-flight modes, and both are very useful.

There are, of course, Ch 7/8 options for both Land and RTL, but it sure would be nice to use Ch 7 with a three-way switch to handle both of those modes, like:

Ch7 PWM low Land
Ch7 PWM mid <no action>
Ch7 PWM high RTL

**Comment by lthall** [comment]
Done
