### ISSUE TITLE
Plane: HIL, bad climb rate readings

### ISSUE THREAD

**Issue by pxkumar2** [ArduPilot/ardupilot#937]
@tridge , @rmackay9 
I use "barometer.get_climb_rate()" to get V_z. This is producing a weird output in HIL mode. I've attached a plot of this variable.
The plot is the response of barometer.get_climb_rate() to a steep dive (almost vertically down) in X-plane. As you can see, we're getting a very odd signal for the climb_rate.
Also, is this the best way to get the vertical velocity even in non-HIL or in the actual flight mode?

Any help will be hugely appreciated. 
![capture](https://cloud.githubusercontent.com/assets/6485612/2584668/4fa2be6a-b9e1-11e3-966e-7f719bce6164.PNG)

**Comment by Naterater** [comment]
Is this still an issue?

**Comment by auturgy** [comment]
HIL was effectively deprecated with the APM.
If it’s revived it will be a new implementation, so this is no longer relevant.
