### ISSUE TITLE
Copter: auto-tune does nothing when AHRS roll/pitch trims are > 3 degrees

### ISSUE THREAD

**Issue by matthewlloyd** [ArduPilot/ardupilot#938]
Auto-tune does not start unless the AHRS pitch and roll angles are less than AUTO_TUNE_LEVEL_ANGLE_CD, which is currently 3 degrees. We are comparing ahrs.roll_sensor and ahrs.pitch_sensor with this threshold, and they are both post-AHRS-trimming. That means if the user has trimmed the copter using the instructions at http://copter.ardupilot.com/wiki/autotrim/, and the computed trim angles are more than 3 degrees (as they were for my quad), AutoTune says that it has started but never actually starts, which can be confusing.

**Comment by Naterater** [comment]
I haven't seen this issue pop up in the last few years. Is it possible that this has been solved since 2014?

**Comment by rmackay9** [comment]
I think we've improved messages being sent to the ground station to warn the user about what's happening so this is no longer an issue.  Txs for doing this review of issues.
