### ISSUE TITLE
differential spoilers fix- need help compiling with new servo.cpp file to test.

### ISSUE THREAD

**Issue by jgilbertfpv** [ArduPilot/ardupilot#9388]
### Feature request - add crow brakes to differential spoilers and fixed so inner moves down/outer up

Differential spoilers have no crow brake option. also i've never seen them set up where the inner goes up and outer goes down, always the opposite. i've added a fix but when i try to compile, i get past the ./waf configure --board px4-v3 part but when i do ./waf plane i get errors referring to Nuttx/config.h when i tried to follow instructions on setting up a build environment with cygwin. and i'm on a capped data speed which makes thing very difficult. 

**Describe the solution you'd like**
I've edited servo.cpp and need a px4-v2 and px4-v3 (i think my board is v2 but ardupilot recognizes v3?)
I am able to compile for SITL but not sure what to do with the elf to test it. but being as it compiles without errors on the changes, i'm thinking i'm off to a good start. i just need a px4-v2 or 3 firmware to flash to test it on the bench.
i did manage to get a .px4 firmware by using the make method but it skipped a few things and when i uploaded my parameters it had 10 missing and everything seems to be a little laggy. but as far as the servo changes everything moved in the correct direction and crow flaps were responding to switch input. I'm unable to compile using the ./waf method because i get errors with nuttx config missing and i'm not sure what to do.

**Platform**
Plane

**Additional context**

[servos.zip](https://github.com/ArduPilot/ardupilot/files/2364974/servos.zip)
![changes](https://user-images.githubusercontent.com/37930433/45274018-03a62f80-b47b-11e8-97e4-85471140fd57.png)

**Comment by Naterater** [comment]
Looks like this issue was solved in https://github.com/ArduPilot/ardupilot/pull/9391, is that correct?

**Comment by jgilbertfpv** [comment]
Yes sorry I forgot about this. I'll close it now
