### ISSUE TITLE
Rover: add support for electric trolling motors

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9407]
It would be nice if we added support for controlling the speed and direction of electric trolling motors like [these from Minn Kota](https://minnkotamotors.johnsonoutdoors.com/freshwater-trolling-motors).  It is likely that these motors accept a PWM at least for the motor speed and possibly for the servo input as well.

There are many other low cost trolling motors on eBay as well that may also work.

This task involves:

- finding a commonly available motor which accepts a pwm input for motor speed and ideally motor direction as well (i.e. motor includes a servo to move the motor).
- testing that it works with ArduPilot and/or modifying ArduPilot to support the motor
- document the connection and setup on our Rover/Boat wiki

This request first came up [here on discuss](https://discuss.ardupilot.org/t/newbie-questions-about-boat-frames).

**Comment by IamPete1** [comment]
We support Torqeedo now, https://github.com/ArduPilot/ardupilot/pull/17979 so maybe we can close?

**Comment by rmackay9** [comment]
yes, we can close this now, thanks!
