### ISSUE TITLE
Copter: Auto trim conflict with disarm

### ISSUE THREAD

**Issue by RMFPV** [ArduPilot/ardupilot#9410]
### Bug report

**Issue details**
Auto trim requires to hold Throttle 0 and Yaw right for 15sec, but motors get disarmed after 15sec of inactivity, so it's impossible to start flying with Auto trim.

**Version**
Latest FW

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
Pixhawk 1

**Comment by IamPete1** [comment]
Auto trim is yaw in the arming direction, not disarming. See https://ardupilot.org/copter/docs/autotrim.html
