### ISSUE TITLE
EKF2/3: getLLH() truncates altitude by 1 meter

### ISSUE THREAD

**Issue by horiuchi4dn** [ArduPilot/ardupilot#9420]
### Bug report

**Issue details**
The last two digits of altitude from NavEKF2_core::getLLH() are always zeros.

https://github.com/ArduPilot/ardupilot/blob/2d3942222b768ebc3df7a733f5b6833f7df1aedd/libraries/AP_NavEKF2/AP_NavEKF2_Outputs.cpp#L322

EKF3 seems using same logic.

**Version**
current

**Comment by WickedShell** [comment]
Good catch, I have a stab at fixing it here #9423. It doesn't affect most of the flight code for reasons outlined in the linked patch that fixes it, but it does affect a couple of libraries, and is definitely worth having handled correctly.

**Comment by WickedShell** [comment]
Fixed in #9423, GitHub didn't automatically close the issue.
