### ISSUE TITLE
Chibios, Revo mini - S.bus doesn't work at Rc in 1

### ISSUE THREAD

**Issue by MFlghts** [ArduPilot/ardupilot#9439]
### Bug report

S.bus and Ppm doesn't work at Rc in 1
Issue was reported by couple of users

**Version**
arduplane.apj | Sep 15 07:58

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Fixed wings

**Hardware type**
Revo mini

**Comment by MFlghts** [comment]
Solved - it's a mistake in the manual, rc-in is at pin 3

**Comment by auturgy** [comment]
Thanks Alex
