### ISSUE TITLE
BOOST option doesn't work properly

### ISSUE THREAD

**Issue by charleslinquist** [ArduPilot/ardupilot#9443]
### Bug report

BOOST mode doesn't work

BOOST function (Servo option #81) doesn't 'stick' through a reboot.  I assume that a register doesn't get loaded properly.  MP reports that the register value is set to "81", but the function doesn't work unless you change it to something OTHER than 81 and then rewrite it.   It then works - until the next reboot.

**Version**
RC10

**Platform**
Copter

**Airframe type**
X4

**Hardware type**
PixHawk

**Comment by IamPete1** [comment]
Sorry we never got to this, please re-open if this is still a issue on 4.1
