### ISSUE TITLE
QuadPlane: larege Att.DesYaw

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#9450]
### Bug report
QuadPlane: larege Att.DesYaw , more than 600.

![2](https://user-images.githubusercontent.com/16251761/45735407-61284200-bc1a-11e8-8044-260c3bd490ee.png)

test in SITL

**Version**
master branch,  commit 0e0d84

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ *] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

**Hardware type**

**Logs**

[2018-09-19 14-37-41.zip](https://github.com/ArduPilot/ardupilot/files/2395733/2018-09-19.14-37-41.zip)

**Comment by IamPete1** [comment]
Sorry we never got to this, feel free to re-open if this issue still exists on 4.1
