### ISSUE TITLE
error happened when running make px4-v3 

### ISSUE THREAD

**Issue by Tenacity-soar** [ArduPilot/ardupilot#9481]
#### Issue details
_Please describe the problem, or desired feature_
 When i build my code use make px4-v3
a problem happen
/home/shangsuning/ardupilot/modules/PX4Firmware/makefiles/firmware.mk:519: recipe for target '/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.elf' failed
make[2]: *** [/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.elf] Error 1
make[2]: Leaving directory '/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build'
/home/shangsuning/ardupilot/modules/PX4Firmware/Makefile.make:143: recipe for target '/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.px4' failed
make[1]: *** [/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.px4] Error 2
make[1]: Leaving directory '/home/shangsuning/ardupilot'
../mk/px4_targets.mk:109: recipe for target 'px4-v3' failed
make: *** [px4-v3] Error 2
can you help me ? thanks

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[√] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
pixhawk
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by OXINARF** [comment]
There is no specific error there, surely you have more detailed messages above that. Also, make build system is deprecated, you should be using waf.

In any case, the issues list isn't the place to put questions.  For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).
