### ISSUE TITLE
EKF BUG: NavEKF3_core::getEkfControlLimits()

### ISSUE THREAD

**Issue by luweikxy** [ArduPilot/ardupilot#9484]
https://github.com/ArduPilot/ardupilot/blob/c02863e00176fdf3eff7cafcc04a216e0efc8b7d/libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp#L377
```
ekfGndSpdLimit = 400.0f; //return 80% of max filter speed
```

should this line be changed to :ekfGndSpdLimit = 4.0f; //return 80% of max filter speed ?
because the unit of ekfGndSpdLimit is m/s not cm/s

**Comment by peterbarker** [comment]
No, the filter limit really is 500m/s :-)
