### ISSUE TITLE
CLI automatic print_log_menu

### ISSUE THREAD

**Issue by rh-galaxy** [ArduPilot/ardupilot#949]
CLI->logs, does print_log_menu on enter and after dump

It is not a big issue, but is it necessary to do this? It takes quite long time (when there are many logs).
Maybe it would be better if it were done as a separate command, nothing else in the CLI is done automatically.

If it is changed it requires a change in MissionPlanner also, but I think it would be for the better.

**Comment by WickedShell** [comment]
CLI has been removed.
