### ISSUE TITLE
Issue connecting TELEM radio with GCS

### ISSUE THREAD

**Issue by gunnir** [ArduPilot/ardupilot#9494]
### Bug report

**Issue details**

When establishing a connection between the GCS and FC via 3DR Telemetry radio the communication is lost within 10 seconds systematically. Connection is established and during parameter load communication/connection is lost. Establishment can only be made again after re-flashing firmware, after which the connection will again be lost within 10 seconds.

Attached images of the issue in QGroundControl. Semi-loaded parameter values can be seen (indicated by green bar with 65% load status). If a manual connection is attempted error returned is "Resource Busy", because the auto connection is 'seemingly' active. Issue repeats on APM Planner and QGC, running FC in a minimum configuration, and on stable USB power supply. Issue is definitely not hardware related, and is related to ArduPilot build, as when flashing PX4 Pro firmware to the FC issue IS NOT present. Connection is stable and telemetry active; able to remotely alter parameters indefinitely on PX4 Pro...

**Version**
ArduPlane V3.9.1
Mac OS X Mojave 10.14 (Issue also present in 10.13.6 High Sierra and 10.12.3 El Capitan)
FTDI Driver 2.2.18
CP2102 USB to UART Bridge Controller V 1.00

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Any

**Hardware type**
Pixhawk PX4 2.4.8 Flight Controller
Powerday 3DR Wireless Telemetry Kit 433 MHz

**Logs**
None available - occurs during boot

Attached images of the load error, and the error when attempting to manually connect. Note, when 'auto-connection' in the GCS is turned off, no error is returned and no connection is established. The radios will always display 'solid green' indicating stable connection whenever this issue occurs.

![screen shot 2018-09-29 at 15 51 01](https://user-images.githubusercontent.com/22751061/46263453-62554b00-c507-11e8-9d6c-a62b3fc888c6.png)
<img width="666" alt="screenshot 2018-09-30 at 01 25 33" src="https://user-images.githubusercontent.com/22751061/46263454-62554b00-c507-11e8-97c9-cdfff6afc0e8.png">

**Comment by gunnir** [comment]
Found work around:

Changing SERIAL1_PROTOCOL to MAVLink2 has created a seemingly stable connection. Set back to MAVLink1 and disconnect occurring again within 10 seconds of first boot after fresh/clean flash of firmware. 

This certainly wasn't an issue on previous builds as have never needed to alter this property?

**Comment by peterbarker** [comment]
I'm thinking this must be fixed by now.  There's been a lot of bugfixes around mavlink1 and mavlink2 interop!

Please reopen if this is still a problem.
