### ISSUE TITLE
Copter: 3.6.0 issues list

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9498]
List of issues for the Copter-3.6.10 release:

- SBUS input not working when using converter board ([discussion](https://discuss.ardupilot.org/t/ac-3-6-10-and-error-reading-sbus/45468), [discussion2](https://discuss.ardupilot.org/t/copter-3-6-10-released/45367/14))
- omnibus pro v2 not working? ([discussion](https://discuss.ardupilot.org/t/copter-3-6-10-released/45367/26))
- Radiolink mini pix telem1, telem2 are swapped (again) ([discussion](https://discuss.ardupilot.org/t/copter-3-6-10-released/45367/17))
- Can't initialise AK09166 reset failed ([discussion](https://discuss.ardupilot.org/t/passthrough-telem-ak09166-reset-failed/45512), [issue](https://github.com/ArduPilot/ardupilot/issues/11935))
- One user's board locks up on boot-up

This is a list of issues to investigate for the Copter-3.6.0 release:

- Matek405-STD not built for stable ([issue](https://github.com/ArduPilot/ardupilot/issues/11292))
- Notch filter not working? ([discussion](https://discuss.ardupilot.org/t/notch-filter-not-working/40616))
- Loss of altitude control not caused by vibration ([discussion](https://discuss.ardupilot.org/t/uncontrolled-climb-after-auto-not-respond-to-land-or-rtl/39689/5))
- Copter not disarming reliably on landing ([discussion](https://discuss.ardupilot.org/t/why-quad-doesnt-want-to-disarm-after-landing-happened-two-times-now-arducopter-3-6-7/39568/21))
- Compass cal makes no noise when started from transmitter ([discussion](https://github.com/ArduPilot/ardupilot/issues/10093))
- lots of questions around rangefinders as alt source ([issue1](https://github.com/ArduPilot/ardupilot/issues/10598), [issue2](https://github.com/ArduPilot/ardupilot/issues/10586))
- external baro bm280 doesn't work on 3.6.6 (works on 3.7) [discussion](**https://discuss.ardupilot.org/t/copter-3-6-6-rc2-available-for-beta-testing/38330/16**).  unfortunately a bad wiki update led a user astray
- flowhold can lean past ANGLE_MAX ([issue](https://github.com/ArduPilot/ardupilot/issues/10524))
- Zubax GPS won't initialise on ChibiOS with normal power (works on USB). https://discuss.ardupilot.org/t/zubax-compass-wont-initialize-on-uavcan-via-onboard-power/38524
- Matek405-STD logging not working. https://discuss.ardupilot.org/t/copter-3-6-0-available-soft-release-for-2-days/34456/122
- parameters wiped with SD card becomes full? (https://discuss.ardupilot.org/t/problem-w-3-7-flash-logging-lost-parameters/37803/2)
- flowhold mode wobbles and jumps (https://discuss.ardupilot.org/t/3-6-4-flowhold-no-such-mode-cheerson-cx-of/37076)
- oneshot125 not working on Navio2 ([discussion](https://discuss.ardupilot.org/t/copter-3-6-4-oneshot125-not-enabled/37067), [discussion2](https://discuss.ardupilot.org/t/copter-3-6-10-released/45367/28))
- -v2 or fmuv2 being loaded (discussion here:https://discuss.ardupilot.org/t/3-6-4-flowhold-no-such-mode-cheerson-cx-of/37076)
- BLHeli passthrough not working.  See [Giorgio discussion here](https://discuss.ardupilot.org/t/copter-3-6-4-released/36749/5).
- PILOT_TKOFF_DZ not working. https://github.com/ArduPilot/ardupilot/issues/9969
- Twitch when switching from Loiter to Auto ([issue](https://github.com/ArduPilot/ardupilot/issues/10072))
- Dataflash log analysis tool needs updating ([issue](https://github.com/ArduPilot/ardupilot/issues/10094))
- UAVCAN external compass appearing as Compass2 ([issue](https://github.com/ArduPilot/ardupilot/issues/10095))
- set-home with 0,0,0 doesn't set home to current location (https://github.com/ArduPilot/ardupilot/issues/9725)
- can't upload terrain missions to boards with no SD card ([issue](https://github.com/ArduPilot/ardupilot/issues/9679), [discussion](https://discuss.ardupilot.org/t/terrain-following-with-spline-wp-on-omnibusnanov6-not-supported))
- "Initialising APM" message if using UAVCAN Zubax GPS.  https://github.com/ArduPilot/ardupilot/issues/9579
- Garmin Lidar Lite v3 offset issue: https://discuss.ardupilot.org/t/lidar-lite-v3-offset-value-issue/34793/13

ChibiOS specific issues:

- SUMD (Graupner RC protocol): https://github.com/ArduPilot/ardupilot/issues/10346
- cx-of not working on kakutef4 (https://discuss.ardupilot.org/t/copter-3-6-5-rc2-available-for-beta-testing/37391)
- mateksys F405 UART2/3 same?  see Gino Nencioni https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/31.  Cheerson CX-OF doesn't work on mateksys F405. https://discuss.ardupilot.org/t/cheerson-cx-of-low-cost-optical-flow-sensor-testing/35598/35

Also an issues in 3.5.7:

- System doesn’t start compass if sbus receiver is plugged in (happens in 3.5.7 too). see Corrado here: https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/63

Resolved I think:

- Pixhawk4-mini doesn't work with SBUS? ([discussion](https://discuss.ardupilot.org/t/pixhawk-4-mini-no-sbus-signal/38961)) (no feedback from user)
- Motor Test leading to disconnect of MP? ([discussion](https://discuss.ardupilot.org/t/copter-3-6-10-rc1-available-for-beta-testing/44531/22))
- CX-OF not working on ChibiOS boards. see Gino's report here: https://discuss.ardupilot.org/t/copter-3-6-6-rc2-available-for-beta-testing/38330/4 -- will be released with Copter-3.6.8
- Copter flips because Pixhack's 2nd IMU orientation is incorrect ([discussion](https://discuss.ardupilot.org/t/ekf-failsafe-change-imu-crash-with-flip/39709/11)) -- bad hardware it seems
- Matek405 Wing with [Beitian GPS/compass](https://www.banggood.com/UBLOX-NEO-M8N-BN-880-Flight-Control-GPS-Module-Dual-Module-Compass-p-971082.html) not booting.  https://discuss.ardupilot.org/t/copter-3-6-5-released/37733/10, report2: https://github.com/ArduPilot/ardupilot/issues/10448 -- fixed in 3.6.7
- Auto Land incorrectly sets target position ([issue](https://github.com/ArduPilot/ardupilot/issues/10617)) - fixed in 3.6.7
- check EKF switching in loiter (see Iron_Donkey's comments along with Randy's in this discussion: https://discuss.ardupilot.org/t/lidar-lite-v3-offset-value-issue/34793/25) -- serious EKF compass selection bug fixed in 3.6.6.
- BMP280 External Baro not working see MarcK's report here:https://discuss.ardupilot.org/t/copter-3-6-6-rc2-available-for-beta-testing/38330/5 -- works in master but not included 3.6 so wiki has been updated
- skipping first spline waypoint in SITL. https://github.com/ArduPilot/ardupilot/issues/9657 - resolved in Copter-3.6.6
- constant compass switching.  see andypiper and Corrado_Steri here: https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/64 - resolved in Copter-3.6.6
- MP is missing 3.6.3, 3.6.4 in previous firmwares list. https://github.com/ArduPilot/MissionPlanner/issues/2079
- Bad logging messages ([issue here](https://github.com/ArduPilot/ardupilot/issues/10124), discussion here: https://discuss.ardupilot.org/t/copter-3-6-0-available-soft-release-for-2-days/34456/98, https://discuss.ardupilot.org/t/prearm-logging-fail-3-6-2/35828) -- hopefully resolved in Copter-3.6.5
- dshot dma issue? https://discuss.ardupilot.org/t/need-help-to-analyze-a-crash-reason/34662/2 -- no follow up reports
- PWM output to ESCs not working 1 in 10 boots.  see Corrado_Steri here: https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/63 -- cannot reproduce
- RC decoding with DSM (https://discuss.ardupilot.org/t/rc-input-decoding-error/35855/3) -- cannot reproduce - interference issue?
- TS100 gps/compass detects QMC5883L compass that doesn't exist.  See Sergey https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/21.  Also again here: https://discuss.ardupilot.org/t/error-height/35467 -- fixed in 3.6.4?
- pixhawk4 voltage meter doesn't work: https://discuss.ardupilot.org/t/pixhawk-4-power-module-readings-not-working/35149 -- fixed in 3.6.4
- OSD not working on MatekF405-CTR. https://discuss.ardupilot.org/t/osd-does-not-work/35470 -- fixed in 3.6.3
- pixhawk4 rc inputs go crazy: https://discuss.ardupilot.org/t/cumulation-of-crashes-due-to-seemingly-weird-input-pixhawk-4/35537/4 -- fixed in 3.6.3
- tradheli defaults changed for ACCEL_Z. discussion: https://discuss.ardupilot.org/t/copter-3-6-1-released/34969/27 -- fixed in master, will go out with 3.6.3
- stable MP doesn't support installing 3.5.7
- Matek 405CTR telemetry not working? see Jonathan_Blumenfeld here: https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/48 -- stream rates were set to 0 (why didn't the GCS set them is unclear -- perhaps user was not using a GCS)
- MiniPix the display SSD1306 blocks the telemetry on the usb port making it impossible to communicate with the FC  (see Gino_Nencioni discussion here: https://discuss.ardupilot.org/t/copter-3-6-1-released/34969/10) -- cannot reproduce, no answer from user when requested params.
- another dshot issue? https://github.com/ArduPilot/ardupilot/issues/9738, https://discuss.ardupilot.org/t/copter-3-6-1-released/34969/13 -- config issue according to tridge
- MP doesn't allow downgrades ([MP issue](https://github.com/ArduPilot/MissionPlanner/issues/1977)) -- fixed in latest beta
- Disabled Safety Switch is sometimes preventing arming https://discuss.ardupilot.org/t/copter-3-6-0-doesnt-obey-brd-safetyenable-0-some-times/34623 -- fixed in 3.6.1-rc1
- minimOSD showing Alt-above-sealevel: https://discuss.ardupilot.org/t/altitude-in-minimosd-relative-to-sea-level/34665/6 -- fixed in 3.6.1-rc1
- 3.5.7's FS_BATT_VOLT isn't being copied over to BATT_LOW_VOLT -- fixed in 3.6.1-rc1
- mavlink update rate slower than 3.5.7? see kknet here: https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/84 -- it's a bit slower with NuttX but faster with ChibiOS
- arming failure tone not played.  see brandon macdougall here: https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/60 -- cannot reproduce
- "PreArm: Hardware Safety Switch" should only be displayed on MP HUD if there are not other pre-arm failures (this could possibly be fixed by changing the order in which we send these messages).  see rickyg32 here: https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/73
- simple mode always starts on?  see Paul Atkin https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/4 -- cannot reproduce
- Pixhawk4 can't save parameters: https://discuss.ardupilot.org/t/parameter-writing-issue-arducopter-v3-6-0-rc10-on-a-pixhawk-4/33221 -- cannot reproduce.
- PixhackV3 - 3rd compass not found. Varun Nelakanti: https://discuss.ardupilot.org/t/copter-3-6-0-rc8-available-for-beta-testing/32374/37

Resolved / removed as 3.6.0 release requirement:

- flowhold won't descend: https://discuss.ardupilot.org/t/flow-hold-wont-descend/34105/3 -- fixed in 3.6.0
- kakutef7 hwdef incorrect?  See Paul Atkin. https://discuss.ardupilot.org/t/copter-3-6-0-rc12-available-for-beta-testing/33718/47 -- fixed in 3.6.0
- Maxbotix I2C sonar freeze. https://github.com/ArduPilot/ardupilot/issues/9602 -- fixed in 3.6.0
- pixracer LED shows incorrect colours: https://discuss.ardupilot.org/t/pixracer-onboard-led-is-messed-up/28493/3 -- fixed and will be included in official release
- DShot causes Cube to freeze up after 10sec. Daniel_Met: https://discuss.ardupilot.org/t/copter-3-6-0-rc10-available-for-beta-testing/33057/10 -- will be released with -rc12
- LidarLight3 using PWM not working.  See FRED_GOEDDERT: https://discuss.ardupilot.org/t/copter-3-6-0-rc10-available-for-beta-testing/33057/12  -- not yet supported in ChibiOS (known issue)
- PixhackV3 - can't do fast sampling.  Roland Mayer: https://discuss.ardupilot.org/t/copter-3-6-0-rc8-available-for-beta-testing/32374/37 -- Pixhack uses MPU6000 that can't do fast sampling
- Sergey: safety button not working on Pixracer: https://discuss.ardupilot.org/t/copter-3-6-0-rc11-available-for-beta-testing/33558/3 -- fixed in -rc12
- gazebo not working with SITL. https://discuss.ardupilot.org/t/arducopter-3-6-sitl-with-gazebo-unstable-flight/34451 -- solved, it was due to performance issue with gazebo.

**Comment by eovnu87435ds** [comment]
Is there a discussion for the "One user's board locks up on boot-up" issue?

**Comment by rmackay9** [comment]
@eovnu87435ds, I had a look around a bit but I couldn't find the discussion... i'm pretty sure it was a one-off but feel free to raise a new discussion if you're seeing something similar.

**Comment by okntrkr** [comment]
https://hizliresim.com/Nb91s2
2 elements marked in the picture in the link are faulty. what can I do ?

**Comment by peterbarker** [comment]
@rmackay9 are we OK to close this?

**Comment by WickedShell** [comment]
I'm going to just go ahead and close this now, as there hasn't been any response from @rmackay9 about closing this. If this is wrong and we want to keep it open, but we are well and truly past 3.6 now, so I think this is stale. If you disagree @rmackay9 please reopen it :)
