### ISSUE TITLE
VTOL-Tilt QHover loss of altitude and not responding to commands in Q_Hover

### ISSUE THREAD

**Issue by IsaacMG91** [ArduPilot/ardupilot#9516]
Issue details
Today I've been testing my plane (VTOL quad tiltrotor with only the two front motors tilting). The first flight has been successful so far, but in the second, I encountered a problem when doing back transition. 

When switching to Q_Hover, the plane slowly stopped and started to descend, despite the commands to keep altitude and even climb.

This is something I have noticed before, but now I have to flights with same setup and conditions, and the issue only appeared in the second. 

This are the motor outputs and the QTUN.THRout for the first flight (only the land transition)
![image](https://user-images.githubusercontent.com/17983046/46476503-a63a9f80-c7e8-11e8-8f45-c3350cd2f469.png)

And this is in the second flight.
![image](https://user-images.githubusercontent.com/17983046/46477734-9d979880-c7eb-11e8-94da-a84853ced1fd.png)

The throttle output seems to be clamped to a fix value in the second flight, not responding to commands.

Version
3.8.5

Platform
[ ] All
[ ] AntennaTracker
[ ] Copter
[X] Plane
[ ] Rover

Airframe type
Quad Tiltrotor VTOL

Hardware type
 Pixhawk 2.1

Logs

first flight - https://drive.google.com/open?id=1l4WwEzhiZCviEUZko6aIwbfl3Dc6KmKa

second flight - https://drive.google.com/open?id=1nBon-XPu5GoM49f3P0FHlVy9flSY8HtV

**Comment by IamPete1** [comment]
sorry we never got to this, I'm going to close, but if your still having the issue on 4.0.8 feel free to re-open or post over on the forum.
