### ISSUE TITLE
Dead link on https://github.com/ArduPilot/ardupilot in README.md file

### ISSUE THREAD

**Issue by 7princekumar** [ArduPilot/ardupilot#9522]
#### Issue details (Documentation issue)
A link to [guidelines for contributors to the ardupilot codebase](
http://dev.ardupilot.org/wiki/guidelines-for-contributors-to-the-apm-codebase) present in the README.md file on 
`https://github.com/ArduPilot/ardupilot` is dead. 

_Image:_
![alt text](https://i.imgur.com/48p9LBm.png)

**Comment by 7princekumar** [comment]
I would like to fix this issue. Please assign me this.

**Comment by khancyr** [comment]
Patch merged ! closing . Thanks
