### ISSUE TITLE
Controlling a collective pitch Quadcopter with pixhawk v2

### ISSUE THREAD

**Issue by maxdrougge** [ArduPilot/ardupilot#9530]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REQUEST WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please do a careful search before opening this, there are already a lot of feature requests**_
If there was a previous discussion in the forum, link to it

### Feature request

**Is your feature request related to a problem? Please describe.**
I'm wondering if there is plans to add software to control a collective pitch quadcopter such as the Assault Reaper 500? 

**Describe the solution you'd like**
I'd like software support to control a collective pitch quadcopter such as the Assault Reaper 500. If there already is a way to do it, I would like to know how.

**Describe alternatives you've considered**
If there is a way to already do it with the existing softwares. 

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

**Comment by auturgy** [comment]
Please use the forum for user support: discuss.ardupilot.org
The wiki is also a great place to find answers to many questions. http://ardupilot.org/copter/docs/heliquads.html
