### ISSUE TITLE
SITL aircraft does not start when used with Gazebo

### ISSUE THREAD

**Issue by jonathan84clark** [ArduPilot/ardupilot#9531]
When I launch the SITL simulation with the following command
`sim_vehicle.py -j4 -w -L KSFO -v ArduCopter --console --map`
The Aircraft is created and I am able to see data from it and connect to it with QGC.

However when I add the Gazebo parameter (to visualize my simulator) with this command:
`sim_vehicle.py -j4 -w -L KSFO -v ArduCopter -f gazebo-iris --console --map`
The last message I see is this:
`MAV> Waiting for heartbeat from tcp:127.0.0.1:5760`

And I don't get any more data from the Simulated copter
After this step is complete I launched Gazebo (using the gazebo command) just incase the simulator was depending on the 3D visualizer in some way. The Gazebo GUI came up but did not show a 3D model of my aircraft and the console showed no connection or data from the simulated drone.

I am following the instructions on:
http://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html
I have also been exploring the forums to see if anyone else has had similar issues. One person fixed this by removing and re-installing Gazebo; this had no effect when I tried it.

Any help would be great!

Thanks,

Jonathan L Clark

**Comment by umer936** [comment]
I believe you need gazebo running to connect to. You need to run the two commands, from the doc page you linked: 
`cd ~/ardupilot/ArduCopter
sim_vehicle.py -f gazebo-iris -D --console --map`
and in another terminal: 
`cd ~/gazebo_ws 
gazebo --verbose worlds/iris_arducopter_demo.world` 

Please paste the gazebo terminal's output. I suspect gazebo is looking in the wrong folder for the iris_*.world file. 

My organization does it a little differently, but these instructions might be helpful: https://github.com/Texas-Aerial-Robotics/Mission8_OutOfControls

**Comment by jonathan84clark** [comment]
@umer936 
Thanks for the info. That worked!
