### ISSUE TITLE
ChibiOS:  need sensors reset feature.

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#9570]
### Feature request

there is no sensors reset feature for chibios systerm,
nuttx systerm imple....
if (px4_start_driver(fmu_main, "fmu", "sensor_reset 20")) 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Platform**
[*] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**

**Comment by IamPete1** [comment]
Do we need one? What is the use case?

**Comment by IamPete1** [comment]
Please re-open if your still interested in this.
