### ISSUE TITLE
Autotest: Add test badges to README 

### ISSUE THREAD

**Issue by Williangalvani** [ArduPilot/ardupilot#9589]
Since the autotest is too slow to run on every pull request, why not show it at least on the Readme page? It is important that it shows somewhere else than at http://autotest.ardupilot.org/, so people at least know when something is broken without going there.

As there are 26 tests right now, I propose we either group them all into something like ![](https://img.shields.io/badge/Autotest-22%2F26-orange.svg) 
Or group by vehicles/task
![](https://img.shields.io/badge/Plane-4%2F4-green.svg)  ![](https://img.shields.io/badge/sub-1%2F2-orange.svg)  ![](https://img.shields.io/badge/copter-3%2F4-orange.svg)

Any thoughts?

**Comment by umer936** [comment]
I like this idea! Did you want to make a PR or can I?

**Comment by Williangalvani** [comment]
I haven't done anything, feel free to do it!
