### ISSUE TITLE
AP_Rangefinder: Type = 2 (MaxbotixI2C) while sensor absent causes board to crash beyond recovery

### ISSUE THREAD

**Issue by vierfuffzig** [ArduPilot/ardupilot#9602]
**Issue details**
This has been reported by @rain-er in chibios gitter. setting RNGFND_TYPE=2 (MaxbotixI2C) without a sensor being actually found or connected causes a board hang on boot that can't be recovered from unless reflashed with fulll param erase. there's no console output in crashed state. 
setting other RNGFND types does allow to boot correctly with console prompt about the sensor not being found if not present.

**Version**/ **Platform**
verified on current chibios copter / plane builds (latest and beta)

**Hardware type**
verified on various chibios-only-type boards (omnibusV6nano, omnibusf4pro, revomini, F35Lightning)

**Logs**
not possible

Basti.

**Comment by rmackay9** [comment]
I've tried to replicate this but wasn't able to using Copter-3.6.0-rc12 and Copter-3.7-dev on a Pixhawk1 nor Mateksys 405-wing.  Perhaps we need someone else to confirm it's an issue on some of the other boards.
