### ISSUE TITLE
All: onboard files support

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#9620]
### Feature request
I think we should implement an onboard file storage feature so that users can store the files they want, such as a separate camera file. This allows for a greater degree of use of the SD card for more functionality. These files can be easily uploaded/downloaded/deleted via digital transmission or usb cable.
![image](https://user-images.githubusercontent.com/16251761/47402863-e18e1580-d779-11e8-9355-c1984477fd9b.png)

**Describe the solution you'd like**
 upload/download/delete files to/from Ardupilot via digital transmission or usb cable.

**Platform**
[*] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by WickedShell** [comment]
Duplicates the actual feature requested in #7914
