### ISSUE TITLE
EKF2/EKF3: fix replay

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9624]
Although I'm not a big user of EKF's reply, my understanding is that it has been broken somehow.

[Replay is described here on the developer wiki](http://ardupilot.org/dev/docs/testing-with-replay.html).

**Comment by huangwen0907** [comment]
@rmackay9 Yes, the Ardupilot's EKF replay function is broken for a long time, I am very appreciate that you can fix it. It is really helpful. THX

**Comment by peterbarker** [comment]
On Thu, 25 Oct 2018, Abner Huang wrote:

> @rmackay9 Yes, the Ardupilot's EKF replay function is broken for a long
> time, I am very appreciate that you can fix it. It is really helpful. THX

What's broken about it?

Currently Working For Me(tm) on master.

**Comment by peterbarker** [comment]
@huangwen0907 Are you able to share that logfile?

**Comment by peterbarker** [comment]
@huangwen0907 FWIW, I think that logfile may be corrupt; it is probably missing the FMT entry for whatever message number 204 is.

**Comment by huangwen0907** [comment]
@peterbarker  This is the log maybe [repaly log]( https://github.com/huangwen0907/File/blob/master/log/log_2_2018-7-10-18-16-14_replay.bin)

**Comment by peterbarker** [comment]
@huangwen0907 OK, thanks, I've reproduced and will have a look.

**Comment by huangwen0907** [comment]
any updates?

**Comment by peterbarker** [comment]
@huangwen0907 Actually, I realised this is a bug I've already fixed.  I'm preparing a PR.

**Comment by peterbarker** [comment]
https://github.com/ArduPilot/ardupilot/pull/9660

Now this seems to complete successfully - generating a valid logfile - but I have not actually looked at the content of that logfile (apart from making sure the NKF messages appear to be present.

I'd appreciate you testing that PR and seeing if it makes sense to you.

**Comment by huangwen0907** [comment]
#9660 
I have tested the branch #9660 you posted, now my replay function can work as desired. thank you very much.

**Comment by peterbarker** [comment]
Fixed.  Thanks for testing, @huangwen0907 !
