### ISSUE TITLE
AntennaTracker: yaw oscillates back and forth

### ISSUE THREAD

**Issue by Habitatea** [ArduPilot/ardupilot#963]
![tracker](https://cloud.githubusercontent.com/assets/3514421/2662128/91cd7f3a-c037-11e3-9096-b90c94a5edef.jpg)
I installed ardutracker on APM2.0 with external GPS, pitch axis seem work fine, but yaw axis oscillate over all range of this servo, forever. I've connected tx pin on APM to rx pin on 3dr telemetry module. 
I don't know if I've something wrong on my setup or it's a bug.
I'd like find more info about ardutraker.

**Comment by SCUBA82** [comment]
What kind of servos are you using?
I'm using on/off servos and had the same issue. The reason for the oscillation was that my servos forgot about their trim/neutral value.
When the APM sends the "neutral value" to stop the servo, the servo moves on and so the APM has to turn back to get to the desired position -> and so on and on... 
After recalibrating the neutral position of my servos the oscillations stoped ... but my servos still lose their neutral position from time to time.
I think I'm going to replace the pontentionmeter of my servo with resistors. So the neutral value should not change anymore...

**Comment by rmackay9** [comment]
I wonder if we can close this issue..?

**Comment by tpascaru** [comment]
I've noticed similar results on my setup. We have some PWM motors with rather large dead zones. I have specified the dead zones in RC1_DZ and RC2_DZ, but cannot see it make any difference. I have an oscilloscope connected to the RC outputs, and see them sweep through the dead zone. If the PID controller does not "know" about the dead zones, it will continuously try to increase (or decrease the PWM) possibly accelerating such adjustments if the "I" term is greater than 0. I am trying to go through the code to see if the Dead Zone is accounted for in the control loop, but as of yet cannot determine. If it's not, that might explain the oscillations.

**Comment by OXINARF** [comment]
Is this still valid?

**Comment by Naterater** [comment]
There has been no response to @OXINARF's question, so closing.

**Comment by anti-vaxxer** [comment]
> Is this still valid?

@OXINARF @Naterater  I believe it's still valid, for when using continuous rotation servos.
as @tpascaru mentioned above, there does not seem to be any parameter to specify Dead Zone for a continuous rotation servo. So the autopilot does not know at what point the servo will start moving.

For example, when the tracker points about 20degrees away from target I can see the yaw PWM change by small amounts which are not enough to rotate the servo, and it does this indefinitely and never rotates toward the target.
My continuous rotation servo seems to have about 200us dead band where it doesn’t have enough torque to rotate the tracker.
There should be an option to set servo dead zone but it doesn’t seem to exist.

This seems to be a major overlooked issue which makes the AntennaTracker not able to properly use continuous rotation servos, unless I'm missing something here?
