### ISSUE TITLE
Can AUTO_ROT parameter change the length of mag_cal_report message packet?

### ISSUE THREAD

**Issue by whiani** [ArduPilot/ardupilot#9635]
Hi I am using Mission Planner 1.3.56 build 1.3.6672.30243 ArduPlane 3.9.2beta3(32c5e6b).
The compass calibration screen is not reporting success once calibration completes. Instead the green bars stay at 99% ,but the compass calibration is successful when i set AUTO_ROT to 0(default is 2).
I have begun to think the same as Michael Oborne , the new extension fields of  the missionplanner are not being set.
however i set AUTO_ROT(default is 2) to 0 ,the new extension fields are also sent,the compass calibration is successful.
so can AUTO_ROT parameter change the length of mag_cal_report message packet?I didn't see that.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[*] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Sorry we never got to this, lots of compass changes in both AP and MP so I suspect it has been fixed.
