### ISSUE TITLE
Copter: DroneKit's condition-yaw does not turn vehicle clockwise

### ISSUE THREAD

**Issue by kane111** [ArduPilot/ardupilot#9648]
### Bug report

**Version**
_What version was the issue encountered with_
Arducopter-3.5.7

**Platform**
[  ] All
[  ] AntennaTracker
[o] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
COPTER

Problem

The command MAV_CMD_CONDITION_YAW does not work clockwise in actual flight. Whereas in SITL it works fine for both directions. We are using the latest dronekit built from source.

**Comment by amilcarlucas** [comment]
Almost one year without response ...

**Comment by OXINARF** [comment]
Closing due to no log and no answer.
