### ISSUE TITLE
RangeFinder: Benewake TFMini and TF02 show distances around 655.34 meters

### ISSUE THREAD

**Issue by nikan8** [ArduPilot/ardupilot#9652]
For some reason, Benewake TFMini sensor reports strange values as displayed by sonarrange variable in Mission planner (this has been tested both on FMUv2 and FMUv5). When the sensor switches to long range mode, sonarrange value jumps to about 650 meters. Is there an easy fix for this? Thanks.

**Comment by rmackay9** [comment]
yes, the issue is that when the lidar is unable to get a distance it returns a values around 65535 (i.e. -1).  We need to add handling for this in the driver..

**Comment by rmackay9** [comment]
I'm hoping to fix this for Copter-3.6.1.

**Comment by nikan8** [comment]
Thank you, However, the issue is that when I read the sensor info using TFMini software as well as in PX4 (QGC) I'm able to get a distance estimate. Perhaps, reliability threshold is set too high in Ardupilot tfmini driver? (approximate distance measure when jump to 655 occurs is at approx. 2meters).

**Comment by nikan8** [comment]
could this change be backported to arduplane 3.9.2?
