### ISSUE TITLE
Copter-3.6.0: skips 1st spline waypoint in SITL

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9657]
in SITL at least (and perhaps in a real vehicle although this hasn't been seen yet), the first Spline waypoint in a mission may be skipped.  To recreate the problem:

1. start master or Copter-3.6 branch in SITL
2. create a mission like below with a takeoff, a spline waypoint and a return-to-launch command
![wp-spline-issues](https://user-images.githubusercontent.com/1498098/47700516-1c042080-dc5a-11e8-9c2c-3d3f99b5a5ae.png)
3. type LOITER to switch to Loiter mode
4. arm throttle (to arm the vehicle)
5. rc 3 1100 (to raise throttle slightly)

you should see that the vehicle climbs to takeoff altitude, the first spline waypoint command completes immediately and the vehicle begins the 2nd spline command.

This issue does not happen in Copter-3.5.7.

The issue appears related to [this commit](https://github.com/ArduPilot/ardupilot/commit/e49d29f8cdcf0467e4dbeeca1d9ce906f8315d61).

**Comment by arjun7965** [comment]
This seems to even happen when spline is the first waypoint after LOITER_TIME. Just recreated this in SITL with:
![image](https://user-images.githubusercontent.com/15646612/47749741-26c3b300-dc64-11e8-9cff-c2515fd8e8f6.png)

**Comment by SwiftGust** [comment]
I think not just the commit the link @rmackay9 pointed, also spline time got issue too.
This is SITL - Gazebo result with spline waypoint, it's not only skipping WP 2, also determines very earlier before reaching other WPs 
Note WP6 is just straight WP, other WPs are spline
![spline issue](https://user-images.githubusercontent.com/13569579/48037286-e5c12680-e1ae-11e8-8a16-b2ff15d2c204.png)

**Comment by SwiftGust** [comment]
@rmackay9 I made PR for the possible solution of this issue https://github.com/ArduPilot/ardupilot/pull/9710

**Comment by rmackay9** [comment]
This is fixed in master and released with Copter-3.6.6.
