### ISSUE TITLE
Rover: always creates log file on each reboot even if LOG_DISARMED = 0 and not armed

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9662]
The title says it all but I've noticed that with Rover-3.5.0-dev each time I reboot the flight controller another log file appears in the Log download list even if the vehicle hasn't been armed.

**Comment by peterbarker** [comment]
On Tue, 30 Oct 2018, Randy Mackay wrote:

> The title says it all but I've noticed that with Rover-3.5.0-dev each time I
> reboot the flight controller another log file appears in the Log download
> list even if the vehicle hasn't been armed.

What's ARMING_REQUIRE?

**Comment by IamPete1** [comment]
I cant replicate this in SITL with defaults, if `ARMING_REQUIRE` = 0 then I think its expected.

**Comment by IamPete1** [comment]
Please re-open if this is still a issue.
