### ISSUE TITLE
Rover: move sailboat functions into a sailboat class

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9673]
The sailboat support is implemented functionally with all the new sailboat features inside of functions starting with sailboat_ (see sailboat.cpp).  We should move all of these into a class and that class should probably also contain the sailboat specific parameters.

This would also allow us to create an SAIL_ENABLE parameter that hides sailboat parameters from view for non-sailboat users.

**Comment by IamPete1** [comment]
done
