### ISSUE TITLE
LED lights fix for Pixhawk4 (FMUv5)

### ISSUE THREAD

**Issue by nikan8** [ArduPilot/ardupilot#9708]
Though a rather minor issue, the auxiliary LEDs on Pixhawk4 board are not on (FMU pwr, b/e, act.). Could this be fixed / backported to stable arduplane release? Thank you.

**Platform**

[X] Plane (master)

**Comment by nikan8** [comment]
Did anyone have a chance to fix the issue?
many thanks.

**Comment by bys1123** [comment]
Pixhawk 4 Mini also heve this problem
