### ISSUE TITLE
DO_SET_HOME handling should set home to current location if lat,lng,alt area all zero

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9725]
In Copter-3.5 we would set the home location to the current location if param1 = 1 OR lat, lon and alt were all zero.  In 3.6 it seems we only support setting home using param1.

I think either should be acceptable ways to set home to the current location.  Accepting 0,0,0 as the current location is something we do in a number of other places.

This was first discussed [here in this Copter-3.6 thread](https://discuss.ardupilot.org/t/sethome-stopped-working/34755).

**Comment by peterbarker** [comment]
236056ffbd321dea7377d2c012d5f19d56516a1b made us treat (0,0,x) as "here" for arbitrary values for x.  x is ignored.
