### ISSUE TITLE
Dshot 150 Bootup problem 

### ISSUE THREAD

**Issue by margus12** [ArduPilot/ardupilot#9738]
**IF YOU DON'T REMOVE THESE FOUR LINES, THEN YOUR REPORT WILL BE CLOSED AUTOMATICALLY**
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

### Bug report

Dshot 150 Bootup

**Issue details**

Bootup the ESC booting into multishot state not dshot

_Please describe the problem_

On bootup some of the ESC 10/1 dosen’t boot into Dshot state.
If i open blheli suite i can see that one or more ESC are in Multishot state.
And if i try to take off it of course flips over.

The telem. also isn’t coming from the ESC.

**Version**
FW3.6 ''soft'' release 
Pixhawk 2.1 Cube
Using Dshot 150
ESC Rev. 32.6

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X

**Hardware type**

Pixhawk 2.1 

**Logs**

![blheli](https://user-images.githubusercontent.com/23522878/48255873-9ed56a00-e416-11e8-8d0f-6268319cd51e.JPG)
![esc missing](https://user-images.githubusercontent.com/23522878/48255875-9ed56a00-e416-11e8-9843-9bd220959069.JPG)
![esc_tel](https://user-images.githubusercontent.com/23522878/48255877-9f6e0080-e416-11e8-9276-1f1d9b86cbb9.JPG)
![param](https://user-images.githubusercontent.com/23522878/48255878-9f6e0080-e416-11e8-873a-22fbb1602de2.JPG)

**Comment by rmackay9** [comment]
Thanks for the report.  I think it's best if we keep the 3.6 support calls in the [support forums here](https://discuss.ardupilot.org/c/arducopter/copter-36).  So I'll close this if that's OK.  Not saying there isn't an issue just that if we don't keep the support calls in the support forums our to-do list just turns into another support forum.  thanks for using AP!
