### ISSUE TITLE
Bug: DataFlash logging for AP_BattMonitor incomplete for charge (mAh)

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/ardupilot#9748]
The logging of consumed charge (mah, curr_tot,...) done here
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BattMonitor/AP_BattMonitor.cpp#L226-L244
is incomplete/flawed. The charge is logged as battery.consumed_mah(battery_instance), i.e. in units of mAh, while CURR_UNITS as well as CURR_MULTS hold '?'.
See
https://github.com/ArduPilot/ardupilot/blob/master/libraries/DataFlash/LogFile.cpp#L1397-L1416
and
https://github.com/ArduPilot/ardupilot/blob/master/libraries/DataFlash/LogStructure.h#L1138-L1141
and
https://github.com/ArduPilot/ardupilot/blob/master/libraries/DataFlash/LogStructure.h#L80-L94

One could use the already available unit { 'i', "A.s" } and conversion { '!', 3.6 }, and correct the CURR_UNITS field and the CURR_MULTS accordingly (or one could introduce a new unit mAh, and adapt CURR_UNITS accordingly which would be more user friendly but I guess you want SI).

Additional comment: The comments 
// (ampere * second => milliampere * hour) and (km/h => m/s)
// (ampere * second => ampere * hour)
are somewhat misleading, since they convert the other way around, i.e., e.g., from milliampere * hour to ampere * second.

EDIT: A similar comment holds for ESC_UNITS and ESC_MULTS, which have a '-' for CTot, while AP_BLHeli logs the consumption as mAh. So, here the logged data is not in SI but mAh, and the unit is missing too. Again, could be corrected with 'i' and '!'.

**Comment by peterbarker** [comment]
@amilcarlucas Thoughts?

**Comment by rmackay9** [comment]
This is probably more for @WickedShell isn't it?

**Comment by ongspxm** [comment]
is this still required? I would want to try to work on this, I traced it to `libraries/AP_BattMonitor` and `libraries/AP_Logger`, am I on the right track?

**Comment by peterbarker** [comment]
@amilcarlucas SI units only.  display things are what tools are for.

**Comment by amilcarlucas** [comment]
Easier to debug, I guess. But yes, SI makes sense.

**Comment by IamPete1** [comment]
We now log in ah, https://github.com/ArduPilot/ardupilot/pull/17652 so I think this can be closed.
