### ISSUE TITLE
Wrong Direction from the F405-STD MCU

### ISSUE THREAD

**Issue by Flying-Pit** [ArduPilot/ardupilot#9750]
### Bug report

**Issue details**
The MCU at the F405-STD is not mounted at the same Direction as the F405-WING

If u want use the F405-STD and write the Arduplane Firmware for F405 at the Board, the Flight-Direction its turned 90degr. It means, if u go Nose down with the FC, at the HUD the Horizont go´s left, the FC gos right.
In the ardware.dat the i thing the INS-ROTATION must be not 180degr, it must be 90degr.
**Version**
F405-STD with last stable Arduplane with_bl.hex
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

**Hardware type**
F405-STD
**Logs**
![f405-mcu](https://user-images.githubusercontent.com/44920818/48300323-69df1b00-e4db-11e8-87f2-4a27ab8e95f5.JPG)

**Comment by vierfuffzig** [comment]
thanks @Flying-Pit for reporting and testing. this will fix default INS rotation on board versions with ICM20602: https://github.com/ArduPilot/ardupilot/pull/9751

cheers, basti.

**Comment by vierfuffzig** [comment]
while other board flavors likely need respective testing and feedback too, imho this can be closed with regard to the STD board type.

basti.
