### ISSUE TITLE
LED driver TCA62724FMG stop production

### ISSUE THREAD

**Issue by jamming** [ArduPilot/ardupilot#9771]
TOSHIBA LED driver TCA62724FMG stop production right now. I2C controlled RGB LED driver NCP5623BMUTBG of Onsemi is good substitute for TCA62724FMG. NCP5623BMUTBG is easy to buy. So it's a good idea to change the drivers to support it.
Basic RGB appliation of NCP5623BMUTBG can be seen in the following link.
'https://github.com/jamming/image/blob/master/NCP5623B-LED-driver.png

**Comment by WickedShell** [comment]
We already have support for NCP5623. https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Notify/NCP5623.cpp
