### ISSUE TITLE
RangeFinder: add support for VL53L1X

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9776]
This enhancement request is to add support for the low-cost 4m range ST VL53L1X lidar. This can be found from various retailers including [sparkfun](https://www.sparkfun.com/products/14722)

**Comment by muramura** [comment]
https://www.pololu.com/product/3415/specs
I know Pololu's device.

**Comment by nghiajenius-dev** [comment]
Hi,

I wrote a driver for this sensor to use it with my 250mm quadcopter, based on Pololu code: [(https://github.com/pololu/vl53l1x-arduino)]. I will do some clean up and make a PR this weekend.

**Comment by nghiajenius-dev** [comment]
Hi @rmackay9,
I have just made a PR for this sensor here: https://github.com/ArduPilot/ardupilot/pull/9845

**Comment by avncalst** [comment]
I have included the VL53L1X ToF in a python-dronekit script on the RPi3 companion computer of my drone. The script also includes artificial intelligence proximity sensing. Code to be found on GitHub https://github.com/avncalst/drone_cnn. Works great.

**Comment by chobitsfan** [comment]
I have fly current master (#9845 merged) with katute f7 aio and vl53l1x. Rangefinder reading looks good when copter is disarmed and I hold the copter to move it up and down. But in real flight, ardupilot stop get reading after copter climbing up to 0.5m. 

![vl53l1x](https://user-images.githubusercontent.com/19793511/58306846-7ac7fc00-7e2f-11e9-8b0a-775f6d4e7377.jpg)

[vl53l1x_flight_log.zip](https://github.com/ArduPilot/ardupilot/files/3215402/vl53l1x_flight_log.zip)

**Comment by chobitsfan** [comment]
After remove black soft pads on the floor, everything works fine.  It seems that the material and black color absorbed laser from vl53l1x.

hi @rmackay9 I have tested it on katute f7 on a Tarot 140 FPV frame. It fly well indoor in althold mode.

**Comment by OXINARF** [comment]
This is supported since #9845 was merged. Thanks to @nghiajenius-dev!
