### ISSUE TITLE
Vehicle slows down more than the speed set via DO_CHANGE_SPEED command

### ISSUE THREAD

**Issue by jdzerve** [ArduPilot/ardupilot#9781]
### Bug report

**Issue details**
The attached mission file contains a route with 3 waypoints.
There is a command to change speed to 10m/s after first WP.
After second WP DO_CHANGE_SPEED command sets the speed to 5m/s

Expected behavior is that vehicle flies at 10m/s towards the 2nd WP and then slows down to 5m/s and continues at 5m/s.

The actual behavior is that vehicle slows down to ~3.4/ms at the 2nd WP which is much less than the expected 5m/s and then accelerates up to 5m/s towards the third WP reaching 5m/s only at the middle of the segment.

If I set the WP speeds to 20 and 10 m/s respectively then vehicle slows down to ~7.4m/s at the second WP.

This has been verified with both SITL and with Pixhawk on real vehicle.

Is this by design or there is a way to fix it?
Thanks.

**Version**
ArduCopter V3.7.0-dev (85243ad5)
The behavior is the same also in earlier ardupilot versions (3.4.6)

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
Pixhawk2 and SITL

**Logs**
Here is the mission dump used to test this case.
QGC WPL 110
0	1	3	179	0	0	0	0	-35.363361	149.16528	585.01147	1
1	0	3	22	0	0	0	0	-35.363361	149.16528	20.92713	1
2	0	3	16	0	2	0	0	-35.363361	149.16528	20.92713	1
3	0	3	178	10.000001	10.000001	-1	0	0	0	0	1
4	0	3	82	0	2	0	0	-35.362579	149.16518	19.351263	1
5	0	3	178	5.0000005	5.0000005	-1	0	0	0	0	1
6	0	3	82	0	2	0	0	-35.362179	149.16507	17.895758	1

**Comment by IamPete1** [comment]
I cant replicate on master, I suspect this has been fixed by the move to SCurves.
