### ISSUE TITLE
Sub: SERVO_OUTPUT_RAW > 8 are not available via mavlink

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9799]
Moved from: bluerobotics/ardusub#113
Original author: @jaxxzer

### Feature request
Setting serial protocol to mavlink 2 does not change anything here.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by WickedShell** [comment]
This is now common code to all vehicles, and seems to be working on all vehicles. @patrickelectric @jaxxzer can you guys confirm that this is still an issue for you? It got moved up in #8345 and I believe this can be closed now.

**Comment by jaxxzer** [comment]
@WickedShell Thanks for the heads up, confirmed
