### ISSUE TITLE
Sub: Add support for TSYS01 on pixhawk 2

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9800]
Moved from: bluerobotics/ardusub#97
Original author: @jaxxzer

### Feature request
The bus is hard coded, it needs to be determined at run time.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by jaxxzer** [comment]
https://github.com/ArduPilot/ardupilot/blob/master/ArduSub/system.cpp#L41
