### ISSUE TITLE
Sub: There is a step input when setting input hold

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9801]
Moved from: bluerobotics/ardusub#165
Original author: @jaxxzer

### Feature request
In the moment that input hold is engaged, any stick displacement from center is additive to where the input hold target is. That means that if the stick is displaced and input hold is subsequently engaged, the input instantly doubles until the stick returns to center (and the desired offset is then obtained).

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by jaylthegreat** [comment]
so what's the solution we're looking for here? 
Don't accept any inputs from the held input channels until they've ALL returned to neutral?
