### ISSUE TITLE
Sub: Auto-document DataFlash messages

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9802]
Moved from: bluerobotics/ardusub#89
Original author: @jaxxzer

### Feature request
like parameters.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by jaxxzer** [comment]
duplicate https://github.com/ArduPilot/ardupilot/issues/5864
