### ISSUE TITLE
Sub: Remove max limit of 10Hz from SR_* parameters.

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9803]
Moved from: bluerobotics/ardusub#163
Original author: @mariyachanniwala

### Feature request

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/16674
