### ISSUE TITLE
Sub: parameter metadata: allow SR_ rates up to 50Hz

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9810]
Moved from: bluerobotics/ardusub#156
Original author: @jaxxzer

### Feature request
Telemetry bandwidth should not be an issue for us, this is safe.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by WickedShell** [comment]
Duplicate of moved issue #9803.
