### ISSUE TITLE
Improve BRD_PWM_COUNT description

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9813]
Moved from: bluerobotics/ardusub#144
Original author: @jaxxzer

### Feature request
https://discuss.bluerobotics.com/t/running-relay-off-pix-hawk-aux-2-3-4/2290/2

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by Naterater** [comment]
This has been an issue on all vehicles for a long time. Agreed.

**Comment by IamPete1** [comment]
Its gone!! https://github.com/ArduPilot/ardupilot/pull/18018
