### ISSUE TITLE
Sub: gps_type does not require reboot?

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9814]
Moved from: bluerobotics/ardusub#143
Original author: @jaxxzer

### Feature request
QGC is reporting that it does, check if this is the case and verify metadata.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by WickedShell** [comment]
It doesn't always require a reboot, but it can require one (if you have a detected type and are trying to swap it (particularly to/from NMEA, or if you want to stop us from using that driver). So the tag of reboot required is the most appropriate tag in the metadata at this time.
