### ISSUE TITLE
Sub: Pixhawk Mini gives sad tone on boot

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9815]
Moved from: bluerobotics/ardusub#142
Original author: @jaxxzer

### Feature request

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by Williangalvani** [comment]
I'm closing this as it has been stable for a while and the Pixhawk Mini is discontinued
