### ISSUE TITLE
Sub: RNGFIND_TYPE default to MAV

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9821]
Moved from: bluerobotics/ardusub#105
Original author: @jaxxzer

### Feature request
This is the only type that can be practically used with ArduSub.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by jaxxzer** [comment]
> This is the only type that can be practically used with ArduSub.

We do have support for ping1d over serial now, but I think MAVLink will remain the most common use-case.
