### ISSUE TITLE
Sub: Add support for x,y,z stabilization at arbitrary attitude

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9823]
Moved from: bluerobotics/ardusub#65
Original author: @jaxxzer

### Feature request
Currently, we can only hold depth or position when we are level.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by jaxxzer** [comment]
We should reject roll/pitch commands in depth hold mode until this is supported.
