### ISSUE TITLE
Sub: Add options for 45degree steps in pitch/roll for AHRS_ORIENTATION

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9824]
Moved from: bluerobotics/ardusub#133
Original author: @jaxxzer

### Feature request

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by jaxxzer** [comment]
This is possible with the support for any arbitrary rotation: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Math/rotations.h#L77
