### ISSUE TITLE
Sub: Better defaults for EK2 and positioning

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9826]
Moved from: bluerobotics/ardusub#127
Original author: @jaxxzer

### Feature request
Default EK2_GPS_TYPE to '2D position' as a start.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by ES-Alexander** [comment]
@Williangalvani can we close this?
I'm assuming it was handled a while ago, and even if it wasn't Sub-4.1 is using EKF3 now anyway.

**Comment by Williangalvani** [comment]
closing as we do have better defaults now, and we no longer use the EKF2
