### ISSUE TITLE
Sub: Verify i gains are zeroed when entering position hold mode.

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9834]
Moved from: bluerobotics/ardusub#83
Original author: @jaxxzer

### Feature request
https://github.com/bluerobotics/ardusub/blob/7839132b1dc0a1071270d95b0d71529e3458d214/ArduSub/control_poshold.cpp#L27

Make sure this is what we want to be doing here.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by Williangalvani** [comment]
The current implementation uses init_xy_controller_stopping_point() which should handle a graceful start
