### ISSUE TITLE
Sub: Make sure pilot input gain does not affect position controller outputs

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9835]
Moved from: bluerobotics/ardusub#84
Original author: @jaxxzer

### Feature request
Verify report that position hold performance depends on input gain setting.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by siddheshih** [comment]
This is my first issue , how do I go about solving it?

**Comment by jaxxzer** [comment]
@siddheshih Thank you for your interest and contribution, I do not believe that this is a good 'first issue'. You may either inspect/step through the source code to verify that the logic is correct. Or you may use software in the loop to run a simulation with different gain settings and look at any difference in the data.

**Comment by Williangalvani** [comment]
closing this as position hold has been reworked quite a bit and is being used for a while now with no issues. 
Feel free to re-open if the issue arrises again.
