### ISSUE TITLE
Sub: Dont allow positive depth readings.

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9837]
Moved from: bluerobotics/ardusub#82
Original author: @jaxxzer

### Feature request
Suggest recalibrating the depth sensor if we are reading positive depth.

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by Naterater** [comment]
Although this make sense for a submarine only, multi-function aircraft and blimps would all benefit from positive altitude positions. Maybe I'm misinterpreting this request though.
