### ISSUE TITLE
Sub: fix metadata for FENCE_ group parameters

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/ardupilot#9839]
Moved from: bluerobotics/ardusub#76
Original author: @jaxxzer

### Feature request
The options are relevant to copter only right now
ie FENCE_ACTION = 'RTL or Land'

**Platform**
[ ] All
[ ] AntennaTracker
[ ] Copter
[ ] Plane
[ ] Rover
[x] Submarine

**Comment by peterbarker** [comment]
Everything in here has been adjusted to be per-vehicle-type now.  Closing.
