### ISSUE TITLE
FrskyD, X GPS/Altitude @ 10Hz

### ISSUE THREAD

**Issue by artemen** [ArduPilot/ardupilot#9852]
#### Issue details
FrskyD frames sent at 1Hz.  For information purposes enough, but not enough for use with antenna trackers which support FrskyD. Given the sufficient baud, please generate GPS and Altitude messages at 10Hz.

#### Version
Using since AC3.2 and AP3.9

#### Platform
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Independent of, but using Y3, X4, Y6,  5ch airplane and flying wing.

#### Hardware type
Independent of, but using pixracer, Pixhawk, omnibus F4 pro

#### Logs
Not relevant.

**Comment by peterbarker** [comment]
Is this still wanted?

Does the bandwidth exist to make this a possibility?

**Comment by IamPete1** [comment]
Closing, @artemen please re-open if this is still something your interested in
