### ISSUE TITLE
Sub: The default stream rates need to be updated

### ISSUE THREAD

**Issue by Williangalvani** [ArduPilot/ardupilot#9859]
Due to https://github.com/mavlink/qgroundcontrol/pull/7017 the default rates are no longer ignored by QGroundControl, so they need to be updated for the values that QGC used to request before this PR.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[X] Submarine

**Comment by peterbarker** [comment]
Surprisingly, this doesn't seem to have been done in master ArduPilot....

**Comment by IamPete1** [comment]
@peterbarker says its fixed on master, so I'm going to close.
