### ISSUE TITLE
Rover: Sensor Setup (Disabled while the vehicle is flying)

### ISSUE THREAD

**Issue by masz106** [ArduPilot/ardupilot#9865]
QGC 3.4.4
FW:Rover 1.8.1
Pixhawk 4

Sensor Setup (Disabled while the vehicle is flying)
No setup possible
extended_sys_state: vtol_state 0 landed_state 2

**Comment by khancyr** [comment]
Hello,

I am sorry, but we don't have rover 1.8.1. I guess you are using PX4 ! So it will be better to report on their forum for user support http://discuss.px4.io/?authComplete=true

**Comment by peterbarker** [comment]
I think this was adequately answered.
