### ISSUE TITLE
DSM RC spikes in ChibiOS

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/ardupilot#9885]
### Bug report
**Issue details**
Random spikes are occuring on all DSM RC channels in ChibiOS.  The timing, duration, and channels all seem to be random.  I found this while trying to figure out why the Solo's gimbal was still twitching even after tridge fixed the serial communication.  Turns out the remaining twitches are in response to these little spikes when they happen to occur on RC6.

Given these these spikes happen on all channels, this could conceivably affect vehicle control, mode changes, failsafes, etc.  They only seem to last a fraction of a second though.

This does not occur in Nuttx master.  Only in ChibiOS.  Which leads me to believe there is still something funky going on in the new decoder.

_These are some screenshots of RC raw input live in QGC._

![spike 3](https://user-images.githubusercontent.com/8234496/48929766-9d497e80-eeb9-11e8-998b-eb7d98e21a0f.JPG)

![spike 1](https://user-images.githubusercontent.com/8234496/48929769-9fabd880-eeb9-11e8-906d-4f00577b5a93.JPG)

![spike 2](https://user-images.githubusercontent.com/8234496/48929771-a1759c00-eeb9-11e8-9571-7f4a8fb0bc21.JPG)

**Version**
Copter 3.7-dev ChibiOS

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
N/A

**Hardware type**
Cube Black

**Comment by Pedals2Paddles** [comment]
@rmackay9 @tridge  I've been watching it on 3.6 this morning and it **does not** experience the DSM spikes.  What is different about DSM in 3.6 vs master?

**Comment by Pedals2Paddles** [comment]
I just did a build based on the current 3.6 branch (RC4) and it also does not have this DSM spiking issue.  So I don't think there is an issue in RC to hold anything up.  Whatever is causing it is only in master.

In fact, I cherry picked in Tridge's commits that fix the gimbal's serial comm issue, and the gimbal is now rock solid stable since the DSM issue isn't there too.

**Comment by rmackay9** [comment]
@Pedals2Paddles, thank you very much for testing that!  Copter-3.6.2 going out shortly!

**Comment by tridge** [comment]
fixed in #9909
