### ISSUE TITLE
New class of frame Octacopter hybrid Hexacopter

### ISSUE THREAD

**Issue by a2sandres** [ArduPilot/ardupilot#9887]
This frame is similar to the Hexacopter X, only that it has two additional motors continuous to motors 1 and 2 of the arducopter Hexa X and its rotation is contrary to the corresponding motors, this frame is ideal for drones that lift heavy loads.

I think that this frame can be added to the octocopter group, however I do not know what would be the ideal configuration for their behaviors and what values ​​they should give it, for example, the factors in degrees.

We have some copters with this frame configuration, but ardupilot and Mission Planner do not have this configuration, I would like it to be added and I also offer help to do it, however I also look for collaboration for this goal, some flights controller have this configuration and I would be very happy that Ardupilot had it too.

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

Attached sample image

![frame octo hexa](https://user-images.githubusercontent.com/36654266/48959545-200f1f80-ef34-11e8-81c1-a604b322a90c.PNG)

**Comment by IamPete1** [comment]
We now support custom frames via scripting, https://github.com/ArduPilot/ardupilot/pull/15708

**Comment by rmackay9** [comment]
I guess though that really we should add a script to support this before closing the issue?

**Comment by IamPete1** [comment]
Its quite a vehicle dependent mix, not just a variation on motors in a circle like the majority of the mixes, to get it working well it ought to be tailored to each vehicle. I'm happy to take a stab a doing a mixer if @a2sandres is still interested.
