### ISSUE TITLE
Battery Monitors (aka Power Modules) 

### ISSUE THREAD

**Issue by skyyuzhang** [ArduPilot/ardupilot#9897]
Battery Monitors (aka Power Modules) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.
I have built a battery monitors connecting with UAVCAN . because I saw a piece of code which is AP_BattMonitor.cpp on AP_BattMonitor. also I set BATT_MONITOR to 8 which is UAVCA-battinfo. but the volt and current is always zero . I think my UAVCAN BattMonitor is working right cause I can get right data form uavcan gui tool. also the data type is uavcan.equipment.power.BatteryInfo. so is this a bug on uavcan battery or this piece of code is not complete? would you give me some help? thank you !!!!!!

**Version**
 3.6.1
**Platform**
 Copter
**Hardware type**
PIXHAWK
**Logs**

**Comment by lvale** [comment]
Please, direct your questions on the appropriate gitter channel.
Closing
