### ISSUE TITLE
RangeFinder: lightware lw20 I2C driver reports 655.35m when it gets a bad reading

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9920]
This is very similar to the issue we've fixed recently for the benewake TFmini and TF02 lidar.  We should be checking the range back from the lidar and if it's over some reasonable limit report a known maximum (120m?) for the lidar (like the maximum of 120m and the RNGFND_MAX_CM + 100cm).

Note: this issue doesn't impact how the vehicle flies, it's just a reporting issue.  It's annoying/scary for users to see 655m I think.

Note2: the same issue probably exists for the Lightware Serial driver.

**Comment by muramura** [comment]
I think that it is better to return the value of 0xFFFF as an abnormal value with a read error and not update its value.
When a continuous error occurs, have the device judge that it is a device abnormality at the higher level.
In the case of transient, I think that it will be updated to the normal value next time.
    // read the high and low byte distance registers
     bool ret = _dev-> read ((uint8_t *) & val, sizeof (val));
     if (ret) {
         // combine results into distance
         reading_cm = be16toh (val);
     }

     return ret;
}

**Comment by OXINARF** [comment]
We can do this, but we already log the status, so log tools/users have the information needed to know if it is valid or not. I would say that doing this is actually an incentive to not check the status and think the information logged has any meaning.

I've changed the label to Enhancement since there isn't really a bug.

**Comment by rmackay9** [comment]
This was resolved in Copter-3.6.10 so closing. https://github.com/ArduPilot/ardupilot/commit/3be85b2afa8cd1cb17e4655b2ec4d34d452d5a0d
