### ISSUE TITLE
SET_ATTITUDE_TARGET support in other modes

### ISSUE THREAD

**Issue by ghost** [ArduPilot/ardupilot#9942]
#### Issue details
Hello,
I was wondering if any other modes other than GUIDED_NOGPS support the SET_ATTITUDE_TARGET command. I used a dronekit script and had the drone take off in GUIDED_NOGPS mode. While it did take off and set the attitude, it didn't take off how it does in GUIDED mode. In GUIDED mode it takes off going completely vertically without going in any other direction while in GUIDED_NOGPS it takes off and moves in a direction most likely due to the lack of GPS. So I was wondering if SET_ATTITUDE_TARGET could be used in modes like GUIDED or POS_HOLD where the drone would maintain its position and then receive the command and move in a direction.

#### Version
Copter 3.5.7

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quadcopter

#### Hardware type
Intel Aero RTF

**Comment by khancyr** [comment]
Hello,

Starting from copter 3.5.X, we support SET_ATTITUDE_TARGET in Guided, guided_nogps, guided inside auto mode.
https://github.com/ArduPilot/ardupilot/blob/Copter-3.5/ArduCopter/GCS_Mavlink.cpp#L1603

https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L1062
