### ISSUE TITLE
Plane 3.9.3: uavcan airspeed doesn't work

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#9946]
### Bug report
**uavcan doesn't work on plane 3.9.3, but works on master branch.**
flashed plane 3.9.3 version, enabled uavcan and set airspeed type to 8, reboot.  no airspeed on hud.
![75d03f37a403fe84c2578625f43f3db](https://user-images.githubusercontent.com/16251761/49427136-8706c100-f7dd-11e8-8de8-2d7e59abd635.png)

just flashed master branch version, didn't change any param, connected to mission planner, airspeed works.
![3d1d5dc6aeb413b77fb672cfccafeb7](https://user-images.githubusercontent.com/16251761/49427409-36dc2e80-f7de-11e8-95f4-0217e7537bfe.png)

**Version**
plane 3.9.3, Chibios version

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[*] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
The cube.

**Comment by EShamaev** [comment]
AP_Airspeed_UAVCAN is not in 3.9.3

![image](https://user-images.githubusercontent.com/7996972/49428092-cfa68600-f7ad-11e8-8797-cd090b9cf8b7.png)

**Comment by liang-tang** [comment]
OMG，I am sorry. I did not notice.
