### ISSUE TITLE
AP_Mount: norm_input breaks gimbal tilt control

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/ardupilot#9973]
### Bug report
**Issue details**
This commit (https://github.com/ArduPilot/ardupilot/commit/9767c743112dfd13894b83ac7cfde7762e721016) is making the Solo's gimbal constantly move back up to level, cutting the angle in half at intervals.  So if I tilt it straight down, it pops up to 45. Then a few seconds later pops up to 67.  Then a few second slater up to half of that and so on.

I removed the commit and it no longer does this.

The commit does this:
`return (rc->norm_input() + 1.0f) * 0.5f * (angle_max - angle_min) + angle_min;`

The `*0,5f` is presumably what is doing it.

**Version**
3.7-dev

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
n/a

**Hardware type**
Cube Black

**Comment by rmackay9** [comment]
ok, it should have been a mostly non-functional change but clearly it's not.  The only change this should cause is the RCx_TRIM value should be used in calculating the gimbal's target angle.  If you have a log that would be good.

**Comment by Pedals2Paddles** [comment]
Solo for reasons unknown had `RC6_TRIM` set for 1000.  I changed i to be half the full PWM range, and that appears to fix the problem on the Solo.  I will update the frame_params files too.

**Comment by rmackay9** [comment]
Txs for testing this.  I think it's probably not useful to add this reliance on the trim value.  I think we will either create a new version of the norm_input function or revert the change.

**Comment by Pedals2Paddles** [comment]
Closing since it's not a bug and now operating properly with the trim parameter set.

**Comment by rmackay9** [comment]
I'd actually like to keep this one open because I think other users will hit the same issue.

**Comment by rmackay9** [comment]
This has been fixed with this PR: https://github.com/ArduPilot/ardupilot/pull/13646 which will go out with Copter-4.0.4.  thanks!
