### ISSUE TITLE
Pixhawk RAW ADC Feedback by Default in Mavlink

### ISSUE THREAD

**Issue by camow7** [ArduPilot/ardupilot#9977]
### Feature request

**Is your feature request related to a problem? Please describe.**
I have been trying to use the Pixhawk with external sensors but there is no easy way to get live feedback of that sensor information on Mission Planner or in custom Ground Station software. I want to use the stock standard releases of Ardupilot and not require my own custom versions.

**Describe the solution you'd like**
I would like to see the standard builds of Ardupilot automatically read and send the RAW ADC readings (value between 0 and 4096) back over a Mavlink data stream so I can process that information on the ground station end. This would allow quick external sensor integration. This data could be sent over one of the extra streams available for device specific comms.

**Describe alternatives you've considered**
I thought initially I could get around this by setting the two external sensors up as range finders 1 and and 2 and then configuring them such that I could convert the distance readings being sent back to meaningful data (i.e. 5m = 34 degress from my temperature sensor). Problem was I didn't want this to affect height control of my copter and I could not find two separate messages for each sonar sensor in Mavlink. At best I could get one reading back.

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
This is to support external sensors that are not being used by the autopilot. It's to assist using the MAV as a data collection device. A use case would be flying the MAV into a potentially hazardous area with gas detection or air quality sensors attached. I want to see the air quality live on my Ground Station. I then want to be able to plug other sensors with 0 - 3.3v outputs in quickly and have their data feeding back. I would be converting the output from the sensors to meaningful values (e.g. 0 - 3.3V OR 0 - 4096 = 0-100 degrees) on the Ground Station end. 

This feature is related to forum post: https://discuss.ardupilot.org/t/pixhawk-adc-and-mavlink/35883/4

**Comment by Naterater** [comment]
I think the conversation belongs here: https://github.com/ArduPilot/ardupilot/issues/877
