### ISSUE TITLE
IOMCU not resetting when flashing FW from Copter 3.2 to 3.7

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/ardupilot#9978]
### Bug report

**Issue details**

When loading current 3.7-dev ChibiOS over the very old Copter 3.2 Nuttx, the FC never completes and reboots.  It hangs up infinitely, requiring the user to power cycle the FC.  Once power cycled, it boots normally and works fine.  @tridge believe it is the IOMCU not resetting.  FYI Going from 3.5 or 3.6 Nuttx to 3.7-dev ChibiOS works fine and does not hang up.

This currently presents a hurdle for scripts that flash firmware (like a solo).  If it just hangs up, there is no feedback to the scripts other than a timeout.  And there is no feedback to user at all.

Currently, for users upgrading their Solo from 3DR's 3.2 branch, we're instructing them to wait a minute or two and then manually power cycle the vehicle.

A possible solution is to have the FC play some kind of sad tone if it cannot complete the installation.  That way the user will know to manually power cycle.

The old 3.2ish branch from 3DR can be found here, including a compiled binary: https://github.com/OpenSolo/ardupilot-solo/releases/tag/solo-1.5.4

**Version**
3.7-dev

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
N/A

**Hardware type**
Cube Black

**Comment by peterbarker** [comment]
The upgrade path for Solo is now well documented (and automated) so I think we can close this now.
