### ISSUE TITLE
.BIN log dates to 1980

### ISSUE THREAD

**Issue by Naterater** [ArduPilot/ardupilot#9984]
### Bug report
.BIN files are being saved with a 1980 date, and it appears to be random. When using the log analysis tools and geotagging, the 1980 date sticks. The GPS link on these flights was solid.

**Version**
Plane 3.9.3 ChibiOS
Plane 3.10 - Latest (late November)

**Platform**
[?] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Believer

**Hardware type**
Cube Black Standard Carrier Board. Here GPS and Here+ GPS (separate builds).

**Logs**
https://www.dropbox.com/s/x3lk1ezq49lagsr/00000018.BIN?dl=0

**Comment by rmackay9** [comment]
MP issue I think so I'll close if that's OK.

**Comment by Naterater** [comment]
No, this is the actual binary logs... 
![image](https://user-images.githubusercontent.com/35429159/49777015-44088a00-fcc4-11e8-94d5-e3cc9f947492.png)

![image](https://user-images.githubusercontent.com/35429159/49777043-600c2b80-fcc4-11e8-8a6d-1c0ac7bdf19c.png)

**Comment by rmackay9** [comment]
@Naterater, but these are logs downloaded using MP right?   Have a peek on the SD card directly and you'll likely see that they don't have a date on them, they are all just numbered.  It's MP that changes the name of the file as part of the download.  I won't close this issue again 'cuz we don't need to get into a tug-of-war.. but I'm pretty sure it's an MP issue.

**Comment by Naterater** [comment]
These are straight from the SD card - NO MP intervention at all.

**Comment by Naterater** [comment]
Haven't seen this issue lately in the 4.0 releases.
